### ISSUE TITLE
“ZED - ZFS Event Daemon” segfaults sporadically under Debian buster

### ISSUE THREAD

**Issue by Beneter** [openzfs/zfs#10049]
### System information
Distribution Name	|  Debian
Distribution Version	|  buster
Linux Kernel	|  4.19.0-8
Architecture	|  amd64
ZFS Version	|  0.7.12-2+deb10u1
SPL Version	| 0.7.12-2
ZED Version	| 0.7.12-2+deb10u1
Installation method: Installed on stretch (from contrib) and upgraded to buster.
AppArmor and Firejail running
Multiple hours of memtest & mprime each do not indicate errors

### Describe the problem you're observing
Sporadically my ZED is segfaulting and spamming my logs:
```
Feb 16 00:33:54 XXXHostnameXXX kernel: show_signal_msg: 7415375 callbacks suppressed
Feb 16 00:33:54 XXXHostnameXXX kernel: zed[3263]: segfault at ffffffffffffff80 ip 0000560773b40cdc sp 00007f9c0111dcd0 error 5 in zed[560773b3a000+c000]
Feb 16 00:33:54 XXXHostnameXXX kernel: Code: c0 75 23 e9 d6 03 00 00 66 0f 1f 44 00 00 48 8b 3d a1 c8 00 00 48 89 c6 e8 31 97 ff ff 48 85 c0 0f 84 b8 03 00 00 49 8b 5f 18 <48> 39 58 18 75 de 48 83 78 20 00 74 d7 48 8b b0 90 00 00 00 48 89
```
I already tried to purge zfs-zed and reinstall it but the segfaults keep happening.
Until now I do not have any data loss. The pools are ONLINE.

### Describe how to reproduce the problem
Unknown. On some days ZED seems to be working fine. On other days I receive hundreds of sefault-logs.

I am happy to provide additional logs if available.

**Comment by andrey42** [comment]
I've had similar segfaults on version 0.7. Got rid of them by upgrading to 0.8.2 from buster-backports official repo. Nowadays there's 0.8.3 release available in buster-backports. Give it a try.
