### ISSUE TITLE
ZFS media compatibility across versions

### ISSUE THREAD

**Issue by montanaviking** [openzfs/zfs#10056]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| RedHat Linux 7.7
Distribution Version	| 
Linux Kernel	| 
Architecture	| 64-bit
ZFS Version	| 0.8.3
SPL Version	| 

### Describe how to reproduce the problem
Question:
Can one safely move ZFS media created with ZFS version 0.8.2 to ZFS 0.8.3 and back again?
I would think that such a minor revision wouldn't introduce file incompatibilities?
I have a system using Ubuntu 18.04 64-bit and wanted to install RedHat 7.7 on another drive on this system to dual-boot Ubuntu and RedHat 7.7. However, the ZFS on Linux for Ubuntu is 0.8.2 and that for RedHat 7.7 is 0.8.3. Is this safe?
Thanks,
Phil

**Comment by ghfields** [comment]
Pool interchangeability is based on the feature flags enabled on the pool.  This goes for different operating systems, as well as different ZFS versions within the same OS.  You can go back and forth as long as the pool only unitizes commonly supported feature flags.  Don't enable don't enable too many flags (this also means don't run `zpool upgrade` blindly).

The #zfsonlinux IRC channel or the [ZFS Discussion mailing list](https://zfsonlinux.topicbox.com/groups/zfs-discuss) should be able to further assist you.

**Comment by montanaviking** [comment]
Thanks! The CentOS7 system I'm checking with ZFS used ZFS 0.8.3 but did not request a pool upgrade when this pool was moved from my ZFS 0.8.2 system so can I assume that no pool upgrade means no problem?
Thanks!

**Comment by rlaager** [comment]
As long as you don’t enable a new feature, you should be okay. There is always the theoretical potential for bugs. I’m not aware of problems with this combination of versions.

**Comment by montanaviking** [comment]
Thanks!
