### ISSUE TITLE
recent linux y2038 changes prevent zfs from building (time_t, timespec, getrawmonotonic gone)

### ISSUE THREAD

**Issue by knot-indicated** [openzfs/zfs#10052]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Arch linux
Distribution Version	| rolling release
Linux Kernel	| 63623fd44972d1ed2bfb6e0fb631dfcf547fd1e7
Architecture	| x86_64
ZFS Version	| 327000ce04b4243f140a38647dca59683d39b8e7
SPL Version	| 327000ce04b4243f140a38647dca59683d39b8e7

### Describe the problem you're observing
Latest zfs fails to build on latest kernel; i think due to kernel commit [412c53a680a97cb1ae2c0ab60230e193bee86387](https://github.com/torvalds/linux/commit/412c53a680a97cb1ae2c0ab60230e193bee86387) and maybe [c766d1472c70d25ad475cf56042af1652e792b23](https://github.com/torvalds/linux/commit/c766d1472c70d25ad475cf56042af1652e792b23).
### Describe how to reproduce the problem
Build ZFS against a kernel with those y2038 commits and get the following error messages:

### Include any warning/errors/backtraces from the system logs

```
make[3]: Entering directory '/home/thz/linux'
  CC [M]  /home/thz/zfs/module/icp/illumos-crypto.o
In file included from /home/thz/zfs/include/os/linux/spl/sys/condvar.h:33,
                 from /home/thz/zfs/include/sys/zfs_context.h:37,
                 from /home/thz/zfs/include/sys/crypto/common.h:39,
                 from /home/thz/zfs/module/icp/illumos-crypto.c:35:
/home/thz/zfs/include/os/linux/spl/sys/time.h:88:15: error: unknown type name ‘time_t’
   88 | static inline time_t
      |               ^~~~~~
/home/thz/zfs/include/os/linux/spl/sys/time.h: In function ‘gethrtime’:
/home/thz/zfs/include/os/linux/spl/sys/time.h:108:18: error: storage size of ‘ts’ isn’t known
  108 |  struct timespec ts;
      |                  ^~
/home/thz/zfs/include/os/linux/spl/sys/time.h:109:2: error: implicit declaration of function ‘getrawmonotonic’ [-Werror=implicit-function-declaration]
  109 |  getrawmonotonic(&ts);
      |  ^~~~~~~~~~~~~~~
/home/thz/zfs/include/os/linux/spl/sys/time.h:108:18: warning: unused variable ‘ts’ [-Wunused-variable]
  108 |  struct timespec ts;
      |                  ^~
cc1: some warnings being treated as errors



```

**Comment by satmandu** [comment]
As mentioned here: https://github.com/openzfs/zfs/pull/9961#issuecomment-591076133

https://github.com/torvalds/linux/commit/412c53a680a97cb1ae2c0ab60230e193bee86387 in 5.6rc3 changes https://github.com/torvalds/linux/blob/v5.6-rc3/include/linux/types.h such that ```time_t``` is no longer available as per https://lore.kernel.org/patchwork/patch/1177824/:

```#ifndef _TIME_T
#define _TIME_T
typedef __kernel_old_time_t	time_t;
#endif
```
That ```time_t``` is needed here: https://github.com/openzfs/zfs/blob/521abcc49a73ac5187f58807b8599de04d9d9765/include/os/linux/spl/sys/time.h#L88
