### ISSUE TITLE
Consider Blake3 as checksum function

### ISSUE THREAD

**Issue by lin7sh** [openzfs/zfs#10058]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Any
Distribution Version	| Any
Linux Kernel	| Any
Architecture	| Any
ZFS Version	| 2.0
SPL Version	| Any

### Describe the problem you're observing
The collision resistance checksum sha256 functions we currently use could be less performant and may not performance well on the platforms  that don't have hardware sha256 acceleration.

The new [blake3](https://github.com/BLAKE3-team/BLAKE3) is a evolution of the blake checksum family, and it's perform really well, it's already on the [roadmap](https://download.libsodium.org/doc/roadmap) of libsodium 1.X we might consider adding it to zfs.

Another interesting thing about blake3 is that it uses 1KB block merkle tree hashing, since zfs also use merkle tree, there is a potential benefit to combine the two.

### Describe how to reproduce the problem
none

**Comment by mcmilk** [comment]
@behlendorf - I would like to implement support for this new hash (strong).
When it is ready - is there a chance of inclusion ? The [smhasher](https://github.com/rurban/smhasher) tests look really fine to me: [blake3-c](https://github.com/rurban/smhasher/blob/master/doc/blake3_c.txt) vs [sha2-256](https://github.com/rurban/smhasher/blob/master/doc/sha2-256.txt)

**Comment by behlendorf** [comment]
@mcmilk I think investigating blake3 further would be interesting.  The benchmarks I've seen are encouraging but there are a few questions we'd want to get answers to.  Off the top of my head, how well does it really perform with ZFS's relatively small block size?  Can it be ported to the kernel easily?  Is this is straight C implementation or would a SIMD optimized version be needed?  I saw one comment that there was no 32-bit implementation which would be a problem.  If there are good answers to these kind of questions and there's a clear performance benefit then I think it's something we'd consider including.

**Comment by mcmilk** [comment]
Thanks for the fast response, I will dig into it and present some results then.

**Comment by mcmilk** [comment]
> @mcmilk I think investigating blake3 further would be interesting. The benchmarks I've seen are encouraging but there are a few questions we'd want to get answers to. Off the top of my head, how well does it really perform with ZFS's relatively small block size? Can it be ported to the kernel easily? Is this is straight C implementation or would a SIMD optimized version be needed? I saw one comment that there was no 32-bit implementation which would be a problem. If there are good answers to these kind of questions and there's a clear performance benefit then I think it's something we'd consider including.

I used currently the reference C implementation, which will run on 32bit and 64bit machines. Also 5 optimized versions are included: 1x neon (arm64 intrinsic, needs testing) + 4x assembly for x86-64.

Blocksizes: for small blocks of 128 byte to 1kib it performs like sha256 ... but then it will be get a lot faster.
The benefits are very different across cpu's - I would like to add some micro-benchmark like flechter4 has it already.

Maybe we could make it also configurable via `/proc/spl/kstat/zfs/checksum` like this:
```
echo sha256-openssl > /proc/spl/kstat/zfs/checksum
echo sha256-avx512 > /proc/spl/kstat/zfs/checksum
echo blake3-generic > /proc/spl/kstat/zfs/checksum
echo blake3-avx2 > /proc/spl/kstat/zfs/checksum
```

The admin should therefore take a look first into this file: `/proc/spl/kstat/zfs/checksum_bench`
```
algo / bytes  64 128 256 512 1024 2k 4k 8k 16k 32k ... 128k
sha256-generic  xx xx xx xx xx xx xx xx 
sha256-sha_ni  xx xx xx xx xx xx xx xx 
sha256-openssl  xx xx xx xx xx xx xx xx 
blake3-generic  xx xx xx xx xx xx xx xx 
blake3-sse2  xx xx xx xx xx xx xx xx 
blake3-sse41  xx xx xx xx xx xx xx xx 
blake3-avx  xx xx xx xx xx xx xx xx 
blake3-avx512  xx xx xx xx xx xx xx xx 
and so on...

```
