### ISSUE TITLE
Add ZFS to the Clear Linux kernel

### ISSUE THREAD

**Issue by zaffle** [openzfs/zfs#10068]
Distribution Name	| Clear Linux
Distribution Version	| 32050
Linux Kernel	| 4.19.106-116.lts2018
Architecture	| 
ZFS Version	| 0.8.3
SPL Version	| 

Question, does anyone know where I can find step by step instructions on how to add zfs to the Clear Linux kernel as it is not appearing on the ZFS on Linux website? I know Intel won't support it due to some licensing purgatory. I am new to adding any modules to the kernel and I am trying to follow the instructions found here: [](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-modules-dkms.html#overview), but so far I cannot replicate the success of others on this issue post "Bundle for ZFS drivers #631" on the forum [](https://github.com/clearlinux/distribution/issues/631). Thank you in advance

**Comment by rincebrain** [comment]
Follow [this](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-modules.html) for how to disable requiring signed modules, then:

`for bundle in devpkg-openssl devpkg-util-linux kernel-lts-dkms;do swupd bundle-add ${bundle};done;`

Then you should be able to ./autogen.sh && ./configure && make && make install && depmod -a, then modprobe zfs.

Setting it up in DKMS would require a bit more work - you could probably plunder the contents of the rpm or deb DKMS package and land it in /usr/src then dkms add it manually, so it keeps up to date.

If you wanted it packaged in swupd, you could [submit a request](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-modules-dkms.html#submit-a-request-to-add-the-module) for them to add it, unless you have reason to think that won't work.

**Comment by zaffle** [comment]
A million thanks! I will try these steps...

**Comment by rincebrain** [comment]
One more caveat - I believe those steps will land the ZFS tools in /usr/local, which doesn't appear to be in the default PATH for root.

So you might want to either change that or change PATH to include /usr/local/sbin and /usr/local/bin. Either way.

**Comment by zaffle** [comment]
Thanks again, that is very good to know.
