### ISSUE TITLE
zpool_trim_start_and_cancel_pos tests initialization instead of trimming

### ISSUE THREAD

**Issue by jgallag88** [openzfs/zfs#10065]
### System information

Type | Version/Name
 --- | --- 
Distribution Name  | n/a
Distribution Version	| n/a
Linux Kernel	| n/a
Architecture	| n/a
ZFS Version	| abef699866508f96157290e2a85482968e094a58
SPL Version	| abef699866508f96157290e2a85482968e094a58

### Describe the problem you're observing
`zpool_trim_start_and_cancel_pos` is a copy of `zpool_initialize_start_and_cancel_pos`. The intention was likely to take the initialization test and modify it so that it performed an equivalent test of the trim logic. However, the test wasn't modified after being copied.
### Describe how to reproduce the problem
n/a
### Include any warning/errors/backtraces from the system logs
n/a

**Comment by behlendorf** [comment]
Indeed that was the intent.

**Comment by rincebrain** [comment]
I think #11649 resolved this.

**Comment by jgallag88** [comment]
This is indeed fixed by https://github.com/openzfs/zfs/pull/11649
