### ISSUE TITLE
[Feature] live dataset migration between pools

### ISSUE THREAD

**Issue by Boris-Barboris** [openzfs/zfs#10077]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing

I would like to be able to "live-migrate" mounted/open filesystems and, if possible, zvols (though /dev/zvol/<pool_name> convention may render this impossible) between pools while maintaining all IO ordering and consistency guarantees, given to the kernel itself and userspace, keeping file descriptors open, and with as little as possible IO freeze. In other language, after the long asynchronous mirroring process (with or without snapshot help) the converged destination dataset should atomically replace it's source at the mount point.

The main use case for me is zero-downtime complete pool defragmentation in small pool + large temporary pool. I would like to live-migrate root in-use filesystems from small pool to large pool, destroy them on the small pool, and live-migrate them back, with complete defragmentation of metaslabs being the desired consequence. Considering the observable complexity of BP rewrite this may be the only tractable way of online defrag that does not involve pool extension.

Alternative use-cases mainly revolve around infrastructure maintance and upgrade operations: storage/LUN migrations for critical workloads.

Implementation may wish to adopt a rich set of heuristics developed in virtualization domain for live-migration of virtual machines, namely convergence tunables and throttling of operations on the source dataset.

**Comment by freqlabs** [comment]
There is a feature in FreeBSD where `zfs rename` has an option to not unmount the current mountpoint. In trying to port this to Linux I found that the kernel does not export the necessary methods to update the underlying device of a mountpoint. Therefore it is not possible to achieve this in a module, ZFS must be built-in to the kernel.

**Comment by devZer0** [comment]
"In trying to port this to Linux I found that the kernel does not export the necessary methods to update the underlying device of a mountpoint."

did you discuss that on lkml? why not add that feature , if possible?

**Comment by freqlabs** [comment]
No I didn't try asking for the Linux kernel to expose a KPI for ZFS. I'm not particularly motivated to, either.

**Comment by devZer0** [comment]
interesting, here is some presentation which describes a live zfs data migration with almost zero downtime (from a client perspective, as you can do failover and afford some tiny interruption) in an nfs scenario:

https://de.slideshare.net/ovhcom/live-migration-of-openzfs-datasets-with-zmotion

if i see this correctly, the mentioned patch is obsolete in the meantime
https://github.com/openzfs/zfs/pull/941

**Comment by freqlabs** [comment]
> There is a feature in FreeBSD where `zfs rename` has an option to not unmount the current mountpoint. In trying to port this to Linux I found that the kernel does not export the necessary methods to update the underlying device of a mountpoint. Therefore it is not possible to achieve this in a module, ZFS must be built-in to the kernel.

We did end up finding a way to do this on Linux too, and the feature was committed in 76a157f00408cbd686b1f270babedfbbf7a3fd3c

**Comment by behlendorf** [comment]
Closing.  See comment above, and commit https://github.com/openzfs/zfs/commit/76a157f00408cbd686b1f270babedfbbf7a3fd3c
