### ISSUE TITLE
How to enable ZSTD compression during pool creation

### ISSUE THREAD

**Issue by shadowrylander** [openzfs/zfs#10089]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I'm using a custom kernel for the [`Surface Book 2`](https://github.com/dmhacker/arch-linux-surface) on `Manjaro Juhraya`, and using the officially maintained `zfs-dkms` package, I am unable to enable `zstd` compression during pool creation; does version `0.8.3` not support `zstd` yet, or does it simply not support it during pool creation, and I have to set it manually per dataset? <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by freqlabs** [comment]
ZSTD is not supported yet.

**Comment by shadowrylander** [comment]
I suppose it's in no pre-release version yet either, correct?

**Comment by freqlabs** [comment]
You can look for the most recent pull request and try using the author's branch, other than that no there is nothing in this repo.

**Comment by shadowrylander** [comment]
Fair enough! Thanks for the help!
