### ISSUE TITLE
Freeze at SCRUB

### ISSUE THREAD

**Issue by tausday** [openzfs/zfs#10091]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.04.1
Linux Kernel	|   4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0
Architecture	|   x86_64 x86_64 x86_64 GNU/Linux
ZFS Version	|  0.8.3-1
SPL Version	|  0.8.3-1

### Describe the problem you're observing
Hello,

if i scrub my  tank after a few seconds the system will be freeze
I have test from 0.7.X Stock of Ubunut until 0.8.0 and 0.8.3 all the same.
### Describe how to reproduce the problem

sudo zpool srub tank
### Include any warning/errors/backtraces from the system logs

If u need any logs pls tell me i dont know what i can do
At the moment i have cancel and the system works

  pool: tank
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub canceled on Sun Mar  1 22:23:04 2020
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            sda     ONLINE       0     0     0
            sdb     ONLINE       0     0     0

errors: No known data errors

This are two Western Digital 3TB Red at home not very often used

**Comment by rincebrain** [comment]
You'll probably have better luck with asking this question in a more interactive forum like IRC or the mailing list, as there's a lot of different information people would probably like to ask you for.

You're saying the system freezes a few seconds after issuing zpool scrub tank - do you mean that it stays frozen forever until you reboot, or just that it becomes intermittently unresponsive?

You said this happens with 0.7.X, 0.8.0, and 0.8.3 - that's pretty surprising.

Is this your root filesystem? Do you have any kind of swap set up? Are you running any kinds of virtualization or containers?

What do zpool get all tank and zfs get all tank say?

Does your system log anything interesting in /var/log/messages for you to find after it freezes?

**Comment by tausday** [comment]
Thx 4 fast response.
Root disk is a ssd and two 3tb as zfs raid 1.
System is freezed completly and need a hard reset.
I have install a new/fresh 18.04  ubuntu lts and only add zfs.
I have no file like log/messages some special files?

NAME  PROPERTY                       VALUE                          SOURCE
tank  size                           2,72T                          -
tank  capacity                       16%                            -
tank  altroot                        -                              default
tank  health                         ONLINE                         -
tank  guid                           11603561150611366278           -
tank  version                        -                              default
tank  bootfs                         -                              default
tank  delegation                     on                             default
tank  autoreplace                    off                            default
tank  cachefile                      -                              default
tank  failmode                       wait                           default
tank  listsnapshots                  off                            default
tank  autoexpand                     off                            default
tank  dedupditto                     0                              default
tank  dedupratio                     1.00x                          -
tank  free                           2,27T                          -
tank  allocated                      456G                           -
tank  readonly                       off                            -
tank  ashift                         0                              default
tank  comment                        -                              default
tank  expandsize                     -                              -
tank  freeing                        0                              -
tank  fragmentation                  0%                             -
tank  leaked                         0                              -
tank  multihost                      off                            default
tank  checkpoint                     -                              -
tank  load_guid                      6716076891721758793            -
tank  autotrim                       off                            default
tank  feature@async_destroy          enabled                        local
tank  feature@empty_bpobj            enabled                        local
tank  feature@lz4_compress           active                         local
tank  feature@multi_vdev_crash_dump  enabled                        local
tank  feature@spacemap_histogram     active                         local
tank  feature@enabled_txg            active                         local
tank  feature@hole_birth             active                         local
tank  feature@extensible_dataset     active                         local
tank  feature@embedded_data          active                         local
tank  feature@bookmarks              enabled                        local
tank  feature@filesystem_limits      enabled                        local
tank  feature@large_blocks           enabled                        local
tank  feature@large_dnode            enabled                        local
tank  feature@sha512                 enabled                        local
tank  feature@skein                  enabled                        local
tank  feature@edonr                  enabled                        local
tank  feature@userobj_accounting     active                         local
tank  feature@encryption             disabled                       local
tank  feature@project_quota          disabled                       local
tank  feature@device_removal         disabled                       local
tank  feature@obsolete_counts        disabled                       local
tank  feature@zpool_checkpoint       disabled                       local
tank  feature@spacemap_v2            disabled                       local
tank  feature@allocation_classes     disabled                       local
tank  feature@resilver_defer         disabled                       local
tank  feature@bookmark_v2            disabled                       local


NAME  PROPERTY              VALUE                 SOURCE
tank  type                  filesystem            -
tank  creation              Do Jan 30  3:28 2020  -
tank  used                  456G                  -
tank  available             2,19T                 -
tank  referenced            456G                  -
tank  compressratio         1.00x                 -
tank  mounted               yes                   -
tank  quota                 none                  default
tank  reservation           none                  default
tank  recordsize            128K                  default
tank  mountpoint            /tank                 default
tank  sharenfs              off                   default
tank  checksum              on                    default
tank  compression           off                   default
tank  atime                 on                    default
tank  devices               on                    default
tank  exec                  on                    default
tank  setuid                on                    default
tank  readonly              off                   default
tank  zoned                 off                   default
tank  snapdir               hidden                default
tank  aclinherit            restricted            default
tank  createtxg             1                     -
tank  canmount              on                    default
tank  xattr                 on                    default
tank  copies                1                     default
tank  version               5                     -
tank  utf8only              off                   -
tank  normalization         none                  -
tank  casesensitivity       sensitive             -
tank  vscan                 off                   default
tank  nbmand                off                   default
tank  sharesmb              off                   default
tank  refquota              none                  default
tank  refreservation        none                  default
tank  guid                  6317007208143413397   -
tank  primarycache          all                   default
tank  secondarycache        all                   default
tank  usedbysnapshots       0B                    -
tank  usedbydataset         456G                  -
tank  usedbychildren        10,7M                 -
tank  usedbyrefreservation  0B                    -
tank  logbias               latency               default
tank  objsetid              54                    -
tank  dedup                 off                   default
tank  mlslabel              none                  default
tank  sync                  standard              default
tank  dnodesize             legacy                default
tank  refcompressratio      1.00x                 -
tank  written               456G                  -
tank  logicalused           456G                  -
tank  logicalreferenced     456G                  -
tank  volmode               default               default
tank  filesystem_limit      none                  default
tank  snapshot_limit        none                  default
tank  filesystem_count      none                  default
tank  snapshot_count        none                  default
tank  snapdev               hidden                default
tank  acltype               off                   default
tank  context               none                  default
tank  fscontext             none                  default
tank  defcontext            none                  default
tank  rootcontext           none                  default
tank  relatime              off                   default
tank  redundant_metadata    all                   default
tank  overlay               off                   default
tank  encryption            off                   default
tank  keylocation           none                  default
tank  keyformat             none                  default
tank  pbkdf2iters           0                     default
tank  special_small_blocks  0                     default

**Comment by tausday** [comment]
hello,

i have found out that the pciexpress sata controller bring problems. If i connect the second disk to Mainboard i have no problems with zfs
