### ISSUE TITLE
Clang - Linux - Unable to build an empty module

### ISSUE THREAD

**Issue by RinCat** [openzfs/zfs#10107]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo
Distribution Version	|  Latest
Linux Kernel	|  5.4.24
Architecture	|  x86_64
ZFS Version	|  0.8.3
SPL Version	|  0.8.3
LLVM/Clang       | 10.0.0

### Describe the problem you're observing
Failed to build kernel module with error:

> configure:17423: checking whether modules can be built
> configure:17483:
>             KBUILD_MODPOST_NOFINAL= KBUILD_MODPOST_WARN=
>             make modules -k -j24 -C /usr/src/linux
>             M=/var/tmp/portage/sys-fs/zfs-kmod-0.8.3/work/zfs-0.8.3/build/conftest &>build/conftest/build.log
> configure:17486: $? = 2
> configure:17489: test -f build/conftest/conftest.ko
> configure:17492: $? = 1
> configure:17500: result: no
> configure:17505: error:
>         *** Unable to build an empty module.

Manual build:

> make: Entering directory '/usr/src/linux-5.4.24-gentoo'
>   CC [M]  /var/tmp/portage/sys-fs/zfs-kmod-0.8.3/work/zfs-0.8.3/build/conftest/conftest.o
> gcc: error: unrecognized command line option ‘-Qunused-arguments’
> gcc: error: unrecognized command line option ‘-mno-global-merge’
> gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=pattern’
> make[1]: *** [scripts/Makefile.build:266: /var/tmp/portage/sys-fs/zfs-kmod-0.8.3/work/zfs-0.8.3/build/conftest/conftest.o] Error 1
> 

ZFS or kernel(?) ignored CC and use gcc to test.

ZFS module can be build with gcc 9.2 without error.

### Describe how to reproduce the problem
Configure portage use clang in `/etc/portage/make.conf`
```
CC="clang"
CXX="clang++"
COMMON_FLAGS="-O2 -pipe"
CFLAGS="-march=znver2 ${COMMON_FLAGS}"
CXXFLAGS="-march=znver2 ${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LD="ld"
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
```

Configure genkernel use clang in `/etc/genkernel.conf`
`KERNEL_CC="/usr/lib/llvm/10/bin/clang"`

Build kernel and zfs
```
genkernel --no-module-rebuild all
emerge -a zfs-kmod
```

### Include any warning/errors/backtraces from the system logs

[build.log](https://gist.github.com/RinCat/a6f1e946cd672044a03eb9228d13a008)
[config.log](https://gist.github.com/RinCat/32cf1346cb11e3b08dbe15b01b9379d7)

### Note
Tried use patch https://github.com/openzfs/zfs/pull/9927/commits/0ab9562abac1b39da136591d3ad4843ca58ebe5b , but the result is same.

**Comment by torvic9** [comment]
You must pass the CC flags to ./configure.

**Comment by torvic9** [comment]
Sorry, please disregard. I misread your comment.
I'm running into the same issue. 
It seems that for the conftest, make reverts to gcc instead of using clang.

**Comment by RinCat** [comment]
I am actually successful build and running on it like a month with clang 10, but did have to time digging further.

I need patching kernel.m4 , and passing CC to it, otherwise it ignored `make CC=clang` in conftest. 


`kernel.m4.patch`
```
--- a/config/kernel.m4  2020-01-22 16:49:04.000000000 -0500
+++ b/config/kernel.m4      2020-03-10 18:23:26.973992178 -0400
@@ -602,7 +602,7 @@
 AC_DEFUN([ZFS_LINUX_COMPILE], [
        AC_TRY_COMMAND([
            KBUILD_MODPOST_NOFINAL="$5" KBUILD_MODPOST_WARN="$6"
-           make modules -k -j$TEST_JOBS -C $LINUX_OBJ $ARCH_UM
+           make CC=$CC modules -k -j$TEST_JOBS -C $LINUX_OBJ $ARCH_UM
            M=$PWD/$1 &>$1/build.log])
        AS_IF([AC_TRY_COMMAND([$2])], [$3], [$4])
 ])
```

and patch from https://12101111.github.io/llvm-compile-zfs-on-root/
`dbuf.c.patch`
```
--- a/module/zfs/dbuf.c
+++ b/module/zfs/dbuf.c
@@ -2397,11 +2397,11 @@ dmu_buf_set_crypt_params(dmu_buf_t *db_fake, boolean_t byteorder,
        bcopy(mac, dr->dt.dl.dr_mac, ZIO_DATA_MAC_LEN);
 }

-#pragma weak dmu_buf_fill_done = dbuf_fill_done
 /* ARGSUSED */
 void
-dbuf_fill_done(dmu_buf_impl_t *db, dmu_tx_t *tx)
+dmu_buf_fill_done(dmu_buf_t *dbuf, dmu_tx_t *tx)
 {
+       dmu_buf_impl_t *db = (dmu_buf_impl_t *)dbuf;
        mutex_enter(&db->db_mtx);
        DBUF_VERIFY(db);
```

And this patch https://github.com/openzfs/zfs/pull/9927

Also local zfs-kmod ebuild with
```
src_compile() {
        set_arch_to_kernel

        emake "${myemakeargs[@]}" CC=$CC
}
```

I am not sure kernel.m4 ignored CC is bug or feature.

**Comment by torvic9** [comment]
Thank you! The first patch helped with the conftest issue, but I'm now running into other unrelated issues...

**Comment by torvic9** [comment]
With your help, I have assembled all the necessary patches in [one patch file](https://github.com/torvic9/linux56-vd/blob/master/zfs/linux-5.6-compat-clang.patch). 
Maybe it could be useful for people running into this issue on 0.8.3.

**Comment by lovesegfault** [comment]
This is still relevant, the bug is still present.

**Comment by foundObjects** [comment]
I'm also seeing this while using clang built kernels on 2.1.1. I've patched dkms to supply all of the LLVM tools when building for an LLVM built kernel but the `Unable to build an empty module` issue persists. My other modules build as expected.

**Comment by foundObjects** [comment]
DKMS has [merged support](https://github.com/dell/dkms/commit/abc62207ec507cf20b58d92032c7362a24ce62be) for Clang/LLD as of 3.0.2. This issue is still present in ZFS 2.1.1 so it seems something is wrong other than "CC and LD aren't set properly." Note that other dkms modules (nvidia, r8168, ntfs3, etc) all build properly against clang/LLVM compiled kernels, the only one that doesn't build is ZFS.

**Comment by szubersk** [comment]
@RinCat @torvic9 @lovesegfault @foundObjects please try OpenZFS 2.1.3 or newer release. Indeed there was an issue with clang-built kernels. To enable clang kernel module compilation please pass `KERNEL_LLVM=1` to `./configure`.
Feel free to close this issue if OpenZFS 2.1.3+ is compiled cleanly by clang.
