### ISSUE TITLE
Empty snapshot folder

### ISSUE THREAD

**Issue by marker5a** [openzfs/zfs#10104]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| ArchLinux
Linux Kernel	| 5.4.15-ck
Architecture	| x86_64
ZFS Version	| 0.8.3-1
SPL Version	| 0.8.3-1

### Describe the problem you're observing
When browsing into the snapshot folder of a zfs filesystem, I can cd into the snapshot, but the folder has no contents.  Mounting the same snapshot using mount -t zfs <snapshot_name> <mountpoint> has the expected files

### Describe how to reproduce the problem
-Create snapshot
-cd <zfs filesystem root>/.zfs/snapshot/<snapshot name>
-ls
-mount -t zfs <zfs filesystem> /mnt
-ls /mnt
### Include any warning/errors/backtraces from the system logs

There are no errors/warnings to report.  One other note, of which may be irrelevant, is that the filesystems I am testing this against are all derived from ZFS on root fs.

**Comment by jhyeon** [comment]
You may find an automount error in `/proc/spl/kstat/zfs/dbgmsg`.  See my comments in #9461 and #9381.
I suspect this error occurs on systems with initramfs which `chroot(2)`s to new root filesystem and starts `init` process by running `switch_root(8)`.

**Comment by marker5a** [comment]
Ah, yes, you're correct... I tried searching for issues before posting so as not to duplicate, so apologies!
FWIW, I am receiving error 512 in the log... for instance

`1583461577   zfs_ctldir.c:1086:zfsctl_snapshot_mount(): Unable to automount /new_root/var/lib/docker/.zfs/snapshot/autosnap_2020-02-29_00:00:08_daily error=512`

**Comment by marker5a** [comment]
Moving to #9461
