### ISSUE TITLE
Why is the lz4 compression ratio low, when using postgresql?

### ISSUE THREAD

**Issue by kroeckx** [openzfs/zfs#10125]
All the documents I read suggest that I should enable lz4 compression for postgresql. But instead of compression I mostly see overhead. When I run "get compressratio", it shows me 1.06x, but that seems totally wrong.

I currently see:
```
# du -sh /pgdata/
786G    /pgdata/
# du -sh --apparent-size /pgdata/
577G    /pgdata/
```

That is, I have an average overhead of 36%.

Postgresql stores all files with a limit of 1GB. On one table du shows 1.5G for most of those files, 1.4G for some others, while du --apparent-size of course shows 1.0G for all of them. If I copy that file to some other location, it will instead say the file takes 692M. Manually compressing the file with lz4 makes it 652M.

A different table actually has most files at 756M.

Any idea why I'm getting this?

**Comment by ahrens** [comment]
`du -sh` includes many effects that can increase the space used, compared to the apparent size, in addition to compression (which strictly decreases space used).  E.g. indirect blocks, RAIDZ overhead (if different than expected), sector size roundup.

To help you understand the space usage, can you tell us: What is your recordsize property?  What is the sector size (ashift)?  What is the vdev configuration (`zpool list -v`)?

**Comment by kroeckx** [comment]
> To help you understand the space usage, can you tell us: What is your recordsize property?  What is the sector size (ashift)?  What is the vdev configuration (`zpool list -v`)?

NAME          PROPERTY    VALUE    SOURCE
rpool/pgdata  recordsize  8K       local

NAME   PROPERTY  VALUE   SOURCE
rpool  ashift    12      local

NAME                                          SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
rpool                                          29T  8.22T  20.8T        -         -     5%    28%  1.00x    ONLINE  -
  raidz2                                       29T  8.22T  20.8T        -         -     5%  28.3%      -  ONLINE
    ata-HGST_HUH721008ALN600_7HKK6LBJ-part4      -      -      -        -         -      -      -      -  ONLINE
    ata-HGST_HUH721008ALN600_7HKK5DMJ-part4      -      -      -        -         -      -      -      -  ONLINE
    ata-HGST_HUH721008ALN600_7HKK00GJ-part4      -      -      -        -         -      -      -      -  ONLINE
    ata-HGST_HUH721008ALN600_7HKK86EJ-part4      -      -      -        -         -      -      -      -  ONLINE

The disks have:
Sector Size:      4096 bytes logical/physical

**Comment by DeHackEd** [comment]
Since you have 4k disks sedctors and 8k filesystem, compression can at best accomplish a 50% space reduction.

But raidz2 adds 2 parity blocks for each filesystem block per stripe, and always rounds up to a multiple of 3 disk sectors. For your 4-disk configuration a successful compression down to 1 disk sector for the data means 3 sectors consumed - 1 data, 2 parity, and the forced rounding looks good. For unsuccessful compression you have 2 data sectors, 2 parity sectors, and then 2 spacer sectors needed to round up to 6 sectors total.

So,  yeah, the overhead is quite high and unfortunately that's expected.

**Comment by kroeckx** [comment]
I don't get the comment about 2 spacer sectors. Can you point to something that explains that?

Do you have a suggestion for how to avoid that overhead?

**Comment by ahrens** [comment]
It's not possible to avoid that overhead, but it is proportionally reduced for larger blocks.  RAIDZ is rarely appropriate for use with small recordsize data.  For more details on RAIDZ space usage, see my blog post: https://www.delphix.com/blog/delphix-engineering/zfs-raidz-stripe-width-or-how-i-learned-stop-worrying-and-love-raidz

**Comment by kroeckx** [comment]
At http://open-zfs.org/wiki/Performance_tuning#PostgreSQL, recordsize=8K is recommended for both the data and the wall, and logbias=throughput for the data (and logbias=latency for the wall).

When reading various things, I think that suggestion for 8K for both is wrong, and that it should probably be set to something higher for the data, but should be set to 8K for the wal.

**Comment by kroeckx** [comment]
I changed the recordsize to 128K, and now the files of 1.5G seem to end up at around 0.5G.

**Comment by kroeckx** [comment]
If I understand this all correctly, with n being the raidz level, so n = 2 for raidz2, you always write in multiples of n+1 sectors. Because of the combination of 8K record size and 4K sector size, if the compression made it less then 4K I was lucky it could fit it in 3 sectors, and if didn't it needed 6 sectors. I had tables where I'm lucky to be just below the 4K, and others where I'm unlucky and just above it. So a recordsize that's higher, in combination with compression, will make the overhead lower.

I think the wiki could use an update.

**Comment by kroeckx** [comment]
If I understand correctly, in the case of raidz2 on 4 disks, if compression isn't used, since it will allocate per 3 sectors, and I wanted to optimize to overhead, I actually want my recordsize to be (a multiple of) the least common multiple of 3 and 4, so 12 sectors, so that I can write:

P P D D
P P D D
P P D D

**Comment by DeHackEd** [comment]
Sorry, filesystem block sizes (before compression) are powers of 2, so the math just doesn't work out when you need a multiple of 3 in that number to completely avoid overhead.

Like ahrens said, you can't avoid overhead. Also if you have compression enabled the block sizes will tend to be inconsistent, and this is just how RAID-Z works. Sorry, but you'll have to deal with it. 

Alternatively I might suggest RAID-10 instead. You tend to get better concurrent access performance and overall IOPS which is probably a good thing for an SQL database.

**Comment by kroeckx** [comment]
I'm happy with the larger recordsize. As I understand it, if I
make it large enough, it will always lower my overhead. In
combination with the compression it's working good.

The IOPS are more than enough for the workload. I just don't
understand why the wiki says to use an 8K recordsize for the data.

**Comment by DeHackEd** [comment]
Because that's the IO size used by postgresql. Reads and writes are in these increments at the application layer, but ZFS will use the recordsize for all IO it performs on disk.

So it will be reading large blocks from disk, checksumming and decompressing large blocks, caching large blocks, and when it's time to write probably replacing large blocks where only a couple of kilobytes were actually modified by the application.

So generally things are more efficient when using smaller blocks other than the increased overhead and fragmentation. But broadly speaking sequential operations on SQL databases should be infrequent and the fragmentation isn't such a serious concern.
