### ISSUE TITLE
cann't see the file in the snapshot through nfs share at client

### ISSUE THREAD

**Issue by dinghuaming** [openzfs/zfs#10149]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  NeoKylinAdvancedServer
Distribution Version	|  6.7
Linux Kernel	|  2.6.32
Architecture	|  x86_64
ZFS Version	|  0.8.3.1
SPL Version	| 0.8.3.1

### Describe the problem you're observing
zfs nfs and snapshot problem. 
when we mount nfs share at client, we cann't see the files in the snapshot directory, but we can see it in the Openindiana. what happens?

### Describe how to reproduce the problem
at server(192.168.22.105) (Linux):
1. create a zfs :  
     zfs create data/test
2. set nfs share: 
     zfs set sharenfs=rw=@192.168.22.106,no_root_squash data/test
3. create a file: 
     touch /data/test/file1
4. create a snapshot:  
     zfs snapshot data/test@one

at client(192.168.22.106)(Linux):
1. create mountpoint diretory:  
       mkdir -p /tmp/test
2. mount share at client(192.168.22.106) :  
      mount 192.168.22.105:/data/test /tmp/test
3. watch file file1:  
   3.1 we can see the file file1:  
             ls -l /tmp/test/file1
   3.2 we cann't see the file file1 in the snapshot: 
             ls -l /tmp/test/.zfs/snapshot/one/files

when the nfs server is Openindiana, we can see the file1 in the snapshot  at client(Linux):
      ls -l /tmp/test/.zfs/snapshot/one/files

**Comment by rincebrain** [comment]
You probably want the NFS export flag "crossmnt" - otherwise, if you have NFS export /foo and a filesystem mounted at /foo/bar, looking in /foo/bar on the NFS client will show empty. (ZFS snapshots are distinct filesystem mounts.)

**Comment by dinghuaming** [comment]
> You probably want the NFS export flag "crossmnt" - otherwise, if you have NFS export /foo and a filesystem mounted at /foo/bar, looking in /foo/bar on the NFS client will show empty. (ZFS snapshots are distinct filesystem mounts.)

yes. this is the problem. thanks.

**Comment by kneutron** [comment]
Please close out this issue if the problem is solved
