### ISSUE TITLE
Fedora 32 repository

### ISSUE THREAD

**Issue by amarshall** [openzfs/zfs#10147]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.6
Architecture	| x86_64
ZFS Version	| n/a
SPL Version	| n/a

### Describe the problem you're observing
No repository available on Fedora 32, which is [in beta](https://fedoramagazine.org/announcing-the-release-of-fedora-32-beta/). Release target is one month away, 2020-04-21 ([see schedule](https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html)).

### Describe how to reproduce the problem
```
curl -IL http://download.zfsonlinux.org/fedora/32/x86_64/repodata/repomd.xml 
```
gives 404

### Include any warning/errors/backtraces from the system logs
n/a

**Comment by mskarbek** [comment]
I would not expect any until the next release o OpenZFS. 0.8.3 supports kernels up to 5.4.x and fc32 will be released with 5.5.x.

**Comment by amarshall** [comment]
> fc32 will be released with 5.5.x

Are you sure? Currently Fedora 32 has 5.6.0.rc5.

**Comment by mskarbek** [comment]
No, I'm not but usually, Fedora introduces new kernel to the stable repo after 2-4 patch releases. We have two/three weeks to 5.6.0 release and 5 weeks to Fedora 32 release so IMO it's quite likely they will endup with 5.5.x.

**Comment by storrgie** [comment]
Tacking on to this as F32 Beta media has been made accessible/available on their frontages

**Comment by mskarbek** [comment]
@storrgie as you can read in https://github.com/openzfs/zfs/pull/9961#issuecomment-607366062 we have to wait until 0.8.4. There is no reason for nagging when it's commonly known that 0.8.3 is not compatible with kernels delivered in fc32. If you need both OpenZFS and fc32 then get 5.4.20 from Koji - https://koji.fedoraproject.org/koji/buildinfo?buildID=1463632 and install it manually.

**Comment by Pascal666** [comment]
0.8.4 packages for Fedora 32 have been released.

https://github.com/openzfs/zfs/wiki/Fedora

**Comment by tonyhutter** [comment]
```
yum install http://download.zfsonlinux.org/fedora/zfs-release.fc32.noarch.rpm
yum install zfs
```

**Comment by storrgie** [comment]
Thanks a ton @tonyhutter for the effort on getting this sorted!

**Comment by MatthewBregg** [comment]
In the wiki, https://github.com/openzfs/zfs/wiki/Fedora, it says 'Fedora Releases: 30, 31'.

Should this be 'Fedora Releases: 30, 31, 32' now?

**Comment by tonyhutter** [comment]
@MatthewBregg thank you!  Fixed.
