### ISSUE TITLE
very slow write performance

### ISSUE THREAD

**Issue by A2116** [openzfs/zfs#10145]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS 7
Distribution Version	| 7.7 1908
Linux Kernel	| 5.4.19
Architecture	| x86_64
ZFS Version	|  0.8.3-1
SPL Version	|  0.8.3-1

### Describe the problem you're observing
I have created a pool with 12 Samsung 860 SSD
when I perform benchmark on raw 12 SSD I get these results
245K read
225K write

but when I create a RAID 10 test pool with 6 mirrors (total 12 drive) I get these performances
315K read
23K write

why write performance is slow about 10 percent of 12 drive instead of 50 percent of it?
what is the impact of caching mechanism on reading and writing?
I have not done any modification on zpool and zfs except creating a volume for test poll on dev level rather than on file level using fio

### Describe how to reproduce the problem

zpool create R1D12 mirror sda sdb mirror sdc sdd mirror sde sdf mirror sdg sdh mirror sdi sdj mirror sdk sdl

zfs create -V 1200G R1D12/R1D12Vol

fio settings:

filename=/dev/zvol/R1D12/R1D12Vol
direct=1
rw=randrw
rwmixread=0
rwmixwrite=100
blocksize=4K
ioengine=libaio
group_reporting
refill_buffers
norandommap
randrepeat=0
numjobs=32
iodepth=64
runtime=300

benchmark setting between raw device test and zfs is same

**Comment by gmelikov** [comment]
Please fill `Describe how to reproduce the problem` section, otherwise performance issue is pointless. Problem is usually in benchmark method.

**Comment by A2116** [comment]
> 
> 
> Please fill `Describe how to reproduce the problem` section, otherwise performance issue is pointless. Problem is usually in benchmark method.

i edited the text

**Comment by gmelikov** [comment]
Not a bug - by default zfs has 128k recordsize, and you benchmark 4k mixed (random? Not sure about rwmixwrite randomness) write, so on each 4k write there will be a 128k full block read (if not cached) and 128k full block write, which is huge write amplification.

For support questions you may use our mailing lists next time https://github.com/openzfs/zfs/wiki/Mailing-Lists .

**Comment by A2116** [comment]
![Raw12SSD4K100RandRead4K](https://user-images.githubusercontent.com/41579812/77133560-b4ca5480-6a78-11ea-85c8-6fff33118dd4.png)
![Raw12SSD4K100RandWrite4K](https://user-images.githubusercontent.com/41579812/77133562-b72cae80-6a78-11ea-8801-a455f718a8c7.png)
![ZFS4KRs4KVbs100RandRead4K](https://user-images.githubusercontent.com/41579812/77133597-d297b980-6a78-11ea-883f-114da3d5d1d8.png)
![ZFS4KRs4KVbs100RandWrite4K](https://user-images.githubusercontent.com/41579812/77133600-d4617d00-6a78-11ea-9706-8c0b5f330cd1.png)
![ZFS128KRs8KVbs100RandRead4K](https://user-images.githubusercontent.com/41579812/77133604-d9bec780-6a78-11ea-9c23-5c8ebf2a5745.png)
![ZFS128KRs8KVbs100RandWrite4K](https://user-images.githubusercontent.com/41579812/77133607-db888b00-6a78-11ea-8817-69001dd1ea72.png)

I uploaded some file that I have tested with a script, with various queue depth and number of jobs, in 3 different configurations, one with raw SSD, second with 4K RecordSize & VolBlockSize and thirth with 128K RecordSize and 8K VolBlockSize

**Comment by gmelikov** [comment]
Ah, sorry, I've missed that you test zvols.

Try to set same volblocksize and fio blocksize, and test larger one (16k, for example).

And you may want to look at https://github.com/openzfs/zfs/wiki/ZFS-on-Linux-Module-Parameters#zvol_threads , or, try to test on several zvols. And you may try to test dataset too, recordsize will be effective for it.

Default zfs parameters usually won't give you full performance from one object/small number of threads especially on ssd without some tuning, because by default it's tuned for massive parallel random requests for many objects, and zvol has it's nuances. And small blocksize wll require more metadata on disk too (more blocks - more meta).

**Comment by A2116** [comment]
I am tested in the different configuration
I am increasing arc_max, also increasing vol_treads and change atime to off
different recordsize, different volblocksize, different number of vol, different ashift (9 or 12) and finally in another server with stronger CPU (2697V2) and with ubuntu and even enabling compression
also i tried init_on_alloc=0 and init_on_free=0
I done the tests on RAID10 (6*2), RAID5 (raidz) and RAID6 (raidz2) and even RAID0 and also I done test on file on the root zfs instead of volume

in all configuration, max write performance for 12 Samsung 860 SSD is 20K to 25K and in rare condition reach to 30K

this happens in the same server that can achieve 240K in reading and writing on 12 disk

my question after all my effort is, am I done something wrong? or it's zfs performance? I see in another post that somebody reaches 127K write on 8 drive, but I think every work that I have done hit to a hard limitation on write performance
all of these is aside with increased performance that gained from caching, in some situations while testing read operation I see both iostat (Linux) and zpool iostat show me zero transfer, while fio shows me 150K iops, that means all io came from the ram
so please tell me what should I do? is any special setting needed to release real zfs performance?
