### ISSUE TITLE
Online a device causing it to do a full resilver

### ISSUE THREAD

**Issue by sjau** [openzfs/zfs#10150]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Nixos
Distribution Version	| Unstable
Linux Kernel	| 5.5.8
Architecture	| x86_64
ZFS Version	| 0.8.3-1
SPLVersion	| 0.8.3-1

### Describe the problem you're observing

On my notebook I have two SSDs that I run in a mirror configuration. At home and at work I have external USB 3.0 drives that I also attached to the mirror.

When I go to work or come back home, I do offline/online the attached mirrors first, e.g.

`zpool offline {pool} {usb-drive}`
`zpool online {pool} {usb-drive}`

The off- and onlining works, however I noticed it will make a full resilver. Meaning it write resilvers around 700GB instead of just what altered since the device was offlined. In General each device usually gets onlined once a day (except the weekends).

According to https://markmail.org/message/prhh6sw7atyljsf6 ,:

_The DTL keeps track of times (txg ranges) when a device was offline. For example, in a mirrored pair, one side of the mirror may go offline for some time.  If it is reattached, only the data which was written to the other side of the mirror while the device was offline needs to be resilvered (scrubbed)._

Because of that post, I assumed it would work with such a "partial" resilver but it's the experience it doesn't. At least not when a usb disk is attached as vdev.

### Describe how to reproduce the problem

1. Setup mirrored system
2. Attach an external usb 3.0 disk to the mirror
3. Let it complete the resilvering
4. Offline the extnerla usb 3.0 disk
5. Wait a while (maybe 1 day) and use the system as usual
6. Online the external usb 3.0 disk again

**Comment by sjau** [comment]
e.g.

```
hyper@subi:~$ zpool status
  pool: tankSubi
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Mon Mar 23 06:25:04 2020
        696G scanned at 75.6M/s, 423G issued at 45.9M/s, 704G total
        435G resilvered, 60.03% done, 0 days 01:44:37 to go
config:

        NAME                                                  STATE     READ WRITE CKSUM
        tankSubi                                              DEGRADED     0     0     0
          mirror-0                                            DEGRADED     0     0     0
            wwn-0x500253887017d116-part2                      ONLINE       0     0     0
            16973600818329360236                              UNAVAIL      0     0     0  was /dev/disk/by-id/usb-TOSHIBA_External_USB_3.0_2012110725463-0:0-part1
            usb-TOSHIBA_External_USB_3.0_20170612010552F-0:0  ONLINE       0     0     1  (resilvering)
            nvme0n1p2                                         ONLINE       0     0     0

errors: No known data errors```

It's been resilvering for 2 1/2h. It was to offline saturday at around 11am. So not quite 2 days offline.

**Comment by devZer0** [comment]
maybe this is some further helpful information in this context:

https://serverfault.com/questions/641136/is-it-possible-to-detach-and-reattach-a-zfs-disk-without-requiring-a-full-resilv

https://oipapio.com/question-7449242

**Comment by sjau** [comment]
Neither is a help. Both state that offlining and onlining should do a delta-resilver but that doesn't seem to be the case with my usb drives. I do have offsite backups also but it's also very nice to just resilver an external usb drive. Because if the system fails at some point (broken ssds, lost, .....), all I need to the external usb disk and a way to boot up the system again and then I can attach new ssd and have it resilver - all while I can already use it again.

**Comment by kneutron** [comment]
At the risk of sounding trite, ZFS is not really intended to work the way you're trying to use it.

The workaround for this (as mentioned in the provided links) is to **not** offline mirror drives -- separate your usb drives into a separate pool (you can probably use zpool split) and do zfs send/recv to update the data on them.

This can probably be closed

**Comment by sjau** [comment]
So, what is offlininig/onlinging for then if you can't offline/online devices?

**Comment by kneutron** [comment]
LMGTFY:

https://docs.oracle.com/cd/E19253-01/819-5461/gazgm/index.html

https://www.thegeekdiary.com/solaris-zfs-how-to-offline-online-detach-replace-device-in-a-storage-pool/

https://docs.joyent.com/private-cloud/troubleshooting/disk-replacement

Offlining a drive is putting it into "a manual administrative state, and healthy drives can be brought back online and active into the pool."  This is considered as **part of the process to replace a failed disk**, NOT as a potential method of backup.

**Comment by RJVB** [comment]
I know, old ticket, but:

> Because if the system fails at some point (broken ssds, lost, .....), all I need to the external usb disk and a way to boot up the system again and then I can attach new ssd and have it resilver - all while I can already use it again.

Erm, no, not to my knowledge, not if you main SSDs are completely broken or lost. I don't know of a way to upgrade an offlined mirror device to a copy/clone of the original pool. All I know that you can do is split if off into/as a new, standalone pool.

If you do that, you will first have to destroy that new pool or at the very least use `zpool attach -f` to turn it into a mirror again. And it's evident that that would be followed by a full resilver.

> At the risk of sounding trite, ZFS is not really intended to work the way you're trying to use it.

That's still something we should better not even think aloud about, isn't it...

> This is considered as part of the process to replace a failed disk, NOT as a potential method of backup.

With all due respect, ZFS doesn't care what you're using the mechanism for. If offlining a mirror is for replacements only, fine, we can't complain about the fact you can't do anything with the offlined mirror (AFAIK). But the OP was just replacing 1 pair of healthy disks with another pair, in different locations. The documentation suggests that doing this should resilver only the changed bits so clearly someone considered it an acceptable use case that you'd replace a mirror with one that had already served with that same pool. And BTW, I can confirm that is indeed what happens, even when the mirror is on a USB drive.
