### ISSUE TITLE
"zpool import -f -a -N -o cachefile=none" still update cachefile

### ISSUE THREAD

**Issue by didrocks** [openzfs/zfs#10160]
### System information

Type | Linux/Ubuntu
Distribution Name	|  Ubuntu
Distribution Version	| focal (incoming 20.04 LTS)
Linux Kernel	|  Linux casanier 5.4.0-18-generic #22-Ubuntu SMP Sat Mar 7 18:13:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Architecture	| x86_64
ZFS Version	| 0.8.3
SPL Version	| 0.8.3

### Describe the problem you're observing

When detecting pools and importing them without wanted to update `/etc/zfs/zpool.cache`, this one is still updated: pools that were not imported before this command call but were listed in /etc/zfs/zpool.cache (like on boot) are removed from /etc/zfs/zpool.cache.

### Describe how to reproduce the problem

1. /etc/zfs/zpool.cache contains "rpool" and "tank". rpool is imported, tank isn’t imported (case when booting for instance, rpool being mounted by initramfs).
2. run `zpool import -f -a -N -o cachefile=none`
-> tank is now imported as expected
-> /etc/zfs/zpool.cache is updated and only contains now "rpool", not "tank"

### Include any warning/errors/backtraces from the system logs
There is no output from the zpool import command itself.

The journal doesn’t show anything special on the import:
```
mars 27 11:58:22 v sudo[7913]: pam_unix(sudo:session): session closed for user root
mars 27 11:58:47 v sudo[8008]:        u : TTY=pts/0 ; PWD=/home/u ; USER=root ; COMMAND=/usr/sbin/zpool import -f -a -N -o cachefile=none
mars 27 11:58:47 v sudo[8008]: pam_unix(sudo:session): session opened for user root by u(uid=0)
mars 27 11:58:47 v sudo[8008]: pam_unix(sudo:session): session closed for user root
mars 27 11:58:47 v zed[8163]: eid=39 class=history_event pool_guid=0x8E462ABF747238BA
mars 27 11:58:47 v zed[8166]: eid=40 class=config_sync pool_guid=0x8E462ABF747238BA
mars 27 11:58:47 v zed[8168]: eid=41 class=pool_import pool_guid=0x8E462ABF747238BA
mars 27 11:58:47 v zed[8171]: eid=42 class=history_event pool_guid=0x8E462ABF747238BA
mars 27 11:58:47 v zed[8174]: eid=43 class=config_sync pool_guid=0x8E462ABF747238BA
```

**Comment by marceloneil** [comment]
I'm experiencing the same issue on Debian Buster. A comment on another issue seemed to point to this as well: https://github.com/openzfs/zfs/issues/8549#issuecomment-520882951
