### ISSUE TITLE
`make deb` builds rpm packages

### ISSUE THREAD

**Issue by Hi-Angel** [openzfs/zfs#10168]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 5.4.28-050428-generic
Architecture	| x86_64
ZFS Version	| 0.8.3
SPL Version	| 0.8.3

    $ modinfo zfs | grep -iw version
    version:        0.8.3-1
    $ modinfo spl | grep -iw version
    version:        0.8.3-1

### Describe the problem you're observing

In 0.8.3 `make deb` builds rpm packages.

### Describe how to reproduce the problem

    $ git clone https://github.com/openzfs/zfs/
    $ cd zfs
    $ git checkout zfs-0.8.3
    $ ./autogen.sh
    $ ./configure
    $ make deb
    $ ls *.rpm

#### Expected

No output from the last command

#### Actual

`rpm` packages were built too, even though only `.deb` were intended to be built.

**Comment by Hi-Angel** [comment]
Worth noting also: `rpm` packages fails to build, but apparently it's because Ubuntu has too old Python, which `./configure` does check and bails out. But all of this is too confusing, and as a user I am not even sure whether `.deb` packages were built as intended, or the build system failed half the way through.

**Comment by gmelikov** [comment]
You should specify dkms or kmod packages, instruction https://github.com/openzfs/zfs/wiki/Custom-Packages#dkms-1

So, it should be: `make -j1 pkg-utils deb-dkms`

**Comment by Hi-Angel** [comment]
> You should specify dkms or kmod packages, instruction https://github.com/openzfs/zfs/wiki/Custom-Packages#dkms-1
> 
> So, it should be: `make -j1 pkg-utils deb-dkms`

Thanks! I checked, this way it also built one `rpm` package, then failed on `recipe for target 'rpm-common'` *(because of the old python)*. Funnily, this was it didn't even built `.deb` packages, apparently because it decided to build `rpm` first, which it then failed.

**Comment by rincebrain** [comment]
make deb-* generates RPMs and then aliens them into DEB files (unless that got changed when I wasn't looking), so that makes some sense.

**Comment by gmelikov** [comment]
@rincebrain is right, we convert rpm packages into deb via alien now.
