### ISSUE TITLE
Improve 'make install' and 'make uninstall'

### ISSUE THREAD

**Issue by thorsteneb** [openzfs/zfs#10174]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu Desktop
Distribution Version	|  18.04.04
Linux Kernel	|  5.3.0-45-generic
Architecture	| x86-64
ZFS Version	| 0.8.3-1
SPL Version	| 0.8.3-1

### Describe the problem you're observing

Issue 1)
'sudo make install' does not install kernel modules into /lib/modules/<kernel-version>/kernel/zfs, leaving the modules that ship with Ubuntu in place.

This means in order to use the new kernel modules, one would need to './scripts/zfs.sh -u; ./scripts/zfs.sh', and repeat that after every boot.

Expected behavior: 'sudo make install' installs the built kernel modules, as well

1b) On Linux distributions that use systemd, should 'sudo make install' enable ZFS services and targets, like a package does, or just make them available to be enabled? Debatable either way.

Issue 2)
'sudo make uninstall' leaves pieces of ZFS behind, as shown by 'sudo ./scripts/zfs-helpers.sh -i' run after 'sudo make uninstall':

thorsten@raidz-expand:~/zfs-release$ sudo ./scripts/zfs-helpers.sh -i
Symlink exists: /sbin/fsck.zfs
Symlink exists: /usr/local/etc/zfs/zpool.d
Symlink exists: /usr/lib/python3/dist-packages/libzfs_core
Symlink exists: /lib/libzfs_core.so
Symlink exists: /lib/libnvpair.so

### Describe how to reproduce the problem

Ubuntu 18.04.04 LTS kernel 5.3.0-45-generic
ZFS master branch as of Apr 2nd 2020
build as per https://github.com/openzfs/zfs/wiki/Building-ZFS

1) Do a 'sudo make install' after build and check md5sums of kernel modules in /lib/modules/<kernel-version/kernel/zfs against the built modules. They should match; they don't currently, meaning the modules don't get installed.

1b) Run 'sudo systemctl list-unit-files | grep zfs' and observe that ZFS services and targets exist, and are all disabled. 

2) After 1), do a 'sudo make uninstall', then run 'sudo ./scripts/zfs-helpers.sh -i' and observe remaining symlinks

### Include any warning/errors/backtraces from the system logs

Not applicable

**Comment by behlendorf** [comment]
> Issue 1) 'sudo make install' does not install kernel modules into /lib/modules//kernel/zfs

The packaging machinery directly uses the `make install` target so I'm fairly certain this is working as intended.  However, the modules may have been installed in a slightly different path.  On my Ubuntu 18.04 system they're installed in `lib/modules/4.15.0-91-generic/extra/` by default.  The Ubuntu provided packaging may be different.

> 1b) On Linux distributions that use systemd, should 'sudo make install' enable ZFS services and targets

Normally this behavior is left up to the platform specific packaging (Ubuntu / Redhat / FreeBSD / etc). This allows multiple platforms with different notions of what should or should not be enabled to do the right thing for their environment.  So this has intentionally not been included in the `make install` target.

> Issue 2) 'sudo make uninstall' leaves pieces of ZFS behind,

This I was able to reproduce by running the following to install in to an alternate root directory, then uninstall it, and see what we left.  We should update the build system to cleanup these untracked files.

```
mkdir /tmp/zfs-install-dir/
DESTDIR=/tmp/zfs-install-dir/ make install
DESTDIR=/tmp/zfs-install-dir/ make uninstall
find /tmp/zfs-install-dir/ -type f
```

**Comment by thorsteneb** [comment]
Additional flavor. This is a Ubuntu 18.04 desktop that was updated from kernel 5.3.0-45 to 5.3.0-46 as part of sudo apt upgrade. On 5.3.0-45, make install was run and the kernel/zfs directory was manually removed.

The extra/ directory does not "come over" to the new kernel, and the kernel/zfs directory has Ubuntu-supplied modules. Results below.

```
thorsten@raidz-expand:~/zfile$ sudo zpool version
zfs-0.8.0-711_gb338c49ca
zfs-kmod-0.8.1-1ubuntu14.3
thorsten@raidz-expand:~/zfile$ sudo zpool import
   pool: filepool
     id: 14224680504819610112
  state: UNAVAIL
status: The pool can only be accessed in read-only mode on this system. It
	cannot be accessed in read-write mode because it uses the following
	feature(s) not supported on this system:
	com.delphix:log_spacemap (Log metaslab changes on a single spacemap and flush them periodically.)
action: The pool cannot be imported in read-write mode. Import the pool with
	"-o readonly=on", access the pool on a system that supports the
	required feature(s), or recreate the pool from backup.
 config:

	filepool    UNAVAIL  unsupported feature(s)
	  sdb       ONLINE
thorsten@raidz-expand:~/zfile$ sudo zpool version
zfs-0.8.0-711_gb338c49ca
zfs-kmod-0.8.1-1ubuntu14.3
thorsten@raidz-expand:~/zfile$ ls /lib/modules/5.3.0-46-generic/extra
ls: cannot access '/lib/modules/5.3.0-46-generic/extra': No such file or directory
thorsten@raidz-expand:~/zfile$ ls /lib/modules/5.3.0-45-generic/extra
avl  icp  lua  nvpair  spl  unicode  zcommon  zfs
thorsten@raidz-expand:~/zfile$ ls /lib/modules/5.3.0-46-generic/kernel/zfs
icp.ko  spl.ko  zavl.ko  zcommon.ko  zfs.ko  zlua.ko  znvpair.ko  zunicode.ko
```

**Comment by behlendorf** [comment]
It depends what you mean by fixed.  There are some long standing conventions regarding kmods and their install locations.  Modules provided by the distribution as part of their kernel should be included in the usual location.  This is what Ubuntu has done.  There are two other common install locations, `updates` and `extra` which are explained in the [depmod.d(5)](http://manpages.ubuntu.com/manpages/xenial/man5/depmod.d.5.html) man page.

We could override the Ubuntu provided kmods by installing them under `updates`; `By default, depmod will give a higher priority to a directory with the name updates using this built-in search string: "updates built-in" but more complex arrangements are possible and are used in several popular distributions.`

But we chose to install them under `extra`, which has the effect that they don't take priority over the kernel provided kmods.  However, if they're the only version installed depmod will find and load them.  This was done in the mainline ZFS code so distribution provided packages could use `updates` as needed without conflicting with our packaging.  A reasonable argument could be made for either default.

For your testing, what you might want to consider doing is adding `extra` to the start of the depmod search path, see `/etc/depmod.d/ubuntu.conf`.  This will force it to use the module installed in extra first as a local customization.

**Comment by thorsteneb** [comment]
Thank you for taking the time to explain that! Two followup questions, please.

> This was done in the mainline ZFS code so distribution provided packages could use updates as needed without conflicting with our packaging

zfsutils-linux on Ubuntu, standard Ubuntu repos, installs into `extra`, not `updates`, and so suffers from not getting its kernel modules loaded. I'd argue that's unexpected behavior from a user standpoint. Is that for Ubuntu to fix, for ZFS to fix, or not considered a defect in the first place?

Secondly, would you accept a PR into your build instructions that explains the kernel module behavior, and directs a user on Ubuntu to set `/etc/depmod.d/ubuntu.conf` ?

**Comment by behlendorf** [comment]
> zfsutils-linux on Ubuntu, standard Ubuntu repos, installs into extra, not updates

That's right.  The modules from this GitHub repo are intentionally installed in to `extra` since they're not provided directly from ubuntu repositories.  This ensures they they won't conflict with any Ubuntu provided kmods which _could_ potentially break kernel package updates.

I'm not sure what Ubuntu's policy is regarding the `updates` directory, but the same issue would exist for other Linux distributions which may have different policies.  So we've opted to install under `extra` as recommend by the [kernel documentation (see INSTALL_MOD_DIR)](https://www.kernel.org/doc/Documentation/kbuild/modules.txt).

That said, I can definitely see how this could be confusing since the newly installed modules don't take priority over the system provided ones.  (Though we encourage users to use their distribution provided version).

> Secondly, would you accept a PR into your build instructions that explains the kernel module behavior, and directs a user on Ubuntu to set /etc/depmod.d/ubuntu.conf ?

Absolutely, I think this would be a great idea.  This isn't the first time this question has come up.

**Comment by thorsteneb** [comment]
Okay, I think I am starting to get this. Thanks again for taking the time to explain.

zfsutils-linux is an Ubuntu package. It's the only package Ubuntu offers that installs ZFS. In case zfsutils-linux added functionality that cannot be served by the kernel modules that ship with Ubuntu, Canonical would be expected to offer an update to those kernel modules in kernel/zfs as well, alongside with the new zfsutils-linux package they are adding to their repos for that version of Ubuntu. So, if I am say on 18.04.04 and Canonical decides to release a zfsutils-linux that implements raidz expansion (in a hypothetical future where that feature is available upstream), then they'd also be expected to release an update to 18.04.04 alongside that, which replaces the kernel modules in kernel/zfs with ones that can handle raidz expansion. In this way, zfsutils-linux is strongly coupled to the base OS and its default kernel modules, rather than decoupled from it.

I didn't get that, that wasn't intuitive to me. And now I know. :)

**Comment by thorsteneb** [comment]
@behlendorf I have added a note about install to the build instructions wiki. It's at https://github.com/thorsteneb/zfs/wiki/Building-ZFS . Take a look please, let me know what changes you might require, and then that can get into the openzfs wiki through edit by someone with edit rights. It turns out Github doesn't support PRs on wiki pages.

**Comment by behlendorf** [comment]
@thorsteneb thank you.  I've added your install note to the wiki.

**Comment by MasterCATZ** [comment]
could someone have an example please all my  /etc/depmod.d/ubuntu.conf    file contains is 
                                                                            
search updates ubuntu built-in

how / where do I add the "extra"

**Comment by behlendorf** [comment]
Like so:

```
search extra updates ubuntu built-in
```
