### ISSUE TITLE
Issue(s) missing from the github tracker

### ISSUE THREAD

**Issue by GregorKopka** [openzfs/zfs#10176]
### System information
https://github.com/openzfs/zfs/issues/

### Describe the problem you're observing
Links in issue comment(s) are broken because the linked issues _are missing_.

HTTP 404 on https://github.com/zfsonlinux/zfs/issues/8115

### Describe how to reproduce the problem
```
$ wget https://github.com/zfsonlinux/zfs/issues/8115
--2020-04-03 10:44:57--  https://github.com/zfsonlinux/zfs/issues/8115
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/openzfs/zfs/issues/8115 [following]
--2020-04-03 10:44:58--  https://github.com/openzfs/zfs/issues/8115
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-04-03 10:44:58 ERROR 404: Not Found.
```
The link is from https://github.com/openzfs/zfs/issues/8798#issuecomment-504751766

```This has been discussed before, I still think https://github.com/zfsonlinux/zfs/issues/8115#issuecomment-439230918 is the way to go.```

Where did issue 8115 go?
Are there more that vanished without a trace?
Can and will these be restored?

**Comment by behlendorf** [comment]
Yes, unfortunately due to circumstances outside our control a handful of issues are no longer available including #8115.  If needed, we should be able to recreate them on a case by case basis.  Sorry about the inconvenience.
