### ISSUE TITLE
Reproduce the brain split when multihost enabled with zfs 0.7.13

### ISSUE THREAD

**Issue by homerl** [openzfs/zfs#10171]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	|  7.6.1810
Linux Kernel	|   3.10.0-957.1.3.el7_lustre.x86_64
Architecture	|  x86_64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing
The Server A and Server B connect a dual controller SAN (not JBOD, here are my test env) .  
The multi-host feature could not protect my data in this test case.     
Thank you...   

### Describe how to reproduce the problem
There are 9 x share block devices connect to server A and server B
1. I create a raidz2 (test_ost0) for 9 devices in server B    
2. I export this zpool in server B
3. I create two zpools for the 9 x share devices in server A, one is 4 x HDD (raidz2test_ost0); another is 5 x HDD (raidz2 test_ost1)
4. I imported the old test_ost0 (9 x devices) in server B. trigger the brain split.

like this: 
```bash
Server A $ zpool list
NAME        SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
test_ost0   113T   456K   113T         -     0%     0%  1.00x  ONLINE  -
test_ost1   106T  1.37M   106T         -     0%     0%  1.00x  ONLINE  -

Server A $ zpool get multihost
NAME       PROPERTY   VALUE      SOURCE
test_ost0  multihost  on         local
test_ost1  multihost  on         local

Server B $   zpool list
NAME        SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
test_ost0   170T  2.60T   167T         -     0%     1%  1.00x  ONLINE  -

Server B $ zpool get multihost
NAME       PROPERTY   VALUE      SOURCE
test_ost0  multihost  on         local


Server A $ zpool status
  pool: test_ost0
 state: ONLINE
  scan: none requested
config:

	NAME                                   STATE     READ WRITE CKSUM
	test_ost0                              ONLINE       0     0     0
	  raidz2-0                             ONLINE       0     0     0
	    360060e8010143da0058b43aa00000000  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000001  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000002  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000003  ONLINE       0     0     0

errors: No known data errors

  pool: test_ost1
 state: ONLINE
  scan: none requested
config:

	NAME                                   STATE     READ WRITE CKSUM
	test_ost1                              ONLINE       0     0     0
	  raidz2-0                             ONLINE       0     0     0
	    360060e8010143da0058b43aa00000004  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000005  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000006  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000007  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000008  ONLINE       0     0     0

Server B $ zpool import -af
Server B $  zpool status
  pool: test_ost0
 state: ONLINE
  scan: none requested
config:

	NAME                                   STATE     READ WRITE CKSUM
	test_ost0                              ONLINE       0     0     0
	  raidz2-0                             ONLINE       0     0     0
	    360060e8010143da0058b43aa00000001  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000002  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000003  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000004  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000005  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000006  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000007  ONLINE       0     0     0
	    360060e8010143da0058b43aa00000008  ONLINE       0     0     0

errors: No known data errors
```

**Comment by gmelikov** [comment]
IIRC multihost saves you from importing already imported pool only. Pools may have same names, you can check their guids, you have two different `test_ost0` pools here.

On your configuration nothing can stops you from creating new pool on top of another by mistake. Linux rereads partition table on disk connection, you can use `partprobe` for that, so second system will see new ZFS partitions from first server only after partitions table update and tell you about it. If you don't update partitions table by itself - you'll rewrite it. It's not zfs-specific.

**Comment by homerl** [comment]
Yes, I agree, I mean in some mistake operation will cause all data loss. The multihost could not lock the resource.

**Comment by devZer0** [comment]
as gmelikov tells, your expectation that multihost feature would protect in your scenario is wrong. 

multihost protects from importing an existing pool on another host, because that would immediately corrupt data structures - it is meant as a protection means, so two hosts never concurrently access a filesystem which is not developed for shared usage.

there is absolutely nothing in zfs which protects from erroneous access besides of that, if you want protection on device level, i.e. avoid a second node from touching the device at all, you need some cluster/lock-manager or such.  even those may not protect from failure in every circumstance, i.e. if someone is doing the zoning wrong in a SAN and a third node "sees" a lun he wasn't meant to - some admin who does not know what he is doing could completely wipe that lun, even if it's protected on the two other nodes by some cluster-manager at the logical/blockdevice-level.

**Comment by homerl** [comment]
@devZer0 Thank you, I got it.
