### ISSUE TITLE
Linux 5.7 compat: blk_alloc_queue()

### ISSUE THREAD

**Issue by sandhoners123** [openzfs/zfs#10181]
### System information

Type | Version/Name: Linux 5.6/5.7 master
 --- | --- 
Distribution Name	| Arch Linux
Distribution Version	| N/A
Linux Kernel	| 5.5/5.6 master, going to update to latest master today
Architecture	| x86_64
ZFS Version	| latest master commit (the "zfs wait" one)
SPL Version	| N/A

### Describe the problem you're observing

checking whether make_request_fn() returns blk_qc_t... configure: error: 
	*** None of the expected "make_request_fn" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-0.8.0-709_g5a42ef04f
	*** Compatible Kernels: 3.10 - 5.4
This same command worked a week ago on 5.6 master. Does not work now
### Describe how to reproduce the problem
Get latest linux kernel from https://github.com/torvalds/linux and run: ./configure --prefix=/ --libdir=/lib --includedir=/usr/include --datarootdir=/usr/share --enable-linux-builtin=yes --with-linux=/usr/src/linux --with-linux-obj=/usr/src/linux
Can someone fix this error

**Comment by sandhoners123** [comment]
Also another note: The function IS declared in blkdev.h the same way as 5.6

**Comment by sandhoners123** [comment]
And here are some logs: checking kernel source directory... /usr/src/linux
checking kernel build directory... /usr/src/linux
checking kernel source version... 5.6.0-AuRon+Rootspring-g5364abc57
checking kernel file name for module symbols... NONE
checking whether modules can be built... yes
checking for kernel config option compatibility... done
checking whether kernel was built with 16K or larger stacks... yes
checking whether mutex_lock() is GPL-only... no
checking whether CONFIG_TRIM_UNUSED_KSYM is disabled... yes
checking whether CONFIG_ZLIB_INFLATE is defined... yes
checking whether CONFIG_ZLIB_DEFLATE is defined... yes
checking whether fpu headers are available... asm/fpu/api.h
checking whether wait_queue_entry_t exists... yes
checking whether /dev/zfs minor is available... 249
checking whether DECLARE_EVENT_CLASS() is available... yes
checking for available kernel interfaces... done
checking whether access_ok() has 'type' parameter... no
checking whether global_node_page_state() exists... yes
checking whether global_zone_page_state() exists... yes
checking whether enum node_stat_item contains NR_FILE_PAGES... yes
checking whether enum node_stat_item contains NR_INACTIVE_ANON... yes
checking whether enum node_stat_item contains NR_INACTIVE_FILE... yes
checking whether enum node_stat_item contains NR_SLAB_RECLAIMABLE... yes
checking whether enum zone_stat_item contains NR_FILE_PAGES... no
checking whether enum zone_stat_item contains NR_INACTIVE_ANON... no
checking whether enum zone_stat_item contains NR_INACTIVE_FILE... no
checking whether enum zone_stat_item contains NR_SLAB_RECLAIMABLE... no
checking whether global_page_state enums are sane... yes
checking whether compile-time stack validation (objtool) is available... yes
checking whether STACK_FRAME_NON_STANDARD is defined... yes
checking whether PDE_DATA() is available... yes
checking whether fops->fallocate() exists... yes
checking whether zlib_deflate_workspacesize() wants 2 args... yes
checking whether struct rw_semaphore member wait_lock is raw... yes
checking whether struct rw_semaphore has member activity... no
checking whether struct rw_semaphore has atomic_long_t member count... yes
checking whether header linux/sched/rt.h exists... yes
checking whether header linux/sched/signal.h exists... yes
checking whether io_schedule_timeout() is available... yes
checking whether usleep_range() is available... yes
checking whether kmem_cache_create_usercopy() exists... yes
checking whether kvmalloc(ptr, flags) is available... yes
checking whether wait_on_bit() takes an action... no
checking whether wq_head->head and wq_entry->entry exist... yes
checking whether timestamp_truncate() exists... yes
checking whether inode->i_*time's are timespec64... yes
checking whether inode_lock_shared() exists... yes
checking whether group_info->gid exists... yes
checking whether kernel_write() takes loff_t pointer... yes
checking whether kernel_read() takes loff_t pointer... yes
checking whether timer_setup() is available... yes
checking whether timer function expects timer_list... yes
checking whether struct timer_list has flags... yes
checking whether super_block->s_user_ns exists... yes
checking whether proc_ops structure exists... yes
checking whether bops->check_events() exists... yes
checking whether bops->release() is void... yes
checking whether REQ_FAILFAST_MASK is defined... yes
checking whether REQ_DISCARD is defined... no
checking whether REQ_FLUSH is defined... no
checking whether REQ_PREFLUSH is defined... yes
checking whether REQ_OP_DISCARD is defined... yes
checking whether REQ_OP_SECURE_ERASE is defined... yes
checking whether REQ_OP_FLUSH is defined... yes
checking whether bio->bi_opf is defined... yes
checking whether bio_set_op_attrs is available... yes
checking whether bio_set_dev() is available... yes
checking whether bio_set_dev() is GPL-only... no
checking whether bio_end_io_t wants 1 arg... yes
checking whether bio->bi_status exists... yes
checking whether bio has bi_iter... yes
checking whether submit_bio() wants 1 arg... yes
checking whether current->bio_list exists... yes
checking whether blkg_tryget() is available... yes
checking whether blkg_tryget() is GPL-only... no
checking whether blkdev_get_by_path() exists... yes
checking whether blkdev_put() exists... yes
checking whether blkdev_reread_part() exists... no
checking whether invalidate_bdev() exists... yes
checking whether lookup_bdev() wants 1 arg... yes
checking whether bdev_logical_block_size() is available... yes
checking whether bdev_physical_block_size() is available... yes
checking whether struct blk_plug is available... yes
checking whether blk_queue bdi is dynamic... yes
checking whether blk_queue_discard() is available... yes
checking whether blk_queue_secure_erase() is available... yes
checking whether blk_queue_flag_set() exists... yes
checking whether blk_queue_flag_clear() exists... yes
checking whether blk_queue_flush() is available... no
checking whether blk_queue_write_cache() exists... yes
checking whether blk_queue_write_cache() is GPL-only... no
checking whether blk_queue_max_hw_sectors() is available... yes
checking whether blk_queue_max_segments() is available... yes
checking whether get_disk_and_module() is available... yes
checking whether get_disk_ro() is available... yes
checking whether generic_readlink is global... no
checking whether ql->discard_granularity is available... yes
checking whether inode_owner_or_capable() exists... yes
checking whether super_block uses const struct xattr_handler... yes
checking whether xattr_handler has name... yes
checking whether xattr_handler->get() wants dentry and inode... yes
checking whether xattr_handler->set() wants dentry and inode... yes
checking whether xattr_handler->list() wants simple... yes
checking whether posix_acl_from_xattr() needs user_ns... yes
checking whether generic_setxattr() exists... no
checking whether posix_acl_release() is available... yes
checking whether posix_acl_release() is GPL-only... no
checking whether set_cached_acl() is usable... yes
checking whether __posix_acl_chmod exists... yes
checking whether posix_acl_equiv_mode() wants umode_t... yes
checking whether posix_acl_valid() wants user namespace... yes
checking whether iops->get_acl() exists... yes
checking whether iops->set_acl() exists... yes
checking whether uncached_acl_sentinel() exists... yes
checking whether posix_acl has refcount_t... yes
checking whether iops->getattr() takes a path... yes
checking whether inode_set_flags() exists... yes
checking whether inode_set_iversion() exists... yes
checking whether sops->show_options() wants dentry... yes
checking whether file_inode() is available... yes
checking whether file_dentry() is available... yes
checking whether fops->fsync() wants no dentry... no
checking whether fops->fsync() wants range... range
checking whether fops->aio_fsync() exists... no
checking whether sops->evict_inode() exists... yes
checking whether sops->dirty_inode() wants flags... yes
checking whether super_block has s_shrink... yes
checking whether shrink_control has nid... yes
checking whether new 2-argument shrinker exists... no
checking whether ->count_objects callback exists... yes
checking whether struct shrink_control exists... yes
checking whether iops->create()/mkdir()/mknod() take umode_t... yes
checking whether iops->lookup() passes flags... yes
checking whether iops->create() passes flags... yes
checking whether iops->get_link() passes delayed... yes
checking whether i_op->tmpfile() exists... yes
checking whether dops->d_automount() exists... yes
checking whether eops->encode_fh() wants inode... yes
checking whether eops->commit_metadata() exists... yes
checking whether clear_inode() is available... yes
checking whether setattr_prepare() is available... yes
checking whether insert_inode_locked() is available... yes
checking whether d_make_root() is available... yes
checking whether d_obtain_alias() is available... yes
checking whether d_prune_aliases() is available... yes
checking whether d_set_d_op() is available... yes
checking whether dops->d_revalidate() takes struct nameidata... no
checking whether dentry uses const struct dentry_operations... yes
checking whether super_block has s_d_op... yes
checking whether truncate_setsize() is available... yes
checking whether security_inode_init_security wants callback... yes
checking whether fst->mount() exists... yes
checking whether super_setup_bdi_name() exists... yes
checking whether set_nlink() is available... yes
checking whether sget() wants 5 args... yes
checking whether lseek_execute() is available... no
checking whether vfs_getattr() wants 4 args... yes
checking whether vfs_getattr() wants 2 args... no
checking whether vfs_getattr() wants 3 args... no
checking whether vfs_fsync() wants 2 args... yes
checking whether fops->iterate_shared() is available... yes
checking whether aops->direct_IO() uses iov_iter... yes
checking whether fops->read/write_iter() are available... yes
checking whether new_sync_read/write() are available... no
checking whether generic_write_checks() takes kiocb... yes
checking whether kmap_atomic wants 1 args... yes
checking whether follow_down_one() is available... yes
checking whether make_request_fn() returns void... no
checking whether make_request_fn() returns blk_qc_t... configure: error: 
	*** None of the expected "make_request_fn" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-0.8.0-709_g5a42ef04f
	*** Compatible Kernels: 3.10 - 5.4

**Comment by sandhoners123** [comment]
I am really confused now, there were no changes to make_request_fn. It is still blk_qt_t

**Comment by rincebrain** [comment]
The complete contents of config.log would be helpful in debugging this.

**Comment by sandhoners123** [comment]
I think this should be a blocker for openzfs 2.0

**Comment by behlendorf** [comment]
> Get latest linux kernel from https://github.com/torvalds/linux 

I haven't had a chance to look in to this yet.  But the Linux 5.6 kernel was officially released on March 29th, and ZFS should build against this just fine.  However, if you're cloning directly from Linus's tree it's likely your using what will be the 5.7 kernel when released.   Can you run `git describe` in your kernel source tree so we can confirm exactly what version your using.

**Comment by sandhoners123** [comment]
Running that gives: fatal: No names found, cannot describe anything.

**Comment by sandhoners123** [comment]
It returns 5364abc57 if i use --always

**Comment by satmandu** [comment]
I attempted to port https://github.com/openzfs/zfs/commit/68dde63d138882860109178f4ab0b7b1b1bb3cfd to the 0.8.x series with this patch: [k5.7-rc1-zfs.patch.txt](https://github.com/openzfs/zfs/files/4471400/k5.7-rc1-zfs.patch.txt)
, which applies to the ubuntu 0.8.x series zfs-dkms and allows kernel 5.7-rc1 to be used. I warn that my zvol.c patch adaptation is pretty hairy. I have also mentioned it here: https://bugs.launchpad.net/ubuntu/+source/zfs-linux/bug/1872373
