### ISSUE TITLE
Feature request: allow setting max ARC size higher than available RAM

### ISSUE THREAD

**Issue by aaronjwood** [openzfs/zfs#10200]
I have a setup where I'm running Windows Server 2019 as my host and Ubuntu 19.10 as a guest under Hyper-V. I'm passing in an HBA card via discreet device assignment so that the guest gets full hardware access to everything it needs in order for ZFS to work correctly. This guest is setup to use dynamic memory between 8 GB and 44 GB. I figured this would mess up the detection of the max ARC size so I set it via `echo options zfs zfs_arc_max=34360000000 >>/etc/modprobe.d/zfs.conf` and `echo "34360000000" > /sys/module/zfs/parameters/zfs_arc_max`.

This behavior doesn't seem to be supported in ZFS at the moment when dynamic memory or any kind of memory ballooning is being used. On any and every reboot the max ARC size is always set to a very low value of somewhere around 4 GB which seems to be what is dynamically allocated at boot time based on usage.

Maybe this is a niche setup/configuration that I have but it'd be nice to not have to constantly lock out 44 GB from the host. FWIW everything works perfectly fine when using a statically allocated amount of memory for the guest.

**Comment by shodanshok** [comment]
Even if using dynamic memory and higher-then-available ARC would be possible, it will defeat the very same purpose of dynamic memory management: reading/writing from/to the zfs datasets will immediately increase ARC, until it hits the max configured value. At this point, any available memory from host is assigned and consumed. In other words, it will be not so different than directly assiging your guest the full 44 GB RAM.

**Comment by aaronjwood** [comment]
Maybe I have a unique usage pattern. Often I remove chunks of data from my server which greatly lowers the ARC size. As you said, my ARC shoots back up once I have another big burst of writes sometime in the future.

For me this scenario can last for days. These times are when I feel the waste of memory, especially when my host could really use it for some other bursty scenarios I have.

Note that this is not always the case. I may remove lots of data but then an unexpected read workload will happen over a day or two, maxing out my ARC pretty fast.
