### ISSUE TITLE
Native pool property 'written' and real written data

### ISSUE THREAD

**Issue by xgiovio** [openzfs/zfs#10217]
Hello,
speaking on reddit with a guy I discovered a strange behaviour in this dataset attribute.

The 'written' attribute should report new referenced space since the latest snapshot.

I made a snapshot and after that i saw that the property was 0 as expected.

I then deleted a file and watched the 'written propery'. It was changed and it was ok.
Then i created an empty file. Watched the 'written propery'. It was changed and it was ok.
After that i wrote 'c' in the file. Saved. Watched the 'written propery'. It was changed and it was ok.
After that i wrote 'd' in the file replacing 'c'. Saved. Watched the 'written propery'. It was the same.

Is this behaviour normal?

Another test I did. Made the snapshot when the file was with 'c' only.  I then saw that the property was 0 as expected.
I changed the 'c' with a 'd' and the 'written' properties changed.
Replacing again 'd' with 'c' the 'written' property didn't change.

Basing on these results, I think the zfs allocates and frees the same amount of bytes (blocks) so the total number of bytes written doesn't change. Am I right?

Could the 'written' property be used to avoid empty snapshots even if the dataset changes in only a single bit?

Thank you

**Comment by DeHackEd** [comment]
`written` is is the number ZFS will use for its estimate of how big an incremental send will be.

 If you overwrite a file made before a snapshot then the new size counts. If you overwrite a file made after a snapshot then you would (roughly) subtract the size of the old file and then add the size of the new file. Metadata differences will throw a wrench into this but new [meta]data is new [meta]data.

From your description absolutely nothing seems out of place.

**Comment by xgiovio** [comment]
Thank you
