### ISSUE TITLE
arc_prune threads end up consuming 50% or more CPU and leads to reduced I/O write performance on a SSD pool.

### ISSUE THREAD

**Issue by ColinIanKing** [openzfs/zfs#10222]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Xenial and Ubuntu Focal
Distribution Version	| 18.04 and 20.04
Linux Kernel	| 4.15-0.39, 5.4.0-24
Architecture	| x86-64
ZFS Version	| 0.7.5-1ubuntu16.4 and 0.8.3-1ubuntu11 
SPL Version	| 0.7.5-1ubuntu16.4 and 0.8.3-1ubuntu11

Issue on Xenial: arc_prune threads end up consuming 50% or more CPU and leads to reduced I/O write performance on a SSD pool. 

With a long-running ripgrep process on the pool, performance started out really good and grew to astonishingly good (iirc ~30kiops, as measured by zpool iostat -v 1). 
However after a few hours the performance has dropped to 30-40 iops. top reports an arc_reclaim and many arc_prune processes to be consuming most of the CPU time.

References: https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1814983

A similar issue has been observed on a system on Focal 20.04 with 3GB memory.

**Comment by rincebrain** [comment]
You may find the advice in #9966 useful - in particular, my first suggestion would be check arc_summary and see if you're constantly running up against the ARC metadata limit, and if so, try increasing it.

**Comment by behlendorf** [comment]
This is being tracked in #9966.  Several changes we're applied as of the zfs-2.1.3 release which significantly improve, by may not fully resolve, this issue.

1259dc6e6 zfs_prune: reset sc.nr_to_scan
786abf532 Reduce number of arc_prune threads
5303fc4c9 Avoid memory allocations in the ARC eviction thread
