### ISSUE TITLE
migrate from zfs-0.8.0_371 to zfs-0.8.3-1

### ISSUE THREAD

**Issue by dipol0** [openzfs/zfs#10229]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ununtu
Distribution Version	| 
Linux Kernel	| 5.4.33
Architecture	| amdx64
ZFS Version	| 0.8.3-1 and zfs-0.8.0-371_ga5308e252
SPL Version	| 

### Describe the problem you're observing
Sorry for my ENG ^)

Previous i have standard kernel - 4.19.98-041998-lowlatency and build zfs-0.8.0_371 as module. Create pool TANK.
Now i:

- get kernel sources v5.4.33 from https://www.kernel.org/
- get sources zfs-0.8.3 from https://github.com/openzfs/zfs/releases/tag/zfs-0.8.3 and integrate it in kernel sources. Make menuconfig, enable ZFS support (not as module), compile and build new custom kernel, install it and reboot....

After boot on new custom kernel i don't can attach may pool TANK.

When i mannualy try **#zpool import TANK** i get this message:

```
This pool uses the following feature(s) not supported by this system:
    com.delphix:log_spacemap (Log metaslab changes on a single spacemap and flush them periodically.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'TANK': unsupported version or feature
```

.... i can import pool TANK in read-only mode??? This is

Check **#zpool --version** on custom kernel and get:

zfs-0.8.3-1
zfs-kmod-0.8.3-1

My previous installation be a 4.19.98-041998-lowlatency and i install zfs-0.8.0_371 as module and pool TANK be created with zfs-0.8.0_371 version and #zpool --version be as:

zfs-0.8.0_371
zfs-kmod-0.8.0_371

******************************************

#~/src/zfs-pre$ zpool --version

zfs-0.8.0-371_ga5308e252
zfs-kmod-0.8.0-371_ga5308e252

#~/src/zfs-pre$ zpool get all TANK

NAME      PROPERTY                       VALUE                          SOURCE
datapool  size                           1,81T                          -
datapool  capacity                       0%                             -
datapool  altroot                        -                              default
datapool  health                         ONLINE                         -
datapool  guid                           1591240932889661983            -
datapool  version                        -                              default
datapool  bootfs                         -                              default
datapool  delegation                     on                             default
datapool  autoreplace                    off                            default
datapool  cachefile                      none                           local
datapool  failmode                       wait                           default
datapool  listsnapshots                  on                             local
datapool  autoexpand                     off                            default
datapool  dedupratio                     1.00x                          -
datapool  free                           1,81T                          -
datapool  allocated                      19,2M                          -
datapool  readonly                       off                            -
datapool  ashift                         12                             local
datapool  comment                        -                              default
datapool  expandsize                     -                              -
datapool  freeing                        0                              -
datapool  fragmentation                  2%                             -
datapool  leaked                         0                              -
datapool  multihost                      off                            default
datapool  checkpoint                     -                              -
datapool  load_guid                      11093107391978959906           -
datapool  autotrim                       off                            default
datapool  feature@async_destroy          enabled                        local
datapool  feature@empty_bpobj            enabled                        local
datapool  feature@lz4_compress           active                         local
datapool  feature@multi_vdev_crash_dump  enabled                        local
datapool  feature@spacemap_histogram     active                         local
datapool  feature@enabled_txg            active                         local
datapool  feature@hole_birth             active                         local
datapool  feature@extensible_dataset     active                         local
datapool  feature@embedded_data          active                         local
datapool  feature@bookmarks              enabled                        local
datapool  feature@filesystem_limits      enabled                        local
datapool  feature@large_blocks           enabled                        local
datapool  feature@large_dnode            enabled                        local
datapool  feature@sha512                 enabled                        local
datapool  feature@skein                  enabled                        local
datapool  feature@edonr                  enabled                        local
datapool  feature@userobj_accounting     active                         local
datapool  feature@encryption             enabled                        local
datapool  feature@project_quota          active                         local
datapool  feature@device_removal         active                         local
datapool  feature@obsolete_counts        active                         local
datapool  feature@zpool_checkpoint       enabled                        local
datapool  feature@spacemap_v2            active                         local
datapool  feature@allocation_classes     enabled                        local
datapool  feature@resilver_defer         enabled                        local
datapool  feature@bookmark_v2            enabled                        local
datapool  feature@redaction_bookmarks    enabled                        local
datapool  feature@redacted_datasets      enabled                        local
datapool  feature@bookmark_written       enabled                        local
datapool  feature@log_spacemap           active                         local
datapool  feature@livelist               enabled                        local

********************** after install zpool v 0.8.3 *********************************

#~/src/zfs-083-v2$ zpool --version

zfs-0.8.3-1
zfs-kmod-0.8.3-1

#~/src/zfs-083-v2$ zpool get all TANK
NAME      PROPERTY                                     VALUE                                        SOURCE
datapool  size                                         1,81T                                        -
datapool  capacity                                     0%                                           -
datapool  altroot                                      -                                            default
datapool  health                                       ONLINE                                       -
datapool  guid                                         1591240932889661983                          -
datapool  version                                      -                                            default
datapool  bootfs                                       -                                            default
datapool  delegation                                   on                                           default
datapool  autoreplace                                  off                                          default
datapool  cachefile                                    none                                         local
datapool  failmode                                     wait                                         default
datapool  listsnapshots                                on                                           local
datapool  autoexpand                                   off                                          default
datapool  dedupditto                                   0                                            default
datapool  dedupratio                                   1.00x                                        -
datapool  free                                         1,81T                                        -
datapool  allocated                                    19,2M                                        -
datapool  readonly                                     off                                          -
datapool  ashift                                       12                                           local
datapool  comment                                      -                                            default
datapool  expandsize                                   -                                            -
datapool  freeing                                      0                                            -
datapool  fragmentation                                2%                                           -
datapool  leaked                                       0                                            -
datapool  multihost                                    off                                          default
datapool  checkpoint                                   -                                            -
datapool  load_guid                                    11093107391978959906                         -
datapool  autotrim                                     off                                          default
datapool  feature@async_destroy                        enabled                                      local
datapool  feature@empty_bpobj                          enabled                                      local
datapool  feature@lz4_compress                         active                                       local
datapool  feature@multi_vdev_crash_dump                enabled                                      local
datapool  feature@spacemap_histogram                   active                                       local
datapool  feature@enabled_txg                          active                                       local
datapool  feature@hole_birth                           active                                       local
datapool  feature@extensible_dataset                   active                                       local
datapool  feature@embedded_data                        active                                       local
datapool  feature@bookmarks                            enabled                                      local
datapool  feature@filesystem_limits                    enabled                                      local
datapool  feature@large_blocks                         enabled                                      local
datapool  feature@large_dnode                          enabled                                      local
datapool  feature@sha512                               enabled                                      local
datapool  feature@skein                                enabled                                      local
datapool  feature@edonr                                enabled                                      local
datapool  feature@userobj_accounting                   active                                       local
datapool  feature@encryption                           enabled                                      local
datapool  feature@project_quota                        active                                       local
datapool  feature@device_removal                       active                                       local
datapool  feature@obsolete_counts                      active                                       local
datapool  feature@zpool_checkpoint                     enabled                                      local
datapool  feature@spacemap_v2                          active                                       local
datapool  feature@allocation_classes                   enabled                                      local
datapool  feature@resilver_defer                       enabled                                      local
datapool  feature@bookmark_v2                          enabled                                      local
datapool  unsupported@com.delphix:redaction_bookmarks  inactive                                     local
datapool  unsupported@com.delphix:redacted_datasets    inactive                                     local
datapool  unsupported@com.delphix:bookmark_written     inactive                                     local
datapool  unsupported@com.delphix:log_spacemap         readonly                                     local
datapool  unsupported@com.delphix:livelist             inactive                                     local

*********************
I try on zfs-0.8.0_371 set properties DISABLE but have:

_~$ zpool set feature@log_spacemap=disabled datapool
cannot set property for 'datapool': property 'feature@log_spacemap' can only be set to 'disabled' at creation time_

Now i rebuild custom 5.4.33 kernel with previous zfs-0.8.0_371 version and pool TANK attached normally (in RW mode). But....

**_How i can do for use stable zfs-0.8.3 without recreate pool TANK as first time ? Another way exists ? Thnx._**

**Comment by rincebrain** [comment]
You can't disable feature flags once they're enabled; you created the pool with all feature flags that the git version supported enabled.

You get to remake your pool or keep running git master.

**Comment by dipol0** [comment]
**rincebrain** 
thnx.
