### ISSUE TITLE
zfs dkms build fails if "awk" is not gawk

### ISSUE THREAD

**Issue by sirn** [openzfs/zfs#10232]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Void Linux
Distribution Version	| rolling
Linux Kernel	| 5.6.5
Architecture	| x86_64-musl
ZFS Version	| 0.8.3
SPL Version	| 0.8.3

### Describe the problem you're observing

When `awk` is not symlinked to `gawk` (e.g. with OpenBSD `lok`), `config.status` will fails with `Segmentation fault`. 

### Describe how to reproduce the problem

1. Install alternative awk implementation, e.g. [lok](https://github.com/dimkr/lok)
2. Symlink `lok` to `/usr/bin/awk`
3. Clean dkms build dir then `dkms build zfs/0.8.3 -k <kernel_version>`

### Include any warning/errors/backtraces from the system logs

```
<snip>
config.status: creating rpm/redhat/zfs-kmod.spec
config.status: creating rpm/redhat/zfs-dkms.spec
config.status: creating rpm/generic/Makefile
config.status: creating rpm/generic/zfs.spec
config.status: creating rpm/generic/zfs-kmod.spec
config.status: creating rpm/generic/zfs-dkms.spec
config.status: creating zfs.release
config.status: creating zfs_config.h
Segmentation fault
```

--------

Normally autoconfig detect and use `gawk` (/usr/bin/gawk) by default if it is present in the system. However, `AC_CONFIG_HEADERS` calls `awk` directly instead of using `$AWK` causing the incorrect binary to be called:

https://github.com/openzfs/zfs/blob/c614fd6e12c0fe2636a82b341e9ab9d150ee3c8a/configure.ac#L43-L46

SEGFAULT is probably lok's bug, but I think `config.status` should be using the detected `$AWK` rather than relying on system-`awk` to be a supported implementation.

**Comment by behlendorf** [comment]
Right, we should be using `$AWK` here.  Though, as you said I don't think that'll resolve the SEGFAULT.  It'd be great if you could identify what `lok` isn't handling correctly.

**Comment by behlendorf** [comment]
We're still using `awk` here but it's unknown if this is still an issue since this issue has only been observed when using `lok`.

**Comment by nabijaczleweli** [comment]
I built current OpenBSD awk and current https://github.com/dimkr/lok, and the results are identical between them, GAWK, and mawk.

**Comment by sirn** [comment]
I just tried again and it looks like this only segfault under lok 6.2 (which was released in 2017). I could confirm ZFS built successfully lok 6.3, so I'm closing this. Thank you!
