### ISSUE TITLE
pool shared between Linux and FreeBSD

### ISSUE THREAD

**Issue by eu41** [openzfs/zfs#10233]
Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| n/a
Linux Kernel	| 5.6.5
Architecture	| amd64
ZFS Version	| 0.8.0-731_g1f043c8be
SPL Version	| 0.8.0-731_g1f043c8be

### Describe the problem you're observing
This pool is shared between FreeBSD and Linux systems for more than 3 years.
This is done using vfs.zfs.check_hostid=0.
Its features are frozen that both systems can use it.

1st disc is sdd (Linux) or ada7 (BSD)
2nd disc is sdf (Linux) or ada0 (BSD)
log and cache are on separate partitions on a SSD:
sdc1/ada6p1
sdc3/ada6p3

zpool status raptor in Linux gives this:

  pool: raptor
 state: ONLINE
status: One or more devices could not be used because the label is missing or
	invalid.  Sufficient replicas exist for the pool to continue
	functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: https://zfsonlinux.org/msg/ZFS-8000-4J
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	raptor      ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdd     ONLINE       0     0     0
	    sdf     ONLINE       0     0     0
	logs	
	  sdc1      ONLINE       0     0     0
	cache
	  ada6p3    UNAVAIL      0     0     0

errors: No known data errors

zpool status raptor in BSD gives this:

  pool: raptor
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: none requested
config:

	NAME         STATE     READ WRITE CKSUM
	raptor       ONLINE       0     0     0
	  mirror-0   ONLINE       0     0     0
	    ada7p1   ONLINE       0     0     0
	    ada0p1   ONLINE       0     0     0
	logs	
	  gpt/slog1  ONLINE       0     0     0
	cache
	  ada6p3     ONLINE       0     0     0

errors: No known data errors

Last week I switched to latest OpenZFS on both systems.
Before that Linux had 0.8.3 and FreeBSD had their stock ZFS.

FreeBSD works just fine, but Linux keeps saying that the cache is unavailable.

I tried to remove it and add it back under both systems using either the partition name, or partition number or partition UUID. Nothing helped.
Any ideas?

Thanks,
Eugen

**Comment by freqlabs** [comment]
Strikes me as odd that the cache shows up as "ada6p3" on Linux. Also interesting that the log device on a different partition on the same SSD is fine.

**Comment by eu41** [comment]
I suspect that things happen differently on the two systems when the pool is imported at boot.
FreeBSD pool import is fast, Linux (with systemd) the import take 15-20 seconds.
On both systems it is done by:
zpool import -c /etc/zfs/zpool.cache -a
