### ISSUE TITLE
zpool iostat appears to hang

### ISSUE THREAD

**Issue by ppokorny** [openzfs/zfs#10245]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	|  7.7.1908
Linux Kernel	| 3.10.0-1062.18.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.3-1
SPL Version	| 0.8.3-1

### Describe the problem you're observing
zpool iostat appears to hang after printing the header

```
capacity     operations     bandwidth 
pool  alloc   free   read  write   read  write
---------------------------------------------------------------------------------------------------------------------------
```

Actually, it's printing an "infinite" number of dash - characters under the headings because the output is a terminal and the columns is less than 42

```
[root@fortknox ~]# stty columns 42
[root@fortknox ~]# zpool iostat
        capacity     operations     bandwidth 
pool  alloc   free   read  write   read  write
----  -----  -----  -----  -----  -----  -----
rpool  1.67G  65.3G      6      0   603K  2.36K
[root@fortknox ~]# stty columns 41
[root@fortknox ~]# zpool iostat
     capacity     operations     bandwidth 
pool  alloc   free   read  write   read  write
---------------------------------------------------------------------------------------------------------------------------
```

### Describe how to reproduce the problem
Set the terminal columns to 41 or less

Run "zpool iostat"

**Comment by ppokorny** [comment]
I have a patch for zpool_main get_namewidth_iostat() which fixes this.

I'm working on forking and creating a pull request.  Or I can just post the patch here in the comments...

**Comment by behlendorf** [comment]
@ppokorny a pull request would be preferred.  Thanks!

**Comment by ppokorny** [comment]
OK.  As a github noob, this is turning out to be trickier than I anticipated.  Getting everything branched off the right head and the commit text formatted correctly.  I'm still expecting I'll get that done because I need to learn.  Here is a (likely tab mangled) patch in-line because it's small.  Wait for the pull request.

### Patch
Fix column width calculation issue when the terminal width is 0
or less than 42.
    
If the terminal width was less than 42, the signed width was set to
a negative number that was then assigned to the unsigned column width
becoming a huge number.

```
diff --git a/cmd/zpool/zpool_main.c b/cmd/zpool/zpool_main.c
index d62a6eb3c..280c61b76 100644
--- a/cmd/zpool/zpool_main.c
+++ b/cmd/zpool/zpool_main.c
@@ -5148,6 +5148,7 @@ print_zpool_script_list(char *subcommand)
 /*
  * Set the minimum pool/vdev name column width.  The width must be at least 10,
  * but may be as large as the column width - 42 so it still fits on one line.
+ * NOTE: 42 is the width of the default capacity/operations/bandwidth output
  */
 static int
 get_namewidth_iostat(zpool_handle_t *zhp, void *data)
@@ -5159,10 +5160,10 @@ get_namewidth_iostat(zpool_handle_t *zhp, void *data)
 	    cb->cb_verbose);
 	columns = get_columns();
 
+	if (columns > 42+10 && width > columns - 42)
+		width = columns - 42;
 	if (width < 10)
 		width = 10;
-	if (width > columns - 42)
-		width = columns - 42;
 
 	cb->cb_namewidth = width;
 
```
