### ISSUE TITLE
ZFS crash with  Kernal: General Pretction Fault 

### ISSUE THREAD

**Issue by yingfengli** [openzfs/zfs#10258]
Type | Version/Name
-- | --
Distribution Name | CentOS 6.10
Distribution Version | CentOS 6.10
Linux Kernel | 2.6.32-754.11.1.el6.x86_64
Architecture | x86_64
ZFS Version | zfs-0.8.3-1. zfs-kmod-0.8.3-1
SPL Version |  

zfs crash and system reboot for 3 times in 4 months. the log as follow:
<img width="874" alt="WechatIMG663" src="https://user-images.githubusercontent.com/4608214/80309192-06979480-8806-11ea-92e8-4d217fe16b0b.png">
<img width="1208" alt="WechatIMG664" src="https://user-images.githubusercontent.com/4608214/80309211-25962680-8806-11ea-8f6b-9ec9d8e69640.png">

**Comment by Zaxmy** [comment]
Cant see anything in those logs that says that ZFS crashed?

**Comment by yingfengli** [comment]
Yes,no obvious evidence . But the server only runs ZFS and NFS service as NAS server with 200T data ,millions of files.  It rebooted 3 times automatically ,and the time for two crash  are  right on the scheduled zfs snapshot time.
