### ISSUE TITLE
Undocumented zpool export option '-F'

### ISSUE THREAD

**Issue by SoongNoonien** [openzfs/zfs#10268]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo
Distribution Version	|  Gentoo Base System release 2.7
Linux Kernel	|  5.4.33-gentoo
Architecture	|  amd64
ZFS Version	|  0.8.3-r0-gentoo
SPL Version	|  0.8.3-r0-gentoo

### Describe the problem you're observing
Dracut exports all pools on shutdown with `zpool export <pool> -F`. The `-F` option isn't documented anywhere neither in the manpage nor in `/usr/lib/dracut/modules.d/90zfs/export-zfs.sh` where it is used. Is this on purpose? 

### Describe how to reproduce the problem
Just export a zpool with `-F` which doesn't produce any errors.

### Include any warning/errors/backtraces from the system logs
There are no error messages.

**Comment by geppi** [comment]
To shed a little light on this option I looked into the source code. It sets a parameter named _hardforce_ which is propagated the callstack down into the function _spa_export_common_ where we find the following comment:

`/* Pool export/destroy
The act of destroying or exporting a pool is very simple.  We make sure there
is no more pending I/O and any references to the pool are gone.  Then, we
update the pool state and sync all the labels to disk, removing the
configuration from the cache afterwards. If the 'hardforce' flag is set, then
we don't sync the labels or remove the configuration cache.*/`

However, I can't tell why dracut doesn't want to sync the lables nor remove the configuration from the cache when exporting.

**Comment by SoongNoonien** [comment]
Thanks for your effort!

> However, I can't tell why dracut doesn't want to sync the lables nor remove the configuration from the cache when exporting.

I think dracut doesn't remove the configuration from the cache to be able to import the pools on the next start with the old cache again.
