### ISSUE TITLE
Cannot `zfs recv` raw incremental encrypted stream after snapshot on destination

### ISSUE THREAD

**Issue by wxcafe** [openzfs/zfs#10275]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10.0
Linux Kernel	| 4.19.0-8-amd64
Architecture	| amd64
ZFS Version	| 0.8.3-1~bpo10+1
SPL Version	| 0.8.3-1~bpo10+1

### Describe the problem you're observing

zfs cannot receive a raw incremental encrypted stream, if there's been a snapshot taken on the destination since the last snapshot was received. Here's a session showing it works on unencrypted datasets but not on encrypted datasets:

```
$ sudo zfs create -o mountpoint=/media pool1/dataset           
$ sudo truncate -s 1G /media/file1
$ sudo zfs snap pool1/dataset@origin-1
$ sudo zfs send -w pool1/dataset@origin-1 | sudo zfs recv pool2/dataset
$ sudo zfs snap pool2/dataset@destination-1
$ sudo zfs snap pool1/dataset@origin-2
$ sudo zfs send -w -i @origin-1 pool1/dataset@origin-2 | sudo zfs recv pool2/dataset
$ sudo zfs list -t snap pool2/dataset
NAME                          USED  AVAIL     REFER  MOUNTPOINT
pool2/dataset@origin-1          0B      -       24K  -
pool2/dataset@destination-1     0B      -       24K  -
pool2/dataset@origin-2          0B      -       24K  -
$
$ sudo zfs destroy -r pool1/dataset
$ sudo zfs destroy -r pool2/dataset
$
$ sudo zfs create -o encryption=on -o keyformat=passphrase -o mountpoint=/media pool1/dataset
Enter passphrase: 
Re-enter passphrase: 
$ sudo truncate -s 1G /media/file1                                               
$ sudo zfs snap pool1/dataset@origin-1                                           
$ sudo zfs send -w pool1/dataset@origin-1 | sudo zfs recv pool2/dataset
$ sudo zfs snap pool2/dataset@destination-1                            
$ sudo zfs snap pool1/dataset@origin-2     
$ sudo zfs send -w -i @origin-1 pool1/dataset@origin-2 | sudo zfs recv pool2/dataset
cannot receive incremental stream: destination pool2/dataset has been modified
since most recent snapshot
$
```

This seems similar to #8758 but it's not the same error and not exactly the same situation, so I thought it ought to be a new issue

### Describe how to reproduce the problem

As demonstrated in the session above, create a dataset with encryption enabled, make a snapshot, send that, make a snapshot of the received dataset, make a new snapshot on the source, and try to send this (incrementally)

### Include any warning/errors/backtraces from the system logs

Nothing, this doesn't crash or anything

**Comment by johnnyjacq16** [comment]
Try doing the zfs send/recv with this command:
`sudo zfs send -w -i @origin-1 pool1/dataset@origin-2 | sudo zfs recv -F pool2/dataset`

**Comment by wxcafe** [comment]
hey @johnnyjacq16. Tried this, it receives but destroys the pool2/dataset@destination1 snapshot (which shouldn't be necessary, as shown with the non-encrypted dataset above)

**Comment by johnnyjacq16** [comment]
zfs send/recv is a one way synchronization, hence zfs send/recv is referred to as zfs replication.
It is not a two way synchronization.

**Comment by wxcafe** [comment]
I know, like I said the receiving side loses the snapshot taken on that receiving side. Please re-read the text of my issue, this works with unencrypted raw incremental streams and has nothing to do with two-way sync

**Comment by johnnyjacq16** [comment]
if you want to keep the snapshot @destination-1
when you create a snapshot on the receiving (pool2) end.
`$ sudo zfs snap pool2/dataset@destination-1`

you should send that snapshot back. send the pool2 snapshot back to pool1.
`sudo zfs send -w -i  pool2/dataset@origin-1 pool2/dataset@destination-1 | sudo zfs recv -F pool1/dataset ` .
Then send after the send/recv is completed create the `$ sudo zfs snap pool1/dataset@origin-2 `snapshot and send it to pool2.
`sudo zfs send -w -i pool1/dataset@destination-1 pool1/dataset@origin-2 | sudo zfs recv -F pool2/dataset`

**Comment by wxcafe** [comment]
that is still not the problem. as you can see, sending an incremental snapshot based on a snap that's not the latest on the destination works fine on unencrypted datasets and should work on encrypted datasets too

**Comment by ElvishJerricco** [comment]
Considering this is possible with unencrypted datasets, I don't see why it shouldn't be possible for encrypted datasets. Can anyone provide some insight as to why this error is thrown?

**Comment by ElvishJerricco** [comment]
Well here's a small explanation in the comments: https://github.com/openzfs/zfs/blob/a631283b745efc8354ad680b3a3c1f7bff38c4f8/module/zfs/dmu_recv.c#L428-L435

#8758 does appear to be the same issue, but before c08c30e was committed.

Is this strictly required, or could it be worked around? One use case is using something like syncoid to replicate a dataset, then using sanoid on the destination to maintain a snapshot history independent of the source.

/cc @tcaputi
