### ISSUE TITLE
send/receive failed with encrypted dataset

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#10284]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Manjaro
Distribution Version	|  Testing
Linux Kernel	|  5.6.10
Architecture	|  x86
ZFS Version	|  0.8.0-753_g6ed4391da
SPL version | 0.8.0-753_g6ed4391da

### Describe the problem you're observing

I am sending/receiving an encrypted and compressed dataset  and get an error at the end:

```
zfs send -w -v zM2Home/home/virtualbox@2020-05-02--14:03 | zfs receive -F -v zstore/data/BACKUP/rakete_home/virtualbox
...
06:34:47    302G   zM2Home/home/virtualbox@2020-05-02--14:03
06:34:48    302G   zM2Home/home/virtualbox@2020-05-02--14:03
06:34:49    303G   zM2Home/home/virtualbox@2020-05-02--14:03
06:34:50    303G   zM2Home/home/virtualbox@2020-05-02--14:03
snap zstore/data/BACKUP/rakete_home/virtualbox@2020-05-02--14:03 already exists; ignoring
cannot receive: failed to read from stream
```
When I do the send without `-w` it works fine without error. 

I have another smaller encrypted dataset which has no issues with `-w`. That makes me believe that either the size of the dataset is an issue or the dataset itself has an issue.

The received size of 303G is the original size of the dataset:

```
17# zfs list zM2Home/home/virtualbox zstore/data/BACKUP/rakete_home/virtualbox
NAME                                        USED  AVAIL     REFER  MOUNTPOINT
zM2Home/home/virtualbox                     303G   459G      303G  legacy
zstore/data/BACKUP/rakete_home/virtualbox   303G  1,21T      303G  /data/BACKUP/rakete_home/virtualbox
```

But the mountpoint is wrong on the received dataset. It should be `legacy` on the receiving side. 
And the value for `keylocation` is wrong on the received dataset either. Should be a keyfile but is set to `prompt` instead.

When I change keylocation and mountpoint on the received dataset I can mount it. And when I compare sender and receiver with `rsync -aAxXhHvn` I see no difference between both datasets. That tells me that the file transfers have been completed. But the job failed at the end with setting the dataset attributes. And again, this only happens with `-w`.

**Comment by rincebrain** [comment]
send -w does not imply -p or-R, which would be required for persisting dataset properties across a send/recv.

**Comment by mabod** [comment]
This has nothing to do with it.
I tried
```
zfs send -w -R
zfs send -w -I
zfs send -w -i
zfs send -i
zfs send 
```

and on the receiving side I destroyed the dataset upfront, including -r. And I used `zfs receive -F` anayways. The result was always the same: it fails as soon as `-w` is used.

**Comment by mabod** [comment]
I verified the issue with a different encrypted pool of 510 GB size. Same issue.

**Comment by mabod** [comment]
I tested again with zfs 0.8.4. The issue is gone. No more error messages. Clean send/receive . I am closing this issue.
