### ISSUE TITLE
Prevent unexpected destroy of dataset

### ISSUE THREAD

**Issue by Fmajor** [openzfs/zfs#10289]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	| 20.20
Linux Kernel	| 5.4.0
Architecture	| amd64
ZFS Version	| zfs-0.8.3-1ubuntu12
SPL Version	| zfs-0.8.3-1ubuntu12

### Describe the problem you're observing
I am a new user for zfs, today i'm playing with the `zfs` commands to create, destroy and send zfs snapshot. I find it really dangerous to type `zfs destroy -r pool/dataset@blabla`, if i have some typo and press enter in advance, with `zfs destroy -r pool/dataset`, then I will lose all my data and have no way to recover it. I share will be very careful, but create and destroy snapshots are frequent operations, If you do this a lot, you may type too quick and make mistakes(e.g., with auto-complete of dataset names or old commands).

my cuurent workaround is always keep an additional snapshot for every dataset with 'hold' flag. Then I can not destroy it accidentally.

I have these new feature requests to solve this problem.
* add new params to constrain the action of zfs destroy, like `zfs destroy -t snapshot`, which will ONLY destroy snapshots

or 

* since we can HOLD a snapshot, also add HOLD flag to a dataset. We can not destroy a dataset with HOLD flag.

Any new feature can prevent unexpected destroy of dataset

**Comment by GregorKopka** [comment]
A hold on a snapshot protects a dataset from destruction.

You can also type the -r at the end of the command, after you checked the rest for being correct. Or use -vn to see what would happen. IMHO not an issue.

**Comment by Fmajor** [comment]
Now I always create a @init snapshot with hold flag when create new datasets
Type the -r at the end of the command is a good suggestion.
Thanks
