### ISSUE TITLE
cannot compile zfs.git -  fatal error: sys/socket.h: No such file or directory

### ISSUE THREAD

**Issue by georgeabr** [openzfs/zfs#10285]
debian sid 64bit

./include/linux/if.h:28:10: fatal error: sys/socket.h: No such file or directory
   28 | #include <sys/socket.h>   /* for struct sockaddr.  */
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:268: /home/george/Downloads/zfs/module/icp/api/kcf_digest.o] Error 1
  CC [M]  /home/george/Downloads/zfs/module/spl/../os/linux/spl/spl-kmem-cache.o
  CC [M]  /home/george/Downloads/zfs/module/spl/../os/linux/spl/spl-kstat.o
In file included from ./include/linux/compat.h:16,
                 from ./arch/x86/include/asm/ftrace.h:74,
                 from ./include/linux/ftrace.h:21,
                 from ./include/linux/perf_event.h:49,
                 from ./include/linux/trace_events.h:10,
                 from ./include/trace/syscall.h:7,
                 from ./include/linux/syscalls.h:85,
                 from /home/george/Downloads/zfs/include/os/linux/spl/sys/vnode.h:29,
                 from /home/george/Downloads/zfs/include/os/linux/spl/sys/sunddi.h:32,
                 from /home/george/Downloads/zfs/include/sys/zfs_context.h:57,
                 from /home/george/Downloads/zfs/module/icp/api/kcf_mac.c:26:

i use this command:
```
./configure --with-linux=/usr/src/linux-headers-5.6.8/ && make -j12 && sudo checkinstall
```

**Comment by gdevenyi** [comment]
You completely ignored the issue template

**Comment by georgeabr** [comment]
.
