### ISSUE TITLE
Can't specify host in zfs set sharenfs

### ISSUE THREAD

**Issue by aarrpp** [openzfs/zfs#1029]
zfs set sharenfs="rw,no_root_squash,no_subtree_check,async" backups
ok

zfs set sharenfs="192.168.1.1(rw,no_root_squash,no_subtree_check,async)" backups
cannot set property for 'backups/': 'sharenfs' cannot be set to invalid options

In /etc/exports  string
/backups  192.168.1.1(rw,no_root_squash,no_subtree_check,async) 
works without problems

**Comment by brouhaha** [comment]
It is just a matter of documentation, but it doesn't look like FransUrbo's zfs.8 patch to improve the documentatoin has been merged. I was having trouble until I found it. Would be nice to get merged.
