### ISSUE TITLE
zfs list sorting by createtxg

### ISSUE THREAD

**Issue by mheubach** [openzfs/zfs#10297]
Hi there,

sorry if this is perhaps the wrong place for my question:

Is createtxg a 64bit value? I use this value in order to sort snapshots for incremental replication. This won't be a problem for the next coming years, I think - but perhaps will be at some day in the future.

With 1000 datasets and snapshots (cleaned up automatically) every 15 Minutes this will result in 4000 TXGs per hour? Am i right here? What else does create TXGs on existing datasets? With 4000 TXGs per hour a 64bit value will suffice for 526 billion years (2^64 / 4000 / 24 / 365 - if my maths are correct). So no need to worry here.

But anyway: is there any chance the value createtxg will overflow and start from zero again? And if so - will sorting by createtxg  break?

Best regards
Manfred

**Comment by ahrens** [comment]
> Is createtxg a 64bit value? 

the TXG is a 64-bit value.  It is assumed to not overflow (which as you saw from your calculations is reasonable). 

> With 1000 datasets and snapshots (cleaned up automatically) every 15 Minutes this will result in 4000 TXGs per hour?

Depends on how the snapshots are created.  You can assume at least one TXG per `zfs` command that modifies on-disk state.  So if you are serially doing `zfs snapshot fs@snap; zfs snapshot fs2@snap; ... 1000x`, there will be at least 1000 txg's.  But if you do `zfs snapshot -r fs@snap`, that might only require 1 txg.
