### ISSUE TITLE
zpool replace --> no such device in /dev

### ISSUE THREAD

**Issue by metalolf** [openzfs/zfs#10301]
Hi Folkz,

i've installed a fresh Ubuntu 20.04 LTS and imported my pool into this. After a short while one disk crashed. Now, that I'm trying to replace it, I'm facing an issue here:

```
sudo zpool status
  pool: fourbays
 state: DEGRADED
status: One or more devices has been taken offline by the administrator.
	Sufficient replicas exist for the pool to continue functioning in a
	degraded state.
action: Online the device using 'zpool online' or replace the device with
	'zpool replace'.
  scan: scrub repaired 0B in 0 days 01:15:49 with 0 errors on Sat Apr 11 23:39:50 2020
config:

	NAME                      STATE     READ WRITE CKSUM
	fourbays                  DEGRADED     0     0     0
	  raidz1-0                DEGRADED     0     0     0
	    sdb                   ONLINE       0     0     0
	    sdc                   ONLINE       0     0     0
	    12186307818742867296  OFFLINE      0     0     0  was /dev/sde2
	    sda                   ONLINE       0     0     0

errors: No known data errors
````
````
sudo zpool replace fourbays 12186307818742867296
cannot open '12186307818742867296': no such device in /dev
must be a full path or shorthand device name
``````

I've tried several spare disks (thought the new one might not be sufficient) but always running into the same issue not being able to replace (nor attach & detach) any new drives ...

**Comment by rincebrain** [comment]
I would guess that you need to specify both old and new device because it's no longer displaying the old device name, and it can't be sure that the name wouldn't have changed since the device was last in the pool. So something like "zpool replace fourbays 12186307818742867296 sde" would probably work, though you'd obviously want to verify which drive it is.

attach and detach are only commands that work for mirror vdevs.

**Comment by metalolf** [comment]
Thx @rincebrain 🙏

> So something like "zpool replace fourbays 12186307818742867296 sde" would probably work

Of course I tried that several times with the same output.
Nevertheless, after some hours of sleep and a fresh brewed coffee in the morning replacement was successful! 🤷‍♂️

Thanks again and have a nice weekend!
