### ISSUE TITLE
dsl_scan_iss, 100 % blocked IO, gcc 10, kernel 5.6.11

### ISSUE THREAD

**Issue by poige** [openzfs/zfs#10312]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| doesn't matter ZoL compiled from sources (latest -dev ATM)
Distribution Version	| 
Linux Kernel	| 5.6.11
Architecture	| x86_64
ZFS Version	| 6ed4391da97a1d183dbabcbe667026deb6678612
SPL Version	| hm? it's same codebase for long now, isn't it?

Subject says it all. I was able to `zfs export -a` that did work not instantly but finally did the thing.

No idea how and when it has been triggered though.

P. S. I'm seeking no help, just letting know that I've seen that kind of issue.

**Comment by poige** [comment]
Seemingly it's related to some other bug: I had 2 pools on a SSD's partition each that being `import`ed and `scrub`bed _simultaneously_ failed with tens of csum errors, but if I `import`-`scrub` them 1-by-1 it goes ok.

Latest ZoL ATM: 7fcf82451c4b75afe327c77683f66bf0c6396a48
5.6.12 w/ "voluntary preemption" this time.

**Comment by poige** [comment]
and finally seems that blocking NCQ for the SSD drive in questions resolves that completely.

**Comment by malventano** [comment]
> and finally seems that blocking NCQ for the SSD drive in question resolves that completely.
> 
> kernel's arg += `libata.force=2.00:noncq`

In my experience, if scrubs aren't bandwidth-limited they will run up against a thread limit (dsc_scan_iss pegs a core). If you disabled queueing, it likely significantly reduced your scrub speed, since you shifted back to a throughput limit, the scan thread would no longer peg a core.

**Comment by poige** [comment]
Eventually I updated SSD's firmware and reverted those changes. Didn't test if the issue persists though.
