### ISSUE TITLE
CentOS 8.1 FATAL: Module zfs not found after fresh install

### ISSUE THREAD

**Issue by gatamah** [openzfs/zfs#10318]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 8.1.1911
Linux Kernel	| 4.18.0
Architecture	| x86_64
ZFS Version	| 8.3
SPL Version	| 8.3

### Describe the problem you're observing
After installing zfs-kmod and rebooting `modprobe zfs` produces the error  `modprobe: FATAL: Module zfs not found in directory /lib/modules/4.18.0-193.10.el8.x86_64`

### Describe how to reproduce the problem
- Install fresh Centos 8.1
- run `dnf update` to upgrade system
- Install zfs repo
- Switch to zfs-kmod repo
- run `dnf install zfs`
- reboot
- run `modprobe zfs` produces the error below. 

### Include any warning/errors/backtraces from the system logs

```
# uname -r
4.18.0-193.10.el8.x86_64
```

```
# modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.18.0-193.10.el8.x86_64
```

However, after rebooting into the older kernel, it works.
```
# uname -r
4.18.0-151.el8.x86_64
```
```
# modprobe zfs

# lsmod | grep zfs
zfs                  4202496  0
zunicode              335872  1 zfs
zlua                  172032  1 zfs
zcommon                94208  1 zfs
znvpair                90112  2 zfs,zcommon
zavl                   16384  1 zfs
icp                   311296  1 zfs
spl                   126976  5 zfs,icp,znvpair,zcommon,zavl
```

**Comment by tonyhutter** [comment]
> # uname -r
> 4.18.0-193.10.el8.x86_64

Centos 8.1 uses the kernel-4.18.0-147.  Are you by chance using the RHEL 8.2 kernel?

Also, we just upgraded to zfs-0.8.4 today.  Can you try a yum update and see if that works?

**Comment by gatamah** [comment]
Thanks. Reinstalled CentOS 8 and it is working.
