### ISSUE TITLE
Fedora 32 has been released and it would be nice to have DKMS packages available for it

### ISSUE THREAD

**Issue by plevart** [openzfs/zfs#10316]
Maybe for next release 0.8.4? Thanks!

**Comment by mskarbek** [comment]
This was already reported for example in this issue: https://github.com/openzfs/zfs/issues/10257.
Support will be added in 0.8.4 and you can follow the progress here: https://github.com/openzfs/zfs/pull/10209.

**Comment by tonyhutter** [comment]
0.8.4 was released today:
```
yum install http://download.zfsonlinux.org/fedora/zfs-release.fc32.noarch.rpm
yum install zfs
```

**Comment by plevart** [comment]
Great. Thanks for developing this wonderful filesystem.
