### ISSUE TITLE
ZTS failure in zvol_misc/zvol_misc_volmode using loopback devices

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#10336]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| unstable
Linux Kernel	| 5.4, 5.6 (probably more)
Architecture	| amd64
ZFS Version	| 0.8.4

### Describe the problem you're observing

`zvol_misc/zvol_misc_volmode` fails if you try to run the full test suite using loopback devices.

This kicks off a cascade that results in `zvol_misc/zvol_misc_zil` also failing.

### Describe how to reproduce the problem

Run the `write_dirs` test and then the `zvol_misc/zvol_misc_volmode` test using loopback devices.

Alternatively, you can do this by hand:

    % truncate -s 512M /tmp/loopdev
    % losetup loop0 /tmp/loopdev
    % parted /dev/loop0 -s -- mklabel gpt
    % parted /dev/loop0 -s -- mkpart part0 10cyl 200cyl
    Warning: The resulting partition is not properly aligned for best performance: 5100s % 2048s != 0s

Ok, we've got a partition set up:

    % ls /dev/loop0*
    loop0 loop0p1

Now, create the pool:

    % zpool create testpool loop0
    % zpool export testpool
    % zpool import testpool
    cannot import 'testpool': no such pool available

"Why can't we import the pool?!"

What does the kernel think the partition table looks like?

    % ls /dev/loop0*
    /dev/loop0 /dev/loop0p1

But what does it actually look like?

    % partprobe /dev/loop0
    % ls /dev/loop0*
    /dev/loop0

And so, it works:

    % zpool import testpool

Maybe a hint is that `blockdev --rereadpt` fails on loopback devices:

**EDIT**: Ugh. I copied the wrong line. This is wrong:

    % blockdev --rereadpt /dev/loop0
    blockdev: ioctl error on BLKRRPART: Device or resource busy

This is what actually happens:

    % blockdev --rereadpt /dev/loop0
    blockdev: ioctl error on BLKRRPART: Invalid argument

This affects the ZTS infrastructure, since `blockdev --rereadpt` is used there. I haven't dug into the `zpool create` code, but is it possible that a similar call is being used there to update the kernel's partition table?

### Discussion

I see two ways to resolve this:

1. Add code in the tests to `partprobe` after `zpool create` pools that we plan on exporting and then re-importing.

2. Add code in `zpool create` to properly update the kernel partition information after `zpool create`-ing.

I have a patch that does 1, but 2 didn't occur to me until I had already written it.

**Comment by behlendorf** [comment]
This looks like the critical bit.

```
% blockdev --rereadpt /dev/loop0
blockdev: ioctl error on BLKRRPART: Device or resource busy
```

We actually already [have code](https://github.com/openzfs/zfs/blob/master/lib/libzfs/os/linux/libzfs_pool_os.c#L304) in `zpool create` which is used to rescan and update the partition tables.  However it relies on `BLKRRPART` to get the job done and we suppress any errors messages caused by an `EBUSY` because they are usually transient and we retry.  Which is unfortunately why no error was logged.  Apparently we can't count on it eventually succeeding.

I think it would be best if we could fix this in `zpool create`, but if `BLKRRPART` fails on loopback devices I'm curious what `partprobe` uses instead?

**Comment by aerusso** [comment]
@behlendorf Please see my edit (I incorrectly copied something from the terminal---the error from blockdev is `Invalid argument`).

> I'm curious what partprobe uses instead?

A real cursory inspection of `libparted/disk.c`

```c
/**
 * Tell the operating system kernel about the partition table layout
 * of \p disk.
 *
 * This is rather loosely defined: for example, on old versions of Linux,
 * it simply calls the BLKRRPART ioctl, which tells the kernel to
 * reread the partition table. On newer versions (2.4.x), it will
 * use the new blkpg interface to tell Linux where each partition
 * starts/ends, etc. In this case, Linux does not need to have support for
 * a specific type of partition table.
 *
 * \return 0 on failure, 1 otherwise.
 */
int
ped_disk_commit_to_os (PedDisk* disk)
```

and `libparted/arch/linux.c`

```c
/*
 * Sync the partition table in two step process:
 * 1. Remove all of the partitions from the kernel's tables, but do not attempt
 *    removal of any partition for which the corresponding ioctl call fails.
 * 2. Add all the partitions that we hold in disk, throwing a warning
 *    if we cannot because step 1 failed to remove it and it is not being
 *    added back with the same start and length.
 *
 * To achieve this two step process we must calculate the minimum number of
 * maximum possible partitions between what linux supports and what the label
 * type supports. EX:    
 *
 * number=MIN(max_parts_supported_in_linux,max_parts_supported_in_msdos_tables)
 */   
static int
_disk_sync_part_table
```

Shouldn't `BLKRRPART` work on a loopback device? This sounds like a kernel bug, right? A freshly created loopback device fails with `blockdev --rereadpt /dev/loop0` as well:

    blockdev --rereadpt /dev/loop0
    blockdev: ioctl error on BLKRRPART: Invalid argument

**Comment by behlendorf** [comment]
> Shouldn't BLKRRPART work on a loopback device? This sounds like a kernel bug, right?

Personally I'd think so.  But if `BLKRRPART` really is a legacy interface as indicated by those partprobe comments there may not be much interest in fixing this in the kernel.

Your comment reminded me that for loopback devices ZFS already never creates a partition table.  So any existing partition table would lead to import issues, particularly if we can't force them to be reread.

An alternate solution to what you originally proposed could be to update the ZTS to never manually partition loopback devices.  I'd think this would avoid the issue entirely but I haven't done any testing.  Plus it has the advantage that we've already started systematically removing this kind of unnecessary partitioning from the test suite, #9995, #9996, #10002, #10036, #10060.  It looks like there's aren't too many more test groups to update.

**Comment by aerusso** [comment]
As of 2.0.1, the underlying issue here is still reproducible, but the ZTS has been modified enough that I am not getting these failures anymore.  I will leave it to someone else's judgment if this bug report should be closed or not.
