### ISSUE TITLE
Should #9749 improve GCM performance on arm64?

### ISSUE THREAD

**Issue by lightrush** [openzfs/zfs#10347]
In the #9749 PR I see that the new asm implementation is conditional on x86_64. I tested GCM on a Raspberry Pi 4 (arm64) with 0.8.3 and 0.8.4, and don't see any significant difference in speed.

Should #9749 improve GCM performance on arm64?

**Comment by AttilaFueloep** [comment]
No, unfortunately not. Only x86_64 architectures supporting the AVX, AES-NI and PCLMULQDQ
extensions will benefit from #9749 .

**Comment by lightrush** [comment]
Thanks for the confirmation. That's good to know for people using ZFS on ARM. 

For some reason, CCM seems to perform significantly faster than GCM on the Pi 4. 256 bit CCM is in the 60-80MB/s range whereas GCM is in the 30-40MB/s range. Is there any contraindication to using CCM?

**Comment by AttilaFueloep** [comment]
The differences between CCM and GCM are briefly discussed in the [PR](https://github.com/openzfs/zfs/pull/9749#issuecomment-569132997). In short, there is no strong contradiction and CCM was the default algorithm until #9749 was merged.

What's a bit surprising is the fact that CCM is faster than GCM on the Pi 4, usually it's the other way around. I would assume that the Pi 4 has hardware acceleration for AES but not for carry-less quadword multiplication (PCLMULQDQ), making the AES operation considerably faster than the GHASH calculation.

**Comment by lightrush** [comment]
Thank you. I think that covers it. Closing.
