### ISSUE TITLE
Mountpoints can become "tangled", preventing zpool destroy 

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#10340]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	| unstable
Linux Kernel	| 5.4, 5.5, 5.6
Architecture	| amd64
ZFS Version	| 0.8.4

### Describe the problem you're observing

`zpool destroy` command will sometimes fail on the first run, complaining of `umount: ... no mount point specified` (but will succeed after sufficient repetitions).  This particular bug also causes `zfs unmount -a` to fail on Linux 5.5 and 5.6.  It was generated from a reduction of a ZTS rsend failure (`rsend_007_pos`) I am seeing on Linux 5.5 and 5.6 (notice that this reproducer also causes strange unmount behavior on 5.4, where the rsend test did not fail).

### Describe how to reproduce the problem

```sh
mkdir /tmp/x
truncate -s 512M /tmp/x/loopdev0
losetup loop0 /tmp/x/loopdev0
zpool create testpool loop0
zfs snapshot testpool@A
zfs clone testpool@A testpool/clone
zfs snapshot -r testpool@B
zfs snapshot -r testpool@C
zfs rename testpool/clone testpool/moved
zfs send -R -I @B testpool@C >/tmp/x/BC
zfs destroy testpool@C
zfs destroy testpool/moved@C
zfs receive -d -F testpool </tmp/x/BC
```

### Include any warning/errors/backtraces from the system logs

Then, run `zpool destroy testpool`:

```
umount: /testpool/moved: no mount point specified.
cannot unmount '/testpool/moved': umount failed
could not destroy 'testpool': could not unmount datasets
```

### Discussion

I've experienced bugs like this before, but didn't bother to get a clean reproducer until now.  My biggest concern is that this bug may mask problems in the ZTS suite. 

Is the best immediate mitigation replacing the `zpool destroy` commands in the ZTS with the more robust `destroy_pool` command, and adding this reproducer to the test suite?

**Comment by johnnyjacq16** [comment]
Could you try to export the pool first then destroying it.
So first run:
`zpool export testpool`
To ensure that the pool got exported run:
`zpool list`
The name of the pool should not show up.
then
`zpool destroy testpool`.

To specify a mountpoint run command:
`zfs set mountpoint=<options> testpool<your dataset>`
your mountpoint options are:

1. legacy
2. specifying a location like /mnt
3. none
Example `zfs set mountpoint=/mnt testpool/moved` to set a mountpoint.

**Comment by aerusso** [comment]
The issue is really that the ZTS system expects `zfs destroy -Rf $poolname` to clear out all the datasets and snapshots.  This causes `rsend_007_pos` to fail.

It's not hard to actually get it to unmount: just try a few times, each time it will unmount more, and then eventually be clean.
