### ISSUE TITLE
zfs rollback silently rolls back to another state

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#10354]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| unstable
Linux Kernel	| 5.6.0-1
Architecture	| amd64
ZFS Version	| 0.8.4
SPL Version	| 

### Describe the problem you're observing
During a bisection of a completely unrelated problem, I would `zfs rollback pool/dataset@snapshot` to an understood state.  At some point during the bisection process, the state achieved after `zfs rollback pool/dataset@snapshot` changed--- `~/.config` went from being populated with many entries to being empty. I suspect that during the process, the rollback was not restoring files that I was deleting from this directory, but I cannot be certain.

The task I was performing during the bisect was simply: logging in, delete some files, starting a desktop session (KDE), and then `systemctl stop user-${uid}.slice`.

At the end, I was unable to rm the `~/.config` directory--it claimed to be nonempty (but `ls -a` showed nothing). I rebooted the machine, and the files in `~/.config` returned. If `zfs diff` is to be trusted, the state of the dataset was  rolled back to the snapshot.

Other datasets appear unaffected.  Rollback is functioning as normal after the reboot.

### Describe how to reproduce the problem

I do not have a reproducer for this.

### Include any warning/errors/backtraces from the system logs

There were no `dmesg` events during the process, and outside of the period is innocuous.

`journalctl` is superficially uninteresting.

The reboot occurred cleanly---no difficulty unmounting the dataset.

**Comment by ahrens** [comment]
This is potentially related to 7ae3f8dc8f1e075108f91ddf6fb16471d4a0f044 / 5a6ac4cffcd0255ca6f730bcf356e12891fd18af, neither of which are present in 0.8.4.
