### ISSUE TITLE
Can't mount smb-share of zfs datasets

### ISSUE THREAD

**Issue by riedinger** [openzfs/zfs#10350]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS Linux release 8.1.1911 (Core)
Distribution Version	| CentOS Linux release 8.1.1911 (Core)
Linux Kernel	|  4.18.0-147.8.1.el8_1.x86_64 CentOS 8.1
Architecture	| x86_64
ZFS Version	|  0.8.4-1
SPL Version	|  0.8.4-1

I'm not sure, if this is a ZFS or Samba issue. I open the issue here, because I think for Samba there should be no difference for the zfs datasets defined by me. The same strange issue was already described on the Samba mailing list, see https://lists.samba.org/archive/samba/2018-January/213095.html two years ago.

I have only 1 ZFS dataset, which is handled by smbd as expected, all others can't be mounted although the ZFS configuration and permissions are almost identical.

For the demonstration of the issue I have written a shell script. You find the output of the script, if it was executed by sh -x below.

At first the script shows that the Samba configuration. At next the configuration of my ZFS datasets zfspool1/subpool1 and zfspool1/subpool2 are compared. IMHO there is no relevant difference.

zfspool1/subpool1 can be mounted via smbd, whereas the mouting of zfspool1/subpool2 fails, if smbd is started as system service. zfspool1/subpool2 can be mounted, if I start smbd  manually.  

I attach the log file with the output of smbd with debug level 10 during a failed mount attempt.
[smbd-debug-output-during-failed-mount-attempt.log](https://github.com/openzfs/zfs/files/4653418/smbd-debug-output-during-failed-mount-attempt.log)

```
############## SOFTWARE VERSIONS
+ sambastatus --version
bug-demonstration.sh: line 2: sambastatus: command not found
+ modinfo zfs
+ grep version
version:        0.8.4-1
rhelversion:    8.1
srcversion:     E9712003D310D2B54A51C97
vermagic:       4.18.0-147.8.1.el8_1.x86_64 SMP mod_unload modversions
############## SAMBA CONFIG
+ cat /etc/samba/smb.conf
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.

[global]
        workgroup = WORKGROUP
        security = user

        passdb backend = tdbsam

        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw

... some shares are ommitted 
[backup]
        comment = Backup for xps15
        path = /export/backup
        guest ok = no
        read only = No
        inherit acls = Yes
############## COMPARISION OF ZFS DATASETS

+ zfs list
NAME                USED  AVAIL     REFER  MOUNTPOINT
zfspool1           7.43T  2.81T      145K  none
zfspool1/subpool1  4.95T  2.81T     4.95T  /export
zfspool1/subpool2  2.48T  2.81T     2.48T  /export
+ zfs get all zfspool1/subpool1
+ sed -e s#zfspool1/subpool1#zfspool1/subpoolX# -e 's/  */ /g'
+ zfs get all zfspool1/subpool2
+ sed -e s#zfspool1/subpool2#zfspool1/subpoolX# -e 's/  */ /g'
+ diff /tmp/attr-subpool1 /tmp/attr-subpool2
3,4c3,4
< zfspool1/subpoolX creation Tue Feb 11 3:42 2020 -
< zfspool1/subpoolX used 4.95T -
---
> zfspool1/subpoolX creation Mon May 18 13:38 2020 -
> zfspool1/subpoolX used 2.48T -
6,7c6,7
< zfspool1/subpoolX referenced 4.95T -
< zfspool1/subpoolX compressratio 1.04x -
---
> zfspool1/subpoolX referenced 2.48T -
> zfspool1/subpoolX compressratio 1.00x -
23,24c23,24
< zfspool1/subpoolX aclinherit restricted default
< zfspool1/subpoolX createtxg 138 -
---
> zfspool1/subpoolX aclinherit restricted local
> zfspool1/subpoolX createtxg 1163265 -
26c26
< zfspool1/subpoolX xattr on default
---
> zfspool1/subpoolX xattr on local
37c37
< zfspool1/subpoolX guid 12839993380611087628 -
---
> zfspool1/subpoolX guid 163394889858938217 -
41c41
< zfspool1/subpoolX usedbydataset 4.95T -
---
> zfspool1/subpoolX usedbydataset 2.48T -
45c45
< zfspool1/subpoolX objsetid 269 -
---
> zfspool1/subpoolX objsetid 728 -
50,53c50,53
< zfspool1/subpoolX refcompressratio 1.04x -
< zfspool1/subpoolX written 4.95T -
< zfspool1/subpoolX logicalused 5.16T -
< zfspool1/subpoolX logicalreferenced 5.16T -
---
> zfspool1/subpoolX refcompressratio 1.00x -
> zfspool1/subpoolX written 2.48T -
> zfspool1/subpoolX logicalused 2.48T -
> zfspool1/subpoolX logicalreferenced 2.48T -
60c60
< zfspool1/subpoolX acltype off default
---
> zfspool1/subpoolX acltype off local
69c69
< zfspool1/subpoolX keylocation prompt local
---
> zfspool1/subpoolX keylocation file:///export/private/zfs-key.zfspool1.subpool2_nosnap local
72c72
< zfspool1/subpoolX encryptionroot zfspool1/subpool1 -
---
> zfspool1/subpoolX encryptionroot zfspool1/subpool2 -

############### zfspool1/subpool1 CAN BE HANDLED BY smbd
+ zfs mount zfspool1/subpool1
+ ls -ld /export /export/backup
drwxr-xr-x. 5 root root 5 May 18 13:17 /export
drwxr-xr-x. 6 jan  jan  6 May 19 12:35 /export/backup
+ systemctl restart smb
+ mount -t cifs -o credentials=/home/jan/smb-credentials //localhost/backup /mnt
+ umount /mnt
+ systemctl stop smb
+ zfs umount zfspool1/subpool1

############### zfspool1/subpool2 CAN'T BE HANDLED BY smbd

+ zfs mount zfspool1/subpool2
+ ls -ld /export /export/backup
drwxr-xr-x. 7 root root 7 May 19 20:08 /export
drwxr-xr-x. 2 jan  jan  2 May 19 20:08 /export/backup
+ systemctl start smb
+ mount -t cifs -o credentials=/home/jan/smb-credentials //localhost/backup /mnt
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
+ journalctl -u smb
+ tail -n 15
May 19 22:45:12 kvm3.sns.eu smbd[19139]:   pidfile_create: ERROR: Failed to create PID file /run/smbd.pid (Permission denied)
May 19 22:46:00 kvm3.sns.eu systemd[1]: smb.service: Failed with result 'protocol'.
May 19 22:46:00 kvm3.sns.eu systemd[1]: Failed to start Samba SMB Daemon.
May 19 22:46:16 kvm3.sns.eu systemd[1]: Starting Samba SMB Daemon...
May 19 22:46:16 kvm3.sns.eu smbd[19313]: [2020/05/19 22:46:16.695735,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
May 19 22:46:16 kvm3.sns.eu smbd[19313]:   daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
May 19 22:46:16 kvm3.sns.eu systemd[1]: Started Samba SMB Daemon.
May 19 22:46:16 kvm3.sns.eu systemd[1]: Stopping Samba SMB Daemon...
May 19 22:46:16 kvm3.sns.eu systemd[1]: Stopped Samba SMB Daemon.
May 19 22:46:17 kvm3.sns.eu systemd[1]: Starting Samba SMB Daemon...
May 19 22:46:17 kvm3.sns.eu smbd[19408]: [2020/05/19 22:46:17.762434,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
May 19 22:46:17 kvm3.sns.eu smbd[19408]:   daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
May 19 22:46:17 kvm3.sns.eu systemd[1]: Started Samba SMB Daemon.
May 19 22:46:17 kvm3.sns.eu smbd[19418]: [2020/05/19 22:46:17.781617,  0] ../../source3/smbd/service.c:784(make_connection_snum)
May 19 22:46:17 kvm3.sns.eu smbd[19418]:   make_connection_snum: canonicalize_connect_path failed for service backup, path /export/backup
+ systemctl stop smb
################### IF smbd IS STARTED MANUALLY ALL WORKS FINE
+ smbd -D
+ sleep 5
+ mount -t cifs -o credentials=/home/jan/smb-credentials //localhost/backup /mnt
+ umount /mnt
+ zfs umount zfspool1/subpool2
```

**Comment by devZer0** [comment]
it seems you are trying to share symlinked dirs - could you please try to export the native zfs path via samba and see if it makes a difference ?

i think you need to instruct samba to follow symlinks, see:  https://unix.stackexchange.com/questions/5120/how-do-you-make-samba-follow-symlink-outside-the-shared-path

**Comment by riedinger** [comment]
No, I didn't try to share a symlinked directory. /export/backup specified in smb.conf is a regular subdirectory of the zfs dataset, which I mounted at /export.

Furthermore, the working zfs dataset and the not working zfs dataset were mounted by my issue demonstration shell script at exactly the same mount point.

**Comment by riedinger** [comment]
I tried to export the zfs mount point directly by Samba. I still see the described problem:

Excerpt from my smb.conf:

 
```
[test]
        comment = Backup for xps15
        path = /export
        guest ok = no
        read only = No
        inherit acls = Yes
```

Excerpts from my testing session:
```
[root@kvm3 ~]# zfs list
NAME                       USED  AVAIL     REFER  MOUNTPOINT
zfspool1                  7.81T  2.43T      145K  none
zfspool1/subpool1         5.31T  2.43T     5.03T  /export
zfspool1/subpool2_nosnap  2.50T  2.43T     2.50T  /export
[root@kvm3 ~]# zfs mount zfspool1/subpool1
[root@kvm3 ~]# mount | grep zfs
zfspool1/subpool1 on /export type zfs (rw,seclabel,xattr,noacl)
[root@kvm3 ~]# ls -ld /export
drwxr-xr-x. 7 root root 7 May 23 18:29 /export
[root@kvm3 ~]# mount -t cifs -o credentials=/home/jan/smb-credentials //localhost/test /mnt
[root@kvm3 ~]# umount /mnt
[root@kvm3 ~]# systemctl stop smb
[root@kvm3 ~]# umount /export
[root@kvm3 ~]# zfs mount zfspool1/subpool2_nosnap
[root@kvm3 ~]# systemctl start smb
[root@kvm3 ~]# mount -t cifs -o credentials=/home/jan/smb-credentials //localhost/test /mnt
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[root@kvm3 ~]# mount | grep zfs
zfspool1/subpool2_nosnap on /export type zfs (rw,seclabel,xattr,noacl)
[root@kvm3 ~]# ls -ld /export
drwxr-xr-x. 5 root root 5 May 20 00:18 /export
```

**Comment by krysstof** [comment]
I have the same issue when I switch my NAS from ubuntu 18.04 to centos 8.2 after a system disk failure.
I had a backup of the smb config file and imported my zpool, no issue here, but when trying to mount the shared folder I had the SMB error canonicalize_connect_path failed 

I found a few mailing list with this problem and one said he stopped the service and he ran "/usr/sbin/smbd -D" and the share was accessible. (https://lists.samba.org/archive/samba/2018-January/213095.html)
I tried the same and it works.

The guess is there is an issue with the way systemctl is starting smb but there was no more follow up (from 2018 and 2019)

i'll dig a bit more on the samba side.

**Comment by silvein** [comment]
I have a similar issue, however some of my shares with paths on ZFS storage worked, and some did not.

I was able to determine that shares work if they are shared off of a dataset with a locally set mountpoint, with the parent mountpoint set to none. I'm not sure if this is because inherited mountpoints don't work or if something with Systemd is preventing nested datasets being accessed correctly.

So for example, `tank/samba/share` mounted at `/media/samba/share` would not work if `tank/samba` _mountpoint_ was set to `/media/samba`, but would work if `tank/samba` was set to none, and `tank/samba/share` was set to `/media/samba/share`.

**Comment by riedinger** [comment]
I think silvein probably directs in the right direction. In my original setup the dataset with the problem was configured to be mounted as subdirectory of the other dataset:
```
[root@kvm3 ~]# zfs list
NAME                       USED  AVAIL     REFER  MOUNTPOINT
zfspool1                  6.96T  3.28T      145K  none
zfspool1/subpool1         4.91T  3.28T     4.91T  /export
zfspool1/subpool2_nosnap  2.05T  3.28T     2.05T  /export/data-jan/macrium_reflect_backups
```

**Comment by ebarkie** [comment]
This is likely due to SELinux.  When `smbd` starts under systemd it's using the `system_u:system_r:smbd_t:s0` context whereas when it's manually invoked it's unconfined.  To verify you could see if this fixes it:

```sh
# setsebool -P samba_export_all_rw 1
```

**Comment by riedinger** [comment]
I can confirm that the quick fix of ebarkie is working for me too.

I can mount all of my smb-shares of zfs datasets, even if smbd is started via systemctl after I used
```
 setsebool -P samba_export_all_rw on
 ```

**Comment by shoop** [comment]
Encountered this on very recent CentOS Stream 8. In order to see the Samba SELinux AVC denials, use

     # semodule -DB

This turns off the silent-by-default denies, causing the denials to show up in

    # ausearch -m avc -ts recent

Turns out that I had shared a path underneath a ZFS dataset, *but* Samba apparently always checks up from the root mount point. For example: if the root mount point is ```/path/to/tank```, a dataset is created at ```/path/to/tank/dataset``` and the intent is to create a share for ```/path/to/tank/dataset/share```, then even the ```/path/to/tank``` needs to be labeled as ```samba_share_t```. It does not make sense to me, but here we are.

So be sure to either drop all SELinux protections for Samba by using

    # setsebool -P samba_export_all_rw on

Or, ensure that the labels are correct from the mount point start:

    # semanage fcontext -a -t samba_share_t '/path/to/tank(/.*)?'
    # restorecon -rv /path/to/tank

Hope this helps.

**Comment by deajan** [comment]
I was unable to get this to work on AlmaLinux 8.5 with zfs 2.0.7-1

SMB sharing `/path/share` with securtity context `samba_share_t`
I enabled SELinux boolean `samba_export_all_rw`.

Unless I set SELinux in permissive mode, I get a lot of `type=AVC msg=audit(1646739818.605:3425): avc:  denied  { dac_override } for  pid=19277 comm="smbd" capability=1  scontext=system_u:system_r:smbd_t:s0 tcontext=system_u:system_r:smbd_t:s0 tclass=capability permissive=0`

In the end, my path was owned by `smb_user:root` with permissions 755. Had to set permissions 775 as smbd seems to act as root for permissions.
