### ISSUE TITLE
zpool create on sparc64 produces a pool with inconsistent hostid

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#10352]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	| unstable
Linux Kernel	| 5.6.0-1
Architecture	| sparc64
ZFS Version	| 0.8.4-1

### Describe the problem you're observing
I created a test pool out of 3 files in raidz1, and immediately after creating the pool, zpool status reports:
```
  pool: testsparc
 state: ONLINE
status: Mismatch between pool hostid and system hostid on imported pool.
        This pool was previously imported into a system with a different hostid,
        and then was verbatim imported into this system.
action: Export this pool on all systems on which it is imported.
        Then import it to correct the mismatch.
   see: http://zfsonlinux.org/msg/ZFS-8000-EY
  scan: none requested
config:

        NAME             STATE     READ WRITE CKSUM
        testsparc        ONLINE       0     0     0
          raidz1-0       ONLINE       0     0     0
            /root/test1  ONLINE       0     0     0
            /root/test2  ONLINE       0     0     0
            /root/test3  ONLINE       0     0     0
```

Exporting and importing the pool does not, in fact, change this.

Interestingly, import doesn't warn that the pool may be in use on another system when tried, it just works.

### Describe how to reproduce the problem
* Create a pool on a sparc64 system
* Execute zpool status

**Comment by nabijaczleweli** [comment]
Does the endianness of the kernel and userland match? I've hypothesised this to be possible on a ppc64le kernel and ppc64 userland, but I'm not sure how you could possibly resolve this tbh.

**Comment by rincebrain** [comment]
This was on real HW that does not support LE at all to the best of my knowledge, so I'm reasonably confident that's not what was going on here.

I'm probably going to close this bug after I get a chance to retest it, because I haven't noticed it with all my playing with sparc64 recently, so I'm guessing whatever quirk caused it has gone away.

**Comment by rincebrain** [comment]
```
# zfs version
zfs-2.1.99-323_g942121cfc
zfs-kmod-2.1.99-323_g942121cfc
# zpool create whatendian raidz1 /tmp/file{1,2,3}
# zpool status whatendian
  pool: whatendian
 state: ONLINE
config:

        NAME            STATE     READ WRITE CKSUM
        whatendian      ONLINE       0     0     0
          raidz1-0      ONLINE       0     0     0
            /tmp/file1  ONLINE       0     0     0
            /tmp/file2  ONLINE       0     0     0
            /tmp/file3  ONLINE       0     0     0

errors: No known data errors
#
```

So "cannot reproduce", I suppose.
