### ISSUE TITLE
Retire the zpool.cache file

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#1035]
I am filing this issue so that the discussion in issue #873 can move here. Anyway, the idea is that we should have a module parameter called zfs_nocachefile such that people could do `echo 'options zfs zfs_nocachefile=1' >> /etc/modprobe.d/zfs.conf` to disable the use of the cachefile when the module is loaded.

**Comment by poscat0x04** [comment]
What is the plan currently? Is the goal of retiring zpool.cache abandoned? I saw no reason given for why this issue is closed as completed.

**Comment by silverhadch** [comment]
I would like to see this deprecated and removed. I even made an AUR Package for Systemd-Based Initrds for Archlinux that packages an sd-zfs hook that hardcoded disables the cache file and boots completly without it.

My Package: https://aur.archlinux.org/packages/mkinitcpio-sd-zfs-poscat
The Wiki Entry: https://wiki.archlinux.org/title/Install_Arch_Linux_on_ZFS#zfs-utils-poscat
