### ISSUE TITLE
put back ZVOL_DIR to zfs.h

### ISSUE THREAD

**Issue by ikozhukhov** [openzfs/zfs#10361]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| DilOS
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing

in this commit https://github.com/openzfs/zfs/commit/d2782af461c62350abb5abe439b57961c72f9cee `ZVOL_DIR` has been moved to FreeBSD only.

we are on DilOS is using "ZVOL_DIR" a lot in different places - will be better revert this change back because it's affect us.
move ZVOL_DIR to original place and change it to:
`#define ZVOL_DIR "/dev/zvol"`

**Comment by freqlabs** [comment]
The value is platform-dependent so I think you should find another place to define it for DilOS.

**Comment by behlendorf** [comment]
Moving this to a common location might be reasonable.  It sounds like Linux, FreeBSD, DilOS, and illumos all use the same location.  We also redundantly declare this same path as `ZVOL_ROOT` in `include/libzutil.h` which ends up only being used on Linux.  But if all platforms do expect the same path keeping this in one place would be nice.

**Comment by freqlabs** [comment]
I wonder why it was defined as just "/dev" before? If it can be "/dev/zvol" everywhere then fantastic! 👍

**Comment by ikozhukhov** [comment]
we have "/dev/zvol" as a long time and using it in others components like COMSTAR (block device), etc
