### ISSUE TITLE
Pool Dencryption with the Key: Failed to open key material file (during booting)

### ISSUE THREAD

**Issue by alexsmartens** [openzfs/zfs#10360]
### System information

Type | Version/Name
 --- | ---  
Distribution Name	|  Ubuntu
Distribution Version	| 20.04 LTS
Linux Kernel	|  5.4.0-26-generic
Architecture	|  AMD64
ZFS Version	|  0.8.3-1ubuntu12
SPL Version	| 0.8.3-1ubuntu12

### Describe the problem you're observing
I'm trying to install Ubuntu on 3 partitions: `ext4` for `/boot`, `msdos` for `boot/efi` and `zfs` for `/`.  Everything works fine when the pool is encrypted with a passphrase (by following [this guide](https://github.com/dynerose/Remote-unlock-native-ZFS/blob/bef71dc4df0e39d41d3a8e26bed5a86d28c7d44a/install.bash)). However, when I encrypt the pool with a key ([my code](https://github.com/alexsmartens/dual-boot-encrytpted-Ubuntu-installation/blob/master/Ubuntu20.04-encryptedZFS)), then I'm seeing the following problem:

![6D917F64-EA5A-4705-A5DD-4F29C3FCE380](https://user-images.githubusercontent.com/26261714/82759021-48d9d480-9db8-11ea-85e1-581c95b237cb.jpeg)

It seems like the problem is that my `/boot` is not mounted before `/`, and I tried to find out how to change the boot sequence with a ZFS system but unfortunately did not find much information about it .

### Describe how to reproduce the problem
[my Ubuntu installation code](https://github.com/alexsmartens/dual-boot-encrytpted-Ubuntu-installation/blob/master/Ubuntu20.04-encryptedZFS)

I would very much appreciate if someone could help me to solve this problem or at list point me to a good documentation on how to do ZFS key encryption on Ubuntu. Thanks!

**Comment by johnnyjacq16** [comment]
@alexsmartens zfs doesn't support encrypted root with the keyformat set to raw.
![image](https://user-images.githubusercontent.com/46075870/82957431-d7ae4300-9faa-11ea-9a40-ca19067450ae.png)
To view the code for yourself go to https://github.com/openzfs/zfs/blob/master/contrib/initramfs/scripts/zfs.
This file is already on your pc, as it was install with the zfs-initramfs package, the location is  /usr/share/initramfs-tools/scripts/zfs

However if you really want to use keyformat=raw on your encrypted root dataset you may need to:
Encrypt your boot partition with cryptsetup then format with ext4.
Include the the dataset key into the initramfs img itself.
Modifying the /usr/share/initramfs-tools/scripts/zfs  file to use keyformat=raw.
Set the dataset keylocation to point to the correct place.
update-initramfs to apply changes the initramfs img.

**Comment by alexsmartens** [comment]
Thank you @johnnyjacq16,
it worked like a charm!
