### ISSUE TITLE
initconfdir is not defined in etc/zfs/Makefile

### ISSUE THREAD

**Issue by gyakovlev** [openzfs/zfs#10375]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Gentoo
Distribution Version	|  rolling
Linux Kernel	|  5.4.42
Architecture	| any
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

### Describe the problem you're observing

`initconfdir` variable is not defined in etc/zfs/Makefile,
so the sed code that's supposed to replace

`-e 's,@initconfdir\@,$(initconfdir),g' \`

actually does

this

```shell-session
make[3]: Entering directory '/var/tmp/portage/sys-fs/zfs-0.8.4/work/zfs-0.8.4/etc/zfs'
(if [ -e /etc/debian_version ]; then \
        NFS_SRV=nfs-kernel-server; \
  else \
        NFS_SRV=nfs; \
  fi; \
  if [ -e /sbin/openrc-run ]; then \
        SHELL=/sbin/openrc-run; \
  else \
        SHELL=/bin/sh; \
  fi; \
  /bin/sed \
         -e 's,@sbindir\@,/sbin,g' \
         -e 's,@sysconfdir\@,/etc,g' \
         -e 's,@initconfdir\@,,g' \  <<<<<<<<<< this is wrong.
         zfs-functions.in >'zfs-functions'; \
  [ 'zfs-functions' = 'zfs-functions' ] || \
        chmod +x 'zfs-functions')
```

as a result, we have this in `/etc/zfs/zfs-functions`

```bash
# Source zfs configuration, overriding the defaults
if [ -f /zfs ]; then
        . /zfs
fi
```

so it never loads `/etc/conf.d/zfs`

it explains https://github.com/openzfs/zfs/issues/10341 as well

**Comment by allen-4** [comment]
There is a second part to #10341 that I don't think this covers. in zfs-funtions.in there is

export ZFS ZED ZPOOL ZPOOL_CACHE ZFS_MOUNT ZFS_UNMOUNT

`# Source zfs configuration, overriding the defaults
if [ -f @initconfdir@/zfs ]; then
	. @initconfdir@/zfs
fi
'
Shouldn't the export statement follow sourcing the zfs configuration like this? 

`# Source zfs configuration, overriding the defaults
if [ -f @initconfdir@/zfs ]; then
	. @initconfdir@/zfs
fi

export ZFS ZED ZPOOL ZPOOL_CACHE ZFS_MOUNT ZFS_UNMOUNT  ZFS_SHARE ZFS_UNSHARE
`
I have a patch attached to the other bug report but wanted feedback prior to submitting a pull request.

**Comment by gyakovlev** [comment]
> There is a second part to #10341 that I don't think this covers. in zfs-funtions.in there is
> 
> export ZFS ZED ZPOOL ZPOOL_CACHE ZFS_MOUNT ZFS_UNMOUNT
> 
> `# Source zfs configuration, overriding the defaults
> if [ -f @initconfdir@/zfs ]; then
> . @initconfdir@/zfs
> fi
> '
> Shouldn't the export statement follow sourcing the zfs configuration like this?
> 
> `# Source zfs configuration, overriding the defaults
> if [ -f @initconfdir@/zfs ]; then
> . @initconfdir@/zfs
> fi
> 
> export ZFS ZED ZPOOL ZPOOL_CACHE ZFS_MOUNT ZFS_UNMOUNT ZFS_SHARE ZFS_UNSHARE
> `
> I have a patch attached to the other bug report but wanted feedback prior to submitting a pull request.

I feel dumb now, I spent some time digging into problem and completely your patch and that you've figured out it already.

next time do a PR, those are better for getting feedback.
also gentoo bug would be useful, I try to handle them in time.

initscripts are not in super-good shape overall, since everyone switched to systemd.

I guess export part is not really needed, the source ( . ) command will override local scope variables anyway, and that's what the script and it's consumers going to use (except for external binaries)

it's probably worth filing a separate PR for discussion, I'll leave it up to you, since you already have the patch. let's leave this PR just to fix empty initconfdir.
