### ISSUE TITLE
Can documentation be improved about which kernel versions are supported?

### ISSUE THREAD

**Issue by henrystrick** [openzfs/zfs#10389]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Linux fedora
Distribution Version	| 32
Linux Kernel	| 5.6.6-200
Architecture	| x86-64
ZFS Version	| 0.8.4-1
SPL Version | 0.8.4-1
DKMS Version	| 2.8

### Background
I have a problem with the OpenZFS (until recently ZFS on Linux) I use on my main desktop computer (Intel NUC). I run Linux Fedora updated every few days to the latest stable version - right now fedora 32. Normally I would be on kernel 5.6.14 - but I am stuck on 5.6.6 which is the nub of my problem. I am cautious about ZFS - only use it for my home files, some other bulk storage files, and for backups of all that. I have upgraded to the fedora 32 package of zfsonlinux.

3-4 weeks ago I tried to upgrade the kernel beyond 5.6.6. ZFS could not cope with that, so I retreated to 5.6.6. The kernel that fedora normally upgrades to is now 5.6.14, and we are weeks later, so I thought perhaps OpenZFS would have been brought in line with the kernel updates. However, today I installed 5.6.14 and then had to regress again.

I think that ZFS is a superb file system. I also use it on a FreeBSD system I run. I'd really love it if it gained more traction and became more widely used. I greatly admire all the (open source) development that has been done and is now being done to have a ZFS version for Linux at all. And the recent idea to merge ZoL with OpenZFS is simply marvellous, and will make a big difference, and I imagine that it has led to a lot of extra work, which probably explains that some other things don't get done.

I only think that - this being the case - the documentation could be considerable enhanced precisely for users like me who are using ZFS on a smaller scale, and are not "industrial" users, but who for future growth and reputation probably are users to be kept satisfied with the practical experience of using ZFS.

### Describe the problem with the current documentation
The FAQ of OpenZFS on Github reads: "The notes for a given ZFS on Linux release will include a range of supported kernels. Point releases will be tagged as needed in order to support the stable kernel available from kernel.org." But the notes of the zfs-0.8.4 release simply state "Compatible with 2.6.32 - 5.6 Linux kernels". There is no hint here that zfs 0.8.4 at the moment runs with kernel 5.6.6 and not with any later 5.6.x kernel.

The OpenZFS > Getting started > fedora documentation reads: " Due to [...] it may happen that you won’t be able to build DKMS package on the most recent kernel update. For example, Fedora 32 was released with kernel 5.6 but it is expected that it will update to 5.7. OpenZFS was released with support for kernel 5.6 but not for 5.7 and there will be no update right after 5.7 will hit Fedora repository so you have to take into account that you will have to pin your kernel version at some point." 

The META file simply says that "5.6" is the latest kernel version that is supported.

### Describe how to reproduce the problem
Run fedora 32; do the usual:

```bash
dnf -x kernel\* upgrade
dnf upgrade
reboot
```

The second upgrade at the moment upgrades the kernel to 5.6.14. You reboot and ZFS does not work any more.
You reboot again and boot into kernel 5.6.6 And ZFS works again.

### Proposal for improvement of the documentation
At present there is only a hint in the documentation that not all kernel versions will work. Would it be possible to state specifically that for fedora, right now, you need to pin your kernel version to 5.6.6 - which seems to be the actual state of affairs? 

Maybe I have missed something. And I'm not asking to fix the underlying real issue - only for the documentation to be that little bit more helpful by stating specifically what (fedora) users like me need to do to continue to have easy and uninterrupted use of their ZFS formatted data. 

Such a message would also mean that we could regularly consult that particular page in the documentation, and not ad hoc every month or so "try out" if by any chance there was a later kernel supported by ZFS. I also do not know if as soon as the 5.7 version comes out, that will be supported.

I know that not all distros handle kernel updates like this. But fedora does. I see in the documentation that you have paid close attention to this in other main distros. It's just that for a fairly simple fedora user, a tiny bit more documentation would greatly help. Many thanks for light that you can throw on this, solutions that you may have, or otherwise some explanation. And thank you for all your greatly appreciated work on ZFS!

**Comment by rincebrain** [comment]
I quickly spun up a Fedora 32 Workstation VM to see what the failure mode is, and it happily built, installed, and loaded without error on 5.6.14-300.fc32.x86_64 for me.

If you could share /var/lib/dkms/zfs/kernel-5.6.14-300.fc32.x86_64-x86_64/log/make.log it would help figure out why you're having issues with it building and I'm not.

**Comment by henrystrick** [comment]
I am back now having rebooted into kernel 5.6.6. The 5.6.14 directory you ask me for does not exist in my file system at the moment. Perhaps I can show you this:

```bash
(base) [xxx@yyy]/var/lib/dkms/zfs% ls                                    
0.8.2                                 kernel-5.3.15-300.fc31.x86_64-x86_64
0.8.3                                 kernel-5.3.16-300.fc31.x86_64-x86_64
0.8.4                                 kernel-5.4.7-200.fc31.x86_64-x86_64
kernel-5.3.11-200.fc30.x86_64-x86_64  kernel-5.4.8-200.fc31.x86_64-x86_64
kernel-5.3.11-300.fc31.x86_64-x86_64  kernel-5.4.13-201.fc31.x86_64-x86_64
kernel-5.3.12-300.fc31.x86_64-x86_64  kernel-5.4.14-200.fc31.x86_64-x86_64
kernel-5.3.13-300.fc31.x86_64-x86_64  kernel-5.5.15-200.fc31.x86_64-x86_64
kernel-5.3.14-300.fc31.x86_64-x86_64  kernel-5.6.6-200.fc31.x86_64-x86_64
``
If you want to, I can reboot again into 5.6.14, and then show you whatever you like.`

**Comment by rincebrain** [comment]
You shouldn't need to reboot into it to test this - run sudo dkms build -m zfs/0.8.4 -v [whatever the version of 5.6.14 you have is - 5.6.14-300.fc32.x86_64 is the version I got when I installed Fedora 32], then either it will bail out early and tell you you need some package installed or get to the point of trying to build, and then /var/lib/dkms/zfs/ should have a directory for 5.6.14-[whatever], and you should be able to share the log/make.log file.

**Comment by henrystrick** [comment]
OK. I'll get back to 5.6.14 and send you a bit of output.

Henry

-- 
  Henry Strick van Linschoten
  henry.strick@fastmail.com

**Comment by rincebrain** [comment]
You don't need to be booted into 5.6.14 to attempt a DKMS build of the modules for it.

**Comment by henrystrick** [comment]
This is what I got:
```bash
(base) [xxx@yyy]~% sudo dkms build -m zfs -v 0.8.4
Module zfs/0.8.4 already built for kernel 5.6.6-200.fc31.x86_64/4
```

**Comment by rincebrain** [comment]
I said sudo dkms build -m zfs/0.8.4 -k [the 5.6.14 kernel version you have].

The -k is important.

**Comment by henrystrick** [comment]
I can give you parts of the file /var/lib/dkms/zfs/kernel-5.6.6-200.fc31.x86_64-x86_64/log/make.log But that whole file is 376 lines long.... 

Don't forget that the kernel side of this is outside my range of knowledge. Perhaps I have missed something very basic. But in the past, when I had zfs under fedora 30 and fedora 31, this never occurred; I just could update normally, and dnf also upgraded all the minor kernel versions, and zfs stayed working without an issue, and without any intervention on my part.

Sorry. I missed the -k I'll repeat.

**Comment by henrystrick** [comment]
Here it is. The immediate output is the same.
```bash
(base) [xxx@yyy]/var/lib/dkms/zfs/kernel-5.6.6-200.fc31.x86_64-x86_64/log% sudo dkms build -m zfs/0.8.4 -k
Module zfs/0.8.4 already built for kernel 5.6.6-200.fc31.x86_64/4
```

**Comment by henrystrick** [comment]
I hope you are aware that my kernel version at the moment is 5.6.6. Not 5.6.14.

**Comment by rincebrain** [comment]
The command you want to run is
```
sudo dkms build -m zfs/0.8.4 -k [the 5.6.14 kernel version you have installed]
```

For example, for the version that is installed in my VM, 5.6.14-300.fc32.x86_64, it would be:
```
sudo dkms build -m zfs/0.8.4 -k 5.6.14-300.fc32.x86_64
```

Do you see how the command I'm asking you to run is different from the one you ran?

**Comment by henrystrick** [comment]
Ah yes. I see. But as I do not know or understand what dkms does, I literally did only what you wrote. So I do that now with my kernel 5.6.6 then = the actual kernel version I have??

**Comment by henrystrick** [comment]
Now it produces something meaningful.

``bash
sudo dkms build -m zfs/0.8.4 -k 5.6.6-200.fc31.x86.64 
Error! echo
Your kernel headers for kernel 5.6.6-200.fc31.x86.64 cannot be found at
/lib/modules/5.6.6-200.fc31.x86.64/build or /lib/modules/5.6.6-200.fc31.x86.64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
```

**Comment by henrystrick** [comment]
In /lib/modules/ I have at the moment three kernels fully present, 5.6.6-200.fc31.x86_64  5.6.14-300.fc32.x86_64  AND  5.5.17-200.fc31.x86_64 

They all have source, with a symbolic link to build, with a symbolic link to /usr/src/kernels

**Comment by rincebrain** [comment]
No, you wanted to use -k 5.6.14-300.fc32.x86_64 , because the point was to try building for that kernel.

(Also, at the end of the version name, it's x86_64, not x86.64.)

**Comment by henrystrick** [comment]
OK. I'll do that then.

Ah yes. Totally different. Now it made a complete build. What can I now do? Reboot into kernel 5.6.14 and it will work? If so, my final question is - should I have found my way to do this dkms command myself? And if so, at what stage? After upgrading from fedora 31 to fedora 32? As it did not happen automatically at any stage....

**Comment by rincebrain** [comment]
If you do sudo dkms install -m zfs/0.8.4 -k 5.6.14-300.fc32.x86_64 it should work on reboot.

You shouldn't have had to do this by hand if you have the DKMS package installed, but since it just worked when we tried manually doing what it should automatically do, it's hard to guess why it didn't.

**Comment by henrystrick** [comment]
OK. Fair enough. Maybe it's just a fedora thing somehow. I got enough from it anyway, that I'll be able to do it again in future if need be. I'll make those last changes, and probably confirm to you tomorrow. It's very late here in the UK. I'm sorry I was so mechanical, as I really had never had anything to do with dkms before. Thank you enormously for your support! It takes away of course my whole argument in this "issue". No doubt you'll know what is the best solution - delete it all, or whatever. Again, many thanks!!

**Comment by henrystrick** [comment]
OK. I rebooted, and everything works and is fine. I got all my questions answered. Great support from the "OpenZFS team". All the best.
