### ISSUE TITLE
syslinux ZFS support

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#10404]
I spoke with the maintainer of syslinux in 2014 at LinuxCon about porting GPL 2.0 licensed ZFS code from illumos-grub into syslinux to provide us with an alternative to GRUB2 and he was okay with it. That never happened, but it is something that came up last night in discussions in #gentoo-dev on freenode.

The neat thing about syslinux is that it makes an initramfs archive dynamically at boot from the rootfs, such that there is no chance of the initramfs being out of sync with the system, especially with regard to the cache file. This makes having syslinux as an alternative to GRUB2 highly desireable for booting systems with a native ZFS rootfs and /boot.

I am not sure if/when I will get to it as it is currently a low priority, but I wanted to open an issue to let others know that the possibility is there. If other distributions want to take the lead on this, please feel free. :)

**Comment by misterbigstuff** [comment]
better off to just write a native EFI driver.

**Comment by misterbigstuff** [comment]
reference: https://efi.akeo.ie/

**Comment by dioni21** [comment]
> better off to just write a native EFI driver.

Why not both?

**Comment by ryao** [comment]
> better off to just write a native EFI driver.

Unless you can put the driver into the EEPROM that stores UEFI, it will not help us in booting off ZFS. It could be done as a separate project though. My feeling is that syslinux would streamline things that are somewhat clunky in GRUB2 at the moment. Having things cached inside the initramfs can cause coherence issues when you say, update your system's ZFS driver, but neglect to rebuild the initramfs archive, which has bit me in the past. Also, the zpool.cache can become out of sync, which is less than ideal. syslinux would solve these problems.

**Comment by omnivagant** [comment]
I too would be interested in this.
