### ISSUE TITLE
Slow sequential read from ZFS volume on KVM

### ISSUE THREAD

**Issue by brainfrog** [openzfs/zfs#10436]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|CentOS
Distribution Version	|7.6.1810
Linux Kernel	|4.14.35-1902.302.2.el7uek.x86_64
Architecture	|x86_64
ZFS Version	|0.7.13-1
SPL Version	|0.7.13-1

### Describe the problem you're observing
KVM Windows 10 machine has about two time slower sequential read performance when deployed on zfs volume rather than the raw xfs file
### Describe how to reproduce the problem
- Install Win 10 on zfs volume 
- Run VM and make a read test
- Copy zfs volume to xfs file
- Run second read test
- Compare results

I've wrote a simple test and run it in git bash on guest
```bash
#!/bin/bash

for (( i=1; i <= 10; i++ ));do
dd if=$1 of=/dev/null bs=1M count=100 skip=$(shuf -i 0-10000 -n 1) iflag=nocache 2>&1 | grep bytes
done
```
Results for zfs volume (59.98 average)
```
104857600 bytes (105 MB, 100 MiB) copied, 0.970724 s, 108 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.62436 s, 40.0 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.88861 s, 55.5 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 4.20993 s, 24.9 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.37547 s, 76.2 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.25526 s, 46.5 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.990914 s, 106 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.46569 s, 42.5 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.74923 s, 59.9 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.60461 s, 40.3 MB/s
```
Results for xfs raw file (119.8 average)
```
104857600 bytes (105 MB, 100 MiB) copied, 0.865971 s, 121 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.954171 s, 110 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.906545 s, 116 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.848727 s, 124 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.881024 s, 119 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.850337 s, 123 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.790515 s, 133 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.991523 s, 106 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.774155 s, 135 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 0.948655 s, 111 MB/s
```
### Pool configuration
<details>
  <summary>zpool settings</summary>
<pre><code>
[root@localhost gamer]# zpool get all data
NAME  PROPERTY                       VALUE                          SOURCE
data  size                           232G                           -
data  capacity                       16%                            -
data  altroot                        -                              default
data  health                         ONLINE                         -
data  guid                           12919438891240495526           -
data  version                        -                              default
data  bootfs                         -                              default
data  delegation                     on                             default
data  autoreplace                    off                            default
data  cachefile                      -                              default
data  failmode                       wait                           default
data  listsnapshots                  off                            default
data  autoexpand                     off                            default
data  dedupditto                     0                              default
data  dedupratio                     1.00x                          -
data  free                           194G                           -
data  allocated                      37.5G                          -
data  readonly                       off                            -
data  ashift                         0                              default
data  comment                        -                              default
data  expandsize                     -                              -
data  freeing                        0                              -
data  fragmentation                  0%                             -
data  leaked                         0                              -
data  multihost                      off                            default
data  feature@async_destroy          enabled                        local
data  feature@empty_bpobj            active                         local
data  feature@lz4_compress           active                         local
data  feature@multi_vdev_crash_dump  enabled                        local
data  feature@spacemap_histogram     active                         local
data  feature@enabled_txg            active                         local
data  feature@hole_birth             active                         local
data  feature@extensible_dataset     active                         local
data  feature@embedded_data          active                         local
data  feature@bookmarks              enabled                        local
data  feature@filesystem_limits      enabled                        local
data  feature@large_blocks           enabled                        local
data  feature@large_dnode            enabled                        local
data  feature@sha512                 enabled                        local
data  feature@skein                  enabled                        local
data  feature@edonr                  enabled                        local
data  feature@userobj_accounting     active                         local
</code></pre>
</details>
<details>
  <summary>zfs settings</summary>
<pre><code>
[root@localhost gamer]# zfs get all data
NAME  PROPERTY              VALUE                  SOURCE
data  type                  filesystem             -
data  creation              Wed Jun 10 17:50 2020  -
data  used                  47.5G                  -
data  available             177G                   -
data  referenced            100K                   -
data  compressratio         1.00x                  -
data  mounted               yes                    -
data  quota                 none                   default
data  reservation           none                   default
data  recordsize            128K                   default
data  mountpoint            /data                  default
data  sharenfs              off                    default
data  checksum              on                     default
data  compression           off                    default
data  atime                 on                     default
data  devices               on                     default
data  exec                  on                     default
data  setuid                on                     default
data  readonly              off                    default
data  zoned                 off                    default
data  snapdir               hidden                 default
data  aclinherit            restricted             default
data  createtxg             1                      -
data  canmount              on                     default
data  xattr                 on                     default
data  copies                1                      default
data  version               5                      -
data  utf8only              off                    -
data  normalization         none                   -
data  casesensitivity       sensitive              -
data  vscan                 off                    default
data  nbmand                off                    default
data  sharesmb              off                    default
data  refquota              none                   default
data  refreservation        none                   default
data  guid                  9640854676276637264    -
data  primarycache          all                    default
data  secondarycache        all                    default
data  usedbysnapshots       0B                     -
data  usedbydataset         100K                   -
data  usedbychildren        47.5G                  -
data  usedbyrefreservation  0B                     -
data  logbias               latency                default
data  dedup                 off                    default
data  mlslabel              none                   default
data  sync                  standard               default
data  dnodesize             legacy                 default
data  refcompressratio      1.00x                  -
data  written               100K                   -
data  logicalused           37.6G                  -
data  logicalreferenced     40.5K                  -
data  volmode               default                default
data  filesystem_limit      none                   default
data  snapshot_limit        none                   default
data  filesystem_count      none                   default
data  snapshot_count        none                   default
data  snapdev               hidden                 default
data  acltype               off                    default
data  context               none                   default
data  fscontext             none                   default
data  defcontext            none                   default
data  rootcontext           none                   default
data  relatime              off                    default
data  redundant_metadata    all                    default
data  overlay               off                    default
</code></pre>
</details>
<details>
  <summary>smartctl</summary>
<pre><code>
[root@localhost gamer]# smartctl -i /dev/sda
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.14.35-1902.302.2.el7uek.x86_64]
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Seagate Barracuda 7200.14 (AF)
Device Model:     ST250DM000-1BD141
Serial Number:    6VYD62RJ
LU WWN Device Id: 5 000c50 051dd77fa
Firmware Version: KC45
User Capacity:    250,059,350,016 bytes [250 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Jun 10 22:24:51 2020 MSK
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
</code></pre>
</details>

[VM config](https://gist.github.com/brainfrog/d308cf357ff83d7e79bab30fc1c24fc0)

ashift: 12
```
[root@localhost gamer]# zpool status data
  pool: data
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        data        ONLINE       0     0     0
          sda       ONLINE       0     0     0

errors: No known data errors
```

### What I've tried with no luck
- set recordsize=1M
- set atime=off
- set volmode=dev

What can I do to improve read performance from zvol?

**Comment by shodanshok** [comment]
This is due to ZVOLs using, by default, a very small block size (8K). Try the following:

 - create a new zvol with `-o volblocksize 128K`

 - copy the old zvol in the new one (ie: `dd if=/dev/oldvol of=/dev/newvol bs=1M iflag=direct oflag=direct`)

 - clear cache by issuing `echo 3 > /proc/sys/vm/drop_cache`

 - retry reading from the zvol with `dd if=/dev/newvol of=/dev/null bs=1M iflag=direct`

**Comment by brainfrog** [comment]
Thanks for suggestion!
I've tried it. But it doesn't looks like a huge improvements, if any. (63.93 avg)
```
104857600 bytes (105 MB, 100 MiB) copied, 1.23121 s, 85.2 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.35579 s, 77.3 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.43895 s, 43.0 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.10056 s, 95.3 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.31687 s, 79.6 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.45219 s, 42.8 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.45767 s, 71.9 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 3.36095 s, 31.2 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 2.06465 s, 50.8 MB/s
104857600 bytes (105 MB, 100 MiB) copied, 1.68495 s, 62.2 MB/s
```
I've used my own test to be consistent with previous results

**Comment by shodanshok** [comment]
Due to the variability of your results, I think the prefetcher does not always engages. Please try using the `dd` command I posted above and share the result. Thanks.

**Comment by brainfrog** [comment]
Ok. I've read that `dd` must have `iflag/oflag=direct` for testing disk performance. Your test seems more suitable.
That what I've got:
Test `dd if=$1 of=/dev/null bs=1M count=10000 iflag=direct`
8k volblocksize result
`10485760000 bytes (10 GB, 9.8 GiB) copied, 243.473 s, 43.1 MB/s`
128k volblocksize result
`10485760000 bytes (10 GB, 9.8 GiB) copied, 267.706 s, 39.2 MB/s`
raw xfs
`10485760000 bytes (10 GB, 9.8 GiB) copied, 118.084 s, 88.8 MB/s`

**Comment by shodanshok** [comment]
Did you test on a newly created volume with the correct `volblocksize` option? Changing it on an existing volume will *not* work.

**Comment by brainfrog** [comment]
Yes. I've created a volume like this `zfs create -V 50G -o volblocksize=128k data/kvm/desktop/windows-vm1-ready-128k`

**Comment by shodanshok** [comment]
Is on another partition of the same disks which you use for ZFS? If not, please show the `smartctl` output of the XFS disk. Anyway, I would suggest to close the issue here and to continue on the mailing list.

**Comment by brainfrog** [comment]
I've gave the whole disk for zpool, tested it, then formatted the disk to xfs and tested again. `smartctl` for that disk in the first comment

**Comment by shodanshok** [comment]
Can you post the output of `iostat -x -k 1` and `zpool iostat -l` (captured on another terminal) during the `dd` command?

**Comment by brainfrog** [comment]
There you are:
`iostat -x -k 1`
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.82    0.00    6.21   17.11    0.00   71.86

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sda               2.00     0.00  312.00    0.00 40064.00     0.00   256.82     2.95    9.34    9.34    0.00   3.21 100.00
sdd               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd0               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd16              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd32              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd48              0.00     0.00   90.00    3.00 43948.00    12.00   945.38     1.03   10.38   10.72    0.00   9.95  92.50
zd64              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd80              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
zd96              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```
`zpool iostat -l `
```
              capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub
pool        alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
data        92.6G   139G     13     17  1.67M  1.79M   62ms  238ms   18ms    8ms    1ms   55ms  105ms  294ms   12ms
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
```

**Comment by shodanshok** [comment]
Well, it really seems the disk is maxed out.  Can you show the output of `arc_summary`?

**Comment by brainfrog** [comment]
Sorry for a long time
<details>
  <summary>arc_summary</summary>
<pre><code>
[root@localhost gamer]# /usr/bin/arc_summary.py

------------------------------------------------------------------------
ZFS Subsystem Report                            Fri Jun 26 15:15:19 2020
ARC Summary: (HEALTHY)
        Memory Throttle Count:                  0

ARC Misc:
        Deleted:                                856.69k
        Mutex Misses:                           20
        Evict Skips:                            101.80k

ARC Size:                               75.78%  5.93    GiB
        Target Size: (Adaptive)         76.97%  6.02    GiB
        Min Size (Hard Limit):          6.25%   500.63  MiB
        Max Size (High Water):          16:1    7.82    GiB

ARC Size Breakdown:
        Recently Used Cache Size:       79.21%  4.68    GiB
        Frequently Used Cache Size:     20.79%  1.23    GiB

ARC Hash Breakdown:
        Elements Max:                           74.97k
        Elements Current:               90.78%  68.06k
        Collisions:                             4.94k
        Chain Max:                              2
        Chains:                                 608

ARC Total accesses:                                     4.79M
        Cache Hit Ratio:                88.34%  4.23M
        Cache Miss Ratio:               11.66%  558.09k
        Actual Hit Ratio:               88.24%  4.22M

        Data Demand Efficiency:         84.40%  588.55k
        Data Prefetch Efficiency:       2.64%   446.89k

        CACHE HITS BY CACHE LIST:
          Most Recently Used:           27.17%  1.15M
          Most Frequently Used:         72.72%  3.07M
          Most Recently Used Ghost:     0.18%   7.78k
          Most Frequently Used Ghost:   0.27%   11.43k

        CACHE HITS BY DATA TYPE:
          Demand Data:                  11.75%  496.75k
          Prefetch Data:                0.28%   11.78k
          Demand Metadata:              87.97%  3.72M
          Prefetch Metadata:            0.01%   339

        CACHE MISSES BY DATA TYPE:
          Demand Data:                  16.45%  91.80k
          Prefetch Data:                77.97%  435.11k
          Demand Metadata:              5.52%   30.79k
          Prefetch Metadata:            0.07%   385


DMU Prefetch Efficiency:                                        5.43M
        Hit Ratio:                      9.18%   498.86k
        Miss Ratio:                     90.82%  4.93M



ZFS Tunables:
        dbuf_cache_hiwater_pct                            10
        dbuf_cache_lowater_pct                            10
        dbuf_cache_max_bytes                              104857600
        dbuf_cache_max_shift                              5
        dmu_object_alloc_chunk_shift                      7
        ignore_hole_birth                                 1
        l2arc_feed_again                                  1
        l2arc_feed_min_ms                                 200
        l2arc_feed_secs                                   1
        l2arc_headroom                                    2
        l2arc_headroom_boost                              200
        l2arc_noprefetch                                  1
        l2arc_norw                                        0
        l2arc_write_boost                                 8388608
        l2arc_write_max                                   8388608
        metaslab_aliquot                                  524288
        metaslab_bias_enabled                             1
        metaslab_debug_load                               0
        metaslab_debug_unload                             0
        metaslab_fragmentation_factor_enabled             1
        metaslab_lba_weighting_enabled                    1
        metaslab_preload_enabled                          1
        metaslabs_per_vdev                                200
        send_holes_without_birth_time                     1
        spa_asize_inflation                               24
        spa_config_path                                   /etc/zfs/zpool.cache
        spa_load_verify_data                              1
        spa_load_verify_maxinflight                       10000
        spa_load_verify_metadata                          1
        spa_slop_shift                                    5
        zfetch_array_rd_sz                                1048576
        zfetch_max_distance                               8388608
        zfetch_max_streams                                8
        zfetch_min_sec_reap                               2
        zfs_abd_scatter_enabled                           1
        zfs_abd_scatter_max_order                         10
        zfs_admin_snapshot                                1
        zfs_arc_average_blocksize                         8192
        zfs_arc_dnode_limit                               0
        zfs_arc_dnode_limit_percent                       10
        zfs_arc_dnode_reduce_percent                      10
        zfs_arc_grow_retry                                0
        zfs_arc_lotsfree_percent                          10
        zfs_arc_max                                       0
        zfs_arc_meta_adjust_restarts                      4096
        zfs_arc_meta_limit                                0
        zfs_arc_meta_limit_percent                        75
        zfs_arc_meta_min                                  0
        zfs_arc_meta_prune                                10000
        zfs_arc_meta_strategy                             1
        zfs_arc_min                                       0
        zfs_arc_min_prefetch_lifespan                     0
        zfs_arc_p_dampener_disable                        1
        zfs_arc_p_min_shift                               0
        zfs_arc_pc_percent                                0
        zfs_arc_shrink_shift                              0
        zfs_arc_sys_free                                  0
        zfs_autoimport_disable                            1
        zfs_checksums_per_second                          20
        zfs_compressed_arc_enabled                        1
        zfs_dbgmsg_enable                                 0
        zfs_dbgmsg_maxsize                                4194304
        zfs_dbuf_state_index                              0
        zfs_deadman_checktime_ms                          5000
        zfs_deadman_enabled                               1
        zfs_deadman_synctime_ms                           1000000
        zfs_dedup_prefetch                                0
        zfs_delay_min_dirty_percent                       60
        zfs_delay_scale                                   500000
        zfs_delays_per_second                             20
        zfs_delete_blocks                                 20480
        zfs_dirty_data_max                                1679843737
        zfs_dirty_data_max_max                            4199609344
        zfs_dirty_data_max_max_percent                    25
        zfs_dirty_data_max_percent                        10
        zfs_dirty_data_sync                               67108864
        zfs_dmu_offset_next_sync                          0
        zfs_expire_snapshot                               300
        zfs_flags                                         0
        zfs_free_bpobj_enabled                            1
        zfs_free_leak_on_eio                              0
        zfs_free_max_blocks                               100000
        zfs_free_min_time_ms                              1000
        zfs_immediate_write_sz                            32768
        zfs_max_recordsize                                1048576
        zfs_mdcomp_disable                                0
        zfs_metaslab_fragmentation_threshold              70
        zfs_metaslab_segment_weight_enabled               1
        zfs_metaslab_switch_threshold                     2
        zfs_mg_fragmentation_threshold                    85
        zfs_mg_noalloc_threshold                          0
        zfs_multihost_fail_intervals                      5
        zfs_multihost_history                             0
        zfs_multihost_import_intervals                    10
        zfs_multihost_interval                            1000
        zfs_multilist_num_sublists                        0
        zfs_no_scrub_io                                   0
        zfs_no_scrub_prefetch                             0
        zfs_nocacheflush                                  0
        zfs_nopwrite_enabled                              1
        zfs_object_mutex_size                             64
        zfs_pd_bytes_max                                  52428800
        zfs_per_txg_dirty_frees_percent                   30
        zfs_prefetch_disable                              0
        zfs_read_chunk_size                               1048576
        zfs_read_history                                  0
        zfs_read_history_hits                             0
        zfs_recover                                       0
        zfs_recv_queue_length                             16777216
        zfs_resilver_delay                                2
        zfs_resilver_min_time_ms                          3000
        zfs_scan_idle                                     50
        zfs_scan_ignore_errors                            0
        zfs_scan_min_time_ms                              1000
        zfs_scrub_delay                                   4
        zfs_send_corrupt_data                             0
        zfs_send_queue_length                             16777216
        zfs_sync_pass_deferred_free                       2
        zfs_sync_pass_dont_compress                       5
        zfs_sync_pass_rewrite                             2
        zfs_sync_taskq_batch_pct                          75
        zfs_top_maxinflight                               32
        zfs_txg_history                                   0
        zfs_txg_timeout                                   5
        zfs_vdev_aggregation_limit                        131072
        zfs_vdev_async_read_max_active                    3
        zfs_vdev_async_read_min_active                    1
        zfs_vdev_async_write_active_max_dirty_percent     60
        zfs_vdev_async_write_active_min_dirty_percent     30
        zfs_vdev_async_write_max_active                   10
        zfs_vdev_async_write_min_active                   2
        zfs_vdev_cache_bshift                             16
        zfs_vdev_cache_max                                16384
        zfs_vdev_cache_size                               0
        zfs_vdev_max_active                               1000
        zfs_vdev_mirror_non_rotating_inc                  0
        zfs_vdev_mirror_non_rotating_seek_inc             1
        zfs_vdev_mirror_rotating_inc                      0
        zfs_vdev_mirror_rotating_seek_inc                 5
        zfs_vdev_mirror_rotating_seek_offset              1048576
        zfs_vdev_queue_depth_pct                          1000
        zfs_vdev_raidz_impl                               [fastest] original scalar sse2 ssse3 avx2
        zfs_vdev_read_gap_limit                           32768
        zfs_vdev_scheduler                                noop
        zfs_vdev_scrub_max_active                         2
        zfs_vdev_scrub_min_active                         1
        zfs_vdev_sync_read_max_active                     10
        zfs_vdev_sync_read_min_active                     10
        zfs_vdev_sync_write_max_active                    10
        zfs_vdev_sync_write_min_active                    10
        zfs_vdev_write_gap_limit                          4096
        zfs_zevent_cols                                   80
        zfs_zevent_console                                0
        zfs_zevent_len_max                                128
        zil_replay_disable                                0
        zil_slog_bulk                                     786432
        zio_delay_max                                     30000
        zio_dva_throttle_enabled                          1
        zio_requeue_io_start_cut_in_line                  1
        zio_taskq_batch_pct                               75
        zvol_inhibit_dev                                  0
        zvol_major                                        230
        zvol_max_discard_blocks                           16384
        zvol_prefetch_bytes                               131072
        zvol_request_sync                                 0
        zvol_threads                                      32
        zvol_volmode                                      1
</code></pre>
</details>

Root dataset test:
```
[root@localhost gamer]# dd if=/data/random.img of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 12.2606 s, 87.6 MB/s
```

**Comment by brainfrog** [comment]
I have found that the read speed degrades on clones.
My zfs list
```
[root@localhost gamer]# zfs list -tall
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
data                                54.2G   171G  1.00G  /data
data/kvm                            53.2G   171G   100K  /data/kvm
data/kvm/desktop                    53.2G   171G    96K  /data/kvm/desktop
data/kvm/desktop/windows            50.0G   171G  50.0G  -
data/kvm/desktop/windows@1             8K      -  50.0G  -
data/kvm/desktop/windows-vm1        1.07G   171G  50.0G  -
data/kvm/desktop/windows-vm1@1         8K      -  50.0G  -
data/kvm/desktop/windows-vm1-ready  2.09G   171G  50.0G  -
```

data/kvm/desktop/windows - base dataset
data/kvm/desktop/windows-vm1 - clone of data/kvm/desktop/windows with some preparation settings
data/kvm/desktop/windows-vm1-ready - clone of data/kvm/desktop/windows-vm1, used by VM



Test: `dd if=$1 of=/dev/null bs=1M count=10000 iflag=direct`
Results:
```
[root@localhost gamer]# echo 3 > /proc/sys/vm/drop_caches
[root@localhost gamer]# ./hdd_test2.sh /dev/zvol/data/kvm/desktop/windows
10485760000 bytes (10 GB) copied, 81.075 s, 129 MB/s
[root@localhost gamer]# echo 3 > /proc/sys/vm/drop_caches
[root@localhost gamer]# ./hdd_test2.sh /dev/zvol/data/kvm/desktop/windows-vm1
10485760000 bytes (10 GB) copied, 114.358 s, 91.7 MB/s
[root@localhost gamer]# echo 3 > /proc/sys/vm/drop_caches
[root@localhost gamer]# ./hdd_test2.sh /dev/zvol/data/kvm/desktop/windows-vm1-ready
10485760000 bytes (10 GB) copied, 144.339 s, 72.6 MB/s
```

**Comment by shodanshok** [comment]
> Sorry for a long time
> 
> arc_summary
> Root dataset test:
> 
> ```
> [root@localhost gamer]# dd if=/data/random.img of=/dev/null bs=1M count=1024
> 1024+0 records in
> 1024+0 records out
> 1073741824 bytes (1.1 GB) copied, 12.2606 s, 87.6 MB/s
> ```

It seems that reading from the root dataset is as fast as XFS. Maybe your zvols are simply allocated from inner disk tracks (with lower transfer rate).
