### ISSUE TITLE
lz4_compress threads when compression disabled, slow performance

### ISSUE THREAD

**Issue by mulroony** [openzfs/zfs#10438]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Redhat 
Distribution Version	| 8.2
Linux Kernel	| 4.18.0-193.1.2.el8_2.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing
Sorry if I am misunderstanding the output of 'perf top', but I am testing a 4 NVMe RAID10 configuration and experiencing some slowness (compared to XFs on MD RAID 10). When I run 'fio', 'perf top' reports spending '25%' in lz4_compress. A flamegraph of 'perf record' shows the same. As best I can tell I have disabled all compression on the dataset so not sure why it is spending time there.. This is a new Dell AMD EPYC 7702P 64-Core Processor system. 

### Describe how to reproduce the problem
```
rmmod zfs
cat  > /etc/modprobe.d/zfs.conf <<EOF
options zfs metaslab_lba_weighting_enabled=0

options zfs zfs_vdev_async_read_max_active=2048
options zfs zfs_vdev_async_read_min_active=512
options zfs zfs_vdev_async_write_max_active=2048
options zfs zfs_vdev_async_write_min_active=512
options zfs zfs_vdev_max_active=8192
options zfs zfs_vdev_sync_read_max_active=2048
options zfs zfs_vdev_sync_read_min_active=512
options zfs zfs_vdev_sync_write_max_active=2048
options zfs zfs_vdev_sync_write_min_active=512

#options zfs zfs_vdev_scheduler=noop

options zfs zfs_max_recordsize=4194304
options zfs zfs_vdev_aggregation_limit=4194304

options zfs zfs_prefetch_disable=1
EOF

modprobe zfs
# Install 4 NVMe drives
zpool create ztest mirror /dev/nvme0n1 /dev/nvme1n1 mirror /dev/nvme2n1 /dev/nvme3n1
zfs set compression=off ztest
zfs set recordsize=16k ztest
fio --filename=/ztest/file_iop --size=500GB --direct=1 --rw=randrw --bs=4k --ioengine=libaio --iodepth=256 --runtime=120 --numjobs=32 --time_based --group_reporting --name=iops-test-job --eta-newline=1
# While running, after it generates the initial file
perf top
```

### Include any warning/errors/backtraces from the system logs
I will attach a FlameGraph collected during the run.

**Comment by mulroony** [comment]
![image](https://user-images.githubusercontent.com/1547352/84340732-2e448100-ab56-11ea-8f28-25815542e88f.png)

**Comment by ahrens** [comment]
ZFS always compresses metadata, including indirect blocks.  Your test is doing random writes, so each write requires modifying (and compressing) a 128KB indirect block.

Side note: I noticed you are using recordsize=16K but --bs=4k, so you'll also be doing read-modify-write for each i/o.

**Comment by mulroony** [comment]
@ahrens - Thanks! Saw an OLD mailing list mention of that, but wasn't sure if it still held true.
