### ISSUE TITLE
Unable to remove recieve resume token

### ISSUE THREAD

**Issue by sebu06** [openzfs/zfs#10439]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Buster
Linux Kernel	| 5.4.41-1-pve
Architecture	| x86_64
ZFS Version	| 0.8.4-pve1
SPL Version	| 0.8.4-pve1

### Describe the problem you're observing
I use resume tokens to send snapshots from another machine to this host. Four month ago a send failed, but I did not notice, because I use the option -F to send the snapshot. After update of kernel / ZFS on the sender side, it will not send the snapshot, because it (correcly) now detects there is a resume token. 

```
root@server:/home/user# zfs get all pool/client/backup | grep token
pool/client/backup  receive_resume_token  1-eb46e146b-d0-789c636064000310a500c4ec50360710e72765a5269730307441d560c8a7a515a7968064d6b1c0e4d990e4932a4b528b817403d31a566cfa4bf2d34b335318187a2da5b789c459fb3920c97382e5f3127353191852124b12758b4bf28b12d353f50d8ce2931293b34b0b1c924ae38d0c0c2d0d8c0c2c19e0000029161d79  -
```
Since the original snapshot does not exist on the client, I would like to remove the resume token - I did so by executing 

```
root@server:/home/user# zfs receive -A pool/client/backup
'pool/client/backup' does not have any resumable receive state to abort```

Since it is a lot of data sent over a slow connection, I would prefer not to resync the whole dataset.

**Comment by ahrens** [comment]
I'm assuming that you were receiving an incremental send into `pool/client/backup` (otherwise, you could just destroy the whole filesystem).  What should have happened is that it created a hidden filesystem `pool/client/backup/%recv` and started to receive into that.  The `zfs receive -A` should have destroyed that `%recv` filesystem, but it didn't find the `%recv` filesystem.

Could you use `zdb -d pool` to check if the %recv filesystem really exists?  You should see something like this:
```
Dataset pool/client/backup/%recv [ZPL], ID 155, cr_txg 42, 922K, 7 objects (inconsistent)
```

**Comment by sebu06** [comment]
Hi,
thanks for the reply. There is not %recv Filesystem. Regarding rhe receive location: I'm doing a recursive send/receive on the client-dataset.

**Comment by ahrens** [comment]
Hm, looking at the code I'm not sure how this would happen.  Can you confirm that there are some snapshots of pool/client/backup?  Also, in the output of `zdb -d pool`, does it show `(inconsistent)` for pool/client/backup?

**Comment by sebu06** [comment]
Hi,
no - there is no (inconsistent) output. There are plenty of snapshots for pool/client/backup.

**Comment by sebu06** [comment]
looking at the code I also cannot see where it goes wrong. But I assume that I can just delete the resume token property, given the fact, that the command actually does nothing else as well?

**Comment by sebu06** [comment]
actually - line 4685 in zfs_main.c

`if (!zfs_prop_get_int(zhp, ZFS_PROP_INCONSISTENT) ||
			    zfs_prop_get(zhp, ZFS_PROP_RECEIVE_RESUME_TOKEN,
			    NULL, 0, NULL, NULL, 0, B_TRUE) == -1) {`

so if the dataset is not inconsistent, it will not delete the resume token, right?

**Comment by ahrens** [comment]
Right.  It should be hitting the case above of finding the `%recv`.  You can try running `zfs destroy pool/client/backup/%recv` and see if that somehow finds the %recv when `zfs recv -A` didn't (although if it works then we won't have much chance of figuring out what went wrong).

**Comment by sebu06** [comment]
The dataset does not exist. Can I do something like 

```zfs unset receive_resume_token ```

**Comment by ahrens** [comment]
> can I do `zfs unset receive_resume_token`

No.

It's possible that the resume token is set on `pool/client/backup` itself, and yet the dataset is not marked inconsistent.  That shouldn't happen, but you can check by running `zdb -dddddd pool $(zfs get -Hp -o value objsetid pool/client/backup)` and then look for `resume` in that output.

**Comment by sebu06** [comment]
There is a resume part in the output
```                com.delphix:resume_offset = 78512128
                com.delphix:resume_bytes = 95158912
                com.delphix:resume_object = 394
                com.delphix:resume_toname = data-storage/backup@bu_20190209
                com.delphix:resume_toguid = 5637202801631902093
```

**Comment by ahrens** [comment]
Interesting, so there is a resume token on pool/client/backup, which is for a full (not incremental) stream (there's no `resume_fromguid`).  Also the `resume_offset` field seems to be missing.  Can you double check that there are no more `resume_*` fields in the `zdb` output?

> no - there is no (inconsistent) output. There are plenty of snapshots for pool/client/backup.

Would you mind pasting the output that shows the snapshots?

**Comment by sebu06** [comment]
Hi,
yes, I'm sure:
```
root@zdv:~# zdb -dddddd pool $(zfs get -Hp -o value objsetid pool/client/backup) | grep resume
                com.delphix:resume_offset = 78512128
                com.delphix:resume_bytes = 95158912
                com.delphix:resume_object = 394
                com.delphix:resume_toname = data-storage/backup@bu_20190209
                com.delphix:resume_toguid = 5637202801631902093
```

Here the list on the server (receiver):
```
root@zdv:~# zfs list | grep backup
pool/client/backup                 179G   213G      179G  none
pool/client/backup@bu_20200415    3.00M      -      179G  -
pool/client/backup@bu_20200416     216K      -      179G  -
pool/client/backup@bu_20200417     216K      -      179G  -
pool/client/backup@bu_20200418     208K      -      179G  -
pool/client/backup@bu_20200419     208K      -      179G  -
pool/client/backup@bu_20200420     224K      -      179G  -
pool/client/backup@bu_20200421     216K      -      179G  -
pool/client/backup@bu_20200422     232K      -      179G  -
pool/client/backup@bu_20200423     216K      -      179G  -
pool/client/backup@bu_20200424     216K      -      179G  -
pool/client/backup@bu_20200425     208K      -      179G  -
pool/client/backup@bu_20200426     208K      -      179G  -
pool/client/backup@bu_20200427     232K      -      179G  -
pool/client/backup@bu_20200428     232K      -      179G  -
pool/client/backup@bu_20200429     224K      -      179G  -
pool/client/backup@bu_20200430     216K      -      179G  -
pool/client/backup@bu_20200501     224K      -      179G  -
pool/client/backup@bu_20200502     208K      -      179G  -
pool/client/backup@bu_20200503     208K      -      179G  -
pool/client/backup@bu_20200504     232K      -      179G  -
pool/client/backup@bu_20200505     232K      -      179G  -
pool/client/backup@bu_20200506     232K      -      179G  -
pool/client/backup@bu_20200507     232K      -      179G  -
pool/client/backup@bu_20200509     200K      -      179G  -
pool/client/backup@bu_20200510     208K      -      179G  -
pool/client/backup@bu_20200511     232K      -      179G  -
pool/client/backup@bu_20200512     232K      -      179G  -
pool/client/backup@bu_20200513     232K      -      179G  -
pool/client/backup@bu_20200514     216K      -      179G  -
pool/client/backup@bu_20200515     216K      -      179G  -
pool/client/backup@bu_20200516     208K      -      179G  -
pool/client/backup@bu_20200517     208K      -      179G  -
pool/client/backup@bu_20200518     224K      -      179G  -
pool/client/backup@bu_20200519     224K      -      179G  -
pool/client/backup@bu_20200520     224K      -      179G  -
pool/client/backup@bu_20200521     208K      -      179G  -
pool/client/backup@bu_20200522     208K      -      179G  -
pool/client/backup@bu_20200523     208K      -      179G  -
pool/client/backup@bu_20200524     208K      -      179G  -
pool/client/backup@bu_20200525       0B      -      179G  -
```

and on the client (sender):
```
ds ➜  ~ sudo zfs list -t snap | grep backup
data-storage/backup@ext_20200414    41.7M      -      179G  -
data-storage/backup@bu_20200521      232K      -      179G  -
data-storage/backup@bu_20200522      208K      -      179G  -
data-storage/backup@bu_20200523      208K      -      179G  -
data-storage/backup@bu_20200524      208K      -      179G  -
data-storage/backup@bu_20200525      224K      -      179G  -
data-storage/backup@bu_20200526      224K      -      179G  -
data-storage/backup@bu_20200527      232K      -      179G  -
data-storage/backup@bu_20200528      216K      -      179G  -
data-storage/backup@bu_20200529      208K      -      179G  -
data-storage/backup@bu_20200530      200K      -      179G  -
data-storage/backup@bu_20200531      200K      -      179G  -
data-storage/backup@bu_20200601      216K      -      179G  -
data-storage/backup@bu_20200602      232K      -      179G  -
data-storage/backup@bu_20200603      232K      -      179G  -
data-storage/backup@bu_20200604      216K      -      179G  -
data-storage/backup@bu_20200605      224K      -      179G  -
data-storage/backup@bu_20200606      208K      -      179G  -
data-storage/backup@bu_20200607      208K      -      179G  -
data-storage/backup@bu_20200608      224K      -      179G  -
data-storage/backup@bu_20200609      208K      -      179G  -
data-storage/backup@bu_20200610      192K      -      179G  -
data-storage/backup@bu_20200611      208K      -      179G  -
data-storage/backup@bu_20200612      208K      -      179G  -
data-storage/backup@bu_20200613      208K      -      179G  -
data-storage/backup@bu_20200614        0B      -      179G  -
```

As you can see with previous versions, snaps have been transferred successfully after the 9th of Febuary (where the uncompleted transfer was happening)

**Comment by sebu06** [comment]
Any idea how I can remove that incomplete token?

**Comment by hainguyen8y** [comment]
I have the same problem

```
hainguyen@ubuntu:~$ sudo zdb -dddddd data $(zfs get -Hp -o value objsetid data/Archives) | grep resume
                com.delphix:resume_bytes = 1259275212816
                com.delphix:resume_toguid = -2326736824219331859
                com.delphix:resume_toname = data/Archives@zfs-auto-snap_monthly-2019-09-01-0413
                com.delphix:resume_object = 1076214
                com.delphix:resume_offset = 635207680
```
zfs-0.8.4

**Comment by hainguyen8y** [comment]
> Hi,
> yes, I'm sure:
> 
> ```
> root@zdv:~# zdb -dddddd pool $(zfs get -Hp -o value objsetid pool/client/backup) | grep resume
>                 com.delphix:resume_offset = 78512128
>                 com.delphix:resume_bytes = 95158912
>                 com.delphix:resume_object = 394
>                 com.delphix:resume_toname = data-storage/backup@bu_20190209
>                 com.delphix:resume_toguid = 5637202801631902093
> ```
> 
> Here the list on the server (receiver):
> 
> ```
> root@zdv:~# zfs list | grep backup
> pool/client/backup                 179G   213G      179G  none
> pool/client/backup@bu_20200415    3.00M      -      179G  -
> pool/client/backup@bu_20200416     216K      -      179G  -
> pool/client/backup@bu_20200417     216K      -      179G  -
> pool/client/backup@bu_20200418     208K      -      179G  -
> pool/client/backup@bu_20200419     208K      -      179G  -
> pool/client/backup@bu_20200420     224K      -      179G  -
> pool/client/backup@bu_20200421     216K      -      179G  -
> pool/client/backup@bu_20200422     232K      -      179G  -
> pool/client/backup@bu_20200423     216K      -      179G  -
> pool/client/backup@bu_20200424     216K      -      179G  -
> pool/client/backup@bu_20200425     208K      -      179G  -
> pool/client/backup@bu_20200426     208K      -      179G  -
> pool/client/backup@bu_20200427     232K      -      179G  -
> pool/client/backup@bu_20200428     232K      -      179G  -
> pool/client/backup@bu_20200429     224K      -      179G  -
> pool/client/backup@bu_20200430     216K      -      179G  -
> pool/client/backup@bu_20200501     224K      -      179G  -
> pool/client/backup@bu_20200502     208K      -      179G  -
> pool/client/backup@bu_20200503     208K      -      179G  -
> pool/client/backup@bu_20200504     232K      -      179G  -
> pool/client/backup@bu_20200505     232K      -      179G  -
> pool/client/backup@bu_20200506     232K      -      179G  -
> pool/client/backup@bu_20200507     232K      -      179G  -
> pool/client/backup@bu_20200509     200K      -      179G  -
> pool/client/backup@bu_20200510     208K      -      179G  -
> pool/client/backup@bu_20200511     232K      -      179G  -
> pool/client/backup@bu_20200512     232K      -      179G  -
> pool/client/backup@bu_20200513     232K      -      179G  -
> pool/client/backup@bu_20200514     216K      -      179G  -
> pool/client/backup@bu_20200515     216K      -      179G  -
> pool/client/backup@bu_20200516     208K      -      179G  -
> pool/client/backup@bu_20200517     208K      -      179G  -
> pool/client/backup@bu_20200518     224K      -      179G  -
> pool/client/backup@bu_20200519     224K      -      179G  -
> pool/client/backup@bu_20200520     224K      -      179G  -
> pool/client/backup@bu_20200521     208K      -      179G  -
> pool/client/backup@bu_20200522     208K      -      179G  -
> pool/client/backup@bu_20200523     208K      -      179G  -
> pool/client/backup@bu_20200524     208K      -      179G  -
> pool/client/backup@bu_20200525       0B      -      179G  -
> ```
> 
> and on the client (sender):
> 
> ```
> ds ➜  ~ sudo zfs list -t snap | grep backup
> data-storage/backup@ext_20200414    41.7M      -      179G  -
> data-storage/backup@bu_20200521      232K      -      179G  -
> data-storage/backup@bu_20200522      208K      -      179G  -
> data-storage/backup@bu_20200523      208K      -      179G  -
> data-storage/backup@bu_20200524      208K      -      179G  -
> data-storage/backup@bu_20200525      224K      -      179G  -
> data-storage/backup@bu_20200526      224K      -      179G  -
> data-storage/backup@bu_20200527      232K      -      179G  -
> data-storage/backup@bu_20200528      216K      -      179G  -
> data-storage/backup@bu_20200529      208K      -      179G  -
> data-storage/backup@bu_20200530      200K      -      179G  -
> data-storage/backup@bu_20200531      200K      -      179G  -
> data-storage/backup@bu_20200601      216K      -      179G  -
> data-storage/backup@bu_20200602      232K      -      179G  -
> data-storage/backup@bu_20200603      232K      -      179G  -
> data-storage/backup@bu_20200604      216K      -      179G  -
> data-storage/backup@bu_20200605      224K      -      179G  -
> data-storage/backup@bu_20200606      208K      -      179G  -
> data-storage/backup@bu_20200607      208K      -      179G  -
> data-storage/backup@bu_20200608      224K      -      179G  -
> data-storage/backup@bu_20200609      208K      -      179G  -
> data-storage/backup@bu_20200610      192K      -      179G  -
> data-storage/backup@bu_20200611      208K      -      179G  -
> data-storage/backup@bu_20200612      208K      -      179G  -
> data-storage/backup@bu_20200613      208K      -      179G  -
> data-storage/backup@bu_20200614        0B      -      179G  -
> ```
> 
> As you can see with previous versions, snaps have been transferred successfully after the 9th of Febuary (where the uncompleted transfer was happening)

I see that the snapshots are newer than the resume_toname. This is maybe problem. The old snapshots were deleted before the resume_receive_token was deleted. I think the token should be deleted right after the partial snapshot is transferred completely.

**Comment by zssfred** [comment]
In my observation, that token is not synchronously updated. This could have risk condition.
