### ISSUE TITLE
Invalid backup stream during zfs receive

### ISSUE THREAD

**Issue by Flyffies** [openzfs/zfs#10441]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Buster (10.4)
Linux Kernel	| 4.19.0-9
Architecture	| amd64
ZFS Version	| 0.8.4-1~bpo10+1
SPL Version	| 0.8.4-1~bpo10+1

### Describe the problem you're observing

I had to restore my System and decided to do so by exporting my ZFS Filesystems via ZFS send to a network share my hoster could provide.

I had to mount my pool in read only in the recovery environment and send the filesystems into a file on the share. 

After reinstalling my server I received the filesystems back into the new pool. on 5 of the 7 this worked no problem. But my nextcloud files (of course the most important one...) has en error while importing.

After running a while it fails with the following error:
`cannot receive new filesystem stream: invalid backup stream`

When I run the snapshotfile through zstreamsdump it fails with this message:
```
<many many records>
BEGIN record
        hdrtype = 0
        features = 0
        magic = 0
        creation_time = 0
        type = 0
        flags = 0x0
        toguid = 0
        fromguid = 0
        toname =
invalid checksum
Incorrect checksum in record header.
Expected checksum = 4935c8a66e56e85c/e1f01e74dc163f48/bcc20562df6ae0c/ec815b9d684b028d
SUMMARY:
        Total DRR_BEGIN records = 26662 (0 bytes)
        Total DRR_END records = 0 (0 bytes)
        Total DRR_OBJECT records = 52078 (8748264 bytes)
        Total DRR_FREEOBJECTS records = 912 (0 bytes)
        Total DRR_WRITE records = 912181 (117219152896 bytes)
        Total DRR_WRITE_BYREF records = 0 (0 bytes)
        Total DRR_WRITE_EMBEDDED records = 0 (0 bytes)
        Total DRR_FREE records = 79454 (0 bytes)
        Total DRR_SPILL records = 0 (0 bytes)
        Total records = 1071287
        Total payload size = 117227901160 (0x1b4b53d0e8)
        Total header overhead = 334241544 (0x13ec1f08)
        Total stream length = 117562143016 (0x1b5f3ff128)
```

On my old server there were some error with a Bad RIP value.
I was able to find similar messages in my kernel as well...

Is there any way I can try to recover the files?
Is there a Tool? Something?

**Comment by Flyffies** [comment]
I just ran zstreamdump again an redirected the output into a file... It looks like all of the output except the first record is zeroes...

Might it be possible to recover the old pool? could that be a possiblility? Sadly I already created the new pool...

**Comment by Flyffies** [comment]
Would It be possible to ignore the zeroed records during a receive? Maybe something could be recovered instead of nothing?

**Comment by ahrens** [comment]
I don't know how you would do that.

**Comment by Flyffies** [comment]
Today I might have a bit more information.

It seems the snaphot somehow contains multiple BEGIN recors at the end of the file...
I could also "grep" through the snapshot and find data that was contained in my files.

I would want to try and remove these tailing zero begin recors (and probably add a matching end record?). Where could I find more information about the binary format itself?

**Comment by Flyffies** [comment]
Ok, I made progress. 
I am able to import 106 Gb of the 117 Gb ZFS. Sadly I am not just able to mount it when using `receive -s`.

Could that somehow be achieved? Not aborting an incomplete transfer, but just take it "as is" and mount it?
