### ISSUE TITLE
request: to stop locking comment sections

### ISSUE THREAD

**Issue by misterbigstuff** [openzfs/zfs#10459]
as I just posted an issue as a person of colour asking to have my thoughts considered, it was closed to discussion and locked as **too heated**.

this is a pretty blatant indicator that you didn't care about race relations at all.

please stop locking all the comment sections for these IMPORTANT ISSUES you supposedly want to further and support.

**Comment by misterbigstuff** [comment]
because black comments matter..

**Comment by ahrens** [comment]
As I indicated in https://github.com/openzfs/zfs/issues/10458, I'm open to a discussion on this.  However, we have seen that when comments are open to anyone, the discussion quickly becomes dominated by people who are not involved in ZFS development, and too heated to be productive.  (e.g. reddit, ars technica).

I believe that as the OP you should be able to continue to post to locked issues.  Members of the OpenZFS github organization can also continue to post to locked issues.

**Comment by ahrens** [comment]
I determined that even the OP can't post on locked issues (unless they are a member of the organization).  I didn't hear from you privately, so I'm going to unlock the other issue and continue the discussion there.
