### ISSUE TITLE
kmod Packages for RHEL/OL/CentOS 8.2 missing

### ISSUE THREAD

**Issue by rgessner** [openzfs/zfs#10466]
RHEL 8.2 was released 2020-04-28
OL 8.2 was released 2020-05-06
Yesterday 2020-06-15 CentOS 8.2 was finally released.

Unfortunately CentOS 8.x is lagging behind the RHEL 8.x release for a long time. I fear that this situation will not change in the future. If I remember correctly the ZFS kmod packages for RHEL are built on CentOS AMI.

Would it be possible to build the ZFS kmod packages on a RHEL or Oracle Linux system?

This would make it possible to provide the appropriate kmod packages more quickly.

**Comment by hseara** [comment]
Do you have an estimate on when we can expect the Centos 8.2 rpm release?

Another related question. The update to centos 8.2 yesterday came to me as a surprise. When I realized what was happening the update was already completed and zfs was non operational, still is. Do you suggest to use ZFS DKMS in the future to avoid such an issue?

**Comment by madalincolea** [comment]
Same issue here. Had to switch to the DKMS version for the moment until the kMod one is available for 8.2 --hopefully soon enough, as having all the dependencies of DKMS building on a server is a real concern.

**Comment by tonyhutter** [comment]
I've got the updated RPMs built and they're going though test.  I'll try to have them available tomorrow.

**Comment by tonyhutter** [comment]
RPMs are out - let me know if you have any issues. 

http://download.zfsonlinux.org/epel/zfs-release.el8_2.noarch.rpm

**Comment by madalincolea** [comment]
No issues here. Switch from DKM back to kMod went just find. Thank you!
