### ISSUE TITLE
FATAL: Module zfs not found in directory /lib/modules/4.18.0-193.6.3.el8_2.x86_64

### ISSUE THREAD

**Issue by jamielsharief** [openzfs/zfs#10465]
I am trying to install ZFS on Redhat 8.1 but `sudo lsmod | grep zfs` returns nothing, and when i run  `sudo modprobe zfs` I get  `FATAL: Module zfs not found in directory /lib/modules/4.18.0-193.6.3.el8_2.x86_64`

Here are my installation instructions

```
yum install http://download.zfsonlinux.org/epel/zfs-release.el8_1.noarch.rpm
yum-config-manager --disable zfs
yum-config-manager --enable zfs-kmod
yum install zfs
reboot
```

**Comment by rgessner** [comment]
`4.18.0-193.6.3.el8_2.x86_64 `

Looks like you are runing CentOS 8.2.2004 (wich was released yesterday).
Take a look at `/etc/redhat-release` on your system.

There are no kmod packages for 8.2 at this point.

**Comment by jamielsharief** [comment]
I have tried on both Redhat 8.1 and CentOS 8.1, and it seems you are right, at some point the system is getting upgraded from 8.1 to 8.2 

```
$ cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core) 
```

**Comment by rgessner** [comment]
i opened #10466 for the issue of the missing packages for 8.2

**Comment by jamielsharief** [comment]
Thats great!!! Right now a simple update of the system breaks everything. Thanks for your help.

**Comment by jamielsharief** [comment]
Just wanted to get back and say thanks, 23 hours later, its working. My first issue was downloading driver 8.1 for 8.2, then installing 8.1 and updating to 8.2 as part of my initial server setup. doh!!!

**Comment by madalincolea** [comment]
> Just wanted to get back and say thanks, 23 hours later, its working. My first issue was downloading driver 8.1 for 8.2, then installing 8.1 and updating to 8.2 as part of my initial server setup. doh!!!

Did you manage to update the kMod zfs driver from the 8.1 repo? Or are you using DKMS?

I couldn't update from 8.1 the kmod package as it's still compiled for 4.18.147. :(

**Comment by jamielsharief** [comment]
> > Just wanted to get back and say thanks, 23 hours later, its working. My first issue was downloading driver 8.1 for 8.2, then installing 8.1 and updating to 8.2 as part of my initial server setup. doh!!!
> 
> Did you manage to update the kMod zfs driver from the 8.1 repo? Or are you using DKMS?
> 
> I couldn't update from 8.1 the kmod package as it's still compiled for 4.18.147. :(

On the ZFS page is particular instructions for [upgrading](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html), I am doing this on a fresh install. This is how I am doing this, note don't run `yum update` or `dnf update` as that will mess things up.

```
$ yum install yum-utils
$ yum install http://download.zfsonlinux.org/epel/zfs-release.el8_1.noarch.rpm
$ yum-config-manager --disable zfs
$  yum-config-manager --enable zfs-kmod
$ yum install zfs
$ reboot
```
