### ISSUE TITLE
zfs send/recv zvol with different volblocksize

### ISSUE THREAD

**Issue by Tualua** [openzfs/zfs#10478]
Hello!

Is it possible to send/receive between zvols with different volblocksize?
I have a zvol with 8k and I want to replicate data to another zvol on wich I want to set volblocksize to 64k.

**Comment by misterbigstuff** [comment]
you could have just run the command to test it - but no.

**Comment by ghfields** [comment]
I believe this discussion from the past week on the zfsonlinux mailing list may have your answer.  The answer looks to be "no".

https://zfsonlinux.topicbox.com/groups/zfs-discuss/T0aa911d8152859b9/changing-recordsize-volblocksize-during-zfs-receive

**Comment by Tualua** [comment]
> you could have just run the command to test it - but no.

Why do you think I asked? Tried without any luck

**Comment by Tualua** [comment]
> I believe this discussion from the past week on the zfsonlinux mailing list may have your answer. The answer looks to be "no".
> 
> https://zfsonlinux.topicbox.com/groups/zfs-discuss/T0aa911d8152859b9/changing-recordsize-volblocksize-during-zfs-receive

Thanks. Looks like its impossible. The only way is to use dd from one zvol to another but then I believe I will lose ability to send snapshots from first pool to second
