### ISSUE TITLE
Request for '-x' option to 'zfs receive'.

### ISSUE THREAD

**Issue by dswartz** [openzfs/zfs#1050]
This is supported by the latest solaris ZFS.  Allows you to 'zfs send -p', sending all properties over, but the 'zfs receive' can override a specified set.  For example 'zfs send -p xxxx | zfs recv -x mountpoint' to pass along all properties _except_ the mountpoint.

**Comment by tristan-k** [comment]
Has this been merged? There is no documentation in the manpage for `zfs receive -x` on Ubuntu 16.04 LTS.
