### ISSUE TITLE
zfs ignores umask for nfs4.2 mounted files unless acltype=posixacl

### ISSUE THREAD

**Issue by dd1dd1** [openzfs/zfs#10504]
server has zfs 0.8.3.1, ubuntu clients (LTS 18.04, LTS 20.04) and centos-8 clients mount zfs volume with nfs4.2 and umask does not work: umask is set to 0022, but all files are created with world-writable permissions (bad!) unless I do "zfs set acltype=posixacl zpool/...". Then umask works correctly. Please fix, umask should work with the default zfs settings. Ask for more details through comments in this issue. Big thanks in advance!

daq01:olchansk$ umask
0022
daq01:olchansk$ ls -l xxx
ls: cannot access 'xxx': No such file or directory
daq01:olchansk$ touch xxx
daq01:olchansk$ ls -l xxx
-rw-rw-rw- 1 olchansk users 0 Jun 26 07:46 xxx
daq01:olchansk$ 

zfs volume settings: (umask does not work)

[root@daqstore ~]# zfs get all pool/daqstore | grep acl
pool/daqstore  aclinherit            restricted             default
pool/daqstore  acltype               off                    default
[root@daqstore ~]# 

zfs volume settings: (umask works correctly)

[root@daqstore ~]# zfs get all zssd1tb/home1 | grep acl
zssd1tb/home1  aclinherit            restricted             default
zssd1tb/home1  acltype               posixacl               local
[root@daqstore ~]# 

For CentOS 7 clients, nfs4.1 is used and umask works correctly.
For CentOS 8 clients, nfs4.2 is used and umask does not work.
For Ubuntu LTS 18.04 server (ZFS 0.7.5), and client, nfs4.2, same thing.
For Ubuntu LTS 20.04, cannot test yet.

See also:
https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1779736
K.O.

**Comment by behlendorf** [comment]
ZFS's expectation is that the VFS will apply the umask but it sounds like that isn't the case when the file is created via nfs4.2.  Would it be possible for you to verify the following small patch fixes the issue?  It effectively always applies the umask when posixacls aren't enabled and doesn't rely on the VFS having done it.

```diff
diff --git a/module/os/linux/zfs/zpl_xattr.c b/module/os/linux/zfs/zpl_xattr.c
index fa3c036..9f60c30 100644
--- a/module/os/linux/zfs/zpl_xattr.c
+++ b/module/os/linux/zfs/zpl_xattr.c
@@ -1058,8 +1058,10 @@ zpl_init_acl(struct inode *ip, struct inode *dir)
        struct posix_acl *acl = NULL;
        int error = 0;
 
-       if (ITOZSB(ip)->z_acl_type != ZFS_ACLTYPE_POSIXACL)
+       if (ITOZSB(ip)->z_acl_type != ZFS_ACLTYPE_POSIXACL) {
+               ip->i_mode &= ~current_umask();
                return (0);
+       }
 
        if (!S_ISLNK(ip->i_mode)) {
                acl = zpl_get_acl(dir, ACL_TYPE_DEFAULT);
```

**Comment by dd1dd1** [comment]
Hi, thank you for quick reply. I am surprised by this, I expected umask to be applied by vfs in the nfs client, so nfs version and back-end filesystem do not matter. Not so, I guess.

 I cannot build a patched version of zfs quickly. If you can provide a patched binary module (I guess for CentOS-7), I can test it easily, but I see how this may not be practical for you. I will try and get around to building a patched version (also add a printk(ip->i_mode) to definitely show whether files come to zfs with the wrong access mode. K.O.

**Comment by behlendorf** [comment]
Reopening, this is related to #8998 and should be verified.
