### ISSUE TITLE
zpool import value to large

### ISSUE THREAD

**Issue by badlandz** [openzfs/zfs#10537]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Linux Mint
Distribution Version	| 20.04
Linux Kernel	| 5.4.0-40-generic
Architecture	| x86_64 (AMD64)
ZFS Version	| 0.8.3-1ubuntu12.1
SPL Version	| 0.8.3-1ubuntu12.1

### Describe the problem you're observing

My zfs 3 disk zpool of all my important data doesn't want to import back after formating my OS drive and reinstalling and trying to reimport. (Went from Mint 19 to 20, imported once, OS reboot, after reboot, then won't mount again).

Was zpool at /home, have new /home on SSD, intended to mount zpool zhome to /zhome, and rsync back to /home, then create new pools with new drives, but something went tragically wrong. 
```
$ sudo zpool import -R /zhome zhome
internal error: Value too large for defined data type
Aborted
```

To be clear, the same command worked when I first got the new OS going, there was an rsync FROM the zpool running from /zhome/user/dir1 to /home/user/dir1 (large one that would have taken 3 days that I forgot about) and I rebooted. After the reboot, trying to import the zpool again gave this error.

Any idea what to try?

### Describe how to reproduce the problem

For others, no idea. For me, running:
`sudo zpool import -R /zhome zhome`

**Comment by ahrens** [comment]
After running the `zpool import`, run `cat /proc/spl/kstat/zfs/dbgmsg` and paste the output here.

**Comment by badlandz** [comment]
Hi Ahrens, errors no longer there. I managed to get things partially fixed (with some data loss). The 3 disk pool was a 4TB, 5TB,a nd 6TB. The 5TB partition table was messed up (looked like a USB boot image was written to it). 

So, I did some investigation and realized there was an 8M /dev/sdx9 on the other two drives at the last "natural" segment that fdisk seemed to want to allow, so I played around in fdisk until I could create that exact size (in sectors) on the disk, then put a /dev/sdx1 for the remaining unused space. Then toggled the partition types until they matched the other two disks. And it imported, so I scrubbed it. Lost about 40 large files, but compared to what I was thinking I was going to lose (all 15TB), it's not that bad.

The manual configuration of the partitions, and making sure the sectors were exactly right took forever by hand. Would be handy if I knew what "zpool create" did when it created them, so I could just run a script to fix partitions. But, that's a project for another day. :-) Thanks though.

**Comment by Nottt** [comment]
I have the same issue, and oh boy how is difficult to find anything related to this error. 

See here what I posted about the same issue happening randomly to my pool after clean reboots

https://github.com/openzfs/zfs/issues/1385#issuecomment-2781206264
