### ISSUE TITLE
ZFS performance issues on high concurrency - 70% native_queued_spin_lock_slowpath overhead

### ISSUE THREAD

**Issue by denogio** [openzfs/zfs#10547]
We're running multiple Dell R6515 with a single AMD EPYC 7302P. We then have a boot device and for zfs we have two P4510 NVMe's mirrored.

OS is Debian 10.4 , but also tested on Ubuntu 18.04 and 20.04.

We use these machines for webhosting. Benchmarking the zpool with fio always gave OK results.

We host websites, and sometimes customers need extra capacity, and then we start to see unexpected performance. Load starts to pile up, and top never showed any io wait, so we never thought that zfs was the main issue. We actually thought it was the AMD EPYC CPUs that did not scale well at high concurrency, but this week we've had time to create a debugging environment and we were VERY surprised to see that actually our main headache was related to the storage layer. We tried putting files on a single xfs formated NVMe, and where our stress-test gave us 15 Rps (request per second) on the ZFS mirro, with a single XFS nvme we had a much more predictable behavior and got 130 Rps in the test.

High load on zfs in top shows that while 5% of cpu usage is in userspace, approx 90-95% is in system as in kernel. Digging further in with perf top shows 75% overhead for native_queued_spin_lock_slowpath, which seems crazy. With XFS, and btrfs for that matter native_queued_spin_lock_slowpath is not even in the list.

We've tried all possible configuration adjustments for zfs and kernel, but no notable performance improvements were seen, except for changing filesystem.

**Comment by earl86** [comment]
I test mysql on xfs, on AMD 7702 ,there is the same like you.
Samples: 3M of event 'cycles', 4000 Hz, Event count (approx.): 2123823803012 lost: 0/0 drop: 0/0                                                                                                                                        
Overhead  Shared Object        Symbol                                                                                                                                                                                                   
  60.57%  [kernel]             [k] native_queued_spin_lock_slowpath
  14.83%  libpthread-2.17.so   [.] pthread_mutex_lock

**Comment by dhpowrhost** [comment]
@earl86 
Yeah i have also replicated this on a softwareraid and lvm, however the performance is better on lvm. 
Did you manage to solve this issue?

**Comment by cyberspicecai** [comment]
> 

mysql has the lock of rw_lock_sx_lock_func, if you dig further, the reason is that mysql will  update the row/record. As you know the database needs ACID, the more the users in mysql, the more percentage of native_queued_spin_lock_slowpath.

**Comment by useribs** [comment]
Anyone managed to find a workaround? Latest PVE 8.3 and fio benchmarks on a pool provide 50-80% system CPU load with 50% overhead in __pv_queued_spin_lock_slowpath

**Comment by amotin** [comment]
@useribs If you have a problem, please create a new issue with all relevant details, flamegraphs, etc instead of galvanizing this corpse of 4 year ago that may have nothing common with your case.  Now all you are saying is that some system is unhappy inside some VM, that, even if related to ZFS, you don't point how.
