### ISSUE TITLE
ARC adapation logic is broken and fix was not imported from FreeBSD to OpenZFS.

### ISSUE THREAD

**Issue by blacklion** [openzfs/zfs#10548]
ARC is one of main parts of ZFS success, as it is state-of-art cache algorithm. Its novelty is using of additional «ghost» LRU and MRU lists which remember evicted items and help to tune LRU/MRU balance. Center part of ARC algorithm is `arc_adap()` function which tune LRU/MLU balance according to 4 types of cache hits (which is passed as `state` agrument): ghost LRU, LRU, MRU, ghost MRU. If this function will be called with wrong cache hit (`state`) adaptation will be sub-optimal and performance will suffer.

Some (long) time ago upstream had been received this commit:

6950 ARC should cache compressed data) in arc_read() do next sequence (access to ghost buffer)

Before this commit, hit to any ghost list was passed `arc_adapt()` before call to `arc_access()` which revive element in cache and change state from ghost to real hit (it is very important!)

After this commit order of calls was reverted and `arc_adapt()` is now called only with «real» hits even if hit was in one of two ghost lists, which render ghost lists useless and break ARC algorithm.

FreeBSD fixes this problem locally in [Change D19094](https://reviews.freebsd.org/D19094) / [Commit r348772](https://svnweb.freebsd.org/base/head/sys/cddl/contrib/opensolaris/uts/common/fs/zfs/arc.c?view=log&pathrev=348772).

This fix have not been ported to upstream, ZoL or OpenZFS, unfortunately.

Current OpenZFS contains same bug, though patch is not applicable, as low-level ARC routines were extended, which is not present in FreeBSD sources.

Crucial change is [this one, in `arc_get_data_impl`](https://svnweb.freebsd.org/base/head/sys/cddl/contrib/opensolaris/uts/common/fs/zfs/arc.c?revision=348772&view=markup&pathrev=348772). All other changes are support this one, to weave proper behavior (adapt or not adapt before changing status of cache element) from call sites of `arc_hdr_alloc_pabd()` (which is named `arc_hdr_alloc_abd()` in OpenZFS).

Without this change ARC in OpenZFS is not ARC at all, and there could be serious performance degradation in some scenarios.

I think, it should be fixed before FreeBSD transition to OpenZFS and this fix will be beneficial for whole OpenZFS community.

**Comment by freqlabs** [comment]
To be clear, this isn't actually in progress, so if anyone is willing to take it up please do :)

**Comment by mattmacy** [comment]
And to be clear, I'd asked @blacklion to file a PR, not an issue.

**Comment by blacklion** [comment]
BTW, original fix will be even worse on new codebase: it will add *second* boolean parameter to some functions (it adds first one in FreeBSD codebase, but OpenZFS added its own boolean parameter to same functions!). It is nightmare from API's point of view: it is very easy to mix two boolean parameters at call sites, as booleans are indistinguishable.

**Comment by mattmacy** [comment]
@blacklion I'll update the interfaces to take a flag

**Comment by blacklion** [comment]
@mattmacy Thank you very much!

**Comment by shodanshok** [comment]
Any chances to see this backported in the 0.8.x releases?

**Comment by behlendorf** [comment]
Possibly if it's not to troublesome to port, the PR was added to the 0.8 tracker.
