### ISSUE TITLE
0.8.4: Fedora 32 and dkms 2.8.2 build - nothing happens

### ISSUE THREAD

**Issue by space88man** [openzfs/zfs#10567]
### System information

Type | Version/Name
--- | ---
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.7.7, 5.7.8
Architecture	| x86_64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

Working dkms RPM: dkms-2.8.1-4.20200214git5ca628c.fc32.noarch
Failing dkms RPM: dkms-2.8.2-1.fc32.noarch
### Describe the problem you're observing

When zfs-dkms is built with dkms 2.8.2 nothing happens. No error messages, process exits with code 0.

```
# With dkms 2.8.2
# dkms build  -m zfs -v 0.8.4 -k 5.7.8-200.fc32.x86_64
# # absolutely nothing happens

# With dkms 2.8.1
Kernel preparation unnecessary for this kernel.  Skipping...                                                                                     
                                                                        
Running the pre_build script:                                           
checking for gawk... gawk                                               
checking metadata... META file                                          
checking build system type... x86_64-pc-linux-gnu                       
checking host system type... x86_64-pc-linux-gnu                        
checking target system type... x86_64-pc-linux-gnu                                                                                               
checking whether to enable maintainer-specific portions of Makefiles... no                                                                       
checking whether make supports nested variables... yes                                                                                           
checking for a BSD-compatible install... /bin/install -c                                                                                         
checking whether build environment is sane... yes                       
checking for a thread-safe mkdir -p... /bin/mkdir -p     
checking whether make sets $(MAKE)... yes                               
checking for gcc... gcc                                                                                                                          
checking whether the C compiler works... yes                                                                                                     
checking for C compiler default output file name... a.out               



```

### Describe how to reproduce the problem

Build zfs-dkms with dkms 2.8.2

### Include any warning/errors/backtraces from the system logs
None

### Additional Information 

* When dkms is reverted to dkms-2.8.1-4.20200214git5ca628c.fc32.noarch build/install works
* This may not be a ZFS bug but just some weird interaction with dkms 2.8.2

**Comment by almereyda** [comment]
I can confirm that reverting to `dkms-2.8.1-4.20200214git5ca628c.fc32.noarch.rpm` allows to build the ZFS Kernel modules, whereas `dkms-2.8.2-1` silently fails with it.

As a surprise, the module will not exist either way, and loading the module fails.

```
# modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.7.8-200.fc32.x86_64
```

This will not happen, when one chooses to run `dkms install zfs/0.8.4` after the build, prior to running `modprobe`.

**Comment by almereyda** [comment]
For other people landing here, i.e. via some search results, it appears useful to leave a note, that one will also wish to prevent the package to update, until this issue is resolved.

After reinstalling the desired version with

    dnf install dkms-2.8.1-4.20200214git5ca628c.fc32.noarch

each invocation of `dnf update` needs to exclude that package.

    dnf --exclude dkms update

To keep this exclusion permanently, it can be added to the dnf configuration.

    echo "exclude = dkms" >> /etc/dnf/dnf.conf

**Comment by scaronni** [comment]
Just pushed DKMS version 2.8.3 with the fix, will update Fedora/EPEL immediately.

**Comment by space88man** [comment]
Closing as it is a DKMS bug.
