### ISSUE TITLE
dbuf cache size is 1/32nd what was intended

### ISSUE THREAD

**Issue by ahrens** [openzfs/zfs#10563]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	| 17ca30185af139588b9617ca0bdbf57027bd3303
SPL Version	|

### Describe the problem you're observing

The size of the dbuf cache is supposed to be ~1/32nd of memory (plus 1/64th of memory for MOS metadata).  However, it's actually 1/1024th of memory.

The problem is that 17ca30185af139588b9617ca0bdbf57027bd3303 changed the starting ARC size from arc_c_max to arc_c_min.  The dbuf cache size is based on `arc_target_bytes()`, which is based on the current ARC target size (arc_c).  See `dbuf_init()`.

One way to fix this would be to make dbuf cache size based on `arc_c_max`, instead of `arc_c`.  We would also need to change `dbuf_cache_target_bytes()`.

@amotin @behlendorf 

### Describe how to reproduce the problem
`grep target /proc/spl/kstat/zfs/dbufstats`

**Comment by amotin** [comment]
It seems weird to me that dbuf_cache_max_bytes is initialized based on arc_target_bytes(), considering the same value (just able to grow) is used as a dynamic limit in run time by dbuf_cache_target_bytes.  I am not exactly sure why do we need the second limit, unless it is set explicitly by administrator via tunable.  From that point initialization to percent of arc_max would look more reasonable, but even some ULONG_MAX would work just fine.

**Comment by ahrens** [comment]
@amotin I agree for `dbuf_cache_max_bytes`.  For `dbuf_metadata_cache_max_bytes`, it's a fixed size so `ULONG_MAX` wouldn't work, we would need to use `arc_max >> dbuf_metadata_cache_shift`.
