### ISSUE TITLE
Broken zfs.ko build on CentOS 7 after commit

### ISSUE THREAD

**Issue by angstymeat** [openzfs/zfs#10565]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7
Linux Kernel	| 4.4.223-1.el7.elrepo.x86_64
Architecture	| x86_64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
I am running CentOS 7 with the LT long-term support kernel 4.4. I have been running this for a few years without issues compiling master.

Today I started having failures loading the zfs module after compilation:
`modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)`

Trying to load the module also generates this in dmesg:
`zfs: Unknown symbol has_capability (err 0)`

The SPL module does load correctly.

I've tracked it down to this commit: e59a377a8fdbf4e66864d1654c0055fdff5f12f4 (that's the one where it starts to fail)

### Describe how to reproduce the problem
Compile using the linux LT kernel from elrepo.

### Include any warning/errors/backtraces from the system logs
```
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
```

**Comment by nivedita76** [comment]
Looks like it only got exported in v4.10.

https://github.com/torvalds/linux/commit/19c816e8e455f58da9997e4c6626f06203d8fbf0

**Comment by angstymeat** [comment]
It looks like it works on the standard CentOS 7 3.10.0 kernel.

I don't have another virtual machine running 4.X to test at the moment.

**Comment by IslandLife** [comment]
I have seen exactly this same problem in Ubuntu . While 0.8.0-911 was OK -912 is not.
On the command line
```
root@somehost:~# zpool list
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
root@somehost:~# /sbin/modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

```
and in /var/log/syslog you see something like this
```
Jul 14 13:02:41 somehost systemd-udevd[659]: Process '/sbin/modprobe zfs' failed with exit code 1.
Jul 14 13:02:41 somehost kernel: [   17.223745] zfs: Unknown symbol has_capability (err 0)
Jul 14 13:02:41 somehost modprobe[2035]: modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
```

**Comment by rdolbeau** [comment]
I also see the problem on a Jetson TX1 running 4.9.140-tegra. I suspect, as @nivedita76 mentioned, this is broken on all pre-4.10 kernel.

Disabling the two offending lines enable a working module:

```
--- a/module/os/linux/zfs/policy.c
+++ b/module/os/linux/zfs/policy.c
@@ -253,8 +253,8 @@ secpolicy_zfs(const cred_t *cr)
 int
 secpolicy_zfs_proc(const cred_t *cr, proc_t *proc)
 {
-	if (!has_capability(proc, CAP_SYS_ADMIN))
-		return (EACCES);
+//	if (!has_capability(proc, CAP_SYS_ADMIN))
+//		return (EACCES);
 	return (0);
 }
```

Although obviously, that is not the 'proper' fix.

**Comment by ahrens** [comment]
Thanks for reporting this and exposing a gap in our testing, which runs on a more recent update of CentOS 7.

We'll look into adding an autoconf check to only use the "new" interface when available.

**Comment by behlendorf** [comment]
I've opened PR #10573 to address this.  For kernels without this functionality we revert to the previous behavior.
