### ISSUE TITLE
Error making RPMs: xxx.in has shebang which doesn't start with '/' (@DEFAULT_INIT_SHELL@)

### ISSUE THREAD

**Issue by dioni21** [openzfs/zfs#10581]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| fc31
Linux Kernel	| 5.7.7-100.fc31.x86_64
Architecture	| x86_64
ZFS Version	| 23c871671c7bc2c79ad6ec1804715f405058cdb6
SPL Version	| XXX

### Describe the problem you're observing
Cannot make rpm-dkms

### Describe how to reproduce the problem
- Clone a new repo
./autogen.sh
./configure
make -j 12
make -j 12 rpm-utils
make -j 12 rpm-dkms

### Include any warning/errors/backtraces from the system logs

Latest messages are:
```
mangling shebang in /usr/src/zfs-0.8.0/contrib/bpftrace/zfs-trace.sh from /bin/sh to #!/usr/bin/sh
*** ERROR: ./usr/src/zfs-0.8.0/etc/init.d/zfs-import.in has shebang which doesn't start with '/' (@DEFAULT_INIT_SHELL@)
*** ERROR: ./usr/src/zfs-0.8.0/etc/init.d/zfs-zed.in has shebang which doesn't start with '/' (@DEFAULT_INIT_SHELL@)
*** ERROR: ./usr/src/zfs-0.8.0/etc/init.d/zfs-mount.in has shebang which doesn't start with '/' (@DEFAULT_INIT_SHELL@)
*** ERROR: ./usr/src/zfs-0.8.0/etc/init.d/zfs-share.in has shebang which doesn't start with '/' (@DEFAULT_INIT_SHELL@)
mangling shebang in /usr/src/zfs-0.8.0/etc/systemd/system-generators/zfs-mount-generator.in from /bin/sh to #!/usr/bin/sh
error: Bad exit status from /tmp/zfs-build-jonny-66Dh21wP/TMP/rpm-tmp.GJkfAS (%install)


RPM build errors:
    line 30: It's not recommended to have unversioned Obsoletes: Obsoletes:      spl-dkms
    Bad exit status from /tmp/zfs-build-jonny-66Dh21wP/TMP/rpm-tmp.GJkfAS (%install)
make[1]: *** [Makefile:1613: rpm-common] Error 1
make[1]: Leaving directory '/root/zfs/zfs'
make: *** [Makefile:1568: rpm-dkms] Error 2
```

**Comment by dioni21** [comment]
@nivedita76 I think this is yours...

**Comment by nivedita76** [comment]
I’ll take a look.

________________________________

**Comment by nivedita76** [comment]
@behlendorf the dkms RPM has to install the entire source tree?

I think the breakage is due to my making etc/init.d/*.in executable, which makes mangle-shebangs complain about them because they're installed with everything else in the dkms RPM.

**Comment by nivedita76** [comment]
@dioni21 can you test if the PR fixes this for you? Unfortunately I have gentoo and the compatibility rpm utility it provides doesn't seem to have shebang mangling.

**Comment by dioni21** [comment]
Problem solved.  Thanks...
