### ISSUE TITLE
How to install ZFS binaries but without the DKMS module on Fedora

### ISSUE THREAD

**Issue by kaspergrubbe** [openzfs/zfs#10588]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| Fedora 31
Linux Kernel	| 5.7.8
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing

I am building my own kernels, and I'm using the zfs flag `--enable-linux-builtin` and with `CONFIG_ZFS=y` in the kernels `.config`-file.

I have installed ZFS following the guide here: https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html

```bash
dnf install http://download.zfsonlinux.org/fedora/zfs-release.fc31.noarch.rpm
dnf install zfs
```

Is there a way of building the userspace tools such as `zpool` and the `systemd` configurations, but without installing DKMS?

**Comment by rincebrain** [comment]
The packages built from the OpenZFS RPM specs have the userland utilities package [depend on zfs-kmod](https://github.com/openzfs/zfs/blob/7457b024ba2be2cf742e07239c20a1c3f3fa9c72/rpm/generic/zfs.spec.in#L127), which is [also provided by zfs-dkms](https://github.com/openzfs/zfs/blob/7457b024ba2be2cf742e07239c20a1c3f3fa9c72/rpm/generic/zfs-dkms.spec.in#L32) - if you wanted your custom kernel packages to not trigger installing zfs-{kmod,dkms}, you could have those kernel packages provide zfs-kmod-[whatever version].

**Comment by pirate** [comment]
@kaspergrubbe you may find this project helpful: https://github.com/pirate/zfsbox
