### ISSUE TITLE
zfs rename fails as non-root user with permission

### ISSUE THREAD

**Issue by selbitschka** [openzfs/zfs#10587]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| LinuxMint
Distribution Version	| 20 (ulyana)
Linux Kernel	| 5.4.0-40
Architecture	|amd64
ZFS Version	|0.8.3-1ubuntu12
SPL Version	|0.8.3-1ubuntu12

### Describe the problem you're observing
Try to delegate permission on creating an renaming snapshot to a non-root user. While the creation of a snapshot works, renaming fails with `cannot rename 'snapshotname': permission denied`. User who try to rename snapshot has `rename` right.

### Describe how to reproduce the problem
Take non-root user i.e. `dummy` and allow several right to create and rename a snapshot:
```
zfs allow -u dummy send,snapshot,hold,destroy,mount,rename,release tank/data
zfs allow tank/data
---- Permissions on tank/data -------------------------
Local+Descendent permissions:
	user dummy destroy,hold,mount,release,rename,send,snapshot
```
Now create a snapshot with as user `dummy` and try to rename it
```
sudo -u zfsbackup zfs snapshot tank/data@test
sudo -u zfsbackup zfs rename tank/data@test tank/data@test2
```
### Include any warning/errors/backtraces from the system logs
```
cannot rename 'tank/data@test': permission denied
```
Unfortunately `zfs rename` has no option `-v` so I didn't get any hint other cause of this problem.

**Comment by mskarbek** [comment]
And you won't be able to rename as a non-root user regardless of the fact that such a user has propper rights set in ZFS. Snapshots are mounted which means you have to unmount it before you can rename it and unmounting is a system operation not ZFS operation that requires root privileges. The non-root user doesn't have the right to do that on Linux.

**Comment by selbitschka** [comment]
If this is the case shouldn't the `zfs snapshot` fail with the same error, since this cause a mount? Also a `zfs destroy %snapshot%` should fail as well, not?

**Comment by scineram** [comment]
Why would it?
