### ISSUE TITLE
[feature] non-sudo dataset management under $HOME

### ISSUE THREAD

**Issue by RJVB** [openzfs/zfs#10596]
I don't think it is currently possible to do any kind of dataset management for anyone but root. I haven't looked closely at the existing possibilities to grant permissions to non-root users, but from what I've seen they're all selective alternatives to making the zfs binary SETUID root.

I have been using ZFS as my primary FS on several (essentially single-user) Linux rigs now; the additional reliability (with copies=N) and flexibility (datasets instead of fixed-size partitions) far outweigh the few drawbacks (RAM requirements, performance). But even as the sole and thus admin user I would prefer localised/selective permissions, obliging me to use sudo to modify crucial/system datasets while still being able to manage other ("my own") datasets freely. For instance those created under $HOME, or with a mountpoint under a location I own, or as a child of a designated dataset (created and configured by root).

I think that what I actually have in mind is a possibility to use datasets as a kind of atomic handle on directories, basically allowing things like `zfs dir create /path/to/frigginbigworkdir` followed at some later point by `zfs dir destroy|delete /path/to/frigginbigworkdir` (which would be near instantaneous rather than potentially take an hour like `rm -rf /path/to/frigginbigworkdir` can).

Thoughts?
Thoughts?

**Comment by rlaager** [comment]
I think the practical answer is that creating and mounting filesystems were traditionally privileged operations. On traditional filesystems, obviously that makes a lot of sense. While that matters _less_ in ZFS, I think it does still make sense. Datasets can and frequently are used in a "policy" way. For example, datasets may be replicated as part of a backup strategy, and snapshots are used and expired per a retention policy.

Anyway `zfs allow` is the official answer to this.
