### ISSUE TITLE
zpool destroy doesn't remove FSTYPE label

### ISSUE THREAD

**Issue by Hi-Angel** [openzfs/zfs#10598]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.19.107
Architecture	| x86_64
ZFS Version	| 0.8.0-932_g317dbea17
SPL Version	| 0.8.0-932_g317dbea17

### Describe the problem you're observing

After a pool is created, zfs sets on devices that consitute the pool a FSTYPE "zfs_member". However upon removing the pool the FSTYPE is not removed, thus confusing into thinking that the device is still in use by some FS.

### Describe how to reproduce the problem

Two notes:

* In steps a `/dev/sda1` device is used to create a pool upon. Consitute it with any other to reproduce it.
* `zpool create` randomly does not set the label. To make sure it is created in steps I call it along with `destroy` in a cycle.

Steps to reproduce in terms of terminal commands:

```
$ lsblk -f /dev/sda
NAME   FSTYPE LABEL UUID MOUNTPOINT
sda
├─sda1
└─sda9
$ for _ in {1..10}; do zpool create test_pool /dev/sda1 && zpool destroy test_pool; done
$ zpool list
no pools available
$ lsblk -f /dev/sda
NAME   FSTYPE     LABEL     UUID                                 MOUNTPOINT
sda
├─sda1 zfs_member test_pool 13892132091355807852
└─sda9
```

#### Expected

FSTYPE is empty

#### Actual

FSTYPE is set to `zfs_member`

**Comment by richardelling** [comment]
A destroyed pool is simply marked as destroyed. And it can be re-imported (undestroyed). If you want to wipe the pool off of the disk, then use something like `wipefs`

**Comment by Hi-Angel** [comment]
Okay, I see, so it is intended that after pool destruction users need to manually call `zpool_clear_label` or an analog. Closing then.
