### ISSUE TITLE
dkms build fails because of missing sys/socket.h (kernel 4.19.133)

### ISSUE THREAD

**Issue by RJVB** [openzfs/zfs#10601]
### System information
Type | Version/Name
 --- | --- Linux
Distribution Name	| Kubuntu
Distribution Version	| 14.04 kept up to date manually
Linux Kernel	| 4.19.133
Architecture	| x86_64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4
### Describe the problem you're observing
the kernel modules fail to build under/against 4.19.133 but build fine against 4.14.23

### Describe how to reproduce the problem
sudo dkms build zfs/0.8.4 -k 4.19.133

### Include any warning/errors/backtraces from the system logs
Relevant bit from "make.log":

```
  gcc -Wp,-MD,/var/lib/dkms/zfs/0.8.4/build/module/icp/.illumos-crypto.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-li
nux-gnu/9/include -I/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/arch/x86/include -I./arch/x86/include/gen
erated  -I/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include -I./include -I/usr/src/linux-headers-4.19.1
33-ck1-mainline-core2-rjvb/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/src/linux-headers-4.19.13
3-ck1-mainline-core2-rjvb/include/uapi -I./include/generated/uapi -include /usr/src/linux-headers-4.19.133-ck1-mainli
ne-core2-rjvb/include/linux/kconfig.h -include /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/
compiler_types.h  -I/var/lib/dkms/zfs/0.8.4/build/module/icp -I/var/lib/dkms/zfs/0.8.4/build/module/icp -D__KERNEL__ 
-Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-func
tion-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falig
n-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=core2 -m
no-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -D
CONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_
AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindire
ct-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address
 -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-address-of-packed-member -O3 -ftracer -mar
ch=core2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-varia
ble -Wno-unused-const-variable -fno-var-tracking-assignments -g -gdwarf-4 -pg -mrecord-mcount -mfentry -DCC_USING_FEN
TRY -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -Wno-array-bounds -Wno-stringop-overflow
 -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-ch
eck -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-ty
pes -Werror=designated-init -fmacro-prefix-map=/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/= -fcf-protect
ion=none -Wno-packed-not-aligned  -I/var/lib/dkms/zfs/0.8.4/build/module/icp/include -std=gnu99 -Wno-declaration-afte
r-statement -include /var/lib/dkms/zfs/0.8.4/build/zfs_config.h  -I/var/lib/dkms/zfs/0.8.4/build/include/spl  -I/var/
lib/dkms/zfs/0.8.4/build/include -std=gnu99 -Wno-declaration-after-statement -include /var/lib/dkms/zfs/0.8.4/build/z
fs_config.h  -I/var/lib/dkms/zfs/0.8.4/build/include/spl  -I/var/lib/dkms/zfs/0.8.4/build/include -D_KERNEL -UDEBUG -
DNDEBUG -D_KERNEL -UDEBUG -DNDEBUG  -DMODULE  -DKBUILD_BASENAME='"illumos_crypto"' -DKBUILD_MODNAME='"icp"' -c -o /va
r/lib/dkms/zfs/0.8.4/build/module/icp/.tmp_illumos-crypto.o /var/lib/dkms/zfs/0.8.4/build/module/icp/illumos-crypto.c
In file included from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/compat.h:16,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/arch/x86/include/asm/ftrace.h:66,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/ftrace.h:21,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/perf_event.h:48,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/trace_events.h:10,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/trace/syscall.h:7,
                 from /usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/syscalls.h:85,
                 from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vnode.h:29,
                 from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/kobj.h:28,
                 from /var/lib/dkms/zfs/0.8.4/build/include/sys/zfs_context.h:45,
                 from /var/lib/dkms/zfs/0.8.4/build/include/sys/crypto/common.h:39,
                 from /var/lib/dkms/zfs/0.8.4/build/module/icp/illumos-crypto.c:35:
/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/if.h:28:10: fatal error: sys/socket.h: No such file or directory
   28 | #include <sys/socket.h>   /* for struct sockaddr.  */
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [/var/lib/dkms/zfs/0.8.4/build/module/icp/illumos-crypto.o] Error 1
make[5]: *** [/var/lib/dkms/zfs/0.8.4/build/module/icp] Error 2
make[4]: *** [_module_/var/lib/dkms/zfs/0.8.4/build/module] Error 2
```

sys/socket.h is present in /usr/include but it's normal that this copy isn't being used because of the compiler options. However, how come a version of the file is found when building against (and under ) 4.14.23 ... or maybe the failing include statement isn't executed ... but if so, why?

I'm not the first to file a ticket about this, I hope mine won't be the la[te]st to be closed without further ado.

**Comment by RJVB** [comment]
For reference, here is the succeeding compile command from 4.14.23

```
  gcc -Wp,-MD,/var/lib/dkms/zfs/0.8.4/build/module/icp/.illumos-crypto.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/9/include -I/home/bertin/work/src/Scratch/kernel/linux-4.14.23/arch/x86/include -I./arch/x86/include/generated  -I/home/bertin/work/src/Scratch/kernel/linux-4.14.23/include -I./include -I/home/bertin/work/src/Scratch/kernel/linux-4.14.23/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/home/bertin/work/src/Scratch/kernel/linux-4.14.23/include/uapi -I./include/generated/uapi -include /home/bertin/work/src/Scratch/kernel/linux-4.14.23/include/linux/kconfig.h  -I/var/lib/dkms/zfs/0.8.4/build/module/icp -I/var/lib/dkms/zfs/0.8.4/build/module/icp -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=core2 -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O3 -ftracer -march=core2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-var-tracking-assignments -g -gdwarf-4 -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init  -I/var/lib/dkms/zfs/0.8.4/build/module/icp/include -std=gnu99 -Wno-declaration-after-statement -include /var/lib/dkms/zfs/0.8.4/build/zfs_config.h  -I/var/lib/dkms/zfs/0.8.4/build/include/spl  -I/var/lib/dkms/zfs/0.8.4/build/include -std=gnu99 -Wno-declaration-after-statement -include /var/lib/dkms/zfs/0.8.4/build/zfs_config.h  -I/var/lib/dkms/zfs/0.8.4/build/include/spl  -I/var/lib/dkms/zfs/0.8.4/build/include -D_KERNEL -UDEBUG -DNDEBUG -D_KERNEL -UDEBUG -DNDEBUG  -DMODULE  -DKBUILD_BASENAME='"illumos_crypto"'  -DKBUILD_MODNAME='"icp"' -c -o /var/lib/dkms/zfs/0.8.4/build/module/icp/.tmp_illumos-crypto.o /var/lib/dkms/zfs/0.8.4/build/module/icp/illumos-crypto.c
```

(for this kernel the `source` and `build` directories point to the actual, prepared kernel sources).

In both cases this is with GCC 9.3.0 .

**Comment by RJVB** [comment]
> However, how come a version of the file is found when building against (and under ) 4.14.23 ... or maybe the failing include statement isn't executed ... but if so, why?

Easy to dig out: the 4.14.23 version of the kernel header linux/compat.h checks has its `#ifdef CONFIG_COMPAT` a lot earlier, before `linux/if.h` is included, which is the culprit that includes sys/socket.h . HOWEVER, both my 4.1x kernels have `CONFIG_COMPAT=y`  so there must be yet more that's going on.

I'm going to try to hardwire _LINUX_IF_H in illumos-crypto.h and see if that unblocks the situation.

**Comment by nivedita76** [comment]
I'm not sure what's going on, but sys/socket.h should not be included when `__KERNEL__` is defined.

This is what the upstream v4.14.133 if.h file looks like:
`#ifndef __KERNEL__`
`#include <sys/socket.h>                 /* for struct sockaddr.         */`
`#endif`

**Comment by RJVB** [comment]
Thanks for picking this up!

>This is what the upstream v4.14.133 if.h file looks like:

I presume you mean the if.h file from the kernel tarball, `linux-4.19.133/include/uapi/linux/if.h`?

I build my kernels from the mainline/upstream kernel tarballs, with just the Con Kolivas patch set applied (plus now the re-export of the SIMD export functions). The if.h header isn't modified.

Yet I find myself with 2 if.h headers in under /usr/src/linux-headers-4.19*:
/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/uapi/linux/if.h
/usr/src/linux-headers-4.19.133-ck1-mainline-core2-rjvb/include/linux/if.h

The latter of which includes <sys/sockets.h> unconditionally, and is of course the one that's being found. 

I've already seen a comment in a bug report somewhere that this file shouldn't be installed, but annoyingly I seem to remember that the build fails if I move that file aside, because it is actually required. Going to have to try again, or possibly replace it with the copy from uapi/linux.

Figuring out where the file comes from isn't going to be easy; it's not the one from the build host's /usr/include/linux dir. either. From what I can tell the scripts/headers_install.sh script is only called to install the if.h from include/uapi/linux .

FWIW, I'm using the 13.018+nmu1 version of the `kernel-package` package to generate my own linux-image and linux-headers .debs . That's the previous version of this package, but judging from `http://launchpadlibrarian.net/457347805/kernel-package_13.018+nmu1_13.018+nmu2.diff.gz` the current version has only had some cosmetic upgrades.

Sigh. Dkms is great when it works, but it's a PITA until then...

**Comment by RJVB** [comment]
BTW, there's definitely something fishy here. I see other files that exist in both `/usr/src/linux-headers-4.19.133/include/{,uapi/}linux` dirs, but most have different double-inclusion-prevention tokens that indicate they should indeed exist in both places, and be different. For instance, `if_vlan.h` defines `_LINUX_IF_VLAN_H_` or `_UAPI_LINUX_IF_VLAN_H_` . 

There are other headers that exist in both locations, where the include/linux copy appears to be the result of a simple search-and-replace of a number of keywords (remove `__user`, `#include <linux/compiler.h>`, `#if[n]def __KERNEL__` with the matching #endif, replace `__volatile__` with `volatile` and a few more similar actions).

I'm going to see if I can put an `#include <uapi/linux/if.h>` statement before the include that leads to loading the wrong if.h file. If that works and if there's some more or less valid reason why I have those 2 conflicting if.h headers this may be the only acceptable workaround (because I might not be the only one in this situation).

**Comment by nivedita76** [comment]
Did you run headers_install.sh (or make headers_install) to populate anything under your usr/src/linux-headers.* directories? That tool is meant only to create the userspace headers to install under /usr/include/, and it indeed does some simple manipulation of the files, including deleting all code protected with #ifdef __KERNEL__, and making code with #ifndef __KERNEL__ unconditional.

/usr/src/linux-headers should be a subset of the kernel source tree. I don't know what kernel-package is doing, but kernel-headers should not contain include/linux/if.h. The standard linux-headers- package doesn't, for example.

**Comment by RJVB** [comment]
>Did you run headers_install.sh (or make headers_install) to populate anything under your usr/src/linux-headers.* directories? 

Not myself, but it's invoked at some point by make-kpkg .

It still is in my 4.9 kernel install; in 4.14 it already contains additional thing. I probably upgraded my kernel-package package because the version I had didn't work with the 4.14 kernel, judging from dates in the notes I kept.

>I don't know what kernel-package is doing, but kernel-headers should not contain include/linux/if.h. The standard linux-headers- package doesn't, for example.

A priori the Deb/Ubuntu linux-{image,headers} packages are created using the same kernel-package package, at least that is my understanding. Maybe it is supposed to be used in conjunction with a distro-provided `debian` directory that patches the headers_install.sh script, which would explain why something goes wrong when used on a mainline kernel?

Let me repeat that I am not the only one with this issue. The good news is that including uapi/linux/if.h prophilactically is a valid workaround, but I bumped into a different issue I may need to report and which somehow is not an issue with the 4.14.23 kernel (vfs_compat.h calling `is_compat_task()` unconditionally which breaks the build because of a -Werror flag and a missing prototype for the function).

**Comment by nivedita76** [comment]
If make-kpkg is invoking it to put something under /usr/src/linux-headers that seems like a bug in kernel-package.

One other workaround you might try: assuming you have a full kernel source directory anyway, linux-headers should be unnecessary -- it's only purpose is trimming down the kernel source tree you require in order to build modules, for people who only have a binary kernel package. You can try symlinking /lib/modules/$KVER/build, which I think should currently point to /usr/src/linux-headers-, to your actual kernel source directory instead.

**Comment by nivedita76** [comment]
There is also a bindep-pkg target in the kernel Makefile itself: if you run make bindeb-pkg (plain deb-pkg will also build source packages) you should get a bunch of packages, including the linux-headers package. The package built this way doesn't contain the duplicate if.h file.

**Comment by RJVB** [comment]
> You can try symlinking /lib/modules/$KVER/build, which I think should currently point to /usr/src/linux-headers-, to your actual kernel source directory instead.

That's what I have been doing with the 4.14.23 kernel, that kernel build directory is huge enough that I'd prefer to remove it (I can't remember how I cleaned the 4.14 one without losing the generated stuff).

**Comment by nivedita76** [comment]
>The good news is that including uapi/linux/if.h prophilactically is a valid workaround, but I bumped into a different issue I may need to report and which somehow is not an issue with the 4.14.23 kernel (vfs_compat.h calling `is_compat_task()` unconditionally which breaks the build because of a -Werror flag and a missing prototype for the function).

HAVE_IN_COMPAT_SYSCALL should be enabled for your kernel version. It might be broken because of the linux-headers issues.

**Comment by RJVB** [comment]
>HAVE_IN_COMPAT_SYSCALL should be enabled for your kernel version. It might be broken because of the linux-headers issues.

compat.h should be in /usr/src/linux-headers-*/linux, right? 

> if you run make bindeb-pkg (plain deb-pkg will also build source packages)
> you should get a bunch of packages, including the linux-headers package

This only creates packages, right - it doesn't install the files first (like `checkinstall` does)?

**Comment by nivedita76** [comment]
> HAVE_IN_COMPAT_SYSCALL should be enabled for your kernel version. It might be broken because of the linux-headers issues.
> compat.h should be in /usr/src/linux-headers-*/linux, right?

it should be include/linux/compat.h. But what I'm saying is that the ZFS configure should have detected that your kernel has in_compat_syscall(), and used it instead of is_compat_task(). The configure test must not have worked.

> if you run make bindeb-pkg (plain deb-pkg will also build source packages) you should get a bunch of packages, including the linux-headers package
> This only creates packages, right - it doesn't install the files first (like `checkinstall` does)?

There's no `checkinstall` in the kernel Makefile, so not sure which target you're referring to. bindep-pkg won't install anything though. You'll get a set of deb files in the parent directory of the kernel tree.

**Comment by RJVB** [comment]
I meant the checkinstall command from the same-named package, which is a bit of a strange name for a script the runs `make install` (actually installing stuff) and then generates a .deb. Or maybe it installs to a `DESTDIR` and installs the package after creating it, not really relevant here.

Anyway, using the `bindep-pkg` target was a good idea, I should have known about that years ago (if it turns out that it indeed streamlines the process of installing the generated packages; I always had to correct some stuff by hand)

**Comment by nivedita76** [comment]
> I meant the checkinstall command from the same-named package, which is a bit of a strange name for a script the runs `make install` (actually installing stuff) and then generates a .deb. Or maybe it installs to a `DESTDIR` and installs the package after creating it, not really relevant here.
> 
> Anyway, using the `bindep-pkg` target was a good idea, I should have known about that years ago (if it turns out that it indeed streamlines the process of installing the generated packages; I always had to correct some stuff by hand)

Taking a look at kernel-package source, it does seem broken. It runs headers_install first, which will create UAPI versions of the header files, and _then_ copies over the actual include directory. This is why you have two if.h's -- the one in include/linux was created by headers_install and cannot be used for module building, but it gets picked up before the real one in include/uapi/linux. Not sure why they added the headers_install step, it should just be deleted.

The Debian package recommends using the upstream target: https://salsa.debian.org/kernel-team/linux/-/blob/master/debian/README.Debian

> We recommend using the 'make deb-pkg' target provided by the upstream
kernel source.

**Comment by RJVB** [comment]
On Wednesday July 22 2020 14:22:31 Arvind Sankar wrote:

Morning,

>module building, but it gets picked up before the real one in include/uapi/linux. Not sure why they added the headers_install step, it should just be deleted.
>
>The Debian package recommends using the upstream target: https://salsa.debian.org/kernel-team/linux/-/blob/master/debian/README.Debian
>
>> We recommend using the 'make deb-pkg' target provided by the upstream
>kernel source.

Well, now that we know that ... :)

The new packages installed fine, and the virtualbox guest additions now also build against the new kernel. Whew, and thanks!

R.

**Comment by RJVB** [comment]
Solved thanks to @nivedita76 .
