### ISSUE TITLE
Please implement "cp --reflink=always" with ZoL

### ISSUE THREAD

**Issue by petermaloney** [openzfs/zfs#1063]
Please implement "cp --reflink=always" with ZoL

I am using it happily with btrfs. For example I downloaded xen 4.1.3 source and wanted to try a few things with it, so I made 3 or 4 copies of the tree (taking little space and being nearly instant due to reflinks) and then did my hacks and tests without having to rebuild each time to install each from the same tree.

using "cp --reflink=always"  is like dedup without dedup enabled

it is not ordinary hardlinks... it is like dedup without the dedup table

http://pastebin.com/2zE9D36u

it's just like dedup... modify the original, and the reflinked copies don't chnage

I don't think it is ever file level... only block. That way if you modify some blocks of a file, it cows only those blocks, not the whole file, just like dedup or snapshots.

ryao on freenode tried this and reported this result:
cp: failed to clone ‘portage/app-cdr/k3b/metadata.xml’ from ‘/usr/portage/app-cdr/k3b/metadata.xml’: Inappropriate ioctl for device

**Comment by galt** [comment]
Clones and snapshots are too heavy duty.

**Comment by beren12** [comment]
bookmarks then?
