### ISSUE TITLE
Support FreeBSD VFS lockless lookup (SMR) 

### ISSUE THREAD

**Issue by myfreeweb** [openzfs/zfs#10638]
https://reviews.freebsd.org/D25581 should be imported here, possibly with a [`__FreeBSD_version >= 1300102`](https://github.com/freebsd/freebsd/commit/21e60a6cf172a5443a194bd59bb0bc6c31c212d0) check..

**Comment by freqlabs** [comment]
mjg said he will open a PR for OpenZFS when he finishes porting/testing.

**Comment by freqlabs** [comment]
#10657
