### ISSUE TITLE
Debian machine seems to have lost /bin symlink to /usr/bin; zpools not found due to bad grep path

### ISSUE THREAD

**Issue by dankamongmen** [openzfs/zfs#10645]
### System information
Type | Debian Unstable
 --- | ---
Distribution Name	| Debian
Distribution Version	| Unstable (2020-07-30)
Linux Kernel	| 5.7.11nlb
Architecture	| x86_64 (AMD 3970X)
ZFS Version	| 0.8.0-1
SPL Version	| 0.8.0-1

### Describe the problem you're observing

I rebooted my Debian machine after building 5.7.11nlb and zfs from head. On boot, my zpools were not imported from the cachefile. `systemctl status zfs-import-cache` revealed that `/usr/bin/grep` couldn't be found. Indeed, my familiar symlink from `/usr/bin` to `/bin` seems to have been replaced with an old-school `/bin` directory (how or when this happened is at present unknown). I had to edit the systemd unit files, replacing `/usr/bin/grep` with `/bin/grep`. Everything then worked fine, but urmph! Nervewracking. 

I'm not sure that this is zfs-on-linux's problem, but wanted to get it up here in case it was about to be widespread. Feel free to close this issue with prejudice.

### Describe how to reproduce the problem

Again, I'm not quite sure how my `/bin` changed without my knowing it. Looking into this.

I'm not sure if zfs uses Autotools to detect the location of e.g. `grep` and writes it to the systemd units prior to installing them. If so, I suppose this behavior is expected, since I presume `grep` would indeed have been reachable via `/usr/bin/grep` before (assuming the `/bin` switch was on boot).

### Include any warning/errors/backtraces from the system logs

Just the "Couldn't find file: /usr/bin/grep" in `zfs-import-cache` and then `zfs-mount` journals.

**Comment by JordanP-Dev** [comment]
I don't think there is anything wrong with your system.  The standard place for grep appears to be /bin/grep on Debian, as well as on Ubuntu 20.04 and Gentoo.  This check was only added recently:

https://github.com/openzfs/zfs/commit/ae12b023082fd91e89507a2a1fc014e64c6767f0

It looks like it will be fixed pretty soon.  There is a pull request to fix checking for the module when it is builtin, with the side effect that it won't use grep any more.

https://github.com/openzfs/zfs/pull/10663

**Comment by dankamongmen** [comment]
Sounds good to me. Marking this closed.
