### ISSUE TITLE
Typo in zfs command help text: "pbkfd2iters" should be "pbkdf2iters"

### ISSUE THREAD

**Issue by skalteis** [openzfs/zfs#10653]
### System information

Type | Version/Name
 Linux x64 | 5.4.23
Distribution Name	| Debian
Distribution Version	| 10.4
Linux Kernel	| 5.4.23
Architecture	| amd64
ZFS Version	| 0.8.3-1
SPL Version	| 0.8.3-1

### Describe the problem you're observing
The help output for the zfs command has a typo: "pbkfd2iters" should be "pbkdf2iters"

### Describe how to reproduce the problem
Just call zfs without parameters

Still present in current HEAD: https://github.com/openzfs/zfs/blob/a15c6f33104a0ef12f36688e5dcca2f16fff8e05/cmd/zfs/zfs_main.c#L404 

Thank you & best regards! :-)

**Comment by Spencer-Kinny** [comment]
@behlendorf 
Please close this issue #10653 ,once merge is completed as its completed in #10850
