### ISSUE TITLE
Overflow in zdb time calculation

### ISSUE THREAD

**Issue by Number774** [openzfs/zfs#10666]
### System information

Distribution Name	| Ubuntu
Distribution Version	| 18.04 LTS
Linux Kernel	| 4.15.0-106-generic
Architecture	|x86_64
ZFS Version	| 0.7.5-1ubuntu16.9
SPL Version	| 0.7.5-1ubuntu2.1

### Describe the problem you're observing
zdb is giving me silly time estimates:
$ sudo zdb -cc zfs

Traversing all blocks to verify checksums and verify nothing leaked ...

loading space map for vdev 0 of 1, metaslab 115 of 116 ...
 545G completed (  17MB/s) estimated time remaining: 489416hr 30min 14sec        294967249sec
(Note that that looks slightly odd - at times all of HH MM SS are approaching 2^32)

### Describe how to reproduce the problem
I ran zdb -cc on a fairly new pool made from 1x1GB spinning rust.

### Include any warning/errors/backtraces from the system logs
None apparent.

**Comment by Spencer-Kinny** [comment]
@behlendorf 
could you please guide me to the debug section, so that I can test my code changes

**Comment by behlendorf** [comment]
@Spencer-Kinny sure, you can use [these directions](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html#running-zloop-sh-and-zfs-tests-sh) to locally run the test suite.  Specifically, running `zloop.sh` for a bit and the `zdb` ZTS test would be a good sanity check.

```
./scripts/zloop.sh
```

```
./scripts/zfs-tests.sh -T zdb
```

**Comment by Spencer-Kinny** [comment]
@behlendorf 
It keeps giving me this error when I execute "./scripts/zloop.sh":
09/01 11:15:57 /ztest -G -VVVVV -m 2 -r 7 -R 2 -v 3 -a 9 -T 59 -P 24 -s 512m -f /var/tmp/zloop-run 
*** ztest crash found - moving logs to /var/tmp/zloop/zloop-200901-111557
mv: cannot stat '/var/tmp/zloop-run/ztest*': No such file or directory
Command failed: mv /var/tmp/zloop-run/ztest* /var/tmp/zloop/zloop-200901-111557/vdev/

So I changed permissions of /var/tmp/* to 777. However it still gives above error

and the script zfs-tests.sh when executed "./scripts/zfs-tests.sh -T zdb" says this
zfs-tests.sh: Cannot find runfile: common.run

**Comment by Number774** [comment]
If this is still open in 6 months I might even take a look myself. I plan to retire then, and will have more time :)
