### ISSUE TITLE
Read/search performance: (perceived) decrease over time?

### ISSUE THREAD

**Issue by RJVB** [openzfs/zfs#10684]
### System information

Type | Linux
Distribution Name	| any
Distribution Version	| any
Linux Kernel	| 4.1x
Architecture	| x86_64
ZFS Version	| 0.7+
SPL Version	| 0.7+

### Describe the problem you're observing

My principle Linux rig is all-ZFS (except for /boot) and the pool it lives on is now several years old. I have the impression that application startup times have been getting longer; could that be the result of fragmentation that's getting too high?
(The pool sits on a single SSHD, laptop obliges, so it might also be that its SSD buffer has died and I'm left with the otherwise average 5400rpm HDD?)

### Describe how to reproduce the problem

Use a pool intensively for years on a development system.

**Comment by misterbigstuff** [comment]
yes, you should probably recreate the pool every so often from backup to avoid fragmentation problems. this is what i have to do. it's annoying.

**Comment by RJVB** [comment]
Annoying indeed for the root, but I do have a trick to make at least one of the steps less cumbersome in the sense that you can continue to work without having to worry about open files, or files modified on the source after they were already backed up:

- attach the target as a mirror zdev
- continue to work during the resilver process
- split off the mirror to a new pool when it's convenient.

Evidently this also clones the fragmentation.


Is there a fragmentation percentage threshold above which performance will degrade noticeably? I'm a bit surprised by this, BTW - I thought filesystems like ZFS intend to use the entire disk space, which should mean they maximise fragmentation and there should be no performance degradation over time...

**Comment by misterbigstuff** [comment]
yeah, mirroring will preserve the previous disk locality issues. you would want to send/recv data to a new pool and this may even result in better compressratio. though if your pool is full enough for it to switch allocation strategy to best-fit it will not really help much or at all. you would need to send to a new *larger* pool then.

**Comment by misterbigstuff** [comment]
as for snapshots i am not sure if you can keep em all when sending to the new pool. someone else who knows more would need to chime in on that. i almost always remove all but the most organised snapshots first.

**Comment by RJVB** [comment]
That's one reason why I rarely use send/receive - too many options, too many ways things can go just wrong :-/

**Comment by misterbigstuff** [comment]
i should clarify. you CAN keep the snapshots. whether this impacts fragmentation on the new pool, is a guess, on my part.
