### ISSUE TITLE
Revisit L2ARC functionality

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#10687]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.8
Linux Kernel	| 3.10.0-1127.13.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing
Current L2ARC behavior is not optimal for several workloads. The key issue is that, by default, sequential reads from the main pool cause L2ARC wear but *no* performance increase during subsequent reads. This is due to the following:

 - a sequential read (eg: `dd if=/tank/test/test.img of=/dev/null bs=1M count=256 status=progress`) causes heavy prefetch activity (ie: almost all the file is read by the prefetcher)
 - as the prefetched buffers are accessed by `dd`, the prefetch flag is cleared
 - the L2ARC feed thread runs and writes the previously marked-as-prefetched buffers to the L2ARC device
 - when re-reading the first file, *no reads* are dispatched to the L2ARC due to `l2arc_noprefetch=0` (default value).

In short, reading big files will almost entirely *write* them to the L2ARC device (via ARC evinction), still no performance increase can be found. This causes unnecessary wear on the L2ARC device, constantly trashing it with once-prefetched data.

Setting `l2arc_noprefetch=1` is not really a solution: while this can, under selected workloads, increase performances, it actually worses the L2ARC device wear (even prefetched but not used buffers are now written to L2ARC).

I strongly feel this behavior should be changed, otherwise any workload when large files are sequentially read (ie: backups) will completely trash L2ARC. On top of my head, I can think about two approaches:

 - add a tunable/property to let L2ARC only cache MFU ARC data: as the prefetcher only operate inside the MRU list, this will completely solve the issue at the cost of not caching in L2ARC any MRU data at all. This seems a reasonable tradeoff if you ask me
 - clear the prefetched flag only after the *second* demand read. While not bullet proof, it will avoid trashing L2ARC with very big files (exceeding ARC coverage). It should be verified, however, that the MRU ghost does not badly interact with this change.

### Describe how to reproduce the problem

 - create a big file under (ie: `/tank/test/test.img`)
 - read it sequentially with `dd if=/tank/test/test.img of=/dev/null bs=1M status=progress`
 - observe how data are written to the L2ARC device
 - re-read the same file with the same command and observe how the L2ARC device does not serve any read; rather, it absorb additional writes until the entire file is cached

**Comment by gamanakis** [comment]
I think I understand your concern here, wearing out the L2ARC device. However your last point:

> re-read the same file with the same command and observe how the L2ARC device does not serve any read

is not entirely true. Upon reading something for the first time from L2ARC, content is cached in ARC and then is served from ARC instead of L2ARC. That is why you conclude "L2ARC device does not serve any read", because the file is served from ARC. On a reboot with persistent L2ARC, when reading the same file you would see initial reads from L2ARC, and then none as the file will be served from ARC (if the ARC is big enough).

All this, as you point out, is *highly* workload specific. While doing backups you have also the option of off-lining the L2ARC device. That said, the first approach you provide maybe relatively easy to implement in the form of a module parameter. 

Let's see if others chime in.

**Comment by shodanshok** [comment]
> Upon reading something for the first time from L2ARC, content is cached in ARC and then is served from ARC instead of L2ARC. That is why you conclude "L2ARC device does not serve any read", because the file is served from ARC.

@gamanakis this is not my experience: I tried reading a file bigger than ARC but smaller than L2ARC and, even when all data were in L2ARC, reads were served by main disks. This is not suprising at all, due to the following code:
https://github.com/openzfs/zfs/blob/ae7b167a98b48260554fd88cef022547283e125f/module/zfs/arc.c#L6051-L6062
Look at point n.5: if `l2arc_noprefetch=1`, then prefetched buffer are *never* read from L2ARC.

However, this is not the main point: after all, one can simply set `l2arc_noprefetch=0`. Rather, the main motivation of this issue is the additional wear posed on the L2ARC device.

> All this, as you point out, is _highly_ workload specific. While doing backups you have also the option of off-lining the L2ARC device (although this may not solve your problem entirely, again depending on the workload). 

Sure, hence I am suggesting a tunable or dataset property rather than a blanked change to the current behavior.

> That said, the first approach you provide maybe relatively easy to implement in the form of a module parameter.

I think so: adding a `l2arc_mruonly` parameter should be quite simple, yet very effective.
Thanks.

**Comment by gamanakis** [comment]
> Look at point n.5: if l2arc_noprefetch=1, then prefetched buffer are never read from L2ARC.

@shodanshok I see your point. I was referring to the case when `l2arc_noprefetch=0`.

In any case I made a quick patch, submitted as a draft PR, #10710. Feel free to try it.

**Comment by shodanshok** [comment]
@gamanakis thank you so much! I will surely test it and report back.
