### ISSUE TITLE
modprobe zfs failing on custom kernel on NixOS with unknown symbol or unknown parameter

### ISSUE THREAD

**Issue by shadowrylander** [openzfs/zfs#10680]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  NixOS
Distribution Version	|  20.03
Linux Kernel	|  [`linux-surface 4.19`](https://github.com/linux-surface/linux-surface/tree/dba4cbd123c3685c2df9e14944e8165992fe9881), via [`nixos-surface`](https://github.com/anthe/nixos-surface)
Architecture	|  x64
ZFS Version	|  0.8.4
SPL Version	|  ???

### Describe the problem you're observing

I am currently attempting to use NixOS on my Surface Book 2 via an external SSD and a partition on the internal SSD; the kernel I am attempting to use is the `linux-surface` kernel, with the original by [`jakeday`](https://github.com/jakeday/linux-surface), and a more up-to-date version maintained by the [`linux-surface`](https://github.com/linux-surface/linux-surface) group. A module for the kernel is maintained by [`anthe`](https://github.com/anthe/nixos-surface).

When attempting to import the zfs root pool, `modprobe` throws `modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)`. `dmesg` then states `zcommon: Unknown symbol __kernel_fpu_begin (err -2)`, right before `zcommon: Unknown symbol __kernel_fpu_end (err -2)`.

I am aware of changes to either the zfs module, or the `kernel_fpu` symbol, but am unsure as to how to implement any fixes for the issue.

**Comment by DeHackEd** [comment]
Using a linux driver for a different kernel than it was originally compiled for is not supported by the kernel. You'll have to rebuild the driver as well if you change the kernel. Even just changing the kernel config options is a risk.

**Comment by shadowrylander** [comment]
By driver, do you mean kernel module? Sorry, a little confused there.

**Comment by DeHackEd** [comment]
Yes

**Comment by shadowrylander** [comment]
Ah; in that case, kernel modules are rebuilt against the specified kernel every time kernel settings change in the primary configuration files. Therefore, the zfs module compiled is specifically for the custom kernel, which, in this case, still produces the error above.

**Comment by shadowrylander** [comment]
What I remember is that NixOS came up with a patch of their own for the zfs module, as described in [this](https://www.phoronix.com/scan.php?page=news_item&px=NixOS-Linux-5.0-ZFS-FPU-Drop) article on phoronix.

**Comment by shadowrylander** [comment]
Yep, the aforementioned patch solved the issue. Closing now.
