### ISSUE TITLE
 dnode_sync is careless with range tree

### ISSUE THREAD

**Issue by pfmooney** [openzfs/zfs#10708]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| illumos-gate
Distribution Version	| built from master
Architecture	| amd64

### Describe the problem you're observing

Details also in [illumos #13034](https://www.illumos.org/issues/13034)

While running a somewhat intensive zvol workload (FreeBSD doing a buildkernel as a hardware virt guest) on a DEBUG illumos-gate system, I saw semi-reliable panics inside zfs:

```
panic message: BAD TRAP: type=e (#pf Page fault) rp=fffffe007d4be490 addr=fffffe5a5616a00c
dump content: kernel pages only
> $C
fffffe007d4be600 zfs_btree_find+0x238(fffffe59eb90a700, fffffe007d4be610, 0)
fffffe007d4be670 range_tree_find_impl+0x134(fffffe59eb90a700, 13960c, 1)
fffffe007d4be6c0 range_tree_find+0x45(fffffe59eb90a700, 13960c, 1)
fffffe007d4be6f0 range_tree_contains+0x10(fffffe59eb90a700, 13960c, 1)
fffffe007d4be740 dnode_block_freed+0x80(fffffe5a090ad520, 13960c)
fffffe007d4be810 dbuf_read_impl+0xe7(fffffe5a35c775d0, fffffe5a57e3b568, 1e)
fffffe007d4be8b0 dbuf_read+0xdb(fffffe5a35c775d0, fffffe5a57e3b568, 1e)
fffffe007d4be960 dmu_buf_hold_array_by_dnode+0x11c(fffffe5a090ad520, 13960c000, 1000, 1, fffffffff79998a0, fffffe007d4be9ac, fffffe007d4be9b0, fffffe5a00000000)
fffffe007d4bea10 dmu_read_uio_dnode+0x54(fffffe5a090ad520, fffffe007d4bec78, 1000)
fffffe007d4bea70 dmu_read_uio+0x73(fffffe59d6d934c0, 1, fffffe007d4bec78, 1000)
fffffe007d4beae0 zvol_read+0xd5(11200000003, fffffe007d4bec78, fffffe59f5208448)
fffffe007d4beb10 cdev_read+0x2a(11200000003, fffffe007d4bec78, fffffe59f5208448)
fffffe007d4beba0 spec_read+0x310(fffffe59de796d00, fffffe007d4bec78, 0, fffffe59f5208448, 0)
fffffe007d4bec20 fop_read+0x60(fffffe59de796d00, fffffe007d4bec78, 0, fffffe59f5208448, 0)
fffffe007d4beef0 preadv+0x22a(4, 167abe8, 1, 13960c000, 0)
fffffe007d4bef00 sys_syscall+0x283()
```

The faulting address appears to be a leaf node of the zfs btree in question.  That btree in question is under going a `range_tree_vacate` operation in another thread:

```
> ::stacks -c range_tree_vacate | ::findstack -v
stack pointer for thread fffffe007c40bc20 (tq:dp_sync_taskq): fffffe007c40b270
  fffffe007c40b2a0 dbuf_redirty+0x24(fffffe5a5324e700)
  fffffe007c40b2f0 dmu_buf_will_dirty_impl+0x8a(f, 9, fffffe59bfa88460)
  fffffe007c40b360 apix_hilevel_intr_prolog+0xa0(fffffe59d2925000, f, 0, fffffe007c40b3e0)
  fffffe007c40b3d0 apix_do_interrupt+0x56e(fffffe007c40b3e0, fffffffffbc609c0)
  fffffe007c40b3e0 _interrupt+0x1f2()
  fffffe007c40b4f0 fletcher_2_incremental_native+0x2b(fffffe5a336d5000, 20000, fffffe007c40b538)
  fffffe007c40b520 fletcher_2_native+0x1e(fffffe5a336d5000, 20000, 0, fffffe007c40b538)
  fffffe007c40b590 arc_cksum_verify+0xca(fffffe5a35ee6740)
  fffffe007c40b5c0 arc_buf_thaw+0x57(fffffe5a35ee6740)
  fffffe007c40b670 arc_release+0x5c5(fffffe5a35ee6740, fffffe5a35edfb40)
  fffffe007c40b6a0 dbuf_release_bp+0x61(fffffe5a35edfb40)
  fffffe007c40b750 free_children+0xb0(fffffe5a35edfb40, 1ce5dd, 2, 0, fffffe5a53896600)
  fffffe007c40b800 free_children+0x350(fffffe5a08e6e468, 1ce5dd, 2, 0, fffffe5a53896600)
  fffffe007c40b8b0 free_children+0x350(fffffe59f207a518, 1ce5dd, 2, 0, fffffe5a53896600)
  fffffe007c40b970 dnode_sync_free_range_impl+0x11a(fffffe5a090ad520, 1ce5dd, 2, 0, fffffe5a53896600)
  fffffe007c40b9d0 dnode_sync_free_range+0x54(fffffe007c40ba70, 1ce5dd, 2)
  fffffe007c40ba40 range_tree_vacate+0x178(fffffe59eb90a700, fffffffff786eca0, fffffe007c40ba70)
  fffffe007c40bad0 dnode_sync+0x3e5(fffffe5a090ad520, fffffe5a53896600)
  fffffe007c40bb20 dmu_objset_sync_dnodes+0x9e(fffffe5a0b769b00, fffffe5a53896600)
  fffffe007c40bb50 sync_dnodes_task+0x31(fffffe5a33de5000)
  fffffe007c40bc00 taskq_thread+0x315(fffffe59ce648c58)
  fffffe007c40bc10 thread_start+0xb()
```

Given that `range_tree_vacate` is implemented as looping `zfs_btree_destroy_nodes` call under the hood, its invariants apply to that btree:
```
 * This function is used to visit all the elements in the tree before
 * destroying the tree. This allows the calling code to perform any cleanup it
 * needs to do. This is more efficient than just removing the first element
 * over and over, because it removes all rebalancing. Once the destroy_nodes()
 * function has been called, no other btree operations are valid until it
 * returns NULL, which point the only valid operation is zfs_btree_destroy().
```

Since no other btree operations should be valid, how is it that `dnode_block_freed` is accessing it (and, not unreasonably, dying on a fault when doing so) to find invalid data?  A closer look at the locks for exclusion lead us to the source of the problem: `dnode_sync_free_range` drops the dnode mutex while performing the free range sync:
```
static void
dnode_sync_free_range(void *arg, uint64_t blkid, uint64_t nblks)
{
        dnode_sync_free_range_arg_t *dsfra = arg;
        dnode_t *dn = dsfra->dsfra_dnode;

        mutex_exit(&dn->dn_mtx);
        dnode_sync_free_range_impl(dn, blkid, nblks,
            dsfra->dsfra_free_indirects, dsfra->dsfra_tx);
        mutex_enter(&dn->dn_mtx);
}
```
During that window, another thread can come along and stumble into the contents of the zfs btree which are invalid to everyone (except the thread doing the `range_tree_vacate`).  Assuming that lock-dropping in `dnode_sync_free_range` is necessary, then `dnode_sync` needs to make more of an effort to prevent other threads from encountering invalid btree state. 

### Describe how to reproduce the problem

It took a rather specific sent of circumstance for me to reproduce it on a certain system, and I've seen it no where else.  I was running FreeBSD HEAD doing a buildkernel inside a bhyve VM running on an illumos system with a DEBUG kernel.

**Comment by pfmooney** [comment]
Note that while `zfs_btree_destroy_nodes()` is in the mix here, I believe this would have still been a danger prior to the integration of #9181.  The prior implementation of `range_tree_vacate()` used `avl_destroy_nodes()` which carries a similar warning in its man page:

> After the `avl_destroy_nodes()` function is called on an AVL tree, the only
> valid functions that may be called on it are additional calls to
> `avl_destroy_nodes()` and finally `avl_destroy()`.

**Comment by adamdmoss** [comment]
Sounds like that condition can be assertable with (at worst) an extra flag.

**Comment by pfmooney** [comment]
> Sounds like that condition can be assertable with (at worst) an extra flag.

I think the big question is: What do the consumers of `dn_free_ranges` expect of it in order to operate correctly?

One could imagine `dnode_sync` holding the range tree pointer in a temporary while `dn_free_ranges` is set to `NULL` so that any thread that happens to acquire `dn_mtx` while `dnode_sync_free_range` has dropped it will not observe the improper btree state.  If, however, consumers of that data require that lookups in that range tree succeed up until `dnode_sync_free_range_impl` is called, then the `range_tree_vacate` strategy probably needs rethinking.  (To likely be replaced with something that leaves the btree in a valid state while it iterates through its contents, removing them.)  I don't personally know enough about the innards here to make a suggestion one way or the other.

**Comment by pfmooney** [comment]
On the note of danger with `dn_mtx`, it seems like this check in `dnode_sync` is probably unsafe as written (accessing `dn_free_ranges` without holding `dn_mtx`):
https://github.com/openzfs/zfs/blob/6d8da84106de1fc8480e1758cc88e81393b4c0c2/module/zfs/dnode_sync.c#L765-L768

**Comment by ahrens** [comment]
It looks like dbuf_read_hole() -> dnode_block_freed() relies on being able to see a free'd block be either in the range tree, or with a hole BP (`BP_IS_HOLE(db->db_blkptr)`).  So I don't think we can just transfer the dn_free_ranges[txgoff] to a local variable and NULL it out.

I think from the point of view of dnode_block_freed() at least, it's fine for it to see it as in the range tree even after we've freed the block on disk.  So we could have dnode_sync() essentially do the dnode_sync_free_range_impl()'s first, and then remove the entries from the range tree.   We could do this all-at-once (i.e. do all the free_range_impl()'s, then get the lock and range_tree_vacate()), or it could be incremental (remove entry from range as we go).

Take a look at the code and see if you agree with this, and I'll take a closer look tomorrow as well.

**Comment by pfmooney** [comment]
Thanks for taking a look.

> It looks like dbuf_read_hole() -> dnode_block_freed() relies on being able to see a free'd block be either in the range tree, or with a hole BP (`BP_IS_HOLE(db->db_blkptr)`). So I don't think we can just transfer the dn_free_ranges[txgoff] to a local variable and NULL it out.

I figured this might be the case, so it's good to get confirmation.

> I think from the point of view of dnode_block_freed() at least, it's fine for it to see it as in the range tree even after we've freed the block on disk. So we could have dnode_sync() essentially do the dnode_sync_free_range_impl()'s first, and then remove the entries from the range tree. We could do this all-at-once (i.e. do all the free_range_impl()'s, then get the lock and range_tree_vacate()), or it could be incremental (remove entry from range as we go).

If it's safe for the items to remain in the tree (and therefore visible to `dnode_block_freed()`) while the others are being freed, that seems like the ideal case, since it avoid all the tree rebalancing as the current code does.  Considering the dropped `dn_mtx` (as part of `dnode_sync_free_range_impl()`) was already somewhat of a surprise, would it be prudent to put an additional guard in place to protect `dn_free_ranges` from modification during the walk, or is that already inherent with the current logic flow?

> Take a look at the code and see if you agree with this, and I'll take a closer look tomorrow as well.

I'll work on drafting something up to check if it seems suitable.

**Comment by ahrens** [comment]
This entry in dn_free_ranges shouldn't be modified while dnode_sync...() is accessing/modifying it.  Since it's specific to this txg, and we can't add more changes once it's in syncing context.

**Comment by pfmooney** [comment]
I changed how the range tree was processed and then emptied.  [On illumos](https://code.illumos.org/c/illumos-gate/+/867) it seemed to perform as desired under the previously problematic workload.  Cherry-picked onto openzfs, it applied cleanly: pfmooney/openzfs@4a38cbd02c508a2c58080ffe109f12b7c2e87749

**Comment by ahrens** [comment]
Looks good to me.  Could you open a PR against OpenZFS with that diff?

**Comment by pfmooney** [comment]
> Looks good to me. Could you open a PR against OpenZFS with that diff?

Done!  Open as #10823

**Comment by pfmooney** [comment]
Thanks for your help on this.
