### ISSUE TITLE
scrub used to fix known data errors causes pool to become degraded, zpool clear restarts scrub

### ISSUE THREAD

**Issue by eharris** [openzfs/zfs#10709]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Buster (stable)
Linux Kernel	|  4.19.0-10-amd64
Architecture	| amd64
ZFS Version	| 0.7.13-1~bpo9+1
SPL Version	| 0.7.13-1~bpo9+1

### Describe the problem you're observing

This is partly a question as well as a feature request.

I had a drive in a very large raidz pool that started to fail, with some sectors returning read errors, but still able to access most of the data.  SMART does not yet report the drive as failing, but the extended offline tests have started to consistently report "Completed: read failure" and the Current_Pending_Sector and Offline_Uncorrectable attributes are near a thousand and are increasing over time.  I did a scrub (which for this pool takes almost a week) which successfully found and repaired some errors on the pool.  However the SMART data indicates that more unreadable sectors are developing.

Rather than wait for the drive to fail completely, I decided to proactively replace the drive, but I wanted to do so in such a way that the pool was without redundancy for a minimum amount of time, and also to have full control over how the recovery was handled, without impacting the performance of this production system.

Since I wasn't sure how zfs would treat the failing drive, and I'm quite familiar with and trust using ddrescue for doing data recovery on drives while minimizing the chances to damage the drive further, I decided to remove the drive and use another system and ddrescue to clone it (insofar as it was possible) rather than doing a traditional `zpool replace`.  I knew that using `zpool replace` would either end up causing a bunch of read errors and VFS stalls, or was likely to take about as much time as a scrub, which I did not want (since doing a scrub on this pool takes almost a week).  There would also be lots of other disk contention on the primary system that would cause the replace to take longer than cloning in a separate system would.

So I pulled the failing drive and used another system and ddrescue to clone it to a new one, which only took about 12 hours.  I then added the newly cloned drive back into the primary system and re-imported the pool as if it was the original drive.  So far so good, the pool and all drives show up as online, and I know that the vast majority of the data in the pool has redundancy, except for a few relatively small holes of data where there were unreadable sectors on the original drive.

Now comes the problem: I started a scrub to repair the small amount of missing data that wasn't on the freshly cloned drive.  After encountering and repairing a fairly small number of errors (less than 20), `zpool status` shows that zfs has marked the drive and the entire pool as DEGRADED and reported "too many errors" next to the drive that has been replaced.

Since I didn't want the pool to be without redundancy (and the DEGRADED seems to indicate that zfs is considering it to be without redundancy) I tried to find any zfs or pool properties that would either temporarily disable CKSUM errors from causing the disk to cause the pool to go into DEGRADED state, or to raise the limit of the number of errors before zfs would mark it as DEGRADED, but I wasn't able to find anything.

I know the replacement drive is good since it was thoroughly tested before being cloned onto, and there are no new drive or zfs errors in dmesg since the new drive was installed.  So as a last-ditch effort to get the pool back into a non-degraded state, I used `zpool clear`, which did successfully get the pool and drive back into ONLINE state, but also (and this is the undesired part) caused the scrub to restart from the beginning.  If I have to clear the device several times, the scrub will be wasting lots of time re-checking already checked and fixed data, which will end up delaying it fixing the remaining data errors and also potentially causing it to go into degraded state.

So here are the questions:

* Is there a way to temporarily make it so that repaired CKSUM errors do not cause a device/pool to become DEGRADED?
* Is there a way to do a `zpool clear` where the in-progress scrub will continue from the point of the last repaired error rather than restarting from the beginning?

Assuming there aren't good answers to those questions, here are the feature requests:

* Add a pool property that either temporarily suppresses repaired checksum (and maybe even read?) errors from causing a device/pool to become degraded, or add the ability to set a property/flag that remains in effect for the duration of the currently in-progress scrub that does so.  Alternatively, have the ability to configure a different (higher) limit that controls this behavior.
* Change the scrub to resume from the point of the last known good data rather than restart from the beginning when a `zpool clear` is issued.  The user can always start another scrub after all errors are repaired if desired.
* Improve and clarify the documentation on how zfs decides when a device/pool becomes degraded.  How many errors of what type?  What properties can be set to control the behavior?
* Add a note to the documentation for `zpool clear` that doing so will cause an in-progress scrub to restart, and pointers to info on how to avoid that.

**Comment by richardelling** [comment]
degraded does not mean there is no redundancy.

**Comment by eharris** [comment]
According to the original Oracle docs at https://docs.oracle.com/cd/E19253-01/819-5461/gamno/index.html if there is a degraded status on a raidz that normally only has a single disk of redundancy, it suggests that this means there is no longer any redundancy.

**Comment by richardelling** [comment]
the Oracle docs say a common case is if a disk is missing, but that is not your case

**Comment by eharris** [comment]
Comment to keep alive.
