### ISSUE TITLE
wishlist: make the mtime of .zfs/snapshot entries the creation time of the corresponding snapshot

### ISSUE THREAD

**Issue by akorn** [openzfs/zfs#10718]
### System information
ZFS Version	| 0.8.4

### Describe the problem you're observing

The mtime, ctime and atime of all entries under foo/.zfs/snapshot are the same as those of foo.

### Describe how to reproduce the problem

`ls -rt .zfs/snapshot` doesn't meaningfully sort the snapshots.

It would be nice if `ls(1)` could sort snapshots by creation time.

I realize this is possible with `zfs list`, but the syntax is much more complicated and verbose.

I also realize this would have a performance cost, because currently the creation time doesn't need to be retrieved when listing `.zfs/snapshot`. Maybe make the behaviour configurable using a zfs module parameter?

**Comment by ds6** [comment]
This appears to be a duplicate of #10690.

**Comment by akorn** [comment]
Quite. My bad.
