### ISSUE TITLE
zfs send -e (embedded, unencrypted) can't be received as child of encrypted fs

### ISSUE THREAD

**Issue by mattcen** [openzfs/zfs#10732]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Debian GNU/Linux 10 (buster)
Linux Kernel	| 4.19.0-10
Architecture	| amd64
ZFS Version	| 0.8.4-2~bpo10+1
SPL Version	| 0.8.4-2~bpo10+1

### Describe the problem you're observing

When I try to `zfs send` an unencrypted ZFS dataset, and then `zfs receive` that as a child of an encrypted ZFS dataset, I receive the error:

```
cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream.
```

When trying the same on macOS, I receive this error:

```
cannot receive new filesystem stream: incompatible embedded data stream feature with encrypted receive.
warning: cannot send 'zfstest/nocrypt@sendme': signal received
```

### Describe how to reproduce the problem

On an unencrypted dataset of a ZFS pool:

```sh
pool=myzfspool
echo mypassphrase > /tmp/zfskeyfile
zfs create "$pool"/testing
zfs create "$pool"/testing/nocrypt
zfs create -o encryption=on -o keyformat=passphrase -o keylocation=file:///tmp/zfskeyfile "$pool"/testing/crypt
zfs snapshot "$pool"/testing/nocrypt@sendme
zfs send -vLecR "$pool"/testing/nocrypt@sendme | zfs receive -Fvs -x encryption "$pool"/testing/crypt/nocrypt
```
Note the error displayed at this point. This error occurs regardless of whether I'm sending data within the same pool, or from one pool to another (on the same machine).

For cleanup:
```sh
zfs destroy -r "$pool"/testing
rm /tmp/zfskeyfile
```

**Comment by ElvishJerricco** [comment]
If you take the `-s` flag off the receive command, you get a different error message:

```
cannot receive new filesystem stream: incompatible embedded data stream feature with encrypted receive.
```

Which indicates you need to take the `-e` flag off the send command. Doing so (even with the `-s` flag on the receive command), will successfully complete the transfer.

Is this just a bug in the error messaging then?

**Comment by ahrens** [comment]
Yes, sounds like `zfs send -e | zfs receive <as encrypted>` simply isn't supported.  Presumably because embedded blocks can't be encrypted.  We could improve the error message here so that users can more easily understand what they need to do to encrypt a filesystem on receive (remove the `-e` flag).

**Comment by ahrens** [comment]
cc @tcaputi

**Comment by mattcen** [comment]
Ah sweet; in which case macOS's error message is much clearer, but I *still* didn't understand it (because I forget that `-e` meant 'embedded'). Removing that works much better! Thanks for help with the debugging, folks. In this case, yes, the bug is with the error message.

**Comment by AttilaFueloep** [comment]
At least this is documented in `zfs-send(8)`:

>  -e, --embed
>  ... Datasets that are sent with this flag may not be received as an encrypted dataset, since encrypted datasets cannot use the embedded_data feature
