### ISSUE TITLE
Permission denied opening file in a directory with a sticky bit

### ISSUE THREAD

**Issue by joshwilliams** [openzfs/zfs#10742]
### System information
Type | Version/Name
 --- | ---
Distribution Name	|	Ubuntu
Distribution Version	|	20.04
Linux Kernel	|	5.4.0-40
Architecture	|	x86_64
ZFS Version	|	0.8.3-1ubuntu12
SPL Version	|	0.8.3-1ubuntu12

### Describe the problem you're observing
After a recent upgrade we started seeing permission denied errors as root when working with files with a specific condition: Calling open() with `O_CREAT` on existing files with a uid that doesn't exist on the local system inside a group-writable and sticky bit set directory.

Really specific. :) But we have an `rsync --inplace` backup process that gets us into that exact condition.

### Describe how to reproduce the problem
In a directory on ZFS with a sticky bit set:
/zfs# mkdir testdir
/zfs# chmod a+t testdir
... which is group writable:
/zfs# chmod g+w testdir
... and has an existing file:
/zfs# touch testdir/test
... which has a uid which isn't present on the system:
/zfs# chown 9999 testdir/test
... then an open() call with O_CREAT fails with Permission denied:
/zfs# ./openat testdir/test
Error opening testdir/test: Permission denied (13)

That's the most narrow test case I could find. Skip any of those steps and it doesn't throw the error. It's just that specific configuration of directory permissions and file ownership that seems to do it.

The ./openat is a simple test that just runs open() (so named as I was originally testing with the openat() call) and is at: https://gist.github.com/joshwilliams/51adb08ca1a31cf63bb6748048bd4858

### Include any warning/errors/backtraces from the system logs
None in any of the system logs that I can find, somewhat surprisingly.

**Comment by BrainwreckedTech** [comment]
Good to hear it's not just me.  I've been having a problem with this for some time now.  It's an issue that just started recently and has been bugging me for a few days.  If forced to answer when it started, I'd say it was some time during the latter half of kernel 5.7's life.

All Arch Linux machines on my home network are set to use /mnt/nfs/pacman/cache as their pacman package cache directory.  The directory is owned by root with permissions 1777, and root is squashed over NFS.

This might be a regression of #6889

**Comment by joshwilliams** [comment]
And the verdict: Totally not ZFS!

Newer kernels have protections against some spoofing attacks, and that sticky bit directory behavior falls right into that pattern.

That's governed in `/proc/sys/fs/protected_regular`. In our sysctl.conf we've set:

```
fs.protected_regular=0
```

...and all is good again!

**Comment by behlendorf** [comment]
@joshwilliams thanks for getting to the bottom of this and following up!  That's good to know.
