### ISSUE TITLE
Why prevhdl is not checked?

### ISSUE THREAD

**Issue by klebertarcisio** [openzfs/zfs#10754]
In the first time of the loop, prevdb and prevhdl are NULL. Why only prevdb is checked?

Why not this?
**if (prevdb != NULL && prevhdl != NULL)** 

I'm talking about line 2133

https://github.com/openzfs/zfs/blob/f2c027bd6a003ec5793f8716e6189c389c60f47a/module/os/linux/zfs/zfs_znode.c#L2102-L2135

**Comment by behlendorf** [comment]
The contract here is that if `zfs_grab_sa_handle()` doesn't return an error then `sa_hdl` and `sa_db` must be set.  They are then always both assign together to `prevhdl` and `prevdb`.  To make this clearer and ensure it's always true we could add an ASSERT.
