### ISSUE TITLE
contrib/dracut/90zfs/zfs-generator.sh - mountpoint=legacy not handled

### ISSUE THREAD

**Issue by mlow** [openzfs/zfs#10776]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	| 0.8.4 |
SPL Version	| 0.8.4 |

### Describe the problem you're observing
`zfs-generator.sh` is used to generate a systemd unit override to 'enhance' the sysroot.mount unit so it properly mounts the ZFS filesystem when using systemd with dracut. However, it will always include `zfsutil` in the mount options, even when the r|
oot dataset has `mountpoint=legacy`. This will result in a failure to mount the root filesystem to /sysroot, and contradicts the instructions in the [readme](https://github.com/openzfs/zfs/blob/master/contrib/dracut/README.dracut.markdown) which states it is possible to set `mountpoint=legacy` along with root kernel command line parameter to `root=ZFS=<dataset>`

The `zfsutil` mount option should not be included in the generated zfs-enhancement.conf file if the root filesystem has `mountpoint=legacy`.

### Describe how to reproduce the problem
I'll use the dataset `tank/rootfs` as the root filesystem in this example.

Set mountpoint=legacy:
```
zfs set mountpoint=legacy tank/rootfs
```

Boot with a systemd based dracut initramfs image and the kernel command line parameter: `root=ZFS=tank/rootfs`

You will be dropped into the emergency shell. At this point it's possible to manually mount the dataset:
```
mount -t zfs tank/rootfs /sysroot
```

And then quit to boot the system.

### Include any warning/errors/backtraces from the system logs
```
filesystem 'tank/rootfs' cannot be mounted using 'zfs mount'.
Use 'zfs set mountpoint=/sysroot' or 'mount -t zfs tank/rootfs /sysroot'.
See zfs(8) for more information.
```

**Comment by L117** [comment]
I have the same issue.
