### ISSUE TITLE
On zfs recv: ASSERT at libzfs_sendrecv.c:2798:recv_fix_encryption_hierarchy()

### ISSUE THREAD

**Issue by helamonster** [openzfs/zfs#10787]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Ubuntu
Distribution Version	|20.04
Linux Kernel	|5.4.0-42-generic \#46-Ubuntu
Architecture	|x86_64
ZFS Version	|0.8.4-1~20.04.york0
SPL Version	|0.8.4-1~20.04.york0

### Describe the problem you're observing
ASSERT on recv side when performing zfs send | zfs recv.
```
root@latitude # zfs send -w -e -c  -L -h -vP -I rpool@2020-08-22-07-46-08 \
  rpool@2020-08-22-08-01-09 | ssh remote-host \
  /sbin/zfs recv -svuF dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool

incremental     2020-08-22-08-06-29     rpool@2020-08-22-08-07-14       624
size    624
fromsnap: '2020-08-22-08-06-29'
tosnap: '2020-08-22-08-07-14'
not_recursive
raw
fss:
    0x86512878ff7ab155:
        name: 'rpool'
        parentfromsnap: 0
        snaps:
            2020-08-22-08-06-29: 2548202800809738513
            2020-08-22-08-07-14: 10098525071028946977
        snapprops:
            2020-08-22-08-07-14:
        snapholds:
            2020-08-22-08-07-14:
rpool@2020-08-22-08-07-14:
    fromsnap: '2020-08-22-08-06-29'
receiving incremental stream of rpool@2020-08-22-08-07-14 into dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool@2020-08-22-08-07-14
0 == nvlist_lookup_nvlist(stream_nvfs, "props", &props)
ASSERT at libzfs_sendrecv.c:2798:recv_fix_encryption_hierarchy()

root@latitude # echo "Pipe status: ${PIPESTATUS[*]}"
Pipe status: 0 255

```
Pool structure:
```
root@latitude # zfs list -r rpool -o name,encryption
NAME                         ENCRYPTION
rpool                               off
rpool/ROOT                          off
rpool/ROOT/arch                     off
rpool/ROOT/arch/HEAD                off
rpool/ROOT/arch/TEST                off
rpool/ROOT/ubuntu                   off
rpool/ROOT/ubuntu/HEAD              off
rpool/ROOT/ubuntu/HEAD/tmp          off
rpool/ROOT/ubuntu/HEAD/var          off
rpool/ROOT/ubuntu/TEST              off
rpool/home                          off
rpool/home/jeremy                   off
rpool/home/root                     off
rpool/private               aes-256-gcm
rpool/scratch                       off
```

However, if I perform a recursive send ( adding the `-R` argument ), it works fine:
```
root@latitude # zfs send -w -e -c -R -L -h -vP -I rpool@2020-08-22-07-46-08 \
  rpool@2020-08-22-08-01-09 | ssh remote-host \
  /sbin/zfs recv -svuF dpool/backups/xyz/jbsnet/latitude/CURRENT/rpool
```

### Describe how to reproduce the problem
I'm not quite sure yet how the system got into this state where it is failing to do incremental receives.

### Include any warning/errors/backtraces from the system logs
There is no output from `/proc/spl/kstat/zfs/dbgmsg` during the zfs recv. The only thing I get is the zfs recv exit code and ASSERT info listed above.

**Comment by helamonster** [comment]
I'm experiencing this also on another system (sending from one pool to another on the same system):
```
root@server $ zfs send -w -e -c -L -h -vP -I \
  rpool@2020-08-24-07-56-22 \
  rpool@2020-08-24-07-58-47 | \
  /usr/sbin/zfs recv -vusF data/rpool

incremental     2020-08-24-07-56-22     rpool@2020-08-24-07-58-47       624
size    624
receiving incremental stream of rpool@2020-08-24-07-58-47 into data/rpool@2020-08-24-07-58-47
snap data/rpool@2020-08-24-07-58-47 already exists; ignoring
received 0B stream in 1 seconds (0B/sec)
0 == nvlist_lookup_nvlist(stream_nvfs, "props", &props)
ASSERT at libzfs_sendrecv.c:2798:recv_fix_encryption_hierarchy()Aborted

root@server $ echo ${PIPESTATUS[@]}

0 134
```

**Comment by helamonster** [comment]
Note:

While the ASSERTION fails and the zfs recv command returns exit code 134, the incremental receive to the next snapshot (not all snapshots including the last one specified on the command line) appears to complete successfully.

So, after multiple such executions, the zfs recv seems to have worked, but I don't know if my datasets have been left in a good state after this.

**Comment by helamonster** [comment]
This issue has hit a couple more of my servers, including mission critical ones so I'd like to get to the bottom of this ASAP. Any help would be greatly appreciated.

The line of code doing the ASSERT:

`VERIFY(0 == nvlist_lookup_nvlist(stream_nvfs, "props", &props));`

From git, this is `libzfs_sendrecv.c`, line `3091`.

It appears that the `recv_fix_encryption_hierarchy` function expects there to be no props in the nvlist, but the nvlist is apparently not empty.


Related comments:
`recv_fix_encryption_hierarchy` function
```
/*
 * This function reestablishes the hierarchy of encryption roots after a
 * recursive incremental receive has completed. This must be done after the
 * second call to recv_incremental_replication() has renamed and promoted all
 * sent datasets to their final locations in the dataset hierarchy.
 */
```

Elsewhere:
```
		/*
		 * The keylocation property may only be set on encryption roots,
		 * but this dataset might not become an encryption root until
		 * recv_fix_encryption_hierarchy() is called. That function
		 * will fixup the keylocation anyway, so we temporarily unset
		 * the keylocation for now to avoid any errors from the receive
		 * ioctl.
		 */
```

None of my datasets have encryption enabled nor a value for `keylocation`.

**Comment by behlendorf** [comment]
@helamonster I believe the issue may be caused by specifying `-w`  (raw) option to `zfs send` when the dataset isn't encrypted.  As described in the `zfs-send(8)` man page this is equivalent to `-Lec`, which you've also specified.  However it looks like `-w` will result in `recv_fix_encryption_hierarchy()` being called when it doesn't need to be, since there is no hierarchy of encryption roots to reestablish in your case.  It looks like you can avoid the issue from now by removing the unnecessary `-w` option from the command line.

@tcaputi would you mind having a quick look at this too.

**Comment by helamonster** [comment]
Just got back to this today. I actually removed the `-h` from the zfs send command and was able to receive without any problem.
