### ISSUE TITLE
zpool command complains about /etc/exports.d

### ISSUE THREAD

**Issue by richardelling** [openzfs/zfs#10785]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| N/A
Distribution Version	| N/A
Linux Kernel	| N/A
Architecture	| N/A
ZFS Version	| post c15d36c674bcfb10975fc835978d4a49d159bf0b
SPL Version	|

### Describe the problem you're observing

If the /etc/exports.d directory does not exist, then `libshare_nfs_init()` attempts to
create it. This can and should fail for non-root users. However, attempts
to run `zpool` as a non-root user are rewarded with
```
user$ zpool list
failed to create /etc/exports.d: Permission denied
no pools available
```

### Describe how to reproduce the problem

1. Verify the /etc/exports.d directory does not exist
2. As a non-root user, type `zpool list`

**Comment by richardelling** [comment]
@grwilson I noticed this when testing zpool_influxdb https://github.com/openzfs/zfs/pull/10786 and was surprised that it seems libzfs_init() causes this.

**Comment by grwilson** [comment]
@richardelling thanks for filing the issue, I'm working on fixing this and will open a PR soon.

**Comment by gyakovlev** [comment]
it also affects grub in a funny way https://bugs.gentoo.org/742503
gentoo package builds are sandboxed, so if grub built with libzfs, it triggers sandbox violation, because some libzfs linked binaries are run during build.
