### ISSUE TITLE
Zpool scrub returns "repaired 0" instead of completed

### ISSUE THREAD

**Issue by tigloo** [openzfs/zfs#1079]
I'm not sure if this is cosmetic issue or a bug. Feel free to discard if irrelevant.

After finishing a scrub operation, ZFS reports:

```
  pool: tank
 state: ONLINE
 scan: scrub repaired 0 in 1h18m with 0 errors on Tue Nov  6 22:47:38 2012
config:

        NAME                                    STATE     READ WRITE CKSUM
        tank                                    ONLINE       0     0     0
          raidz2-0                              ONLINE       0     0     0
            scsi-SATA_ST3000DM001-9YN_S1F0MYWK  ONLINE       0     0     0
            scsi-SATA_ST3000DM001-9YN_W1F0VW8Z  ONLINE       0     0     0
            scsi-SATA_ST3000DM001-9YN_Z1F0Q831  ONLINE       0     0     0
            scsi-SATA_ST3000DM001-9YN_Z1F0QYAT  ONLINE       0     0     0

errors: No known data errors
```

I would have expected "scrub completed", because "repaired 0" sounds like data recovery was actually attempted. The pool shows no errors though.

**Comment by GTP95** [comment]
I'm confused. You say that this is the output expected from an healty pool, but when my pool was "new" the zpool status command used to output "scan: none requested". But now now i get: "scan: scrub repaired 0 in 0h12m with 0 errors on Sun Nov 13 00:36:50 2016". Why should it have changed? I would think that an automatic scrub was done for some reason but it didn't find any error, but I'm not sure. Could you please clarify this to me? Full output of the command below:
giacomo@FOTO:~$ sudo zpool status
  pool: FOTO
 state: ONLINE
  scan: scrub repaired 0 in 0h12m with 0 errors on Sun Nov 13 00:36:50 2016
config:

        NAME                                  STATE     READ WRITE CKSUM
        FOTO                                  ONLINE       0     0     0
          mirror-0                            ONLINE       0     0     0
            ata-TOSHIBA_DT01ACA100_951LS13NS  ONLINE       0     0     0
            ata-TOSHIBA_DT01ACA100_951LS06NS  ONLINE       0     0     0

errors: No known data errors


Sorry for poor formatting, I'm writing from my smartphone.
