### ISSUE TITLE
ZFS Channel Program ZCP , insane raise in memory consumption

### ISSUE THREAD

**Issue by michaelvvvvv** [openzfs/zfs#10801]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu , but also Proxmox 6.2-x
Distribution Version	| 20.4 LTS
Linux Kernel	| 5.4.0-42-generic
Architecture	| x86_64
ZFS Version	| 0.8.3
SPL Version	| 0.8.3

### Describe the problem you're observing

After having a lot of snapshot, I started using ZCP for getting it faster , which works very well.

I discovered that query through 12000 snapshots on a zpool took up approximately 1.7 mbyte of memory , running
it with this cmd **zfs program -j -m 1700000 -t 500000 rpool /var/www/html/channel/test.lua rpool 1**

when having more that 16628 on my server I got this error **Memory limit exhausted** , when running
this cmd **zfs program -j -m 100000000 -t 500000 rpool /var/www/html/channel/test.lua rpool 1**

So getting **38.56** percent more snapshots uses **58.82** times more memory **5882** percent.

My Channel Program..

________________________________________________________________________________________

args = ...

dataset = args["argv"][1]

recursive = 0 -- shall we got recursive
slow      = 0 -- shall add more info to snapshots slower

if (args["argv"][2]) then
    recursive = tonumber(args["argv"][2])
end

if (args["argv"][3]) then
    slow = tonumber(args["argv"][3])
end

d_nr=0
s_nr=0
snaps = {}
datasets = {}

function gather_collect(root, to_collect)
    for child in zfs.list.children(root) do
	if recursive==1 then
    	    to_collect = gather_collect(child, to_collect)
	end 
    end
    for snap in zfs.list.snapshots(root) do
        for clone in zfs.list.clones(snap) do
	    if recursive==1 then
        	to_collect = gather_collect(clone, to_collect)
	    end
        end

        guid = zfs.get_prop(snap,"guid")
        createtxg = zfs.get_prop(snap,"createtxg")
        
        used = 0
        creation = 0
        referenced = 0

        if slow==1 then
          used = zfs.get_prop(snap,"used")
          referenced = zfs.get_prop(snap,"referenced")
          creation = zfs.get_prop(snap,"creation")
        end

        resultset = snap .. "," .. guid .. "," .. createtxg .. "," .. used .. "," .. referenced .. "," .. creation

        table.insert(snaps, resultset)
    end

    guid = zfs.get_prop(root,"guid")
    createtxg = zfs.get_prop(root,"createtxg")
    usedbydataset = zfs.get_prop(root,"usedbydataset")
    usedbysnapshots = zfs.get_prop(root,"usedbysnapshots") 
    used = zfs.get_prop(root,"used")
    creation = zfs.get_prop(root,"creation")
    
    resultset = root .. "," .. guid .. "," .. createtxg  .. "," .. usedbydataset .. "," .. usedbysnapshots .. "," .. used .. "," .. creation

    table.insert(datasets, resultset)
    return to_collect
end

gather_collect(dataset, {})

version = "0.02"

d_nr = #datasets
s_nr = #snaps

results = {}
results["ver"] = version
results["snr"] = s_nr
results["dnr"] = d_nr
results["dataset"] = datasets
results["snaps"] = snaps

return results
________________________________________________________________________________________

Sorry tried to set my channel program in the **code** tag but whatever i do github formatting is very bad.

### Describe how to reproduce the problem
It's quite easy. I have installed sanoid  , https://github.com/jimsalterjrs/sanoid and after some time you'll hare a
bunch of snapshots. It goes faster If you have more dataset as on Proxmox and Ubuntu 20.4 by default.

**Comment by kernelOfTruth** [comment]
what are your hardware specs, how is the zfs pool set up ?

what is the composition of the files (numbers, size, etc.) ?

**Comment by michaelvvvvv** [comment]
Hardware specs does not matter , as it's a memory behavior issue , see my post.
You will need at lot of snapshots on a zpool to trigger this.

I was hoping too make a function which could list all my snapshots very fast on an entire zpool.

This was not possible , so I did a listning on each dataset instead.

Just in case Hardware...

Amd Ryzen 3600
64Gb RAM
NVmn 1TB 
Several Harddirves not running on ZFS.
