### ISSUE TITLE
Rename "Type: Test Suite" to "Component: Test Suite"

### ISSUE THREAD

**Issue by Ornias1993** [openzfs/zfs#10803]
### Describe the feature would like to see added to OpenZFS

A clear and simple rename of the current "Type: Test Suite" to "Component: Test Suite"

### How will this feature improve OpenZFS?

The test suite and build bots are, for a rather large part, part of the OpenZFS codebase.
A lot of test related issues actually require a PR/commit in either this repo or the Buildbot repo to fix.
Those issues can also very in type: Regressions, defects, questions, performance etc.

Hence it makes a lot more sense to tag "Test Suite" related issues as a component instead of a type

**Comment by behlendorf** [comment]
Agreed, renamed.
