### ISSUE TITLE
Remove tags for: outdated test results and Missing Template

### ISSUE THREAD

**Issue by Ornias1993** [openzfs/zfs#10804]
### Describe the feature would like to see added to OpenZFS

Remove the tags:
"outdated test results"
and
"Missing Template"

### How will this feature improve OpenZFS?

Those tags feel like the odd-kid-on-the-block, considering this project has clearly moved to "Type", "Status" and "Component" based tagging.
If indeed it needs retesting or is missing a template in such a way that it's hindering contributors for working on the issue, this would basically already be a "Status: Feedback requested". Because a problematic missing template already means information would be missing and test results are also a form of feedback.
The only thing would be that the maintainer needs to be clear what type of feedback he wants on the issue itself, but thats already the standard practice on this repo.

Just removing those tags and retagging the currently tagged issues as "Status: Feedback requested" would work just fine. In cases where it wouldn't be clear what feedback was requested, a manual comment might be requried.

### Additional context

To be clear: Both of those tags aren't used very frequently anymore and most issues having those would already be either stale or close to stale

*edit*
It looks like most of these tags are already added in companion of "Status: Feedback requested", which makes the transfer quite easy.
They also looks to be mostly used prior to 2019

**Comment by behlendorf** [comment]
In practice these labels were not used, I've removed both.
