### ISSUE TITLE
How to build zfs on Linux so that its function arguments are saved on stack?

### ISSUE THREAD

**Issue by youzhongyang** [openzfs/zfs#10817]
### Ask your question!
When analyzing Linux OS crash dump, it seems it's almost impossible to find out what the argument values of the function on the stack trace are, as you can see in the assembly code, it does not push/save %rdi, %rsi and such to the stack.

Is there a way to build zfs so that it can do a better job for debugging/troubleshooting purposes?

**Comment by richardelling** [comment]
There are about 2 million compiler options (maybe more? :-) and more than one compiler supported.
If there is one needed to add this, then look at config/always-compiler-options.m4

**Comment by behlendorf** [comment]
The [2019 OpenZFS Developer Summit](https://openzfs.org/wiki/OpenZFS_Developer_Summit_2019) had two good talks on debugging ZFS.  You might be interested in "Debugging ZFS: State of the Art on Linux", and "Debugging ZFS: From Illumos to Linux".

**Comment by youzhongyang** [comment]
@behlendorf Thanks, I've watched those two talks, very helpful.

**Comment by youzhongyang** [comment]
@richardelling Yeah there are too many compiler options. I saw some fancy stack trace with well-formated arguments and values, probably posted by some FreeBSD developer. On illumos, it is also possible to get kernel function arguments. On Linux, I am still struggling ...

**Comment by behlendorf** [comment]
@youzhongyang if you find a debugging tool which can do this I'd love to know.  Personally, I've always resorted to using `crash` which does let you dump the full stack frame.  But you need to manually inspect the stack frame to find what you're looking for which is a lot of work.

**Comment by youzhongyang** [comment]
@behlendorf Yes, I use crash utility to analyze OS crash dump, it can dump stack trace, with no arguments for each function on the stack trace. I disassembled some zfs functions + some Linux kernel functions, I can see it is not compiled/built in such a way that arguments can be digged out from the stack.

**Comment by behlendorf** [comment]
@youzhongyang you can use the `--enable-debuginfo` option to configure to enable some additional debug flags, specifically `-g -fno-inline -fno-ipa-sra`.

**Comment by youzhongyang** [comment]
@behlendorf Thanks. My zfs was built with --enable-debuginfo, I can load the debug zfs.ko et al and inspect zfs structs once I have the pointer, but I am trying to find out how I can get the args of each function on the stack trace.

**Comment by youzhongyang** [comment]
I see what you meant. My zfs version is 0.8.4, master branch checks no-ipa-sra stuff. I will modify options for 0.8.4 to use -g -fno-inline -fno-ipa-sra, see if it makes a difference.

**Comment by youzhongyang** [comment]
Illumos used a patched version of gcc to do the source code compiling. It is modified to support option '-msave-args'. The official version of gcc does push function args to stack under -O0 (no optimization), but once optimization is turned on, it stops doing that.

Here is an example under illumos:
```
> zfs_fid::dis
zfs_fid:                        pushq  %rbp
zfs_fid+1:                      movq   %rsp,%rbp
zfs_fid+4:                      subq   $0x60,%rsp
zfs_fid+8:                      movq   %r12,-0x40(%rbp)
zfs_fid+0xc:                    movq   %r13,-0x38(%rbp)
zfs_fid+0x10:                   movq   %rsi,%r13
zfs_fid+0x13:                   movq   %rsi,-0x10(%rbp) <---- save 2nd arg on stack
zfs_fid+0x17:                   movq   %rdi,-0x8(%rbp)  <---- save 1st arg on stack
```

While under Linux, there's no way you can get the args from the stack:
```
crash> dis zfs_fid
<zfs_fid>:   nopl   0x0(%rax,%rax,1) [FTRACE NOP]
<zfs_fid+5>: push   %rbp
<zfs_fid+6>: mov    %rsp,%rbp
<zfs_fid+9>: push   %r15
<zfs_fid+11>:        push   %r14
<zfs_fid+13>:        push   %r13
<zfs_fid+15>:        mov    %rdi,%r13
<zfs_fid+18>:        push   %r12
<zfs_fid+20>:        push   %rbx
<zfs_fid+21>:        mov    %rsi,%rbx
<zfs_fid+24>:        mov    $0xffffffffc0ac59e0,%rsi
<zfs_fid+31>:        sub    $0x10,%rsp
<zfs_fid+35>:        mov    -0x1f8(%rdi),%r14
<zfs_fid+42>:        mov    %gs:0x28,%rax
<zfs_fid+51>:        mov    %rax,-0x30(%rbp)
<zfs_fid+55>:        xor    %eax,%eax
<zfs_fid+57>:        mov    0x28(%rdi),%rax
<zfs_fid+61>:        mov    0x3b8(%rax),%r15
<zfs_fid+68>:        lea    0x108(%r15),%r12
<zfs_fid+75>:        mov    %r12,%rdi
<zfs_fid+78>:        callq  0xffffffffc099b5d0 <rrm_enter_read>
```
