### ISSUE TITLE
Combine "Stale" and "Inactive" labels

### ISSUE THREAD

**Issue by Ornias1993** [openzfs/zfs#10815]
### Describe the feature would like to see added to OpenZFS

Combine the "Status: Stale" and "Status: Inactive" labels.
Preferably into just "Status: Stale" 

Means about the same, otherwise the bot is going to double tag a lot and it would need a bot config change

### How will this feature improve OpenZFS?

it would unify "PR" centered tags (Inactive) and Issue centered tags (Stale), which basically serve the same goal.

### Additional context

This does not mean enabling stalebot on the PR's, it's just using the same label the bot would otherwise use manually on PR's, just like inactive is used now.

**Comment by Spencer-Kinny** [comment]
@Ornias1993 

Could you please hint at which files/components need to be updated for this change.

**Comment by Ornias1993** [comment]
@sailnfool nothing, it was part of a series of suggested github labeling changes.

However: i have been looking into github addons that would make the github config editable from a file (and thus PR’able)... but such a thing would need more carefull consideratiom.

**Comment by Spencer-Kinny** [comment]
@Ornias1993 
alright

**Comment by Ornias1993** [comment]
I think the repo is running quite well at the moment, hence closing this.
If this ever gets implemented it would most likely be within the scope of a complete repo-process overhaul anyway.
