### ISSUE TITLE
configure fails with --enable-linux-builtin when CONFIG_MODULES=n 

### ISSUE THREAD

**Issue by nihil-2019** [openzfs/zfs#10832]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Arch
Distribution Version	| rolling (up to date as of the submission of this bug report)
Linux Kernel	| 5.8.4
Architecture	| x86-64
ZFS Version	| 2.0.0-rc1
SPL Version	| 2.0.0-rc1

### Describe the problem you're observing
After copying my `.config` & running `make prepare` under a copy of the Linux source, then running `autogen.sh` & `configure` with `--enable-linux-builtin` in a clean zfs source tree, I get the error
```
configure: error: 
        *** Unable to build an empty module.
        *** Please run 'make scripts' inside the kernel source tree.
```
I also tried to run `make oldconfig` & `make scripts` in the kernel directory before re-cloning the zfs tree & retrying the above steps, though I do realize that `make prepare` builds those targets automatically - still the same result. Note that I was able to successfully build zfs into the kernel with 5.6/0.8.x just a few months ago, & each time `configure` ran normally.
### Describe how to reproduce the problem
Run `make prepare` in a configured Linux source tree (in this case under /tmp/linux/), then run `sh autogen.sh` & `sh configure --with-config=kernel --with-linux=/tmp/linux/ --with-linux-obj=/tmp/linux/ --enable-linux-builtin`. `configure` will fail.
### Include any warning/errors/backtraces from the system logs
`config.log` (before patch):
```
configure:13570: checking kernel file name for module symbols     
configure:13600: result: NONE                                                  
configure:13701: checking whether modules can be built             
configure:13762:                     
            KBUILD_MODPOST_NOFINAL= KBUILD_MODPOST_WARN=     
            make modules -k -j16 -C /tmp/linux/                         
            M=/tmp/zfs/build/conftest >build/conftest/build.log 2>&1     
configure:13765: $? = 2                                                   
configure:13768: test -f build/conftest/conftest.o                  
configure:13771: $? = 1     
configure:13779: result: no     
configure:13786: error:      
        *** Unable to build an empty module.     
        *** Please run 'make scripts' inside the kernel source tree.
```
`build/conftest/build.log`:
```
make: Entering directory '/tmp/linux'    
make[1]: *** No rule to make target '/tmp/zfs/build/conftest/modules.order', needed by '/tmp/zfs/build/conftest/Module.symvers'.    
WARNING: Symbol version dump "Module.symvers" is missing.    
         Modules may not have dependencies or modversions.    
make[1]: Target '__modpost' not remade because of errors.    
make: *** [Makefile:1672: modules] Error 2    
make: Leaving directory '/tmp/linux'
```

**Comment by behlendorf** [comment]
@nihil-2019 the issue might related to specifying `--with-config=kernel`.  The procedure we use to test the built in functionality is described in this https://github.com/openzfs/zfs/issues/10450#issuecomment-643654436 .  Can you give it another try following those steps.

**Comment by nihil-2019** [comment]
The issue seems to be zfs tripping up on `CONFIG_MODULES=n` again... Both my config & the x86-64 defconfig pass `configure` with that option set to y, & fail with it on n, regardless of whether `--with-config=kernel` is specified or not. The false detection of `CONFIG_DEBUG_LOCK_ALLOC` seems to not be an actual issue but rather the result of that test depending on `ZFS_AC_KERNEL_TEST_MODULE`, as it only happens when patching that out, so I'll go ahead & remove that from the initial post.

**Comment by RoelofSol** [comment]
One solution to get modules building again is to add MODORDER and an output file to config/kernel.m4:LINUX_COMPILE to 

```
AC_DEFUN([ZFS_LINUX_COMPILE], [
	AC_TRY_COMMAND([
	    KBUILD_MODPOST_NOFINAL="$5" KBUILD_MODPOST_WARN="$6"
	    make modules -k -j$TEST_JOBS -C $LINUX_OBJ $ARCH_UM
	    M=$PWD/$1 MODORDER=/dev/null $(basename $1).o >$1/build.log 2>&1])
	AS_IF([AC_TRY_COMMAND([$2])], [$3], [$4])
])
```

**Comment by arvidbrodin** [comment]
I can confirm this error with ZFS version 2.0.5 and kernel-5.10.62.

config.log:
```
configure:17538: checking kernel source directory
configure:17581: result: /usr/src/linux
configure:17592: checking kernel build directory
configure:17619: result: /usr/src/linux
configure:17622: checking kernel source version
configure:17670: result: 5.10.62-zfs
configure:17702: checking kernel file name for module symbols
configure:17732: result: NONE
configure:17833: checking whether modules can be built
configure:17901:
            KBUILD_MODPOST_NOFINAL= KBUILD_MODPOST_WARN=
            make modules -k -j4 -C /usr/src/linux
            M=/var/tmp/portage/sys-fs/zfs-kmod-2.0.5/work/zfs-2.0.5/build/conftest >build/conftest/buil
d.log 2>&1
configure:17904: $? = 2
configure:17907: test -f build/conftest/conftest.o
configure:17910: $? = 1
configure:17918: result: no
configure:17925: error:
        *** Unable to build an empty module.
        *** Please run 'make scripts' inside the kernel source tree.
```

build/conftest/build.log:
```
make: Entering directory '/usr/src/linux-5.10.62'
make[1]: *** No rule to make target '/var/tmp/portage/sys-fs/zfs-kmod-2.0.5/work/zfs-2.0.5/build/conftest/modules.order', needed by '/var/tmp/portage/sys-fs/zfs-kmod-2.0.5/work/zfs-2.0.5/build/conftest/Module.symvers'.
WARNING: Symbol version dump "Module.symvers" is missing.
         Modules may not have dependencies or modversions.
make[1]: Target '__modpost' not remade because of errors.
make: *** [Makefile:1726: modules] Error 2
make: Leaving directory '/usr/src/linux-5.10.62'
```

After modifying "conftest" not to fail, I get additional failures of configuration tests:
```
checking whether mutex_lock() is GPL-only... yes
configure: error:
	*** Kernel built with CONFIG_DEBUG_LOCK_ALLOC which is incompatible
	*** with the CDDL license and will prevent the module linking stage
	*** from succeeding.  You must rebuild your kernel without this
	*** option enabled.

```
... which is wrong:
```
# grep CONFIG_DEBUG_LOCK_ALLOC /usr/src/linux/.config
# CONFIG_DEBUG_LOCK_ALLOC is not set
```
Again modifying this test not to fail:

```
configure: error:
	*** This kernel does not include the required zlib inflate support.
	*** Rebuild the kernel with CONFIG_ZLIB_INFLATE=y|m set.
```
... which is again wrong:
```
# grep CONFIG_ZLIB_INFLATE /usr/src/linux/.config
CONFIG_ZLIB_INFLATE=y
```

RoelofSol's change of ZFS_LINUX_COMPILE does not fix this.

I see there was talk in previous similar bug reports of adding CONFIG_MODULES=n to the integration testing. Is there some progress on that?

**Comment by arvidbrodin** [comment]
I managed to work around this issue by temporarily setting CONFIG_MODULES=y, running 'make prepare' in the kernel tree, then configuring zfs-kmod and running './copy-builtin /usr/src/linux' in the zfs-kmod source folder, then setting CONFIG_MODULES=n again (and CONFIG_ZFS=y of course), then building the kernel.

I did get some build warnings, don't know if those are related to building without modules:
```
# make -j4
...
  AR      init/built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.o' being placed in section `.eh_frame'
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.o' being placed in section `.eh_frame'
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.o' being placed in section `.eh_frame'
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.o' being placed in section `.eh_frame'
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.o' being placed in section `.eh_frame'
ld: warning: orphan section `.eh_frame' from `fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.o' being placed in section `.eh_frame'
  SORTTAB vmlinux
...
```

Seems to boot ok:
`[    0.281301] ZFS: Loaded module v2.0.5-r0-gentoo, ZFS pool version 5000, ZFS filesystem version 5`

And the pool is visible:
```
# zpool status
  pool: pool1
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: resilvered 2.06T in 04:51:52 with 0 errors on Fri Sep  3 19:52:36 2021
config:

	NAME                                                STATE     READ WRITE CKSUM
	pool1                                               ONLINE       0     0     0
	  mirror-0                                          ONLINE       0     0     0
	    ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N0988278-part1  ONLINE       0     0     0
	    ata-WDC_WD60EFZX-68B3FN0_WD-C80RNLAG-part1      ONLINE       0     0     0
```

I will hold off upgrading the pool until things seem stable, and I will comment again here if any problems arise.

**Comment by beeselmane** [comment]
Hello, I was wondering if there was any update on this issue? I'm currently getting the same issue on an up to date Gentoo system with kernel version `5.10.76` with `CONFIG_MODULES=n` when installing ZFS-2.2.1 from portage. The workaround posted above seems to be working for me, I temporarily enabled modules to get the sources to copy to the kernel source tree, and the kernel build completed without issue, but it seems autoconf shouldn't require `CONFIG_MODULES` when run with the `--enable-linux-builtin` option.

**Comment by szubersk** [comment]
The problem here is that while logically, from user perspective, OpenZFS should not require `CONFIG_MODULES` to be enabled with `--enable-linux-builtin`, all autoconf checks are attempts to compile a stub Linux module to test certain Linux source code and configuration capabilities.

If you guys see a way out of this (maintaining autoconf check capabilities and not having to compile stub modules) we are all eyes.

**Comment by szubersk** [comment]
@nihil-2019 @beeselmane @arvidbrodin please apply #13361 to see if it helps your cause.
