### ISSUE TITLE
Change main branch name and document branching structure

### ISSUE THREAD

**Issue by Ornias1993** [openzfs/zfs#10849]
### Describe the feature would like to see added to OpenZFS

- Rename the main branch to "dev" for active development
- Create a new release branch "release" for latest release (instead of zfs-2.0-release or zfs-2.0-staging)
- Document the branching structure in the contribution guidelines and other places

### Why this change?
Currently OpenZFS uses the master branch for general development and does a lot of backporting to previous versions using either PR's or (since a short while) staging branches.
Having a master branch for active development might not be the cleanest solution with semantic verioning and/or automation. Also: some of the leadership has voiced the wish to get rid of "master" and "slave" definitions where possible. (Hint: @ahrens )

Hence I would suggest the following new branching structure:
- release (contains the latest released code)
- dev (contains any new pushes, set as "main branch" for the repo)
- zfs-*-staging (where * is Major.Minor version version, containing code before creating a backport release. Example: 0.8-staging)
- zfs-*-release (where * is the Major.Minor version , containing code before creating a backport release. Example: 0.8-release)

Optional:
- staging (in case we want/need to exclude certain commits for a release to the release branch. Could be created if the need arises)

### How will this feature improve OpenZFS?

The above structure gives a lot more freedom than the previous one and leave a lot more options to automate things in the future. For example: Given this structure we could start looking into automated releases based when content is pushed to a release branch.

### Additional context

- Why use a "release" branch for latest version, instead of the zfs-*-release structure?

To be compatible with automatic (semantic) versioning, it would be easier to just branch off old versions from a general release branch on creation of a new minor or major release.

- Why set "dev" as the main repo branch?

If we set "dev" as main repo branch we can still merge changes to github behavoir without pushing to a release branch. If we ever would introduce automatic versioning, that is one less headache to deal with.

- Why talk so much about automation?

Besides this feature request, i'm also looking into changelogging (#10756) and moving to semantic versioning (#10334). Both of which have great solutions for automation, but besides versioning the current branching isn't ideal for it. Considering the above listed changes are relatively minor, I think it's worthwhile executing those (or at least actively considering them) before working on more of the changelogging, versioning and automation changes.

**Comment by IvanVolosyuk** [comment]
I wonder what is the expected behavior for 'release' branch when branching zfs-3.0-release after zfs-2.0-release? I would imagine it will be force-pushed from 'dev' branch when branching? Or alternatively, you will merge old 'release' with current 'dev' using 'git commit-tree' using latest 'dev' tree to keep continuity?

**Comment by Ornias1993** [comment]
Release would be latest minor release (0.x.0), major releases are als a new minor release (reset to 0). So nothing special. 
The zfs-x.y-release branches are for backports. So on creation of a new minor we would create a new release z.y branch (either manually or automatically, preferably automated).

Releases get stages in staging and PR’ed into release branches in one go. (I think this would need some more description?).

**Comment by Ornias1993** [comment]
By now the branching and releases have been improved significantly already, i'm not sure if this is still precisely the way we want to go, hence closing.
