### ISSUE TITLE
Add OpenZFS discuss mailinglist

### ISSUE THREAD

**Issue by Ornias1993** [openzfs/zfs#10845]
### Describe the feature would like to see added to OpenZFS

I would like to see a multiplatform support/discussion mailinglist, like we have "zfs-discuss" for ZoL.
More specific:
discuss@open-zfs.org

### How will this feature improve OpenZFS?

The current list of mailinglists lists the following options:
developer@open-zfs.org
zfs-devel@list.zfsonlinux.org
zfs-discuss@list.zfsonlinux.org
freebsd-fs@freebsd.org

Where zfs-discuss is basically supposed to be a mailinglist for the community to discuss, brainstorm and support eachother ("Community Support").

However:
OpenZFS is currently mostly multiplatform, as is this github, and it would be nice if we can point people needing help to a mailinglist that reflects the actual factual code repository.

It just feels so off that there is no zfs-discuss equivalent that is open to BSD users, besides a general FreeBSD filesystem mailinglist that isn't even centered around ZFS.

Adding a clear and simple multi-platform "discuss" equivalent under the openzfs brandname, is a simple solution which we can also use to directly point users towards using a method as proposed in #10833

### Additional context

To be clear:
This is not a request to add an OpenZFS Discuss url to the documentation (like someone tried to do in openzfs/openzfs-docs#51), this is a request for (I guess) @behlendorf or @ahrens (whoever maintains the mailinglists) to add an actual mailinglist.

**Comment by Ornias1993** [comment]
To be clear:
This is not a request to add an OpenZFS Discuss url to the documentation (like someone tried to do in https://github.com/openzfs/openzfs-docs/pull/51), this is a request for (I guess) @behlendorf or @matt (whoever maintains the mailinglists) to add an actual mailinglist.

**Comment by Rudd-O** [comment]
Looks like we need an issue label `Type: Process`.

**Comment by mschilli87** [comment]
@Ornias1993: Are you sure you didn't intend to ping Matthiew Ahrens (@ahrens) instead of Matthew Mohrman? :wink:

**Comment by Ornias1993** [comment]
SHOOT. Yes.

**Comment by Ornias1993** [comment]
> Looks like we need an issue label `Type: Process`.

That isn't such a bad idea, but might be needless because most `Type: Process` have a big overlap with `Type: Documentation` which leads to a scenario where just about every `Type: Process` would need to also be tagged with `Type: Documentation` (See #10853)

**Comment by Ornias1993** [comment]
I don't think this is the right place to endlessly keep this documented. The wiki would be a beter place in due time, if people still want these changes.
