### ISSUE TITLE
Race in Dracut pre-mount

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs#10854]
```
 0m23.46  TT:      VM.console:                             run@ 310	[    1.844579] dracut-pre-mount[322]: The ZFS modules are not loaded.
 0m23.46  TT:      VM.console:                             run@ 310	[    1.845640] dracut-pre-mount[322]: Try running '/sbin/modprobe zfs' as root to load them.
 0m23.59  TT:      VM.console:                             run@ 310	[    1.977539] dracut-pre-mount[329]: The ZFS modules are not loaded.
 0m23.59  TT:      VM.console:                             run@ 310	[    1.978603] dracut-pre-mount[329]: Try running '/sbin/modprobe zfs' as root to load them.
```

Looks like it's coming from this file:

```
[user@ring2-projects dracut]$ cat 90zfs/zfs-load-key.sh.in
#!/bin/bash

# only run this on systemd systems, we handle the decrypt in mount-zfs.sh in the mount hook otherwise
[ -e /bin/systemctl ] || return 0

# This script only gets executed on systemd systems, see mount-zfs.sh for non-systemd systems

# import the libs now that we know the pool imported
[ -f /lib/dracut-lib.sh ] && dracutlib=/lib/dracut-lib.sh
[ -f /usr/lib/dracut/modules.d/99base/dracut-lib.sh ] && dracutlib=/usr/lib/dracut/modules.d/99base/dracut-lib.sh
# shellcheck source=./lib-zfs.sh.in
. "$dracutlib"

# load the kernel command line vars
[ -z "$root" ] && root="$(getarg root=)"
# If root is not ZFS= or zfs: or rootfstype is not zfs then we are not supposed to handle it.
[ "${root##zfs:}" = "${root}" ] && [ "${root##ZFS=}" = "${root}" ] && [ "$rootfstype" != "zfs" ] && exit 0

# There is a race between the zpool import and the pre-mount hooks, so we wait for a pool to be imported
while true; do
    zpool list -H | grep -q -v '^$' && break
    [ "$(systemctl is-failed zfs-import-cache.service)" = 'failed' ] && exit 1
    [ "$(systemctl is-failed zfs-import-scan.service)" = 'failed' ] && exit 1
    sleep 0.1s
done

# run this after import as zfs-import-cache/scan service is confirmed good
# we do not overwrite the ${root} variable, but create a new one, BOOTFS, to hold the dataset
if [ "${root}" = "zfs:AUTO" ] ; then
    BOOTFS="$(zpool list -H -o bootfs | awk '$1 != "-" {print; exit}')"
else
    BOOTFS="${root##zfs:}"
    BOOTFS="${BOOTFS##ZFS=}"
fi

# if pool encryption is active and the zfs command understands '-o encryption'
if [ "$(zpool list -H -o feature@encryption $(echo "${BOOTFS}" | awk -F\/ '{print $1}'))" = 'active' ]; then
    # if the root dataset has encryption enabled
    ENCRYPTIONROOT=$(zfs get -H -o value encryptionroot "${BOOTFS}")
    # where the key is stored (in a file or loaded via prompt)
    KEYLOCATION=$(zfs get -H -o value keylocation "${ENCRYPTIONROOT}")
    if ! [ "${ENCRYPTIONROOT}" = "-" ]; then
        KEYSTATUS="$(zfs get -H -o value keystatus "${ENCRYPTIONROOT}")"
        # continue only if the key needs to be loaded
        [ "$KEYSTATUS" = "unavailable" ] || exit 0
        # if key is stored in a file, do not prompt
        if ! [ "${KEYLOCATION}" = "prompt" ]; then
            zfs load-key "${ENCRYPTIONROOT}"
        else
            # decrypt them
            TRY_COUNT=5
            while [ $TRY_COUNT -gt 0 ]; do
                systemd-ask-password "Encrypted ZFS password for ${BOOTFS}" --no-tty | zfs load-key "${ENCRYPTIONROOT}" && break
                TRY_COUNT=$((TRY_COUNT - 1))
            done
        fi
    fi
fi
```

There is no way that works because the module is not loaded at this point in time.  It looks like the pre-mount hook in Dracut is actually running before the module is loaded, which makes sense because the module is loaded here (which runs later, obviously, because the mount hook runs after the pre-mount hook, and they are strictly-ordered):

```
[user@ring2-projects zfs]$ grep -r modprobe contrib/dracut/
contrib/dracut/90zfs/mount-zfs.sh.in:modprobe zfs 2>/dev/null
```

This should probably be fixed by loading the module earlier, during the pre-mount sequence, before loading the keys.  I note that there are no systemd unit files installed in the initial RAM disk that import the module -- I reckon that would be a better fix.

Easy reproducer: run https://github.com/Rudd-O/zfs-fedora-installer/ with Fedora 32 as `--releasever` on a system that has Fedora and ZFS already.  You should be able to see this scroll on your terminal as the test boot happens (near the end).

Clarification: the system as built by the reproducer code *does boot*, but that system of course does not use any ZFS key that would otherwise be necessary to boot it (it at most supports cryptsetup LUKS for the underlying backing devices of the pool), therefore, due to this bug, it is strongly unlikely that anyone wanting to use a ZFS key at boot time will succeed.  Patches are welcome to extend the reproducer code to support ZFS root pool encryption keys, so that automated testing of these corner cases can be done.

**Comment by Rudd-O** [comment]
@rlaager

**Comment by Rudd-O** [comment]
FYI I regularly run the reproducer on my build farm as a sanity check before I upgrade my systems to new ZFS.  It really should be run by the buildbot.  I recently made a fix that allows it to work with SELinux in enforcing mode.

**Comment by Rudd-O** [comment]
BTW, I can only run the reproducer code in EC2 using one of the metal instances, because it requires KVM support to run in a reasonable amount of time (it will run in a normal EC2 instance but it will take ten times as long).

`eu-west-1 ami-0ce2a6144475cf269 i3.metal`

**Comment by rlaager** [comment]
> @rlaager

I don't know anything about Dracut. I use Debian derivatives with initramfs.

**Comment by Rudd-O** [comment]
I can't repro this anymore.
