### ISSUE TITLE
Fedora 32 updated to kernel 5.8.4-200.fc32.x86_64 dkms build errors: too many arguments to function ‘__vmalloc’

### ISSUE THREAD

**Issue by plevart** [openzfs/zfs#10862]
Hi, recently the Fedora 32 updates shipped new kernel version 5.8.4 and the DKMS build procedure for zfs 0.8.4 fails with the following errors:

  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_mac.o
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c: In function ‘spl_kmem_alloc_impl’:
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:183:11: error: too many arguments to function ‘__vmalloc’
  183 |     ptr = __vmalloc(size, lflags | __GFP_HIGHMEM,
      |           ^~~~~~~~~
In file included from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vmem.h:30,
                 from /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:28:
./include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~
make[5]: *** [scripts/Makefile.build:281: /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.o] Error 1
make[5]: *** Waiting for unfinished jobs....

...

  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/nvpair_alloc_fixed.o
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c: In function ‘kv_alloc’:
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c:206:9: error: too many arguments to function ‘__vmalloc’
  206 |   ptr = __vmalloc(size, lflags | __GFP_HIGHMEM, PAGE_KERNEL);
      |         ^~~~~~~~~
In file included from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vmem.h:30,
                 from /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c:30:
./include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~

...

  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zcommon/zfs_fletcher_sse.o
/var/lib/dkms/zfs/0.8.4/build/module/lua/ldo.o: warning: objtool: f_parser()+0xf7: unreachable instruction

...

  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/dmu_send.o
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/modes/aesni-gcm-x86_64.o
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/dmu_traverse.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/dmu_tx.o
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/modes/ghash-x86_64.o

...

  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/zfs_rlock.o
/var/lib/dkms/zfs/0.8.4/build/module/zfs/zcp.o: warning: objtool: zcp_parse_args()+0x1f9: unreachable instruction

**Comment by plevart** [comment]
I see this has already been fixed in https://github.com/openzfs/zfs/pull/10422
Are there any plans for updated DKMS packages for Fedora 32 ?

**Comment by mskarbek** [comment]
@plevart: https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html
You will have to rever to 5.7.x and just wait. There is no specific date and OpenZFS does not follow the kernel release schedule to sync with it (unfortunately).
