### ISSUE TITLE
Zpool and >2TB disks

### ISSUE THREAD

**Issue by RicardoLorenzo** [openzfs/zfs#1087]
We currently use SPL/ZFS 0.6.0-rc10 and Linux 3.0. If i make a pool with a LUN of 16TB for example:

  # zpool create Pool1 /dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df
  # zpool list
  NAME    SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
  Pool1  1,98T  77,5K  1,98T     0%  1.00x  ONLINE

zpool command automatically create a partition with 2TB GPT limit. In the other hand zfs-fuse create a pool with complete disk, and this kind of pools can be imported using zfsonlinux without any problem.

if i try the following:

  # dd if=/dev/zero of=/dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df bs=1M count=1
  1+0 records in
  1+0 records out
  1048576 bytes (1,0 MB) copied, 0,00256356 s, 409 MB/s
  # parted /dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df --script -- mklabel gpt
  # parted /dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df --script -- mkpart primary 0 -1
  Aviso: The resulting partition is not properly aligned for best performance.
  # parted /dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df --script -- print
  Model: XXXXX (scsi)
  Disk /dev/sdb: 16,9TB
  Sector size (logical/physical): 512B/512B
  Partition Table: gpt

  Numero  Inicio  Fin     Tamaño  Sistema de ficheros  Nombre   Banderas
   1      17,4kB  16,9TB  16,9TB                       primary
  # zpool create Pool1 /dev/disk/by-id/scsi-36848f690e4e265001834dba3080869df-part1
  # zpool list
  NAME    SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
  Pool1  15,2T   109K  15,2T     0%  1.00x  ONLINE  -

Everything is fine, but when i reboot the machine, pool cannot be imported

  # zpool status
    pool: Pool1
   state: UNAVAIL
  status: One or more devices could not be used because the label is missing 
    or invalid.  There are insufficient replicas for the pool to continue
    functioning.
  action: Destroy and re-create the pool from
    a backup source.
     see: http://zfsonlinux.org/msg/ZFS-8000-5E
   scan: none requested
  config:

```
NAME                                            STATE     READ WRITE CKSUM
Pool1                                           UNAVAIL      0     0     0  insufficient replicas
  scsi-36848f690e4e265001834dba3080869df-part1  UNAVAIL      0     0     0  corrupted data
```

How can i make pools using zpool with a LUN >2TB without using zfs-fuse?

**Comment by lihui2090** [comment]
@RicardoLorenzo 
I  meet this question too ,  SCSI controller module on Linux kernel, how can i change scsi to meet zfs.ths.
