### ISSUE TITLE
dracut always generates little-endian /etc/hostid

### ISSUE THREAD

**Issue by gyakovlev** [openzfs/zfs#10887]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| rolling
Linux Kernel	| 5.4.62
Architecture	| ppc64 (big endian)
ZFS Version	| 0.8.4-2.0.0-rc1

### Describe the problem you're observing
Code in dracut that copies hostid to initramfs during assembly always assumes little-endian mode.
https://github.com/openzfs/zfs/blob/cd80273909184426d5f38050c3163de43031098f/contrib/dracut/90zfs/module-setup.sh.in#L85-L90

bug glibc expects `/etc/hostid` to be written in native-endian, so big.
after boot `zpool status` will list a warning which says that hosit of the pool and the system do not match.
after observing hostid with zdb its clearly seen it's byteswapped to little-endian.

there is another piece of code which generates hostid before importing the pool.
https://github.com/openzfs/zfs/blob/cd80273909184426d5f38050c3163de43031098f/contrib/dracut/90zfs/parse-zfs.sh.in#L6-L19

it's possible to enchance `module-setup.sh` to generate proper one, this code works.
```bash
	# Synchronize initramfs and system hostid
	AA=`hostid | cut -b 1,2`
	BB=`hostid | cut -b 3,4`
	CC=`hostid | cut -b 5,6`
	DD=`hostid | cut -b 7,8`

	# this returns 1 for little-endian and \0\0256 for big-endian
	case $(printf '\1' | od -dAn) in
		*256)
			echo -ne "\\x${AA}\\x${BB}\\x${CC}\\x${DD}" > "${initdir}/etc/hostid"
			;;
		*)
			echo -ne "\\x${DD}\\x${CC}\\x${BB}\\x${AA}" > "${initdir}/etc/hostid"
			;;
	esac
```

but the `parse-zfs.sh` code runs inside initrd on boot and not sure it's ok to require coreutils's `od` binary inside initrd to detect endianess. Maybe there are better ways 

I can open a PR to fix this after I come up with acceptable solution, but any thoughts are welcome.

### Describe how to reproduce the problem
generate initrd on big-endian system and reboot.
warning about mismatching hostid is printed in `zpool status`, pool refuses to import without `zfs_force=1` and/or `spl.spl_hostid=0x.....` passed.

**Comment by behlendorf** [comment]
Another option would be `lscpu` but unfortunately neither it or `od` are included in the default initramfs images I checked.  Adding either of them is an option, it would just slightly increase the image size.  The most efficient thing I can think of would be to convert the `zgenhostid` script to a small C program and then use that. It looks it also assumes little-endian so we'd want to fix that.
