### ISSUE TITLE
BUG: kernel NULL pointer dereference

### ISSUE THREAD

**Issue by KosmiK2001** [openzfs/zfs#10895]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| Current
Linux Kernel	| 5.4.60
Architecture	| x86_64
ZFS Version	| v2.0.0-rc1_46_g75bf636cd
SPL Version	| v2.0.0-rc1_46_g75bf636cd

### Describe the problem you're observing
https://pastebin.com/bC0SdW1a

### Describe how to reproduce the problem
Ok. Pool storage-2TB.
storage-2TB/VM/windows7_x64_solidworks  72,3G  1004G     27,5G  -
Qemu: windows7_x64.
O&O Defrag: full optimization+ Wipe free space.
But, on shutdown windows7 i got "NULL pointer dereference" in dmesq.

### Include any warning/errors/backtraces from the system logs

zfs get all storage-2TB/VM/windows7_x64_solidworks
https://pastebin.com/eY9sihWx

**Comment by IvanVolosyuk** [comment]
Stack trace might be useful to understand what has happened.

**Comment by behlendorf** [comment]
Thanks for posting the back traces.  I took a look at the console logs and from what I can tell this doesn't appear to have been an issue with ZFS.  The panic came from `io_ring_submit()` which was manipulating a corrupt list above the ZFS layers.  In fact, I don't see anything ZFS related in the stacks.  This may be a kernel bug.

**Comment by KosmiK2001** [comment]
> Thanks for posting the back traces. I took a look at the console logs and from what I can tell this doesn't appear to have been an issue with ZFS. The panic came from `io_ring_submit()` which was manipulating a corrupt list above the ZFS layers. In fact, I don't see anything ZFS related in the stacks. This may be a kernel bug.

Good evening.
You are completely correct. Today I repeated all the steps with the virtual machine, but the virtual disk did
 with qemu-img. I put the file in an ext4 based storage.
And got the same problem again.
So it's a false alarm.

**Comment by behlendorf** [comment]
@KosmiK2001 thanks for confirming that's really the case.  Given it's not an OpenZFS issue I'm going to close this issue.
