### ISSUE TITLE
No rule to make target cityhash.c with --enable-debug

### ISSUE THREAD

**Issue by tonyhutter** [openzfs/zfs#10907]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 33
Linux Kernel	| 5.8.7-300.fc33.x86_64
Architecture	| x86-64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
`./autogen.sh && ./configure --enable-debug && make` fails on Fedora 33.  It builds correctly if you omit the `--enable-debug`.

### Describe how to reproduce the problem
`./autogen.sh && ./configure --enable-debug && make`  on F33.

### Include any warning/errors/backtraces from the system logs
```
make[3]: Entering directory '/home/fedora/zfs/lib/libzpool'
  CC       kernel.lo
  CC       taskq.lo
  CC       util.lo
  CC       zfeature_common.lo
  CC       zfs_comutil.lo
...
  CC       btree.lo
make[3]: *** No rule to make target '../../module/zfs/cityhash.c', needed by 'cityhash.lo'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC       bqueue.lo
make[3]: Leaving directory '/home/fedora/zfs/lib/libzpool'
make[2]: *** [Makefile:668: all-recursive] Error 1
make[2]: Leaving directory '/home/fedora/zfs/lib'
make[1]: *** [Makefile:881: all-recursive] Error 1
make[1]: Leaving directory '/home/fedora/zfs'
make: *** [Makefile:742: all] Error 2
```

**Comment by tonyhutter** [comment]
Closing issue - I did a `make distclean` and the issue went away.  I had previously checked out another branch before checking out master and attempting to build it, so maybe there were some remnant files left over that interferred with the build.

**Comment by dreamcat4** [comment]
Encountered this same error today. Trying to build the 2.0 release. Not with the same configure arguments, instead `./configure --with-config=use`

Did a `make distclean`. Then tried again (from the beginning, from `autogen.sh`). And it compiled. Not sure why this happen. But thanks for the tip here. It saved a lot of time.

**Comment by hergenroder** [comment]
Experienced same error after updating an existing fork. Several files had been relocated and "make clean" did not prevent Autotools from generating Plo files with bad paths. Manually changing the paths led to a successful build but a fresh "git clone" resolved the issue.
