### ISSUE TITLE
gpg key import problem

### ISSUE THREAD

**Issue by ondrejtichacek** [openzfs/zfs#10909]
I tried to import gpg keys according to [openzfs documentation](https://openzfs.github.io/openzfs-docs/Project%20and%20Community/Signing%20Keys.html) i.e. using
```
gpg --keyserver pgp.mit.edu --recv D4598027
```
The operation takes very long and exits with
```
gpg: keyserver receive failed: No keyserver available
```

Viewing the key details through the web interface is also extremely slow, signifying some problem with the server.

I hope this is the correct channel to report this issue, if not, I apologize.
Thank you.

**Comment by AfroThundr3007730** [comment]
Late to the party, but that seems like an issue with the MIT keyserver, not anything to do with the project. You can try a different keyserver, whenever that happens, as they're synchronized:
```
gpg --keyserver keyserver.ubuntu.com --recv D4598027
```
