### ISSUE TITLE
arcstat l2_misses can be very incorrect

### ISSUE THREAD

**Issue by adamdmoss** [openzfs/zfs#10913]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 18.04.05
Linux Kernel	| Linux version 5.4.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
Architecture	| x86_64
ZFS Version	| git zfs-2.0-release @ 29bc31f62f3021e703513b269d5fa629063df1da
SPL Version	| git zfs-2.0-release @ 29bc31f62f3021e703513b269d5fa629063df1da

### Describe the problem you're observing

I was wondering why my L2 hit ratio always seemed so low, so finally decided to look into it...

The way that arc_read() currently accounts L2 hits/misses, if ANY pool has an l2arc then ALL reads that don't hit an l2arc are considered to be a miss, even if the read is from a pool that doesn't have an l2arc configured.

edit: The same over-eager miss accounting appears to also happen for reads from datasets which have secondarycache=none but whose pools have l2arc; this shouldn't count as a miss.

### Describe how to reproduce the problem

Set up two pools on the same system, one backed by an l2arc and one not.  Read data from the pool which doesn't have an l2arc; these reads cause l2_misses to rise (i.e. in /proc/spl/kstat/zfs/arcstats)

### Include any warning/errors/backtraces from the system logs
n/a

**Comment by adamdmoss** [comment]
Pinging @gamanakis just 'cos they're an L2ARC expert at this point. :)

**Comment by Ornias1993** [comment]
ZFS version should be:
2.0.0 RC1 (just to be clear this isn't release, in the future)

**Comment by adamdmoss** [comment]
> ZFS version should be:
> 2.0.0 RC1 (just to be clear this isn't release, in the future)

It's the name of the upstream branch I was using - I'm not making any claims about its naming accuracy. :)

**Comment by Ornias1993** [comment]
@adamdmoss Please just use the VERSION you are using... To keep things consistent, which is:  2.0.0 RC1

**Comment by adamdmoss** [comment]
I gave the commit id - 29bc31f

**Comment by Ornias1993** [comment]
> I gave the commit id - [29bc31f](https://github.com/openzfs/zfs/commit/29bc31f62f3021e703513b269d5fa629063df1da)

It asks for a version, not a branch and commit.
People might want to help you in 4 weeks and notice "release" without noticing your commit link. Thats why versions are asked, not commit references. Doing something else than just giving the version (such as a branch and commit) when there is a valid version in the release tree leads to needless errors.
As I said before: it asks for versions for a reason. Branches and commit might be fine, but if there is a version, please use a version. Thats all i'm going to say about it.
