### ISSUE TITLE
zfs send stream from 0.8.4 can't be read by ZoL < 0.7

### ISSUE THREAD

**Issue by PaulZ-98** [openzfs/zfs#10911]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 16.04
Linux Kernel	| 4.15
Architecture	| amd64
ZFS Version	| 0.8.4
SPL Version	|

### Describe the problem you're observing
zfs send stream from 0.8.4 can't be read by ZoL < 0.7
### Describe how to reproduce the problem
Direct a full send stream to a file with 0.8.4.
Place file on system running zfs 0.6.5.9
zfs recv -F dataset < sendfile
recv hangs
### Include any warning/errors/backtraces from the system logs
```
zstreamdump -v
...
FREEOBJECTS firstobj = 37 numobjs = 18446744073709551578
...
```
The large numobjs is not handled by ZoL < 0.7 and loops forever processing free objects.

There is code near the top of the dump_freeobjects function to head off this problem by limiting numobjs.  But as part of redacted send, the code
```
if (numobjs == 0)
		numobjs = UINT64_MAX - firstobj;
```
was added.  It has the effect of reinstating the large number "numobjs" which was limited earlier in the function.

How necessary is it to have numobjs be UINT64_MAX - firstobj?

**Comment by PaulZ-98** [comment]
Tagging @pcd1193182

**Comment by pcd1193182** [comment]
I think we can either just ASSERT that numobjs isn't zero on entry to the function, or do the numobjs = uint64_max - firstobj before we cap the value. I'll test those options and post a PR.
