### ISSUE TITLE
Hibernation not working if system memory including ARC is above 50%

### ISSUE THREAD

**Issue by tobiaspc** [openzfs/zfs#10924]
### System information

Type | Laptop
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| up to date
Linux Kernel	| 5.8.8
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1
Memory Size   | 32 GB
Swap Partition | 32 GB

### Describe the problem you're observing
This machine runs Arch Linux with ZFS on root using the ArchZFS repo. 
Hibernation fails if the total used system memory is more than 50% at the time of hibernating. 
After the hibernation fails, system memory is usually below 20% and a repeated hibernation works.

### Describe how to reproduce the problem

Working case
- Boot system
- Check memory usage, should be very low
- Hibernate system 
- Success

Failing case:
- Boot system
- Fill up the ARC by using the system for a few hours
- Easy way: `find . ! -empty -type f -exec md5sum {} +`
- ARC is then at the maximum configured size, about 15GB at my machine with 32 GB of memory.
- Total memory usage is slightly above that
- Hibernate system
- Hibernation fails with the following message:
`PM: hibernation: Image allocation is 1109922 pages short`

Workaround: Drop caches before hibernation:
- `sync`
- `echo 3 > /proc/sys/vm/drop_caches`
- `sleep 5`
- hibernate

Interestingly, the caches are dropped during the hibernation process nevertheless. Therefore, a repeated attempt to hibernate did work every time so far.

The root cause for this problem seems to be that the kernel needs at least 50% free memory to hibernate, explained in section XI of this article:
https://lwn.net/Articles/243404/

If the kernel was able to just dump the whole memory directly to disk it would be possible to stop dropping the cache during hibernation at all, in case the swap is empty at that time. 

Since this is not the case, the kernel drops the cache, including the ARC. However, the ARC seems to be dropped "too late" in the process, therefore, preventing hibernation in case memory is above 50%.

I wrote a systemd unit that hooks into the hibernate.target with the following content:

```
[Unit]
Description=Local system hibernate actions
Before=hibernate.target

[Service]
Type=oneshot
ExecStart=/usr/bin/echo 3 > /proc/sys/vm/drop_caches
ExecStart=/usr/bin/sleep 5

[Install]
WantedBy=hibernate.target
```

This seems to work so far, however, this can not be the optimal solution, since users expect hibernation to work out of the box, without any manual configuration.

### Include any warning/errors/backtraces from the system logs

```
Sep 03 19:39:39 hostname systemd[1]: Created slice system-suspend.slice.
Sep 03 19:39:39 hostname systemd[1]: Started Local system suspend actions.
Sep 03 19:39:40 hostname systemd[1]: Reached target Sleep.
Sep 03 19:39:40 hostname systemd[1]: Starting Hibernate...
Sep 03 19:39:40 hostname systemd-sleep[1032838]: Suspending system...
Sep 03 19:39:40 hostname kernel: PM: hibernation: hibernation entry
Sep 03 19:39:40 hostname kernel: bbswitch: enabling discrete graphics
Sep 03 19:39:52 hostname kernel: Filesystems sync: 0.044 seconds
Sep 03 19:39:52 hostname kernel: Freezing user space processes ... (elapsed 0.003 seconds) done.
Sep 03 19:39:52 hostname kernel: OOM killer disabled.
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0x00000000-0x00000fff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0x00058000-0x00058fff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0x0009d000-0x000fffff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0x9f42e000-0x9f42ffff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0xa2ab2000-0xa2bb1fff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0xa8d71000-0xab5fefff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Marking nosave pages: [mem 0xab600000-0xffffffff]
Sep 03 19:39:52 hostname kernel: PM: hibernation: Basic memory bitmaps created
Sep 03 19:39:52 hostname kernel: PM: hibernation: Preallocating image memory
Sep 03 19:39:52 hostname kernel: PM: hibernation: Image allocation is 153575 pages short
Sep 03 19:39:52 hostname kernel: acpi LNXPOWER:05: Turning OFF
Sep 03 19:39:52 hostname kernel: acpi LNXPOWER:04: Turning OFF
Sep 03 19:39:52 hostname kernel: PM: hibernation: Basic memory bitmaps freed
Sep 03 19:39:52 hostname kernel: OOM killer enabled.
Sep 03 19:39:52 hostname kernel: Restarting tasks ... done.
Sep 03 19:39:52 hostname kernel: bbswitch: disabling discrete graphics
```

**Comment by gdevenyi** [comment]
I don't believe hibernation is supported at all so that fact that it works under some conditions is considered "luck"

**Comment by tobiaspc** [comment]
Well, that is good to know, now that I converted to system to ZFS only. Is there a source for this statement? 
Apart from that, after a few weeks of using ZFS on root with multiple hibernation / resume cycles each day, I can say, at least for me, it works as expected with the fix above.

**Comment by adamdmoss** [comment]
I've never had a problem with hibernation, though my root isn't on ZFS if that's a factor (I doubt it)

**Comment by gdevenyi** [comment]
https://github.com/openzfs/zfs/issues/260

**Comment by tobiaspc** [comment]
Merci!

**Comment by runderwo** [comment]
This is still a problem, and still requires the same workaround.
