### ISSUE TITLE
ZFS and ZZSTD: Memory is not cleared (held) when the pool is exported.

### ISSUE THREAD

**Issue by KosmiK2001** [openzfs/zfs#10938]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| Current (stable)
Linux Kernel	| 5.7.19
Architecture	| x86_64
ZFS Version	|  2.0.0-rc1_58_g085321621
SPL Version	| 2.0.0-rc1_58_g085321621

### Describe the problem you're observing
Good evening. It looks like I caught a situation in which zfs and zzstd modules do not return RAM back: after a forced reset of caches, after exporting a pool.
### Describe how to reproduce the problem
It is quite easy to reproduce the situation (perhaps).
It is enough to use a virtual machine with a zvol disk, which uses zstd compression.
Below I attach links to archives: the first archive - step-by-step actions with a copy of /proc/ spl with an attached memory file, which indicates the current consumption of RAM; the second archive contains properties and parameters of the pool, its date of sets and three zvol disks.
Only one way to free using (locked by zfs) memory: rmmod zfs zzstd
Hopefully this helps to identify, or at least give a hint where to look for the problem.
Also, modprobe for zfs:
options zfs zfs_arc_max=27917287424 zfs_arc_min=67108864 l2arc_noprefetch=0 l2arc_write_max=67108864 l2arc_write_boost=67108864 l2arc_norw=1 zio_dva_throttle_enabled=0 zfs_vdev_cache_size=1048576 zfs_vdev_cache_max=16384 zfs_vdev_cache_bshift=13 zfs_prefetch_disable=0 zfetch_max_distance=4194304 zfs_vdev_async_read_max_active=128 zfs_vdev_scrub_min_active=8 zfs_vdev_scrub_max_active=32 zfs_max_recordsize=16777216
### Include any warning/errors/backtraces from the system logs

ZFS - memory leak.tar.gz
https://drive.google.com/file/d/1p3sOT5i9UGlCk1qEGBB4anXswXireQC_/view?usp=sharing

STORAGE-2TB.tar.gz
https://drive.google.com/file/d/1j638Y6fu1yMJVXkk5ty7PWyyoAzipuzL/view?usp=sharing

I also noticed that memory is freed if data is read from datasets. It looks like only zvol-disks are affected.
But this is not accurate, since I have not yet figured out how to check datasets for memory leaks.
**Also this memory cannot be released by "stress -t 35 -c 4 -m 1 --vm-bytes 45G".**

**Comment by Ornias1993** [comment]
@KosmiK2001 Could you explain what the problem is in a TLDR?
Some sort of memory leak, but it would be nice to actually explain what the leak is in the PR instead of pointing to two archieves, we don't all have the time for a deepdive.

Your files do not actually include steps to reproduce it seems, just a lot of debug data.
So to be clear: is it a memory leak (endlessly expanding memory consumption) or just memory not being freed (endlessly reserved memory with a fixed size)?

@BrainSlayer and @c0d3z3r0 You two might want to have a look at this one though.

**Comment by KosmiK2001** [comment]
> @KosmiK2001 Could you explain what the problem is in a TLDR?
> Some sort of memory leak, but it would be nice to actually explain what the leak is in the PR instead of pointing to two archieves, we don't all have the time for a deepdive. (How to trigger it, how much memory is leaking etc.)
> 
> Your files do not actually include steps to reproduce it seems, just a lot of debug data.
> So to be clear: is it a memory leak (endlessly expanding memory consumption) or just memory not being freed (endlessly reserved memory with a fixed size)?
> 
> @BrainSlayer and @c0d3z3r0 You two might want to have a look at this one though.

Indeed, perhaps I did not describe the problem correctly.
Yes, there is a fact that the zfs and zzstd modules retain RAM when clearing caches, and even after exporting the pool.
I'm not sure about the infinite expansion of the size of the held RAM. Perhaps the frames keep the consumption of about 50% of the RAM.

About the steps to repeat the problem.
It is enough to use zvol for the virtual machine. You can also use zstd compression.
In the second archive I have attached all the properties of the pool.
I noticed the problem on "storage-2TB/VM/Windows8_x64_AutoCad".
Perhaps the problem is repeated or found in other compressions and with different properties.

**Comment by Ornias1993** [comment]
@KosmiK2001 Its a good question, when exporting (and importing a non-zstd pool), ZFS-ZSTD allocator memory shouldn't be retained. Period. You are very right there.

Just for the record how much ram and cpu threads does your system have? ZFS-ZSTD allocates memory based on the amount of threads available afaik, so if you have 16 threads and 12gb ram, that might indeed become somewhat of an issue

**Comment by KosmiK2001** [comment]
> @KosmiK2001 Its a good question, when exporting (and importing a non-zstd pool), ZFS-ZSTD allocator memory shouldn't be retained. Period. You are very right there.
> 
> Just for the record how much ram and cpu threads does your system have? ZFS-ZSTD allocates memory based on the amount of threads available afaik, so if you have 16 threads and 12gb ram, that might indeed become somewhat of an issue

Supermicro X9DRH-7TF/7F/iTF/iF/X9DRH-7TF/7F/iTF/iF
Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (dual)
32gb ram
options zfs zfs_arc_max=27917287424 zfs_arc_min=67108864

**Comment by BrainSlayer** [comment]
zstd uses a static memory pool and yes its static. which means it may keep memory but it will never go over its limit. with 4 cores the memory pool may contain a maximum of 32 preallocated objects. this is required for fast reusing, but it does also release objects if not in use for more than 2 minutes. and will only use as much as required, but never more than the top limit. of course you can bringt all to the extreme by setting a compression level of 19 which will result in a object size of about 70 mb per object. with standard level of 3 its about 2 mb. but from the allocator design it simply cannot leak. but objects may remain for later reuse. thats all

**Comment by Ornias1993** [comment]
I also do not see a memory leak here, just the allocator keeping a tight claim on its memory.
In general ZSTD memory is considered a priority, because all sorts of "funny" things might happen when it runs out of memory (although we accounted for most of them, it would have consequences, for example in terms of performance). So no, if ZSTD needs (for example) 2GB, it gets 2GB period. Only alternative is picking a lighter zstd level.

@KosmiK2001 For completeness:
If you export the pool and wait 15 minutes, does it still reserve memory for zstd? because THAT would be a bug.

**Comment by KosmiK2001** [comment]
> @KosmiK2001 For completeness:
> If you export the pool and wait 15 minutes, does it still reserve memory for zstd? because THAT would be a bug.

pool exported: **9.86gb**
cache_clear: **9.83gb**
after 30min (drop caches + stress -t 35 -c 4 -m 1 --vm-bytes 37G): **9.29gb**
rmmod zfs: **3.57gb**
rmmod zzstd:**2.05gb**

**Comment by Ornias1993** [comment]
@BrainSlayer any thoughts?

**Comment by BrainSlayer** [comment]
> @BrainSlayer any thoughts?

i see nothing which proofs that this is related to zstd. zstd polls only for release of memory per compression action. so if you use the full memory pool and then all read/write access stops. the memory will remain allocated. now start a single file access 2 minutes later and you will see the ram dropping. as i said. i do not run something like a background thread which constantly checks for freeing memory. it checks only if something can be released at allocation time of a slot. a typical usecase. so using a volume in a regular way this isnt a problem. this here this  is a synthetic usecase. just exporting. then forget about it and check memory. but this is no usecase. if nothing accesses the volume, the allocator will not check if a pooled memory slot can be released. with regular volume usage the memory will dynamicly freed and allocated as required. or not if you run stress tests and stop immediatly using the volume. the rule for releasing a slot is, if a memory object is not in use for more then 2 minutes.

**Comment by Ornias1993** [comment]
@BrainSlayer I didn't fully understand your previous comment, now I do. Thanks.
I agree it's a very rare occurance and shouldn't be called a "usecase", that being said: I also agree with the reporter of this issue that this memory should preferably be cleared on export in the future.

@KosmiK2001 You might want to adapt your Issue and your title.
Something like:
"ZZSTD memorypool not cleared on export"

**Comment by BrainSlayer** [comment]
> @BrainSlayer I didn't fully understand your previous comment, now I do. Thanks.
> I agree it's a very rare occurance and shouldn't be called a "usecase", that being said: I also agree with the reporter of this issue that this memory should preferably be cleared on export in the future.
> 
> @KosmiK2001 You might want to adapt your Issue and your title.
> Something like:
> "ZZSTD memorypool not cleared on export"

it cannot be cleared on export. its a algorithm. the algorithm doesnt know about higher level functions. introducing a timer which checks ever 3 minutes for remaining object is the only option. but i'm no big fan of extra cpu cycles which are only catching corner cases which will never happen if you use zfs as storage device

**Comment by BrainSlayer** [comment]
@KosmiK2001 if you have some time to play. check this code tree. its in sync with zfs master and contains a new patch which checks every minute if orphan memory objects can be released. its a small patch, but its also untested
https://github.com/brainslayer/zfs
https://github.com/BrainSlayer/zfs/commit/b4acf2bd393211aab119d18ce51fa62f811b8b68

**Comment by KosmiK2001** [comment]
> @KosmiK2001 if you have some time to play. check this code tree. its in sync with zfs master and contains a new patch which checks every minute if orphan memory objects can be released. its a small patch, but its also untested
> https://github.com/brainslayer/zfs
> [BrainSlayer@b4acf2b](https://github.com/BrainSlayer/zfs/commit/b4acf2bd393211aab119d18ce51fa62f811b8b68)

ok. i'l having free ssd, so i will check this with out current pool with data...(nut, only after chromium will compile in -j 32 :-( )

**Comment by BrainSlayer** [comment]
i'm sure to 90% that it works. but there is still a risc of course

**Comment by BrainSlayer** [comment]
damn there seem to be a cyclic dependency in the module order. need to rethink something

**Comment by KosmiK2001** [comment]
ok, i still compiling ..so..

**Comment by BrainSlayer** [comment]
fixed the problem in the meantime. new version is commited

**Comment by KosmiK2001** [comment]
well, oops:
[37837.619168] zzstd: Unknown symbol zthr_destroy (err -2)
[37837.619178] zzstd: Unknown symbol zthr_cancel (err -2)
[37837.619197] zzstd: Unknown symbol zthr_create_timer (err -2)
[37857.264536] zzstd: Unknown symbol zthr_destroy (err -2)
[37857.264555] zzstd: Unknown symbol zthr_cancel (err -2)
[37857.264585] zzstd: Unknown symbol zthr_create_timer (err -2)

**Comment by Ornias1993** [comment]
@KosmiK2001 did you rebuild the lastest version from @BrainSlayer

**Comment by KosmiK2001** [comment]
@BrainSlayer 
well, i did a same test on openzfs master, but with ssd120gb pool.
`zpool create -f -d -o feature@spacemap_v2=disabled -o feature@extensible_dataset=enabled -o feature@large_blocks=enabled -o feature@async_destroy=enabled -o feature@enabled_txg=enabled -o feature@embedded_data=disabled -o feature@empty_bpobj=disabled -o feature@spacemap_histogram=disabled -o feature@filesystem_limits=disabled -o feature@lz4_compress=enabled -o feature@sha512=disabled -o feature@skein=disabled -o feature@edonr=enabled -o feature@userobj_accounting=disabled -o feature@hole_birth=disabled -o feature@bookmarks=disabled -o feature@zstd_compress=disabled -O atime=off -O compression=gzip-9 -O checksum=edonr -O dedup=on -O xattr=off -O mountpoint=/zssd "$poolname" -o ashift=12 $disk
`
then i created zvol
`zfs create -V 24G -b 512k -o dedup=on -o compress=gzip-9 -o checksum=edonr ssd120gb/Windows8_x64_AutoCad`
and i duplicated from hdd with zstd15 to ssd with gzip-9.
then i started it, do some defrag, space clear. shutdown windows8.
zpool export ssd120gb and cache_clear. memory was not holdet.
after rmmod zfs i also got 1gb ram.
rmmod all others modules ..same ram usage....
so..zzstd & zfs...:-(

**Comment by KosmiK2001** [comment]
> @KosmiK2001 did you rebuild the lastest version from @BrainSlayer

of cource....i did local overlay for zfs-9999 and zfs-kmod-9999 ebuilds and changed it from openzfs to BrainSlayer....
its builded ok, but,...insmod sayd: no bruh...nonono..

**Comment by KosmiK2001** [comment]
btw, w/o using any zstd compression in pool, after pool exported, zfs module hold around 1.2gb!!
so, `zfs_arc_min=67108864` mean anything now??
strange, in 0.8.2 and prev's - the behavior was different!! The zfs module returned memory completely, except 64MB, and returned it when clearing caches.
why **now** he keeps this memory?

**Comment by BrainSlayer** [comment]
have you waited at least one minute? the memory pool release check will only be done once in a minute

**Comment by BrainSlayer** [comment]
in the meantime i made some internal test and added also debuggin code to check if memory is released. the new code works as expected and checks every 60 seconds for release of pooled objects and since each object has a timeout of 2 minutes, all was released after 3 minutes maximum wait time

**Comment by BrainSlayer** [comment]
btw for loading zzstd, zcommon must be loaded first (zzstd depends on that module in my modication). insmod is a bad idea here anyway. use modprobe.

**Comment by BrainSlayer** [comment]
https://github.com/openzfs/zfs/pull/10969

**Comment by KosmiK2001** [comment]
@BrainSlayer 
WOW!

I just tested your patch and I must say it works. Not right away, but ... I even noticed this moment on the graph of RAM usage. And the pool was not exported at that moment.
Really - 1.2-1.5GB of memory was freed.
But there is still the zfs module itself. He still retains memory.
Is it possible to remake this patch so that it works (also) at the time of a request to free caches, buffers or lack of RAM? That would be awesome!

**Comment by Ornias1993** [comment]
This PR is very ZSTD specific and no, it's not supposed to help out low-ram scenario's. ZSTD needs it's ram and if you are too tight to have a few GB for ZSTD, you shouldn't enable it in the first place. (regardless of when and how its freed)

**Comment by KosmiK2001** [comment]
@Ornias1993 
No, these 1.2-1.5GB are not a problem (although the fact of retention was unexpected for me).
The problem is in the **zfs** module. Which holds 6GB just like that.

**Comment by BrainSlayer** [comment]
@KosmiK2001 the zstd code is very independend from zfs. this has also nothing todo with this report here. consider also that not only zfs might be responsible. think also about the linux slab and filesystem cache. and since you have deduplication enabled zfs will use alot of ram depending of the blocks you have stored. to reduce the usage you may increase the recordsize. i use 1MB for my own storage. this of course only for new stored records and has no effect for already existing files/datablocks

**Comment by BrainSlayer** [comment]
> @Ornias1993
> No, these 1.2-1.5GB are not a problem (although the fact of retention was unexpected for me).
> The problem is in the **zfs** module. Which holds 6GB just like that.
> 
> @BrainSlayer
> What if this parameter
> `**& zstd_memory_liberator_cb, NULL, NULL, SEC2NSEC (60));**`
> is moved to the settings of the zzstd module? (I probably want a lot).
> In my opinion, this is a completely correct decision: leave it at the discretion of the user.

which parameter? the 60 seconds? zstd has no settings except for the compression level. so nothing can be moved. consider also that the memory pool has a own timeout for orphan entries. it just checks every 60 seconds but the entries have a timeout of 120 seconds. so decreasing just detects earlier that a entry is not in use anymore. but doing it lazy without hurry is still a good approach. everything else will just turn the concept of caching into shit. i dont think that a adjustment is required here.

**Comment by KosmiK2001** [comment]
> @KosmiK2001 the zstd code is very independend from zfs. this has also nothing todo with this report here. consider also that not only zfs might be responsible. think also about the linux slab and filesystem cache. and since you have deduplication enabled zfs will use alot of ram depending of the blocks you have stored. to reduce the usage you may increase the recordsize. i use 1MB for my own storage. this of course works only for new stored records and has no effect for already existing files/datablocks

In fact, deduplication on the hdd pool is not used.
I only used it on ssd pool.
So, dedup not a problem.

**Comment by KosmiK2001** [comment]
Well, in any case - we are waiting for this patch in the master branch.

**Comment by BrainSlayer** [comment]
no matter where you use it. it takes ram. i doesnt matter if its enabled on the hdd or ssd. each written record gets a entry in the deduplication table

**Comment by KosmiK2001** [comment]
To be honest, I'm not sure if the problem is completely resolved. The patch solves the problem of memory retention by the zstd module. The zfs module after this patch, when BrainSlayer released a working patch, was still holding a considerable amount of memory after the pool was exported.

**Comment by Ornias1993** [comment]
@KosmiK2001 If there are any remaining issues that are not related to ZSTD, please file a seperate issue! :)

**Comment by KosmiK2001** [comment]
@Ornias1993 
ah..sorry? np. ok.

**Comment by Ornias1993** [comment]
Well, even if it's just the fact no one is going to read through a whole discussion about zstd to get to your message that it isn't only zstd ;)

**Comment by KosmiK2001** [comment]
Ok, some fresh results.
dataset.zstd-19. recordsize=128k: Perfect.
recordsize=1M: zfs holds some ram, zstd also.
recordsize=16M: zfs holds around 6g, zstd..300-400m.
I will test more. will see.

**Comment by KosmiK2001** [comment]
hmm, well, it looks like the root of the problem lies in the non-standard recordsize. At 1m, memory retention is already starting. by 16m - the amount of retained memory grows. 
I ran the tests again. This time - in a similar way:
zfs create -V 24G **-b 16M -o compression=lz4** -o dedup =on -o checksum =sha512 ssd120gb/Windows8_x64_AutoCad
The result is not comforting. The zfs module holds and does not give back RAM.
Hmm, apparently we need to issue a new bug, exclusively for the zfs module and its work on non-standard recordsize.
_So far, I can't even imagine what to write in the new bug report._

**Comment by Ornias1993** [comment]
> So far, I can't even imagine what to write in the new bug report.

“Zfs does not return ram on export with high record sizes”

**Comment by BrainSlayer** [comment]
i dont think so. zstd does not take care about record sizes. it releases memory if the memory is not in use. i debugged this to a very deep level and it works perfect. but as far as there are still file accesses the memory might be still hold
