### ISSUE TITLE
Build error: 'FALLOC_FL_PUNCH_HOLE' undeclared

### ISSUE THREAD

**Issue by angstymeat** [openzfs/zfs#10947]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 18
Linux Kernel	| 3.11.10-100
Architecture	| x86-64
ZFS Version	| master
SPL Version	| master

### Describe the problem you're observing
Compiling the current git master under F18 causes:
```
make[3]: Entering directory `/root/src/zfs-master/lib/libzpool'
  CC       vdev_file.lo
../../module/os/linux/zfs/vdev_file.c: In function 'vdev_file_io_start':
../../module/os/linux/zfs/vdev_file.c:276:10: error: 'FALLOC_FL_PUNCH_HOLE' undeclared (first use in this function)
../../module/os/linux/zfs/vdev_file.c:276:10: note: each undeclared identifier is reported only once for each function it appears in
../../module/os/linux/zfs/vdev_file.c:276:33: error: 'FALLOC_FL_KEEP_SIZE' undeclared (first use in this function)
```

This doesn't happen with 0.8.2-1 or earlier.

I know that F18 is very outdated, but I still have a few months before I can upgrade the system, and the kernel is still within the officially-supported range for ZFS.

I do see that it is defined in `/usr/src/kernels/3.11.10-100.fc18.x86_64/include/uapi/linux/falloc.h`
### Describe how to reproduce the problem
Download git master, autogen, configure, and then run make.

### Include any warning/errors/backtraces from the system logs
```
Making all in libzpool
make[3]: Entering directory `/root/src/zfs-master/lib/libzpool'
  CC       vdev_file.lo
../../module/os/linux/zfs/vdev_file.c: In function 'vdev_file_io_start':
../../module/os/linux/zfs/vdev_file.c:276:10: error: 'FALLOC_FL_PUNCH_HOLE' undeclared (first use in this function)
../../module/os/linux/zfs/vdev_file.c:276:10: note: each undeclared identifier is reported only once for each function it appears in
../../module/os/linux/zfs/vdev_file.c:276:33: error: 'FALLOC_FL_KEEP_SIZE' undeclared (first use in this function)
make[3]: *** [vdev_file.lo] Error 1
make[3]: Leaving directory `/root/src/zfs-master/lib/libzpool'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/src/zfs-master/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/src/zfs-master'
make: *** [all] Error 2
```

**Comment by behlendorf** [comment]
@angstymeat if you can include the needed header the should resolve your build issue.  Alternately, you could make the following change to disable hole punching when trimming file vdevs.

```diff
diff --git a/module/os/linux/zfs/vdev_file.c b/module/os/linux/zfs/vdev_file.c
index a4e71ca..021c527 100644
--- a/module/os/linux/zfs/vdev_file.c
+++ b/module/os/linux/zfs/vdev_file.c
@@ -272,7 +272,7 @@ vdev_file_io_start(zio_t *zio)
                int mode = 0;
 
                ASSERT3U(zio->io_size, !=, 0);
-#ifdef __linux__
+#if defined(__linux__) && defined(FALLOC_FL_PUNCH_HOLE)
                mode = FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE;
 #endif
                zio->io_error = zfs_file_fallocate(vf->vf_file,
```

**Comment by angstymeat** [comment]
I don't mean for you to do my tech support for me, but...

I tried this a month ago, but I didn't have the time to look deeper. When I try to add the directory with falloc.h using CFLAGS, it appears to ignore the CFLAGS variable, and I get the same error.

When I apply the above patch, I eventually get:
```
make[3]: Entering directory `/usr/src/kernels/3.11.10-100.fc18.x86_64'
  CC [M]  /root/src/zfs-master/module/spl/../os/linux/spl/spl-cred.o
/root/src/zfs-master/module/spl/../os/linux/spl/spl-cred.c: In function ‘crgetgroups’:
/root/src/zfs-master/module/spl/../os/linux/spl/spl-cred.c:110:27: error: request for member ‘val’ in something not a structure or union
make[5]: *** [/root/src/zfs-master/module/spl/../os/linux/spl/spl-cred.o] Error 1
make[4]: *** [/root/src/zfs-master/module/spl] Error 2
make[3]: *** [_module_/root/src/zfs-master/module] Error 2
```

**Comment by behlendorf** [comment]
Closing.  There is probably still an issue building with this 3.11.10-100, but it's not something which we anticipate having time to investigate. Still thanks for opening this issue so it's at least tracked.

**Comment by aasraoui** [comment]
@behlendorf can you point out the full path for vdev_file.c to make the changes ..
using zfs-2.1.5 tar file thanks in advance!!
