### ISSUE TITLE
Pools are not imported/mounted on boot. 

### ISSUE THREAD

**Issue by AngryAdmean** [openzfs/zfs#10941]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox 6.2
Distribution Version	| 6.2-11
Linux Kernel	|  5.4.60-1-pve
Architecture	| x86-64
ZFS Version	|  2.0.0-rc1_65_g9569c3116
SPL Version	| 2.0.0-rc1_65_g9569c3116

### Describe the problem you're observing
Pools wont automatically import during proxmox boot.

### Describe how to reproduce the problem
Install Proxmox 6.2-1

Run the following commands:
apt-get update
apt-get upgrade
apt-get dist-upgrade

apt-get install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev pve-headers python3 python3-dev python3-setuptools python3-cffi libffi-dev git

git clone https://github.com/zfsonlinux/zfs
cd zfs
git checkout zfs-2.0.0-rc1
sh autogen.sh
./configure
make deb

Remove the following packages or installation of newly built packages fails.
apt-get remove zfs zfs-dkms libzfs2 libzpool2 libnvpair1linux libzfs2linux libzpool2linux libuutil1linux

Install the newly built packages.
dpkg -i zfs_2.0.0-0_amd64.deb zfs-dkms_2.0.0-0_amd64.deb libnvpair1_2.0.0-0_amd64.deb libzfs2_2.0.0-0_amd64.deb libzpool2_2.0.0-0_amd64.deb libuutil1_2.0.0-0_amd64.deb zfs-test_2.0.0-0_amd64.deb zfs-dracut_2.0.0-0_amd64.deb zfs-initramfs_2.0.0-0_amd64.deb python3-pyzfs_2.0.0-0_amd64.deb

I "fixed it" by running apt-get install zfsutils-linux (from debian/proxmox repository) but they replace some of the newly built and installed packages. However, persistent l2arc for instance still works and the pools are imported on boot.

### Include any warning/errors/backtraces from the system logs

None that I could find.

**Comment by Fabian-Gruenbichler** [comment]
(Proxmox developer here)

please note that `make deb` from the upstream repo, and packages built 'properly' for Debian/Proxmox differ quite a lot in how they are integrated into the system at large. we are already starting testing internally with the RC,  and once there are usable packages we will make them available for broader testing/publically as well.

**Comment by cyprix** [comment]
@AngryAdmean I had the same issue on the Ubuntu 18.04.5.
After installing the dracut package it was fixed.
