### ISSUE TITLE
Fedora 32 add dkms for 2.0.0RC2

### ISSUE THREAD

**Issue by monwarez** [openzfs/zfs#10954]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Fedora
Distribution Version	|32
Linux Kernel	|5.8.9
Architecture	|x86_64
ZFS Version	|0.8.4
SPL Version	|

### Describe the problem you're observing
Since the version of kernel 5.8 zfs version 0.8.4 is not supported, so we may need to have access to the release candidate by using the testing repository
### Describe how to reproduce the problem
Build the dkms package for the latest kernel

By updating the `dkms.conf` file to include the new version `2.0.0` and the `zzstd` module it is possible to build the dkms with fedora, would it be possible to have the updated version in the testing repository ?

**Comment by Ornias1993** [comment]
@monwarez Thanks for the issue! :)
I still don't really get what you are asking... though, previously there was an issue with you not being able to build OpenZFS2.0 RC2 with ZSTD enabled... You mean you solved the issue? In that case it might be faster just to create a PR for your fix.

But what testing repository? OpenZFS doesn't maintain a repository with per-repo afaik.

**Comment by monwarez** [comment]
The change on the dkms was due to OpenZFS2.0 RC2 introduction to zzstd as a separate module `module/zstd`.
My fixes for zstd was just to add it to the dkms.conf so that it install zzstd module and thus no undefined symbol about zstd compression. As a side note I am not rebuilding an rpm, just using dkms to directly build the RC version.
As per https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html it seems like zfsonlinux is hosting the rpm repository. But since zfsonlinux is now openzfs I am a little bit confuse.

**Comment by Ornias1993** [comment]
@monwarez It seems the ZZSTD module is actually already added to the dkms.conf creation script (as linked above) so you should be fine without changes.

I think those repo's are just outdated. Are you sure they actually include OpenZFS2.0 RC2?
I tried to find out who is responsible for it:
Officially for those things either the repo or ZFSonLinux is responsible. Remember: OpenZFS doesn't make packages for every OS, thats the responsibiltity of the downstream.

I think @behlendorf is still also the one to contact about it though.

**Comment by monwarez** [comment]
Those repos does not include OpenZFS 2.0RC2, that is why I manually extracted the tarball to the correct place,and used the outdated `dkms.conf` that was generated for 0.8.4 .
Thanks for the clarification.

**Comment by Ornias1993** [comment]
@monwarez Thanks for your clarification too!
You shouldn't use a dkms.conf generated for 0.8.4 with a 2.0.0RC tarball.
You can just generate a good dkms.conf the normal way (using the build scripts) :)

**Comment by behlendorf** [comment]
@monwarez adding the 2.0-rc2 release to the Fedora testing repositories is a good idea.  Thanks for the reminder.  Until then you can locally build the same dkms packages from the tarball by running:

```sh
./configure
make rpm-dkms rpm-utils
```

**Comment by behlendorf** [comment]
The OpenZFS 2.0.0-rc3 release has been added to the testing repositories for Fedora 31,32 and CentOS 7.8 ,8.2.
