### ISSUE TITLE
Testing Repo for Fedora 32 not working

### ISSUE THREAD

**Issue by jochendemuth** [openzfs/zfs#10964]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.8
Architecture	| x86_64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

### Describe the problem you're observing
[root@home ~]# dnf update
ZFS on Linux for Fedora 32 - Testing                                                                                                    594  B/s | 243  B     00:00    
Errors during downloading metadata for repository 'zfs-testing':
  - Status code: 403 for http://download.zfsonlinux.org/fedora-testing/32/x86_64/repodata/repomd.xml (IP: 52.218.233.232)
Error: Failed to download metadata for repo 'zfs-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: zfs-testing
Last metadata expiration check: 0:05:45 ago on Tue 22 Sep 2020 09:36:13 AM EDT.
Dependencies resolved.
Nothing to do.
Complete!

### Describe how to reproduce the problem
Current production ZFS/SPL version (0.8.4) not support on available kernels in Fedora 32 (https://github.com/openzfs/zfs/issues/10922). In bug 10922 @Ornias1993, @behlendorf recommend upgrading to 2.0.0rc or 0.8.5-staging respectively. 
Trying to enable fedora-testing repo to get access to recommended zfs version.
Above error indicates that fedora-testing repo is not working for Fedora 32.

### Include any warning/errors/backtraces from the system logs
Content of http://download.zfsonlinux.org/fedora-testing/32/x86_64/repodata/repomd.xml:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E041996235A6942B</RequestId>
<HostId>
+7fMLrvPFUv30sypvSg6Os7h9E3WLGBN/rcjs7Y80dG8CBjPN6SKJekXstX2iBuI9N7yFpFEj9A=
</HostId>
</Error>

**Comment by jochendemuth** [comment]
Package manager provide convenient accessibility of pre-release versions to a larger audience rather than relying on the method of source download and manual compilation. The process of maintaining testing repo should be largely automated (certainly scriptable) at this point. 
I understand and appreciate that these types of peripheral issues take away focus from fixing issues in the actual zfs code, but on the other hand it is a critical vehicle to expand the community. 
Please consider fixing.

**Comment by Ornias1993** [comment]
As pointed out in the issue you refer too, there is no test build on fedora 32 yet at all.
You can close this issue, because it's another side of the same issue highlighted in #10922.

In bug 10922 we point out you need to install it yourself, because the testing repo is outdated (there is none for fedora 32, as openzfs2.0 or 0.8.5 isn't on the repo yet which is required for 32 builds)

**Comment by behlendorf** [comment]
@jochendemuth it's definitely a challenge keeping up with Fedora.  I'll see about adding the 2.0.0-rc2 release to the zfs-testing repository.  Once 0.8.5 is tagged it'll be added to the main repository.

**Comment by jochendemuth** [comment]
@behlendorf Thanks! ZFS is back on my Fedora 32!
