### ISSUE TITLE
Intermittent /bin/ls EIO for .zfs over NFS

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#10974]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Scientific Linux
Distribution Version	| 7.8
Linux Kernel	| 3.10.0-1127.18.2.el7
Architecture	| x86_64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

### Describe the problem you're observing

/bin/ls is occasionally returning EIO for .zfs over NFS (vers=3). Note, I do not see this problem directly on the ZFS server, the underlying zpool is healthy, and I also don't see this problem on the NFS client for any other directory besides .zfs.

### Describe how to reproduce the problem
```
#
# Start with filesystem unmounted on NFS client and let the automounter do its thing
#
[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs
shares  snapshot

[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs/oops
ls: cannot access /home/stuart.anderson/.zfs/oops: Input/output error

[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs
ls: cannot open directory /home/stuart.anderson/.zfs: Input/output error

[root@ldas-pcdev10 ~]# umount /home/stuart.anderson

[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs
shares  snapshot

[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs/oops
ls: cannot access /home/stuart.anderson/.zfs/oops: No such file or directory

[root@ldas-pcdev10 ~]# ls /home/stuart.anderson/.zfs
shares  snapshot
```

### Include any warning/errors/backtraces from the system logs

```
#
# NFS client mount options
#
[root@ldas-pcdev10 ~]# grep stuart.anderson /proc/mounts
zfshome1:/home1/stuart.anderson /home/stuart.anderson nfs rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,addr=10.14.0.154 0 0

#
# NFS server sharenfs options
#
[root@cascade2 ~]# zfs get sharenfs home1/stuart.anderson
NAME                   PROPERTY  VALUE                                                                     SOURCE
home1/stuart.anderson  sharenfs  rw=@10.14.0.0/16:@10.9.0.0/16,sync,root_squash,crossmnt,no_subtree_check  inherited from home1
```

**Comment by stuartthebruce** [comment]
I am still seeing this with ZFS 0.8.5, so I am curious if anyone else has seen anything similar, or if perhaps this an NFS bug rather than a ZFS bug (even though it only happens for the .zfs directory)?

**Comment by asciiphil** [comment]
I have not seen this problem since upgrading my NFS server to OpenZFS 2.0 (specifically 2.0.6).  That's not necessarily completely definitive, since it was an intermittent problem before.  But it does look promising so far.

**Comment by youzhongyang** [comment]
Setting zfs_expire_snapshot=0 helped us.

**Comment by asciiphil** [comment]
After months of running on OpenZFS 2.0.6, I have not seen this problem recur on our server.  I'm willing to consider it to be have been fixed.

**Comment by stuartthebruce** [comment]
Works for me. I will re-open this issue if I see the problem again with any ZFS 2.x.y systems.
