### ISSUE TITLE
ZTS: l2arc/persist_l2arc_007_pos failure

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#10981]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Any
Distribution Version	| Any
Linux Kernel	| Any
Architecture	| x86_64
ZFS Version	| zfs-2.0.0-rc1-93-gcf26677

### Describe the problem you're observing

```
Tests with results other than PASS that are unexpected:
    FAIL l2arc/persist_l2arc_007_pos (expected PASS)
```

### Describe how to reproduce the problem

Occasionally reproduced by the CI during testing.

### Include any warning/errors/backtraces from the system logs

http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/13298/steps/shell_9/logs/summary

**Comment by behlendorf** [comment]
@gamanakis would you mind taking a look at this issue.  This is one of the more common failures we've been seeing in the CI.

**Comment by gamanakis** [comment]
Sure! I wasn't aware it is failing often. I think I can fix this easily.
