### ISSUE TITLE
MMP design question

### ISSUE THREAD

**Issue by homerl** [openzfs/zfs#10987]
### Ask your question!
MMP is kindness, before MMP, There is no protected for brain split in ZFS.
Our 99.9 % ZFS crash because of MMP timeout with a device.
1. Does the only way to increase MMP default timeout? 
    If yes, When a single device hangs, the zpool hangs too. and all users access this zpool hang too.  
    The timeout just avoids the issue, not resolved.
    In my opinion, it's a raid system, What the basic raid protect?
    I think raid5 is for protects the single device failure. 
    Before some devices failed, the device latency will take some mins, The timeout could not stop the zpool suspend. 
    if not, Could you please show me the better way?

2. Does zpool import return failed is better than letting zpool suspend?
Thank you.

**Comment by behlendorf** [comment]
@homerl it is possible (and reasonable) to configure MMP such that it won't automatically suspend the pool by setting the module option `zfs_multihost_fail_intervals = 0`.  This will provide you the `zpool import` protection offered by MMP without the concern that it might suspend your pool.

**Comment by homerl** [comment]
@behlendorf 
Thank you.
