### ISSUE TITLE
zfs receive: Input/output error accessing dataset after resuming interrupted receive

### ISSUE THREAD

**Issue by asomers-ax** [openzfs/zfs#10995]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  FreeBSD
Distribution Version	| 13.0-CURRENT and 12-STABLE
Linux Kernel	| N/A
Architecture	| amd64
ZFS Version	| 0.8.0-1
SPL Version	| N/A

### Describe the problem you're observing

When resuming an interrupted ZFS send stream that creates a new dataset with the same name as an existing dataset, if the existing dataset is accessed after the failed receive, then after the subsequent successful receive it will return EIO.  This happens because nothing mounts the new dataset, leaving the old, no longer valid dataset still mounted. 

### Describe how to reproduce the problem
```sh
sudo zpool create testpool vtbd1
sudo zfs create testpool/src
sudo zfs create testpool/dst
sudo dd if=/dev/zero bs=1m count=2 of=/testpool/src/zerofile
sudo zfs snapshot testpool/src@1
sudo zfs send -v testpool/src@1 | head -c 1000000 | sudo zfs recv -Fsv testpool/dst
ls -a /testpool/dst
sudo zfs send -t $(zfs get -Hovalue receive_resume_token testpool/dst) | sudo zfs recv -Fsv testpool/dst
ls -a /testpool/dst
```
```
$ ls -a /testpool/dst
ls: /testpool/dst: Input/output error
```

Downstream issue: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248606

**Comment by asomers-ax** [comment]
BTW, I have a working patch to fix this.  I just haven't figured out how to build the OpenZFS repo yet.

**Comment by behlendorf** [comment]
> BTW, I have a working patch to fix this. I just haven't figured out how to build the OpenZFS repo yet.

That's great.  There is some developer documentation about how to build the repository [here](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html#developing-in-tree).  It looks like it's still a little Linux centric and should be updated, but the basic procedure applies to FreeBSD.

```sh
git clone https://github.com/openzfs/zfs
sh autogen.sh
./configure
make
```
