### ISSUE TITLE
Fedora: "Unknown symbol" on zfs_zstd_(de)compress at modprobe

### ISSUE THREAD

**Issue by c3d** [openzfs/zfs#11004]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.6.15-300-fc32 and 5.8.4-200-fc32
Architecture	| x86_64
ZFS Version	| 0.8.4 and 0.8.5 (from master)
SPL Version	| 0.7.9
Version (as reported by modinfo) |  2.0.0-rc1_100_g6c9f52442

### Describe the problem you're observing

ZFS module built using dkms build correctly, but fail to load and the following message is seen on `dmesg`:

```
# modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
# dmesg
[ 3126.089124] zfs: Unknown symbol zfs_zstd_compress (err -2)
[ 3126.089632] zfs: Unknown symbol zfs_zstd_decompress_level (err -2)
[ 3126.090223] zfs: Unknown symbol zfs_zstd_decompress (err -2)
```

### Describe how to reproduce the problem

On Fedora 32 system, after `dnf update`, booting either 5.6.15-300-fc32 and 5.8.4-200-fc32:

Method 1 (only works with 5.6.15 kernel, the `dkms build` of 0.8.4 fails against 5.8.4 with errors like `__vmalloc` call not having right number of arguments):

1. `dnf install http://download.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm`
2. `dnf remove zfs` (also removes `libvirt` in my case`
3. `dnf install zfs`
4. `modprobe zfs`

I get the same result if I manually rebuild with `dkms build zfs/0.8.4` and then `dkms install`.

Method 2: (Tested against both 5.6.15 and 5.8.4 kernel)

1. Git clone zfs repository master branch, commit 5aa3e3d3be4b0c2a2f30cd0a6de49ad1d0c42de2, into `/usr/src/zfs-0.8.5`.
2. Run `autogen.sh`
3. Copy `dkms.conf`  from `/usr/src/zfs-0.8.4` installed by `dnf install zfs-dkms` 
4. Change version number to 0.8.5
5. `dkms build zfs/0.8.5` then `dkms install zfs/0.8.5`

Of note, building manually _seems_ to work, but really does not:

Method 3, tested against 5.8.4:

1. From the clone above, run `autogen.sh` then `configure` and `make`
2. Run `make install`
3. Then the module does build and `modprobe` loads it (still with the silly version, `2.0.0-rc1_100_g6c9f52442`)
4. `zpool import` does work and shows my pool as online
5. However, `zpool import data` crashes in `mount.zfs` with an unsatisfied symbol

```
# zfs mount data
/sbin/mount.zfs: symbol lookup error: /sbin/mount.zfs: undefined symbol: zfs_parse_mount_options
```

### Include any warning/errors/backtraces from the system logs

```
# modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
# dmesg
[ 3126.089124] zfs: Unknown symbol zfs_zstd_compress (err -2)
[ 3126.089632] zfs: Unknown symbol zfs_zstd_decompress_level (err -2)
[ 3126.090223] zfs: Unknown symbol zfs_zstd_decompress (err -2)
```

**Comment by c3d** [comment]
Updated description with mount error.

Also, I was wrong about this being successful on 5.6.15. After reboot, I got the same mount error there too.

**Comment by c3d** [comment]
It looks like the mount error goes away if I do a `dnf remove zfs`. I suspect an incompatibility between the version of the tools installed by `dnf install zfs` and the version installed by doing `make` / `make install`.

**Comment by c3d** [comment]
Confirmed that the problem with the `mount` crash is related to having two versions together. I was successful re-importing and mounting my pool even with kernel 5.8.4 using `configure --prefix=/usr` (after `dnf uninstall zfs`).

So something about the Fedora `dkms` build process causing two specific symbols to not load correctly. I wonder if this is related to the fact that at some point I was running with something (kernel with lock debug or something like that?) that required a non-tained kernel. That was a long time ago. Hmm.

**Comment by behlendorf** [comment]
@c3d the missing symbols are provided by a new `zzstd.ko` kernel module which is part of the 2.0 and master branches but not the previous releases.  If you're using the `dkms.conf` from 0.8.4 it wouldn't include the lines to install this new kmod.  You could add them, see the bottom of the `scripts/dkms/mkconf` script.  Or better yet, you could build dkms packages using master and use those. 

```sh
./configure
make rpm-dkms rpm-utils
```

**Comment by c3d** [comment]
@behlendorf Thanks. Did I just hit a bad window in the way the "official" packages were built? Or is a fix needed there?

**Comment by behlendorf** [comment]
So the 0.8.4 packages don't support the 5.8.4 Fedora kernel which recently rolled out.  There's an 0.8.5 tag on the way with the backported compatibility patch, but it hasn't been tagged yet and added to the repos.  So if you need to use the new kernel you'll have to stick to the master branch for a little bit.

**Comment by c3d** [comment]
Perfect, thanks. Closing issue, it contains enough information for someone else hitting this.
