### ISSUE TITLE
modprobe zfs returns error on all rc's

### ISSUE THREAD

**Issue by jemmille** [openzfs/zfs#1102]
Info:

uname -r
2.6.32-279.14.1.el6.x86_64 Centos 6.3 Final

modprobe zfs

FATAL: Error inserting zfs (/lib/modules/2.6.32-279.14.1.el6.x86_64/addon/zfs/zfs/zfs.ko): Unknown symbol in module, or unknown parameter (see dmesg)

dmesg:

(there are TONS of zfs: disagrees about...)
zfs: disagrees about version of symbol vn_fsync
zfs: Unknown symbol vn_fsync
conftest[3917]: segfault at 7f057f7abe48 ip 00000000004007fe sp 00007f057f7afe50 error 6 in conftest[400000+1000]
conftest[4281]: segfault at 7fcb54300e48 ip 00000000004007fe sp 00007fcb54304e50 error 6 in conftest[400000+1000]
conftest[29500]: segfault at 7fcce0e31e48 ip 00000000004007fe sp 00007fcce0e35e50 error 6 in conftest[400000+1000]
zfs: disagrees about version of symbol zpool_prop_default_numeric

This is happening no matter what RC i use.  I'm guessing this has something to do with how things are linked when using dkms vs non-dkms.  I had previously tried using the dkms modules (without success), removed them, then reinstalled rc-11 last week and it was working fine. and got it to a working state.  This began occurring after a reboot.  When I remove everything (zfs and spl), I recieve errors about the kernel modules from zfs not existing in /lib/modules/my_kernel/weak-modules/

The spl modules will load:

lsmod |grep spl
spl                   253612  4 zcommon,znvpair,zavl,zunicode
zlib_deflate           21629  1 spl

Just to add:

rpm -qa |grep spl
spl-0.6.0-rc11.x86_64
spl-modules-0.6.0-rc11_2.6.32_279.14.1.el6.x86_64
spl-modules-devel-0.6.0-rc11_2.6.32_279.14.1.el6.x86_64

rpm -qa |grep zfs
zfs-devel-0.6.0-rc11.x86_64
zfs-0.6.0-rc11.x86_64
zfs-dracut-0.6.0-rc11.x86_64
zfs-modules-devel-0.6.0-rc11_2.6.32_279.14.1.el6.x86_64
zfs-modules-0.6.0-rc11_2.6.32_279.14.1.el6.x86_64
zfs-test-0.6.0-rc11.x86_64

And this is the output I get when I remove the zfs-modules rpm:

rpm -e zfs-modules
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/znvpair.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/zpios.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/zunicode.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/spl.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/splat.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/zavl.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/zfs.ko: No such file or directory
WARNING: Can't read module /lib/modules/2.6.32-279.14.1.el6.x86_64/weak-updates/zcommon.ko: No such file or directory

Same thing happens when i remove spl-modules.

**Comment by Harvie** [comment]
> I'd suggest you just make sure you purge all the dkms bits from the system before trying again.

Can't you just modify the make script to always build against the spl from the same directory?
My dkms built both spl.ko and zfs.ko, but still geting "unknown symbol"...
