### ISSUE TITLE
ZFS 2.0.0-rc3 hangs while installing ubuntu 20.04 in qemu 

### ISSUE THREAD

**Issue by alexanderhaensch** [openzfs/zfs#11036]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| Stable
Linux Kernel	| 5.8.13
Architecture	| amd64
ZFS Version	| 2.0.0-rc3
SPL Version	|

### Describe the problem you're observing
Today i tried to install ubuntu desktop 20.04 from iso in virt-manager. Installation was stopping at some moment with virt-manager hang and qemu vm stopped. No recovery possible. Tried to reboot. System was unable to unmount the directories where the ubuntu qcow2 image was stored.

### Describe how to reproduce the problem
After reboot, i tried again to boot the vm ->  similar error message in dmesg.
### Include any warning/errors/backtraces from the system logs

**First dmesg output:**

 ------------[ cut here ]------------
 kernel BUG at fs/inode.c:1668!
 invalid opcode: 0000 [#1] SMP NOPTI
 CPU: 3 PID: 8412 Comm: qemu-event Tainted: P           O      5.8.12 #1
 Hardware name: System manufacturer System Product Name/TUF GAMING X570-PLUS (WI-FI), BIOS 2407 07/01/2020
 RIP: 0010:iput+0x1ab/0x1f0
 Code: 5d e9 19 fb ff ff 48 8b 85 98 00 00 00 eb a5 85 d2 74 a1 48 83 bd e0 00 00 00 00 74 97 a9 00 00 01 00 75 90 e9 44 ff ff ff c3 <0f> 0b a9 b7 08 00 00 75 1c 8b 85 58 01 00 00 85 c0 75 12 48 8b 45
 RSP: 0018:ffffbf61d7e93940 EFLAGS: 00010202
 RAX: 0000000000000002 RBX: ffffa01462705ee0 RCX: 0000000000000002
 RDX: 000000000000064b RSI: ffffffffc0a14a80 RDI: ffffffffc08b3f4a
 RBP: ffffffffc08b3f4a R08: 0000000000000000 R09: 0000000000000000
 R10: ffffbf61d7e939a0 R11: 0000008000000000 R12: 0000000000000000
 R13: ffffa0197511e000 R14: 0000000000000002 R15: ffffffffc08b3d52
 FS:  00007f092dffb700(0000) GS:ffffa0199eac0000(0000) knlGS:0000000000000000
 CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 CR2: 00007f095e4db870 CR3: 0000000487f3e000 CR4: 0000000000340ee0
 Call Trace:
  zfs_getsecattr+0x4fb/0x570 [zfs]
  ? dmu_zfetch+0x1d2/0x18a0 [zfs]
  ? dbuf_read+0x29b/0x4f0 [zfs]
  ? dbuf_read+0x29b/0x4f0 [zfs]
  ? _cond_resched+0x15/0x30
  ? __kmalloc_node+0x1fe/0x310
  ? _cond_resched+0x15/0x30
  ? mutex_lock+0xe/0x30
  ? dbuf_sync_list+0x223/0x260 [zfs]
  ? sa_handle_get+0x1003/0x11e0 [zfs]
  ? _cond_resched+0x15/0x30
  ? mutex_lock+0xe/0x30
  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
  zfs_setattr+0x1d5a/0x22d0 [zfs]
  ? mutex_lock+0xe/0x30
  ? security_capable+0x36/0x50
  ? _cond_resched+0x15/0x30
  ? __kmalloc_node+0x1fe/0x310
  zpl_write_common+0x13f/0x860 [zfs]
  notify_change+0x333/0x4a0
  chown_common.isra.0+0xdc/0x180
  do_fchownat+0x7f/0xc0
  __x64_sys_chown+0x1e/0x30
  do_syscall_64+0x4d/0xd0
  entry_SYSCALL_64_after_hwframe+0x44/0xa9
 RIP: 0033:0x7f095e0cee77
 Code: 39 84 24 98 00 00 00 75 a1 48 89 ef e8 32 c9 f9 ff eb a0 e8 7b db 01 00 66 2e 0f 1f 84 00 00 00 00 00 90 b8 5c 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d e9 af 0c 00 f7 d8 64 89 01 48
 RSP: 002b:00007f092dffa798 EFLAGS: 00000206 ORIG_RAX: 000000000000005c
 RAX: ffffffffffffffda RBX: 00007f0904389230 RCX: 00007f095e0cee77
 RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00007f094c034b50
 RBP: 00007f090417b390 R08: 0000000000000001 R09: 0000000000000000
 R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
 R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
 Modules linked in: xt_recent ipt_REJECT nf_reject_ipv4 xt_conntrack xt_hashlimit xt_addrtype xt_mark iptable_mangle xt_MASQUERADE iptable_nat xt_CT iptable_raw nfnetlink_log xt_NFLOG nf_log_ipv4 nf_log_common xt_LOG nf_nat_tftp nf_nat_snmp_basic nf_conntrack_snmp nf_nat_sip nf_nat_pptp nf_nat_i>
  stp llc amdgpu snd_hwdep snd_pcsp snd_seq_device videobuf2_v4l2 iwlmvm btusb kvm_amd snd_pcm videobuf2_common eeepc_wmi btrtl asus_wmi kvm snd_timer sp5100_tco videodev btbcm iommu_v2 snd sparse_keymap mac80211 irqbypass rapl video wmi_bmof mc libarc4 k10temp i2c_piix4 gpu_sched soundcore joyd>
 ---[ end trace 1bebaefd10f71425 ]---

**after reboot:**
------------[ cut here ]------------
kernel BUG at fs/inode.c:1668!
invalid opcode: 0000 [#1] SMP NOPTI
CPU: 21 PID: 11285 Comm: prio-rpc-worker Tainted: P           O      5.8.13 #1
Hardware name: System manufacturer System Product Name/TUF GAMING X570-PLUS (WI-FI), BIOS 2407 07/01/2020
RIP: 0010:iput+0x1ab/0x1f0
Code: 5d e9 19 fb ff ff 48 8b 85 98 00 00 00 eb a5 85 d2 74 a1 48 83 bd e0 00 00 00 00 74 97 a9 00 00 01 00 75 90 e9 44 ff ff ff c3 <0f> 0b a9 b7 08 00 00 75 1c 8b 85 58 01 00 00 85 c0 75 12 48 8b 45
RSP: 0018:ffffacea10ec7940 EFLAGS: 00010202
RAX: 0000000000000002 RBX: ffff98dc27497020 RCX: 0000000000000002
RDX: 000000000000064b RSI: ffffffffc0ae8a80 RDI: ffff98de2466da60
RBP: ffff98de2466da60 R08: 0000000000000000 R09: 0000000000000000
R10: ffffacea10ec79a0 R11: 0000008000000000 R12: 0000000000000000
R13: ffff98de24b66000 R14: 0000000000000002 R15: ffff98de2466d868
FS:  00007f65fb7fe700(0000) GS:ffff98de3ef40000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007f65faac2de0 CR3: 00000005e6884000 CR4: 0000000000340ee0
Call Trace:
 zfs_getsecattr+0x4fb/0x570 [zfs]
 ? _cond_resched+0x15/0x30
 ? dbuf_read+0x29b/0x4f0 [zfs]
 ? dbuf_read+0x29b/0x4f0 [zfs]
 ? _cond_resched+0x15/0x30
 ? __kmalloc_node+0x1fe/0x310
 ? _cond_resched+0x15/0x30
 ? mutex_lock+0xe/0x30
 ? dbuf_sync_list+0x223/0x260 [zfs]
 ? sa_handle_get+0x1003/0x11e0 [zfs]
 ? _cond_resched+0x15/0x30
 ? mutex_lock+0xe/0x30
 ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
 zfs_setattr+0x1d5a/0x22d0 [zfs]
 ? mutex_lock+0xe/0x30
 ? security_capable+0x36/0x50
 ? _cond_resched+0x15/0x30
 ? __kmalloc_node+0x1fe/0x310
 zpl_write_common+0x13f/0x860 [zfs]
 notify_change+0x333/0x4a0
 chown_common.isra.0+0xdc/0x180
 do_fchownat+0x7f/0xc0
 __x64_sys_chown+0x1e/0x30
 do_syscall_64+0x4d/0xd0
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f660768ae77
Code: 39 84 24 98 00 00 00 75 a1 48 89 ef e8 32 c9 f9 ff eb a0 e8 7b db 01 00 66 2e 0f 1f 84 00 00 00 00 00 90 b8 5c 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d e9 af 0c 00 f7 d8 64 89 01 48
RSP: 002b:00007f65fb7fd6c8 EFLAGS: 00000206 ORIG_RAX: 000000000000005c
RAX: ffffffffffffffda RBX: 00007f65d8000b80 RCX: 00007f660768ae77
RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00007f65ac37eeb0
RBP: 00007f65ac173710 R08: 0000000000000001 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Modules linked in: xt_recent ipt_REJECT nf_reject_ipv4 xt_conntrack xt_hashlimit xt_addrtype xt_mark iptable_mangle xt_MASQUERADE iptable_nat xt_CT iptable_raw nfnetlink_log xt_NFLOG nf_log_ipv4 nf_log_common xt_LOG nf_nat_tftp nf_nat_snmp_basic nf_conntrack_snmp nf_nat_sip nf_nat_pptp nf_nat_i>
 amdgpu uvcvideo snd_pcsp snd_seq_device snd_hwdep btusb iwlwifi videobuf2_vmalloc snd_pcm btrtl kvm videobuf2_memops videobuf2_v4l2 btbcm eeepc_wmi btintel videobuf2_common asus_wmi snd_timer irqbypass videodev bluetooth sparse_keymap iommu_v2 sp5100_tco snd ecdh_generic video rapl mc wmi_bmof>
---[ end trace 8e8222e65cd7213d ]---

**Comment by IvanVolosyuk** [comment]
Do you have xattr=sa set by any chance? There is a similar looking bug with a different stack trace: https://github.com/openzfs/zfs/issues/11054 I wonder if this can be the same issue.

**Comment by behlendorf** [comment]
Would you mind testing again with 2.0.0-rc4 which has been tagged. It contains the fix for #11054 which does look very similar.

**Comment by alexanderhaensch** [comment]
I think it is solved with 2.0.0-rc4 i could not reproduce the problem. Thanks
