### ISSUE TITLE
leaf node deletion in range tree

### ISSUE THREAD

**Issue by Finix1979** [openzfs/zfs#11044]
### Ask your question!
After removing a range section, the parameter rs structure may contain an invalid value. Therefore, could not reference it later.

in range_tree_add_impl function, call rs = zfs_btree_find(&rt->rt_root, &rsearch, &where) to get rs, if rs not empth, and gap is true, it may call zfs_btree_remove to delete this rs first. if this causes whole leaf deletion, the rs may point to invalid value. Further using rs will cause error such as range_tree_stat_decr(rt, rs);

**Comment by ahrens** [comment]
@pcd1193182, could you take a look at this?

**Comment by pcd1193182** [comment]
This is a bug; filing a PR to fix it now.
