### ISSUE TITLE
How to keep debuginfo in zfs modules?

### ISSUE THREAD

**Issue by youzhongyang** [openzfs/zfs#11060]
### Ask your question!

I built zfs by doing

- sh autogen.sh
- ./configure --enable-debuginfo
- make -j$(nproc) && make deb
 
The zfs modules generated under the 'module' folder can be used in 'crash' utility to load symbols and debugging data, but those installed by the .deb package cannot. 

I can see the size is quite different.

```
# dpkg -c kmod-zfs-5.4.0-26-lowlatency_0.8.5-1_amd64.deb | grep zfs.ko
-rw-r--r-- root/root   3823784 2020-10-13 15:41 ./lib/modules/5.4.0-26-lowlatency/extra/zfs/zfs/zfs.ko
lrwxrwxrwx root/root         0 2020-10-13 15:41 ./usr/lib/.build-id/5e/86b5d9675db9b7279c8ceea2982a82081b0b8c -> ../../../../lib/modules/5.4.0-26-lowlatency/extra/zfs/zfs/zfs.ko

# find . -name zfs.ko -ls
    24478  33301 -rw-r--r--   1 root     root     67737560 Oct 13 15:31 ./module/zfs/zfs.ko
```

My question is - is there a way to prevent it from stripping off useful debuginfo in the *.ko files when generating .deb packages?

### Which portion of the codebase does your question involve?
zfs 0.8.5
Ubuntu 20.04 LTS

**Comment by behlendorf** [comment]
When building packages there should be a `zfs-kmod-debuginfo` package which can be installed which contains the stripped symbols and debugging data.  It looks like we're not be converting that `rpm` package to a `deb` in `config/deb.am`.  Fixing that would probably be the best fix assuming the resulting package works as intended.

Alternately, you should be able to add the following to the top of `rpm/generic/zfs-kmod.spec.in` to prevent it from stripping the modules and creating a debuginfo package.

```
%global _enable_debug_package 0
%global debug_package %{nil}
```

**Comment by youzhongyang** [comment]
@behlendorf - Thanks Brian. I remember I saw that zfs-kmod-debuginfo*.rpm when building zfs on Centos and Oracle Linux.

I edited rpm/generic/zfs-kmod.spec.in as you suggested, but it didn't help, either 0.8.5 or master branch produces *.ko files being stripped off.

I tried a different approach - renaming /usr/bin/strip to something else, it worked.

**Comment by behlendorf** [comment]
That should work too!  Still let's go ahead and leave this open until it can be sorted out properly.

**Comment by adamdmoss** [comment]
FWIW I have a similar issue with zfs-2.0.x/trunk.  Couldn't really untangle the issue in twenty minutes. :)

**Comment by rincebrain** [comment]
To convince my dkms-built modules to leave debug info in (on 0.8.6, at least), I put the following in my /etc/sysconfig/zfs and rebuilt. (Just in case anyone using DKMS has a similar issue.)
```
ZFS_DKMS_ENABLE_DEBUG=y
ZFS_DKMS_ENABLE_DEBUGINFO=y
ZFS_DKMS_DISABLE_STRIP=y
```
