### ISSUE TITLE
nfstest_sparse fails for SEEK operations with NFS+ZFS.

### ISSUE THREAD

**Issue by pradeepthomas** [openzfs/zfs#11072]
### System information

Distribution Name	| Ubuntu
Distribution Version	| 20.04
Linux Kernel	| 5.4.0-51-generic
Architecture	| x86_64
ZFS Version	| 0.8.3-1ubuntu12.4
SPL Version	| 0.8.3-1ubuntu12.4

### Describe the problem you're observing
nfstest_sparse is part of NFSTest suite. This test fails with the following error:
```
    DBG3: 10:32:17.189694 - SEEK using SEEK_DATA on file /mnt/nfstest1/nfstest_sparse_20201014103210_f_2 starting at offset 65536
    INFO: 10:32:17.258652 - SEEK returned offset 65536
    DBG2: 10:32:17.258879 - Trace stop
    DBG2: 10:32:17.258980 - /usr/bin/sudo killall tcpdump
    DBG2: 10:32:17.289253 - /usr/bin/sudo kill 135694
    PASS: SEEK should succeed searching for the next data
    FAIL: SEEK should return correct offset when the next data is found, expecting offset 131072 but got 65536
```
[nfstest_sparse_20201014103210.log](https://github.com/openzfs/zfs/files/5388420/nfstest_sparse_20201014103210.log)

### Describe how to reproduce the problem
Run nfstest_sparse with an export backed by ZFS
```
nfstest_sparse -s <nfs-server-ip> -e /<export-name> -m /mnt/nfstest1 --createlog --tmpdir /tmp --createtraces --keeptraces -v debug --runtest seek01
```
If the test is run against an export backed by ext4, it passes.

**Comment by behlendorf** [comment]
There's a good chance this has been resolved in the latest 2.0, and 2.1 releases.  However, I have not verified that.
