### ISSUE TITLE
Null pointer dereference, RIP dmu_object_size_from_db [zfs]

### ISSUE THREAD

**Issue by rootflags** [openzfs/zfs#11076]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.1 LTS
Linux Kernel	|  5.4.0-48-generic
Architecture	| x86_64
ZFS Version	| 0.8.3-1ubuntu12.4
SPL Version	| 0.8.3-1ubuntu12.4

### Describe the problem you're observing
kernel dump, OS keeps running but some disk access blocks indefinitely waiting on I/O.

### Describe how to reproduce the problem
Unsure how to reproduce.  I detect the result when the nightly mlocate db update hangs and eventually gets killed.

### Include any warning/errors/backtraces from the system logs

```
[977070.190070] BUG: kernel NULL pointer dereference, address: 0000000000000078
[977070.190093] #PF: supervisor read access in kernel mode
[977070.190103] #PF: error_code(0x0000) - not-present page
[977070.190112] PGD 7b4df7067 P4D 7b4df7067 PUD 604c64067 PMD 0
[977070.190124] Oops: 0000 [#1] SMP NOPTI
[977070.190132] CPU: 4 PID: 3075689 Comm: Plex Media Scan Tainted: P           O      5.4.0-48-generic #52-Ubuntu
[977070.190148] Hardware name: Gigabyte Technology Co., Ltd. Z390 GAMING X/Z390 GAMING X-CF, BIOS F6 12/04/2018
[977070.190200] RIP: 0010:dmu_object_size_from_db+0x32/0x80 [zfs]
[977070.190212] Code: e5 41 55 49 89 f5 48 c7 c6 c0 00 46 c1 41 54 49 89 d4 53 48 89 fb 48 8b 7f 28 e8 79 f2 0f 00 48 8b 43 28
48 8b 90 88 00 00 00 <8b> 42 78 41 89 45 00 48 8b 4a 60 f6 41 07 01 74 2c 48 8b 41 18 48
[977070.190241] RSP: 0018:ffffaf73cca1bd18 EFLAGS: 00010246
[977070.190251] RAX: ffff98d0f3984360 RBX: ffff98d1532614b8 RCX: 0000000000000009
[977070.190264] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff98d0f3984390
[977070.190276] RBP: ffffaf73cca1bd30 R08: ffff98d16406dac0 R09: ffff98d16406dc88
[977070.190288] R10: 0000000000000800 R11: 0000000000000001 R12: ffffaf73cca1bd60
[977070.190300] R13: ffffaf73cca1bd5c R14: ffff98d5b9d54108 R15: ffff98d16406da98
[977070.190313] FS:  00007fd6272c4bc0(0000) GS:ffff98d5de300000(0000) knlGS:0000000000000000
[977070.190327] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[977070.190338] CR2: 0000000000000078 CR3: 000000050644e001 CR4: 00000000003606e0
[977070.190350] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[977070.190363] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[977070.190375] Call Trace:
[977070.190410]  sa_object_size+0x15/0x20 [zfs]
[977070.190450]  zfs_getattr_fast+0xbd/0x220 [zfs]
[977070.190489]  zpl_getattr_impl.isra.0+0x2b/0x40 [zfs]
[977070.190529]  zpl_getattr+0x12/0x20 [zfs]
[977070.190538]  vfs_getattr_nosec+0x9b/0xb0
[977070.190546]  vfs_getattr+0x37/0x50
[977070.190553]  vfs_statx+0x93/0xe0
[977070.190560]  __do_sys_newstat+0x3e/0x80
[977070.190568]  __x64_sys_newstat+0x16/0x20
[977070.190577]  do_syscall_64+0x57/0x190
[977070.190586]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[977070.190596] RIP: 0033:0x7fd62878762a
[977070.190603] Code: 00 00 75 05 48 83 c4 18 c3 e8 f2 24 02 00 66 90 f3 0f 1e fa 41 89 f8 48 89 f7 48 89 d6 41 83 f8 01 77 2d
b8 04 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 06 c3 0f 1f 44 00 00 48 8b 15 31 a8 0d 00 f7
[977070.190632] RSP: 002b:00007ffe18599838 EFLAGS: 00000246 ORIG_RAX: 0000000000000004
[977070.190646] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007fd62878762a
[977070.190658] RDX: 00007ffe18599868 RSI: 00007ffe18599868 RDI: 0000000002c67410
[977070.190670] RBP: 00007ffe18599990 R08: 0000000000000001 R09: 0033706d2e647261
[977070.190683] R10: 0000000002125010 R11: 0000000000000246 R12: 00007ffe185999c0
[977070.190695] R13: 00000000028d5b30 R14: 0000000002ace0a0 R15: 00007ffe18599928
[977070.190708] Modules linked in: cpuid ipt_REJECT nf_reject_ipv4 xt_multiport xt_MASQUERADE xt_nat xt_dscp xt_DSCP xt_hashlim
it xt_length xt_tcpudp xt_state xt_conntrack nf_log_ipv4 nf_log_common xt_LOG iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf
_defrag_ipv4 iptable_mangle iptable_filter bpfilter binfmt_misc nls_iso8859_1 si2157 lgdt3306a dm_multipath scsi_dh_rdac scsi_d
h_emc scsi_dh_alua cx231xx_dvb dvb_core cx231xx_alsa intel_rapl_msr cx25840 mei_hdcp cx231xx videobuf_vmalloc tveeprom cx2341x
zfs(PO) videobuf_core i2c_mux zunicode(PO) videodev snd_sof_pci zavl(PO) mc snd_sof_intel_hda_common icp(PO) intel_rapl_common
snd_soc_hdac_hda snd_sof_intel_hda snd_sof_intel_byt snd_sof_intel_ipc snd_sof zcommon(PO) snd_hda_codec_hdmi x86_pkg_temp_ther
mal znvpair(PO) snd_sof_xtensa_dsp intel_powerclamp snd_hda_ext_core kvm_intel spl(O) snd_soc_acpi_intel_match snd_soc_acpi zlu
a(PO) kvm snd_hda_codec_realtek snd_soc_core rapl snd_hda_codec_generic intel_cstate ledtrig_audio snd_compress
[977070.190724]  ac97_bus snd_pcm_dmaengine snd_hda_intel input_leds snd_intel_dspcfg serio_raw ir_rc5_decoder intel_wmi_thunde
rbolt wmi_bmof snd_hda_codec snd_hda_core rc_hauppauge snd_hwdep snd_pcm mceusb snd_timer rc_core snd mei_me soundcore mei ie31
200_edac intel_pch_thermal mac_hid acpi_pad sch_fq_codel coretemp ip_tables x_tables autofs4 xfs btrfs zstd_compress raid10 rai
d456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid0 multipath linear raid1 hid_generic
 usbhid hid crct10dif_pclmul i915 crc32_pclmul ghash_clmulni_intel aesni_intel crypto_simd i2c_algo_bit drm_kms_helper cryptd s
yscopyarea glue_helper sysfillrect sysimgblt ahci fb_sys_fops libahci mpt3sas e1000e drm i2c_i801 raid_class scsi_transport_sas
 wmi video pinctrl_cannonlake pinctrl_intel
[977070.190971] CR2: 0000000000000078
[977070.190978] ---[ end trace 6a62056209068c81 ]---
```

**Comment by Ornias1993** [comment]
Could you give us a short overview of your pool en vdevs?

**Comment by rootflags** [comment]
Anything else you'd like aside from this, just let me know:

``
root@nas:# zpool list -v
NAME                                                 SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
saspool                                             32.5T  15.5T  17.0T        -         -     2%    47%  1.00x    ONLINE  -
  raidz1                                            32.5T  15.5T  17.0T        -         -     2%  47.6%      -  ONLINE
    wwn-0x5000c50084217227                              -      -      -        -         -      -      -      -  ONLINE
    wwn-0x5000c50084154953                              -      -      -        -         -      -      -      -  ONLINE
    wwn-0x5000c5008417edcf                              -      -      -        -         -      -      -      -  ONLINE
    wwn-0x5000c50083b0f4ef                              -      -      -        -         -      -      -      -  ONLINE
    wwn-0x5000c50062f10857                              -      -      -        -         -      -      -      -  ONLINE
    wwn-0x5000c50062f10953                              -      -      -        -         -      -      -      -  ONLINE
logs                                                    -      -      -        -         -      -      -      -  -
  ata-KINGSTON_SUV500M8120G_50026B768258A23E-part5  3.97G   260K  3.97G        -         -     0%  0.00%      -  ONLINE
cache                                                   -      -      -        -         -      -      -      -  -
  sdh7                                              62.3G  53.6G  8.66G        -         -     0%  86.1%      -  ONLINE
ssdpool                                             1.73T   837G   939G        -         -    30%    47%  1.00x    ONLINE  -
  mirror                                            1.73T   837G   939G        -         -    30%  47.1%      -  ONLINE
    scsi-SATA_KINGSTON_SA400S3_50026B76835F52A0         -      -      -        -         -      -      -      -  ONLINE
    ata-MZ7KM1T9HMJP0D3_S3BRNX0J702208                  -      -      -        -         -      -      -      -  ONLINE
logs                                                    -      -      -        -         -      -      -      -  -
  ata-KINGSTON_SUV500M8120G_50026B768258A23E-part4  3.97G   120K  3.97G        -         -     1%  0.00%      -  ONLINE


root@nas:# zpool status
  pool: saspool
 state: ONLINE
  scan: scrub repaired 0B in 0 days 06:13:46 with 0 errors on Sun Oct 11 06:37:47 2020
config:

        NAME                                                STATE     READ WRITE CKSUM
        saspool                                             ONLINE       0     0     0
          raidz1-0                                          ONLINE       0     0     0
            wwn-0x5000c50084217227                          ONLINE       0     0     0
            wwn-0x5000c50084154953                          ONLINE       0     0     0
            wwn-0x5000c5008417edcf                          ONLINE       0     0     0
            wwn-0x5000c50083b0f4ef                          ONLINE       0     0     0
            wwn-0x5000c50062f10857                          ONLINE       0     0     0
            wwn-0x5000c50062f10953                          ONLINE       0     0     0
        logs
          ata-KINGSTON_SUV500M8120G_50026B768258A23E-part5  ONLINE       0     0     0
        cache
          sdh7                                              ONLINE       0     0     0

errors: No known data errors

  pool: ssdpool
 state: ONLINE
  scan: scrub repaired 0B in 0 days 00:59:41 with 0 errors on Sun Oct 18 07:46:48 2020
config:

        NAME                                                STATE     READ WRITE CKSUM
        ssdpool                                             ONLINE       0     0     0
          mirror-0                                          ONLINE       0     0     0
            scsi-SATA_KINGSTON_SA400S3_50026B76835F52A0     ONLINE       0     0     0
            ata-MZ7KM1T9HMJP0D3_S3BRNX0J702208              ONLINE       0     0     0
        logs
          ata-KINGSTON_SUV500M8120G_50026B768258A23E-part4  ONLINE       0     0     0

errors: No known data errors


root@nas:# zdb
saspool:
    version: 5000
    name: 'saspool'
    state: 0
    txg: 11360649
    pool_guid: 4815939149989300756
    errata: 0
    hostid: 2171838974
    hostname: 'nas'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 4815939149989300756
        create_txg: 4
        children[0]:
            type: 'raidz'
            id: 0
            guid: 9380977571506777965
            nparity: 1
            metaslab_array: 256
            metaslab_shift: 38
            ashift: 12
            asize: 36006962135040
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 129
            children[0]:
                type: 'disk'
                id: 0
                guid: 6021440414586738532
                path: '/dev/disk/by-id/wwn-0x5000c50084217227-part1'
                whole_disk: 1
                DTL: 9134
                create_txg: 4
                com.delphix:vdev_zap_leaf: 130
            children[1]:
                type: 'disk'
                id: 1
                guid: 4334613531403734382
                path: '/dev/disk/by-id/wwn-0x5000c50084154953-part1'
                whole_disk: 1
                DTL: 9133
                create_txg: 4
                com.delphix:vdev_zap_leaf: 131
            children[2]:
                type: 'disk'
                id: 2
                guid: 14584006053738849842
                path: '/dev/disk/by-id/wwn-0x5000c5008417edcf-part1'
                whole_disk: 1
                DTL: 9132
                create_txg: 4
                com.delphix:vdev_zap_leaf: 132
            children[3]:
                type: 'disk'
                id: 3
                guid: 4324762355938055560
                path: '/dev/disk/by-id/wwn-0x5000c50083b0f4ef-part1'
                whole_disk: 1
                DTL: 9131
                create_txg: 4
                com.delphix:vdev_zap_leaf: 133
            children[4]:
                type: 'disk'
                id: 4
                guid: 1562098758265529117
                path: '/dev/disk/by-id/wwn-0x5000c50062f10857-part1'
                whole_disk: 1
                DTL: 9130
                create_txg: 4
                com.delphix:vdev_zap_leaf: 134
            children[5]:
                type: 'disk'
                id: 5
                guid: 7559409801593835154
                path: '/dev/disk/by-id/wwn-0x5000c50062f10953-part1'
                whole_disk: 1
                DTL: 9129
                create_txg: 4
                com.delphix:vdev_zap_leaf: 135
        children[1]:
            type: 'disk'
            id: 1
            guid: 14941001358119271218
            path: '/dev/disk/by-id/ata-KINGSTON_SUV500M8120G_50026B768258A23E-part5'
            whole_disk: 0
            metaslab_array: 512
            metaslab_shift: 25
            ashift: 12
            asize: 4290248704
            is_log: 1
            DTL: 9128
            create_txg: 47
            com.delphix:vdev_zap_leaf: 384
            com.delphix:vdev_zap_top: 385
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
ssdpool:
    version: 5000
    name: 'ssdpool'
    state: 0
    txg: 11100216
    pool_guid: 935947498435823010
    errata: 0
    hostid: 2171838974
    hostname: 'nas'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 935947498435823010
        create_txg: 4
        children[0]:
            type: 'mirror'
            id: 0
            guid: 2042578121953488326
            metaslab_array: 256
            metaslab_shift: 34
            ashift: 12
            asize: 1920368902144
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 129
            children[0]:
                type: 'disk'
                id: 0
                guid: 5880258776544284776
                path: '/dev/disk/by-id/scsi-SATA_KINGSTON_SA400S3_50026B76835F52A0-part1'
                devid: 'ata-KINGSTON_SA400S371920G_50026B76835F52A0-part1'
                phys_path: 'pci-0000:00:17.0-ata-6'
                whole_disk: 1
                DTL: 140
                create_txg: 4
                com.delphix:vdev_zap_leaf: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 13781901281826708865
                path: '/dev/disk/by-id/ata-MZ7KM1T9HMJP0D3_S3BRNX0J702208-part1'
                whole_disk: 1
                DTL: 29023
                create_txg: 4
                com.delphix:vdev_zap_leaf: 131
        children[1]:
            type: 'disk'
            id: 1
            guid: 7369585713031252273
            path: '/dev/disk/by-id/ata-KINGSTON_SUV500M8120G_50026B768258A23E-part4'
            whole_disk: 0
            metaslab_array: 65
            metaslab_shift: 25
            ashift: 12
            asize: 4290248704
            is_log: 1
            DTL: 29022
            create_txg: 36
            com.delphix:vdev_zap_leaf: 384
            com.delphix:vdev_zap_top: 385
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

```
