### ISSUE TITLE
ZFS panic on OSX trying to delete snapshot

### ISSUE THREAD

**Issue by kneutron** [openzfs/zfs#11084]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| OSX 10.13 High Sierra
Distribution Version	| 10.13
Linux Kernel	| N/A
Architecture	| amd64
ZFS Version	| zfs-1.9.4-0 / zfs-kmod-1.9.4-0
SPL Version	|

### Describe the problem you're observing
iMac has randomly rebooted a couple of times in the last week, traced it down to a problematic ZFS snapshot

### Describe how to reproduce the problem
```
NAME                                                                             USED  REFER  MOUNTPOINT                                                                                             CREATION

zsgtera4/shrcompr-zsgt2B@zseatera4bkp-20200802001809                             207G   659G  /Volumes/zsgtera4/shrcompr-zsgt2B/.zfs/snapshot/zseatera4bkp-20200802001809                            Sun Aug  2  0:18 2020
```

# **zfs destroy zsgtera4/shrcompr-zsgt2B@zseatera4bkp-20200802001809** ## results in PANIC -- also occurs when dual-booting to Linux and trying to delete it from ZFS 0.8.4 there

panic(cpu 2 caller 0xffffff7fa6e842be): zfs: allocating allocated segment(offset=121443069952 size=90112) of (offset=121443069952 size=90112)

Note: **zpool scrub** detected no errors; this is a single-disk pool, 4TB SG NAS drive on Firewire-800

### Include any warning/errors/backtraces from the system logs

See screenshot at:

https://postimg.cc/0MKCjBzs

OR

https://i.postimg.cc/W3XYWRjh/zfs-panic-Screen-Shot-2020-10-17-at-7-57-00-PM.png

**Comment by rincebrain** [comment]
You probably wanted [this](https://github.com/openzfsonosx/zfs/issues) issue tracker.

**Comment by Ornias1993** [comment]
@rincebrain agreed, maybe also just tag @lundman

**Comment by lundman** [comment]
You can set zfs_recovery=1 to allow the destroy to complete:

```sysctl kstat.zfs.darwin.tunable.zfs_recover=1```

Possibly adding it to `/etc/zfs/zsysctl.conf` if you need it on permanently.

**Comment by kneutron** [comment]
> sysctl kstat.zfs.darwin.tunable.zfs_recover=1

--Thanks so much! That appears to have fixed the issue.  I backed up the disk/pool JIC and had to boot with the disk powered down because the system kept resetting itself.

--I have a borked internal 1TB disk and have to run from the USB Samsung T5, thank God for Carbon Copy Cloner.  After the OSX finally booted OK:

```
DBP=/var/run/disk/by-path
zpool import -d $DBP zsgtera4
sysctl kstat.zfs.darwin.tunable.zfs_recover=1
zfs destroy ## bad snapshotname == OK
```

--If this saved me from having to destroy the pool and recreate it, much thanks!!

**Comment by Ornias1993** [comment]
@kneutron You can close the issue now I think, its the big bad button ;)
