### ISSUE TITLE
Fedora repodata Download Fails with a 403

### ISSUE THREAD

**Issue by JStefanikIBM** [openzfs/zfs#11089]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.8.15-201
Architecture	| s390x
ZFS Version	| N/A
SPL Version	| N/A

### Describe the problem you're observing
When attempting to install zfs with dnf following the documentation found here:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html

dnf fails, reporting the following error:
Errors during downloading metadata for repository 'zfs':
  - Status code: 403 for http://download.zfsonlinux.org/fedora/32/s390x/repodata/repomd.xml (IP: 52.218.204.32)
Error: Failed to download metadata for repo 'zfs': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: zfs
 

### Describe how to reproduce the problem
Add the zfs repo using:
```sudo dnf install http://download.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm```

Attempt to install zfs using:
```sudo dnf install zfs```

**Comment by behlendorf** [comment]
The repository only provides packages for the x86_64 architecture.  You'll need to locally compile package for the s390x architecture.

```
Packages are available for the following configurations:

Fedora Releases: 30, 31, 32
Architectures: x86_64
```

**Comment by JStefanikIBM** [comment]
Ah, that would explain it.  Although I do find it odd that it returns a 403 instead of 404.

I'll close this issue.  Thanks!
