### ISSUE TITLE
Null pointer dereferences, general protection faults, soft lockups and hung tasks after forced reboot

### ISSUE THREAD

**Issue by haarp** [openzfs/zfs#11092]
Hello,

first, the important question: The pool is obviously fscked and I'm going to nuke it and start over. Before I do that, should I go through the trouble of diagnosing things further? i.e. Is ZFS failing on borked pools considered a bug, or a simply a lost cause?

### System information
Type | Version/Name
 --- | ---
Distribution Name	| Debian Linux
Distribution Version	| 10
Linux Kernel	| 4.19.0-11-amd64
Architecture	| amd64
ZFS Version	| 0.8.4-2~bpo10+1
SPL Version	| 0.8.4-2~bpo10+1

### Describe the problem you're observing
After running into #3461, **all** ZFS-related commands were hopelessly getting stuck, even those concerning unrelated pools only. This forced me to reset the machine. Since then, I am constantly getting null pointer dereferences, general protection faults, soft lockups, hung tasks and other nasties. Another reboot allows the machine and pool to work again, until another such bug is triggered.

### Describe how to reproduce the problem
I don't know how to get the pool into such a state in the first place.

But I think I can trigger the kernel problems. I suspect it's related to snapshots. I can create/send/receive them just fine, but it seems accessing the data behind one seems to trigger it. I need to do further testing to confirm, but won't do it if there's no interest.

### Include any warning/errors/backtraces from the system logs
Too much log to provide inline. I'm providing pastebin links. I have three flavors to choose from:

[Null pointer dereference](https://nopaste.xyz/?77a045ac27cfa6aa#62wnuQLAHgxpGEKg2T49BtpKQZrKu7opDxpgzfjiq1kv)
[General protection fault & soft lockup](https://nopaste.xyz/?6fbdde4b84f4b0a5#GYvi88wfWmJLPQpk1TYbcSse2VC1zzUAjZL5fmwq5H8a)
[Hung task](https://nopaste.xyz/?144e66994c7df703#3Pjdbt2KmxQp4nCVyNFgzx7GXyfwt5MXSjwrSgAKVYTA )

Thanks!

**Comment by adamdmoss** [comment]
I think the hung task is just a symptom of something that went wrong a lot earlier.  The other traces are interesting but they don't look familiar to me FWIW.

**Comment by haarp** [comment]
What triggered the hung tasks yesterday doesn't seem to do anything today, so it seems you're right. I don't know how to reproduce whatever went wrong beforehand, but it does happen randomly and frequently.

Is there a way to figure out from the logs which pool is affected?

**Comment by haarp** [comment]
Abandoned, I don't have the affected pool anymore.
