### ISSUE TITLE
'configure' fails on Kernel 5.8 with no module support

### ISSUE THREAD

**Issue by morian** [openzfs/zfs#11107]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Linux Kernel	| 5.8+
Architecture	| amd64
ZFS Version	| 0.8.6-staging, 2.0.0-rc4

### Describe the problem you're observing

Configure fails when used in builtin mode for Linux 5.8 and 5.9 when those have no support for loadable modules.
It works on Linux 5.7 and lower with the same ZFS versions mentioned earlier.
The command I use:
```console
$ ./configure --with-linux=/path/to/linux-stable.git --enable-linux-builtin
[...]
checking kernel source directory... /path/to/linux-stable.git
checking kernel build directory... /path/to/linux-stable.git
checking kernel source version... 5.8.16
checking kernel file name for module symbols... NONE
checking whether modules can be built... no
configure: error: 
	*** Unable to build an empty module.
	*** Please run 'make scripts' inside the kernel source tree.
```

### Include any warning/errors/backtraces from the system logs

Here is the extract of `config.log`:
```
configure:49874: checking whether modules can be built
configure:49935: 
      KBUILD_MODPOST_NOFINAL= KBUILD_MODPOST_WARN=
      make modules -k -j8 -C /path/to/linux-stable.git 
      M=/path/to/zfs.git/build/conftest >build/conftest/build.log 2>&1
configure:49938: $? = 2
configure:49941: test -f build/conftest/conftest.o
configure:49944: $? = 1
configure:49952: result: no
configure:49959: error: 
  *** Unable to build an empty module.
  *** Please run 'make scripts' inside the kernel source tree.
```

More interestingly, here is the content of `build/conftest/build.log`:
```
make: Entering directory '/path/to/linux-stable.git'
make[1]: *** No rule to make target '/path/to/zfs.git/build/conftest/modules.order', needed by '/path/to/zfs.git/build/conftest/Module.symvers'.
WARNING: Symbol version dump "Module.symvers" is missing.
         Modules may not have dependencies or modversions.
make[1]: Target '__modpost' not remade because of errors.
make: *** [Makefile:1665: modules] Error 2
make: Leaving directory '/path/to/linux-stable.git'
```

### Further analysis in kernel changes

Of course this sudden breakage cannot be attributed to ZFS but this has a direct impact when you want to compile ZFS in a standalone kernel.
I did a little bisect in the kernel sources between 5.7 and 5.8 and found that the following commit is responsible:
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=436b2ac603d58504f38041a0cd8adb5aeace992b

It seems to be part of a bigger refactoring around modpost performed by Masahiro Yamada (@masahir0y).

There may be a workaround but honestly I don't fully understand what really causes this issue.

**Comment by masahir0y** [comment]
I tried zfs configure against v5.8.16 kernel,
which was built with x86_64 defconfig.

At least, I did not observe the build system error you reported
although I was hit with a different kind of issue.

    masahiro@oscar:~/ref/zfs$ ./configure --with-linux=/home/masahiro/ref/linux-stable --enable-linux-builtin
    [ snip ]
    checking makedev() is declared in sys/sysmacros.h... yes
    checking makedev() is declared in sys/mkdev.h... no
    checking for issetugid... no
    checking for mlockall... yes
    checking for strlcat... no
    checking for strlcpy... no
    checking kernel source directory... /home/masahiro/ref/linux-stable
    checking kernel build directory... /home/masahiro/ref/linux-stable
    checking kernel source version... 5.8.16
    checking kernel file name for module symbols... NONE
    checking whether modules can be built... yes
    checking for kernel config option compatibility... done
    checking whether kernel was built with 16K or larger stacks... yes
    checking whether mutex_lock() is GPL-only... no
    checking whether CONFIG_TRIM_UNUSED_KSYM is disabled... yes
    checking whether CONFIG_ZLIB_INFLATE is defined... yes
    checking whether CONFIG_ZLIB_DEFLATE is defined... yes
    checking whether fpu headers are available... asm/fpu/api.h
    [ snip ]
    masahiro@oscar:~/ref/zfs$ ls build/conftest/
    build.log  conftest.c  conftest.h  conftest.mod  conftest.o  Makefile  modules.order

build/conftest/modules.order was correctly created.

Instead, I saw an incompatible license error.
This is expected because build/conftest/conftest.c
has MODULE_LICENSE("CDDL").

    masahiro@oscar:~/ref/zfs$ cat  build/conftest/build.log 
    make: Entering directory '/home/masahiro/ref/linux-stable'
      CC [M]  /home/masahiro/ref/zfs/build/conftest/conftest.o
      MODPOST /home/masahiro/ref/zfs/build/conftest/Module.symvers
    FATAL: modpost: GPL-incompatible module conftest.ko uses GPL-only symbol 'trace_event_raw_init'
    make[1]: *** [scripts/Makefile.modpost:111: /home/masahiro/ref/zfs/build/conftest/Module.symvers] Error 1
    make[1]: Target '__modpost' not remade because of errors.
    make: *** [Makefile:1665: modules] Error 2
    make: Leaving directory '/home/masahiro/ref/linux-stable'
    masahiro@oscar:~/ref/zfs$ grep MODULE_LICENSE  build/conftest/conftest.c
    		MODULE_LICENSE("CDDL");

**Comment by morian** [comment]
@masahir0y: I was able to see this but this too when using a default kernel configuration, and this seems to be related to the normal checks performed by the configure script (perhaps `checking whether detailed kmem tracking is enabled` which is the last one executed), and the result is `no` then.

To reproduce the original issue here you need to turn off module loading support on the target kernel configuration.
This creates a weird situation where you ask the kernel build system to build kernel modules while modules are disabled but this is how it's done when configuring ZFS before using its `copy-builtin` script.

The final goal here is to create a single kernel binary with builtin ZFS support, then used to boot specific machines or VMs.

**Comment by HGuillemet** [comment]
Juste a note for people facing this error: as a workaround, you can activate temporarily the support for modules in the kernel, then run the ZFS configure and copy-builtin, then disable the module support and compile the kernel with ZFS builtin.

**Comment by masahir0y** [comment]
You cannot build external modules when CONFIG_MODULES is disabled. So, this is the correct behavior on the kernel side. This project is doing something fishy.

Also, Linux kernel with built-in ZFS is questionable.
https://www.fsf.org/licensing/zfs-and-linux

**Comment by morian** [comment]
This used to be supported by ZFS with Linux 5.7, it was just broken along the way to 5.8, even though I understand that this was probably a hackish way to do it.

On the legal aspect, I do not distribute any built kernel and just use them on some personal machines, which is the only way we should be linking both against each other (for private use).

Now I can follow the advice provided by @HGuillemet but I would like to know whether this is something ZFS plans to support for those new kernels or if this will be discontinued / not worth supporting anymore.
