### ISSUE TITLE
Is it acceptable to pull in `nasm` as a build dependency?

### ISSUE THREAD

**Issue by AttilaFueloep** [openzfs/zfs#11109]
### Ask your question!

While trying to speedup AES-GCM using SSE, I found some promising [assembler code](https://github.com/intel/intel-ipsec-mb). which should be relatively easy to port to the ICP. The major problem is that this code is written for the `nasm` assembler and makes heavy use of macros etc. Porting this to GNU `as` would require substantial work, if possible at all. I think I've two options to proceed:

1.) Pull in `nasm` as a new build dependency and use it inside the zfs source tree.

2.) Use `nasm` inside the intel tree to create object files and disassemble them to GNU `as` syntax using [`objconv`](https://www.agner.org/optimize/#objconv) Those generated files could then be imported to the zfs tree.

I tested option 2.) and it actually works (with a bit of tweaking) but creates really large and unreadable assembler files since all macros, loops etc. are expanded. So I think option 1.) would be the preferred one.

I'd appreciate any feedback which option would be the preferred one.

### Which portion of the codebase does your question involve?

Build system and ICP.

**Comment by gdevenyi** [comment]
I suspect asm code will not be acceptable due to not supporting multiple architectures.

**Comment by AttilaFueloep** [comment]
Are you sure? There already is x86, arm and other assembler code in place to speed up checksums, raidz calculations and encryption. And the ICP is Linux only anyhow, or am I wrong?

**Comment by lundman** [comment]
I use ICP on both macOS and Windows. But as both are (will be) compiled with clang, what's in the tree just works. I do not know what nasm has in terms of support on either.

**Comment by AttilaFueloep** [comment]
Good to know, did you integrate #9749? I guess not. Regarding [`nasm`](https://en.wikipedia.org/wiki/Netwide_Assembler), yes it's available on [Windows 32/64](https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/) and [macOS](https://brewinstall.org/install-nasm-on-mac-with-brew/).

**Comment by lundman** [comment]
I have not yet, but if changes uses simd_x86.h/asm_linkage.h then they should just work - the hard parts are in there :)

**Comment by AttilaFueloep** [comment]
IRC only partly, but that shouldn't be hard to change. I'll have a look.

**Comment by AttilaFueloep** [comment]
@behlendorf Any opinion on this? `nasm` is available on pretty much any platform, FreeBSD, Illumos, Mac OS,and Windows at least.

**Comment by behlendorf** [comment]
As long as we made sure it was implemented in such a way that it could be easily disabled.  For example when `nasm` isn't available for whatever reason, I think this would be fine.

**Comment by AttilaFueloep** [comment]
Yes, doing a configure check for nasm/yasm and compiling the code only if available is the way to go.
