### ISSUE TITLE
Add a repo for Fedora 33

### ISSUE THREAD

**Issue by rabin-io** [openzfs/zfs#11119]
### Describe the feature would like to see added to OpenZFS

Add a repo for fedora 33.

F33 is using the 5.8 kernel (5.8.16-300.fc33)

**Comment by tonyhutter** [comment]
Please give it a try:
http://download.zfsonlinux.org/fedora/zfs-release.fc33.noarch.rpm

**Comment by gogi983** [comment]
> Please give it a try:
> http://download.zfsonlinux.org/fedora/zfs-release.fc33.noarch.rpm

Can you add "zfs-testing" repo for Fedora 33 too please?
Thanks a lot.

**Comment by rabin-io** [comment]
Thx, 

Just a quick update from my end, I was able to upgrade my F32 system without any problems.
and the module has compiled and my pool is working.

Thx, again.
