### ISSUE TITLE
zpool import mirror with multipath devices leads to UNAVAIL device (with high latency devices)

### ISSUE THREAD

**Issue by Thoro** [openzfs/zfs#11111]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS 7
Distribution Version	| 
Linux Kernel	| 5.4.60
Architecture	| x64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

### Describe the problem you're observing
Setup is as follows:

2 multipath devices with iSCSI (high latency > 10ms, low throughput < 20 mbit), both are added to a zpool mirror, after export and import with 

```
/sbin/zpool import -N -d /dev/mapper/v-55e18e36-0d33-4dcf-b985-968ca78cf957-0 -d /dev/mapper/v-55e18e36-0d33-4dcf-b985-968ca78cf957-1 v-55e18e36-0d33-4dcf-b985-968ca78cf957
```
zpool status reports 

```
  pool: v-55e18e36-0d33-4dcf-b985-968ca78cf957
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
        invalid.  Sufficient replicas exist for the pool to continue
        functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: scrub repaired 0B in 0 days 00:00:02 with 0 errors on Mon Oct 26 13:04:47 2020
config:

       	NAME                                          STATE     READ WRITE CKSUM
        v-55e18e36-0d33-4dcf-b985-968ca78cf957        DEGRADED     0     0     0
          mirror-0                                    DEGRADED     0     0     0
            18438868803837872745                      UNAVAIL	   0     0     0  was /dev/mapper/v-55e18e36-0d33-4dcf-b985-968ca78c
f957-0
            v-55e18e36-0d33-4dcf-b985-968ca78cf957-1  ONLINE	   0     0     0

errors: No known data errors
```

Could the high latency devices be the issue? (I'm testing via VPN connection)

### Describe how to reproduce the problem

- Connect 2 iSCSI devices with multipath devices (high latency devices (> 10ms))
- Create a mirror zfs pool ( zpool create -o ashift=9 -m none  v-55e18e36-0d33-4dcf-b985-968ca78cf957 mirror /dev/mapper/v-55e18e36-0d33-4dcf-b985-968ca78cf957-0 /dev/mapper/v-55e18e36-0d33-4dcf-b985-968ca78cf957-1)
- Export the pool (zfs export v-55e18e36-0d33-4dcf-b985-968ca78cf957)
- Reimport the pool (zfs import -N -d /dev/mapper v-55e18e36-0d33-4dcf-b985-968ca78cf957)

### Include any warning/errors/backtraces from the system logs

Edit: should work according to here: https://openzfs.org/wiki/ZFS_on_high_latency_devices  .. says 100ms + devices, I only got 10 ms

**Comment by gdevenyi** [comment]
This sounds like the multipath is failing the device path? Perhaps the multipath config needs to be adjusted to not fail so readily.

**Comment by Thoro** [comment]
multipath is definitly not failing - it's also set to queue_if_fail

There's also no messages on dmesg.

A zfs scrub brings the missing volume back online.

**Comment by Thoro** [comment]
This also happens with storage devices in the same network mounted via iSER (100G infiniband) - so can't be a latency issue.

**Comment by Thoro** [comment]
I believe I actually have figured out why it is happening: (I was not aware this might be relevant!)

the two iSCSI volumes are provided from different storage, one storage is a ZPOOL and therefore a ZVOL, the other storage is LVM.

The volume from the ZPOOL is consistently unavailable.

Based on what I know about zvols they should be just block storage and if shared via iSCSI should behave like a normal volume. What causes zpool import to not like the zvol volume? Maybe some timing issue connected to sync commit or similar?

**Comment by Thoro** [comment]
Following the revelation I tried now to import / create a pool with 2 zvol disks, the creation works, but the import fails with

```
/sbin/zpool import -N -d /dev/mapper/v-04152274-afa0-4c14-bc2c-80510e9b80fb-0 -d /dev/mapper/v-04152274-afa0-4c14-bc2c-80510e9b80fb-1 v-04152274-afa0-4c14-bc2c-80510e9b80fb
cannot import 'v-04152274-afa0-4c14-bc2c-80510e9b80fb': block size out of range or does not match
	Destroy and re-create the pool from
	a backup source.
```

When checking the blocksize for both disks:

```
blockdev --getsize64 /dev/mapper/v-04152274-afa0-4c14-bc2c-80510e9b80fb-0
100007936
blockdev --getsize64 /dev/mapper/v-04152274-afa0-4c14-bc2c-80510e9b80fb-1
100007936
```

volblocksize is set to 128K on both zvols

This might be connected to #11087
