### ISSUE TITLE
openzfs 2.0 rc5: znvpair: module license 'CDDL' taints kernel.

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#11157]
Since today I am using 

```
zfs-dkms-rc 2.0.0_rc5-1
zfs-utils-rc 2.0.0_rc5-1
```

on my Arch based system with kernel 5.9.3. With this I see a new "taints kernel" message in the log:

`kernel: znvpair: module license 'CDDL' taints kernel.`

While with zfs 0.8.5 there was a taint message for the `zlua` module:

`kernel: zlua: module license 'MIT' taints kernel.`

`zlua` is loaded for zfs 2.0 rc5 as well, but not tainting the kernel anymore. 
And why is `znvpair` tainting the kernel now with zfs 2.0 rc5 ?

**Comment by behlendorf** [comment]
The kernel taint message is printed once when the first non-GPL module license is loaded.  This used to occur for the `zlua` module because it used an unexpected license string,.  This was fixed in 6867d00 which is part of -rc5 so the warning message simply shifted to the next module being loaded.
