### ISSUE TITLE
RFC: rename the zpool_influxdb command

### ISSUE THREAD

**Issue by snajpa** [openzfs/zfs#11156]
### Describe the problem you're observing

Firstly, I'm really sorry I'm coming with this now, that https://github.com/openzfs/zfs/pull/10786 has been merged; but I've mised the (arguably tiny) window for reviews for that, so here we are...

The problem I'm having:

I've been using ZFS for years, some of the commands are so deeply embedded in my muscle memory and I would say I'm not alone in this... so it would be best if we could avoid changes upsetting this equilibrium :-D

For years, I've been typing this, when I wanted to get the status of zpool:

```zpo<tab>status```

... and it has always worked on all the platforms supported by OpenZFS.

But now, that the `zpool_influxdb` command has been merged and since it installs to globally accessible directory within common $PATH settings, it just irks me, but really badly.

So I would like to propose a change, which will fix this.

Looking at the PR, where the command got merged, I think the best course of action would be rewiring the logic directly under `zpool` command, my best bet would be a new `zpool monitor` subcommand, where I'd be for having a `-i` switch, which would produce the format needed for InfluxDB.

Then we could have `-p` for Prometheus, etc.

I was thinking whether to send this as a PR directly, but I think I would like to discuss this first, before I invest some real time into this :slightly_smiling_face:

What do others think?

@richardelling as the author of the original PR, would you have any problem with me rewiring this under the `zpool` command directly? Or is there some caveat I'm overlooking, which prevented you to do that in the first place? Thx! ;)

**Comment by behlendorf** [comment]
That's a good point about breaking tab completion of the `zpool` command.  There's years of muscle memory there and I can easily see that becoming a real annoyance.  @snajpa if you're volunteering to do the work to convert it to a proper subcommand I personally wouldn't have any objection.  Since this command isn't part of the 2.0 release now would be the time to do it.

**Comment by snajpa** [comment]
So it ended up being easier to rewire it as `monitor-influxdb` subcommand, we can add `monitor-prometheus` and such later :)
