### ISSUE TITLE
Over time my short hand links have changed to UUID

### ISSUE THREAD

**Issue by MasterCATZ** [openzfs/zfs#11161]
[zpoolstatus.txt](https://github.com/openzfs/zfs/files/5497337/zpoolstatus.txt)
[zdb.txt](https://github.com/openzfs/zfs/files/5497338/zdb.txt)

their used to be shorthand names going from ZFSB1 - ZFSB15  but over time they kept changing over to 

dm-uuid-mpath-3500XXXX 

now only ZFSB15 remains still short hand 
I need to replace dm-uuid-mpath-35000c500500aa357 that should be ZFSB13 

I have updated my multipath with the new wwid 

multipath {
            wwid    35000cca234e04df1
            alias   ZFSB13

is their anyway to get zfs working with the shorthand names again ?  
I have noticed the /etc/mapper/WWID file no longer exists this might be the root cause but ZFSB15 still is shorthanded

sudo zpool replace ZFS3WAY ZFSB13
cannot open 'ZFSB13': no such device in /dev
must be a full path or shorthand device name

sudo zpool replace ZFS3WAY dm-uuid-mpath-35000c500500aa357 dm-uuid-mpath-35000cca234e04df1
cannot open 'dm-uuid-mpath-35000cca234e04df1': no such device in /dev
must be a full path or shorthand device name

sudo zpool replace ZFS3WAY dm-uuid-mpath-35000c500500aa357 /dev/mapper/ZFSB13

would I have to do something like this on all of the others ? or is their a way to update the paths ?

Distribution Name	| Ubuntu
Distribution Version	| 20.04.1 LTS
Linux Kernel	| 5.8.16-050816-generic
Architecture	|
ZFS Version	| zfs-0.8.1-1
SPL Version	|

modinfo zfs |   2.0.0-rc1_55_g8e7fe49b2

modinfo spl |  2.0.0-rc1_55_g8e7fe49b2

### Describe the problem you're observing
short hand names changed at some stage over the last year while going from Ubuntu 19 - 20 
### Describe how to reproduce the problem
re-importing pool with broken kernels

**Comment by IvanVolosyuk** [comment]
What about:
zpool export pool
zpool import -d /dev/path-for-you-shortnames pool

**Comment by MasterCATZ** [comment]
Perfect
Thank You very much 
now I can quickly identify what bay they are in again
