### ISSUE TITLE
Deleted file (through NFS) not freeing up space, busy after unexport

### ISSUE THREAD

**Issue by JanMatas** [openzfs/zfs#11163]
### System information

Type | Version/Name
 --- | ---
Distribution Name | Ubuntu
Distribution Version | 20.04.1 LTS
Linux Kernel|Linux version 5.4.0-1025-aws
Architecture|x86_64
ZFS Version|0.8.3-1ubuntu12.4
SPL Version|0.8.3-1ubuntu12.4

### Describe the problem you're observing
Hi, 

we are seeing a bit of a weird issue that sometimes, non deterministically, files that are stored in ZFS do not free space after deletion. Those files are exported through NFS, through which we also delete the file, after which we expect the space to be freed.

### Describe how to reproduce the problem

1. We export a ZFS dataset via NFS with the following options: `(rw,async,wdelay,hide,nocrossmnt,secure,no_root_squash,no_all_squash,no_subtree_check,secure_locks,acl,no_pnfs,anonuid=65534,anongid=65534,sec=sys,rw,secure,no_root_squash,no_all_squash)` on path `/projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63`
1. We run `cp 1mb 1mb.copy && rm 1mb.copy` (where 1mb is just a file with 1mb of random data) repeatedly on NFS client in the mounted directory.
1. We observe `df` on the specific mountpoint going up, while `du` stays constant. Note that ~10% of the invocations of the command cp + rm command fail to free up space. **Note the difference in df (418M) and du (21M)** produced after running the command in the loop for a while.
```
# df -h .
Filesystem                                            Size  Used Avail Use% Mounted on
projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63  5.0G  418M  4.6G   9% /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
```
```
root@ip-172-2-193-144:/projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63# du -hs .
21M	.
```
4. On ZFS server, we "unexport" the dataset successfully in hope that NFS created some data that was not freed properly. We verify that dataset was unexported:
`cat /var/lib/nfs/etab | grep fda0b598` - returns nothing
`lsof | grep fda0b598` - nothing in lsof
Also, `fuser` shows nothing: 
```
# fuser -v /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
                     USER        PID ACCESS COMMAND
/projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63:
                     root     kernel mount /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
``` 
5. The result in `df` and `du` did not change by unexporting. 
6. We try to unmount the dataset, which fails with target is busy. We checked lsof on NFS client, there was nothing open. We restarted the client just to be sure, there was still nothing open, but the target was still busy. 
```
# zfs unmount -f  projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
umount: /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63: target is busy.
cannot unmount '/projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63': umount failed
```
We apologize if this is more likely an NFS issue. The problematic behaviour is that file operations are leaving behind data for indefinite periods of time that is filling up quotas. We hoped that remount of dataset will help, but that does not seem possible. Any advice on how to debug this would be greatly appreciated! Specifically, is there any way to find out what is taking up space and what is preventing it from being freed?

**Comment by Rydako** [comment]
I had a similar issue recently on ubuntu 20.10/zfs 0.8.4. 

A restart cleared up whatever was preventing the space from being seen as freed up in zfs.

I'll be open for testing if needed as well - was planning on playing around this weekend and opening an issue if i thought it was zfs related.

**Comment by jstastny** [comment]
I am colleague of @JanMatas and as a followup to the investigation described in the initial post, we have restarted the NFS service on the server this morning (in low traffic time) with `service nfs-kernel-server restart`.  This has reclaimed the free space:
```
# df -h .
Filesystem                                            Size  Used Avail Use% Mounted on
projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63  5.0G  418M  4.6G   9% /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
# service nfs-kernel-server restart
# df -h .
Filesystem                                            Size  Used Avail Use% Mounted on
projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63  5.0G   22M  5.0G   1% /projects-pool/p-fda0b598-f9b5-4136-a51d-fd90922b7b63
```

While this has confirmed our biggest suspect, which was NF, this is an operation we cannot afford to make -- as it causes downtime to our NFS clients.

Is anybody aware of either 
-  a way to restart / force NFS to release these "stale handles" (or whatever is keeping our space allocated) without actual downtime to NFS service
- way to even detect this
- or ideally way to completely avoid this...

Thanks a lot for any inputs!

**Comment by dkobras** [comment]
This issue has been closed as stale years ago, but the behavior still shows with current ZoL versions:

When the NFSv4.x client decides to close the file that has been unlinked elsewhere in the meantime, it issues a COMPOUND with the following ops:

```
SEQUENCE
PUTFH
GETATTR
CLOSE
```

The PUTFH results in a call to `zpl_fh_to_dentry()`, which return ESTALE because of the file's unlinked state. This behavior is specific to ZFS, whereas the call succeeds for other Linux filesystems (see #18699).

Due to the error, knfsd terminates COMPOUND processing at the PUTFH stage. In particular, the final CLOSE is never evaluated, and the filecache entry for this file is never reaped as long as the NFS client remains (either as an active, or as a courtesy client). Hence, the filesystem cannot free up the allocated space for this file because the filecache still holds an active reference.
