### ISSUE TITLE
Question about "Log Space Map Obsolete Entry Statistics"

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#11177]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| EndeavourOS
Distribution Version	|
Linux Kernel	|5.9.4-arch1-1
Architecture	|x86_64
ZFS Version	|2.0.0-rc5
SPL Version	|2.0.0-rc5

### Describe the problem you're observing

Now that I moved to zfs 2.0.0 rc5 and upgraded my pools I want to revisit the "space map refcount mismatch" topic which I have already mentioned here a long while ago:
https://github.com/openzfs/zfs/issues/7204

Although this refcount mismatch is not a problem I consider it a cosmetic issue ;-)

With zfs 2.0.0-rc5 I get additional output on the topic when running `zdb -m`:

```
Log Space Map Obsolete Entry Statistics:
4        valid entries out of 73       - txg 39438022
2        valid entries out of 59       - txg 39438023
7        valid entries out of 66       - txg 39438025
6        valid entries out of 69       - txg 39438026
8        valid entries out of 63       - txg 39438027
7        valid entries out of 61       - txg 39438028
11       valid entries out of 56       - txg 39438029
21       valid entries out of 63       - txg 39438030
21       valid entries out of 60       - txg 39438032
22       valid entries out of 61       - txg 39438033
27       valid entries out of 59       - txg 39438034
46       valid entries out of 76       - txg 39438035
43       valid entries out of 73       - txg 39438036
42       valid entries out of 69       - txg 39438037
38       valid entries out of 58       - txg 39438039
52       valid entries out of 66       - txg 39438040
44       valid entries out of 57       - txg 39438041
56       valid entries out of 67       - txg 39438042
50       valid entries out of 57       - txg 39438043
47       valid entries out of 56       - txg 39438044
67       valid entries out of 67       - txg 39438045
59       valid entries out of 59       - txg 39438046
64       valid entries out of 64       - txg 39438047
63       valid entries out of 63       - txg 39438048
807      valid entries out of 1522     - total

space map refcount mismatch: expected 284 != actual 260
```
Is there anything I can do to clean things up? Is this new info helping?

**Comment by ahrens** [comment]
> I get additional output on the topic

`Log Space Map Obsolete Entry Statistics` is simply additional information, unrelated to `space map refcount`, and does not indicate any problem.  You can read more about the Log Space Map here: https://github.com/openzfs/zfs/pull/8442

**Comment by mabod** [comment]
Thanks. This is good info.
