### ISSUE TITLE
[FreeBSD] OpenZFS kmod fails to load after 12.2-RELEASE upgrade

### ISSUE THREAD

**Issue by tomoyat1** [openzfs/zfs#11180]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 12.2-RELEASE
Architecture	| x86_64
ZFS Version	| 2.0.0-rc5

### Describe the problem you're observing
After upgrading to FreeBSD 12.2-RELEASE, the openzfs kmod does not load on boot.

### Describe how to reproduce the problem
1. Install FreeBSD 12.1-RELEASE
1. `pkg install openzfs` ... This should install version `2020110200` of openzfs and openzfs-kmod
1. `freebsd-update upgrade -r 12.2-RELEASE`
1. reboot (to finish the FreeBSD upgrade)

### Include any warning/errors/backtraces from the system logs

Right after the kernel loads the following is outputed. 
```
link_elf_obj: symbol vm_page_max_wired undefined
KLD file openzfs.ko - could not finalize loading
```

**Comment by freqlabs** [comment]
This is a general issue with kmods in the FreeBSD pkg repo. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250700#c1

**Comment by freqlabs** [comment]
As a workaround, you can install it from the ports tree.
