### ISSUE TITLE
Packages for EL7.9

### ISSUE THREAD

**Issue by Reamer** [openzfs/zfs#11197]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.8 (current) -> 7.9
Linux Kernel	| 3.10.0-1127.19.1.el7.x86_64 (current) -> 3.10.0-1160.2.2.el7
Architecture	| x86_64
ZFS Version	| 0.8.5-1
SPL Version	| 0.8.5-1

### Describe the problem you're observing
The latest minor CentOS updates require new ZFS kmod packages. At the moment they are not yet available according to the documentation.

### Describe how to reproduce the problem

At the moment I do not have a test machine available to check if the current 7.8 kmod packages work with the kernel of 7.9. Therefore I am currently running with the 7.8 kernel.

Please upload new 7.9 zfs packages or update the documentation if 7.8 packages run with 7.9.

**Comment by behlendorf** [comment]
@Reamer thanks for the reminder.  A new repository has been added for 7.9 with new packages.  Documentation will be updated shortly.

**Comment by Reamer** [comment]
It works, thanks for your quick help.
