### ISSUE TITLE
PR involvement

### ISSUE THREAD

**Issue by georgeyil** [openzfs/zfs#11192]
### Ask your question!

I wonder if the below PR's are involved in 0.8.x or will be involded in the 2.0 release. I apologize if I miss them in the commit logs.

#10163
#10099
#10067
#10184

### Which portion of the codebase does your question involve?
zvol and zfs send/receive

**Comment by behlendorf** [comment]
All of the PRs you mentioned will be in included in the 2.0 release.  None have been backported to the 0.8 releases.
