### ISSUE TITLE
degradation with bootfs after commit https://github.com/openzfs/zfs/commit/7b4e27232dec4595ef842ce7c0e31aafd255a20a

### ISSUE THREAD

**Issue by ikozhukhov** [openzfs/zfs#11228]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| DilOS
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	|
SPL Version	|

### Describe the problem you're observing
we are using BEADM = Boot Environment Adm with rpool and manage boot process with bootfs snapshots.

i try to port https://github.com/openzfs/zfs/commit/7b4e27232dec4595ef842ce7c0e31aafd255a20a to DilOS and have found degradations with test rpoolpool - it's possible rename primary boot dataset and it is big danger.

### Describe how to reproduce the problem

```
root@zfs-t1:~# beadm list
BE                                               Active Mountpoint Space Policy Created
dilos_2011090914                                 -      -          2.30M static 2020-11-09 20:17
dilos_2.0.2.74                                   -      -          3.62M static 2020-11-09 23:46
dilos_2.0.2.74-20201110-1-0-int2-mm              -      -          2.63M static 2020-11-11 02:05
dilos_2.0.2.74-20201111-1-0-int2-zfs-v5          -      -          2.54M static 2020-11-12 02:30
dilos_2.0.2.75-20201116-1-0-int2-zfs2            -      -          2.88M static 2020-11-16 01:41
dilos_2.0.2.75-20201116-2-0-int2-zfs2            -      -          2.79M static 2020-11-16 10:29
dilos_2.0.2.75-20201117-1-0-int2-zfs2-t2         -      -          2.68M static 2020-11-17 21:13
dilos_2.0.2.75-20201117-2-0-int2-zfs2-t2         -      -          2.49M static 2020-11-17 22:53
dilos_2.0.2.75-loader                            -      -          2.46M static 2020-11-17 23:36
dilos_2.0.2.75-20201117-3-0-int2-zfs2-t2         -      -          2.47M static 2020-11-17 23:53
dilos_2.0.2.75-20201118-1-0-int2-zfs2-t2         -      -          2.92M static 2020-11-18 11:03
dilos_2.0.2.76                                   -      -          2.99M static 2020-11-18 18:34
dilos_2.0.2.76-20201120-1-0-int2-zfs2-wait       -      -          3.01M static 2020-11-20 14:14
dilos_2.0.2.76-20201120-3-0-int2-zfs2-wait-limit -      -          3.09M static 2020-11-20 22:22
dilos_2.0.2.76-20201122-1-0-int2-zfs2-rename     NR     /          3.16G static 2020-11-22 03:11

root@zfs-t1:/var/tmp/test_results/20201122T031835/rootpool/rootpool_003_neg# cat merged
ASSERTION: system related filesystems can not be renamed or destroyed

ERROR: zfs rename rpool/ROOT/dilos_2.0.2.76-20201122-1-0-int2-zfs2-rename rpool/newfs unexpectedly exited 0
```

this operation shouldn't be possible if we are booted from activated bootfs dataset

**Comment by IvanVolosyuk** [comment]
I wonder if this should be disabled as well:
```
$ zfs destroy -r rpool/ROOT
```
I didn't realize that now I can do:
```
$ zfs rename rpool/ROOT rpool/ROOT.broken
$ zfs clone rpool/ROOT.broken@last-good rpool/ROOT
$ reboot
```
... and it's awesome!

**Comment by ikozhukhov** [comment]
did you try reproduce my scenario with zfs rename ?

**Comment by freqlabs** [comment]
This might be why:
https://github.com/openzfs/zfs/commit/7b4e27232dec4595ef842ce7c0e31aafd255a20a#diff-67405fd8ed997cc6b2cda757c551601de2e0c433e3b31cdfa9a0e634b1b54a30R4473-R4476
I think you should be able to change the test to expect this to work now, since the rootfs will be unmounted when renamed.

**Comment by ikozhukhov** [comment]
it is NOT test failure - it is real fail and danger on system with bootfs on rpool - where you are able rename activated dataset where you shouldn't to do it

**Comment by freqlabs** [comment]
The motivation of the commit was to be able to safely rename the active dataset.

**Comment by ikozhukhov** [comment]
example: i have booted with activated dataset 'rpool/ROOT/main', where all services up and running. if i renamed it to another one and create clean one 'rpool/ROOT/main' - my reboot will be failed to active dataset - because it can be clean, but loader contain reference to it. to me - it is not applicable with Boot Environment (BE).
