### ISSUE TITLE
~20% performance regression on cached reads due to zfetch changes

### ISSUE THREAD

**Issue by ahrens** [openzfs/zfs#11220]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	| master (at or after https://github.com/openzfs/zfs/commit/af20b97078af7bf4ba7552dff04cc40b643ab72c)
SPL Version	|

### Describe the problem you're observing

Performance of sequential ARC-cached reads with recordsize=8k is ~20% lower than before commit https://github.com/openzfs/zfs/commit/af20b97078af7bf4ba7552dff04cc40b643ab72c.  @tonynguien measured ~3.4GB/s vs ~4.3GB/s.

The problem is that additional CPU time is spent in dbuf_issue_final_prefetch() and callees. Previously, this function called `arc_read(done=NULL)`, so the ARC only needed to ensure the data is in the ARC.  The commit changed this to use a done-func (`dbuf_issue_final_prefetch_done`), which means that the ARC needs to provide the prefetched data, by instantiating an arc_buf_t and decompressing/copying the data.  The additional CPU time required to do this can be significant.

### Describe how to reproduce the problem

Sequential ARC-cached reads (including the test that's in the performance test suite).

cc @mattmacy @adamdmoss

**Comment by mattmacy** [comment]
The arc_buf_t obviously isn't needed by the done func in this case - it's just there to track read completion, could we just pass a flag to arc_read to indicate that it can execute the callback without instantiating an arc buf?

**Comment by ahrens** [comment]
Yeah that seems like a good option to me.
