### ISSUE TITLE
Panic in zone_dataset_visible() on FreeBSD 13-CURRENT

### ISSUE THREAD

**Issue by jurajlutter** [openzfs/zfs#11241]
### System information
FreeBSD | 13-CURRENT
Distribution Name	| FreeBSD
Distribution Version	| 13
Linux Kernel	|
Architecture	| amd64
ZFS Version	| tag 8583540c6
SPL Version	|

### Describe the problem you're observing
After updating to recent -CURRENT and loading openzfs.ko upon boot, the following panic occurs at boot:

```
__mtx_lock_flags() at __mtx_lock_flags+0x49/frame 0xfffffe01a3f59bc0
zone_dataset_visible() at zone_dataset_visible+0x6b/frame 0xfffffe01a3f59c10
zfs_mount() at zfs_mount+0x26c/frame 0xfffffe01a3f59d90
vfs_domount() at vfs_domount+0x89c/frame 0xfffffe01a3f5a000
vfs_donmount() at vfs_donmount+0x872/frame 0xfffffe01a3f5a0a0
kernel_mount() at kernel_mount+0x57/frame 0xfffffe01a3f5a0f0
parse_mount() at parse_mount+0x4a1/frame 0xfffffe01a3f5a230
vfs_mountroot() at vfs_mountroot+0x589/frame 0xfffffe01a3f5a3a0
start_init() at start_init+0x1f/frame 0xfffffe01a3f5a430
fork_exit() at fork_exit+0x80/frame 0xfffffe01a3f5a470
fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe01a3f5a470
```

If I'm correct, `zone_dataset_visible()` comes from OpenZFS. The output above is from `ddb`.
Using in-tree ZFS works OK.

If there any other recommended diagnostic steps, I can follow them.

**Comment by freqlabs** [comment]
@jurajlutter Can you report the panic string from this? It would be on the console before the backtrace, something like
```panic: bla bla bla```

**Comment by freqlabs** [comment]
We discussed this elsewhere and I believe it was a transient issue not related to ZFS. If it reappears please do reopen the issue.
