### ISSUE TITLE
Conflicting GCM Definitions with In-Tree

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#11246]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch
Distribution Version	| Current
Linux Kernel	| 5.4 (probably happens with any kernel)
Architecture	| x86_64 (also probably not relevant)
ZFS Version	| 0.8.4
SPL Version	|

### Describe the problem you're observing

When building ZFS in-tree with `CONFIG_ZFS=y` and `CONFIG_CRYPTO_GCM=y`, the build breaks with:
```
fs/zfs/icp/algs/modes/gcm.c:1493:23: error: passing argument 1 of ‘gcm_init_htab_avx’ from incompatible pointer type [-Werror=incompatible-pointer-types]
```

**Comment by AttilaFueloep** [comment]
I'll have a look later today.

**Comment by AttilaFueloep** [comment]
@sempervictus  I think I know what the problem is. Could you please try this patch?
```
diff --git a/module/icp/algs/modes/gcm.c b/module/icp/algs/modes/gcm.c
index 0b89b0ef4..c8f96014c 100644
--- a/module/icp/algs/modes/gcm.c
+++ b/module/icp/algs/modes/gcm.c
@@ -1052,8 +1052,8 @@ extern void gcm_xor_avx(const uint8_t *src, uint8_t *dst);
 extern void aes_encrypt_intel(const uint32_t rk[], int nr,
     const uint32_t pt[4], uint32_t ct[4]);
 
-extern void gcm_init_htab_avx(uint64_t Htable[16][2], const uint64_t H[2]);
-extern void gcm_ghash_avx(uint64_t ghash[2], const uint64_t Htable[16][2],
+extern void gcm_init_htab_avx(uint64_t Htable[12][2], const uint64_t H[2]);
+extern void gcm_ghash_avx(uint64_t ghash[2], const uint64_t Htable[12][2],
     const uint8_t *in, size_t len);
 
 extern size_t aesni_gcm_encrypt(const uint8_t *, uint8_t *, size_t,
```

Sorry for the inconvenience.

**Comment by AttilaFueloep** [comment]
Commit c6b0680 changed `Htable` to be a `uint64 *`, so master and 2.0.0 >= rc5 should be fine. I'm going to open a PR against the zfs-0.8.6-staging branch once the fix is confirmed.

**Comment by sempervictus** [comment]
Thanks, i did something gross to make it compile in the meantime:
```
diff --git i/fs/zfs/icp/algs/modes/gcm.c w/fs/zfs/icp/algs/modes/gcm.c
index 5fe4d98dbeba..6893e05144ba 100644
--- i/fs/zfs/icp/algs/modes/gcm.c
+++ w/fs/zfs/icp/algs/modes/gcm.c
@@ -1490,7 +1490,10 @@ gcm_init_avx(gcm_ctx_t *ctx, unsigned char *iv, size_t iv_len,
        aes_encrypt_intel(keysched, aes_rounds,
            (const uint32_t *)H, (uint32_t *)H);
 
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
        gcm_init_htab_avx(ctx->gcm_Htable, H);
+#pragma GCC diagnostic pop
 
        if (iv_len == 12) {
                bcopy(iv, cb, 12);
```
pulling the patch in now, will test and ping back

**Comment by sempervictus** [comment]
@AttilaFueloep: seems to be working - build hasnt failed yet :). Thank you
While i have you, could you possibly enlighten me as to what `Htable[16][2]` logically means? I read that as "the third ? of the 17th bit in Htable," and can't figure out what the 2nd index is trying to access.

**Comment by sempervictus** [comment]
Unfortunately, that didn't work. Having removed the `#pragma` statements and applied the patch above, i'm still seeing the same exact error.
The build environment is GCC 10.2:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
```

**Comment by AttilaFueloep** [comment]
Strange, I greped the linux source tree for  `gcm_init_htab_avx`, `gcm_ctx_t`, and `gcm_Htable` and found nothing. I guess I've to figure out how to build the kernel with zfs as a builtin module to reproduce this. I'm also wondering why it would pass if compiled as a loadable module, since the call and the prototype don't match. Maybe different gcc flags or  different gcc version?  I'm still on gcc 10.1.0. 

`gcm_init_htab_avx(uint64_t Htable[16][2], const uint64_t H[2]);` is a declaration that this functions takes a pointer to a two dimensional array (16 rows, 2 columns) of `uint64_t`'s as its first argument. So the error would make sense, since we are passing in an array of twelf rows and two columns.

**Comment by AttilaFueloep** [comment]
By the way, did you try to compile master as a builtin module recently? I'm wondering if that would work.

**Comment by sempervictus** [comment]
So for the in-tree build, this should do it from the ZFS source tree:
```
#!/bin/bash
KDIR=<YOUR KERNEL SOURCE PATH>
TAG="$(git branch --show-current |awk '{print$1}')"
echo "Using KDIR $KDIR and cleaning tree in $PWD"
git clean -dxf
./autogen.sh && 
./configure --disable-debug --disable-debuginfo --enable-linux-builtin --with-linux="$KDIR" && \
./copy-builtin "$KDIR" && \
cd $KDIR && \
rm include/zfs/.gitignore && \
git add . && git commit -am "ZFS: $TAG builtin" && \
echo 'CONFIG_ZFS=y' >> .config
```

That said, i'm suspicious of the root cause here. Clearly the fix you proposed lines up the indices with the code change referenced, and i'm now seeing this even with `CRYPTO_GCM=m` on the same exact code that worked fine two days ago. My GCC hasn't changed, kernel sources either. I dont know why the original code worked before your fix, i'm very confused as to why it doesnt work now (unless GCC is incorrectly inferring the argument types which doesnt seem to make sense).
I tried this the non-grsecurity-patched tree, and am seeing the same thing, although that one's using the GrapheneOS hardening patches (nowhere near the level of change/impact as grsec). I can try an upstream clean kernel, but i think its something in the build chain other than GCC (the 10.2 here was installed when Arch released it and the package hasnt updated for months).

**Comment by AttilaFueloep** [comment]
Thanks a lot for your detailed description of the process. It's a bit late here (GMT+1) so I'll give it a whirl tomorrow. I'm going to use the v5.4 tag and the default Kconfig + `CONFIG_CRYPTO_GCM=y` and `CONFIG_ZFS=y` and will report back how it goes.

I figured out why the wrong prototype didn't cause an error, `uint64_t Htable[16][2]`, `uint64_t Htable[][2]` and`uint64_t (*)[2]` are all equivalent.  I think it has to do with the fact that C performs no bounds checking for formal parameters. What's a bit counterintuitive though is the fact that the second array index is indeed checked, but that's a different story. So basically my patch shouldn't make any difference as is.

Indeed a strange effect you are seeing.

**Comment by sempervictus** [comment]
@AttilaFueloep: thanks for digging through and explaining that. Is there a better way to write the call structure so as to give GCC better visibility into what happening?
All of the kconfigs i use turn on the majority of hardening options including the GCC STRUCTLEAK plugin and friends . I wonder if the indirection involved here is upsetting them somehow.

**Comment by AttilaFueloep** [comment]
Sorry, can't reproduce with zfs 0.8.4, linux 5.4.75 and gcc 10.1.0.

This smells like a compiler bug. Given the described behaviour I'd say this is the most likely explanation. Could you show the lines following the error line you give in the issue description above? It would be good to see what the compiler thinks it is expecting and thinks it got.

The other possibility is that warning you are seeing is caused by the patches you pull in, so it would be good if you could you try with an upstream clean kernel.

**Comment by AttilaFueloep** [comment]
@sempervictus Any news on this?

**Comment by sempervictus** [comment]
I've not had a chance to do a full clean build - been working on getting some of our linux-hardened branch upstreamed to another project in my "copious" spare time, but i'll try to get this run in the mainline kernel tree today and ping back.
When you build, do you have GCC plugins enabled?

**Comment by AttilaFueloep** [comment]
No hurry, just ping back when you have results.

It looks like the struct leak plugins are loaded:
```
-fplugin=./scripts/gcc-plugins/structleak_plugin.so -fplugin-arg-structleak_plugin-byref-all
```
but I'm not deep enough into the kernel build system to say so definitely.

**Comment by AttilaFueloep** [comment]
If you still can reproduce this, it would also be good to see what gcc expects, something like:
```
t.c: In function ‘main’:
t.c:8:19: error: passing argument 1 of ‘wrong_proto’ from incompatible pointer type [-Wincompatible-pointer-types]
    8 |   a = wrong_proto(arg);
      |                   ^~~
      |                   |
      |                   int (*)[4]
t.c:1:21: note: expected ‘int (*)[2]’ but argument is of type ‘int (*)[4]’
    1 | int wrong_proto(int arg[6][2]);
      |                 ~~~~^~~~~~~~~
```

**Comment by sempervictus** [comment]
Just did a upstream-5.4.81 + zfs-0.8.4 build, appears to have worked fine.
I re-ran on the hardened branch, and that worked as well. There's something afoot with my build chain, Cheshire Cat style.
Given that i can't reproduce this with upstream, i think its safe to say that nobody else should be impacted. I'll keep an eye on the CI build logs to see if it pops back up, try to collect whatever surrounding outputs that we log
