### ISSUE TITLE
openzfs-2.0.0-rc7 zpool import hangs

### ISSUE THREAD

**Issue by zviratko** [openzfs/zfs#11245]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo Linux
Distribution Version	| ~amd64
Linux Kernel	| 5.9.11-gentoo
Architecture	| amd64
ZFS Version	| 2.0.0-rc7
SPL Version	| 2.0.0-rc7

### Describe the problem you're observing

After updating from openzfs-2.0.0-rc6 to openzfs-2.0.0-rc7 I am observing a hang on boot.
Running debug shell in initramfs (I am running root on ZFS, initramfs is genkernel/linuxrc) I see that "zpool import" takes 1m16s (consistently) to return with correct ata. Not sure how long it took on rc6, but it surely didn't take more than a second or so to mount the pool.

EDIT: This was a red herring caused by missing zpool.cache. The actual import simply never completes.

My root pool is on a 2 drive NVMe mirror.
There is also a boot pool on the same NVMe pair.

There is also a data pool on 6 SATA drives with 2 SSD cache drives for L2ARC and SLOG.

Drives and pools are probably detected correctly, it just takes a long time.

I waited for ~15 minutes and the system didn't boot, I'll try waiting longer when I can, maybe something can be dug up from a running system.

I don't think the problem is in the userland utilities: 2.0.0-rc6 kernel modules + 2.0.0-rc7 userland work just fine.

### Include any warning/errors/backtraces from the system logs

I see nothing in dmesg indicating some sort of I/O error or hang, no errors anywhere. Let me know how I can help debug this. Unfortunately the initramfs environment is limited so I can't look at stack or something like that (at least not easily).

**Comment by behlendorf** [comment]
If possible could you verify the delay isn't present in 2.0.0-rc6.  I understand the initramfs environment is limited but perhaps you could still determine if it appears to be IO or cpu bound?

**Comment by zviratko** [comment]
2.0.0-rc6 works just fine, boot is swift including importing all pools (rpool in initramfs and the ata pool after that).
2.0.0-rc6 kmod + 2.0.0-rc7 userland also works fine

**Comment by zviratko** [comment]
To elaborate more - I haven't tried running plain "zpool import" with 2.0.0-rc6, so it's possible it's a red herring and the ramdisk runs something else (I think it actually does something like "mount -t zfs $noideawhat")

I don't think it's anything-bound - "time zpool import" reported 1m16s real, rest was pretty much zero. Drive LEDs indicate nothing.

**Comment by behlendorf** [comment]
I don't see anything in the [release notes](https://github.com/openzfs/zfs/releases/tag/zfs-2.0.0-rc7) which would be a likely cause.  The most plausible kernel side changes from rc6 to rc7 which might have caused this would be a3a4b8def7 or ccfa35c6, could you try reverting each of those changes to see if it helps?

**Comment by zviratko** [comment]
Thank you. I will try and report back (tomorrow).

I do have some parameters set not default:
options zfs zfs_per_txg_dirty_frees_percent=0 l2arc_noprefetch=0 l2arc_write_max=33554432 l2arc_write_boost=33554432 zfs_vdev_scrub_max_active=4 zfs_vdev_scrub_min_active=0 zfs_scrub_min_time_ms=100

And this should be the command that hangs in initramfs (at least for ~15 minutes, possibly forever)
/sbin/zpool import -N -c /etc/zfs/zpoo.cache -f rpool

**Comment by zviratko** [comment]
I ran the zpool import in background so I could gather something
1) cpu is doing nothing
2) drives are doing nothing
3) zpool import is in D state and photo of stack is attached :-)
![IMG_1439](https://user-images.githubusercontent.com/3704384/100390776-dc26e780-3031-11eb-95a9-9907cb056ccb.jpeg)

**Comment by zviratko** [comment]
Success!

Reverting https://github.com/openzfs/zfs/commit/a3a4b8def716eda636a1f864c49d25c5bac92822# did the trick.
Pool imported instantly and the server booted just fine.

Let me know if I can help debug it further.

**Comment by behlendorf** [comment]
Thanks that definitely narrows it down.  @zviratko were you able to reproduce the issue with the default module tunings?  Were there any background activities (scrub resilver, initialize, etc)which might have been in progress when trying to import?  Or anything else non-standard about the pool?  Do both pools experience this long delay or only one?  @amotin might have some suggestions for additional things to check.

**Comment by zviratko** [comment]
I tried increasing zfs_vdev_scrub_min_active(=2), zfs_vdev_initializing_min_active(=2), zfs_vdev_initializing_max_active(=3) (when are those two used?) with no effect. I also tried with and without the cache file.

There was nothing going on in the pools, and the root pool is a simple one.

The only non-standard things is that rpool doesn't have all features enabled, those are missing:

rpool
      redaction_bookmarks
      redacted_datasets
      bookmark_written
      log_spacemap
      livelist
      device_rebuild
      zstd_compress

And the only relevant tuning is "libata.fua=1" on cmdline (not sure if that's the default nowadays).
I'm running a 5.9.11 kernel, maybe nobody tested on that yet?

I will retest with defaults and also the data pool when I can, but I'm pretty sure that patch just sets the number of requests to zero somewhere... :)

**Comment by zviratko** [comment]
Oh yeah, also bleeding edge versions everywhere, like
gcc (Gentoo 10.2.0-r3 p4) 10.2.0

**Comment by JordanP-Dev** [comment]
If it helps to narrow it down, I am also running Gentoo with kernel 5.9.11 and zfs 2.0.0-rc7 and my pool loads fine.  My pool does have all features enabled, though.

**Comment by amotin** [comment]
@zviratko Thanks for the report, unfortunately so far I can't guess what could it be just looking on the code.  If it happen immediately on the pool import, may be you could add some debugging into vdev_queue_class_to_issue(), vdev_queue_pending_add() and vdev_queue_pending_remove() to see what I/O priorities are going through and what are the values of vq->vq_ia_active and vq->vq_nia_credit ?  I suppose some I/O accounting issue could block non-interactive I/Os, but I don't see how could it happen.

**Comment by zviratko** [comment]
If you give me a patch I could add some debuggin easily enought, but I can't code.

Sorry for no updates, I need physical access to this machine to debug it, hopefully I'll have some more info this week.

**Comment by amotin** [comment]
@zviratko This is the kind of debug I was thinking about: https://github.com/amotin/zfs/commit/8b43232ce6b0e2ba7c67e7731fad6420a2ecd2fc
It is pretty noisy, so I'd prepare some way of console logging and hope the issue reproduce on the first attempt.

**Comment by zviratko** [comment]
I tested it with another pool - same behaviour, zpool import just hangs.

@amotin that patch applies cleanly, but it won't compile due to missing stdio
I modified all the printf() to dprintf() which compiled, then did

echo 1 >zfs_dbgmsg_enable
echo 0xffffffde >zfs_flags
zpool import ...

but I see nothing with "c2i" preffix in /proc/spl/kstat/zfs_dbgmsg
Maybe I'm using it wrong?

However, after a while I got something that could be useful. Sorry, only photo again, and just the head and tail of that block... Need to figure a way to get that log out better.
![IMG_1440](https://user-images.githubusercontent.com/3704384/100769400-48239a00-33fc-11eb-923a-3fd25afa552b.jpeg)
![IMG_1441](https://user-images.githubusercontent.com/3704384/100769416-4f4aa800-33fc-11eb-9274-916c9095ef26.jpeg)

**Comment by zviratko** [comment]
btw looking into /proc/spl/kstat/zfs/rpool I see state=ONLINE and the "io" file indicates some reads and writes occured as well..

**Comment by zviratko** [comment]
Eureka.

echo 0 >zfs_vdev_scrub_min_active

this setting makes zpool import hang

I should have found that out sooner, but I didn't realize "udevadm trigger --action=add" would load the zfs module, so me later removing /etc/modprobe.d/zfs.conf and loading it didn't use the defaults...

**Comment by amotin** [comment]
Good catch with zero min_active.  The PR #11261 should fix it.  Please test,

**Comment by zviratko** [comment]
Thanks. I already removed those tunables in order to test the impact of your patches (not that my workload is latency intensive or anything, but even with single-user usage any scrub was very noticeable), but I'll retest with that PR once my scrubs complete.

**Comment by zviratko** [comment]
@amotin I can confirm that openzfs-2.0.0 with https://github.com/openzfs/zfs/commit/a3a4b8def716eda636a1f864c49d25c5bac92822 and https://github.com/openzfs/zfs/pull/11261 boots fine with zfs_vdev_scrub_min_active=0 and thus allows me to shoot myself in the leg :-)
