### ISSUE TITLE
reduce zio allocation in dmu_buf_hold_array_by_dnode

### ISSUE THREAD

**Issue by Finix1979** [openzfs/zfs#11251]
### Ask your question!

It seems the zio only created for reading in dmu_buf_hold_array_by_dnode function. If so, suggest to add "if (read)" before zio_root and zio_wait.

### Which portion of the codebase does your question involve?
master

**Comment by behlendorf** [comment]
@Finix1979 you're correct.  In fact, PR #9836 includes a version of this optimization, 0705862, which didn't quite get finalized and merged.  If you're interested in picking up this work it'd be great if you could open a new PR.

**Comment by Finix1979** [comment]
I open PR #11256
