### ISSUE TITLE
Removing a vdev and attaching it to another vdev results in CKSUM errors during resilver

### ISSUE THREAD

**Issue by gamanakis** [openzfs/zfs#11257]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	| (rolling)
Linux Kernel	| 5.9.9
Architecture	| x64
ZFS Version	| 04a82e043d067181a8b352921ef6a3c3ac875b59 and 0.8.5
SPL Version	| see above

### Describe the problem you're observing
Removing a top-vdev and reattaching to another top-vdev in the same pool results in CKSUM errors while resilvering. This was observed in a 11TB production pool with 128kB recordsize and is reproducible in a VM using the following script.

### Describe how to reproduce the problem
This is reproducible in both 0.8.5 and 04a82e043d067181a8b352921ef6a3c3ac875b59:
```
truncate -s 4G {a,b}
zpool create -f -O recordsize=4k test ~/{a,b}
fio --name=test --size=2G --nrfiles=512 --readwrite=read --directory=/test
zpool remove test ~/b
zpool attach test ~/a ~/b
zpool status test
```
After resilvering is done the newly attached vdev shows CKSUM errors in zpool status.
However no real data corruption seems to occur as a zpool scrub does not report any errors.

Looking at the implementation of Nexenta I found two relevant commits:
1) https://github.com/Nexenta/illumos-nexenta/commit/f7d80bb043e6d74054633d0eecb255350d92ce51 based on 
https://github.com/openzfs/zfs/pull/8753 (waiting for current tx to sync while scanning during resilver)

and

2) https://github.com/Nexenta/illumos-nexenta/commit/847e400 (thread locking of scan queues)

However none of these approaches resolve the bug (tested locally).
Removing the vdev and reattaching it is crucial to triggering the bug. When attaching a fresh (ie non previously removed vdev) device, the CKSUM errors do not occur.

### Include any warning/errors/backtraces from the system logs

```
zpool status:
pool: tst3
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
        attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
        using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: resilvered 2.08G in 0 days 00:00:26 with 0 errors on Tue Dec  1 12:33:40 2020
remove: Removal of vdev 1 copied 1.07G in 0h0m, completed on Tue Dec  1 12:33:10 2020
    8.77K memory used for removed device mappings
config:

        NAME                      STATE     READ WRITE CKSUM
        tst3                      ONLINE       0     0     0
          mirror-0                ONLINE       0     0     0
            /home/user/vdevs/a  ONLINE       0     0     0
            /home/user/vdevs/b  ONLINE       0     0    14

errors: No known data errors

```

```
zpool events -v:
Dec  1 2020 12:33:38.028552122 ereport.fs.zfs.checksum
        class = "ereport.fs.zfs.checksum"
        ena = 0x15985ab1e9e00c01
        detector = (embedded nvlist)
                version = 0x0
                scheme = "zfs"
                pool = 0xf7542d83774def6a
                vdev = 0xb4ae9f5bec165b83
        (end detector)
        pool = "tst3"
        pool_guid = 0xf7542d83774def6a
        pool_state = 0x0
        pool_context = 0x0
        pool_failmode = "wait"
        vdev_guid = 0xb4ae9f5bec165b83
        vdev_type = "file"
        vdev_path = "/home/user/vdevs/b"
        vdev_ashift = 0x9
        vdev_complete_ts = 0x115985afec23
        vdev_delta_ts = 0x4da69
        vdev_read_errors = 0x0
        vdev_write_errors = 0x0
        vdev_cksum_errors = 0xe
        vdev_delays = 0x0
        parent_guid = 0x248200fb1cd637b7
        parent_type = "mirror"
        vdev_spare_paths = 
        vdev_spare_guids = 
        zio_err = 0x0
        zio_flags = 0x1008a8
        zio_stage = 0x200000
        zio_pipeline = 0x1f00000
        zio_delay = 0x0
        zio_timestamp = 0x0
        zio_delta = 0x0
        zio_offset = 0xd413c00
        zio_size = 0x600
        bad_ranges = 0x0 0x600 
        bad_ranges_min_gap = 0x8
        bad_range_sets = 0xbad 
        bad_range_clears = 0xb9a 
        bad_set_histogram = 0x37 0x2d 0x2f 0x38 0x2e 0x2e 0x37 0x2e 0x2f 0x2e 0x37 0x2e 0x2e 0x38 0x2e 0x2e 0x2f 0x27 0x39 0x28 0x31 0x2b 0x2f 0x37 0x2d 0x2d 0x29 0x25 0x35 0x35 0x36 0x2d 0x2c 0x33 0x2e 0x32 0x33 0x39 0x3a 0x2b 0x33 0x35 0x38 0x35 0x34 0x2f 0x2c 0x2d 0x29 0x2e 0x36 0x3c 0x2b 0x30 0x38 0x2f 0x0 0x0 0x0 0x2c 0x31 0x32 0x37 0x3d 
        bad_cleared_histogram = 0x32 0x2b 0x34 0x32 0x2a 0x34 0x33 0x2b 0x2a 0x35 0x32 0x2b 0x34 0x32 0x2a 0x34 0x36 0x3d 0x2e 0x35 0x33 0x39 0x35 0x32 0x34 0x28 0x32 0x3a 0x2f 0x23 0x2f 0x36 0x39 0x32 0x2c 0x2a 0x2f 0x2c 0x2f 0x3a 0x35 0x33 0x33 0x36 0x30 0x2c 0x2f 0x34 0x34 0x2f 0x29 0x2c 0x2d 0x30 0x2b 0x30 0x0 0x0 0x0 0x2b 0x2f 0x35 0x2c 0x33 
        time = 0x5fc62a12 0x1b3abba 
        eid = 0x18e

**Comment by behlendorf** [comment]
This appears to be caused by a simplification made in the device removal code.  When resilvering both halves of the mirror are read unconditionally without consulting the DTL which would indicate the data is missing.  In practice this isn't harmful since the checksum is used to determine the correct data.  However, it appears that it does bubble up and gets reported as a checksum error which isn't ideal. We could investigating somehow suppressing these warnings, or making the code smart enough to take in to account the DTL.

https://github.com/openzfs/zfs/blob/master/module/zfs/vdev_indirect.c#L1348-L1355
https://github.com/openzfs/zfs/blob/master/module/zfs/vdev_indirect.c#L1274-L1283

**Comment by gamanakis** [comment]
@behlendorf Thank you for outlining this! I will try to come up with a PR.
