### ISSUE TITLE
zfs-diff.8 missing argument in -F description

### ISSUE THREAD

**Issue by melak** [openzfs/zfs#11268]
### System information
N/A (Git HEAD)

### Describe the problem you're observing
`man zfs-diff` renders as
```
 -F  Display an indication of the type of file, in a manner similar to
     the - option of ls(1).
```
There is a missing `F` flag argument to the `Fl` macro in `man/man8/zfs-diff.8`:

```diff
--- a/man/man8/zfs-diff.8
+++ b/man/man8/zfs-diff.8
@@ -66,7 +66,7 @@ R       The path has been renamed
 .Bl -tag -width "-F"
 .It Fl F
 Display an indication of the type of file, in a manner similar to the
-.Fl
+.Fl F
 option of
 .Xr ls 1 .
 .Bd -literal
```
### Describe how to reproduce the problem
Run `man zfs-diff`, read description for `-F`.

**Comment by freqlabs** [comment]
@melak would you like to open a pull request for this change?
