### ISSUE TITLE
zvol blocksize read leads 4k seperate read io

### ISSUE THREAD

**Issue by Finix1979** [openzfs/zfs#11267]
### Ask your question!

I create a simple zvol(p1/v1) with volblocksize=16K setting and use dd to fill random data first. In order to make ARC clean, I export pool and import it again. Then use dd if=/dev/p1/v1 of=/dev/null bs=16K count=3 iflag="direct" 

From biosnoop, I get this:
5.513781    zvol           11799  sdb     R 77733998   4096     23.15
5.513863    zvol           11799  sdb     R 77734006   4096     23.16
5.514291    zvol           11799  sdb     R 77734014   4096     23.54
5.514317    zvol           11799  sdb     R 77734022   4096     23.54
5.514979    zvol           11802  sdb     R 77734030   4096      0.25
5.515011    zvol           11802  sdb     R 77734038   4096      0.19
5.515034    zvol           11802  sdb     R 77734046   4096      0.17
5.515063    zvol           11802  sdb     R 77734054   4096      0.18
5.515432    zvol           11795  sdb     R 77734062   4096      0.20
5.515457    zvol           11795  sdb     R 77734070   4096      0.19
5.515463    zvol           11795  sdb     R 77734078   4096      0.18
5.515475    zvol           11795  sdb     R 77734086   4096      0.17

Each IO size is 4k instead of 16K. I noticed that vdev_disk_io_start function is called 12 times, each for 4K. 
After further analysis, I think this 4k comes from dbuf module.

Is that by design? Or any export parameter can be used to get better IO merge?

### Which portion of the codebase does your question involve?
0.8.5

**Comment by behlendorf** [comment]
The IO size issued to the underlying devices will depend on the exact pool configuration.  For example, if you're using 5 disk or larger raidz pool then a 16k block will result in a 4k IO for each disk.  (four 4k data chunks plus an one 4k parity chunk).  On the other hand for a mirrored pool you should see larger IO sizes.  In practice ZFS will further aggregate adjacent IOs when possible.

**Comment by Finix1979** [comment]
Thank you @behlendorf 
The above output of biosnoop is a pool constructed by only one disk. 
Today I could not reproduce this. Close it for now
