### ISSUE TITLE
This page was moved to a broken URL (ZFS-on-Linux-Module-Parameters)

### ISSUE THREAD

**Issue by IvanVolosyuk** [openzfs/zfs#11263]
In the wiki page (which is the first google result for "zfs module parameters"):
https://github.com/openzfs/zfs/wiki/ZFS-on-Linux-Module-Parameters

The content is:
**This page was moved to: https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/ZFS%20on%20Linux%20Module%20Parameters.html**

The destination link is a broken URL.

**Comment by behlendorf** [comment]
Thanks.  I've updated the destination URL.
