### ISSUE TITLE
Failed install on packaging for 2.x in Fedora

### ISSUE THREAD

**Issue by storrgie** [openzfs/zfs#11289]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 32
Linux Kernel	| 5.9.11
Architecture	| x86_64
ZFS Version	| 2.0.0
SPL Version	|

### Describe the problem you're observing

Recently pulled update for 2.0.0-1. Appears to build properly. Appears to be installed (dkms {build, install} reports back that the package is built and installed. When you try to load the module you get:

```
modprobe: ERROR: could not insert 'zfs': Exec format error
```

### Describe how to reproduce the problem

update fedora with the zfs repostiory

**Comment by mskarbek** [comment]
Just tested using the official repo and dkms package, can't confirm.
```
# uname -a
Linux wn03 5.9.11-100.fc32.x86_64 #1 SMP Tue Nov 24 19:16:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# modprobe zfs
# dmesg
(...)
[  950.948124] spl: loading out-of-tree module taints kernel.
[  950.949474] spl: module verification failed: signature and/or required key missing - tainting kernel
[  950.993710] znvpair: module license 'CDDL' taints kernel.
[  950.993768] Disabling lock debugging due to kernel taint
[  953.116183] ZFS: Loaded module v2.0.0-1, ZFS pool version 5000, ZFS filesystem version 5
```

**Comment by storrgie** [comment]
Thanks @mskarbek, your post let me feel comfortable knowing that I'd be able to get F32/F33 working, so I rebuilt the system. The state that I was in was likely something to do with packaging issues during the F32 window. I'm working again, closing this.
