### ISSUE TITLE
rpm package is not SELinux-aware

### ISSUE THREAD

**Issue by bernie1995** [openzfs/zfs#11299]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Centos
Distribution Version	| 7
Linux Kernel	| 3.10
Architecture	| x86_64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing

/dev/zfs is labeled as system_u:object_r:device_t:s0, should be system_u:object_r:zfs_device_t:s0 or something. we monitor or production storage via snmpd, with selinux enforcing snmpd_t is not allowed to { read write } device_t files: we would like to allow snmpd_t to access zfs_device_t files (/dev/zfs) without the need to allow access to every other device_t.

### Describe how to reproduce the problem

install zfs on centos, run ls -lZ /dev/zfs

**Comment by behlendorf** [comment]
This would definitely be handy.  Unfortunately, the SELinux labeling is controlled by the default policy provided by the distribution and not by the rpm packaging.  There's nothing I'm aware of we can do from a project standpoint to change this.  This is a change which would need to be made to CentOS's policy, or you'll need to roll your own custom policy.

**Comment by mskarbek** [comment]
OpenZFS could provide its policy set packaged as a separate, additional rpm. SELinux is modular and allows side loading additional policies - that would solve the issue with correct labeling of ZFS device. Part with snmpd access should be handled by snmpd policy either custom or in the upstream.

**Comment by bernie1995** [comment]
>  you'll need to roll your own custom policy.

Will do.

**Comment by bernie1995** [comment]
Done, this was way easier than expected.

Since upstream doesn't seem interested in this fix we'll start pushing our own custom built rpms. :+1:

**Comment by behlendorf** [comment]
@mskarbek I'd be interested to see what's involved in us providing a policy which could be side loaded.  Can you provide a link to any documentation for this?
