### ISSUE TITLE
Which is the compression method being used?

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#11298]
How can I find out which compression method zfs is using when the property is `compression=on` ? Is the default still `lz4` or has that changed to `zstd`?

**Comment by AllKind** [comment]
`zfs list -o compression`
or
`zfs get compression`

**Comment by gmelikov** [comment]
It's still LZ4 https://github.com/openzfs/zfs/blob/master/module/zfs/zio_compress.c#L103 , as described in man too https://openzfs.github.io/openzfs-docs/man/8/zfsprops.8.html?highlight=compression:
```
The current default compression algorithm is either lzjb or, if the lz4_compress feature is enabled, lz4. 
```

**Comment by mabod** [comment]
ok. So i get that other than checking the documentation or the source code there is no command for it.

@AllKind :

`zfs get compression`" does not do the job:

```
4# zfs get compression tank
NAME    PROPERTY     VALUE           SOURCE
zstore  compression  on              local
```

You do not know which compression is being used.
