### ISSUE TITLE
OpenZfs 2.0.0 Dkms packages for centos7

### ISSUE THREAD

**Issue by xgiovio** [openzfs/zfs#11308]
Any news when these packages will be available?

**Comment by gdevenyi** [comment]
#10333

**Comment by behlendorf** [comment]
If you'd like to test out the OpenZFS 2.0 packages for CentOS they are available from the [zfs-testing](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html#testing-repositories) repository.

**Comment by xgiovio** [comment]
> If you'd like to test out the OpenZFS 2.0 packages for CentOS they are available from the [zfs-testing](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html#testing-repositories) repository.

That is an rc5 candidate. I would like to install the definitive version. When will it be available? What is the point of releasing publically a release if there aren't the rpm packages for the end users after a week and more from the source release.
At least a wiki to build these rpms ourself.

**Comment by xgiovio** [comment]
I folowd this to build! thanks 
https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html

**Comment by behlendorf** [comment]
It looks like you were using the CentOS 7.8 instead of CentOS 7.9 repository.  Normally, we just build new packages for the latest release.  You'll want to use this zfs-release package.

http://download.zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm

**Comment by xgiovio** [comment]
Thanks
