### ISSUE TITLE
ZFS supposed independant clones

### ISSUE THREAD

**Issue by B3r3n06** [openzfs/zfs#11316]
Hello,

### Issue
ZFS provides a dataset cloning feature.
Technically, the procedure is the below:
  zfs create MYdataset
  zfs snapshot MYdataset@MYmark
  zfs clone MYdataset@MYmark MYNEWdataset
  zfs promote MYNEWdataset

From this, MYNEWdataset is supposed totally independant from its origin MYdataset.

However, when the clone becomes useless and to be destroyed, it appears a bug:
  zfs destroy MYNEWdataset
cannot destroy 'MYNEWdataset': filesystem has children
use '-r' to destroy the following datasets:
MYNEWdataset@MYmark

  zfs destroy -r MYNEWdataset
cannot destroy 'MYNEWdataset': filesystem has dependent clones
use '-R' to destroy the following datasets:
MYdataset

So enforcing the action will delete the original dataset, still used.
From this, there is no escape but destroying original dataset for real and rebuild it.

### System information
This happens on ZFS on Ubuntu 18.04.5 and FreeBSD 12.

Versions on Ubuntu:
ZFS version:        0.7.5-1ubuntu16.10
SPL version:        0.7.5-1ubuntu2.2

**Comment by churchers** [comment]
As far as I can see this is expected behaviour.

A clone does not duplicate any data (that's the whole point), and so it is dependent on the original dataset.
In your case, when `MYNEWdataset` is created, it relies on `MYdataset`. All the promote command does it reverse the dependency so that `MYNEWdataset` becomes the "primary". This gives you the ability to destroy `MYdataset` and keep `MYNEWdataset`.

>Promotes a clone file system to no longer be dependent on its
>"origin" snapshot. This makes it possible to destroy the file system
> that the clone was created from. The clone parent-child dependency
>relationship is reversed, so that the origin file system becomes a
>clone of the specified file system.

The first sentence here does read somewhat as if the dependency is gone. However if you continue reading it very clearly states that now the original dataset is basically now the clone. You still only have one copy of the data on disk, so your options for deleting come down to a. delete the clone or b. delete the current "primary" dataset and destroy both in the process.

If you plan to use the clone (`MYNEWdataset`) for something temporarily, then scrap it, you shouldn't promote it. Keep the original dataset as the master.

**Comment by B3r3n06** [comment]
Hello Ahrens,

Thanks for your answer.

I understand what you say and what is written seems to be apparently the case. To me, this then becomes an issue of terms.
If I clone you, once your clone is independant of you (as the zfs clone command indicates), I can kill it without having to kill you. Else that is not a clone. A clone is an independant copy, even if, to save disk space, it relies on the data block of its original source. If ZFS behaves this way ok, but then a "zfs unpromote" command should exist to avoid a deadend issue upon misuse.

Taking the example of BTRfs, if I create a snapshot of a dataset, this dataset has its own life, can be modified, destroyed, whatever. There is no snapshot hierarchy either.. The clone counts the difference with its "master" as disk space, no more.
Once I finished using it, I just delete the snapshot and the associated directory & data vanish.

With ZFS, creating a real clone seems then not possible but at the price of zfs send|zfs receive.
If I want to have what looks like a clone, ZFS wants a snapshot first (meaning a snapshot is required per clone if there is just a small difference in data)

That is the purpose I want to achieve is the capability for students to work on their own directory tree with the capability of rollback based on versioning (then it should be possible to rollback at any version level without loosing snapshot done later in time), based from an original containing the exercice. Once the student finished, he can keep its clone for later use or the clone is destroyed to free space.

If that is not a bug, maybe this could become a dev request ?

Thanks

Brgrds

**Comment by churchers** [comment]
[quote]With ZFS, creating a real clone seems then not possible but at the price of zfs send|zfs receive.[/quote]

I'm confused at what you mean by a "real" clone. The point of clone is to create two separate identical datasets without having to duplicate any data. The clone takes no space other than new data written to it. If needed, you can delete the clone with no issue. Now of course, if you try to delete the original dataset, you can't as it has dependent clones. The clone only stores its differences and is relying on the data in that original dataset. If you really want to scrap the original but keep the clone, you need to promote the clone so it becomes the "master". 

I can't see how this could possibly work any other way without having two full copies (i.e. send/recv). I know nothing of BTRFS but I can't see how you could snapshot/clone a dataset with zero data copy, then delete that original dataset.

One possible "improvement" here could be the ability to destroy a master and have the data automatically promoted to the oldest clone. I would probably still suggest ZFS having a warning for this though with `-f` or some specific argument required to actually make it work. This way you could have two datasets (a master and clone) that appear independent, and either could be deleted; The data would just move to whichever one still exists. All you're really doing though is avoiding the promote step, which many would argue is preferred as it gives the administrator complete control over which dataset is currently the master.

For your teaching example you just need to have a base dataset containing the exercise. Clone it for each student but *do not* run promote on any of them. Each student can work on their own clone and make their own snapshots, and all the clones can be removed if not needed. They will all only take the space required by changes. The only caveat is that rolling back on ZFS removes the intermediate snapshots, so you can't rollback to a month ago, then go forward again. This isn't an issue of cloning, but ZFS in general. (You can of course however look in any snapshot to retrieve data from that point in time)

**Comment by B3r3n06** [comment]
Hello Matt,

Agree, there is a confusion, probably coming from me.

Moving backwards, I sense this might come because I played with BTRfs which was simpler to achieve my needs and probably because I am far from mastering ZFS.

With BTRfs, a snapshot have its own life and is mountable. It relies on its master of course, but since a snapshot is built, that is call. So I snap the dir to another mount point and then student does whatever. At the end, I destroy snap, no more.
And yes, if on BTRfs you delete the "master", automatically the blocks are assigned to the snapshot.
That is part of BTRfs issue by the way because such an action cost so much that everything's frozen meanwhile and since it is still used by processes, it might generate data corruption...

On ZFS, a snapshot is not a mountpoint but if I deliberately mount it, which has a mountpoint cost. To become a directory, it must be zfs cloned. I understand a 'static' image is required for the clone and so the snapshot is required for this.
But then it means each clone must have its own snapshot, except of course, if at a moment the teacher frozen the dataset. But then, changes he will perform will be lost. The snapshot blocks evolution.
After all from what I understand,, a zfs clone is no more than a RW mounted snapshot.

What if there is no snapshot ? The original could keep evolving, ok. But if there was no snapshot, would it make a difference ? Some block would change, clone will reflect that, ok. If that is not wished, then a snapshot remains possible.

**Comment by B3r3n06** [comment]
About "They will all only take the space required by changes. The only caveat is that rolling back on ZFS removes the intermediate snapshots, so you can't rollback to a month ago, then go forward again. This isn't an issue of cloning, but ZFS in general. (You can of course however look in any snapshot to retrieve data from that point in time)"

Agree, that is a real concern.. Since I have this strong need and mounting to copy is not acceptable (due to the delay on big amount of data), I may have found a workaround playing on snapshot+clone. 

My idea I just got (still to test & check) would then be to have a clone per version.
Because zfs clone is mounted and lives, I think it will be exactly the same as my BTRfs sub snaps :-)
From this moment, versionning without hierarchical enforcement will not be performed with "zfs rollback" but zfs clones that would be "clones of clones" for the requesting student.

To be tested :-)

**Comment by IvanVolosyuk** [comment]
To 'unpromote' a clone you can just promote the original and you can delete the clone after that. In your example:
zfs promote MYdataset will do the trick
zfs destroy MYNEWdataset

You can also keep just MYNEWdataset:
zfs promote MYNEWdataset
zfs destroy MYdataset

**Comment by B3r3n06** [comment]
Ookkk, thanks Ivan, I am currently moving data from BTRfs back to ZFS, I will then see how far can I go to reach the same situation as before (in termes of flexibiliy I mean), because BTRfs, in terms of performance, is really bad..

**Comment by B3r3n06** [comment]
Hello guys,

I am taking the opportunity of skilled ZFS fellows around to be sure.

To reach again the rolling back feature WITH versionning (ZFS destroy earlier snapshots), I wonder if using zfs clone could do.

My idea:
Multiple snapshot exist : T0, T1, T2, from oldest to newest.
With ZFS, if I restore T1, I will loose T2.

So the idea would then be NOT to restore T1 but to zfs clone T1 as new dataset.
With this, T1 clone becomes the current dataset and so no interference with T2 and others.

HOWEVER, I wonder if after a while, multiple rollbacks will not finally affect the consistency of the ZFS dataset.
It could generate some "cross" datasets/snapshots...

Feedback welcome.

Thanks

**Comment by B3r3n06** [comment]
Digging a bit, I realize ZFS might be similar to BTRfs about snapshot and might be able to provide the same service.

ZFS stores its snapshots into MYdataset/.zfs/snapshot/[name].
Files are directly accessible here.

Now, it is possible to snapshot the snapshot ? ;-)
This way, changes would be performed on a copy of the snapshot, saving the original ?

Feedback still welcome :-)

**Comment by IvanVolosyuk** [comment]
You can zfs set readonly=on and snapshot twice - you will get two copies of
snapshot. You cannot snapshot the content of .zfs/snapshot/blah.

I used clones quite a bit. You can make a tree of clones if you want. The
tricky part with clones is to do incremental sends to preserve the tree
structure of clones. What I did is I made clones to be children of the
original. This way I could replicate the structure using 'zfs send -R' and
after that sent incremental updates to all clones independently. Not sure
how I can add more clones in this setup though.

**Comment by B3r3n06** [comment]
Hello Ivan,

Thanks for your answer.

In fact, I sense the blocking point is precisely the fact snapshots and thus clones are always dependant from a "master".
I got the same situation in BTRfs, but there snapshots were the same type of objects as the master was, and mountable wherever wanted.

To satisfy the need, solution was simple
/mydir -> snapshot S_T0 -> /snaphots/S_T0
/mydir -> snapshot S_T1 -> /snaphots/S_T1
/mydir -> snapshot S_T2 -> /snaphots/S_T2

When I needed to put S_T1 in place of the original /mydir, it was simple:
/snapshots/S_T1 -> snapshot mydir ->/mydir
simple as this because there is no link between mountpoint and volume name.

From this, since /mydir was a snapshot accessible as a directory, it was used for the need.

With this same logic, I was able to have versioning...into clones !
That is S_T1 -> /myCLONEdir

Maybe that is a bit confusing as expressed, I try to focus on how to satisfy the need rather than the way BTRfs or ZFS behaves from my understanding :-(

**Comment by richardelling** [comment]
The part you are missing is that the clone is a new dataset. So rather than
trying to replace /mydir
with a child of itself. Just use the child.
 -- richard

**Comment by B3r3n06** [comment]
Hello Richard,

I got you.

However, there are constraints to comply with :-)

Example, mydir must be kept but ok, a mountpoint could do the trick.

Also there is a hierarchical dependancy : /MYpool/MYdataset/MYsubdataset -> MYsubdataset being the clone, must be into the MYsubdataset subdirectory of MYdataset directory :-)

I know, the need is quite complex :-)

Brgrds

**Comment by IvanVolosyuk** [comment]
I kinda lost the context if you still talking about ZFS or BTRFS. In ZFS a clone can be anywhere in the hierarchy of the pool not necessary a child dataset of a primary dataset and you can reverse child / parent relationship with 'zfs promote' without moving/renaming any datasets.
