### ISSUE TITLE
ZED isn't updating the zfs-list.cache file

### ISSUE THREAD

**Issue by sunflsks** [openzfs/zfs#11330]
### System information
Arch Linux 5.9.13 with zfs-utils and module at version 2.0.0-1

### Describe the problem you're observing
Whenever I create a new dataset, change properties on an existing dataset, or something like that, the file in `/etc/zfs/zfs-list.cache/zroot` is not updated. This last change on the cache file was on December 1st, and I upgraded to ZFS 2.0.0 two days later so I think that ZFS 2.0.0 is part of the issue. I haven't updated my zpool yet, and I don't plan on doing so either so that may also be part of the problem.

### Describe how to reproduce the problem
Change the properties of any dataset or try to add a dataset. It won't update the `zfs-list.cache/zroot` file.

**Comment by Finermeerkat137** [comment]
As a temporary fix I just created a systemd oneshot service that runs `zfs mount -a` on startup.

**Comment by dmtrbm** [comment]
See #11164.

**Comment by InsanePrawn** [comment]
For the time being: remove `history_event` from `ZED_SYSLOG_SUBCLASS_EXCLUDE="..."` in your `/etc/zfs/zed.d/zed.rc` to fix.

**Comment by Finermeerkat137** [comment]
Thanks, I'll try that :)

**Comment by behlendorf** [comment]
Closing.  The fix in  #11347 was applied to the 2.0 and 2.1 branches.

**Comment by IntelligentesTierMaulApollo13** [comment]
A follow-up question: This bug then also needs to be taken into account when following the description on how to install a [Debian 11 on ZFS root](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html), correct? 

I failed to  get an updated cache (`/etc/zfs/zfs-list.cache/bpool`) and found this bug report while searching for a solution. /etc/zfs/zed.d/zed.rc contains the line `ZED_SYSLOG_SUBCLASS_EXCLUDE="history_event"`
