### ISSUE TITLE
OpenZFS RHEL8:Error in POSTIN scriptlet in rpm package zfs-dkms

### ISSUE THREAD

**Issue by Zaryob** [openzfs/zfs#11332]
## System information
Type | Version/Name
 --- | ---
Distribution Name	| Red Hat Enterprise 
Distribution Version	| 8.3 (Ootpa)
Linux Kernel	| 4.18.0-240.1.1.el8_3.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.5
SPL Version	|

### Describe the problem you're observing
I'm trying to install zfs on RHEL 8. I tried to install by following [the following way](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html#dkms) but POSTINT script cannot complated succesfully.

### Describe how to reproduce the problem

I tried to install zfs with selecting dkms way. But it give me that error.
```
....
  Komut dosyası yürütülüyor     : zfs-dkms-0.8.5-1.el8.noarch           113/114 
Removing old zfs-0.8.5 DKMS files...

------------------------------
Deleting module version: 0.8.5
completely from the DKMS tree.
------------------------------
Done.
Loading new zfs-0.8.5 DKMS files...
Building for 4.18.0-240.1.1.el8_3.x86_64
Building initial module for 4.18.0-240.1.1.el8_3.x86_64
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.8.5/build/make.log for more information.
uyarı: %post(zfs-dkms-0.8.5-1.el8.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package zfs-dkms
....
```

### Include any warning/errors/backtraces from the system logs
this is my make log. [make.log](https://github.com/openzfs/zfs/files/5683637/make.log)

**Comment by mskarbek** [comment]
[#11195](https://github.com/openzfs/zfs/issues/11195)

**Comment by truatpasteurdotfr** [comment]
it should be fixed fix 0.8.6, imho

**Comment by Zaryob** [comment]
I will look at it.

**Comment by tonyhutter** [comment]
@Zaryob try re-installing the zfs-release RPM.  The one I initially generated with the 0.8.6 release didn't have a `%post` fix that @behlendorf had put in the earlier zfs-release RPMs.  I just uploaded some new ones with the fix.
