### ISSUE TITLE
0.8.6 and CentOS-Stream

### ISSUE THREAD

**Issue by truatpasteurdotfr** [openzfs/zfs#11342]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| Stream (8)
Linux Kernel	|4.18.0-257.el8.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.6
SPL Version	|

### Describe the problem you're observing
4.18.0-257.el8.x86_64 unknown from configure script

### Describe how to reproduce the problem
- wget https://github.com/openzfs/zfs/releases/download/zfs-0.8.6/zfs-0.8.6.tar.gz
- tar xzvf zfs-0.8.6.tar.gz
- cd zfs-0.8.6/
- ./configure && make rpms
### Include any warning/errors/backtraces from the system logs

```
checking whether submit_bio is member of struct block_device_operations... checking whether blk_alloc_queue() expects request function... no
checking whether make_request_fn() returns void... no
checking whether make_request_fn() returns blk_qc_t... no
checking whether make_request_fn() returns int... configure: error:
        *** None of the expected "make_request_fn" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-0.8.6-1
        *** Compatible Kernels: 2.6.32 - 5.9

```

**Comment by truatpasteurdotfr** [comment]
According to the plan, 4.18.0-257.el8.x86_64 should look like what the RHEL 8.4 kernel will be based on.

**Comment by alexeynavarkin** [comment]
Got same error after centos upgrade.

**Comment by tendonut** [comment]
Ditto for me. Fresh CentOS Stream 8 install, unable to downgrade kernel to get to a working state.

**Comment by behlendorf** [comment]
PR #11374 has been opened against master with a fix for this.

**Comment by truatpasteurdotfr** [comment]
thx for #11374 (which applies fine on zfs-2.0.0):
```
tar xzf zfs-2.0.0.tar.gz && cd zfs-2.0.0 && wget https://github.com/openzfs/zfs/pull/11374.patch && patch -p1 -i 11374.patch
./autogen.sh && ./configure && make rpms
```
is adapting the PR for 0.8.6 is enough ?

**Comment by behlendorf** [comment]
Yes, it should be.  Although I haven't verified it myself.
