### ISSUE TITLE
Value of used increases over time for an empty pool

### ISSUE THREAD

**Issue by WhiteTrashLord** [openzfs/zfs#11340]
I installed zfs-2.0.0-1 on an Ubuntu 18.04 system to do some tests. I used this command to create the pool:
zpool create pool /dev/sdb -f

I enabled the zstd compression because I wanted to test how good the compression is.
I also changed the recordsize multiple times.
I added several small files. Then I deleted all files and added other files. I did this several times.
I noticed that the value for the property used ( command zfs get all ) slowly increased over time for a pool which has 0 files.

Example values ( both times there were no files in the pool):

used 648K
used 756K

I don't understand why it doesn't show 0K when there are 0 files in the pool.
But even more confusing is that the value increases over time. Maybe it is a bug?

**Comment by behlendorf** [comment]
Internally each filesystem will allocate a small amount of space for its own bookkeeping.  This is reflected in the used space and is why even after removing all the files some space is still used.  It may increase somewhat over time.
