### ISSUE TITLE
CPU Stall When Using compression=zstd-19

### ISSUE THREAD

**Issue by owenthewizard** [openzfs/zfs#11350]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| default/linux/amd64/17.1/no-multilib
Linux Kernel	| 5.4.80-gentoo-r1
Architecture	| x86_64
ZFS Version	| 2.0.0-r0-gentoo
SPL Version	| 2.0.0-r0-gentoo

### Describe the problem you're observing

While copying a large amount of files to a ZFS dataset with `compression=zstd-19`, dmesg reports:
```
rcu: INFO: rcu_sched self-detected stall on CPU
rcu:    4-....: (2098 ticks this GP) idle=90e/1/0x4000000000000002 softirq=3802/3802 fqs=993
        (t=2100 jiffies g=9065 q=2912)
```
See the dmesg.txt below for the full logs.

### Describe how to reproduce the problem

1. Create a dataset and set compression to zstd-19
`zfs create -o compress=zstd-19 pool/test-zstd-19`
2. Copy a large amount of files, in my case some data containing many JPEG images, some text files, some C sources files, some zip files .... to the dataset. In my case this was using `rsync` over `ssh`.
`rsync -arh --progress ./ [redacted]@[redacted]:/storage/`

### Include any warning/errors/backtraces from the system logs

[dmesg.txt](https://github.com/openzfs/zfs/files/5699617/dmesg.txt)

<br>

#### Please let me know if there is any more information I can provide that would be helpful.

**Comment by Ornias1993** [comment]
Thanks for the report!
> Please let me know if there is any more information I can provide that would be helpful.

- Could you share the amount of RAM and the CPU type?
- Be sure you aren't using ZSTD-19 with insufficient ram, it requires GIGABYTES just for itself.
- Be aware ZSTD-19 is mostly just included for reference and futureproofing, it has quite a few downsides. It also is not a very big improvement over something like ZSTD-9

**Comment by owenthewizard** [comment]
> Could you share the amount of RAM and the CPU type?

192 GB worth of DDR3 ECC RDIMMs running at 1333 MHz
2x Intel Xeon E5-2430L v2

**Comment by Ornias1993** [comment]
Okey, I got you: with that setup you dont give a flying duck about the CPU or RAM pressure of zstd-19.

That being said: you should als not run into Any hardware limits...

**Comment by Ornias1993** [comment]
@behlendorf This goes byond a performance issue, as with his setup he should not have the issue he is having.
I think retagging to "Defect" and "Triage Needed" might be warranted...

**Comment by owenthewizard** [comment]
I just transferred 14G of JPEGs and a few MP4s to my `zstd-19` dataset and did not encounter this issue.

**Comment by owenthewizard** [comment]
Closing this as I can not reliably re-create the issue.

**Comment by owenthewizard** [comment]
I was able to trigger this again by copying a large ISO to a dataset with `zstd-19`. Not sure if the problem is with ZFS to Broadcom's `tg3`.

For now I'll just avoid `zstd-19`.

[dmesg.txt](https://github.com/openzfs/zfs/files/6176412/dmesg.txt)
