### ISSUE TITLE
Clarify zfs_prefetch_disable

### ISSUE THREAD

**Issue by h1z1** [openzfs/zfs#11369]
### Ask your question!

The following was added as part of https://github.com/openzfs/zfs/commit/f664f1ee7fc9dd7101171f6518c67951cb5bd8cf:

```
	/*
	 * If we are overwriting a dedup BP, then unless it is snapshotted,
	 * when we get to syncing context we will need to decrement its
	 * refcount in the DDT.  Prefetch the relevant DDT block so that
	 * syncing context won't have to wait for the i/o.
	 */
	if (db->db_blkptr != NULL) {
		db_lock_type_t dblt = dmu_buf_lock_parent(db, RW_READER, FTAG);
		ddt_prefetch(os->os_spa, db->db_blkptr);
		dmu_buf_unlock_parent(db, dblt, FTAG);
```

Was  (or should),   there not be a check that dd is enabled at all?  Otherwise that code is hit wayy more often then it should just to end up effectively as a noop and is not affected by the zfsS_prefetch_disable parameter.

### Which portion of the codebase does your question involve?

zfs prefetch, more specifically in dedupe 

### Additional context

There are quite a few other codepaths where dd is still involved although it's not enabled.

It's also worth noting zfs_dedup_prefetch exists but is only used in ddt_prefetch.  Might be an option to consult.

**Comment by behlendorf** [comment]
> Should there not be a check that dd is enabled at all? 

I don't believe so.  Even if dedup is disabled we want to prefetch any previously written dedup'ed block pointer which need to be updated so they're available in sync'ing content.

**Comment by h1z1** [comment]
You won't prefetch that if dd prefetch is disabled though (zfs_dedup_prefetch) but you do take that path regardless and the lock.

**Comment by h1z1** [comment]
Closing.  Patched it locally a while ago.. problem fixed yay.
