### ISSUE TITLE
RHEL and Fedora users are vulnerable to MitM

### ISSUE THREAD

**Issue by dkoao** [openzfs/zfs#11366]
The wiki requires the users to install a repository's rpm that's transmitted over plain http. An attacker can simply replace this file in-transit with a subtly malicious one without the victim noticing.

**Comment by behlendorf** [comment]
The documentation also makes it clear the the repository and packages themselves are all secured by gpg signatures. You need to manually verify the fingerprint after installing the zfs-release package. Still, this question has come up before so I'll see about moving the `zfs-release` packages to a https address.

**Comment by dkoao** [comment]
>You need to manually verify the fingerprint after installing the zfs-release package

I think you misunderstood my point. My point is that the zfs-release package itself is transmitted over http, and an attacker can replace it easily with a malicious one, even if the GPG keys match after the installation.

**Comment by dkoao** [comment]
The package can keep dropping the correct repository configuration with the correct GPG key even if it has been altered.

**Comment by dkoao** [comment]
If you guys have something against HTTPS, just provide the hashes for the file on the wiki.

CentOS does a similar thing by providing the hashes [in the release notes](https://wiki.centos.org/action/show/Manuals/ReleaseNotes/CentOS8.2011?action=show&redirect=Manuals%2FReleaseNotes%2FCentOSLinux8#Verifying_Downloaded_Installation_Images).

**Comment by behlendorf** [comment]
I've moved the `zfs-release` packages to a secure https address at the zfsonlinux.org domain and updated the documentation accordingly. 

https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html
https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html

**Comment by dkoao** [comment]
Thank you very much for the quick response. I appreciate it a lot.
