### ISSUE TITLE
zfs-0.8.6 not build, ${CPP} is empty

### ISSUE THREAD

**Issue by el-dge** [openzfs/zfs#11360]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Slackware
Distribution Version	| current
Linux Kernel	| 5.4.83
Architecture	| x86_64
ZFS Version	| 0.8.6
SPL Version	| 0.8.6-1

### Describe the problem you're observing

./configure fails with :
```
checking kernel source directory... /usr/src/linux-5.4.83
checking kernel build directory... /usr/src/linux-5.4.83
checking kernel source version... ./configure: line 55754: -I: command not found
Not found
configure: error: 
        *** Cannot determine kernel version.
```
***${CPP} is empty***

$utsrelease (generated/utsrelease.h) and $kernelbuild (/usr/src/linux-5.4.83) is ok.
```
cat /usr/src/linux-5.4.83/include/generated/utsrelease.h
#define UTS_RELEASE "5.4.83"
```

$CC = gcc

The last time, for 0.8.5 no problems.

### Describe how to reproduce the problem
```
./autogen.sh
./configure
```
### Include any warning/errors/backtraces from the system logs

In config.log : 
```
configure:55629: checking kernel source directory
configure:55677: result: /usr/src/linux-5.4.83
configure:55689: checking kernel build directory
configure:55721: result: /usr/src/linux-5.4.83
configure:55724: checking kernel source version
configure:55757: result: Not found
configure:55759: error: 
        *** Cannot determine kernel version.

```

**Comment by rincebrain** [comment]
Do other external modules build against this kernel tree? Do other versions of ZoL?

**Comment by el-dge** [comment]
- Do other external modules build against this kernel tree? : no
- Do other versions of ZoL? I tested 0.8.5  which was working yesterday and does not compile either so I think it's more from me, sorry for the inconvenience. If it persists, I will reopen.

Thank you very much for your response and your tips.
