### ISSUE TITLE
configure error building against torvalds/linux@8653b778e454

### ISSUE THREAD

**Issue by rkitover** [openzfs/zfs#11387]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| unstable with profile default/linux/amd64/17.1/desktop/plasma/systemd
Linux Kernel	| linus git master at torvalds/linux@8653b778e454
Architecture	| amd64
ZFS Version	| git master at 0c763f76b
SPL Version	| git master at 0c763f76b

### Describe the problem you're observing

`./configure` bails out with an error:

```
checking whether REQ_FAILFAST_MASK is defined... yes
checking whether REQ_DISCARD is defined... no
checking whether REQ_FLUSH is defined... no
checking whether REQ_PREFLUSH is defined... yes
checking whether REQ_OP_DISCARD is defined... yes
checking whether REQ_OP_SECURE_ERASE is defined... yes
checking whether REQ_OP_FLUSH is defined... yes
checking whether bio->bi_opf is defined... yes
checking whether bio_set_op_attrs is available... yes
checking whether bio_set_dev() is available... yes
checking whether bio_set_dev() is GPL-only... yes
checking whether bio_end_io_t wants 1 arg... yes
checking whether bio->bi_status exists... yes
checking whether bio has bi_iter... yes
checking whether submit_bio() wants 1 arg... yes
checking whether current->bio_list exists... yes
checking whether blkg_tryget() is available... yes
checking whether blkg_tryget() is GPL-only... yes
checking whether blkdev_get_by_path() exists... yes
checking whether blkdev_put() exists... yes
checking whether blkdev_reread_part() exists... no
checking whether invalidate_bdev() exists... yes
checking whether lookup_bdev() wants 1 arg... no
checking whether lookup_bdev() wants 2 args... configure: error: 
        *** None of the expected "lookup_bdev()" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-2.0.0-rc1_297_g0c763f76b
        *** Compatible Kernels: 3.10 - 5.9
```

### Describe how to reproduce the problem

```bash
sh autogen.sh && ./configure --with-linux=/usr/src/linux
```

With the linux tree on git master at 8653b778e454.

**Comment by rkitover** [comment]
Fixed sha links.

**Comment by Ornias1993** [comment]
Maybe we should start enforcing linux kernel bugs to actually released (either rc, alpha or beta) kernels....
Are we now going to accept reports for kernel bugs in not-even-alpha kernels?!

**Comment by rkitover** [comment]
Just to be clear, I do not expect zfs to work perfectly with the git kernel, and no one does, this is just a report about something I noticed and may or may not be a starting point for further development.

I'm sorry I'm not familiar with the buildbot tasks right now.

If you feel this needs to be addressed, I can start looking into it, I've done some config/API related stuff previously although it has been a while.
