### ISSUE TITLE
zpool list shows vdev of same size as 127GB and sometime 128GB

### ISSUE THREAD

**Issue by justinpryzby** [openzfs/zfs#11395]
$ sudo lvs --units b # I realize that putting ZFS/LVM is discouraged.
```
  LV            VG              Attr       LSize         Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
...
  zfs2          data            -wi-ao---- 137438953472B
  zfs3          data            -wi-ao---- 137438953472B
```

$ sudo zpool list -
```
NAME         SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
zfs          254G   134G   121G        -         -    16%    52%  1.00x    ONLINE  -
  zfs2       127G  81.8G  45.2G        -         -    13%  64.4%      -  ONLINE
  zfs3       128G  52.2G  75.3G        -         -    20%  40.9%      -  ONLINE
```

=> Two vdevs of same size shown as different sizes.

### System information
Type | Version/Name
 --- | ---
Distribution Name	| Centos7
Distribution Version	| 7
Linux Kernel	| 3.10.0-1062.el7
Architecture	| x86_64
ZFS Version	| zfs-dkms-2.0.0-1.el7.noarch
SPL Version	| 2.0.0-1

**Comment by behlendorf** [comment]
Could you please run `zpool list -vp`.  This will output the exact size in bytes instead of the human readable version so we can double check they're actually the same size.  They _may_ be slightly different if ZFS determined they were not ideally aligned.

**Comment by justinpryzby** [comment]
Seems you're right.  So there's no issue then, unless someone wanted to also make visible the size of the device itself.  I guess by reading its size from the kernel (which would also show if the device has been "grown" without expanding pool's vdev).

$ zpool list -vp
NAME                SIZE         ALLOC          FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
zfs         273267294208  143865057792  129402236416        -         -     16     52   1.00    ONLINE  -
  zfs2      136365211648  87860267520  48504944128        -         -     13     64      -  ONLINE
  zfs3      136902082560  56004790272  80897292288        -         -     20     40      -  ONLINE

**Comment by behlendorf** [comment]
Great. then that explains it.  I think the `zpool list -p` option should be sufficient.  I'll go ahead and close this out.
