### ISSUE TITLE
PANIC when sending encrypted dataset with the raw flag

### ISSUE THREAD

**Issue by allthesebugsv2** [openzfs/zfs#11405]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debain (TrueNas Scale)
Distribution Version	|  11
Linux Kernel	| SMP Debian 5.9.1-1 (2020-10-17) 
Architecture	| x86_64
ZFS Version	| 2.0.0
SPL Version	| 2.0.0

### Describe the problem you're observing

My encrypted pool has been running without problems for months, including incoming sends from other non-encrypted pools.
However, trying to send any encrypted dataset from the pool to another pool, the send immediately becomes stuck and panic messages appear in the dmesg log. While the system remains responsive, the only way to reset the receiving pool into a working state is a reboot.

Note that both pools are local.
### Describe how to reproduce the problem
Using the following command triggers the error:
`zfs send -wp mpool/main/docker@autosnap_2020-12-23_18:45:14_monthly  |  zfs recv -Fdu bpool/mpool-backup`
Not using any receive parameters still triggers the error:
`zfs send -wp mpool/main/docker@autosnap_2020-12-23_18:45:14_monthly  |  zfs recv bpool/mpool-backup`

### Include any warning/errors/backtraces from the system logs
```
[ 7205.586818] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, &zio->io_bookmark, BP_GET_TYPE(bp), BP_GET_DEDUP(bp), BP_SHOULD_BYTESWAP(bp), salt, iv, mac, psize, zio->io_abd, eabd, &no_crypt)) failed (0 == 13)
[ 7205.587048] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, &zio->io_bookmark, BP_GET_TYPE(bp), BP_GET_DEDUP(bp), BP_SHOULD_BYTESWAP(bp), salt, iv, mac, psize, zio->io_abd, eabd, &no_crypt)) failed (0 == 13)
[ 7205.605688] PANIC at zio.c:4134:zio_encrypt()
[ 7205.605691] Showing stack for process 4335
[ 7205.624857] PANIC at zio.c:4134:zio_encrypt()
[ 7205.624859] Showing stack for process 4336
[ 7205.629540] CPU: 3 PID: 4335 Comm: z_wr_iss Tainted: P           OE     5.9.0-1-amd64 #1 Debian 5.9.1-1
[ 7205.652909] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./J5040-ITX, BIOS P1.60 01/17/2020
[ 7205.663136] Call Trace:
[ 7205.665748]  dump_stack+0x6b/0x88
[ 7205.669323]  spl_panic+0xd4/0xfc [spl]
[ 7205.673448]  zio_encrypt+0x740/0x800 [zfs]
[ 7205.677963]  ? zio_write_compress+0xcca/0x11a0 [zfs]
[ 7205.683424]  zio_execute+0xea/0x230 [zfs]
[ 7205.687762]  taskq_thread+0x24f/0x4b0 [spl]
[ 7205.692202]  ? wake_up_q+0xa0/0xa0
[ 7205.695936]  ? zio_execute_stack_check.constprop.0+0x10/0x10 [zfs]
[ 7205.702525]  ? taskq_thread_spawn+0x50/0x50 [spl]
[ 7205.707605]  kthread+0x11b/0x140
[ 7205.710986]  ? __kthread_bind_mask+0x60/0x60
[ 7205.715563]  ret_from_fork+0x1f/0x30
[ 7205.719403] CPU: 2 PID: 4336 Comm: z_wr_iss Tainted: P           OE     5.9.0-1-amd64 #1 Debian 5.9.1-1
[ 7205.729288] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./J5040-ITX, BIOS P1.60 01/17/2020
[ 7205.739389] Call Trace:
[ 7205.741945]  dump_stack+0x6b/0x88
[ 7205.745431]  spl_panic+0xd4/0xfc [spl]
[ 7205.749477]  zio_encrypt+0x740/0x800 [zfs]
[ 7205.753995]  ? zio_write_compress+0xcca/0x11a0 [zfs]
[ 7205.759368]  zio_execute+0xea/0x230 [zfs]
[ 7205.760653] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, &zio->io_bookmark, BP_GET_TYPE(bp), BP_GET_DEDUP(bp), BP_SHOULD_BYTESWAP(bp), salt, iv, mac, psize, zio->io_abd, eabd, &no_crypt)) failed (0 == 13)
[ 7205.763567]  taskq_thread+0x24f/0x4b0 [spl]
[ 7205.763573]  ? wake_up_q+0xa0/0xa0
[ 7205.763704]  ? zio_execute_stack_check.constprop.0+0x10/0x10 [zfs]
[ 7205.763716]  ? taskq_thread_spawn+0x50/0x50 [spl]
[ 7205.782875] PANIC at zio.c:4134:zio_encrypt()
[ 7205.787237]  kthread+0x11b/0x140
[ 7205.787239]  ? __kthread_bind_mask+0x60/0x60
[ 7205.787243]  ret_from_fork+0x1f/0x30
[ 7205.818996] Showing stack for process 4337
[ 7205.823349] CPU: 1 PID: 4337 Comm: z_wr_iss Tainted: P           OE     5.9.0-1-amd64 #1 Debian 5.9.1-1
[ 7205.833324] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./J5040-ITX, BIOS P1.60 01/17/2020
[ 7205.843576] Call Trace:
[ 7205.846199]  dump_stack+0x6b/0x88
[ 7205.849727]  spl_panic+0xd4/0xfc [spl]
[ 7205.853844]  zio_encrypt+0x740/0x800 [zfs]
[ 7205.858380]  ? zio_write_compress+0xcca/0x11a0 [zfs]
[ 7205.863773]  zio_execute+0xea/0x230 [zfs]
[ 7205.868019]  taskq_thread+0x24f/0x4b0 [spl]
[ 7205.872467]  ? wake_up_q+0xa0/0xa0
[ 7205.876176]  ? zio_execute_stack_check.constprop.0+0x10/0x10 [zfs]
[ 7205.882749]  ? taskq_thread_spawn+0x50/0x50 [spl]
[ 7205.887717]  kthread+0x11b/0x140
[ 7205.891174]  ? __kthread_bind_mask+0x60/0x60
[ 7205.895695]  ret_from_fork+0x1f/0x30
```

**Comment by allthesebugsv2** [comment]
As a small update: the send & receive works fine (with the above command) if done over the network to another client machine with the same receiving pool attached.

So for some reason the above error only occurs when both pools are attached to the same machine.

**Comment by simar0at** [comment]
I think I've got a very similar kind of problem when receiving a particular zfs send stream on Truenas 12.0 U1 core (FreeBSD):
```
VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, &zio->io_bookmark, BP_G ET_TYPE(bp), BP_GET_DEDUP(bp), BP_SHOULD_BYTESWflP(bp), salt, iv, mac, psize, zio->io_abd, eabd, &no_ crypt)) failed (0 == 13)

cpuid = 7

time = 1609775787

KDB: stack backtrace:

db_trace_self_urapper() at db_trace_self_urapper+0x2b/frame 0xfffffe00a0944990

vpanicO at vpanic+0xl7b/frame 0xfffffe00a09449e0

spl_panic() at spl_panic+0x3a/frame 0xfffffe00a0944a40

zio_encrypt() at zio_encrypt+0x543/frame 0xfffffe00a0944ad0

zio_execute() at zio_execute+0x6a/frame 0xfffffe00a0944b20

taskqueue_run_locked() at taskqueue_run_locked+0xl44/frame 0xfffffe00a0944b80 taskqueue_thread_loop() at taskqueue_thread_loop+0xb6/frame 0xfffffe00a0944bb0 fork_exit() at fork_exit+0x7e/frame 0xfffffe00a0944bf0 fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe00a0944bf0

	 trap 0, rip = 0, rsp = 0, rbp = 0 	

KDB: enter: panic [ thread pid 0 tid 101772 ]

Stopped at	kdb_enter+0x37: movq $0,0xl64afc6(Xrip)

db:0:kdb.enter.default> urite cn_mute 1 cn_mute	0
```
The whole dataset is old and started its life on ZoL 0.6.x but on another machine. It was upgraded over time to 2.0.0 rc. It was sent to be encrypted on its current location from another Linux machine without any panic on a OpenZFS 2.0.0 rc. All Linux machines are Ubuntu 18.04 (various kernels and ZoL versions)
The screen paniced a physical server so I replicated the situation on a VM. The above lines are from this VM.

**Comment by freqlabs** [comment]
This issue is in progress here https://jira.ixsystems.com/browse/NAS-107636

**Comment by rincebrain** [comment]
Reading that issue, it seems like this came from a TrueNAS-specific patch that was being carried, so this doesn't affect upstream and can be closed?

@freqlabs is that accurate?

**Comment by freqlabs** [comment]
TrueNAS SCALE (zfs-2.0) never had the issue that was present in CORE  (zfs-2.1), so the OP's issue seems like it should be different. I'm confused by their reporting it as zfs-2.0.0 on what is clearly SCALE based on the docker datasets. The ticket I linked was specific to SCALE and is closed now. I'll close this here under the assumption that it is no longer applicable.
