### ISSUE TITLE
zfs redact gives misleading error message when redaction snapshot is missing

### ISSUE THREAD

**Issue by Baltram** [openzfs/zfs#11426]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Ubuntu
Distribution Version	|20.10
Linux Kernel	|5.8.0-33-generic
Architecture	|x86_64
ZFS Version	|2.0.0-0york0~20.04 (from JonathonF PPA)
SPL Version	|2.0.0-0york0~20.04

### Describe the problem you're observing

When specifying a valid parent snapshot but a non-existent redaction snapshot, ```zfs redact``` produces a misleading error message indicating that the parent snapshot is missing (rather than the redaction snapshot).

### Describe how to reproduce the problem

```
zfs redact tank@valid_snapshot bookmark tank@non_existent_snapshot
```

**Comment by ahrens** [comment]
@pcd1193182 could you take a look at this?

**Comment by Baltram** [comment]
This bug is still present in version 2.1.1.

**Comment by pcd1193182** [comment]
I will take a look at this early next week and hopefully open a PR the same day.
