### ISSUE TITLE
zfs redact fails when dnodesize=auto

### ISSUE THREAD

**Issue by Baltram** [openzfs/zfs#11425]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Ubuntu
Distribution Version	|20.10
Linux Kernel	|5.8.0-33-generic
Architecture	|x86_64
ZFS Version	|2.0.0-0york0~20.04 (from JonathonF PPA)
SPL Version	|2.0.0-0york0~20.04

### Describe the problem you're observing

When creating a redaction bookmark on a pool with dnodesize=auto, ```zfs redact``` produces the following error message.

```redaction snapshot must be descendent of snapshot being redacted```

Despite this, a redaction bookmark is created and appears usable.
With dnodesize=legacy, no such error occurs.

### Describe how to reproduce the problem

```
modprobe brd rd_nr=1 rd_size=100000
zpool create -O dnodesize=auto -O mountpoint=/mnt/tank tank /dev/ram0
echo 123456 > /mnt/tank/sensitive
zfs snapshot tank@1
echo 000000 > /mnt/tank/sensitive
zfs snapshot tank@2
zfs redact tank@1 1_r tank@2
```

**Comment by ahrens** [comment]
@pcd1193182 Could you take a look at this?  note: `dnodesize=auto` is the same as `dnodesize=1k`, i.e. 2 slots.

**Comment by pcd1193182** [comment]
I will take a look at this when I get a moment, hopefully this week or next.

**Comment by pcd1193182** [comment]
I believe the issue here is that `dmu_object_next` doesn't correctly handle the case where `*objectp == -1` if we have large dnodes enabled. The fix is to immediately return `ESRCH` in that case. I'll open a PR with the fix soon if testing agrees with my conclusions.
