### ISSUE TITLE
zfs send -p w/compress=zstd causes "internal error" when received on older system

### ISSUE THREAD

**Issue by arm32let** [openzfs/zfs#11428]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| debian
Distribution Version	| 9
Linux Kernel	| 4.9.80
Architecture	| armv7
ZFS Version	| 2.0.0

### Describe the problem you're observing

zfs send/recv crash zfs on systems with old versions with no zstd support

### Describe how to reproduce the problem

* create fs with zstd on host with 2.0
* snapshot fs
* receive fs on host with zfs 0.8

### Include any warning/errors/backtraces from the system logs

```
root@host08:~# cat /tmp/a | zfs recv rpool/test
internal error: Invalid argument
Aborted (core dumped)
root@host08:~# 
```

**Comment by Ornias1993** [comment]
Without the send commands you used, no one is going to be able to say much about this.

**Comment by arm32let** [comment]
Although it is shockingly simple to reproduce here's "the send commands":

```
root@zfs20:~# zfs version
zfs-2.0.0-1
zfs-kmod-2.0.0-1
root@zfs20:~# ssh root@zfs08 zfs version
zfs-0.8.6-1
zfs-kmod-0.8.6-1
root@zfs20:~# zfs create -o compression=zstd testpool/fs
root@zfs20:~# zfs snap testpool/fs@s1
root@zfs20:~# zfs send -Levp testpool/fs@s1 > /tmp/a
full send of testpool/fs@s1 estimated size is 12.6K
total estimated size is 12.6K
root@zfs20:~# scp /tmp/a root@zfs08:/tmp/a
a                                100%   44KB  35.0MB/s   00:00    
root@zfs20:~# 
```

```
root@zfs08:~# zfs recv testpool/fs < /tmp/a
internal error: Invalid argument
Aborted (core dumped)
root@zfs08:~# 
```

**Comment by Ornias1993** [comment]
It isn't "shockingly simple" if you use flags to customise a send command. 
Here is your issue I think, from the manual:
-e
>  If the lz4_compress feature is active on the sending system, then the receiving system must have that feature enabled as well. 

I presume the same goes for ZSTD...

**Comment by devZer0** [comment]
yeah, but a program made to handle a stream of data should not crash if it receives "unexpected data"

**Comment by arm32let** [comment]
> Here is your issue I think, from the manual:
> I presume the same goes for ZSTD...

Your presumption is incorrect:
```
root@zfs20:~# zfs version
zfs-2.0.0-1
zfs-kmod-2.0.0-1
root@zfs20:~# zpool get feature@lz4_compress
NAME      PROPERTY              VALUE                 SOURCE
testpool  feature@lz4_compress  active                local
root@zfs20:~# ssh root@zfs08 zfs version
zfs-0.8.6-1
zfs-kmod-0.8.6-1
root@zfs20:~# ssh root@zfs08 zpool get feature@lz4_compress testpool
NAME      PROPERTY              VALUE                 SOURCE
testpool  feature@lz4_compress  disabled              local
root@zfs20:~# zfs create testpool/fs
root@zfs20:~# zfs snap testpool/fs@s1
root@zfs20:~# zfs send -e testpool/fs@s1 | ssh root@zfs08 zfs recv testpool/fs
cannot receive new filesystem stream: pool must be upgraded to receive this stream.
root@zfs20:~# 
```

```
root@zfs20:~# zfs create -o compression=zstd testpool/fs_zstd
root@zfs20:~# zfs snap testpool/fs_zstd@s1
root@zfs20:~# zfs send -Lvp testpool/fs_zstd@s1 | ssh root@zfs08 zfs recv testpool/fs
full send of testpool/fs_zstd@s1 estimated size is 12.6K
total estimated size is 12.6K
internal error: Invalid argument
root@zfs20:~# 
```

**Comment by Ornias1993** [comment]
Interesting indeed.
But considering your attitude, i’m off to focus on positive projects.

Good luck!

**Comment by ahrens** [comment]
It's unusual to be using `-e` (`--embed`) without `-c` (`--compressed`).  I wonder if that could be at play here.  @allanjude, could you take a look at this?

Also, maybe -e should imply -c, since I don't think there's any reason for it not to.  All releases that support embedded records also support compressed records.

**Comment by allanjude** [comment]
So when I modified the zfs send code, I added a special case for -e, if the zstd send-stream flag is not enabled, we will send zstd-compressed embedded block pointers as normal block pointers: https://github.com/openzfs/zfs/blob/master/module/zfs/dmu_send.c#L869

The invalid argument error is from the -p flag, where the send is including "compression=zstd" in the properties nvlist, but that is out-of-range for the ENUM on the 0.8.x side.

**Comment by allanjude** [comment]
> The invalid argument error is from the -p flag, where the send is including "compression=zstd" in the properties nvlist, but that is out-of-range for the ENUM on the 0.8.x side.

You should be able to resolve this by just adding `-o compress=lz4` or `-o compress=off` to the `zfs recv` command, to override the compression property so it doesn't have an invalid value.

**Comment by arm32let** [comment]
> It's unusual to be using -e (--embed) without -c (--compressed)

the issue occurs without `-e` so this doesn't even matter

> You should be able to resolve this by just adding -o compress=lz4 or -o compress=off to the zfs recv command, to override the compression property so it doesn't have an invalid value.

unfortunately this doesn't solve it either:

```
root@zfs20:~# zfs send -Lvp testpool/fs_zstd@s1 | ssh root@zfs08 zfs recv -o compress=off testpool/fs
full send of testpool/fs_zstd@s1 estimated size is 12.6K
total estimated size is 12.6K
internal error: Invalid argument
```

**Comment by secabeen** [comment]
Allan, did you typo the recommended argument?  I believe the -o flag should be `-o compression=off` or `-o compression=lz4`, not `-o compress=off|lz4`

**Comment by arm32let** [comment]
that doesn't make any difference, still broken:
```
root@zfs20:~# zfs send -Lvp testpool/fs_zstd@s1 | ssh root@zfs08 zfs recv -o compression=off testpool/fs
full send of testpool/fs_zstd@s1 estimated size is 12.6K
total estimated size is 12.6K
internal error: Invalid argument
```

**Comment by ahrens** [comment]
The problem occurs when receiving a `send -p` stream with an unrecognized property value (e.g. `compression=zstd` on an older release).  We'll look into handling this error more gracefully, with an informative warning/error message, and potentially backporting that (at least to the 2.0 branch).

We'll also look into why `receive -o compress=...` doesn't suppress the error.  I suspect it's related to this behavior (from the manpage): `Received properties are retained in spite of being overridden and may be restored with zfs inherit -S.`.  I don't think we would want to retain an unrecognized property value, so we may need to add a special case to not retain it if it is overridden (by `-o`/`-x`) and is not recognized.

**Comment by arm32let** [comment]
>  We'll look into handling this error more gracefully, with an informative warning/error message, and potentially backporting that (at least to the 2.0 branch).

That won't fix anything because the issue is occurring on the host with 0.8 installed.

**Comment by allanjude** [comment]
> 
> 
> > We'll look into handling this error more gracefully, with an informative warning/error message, and potentially backporting that (at least to the 2.0 branch).
> 
> That won't fix anything because the issue is occurring on the host with 0.8 installed.

Right, Matt's solution will make 0.8.next include these fixes, or at least an error message that tells the user what to do to move forward.

**Comment by arm32let** [comment]
So when we can expect this regression to be fixed in zfs-0.8.7?

**Comment by ahrens** [comment]
@arm32let there's no specific timeline for that.  The next step is for someone to implement the fix and open a PR against the master branch.

**Comment by arm32let** [comment]
This isn't going anywhere anytime soon and we can't keep systems without backups in production. Upgrading is not an option for us either due to all the outstanding bugs still plaguing newer zfs versions, so we moved away to a different storage platform.
