### ISSUE TITLE
Ubuntu Server 20.04.1 openZFS 2.0.1 - no zpool automatic import on reboot

### ISSUE THREAD

**Issue by Tualua** [openzfs/zfs#11450]
Hello!
Can't get ZFS pool automatic import to work

OS

    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

Kernel

    5.4.0-58-generic

Install

    wget https://github.com/openzfs/zfs/releases/download/zfs-2.0.1/zfs-2.0.1.tar.gz
    tar xf zfs-2.0.1.tar.gz
    cd zfs-2.0.1
    sh autogen.sh
    ./configure
    make -s -j$(nproc) deb-dkms deb
    dpkg -i zfs-dkms_2.0.1-1_amd64.deb zfs_2.0.1-1_amd64.deb libzfs4_2.0.1-1_amd64.deb libnvpair3_2.0.1-1_amd64.deb             
    libuutil3_2.0.1-1_amd64.deb

Enabled services

    systemctl enable zfs-import-cache
    systemctl enable zfs-import.target

    systemctl status zfs-import-cache
    ● zfs-import-cache.service - Import ZFS pools by cache file
         Loaded: loaded (/lib/systemd/system/zfs-import-cache.service; enabled; vendor preset: enabled)
         Active: inactive (dead)
           Docs: man:zpool(8)

    systemctl status zfs-import.target
    ● zfs-import.target - ZFS pool import target
         Loaded: loaded (/lib/systemd/system/zfs-import.target; enabled; vendor preset: enabled)
         Active: inactive (dead)

Imported pool then

    zpool set cachefile=/etc/zfs/zpool.cache data

data is my pool

After each reboot I have to manually import my pool. Is this a bug or I'm doing something wrong?

**Comment by morph027** [comment]
Using the latest [debian unstable packages](https://packages.debian.org/sid/zfs-dkms) (rebuild using `dpkg-buildpackage`) on 20.04 even w/ latest mainline kernel 5.10.6 the import works without any problems.

**Comment by gdevenyi** [comment]
ubuntu and debian packages by-default enable services on install. ZFS custom built packages do not, and the current instructions don't explain how to enable them.

I believe arch has this documented:
https://wiki.archlinux.org/index.php/ZFS#Automatic_Start

**Comment by Tualua** [comment]
> ubuntu and debian packages by-default enable services on install. ZFS custom built packages do not, and the current instructions don't explain how to enable them.
> 
> I believe arch has this documented:
> https://wiki.archlinux.org/index.php/ZFS#Automatic_Start

I'm sorry, did you read what I wrote? I said I enabled services

**Comment by URestrepo** [comment]
I do not know if your issue is similar to mine, but there seems to be an issue when drives are not detected fast enough and ZFS is imported before drives are seen by the system. 

There is a section in the Arch Wiki:
https://wiki.archlinux.org/index.php/ZFS#Pool_cannot_be_found_while_booting_from_SAS/SCSI_devices
