### ISSUE TITLE
zfs destroy <snapshot>% destroys all later snapshots

### ISSUE THREAD

**Issue by snsb-seifert** [openzfs/zfs#11479]
### System information

gentoo
kernel 4.19.57
zfs 0.8.1

### Description
zfs destroy snapshot with the % syntax to destroy consecutive snapshots will destroy all following snapshots if the second snapshot is not given.

### Example:
filesystem with snapshots:
snapshotA
snapshotB
snapshotC

zfs destroy pool/filesystem@snapshotA%

will destroy all snapshots from snapshotA to snapshotC

### expected
According to the man-pages a not given second snapshot after the % sign is not allowed and should be rejected.

**Comment by AttilaFueloep** [comment]
Looks like you're referring to an outdated man-page version. `zfs-destroy(8)` states:

```
An inclusive range of snapshots may be specified by separating the first and last
snapshots with a percent sign.  The first and/or last snapshots may be left blank, 
in which case the filesystem's oldest or newest snapshot will be implied.
```

**Comment by AttilaFueloep** [comment]
Actually even the old zfs-0.6.5 zfs(8) man page contains that paragraph.

**Comment by snsb-seifert** [comment]
Yes, sorry.
I just looked at the call syntax

```zfs destroy [-Rdnprv] filesystem|volume@snap[%snap[,snap[%snap]]]...```

which seems that % is always followed by a snapshot name.
I didn't read the paragraph. (maybe in some kind of panic...)

Sorry for the inconvenieance.

**Comment by AttilaFueloep** [comment]
No problem.
