### ISSUE TITLE
zfs-dkms conflicts on Ubuntu 20.04

### ISSUE THREAD

**Issue by zmiguel** [openzfs/zfs#11496]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu 
Distribution Version	| 20.04.1 LTS
Linux Kernel	|   5.4.0-62-generic
Architecture	|  amd64
ZFS Version	|  2.0.1-1
SPL Version	|  2.0.1-1

### Describe the problem you're observing
I'm unable to get zfs-dkms to work, I get conflicts when building and installing from source

### Describe how to reproduce the problem
After building ZFS from source as per [the doc page](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html) and installing with the `sudo make install; sudo ldconfig; sudo depmod` command zfs is only installed for the currently installed kernel version, this is mostly fine. But after a kernel update and reboot zfs stops working. This is not ideal on a server/nas environment like the one I'm using.

I don't notice any errors when installing with the command above, but when installing from the built .bed files I get this error: 
```
Unpacking zfs-dkms (2.0.1-1) ...
dpkg: error processing archive zfs-dkms_2.0.1-1_amd64.deb (--install):
 trying to overwrite '/usr/src/zfs-2.0.1/include/cityhash.h', which is also in package kmod-zfs-devel 2.0.1-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 zfs-dkms_2.0.1-1_amd64.deb
```

output of `sudo dkms status`:
```
nvidia, 455.45.01, 5.4.0-62-generic, x86_64: installed
```
I've tried to uninstall everything using the uninstall command in the docs, reboot, install again it that didn't fix it.
I've tried reinstalling only the non -devel packages, also got the same error.
Deleting the file also doesn't work

---

Am I doing something wrong? What could I do to fix this?

Thank you.

**Comment by AllKind** [comment]
Looks like you have the kmod packages installed and want to also install the dkms packages.
Get rid of those and install dkms only:
https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html

**Comment by AllKind** [comment]
You could also use this ppa:
https://launchpad.net/~jonathonf/+archive/ubuntu/zfs

**Comment by zmiguel** [comment]
Thank you @AllKind! After a clean of all zfs things on my system and build+install from that link it worked. ZFS is now using DKMS.

Issue fixed, maybe adding some dkms info on the 'building zfs' page would be useful for other people.

**Comment by zmiguel** [comment]
Sorry for reopening this, but after installing I've lost the ability to mount pools on boot. zfs-zed isn't installed and the `/etc/default/zfs` file is being ignored.

If I try to install zfs-zed from apt it tries to remove zfs.

Couldn't find any help about this online.

@AllKind any ideas on what to do?

**Comment by AllKind** [comment]
I think you need to manually enable systemd units. (that is when compiling from source)
`systemctl list-units |grep -i zfs`

This is how it looks for me:

>   zfs-import-cache.service                                                                                                                             loaded active     exited    Import ZFS pools by cache file                                                                             
  zfs-load-module.service                                                                                                                              loaded active     exited    Install ZFS kernel module                                                                                  
  zfs-mount.service                                                                                                                                    loaded active     exited    Mount ZFS filesystems                                                                                      
  zfs-share.service                                                                                                                                    loaded active     exited    ZFS file system shares                                                                                     
  zfs-volume-wait.service                                                                                                                              loaded active     exited    Wait for ZFS Volume (zvol) links in /dev                                                                   
  zfs-zed.service                                                                                                                                      loaded active     running   ZFS Event Daemon (zed)                                                                                     
  zfs-import.target                                                                                                                                    loaded active     active    ZFS pool import target                                                                                     
  zfs-volumes.target                                                                                                                                   loaded active     active    ZFS volumes are ready                                                                                      
  zfs.target                                                                                                                                           loaded active     active    ZFS startup target                                                                                         

list the content of the zfs .deb created, to see that zed should be there:
`dpkg -c zfs_2.0.1-1_amd64.deb`

**Comment by AllKind** [comment]
> /etc/default/zfs file is being ignored.
What was your prefix during configure? (defaults to /usr/local).
Really you should use the ppa...

**Comment by zmiguel** [comment]
I'll probably end up switching to the ppa... but here are the outputs from that:

`systemctl list-units |grep -i zfs` 

>   zfs-import-cache.service                                                                                                       loaded active exited    Import ZFS pools by cache file                                                     
>   zfs-zed.service                                                                                                                loaded active running   ZFS Event Daemon (zed)                                                             
>   zfs-import.target                                                                                                              loaded active active    ZFS pool import target                                                             
>   zfs.target                                                                                                                     loaded active active    ZFS startup target                                                                 

and on `dpkg -c zfs_2.0.1-1_amd64.deb` I can see `/etc/default/zfs` and no other file like this one.

I didn't set any prefix, used the default options like before and it was working. In fact not single file is added to /usr/local/

**Comment by AllKind** [comment]
> In fact not single file is added to /usr/local/

They'd be in /usr/local/{etc,sbin,...}

`systemctl cat zfs-import-cache.service`

There you'll see the actual command (and the zpool bin path) for importing.

`zpool get cachefile`

Shows the cache file that is set.

**Comment by zmiguel** [comment]
> They'd be in /usr/local/{etc,sbin,...}

Then one would assume they are in /usr/local/etc/default/zfs, when they are not, the 2 zfs related folders there don't have any files related to /etc/default/zfs

> There you'll see the actual command (and the zpool bin path) for importing.
> 
> `zpool get cachefile`
> 
> Shows the cache file that is set.

I don't see how this is relevant to the issue, could you please explain? The pool is imported fine, but the `zfs mount -a` command is not run when the system starts.

And considering I didn't change anything directory settings when I compiled, how come it worked without dkms, but now with dkms build it stopped working?

**Comment by AllKind** [comment]
Maybe try to enable zfs-mount.service.
`systemctl enable zfs-mount.service`
