### ISSUE TITLE
Trouble Importing with -T option: one or more devices is currently unavailable

### ISSUE THREAD

**Issue by cousins** [openzfs/zfs#11504]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| CentOS 
Distribution Version	| 6.7  (I know! it's an old system on an inside system not accessible directly)
Linux Kernel	|  2.6.32-696.1.1
Architecture	| x86_64
ZFS Version	|  0.6.5.9-1
SPL Version	|  0.6.5.9-1

I'm in a similar boat as #7808. Trying to revert back to a previous TXG but getting the message `cannot import pool40: one or more devices is currently unavailable`

I destroyed some snapshots a couple of days ago on a backup system and now I realize that I'd like to get them back. I have found a txg from the command:

`zdb -hhe pool40`

and it shows:

```
...
  history zone: 'linux'
  history who: 0
  history time: 1611072080
  history hostname: 'nfs4.localdomain'
unrecognized record:
  dsname: 'pool40/home@2020-09-01'
  dsid: 6654
  history internal str: ''
  internal_name: 'destroy'
  history txg: **38984040**
  history time: 1611072081
  history hostname: 'nfs4.localdomain'
unrecognized record:
  ioctl: 'destroy_snaps'
  in_nvl:
      snaps:
          pool40/home@2020-09-01
  history zone: 'linux'
  history who: 0
  history time: 1611072083
  history hostname: 'nfs4.localdomain'
2021-01-19.11:01:23 zfs destroy pool40/home@2020-09-01
  history command: 'zfs destroy pool40/home@2020-09-01'
...
```

I tried reverting to it by exporting the pool and then importing with -T for that txg  but it gave the dreaded `cannot import pool40: one or more devices is currently unavailable` message.

So, I wondered about the Uber blocks and tried to list them with 
```
[root@nfs4 /]# zdb -e pool40 -ul
--------------------------------------------
LABEL 0
--------------------------------------------
failed to read label 0
--------------------------------------------
LABEL 1
--------------------------------------------
failed to read label 1
--------------------------------------------
LABEL 2
--------------------------------------------
failed to read label 2
--------------------------------------------
LABEL 3
--------------------------------------------
failed to read label 3

```

Then I tried listing them from devices and got better results with four LABEL sections and 32 Uberblocks but they are mostly from today (maybe from exporting and importing?) but there are actually a few from September. Does that give hope that there is a chance I can roll back to a transaction from January 19?:

```
Uberblock[20]
	magic = 0000000000bab10c
	version = 5000
	txg = 39037716
	guid_sum = 8620789707633366463
	timestamp = 1611358064 UTC = Fri Jan 22 18:27:44 2021
Uberblock[21]
	magic = 0000000000bab10c
	version = 5000
	txg = 37162741
	guid_sum = 8620789707633366463
	timestamp = 1601393839 UTC = Tue Sep 29 11:37:19 2020
Uberblock[22]
	magic = 0000000000bab10c
	version = 5000
	txg = 37162774
	guid_sum = 8620789707633366463
	timestamp = 1601394021 UTC = Tue Sep 29 11:40:21 2020
Uberblock[23]
	magic = 0000000000bab10c
	version = 5000
	txg = 39037655
	guid_sum = 8620789707633366463
	timestamp = 1611357737 UTC = Fri Jan 22 18:22:17 2021
Uberblock[24]
	magic = 0000000000bab10c
	version = 5000
	txg = 39037720
	guid_sum = 8620789707633366463
	timestamp = 1611358085 UTC = Fri Jan 22 18:28:05 2021
Uberblock[25]
	magic = 0000000000bab10c
	version = 5000
	txg = 39037689
	guid_sum = 8620789707633366463

```

This backup system hasn't been updated in quite a while. As in: 0.6.5.9-1. Would it make sense to update now? Or try to deal with it with the tools that were available then? I didn't see any answer to the -T problem so I'm wondering if it has been fixed and maybe I can try a newer version of ZFS to make it work. 

Thanks for your help.

**Comment by rcproam** [comment]
Encountered same issue on Debian 11 with much newer kernel/module detailed here:

https://github.com/openzfs/zfs/issues/7808#issuecomment-1016831972
