### ISSUE TITLE
Checksum errors on all drives with draid

### ISSUE THREAD

**Issue by lutorm** [openzfs/zfs#11510]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Centos
Distribution Version	| 8.1
Linux Kernel	| 4.18.0-147.8.1.el8_1.x86_64
Architecture	| x86_64
ZFS Version	| master (60a2434b295f395bbedcec2c4cd6a54530edf29a)
SPL Version	| master (60a2434b295f395bbedcec2c4cd6a54530edf29a)

### Describe the problem you're observing

I wanted to try out turning my 6x8tb raidz2 array into a draid. Built rpms from the current master and installed them. Failed two drives on the raidz2 and turned those into a mirror, sent all the data over to it (it fit), and destroyed the raidz2. Created a draid2:3d:1s with two missing drives using two sparse files  loopbacks instead:

```
zpool create -f test draid2:3d:1s:6c /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJDA6VL /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VGJ7UJRG /dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VJH4USWX /dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VJH4WB2X /dev/loop1 /dev/loop2
```

Immediately failed the two loopbacks.
```zpool offline -f test loop1```
```zpool offline -f test loop2```

and sent the data over to the new draid pool. Once send was complete, destroyed the 2-drive mirror and replaced the failed loopbacks with them:
```zpool replace test loop1 /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAK5NSML```
```zpool replace test loop2 /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VGH8ZVGG```

At that point, the pool resilvered and I thought everything was A-ok. However, then I tried a scrub. Immediately the VAK5NSML drive got thrown out on too many checksum errors. No read or write errors from the drive.

The pool resilvered, I tried a long smart self-test on that failed drive and it passed. Tried clearing the errors, the pool  put the drive back in use and resilvered, no errors. Tried a scrub again, same drive gets kicked out on checksum errors.

At this point I assume that drive is bad and offlined it and took it off to run WDC's diagnostics on it on another system. The pool resilvered and then started a scrub. Now all hell breaks loose and all drives show checksum errors and data corruption:

```
  pool: data
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub in progress since Sat Jan 23 16:02:11 2021
        7.09T scanned at 374M/s, 6.97T issued at 367M/s, 11.9T total
        1.05M repaired, 58.71% done, 03:53:20 to go
  scan: resilvered (draid2:3d:6c:1s-0) 2.66T in 04:30:11 with 0 errors on Sat Jan 23 16:02:11 2021
config:

        NAME                                     STATE     READ WRITE CKSUM
        data                                     DEGRADED     0     0     0
          draid2:3d:6c:1s-0                      DEGRADED     0     0     0
            ata-WDC_WD80EFAX-68KNBN0_VAJDA6VL    ONLINE       0     0 40.8K  (repairing)
            ata-WDC_WD80EFAX-68KNBN0_VGJ7UJRG    DEGRADED     0     0 38.9K  too many errors  (repairing)
            ata-WDC_WD80EFZX-68UW8N0_VJH4USWX    ONLINE       0     0 31.0K  (repairing)
            ata-WDC_WD80EFZX-68UW8N0_VJH4WB2X    ONLINE       0     0 35.3K  (repairing)
            spare-4                              DEGRADED     0     0 46.8K
              ata-WDC_WD80EFAX-68KNBN0_VAK5NSML  OFFLINE      0     0 1.13K
              draid2-0-0                         ONLINE       0     0     0  (repairing)
            ata-WDC_WD80EFAX-68KNBN0_VGH8ZVGG    DEGRADED     0     0 41.4K  too many errors  (repairing)
        logs
          vg_krypton-zil                         ONLINE       0     0     0
        cache
          sdf                                    ONLINE       0     0     0
        spares
          draid2-0-0                             INUSE     currently in use

errors: 25763 data errors, use '-v' for a list
```

These drives are not all on the same controller and they've been running the raidz2 without errors for months, so it really seems like a remarkable coincidence if this is unrelated to using the new features on master.

### Describe how to reproduce the problem

I'm not sure whether the above sequence of events will reproduce the problem if I perform them again, given all the resilvers and scrubs it's a several day operation. If there are any specific tests you'd like me to perform, I'd be happy to, but I do need the pool 

### Include any warning/errors/backtraces from the system logs

There are no errors related to this in the logs I can see.

**Comment by IvanVolosyuk** [comment]
FYI @behlendorf 
I was able to consistently reproduce the first part with one drive having errors in a qemu VM. Somehow I couldn't use full disks for draid, but managed to reproduce with partitions instead (zfs master @ge2870fb24):
```
(none) / # truncate -s 1G /tmp/loop1
(none) / # truncate -s 1G /tmp/loop2
(none) / # losetup /dev/loop1 /tmp/loop1
(none) / # losetup /dev/loop2 /tmp/loop2
(none) / # zpool create -f test draid2:3d:1s:6c /dev/sda1 /dev/sdb1 /dev/sdc1 /dev/sdd1 /dev/loop1 /dev/loop2
(none) / # zpool status
  pool: test
 state: ONLINE
config:

        NAME                 STATE     READ WRITE CKSUM
        test                 ONLINE       0     0     0
          draid2:3d:6c:1s-0  ONLINE       0     0     0
            sda1             ONLINE       0     0     0
            sdb1             ONLINE       0     0     0
            sdc1             ONLINE       0     0     0
            sdd1             ONLINE       0     0     0
            loop1            ONLINE       0     0     0
            loop2            ONLINE       0     0     0
        spares
          draid2-0-0         AVAIL

errors: No known data errors
(none) / # zpool offline test loop1
(none) / # zpool offline test loop2
(none) / # cp /bin/* /test/
(none) / # zpool replace test loop1 /dev/sde1
(none) / # zpool replace test loop2 /dev/sdf1
(none) / # zpool status
  pool: test
 state: ONLINE
  scan: resilvered 6.58M in 00:00:00 with 0 errors on Mon Jan 25 01:27:04 2021
config:

        NAME                 STATE     READ WRITE CKSUM
        test                 ONLINE       0     0     0
          draid2:3d:6c:1s-0  ONLINE       0     0     0
            sda1             ONLINE       0     0     0
            sdb1             ONLINE       0     0     0
            sdc1             ONLINE       0     0     0
            sdd1             ONLINE       0     0     0
            sde1             ONLINE       0     0     0
            sdf1             ONLINE       0     0     0
        spares
          draid2-0-0         AVAIL

errors: No known data errors
(none) / # zpool scrub test
(none) / # zpool status
  pool: test
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
        attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
        using 'zpool clear' or replace the device with 'zpool replace'.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-9P
  scan: scrub repaired 6.05M in 00:00:01 with 0 errors on Mon Jan 25 01:27:16 2021
config:

        NAME                 STATE     READ WRITE CKSUM
        test                 ONLINE       0     0     0
          draid2:3d:6c:1s-0  ONLINE       0     0     0
            sda1             ONLINE       0     0     0
            sdb1             ONLINE       0     0     0
            sdc1             ONLINE       0     0     0
            sdd1             ONLINE       0     0     0
            sde1             ONLINE       0     0   203
            sdf1             ONLINE       0     0     0
        spares
          draid2-0-0         AVAIL

errors: No known data errors
```

**Comment by lutorm** [comment]
Two more pieces of information that may or may not be related:

- The only file that zpool says has had errors is a zvol hosting NTFS that I was experimenting with, so it's had constant writes to it the whole time this was going on. The approx 8TB of preexisting data on the pool appears not to have been corrupted.
- Looking through the logs, I noted that oom-killer had fired 3 times, twice on httpd and once on duplicity. I've never noticed oom-killer doing anything before on this system, although I haven't looked either. The machine has 16GB ram.

**Comment by behlendorf** [comment]
@lutorm @IvanVolosyuk thanks for the detailed report.   We recently uncovered an issue which may explain what you're seeing. Would it be possible for you to apply the patch from #11489 and see if you're still able to reproduce the issue.

**Comment by IvanVolosyuk** [comment]
#11489 fixes my qemu test.

**Comment by lutorm** [comment]
I will try, I'm having a very hard time building the custom rpms. 9 times out of 10 rpmbuild segfaults during the build and corrupts my rpm database...

**Comment by IvanVolosyuk** [comment]
You just need a patched kernel or kernel module.

**Comment by lutorm** [comment]
Ok applied the patch and re-added the offlined drive since it tested out fine. Resilver and scrub completed without errors, but strangely enough the spare is still in use:

```
[root@krypton ~]# zpool status
  pool: data
 state: ONLINE
  scan: scrub repaired 0B in 11:31:24 with 0 errors on Sun Jan 24 23:48:39 2021                                                             
config:

        NAME                                     STATE     READ WRITE CKSUM                                                                 
        data                                     ONLINE       0     0     0                                                                 
          draid2:3d:6c:1s-0                      ONLINE       0     0     0                                                                 
            ata-WDC_WD80EFAX-68KNBN0_VAJDA6VL    ONLINE       0     0     0                                                                 
            ata-WDC_WD80EFAX-68KNBN0_VGJ7UJRG    ONLINE       0     0     0                                                                 
            ata-WDC_WD80EFZX-68UW8N0_VJH4USWX    ONLINE       0     0     0                                                                 
            ata-WDC_WD80EFZX-68UW8N0_VJH4WB2X    ONLINE       0     0     0                                                                 
            spare-4                              ONLINE       0     0     0                                                                 
              ata-WDC_WD80EFAX-68KNBN0_VAK5NSML  ONLINE       0     0     0                                                                 
              draid2-0-0                         ONLINE       0     0     0                                                                 
            ata-WDC_WD80EFAX-68KNBN0_VGH8ZVGG    ONLINE       0     0     0                                                                 
        logs
          vg_krypton-zil                         ONLINE       0     0     0                                                                 
        cache
          sdf                                    ONLINE       0     0     0                                                                 
        spares
          draid2-0-0                             INUSE     currently in use                                                                 

errors: No known data errors
```
Shouldn't the spare be available again since all the drives are present now?

**Comment by behlendorf** [comment]
@lutorm normally it will automatically detach itself when resilvering to the new replacement device.  I'm not quite sure why that didn't happen in this case.  You can manually detach the space which is still in use according to your `zpool status` output by running `zpool detach data draid2-0-0`.

**Comment by IvanVolosyuk** [comment]
I also saw this in my setup. The spare didn't detach automatically and I
successfully detached it manually. I thought auto detaching requires zed,
but I was in single user mode when doing resilver.
