### ISSUE TITLE
New try on Updating to Version 2 on Ubuntu 20.10 with Kernel 5.8.0-41

### ISSUE THREAD

**Issue by nicedevil007** [openzfs/zfs#11556]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.10
Linux Kernel	| 5.8.0-41
Architecture	| x64
ZFS Version	| 0.8.4-1ubuntu11
SPL Version	| 0.8.4-1ubuntu11

### Describe the problem you're observing
I'm trying to update to Version 2.0.2 right now and the install runs til the end and then I check again which version am I running... still the old one.

### Describe how to reproduce the problem
```
apt update
apt install zfsutils-linux
```
Was doing this because of the wiki I found here: https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/index.html

**Comment by AllKind** [comment]
Well, you won't get version 2.0.2 from ubuntu I guess. It was released like 5 hours ago. And I don't think they'll do a major upgrade in this release cycle.
You can follow this guide to install the newest version:
https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
Make sure to uninstall the ubuntu packages before installing the custom build.

**Comment by nicedevil007** [comment]
@AllKind thank you very much, I followed the steps and I'm struggling with the uninstallation of zfs that is provided by ubuntu itself.

```root@ubuntu:~/ZOL/zfs-2.0.2# apt remove --purge  zfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  zfs*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 4,799 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 224444 files and directories currently installed.)
Removing zfs (2.0.2-1) ...
Processing triggers for man-db (2.9.3-2) ...
(Reading database ... 224175 files and directories currently installed.)
Purging configuration files for zfs (2.0.2-1) ...
dpkg: warning: while removing zfs, directory '/usr/lib/systemd/system-preset' not empty so not removed
dpkg: warning: while removing zfs, directory '/usr/lib/systemd/system-generators' not empty so not removed
dpkg: warning: while removing zfs, directory '/usr/lib/systemd/system' not empty so not removed
dpkg: warning: while removing zfs, directory '/etc/zfs' not empty so not removed```

After this I do a "check":

```root@ubuntu:~/ZOL/zfs-2.0.2# zfs version
zfs-0.8.4-1
zfs-kmod-0.8.4-1ubuntu11```

And then I tryed again to remove ZFS with the following error:

```root@ubuntu:~/ZOL/zfs-2.0.2# apt remove zfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'zfs' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

So how can I get rid of the version 0.8.4?

Oh and an other question, do I need the KMOD or DKMS part of this "DIY guide" (or maybe both?)?

**Comment by AllKind** [comment]
> dpkg: warning: while removing zfs, directory '/usr/lib/systemd/system-preset' not empty so not removed

Thats ok, you don't want to remove the systemd directories ;)

`apt search zfs|grep "^i"`
Will show you the zfs packages still installed.
You can purge them in one with something like this:
`sudo apt purge $(apt search zfs|grep "^i"| awk '{ print $2 }')`
Reboot (more easy), or remove the still loaded zfs kernel modules.
Then install the dkms. Kmods are only built for one specific kernel and will not be available once you upgrade your kernel.

**Comment by nicedevil007** [comment]
@AllKind 

mhhh I did both of your "onliners" without success:

```
root@ubuntu:~/ZOL/zfs-2.0.2# sudo systemctl stop docker
root@ubuntu:~/ZOL/zfs-2.0.2# sudo zpool export storage
root@ubuntu:~/ZOL/zfs-2.0.2#  sudo apt search zfs|grep "^i"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

root@ubuntu:~/ZOL/zfs-2.0.2# sudo apt purge $(apt search zfs|grep "^i"| awk '{ print $2 }')

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

now?

**Comment by AllKind** [comment]
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

So nothing is installed any more...
Install.. reboot...

**Comment by nicedevil007** [comment]
Nope it is still installed... I can still enter zfs version. It didn't uninstall it, that was what I would like to show you.
My friend that deployed it last year told me that he compiled it so it is located under /usr/local

Is there a way to uninstall it properly with a "oneliner"?

**Comment by nicedevil007** [comment]
@AllKind 

so beeing testing a lot with uninstalling, reinstalling, compiling and so on. What I found out all the time after installation is that the kmod 0.8.4 was still present.

And this will always been loaded after reboot.

```
root@ubuntu:~# dmesg | grep -i zfs
[    4.324772] systemd[1]: Reached target ZFS startup target.
[    6.427113] ZFS: Loaded module v0.8.4-1ubuntu11, ZFS pool version 5000, ZFS filesystem version 5
```

Friend also told me to try to rebuild initramfs

```
root@ubuntu:~# update-initramfs -u
update-initramfs: Generating /boot/initrd.img-5.8.0-41-generic
I: The initramfs will attempt to resume from /dev/dm-0
I: (/dev/mapper/ubuntu--vg-ubuntu--lv)
I: Set the RESUME variable to override this.
```

And the version that was shown to me looks always the same:

```
root@ubuntu:~/ZOL/zfs-2.0.2# zfs version
zfs-2.0.2-1
zfs-kmod-0.8.4-1ubuntu11
```

Seaching for installed dpkg packages was fine (I mean I can't find any except Sanoid which is fine)

```
root@ubuntu:~# dpkg -l | grep -i zfs
rc  sanoid                                     2.0.3-2                           all          Policy-driven ZFS snapshot management and replication tool
```

Maybe someone else got an Idea on how to get rid of the "old" kmod version?

**Comment by AllKind** [comment]
delete the directory /lib/modules/$(uname -r)/extra/zfs
rebuild your initramfs
reboot

**Comment by AllKind** [comment]
just weird that on ubuntu 20.10 you cannot pipe the output of apt, while in linux mint 19.x, which is based on ubuntu 18.04 you can.

**Comment by nicedevil007** [comment]
> delete the directory /lib/modules/$(uname -r)/extra/zfs
> rebuild your initramfs
> reboot

I tryed to find the package, and it wasn't inside the "extra" folder by any reason.

```
root@ubuntu:/lib/modules# find /lib/modules -name zfs
/lib/modules/5.8.0-38-generic/kernel/zfs
/lib/modules/5.8.0-41-generic/kernel/zfs
```

save to remove it there as well? :D
