### ISSUE TITLE
META file in zfs-2.0-release was updated with new zfs version but max kernel is still 5.10

### ISSUE THREAD

**Issue by ljmanz** [openzfs/zfs#11616]
### System information

Type | Version/Name
 --- | ---
ZFS Version	| 2.0.3

### Describe the problem you're observing

The META file was tagged for release 2.0.3, the version number was updated but the maximum kernel version is still on 5.10:

https://github.com/openzfs/zfs/commit/65a89d9f499da5602b25e91bf0bf849fdf0e8776#

The release page says that 2.0.3 supports up to kernel 5.11:

https://github.com/openzfs/zfs/releases/tag/zfs-2.0.3

**Comment by behlendorf** [comment]
The 2.0.3 release was tagged prior to the final 5.11 kernel release.  However, it does contain all of the needed compatibility patches and will work fine with the 5.11 kernel.  We updated the documentation in the release notes make it clear it was compatible.
