### ISSUE TITLE
no import to special TXG in readonly=on

### ISSUE THREAD

**Issue by ikozhukhov** [openzfs/zfs#11634]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| DilOS
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	|
SPL Version	|

### Describe the problem you're observing
we have attached 2 servers to one JBOD by LSI cables.
we have imported pool on one server in original RW mode.
try to import pool in readonly=on on another server

`time zpool import -m -f -o readonly=on -o cachefile=none p4r2s`
it is working as well

try to found TXG on on RW mode server and try to import in to another server:
`time zpool import -m -f -o readonly=on -o cachefile=none -T 84072 p4r2s`

server hang on import and i can see pool status is RECOVERING instead of IMPORTING

**Comment by ahrens** [comment]
`zpool import -T` is always very slow, because it verifies all blocks in the pool.
