### ISSUE TITLE
RHEL 8.3 and Centos build failtures.

### ISSUE THREAD

**Issue by Zaryob** [openzfs/zfs#11631]
I'm using zfs repository and tried to install zfs-dkms package and I get compile error in both operating systems. dkms log is same.

 It seems that issue is related with #11195 and #11320  but this issued due to totally different problem
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  RHEL
Distribution Version	| 8.3
Linux Kernel	| 5.10.11.el8.elrepo.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.5-1.el8
SPL Version	|

### Describe the problem you're observing
I'm trying to install zfs-dkms package. but probably some reasons of changes in linux kernelI cannot compile it as well.

### Describe how to reproduce the problem
I tried to install zfs-dkms package but not compiled zfs kernel module. Thats why I go to /usr/src dir than I started following command 
```
dkms build zfs/0.8.5
```
it not compiled as well and give me error log .
### Include any warning/errors/backtraces from the system logs
This is whole log.
[make.log](https://github.com/openzfs/zfs/files/6018650/make.log)

Cause of build exception is that.
```
/var/lib/dkms/zfs/0.8.5/build/include/linux/blkdev_compat.h:378:37: hata: implicit declaration of function 'check_disk_change'; did you mean 'bdev_disk_changed'? [-Werror=implicit-function-declaration]
 #define vdev_bdev_reread_part(bdev) check_disk_change(bdev)
                                     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.5/build/module/zfs/vdev_disk.c:218:17: bilgi: in expansion of macro 'vdev_bdev_reread_part'
     int error = vdev_bdev_reread_part(bdev);
                 ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.5/build/module/zfs/vdev_disk.c: 'vdev_blkg_tryget' işlevinde:
/var/lib/dkms/zfs/0.8.5/build/module/zfs/vdev_disk.c:506:37: hata: 'struct percpu_ref' türü 'count' isimli üye içermiyor
   rc = atomic_long_inc_not_zero(&ref->count);
                                     ^~
cc1: some warnings being treated as errors
```

**Comment by rincebrain** [comment]
0.8.x cannot and is unlikely to ever build against 5.10 and above. cf. https://github.com/openzfs/zfs/issues/11449#issuecomment-757380573

**Comment by Zaryob** [comment]
> 0.8.x cannot and is unlikely to ever build against 5.10 and above. cf. [#11449 (comment)](https://github.com/openzfs/zfs/issues/11449#issuecomment-757380573)
> 
> If you want to use ZoL against a 5.10.x kernel, enable the zfs-testing repo and install 2.0.x.

I made it yesterday but I just mentioned if someone have same error in future, dont try to open new issue

**Comment by behlendorf** [comment]
Closing.  As mentioned above, the 0.8.x release supports up to Linux 5.9 kernels.  A 2.x release must be used for 5.10 and newer kernels.
