### ISSUE TITLE
ZFS interop problem with (LSM) SMACK setting xattrs on object creation

### ISSUE THREAD

**Issue by TerraTech** [openzfs/zfs#11646]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| default/linux/amd64/17.1/hardened
Linux Kernel	| 5.10.27-gentoo
Architecture	| x86_64
ZFS Version	| 2.0.4-r0-gentoo
SPL Version	| 2.0.4-r0-gentoo

### Describe the problem you're observing
From: https://github.com/cschaufler/smack-next/issues/1#issuecomment-784549365
> ZFS is willing to have you set xattrs but isn't going to
set them on object creation it appears.

### Describe how to reproduce the problem
Procedure in linked issue:  https://github.com/cschaufler/smack-next/issues/1#issue-814452076

### Include any warning/errors/backtraces from the system logs

Linked issue: https://github.com/cschaufler/smack-next/issues/1

So far I have tested this on other filesystems like `ext4` and `tmpfs` and both are properly applying the security label for both file and directory creations.  In the linked issue, I also tried this on a zfs filesystem with both `xattr=sa` and `xattr=on`, in both cases the security label was _not_ applied to newly created fs object.

**Comment by TerraTech** [comment]
I just finished testing on VoidLinux and ZFS is exhibiting same behavior with recent Linux kernel and ZFS versions.
Distro: VoidLinux
Kernel: **5.10.18**
Arch: x86_64
ZFS: **2.0.3**

As an aside, I tested `btrfs` and labels were being applied/trasmutated properly on new file/dir creation.

**Comment by TerraTech** [comment]
I would like to request a review of the following commit:
https://github.com/TerraTech/zfs/commit/9a986a6ef42243df0ef95545c6d8e1f293172ad4

So far, it has fixed all of my ZFS+SMACK problems, however I am not sure if it is safe to move `d_instantiate()` to after the `security` and `acl` setup.  I'm concerned I may have created a memory leak, or a ticking time bomb in some rare corner case.

For SMACK to work properly, (at minimum) `d_instantiate()` must be called after `zpl_xattr_security_init()` since SMACK needs to probe the xattr entries in `d_instantiate()` and `smk_fetch()`.

All of the patching and testing work was performed on the VoidLinux system above.  I've also patched up my Gentoo workstation (100% zfs-0.8.6 [12TB]) and it is working there as well.

If the patch is deemed OK, I will convert the above commit to a proper PR and submit.

Thank you.

**Comment by TerraTech** [comment]
I've updated by Gentoo workstation to: Linux 5.10.22 + zfs-2.0.4 and zfs+SMACK appears to be working properly.

**Comment by behlendorf** [comment]
@TerraTech moving the `d_instantiate()` call after `zpl_xattr_security_init()` looks right.  It actually may resolve an unlikely leak by instantiating the dentry only after no other failures are possible and we know we won't call `zfs_remove()`.  You're going to want to update the other entries points where this can happen as well, `zpl_mknod`, `zpl_mkdir`, `zpl_symlink`.

> I've updated my Gentoo workstation to: Linux 5.10.22 + zfs-2.0.4 and zfs+SMACK appears to be working properly.

Do you mean it's working without your proposed change?

**Comment by TerraTech** [comment]
> @TerraTech moving the `d_instantiate()` call after `zpl_xattr_security_init()` looks right. It actually may resolve an unlikely leak by instantiating the dentry only after no other failures are possible and we know we won't call `zfs_remove()`. You're going to want to update the other entries points where this can happen as well, `zpl_mknod`, `zpl_mkdir`, `zpl_symlink`.
> 
Do you want me to start working on a proper PR with those entrypoints handled as well?  Are there more than the 3 (extra) you listed above?

> > I've updated my Gentoo workstation to: Linux 5.10.22 + zfs-2.0.4 and zfs+SMACK appears to be working properly.
> 
> Do you mean it's working without your proposed change?
Sorry, that was meant to say that I had upgraded my workstation to newer versions and the patch is still working to solve the problem with zfs+SMACK.
