### ISSUE TITLE
Add init script to automatic load keys

### ISSUE THREAD

**Issue by ogelpre** [openzfs/zfs#11659]
### Motivation

I am using ZFS with encryption on a storage server. The root pool is decrypted during boot in dracut. With [dracut-crypt-ssh](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh) decryption of root pool is possible from remote.

OpenZFS datastores have to be decrypted afterwards manually.

### Describe the feature would like to see added to OpenZFS

A init script for OpenZFS which loads keys from URI saved in keylocation property.

### How will this feature improve OpenZFS?

This adds a similar functionality to OpenZFS like `/etc/crypttab` for encrypted block devices on Linux.

**Comment by crocket** [comment]
One problem with key files is that a ZFS dataset can't contain multiple keys. If you lose key files, your encrypted zfs dataset is lost.

I also think key files can be stolen by hackers. If you memorize one passphrase, multiple zfs datasets can be unlocked with one passphrase during boot.

**Comment by ogelpre** [comment]
> One problem with key files is that a ZFS dataset can't contain multiple keys. If you lose key files, your encrypted zfs dataset is lost.

That is no argument, because as soon as the system is up and running and attacker has also access to the already loaded keys and mounted filesystems.

Please stop hijacking this feature request. You don't have to use this feature and can use other solutions.

**Comment by crocket** [comment]
Anyway, it is good to have /etc/init.d/zfs-load-key
