### ISSUE TITLE
Multiple "zio error=61 type=1" errors not faulting a vdev

### ISSUE THREAD

**Issue by UnknownNet** [openzfs/zfs#11672]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.8.2003
Linux Kernel	| 3.10.0-1127.19.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing

We have a number of 10-drive raidz2 zpools on a system. The drives are in a JBOD connected to the system, with multipath providing pathing to each drive. We have seen drives begin to log multiple errors into syslog/dmesg, accumulating a large number of errors. We have yet to find the key, but at some point the zpool appears to go non-responsive (deeper information at this point is difficult due to pacemaker stoniths as this is a production filesystem).

An example of the errors are:

```
Feb 16 10:57:31 node0 kernel: [888148.088324] sd 2:3:77:0: [sdkh] tag#19 BRCM Debug mfi stat 0x2d, data len requested/completed 0x1000/0x0
Feb 16 10:57:31 node0 kernel: [888148.088341] sd 2:3:77:0: [sdkh] tag#19 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=9s
Feb 16 10:57:31 node0 kernel: [888148.088347] sd 2:3:77:0: [sdkh] tag#19 Sense Key : Medium Error [current]
Feb 16 10:57:31 node0 kernel: [888148.088349] sd 2:3:77:0: [sdkh] tag#19 Add. Sense: Unrecovered read error
Feb 16 10:57:31 node0 kernel: [888148.088352] sd 2:3:77:0: [sdkh] tag#19 CDB: Read(16) 88 00 00 00 00 00 a1 d6 69 a8 00 00 00 08 00 00
Feb 16 10:57:31 node0 kernel: [888148.088354] blk_update_request: critical medium error, dev sdkh, sector 2715183528
Feb 16 10:57:31 node0 kernel: [888148.088362] blk_update_request: critical medium error, dev dm-49, sector 2715183528
Feb 16 10:57:31 node0 kernel: [888148.088367] zio pool=node0-storage006 vdev=/dev/mapper/node0-storage006-6p1 error=61 type=1 offset=1390172917760 size=4096 flags=180880
```

It appears that ZFS never automatically faults the bad vdev, and instead keeps all vdevs online even though I/O to the underlying device is having issues.

I'm unsure if there's something else going on here keeping ZFS from faulting that drive, or if this is some kind of underlying bug.

### Include any warning/errors/backtraces from the system logs

Log excerpt is above, this was taken from dmesg. We have also seen the following (though not seemingly as often as above):

```
Feb 16 01:05:26 node0 kernel: [852621.670537] sd 2:3:77:0: [sdkh] tag#6 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=2s
Feb 16 01:05:26 node0 kernel: [852621.670558] sd 2:3:77:0: [sdkh] tag#6 Sense Key : Hardware Error [current] [descriptor]
Feb 16 01:05:26 node0 kernel: [852621.670570] sd 2:3:77:0: [sdkh] tag#6 Add. Sense: Power-on or self-test failure(0)
Feb 16 01:05:26 node0 kernel: [852621.670580] sd 2:3:77:0: [sdkh] tag#6 CDB: Synchronize Cache(10) 35 00 00 00 00 00 00 00 00 00
Feb 16 01:05:26 node0 kernel: [852621.670664] blk_update_request: critical target error, dev dm-49, sector 0
Feb 16 01:05:26 node0 kernel: [852621.670673] zio pool=node0-storage006 vdev=/dev/mapper/node0-storage006-6p1 error=121 type=5 offset=0 size=0 flags=100480
```
We are working with the hardware vendor on the drive issues specifically, but it seems like ZFS should be able to handle this situation a bit better.

**Comment by IvanVolosyuk** [comment]
Might be useful to add output of 'zpool status' to examine if the errors are reported by ZFS as well as quantity of the errors.

**Comment by UnknownNet** [comment]
> Might be useful to add output of 'zpool status' to examine if the errors are reported by ZFS as well as quantity of the errors.

As this issue is somewhat sporadic and includes pacemaker STONITH, I do not have "zpool status" of the system at time of the issue. After a failover and attempting to bring the zpools back online (either on the failover pair or after a reboot of the system) we do see errors finally show:

```
[root@node0 ~]# zpool status node0-storage006
  pool: node0-storage006
 state: DEGRADED
status: One or more devices are faulted in response to persistent errors.
        Sufficient replicas exist for the pool to continue functioning in a
        degraded state.
action: Replace the faulted device, or use 'zpool clear' to mark the device
        repaired.
  scan: resilvered 596G in 0 days 01:30:03 with 0 errors on Tue Feb  2 17:10:03 2021
config:
        NAME                                     STATE     READ WRITE CKSUM
        node0-storage006                         DEGRADED     0     0     0
          raidz2-0                               DEGRADED     0     0     0
            node0-storage006-0                   ONLINE       0     0     0
            node0-storage006-1                   ONLINE       0     0     0
            node0-storage006-2                   ONLINE       0     0     0
            node0-storage006-3                   ONLINE       0     0     0
            node0-storage006-4                   ONLINE       0     0     0
            node0-storage006-5                   ONLINE       0     0     0
            node0-storage006-6                   ONLINE       0     0     0
            node0-storage006-7                   ONLINE       0     0     0
            node0-storage006-8                   ONLINE       0     0     0
            node0-storage006-9                   FAULTED     12     0     0  too many errors
        logs
          dm-uuid-part2-mpath-35000c500a18b6647  ONLINE       0     0     0
errors: No known data errors
```
One big issue with this is that while only faulted, the zpool should still be useable (as it is only degraded and not fully faulted) something is signalling to pacemaker to actually stonith the node as the zpool is non-reponsive.
