### ISSUE TITLE
new fs not mounted after "zfs clone"

### ISSUE THREAD

**Issue by swirflon** [openzfs/zfs#11695]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Centos
Distribution Version	| 8.3
Linux Kernel	| 4.18.0-240.15.1.el8_3
Architecture	| x86_64
ZFS Version	| 2.0.3-1
SPL Version	|  2.0.3-1

### Describe the problem you're observing
tank/myfs with >> files

OK zfs snapshot tank/myfs@current
NOK zfs clone tank/myfs@current tank/myfs_export  // OK in a sense of no exception shown
OK zfs list // clone with mountpoint shown
NOK ls /tank/myfs_export  or zfs mount -a ls  /tank/myfs_export  

0 files

### Describe how to reproduce the problem
zfs destroy tank/myfs_export
repeat 
same result 

### Include any warning/errors/backtraces from the system logs
no warnings/backtraces/kernel message buffer entries/syslog entries

**Comment by ahrens** [comment]
Did you verify that the clone is actually mounted?  (e.g. with `df`)
If you are still stuck, please paste the entire output of your session so that we can try to help you understand what's happening here.

**Comment by swirflon** [comment]
it's indeed not mounting. Tested again empty filesystem below as for filled. It worked without a hitch though in 0.8.6. and before. Below the command and abridged output trace:

OK zfs snapshot neo/stor/userhome@mysnap
OK zfs list -o space -t snapshot
neo/stor/userhome@mysnap                    -     0B         -       -              -          -
OK zfs clone neo/stor/userhome@mysnap neo/stor/userhome_export
OK zfs list
neo/stor/userhome_export     0B  74.1T      279K  /neo/stor/userhome_export
NOK df | grep export        // mount, cat /proc/mounts  i.a. all the same 
not mounted

OK zfs mount -a
NOK df | grep export
not mounted

no log entries at standard locations

zdb -d neo
Dataset neo/stor/userhome_export [ZPL], ID 66318, cr_txg 4467233, 279K, 6 objects

**Comment by swirflon** [comment]
can't reproduce it on a ZFS built from master in a test setting

**Comment by pacedproton** [comment]
resolved with 2.1 and -- that being the probable cause -- the versions of both zfs & zfs-kmod being the same. There may be a bug in the latter with zfs-dracut having picked up an old kmod for initrd. Resolution: remove zfs-dracut.
