### ISSUE TITLE
ZFS 2.x RPMs not available for CentOS 7

### ISSUE THREAD

**Issue by cvoltz** [openzfs/zfs#11701]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.9.2009
Linux Kernel	| 3.10.0-1160.15.2.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.6-1
SPL Version	| 0.8.6-1

### Describe the problem you're observing

ZFS 2.x RPMs are not available for CentOS 7 even though the kernel is supported according to the ZFS documentation.

### Describe how to reproduce the problem

1. Install CentOS 7.9.2009
1. `yum install -y https://zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm`
1. `yum install -y epel-release`
1. `yum install -y kernel-devel zfs`
1. `rpm -q zfs`

zfs-0.8.6-1.el7.x86_64 is returned instead of zfs-2.0.3-1.el7.x86_64.

I've verified that the RPMs can be built from the source tarballs on the target system so the problem is just that they aren't available from http://download.zfsonlinux.org/epel/7.9/x86_64.

**Comment by rincebrain** [comment]
You may have better luck with the RPMs in the "zfs-testing" repo - I think those are 2.0.X.

**Comment by gdevenyi** [comment]
#10333

**Comment by behlendorf** [comment]
The 2.0 release is compatible with CentOS 7.9, packages are available from the [zfs-testing](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html#testing-repositories) repository.
