### ISSUE TITLE
l2 headers are unevictible and large

### ISSUE THREAD

**Issue by adamdmoss** [openzfs/zfs#11702]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| ubuntu
Distribution Version	| 18.04.x
Linux Kernel	| 5.4.0-58-generic (ubuntu)
Architecture	| x64
ZFS Version	| master @ e7a06356c13c972c894e00b702ae7a5f5bf187e5
SPL Version	|

### Describe the problem you're observing

The sum of the arc_buf_hdr_t_l2only objects on my 16GB system is constantly around 1.8GB and never shrinks.  I have around 280GB of l2arc allocated to pools.

```
% sudo grep l2 /proc/slabinfo 
arc_buf_hdr_t_l2only 17993321 18036144     96   42    1 : tunables    0    0    0 : slabdata 429432 429432
```
```
NAME                                                  SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
backups-on-6tbusb                                    5.45T  2.16T  3.30T        -         -     0%    39%  1.00x    ONLINE  -
  usb-WD_Elements_25A3_57583531443638444C303041-0:0  5.45T  2.16T  3.30T        -         -     0%  39.5%      -  ONLINE  
cache                                                    -      -      -        -         -      -      -      -  -
  nvme0n1p2                                          4.65G  1.42G  3.23G        -         -     0%  30.5%      -  ONLINE  
zfs3-on-3tbusb                                       2.72T  1.86T   874G        -         -    15%    68%  1.21x    ONLINE  -
  ata-ST3000DM001-1CH166_W1F3ASPS                    2.72T  1.86T   874G        -         -    15%  68.6%      -  ONLINE  
cache                                                    -      -      -        -         -      -      -      -  -
  nvme0n1p3                                          11.5G  7.50G  4.00G        -         -     0%  65.2%      -  ONLINE  
zfs4-on-8tbgold                                      7.27T  5.48T  1.78T        -         -    10%    75%  1.00x    ONLINE  -
  ata-WDC_WD8004FRYZ-01VAEB0_VAKDG3ML                7.27T  5.48T  1.78T        -         -    10%  75.5%      -  ONLINE  
cache                                                    -      -      -        -         -      -      -      -  -
  nvme0n1p4                                           264G   259G  5.60G        -         -     0%  97.9%      -  ONLINE  
```

I suspect it's by-design that l2 headers are proportional to used l2 space and there is no effective eviction process but I wanted to verify that this isn't a bug before I consider attacking this, since I have vague memories that this wasn't always the case. :)  Perhaps this was always the case but it was harder to notice before persistent l2arc because headers would be gradually allocated as the l2arc very slowly filled up from empty.  (@gamanakis would certainly know!)

This morning I made a couple of dumb attempts to:
a) shrink l2arc_buf_hdr_t and arc_buf_hdr_t so at least the overhead would be lower
_- but they're pretty tightly packed already_
b) just keep l2arc_log_ent_phys_t around and l2arc_hdr_restore() them on-demand
_- too hard for a quick hack, might try again, but those phys_t's are also fairly large so this wouldn't be the order-of-magnitude saving I'd rather like_
c) some handwavy sort of bloom filter to quickly discover what's *not* in various subspans of the physical l2arc without necessarily keeping the details around
_- assumes that l2arc read and writes are pretty temporally localized to sub-areas of the physical l2arc over time, which seems likely given its FIFO nature_
_- I got bored and wanted to play video games instead, might pick this up another day 
:)_

**Comment by gamanakis** [comment]
From my understanding the L2ARC headers are stored in the ARC, so that ZFS has a way of knowing that a buffer is stored in L2ARC. As such they are not evictable in the present design, meaning that if they are evicted ZFS would think those buffers are not in L2ARC.

**Comment by shodanshok** [comment]
> From my understanding the L2ARC headers are stored in the ARC, so that ZFS has a way of knowing that a buffer is stored in L2ARC. As such they are not evictable in the present design, meaning that if they are evicted ZFS would think those buffers are not in L2ARC.

It is my understanding also. The best method to limit L2ARC headers seems to use a relatively large (128K) recordsize.
@adamdmoss what is your current recordsize?

**Comment by behlendorf** [comment]
That's right, the current design depends on the l2 header remaining in memory to locate the buffer stored in the L2ARC.  There was some discussion in the past about adding a limit to prevent these headers from consuming too much memory.  Since if you add a very large L2ARC device to a system with very little memory it can be a real problem.  At least in this case it would be preferable to just use less of the L2ARC rather than exhausting system memory.

**Comment by shodanshok** [comment]
@behlendorf it strongly depends of dataset recordsize. For example, on a 128K recordsize:

```
L2 ARC Size: (Adaptive)                         722.39  GiB
        Compressed:                     69.09%  499.07  GiB
        Header Size:                    0.06%   455.43  MiB
```

A ~500GB allocated L2ARC results in less than 500MB headers. 

Does the already available metadata limit includes the L2ARC headers? If so, rather than juggling with the code, I think it would be better to simply clearly document that the combination of small recordsize & large L2ARC should be avoided on low-mem machines.

**Comment by adamdmoss** [comment]
So I think this was a self-inflicted wound - most my l2arc-backed datasets have 128k-1M recordsizes, but I was doing a bunch of stress-testing of some zstd patches with a variety of low recordsizes, so I guess I have to wait until they get FIFO'd out. :)

Having this bloat did turn up a few interesting bugs in evict/reap code (which assumes it can always evict meta down to a certain threshold, which isn't the case when l2 headers dominate the meta size), but that's a different issue!

So it'd be nice to have a strategy implemented to mitigate this, but I'm adequately happy to close this as 'things are working as expected'.

**Comment by IvanVolosyuk** [comment]
> So I think this was a self-inflicted wound - most my l2arc-backed datasets have 128k-1M recordsizes, but I was doing a bunch of stress-testing of some zstd patches with a variety of low recordsizes, so I guess I have to wait until they get FIFO'd out. :)

Just a note from another bug: #11738 shows that if you deleted the test-sets it will shrink l2arc, but after reboot all deleted objects are back and using the ARC space by design. This is probably what you experienced in your testing.

**Comment by behlendorf** [comment]
Closing.  As mentioned above this is working as intended, the memory usage strongly depends on the recordsize.  Improvements could certainly be made in this area if someone is interested in working on it.
