### ISSUE TITLE
zdb spa_misc.c:393:spa_load_failed() on otherwise healthy pool

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#11719]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Scientific Linux
Distribution Version	| 7.9
Linux Kernel	| 3.10.0-1160.15.2.el7
Architecture	| x86_64
ZFS Version	| 0.8.6
SPL Version	| 0.8.6

### Describe the problem you're observing

zdb -e reports errors on a pool that otherwise appears healthy

### Describe how to reproduce the problem
```
[root@cascade2 ~]# zdb -e home1 | egrep error
zdb: can't open 'home1': Input/output error
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): metaslab_init failed [error=5]
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): vdev_load: metaslab_init failed [error=5]
spa_misc.c:393:spa_load_failed(): spa_load(home1, config trusted): FAILED: vdev_load failed [error=5]
```
### Include any warning/errors/backtraces from the system logs
```
[root@cascade2 ~]# zpool status home1
  pool: home1
 state: ONLINE
  scan: resilvered 0B in 0 days 03:24:45 with 0 errors on Sun Feb  7 18:49:50 2021
config:

	NAME                      STATE     READ WRITE CKSUM
	home1                     ONLINE       0     0     0
	  raidz3-0                ONLINE       0     0     0
	    35000cca253134c28     ONLINE       0     0     0
	    35000cca253146b40     ONLINE       0     0     0
	    35000cca253155e44     ONLINE       0     0     0
	    35000cca25319f9ac     ONLINE       0     0     0
	    35000cca2531a6ba0     ONLINE       0     0     0
	    35000cca2531b8108     ONLINE       0     0     0
	    35000cca2531bcadc     ONLINE       0     0     0
	    35000cca2531d41f4     ONLINE       0     0     0
	    35000cca2531d46c8     ONLINE       0     0     0
	    35000cca2531d4cac     ONLINE       0     0     0
	    35000cca2531da728     ONLINE       0     0     0
	    35000cca2531da880     ONLINE       0     0     0
	    35000cca2531dad74     ONLINE       0     0     0
	    35000cca2531ff2bc     ONLINE       0     0     0
	    35000cca2531ffff8     ONLINE       0     0     0
	  raidz3-1                ONLINE       0     0     0
	    35000cca253204e9c     ONLINE       0     0     0
	    35000cca253205ffc     ONLINE       0     0     0
	    35000cca2532067e0     ONLINE       0     0     0
	    35000cca253207fdc     ONLINE       0     0     0
	    35000cca253207ff4     ONLINE       0     0     0
	    35000cca2532081b0     ONLINE       0     0     0
	    35000cca25320d79c     ONLINE       0     0     0
	    35000cca25320dad0     ONLINE       0     0     0
	    35000cca25320e460     ONLINE       0     0     0
	    35000cca2532105a8     ONLINE       0     0     0
	    35000cca253217370     ONLINE       0     0     0
	    35000cca2532176f4     ONLINE       0     0     0
	    35000cca2532178d8     ONLINE       0     0     0
	    35000cca25321b168     ONLINE       0     0     0
	    35000cca25321b5f8     ONLINE       0     0     0
	  raidz3-2                ONLINE       0     0     0
	    35000cca25321b774     ONLINE       0     0     0
	    35000cca25321c2e0     ONLINE       0     0     0
	    35000cca25321c61c     ONLINE       0     0     0
	    35000cca25321c804     ONLINE       0     0     0
	    35000cca25321c870     ONLINE       0     0     0
	    35000cca25321c898     ONLINE       0     0     0
	    35000cca25321c910     ONLINE       0     0     0
	    35000cca25321c938     ONLINE       0     0     0
	    35000cca25321ca74     ONLINE       0     0     0
	    35000cca25323980c     ONLINE       0     0     0
	    35000cca253241428     ONLINE       0     0     0
	    35000cca253241574     ONLINE       0     0     0
	    35000cca253246560     ONLINE       0     0     0
	    35000cca2532479a4     ONLINE       0     0     0
	    35000cca253247c68     ONLINE       0     0     0
	  raidz3-3                ONLINE       0     0     0
	    35000cca25324a360     ONLINE       0     0     0
	    35000cca25324b7c0     ONLINE       0     0     0
	    35000cca25324d8e8     ONLINE       0     0     0
	    35000cca25324dc4c     ONLINE       0     0     0
	    35000cca253251828     ONLINE       0     0     0
	    35000cca253256f0c     ONLINE       0     0     0
	    35000cca253257210     ONLINE       0     0     0
	    35000cca2532572e4     ONLINE       0     0     0
	    35000cca2532586ec     ONLINE       0     0     0
	    35000cca25325c5f4     ONLINE       0     0     0
	    35000cca25325c610     ONLINE       0     0     0
	    35000cca25325c76c     ONLINE       0     0     0
	    35000cca25325fb38     ONLINE       0     0     0
	    35000cca25325fb5c     ONLINE       0     0     0
	    35000cca25325fb78     ONLINE       0     0     0
	special
	  mirror-6                ONLINE       0     0     0
	    zfs-64e840b01f4e178c  ONLINE       0     0     0
	    zfs-2901cad643f112c3  ONLINE       0     0     0
	    zfs-8fa1031490ad0ab2  ONLINE       0     0     0
	    zfs-3cf59d1d145ab04b  ONLINE       0     0     0
	  mirror-7                ONLINE       0     0     0
	    zfs-cc86d88f575882ba  ONLINE       0     0     0
	    zfs-039251109fb434af  ONLINE       0     0     0
	    zfs-e7c241bb7dcd4fb8  ONLINE       0     0     0
	    zfs-b13cf73ec91bb5d2  ONLINE       0     0     0
	logs
	  mirror-4                ONLINE       0     0     0
	    zfs-b30c96b1eb59e20f  ONLINE       0     0     0
	    zfs-0f8de84266666364  ONLINE       0     0     0
	  mirror-5                ONLINE       0     0     0
	    zfs-72606fae4de92cf2  ONLINE       0     0     0
	    zfs-0978488aae2a7c56  ONLINE       0     0     0
	cache
	  nvme4n1p1               ONLINE       0     0     0
	  nvme5n1p1               ONLINE       0     0     0

errors: No known data errors
```

**Comment by ahrens** [comment]
It looks like your pool may be imported (i.e. used by the kernel) while running `zdb`.  In this case zdb may fail due to the kernel's concurrent changes to on-disk state.  To work around this, either export the pool from the kernel, or create a checkpoint and run zdb against the checkpoint (`zdb -k`).

**Comment by stuartthebruce** [comment]
Yes, the pool is imported, and I get a slightly different dbgmsg from a checkpoint, but the same spa_load_failed,
```
[root@cascade2 ~]# zpool status | grep checkpoint
checkpoint: created Tue Mar  9 16:38:11 2021, consumes 3.48G

[root@cascade2 ~]# zdb -k -e home1 | egrep error
zdb: can't open 'home1': Input/output error
vdev.c:125:vdev_dbgmsg(): disk vdev '/dev/disk/by-partlabel/zfs-b30c96b1eb59e20f': vdev_load: vdev_dtl_load failed [error=5]
spa_misc.c:393:spa_load_failed(): spa_load(home1, config trusted): FAILED: vdev_load failed [error=5]
```
And the same after destroying the snapshot
```
[root@cascade2 ~]# zpool checkpoint -d home1
[root@cascade2 ~]# zpool status | grep checkpoint
[root@cascade2 ~]# zdb -e home1 | egrep error
zdb: can't open 'home1': Input/output error
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): metaslab_init failed [error=5]
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): vdev_load: metaslab_init failed [error=5]
spa_misc.c:393:spa_load_failed(): spa_load(home1, config trusted): FAILED: vdev_load failed [error=5]
```

**Comment by stuartthebruce** [comment]
```
[root@cascade2 ~]# zdb -e home1 > home1.txt
zdb: can't open 'home1': Input/output error
```
[home1.txt](https://github.com/openzfs/zfs/files/6112599/home1.txt)

**Comment by ahrens** [comment]
Thanks.  For those reading along, here's the full dbgmsg, which doesn't tell us much:
```
ZFS_DBGMSG(zdb) START:
spa.c:5490:spa_import(): spa_import: importing home1
spa_misc.c:408:spa_load_note(): spa_load(home1, config trusted): LOADING
vdev.c:125:vdev_dbgmsg(): disk vdev '/dev/mapper/35000cca2531da728': best uberblock found for spa home1. txg 129685707
spa_misc.c:408:spa_load_note(): spa_load(home1, config untrusted): using uberblock with txg=129685707
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): metaslab_init failed [error=5]
vdev.c:130:vdev_dbgmsg(): mirror-4 vdev (guid 10623750380422153729): vdev_load: metaslab_init failed [error=5]
spa_misc.c:393:spa_load_failed(): spa_load(home1, config trusted): FAILED: vdev_load failed [error=5]
spa_misc.c:408:spa_load_note(): spa_load(home1, config trusted): UNLOADING
ZFS_DBGMSG(zdb) END
```

I created a pool with similar vdevs and couldn't reproduce the problem (at least not with a trivial test case):
```
  pool: test
 state: ONLINE
config:

	NAME                  STATE     READ WRITE CKSUM
	test                  ONLINE       0     0     0
	  raidz3-0            ONLINE       0     0     0
	    /var/tmp/vdevs/a  ONLINE       0     0     0
	    /var/tmp/vdevs/b  ONLINE       0     0     0
	    /var/tmp/vdevs/c  ONLINE       0     0     0
	    /var/tmp/vdevs/d  ONLINE       0     0     0
	    /var/tmp/vdevs/e  ONLINE       0     0     0
	    /var/tmp/vdevs/f  ONLINE       0     0     0
	    /var/tmp/vdevs/g  ONLINE       0     0     0
	special
	  mirror-1            ONLINE       0     0     0
	    /var/tmp/vdevs/h  ONLINE       0     0     0
	    /var/tmp/vdevs/i  ONLINE       0     0     0
	    /var/tmp/vdevs/j  ONLINE       0     0     0
	    /var/tmp/vdevs/k  ONLINE       0     0     0
	  mirror-2            ONLINE       0     0     0
	    /var/tmp/vdevs/l  ONLINE       0     0     0
	    /var/tmp/vdevs/m  ONLINE       0     0     0
	    /var/tmp/vdevs/n  ONLINE       0     0     0
	    /var/tmp/vdevs/o  ONLINE       0     0     0
	logs
	  mirror-3            ONLINE       0     0     0
	    /var/tmp/vdevs/p  ONLINE       0     0     0
	    /var/tmp/vdevs/q  ONLINE       0     0     0
	  mirror-4            ONLINE       0     0     0
	    /var/tmp/vdevs/r  ONLINE       0     0     0
	    /var/tmp/vdevs/s  ONLINE       0     0     0
	cache
	  /var/tmp/vdevs/t    ONLINE       0     0     0
	  /var/tmp/vdevs/u    ONLINE       0     0     0

errors: No known data errors
```

It's too bad zdb doesn't give us more info about the i/o errors it encountered (like what we can get from `zpool events -v` when the kernel has i/o errors).  I wonder if there's something going wrong with how zdb is accessing the `by-partlabel` devices?  Although I would think it would fail even earlier if those vdevs were completely inaccessible (e.g. it couldn't read the zfs labels).

**Comment by stuartthebruce** [comment]
@ahrens are you able to export your test pool and re-import with -d /dev/disk/by-label (or equivalent)? Otherwise later this week I can convert another pool to a similar configuration to see if that causes problems for zdb.

**Comment by stuartthebruce** [comment]
This pool is now managed by a Rocky Linux 8.5 server running ZFS 2.1.2 and generates a similar error,
<pre>
[root@zfs3 ~]# zdb home1 | egrep error
zdb: can't open 'home1': Input/output error
vdev.c:153:vdev_dbgmsg(): disk vdev '/dev/nvme8n7p1': vdev_load: vdev_dtl_load failed [error=5]
vdev.c:153:vdev_dbgmsg(): disk vdev '/dev/nvme6n7p1': vdev_load: vdev_dtl_load failed [error=5]
vdev.c:153:vdev_dbgmsg(): disk vdev '/dev/nvme6n4p1': vdev_load: vdev_dtl_load failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-0 vdev (guid 13951287261081704258): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-0 vdev (guid 13951287261081704258): vdev_load: metaslab_init failed error=5]
vdev.c:158:vdev_dbgmsg(): raidz-1 vdev (guid 17121811968238455899): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-1 vdev (guid 17121811968238455899): vdev_load: metaslab_init failed error=5]
vdev.c:153:vdev_dbgmsg(): disk vdev '/dev/nvme7n1p1': metaslab_init failed [error=5]
vdev.c:153:vdev_dbgmsg(): disk vdev '/dev/nvme7n1p1': vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-2 vdev (guid 5403497146890759845): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-2 vdev (guid 5403497146890759845): vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-3 vdev (guid 2120567361493002780): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-3 vdev (guid 2120567361493002780): vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): mirror-6 vdev (guid 18345916408857067993): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): mirror-6 vdev (guid 18345916408857067993): vdev_load: metaslab_init failed [error=5]
spa_misc.c:404:spa_load_failed(): spa_load(home1, config trusted): FAILED: vdev_load failed [error=5]
</pre>
I also see a similar error on another independent system with a similar pool,
<pre>
[root@zfs4 ~]# zdb home3 | egrep error
zdb: can't open 'home3': Input/output error
vdev.c:158:vdev_dbgmsg(): raidz-2 vdev (guid 10053772364381122931): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-3 vdev (guid 2224021987957242030): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-2 vdev (guid 10053772364381122931): vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-3 vdev (guid 2224021987957242030): vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-1 vdev (guid 7773482507541489146): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-1 vdev (guid 7773482507541489146): vdev_load: metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-0 vdev (guid 15811688938966524033): metaslab_init failed [error=5]
vdev.c:158:vdev_dbgmsg(): raidz-0 vdev (guid 15811688938966524033): vdev_load: metaslab_init failed [error=5]
spa_misc.c:404:spa_load_failed(): spa_load(home3, config trusted): FAILED: vdev_load failed [error=5]
</pre>
One of these systems is able to run `zdb -C` and the other isn't,
<pre>
[root@zfs3 ~]# zdb -C | grep ashift
            ashift: 12
            ashift: 12
            ashift: 12
            ashift: 12
            ashift: 0
            ashift: 0
            ashift: 9
            ashift: 9
            ashift: 9
            ashift: 9
</pre>
<pre>
[root@zfs4 ~]# zdb -C home3 | grep ashift
zdb: can't open 'home3': Invalid exchange
</pre>

**Comment by stuartthebruce** [comment]
However, I have a 3rd similarly configured system that is not generating this error,
<pre>
[root@zfs1 ~]# zdb home2 | egrep error
    146914    2   128K    16K  61.5K     512    80K  100.00  persistent error log
dmu_object_next() = 52

[root@zfs1 ~]# zdb -C | grep ashift
            ashift: 12
            ashift: 12
            ashift: 12
            ashift: 12
            ashift: 9
            ashift: 9
            ashift: 0
            ashift: 0
            ashift: 0
            ashift: 0
            ashift: 0
            ashift: 9
            ashift: 9
            ashift: 9
            ashift: 0
            ashift: 9
</pre>
