### ISSUE TITLE
zfs stops working - enabling CONFIG_LATENCYTOP 

### ISSUE THREAD

**Issue by ixvz** [openzfs/zfs#11721]
CRUX 3.6 x64

kernel 5.4.80

# modinfo zfs | grep -iw version
version:        2.0.3-1
# modinfo spl | grep -iw version
version:        2.0.3-1

after enabling CONFIG_LATENCYTOP in kernel and reboot
zfs stops working

**Comment by kernelOfTruth** [comment]
>after enabling CONFIG_LATENCYTOP in kernel and reboot
