### ISSUE TITLE
Reported L2ARC size shrinking over time

### ISSUE THREAD

**Issue by PeterCxy** [openzfs/zfs#11738]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 10
Linux Kernel	| 4.19.171
Architecture	| amd64
ZFS Version	| 2.0.4
SPL Version	| 2.0.2

Note: my OpenZFS is installed via compiling the upstream version following `Custom Packages` in OpenZFS Wiki. It is not the version packaged in Debian's repository.

### Describe the problem you're observing

(It seems that a similar case exists on [FreeBSD bugtracker](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250323), which could provide more information if my description is not enough)

My OpenZFS pool setup is a mirror vdev with 2x2 TB HDDs and two 100GB partitions on two SSDs as cache vdevs, resulting in a total L2ARC size of 200GB.

The issue is that I have noticed the L2ARC size shrinks over time, both in `l2_asize` in `/proc/spl/kstat/zfs/arcstats` and in the `ALLOC` column of the cache vdevs in the output of `zpool list -v`.

Shortly after boot, `arcstats` shows something like

```
l2_size                         4    472453769216
l2_asize                        4    213204880384
```

...which is the expected ~200GB.

But after around a week of uptime (could be more, I didn't keep a detailed record), the output becomes

```
l2_size 4 154500634112
l2_asize 4 70061155328
```

...which suggests that the size is now around 65GB.

After a few more days, it shrinks even more

```
l2_size                         4    51231725056
l2_asize                        4    23947132928
```

to around 22GB.

The `ALLOC` column of the output of `zpool list -v` agrees with the above, and a reboot restores the size immediately to the full 200GB.

I haven't used OpenZFS a lot in the past, and this installation was only done after the 2.0.0 update, so I am not sure if this is really a bug or expected behavior. My only previous experience with ZFS was on FreeBSD 12 with its non-OpenZFS implementation and such behavior did not happen on it (this is also apparent from the FreeBSD bug report mentioned earlier). If it is expected, it might help to document the behavior somewhere (as I couldn't find much about this in the documentation).

### Describe how to reproduce the problem

1. Create a pool similar to mine with L2ARC
2. Observe the L2ARC size shrinkage over time

**Comment by IvanVolosyuk** [comment]
I think it is similar to #11209.
What's interesting is after reboot L2ARC comes up larger than before reboot. I have confirmed that using my netdata graphs. I think the reason for that is after reboot some objects which was invalidated from l2arc and had their in ram headers removed are not detected by the persisted l2arc code. @gamanakis may know better.

**Comment by PeterCxy** [comment]
@IvanVolosyuk The L2ARC size seems to up consistently as the maximum 200 GB, not just larger than before reboot. If it is the same issue as #11209, then it looks like the persistent L2ARC code didn't just fail to detect *some* removed objects; it failed to detect *all* removed objects during those days of uptime.

**Comment by PeterCxy** [comment]
I see that in #11209 the shrinkage is caused by a VM writing a lot of short-lived blocks to the ZFS, but in my case the main I/O workload is a mostly append-only PostgreSQL database. I can't think of anything on my server that could be writing a lot of short-lived blocks to the filesystem.

**Comment by IvanVolosyuk** [comment]
Might be db journal rewritten over and over, might be overwrites in db, might be something else. Anything interesting in iotop?

**Comment by PeterCxy** [comment]
@IvanVolosyuk nothing really other than the db processes.

I agree the 200GB value after reboot is probably the problem here rather than the shrinking behavior. All active data with `secondarycache` enabled on my entire disk doesn't even add up to 200GB yet (after zstd compression, that is). But again, if this is due to persistent L2ARC not detecting deleted objects correctly, then it probably failed to detect *most* of them because the L2ARC size goes back up to 200GB *consistently* after reboot, even when the size was merely 20GB before reboot. Or maybe this is expected for persistent L2ARC and I'm simply missing something here.

**Comment by gamanakis** [comment]
>I think the reason for that is after reboot some objects which was invalidated from l2arc and had their in ram headers removed are not detected by the persisted l2arc code.

Yes, this is by design, the invalided L2ARC headers are not detected by the peristent L2ARC code. So invalidated L2ARC headers may be restored. This is not a problem though, as ZFS will realize this is the case if it reads invalidated buffers from L2ARC (checksum) and will fetch from the vdevs of the pool.

**Comment by PeterCxy** [comment]
Thanks, that makes sense. I'm closing this as it seems not to be an actual issue. Hopefully the existence of this thread can act as some sort of documentation for anyone that gets confused by the same behavior in the future.
