### ISSUE TITLE
Fedora 34 repository

### ISSUE THREAD

**Issue by amarshall** [openzfs/zfs#11789]
### Describe the feature would like to see added to OpenZFS

Fedora 34 Beta has been released, as such it would be nice to have an official OpenZFS repository available for it.

### How will this feature improve OpenZFS?

Upcoming version of Fedora 34 will work with official repositories.

### Additional context

Fedora 34 is using kernel 5.11, and so should largely be compatible with the latest OpenZFS release.

**Comment by gdevenyi** [comment]
#10333

**Comment by amarshall** [comment]
@gdevenyi Not sure how that ticket is related to this one, if you could elaborate that would be helpful.

**Comment by gdevenyi** [comment]
> @gdevenyi Not sure how that ticket is related to this one, if you could elaborate that would be helpful.

I ping my meta-issue about Ubuntu and Debian being treated as second-class distributions for every issue where someone asks for another update to packaging to support another Fedora/Centos/RHEL release.

**Comment by felixphew** [comment]
Any progress? Fedora 34 should be coming out soon. I'm happy to help test (the package or the upgrade process), if that would be useful.

**Comment by Evernow** [comment]
Fedora 34 will be released on the 20th of April as per the schedule: https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html

**Comment by felixphew** [comment]
The repo appears to exist now!

**Comment by Evernow** [comment]
Users still can't seem to download the repo file: https://zfsonlinux.org/fedora/zfs-release.fc34.noarch.rpm

Note, Fedora 34 is going to be released tomorrow

**Comment by behlendorf** [comment]
The repository was created and is ready, we'll publish the repo file when Fedora 34 is officially released.

**Comment by tonyhutter** [comment]
Fedora 32 links are live now, closing issue.
