### ISSUE TITLE
Update mapping of file attributes/flags between linux and freebsd

### ISSUE THREAD

**Issue by manfromafar** [openzfs/zfs#11780]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Freebsd, Ubuntu
Distribution Version	| 12.2, 20.04
Linux Kernel	| 5.4.0-60-generic
Architecture	| amd64
ZFS Version	| 2.0.0, 2.0.4
SPL Version	| 2.0.0 2.0.4

### Describe the problem you're observing
When migrating a zpool from freebsd to linux (or vice versa) not all file attributes/flags are mapped correctly leading to strange behavior. 

Example:
Setting the sunlnk file flag on freebsd for a file or folder. This changes the directory or file to be append only and cannot be deleted. 
When you import the zpool into linux and check lsattr on the folder/file no append flag is set but if you try to delete the folder or file you will receive a operations not permitted error from rm.
These means that zfs is still honoring the flag even though the end user can't make changes to it  
setting chatter -a does no resolve the issue and the only way to remove the flag is to reload the zpool into freebsd and remove the flag. 

As a side note the schg (immutable flag) works and when viewed from linux the i attribute is set and is able to be edited. 

### Describe how to reproduce the problem
create a pool on freebsd 

create a folder in the zpool

set the sunlnk flag on the file or folder 

`chflags sunlnk {file/folder}`

confirm the sunlnk flag is set

`ls -lo {file/folder}`

export the pool on freebsd and import it on a linux host 

try to delete the file/folder that was created on freebsd 
`rm -rf {file/folder}`

check the file attributes

`lsattr {file/folder}`

this should return no flags 
`--------------`

**Comment by usaleem-ix** [comment]
@behlendorf  will try to reproduce and report my findings
