### ISSUE TITLE
Show nanoseconds timestamp in stat command

### ISSUE THREAD

**Issue by ghost** [openzfs/zfs#11808]
### Describe the feature would like to see added to OpenZFS
A FreeBSD commiter said to create a report here for nanosecond support in stat command.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254593#c1

### How will this feature improve OpenZFS?
There are users who want to display the nanoseconds timestamp for their directories and files in stat command in Terminal on FreeBSD.
https://forums.freebsd.org/threads/how-to-change-the-stat-command-time-format-because-of-nanoseconds.79045/#post-495945

### Additional context
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254593

> Description:
> 
> There are users who want to have nanoseconds in stat command, because these users use file systems like ZFS which internally stores nanosecond timestamps.
> 
> https://forums.freebsd.org/threads/how-to-change-the-stat-command-time-format-because-of-nanoseconds.79045/#post-495945
> 
> 
> I also agree that it must be displayed as standard.
> 
> That means
> 
> Current behavior only with stat command:
> stat /
> 159 2 drwxr-xr-x 25 root wheel 1048 512 "Feb 24 19:25:21 2021" "Mar 27 02:39:54 2021" "Mar 27 02:39:54 2021" "Jan  1 00:59:59 1970" 32768 8 0 /
> 
> 
> Expected behavior:
> stat /
> 159 2 drwxr-xr-x 25 root wheel 1048 512 
> 
> Accessed: "Mar 27 02:39:54.640747015 2021" 
> Modified: "Mar 27 02:39:54.640747015 2021" 
> Changed:  "Mar 27 02:39:54.640747015 2021" 
> Created:  "Jan  1 00:59:59.000000000 1970" 
> 
> 32768 8 0 /

**Comment by rincebrain** [comment]
That...really seems like a request to change the stat(1) command, and not something that needs the filesystem's involvement if the filesystem already exposes the underlying representation with enough precision.

**Comment by devZer0** [comment]
Please can sombody close this or provide me permission to close such bugreports ? 

this is open for 12 days now and that's exactly 12 days too long.

on linux stat already exposes nanosecond precision per default.

the referenced bugreports tells,  that you can make bsd stat behave similar with additional param,  so this issue is misplaced here. 

openzfs project does not maintain stat utility.

```
# stat /zfspool/backup.tar
  File: /zfspool/backup.tar
  Size: 1151928320	Blocks: 2249834    IO Block: 131072 regular file
Device: 35h/53d	Inode: 4           Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-04-06 13:15:40.905952369 +0200
Modify: 2021-04-06 13:15:43.161916106 +0200
Change: 2021-04-06 13:15:43.161916106 +0200
 Birth: -
