### ISSUE TITLE
encrypted dataset: dracut pre-mount hook: cannot open '-': dataset does not exist

### ISSUE THREAD

**Issue by denizzzka** [openzfs/zfs#11800]
I created encrypted dataset on rpool and init isn't promts me to enter password for it while booting

Dataset name:
rpool/ROOT/mnt_cryptfs

its mountpoint is:
/mnt/cryptfs

Boot console output:

```
мар 26 01:24:06 denpc systemd[1]: Starting dracut pre-mount hook...
мар 26 01:24:06 denpc dracut-pre-mount[2876]: cannot open '-': dataset does not exist
мар 26 01:24:06 denpc systemd[1]: Finished dracut pre-mount hook.
мар 26 01:24:08 denpc systemd[1]: dracut-pre-mount.service: Succeeded.
```

Also I tried to replace dracut by initramfs and it also isn't tries to ask me for password but not returns any errors

### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| sid
Linux Kernel	| Linux denpc 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
Architecture	| x86_64
ZFS Version	| zfs-2.0.3-1 zfs-kmod-2.0.3-1
SPL Version	| 2.0.3-1

**Comment by denizzzka** [comment]
Tried to rename dataset by removing underscore symbol (rpool/ROOT/mntcryptfs) - is not helps

Packages versions:
```
ii  libzfs2linux                                                0.8.6-1                                                       amd64        OpenZFS filesystem library for Linux
ii  libzfs4linux                                                2.0.3-1                                                       amd64        OpenZFS filesystem library for Linux
ii  zfs-dkms                                                    2.0.3-1                                                       all          OpenZFS filesystem kernel modules for Linux
ii  zfs-dracut                                                  2.0.3-1                                                       all          OpenZFS root filesystem capabilities for Linux - dracut
ii  zfs-zed                                                     0.8.4-2                                                       amd64        OpenZFS Event Daemon
ii  zfsutils-linux                                              2.0.3-1                                                       amd64        command-line tools to manage OpenZFS filesystems
```

**Comment by denizzzka** [comment]
zfs-zed was updated to 2.0.3-1, nothing has changed

**Comment by denizzzka** [comment]
Found what I have ZVOL dataset with "mountpoint" '-':
```
denizzz@denpc ~> sudo zfs list rpool/swap_luks
NAME              USED  AVAIL     REFER  MOUNTPOINT
rpool/swap_luks  16.7G  33.5G     8.17G  -
```

**Comment by nabijaczleweli** [comment]
What's your `boot=` cmdline parameter and full output of `zfs list -o name,mountpoint,encryptionroot,keylocation` for your root pool?

**Comment by denizzzka** [comment]
> What's your boot= cmdline parameter

Command line: root=ZFS=rpool/ROOT/debian ro cgroup_enable=memory swapaccount=1 quiet initrd=\EFI\Debian\initrd.img

> and full output of zfs list -o name,mountpoint,encryptionroot,keylocation for the root pool?

(I added pool name to `zfs list` command to avoid unrelated output) 
```
denizzz@denpc ~> sudo zfs list rpool -o name,mountpoint,encryptionroot,keylocation
NAME   MOUNTPOINT  ENCROOT  KEYLOCATION
rpool  none        -        none
```

**Comment by nabijaczleweli** [comment]
Hm, yeah. Can you try the top commit off #12108?

If you're on 2.0.3, it's identical to replacing
```sh
    # where the key is stored (in a file or loaded via prompt)
    KEYLOCATION=$(zfs get -H -o value keylocation "${ENCRYPTIONROOT}")
    if ! [ "${ENCRYPTIONROOT}" = "-" ]; then
        KEYSTATUS="$(zfs get -H -o value keystatus "${ENCRYPTIONROOT}")"
```
with
```sh
    if ! [ "${ENCRYPTIONROOT}" = "-" ]; then
        KEYLOCATION=$(zfs get -H -o value keylocation "${ENCRYPTIONROOT}")
        KEYSTATUS="$(zfs get -H -o value keystatus "${ENCRYPTIONROOT}")"
```
in `/usr/lib/dracut/modules.d/90zfs/zfs-load-key.sh`, so if you could edit that, regenerate, and reboot, you should no longer get the error.
