### ISSUE TITLE
Please support zstd --long matching mode

### ISSUE THREAD

**Issue by justinpryzby** [openzfs/zfs#11835]
$SUBJECT allows better/faster compression.

For some backup data:
$ time zstd -c9 --long ./2021_01_01 |wc -c
96161974
real    0m41.054s

$ time zstd -c16 ./2021_01_01 |wc -c
103094469
real    7m46.524s

**Comment by jebsolutions** [comment]
As I understand it, 

This won't really help. :(

The stand alone command line ZSTD compressor can treat the *whole file* as a single logical chunk of data.  Long mode can makes sense here -- look farther ahead for matches for potential better compression at the expense of compression time.

But with ZFS...under the hood a file is stored as record size chunks.  Each record size chunk is compressed *independent* of any other chunks.  The default record size is 128k, which is smaller than the size that --long look ahead applies to (> 128MB).

**Comment by mcmilk** [comment]
@jebsolutions - you are correct, zstd long range mode is not really a thing that zfs can do ;-)

@justinpryzby: this issue can be closed, the requested feature can not be done
