### ISSUE TITLE
cache flush (drop_cache)  and/or direct IO for data verification purposes

### ISSUE THREAD

**Issue by jjYBdx4IL** [openzfs/zfs#11885]
I need a mechnism to verify that my zfs server received its data correctly. For that I need to make sure that the verification process runs against actual data stored physically on disk. Currently, I'm using sync, drop_caches and manual cache starvation (slow!) for that. Alternatively, I could reboot the machine. None of that is satisfactory for a filesystem that claims high data security but does not provide a means to verify the correct transfer of data to it.

A reliably working drop_caches mechanism would be preferable im my case.

**Comment by adamdmoss** [comment]
What doesn't work about drop_caches?  It appears to work fine for me.
Also, FWIW, I believe 'zpool scrub' is exactly the process you describe: 'make sure that the verification process runs against actual data stored physically on disk'

**Comment by jjYBdx4IL** [comment]
I read somewhere that it's not 100%. And I can confirm that. And scrub cannot compare data to external data sources where I'm copying from.

**Comment by h1z1** [comment]
> I read somewhere that it's not 100%.  And I can confirm that.

Would be the first time I've ever heard this.   What are you writing to drop_caches because there are three values that do  [different things](https://github.com/torvalds/linux/blob/29c395c77a9a514c5857c45ceae2665e9bd99ac7/Documentation/admin-guide/sysctl/vm.rst#drop_caches). 

> And scrub cannot compare data to external data sources where I'm copying from. For that I need to read back the on-disk data.

You're over thinking this.  Any hash function (sha*, md5, etc) on the source data can be compared to what you stored.   Regardless of what is in cache somewhere, scrub most certainly _does_ read from disk, that is the point of it.

**Comment by jjYBdx4IL** [comment]
Check zpool iostat after dropping caches. Pointless.

**Comment by h1z1** [comment]
Those stats aren't going to show you what hit disk.  There's no universal way to verify something in between hasn't lied (*cough EMC .. cloud providers*).   You have to force ZFS to not do the right thing (enabling nocacheflush for example).

You don't need to reboot.  ZFS groups at most zfs_txg_timeout writes into one batch.  Default is I believe 3 seconds .  

> None of that is satisfactory for a filesystem that claims high data security but does not provide a means to verify the correct transfer of data to it.

That is a ridiculous assumption to make.

Not sure what it is you're trying to validate though.  Data at rest IS verifiable or it would not have succeeded. Period.
