### ISSUE TITLE
Wrong return operand order in asm zfs_fetcher

### ISSUE THREAD

**Issue by slavonnet** [openzfs/zfs#11908]
in code module/zcommon/zfs_fletcher_intel.c:
```
                asm volatile("vpaddq %ymm4, %ymm0, %ymm0");
                asm volatile("vpaddq %ymm0, %ymm1, %ymm1");
                asm volatile("vpaddq %ymm1, %ymm2, %ymm2");
                asm volatile("vpaddq %ymm2, %ymm3, %ymm3");
```
in examole  from Intel https://software.intel.com/content/www/us/en/develop/articles/fast-computation-of-fletcher-checksums.html another order of params:
```
.sloop
	vpmovzxdq  data, [buf]	; loads DWORD data into QWORD lanes
	add	   buf, 16
	vpaddq	   a, a, data
	vpaddq	   b, b, a
	vpaddq	   c, c, b
	vpaddq	   d, d, c
	cmp	   buf, end
	jb	   .sloop
```

you have `ymm0 += ymm1 + ymm1` must be `ymm0 += ymm0 + ymm1`

VPADDQ ymm1, ymm2, ymm3/m256 
Add packed quadword integers from ymm2, ymm3/m256 and store in ymm1.

Right?

Must be like this:

```
                asm volatile("vpaddq %ymm4, %ymm4, %ymm0");
                asm volatile("vpaddq %ymm0, %ymm0, %ymm1");
                asm volatile("vpaddq %ymm1, %ymm1, %ymm2");
                asm volatile("vpaddq %ymm2, %ymm2, %ymm3");
```

If I'm right, then the fix will automatically tell everyone that all the check amounts are not correct and the systems will fall off en masse?

Havre a nice day!

**Comment by behlendorf** [comment]
I see what you're saying but I'd be very surprised if we've been calculating incorrect fletcher values.  When adding this functionality we added two cross-checks to ensure all of the optimized implementations generate the same checksums.

1) If you set the module option `/sys/module/zcommon/parameters/zfs_fletcher_4_impl=cycle` then ZFS will cycle through the available implementations when checksumming blocks.  This should immediately show checksum failures if one of the implementations was wrong.

2) The `ztest_fletcher()` function in the `ztest` test program verifies this code by allocating a buffer, randomly filling it, then verifying that all of the fletcher implementations generate the exact same checksum.

Offhand I can't explain the discrepancy.  But neither of the checks above have ever detected and issue, nor have we had any reports of this kind of problem.

**Comment by rincebrain** [comment]
I looked in the [big Intel Manuals](https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html#combined), and I can't find anything that specifies that the first and second operands must be the same. It says "The PADDQ and VPADDQ instructions add packed quadword integers from the first source operand and second
source operand and store the packed integer results in the destination operand. " - for PADDQ, the destination operand appears to be implicit (e.g. you do paddq xmm1, xmm2 and it does xmm1 = xmm1 + xmm2), but for VPADDQ, it's explicitly separate.

The descriptions of the two instructions' operations (paddq and vpaddq) go:
```
PADDQ (with 64-Bit operands)
DEST[63:0] := DEST[63:0] + SRC[63:0];

VPADDQ (VEX.128 encoded instruction)
DEST[63:0] := SRC1[63:0] + SRC2[63:0];
DEST[127:64] := SRC1[127:64] + SRC2[127:64];
DEST[MAXVL-1:128] := 0;
```

and I'd really expect them to allude somewhere to the need for operand1 and operand2 to be the same if that requirement existed (or even, like with paddq, not make it a 3-operand instruction at all if you're going to do that, and just make it 2).

**Comment by AttilaFueloep** [comment]
@slavonnet  You're not taking into account the differences between Intel and AT&T syntax. OpenZFS is using the AT&T syntax, and Intel, well, Intel syntax. So this Intel syntax snippet
```
> .sloop
> 	vpmovzxdq  data, [buf]	; loads DWORD data into QWORD lanes
> 	add	   buf, 16
> 	vpaddq	   a, a, data
> 	vpaddq	   b, b, a
> 	vpaddq	   c, c, b
> 	vpaddq	   d, d, c
> 	cmp	   buf, end
> 	jb	   .sloop
```
would read 
```
> .sloop
> 	vpmovzxdq  (buf), data	; loads DWORD data into QWORD lanes
> 	add	   $16, buf
> 	vpaddq	   data, a, a
> 	vpaddq	   a, b, b
> 	vpaddq	   b, c, c
> 	vpaddq	   c, d, d
> 	cmp	   buf, end
> 	jb	   .sloop
```
 in AT&T syntax, which perfectly matches the existing code.

**Comment by slavonnet** [comment]
@rincebrain My post is about the fact that the destination operand in those instructions that I saw is always the first, and you have the last.

@AttilaFueloep The last time I actually wrote in ASM was back in the days of PalmOS. I did not know that there is a different type of code recording (intel and at & t).

How do I understand the false alarm? I apologize for disturbing you then.

**Comment by AttilaFueloep** [comment]
D'oh, the above `cmp  buf, end` should of course read `cmp end, buf`.

@slavonnet No problem, glad to help. Could you please close this issue if your concern is resolved?
