### ISSUE TITLE
Intermittent stat Input/output errors on 0.8.6

### ISSUE THREAD

**Issue by nathanfaber** [openzfs/zfs#11910]
### System information
Type | Version/Name
--- | ---
Distribution Name	| CentOS 
Distribution Version	| 7-9.2009.1
Linux Kernel	| 3.10.0-1160.21.1
Architecture	| x86_64
ZFS Version	| 0.8.6-1
SPL Version	| 0.8.6-1

### Describe the problem you're observing
We upgraded a large pool from 0.6.5.8-1 to 0.8.6-1 recently and have had intermittent Input/output errors using stat for files that have been at rest for years. We can see this happening in the logs from a batch borg that runs nightly while it scans over the filesystem. When borg runs again or when we manually check these files, they succeed without stat errors.

The pool was upgraded 4/1 - you can see the errors appearing shortly after in the histogram: `2021-04-01.10:47:28 zpool upgrade Pool1`

This system has been running for years with the same pool, without error. We have a parallel system still running with 0.6.5.8-1 that continues without error.

<img width="1198" alt="Screen Shot 2021-04-16 at 10 12 03 AM" src="https://user-images.githubusercontent.com/16848553/115037214-3a971a00-9e9c-11eb-82fc-16b0a8bd8d73.png">

<img width="1198" alt="Screen Shot 2021-04-16 at 10 19 02 AM" src="https://user-images.githubusercontent.com/16848553/115038118-37e8f480-9e9d-11eb-9935-2425fb2ef4d6.png">

```
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
Pool1   308T   292T  15.8T        -         -    36%    94%  1.00x    ONLINE  -
```

### Describe how to reproduce the problem
We are unable to reproduce this on demand. Attempting to observe one of the files that failed a stat after the fact works correctly.

### Include any warning/errors/backtraces from the system logs
Nothing is reported that we can find, beyond the userspace errno.

**Comment by behlendorf** [comment]
> Nothing is reported that we can find, beyond the userspace errno.

Thanks for reporting this.  Can you determine what `errno` is being returned by the stat, that might provide some additional insight in to the problem.

**Comment by rincebrain** [comment]
The screenshot contains the results of searching for "stat: [Errno 5] Input/output error", so I'm going to go out on a limb and say it's EIO.

**Comment by nathanfaber** [comment]
> > Nothing is reported that we can find, beyond the userspace errno.
> 
> Thanks for reporting this. Can you determine what `errno` is being returned by the stat, that might provide some additional insight in to the problem.

Apologies, I thought I included that. According to borg error messages, it is errno 5 (`stat: [Errno 5] Input/output error`).
I am attempting to catch it live but no luck yet.

**Comment by nathanfaber** [comment]
More datapoints:
1) There was a scrub running during these I/O errors to user space which finished two days ago (`scrub repaired 4K in 7 days 20:04:54 with 0 errors on Sat Apr 17 16:04:56 2021`)
2) A disk just faulted out of that pool today bringing it to DEGRADED (z3). `2021-04-19T09:09:22.229400-04:00 zed: eid=8318 class=statechange pool_guid=0x98AE6D3B8A796660 vdev_path=/dev/sdca1 vdev_state=FAULTED`
3) No additional input/output stat errors have occurred since the end of the screen shot search. (Last one: `2021-04-16T03:32:16.805333-04:00`)
