### ISSUE TITLE
Building from git tip no longer changes the RPM 'release' version number

### ISSUE THREAD

**Issue by siebenmann** [openzfs/zfs#11916]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 33
Linux Kernel	| 5.11.12-200.fc33.x86_64
Architecture	| x86_64
ZFS Version	| git tip, currently 44287ffa0d5d6f23b4dc082b67ea5b7c5a465d8e
SPL Version	| git tip, currently 44287ffa0d5d6f23b4dc082b67ea5b7c5a465d8e

### Describe the problem you're observing

In the past, building from git tip generated RPMs with 'release' version numbers that contained git revision information, for example rc1_471_g38280c352.fc33. Starting recently, the generated version number does not contain this information when built from git tip; I get only a RPM version of '2.1.99' and a Release of '1.fc33'. This makes DNF believe that your newly generated git tip RPMs are the same version as your currently installed older no-longer-git-tip RPMs, and refuse to upgrade them.

The modinfo command also shows the version as 2.1.99-1, although (for my installed module) it reports the 'srcversion' as B64ADE3D6B29D74760B0135.

### Describe how to reproduce the problem
Build from git tip with `autogen.sh; configure --with-config=user; make pkg-utils rpm-dkms`. It's possible that this is no longer the correct way to build ZFS from source for DKMS RPMs, but this is the traditional incantation that's worked for me so far.

**Comment by siebenmann** [comment]
On investigation of what `configure` is doing to determine the version number, I believe that it winds up running:
```
 _match="${ZFS_META_NAME}-${ZFS_META_VERSION}"
 _alias=$(git describe --match=${_match} 2>/dev/null)
```
However, since commit 9ac82cab2d8e5235b61e6811203793758c30b994, I believe that ZFS_META_VERSION has been increased to something that is not tagged in the repository, which makes this into `git describe --match=zfs-2.1.99`, which fails. As a result, `configure` winds up using the base release version from `META` of 1.

Fixing this may be awkward, since one doesn't really want to take the version number down from 2.1.99 (since then dnf will think that the newly generated RPMs are older than your installed 2.1.99-1 RPMs).

**Comment by behlendorf** [comment]
That's an unfortunate side effect of this change.  One way to address this would be to push a `zfs-2.1.99` tag to the repository which references commit 9ac82ca.  This would allow the existing machinery to work as intended and avoiding rolling back any version numbers.  The `release` field for the master branch would be updated to `zfs-2.1.99-117-g44287ffa0` which is newer than `2.1.99-1`.

**Comment by siebenmann** [comment]
I can now confirm that this appears to work. I built new ZFS RPMs as part of a Fedora kernel update, they had version and release numbers that looked right ('2.1.99-119_gf9bece92e.fc33', current git tip), and dnf would upgrade my existing 2.1.99-1 RPMs to them.
