### ISSUE TITLE
OpenZFS release tarballs are unusable on FreeBSD due to missing file

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#11922]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 12.2/13.0
Architecture	| x86_64
ZFS Version	| 2.0.X

### Describe the problem you're observing
While trying to see if #11921 was ever not true, I grabbed a release tarball of 2.0.4, and discovered this.

Attempting to use any 2.0.X release tarball (I tested 2.0.0, 2.0.3, and 2.0.4) on FreeBSD fails to compile with an error about being unable to find a "sys/ccompat.h" include. Said file exists in include/os/freebsd/spl/sys/ccompat.h in the repo dating back to before 2.0-release was first created, but somehow it didn't make it into any of the release tarballs.

Cloning git, checking out any of the zfs-2.0.X tags, and building works.

(It appears this has already been fixed in whatever packaging scripts are in use, as the 2.1.0-rc3 tarball contains the file in question, so this bug is mostly for other people to find if they run across this problem and search for it.)

### Describe how to reproduce the problem
Just grab any of the OpenZFS 2.0.X release tarballs and try building them on FreeBSD.

**Comment by allanjude** [comment]
This was fixed in https://github.com/openzfs/zfs/commit/92e8fb63956e8df91bab9644a2b5838486942686 when I found the same problem.

**Comment by rincebrain** [comment]
Ah, great! Thanks for the context.

**Comment by allanjude** [comment]
We might need to tag it somewhere to have it pulled into the next 2.0.x release

Maybe @tonyhutter knows what the procedure is for that

**Comment by gdevenyi** [comment]
What about doing a quick x.x.x.1 tag for all those to fix them so there are usable tarballs?

**Comment by behlendorf** [comment]
Recently we've been using project tag to keep track of any backports.  I went ahead and added the original issue #11705 to the 2.0-release project so we remember to pull it in for the next tag.
