### ISSUE TITLE
zed_guid_to_pool() broken on hosts with dash as /bin/sh

### ISSUE THREAD

**Issue by ZNikke** [openzfs/zfs#11954]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.2 LTS
Linux Kernel	|5.4.0-72-generic
Architecture	|x86_64
ZFS Version	|2.1.0-rc4
SPL Version	|2.1.0-rc4

### Describe the problem you're observing

On hosts with `dash` as `/bin/sh` the `zed_guid_to_pool()` helper function in `zed.d/zed-functions.sh` doesn't work due to using the dash-internal `printf` with a format it doesn't understand.

Suggested workaround is to either use the binary printf, ie `/usr/bin/printf` although `/bin/printf` works on newer Linux distros, or to simply declare the zed.d scripts to be bash scripts with `#!/bin/bash`.

The latter would likely be more honest with regards to how much is actually tested with other shells, and make it easier for developers with nice features like local variables in functions etc. There's nothing wrong with stating that a script is a bash-script, it's just being honest with the dependency. But saying that a script is an sh-script opens up cans of worms since then you must really really be sh, which I know openzfs knows and tries hard to be but yet cases like this are missed despite shellcheck etc.

### Describe how to reproduce the problem

```
# /bin/dash
# . /etc/zfs/zed.d/zed-functions.sh
# zed_guid_to_pool $(zpool list -Ho guid | head -n 1)
/bin/dash: 514: printf: %l: invalid directive
```

**Comment by nabijaczleweli** [comment]
Added this to #11935
