### ISSUE TITLE
"zd0 p1 p2 3" what is this?! "zd16 p1 p2 3" Make it stop! "zd96: p1 p2 p3 p4 p5 p6 p7 p8" Help!

### ISSUE THREAD

**Issue by timdonovanuk** [openzfs/zfs#11979]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox
Distribution Version	| 6.4
Linux Kernel	| 5.4.106-1-pve
Architecture	| Intel NUC 11 Pro i3
ZFS Version	| 2.0.4-pve1
SPL Version	| 2.0.4-pve1

### Describe the problem you're observing

Generally my proxmox terminal doesn't show any output. It just sits there. Until recently.

``zd0 p1 p2 3 ``

What on earth is this appear on the command line? Well maybe it will go away?

``zd16 p1 p2 3``

Uh...what? Help?

``zd16 p1 p2 3``
``zd48: p1 p2 p3``

I'm now up to random ``zd96: p1 p2 p3 p4 p5 p6 p7 p8`` messages appearing unsolicited on my console and there is no indication of what they are.

**Why I'm reporting this:** If you google these weird messages, most of the reports are complaining about kernel panics, which means seeing these completely spurious messages popup in my console is diconcerting to say the least!

dmesg just shows the same output.

**Comment by mskarbek** [comment]
Its just indication of an udev event.

`dmesg`:
```
[ 6462.939580]  zd48: p1 p2
[ 6463.963503]  zd48: p1 p2
[ 6464.978310]  zd48: p1 p2
```

`udevadm`:
```
# udevadm monitor                                                                                                                                                                             [5/5]
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[6436.391247] change   /devices/virtual/block/zd48 (block)
UDEV  [6436.418297] change   /devices/virtual/block/zd48 (block)
KERNEL[6462.939349] change   /devices/virtual/block/zd48 (block)
KERNEL[6462.940236] add      /devices/virtual/block/zd48/zd48p1 (block)
KERNEL[6462.940312] add      /devices/virtual/block/zd48/zd48p2 (block)
```
This will happen whenever you will create new VM in Proxmox and install system on it - ZVOL will be partitioned which will trigger udev event on the host and print information about it. Nothing to be worried about.

**Comment by timdonovanuk** [comment]
Ah thank you! I wonder if the mechanism outputting these could be tweaked to be a little bit more descriptive?

**Comment by nabijaczleweli** [comment]
These are actually output by the kernel partitioner in `linux/block/partitions.c#check_partition()`:
```c
	state->bdev = bdev;
	disk_name(hd, 0, state->name);
	snprintf(state->pp_buf, PAGE_SIZE, " %s:", state->name);
	if (isdigit(state->name[strlen(state->name)-1]))
		sprintf(state->name, "p");

	i = res = err = 0;
	while (!res && check_part[i]) {
		memset(state->parts, 0, state->limit * sizeof(state->parts[0]));
		res = check_part[i++](state);
		if (res < 0) {
			/*
			 * We have hit an I/O error which we don't report now.
			 * But record it, and let the others do their job.
			 */
			err = res;
			res = 0;
		}

	}
	if (res > 0) {
		printk(KERN_INFO "%s", state->pp_buf);

		free_page((unsigned long)state->pp_buf);
		return state;
	}
```

Where `state->pp_buf` is populated by the format-specific partitioners in `block/partitions/{msdos,efi,ultrix,,&c.}.c`, usually via `block/partitions/check.h#put_partition()`:
```c
static inline void
put_partition(struct parsed_partitions *p, int n, sector_t from, sector_t size)
{
	if (n < p->limit) {
		char tmp[1 + BDEVNAME_SIZE + 10 + 1];

		p->parts[n].from = from;
		p->parts[n].size = size;
		snprintf(tmp, sizeof(tmp), " %s%d", p->name, n);
		strlcat(p->pp_buf, tmp, PAGE_SIZE);
	}
}
```

You can only disable partitioning on loops; mmcblk RPMB and BOOT areas are never scanned, nor are nvmeXcXnX devices.

**Comment by kneutron** [comment]
FYI this does not appear to be a ZFS-specific issue and can probably be closed

**Comment by behlendorf** [comment]
Closing.  The message here could probably be improved but as mentioned above it's generated by the kernel and not OpenZFS so there's nothing we can do about it.
