### ISSUE TITLE
zfs send on readonly pools broke in 2.0

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#11985]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| bullseye
Linux Kernel	| 5.10.0-6-amd64
Architecture	| x86_64
ZFS Version	| 2.0.3

### Describe the problem you're observing
Someone came on IRC asking for help sending a pool that panicked on importing readwrite but imported readonly fine. We suggested using `zfs send [filesystem]`, since everything on the pool was, by definition, readonly. They reported that they got back "warning: cannot send 'testpool': Invalid argument". We tried to reproduce this, and found that it worked as expected on 0.8.6-1~bpo10+1 and was broken as they reported on 2.0.3 and 2.1.0-rc4.

### Describe how to reproduce the problem
```
zpool import -o readonly=on testpool
zfs send testpool > /dev/null
```

edit to add:
Per later discussion, this doesn't reproduce on Debian buster, CentOS 7, or CentOS 8.
It definitely reproduces with the aforementioned ZFS versions on Debian bullseye.
The original report that I was reproducing was from Gentoo.
(Since 0.8.x caps on 5.9, and bullseye ships kernel 5.10, I can't test if that would break, too.)
2.1.0-rc4 works fine on buster on the stock kernel (4.19.0-16-amd64), now I'm going to try a buster-backports kernel on buster and see if that breaks. If it does, I'm going to try and figure out if there's a specific version where it starts breaking on vanilla kernels - if it doesn't, same question against bullseye instead.

**Comment by h1z1** [comment]
What version was the pool created with?

```
[works] 0.8.0 -> 2.1.99-1
[works] 2.1.99-1 -> 0.8.0 
[works] 2.1.99-1  <-> 2.1.99-1
```

**Comment by rincebrain** [comment]
The pools I tested that it didn't work on were created right before attempting this, on 2.0.3 and 2.1.0-rc4. And the problem was not some incompatibility with the receiver, the problem was that `zfs send testpool` with the readonly pool errored out without generating a stream at all.

**Comment by h1z1** [comment]
> The pools I tested that it didn't work on were created right before attempting this, on 2.0.3 and 2.1.0-rc4.

Good to know, so we're at somewhere between 2.1.0-rc4 and 2.1.99

> And the problem was not some incompatibility with the receiver, the problem was that `zfs send testpool` with the readonly pool errored out without generating a stream at all.
>

Understood.  I did that to confirm the stream was valid.

**Comment by rincebrain** [comment]
> 2.1.99

Could you include what git version you're using, since 2.1.99 just means "some revision of git master before 2.1 was released"?

I just tested this with c903a756 and it still fails in the way I described.

**Comment by h1z1** [comment]
```
# zfs version
zfs-2.1.99-1
zfs-kmod-2.1.99-1
#
```

https://github.com/openzfs/zfs/releases/tag/zfs-2.1.99

**Comment by rincebrain** [comment]
Oh, you...actually used that tag. It's not really...meant to be used, it's just a workaround for #11916 .

Regardless, I suspect you're doing something differently, since the alternative is to propose "it broke in a strange way, started working again in a very narrow window of commits, and then broke again in the same way". Or there's something different between my system and yours that results in a behavior difference - what distro et al are you on, so I can test?

**Comment by h1z1** [comment]
Weird I added that to the message above heh.   Githubthings(tm)

That was done using CentOS 7.7,  5.4 kernel

As for steps, I assumed you were doing something like :

```
#  ZP=tank
#  D0=/dev/shm/${ZP}.00.bin
#     zpool destroy $ZP
#     dd if=/dev/zero of=$D0 bs=4096 count=$((1000000000/4096))
#     zpool create $ZP ${D0}
#     touch /$ZP/foobar.baz
#     zpool export $ZP
#     zpool import -o readonly=on -d ${D0} $ZP
#     zfs send $ZP > /dev/null
#     zpool export $ZP
#     zpool destroy $ZP
```

**Comment by rincebrain** [comment]
That is, more or less, what I'm doing, yes - I'm using `truncate` to generate the sparse files, and trying against the existing pool i generated on 0.8 as well just in case, but otherwise, yeah.

Let me see about reproducing this, I do have a CentOS 8 VM, a 7 VM shouldn't be that hard to produce...

**Comment by rincebrain** [comment]
I've made a discovery.

This is just a dupe of #11445. Closing.

**Comment by h1z1** [comment]
What the..  wonder why that didn't come up in search.      Maybe zfs should produce some helpful warning but aside from that +1 for finding.
