### ISSUE TITLE
Fedora 34 zfs-testing repo returns 403 Access Denied

### ISSUE THREAD

**Issue by dave0x40** [openzfs/zfs#11981]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 34
Linux Kernel	| 5.11.17-300
Architecture	| x86_64
ZFS Version	| 2.0.4-1
SPL Version	| 2.0.4-1

### Describe the problem you're observing
zfs-testing repo for Fedora 34 is missing

### Describe how to reproduce the problem

```
dnf install https://zfsonlinux.org/fedora/zfs-release.fc34.noarch.rpm
gpg --import --import-options show-only /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
dnf config-manager --enable zfs-testing
dnf update
```

### Include any warning/errors/backtraces from the system logs
```
Errors during downloading metadata for repository 'zfs-testing':
  - Status code: 403 for http://download.zfsonlinux.org/fedora-testing/34/x86_64/repodata/repomd.xml (IP: 2600:1fa0:4081:1c49:34da:853a::)
```

<!--
*IMPORTANT* - Please mark logs and text output from terminal commands
or else Github will not display them correctly.
An example is provided below.

Example:
```
this is an example how log text should be marked (wrap it with ```)

-->

**Comment by behlendorf** [comment]
The F34 zfs-testing repository has been added and contain zfs-2.1.0-rc4.
