### ISSUE TITLE
zpool hang when open autotrim and continue working about 3 days under high load

### ISSUE THREAD

**Issue by green-apple-ok** [openzfs/zfs#12018]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 14.04.1
Linux Kernel	| 4.4.0-24-generic
Architecture	| x86_64
ZFS Version	| 0.8.6-1
SPL Version	| 0.8.6-1

### Describe the problem you're observing
Create zpool with autotrim = on, then create 4 zvol to use. After about 3 days, zpool hang for ever.
### Describe how to reproduce the problem
1. create zpool with autotrim = on
2. create 4 zvols with fc target to export to other pc.
3. perform stress test
4. about 3 days, zpool hung

### Include any warning/errors/backtraces from the system logs

![image](https://user-images.githubusercontent.com/81225739/117598189-d6edcd00-b179-11eb-8e45-00b9c21e9bd0.png)

**Comment by kneutron** [comment]
Support for Ubuntu 14.04 LTS ended on April 30th 2019. Suggest you upgrade your OS and kernel version.

**Comment by green-apple-ok** [comment]
We have already upgraded the kernel to 4.4.0-24. And from which kernel version the trim can support well?

**Comment by kneutron** [comment]
Upgrading just the kernel is not sufficient - your entire OS is not supported (for over 2 years now) and will not receive any patches or security updates. Suggest you upgrade to at least Ubuntu 18 if not 20.04 after doing a full backup

**Comment by TimLand** [comment]
> Upgrading just the kernel is not sufficient - your entire OS is not supported (for over 2 years now) and will not receive any patches or security updates. Suggest you upgrade to at least Ubuntu 18 if not 20.04 after doing a full backup

Is there any centos version suggest？ centos 7 is ok？
