### ISSUE TITLE
resilvering process consume all memory and swap

### ISSUE THREAD

**Issue by nasiryilmaz** [openzfs/zfs#12013]
I have 2.0.4 with rhel 7.9  

The total data size is 206 TB multi-disk resilvering process is running  after a while resilvering process suck in all memoy  kdump crash the systems

Mem:           125G        111G         13G        920M        1.2G         13G
Swap:          122G        2.0G        120G

**Comment by rincebrain** [comment]
Could you please provide some more details about the system and problem in question?

* What is the layout of the pool or pools on the system?
* How many disks are you resilvering at the same time - in the same pool, or in different ones?
* Has this happened once, or multiple times?
* Did anything possibly relevant get logged in dmesg before the crash?
