### ISSUE TITLE
corrupted pool with 2.1.0-rc5

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#12025]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| EndeavourOS
Distribution Version	|
Linux Kernel	| 5.12.2 (zen)
Architecture	| x86 (AMD)
ZFS Version	| 2.1.0-rc5
SPL Version	| 2.1.0-rc5

### Describe the problem you're observing

Today I gave 2.1.0-rc5 a try. I had 2.0.4 installed before. install with dkms was going fine, but after boot one of my pools is throwing an error:

```
  pool: zstore
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 07:35:40 with 0 errors on Thu Apr  1 07:35:41 2021
config:

	NAME                       STATE     READ WRITE CKSUM
	zstore                     ONLINE       0     0     0
	  mirror-0                 ONLINE       0     0     0
	    WD40EFRX-WCC7K6XALFKX  ONLINE       0     0     0
	    WD40EFRX-WCC7K2YAJA69  ONLINE       0     0     0
	  mirror-1                 ONLINE       0     0     0
	    WD40EFRX-WCC7K6YX6SAA  ONLINE       0     0     0
	    WD40EFRX-WCC7K4JKN36U  ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        zstore/data/BACKUP/rakete_home:<0x0>
```

I did not do a feature upgrade yet. Obvioulsy it is an issue with dataset `zstore/data/BACKUP/rakete_home`. It is not mounted and if I try to mount it I get:

```
6# zfs mount zstore/data/BACKUP/rakete_home
cannot mount 'zstore/data/BACKUP/rakete_home': Input/output error
```
How should I approach this now?

**Comment by AttilaFueloep** [comment]
Most likely this is #11294, so your pool should be fine. I'd just wait for #11300 to land or revert d1d4769.

**Comment by mabod** [comment]
ok. Or can I just go back to 2.0.4? Will that clear the error?

**Comment by mabod** [comment]
ok. thanks. May be this question is off topic, but why isnt it possible to to selective / partial scrubs for specific datasets. e.g. 
`zpool scrub mypool/mydataset` 
This would help dramatically  to fix an issue like this.

**Comment by mabod** [comment]
One scrub was enough for me to remove the error message. Thanks. I will close this issue.
