### ISSUE TITLE
Partial scrub support

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#12026]
I am wondering if it would be possible to get the zpool command to support partial scrubs by dataset. e.g. 
`zpool scrub mypool/mydata1/mydatset2`

Every once in a while we see meta data issues like

https://github.com/openzfs/zfs/issues/12025
https://github.com/openzfs/zfs/issues/11294

They are only affecting one dataset and could easily be fixed. But instead a full scrub of the whole pool is need which can take days.

**Comment by AttilaFueloep** [comment]
Looks like #8995 should do the job.

**Comment by mabod** [comment]
Yes, that looks right.
But this PR is already in the pipeline for 2 years. Not very promising.

**Comment by AttilaFueloep** [comment]
Still your your best bet I'd say since a) it gained some traction recently and b) it perfectly matches your use case. I'd close this one and participate there.

**Comment by mabod** [comment]
Closing this. Waiting for the PR.

**Comment by jumbi77** [comment]
Beside the already mentioned PRs there is also PR #7257 which is open for a long time. Looking forward to this PR too :)
