### ISSUE TITLE
Attempting to use ZFS on files over NFS is problematic for FreeBSD

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#12032]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13.0-RELEASE
Architecture	| x86_64
ZFS Version	| 2.1.99-150-ga27ab6d43

### Describe the problem you're observing
While debugging #12022, I had been working with pools on files over NFS.

When I tried this on FreeBSD/PPC64 with my changes, it failed in the ways I am about to describe, so I tried it with vanilla git on FreeBSD/x86_64, and here we are.

zpool import -d [NFS mount] will report no pools available on FBSD.
If you attempt to create such a pool on a file in FBSD, it will report "internal error: out of memory"
zdb -e -p [NFS mount] [pool there] [...] will report No such file or directory.

zpool import -d [local path with copied pool file] [pool name] works fine.

I'm positive this used to work as of the OpenZFS version shipped in FBSD 13.0-RELEASE (it calls itself 2.0.0-FreeBSD-gf11b09dec), as it's how I imported and created one of the datasets for #12030.

### Describe how to reproduce the problem
mount [path to NFS share] /mnt/
zpool import -d /mnt/ or zpool create poolname /mnt/somefile

### Include any warning/errors/backtraces from the system logs
dmesg logged
`pid 857 (zpool) attempted to use unsafe AIO requests - not logging anymore`
but otherwise nothing.

**Comment by rincebrain** [comment]
From a quick test, it certainly appears to - `zpool import -d [...]` shows pools, `zpool import -d [...] poolname` successfully imports one and mounts all datasets...

**Comment by freqlabs** [comment]
Ah, the import code was recently enhanced to do AIO by e50b5217e7, I wonder if that is having issues over NFS.
