### ISSUE TITLE
possible O_TMPFILE regression

### ISSUE THREAD

**Issue by dankamongmen** [openzfs/zfs#12060]
### System information
Type | Debian Unstable, 5.12.1
 --- | ---
Distribution Name	| Debian
Distribution Version	| Unstable
Linux Kernel	| Custom 5.12.1
Architecture	| x86_64 (amd threadripper)
ZFS Version	|zfs-2.1.99-1
SPL Version	|2.1.99-1
`[   13.210470] ZFS: Loaded module v2.1.99-1, ZFS pool version 5000, ZFS filesystem version 5`

### Describe the problem you're observing
In my previous 5.11.18 kernel, `O_TMPFILE` worked just fine on my zfs datasets. Since booting into 5.12.1, all attempts to use `O_TMPFILE` fail with `EOPNOTSUPP`. It's entirely possible that this is somehow my error, as it seems a surprising regression.

### Describe how to reproduce the problem

```c
[schwarzgerat](1) $ cat ~/zfs.c 
#define _GNU_SOURCE
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>

int main(int argc, char** argv){
  int fd = open(argv[1], O_TMPFILE|O_RDWR);
  if(fd < 0){
    fprintf(stderr, "error: %s\n", strerror(errno));
    return -1;
  }
  printf("opened %s at %d\n", argv[1], fd);
  close(fd);
  return 0;
}
[schwarzgerat](0) $ 
```

compile it, and provide a path on a zfs dataset. `EOPNOTSUPP` results.

**Comment by dankamongmen** [comment]
argh, it's `EOPNOTSUPP`, not `ENOENT`:


```c
[schwarzgerat](255) $ strace -f ./a.out erp
execve("./a.out", ["./a.out", "erp"], 0x7ffcf2037ec0 /* 62 vars */) = 0
brk(NULL)                               = 0x56059cd41000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=327289, ...}) = 0
mmap(NULL, 327289, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f913e54d000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@n\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1839792, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f913e54b000
mmap(NULL, 1852680, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f913e386000
mprotect(0x7f913e3ab000, 1662976, PROT_NONE) = 0
mmap(0x7f913e3ab000, 1355776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25000) = 0x7f913e3ab000
mmap(0x7f913e4f6000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x170000) = 0x7f913e4f6000
mmap(0x7f913e541000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f913e541000
mmap(0x7f913e547000, 13576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f913e547000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f913e54c540) = 0
mprotect(0x7f913e541000, 12288, PROT_READ) = 0
mprotect(0x56059c4d0000, 4096, PROT_READ) = 0
mprotect(0x7f913e5c7000, 4096, PROT_READ) = 0
munmap(0x7f913e54d000, 327289)          = 0
openat(AT_FDCWD, "erp", O_RDWR|O_TMPFILE, 0163400) = -1 EOPNOTSUPP (Operation not supported)
write(2, "error: Operation not supported\n", 31error: Operation not supported
) = 31
exit_group(-1)                          = ?
+++ exited with 255 +++
```

**Comment by dankamongmen** [comment]
my old kernel also claims 2.1.99-1 zfs:
```
[schwarzgerat](0) $ modinfo /lib/modules/5.11.18nlb/extra/zfs/zfs.ko | grep -i version
version:        2.1.99-1
srcversion:     766F28BBCC106A0EEE0347D
vermagic:       5.11.18nlb SMP mod_unload modversions 
[schwarzgerat](0) $ 
```

**Comment by rincebrain** [comment]
2.1.99 is either the version used if you have a git checkout or you downloaded the otherwise-unlabeled 2.1.99 tag which was created just to work around a bug and built it. (Normally it also embeds the git revision if you did the former...)

**Comment by dankamongmen** [comment]
> 2.1.99 is either the version used if you have a git checkout or you downloaded the otherwise-unlabeled 2.1.99 tag which was created just to work around a bug and built it. (Normally it also embeds the git revision if you did the former...)
> 
> edit: your test program WFM on a system I had laying around running [2babd20](https://github.com/openzfs/zfs/commit/2babd200454eff922ba2cae23a20db2308ec8059) . Do you know what version your ZFS modules are, beyond that version string (e.g. if it's a custom kernel, who built them?)

i am running a git checkout. i built them, and am comfortable doing any testing you might like.

here's the machine's 5.12.1nlb configuration: https://nick-black.com/tabpower/config-5.12.1nlb

**Comment by rincebrain** [comment]
Can you specify which git revision your modules are built from, so I can
try reproducing it?

**Comment by dankamongmen** [comment]
i am fairly certain that they are b1e44cdcea09db50c887c2b301e1af1fae1b5aa0, but it might be a slightly older revision (a few days at maximum). is there any way to extract the particular git version from the compiled module?

**Comment by dankamongmen** [comment]
the same `srcversion` is claimed for my 5.12.1nlb kernel's zfs.ko as was my 5.11.18nlb:

```
[schwarzgerat](0) $ modinfo /lib/modules/5.12.1nlb/extra/zfs/zfs.ko | grep -i vers
version:        2.1.99-1
srcversion:     766F28BBCC106A0EEE0347D
vermagic:       5.12.1nlb SMP mod_unload modversions 
```

**Comment by rincebrain** [comment]
If it were compiled into the binary, it'd be reported by "zfs version" and
you could go grepping through "strings" on it - but if it's not reported by
"zfs version", I doubt it's there.

I'm unfamiliar with doing anything useful with srcversion, I'll probably
just test the commit you mentioned then one perhaps a week prior.

**Comment by dankamongmen** [comment]
[schwarzgerat](0) $ zfs version
zfs-2.1.99-1
zfs-kmod-2.1.99-1
[schwarzgerat](0) $

**Comment by rincebrain** [comment]
Neat. On 5.10.0-6-amd64 and  b1e44cd I cannot reproduce this, on 5.12.1 with the identical .config file to yours and  b1e44cd I can.

Let's see what's going on...

**Comment by dankamongmen** [comment]
awesome; after verifying that `O_TMPFILE` was indeed intended to be supported by zfs, i assumed i was somehow making a terrible blunder, and hesitated to report. let me know anything i can do to assist (i'm comfortable rebuilding kernel/modules, running bpf programs, etc.)

**Comment by rincebrain** [comment]
Having not seen any obvious likely candidates in the Linux kernel commit logs or OpenZFS commit logs, I'm bisecting the former between 5.10.0 and 5.12.0 to see where it breaks.

This may take a little while.

**Comment by dankamongmen** [comment]
> Having not seen any obvious likely candidates in the Linux kernel commit logs or OpenZFS commit logs, I'm bisecting the former between 5.10.0 and 5.12.0 to see where it breaks.
> 
> This may take a little while.

Well, like I said, 5.11.18 seems to work, so I'd think you could start there. Not that it matters *too* much with logarithmic search =]

**Comment by rincebrain** [comment]
The problem with that is that Linux versioning isn't monotonic like that - the point releases are backports off the main git tree, but 5.11.18 is on a different tree than 5.12.

**Comment by rincebrain** [comment]
Getting close to finishing the bisect, I am suspicious of torvalds/linux@6521f89170829 .

**Comment by rincebrain** [comment]
Damn, git bisect said "sorry chief it's one of ~15 commits you marked skip, good luck" (all the "skip" commits OpenZFS didn't build against because they had some but not all of the changes that e2a8296131e94ad785f5564156ed2db1fdb2e080 is intended to make compatible with).

I'll examine them manually and see if I can figure out what churned.
[12060bisect.log](https://github.com/openzfs/zfs/files/6510942/12060bisect.log)

**Comment by rincebrain** [comment]
![isn't that neat](https://user-images.githubusercontent.com/214141/118895790-d6b9a400-b8d4-11eb-8cd3-f6fcfd077688.png)

Isn't that nice? :)

(There's still a nonzero amount of work to be done to get this into a PR-able form, I just thought you'd appreciate it.)

**Comment by dankamongmen** [comment]
nicely done!

**Comment by dankamongmen** [comment]
let me know when you have a diff you'd like me to test with

**Comment by rincebrain** [comment]
That was simpler than I expected, in that it did not require doing most of the plumbing I expected it to, just the signature adjustment...

Feel free to experiment with the patch in that PR.
