### ISSUE TITLE
zpool status -x exit code

### ISSUE THREAD

**Issue by spmfox** [openzfs/zfs#12100]
### Describe the feature would like to see added to OpenZFS
Add a error exit code (non zero) to a "zpool status -x" that is reporting an error with any pools.

### How will this feature improve OpenZFS?
This is a small improvement that will help with automation or script creation to periodically check the status of pools.

### Additional context
I did search the issues, there are a lot of issues that mention "exit" or "exit code" so I apologize if this is a duplicate but I didn't see anything like this. I did look at the source code to see if this would be as easy as changing a zero to a one but it doesn't look like that's the case and I don't have much C experience yet.

**Comment by nabijaczleweli** [comment]
That's easy enough (see #12107), but it seems like you're (ab)using timers and zpool-status to do something *much* better served by ZED notifications or reading `/proc/spl/kstat/zfs/$POOL/state` directly, if for automation – why?

**Comment by gmelikov** [comment]
`/proc/spl/kstat/zfs/$POOL/state` was introduced exactly for this case, and it's non-locking https://github.com/openzfs/zfs/commit/f0ed6c744872ec6dc4838947ffc597f4d141864a, this reason is usually all you need to use it in any automation tool.

**Comment by spmfox** [comment]
> `/proc/spl/kstat/zfs/$POOL/state` was introduced exactly for this case, and it's non-locking [f0ed6c7](https://github.com/openzfs/zfs/commit/f0ed6c744872ec6dc4838947ffc597f4d141864a), this reason is usually all you need to use it in any automation tool.

This looks like it works perfectly. I can use that for my purpose, thank you @nabijaczleweli @gmelikov for showing me this.

My inspiration for this was how smartctl -H would return an error exit code along with the actual error and thought zpool status could use this too.

I'm going to close this because it looks like the functionality already exists as you pointed out, so thank you again for the quick responses.
