### ISSUE TITLE
IO is bottlenecked through a single lock

### ISSUE THREAD

**Issue by robn** [openzfs/zfs#12121]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 10.9
Linux Kernel	| 5.10.19-1~bpo10+1
Architecture	| amd64
ZFS Version	| 2.0.4
SPL Version	| 2.0.4

### Describe the problem you're observing

tl;dr: IO is bottlenecked through the kstat lock in `vdev_queue.c`.

I have a large pool of 24x 8T NVMe devices (Intel DC P4510), configured as a single pool of 2x12 RAIDZ2.

```

	NAME           STATE     READ WRITE CKSUM
	i44cyrus       ONLINE       0     0     0
	 raidz2-0     ONLINE       0     0     0
	   i44disk1   ONLINE       0     0     0
...
	   i44disk11  ONLINE       0     0     0
	   i44disk12  ONLINE       0     0     0
	 raidz2-1     ONLINE       0     0     0
	   i44disk13  ONLINE       0     0     0
...
	   i44disk24  ONLINE       0     0     0
```

Yesterday I started bringing in some 40T of data from a different machine using a normal `send | recv` over a direct 10G connection. It appears that we're getting a sustained throughput of ~250M/s. We haven't done a lot of tuning yet so I wasn't entirely sure if this was "good" or not, but it felt low, so I went digging.

(note: there is nothing else of any consequence running on this machine; just basic OS services)

On the receiving side, `perf top` reported that 25% of its time is spent in `osq_lock`, which is the kernel spinlock. So I fired up `bpftrace` and got to work.

Bucketing by the lock pointer shows that there's a single lock receiving a lot more attention than the others:

```
[fastmail root(robn)@imap44 ~]# bpftrace -e 'kprobe:osq_lock { @[arg0] = count(); }'
Attaching 1 probe...
^C
@[-117676299645548]: 1
@[-117669704412716]: 1
@[-117485265829068]: 1
@[-117625234665004]: 1
@[-117458348531436]: 1
...
@[-117723405763756]: 3502
@[-117723442693292]: 3509
@[-117716388578476]: 3540
@[-117723405747372]: 3573
@[-117719621901892]: 11432
@[-117711093901308]: 144076
```

Inspecting this single lock:

```
[fastmail root(robn)@imap44 ~]# bpftrace -e 'kprobe:osq_lock /arg0 == -117711093901308/ { @[kstack(3)] = count() }'
stdin:1:23-25: WARNING: comparison of integers of different signs: 'unsigned int64' and 'int64' can lead to undefined behavior
kprobe:osq_lock /arg0 == -117711093901308/ { @[kstack(3)] = count() }
                      ~~
Attaching 1 probe...
^C

@[
    osq_lock+1
    __mutex_lock.isra.9+137
    vdev_queue_io_to_issue+2778
]: 93753
@[
    osq_lock+1
    __mutex_lock.isra.9+137
    vdev_queue_io_done+235
]: 120459
@[
    osq_lock+1
    __mutex_lock.isra.9+137
    vdev_queue_io+273
]: 205863
@[
    osq_lock+1
    __mutex_lock.isra.9+137
    vdev_queue_io_remove+124
]: 208130
```

I didn't know very much about the internals at this point, and I was assuming there was a single lock around all devices or something like that. After studying `vdev_queue_io` and the headers I saw that a `struct vdev` has `vdev_queue` and `vq_lock` inlined, so the vdev is a reasonable proxy for the lock for tracing purposes, and so:

```
[fastmail root(robn)@imap44 ~]# cat zio.bt 
#include <sys/zio.h>

kprobe:vdev_queue_io
{
  @[((struct zio *)arg0)->io_vd] = count()
}
```

```
[fastmail root(robn)@imap44 ~]# bpftrace -I/usr/include/libspl -I/usr/include/libzfs zio.bt
Attaching 1 probe...
^C

@[0xffff94ee60054000]: 14228
@[0xffff94edce118000]: 14288
@[0xffff94f06863c000]: 14316
@[0xffff94f0034a8000]: 14342
@[0xffff94edfb11c000]: 14491
@[0xffff94edce9f4000]: 14560
@[0xffff94f004790000]: 14703
@[0xffff94ee62378000]: 14785
@[0xffff94ee6d3a8000]: 14799
@[0xffff94edce11c000]: 14855
@[0xffff94edfc550000]: 14867
@[0xffff94f0034ac000]: 14954
@[0xffff94edce358000]: 14996
@[0xffff94ee60040000]: 15017
@[0xffff94ee60050000]: 15065
@[0xffff94f0034a0000]: 15066
@[0xffff94f004794000]: 15110
@[0xffff94ee6d3ac000]: 15184
@[0xffff94edfb118000]: 15191
@[0xffff94edfc554000]: 15199
@[0xffff94f0034a4000]: 15232
@[0xffff94ee6237c000]: 15255
@[0xffff94edce9f0000]: 15255
@[0xffff94edce35c000]: 15273
```

24 separate vdevs, each receiving roughly the same amount of traffic, and none of them with an outlier. So vdev locks are not responsible!

To read it, `vdev_queue_io` (and friends) only work on the vdev lock, so I couldn't understand how the single busy lock was matching the traces that I had. But then I saw that `vdev_queue_io_add` is only called from one place and is `static`, so it has been inlined. But lo, there's another lock, and a global lock at that.

We can't probe an inlined function, but we can probe the thing it calls:

```
[fastmail root(robn)@imap44 ~]# bpftrace -e 'kprobe:kstat_waitq_enter { @[kstack(3)] = count() }'
Attaching 1 probe...
^C

@[
    kstat_waitq_enter+1
    vdev_queue_io+304
    zio_vdev_io_start+156
]: 270092
```

And there it is: all the vdev ops are waiting on a single lock, for a stats counter no less! Oh no!

I don't have a great theory but I suspect this perhaps isn't as noticeable on higher-latency devices (spinners) because they're slower than the lock wait, and perhaps isn't as noticeable on NVMe mirrors because probably most of the time there's only two drives in the mirror, so it doesn't get amplified quite so much.

### Describe how to reproduce the problem

It should be enough to have a wide RAIDZ vdev on top of low-latency devices. And then just pour data into with `zfs recv`.

(I can reproduce this reliably, however I'm on tight deadlines so I don't immediately have much time for experimenting. But I would like to help, and will have a lot more hardware available to work with in the next week or two).

**Comment by scineram** [comment]
Coud you test #12114?

**Comment by robn** [comment]
> Could you test #12114?

A quick read of that change suggests that it won't help, as it doesn't do anything with the lock in question. I will test anyway for avoidance of doubt, but I can't do it for a couple of days.

**Comment by behlendorf** [comment]
Nice detective work.  For a quick way to verify this you can safely comment out those calls to update the stats in `vdev_queue_io_add()`, `vdev_queue_io_remove()`, `vdev_queue_pending_add()` and `vdev_queue_pending_remove()`.  It'll just disable these stats which are visible by reading `/proc/spl/lstat/zfs/<pool>/io`.

It looks like this would be a hot spot on all platforms, and it's the only place in the code where we use these `kstat_waitq_*` / `kstat_runq_*` interfaces.  In practice, I'm not sure how helpful these stats really are to user space so dropping them might be best thing to do.  @amotin any thoughts on this?

**Comment by omarkilani** [comment]
@robn I've created a patch to test this out since I'm doing some testing on fast-ish devices:

https://gist.github.com/omarkilani/64a365d90a7ae388231837f8a76c9a35

For me, this reproducibly improves a short running (60 seconds) pgbench from 13,000tps to 14,500tps.

On a long running pgbench (600 seconds) it's not as noticeable though.

**Comment by robn** [comment]
Thanks all. I should be able to run the same load on Monday, so I'll try patching this out and see where we end up.

**Comment by robn** [comment]
I'm now running @omarkilani's patch (thank you!) in production on a full user workload. `perf top` says we're spending ~0.5% in `osq_lock`, down from 4-5% before the patch (on this workload, which is not the same as when I originally reported it).

So removing or otherwise reworking this stats lock would seem to be a very nice win. If nothing else, I'll keep the patch locally.

**Comment by amotin** [comment]
I've also noticed this issue with profiler last week.  It should be addressed.  Since this code was primarily used on illumos and barely usable via procfs/sysctl on Linux/FreeBSD, @ahrens proposed to disable it by default by adding a tunable.  But since `zpool iostat` was not existing when this code was written, I am thinking whether it should be removed now completely as obsolete, alike to @omarkilani patch, just probably pulling more of unused structures.  Or we could still keep it disabled to not diverge from illumos, if they still want/need it.

**Comment by ahrens** [comment]
@amotin I'm good with any of the solutions you mentioned.

**Comment by behlendorf** [comment]
@amotin I like the idea of removing it entirely since there are better tools available these days to get this kind of profiling information.  Plus it looks to me like `vdev_queue.c` is the only consumer of `kstat_waitq_enter()/exit()` and `kstat_runq_enter()/exit()`.  We could remove these interfaces entirely from the FreeBSD/Linux SPL layers which would ensure we don't add any new consumers.  Which would be nice.  If they're ever needed by illumos it would be easy enough to add them back with some platform specific code.

**Comment by robn** [comment]
Awesome, thanks all!
