### ISSUE TITLE
zfs/hkdf.c:81: possible wrong sized buffer ?

### ISSUE THREAD

**Issue by dcb314** [openzfs/zfs#12130]
In function ‘hkdf_sha512_expand’,
    inlined from ‘hkdf_sha512’ at ../../module/zfs/hkdf.c:165:8:
../../module/zfs/hkdf.c:81:24: warning: ‘crypto_mech2id’ accessing 32 bytes in a region of size 16 [-Wstringop-overflow=]
   81 |         mech.cm_type = crypto_mech2id(SUN_CKM_SHA512_HMAC);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../module/zfs/hkdf.c: In function ‘hkdf_sha512’:
../../module/zfs/hkdf.c:81:24: note: referencing argument 1 of type ‘char *’

**Comment by dioni21** [comment]
What are your distro and gcc versions?  Could be the same problem i had in #12188

**Comment by dcb314** [comment]
Fedora Linux and latest development gcc with flag -D_FORTIFY_SOURCE=2
