### ISSUE TITLE
cannot import pool in initramfs after reboot if zpool.cache is absent

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs#1213]
For some reason, if the pool is not exported at poweroff, and the zpool.cache is absent in the initramfs, the pool cannot be imported with 'pool may be in use from another system'.

I went into the source here:

https://github.com/Rudd-O/zfs/blob/master/cmd/zpool/zpool_main.c#L1699

the linked check above just fails.  Checked with zdb and indeed the pool config does not have a hostid attribute.  Which leads me to believe that the hostid attribute is, for some reason, never getting written in the pool, so next reboot it cannot be read, thus the check for "same hostid" (if ((unsigned long)hostid != system_hostid) {, two lines below the above code) never takes place.

This seems to be a bug -- if the pool is not exported, the hostid attribute should still be in the pool config, cache or not.  Naturally, this breaks zfs-on-root.

Help?

**Comment by gnif** [comment]
For those on the older version, here is a hook for initramfs-tools to remove the zpool.cache file during initramfs creation.

```bash
#!/bin/sh
PREREQ="zfs"
prereqs() {
        echo "$PREREQ"
}

case $1 in
        prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -f "${DESTDIR}/etc/zfs/zpool.cache" ]; then
        rm "${DESTDIR}/etc/zfs/zpool.cache";
fi
```
