### ISSUE TITLE
I am using ubuntu 21 with openzfs 2. I ran zdb -S tank but it hard hangs my system after about 5 min. can I increase verbose or any way to debug why its doing it? thanks

### ISSUE THREAD

**Issue by kocoman1** [openzfs/zfs#12153]
I am using ubuntu 21 with openzfs 2. I ran zdb -S tank but it hard hangs my system after about 5 min. can I increase verbose or any way to debug why its doing it? thanks

**Comment by rincebrain** [comment]
How much RAM do you have, and how large is the pool "tank"? `zdb -S` can have nontrivial RAM usage.
