### ISSUE TITLE
Encryption property does not show as inherited, when the pool is encrypted

### ISSUE THREAD

**Issue by directionless** [openzfs/zfs#12181]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 21.04
Linux Kernel	| 5.11.0-1007-gcp
Architecture	| x86_64
ZFS Version	|  2.0.2-1ubuntu5
SPL Version	| 2.0.2-1ubuntu5

### Describe the problem you're observing

If I create an encrypted pool, I think and datasets created within it should be encrypted. But, this is not displayed with `zfs get`

### Describe how to reproduce the problem

```shell
sudo openssl rand -out /root/password 32
sudo zpool create -O mountpoint=none \
  -O encryption=aes-256-gcm -O keyformat=raw -O keylocation=file:///root/password \
  tank-enc /dev/sdb1
sudo zfs create -o encryption=off tank-enc/ds-clear -o mountpoint=/zfs/tank-enc/ds-clear

seph@seph-linux-disk-encryption-test:~$ zfs get encryption,encryptionroot tank-enc tank-enc/ds-clear
NAME               PROPERTY        VALUE        SOURCE
tank-enc           encryption      aes-256-gcm  -
tank-enc           encryptionroot  tank-enc     -
tank-enc/ds-clear  encryption      off          default
tank-enc/ds-clear  encryptionroot  -            -
```
### Include any warning/errors/backtraces from the system logs

N/A

**Comment by allanjude** [comment]
You explicitly overrode it and set encryption=off...

```
$ zfs create -o encryption=aes-256-gcm -o compression=lz4 -o keyformat=passphrase -o keylocation=prompt zstore/test/encrypted
Enter passphrase:
Re-enter passphrase:
$ zfs create zstore/test/encrypted/child
$ zfs create zstore/test/encrypted/child/grandchild
$ zfs create -o encryption=off -o compression=gzip zstore/test/encrypted/child/unencrypted
$ zfs get -r encryption,compression zstore/test/encrypted
NAME                                     PROPERTY     VALUE           SOURCE
zstore/test/encrypted                    encryption   aes-256-gcm     -
zstore/test/encrypted                    compression  lz4             local
zstore/test/encrypted/child              encryption   aes-256-gcm     -
zstore/test/encrypted/child              compression  lz4             inherited from zstore/test/encrypted
zstore/test/encrypted/child/grandchild   encryption   aes-256-gcm     -
zstore/test/encrypted/child/grandchild   compression  lz4             inherited from zstore/test/encrypted
zstore/test/encrypted/child/unencrypted  encryption   off             default
zstore/test/encrypted/child/unencrypted  compression  gzip            local
```

The source value is not set for encryption, but it does 'inherit' correctly.

**Comment by directionless** [comment]
> You explicitly overrode it and set encryption=off...

Oh! I'm not sure I'm getting the details right. Extending my testing:
```shell
sudo openssl rand -out /root/password 32
sudo zpool create -O mountpoint=none \
  -O encryption=aes-256-gcm -O keyformat=raw -O keylocation=file:///root/password \
  tank-enc /dev/sdb1
sudo zfs create -o encryption=off tank-enc/ds-clear -o mountpoint=/zfs/tank-enc/ds-clear
sudo zfs create tank-enc/ds-clear2 -o mountpoint=/zfs/tank-enc/ds-clear2

seph@seph-linux-disk-encryption-test:~$ zfs get encryption,encryptionroot tank-enc tank-enc/ds-clear  tank-enc/ds-clear2
NAME                PROPERTY        VALUE        SOURCE
tank-enc            encryption      aes-256-gcm  -
tank-enc            encryptionroot  tank-enc     -
tank-enc/ds-clear   encryption      off          default
tank-enc/ds-clear   encryptionroot  -            -
tank-enc/ds-clear2  encryption      aes-256-gcm  -
tank-enc/ds-clear2  encryptionroot  tank-enc     -
```

So that seems correct.

But I'm confused about whether or not `tank-enc/ds-clear` is encrypted. I had naively assumed that any children, regardless of their encryption settings, would be encrypted if the underlying pool was.

**Comment by allanjude** [comment]
The 'encryption root' is the key. You can have multiple different keys, this is what makes ZFS encryption more powerful than regular full-disk encryption. You can unload the key for tank-enc, and still have the key for 'tank-other' loaded, and only the loaded files are accessible

**Comment by directionless** [comment]
That makes sense. So if I understand this correctly, encryption can be applied at one or more of the nested layers. This allows volume to have greater key controls, if needed. `zfs get` displays these properties for the given dataset.

So maybe I'm asking the wrong question. For a given data set, is there a way for me to tell if it's encrypted at rest? From my understanding here, I'd need to traverse up the layers until I found one that was encrypted.

**Comment by allanjude** [comment]
If it is encrypted, it will have `encryption=on` and if it has `encryption=off` then it is NOT encrypted.
You can tell which KEY it is using, by examining the `encryptionroot`

If a key is unloaded (meaning the data is truly at-rest), then the filesystem cannot be mounted (that requires the key)

**Comment by directionless** [comment]
I'm still kinda confused. 

In the original example, is `tank-enc/ds-clear` encrypted at rest? I've been assuming it is, and I'm trying to understand how to determine whether a given dataset is encrypted. It sounds like I cannot just look at the `encryption` setting, and I need to examine all the parents ones as well.

**Comment by rincebrain** [comment]
The answer above says "if encryption is set to not-off, it's encrypted; if it's off, it's not". Where are you getting "I can't trust that property"?

**Comment by directionless** [comment]
I am probably mis-applying common sense. I had thought that a pool being encrypted, _must_ mean that the datasets inside it are also encrypted. But experimenting, I see that's not the case.

So, setting encryption on the pool does not encrypt the pool, it specifies a setting that will be inherited by datasets in the pool. (Unless they set otherwise). 

In my above example, `tank-enc/ds-clear` is not encrypted, and I can mount it without keys loaded:
```
seph@seph-linux-disk-encryption-test:~$ sudo zfs unmount -a
seph@seph-linux-disk-encryption-test:~$ sudo zfs unload-key -a
seph@seph-linux-disk-encryption-test:~$ sudo zfs mount tank-enc/ds-clear
seph@seph-linux-disk-encryption-test:~$ ls /zfs/tank-enc/ds-clear
inherited
seph@seph-linux-disk-encryption-test:~$ 
```

I think this answers me question. I don't know if there's something that could be clarified in the documentation. This is, perhaps, what the "logically nested" part means -- properties are inherited in a tree, but there is no deeper mingling.

Thank you for helping me work through it
