### ISSUE TITLE
Wording regarding an error importing zfs pool

### ISSUE THREAD

**Issue by hetzbh** [openzfs/zfs#12199]
Hi,
The following issue appears in ZFS 0.8.x regardless on any Linux distribution..

I have a RAID card which hosts a ZFS pool and the system boots from a SATA disk using an ext4 partition.

Today, after upgrading kernel and rebooting, zfs didn't import my pool, and only showed an error "cannot import metadata is corrupted"

After trying to check my system, it seems that the disks from the RAID card are not recognized by the OS, due to an issue with mpt3sas kernel module. After fixing the mpt3sas kernel module issue, the pool was imported successfully without any problem.

If I may suggest something: in the import section of ZFS, it should actually check if the cache if available and if not, show a message that "Cache is not available, are the disks online?" instead of showing a message about corruption.

**Comment by rincebrain** [comment]
#8175 #8411 for prior discussion.
