### ISSUE TITLE
More selective deduplication (e.g. only xattrs, or only small blocks)

### ISSUE THREAD

**Issue by akorn** [openzfs/zfs#12203]
I have a backup server I copy millions of files to, using `rsync --fake-super`.

This results in rsync storing some metadata for each file in an xattr called `user.rsync.%stat`, whose contents happens to be identical for many of my files. I estimate millions of such xattrs with identical content, each taking up a few dozen bytes.

There are many large files (such as tiff images, >16MB) which are not efficiently deduplicatable, but also many small ones (<16k) that would be.

I imagine it might be worthwhile to have a feature like `special_small_blocks` for dedup, e.g. `dedup_small_blocks`. Then again, I'm not sure what the performance impact would be (e.g. if having the xattrs dedupped would be better or worse than writing each instance out individually), so maybe this is a stupid idea; just throwing it out there.

**Comment by amotin** [comment]
The combination of dedup and small blocks makes me shiver.  If the blocks appear unique it may so much inflate the dedup table that it become dangerous or unacceptably slow.  For small blocks and xattrs I would let it be handled by compression, embedded blocks and/or xattr=sa.

**Comment by akorn** [comment]
I already use `xattr=sa`. So you're saying that deduplicating those millions of identical xattrs wouldn't make sense? Across the entire backup there might be at most a thousand different-valued xattrs, each with a million or more instances. (I could count them, but it would take a while.)

I have "lots" of RAM, l2arc on SSD as well as a special allocation class vdev on SSD, so I naïvely I assumed the performance hit wouldn't be so bad. A growing DDT would have to be weighed against a worse cache hit ratio for calls like `lgetxattr()` -- if the xattrs were dedupped, `lgetxattr()` would, I assume, involve less I/O than without dedup. Can you predict that the result would always be worse with dedpulication? (I'll take your word for it.)

**Comment by bghira** [comment]
curious why the native special vdev doesn't work for storing your metadata? instead of storing stats in a file like this.

**Comment by akorn** [comment]
> curious why the native special vdev doesn't work for storing your metadata? instead of storing stats in a file like this.

I'm not sure I understand your question.

I assume the xattrs rsync creates go to the special vdev anyway (and incidentally take up far more space there than necessary). What "stats in a file" do you mean?

**Comment by amotin** [comment]
With 'xattr=sa' the xattr should be stored in expanded dnodes, not as separate blocks.  It should greatly reduce the overheads, but I suppose it won't be dedupable after that.

**Comment by bghira** [comment]
> This results in rsync storing some metadata for each file in an xattr called user.rsync.%stat, whose contents happens to be identical for many of my files. I estimate millions of such xattrs with identical content, each taking up a few dozen bytes.

sorry, i mis-read this thinking it makes a file for each one. my brain added "in a" before "file" and somehow unlinked xattr from the concept. my apologies.

**Comment by behlendorf** [comment]
To follow up on what @amotin said, it sounds like your xattrs are small enough that they'll be stored with the dnode since you've set `xattr=sa`.  You can use `zdb -ddddd <pool/dataset> <object>` to verify that's the case, like so:

```
zdb -ddddd tank/fs $(stat /tank/fs/file --format=%i)
```

You'll want to check the `dnode_flags` and see if the `SPILL_BLKPTR` flag is set.  This indicates an external block was needed since all the xattrs couldn't fit in the dnode area.  In this case you can increase the dnode size by setting `dnodesize=1k`.  It'll only apply to new files, but it's preferable since it then doesn't cost you any additional space and because the xattrs will be read in on first access along with the other basic metadata (mtime, atime, size, etc).

**Comment by akorn** [comment]
My `dnodesize` is `auto` and `SPILL_BLKPTR` is not set; one such `user.rsync.%stat` xattr takes up 84 bytes, which is in the same ballpark as the number of bits in a dedup hash, so that space savings, even if they were achievable, would be negligible.

Since, if I understand you correctly, `lgetxattr()` is "free" after `fstat()` (it doesn't involve additional I/O), I suppose there is nothing to optimize further. Thanks and closing report.
