### ISSUE TITLE
zfs diff generates incorrect output for modified files

### ISSUE THREAD

**Issue by Dave--G** [openzfs/zfs#12219]
Using zfs 2.0.2 on Ubuntu 21.04, according to the documentation running "zfs diff filesystem@snap1 filesystem@snap2" should indicate a changed file with output : "M" in key-1 followed by /path/to/file in key-2.

Instead zfs diff generates "-" in key-1, /path/to/file in key-2, then "+" in key-1, /path/to/file in key-2.
The file is being shown as deleted and added instead of modified.

Often these are not adjacent in the output but "| sort -k 2" (pipe to sort on the 2ns column) cleans this up.

Related info:
1.  The files being updated are via a virtio-fs share to a Windows application running in a VM.  The Windows application is likely rewriting the entire file (a proprietary CAD app, likely encrypted contents) however this shouldn't matter.
2. This may be an unrelated issue but I'm also seeing a lot of possibly related /path/to/(on_delete_queue) in the same output.  "(on_delete_queue)" is being generated by zfs diff.

**Comment by rincebrain** [comment]
Can you examine `ls -i [path to file demonstrating this in old snapshot] [path to file in new snapshot]` and confirm they're the same value? If they're not, then it's most likely the case that the file was indeed created anew and renamed into place by something.

**Comment by Dave--G** [comment]
Yes the files are on a different inodes.  This may be 'as designed' although for the sake of snapshot-snapshot comparison, inode # probably isn't so useful in many use-cases.  Suggest snapshot(hash)-snapshot(hash) is more relevant & consistent than snapshot(inode)-snapshot(inode) for most purposes.

This may be an enhancement.  I've scripted a workaround that merges -/+ into M but it's a slow hack.

**Comment by Dave--G** [comment]
(Just skimming code I'm not familiar with here) the fix looks like a trivial -2+1 change on line 336 of libzfs_diff.c.  Just change the hard-coded ZDIFF_REMOVED/ZDIFF_ADDED outputs to a single ZDIFF_MODFIED output.

**Comment by rincebrain** [comment]
I am not an expert on this code, but I believe that segment is handling "the object numbered 123 in fromsnap is not the same object as the object numbered 123 in tosnap", not "the object named 1/2/3 in fromsnap is not the same as the object named 1/2/3 in tosnap" - the latter would, I think, be a fair bit more overhead to handle the way you desire.
