### ISSUE TITLE
Run CI tests with AddressSanitizer

### ISSUE THREAD

**Issue by ahrens** [openzfs/zfs#12216]
### Describe the feature would like to see added to OpenZFS

OpenZFS supports building the userland components (including libzpool, ztest, zdb) with AddressSanitizer support, by running `./configure --enable-asan`.  It would be great if the automated tests ran zloop with this flag.  It might even make sense for debug builds to always use asan.

### How will this feature improve OpenZFS?

Helps us find bugs sooner, pre-integration.  e.g. https://github.com/openzfs/zfs/issues/12215, https://github.com/openzfs/zfs/pull/10193, https://github.com/openzfs/zfs/pull/9706, #12339

**Comment by szubersk** [comment]
@ahrens I think we can close this issue.

**Comment by behlendorf** [comment]
Right, thanks!
