### ISSUE TITLE
ZFS 0.8.6 build failure on CentOS 8 Stream 4.18.0-310.el8.x86_64

### ISSUE THREAD

**Issue by arcasinky** [openzfs/zfs#12234]
System specs:  CentOS 8 Stream x86-64
Kernel:  4.18.0-310.el8.x86_64
ZFS release:  0.8.6-1.el8

RedHat pushed 4.18.0-310 to CentOS 8 Stream sometime in the last couple days.  Unfortunately, this breaks ZFS dkms:

    CC [M]  /var/lib/dkms/zfs/0.8.6/build/module/spl/spl-err.o
    In file included from /var/lib/dkms/zfs/0.8.6/build/include/sys/dmu.h:848,
                 from /var/lib/dkms/zfs/0.8.6/build/include/sys/spa.h:44,
                 from /var/lib/dkms/zfs/0.8.6/build/include/sys/zio.h:36,
                 from /var/lib/dkms/zfs/0.8.6/build/module/zfs/abd.c:121:
    /var/lib/dkms/zfs/0.8.6/build/include/linux/blkdev_compat.h: In function ���get_disk_and_module���:
    /var/lib/dkms/zfs/0.8.6/build/include/linux/blkdev_compat.h:151:10: error: implicit declaration of function ���get_disk���; did you mean ���put_disk���? [-Werror=implicit-function-declaration]
    return (get_disk(disk));

**Comment by arcasinky** [comment]
(Note: unlike #12198 that I opened for a machine running CentOS 8, this problem occurs on a machine running CentOS 8 Stream)

**Comment by rincebrain** [comment]
Looks like in git, c449d4b06d1a6f26e3e422a845bff99a52b70000 dropped the use of that function entirely. 

I can confirm 0.8.6 fails this way (as does, unsurprisingly, the zfs-0.8.7-staging branch right now.)

2.0.4 should (and does, on my 8 Stream box running 310) build fine.

One hopes that either an 0.8.7 will get cut or 2.0.X will get bumped to the main repo by 2.1 coming out.

**Comment by arcasinky** [comment]
I concur.  2.0.4 builds successfully on Stream 8 with that kernel.  I'll just switch to 2.0.4 on this Stream 8 machine.

That leads to the following question:  This Stream 8 machine acts as a backup machine that receives, via syncoid, snapshots from our primary machine that's still at the 0.8.6 level.  Would you anticipate that version difference to cause  problems?

**Comment by rincebrain** [comment]
Unless you have incompatible feature flags and explicitly choose send flags that incorporate them from a newer to an older version (e.g. using compression=zstd and send -c or -p), I believe the expectation is that everything will work fine - and if you find a violation of that expectation, look for an existing one, then file a bug.

**Comment by gilgwath** [comment]
Last Tue (15.06.21) I have tried installing the zfs package from zfs-testing, after I read here that 0.8.6 from the zfs repository was confirmed to be busted on kernel  4.18.0-310.el8.x86_64. It tried installing zfs-0.8.7 from zfs-testing and as reported here before, DKMS failed. I tried again yesterday, and it installed zfs-2.0.4 successfully. :-)

Thank you for moving a working version into zfs-testing!

**Comment by zorinlynx** [comment]
> One hopes that either an 0.8.7 will get cut or 2.0.X will get bumped to the main repo by 2.1 coming out.

Does anyone know what the hold up on this is? Are there still outstanding issues with 2.0.x?

I've been half-tempted to move to the zfs-testing repo to upgrade to 2.x but figure there must be a reason why it's been held back this long. In fact this is the longest a new release has been held back in the time I've been running OpenZFS!

**Comment by behlendorf** [comment]
OpenZFS 2.0.5 was released today and a new repository for CentOS 8.4 was created with the 2.0.5 packages in the main repository.  

The zfs-testing repository is perhaps a bit incorrectly named (and explained), it should probably called something like zfs-next.  It contains the version of OpenZFS we intend to ship for the next CentOS/RHEL minor release, in this case 8.4.

**Comment by carlwgeorge** [comment]
zfs-next would align nicely with [epel-next](https://fedoraproject.org/wiki/EPEL_Next), which was recently [announced](https://lists.fedoraproject.org/archives/list/epel-announce@lists.fedoraproject.org/thread/UYBLBN7WRCGKZZ3KY2SDFU63BDRD5FDL/) and serves a similar purpose.

**Comment by behlendorf** [comment]
Closing.  The 2.1.5 packages are the current supported release for CentOS 8 stream.  I agree a `zfs-next` repository would be a nice way to track provide packages for it.
