### ISSUE TITLE
zfs issue with 32bit on arm - debian Buster

### ISSUE THREAD

**Issue by heapxor** [openzfs/zfs#12243]
Hello,
 i made work zfs on armbian ubuntu focal; Linux bananapi 5.4.88-sunxi; zfs-dkm 2.0x

Trying to achieve similar functionality on armbian debian buster; while installing zfs-dkms its aborting with message>
Ok, aborting, since ZFS is not designed for 32-bit kernels.

Any idea what kind of issue it might be? Thanks

``
root@bananapi:~# apt install --reinstall zfs-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 6 not upgraded.
Need to get 2,231 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster-backports/contrib armhf zfs-dkms all 2.0.3-1~bpo10+1 [2,231 kB]
Fetched 2,231 kB in 1s (3,027 kB/s)
Preconfiguring packages ...
(Reading database ... 69467 files and directories currently installed.)
Preparing to unpack .../zfs-dkms_2.0.3-1~bpo10+1_all.deb ...
Unpacking zfs-dkms (2.0.3-1~bpo10+1) over (2.0.3-1~bpo10+1) ...
Setting up zfs-dkms (2.0.3-1~bpo10+1) ...
Ok, aborting, since ZFS is not designed for 32-bit kernels.
Processing triggers for initramfs-tools (0.133+deb10u1) ...
update-initramfs: Generating /boot/initrd.img-5.4.88-sunxi
update-initramfs: Converting to u-boot format
root@bananapi:~# uname -a
Linux bananapi 5.4.88-sunxi #21.05.1 SMP Thu May 6 20:18:43 UTC 2021 armv7l GNU/Linux
root@bananapi:~#
``

**Comment by rincebrain** [comment]
At least on Debian, installing the ZFS packages from apt pops an interactive "danger: installing on 32-bit, continue y/n", and probably defaults to n if non-interactive.

More generally, problems with the distro-provided packages should probably go against that distro's bugtracker for the packages.

**Comment by heapxor** [comment]
@rincebrain you were right, thank you..

echo "zfs-dkms zfs-dkms/stop-build-for-32bit-kernel boolean false" | debconf-set-selections

fixed
