### ISSUE TITLE
kmod packages for EL8.4

### ISSUE THREAD

**Issue by ecnepsnai** [openzfs/zfs#12268]
_My apologies if this has been brought up before, but I haven't been able to locate a EL8.4 specific request, only requests about CentOS Stream (which is different)_

Redhat released RHEL 8.4 and CentOS (as well as Rocky Linux) have also released their editions. Could we get a patch update to the 0.8.x branch with kmod packages?

Thanks!

**Comment by behlendorf** [comment]
Packages for RHEL 8.4 (zfs 2.0.5) have been added to the repository, you'll want to use the new 8_4 repository.

https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html
