### ISSUE TITLE
#12145 breaks support for x32

### ISSUE THREAD

**Issue by hvdijk** [openzfs/zfs#12269]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| N/A
Distribution Version	| N/A
Linux Kernel	| 5.12.12
Architecture	| x86_64 (x32)
ZFS Version	| 2.1.0-rc7
SPL Version	| 

### Describe the problem you're observing

```
make[3]: Entering directory '/home/harald/zfs/lib/libzpool'
  CCLD     libzpool.la
ld.lld: error: undefined symbol: atomic_load_64
>>> referenced by aggsum.c:119 (../../module/zfs/aggsum.c:119)
>>>               .libs/aggsum.o:(aggsum_lower_bound)
>>> referenced by aggsum.c:125 (../../module/zfs/aggsum.c:125)
>>>               .libs/aggsum.o:(aggsum_upper_bound)
>>> referenced by aggsum.c:218 (../../module/zfs/aggsum.c:218)
>>>               .libs/aggsum.o:(aggsum_compare)
>>> referenced 1 more times

ld.lld: error: undefined symbol: atomic_store_64
>>> referenced by aggsum.c:157 (../../module/zfs/aggsum.c:157)
>>>               .libs/aggsum.o:(aggsum_value)
>>> referenced by aggsum.c:158 (../../module/zfs/aggsum.c:158)
>>>               .libs/aggsum.o:(aggsum_value)
>>> referenced by aggsum.c:199 (../../module/zfs/aggsum.c:199)
>>>               .libs/aggsum.o:(aggsum_add)
>>> referenced 3 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:1115: libzpool.la] Error 1
make[3]: Leaving directory '/home/harald/zfs/lib/libzpool'
make[2]: *** [Makefile:701: all-recursive] Error 1
make[2]: Leaving directory '/home/harald/zfs/lib'
make[1]: *** [Makefile:906: all-recursive] Error 1
make[1]: Leaving directory '/home/harald/zfs'
make: *** [Makefile:767: all] Error 2
```

### Describe how to reproduce the problem

Build with plain `./configure && make` on an x32 system.

### Include any warning/errors/backtraces from the system logs

N/A

The problem is that on x32, `_LP64` is not defined so `atomic_load_64` gets declared as a function, but `atomic.c` does not get to define that function because x32 is still x86_64, so the assembly version `lib/libspl/asm-x86_64/atomic.S` is picked over `lib/libspl/asm-generic/atomic.c`.

For x32, it should be fine to use the same macro using `volatile` that also gets defined for LP64 mode.

**Comment by hvdijk** [comment]
I suspect plain old x86 may be broken as well, since it also uses an assembly version and it also does not define `_LP64`.

For x32, the below makes the build complete successfully. I will submit this as a PR once I can do some proper testing.

For x86, I will try to confirm whether there is really a problem there and give details if there is.

```diff
--- a/lib/libspl/include/atomic.h
+++ b/lib/libspl/include/atomic.h
@@ -256,7 +256,7 @@ extern uint64_t atomic_swap_64(volatile uint64_t *, uint64_t);
 #define        atomic_load_8(p)        (*(volatile uint8_t *)(p))
 #define        atomic_load_16(p)       (*(volatile uint16_t *)(p))
 #define        atomic_load_32(p)       (*(volatile uint32_t *)(p))
-#ifdef _LP64
+#if defined(_LP64) || defined(__x86_64__)
 #define        atomic_load_64(p)       (*(volatile uint64_t *)(p))
 #elif defined(_INT64_TYPE)
 extern uint64_t atomic_load_64(volatile uint64_t *);
@@ -281,7 +281,7 @@ extern uint64_t atomic_load_64(volatile uint64_t *);
        (*(volatile uint16_t *)(p) = (uint16_t)(v))
 #define        atomic_store_32(p, v)           \
        (*(volatile uint32_t *)(p) = (uint32_t)(v))
-#ifdef _LP64
+#if defined(_LP64) || defined(__x86_64__)
 #define        atomic_store_64(p, v)           \
        (*(volatile uint64_t *)(p) = (uint64_t)(v))
 #elif defined(_INT64_TYPE)
```

**Comment by hvdijk** [comment]
It looks like the x86 breakage is known and handled as #12244 in a way that should fix things for x32 too, though possibly in a suboptimal way. Will recheck with the fix for that to make sure.

**Comment by behlendorf** [comment]
@hvdijk you can pull the head of the zfs-2.1-release branch, we've applied the missing patch there.

**Comment by hvdijk** [comment]
Can confirm the build now works, thanks. In theory the change still makes sense, the `volatile uint64_t` approach would be an improvement for x32, in practice it doesn't matter as these definitions of `atomic_load_64` and `atomic_store_64` are entirely unused: `atomic_load_64` and `atomic_store_64` are only used in `module/zfs/aggsum.c`, which for Linux picks up the definitions from `include/os/linux/spl/sys/atomic.h` instead, and I am not aware of non-Linux kernels supporting x32.
