### ISSUE TITLE
ZFS 2.0 support?

### ISSUE THREAD

**Issue by ThomasLohmann** [openzfs/zfs#12305]
Hi everyone,

do you have any plans to support ZFS version 2.0+ asap? A couple of useful features have been added to this version and the current OpenEBS ZFS Driver still only supports version 0.8. Please, see the following link for more details: https://github.com/openzfs/zfs/releases/tag/zfs-2.0.0

Best regards,
Thomas

**Comment by mskarbek** [comment]
You posted in the wrong issue board. :)

**Comment by ThomasLohmann** [comment]
Oh I see. My bad :)!

I will close this issue.
