### ISSUE TITLE
arc_summary shows L2ARC Write Faulted

### ISSUE THREAD

**Issue by Ryushin** [openzfs/zfs#12304]
So arc_summary showing a Faulted error for what I believe is normal operation:
```
L2ARC writes:
        Writes sent:                                  FAULTED     561.1k
        Done ratio:                                   100.0 %     561.1k
        Error ratio:                                    0.0 %          0
```

Line 748 in arc_summary is the cause of this:
```
if arc_stats['l2_writes_done'] != arc_stats['l2_writes_sent']:
        prt_i2('Writes sent:', 'FAULTED', f_hits(arc_stats['l2_writes_sent']))
```

Running a loop to check the writes sent and done doesn't show a match about 1 in five and one is incremented by 1 over the other.
```
while :;do cat /proc/spl/kstat/zfs/arcstats | egrep "l2_writes_sent|l2_writes_done";echo;sleep 1;done
l2_writes_sent                  4    561873
l2_writes_done                  4    561873

l2_writes_sent                  4    561875
l2_writes_done                  4    561875

l2_writes_sent                  4    561877
l2_writes_done                  4    561877

l2_writes_sent                  4    561878
l2_writes_done                  4    561878

l2_writes_sent                  4    561883
l2_writes_done                  4    561882

l2_writes_sent                  4    561884
l2_writes_done                  4    561884
```

I have six 15.4TB NVME devices that are acting as L2ARC for a 1.6PB pool.

**Comment by bghira** [comment]
wow you must have a _lot_ of memory for 15.4TB of L2ARC to be useful, considering how much space the hdr take up.

**Comment by Ryushin** [comment]
System has 512GB of memory with 416GB set for zfs_arc_max.  System as 232 hard drives in the pool the the six NVME drives for L2ARC.  Record size is 1M.  I estimated 16GB of RAM would be needed for the L2ARC.

**Comment by Ryushin** [comment]
This is still occurring as of version 2.1.5

**Comment by amotin** [comment]
It is indeed a minor cosmetic bug.  I've opened the PR to fix it.
