### ISSUE TITLE
Zlib may not be able to decompress some data compressed using QAT

### ISSUE THREAD

**Issue by hedongzhang** [openzfs/zfs#12317]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| redhat
Distribution Version	| 7.8
Linux Kernel	| any
Architecture	| x86
ZFS Version	| zfs-2.1
SPL Version	| 

### Describe the problem you're observing
We used QAT compression data blocks. When we did not use QAT cards, we found that several data blocks could not be decompressed using zlib. At first, we thought the data was corrupted. But the test found that the QAT card can be normally decompressed, the data seems to be no problem, the problem is the checksum(ADLER32) of last four byte. Then we queried the QAT API and found that the CpaDcGeneratefooter function that calculates the checksum code does not support the CPA_DC_STATELESS mode. ZFS uses the CPA_DC_STATELESS mode of the QAT card. So we think that might be a problem.

```c
//qat_compress.c 195 line
		sd.sessState = CPA_DC_STATELESS;
		sd.deflateWindowSize = 7;
		sd.checksum = CPA_DC_ADLER32;

//qat_compress.c 440 line
		status = cpaDcGenerateFooter(session_handle,
		    flat_buf_dst, &dc_results);
		if (status != CPA_STATUS_SUCCESS)
			goto fail;
```

[QAT Data Compression API page:61)](https://01.org/sites/default/files/downloads//apidocdcqadcapiv212public.pdf)

**Comment by cfzhu** [comment]
Hi Hedong @hedongzhang , As we discussed offline, this was a know issue, and was fixed by PR https://github.com/openzfs/zfs/pull/7338,  Could you close this issue?
