### ISSUE TITLE
Unable to create dRAID vdevs on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by chong601** [openzfs/zfs#12324]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04 LTS
Linux Kernel	| 5.4.0-77-generic/5.8.0-59-generic
Architecture	| x86-64
ZFS Version	| 2.1.0-1
SPL Version	| 2.1.0-1

### Describe the problem you're observing
I wanted to try out dRAID as part of my storage system since the release of 2.1.0 happened yesterday and I'm unable to create dRAID pool on Ubuntu 20.04 LTS on non-HWE and HWE kernels.
### Describe how to reproduce the problem
Follow the steps defined in [here](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#debian-and-ubuntu) to create a Ubuntu DKMS installation and create a dRAID pool.

Expected result: A dRAID pool is created
Actual result: An error message `cannot create 'zfs-draid': dRAID vdevs are unsupported by the kernel` is printed when creating a dRAID pool
### Include any warning/errors/backtraces from the system logs
```
chong601@chong601-r710:~$ sudo zpool create -o ashift=12 -O compression=lz4 -O xattr=sa 
-O normalization=formD -O atime=off -O relatime=on zfs-draid draid1 
scsi-SATA_ST9500530NS_9SP16EK2-part3 scsi-SATA_ST9500530NS_9SP199SF-part3 scsi-SATA_ST9500530NS_9SP172KF-part3
scsi-SATA_ST9500530NS_9SP1JDJX-part3 scsi-SATA_ST9500530NS_9SP17CKZ-part3 scsi-SATA_ST9500530NS_9SP1CCYV-part3
cannot create 'zfs-draid': dRAID vdevs are unsupported by the kernel
```
No additional warnings/errors/backtraces from system logs were found.

**Comment by rincebrain** [comment]
If you already had ZFS kernel modules loaded, and install newer ones, I don't think anything involved is going to forcibly unload the old ones.

In addition, on at least Ubuntu, [there's an additional gotcha about installing custom ZFS modules](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html#install).

So check `zpool version`, confirm that zfs-kmod is indeed not reporting 2.1.0, correct the above if you haven't already, then unload and reload the modules.

If it does report the same version, then this becomes more exciting.

**Comment by chong601** [comment]
Ah thanks for the heads up! The zfs-kmod does report `zfs-kmod-0.8.4-1ubuntu11.2`
I'll go for a system reinstall and try again (the OS itself has a few issues unrelated to this issue).

**Comment by chong601** [comment]
Issue resolved!

I have to unload the distribution-provided ZFS module before installing the zfs-dkms packages.
```
chong601@chong601-r710-v2:~$ zpool status
  pool: zfs-draid
 state: ONLINE
config:

        NAME                                      STATE     READ WRITE CKSUM
        zfs-draid                                 ONLINE       0     0     0
          draid1:5d:6c:0s-0                       ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP16EK2-part3  ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP199SF-part3  ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP172KF-part3  ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP1JDJX-part3  ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP17CKZ-part3  ONLINE       0     0     0
            scsi-SATA_ST9500530NS_9SP1CCYV-part3  ONLINE       0     0     0

errors: No known data errors
chong601@chong601-r710-v2:~$ zpool version
zfs-2.1.0-1
zfs-kmod-2.1.0-1
chong601@chong601-r710-v2:~$ modinfo zfs | grep -iw version
version:        2.1.0-1
chong601@chong601-r710-v2:~$ modinfo spl | grep -iw version
version:        2.1.0-1
chong601@chong601-r710-v2:~$ uname -a
Linux chong601-r710-v2 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by temask88** [comment]
> Проблема решена!
> 
> Перед установкой пакетов zfs-dkms мне нужно выгрузить модуль ZFS из дистрибутива.
> 
> ```
> chong601@chong601-r710-v2:~$ zpool status
>   pool: zfs-draid
>  state: ONLINE
> config:
> 
>         NAME                                      STATE     READ WRITE CKSUM
>         zfs-draid                                 ONLINE       0     0     0
>           draid1:5d:6c:0s-0                       ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP16EK2-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP199SF-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP172KF-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP1JDJX-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP17CKZ-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP1CCYV-part3  ONLINE       0     0     0
> 
> errors: No known data errors
> chong601@chong601-r710-v2:~$ zpool version
> zfs-2.1.0-1
> zfs-kmod-2.1.0-1
> chong601@chong601-r710-v2:~$ modinfo zfs | grep -iw version
> version:        2.1.0-1
> chong601@chong601-r710-v2:~$ modinfo spl | grep -iw version
> version:        2.1.0-1
> chong601@chong601-r710-v2:~$ uname -a
> Linux chong601-r710-v2 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> ```

Tell me exactly how you create draid on ubuntu 20.04
I am now also faced with the error - _dRAID vdevs are unsupported by the kernel_
zfs verision outputs:
_zfs-2.1.99-399_g7eebcd2be
zfs-kmod-0.8.3-1ubuntu12.10_

You wrote about unloading zfs modules from the distribution. How to do it?

**Comment by temask88** [comment]
> Issue resolved!
> 
> I have to unload the distribution-provided ZFS module before installing the zfs-dkms packages.
> 
> ```
> chong601@chong601-r710-v2:~$ zpool status
>   pool: zfs-draid
>  state: ONLINE
> config:
> 
>         NAME                                      STATE     READ WRITE CKSUM
>         zfs-draid                                 ONLINE       0     0     0
>           draid1:5d:6c:0s-0                       ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP16EK2-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP199SF-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP172KF-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP1JDJX-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP17CKZ-part3  ONLINE       0     0     0
>             scsi-SATA_ST9500530NS_9SP1CCYV-part3  ONLINE       0     0     0
> 
> errors: No known data errors
> chong601@chong601-r710-v2:~$ zpool version
> zfs-2.1.0-1
> zfs-kmod-2.1.0-1
> chong601@chong601-r710-v2:~$ modinfo zfs | grep -iw version
> version:        2.1.0-1
> chong601@chong601-r710-v2:~$ modinfo spl | grep -iw version
> version:        2.1.0-1
> chong601@chong601-r710-v2:~$ uname -a
> Linux chong601-r710-v2 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> ```

Tell me exactly how you create draid on ubuntu 20.04
I am now also faced with the error - _dRAID vdevs are unsupported by the kernel_
zfs verision outputs:
_zfs-2.1.99-399_g7eebcd2be
zfs-kmod-0.8.3-1ubuntu12.10_

You wrote about unloading zfs modules from the distribution. How to do it?

**Comment by rincebrain** [comment]
ZFS git has a script in scripts/zfs.sh to helpfully unload them.

You can then `modprobe zfs` and be merry, assuming [you've worked around the caveat with Ubuntu](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html#install) and installed the modules already.

**Comment by temask88** [comment]
The result is the same. Do I have to install a clean OS install?

**Comment by temask88** [comment]
before installing zfs 2.1, I installed version zfs-util 0.8.3
