### ISSUE TITLE
recordsize=16M causes "memory exhausted"

### ISSUE THREAD

**Issue by justinpryzby** [openzfs/zfs#12323]
Distribution Name	| centos
Distribution Version	| 7.8.2003
Linux Kernel	| 3.10.0-1160.11.1.el7
Architecture	| x86_64
ZFS Version	| zfs-2.0.5-1
SPL Version	| 2.0.5-1

Copying file to an FS with recordsize=16M triggers errors.
This seems to be true for different compression methods.

```
sudo zfs set compress=gzip recordsize=16M zfs/test2
sudo strace cp /zfs/test/1 /zfs/test2/2
cp: memory exhausted

stat("/zfs/test2/2", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
stat("/zfs/test/1", {st_mode=S_IFREG|0644, st_size=7463305, ...}) = 0
stat("/zfs/test2/2", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("/zfs/test/1", O_RDONLY)           = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=7463305, ...}) = 0
open("/zfs/test2/2", O_WRONLY|O_TRUNC)  = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
mmap(NULL, 244561485824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

**Comment by justinpryzby** [comment]
Looks like this is resolved/avoided by using cp --sparse=always.  The absurd buffer size comes from copy.c:

```
      /* If not making a sparse file, try to use a more-efficient
         buffer size.  */
      if (! make_holes)
        { 
          /* Compute the least common multiple of the input and output
             buffer sizes, adjusting for outlandish values.  */
          size_t blcm_max = MIN (SIZE_MAX, SSIZE_MAX) - buf_alignment_slop;
          size_t blcm = buffer_lcm (io_blksize (src_open_sb), buf_size,
                                    blcm_max);
```
stat("/zfs/test/a-1", {st_dev=makedev(0, 43), st_ino=7728, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=16777216, st_blocks=1, st_size=0, st_atime=1625356863 /* 2021-07-03T17:01:03.620085235-0700
 */, st_atime_nsec=620085235, st_mtime=1625356975 /* 2021-07-03T17:02:55.816134677-0700 */, st_mtime_nsec=816134677, st_ctime=1625356975 /* 2021-07-03T17:02:55.816134677-0700 */, st_ctime_nsec=816134677}) = 0
stat("/zfs/test/1", {st_dev=makedev(0, 43), st_ino=1508, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=7463424, st_blocks=14578, st_size=7463305, st_atime=1625356860 /* 2021-07-03T17:01:00.9281080
14-0700 */, st_atime_nsec=928108014, st_mtime=1625355609 /* 2021-07-03T16:40:09.564544182-0700 */, st_mtime_nsec=564544182, st_ctime=1625355609 /* 2021-07-03T16:40:09.564544182-0700 */, st_ctime_nsec=564544182}) = 0

; lcm(16777216, 7463424)
        244561477632

Maybe ZFS should return a different st_blksize (?)  If not, feel free to close this issue.

**Comment by behlendorf** [comment]
Thanks for investigating this.  We could return a smaller `st_blksize` size here, even if it's not the optimal block size, but this really does seem like a case `cp` should handle better.  Regardless, let's leave this open for now.

**Comment by behlendorf** [comment]
I'm closing this out.  While we could misreport the internal block size for the benefit of `cp` that seems like the wrong way to resolve this.
