### ISSUE TITLE
The Bug Report issue template is very Linux specific

### ISSUE THREAD

**Issue by grahamc** [openzfs/zfs#12338]
The default issue template includes this section of template:

```

### System information
<!--  add version after "|" character -->
Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	|
SPL Version	|
<!--
Commands to find ZFS/SPL versions:
modinfo zfs | grep -iw version
modinfo spl | grep -iw version
-->
```

This is great for Linux users, but not so applicable for other OSes. For example, in #12337 I put in some information about a Joyent machine.

**Comment by nshalman** [comment]
To be fair, illumos isn't quite on OpenZFS just yet, AFAIK. It was just the machine I had at hand and it does exhibit the same bug which I think is useful information. FreeBSD is probably the more important one at this stage.

**Comment by behlendorf** [comment]
Good point, we probably should update to cover both Linux and FreeBSD.  How about something like this.

```
### System information
<!--  add version after "|" character -->
Type | Version/Name
 --- | ---
Distribution Name       |
Distribution Version    |
Kernel Version  |
Architecture    |
OpenZFS Version |
<!--
Command to find OpenZFS version:
zfs version

Commands to find kernel version:
uname -r                # Linux
freebsd-version -r      # FreeBSD
-->
```
