### ISSUE TITLE
zfs 2.1.0 needlessly links in libatomic

### ISSUE THREAD

**Issue by hvdijk** [openzfs/zfs#12345]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	| 5.13.1
Architecture	| x86_64 (x32)
ZFS Version	| 2.1.0
SPL Version	|

### Describe the problem you're observing

zpool fails to start unless libatomic.so is present.

### Describe how to reproduce the problem

Install zfs 2.1.0.

### Include any warning/errors/backtraces from the system logs

N/A

https://github.com/openzfs/zfs/blob/master/config/user-libatomic.m4#L14 claims:

>     dnl # Technically, we could check if the platform *actually* needs -latomic,
>     dnl # or if it has native support for all the intrinsics we use,
>     dnl # but it /really/ doesn't matter, and C11 recommends to always link it.

It really does matter. When using zfs for the root partition, zfs needs to be installed on initramfs. initramfs should be small; it seems silly to force a shared library to be included there that is completely unused.

Workaround: build zfs in a chroot where libatomic.so is not available.

P.S.: The "C11 recommends to always link it" cannot be right, C11 does not acknowledge the existence of any libatomic library. I imagine it is intended to say something else, but I do not quite know what. It would be useful if this could be reworded.

**Comment by behlendorf** [comment]
Thanks for filing this, it does seem like we could be a bit smarter about this.  cc: @nabijaczleweli

**Comment by nabijaczleweli** [comment]
I mean, it's 31k, but I can see how that's an issue in absence of LTO; see #12359

**Comment by hvdijk** [comment]
Thanks, tested on top of 2.1.0 and can confirm it correctly detects that -latomic is not needed on my system, the resulting binaries are the same as when vanilla 2.1.0 is built in a chroot without libatomic.
