### ISSUE TITLE
I can import a pool on two linux machines and on freebsd not

### ISSUE THREAD

**Issue by michaelhmich** [openzfs/zfs#12367]
I have two linux partitions with open-zfs 2.1.99 and on reboot or shutdown it is running a script exporting the pool which is on a second hd, another script runs on login importing the pool, works fine and flawless

now, I have a Frrebsd 13 machine where the disk is perfectly recognized by bios and freebsd as second ada device but zfs or zpool does not find it, as if it wouldn't be there, their zfs version is 2.0 but I guess or hope that has nothing to do, I tried to import with pool name, with /dev.sdb and sdb1, as well as with UID 

are both verions incomptible or where could be the problem?

thank's

**Comment by allanjude** [comment]
So `zpool import` just reports no pools found?
what if you do: `zdb -l /dev/ada1p1` or whatever the device/partition is on FreeBSD?

**Comment by michaelhmich** [comment]
for not getting confused, ada1 is zfs
FreeBSD 13.0-RELEASE
***@***.***:~ % sudo zpool status
 pool: zroot
state: ONLINE
config:

       NAME        STATE     READ WRITE CKSUM
       zroot       ONLINE       0     0     0
         ada1p3    ONLINE       0     0     0




ok, as you asked:

***@***.***:~ % sudo zdb -l ada1p1
failed to unpack label 0
failed to unpack label 1
failed to unpack label 2
failed to unpack label 3


this is the inter changable disk on your command
***@***.***:~ % sudo zdb -l ada2p1
failed to unpack label 0
failed to unpack label 1
failed to unpack label 2
failed to unpack label 3

doesn't matter if I put ada2 or ada2p1

ada0 gives the same result

this is the "prove" from dmesg

ada0 at ata2 bus 0 scbus0 target 0 lun 0
ada0: <WDC WD5000AAKX-003CA0 15.01H15> ATA8-ACS SATA 3.x device
ada0: Serial Number WD-WCAYUEP01916
ada0: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
ada0: 476938MB (976771055 512 byte sectors)

ada1 at ata4 bus 0 scbus2 target 0 lun 0
ada1: <WDC WD1600AABS-00PRA0 05.06H05> ATA-7 SATA 2.x device
ada1: Serial Number WD-WMAP9C839791
ada1: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
ada1: 152626MB (312579695 512 byte sectors)

ada2 at ata5 bus 0 scbus3 target 0 lun 0
ada2: <WDC WD1600AABS-00PRA0 05.06H05> ATA-7 SATA 2.x device
ada2: Serial Number WD-WMAP9C839886
ada2: 300.000MB/s transfers (SATA 2.x, UDMA5, PIO 8192bytes)
ada2: 152626MB (312579695 512 byte sectors)


FDISK from ada0
***@***.***:~ % sudo fdisk /dev/ada0
******* Working on device /dev/ada0 *******
parameters extracted from in-core disklabel are:
cylinders=969018 heads=16 sectors/track=63 (1008 blks/cyl)

Figures below won't work with BIOS for partitions not in cyl 1
parameters to be used for BIOS calculations are:
cylinders=969018 heads=16 sectors/track=63 (1008 blks/cyl)

Media sector size is 512
Warning: BIOS sector numbering starts with sector 1
Information from DOS bootblock is:
The data for partition 1 is:
sysid 131 (0x83),(Linux native)
   start 2048, size 122880000 (60000 Meg), flag 0
       beg: cyl 4/ head 4/ sector 1;
       end: cyl 1023/ head 254/ sector 2
The data for partition 2 is:
sysid 5 (0x05),(Extended DOS)
   start 122882048, size 16384000 (8000 Meg), flag 0
       beg: cyl 481/ head 13/ sector 45;
       end: cyl 476/ head 232/ sector 12
The data for partition 3 is:
sysid 131 (0x83),(Linux native)
   start 139266048, size 737280000 (360000 Meg), flag 0
       beg: cyl 476/ head 232/ sector 13;
       end: cyl 290/ head 119/ sector 21
The data for partition 4 is:
sysid 131 (0x83),(Linux native)
   start 876546048, size 100222017 (48936 Meg), flag 80 (active)
       beg: cyl 290/ head 119/ sector 22;
       end: cyl 384/ head 254/ sector 63


FDISK ada1
***@***.***:~ % sudo fdisk /dev/ada1
******* Working on device /dev/ada1 *******
parameters extracted from in-core disklabel are:
cylinders=310098 heads=16 sectors/track=63 (1008 blks/cyl)

Figures below won't work with BIOS for partitions not in cyl 1
parameters to be used for BIOS calculations are:
cylinders=310098 heads=16 sectors/track=63 (1008 blks/cyl)

Media sector size is 512
Warning: BIOS sector numbering starts with sector 1
Information from DOS bootblock is:
The data for partition 1 is:
sysid 238 (0xee),(EFI GPT)
   start 1, size 312579694 (152626 Meg), flag 0
       beg: cyl 0/ head 0/ sector 2;
       end: cyl 1023/ head 255/ sector 63
The data for partition 2 is:
<UNUSED>
The data for partition 3 is:
<UNUSED>
The data for partition 4 is:
<UNUSED>

FDISK ada2
***@***.***:~ % sudo fdisk /dev/ada2
******* Working on device /dev/ada2 *******
parameters extracted from in-core disklabel are:
cylinders=310098 heads=16 sectors/track=63 (1008 blks/cyl)

Figures below won't work with BIOS for partitions not in cyl 1
parameters to be used for BIOS calculations are:
cylinders=310098 heads=16 sectors/track=63 (1008 blks/cyl)

Media sector size is 512
Warning: BIOS sector numbering starts with sector 1
Information from DOS bootblock is:
The data for partition 1 is:
sysid 238 (0xee),(EFI GPT)
   start 1, size 312579694 (152626 Meg), flag 0
       beg: cyl 1023/ head 255/ sector 63;
       end: cyl 1023/ head 255/ sector 63
The data for partition 2 is:
<UNUSED>
The data for partition 3 is:
<UNUSED>
The data for partition 4 is:
<UNUSED>

all 3 drives are in perfect state, no sector bad or whatever


cheers,
Michael HMich
(17)9.8123.8200
-
C865 F6AF 30AC CE61 D85B C975 8B72 1907 ED40 7B4C

**Comment by allanjude** [comment]
> 
> for not getting confused, ada1 is zfs 

So, you have a pool already imported, called zroot, that is ada1p3.

What is the 2nd pool called? what does `zpool import` say?

On FreeBSD, try `gpart show`

**Comment by michaelhmich** [comment]
let's kill  the freebsd disk first, I have the setup from my mother :) it's a factory setup with root on zfs 

hm@hm-fbsd:~ % df -h
Filesystem            Size    Used   Avail Capacity  Mounted on
zroot/ROOT/default    141G    6,5G    134G     5%    /
devfs                 1,0K    1,0K      0B   100%    /dev
procfs                4,0K    4,0K      0B   100%    /proc
linprocfs             4,0K    4,0K      0B   100%    /compat/linux/proc
linsysfs              4,0K    4,0K      0B   100%    /compat/linux/sys
tmpfs                 2,8G    4,0K    2,8G     0%    /compat/linux/dev/shm
zroot/tmp             134G    144K    134G     0%    /tmp
zroot/var/log         134G    620K    134G     0%    /var/log
zroot/usr/home        136G    1,5G    134G     1%    /usr/home
zroot/usr/ports       134G     96K    134G     0%    /usr/ports
zroot/usr/src         134G     96K    134G     0%    /usr/src
zroot/var/mail        134G    144K    134G     0%    /var/mail
zroot/var/audit       134G     96K    134G     0%    /var/audit
zroot/var/crash       134G     96K    134G     0%    /var/crash
zroot                 134G     96K    134G     0%    /zroot
zroot/var/tmp         134G     96K    134G     0%    /var/tmp
devfs                 1,0K    1,0K      0B   100%    /compat/linux/dev
fdescfs               1,0K    1,0K      0B   100%    /compat/linux/dev/fd
tmpfs                 2,8G    4,0K    2,8G     0%    /compat/linux/dev/shm
-------------------------------------------

this is the disk, zpool zfotos I am not able to import into the above freebsd setup 

hm@hm-fbsd:~ % gpart show /dev/ada2
=>       40  312579616  ada2  GPT  (149G)
         40       2008        - free -  (1.0M)
       2048  312559616     1  apple-zfs  (149G)
  312561664      16384     9  solaris-reserved  (8.0M)
  312578048       1608        - free -  (804K)


hm@hm-fbsd:~ % sudo zpool import -f zfotos
Password:
cannot import 'zfotos': no such pool available  <<<<<-----------

ANY zfs/zpool cmd I use to catch the pool zfotos which is adaXp1 (whole) disk, gives the same answer 

and here also zfs recognized
m@hm-fbsd:~ % sudo gpart list /dev/ada2
Geom name: ada2
modified: false
state: OK
fwheads: 16
fwsectors: 63
last: 312579655
first: 40
entries: 128
scheme: GPT
Providers:
1. Name: ada2p1
   Mediasize: 160030523392 (149G)
   Sectorsize: 512
   Stripesize: 0
   Stripeoffset: 1048576
   Mode: r0w0e0
   efimedia: HD(1,GPT,f9c32eb7-721e-fc41-9b9b-0bf7cda40f47,0x800,0x12a14800)
   rawuuid: f9c32eb7-721e-fc41-9b9b-0bf7cda40f47
   rawtype: 6a898cc3-1dd2-11b2-99a6-080020736631
   label: zfs-db7e5839e630848f
   length: 160030523392
   offset: 1048576
   type: apple-zfs
   index: 1
   end: 312561663
   start: 2048
2. Name: ada2p9
   Mediasize: 8388608 (8.0M)
   Sectorsize: 512
   Stripesize: 0
   Stripeoffset: 160031571968
   Mode: r0w0e0
   efimedia: HD(9,GPT,dc8289f1-138a-5d4c-85fe-3a0ae9579210,0x12a15000,0x4000)
   rawuuid: dc8289f1-138a-5d4c-85fe-3a0ae9579210
   rawtype: 6a945a3b-1dd2-11b2-99a6-080020736631
   label: (null)
   length: 8388608
   offset: 160031571968
   type: solaris-reserved
   index: 9
   end: 312578047
   start: 312561664
Consumers:
1. Name: ada2
   Mediasize: 160040803840 (149G)
   Sectorsize: 512
   Mode: r0w0e0


I found another case but kind of different and the guy wrote changing freebsd zfs to openzfs solved his problem, so that for my case smells like problem because mine is zfsroot and I don't like to make it worther at it is

**Comment by michaelhmich** [comment]
I have a feeling this goes to a dead end, at least for now
don't know why I didn't do it before, but the thing is the freebsd zfs disk is also not seen with openzfs on my Linux
it also will not do any good changing the zfs on freebsd with the openzfs from freebsd ports, it might come out that I can forget the drive ... 
hope that somebody has a good solution because otherwise this issue has none

**Comment by michaelhmich** [comment]
different zpool properties could cause the problem? anyway, here they are: 

[diff-eIZ_zpool_properties.log](https://github.com/openzfs/zfs/files/6830971/diff-eIZ_zpool_properties.log)

**Comment by michaelhmich** [comment]
at least for me I solved this problem and is working for a couple of days so far
the difference between the FBSD zpool and Linux pool was the partition label, fbsd had a clean GPT label and Linux a primary DOS label and a secondary (backup) GPT, which Linux seems to accept but freebsd not, so I fixed this "problem" writing a clean gpt label onto the linux partitions and export/import is working fine now, I can access from both Os's

**Comment by samarulmeu** [comment]
Can you please specify how did you write the GPT label. It seems I am having the same [issue](https://www.reddit.com/r/freebsd/comments/10vvj1y/cannot_import_zfs_pool_from_usb_ssd/).

Thank you!
