### ISSUE TITLE
Potential deadlock due to the unreleased lock

### ISSUE THREAD

**Issue by jenny-cheung** [openzfs/zfs#12371]
Dear Developers:
         First, thank you for your checking! It seems the lock &tpool->tp_mutex without being released in the method` tpool_worker`. Is  there incorrect order between statements` pthread_mutex_unlock(&tpool->tp_mutex)`; and `pthread_cleanup_push(job_cleanup, tpool);.`

https://github.com/openzfs/zfs/blob/60ffc1c460e4cdf3c3ca12c8840fd0675a98ed0d/lib/libtpool/thread_pool.c#L110

https://github.com/openzfs/zfs/blob/60ffc1c460e4cdf3c3ca12c8840fd0675a98ed0d/lib/libtpool/thread_pool.c#L190

Related codes as follows.
```

static void *
tpool_worker(void *arg)
{
                        ...;
			pthread_mutex_unlock(&tpool->tp_mutex);  //here
			pthread_cleanup_push(job_cleanup, tpool);  // here
			free(job);

			sigset_t maskset;
			(void) pthread_sigmask(SIG_SETMASK, NULL, &maskset);

			/*
			 * Call the specified function.
			 */
			func(arg);
			/*
			 * We don't know what this thread has been doing,
			 * so we reset its signal mask and cancellation
			 * state back to the values prior to calling func().
			 */
			(void) pthread_sigmask(SIG_SETMASK, &maskset, NULL);
			(void) pthread_setcanceltype(PTHREAD_CANCEL_DEFERRED,
			    NULL);
			(void) pthread_setcancelstate(PTHREAD_CANCEL_ENABLE,
			    NULL);
			pthread_cleanup_pop(1);
		}
		if (elapsed && tpool->tp_current > tpool->tp_minimum) {
			/*
			 * We timed out and there is no work to be done
			 * and the number of workers exceeds the minimum.
			 * Exit now to reduce the size of the pool.
			 */
			break;
		}
	}
	pthread_cleanup_pop(1);
	return (arg);
}
```

```
static int
create_worker(tpool_t *tpool)
{
	...;
	error = pthread_create(&thread, &tpool->tp_attr, tpool_worker, tpool); // tpool_worker involved here
	(void) pthread_sigmask(SIG_SETMASK, &oset, NULL);
	return (error);
}

```

Best,

**Comment by jenny-cheung** [comment]
Hi, developers @Gelma @behlendorf @nivedita76 @alaviss 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by Gelma** [comment]
Thanks a lot! I can try to reproduce it, but I need a few months. Thanks again

**Comment by jenny-cheung** [comment]
@Gelma Thank you indeed!

**Comment by chrisrd** [comment]
Caveat: I know nothing about this code in particular and very very little about kernel threads in general and I'm just briefly looking at this issue whilst waiting for an unrelated task to finish. That said, at a quick read of the code...

It seems ok to me?

```static void
worker_cleanup(void *arg)
{
...
        pthread_mutex_unlock(&tpool->tp_mutex);
}

static void
job_cleanup(void *arg)
{
...
        pthread_mutex_lock(&tpool->tp_mutex);
...
}

static void *
tpool_worker(void *arg)
{
...
        pthread_mutex_lock(&tpool->tp_mutex);                      <<< locked
        pthread_cleanup_push(worker_cleanup, tpool);               <<< "pushes" an unlock(A)
...
                if ((job = tpool->tp_head) != NULL &&
                    !(tpool->tp_flags & TP_SUSPEND)) {
...
                        pthread_mutex_unlock(&tpool->tp_mutex);    <<< unlocked
                        pthread_cleanup_push(job_cleanup, tpool);  <<< "pushes" lock(B)
...
                        pthread_cleanup_pop(1);                    <<< "pops" lock(B), i.e. now locked 
                }
...
        }
        pthread_cleanup_pop(1);                                    <<< "pops" unlock(A), i.e. now unlocked
        return (arg);
}
```

**Comment by jenny-cheung** [comment]
@chrisrd Hi, thank you for your analysis. I am also not expert and very happen  to discuss.
Yes, it seems the lock is released. However, it is possible for the lock A to be unlocking twice by `pthread_mutex_unlock(&tpool->tp_mutex);` and  `pthread_cleanup_pop(1);` in your example?

**Comment by chrisrd** [comment]
@jenny-cheung Which `pthread_cleanup_pop(1);` are you thinking might unlock for a second time?

The first `pthread_cleanup_pop(1);` (`"pops" lock(B)` in the annotation) is calling `job_cleanup` which was configured by the `lockpthread_cleanup_push(job_cleanup, tpool);` just before it. If you look at `job_cleanup()`, that's doing a lock rather than an unlock.

The second `pthread_cleanup_pop(1);`  (`"pops" lock(A)` in the annotation) is calling `worker_cleanup`, configured by `pthread_cleanup_push(worker_cleanup, tpool);` near the start, and `worker_cleanup()` is doing an unlock.

Note that `pthread_cleanup_push()` doesn't call `worker_cleanup` or `job_cleanup`, it just remembers which function to call, and that function is then called by `pthread_cleanup_pop()`.

**Comment by jenny-cheung** [comment]
@chrisrd Thank you very much! My question is completely solved. It should be a mistake.
