### ISSUE TITLE
Debian Buster ZFS 2.1.0 incorrect package dependency

### ISSUE THREAD

**Issue by turkerali** [openzfs/zfs#12386]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Debian
Distribution Version	| Buster
Kernel Version	|  Linux aet02 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
Architecture	| amd64
OpenZFS Version	| 2.1.0

### Describe the problem you're observing
Normally I use zfs-2.0.3-9~bpo10+1 from Debian Buster backports repository. Today I wanted to try ZFS 2.1.0.
After successful build, I noticed that "libzpool5_2.1.0-1_amd64.deb" depends on "libzfs4linux", but no package
is generated with this name (see list of generated packages below).  I believe this package is zfs 2.0 specific.

List of packages generated:
--------------------
kmod-zfs-4.19.0-17-amd64_2.1.0-1_amd64.deb
kmod-zfs-devel_2.1.0-1_amd64.deb
kmod-zfs-devel-4.19.0-17-amd64_2.1.0-1_amd64.deb
libnvpair3_2.1.0-1_amd64.deb
libuutil3_2.1.0-1_amd64.deb
libzfs5_2.1.0-1_amd64.deb
libzfs5-devel_2.1.0-1_amd64.deb
libzpool5_2.1.0-1_amd64.deb
python3-pyzfs_2.1.0-1_amd64.deb
zfs_2.1.0-1_amd64.deb
zfs-dkms_2.1.0-1_amd64.deb
zfs-dracut_2.1.0-1_amd64.deb
zfs-initramfs_2.1.0-1_amd64.deb
zfs-test_2.1.0-1_amd64.deb

### Describe how to reproduce the problem
wget https://github.com/openzfs/zfs/releases/download/zfs-2.1.0/zfs-2.1.0.tar.gz
tar -xzvf zfs-2.1.0.tar.gz
cd zfs-2.1.0
sh autogen.sh
./configure
make -s -j$(nproc)
make deb

**Comment by John-Appleseed** [comment]
Compiling then installing zfs .deb packages will still product the same error on zfs-2.1.2. How did you resolve this?
```
# zfs compiling steps
git clone https://github.com/openzfs/zfs
cd zfs
git checkout tags/zfs-2.1.2 -b "zfs-2.1.2-branch"
sh autogen.sh
./configure
make deb #example for Debian/Ubuntu
dpkg -i *.deb
```
```
Setting up libzfs5-devel (2.1.2-1) ...
dpkg: dependency problems prevent configuration of libzpool5:
 libzpool5 depends on libzfs4linux (>= 2.0); however:
  Package libzfs4linux is not installed.

dpkg: error processing package libzpool5 (--install):
 dependency problems - leaving unconfigured
Setting up zfs-dracut (2.1.2-1) ...
Setting up zfs-initramfs (2.1.2-1) ...
Setting up zfs-test (2.1.2-1) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Errors were encountered while processing:
 libzpool5
```

**Comment by lucidBrot** [comment]
I am trying to compile and install zfs-2.1.9 on ubuntu 22.04 and I have the same problem. The generated deb files contain `libnvpair3`, but depend on `libnvpair3linux`.  

For example, `dpkg-deb --info ./libzpool5_2.1.9-1_amd64.deb` shows that it depends on:
```
 Depends: libc6 (>= 2.34), libzfs4linux (>= 2.0), zlib1g (>= 1:1.1.4)
 Section: alien
```

The package `libzfs5linux` does exist in the apt repositories, but it is an old version and "replaces/breaks" `libnvpair3`, which should also be installed according to the [instructions](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#dkms-1).

IMO this issue should be reopened, unless there is a documented way to build `libnvpair3linux` that I have not found.

**Comment by lucidBrot** [comment]
By the magic of asking about it on the internet, it has worked now for me!

The trick was to first uninstall any old or new zfs-related packets, then *rebuilding* the debs. Here's an excerpt from my notes:  

> 
> ```
> sudo apt remove libzfs4linux
> ```
> 
> ... that again removes `zfs` and `zfs-test` and `libzpool5`...
> 
> and that triggers a zfs-dkms rebuild?! Which then of course fails.
> 
> ```
> sudo apt remove libzfs4linux zfs-dkms zfs-dracut zfs-initramfs python3-pyzfs libzfs5-devel
> sudo apt autoremove
> ```
>  
> ```
> make -j1 deb-utils deb-dkms
> for file in *.deb; do sudo gdebi -q --non-interactive $file; done
> ```
> 
> And now it works?? 

So it seems that somehow my existing installation had an impact on what the generated debs require. The new deb now, to go with my previous example of `dpkg-deb --info ./libzpool5_2.1.9-1_amd64.deb`, shows that it depends on nothing at all.

**Comment by freqlabs** [comment]
#12322
