### ISSUE TITLE
zfs create: create zvol so slow

### ISSUE THREAD

**Issue by meilihao** [openzfs/zfs#12401]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| ubuntu
Distribution Version	| 16.04.6
Kernel Version	| 4.4.0-177-generic
Architecture	| aarch64
OpenZFS Version	| 0.8.6

### Describe the problem you're observing
`zfs create -V` so slow. This time it took 4 minutes, and there was 29 minutes before, and no error in syslog.

![截图_选择区域_20210720165846](https://user-images.githubusercontent.com/4382586/126294625-622d5b13-941d-4215-9507-86c2c32f4ab3.png)

![截图_选择区域_20210720165954](https://user-images.githubusercontent.com/4382586/126294868-5f85ae9f-b205-4c39-a487-591f087a2583.png)

![截图_选择区域_20210720165643](https://user-images.githubusercontent.com/4382586/126296322-73dacaac-4ad7-4169-aaf5-73ed9794bdc2.png)
![截图_选择区域_20210720175418](https://user-images.githubusercontent.com/4382586/126304318-8778cda5-76b1-4133-868c-b0d0a0e1b910.png)

### Describe how to reproduce the problem
unkown

**Comment by allanjude** [comment]
Can you provide the output of `zpool list -v`
