### ISSUE TITLE
Cannot import zpool after upgrade.

### ISSUE THREAD

**Issue by notacompletemoron** [openzfs/zfs#12403]
This is in direct relation to https://github.com/openzfs/zfs/issues/12322, found this due to a bug report at the Ubuntu Launchpad, and I made a post at https://www.reddit.com/r/AskUbuntu/comments/ooel3v/cant_update_zol_because_of_unmet_dependencies

I was having trouble upgrading the version of zfsutils-linux, and now I cannot access my pool. Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-80-generic x86_64)

--------------------------

sudo zpool import TANK
This pool uses the following feature(s) not supported by this system:
	com.delphix:log_spacemap (Log metaslab changes on a single spacemap and flush them periodically.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'TANK': unsupported version or feature

--------------------------

sudo zpool import -d /dev/disk/by-label/TANK -f
   pool: TANK
     id: 16290916184379626790
  state: UNAVAIL
status: The pool can only be accessed in read-only mode on this system. It
	cannot be accessed in read-write mode because it uses the following
	feature(s) not supported on this system:
	com.delphix:log_spacemap (Log metaslab changes on a single spacemap and flush them periodically.)
action: The pool cannot be imported in read-write mode. Import the pool with
	"-o readonly=on", access the pool on a system that supports the
	required feature(s), or recreate the pool from backup.
 config:

	TANK                                                     UNAVAIL  unsupported feature(s)
	  mirror-0                                               ONLINE
	    wwn-0x5000c500b2ee4433                               ONLINE
	    wwn-0x5000c500b2ee40ac                               ONLINE
	  mirror-1                                               ONLINE
	    TANK                                                 ONLINE
	    wwn-0x5000c500b52621f6                               ONLINE
	  mirror-2                                               ONLINE
	    wwn-0x5000c500b5269466                               ONLINE
	    wwn-0x5000c500b526b774                               ONLINE
	cache
	  ata-Samsung_SSD_860_EVO_250GB_S*-part2
	  ata-Samsung_SSD_860_EVO_250GB_S*-part2
	logs	
	  mirror-3                                               ONLINE
	    ata-Samsung_SSD_860_EVO_250GB_S*-part1  ONLINE
	    ata-Samsung_SSD_860_EVO_250GB_S*-part1  ONLINE

--------------------------

I cannot scrub TANK in RO mode, as expected. Serial numbers redacted.

What is my path to resolution?

EDIT: And I just realized that I have a drive down.

**Comment by notacompletemoron** [comment]
Huh. Looks like I have an old kernel.

zfs version
zfs-2.1.0-0york2~18.04
zfs-kmod-0.8.3-1ubuntu12.10

How do I update the kmod?

**Comment by gertvdijk** [comment]
> I was having trouble upgrading the version of zfsutils-linux

When updating ZFS, you should also update the kernel modules, `zfsutils-linux` is just the 'userspace' tooling.

First of all; how did you attempt the initial upgrade of that packaged? Installed a PPA or something? Then also install the `zfs-dkms` package to build & install the kernel modules.

Verify with `apt policy zfs-dkms zfsutils-linux` for example that your package sources are providing versions that align with each other.
