### ISSUE TITLE
Ubuntu 20.04.2 LTS kernel 5.11.0-25 zfs send | receive broken

### ISSUE THREAD

**Issue by timkgh** [openzfs/zfs#12462]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.2 LTS
Kernel Version	| 5.11.0-25-generic #27~20.04.1-Ubuntu
Architecture	| amd64
OpenZFS Version	| zfs-0.8.3-1ubuntu12.12, zfs-kmod-2.0.2-1ubuntu5

### Describe the problem you're observing
Trying to run `zfs send | receive` and getting an error:
```
# zfs send  'rpool/home'@'autosnap_2020-08-01_00:59:01_monthly' | zfs receive  -s -F 'nas/rpool_backup/home'
cannot receive: failed to read from stream
cannot receive new filesystem stream: dataset does not exist
```
This used to work before the recent Ubuntu kernel update from 5.8 to 5.11

Ubuntu updates that broke it:
```
Upgrade: linux-headers-generic-hwe-20.04:amd64 (5.8.0.63.71~20.04.45, 5.11.0.25.27~20.04.10), linux-
image-generic-hwe-20.04:amd64 (5.8.0.63.71~20.04.45, 5.11.0.25.27~20.04.10), linux-generic-hwe-20.04
:amd64 (5.8.0.63.71~20.04.45, 5.11.0.25.27~20.04.10)
```

Sending the `zfs send` part to a file works, but then sending the file to `zfs receive` also fails. The dump file size seems reasonable but the contents may not be correct.

### Describe how to reproduce the problem
See above.

### Include any warning/errors/backtraces from the system logs

I don't see any related errors in dmesg or /var/log/syslog

**Comment by timkgh** [comment]
Downgrading the kernel to `5.8.0-63-generic #71~20.04.1-Ubuntu` and `zfs-kmod-0.8.4-1ubuntu11.2` makes the problem go away.

**Comment by gdevenyi** [comment]
This should be an ubuntu bug if its ubuntu-packaged zfs.

**Comment by timkgh** [comment]
> This should be an ubuntu bug if its ubuntu-packaged zfs.

_If_ the problem is in zfs-kmod, would Ubuntu be able to fix it?

**Comment by timkgh** [comment]
Reported to Ubuntu also:
https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939177

**Comment by Evernow** [comment]
> would Ubuntu be able to fix it?

They're the ones who package this, not OpenZFS.

**Comment by timkgh** [comment]
I understand, but it sounds like the assumption is a packaging issue and not a code bug. I think it requires a bit more investigation to determine where the bug really is.

**Comment by gdevenyi** [comment]
As per #10333 open-zfs doesn't provide nor support pre-compiled packages for Debian and Ubuntu. Ubuntu has an older packaged version than currently available on the 0.8.x series, so its possible this issue has already been solved on 0.8.x or 2.x series, so you will have to compiled your own to check, or you will have to wait for Ubuntu to address the bug.

**Comment by timkgh** [comment]
Do userspace tools version need to match the kmod version? It might be a compatibility issue between the two: `zfs-0.8.3-1ubuntu12.12` and `zfs-kmod-2.0.2-1ubuntu5`

**Comment by gdevenyi** [comment]
most definitely.

**Comment by mhov** [comment]
As a workaround try dropping the resumable flag `-s` from the `zfs receive`, it was recommended in the ubuntu issue https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1939177.

**Comment by electricboogie** [comment]
FYI, building the userland for HWE kernel (hirsute kernel) fixes this issue.  Ubuntu is packaging a 2.0 zfs module but keeping the 0.8.4 userland.
