### ISSUE TITLE
Sometimes zfs_gitrev.h has wound up wrong in release tarballs

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#12465]
### Describe the problem you're observing
I was wondering why I was seeing "software version unknown" on the import events on my pool, so I looked.
```
$ grep META /tmp/zfs*/include/zfs_gitrev.h
/tmp/zfs-0.8.0/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.0-0-ge34c3ee2fcbb"
/tmp/zfs-0.8.1/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.1-0-gc7d2212"
/tmp/zfs-0.8.2/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.2-0-g1222e92-dirty"
/tmp/zfs-0.8.3/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.3-0-g9bb3d57-dirty"
/tmp/zfs-0.8.4/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.7.0-2489-gf5fd31fa8"
/tmp/zfs-0.8.5/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.5-0-g270c9465b"
/tmp/zfs-0.8.6/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.8.6-0-g9dbe2d626"
/tmp/zfs-2.0.0/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-2.0.0-0-gdcbf84749-dist"
/tmp/zfs-2.0.1/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-2.0.1-0-g32a78e579-dist"
/tmp/zfs-2.0.2/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-2.0.2-0-gd022406a1-dist"
/tmp/zfs-2.0.3/include/zfs_gitrev.h:#define     ZFS_META_GITREV "unknown"
/tmp/zfs-2.0.4/include/zfs_gitrev.h:#define     ZFS_META_GITREV "unknown"
/tmp/zfs-2.0.5/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-0.7.0-3602-gb4f98016c-dist"
/tmp/zfs-2.1.0/include/zfs_gitrev.h:#define     ZFS_META_GITREV "zfs-2.1.0-0-g4f92fe0f5-dist"
```

I don't know how the sausage is made between a tag in git and a tarball on Github, so I leave it as an exercise to whomever handles building these to figure out how to correct it, but it's rather frustrating that when I go to ask "hey, what versions did I import this pool on", I get back "who knows". (In my case, Debian packaged 2.0.3. Womp womp.)

### Describe how to reproduce the problem
Fetch the tarballs, win a prize.

**Comment by rincebrain** [comment]
(If somebody could tag this Component: Packaging that would be swell, since I evidently can not.)

**Comment by tonyhutter** [comment]
Is git installed https://github.com/openzfs/zfs/issues/11811?

**Comment by tonyhutter** [comment]
Nevermind, you're looking at the tarball files, not the ones generated locally.  Anyway, it's a known issue for 2.0.3-4 tarballs.  I'm a little wigged out that the 2.0.5 one is reporting zfs-0.7.0 though... 

I'll assign this to myself to sanity check `zfs_gitrev.h` before release, or update `./scripts/make_gitrev.sh` to add a sanity check.

**Comment by rincebrain** [comment]
You know, I swear I searched before opening this, but didn't turn that up...

Though the fact that it's present in 2.0.5 means I probably would have still opened this anyway, or at least replied there.

(Debian currently does not clobber the upstream zfs_gitrev.h, but had a flaw in the DKMS packages in 0.8.x that did, if I read it right on every dkms build, which is probably why that behavior happened before 2.0.x there.)

**Comment by rincebrain** [comment]
```
$ grep ZFS_META_GITREV zfs*/include/zfs_gitrev.h
zfs-2.0.6/include/zfs_gitrev.h:#define  ZFS_META_GITREV "zfs-0.7.0-3624-g3b440457a-dist"
zfs-2.1.1/include/zfs_gitrev.h:#define  ZFS_META_GITREV "zfs-2.1.1-0-g71c609852-dist"
```

**Comment by tonyhutter** [comment]
I'm going to close this - we've been careful about building the tarballs so that ZFS_META_GITREV is correct, and this has not been an issue for the last couple releases.
