### ISSUE TITLE
vdev_id  command returns SUCCESS when no vdev_id.conf is present

### ISSUE THREAD

**Issue by rugubara** [openzfs/zfs#12485]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| rolling
Kernel Version	| 5.13.11
Architecture	| x86_64
OpenZFS Version	| 2.1.0

### Describe the problem you're observing
The /dev directory is cluttered with strange symlinks /dev/Unable /dev/to /dev/device /dev/open /dev/file ;  directory /dev/dev
### Describe how to reproduce the problem
rename /etc/zfs/vdev_id.conf and let udev process the output from vdev_id error messages

### Include any warning/errors/backtraces from the system logs
I think the culprit are the following lines from vdev_id:
```
if [ ! -r "$CONFIG" ] ; then
	echo "Error: Config file \"$CONFIG\" not found"
	exit 0
fi
```
exit 0 causes udev to process the standard output with error messages in the rule. 
I changed to  ```exit 1``` and run udevadm test -> the strange directories and links went away.

**Comment by gdevenyi** [comment]
Doesn't vdev_id run no matter what and as such needs to succeed if no configuration is active?

**Comment by rugubara** [comment]
Any udev helper must return 0 if it wants udev to process the stdout it produced. It should return non-zero, when stdout contains error messages or some other garbage and the rule should not pay attention.
