### ISSUE TITLE
zfs list -v should display the same top-level device names as zpool status

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#12510]
### Describe the feature would like to see added to OpenZFS

`zpool list -v` should display the same top-level device names as zpool status. In version 2.0.5 and 2.1.0 `zpool list -v`. For example,

```
[root@zfsscratch ~]# zpool status | head
  pool: scratch
 state: ONLINE
config:

	NAME                                   STATE     READ WRITE CKSUM
	scratch                                ONLINE       0     0     0
	  mirror-0                             ONLINE       0     0     0
	    36000402001e022294341c80b00000000  ONLINE       0     0     0
	    36000402004e021e34244d00a00000000  ONLINE       0     0     0
	  mirror-1                             ONLINE       0     0     0

[root@zfsscratch ~]# zpool list -v | head
NAME                                    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
scratch                                 326T  1.16M   326T        -         -     0%     0%  1.00x    ONLINE  -
  mirror                               5.39T    72K  5.39T        -         -     0%  0.00%      -    ONLINE
    36000402001e022294341c80b00000000      -      -      -        -         -      -      -      -    ONLINE
    36000402004e021e34244d00a00000000      -      -      -        -         -      -      -      -    ONLINE
  mirror                               5.39T   100K  5.39T        -         -     0%  0.00%      -    ONLINE
    36000402001e022294341c82700000000      -      -      -        -         -      -      -      -    ONLINE
    36000402004e021e34244d03200000000      -      -      -        -         -      -      -      -    ONLINE
  mirror                               5.39T    56K  5.39T        -         -     0%  0.00%      -    ONLINE
    36000402001e022294341c87100000000      -      -      -        -         -      -      -      -    ONLINE
```
The proposal is for `zpool list -v` to display `mirror-0`, `mirror-1`, ...

### How will this feature improve OpenZFS?

Provide uniform device names when comparing the output from multiple commands.

### Additional context

Also nice to be able to cut-n-paste output from `zpool list -v` into another ZFS command.

**Comment by akashb-22** [comment]
@behlendorf @stuartthebruce 
hi, I tried to address this issue, please review the change [https://github.com/akashb-22/zfs/tree/vdev_enum](url) .
I have attached the output of the zpool commands after the patch. please let me know if I'm missing something here.
[zpool_output.txt](https://github.com/openzfs/zfs/files/7956522/zpool_output.txt)

**Comment by stuartthebruce** [comment]
I haven't reviewed the code, but the example output is exactly what I am looking for. Thanks!

**Comment by behlendorf** [comment]
Thanks!  The patch handles it in the same way it was done for `zpool status` which is great.  Let's just get a PR open so we can get it integrated.
