### ISSUE TITLE
debian root on zfs problem with secure boot

### ISSUE THREAD

**Issue by Dragon-debian** [openzfs/zfs#12540]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Debian
Distribution Version	|11
Kernel Version	|5.10.0-8-amd64
Architecture	|x86_64
OpenZFS Version	|2.0.3-9

### Describe the problem you're observing
I installed Debian 11 (bullseye) using [Debian Buster Root on ZFS](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html) guide. (with some modifications in datasets and their properties)
At first, secure boot was disabled, after Installation, I created a private rsa key and a certificate for MOK, using this command:
```
openssl req -x509 -new -newkey rsa:2048 -keyout /root/mok.priv -outform \
      DER -out /root/mok.der -days 730 -subj "/CN=Personal CA/" -nodes
```
and then imported that to the MOK using this command:
```
mokutil --import /root/mok.der
```

after that I signed the ZFS modules using this:
```
for i in $(ls /lib/modules/5.10.0-8-amd64/updates/dkms/*); do
/lib/modules/5.10.0-8-amd64/source/scripts/sign-file sha512 /root/mok.priv /root/mok.der $i; done
```
then I checked modules signatures with modinfo (i will put the output of `modinfo zfs`) and also using this command (second way is mentioned [here](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot).)
```
hexdump -Cv /lib/modules/5.10.0-8-amd64/updates/dkms/module-name.ko | tail -n 5
```
all modules were signed, so I rebooted the computer, enabled the secure boot and enrolled my certificate but after booting the OS, I dropped to initramfs recovery shell,  saw that the zfs module didnt load because it isnt signed.
I rebooted several times, disabled and re-enabled the secure boot, tried different keys, deleted and re-imported the certificates, on both real hardware and virtual machine,  but the result didnt change.

In the initramfs shell, the dmesg output showed that my certificate was loaded, but modinfo didnt show the signature while hexdump returned the same value as before.
I think some components to check modules signatures arent present in the intramfs or they may involve after the root filesystem is mounted.

I also tried the built-in feature of dkms for module signing by uncommenting the line `#sign_tool="/etc/dkms/sign_helper.sh` in `/etc/dkms/framework.conf` and putting my private key and certificate in the right location, but the results were the same.

After those, I changed my initramfs system to dracut, by installing `zfs-dracut` package.
In this situation, modules loaded and system started to work. But there is problem with dracut, I cant access root snapshots, the directory `/.zfs/snapshot` contains directories with same names with snapshots, but all of theme are empty and have 777 permission. I think thats another bug.

Results doesnt change when using virtual machine or real hardware. I also tried the same things on buster, but it didnt work at all, no matter using dracut or initramfs-tools as initramfs system or which kernel you installed.

When using a normal linux flesystem such as ext4, boot process finishes with no problem. (zfs is installed and signed. no change in initramfs system)

I saw this #9605, but it didnt help me.
### Describe how to reproduce the problem
1- Install debian with root on zfs as decribed [here](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html).
2- Generate a private key and a certificate for module signing.
3- Sign the modules.
4- enroll the certificate in MOK.
5- Enable secure boot.
6- Boot the system, you should drop in initramfs recovery shell.

### Include any warning/errors/backtraces from the system logs

output of  `modinfo zfs | grep -v ^parm` in booted system, no secure boot.
```
filename:       /lib/modules/5.10.0-8-amd64/updates/dkms/zfs.ko
version:        2.0.3-9
license:        CDDL
author:         OpenZFS
description:    ZFS
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     589A10A280F2E97C4C1E9F6
depends:        spl,znvpair,icp,zlua,zzstd,zunicode,zcommon,zavl
retpoline:      Y
name:           zfs
vermagic:       5.10.0-8-amd64 SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         Personal CA
sig_key:        5F:F0:12:CD:36:6B:47:0F:E4:98:63:B4:91:FF:A1:47:D6:CF:B0:34
sig_hashalgo:   sha512
signature:      8E:8D:0C:61:B1:15:06:17:A8:E9:8B:21:C1:67:DE:98:E1:3D:B1:A6:
                E6:8B:CF:D1:56:B6:6C:52:0D:56:2E:C3:75:91:B7:BD:F1:B6:F2:0C:
                69:6C:64:F8:35:98:C0:92:99:F8:70:FF:64:39:B2:94:FD:C0:9E:9B:
                CF:3A:DF:95:40:DB:7C:6D:61:D5:49:60:E1:AA:23:AF:24:3F:AC:50:
                DD:87:15:84:8B:02:81:E6:09:CF:BD:A4:B6:85:A6:9E:D4:D8:EE:55:
                A3:21:1E:44:27:C2:A8:AE:BB:B6:56:62:7E:7B:F0:00:50:0D:E7:7C:
                2A:DF:88:10:33:43:DD:81:26:4F:04:A4:6F:60:BA:09:95:93:3E:68:
                72:2B:00:D8:27:2B:E3:D8:E8:85:66:6E:30:0D:45:E5:C8:7A:D1:51:
                CA:7A:3F:E6:CE:F9:4E:28:2E:89:84:B8:28:1C:A9:27:10:34:58:A4:
                0B:63:CC:3D:F1:5E:9F:59:96:A1:34:94:06:5A:5C:94:11:4E:22:91:
                3C:BF:11:23:BD:C0:39:32:2E:56:9D:91:68:10:83:A4:18:3A:7F:FB:
                02:97:FC:6D:8B:09:4D:24:BF:0D:7B:16:D3:D4:DE:D8:B7:18:E8:DB:
                92:AC:23:B4:D8:B0:9B:34:AE:26:95:0F:C0:A0:BD:E6
```
output of `modinfo zfs | grep -v ^parm` in initramfs recovery shell, secure boot enabled.
```
filename:       /lib/modules/5.10.0-8-amd64/updates/dkms/zfs.ko
author:         OpenZFS
description:    ZFS
license:        CDDL
version:        %lld
version:        2.0.3-9
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     589A10A280F2E97C4C1E9F6
depends:        spl,znvpair,icp,zlua,zzstd,zunicode,zcommon,zavl
vermagic:       5.10.0-8-amd64 SMP mod_unload modversions
```
output of `hexdump -Cv /lib/modules/5.10.0-8-amd64/updates/dkms/zfs.ko | tail -n 5` is the same, both in booted system and in initramfs recovery shell.
```
0057b720  db 92 ac 23 b4 d8 b0 9b  34 ae 26 95 0f c0 a0 bd  |...#....4.&.....|
0057b730  e6 00 00 02 00 00 00 00  00 00 00 01 91 7e 4d 6f  |.............~Mo|
0057b740  64 75 6c 65 20 73 69 67  6e 61 74 75 72 65 20 61  |dule signature a|
0057b750  70 70 65 6e 64 65 64 7e  0a                       |ppended~.|
0057b759
```
output of `dmesg | grep -i cert` in initramfs recovery shell, secure boot enabled.
```
[    1.051425] Loading compiled-in X.509 certificates
[    1.077469] Loaded X.509 cert 'Debian Secure Boot CA: 6ccece7e4c6c0d1f6149f3dd27dfcc5cbb419ea1'
[    1.077510] Loaded X.509 cert 'Debian Secure Boot Signer 2021 - linux: 4b6ef5abca669825178e052c84667ccbc0531f8c'
[    1.080591] integrity: Loading X.509 certificate: UEFI:db
[    1.080643] integrity: Loaded X.509 cert 'Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53'
[    1.080679] integrity: Loading X.509 certificate: UEFI:db
[    1.080719] integrity: Loaded X.509 cert 'Microsoft Corporation UEFI CA 2011: 13adbf4309bd82709c8cd54f316ed522988a1bd4'
[    1.080754] integrity: Loading X.509 certificate: UEFI:db
[    1.080786] integrity: Loaded X.509 cert 'Mocca: eee4ae78c24bf4a5488b6b77c611edde'
[    1.080812] integrity: Loading X.509 certificate: UEFI:db
[    1.081837] integrity: Loaded X.509 cert '0RB71-80: 9a80e46022d53f8b4e227a3550427c3a'
[    1.082861] integrity: Loading X.509 certificate: UEFI:db
[    1.084096] integrity: Loaded X.509 cert 'LCFC: 16e5000ec0e008a3434536c06d55a3b6'
[    1.085115] integrity: Loading X.509 certificate: UEFI:db
[    1.086132] integrity: Loaded X.509 cert '0XCGCZ411511: 1964db88f8d3688e4b4979178539526e'
[    1.089194] integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
[    1.090416] integrity: Loaded X.509 cert 'Debian Secure Boot CA: 6ccece7e4c6c0d1f6149f3dd27dfcc5cbb419ea1'
[    1.091472] integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
[    1.092680] integrity: Loaded X.509 cert 'Personal CA: 87e9daef2e15410d9f6d6fe3058b7ec98ef03487'
```
last two lines are about my certificate.

this is my last certificate. all modules are signed with its corresponding private key.
[mok.der.gz](https://github.com/openzfs/zfs/files/7117642/MOK-0002.der.gz)

**Comment by Dragon-debian** [comment]
I did some tests and realized that by installing cryptsetup-initramfs package, system recognizes modules signatures and inserts the zfs module and starts to boot. I was using initramfs-tools as my initramfs system, the default initramfs system of debian. zfs-initramfs package was installed.

I also tried this on debian 10, but no matter what I did, it didnt work.

It seems that cryptsetup-initramfs package adds some hooks to the initramfs, so system can recognize modules signatures before even mounting the root filesystem. Isnt it better to mention this somewhere in [Debian B](url)

**Comment by humphreylee** [comment]
I have zfs (encrypted rpool) on Debian sid (dual boot witn Win10) and regularly do `apt full-upgrade`. I'm a step away from enabling SecureBoot, but upon seeing this issues report, haven't enabled it yet. Have been keeping an eye on this issue.

As you've highlighted, I'm also missing the link between zfs modules and cryptsetup-initramfs.

Am I right to say that your steps were below? Do I missed anything like reconfigure initramfs, e.g. `update-initramfs` or `update-grub`, `grub-install`? 
1. apt install cryptsetup-initramfs
2. reboot?

**Comment by Dragon-debian** [comment]
yes, you are almost right, but I was signed my modules before installing `cryptsetup-initramfs`, using built in feature of dkms to automatically sign the modules.
I enabled that by uncommenting the line `sign_tool="/etc/dkms/sign_helper.sh"` in `/etc/dkms/framework.conf` file, so module signing works for all dkms modules.
I also put my mok.der and mok.priv under an encrypted zfs dataset to  protect theme against physical access to hard drive ( my root dataset is not encrypted. but I have some plans for that). because of encrypted dataset, modified the `sign_helper.sh` script to try to load the dataset key and mount it before trying to sign the module. I also wrote a bash script and daemonized that with systemd to always check, unload dataset key and unmount it after 10 second that script recognized dataset is mounted or its key is loaded to prevent my private key from being leaked.

`cryptsetup-initramfs` package has a trigger that that updates the initramfs, `update-initramfs`, triggers `update-grub`, so  no need to use `update-grub` or `update-initramfs` manually.

**Comment by humphreylee** [comment]
Thanks for responding. 

Just for clarification, I guessed the signing of the modules followed the steps as described in this [Debian SecureBoot guide](https://wiki.debian.org/SecureBoot#Using_your_key_to_sign_modules)?

Second question  - Does it matter where you save these files - mok.der and mok.priv. The way I understand it is once you boot-up (after Debian SecureBoot guide), it is registered into the UEFI/BIOS. BTW, I had the signing works but that was btrfs. Under zfs, my rpool is encrypted, while bpool is not. 

I've plan to enable SecureBoot, but upon seeing your problem, I hold back my plan. Need to understand the cryptsetup-initfamfs.

I'm not not native English speaker as well.

**Comment by ReliefCrew** [comment]
A helper script for all this was created [here](https://gist.github.com/ReliefCrew/6beeef4ca3d9afc8fe233c7fcac93799).

**Comment by humphreylee** [comment]
After running that script (very fantastic script), don't forget to run 
`mokutil --import /var/lib/shim-signed/mok/MOK.der`
which I added to the end of that script.
