### ISSUE TITLE
ZFS (DRAID) zabbix - Disk read/write request responses are too high

### ISSUE THREAD

**Issue by temask88** [openzfs/zfs#12542]
DRAID 24HDD, 2 cache nvme.

At the time of writing to the pool, the zabbix swears at the read from the pool, although reading at this moment does not occur.

![130204425-e31081e8-e5fe-4f54-9d49-4f402eb55015](https://user-images.githubusercontent.com/45000603/132350703-3d3ce68e-ac8f-4c3e-9fbc-b2b5adfc36cf.png)

If, at the time of writing to the pool, at the same time, you start reading from it that the problem disappears.

Problem only with writing and no reading.

Zabbix trigger:
min(/zfs-store/vfs.dev.read.await[sdd],15m) > {$VFS.DEV.READ.AWAIT.WARN:"sdd"} or min(/zfs-store/vfs.dev.write.await[sdd],15m) > {$VFS.DEV.WRITE.AWAIT.WARN:"sdd"}

$VFS.DEV.READ.AWAIT.WARN - 20
$VFS.DEV.WRITE.AWAIT.WARN - 20
![130206880-faf5f29b-5db2-4759-a7fe-f598b2d45eac](https://user-images.githubusercontent.com/45000603/132345140-7ff0ee03-83fd-497b-be21-1d3944ff87fa.png)

It is not clear the problem of collection by zabbix or a problem with tuning / optimizing zfs

this is what iostat shows at that moment - no read, write
![130214510-c591aacc-b6e9-437f-b1a3-44b58a55c449](https://user-images.githubusercontent.com/45000603/132345206-e9fe458b-b695-4384-bf41-3a62d7b9481f.png)

The question is, is this a normal situation? is it related to the ZFS and CoW?
If so, what is the best way to monitor disk performance?
If not, what is it ?

**Comment by behlendorf** [comment]
Depending on your hardware this could be normal.  Those read I/O latencies are high, but the HDDs may be prioritizing writes when there are only infrequent reads. It's hard to say.  You can also check `zpool iostat -l` to get a better idea of how long I/Os are queued in ZFS being being issued, and how long it takes the disk to handle them once issued.

One way to [monitor disk performance](https://github.com/openzfs/zfs/blob/zfs-2.1.0/cmd/zpool_influxdb/README.md) is with the `zpool_influxdb` utility which was included in the 2.1 release.

**Comment by temask88** [comment]
here is the moment in time when writing is active in the pool and there is no reading
![image](https://user-images.githubusercontent.com/45000603/133059752-150a86f5-b062-44b3-8d70-b6c78615b2ca.png)

**Comment by behlendorf** [comment]
There may not be any application reads, but internally ZFS may need to read some data if it's not cached.  It looks like the HDDs may be slow to service some of those reads, possibly because they are also a large number of outstanding writes.
