### ISSUE TITLE
Whether HDDs in the storage pool can be hibernated when cache SSDs are hit.

### ISSUE THREAD

**Issue by daiaji** [openzfs/zfs#12551]
I found that even if the Cache SSD in the data pool is hit, the HDD in the storage pool will not be hibernated. Even if I manually hibernate the HDD, zfs still seems to wake up the HDD.
I obviously no longer read data from the HDD, why does the HDD still wake up?
Is it because the metadata is stored in the HDD?
It seems that the behavior of keeping the HDD awakened when only reading the data in the SSD is only consuming the life of the HDD and causing additional energy waste.

**Comment by gmelikov** [comment]
I'm not ready to prepare a proof, but HDD hibernation usually shorten life of HDD, instead of any help.
It's only good for energy savings.

On subject - check iostat to see if there is any read request to HDD. ZFS won't wake up HDD unless there is any IO operation. There is no plan AFAIK to explicitly support case with partial hibernation.

Not a bug for me. Next time please use `Discussions` section for questions.

**Comment by daiaji** [comment]
When the use environment always hits the Cache SSD and does not read data from the HDD for a long time, don't wake up the HDD frequently to keep the HDD dormant for a long time. Isn't it possible to reduce the operation of the HDD to extend the lifespan? I certainly know that frequent hibernation and wake-up are not good for the lifespan of the HDD. But only with reasonable power management, the benefits are not obvious.

**Comment by gmelikov** [comment]
I've meant that if there was really no IO on HDD - ZFS won't stop disk from hibernation, so it's already energy-safe in this case.

If you found such case where we issue unnecessary IO - it would be great to speak based on example, stats and code.

**Comment by daiaji** [comment]
https://forum.manjaro.org/t/the-strange-i-o-behavior-of-zfs
As shown in this topic, I did find some additional writes to ZFS, but I don't know what that is.

**Comment by gmelikov** [comment]
@daiaji 99% it's default atime=on, did you disable it?

**Comment by daiaji** [comment]
I will try to disable the ATIME mount parameters.

**Comment by gmelikov** [comment]
Jfyi it's a zfs dataset parameter.

**Comment by daiaji** [comment]
Thank you, after enabling noatime, HDD seems to be able to sleep peacefully. I am trying relatime and looking forward to the realization of [lazytime](https://github.com/openzfs/zfs/issues/9843).🥰
