### ISSUE TITLE
zpool list -v should show SIZE for spares

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#12561]
### Describe the feature would like to see added to OpenZFS

`zpool list -v` should display the size of `spares` devices rather than "-" as is currently the case for version 2.1.0

### How will this feature improve OpenZFS?

This would make it easier to determine which `spares` are large enough to replace which devices if/when needed

**Comment by rHermes** [comment]
I would like to attempt to solve this as a first issue, if that is ok?

**Comment by stuartthebruce** [comment]
Go for it.

**Comment by behlendorf** [comment]
@rHermes we'd appreciate the help.

**Comment by rHermes** [comment]
I've been looking at this for the past few days and I've come to some realizations:

This is not a special case for `spares`, but rather for all non toplevel vdevs. Checking if the `size` is equal to `0` actually seems to be the way to determine if a vdev is infact a toplevel one or not.

This makes the change harder than expected. I've asked around on the slack channel for the reason why only top level `vdev`s have size information available, but I've got no answer. I'll try on the mailinglist next, but for now I'm not sure why.

There also appears to be an initiative to make this accessable to the zpool command: https://openzfs.topicbox.com/groups/developer/Tb11994f96a39413b. These per vdev props, would allow the user access to these properties. I'm going to checkout allan judes change later, to see how he does it.

It also appears that we do have the size of the physical disk in `include/sys/vdev_impl.h` line 408, parameter `vdev_psize`. I'm not sure how to get this from the kernel side and over to the userside, but I'm investigating this too.

I think that this might take a little while, atleast with my level of understand of the workings of ZFS at this point
