### ISSUE TITLE
with zfs version 0.85,zvol has deadlock with dmu_zfetch interface in linux with kernel 4.14.44.

### ISSUE THREAD

**Issue by oracleloyall** [openzfs/zfs#12591]
Zfs on linux kernel 4.14.44 with some errors as follows:
Sep 11 20:41:51 bjyq-ngbk-mgnode1 kernel: [20529]: scst: scst_abort_cmd:5358:Aborting cmd ffff94c1fa5ab180 (tag 1191248, op WRITE(16))
Sep 11 20:41:51 bjyq-ngbk-mgnode1 kernel: [20529]: scst: scst_abort_cmd:5479:cmd ffff94c1fa5ab180 (tag 1191248, sn 4294967276) being executed/xmitted (state TGT_PRE_EXEC, op WRITE(16), proc time 79 sec., timeout 60 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 0 (mcmd ffff94c297e699a0), initiator 10:00:00:90:fa:0e:c1:fa, target 51:40:2e:c0:12:cb:fe:3a)
Sep 11 20:41:51 bjyq-ngbk-mgnode1 kernel: [20529]: scst_call_dev_task_mgmt_fn_done:5310:Calling dev handler vdisk_blockio task_mgmt_fn_done(fn=0)
Sep 11 20:41:51 bjyq-ngbk-mgnode1 kernel: [20529]: scst_call_dev_task_mgmt_fn_done:5313:Dev handler vdisk_blockio task_mgmt_fn_done() returned
Sep 11 20:41:51 bjyq-ngbk-mgnode1 kernel: [20529]: scst: scst_set_mcmd_next_state:5534:cmd_finish_wait_count(1) not 0, preparing to wait
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:1283 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0  1283      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task txg_quiesce:37137 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: txg_quiesce     D    0 37137      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __wake_up_common_lock+0x87/0xc0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: cv_wait_common+0xf8/0x130 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? remove_wait_queue+0x60/0x60
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: txg_quiesce_thread+0x2a7/0x390 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? txg_fini+0x2a0/0x2a0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: thread_generic_wrapper+0x6f/0x80 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __thread_exit+0x20/0x20 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task v-lanuwyko1_0:2749 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: v-lanuwyko1_0   D    0  2749      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: cv_wait_common+0xf8/0x130 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? remove_wait_queue+0x60/0x60
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rangelock_enter+0x304/0x560 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_request+0x1ce/0x3a0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: generic_make_request+0x115/0x2f0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: submit_bio+0x6e/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: blockio_exec_rw+0x320/0x850 [scst_vdisk]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? blockio_exec_rw+0x850/0x850 [scst_vdisk]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: blockio_exec_write+0x8c/0x130 [scst_vdisk]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: vdev_do_job+0x9b/0x320 [scst_vdisk]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: blockio_exec+0x85/0x350 [scst_vdisk]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: scst_do_real_exec+0xa4/0x590 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? scst_no_dlm_pr_cleanup+0x10/0x10 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: scst_exec_check_blocking+0x210/0x740 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: scst_exec_check_sn+0x1fc/0x4d0 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: scst_process_active_cmd+0x60c/0x2b10 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: scst_cmd_thread+0x390/0x8d0 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? remove_wait_queue+0x60/0x60
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? scst_cmd_done_local+0x2f0/0x2f0 [scst]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:21197 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 21197      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_write_failed+0x20d/0x380
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_write_failed+0x13/0x20
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_write+0x29/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0x1a9/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:21596 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 21596      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:21625 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 21625      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_write_failed+0x20d/0x380
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_write_failed+0x13/0x20
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_write+0x29/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0x1a9/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:21633 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 21633      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:22015 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 22015      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:22019 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 22019      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: INFO: task zvol:22020 blocked for more than 120 seconds.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel:      Tainted: P           OE   4.14.44 #1
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol            D    0 22020      2 0x80000000
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: Call Trace:
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __schedule+0x28b/0x860
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: schedule+0x32/0x80
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: rwsem_down_read_failed+0x139/0x1c0
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: call_rwsem_down_read_failed+0x14/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? dbuf_hold_impl+0xa1/0xc0 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: down_read+0x1c/0x30
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_zfetch+0xb3/0x570 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_buf_hold_array_by_dnode+0x3fb/0x480 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: dmu_write_uio_dnode+0x56/0x140 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: zvol_write+0x19a/0x630 [zfs]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x34/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __switch_to_asm+0x40/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: taskq_thread+0x2d2/0x530 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? wake_up_q+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: kthread+0xff/0x140
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? taskq_thread_spawn+0x50/0x50 [spl]
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ? __kthread_parkme+0x70/0x70
Sep 11 20:42:30 bjyq-ngbk-mgnode1 kernel: ret_from_fork+0x35/0x40
Sep 11 20:42:31 bjyq-ngbk-mgnode1 kernel: [53943]: sqa_qla2xxx_handle_tmr:567:sqatgt(3/0): Received task management cmd: lun=0, type=65531, tag=1192640
Sep 11 20:42:31 bjyq-ngbk-mgnode1 kernel: [53943]: sqa_qla2xxx_handle_tmr:609:sqatgt(3/0): TMR_ABORT_TASK received.

**Comment by rincebrain** [comment]
Please don't just delete the issue template and paste a wall of text.

You may also wish to test a version that came out more recently.

**Comment by Evernow** [comment]
That kernel is ancient, it's ok to use the LTS kernel, it's not ok to be out of date on it. [Follow upstream.](https://www.kernel.org/). You're using a kernel that was released back in March 2018, that is ridiculous.

And as mentioned, use a supported release like 2.0 or 2.1.
