### ISSUE TITLE
Latest version support for all Linux distros (via shell script)

### ISSUE THREAD

**Issue by ThomasLohmann** [openzfs/zfs#12592]
Hi everyone,

it would be great, if you can write a general shell script like "curl -sSLf https://get.openzfs.org | sudo sh" + "sudo install zfs --version=latest or 2.1.1". In this way, you don't need to build ZFS for all distros. In addition, Linux users can always use the latest version of ZFS without to be depends on distro updates itself. For example, currently we use Ubuntu 20.04 and the only way how we can use the latest ZFS version (2.1.1) is either via a custom build (too complicated) or via a PPA (it's not the most secure way): https://launchpad.net/~jonathonf/+archive/ubuntu/zfs 

k0s (Kubernetes distro) also follows the shell script approach and it simplifies the installation of Kubernetes by a lot. See link: https://docs.k0sproject.io/v1.22.2+k0s.0/install/

Regards,
Thomas

**Comment by gmelikov** [comment]
I'm against "curl | sudo"-like distribution for such a critical component like FS as default way. In addition, it is a good practice to use stable, not latest, version for mission-critical infrastructure, so distro updates are the essential part of this process (want stable - use debian/ubuntu LTS, want bleeding-edge - use debian SID/rolling distro).

It may be useful to have such script, but not in a `In this way, you don't need to build ZFS for all distros` paradigm.

Main point - it's the FS, we should be conservative here.

**Comment by ThomasLohmann** [comment]
@gmelikov I disagree with you. Yes, the FS is a critical component, but DevOps should have the option to test the latest version of ZFS on any Linux distro at their own risk as simple as possible (shell script). The gap between the latest ZFS version and current LTS is just too big. For example, Ubuntu 20.04 still supports only version 0.8.X, while there is already version 2.1.X. In addition, the main requirement for ZFS is actually the Linux kernel. And ZFS version 2.1.1 supports the kernel version 3.10 - 5.14. (see link: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.1). Kernel version 3.10 is kind of 100 years old. Finally, most other stuff what distros will add on top each new release are not that relevant for ZFS except the Linux kernel. So I don't get your concerns.

Regards,
Thomas

**Comment by gmelikov** [comment]
@ThomasLohmann I'll align main part of my comment - 

> It may be useful to have such script, but not in a `In this way, you don't need to build ZFS for all distros` paradigm.

If we are talking about "one more method for bleeding-edge tests" - it looks interesting, but IMHO it should not be the only or main one.

And building packages is not so hard https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html (up to 10 lines of copy-paste).

**Comment by ThomasLohmann** [comment]
Yes, it should be at least another "easy" installation method. Have you ever tried the custom build which you mentioned above? It's not that easy as you think and a disaster of complexity compared to a simple PPA like the following: https://launchpad.net/~jonathonf/+archive/ubuntu/zfs

The only problem with the PPA above (or any other PPA regarding ZFS) is, that ZFS itself doesn't maintain it. In additon, launchpad.net is an Ubuntu thing and not a general Linux software distribution channel. That's the reason why we need a general shell script which can be used everywhere. Finally, to build packages for every Linux distro is an outdated approach which takes too much maintenance.

**Comment by gmelikov** [comment]
> Have you ever tried the custom build which you mentioned above

As a contributor I've built them many times, so I'm biased here. I truly don't see problems with copy-pasting 5-10 commands to do so. 

To be constructive from my side - could you describe which may be changed in documentation/method, did you have some exact problems with build?

> The only problem with the PPA above (or any other PPA regarding ZFS) is, that ZFS itself doesn't maintain it. In additon, launchpad.net is an Ubuntu thing and not a general Linux software distribution channel. That's the reason why we need a general shell script which can be used everywhere. Finally, to build packages for every Linux distro is an outdated approach which takes too much maintenance.

It may be a problem for one exact distro, yes. But `curl | sudo bash` way won't fix all problems too. I'm afraid to ask how could you easily update such installations. It would be better to distinct distribution and build parts of this question. Build part looks good to me, but not distribution one.

To begin with, this script will consist of different sections, each unique to different distro and OS. And soon you'll get to `curl openzfs.org/ubuntu | sudo bash`. And we can't just stop to support repo-based distribution, it would be a hassle to support different installation methods, some distros maintain their repos by themself.

> Another solution could be to get rid of all those old Oracle license issues for OpenZFS if they still exist. After that, you could nerve Linus Torvalds once again to push OpenZFS into the Linux kernel itself. In this way, we get newer versions of OpenZFS via the Linux Kernel which will be updated by distros from time to time anyway (within the same distro version, e.g. Ubuntu 20.04).

Funny thing is that in-tree code distributes new features far slower, usually you can't update to bleeding-edge kernel. But I don't want to move this issue to license questions.

So, to conclude - build part of this question may be interested, but not distribution one, IMHO.

**Comment by bghira** [comment]
devops are the last people who would ask for this. speaking as a devops engineer :-)

**Comment by ThomasLohmann** [comment]
Ok, as I can see nobody is interested to install OpenZFS as simple as possible to test the latest features (without custom build). So with a bit of luck, Ubuntu 24.04 will support OpenZFS 2.1.X out of the box. Because I'm not even sure if Ubuntu 22.04 will actually support it. So let's talk to each other once again in 2.5 years. Maybe until this date bcachefs will take over the market (link: https://en.wikipedia.org/wiki/Bcachefs) and this discussion is done anyway...

**Comment by mabod** [comment]
> Maybe until this point of time, bcachefs will take over the market (link: https://en.wikipedia.org/wiki/Bcachefs) and this discussion is done anyway...

You mean bcachefs will take over like btrfs took over more than 10 years ago? Sorry, could'nt resist. ;-)

**Comment by mskarbek** [comment]
Bcachefs is a one-man show. Awesome, admirable work with all the good intentions, but thinking that it will achieve in the next few years' production quality state is a little too optimistic. If building packages is for you too complicated, why not wrap that process in a shell script? That way you will achieve your goal of a single script installation and at the same time have protection of a proven installation method.

**Comment by ThomasLohmann** [comment]
History told us, that nothing on earth will stay forever and that's also valid for OpenZFS. Or as Jeff Bezos once said: "My daily job is to delay the downfall of Amazon as much as possible, since it will happen anyway". And to avoid the downfall, Amazon listens to their customers everyday. I'm saying this, because I expect the same openness from the OpenZFS developers, so that you are able to improve your product everyday. Overall, I think we are done here and the shell script or any other simpler installation method is not an option for you at the moment.

@mabod you have no idea... Facebook has been using btrfs in production for several years. Just because something is not used by mainstream doesn't mean it is bad. See link: https://facebookmicrosites.github.io/btrfs/docs/btrfs-facebook.html

**Comment by mskarbek** [comment]
True wisdom is to know when customers will actually harm themselves with what they are asking for. Shell script may work perfectly well when we are talking about statically build Golang binaries (like mentioned k8s). Maintaining a universal, production-quality installation/update script for such a crucial component of the operating system like the file system is an entirely different beast.

Facebook is using a carefully selected and curated subset of btrfs functions, which they maintain themselves by hiring btrfs core developers. It's a single, non-replicable use case that can't serve as an example.

**Comment by ThomasLohmann** [comment]
@mskarbek true wisdom is if you don't think that you are wiser than others. Since this is the biggest mistake most people make...

**Comment by docent-net** [comment]
"curl -sSLf https://get.openzfs.org | sudo sh" is a terrible way of installing anything. This is an antipattern we should all avoid. It teaches people to install directly from the internet. It's just wrong.

There is a reason for using distro packages, releases and some other popular models of delivering software. It is a security and compliance.

Also - I just don't imagine maintenance burden of such scripts. Idempotency would be a hassle, plus this would be one huge stack of imperative blocks.

**Comment by behlendorf** [comment]
Closing as requested.
