### ISSUE TITLE
incremental send stream requires large-block

### ISSUE THREAD

**Issue by thankph** [openzfs/zfs#12608]
### Discussed in https://github.com/openzfs/zfs/discussions/12606

| Type  | Version/Name |
| ------------- | ------------- |
| Distribution Name  | Ubuntu  |
|  Distribution Version | 20.04 |
| Kernel Version | 5.4.0-52-generic |
| Architecture | amd64 |
| OpenZFS Version| 2.1.1 |

<div type='discussions-op-text'>

<sup>Originally posted by **thankph** October  3, 2021</sup>
I have a setup with three machines.  One machine I'll refer to as the sender, and two other machine are the receivers.  The sender frequently sends incremental snapshots to both receivers.  I upgraded one of the receiving hosts to openzfs  2.1.1 and after a week with no issues, upgraded the second receiver to version 2.1.1, which is where I started experiencing a problem sending incremental snapshosts on some datasets.

<br />

When sending to one of the receivers, I get the following error when sending incremental snapshosts:

<br />

`cannot receive incremental stream: incremental send stream requires -L (--large-block), to match previous receive.`

<br />

The `recordsize` for the `dataset` in question is `1M` on all three hosts.  

<br />

The receiving zpool with no issues is reporting the `large_blocks` feature as 'enabled' as opposed to 'active', where incremental sends for some datasets are failing.   Could this be the problem?  

<br />

I don't want to lose any data, read that there are some issues with using the `-L` flag.  Any ideas?  Thanks.   </div>

**Comment by TPolzer** [comment]
I can reproduce this issue. The timing suspiciously coincides with an update from the debian package zfs-dkms 2.1.5-1~bpo11+1 to 2.1.11-1.

Setting -L on the sending side doesn't change the error message at all.

**Comment by TPolzer** [comment]
Indeed, setting -L on the sender doesn't change the sent stream at all (verified with sha1sum), which makes sense because I never used large records on the sender side.

**Comment by TPolzer** [comment]
The receiver had (inherited) recordsize=1M set, but changing it to 128k didn't make any difference (and there should be no records >128k, because as written above this is a backup dataset of a machine with default 128k recordsize everywhere).

**Comment by Bzzz** [comment]
Still present in zfs-2.3.2-1.
Strangely though, only some of my ZFS are affected. I just sent my master pool over to another array, which has since been declared as the master. Syncing back snapshots does work for some ZFS, and produces the error message for others. Some of the previous master ones were recordsize=1M and some 128k, and there are working and nonworking examples for both sizes. New master is 1M per root setting/inheritance.

**Comment by AustinWise** [comment]
I got the same error message from `zfs receive`. I'm not sure if it is the same issue as the one reported here, so I opened a new issue: #18101.
