### ISSUE TITLE
Large increase of kernel module if BTF is enabled

### ISSUE THREAD

**Issue by Mic92** [openzfs/zfs#12635]
### Describe the problem you're observing

When enabling `DEBUG_INFO_BTF` than the module size increases from 881K to 9.4M
This is a 10x increase and we wonder why this is larger than what we see for the whole kernel (vmlinux).
Is there more btf information stored in this formate compared to other kernel modules?

### Describe how to reproduce the problem

see description

**Comment by Atemu** [comment]
Yeah, it's a requirement: I just set it to no and that disabled BTF.

**Comment by szubersk** [comment]
As mentioned by @Atemu BTF needs generic debug info.
```
Depends on: DEBUG_INFO [=y] && !DEBUG_INFO_SPLIT [=n] && !DEBUG_INFO_REDUCED [=n] && (!GCC_PLUGIN_RANDSTRUCT [=n] || COMPILE_TEST [=n])
```

Just enabling BTF increased the vmlinux size nearly 4.7x
```
-rwxr-xr-x 1 debian debian 62420120 Apr 22 00:19 vmlinux*
-rwxr-xr-x 1 debian debian 13299936 Apr 22 00:17 vmlinux.orig*
```

A tenfold increase on a very small module (prone to error amplification) with rather sophisticated source code should not be surprising. The issue reported here cannot be fixed at OpenZFS level, if it can be fixed at all. I cannot speak for BTF dependency on debug symbols but I'd trust it was for a reason.
