### ISSUE TITLE
Failure importing pool from initrd (initial ramdisk) on Linux

### ISSUE THREAD

**Issue by htkmmo** [openzfs/zfs#12645]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora(ish)
Distribution Version	|  31
Kernel Version	|  4.14.246
Architecture	|  x86_64
OpenZFS Version	|  2.0.6

### Describe the problem you're observing

I am trying to build an initrd for booting my ZFS root (a raid0 of two nvme's). The problem is that for my minimal setup the pool importing operation takes a very long time (more than 30sec.) and ends up in a kernel panic (the console image is at end).  This happens both on real system as well as when debugging under QEMU (version 6.1).

Please note that for a very small, one drive pool, the import operation does succeed under QEMU but as well after a long running time.

I must also mention that the root pool imports fine with my old kernel 4.9.218 which has ZFS version 0.8 with modules compiled in.

### Describe how to reproduce the problem

You can't easily reproduce the problem on your end. To give you an idea the init script is below. If you really have time for a deeper look I can send the kernel image, initrd and the startup command for QEMU. The initrd contains only the libraries needed by zpool and the few utilities used. For some strange reason even a command like 'zpool import' to show the available pools takes more than 30 sec.

#!/bin/bash
export PATH=/bin:/sbin

echo Inserting ZFS modules
insmod mod/spl.ko
insmod mod/zzstd.ko
insmod mod/zavl.ko
insmod mod/zlua.ko
insmod mod/znvpair.ko
insmod mod/zunicode.ko
insmod mod/zcommon.ko
insmod mod/icp.ko
insmod mod/zfs.ko

echo Mounting fs
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

ls -l /dev/zfs
cat /proc/partitions

echo Importing pool
zpool import -f nvme -o readonly=on

### Include any warning/errors/backtraces from the system logs

![tst](https://user-images.githubusercontent.com/2489106/137354824-e563bfed-d809-46ba-bd6d-e0223af36924.png)

**Comment by rincebrain** [comment]
Well, if it's not spending most of its time in the kernel, great, then sharing an strace (ideally with -f and (-r or -t), to indicate how long it spends on things) might be helpful.

Other people might just be shrugging. 30 seconds is, after all, not an impossibly long duration for boot, especially if you're not booting that often.

**Comment by htkmmo** [comment]
Found the reason for the 30 sec duration, it has to do with using libudev and waiting (zpool_label_disk_wait). Compiling with HAVE_LIBUDEV disabled in zfs_config.h makes the pool import complete within a second. 

This all was when using version 0.8.6, not sure if the kernel BUG in 2.0.6 goes away. Now I don't have the time to test 2.0.6 again and I'll stick with the 0.8 branch as it was problem free for my use.
