### ISSUE TITLE
zfs_read() returns early on FreeBSD

### ISSUE THREAD

**Issue by markjdb** [openzfs/zfs#12694]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	|
Kernel Version	| 14.0-CURRENT
Architecture	| amd64
OpenZFS Version	| zfs-kmod-2.1.99-FreeBSD_gec64fdb93

### Describe the problem you're observing
Commit 59eab1093a361ca76849ca76b2ec079c8736e8e3 causes read(2) to return early on FreeBSD. While this is of course permitted, many applications don't handle it well.

### Describe how to reproduce the problem
Run this program on FreeBSD with the OpenZFS commit in question: https://gist.github.com/markjdb/81cc9d0d1e0977232bd5802d72992da5

The FreeBSD VFS disables page faults in the current thread before calling VOP_READ. If a fault occurs while accessing the user buffer, EFAULT is returned and the VFS handles it before retrying the VOP. This scheme is meant to avoid certain deadlocks, see the comment here: https://github.com/freebsd/freebsd-src/blob/2b68eb8e1dbbdaf6a0df1c83b26f5403ca52d4c3/sys/kern/vfs_vnops.c#L1199

The problem is that commit 59eab1093a361ca76849ca76b2ec079c8736e8e3 squashes EFAULT before it returns to the FreeBSD VFS, thus causing the system call to return early in conditions where this isn't desired.

**Comment by behlendorf** [comment]
Closing, this was addressed by #12698.
