### ISSUE TITLE
spl_taskq_expand() scheduling while atomic

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#12696]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	|
Kernel Version	| 5.8.0-59-lowlatency #66~20.04.1-Ubuntu
Architecture	|
OpenZFS Version	| 2.1

### Describe the problem you're observing

Reported in this https://github.com/openzfs/zfs/pull/12664#issuecomment-952355241.  This issue was introduced by the taskq hotplug change, 60a4c7d2a2f8e8123e3c2e45d1773b5849f74b16, which calls `kthread_create()` from an atomic context.  This debug warning is enabled when the kernel is built with `CONFIG_DEBUG_ATOMIC_SLEEP`.

```
Oct 25 12:37:48 foxbox kernel: [103815.516588] CPU: 1 PID: 15 Comm: cpuhp/1 Tainted: P           OE     5
.8.0-59-lowlatency #66~20.04.1-Ubuntu
Oct 25 12:37:48 foxbox kernel: [103815.516589] Hardware name: Gigabyte Technology Co., Ltd. Z68MA-D2H-B3/
Z68MA-D2H-B3, BIOS F10 02/23/2012
Oct 25 12:37:48 foxbox kernel: [103815.516590] Call Trace:
Oct 25 12:37:48 foxbox kernel: [103815.516599]  dump_stack+0x74/0x92
Oct 25 12:37:48 foxbox kernel: [103815.516602]  __schedule_bug.cold+0x4c/0x5d
Oct 25 12:37:48 foxbox kernel: [103815.516606]  __schedule+0x789/0xa70
Oct 25 12:37:48 foxbox kernel: [103815.516609]  schedule+0x6e/0xe0
Oct 25 12:37:48 foxbox kernel: [103815.516611]  schedule_timeout+0x132/0x180
Oct 25 12:37:48 foxbox kernel: [103815.516615]  ? ttwu_queue_wakelist+0x9b/0xd0
Oct 25 12:37:48 foxbox kernel: [103815.516618]  wait_for_completion_killable+0x8a/0x140
Oct 25 12:37:48 foxbox kernel: [103815.516622]  __kthread_create_on_node+0xd6/0x1c0
Oct 25 12:37:48 foxbox kernel: [103815.516630]  ? task_done+0xb0/0xb0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516633]  ? string_nocheck+0x4f/0x60
Oct 25 12:37:48 foxbox kernel: [103815.516639]  ? task_done+0xb0/0xb0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516645]  ? taskq_thread_create+0xf0/0xf0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516647]  kthread_create_on_node+0x49/0x60
Oct 25 12:37:48 foxbox kernel: [103815.516652]  ? task_done+0xb0/0xb0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516658]  spl_kthread_create+0x88/0xd0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516665]  taskq_thread_create+0x6a/0xf0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516671]  spl_taskq_expand+0xc0/0xd0 [spl]
Oct 25 12:37:48 foxbox kernel: [103815.516675]  cpuhp_invoke_callback+0x248/0x630
Oct 25 12:37:48 foxbox kernel: [103815.516678]  cpuhp_thread_fun+0xb8/0x120
Oct 25 12:37:48 foxbox kernel: [103815.516681]  smpboot_thread_fn+0xfc/0x1f0
Oct 25 12:37:48 foxbox kernel: [103815.516683]  ? sort_range+0x30/0x30
Oct 25 12:37:48 foxbox kernel: [103815.516685]  kthread+0x129/0x170
Oct 25 12:37:48 foxbox kernel: [103815.516686]  ? kthread_park+0x90/0x90
Oct 25 12:37:48 foxbox kernel: [103815.516690]  ret_from_fork+0x1f/0x30
Oct 25 12:37:48 foxbox kernel: [103815.517031] BUG: scheduling while atomic: cpuhp/1/15/0x00000000
```

### Describe how to reproduce the problem

It should be possible to reproduce this warning on any kernel with `CONFIG_DEBUG_ATOMIC_SLEEP` enabled when handling a hotplug event.  The issue is that `spl_taskq_expand()` takes the taskq's `tq_lock` spinlock then calls `spl_kthread_create()` which may sleep.  The thread creation needs to be moved outside the atomic spinlock context to resolve this.  Based on the documentation I was able to find sleeping in the hotplug callback should be fine.

**Comment by sunilvaltix** [comment]
Is this marked to land in 2.1.x in near future?

**Comment by RJVB** [comment]
Other inquiring minds like to know this too. I'm seeing what I presume is the same bug after resuming from sleep: I get the backtrace 3 or 4 times in the syslog, curiously always for CPU (core) 3.  I have yet to notice any other effects, it looks like the log entry is just a (debug) message about something that is being handled.

I do also see this before each backtrace:
```
Jan 27 11:48:07 Bola kernel: [259714.830485] Preemption disabled at:
Jan 27 11:48:07 Bola kernel: [259714.830491] [<          (null)>]           (null)
Jan 27 11:48:07 Bola kernel: [259714.830503] CPU: 3 PID: 26 Comm: cpuhp/3 Tainted: P        W  OE   4.14.23-ck1-mainline-core2-rjvb #1
```

I suppose I would have noticed if preemption *remained* disabled...?

**Comment by RJVB** [comment]
I have zswap enabled and can confirm that #12696 is a sufficient fix even in that case.

**Comment by behlendorf** [comment]
Thanks for noticing this wasn't in the 2.1.x patch stack, we'll add it to the list.

**Comment by behlendorf** [comment]
Closing since this was fixed in master.
