### ISSUE TITLE
Rocky/RHEL: Cannot boot from legacy root-filesystem - cmdline:  root=ZFS=pool/ROOT/rocky-8.4

### ISSUE THREAD

**Issue by storepeter** [openzfs/zfs#12706]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 8.4
Kernel Version	| 4.18
Architecture	| x84_64
OpenZFS Version	| 2.0.6

Mounting legacy root filesystems under Rocky-8.4 does not work. and I believe this is the case for all RHEL based systems

On Debian and Ubuntu I use **root=ZFS=pool/ROOT/ubuntu-20.04** on the cmdline to boot into Linux with root-on-ZFS, the dataset has the mountpoint set to legacy.   I have been using this setup for 10 year.  My ZFS-filesystem can hence be booted from different OS-es including FreeBSD and Illumos in the past.

Now that RHEL is available for ordinary people again via Rocky 8.4 I thought I would check it out.  Unfortunately, I could not boot Rocky Linux from a legacy-mounted dataset.

The culprit is dracut (initramfs) which always want to mount the rootfs-dataset with **-o zfutils**, which again means you cannot use legacy mount.

The Rocky-8.4 version of **/lib/dracut/modules.d/90zfs** seems to be an older version of your **zfs/contrib/dracut/90zfs/**

I have described how I got Rocky-Linux to bringup my ZFS-file-system on my blog http://peter.lorenzen.us/zfs/installing-rocky-8-4-rhel-into-a-live-zfs-filesystem

To get Rocky-84 to boot from a legacy dataset I had to apply the patch below, on the Rocky root-file-system, I believe the patch would also work on your current version, although the proper way to implement this should rely on access to the online pool/dataset (which is not the case when zfs-generator.sh is called now).
```
--- /lib/dracut/modules.d/90zfs/zfs-generator.sh.orig	2021-09-16 20:22:33.000000000 -0400
+++ /lib/dracut/modules.d/90zfs/zfs-generator.sh	2021-10-29 19:34:19.271560868 -0400
@@ -28,11 +28,26 @@
 	exit 0
 
 rootfstype=zfs
-case ",${rootflags}," in
-	*,zfsutil,*) ;;
-	,,)	rootflags=zfsutil ;;
-	*)	rootflags="zfsutil,${rootflags}" ;;
-esac
+mountpoint=""
+if [ x"$(zpool list -Ho name)" = "x" ]; then
+	echo "zfs-generator: zpool is not imported yet so we cannot see if mountpoint is legacy" >> /
dev/kmsg
+	if [ "${root##ZFS=}" != "$root" ]; then
+		echo "zfs-generator: root=$root - assume legacy if root=ZFS=" >> /dev/kmsg
+		mountpoint="legacy"
+	fi
+else
+	mountpoint="$(zfs get -Ho value mountpoint ${root##ZFS=})"
+fi
+if [ "$mountpoint" = legacy ]; then
+	echo "zfs-generator: $root is legacy mount" >> /dev/kmsg
+else
+	echo "zfs-generator: $root is not legacy setting zfutil" >> /dev/kmsg
+	case ",${rootflags}," in
+		*,zfsutil,*) ;;
+		,,)	rootflags=zfsutil ;;
+		*)	rootflags="zfsutil,${rootflags}" ;;
+	esac
+fi
```

**Comment by Dragon-debian** [comment]
cant you simply set `canmount=noauto` for root dataset?

**Comment by ne9z** [comment]
There's just no need to use legacy mountpoints here. Like the above comment, use noauto with `/` mountpoint instead.

**Comment by storepeter** [comment]
I do understand that there are ways to get around this missing functionality

Using canmount=noauto and mountpoint=/ means I cannot have concurrent
access to all root-filesystems, and conveniently have access to a full Ubuntu
environment on the ZFS-host boted by Redhat. via f.ex chroot, or nfs-root and virtual box.

if your are brave try something like this on your Linux box:
```

$ sudo zfs set canmount=noauto t470t/ROOT/FreeBSD-13.0-RELEASE
$ sudo zfs set mountpoint=/ t470t/ROOT/FreeBSD-13.0-RELEASE
$ sudo mount -t zfs t470t/ROOT/FreeBSD-13.0-RELEASE /t470t/ROOT/FreeBSD-13.0-RELEASE
 sudo: unable to resolve host t470t: Temporary failure in name resolution
 filesystem 't470t/ROOT/FreeBSD-13.0-RELEASE' cannot be mounted using 'mount'.
 Use 'zfs set mountpoint=legacy' or 'zfs mount t470t/ROOT/FreeBSD-13.0-RELEASE'.
 See zfs(8) for more information.
```

It is not good, - what do you expect will happen ?

I could probably make a script to modify all zfs root datasets each time I change boot-OS,
but my preferred route was/is to fix the the bug where the bug is so the system conforms to its manual.

I actually find it quite funny  that Rocky-Linux goal of being 100% bug-compatible with RedHat
means that even if there was a will to fix this, it would only ripple down sometime in the future ;-)

Something is not right here, or maybe it is just me.

**Comment by AttilaFueloep** [comment]
Yes, that's a valid concern. But I think the proper way to address this is to add `mountpoint` to the temporary mount point properties. That way way you can mount using `zfs mount -o mountpoint=/mnt rpool/be2`.  If there is agreement I can spin something up.

**Comment by storepeter** [comment]
II don't know what temporary mountpoint refers to, I just need a permanent way to have access to all my O.S-es.  It is very convenient to be able to use Redhat tools even when running Ubuntu. or just being able to return to an older versions of Ubuntu.

In this world of bit-rod I will give you an example:  I needed to compile Openwrt-18.06.1, My server is running Ubuntu-20.04.3 and out of the box, what was common two years ago does not compile any-more.  Luckyly I have all my previous Root-filesystems available in my ZFS pool. so a chroot (or nfs-root VirtualBox boot) is all that is needed to get things working instantly.

I started this issue mostly so that sys-admins who got stuck at this issue could fix it themselves, and move on.  That was in October, by now it is clear to me that that nobody uses ZFS this way in the Redhat world, so maybe the easiest is to change the Manual to say that in our Redhat walled garden we do not support this kind of thing. It is in the first section here: https://github.com/openzfs/zfs/blob/master/contrib/dracut/README.dracut.markdown

On the other hand, I am disappointed to see that even though OpenZFS seems to consolidate the core source code, the way the systems boot differ more now than 10 years ago. I once had a grub.cfg which could boot Ubuntu,FreeBSD and Illumos, 
This is not the case any-more, and it is probably natural that f.ex. FreeBSD does not care if their ZFS pool can be booted by a Linux OS, or vice versa.

Personally I would aim for a system where it would be easy to migrate from one O.S.  to another, This has happened 3 times for me during the 10 years life-span of my ZFS-pool. http://peter.lorenzen.us/linux/installing-freebsd-into-a-live-zfs-filesystem-from-f-ex-linux

For this particular issue,  all you need to do is to fix the bug, I even included a fix, although  as I write there might be a better way.

**Comment by Dragon-debian** [comment]
you can mount a zfs dataset that has `canmount=noauto` or `canmount=on` with mount command without changing its `mountpoint` property. just use `-o zfsutil` with the mount command.
try this with your dataset
```bash
mount -t zfs -o zfsutil t470t/ROOT/FreeBSD-13.0-RELEASE /t470t/ROOT/FreeBSD-13.0-RELEASE
```
I have four different boot environments with `canmount=noauto` and  `mountpoint=/`
```bash
rpool/ROOT/debian/default
rpool/ROOT/debian/test
rpool/ROOT/arch/default
rpool/ROOT/void/test
```
two debian bullseye. `rpool/ROOT/debian/default` is my primary boot environment, `rpool/ROOT/debian/test` is a clone of `rpool/ROOT/debian/default` that  I sometimes use for testing things.
a minimal arch linux, it doest have any graphical interface
and a minimal void linux installation similar to arch.

sometimes I need to use arch for a quick test, I simply mount its dataset like this:
```bash
sudo mount -t zfs -o zfsutil rpool/ROOT/arch/default /mnt
```
and then jump to it with chroot.
the zfs version in debian is 2.0.3, both arch linux and void linux, has a higher version zfs.

I dont know the zfs version in RHEL 8 but I think this should work there too.
the `-o zfsutil` is documented in `mount.zfs` command man page. mount.zfs(8)

**Comment by AttilaFueloep** [comment]
Right, I didn't thought about the `mount -o zfsutil` option. That achieves the same as a potential `zfs mount -o mountpoint=` would.
