### ISSUE TITLE
[5.16] wait_on_page_bit() is gone

### ISSUE THREAD

**Issue by 65a** [openzfs/zfs#12756]
zfs_vnops_os.c:3534:33: error: implicit declaration of function 'wait_on_page_bit'

**Comment by 65a** [comment]
References to this not found at HEAD in linux sources

**Comment by jgottula** [comment]
As with #12757, it would have been helpful if you'd used the issue template. This is actually a Linux kernel 5.16 compat breakage, and the issue title should be changed to reflect that.

Anyway. The relevant commit is https://github.com/torvalds/linux/commit/101c0bf67f50ca0e8b9da97b26f8dc7cb232b4d3, which renames `wait_on_page_bit` to `folio_wait_bit`.

The sole caller in the ZFS codebase appears to be `zfs_putpage`.

**Comment by 65a** [comment]
See notes on that issue. Title updated, apologies for confusion, was hoping HEAD reference here was clear.

**Comment by jgottula** [comment]
> apologies for confusion, was hoping HEAD reference here was clear.

This is partly on me; I looked at the highest-numbered issue first and then went in descending order, so I only saw that bit after having written up the first reply and already figured out that it was 5.16-next. 😬

**Comment by 65a** [comment]
No worries, I should be more clear. I guess friday evening is not a good time for me to file bugs, and I came with the old -CURRENT mindset that everything is at HEAD. Will use template in the future, and appreciate the challenges faced by anyone contributing. Cheers, at least it's ZFS :)

**Comment by satmandu** [comment]
I believe https://github.com/openzfs/zfs/pull/12800 also fixes this.

**Comment by behlendorf** [comment]
@satmandu thanks, you are correct.
