### ISSUE TITLE
zpool clear should continue scrub from point it left off, not restart from beginning

### ISSUE THREAD

**Issue by eharris** [openzfs/zfs#12761]
I have a raidz pool that takes a very long time (almost a week) to scrub or rebuild, and the automatic halting of a scrub after some arbitrary number of repaired errors makes it effectively impossible to do maintenance on the pool.  Because zfs automatically stops a scrub if some arbitrary number of "too many" repairs is needed, the only means left is to issue a `zpool clear`, but that causes the scrub to restart from the beginning, which causes massive delays re-checking data that has already been repaired.

`zpool clear` should cause the scrub to resume from the point it stopped, rather than restart.  If someone needs to restart from the beginning, that is easily done by canceling the scrub and then restarting it.

Opening this since original issue (#10709) was closed as stale with no way to reopen.  More details on the use case are there.

**Comment by bghira** [comment]
well you're on 0.7.x in that original issue and there's been substantial improvements to the scan/resilver code in the 2.x series

**Comment by eharris** [comment]
Has this change already been made in the scrub code in a later version?  Otherwise it's still an issue.

**Comment by bghira** [comment]
yep it's been in a release for quite some time now and plenty of us have been using it since even before then
