### ISSUE TITLE
Zpool not showing up in `zdb -L` output

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#12774]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch
Distribution Version	| Current
Kernel Version	| 5.4.159
Architecture	| x86_64
OpenZFS Version	| 2.0.4

### Describe the problem you're observing

Host with 3 zpools only shows 2 of them via `zdb -L` and all three in `zpool list`

**Comment by Dragon-debian** [comment]
can you provide more information? such as `zpool status` `zdb -L`, pool version and other things.
