### ISSUE TITLE
Kernel panic on incremental send/recv between two encrypted datasets on the same pool, dest is using zstd-19

### ISSUE THREAD

**Issue by darrenfreeman** [openzfs/zfs#12785]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| debian
Distribution Version	| 11.1
Kernel Version	| 5.7.0-1-amd64
Architecture	| x86-64 AMD Opteron 6272 w/ 8 nodes and 64 cores, 128 GiB RAM
OpenZFS Version	| zfs-2.0.3-9 zfs-kmod-2.0.3-9

### Describe the problem you're observing
The `zfs send | zfs recv` is frozen, and an attempt to `zfs set mountpoint=` on the source dataset also hanged. So the system had to be rebooted.

Upon reboot, a scrub appears to have started by itself.

```
  pool: rpool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub in progress since Tue Nov 23 08:00:01 2021
        13.9T scanned at 2.50G/s, 13.3T issued at 0B/s, 15.9T total
        0B repaired, 83.48% done, no estimated completion time
config:

        NAME         STATE     READ WRITE CKSUM
        rpool        ONLINE       0     0     0
          raidz2-0   ONLINE       0     0     0
            rpool0   ONLINE       0     0     0
            rpool1   ONLINE       0     0     0
            rpool2   ONLINE       0     0     0
            rpool3   ONLINE       0     0     0
            rpool4   ONLINE       0     0     0
            rpool5   ONLINE       0     0     0
        logs
          rpool-log  ONLINE       0     0     0
        cache
          sdg5       ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <0xc6ca>:<0x0>
```

### Describe how to reproduce the problem

I don't think this will reproduce, but it's what I was doing at the time:

```
zfs send rpool/sub/source@end -I start | pv | zfs recv -u rpool/sub/dest
```

Source and destination datasets are encrypted using the same root. The only difference should be that `compression=lz4` on the source, but `compression=zstd-19` on the dest. CPU usage was around 75%, on this system which is otherwise at 1% - I attribute this to zstd compression. This is not the first dataset, on this pool, that I have successfully recompressed using the above technique. I have also done many TB of raw send/recv of encrypted datasets between pools, without rebooting, before this step which failed.

### Include any warning/errors/backtraces from the system logs
```
Nov 23 21:14:24 host kernel: VERIFY3(0 == dmu_bonus_hold_by_dnode(dn, FTAG, &db, flags)) failed (0 == 5)
Nov 23 21:14:24 host kernel: PANIC at dmu_recv.c:1811:receive_object()
Nov 23 21:14:24 host kernel: Showing stack for process 3588403
Nov 23 21:14:24 host kernel: CPU: 20 PID: 3588403 Comm: receive_writer Tainted: P           OE     5.7.0-1-amd64 #1 Debian 5.7.6-1
Nov 23 21:14:24 host kernel: Hardware name: SGI.COM H2106-G7/H8QG6-F, BIOS 080016     06/24/2014
Nov 23 21:14:24 host kernel: Call Trace:
Nov 23 21:14:24 host kernel:  dump_stack+0x66/0x90
Nov 23 21:14:24 host kernel:  spl_panic+0xd4/0xfc [spl]
Nov 23 21:14:24 host kernel:  ? dbuf_rele_and_unlock+0x30c/0x660 [zfs]
Nov 23 21:14:24 host kernel:  ? dbuf_read+0x1cc/0x510 [zfs]
Nov 23 21:14:24 host kernel:  ? zfs_zevent_post+0x1f0/0x2a0 [zfs]
Nov 23 21:14:24 host kernel:  receive_object+0x95d/0xca0 [zfs]
Nov 23 21:14:24 host kernel:  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
Nov 23 21:14:24 host kernel:  ? _cond_resched+0x15/0x30
Nov 23 21:14:24 host kernel:  receive_writer_thread+0x1d9/0x9f0 [zfs]
Nov 23 21:14:24 host kernel:  ? receive_process_write_record+0x190/0x190 [zfs]
Nov 23 21:14:24 host kernel:  ? thread_generic_wrapper+0x6f/0x80 [spl]
Nov 23 21:14:24 host kernel:  thread_generic_wrapper+0x6f/0x80 [spl]
Nov 23 21:14:24 host kernel:  kthread+0xf9/0x130
Nov 23 21:14:24 host kernel:  ? __thread_exit+0x20/0x20 [spl]
Nov 23 21:14:24 host kernel:  ? kthread_park+0x90/0x90
Nov 23 21:14:24 host kernel:  ret_from_fork+0x22/0x40
```

Subsequently, sanoid attempted to snapshot an unrelated dataset. I'm not sure whether it completed, but I suspect not.

And then the inevitable time-out:

```
Nov 23 21:17:23 host kernel: INFO: task txg_quiesce:1075648 blocked for more than 120 seconds.
Nov 23 21:17:23 host kernel:       Tainted: P           OE     5.7.0-1-amd64 #1 Debian 5.7.6-1
Nov 23 21:17:23 host kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Nov 23 21:17:23 host kernel: txg_quiesce     D    0 1075648      2 0x80004000
Nov 23 21:17:23 host kernel: Call Trace:
Nov 23 21:17:23 host kernel:  __schedule+0x2da/0x770
Nov 23 21:17:23 host kernel:  schedule+0x4a/0xb0
Nov 23 21:17:23 host kernel:  cv_wait_common+0xfb/0x130 [spl]
Nov 23 21:17:23 host kernel:  ? finish_wait+0x80/0x80
Nov 23 21:17:23 host kernel:  txg_quiesce_thread+0x2b1/0x3a0 [zfs]
Nov 23 21:17:23 host kernel:  ? txg_sync_thread+0x4a0/0x4a0 [zfs]
Nov 23 21:17:23 host kernel:  thread_generic_wrapper+0x6f/0x80 [spl]
Nov 23 21:17:23 host kernel:  kthread+0xf9/0x130
Nov 23 21:17:23 host kernel:  ? __thread_exit+0x20/0x20 [spl]
Nov 23 21:17:23 host kernel:  ? kthread_park+0x90/0x90
Nov 23 21:17:23 host kernel:  ret_from_fork+0x22/0x40
Nov 23 21:17:23 host kernel: INFO: task receive_writer:3588403 blocked for more than 120 seconds.
Nov 23 21:17:23 host kernel:       Tainted: P           OE     5.7.0-1-amd64 #1 Debian 5.7.6-1
Nov 23 21:17:23 host kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Nov 23 21:17:23 host kernel: receive_writer  D    0 3588403      2 0x80004000
Nov 23 21:17:23 host kernel: Call Trace:
Nov 23 21:17:23 host kernel:  __schedule+0x2da/0x770
Nov 23 21:17:23 host kernel:  schedule+0x4a/0xb0
Nov 23 21:17:23 host kernel:  spl_panic+0xfa/0xfc [spl]
Nov 23 21:17:23 host kernel:  ? dbuf_rele_and_unlock+0x30c/0x660 [zfs]
Nov 23 21:17:23 host kernel:  ? dbuf_read+0x1cc/0x510 [zfs]
Nov 23 21:17:23 host kernel:  ? zfs_zevent_post+0x1f0/0x2a0 [zfs]
Nov 23 21:17:23 host kernel:  receive_object+0x95d/0xca0 [zfs]
Nov 23 21:17:23 host kernel:  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
Nov 23 21:17:23 host kernel:  ? _cond_resched+0x15/0x30
Nov 23 21:17:23 host kernel:  receive_writer_thread+0x1d9/0x9f0 [zfs]
Nov 23 21:17:23 host kernel:  ? receive_process_write_record+0x190/0x190 [zfs]
Nov 23 21:17:23 host kernel:  ? thread_generic_wrapper+0x6f/0x80 [spl]
Nov 23 21:17:23 host kernel:  thread_generic_wrapper+0x6f/0x80 [spl]
Nov 23 21:17:23 host kernel:  kthread+0xf9/0x130
Nov 23 21:17:23 host kernel:  ? __thread_exit+0x20/0x20 [spl]
Nov 23 21:17:23 host kernel:  ? kthread_park+0x90/0x90
Nov 23 21:17:23 host kernel:  ret_from_fork+0x22/0x40
```

(Omitted three more similar timeouts.)

**Comment by darrenfreeman** [comment]
Likely related to #12001, #12270.

Maybe related to #12014, #12594, #12732.

**Comment by darrenfreeman** [comment]
I allowed this scrub to complete normally, then sent the remaining snapshots to the destination dataset. The "permanent errors" were still listed against the pool.

Then I performed a second scrub, and after that, there are no permanent errors listed. I have not rebooted or export/import etc. in the meantime.

```
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0B in 11:55:37 with 0 errors on Wed Nov 24 14:00:59 2021
config:

        NAME         STATE     READ WRITE CKSUM
        rpool        ONLINE       0     0     0
          raidz2-0   ONLINE       0     0     0
            rpool0   ONLINE       0     0     0
            rpool1   ONLINE       0     0     0
            rpool2   ONLINE       0     0     0
            rpool3   ONLINE       0     0     0
            rpool4   ONLINE       0     0     0
            rpool5   ONLINE       0     0     0
        logs
          rpool-log  ONLINE       0     0     0
        cache
          sdg5       ONLINE       0     0     0

errors: No known data errors
```

This "permanent errors", "data corruption", and "Otherwise restore the entire pool from backup." messaging really needs to change. It's rather frightening, and the solution appears to be to scrub it __not once, but twice__.

**Comment by darrenfreeman** [comment]
In case it becomes relevant, I just noticed that I hadn't loaded the keys for the affected datasets. If someone else can't get the message to clear, try not having keys loaded.

**Comment by darrenfreeman** [comment]
Well, it happened again, under similar conditions:

```
zfs send rpool/src@snapshot | pv | zfs recv -u -o recordsize=1M -o compression=zstd-19 rpool/dest
```

The output from pv indicates that 21.3 GB of the stream has been processed so far. I noticed some extra things in the system log, which could possibly be involved in triggering this issue:

```
Nov 24 22:18:37 host systemd[1]: sanoid.service: Succeeded.
Nov 24 22:18:37 host systemd[1]: Finished Snapshot ZFS filesystems.
Nov 24 22:18:37 host systemd[1]: sanoid.service: Consumed 42.905s CPU time.
Nov 24 22:18:38 host systemd[1]: Starting Prune ZFS snapshots...
Nov 24 22:18:39 host sanoid[1613707]: INFO: pruning snapshots...
Nov 24 22:18:39 host sanoid[1613707]: INFO: pruning other/sub/first@autosnap_2021-11-24_08:15:16_frequently ...
Nov 24 22:18:39 host sanoid[1613707]: INFO: removing destroyed snapshots from cache.
Nov 24 22:18:39 host sanoid[1613707]: INFO: pruning other/sub/second@autosnap_2021-11-24_08:15:16_frequently ...
Nov 24 22:18:41 host sanoid[1613707]: INFO: removing destroyed snapshots from cache.
Nov 24 22:18:41 host sanoid[1613707]: INFO: pruning other/third@autosnap_2021-11-24_08:15:16_frequently ...
Nov 24 22:18:43 host sanoid[1613707]: INFO: removing destroyed snapshots from cache.
Nov 24 22:18:43 host sanoid[1613707]: INFO: pruning other/another/fourth@autosnap_2021-11-24_10:45:20_frequently ...
Nov 24 22:18:43 host sanoid[1613707]: INFO: deferring pruning of other/another/fourth@autosnap_2021-11-24_10:45:20_frequently - other/another/p>
Nov 24 22:18:43 host sanoid[1613707]: INFO: pruning rpool/another/fifth@autosnap_2021-11-24_10:15:05_frequently ...
Nov 24 22:19:02 host CRON[1615373]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Nov 24 22:19:02 host CRON[1615411]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 24 22:19:02 host CRON[1615373]: pam_unix(cron:session): session closed for user root
Nov 24 22:20:00 host sanoid[1613707]: INFO: removing destroyed snapshots from cache.
Nov 24 22:20:00 host sanoid[1613707]: INFO: pruning other/sub/sixth@autosnap_2021-11-24_08:15:16_frequently ...
Nov 24 22:20:00 host kernel: VERIFY3(0 == dmu_bonus_hold_by_dnode(dn, FTAG, &db, flags)) failed (0 == 5)
Nov 24 22:20:00 host kernel: PANIC at dmu_recv.c:1811:receive_object()
Nov 24 22:20:00 host kernel: Showing stack for process 1622663
Nov 24 22:20:01 host kernel: CPU: 56 PID: 1622663 Comm: receive_writer Tainted: P           OE     5.7.0-1-amd64 #1 Debian 5.7.6-1
Nov 24 22:20:01 host kernel: Hardware name: SGI.COM H2106-G7/H8QG6-F, BIOS 080016     06/24/2014
Nov 24 22:20:01 host kernel: Call Trace:
Nov 24 22:20:01 host kernel:  dump_stack+0x66/0x90
Nov 24 22:20:01 host kernel:  spl_panic+0xd4/0xfc [spl]
Nov 24 22:20:01 host kernel:  ? dbuf_rele_and_unlock+0x30c/0x660 [zfs]
Nov 24 22:20:01 host kernel:  ? dbuf_read+0x1cc/0x510 [zfs]
Nov 24 22:20:01 host kernel:  ? zfs_zevent_post+0x1f0/0x2a0 [zfs]
Nov 24 22:20:01 host kernel:  receive_object+0x95d/0xca0 [zfs]
Nov 24 22:20:01 host kernel:  ? dnode_rele_and_unlock+0x5c/0xc0 [zfs]
Nov 24 22:20:01 host kernel:  ? _cond_resched+0x15/0x30
Nov 24 22:20:01 host kernel:  receive_writer_thread+0x1d9/0x9f0 [zfs]
Nov 24 22:20:01 host kernel:  ? receive_process_write_record+0x190/0x190 [zfs]
Nov 24 22:20:01 host kernel:  ? thread_generic_wrapper+0x6f/0x80 [spl]
Nov 24 22:20:01 host kernel:  thread_generic_wrapper+0x6f/0x80 [spl]
Nov 24 22:20:01 host kernel:  kthread+0xf9/0x130
Nov 24 22:20:01 host kernel:  ? __thread_exit+0x20/0x20 [spl]
Nov 24 22:20:01 host kernel:  ? kthread_park+0x90/0x90
Nov 24 22:20:01 host kernel:  ret_from_fork+0x22/0x40
Nov 24 22:20:01 host CRON[1623091]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Nov 24 22:20:01 host sanoid[1613707]: INFO: removing destroyed snapshots from cache.
Nov 24 22:20:00 host systemd[1]: Starting system activity accounting tool...
Nov 24 22:20:01 host CRON[1623092]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 24 22:20:00 host systemd[1]: sysstat-collect.service: Succeeded.
Nov 24 22:20:01 host CRON[1623091]: pam_unix(cron:session): session closed for user root
Nov 24 22:20:00 host systemd[1]: Finished system activity accounting tool.
Nov 24 22:20:01 host systemd[1]: sanoid-prune.service: Succeeded.
Nov 24 22:20:01 host systemd[1]: Finished Prune ZFS snapshots.
Nov 24 22:20:01 host systemd[1]: sanoid-prune.service: Consumed 2.941s CPU time.
```

Note that sanoid is never touching the src/dest datasets, but it is interacting with the pool that they are on. Also syncoid is sending snapshots onto this pool, every few minutes.

I'm not sure if a reboot was required, I was able to mount the source dataset, I was able to look at its properties. But, the dest is hanging around mid-receive, and the receive process couldn't be killed. I tried to unmound the source dataset, and that command froze, so I decided to reboot.

Prior to actually rebooting, I took a `zpool status -v`:

```
  pool: rpool
 state: ONLINE
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 11:55:37 with 0 errors on Wed Nov 24 14:00:59 2021
config:

        NAME         STATE     READ WRITE CKSUM
        rpool        ONLINE       0     0     0
          raidz2-0   ONLINE       0     0     0
            rpool0   ONLINE       0     0     0
            rpool1   ONLINE       0     0     0
            rpool2   ONLINE       0     0     0
            rpool3   ONLINE       0     0     0
            rpool4   ONLINE       0     0     0
            rpool5   ONLINE       0     0     0
        logs
          rpool-log  ONLINE       0     0     0
        cache
          sdg5       ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        rpool/another/seventh/%recv:<0x0>
```

The dataset mentioned on the last line above, is receiving via syncoid, on minutes ending in 1 or 6, via the following invocation from cron. (It's currently the only instance of syncoid being run anywhere.)
```
syncoid --no-sync-snap --create-bookmark other/another/fourth rpool/another/seventh
```

It's likely not a big delta at all, and there's every chance that this is what some of the CRON log messages are about.

**Comment by darrenfreeman** [comment]
Upon reboot, the pool status shows the same as above. A scrub has not begun, and the error shows the same, with `rpool/another/seventh/%recv<0:0>`. The corresponding dataset had a `receive_resume_token`.

I then tried `zfs receive -A rpool/another/seventh` and got the error message:
```
'rpool/another/seventh' does not have any resumable receive state to abort.
```

I checked again, and the token was gone. I don't know whether syncoid did this, but as the key for rpool was not loaded, syncoid was unable to send new snapshots.

The end of `zpool status -v` now reads:

```
errors: Permanent errors have been detected in the following files:

        <0x39e2>:<0x0>
```

I loaded the keys, and manually invoked syncoid. It ran fine, the snapshots have appeared on `rpool/another/seventh`. The anonymous error still appears on zpool status, so I shall scrub twice, and see what happens.

**Comment by Ornias1993** [comment]
@darrenfreeman It's known for a LONG LONG time by now that you should NOT use ZSTD-19, there are known issues with it.

**Comment by darrenfreeman** [comment]
@Ornias1993 that was never conveyed to me. It's shipping in Debian without any warnings.

Can you please link me to where it's been posted?

**Comment by darrenfreeman** [comment]
FWIW, I've diffed at least a GB of data between snapshots mounted side by side, lz4 and zstd-19. So far no differences found, no data loss that I'm aware of.

**Comment by Ornias1993** [comment]
> @Ornias1993 that was never conveyed to me. It's shipping in Debian without any warnings.
> 
> Can you please link me to where it's been posted?

It has been discussed by me and other devs involved with the ZSTD on ZFS project back in the day quite a few times. I'm not 100% sure what the issues where, just that there where a few serieus issues with the higher levels.

Those where also just included "because we can" and not considered "realistic" for any "reasonable usecase" (as discussed publically a few times).

Sadly enough, me and most other ZSTD on ZFS related developers quit working on it, because of lack of support by the maintainers here. (except Allan Jude, but that guy is 99% talk anyway)

**Comment by darrenfreeman** [comment]
I have only seen public discussion in favour of zstd on zfs. If there are serious issues, then it needs to be given equal exposure. But for the record, is what I'm seeing likely to be one of those issues?

I believe I have a "reasonable usecase". I know that it's taking 75% CPU, on this machine, to achieve about 100-200 MB/s of compression speed, and I don't care for these bulky and hardly-touched datasets. The gains are well worth it to be able to do a raw send/recv to a slow machine, over a slow link. That machine only ever has to scrub, it never has to decompress.

Overall I've been very impressed with zstd-19 on zfs, aside from this issue.

**Comment by Ornias1993** [comment]
> I have only seen public discussion in favour of zstd on zfs. If there are serious issues, then it needs to be given equal exposure. But for the record, is what I'm seeing likely to be one of those issues?
> 
> I believe I have a "reasonable usecase". I know that it's taking 75% CPU, on this machine, to achieve about 100-200 MB/s of compression speed, and I don't care for these bulky and hardly-touched datasets. The gains are well worth it to be able to do a raw send/recv to a slow machine, over a slow link. That machine only ever has to scrub, it never has to decompress.
> 
> Overall I've been very impressed with zstd-19 on zfs, aside from this issue.

Might be, kernelpanics are known on zstd-19.
The discussions are there, we’ve over 2000 comments bsck and forth just on thus github, including older issues.
Anyway /care because we quit working on it, just wamted  to give you the headsup, searching on zstd should turn-up shit.

**Comment by robszy** [comment]
The problem with changing version is that is need rewriting compressed ARC code and fixes to encryption (it is mystery that no one thought about that compression will change and we cannot bind to exact compressed bytes  in encryption ) maybe by authenticating decompressed data but it needs time ( money ) and as it looks there is no intention to fix this problems (I saw that all encryption is neglected and poorly supported ) but are critical to  keep zstd updated thus not vulnerable and secure and if it is not in agenda of zfs I don't know what is.


If anyone want to change zstd version he needs to push complete solution because there is no interest in doing that by maintainers. Next versions would be easier to push but there is no help/interest from maintainers as @Ornias1993 rightly said to support bumping zstd version which is right no matter what and other parts of code must be rewritten to make it easy to bump to 1.6 and so on in my opinion

**Comment by Ornias1993** [comment]
@robszy This is a beter sumary, as the post from @rincebrain is a summary of a summary (of a summary?):
https://github.com/openzfs/zfs/pull/11367#pullrequestreview-559645117

> 2. We need to assume that moving from v1.4.5 to v1.4.8 means blocks may now be compressed differently between versions.  As noted in the original PR this is an issue for the compressed ARC and for encryption which depend on being able to re-compress and buffer and have it identically match what's on disk.  This is why we needed to include the zstd version number in the block header.  So we're going to need to either include both versions of zstd and provide an interface to request a specific zstd version.  Or determine if we can relax this restriction somewhat with some changes to the higher level compressed ARC and encryption code.
> 3. Decide if now is really the best time to bump the zstd version.  If we determine in 2) that we absolutely need to maintain multiple versions this will  increase the code complexity and result in progressively larger `zzstd.ko` binaries the more often we update the version.  To avoid that we may want to intentionally not update the version very frequently.
> 4. As part of any update to the zstd version we'll need to include tests cases which verify the new code works fine with pools created with an older version.  We'll also need to ensure the older 1.4.5 based ZFS code works fine with pools created with 1.4.8 based code.  The seconds set of tests wouldn't be easy to add to the ZTS so some manual testing would probably be needed.  We'd also want to make sure to test with encrypted pools that use compressed L2ARC devices since that's where we'd expect the most trouble.
> 
> I believe allanjude was already planning to tackle some of these items in the new year.

1. was not an issue
2. 
- Either contain multiple ZSTD versions and rewrite code to recompress with older versions in some cases
- Or rewrite and/or remove some of the (un)compressed ARC and encryption code
3. was mostly fixed as no one wants to ship ZFS with multiple huge binaries
4. Those testcases are rather trivial to add

So in short:
- Someone has to idealy make compressed L2ARC mandatory
- Some checks that recompress data need to be adapted
- Some Tests has to be writen

The problem is the amount of trust they maintainers repeatly put into the false promisses of Allan Jude.
If just they where honest that he almost never delivers on promises and said "Well he didn't deliver, lets step up to the task of finding someone else to fix these issues".

Because the thing with the above is:
It has nothing to do with ZSTD, it's general design of ZFS that needs to be adapted. That's also why I considered it out-of-scope of the ZSTD update itself.
The ZSTD stack itself is 100% able to be updated and even already contains compatiblity hooks that allow it to be easily updated in the future.

**Comment by darrenfreeman** [comment]
For myself, and anyone trying to follow this, is it safe to leave datasets as zstd? Is the issue purely that sometimes non-raw datasets can't be received without rendering the system unusable?

Is there any mitigation? Like taking off memory pressure until the receive is completed? (E.g. I could stop syncoid.)

My user feedback is that the feature is very useful, I would rather complete recompressing this data for archival, if it's safe to leave it with zstd once it finishes.

**Comment by robszy** [comment]
Zstd group didn't propose to make required changes if Allan Jude won't deliver till some deadline with of course little help as it is outofscope ? It would be ridiculous if they had refused that offer because it would mean that they don't care about updating zfs software.

Or maintainers doesn't allow you to change arc code or they just won't help with that change ?

Maybe pulling those required changes with help whoever want to help will resolve this issue ?

**Comment by robszy** [comment]
Back to issue. No one will answers question @darrenfreeman  are asking because this issue needs investigation and from my understanding there is no big interest in solving send/receive issues also with encryption so most probably this issue won't be resolved ever or You could try to resolve it alone :) as there is no support from my understanding.

**Comment by darrenfreeman** [comment]
I am investigating without looking at any code. My current test is to recompress 3 TB, after dropping the L2ARC, SLOG, and stopping sanoid/syncoid. Many would find that a reasonable compromise if it succeeds, since those can be added back afterwards.

**Comment by robszy** [comment]
Maybe someone can shed a light what this assert means:

> VERIFY3(0 == dmu_bonus_hold_by_dnode(dn, FTAG, &db, flags)) failed (0 == 5)

It could lead to source of troubles ?

**Comment by BrainSlayer** [comment]
zstd-19 with 64 cores? nice. or to make it short. how to consume all of your 128 gb ram at once. your bug is very likelly a out of memory condition and yes, this leads to panics

**Comment by darrenfreeman** [comment]
Well it's currently sending that 3 TB dataset from lz4 to zstd-19, with practically nothing else happening on the box. Here is the resource usage reported by `top`:

```
load average: 106.36, 103.88, 106.02

%Cpu(s):  0.0 us, 72.6 sy,  0.0 ni, 20.6 id,  6.4 wa,  0.0 hi,  0.3 si,  0.0 st
GiB Mem :    125.9 total,    108.6 free,     16.8 used,      0.4 buff/cache
GiB Swap:     16.0 total,     15.2 free,      0.8 used.    108.3 avail Mem 
```

So nope, not currently out of memory, by a very wide margin. But then, I wasn't watching when it failed those two times. Does zstd occasionally blow up in memory usage?

**Comment by darrenfreeman** [comment]
Also @BrainSlayer it's doing 100-200 MB per *second*. I monitor this using `pv` in the pipe between send and receive.

**Comment by robszy** [comment]
add also watch for free to monitor memory

**Comment by darrenfreeman** [comment]
Note the recordsize is left at the default 128 KiB on source and destination, so it's not really compressing 100 MB in a second, it's compressing 800 records in a second.

**Comment by darrenfreeman** [comment]
That send/recv completed, output of pv:

```
3.06TiB 9:41:22 [91.8MiB/s]
```

**Comment by ahrens** [comment]
The symptoms seem identical to https://github.com/openzfs/zfs/issues/12001 and https://github.com/openzfs/zfs/issues/12270, which don't use zstd.  So I don't see any evidence that this is specific to ZSTD.

I'm going to mark zstd-specific comments as offtopic.  Polite suggestions for how to improve ZSTD are welcome in other (perhaps new) issues.

**Comment by darrenfreeman** [comment]
The second hang, above, showed that a snapshot was being received via syncoid. And this snapshot was the one with the "permanent" error in its partially received state. I have just transferred a large single snapshot, without a hang. Syncoid was not running, and the send/recv was not incremental. Now going to reinstate sanoid and syncoid.

**Comment by ahrens** [comment]
There are a few places that can return EIO in this path.  

Can you try reproducing with SET_ERROR tracing enabled, `$ echo 512 >/sys/module/zfs/parameters/zfs_flags` (see `__set_error()`) and then gather zfs_dbgmsg after reproducing (`cat /proc/spl/kstat/zfs/dbgmsg`, or by using `sdb` on the crash dump).  

It might also be helpful to see `zpool history -i` (at least the last few hundred lines, that might be relevant to this dataset).  

Let's also get all the properties involved, `zfs get all pool/source pool/dest`.
