### ISSUE TITLE
Can't create a zpool with a file vdev with latest pool version (0.6.0-rc14)

### ISSUE THREAD

**Issue by sparisot** [openzfs/zfs#1280]
With ZOL 0.6.0-rc14, I can't create a zpool with a file vdev anymore :

```
# zpool create toto /tmp/d
cannot create 'toto': invalid argument for this pool operation
# echo $?
1
#
```

With an older pool version (so without feature flags) it works fine :

```
# zpool create -o version=28 toto /tmp/d
#
```

/tmp/d is :

```
dd if=/dev/zero of=/tmp/d bs=128M count=1
```

I'm using Debian Wheezy i686 (kernel 3.2.35)

**Comment by Rovanion** [comment]
Yes, it would be useful if this mismatch could be signalled to the user in some better way.
