### ISSUE TITLE
Installation order issue

### ISSUE THREAD

**Issue by Moerten85** [openzfs/zfs#12822]
I broke three fresh Fedora 34/35 installations after having installed ZFS as mentioned in your documentation here:

https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora/index.html

The command...
```
dnf install -y kernel-devel zfs
```
...causes to the following error:
```
Loading new zfs-2.1.1 DKMS files...
Building for 5.15.6-100.fc34.x86_64
**Module build for kernel 5.15.6-100.fc34.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.**

  Installieren          : zfs-2.1.1-1.fc34.x86_64                                                                                                                                                  203/204 
  Ausgeführtes Scriptlet: zfs-2.1.1-1.fc34.x86_64                                                                                                                                                  203/204 
Created symlink /etc/systemd/system/zfs-import.target.wants/zfs-import-cache.service → /usr/lib/systemd/system/zfs-import-cache.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-mount.service → /usr/lib/systemd/system/zfs-mount.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-share.service → /usr/lib/systemd/system/zfs-share.service.
Created symlink /etc/systemd/system/zed.service → /usr/lib/systemd/system/zfs-zed.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-zed.service → /usr/lib/systemd/system/zfs-zed.service.
Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target → /usr/lib/systemd/system/zfs.target.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-import.target → /usr/lib/systemd/system/zfs-import.target.
Created symlink /etc/systemd/system/zfs-volumes.target.wants/zfs-volume-wait.service → /usr/lib/systemd/system/zfs-volume-wait.service.

  Installieren          : kernel-devel-5.15.6-100.fc34.x86_64                                                                                                                                      204/204 
  Ausgeführtes Scriptlet: kernel-devel-5.15.6-100.fc34.x86_64                                                                                                                                      204/204 
  Ausgeführtes Scriptlet: zfs-2.1.1-1.fc34.x86_64                                                                                                                                                  204/204 
  Ausgeführtes Scriptlet: kernel-devel-5.15.6-100.fc34.x86_64   
```
But as you can see this will fail because the kernel-devel becomes installed after ZFS. Thus the ZFS installation fails. And WHY THE HELL is this important information that the installation failed NOT MARKED RED so everyone can see this within this 100drets of terminal lines. I installed Fedora now for the third time not having seen this message before and wondering about the following error when executing modprobe:
```
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.15.6-100.fc34.x86_64
```
I wasted a hole day on getting ZFS working again now and moved back to Fedora 34 finally because it is not working with Fedora 35 anymore. So PLEASE update the documentation or even better the install routine if possible. I am getting to old for this linux frickelzeug.

**Comment by Moerten85** [comment]
Yeah it's like I said. I did a
```
dnf remove ZFS
```
and
```
dnf install -y kernel-devel zfs
```
again -> Same error as before. Then I did the following
```
dnf install -y kernel-devel
dnf install -y ZFS
```
with separated calls and it worked. Unbelievable. AM I THE FIRST PERSON INSTALLING ZFS OR WHAT!

**Comment by Moerten85** [comment]
PS: I am wondering why kernel-devel is not a dependency of the ZFS package. You can install ZFS without kernel-devel what will fail for sure.

**Comment by svde** [comment]
kernel-devel is required by zfs-dkms:

```
$ rpm -qR zfs-dkms-2.1.1-1.fc34.noarch | grep kernel
kernel-devel >= 3.10
kernel-devel <= 5.14.999
```

To be safe, install kernel-devel first (as you already mentioned).

**Comment by tyll** [comment]
@behlendorf as I mentioned in my previous comment, this does not look like a documentation issue but incorrect dependency declarations in the spec file dnf/yum is capable of ensuring that packages are installed in the correct order when it gets the correct information.

**Comment by tyll** [comment]
@behlendorf please see #12832

**Comment by behlendorf** [comment]
@tyll that's for the fix.  I didn't mean to imply this was solely a documentation issue, just that the related documentation should also be revisited.  I've also gone ahead and opened #12833 to track some additional warnings I observed when installing the packages.
