### ISSUE TITLE
Linux 5.15 compatibility

### ISSUE THREAD

**Issue by hmenke** [openzfs/zfs#12847]
### Describe the feature would like to see added to OpenZFS

Please make a release with the Linux 5.15 compatibility patches merged in and
```
Linux-Maximum: 5.15
```
in `META`. Right now some downstream consumers like the NixOS Linux distributions are in limbo because 5.14 is EOL and is being removed and 5.15 is not yet supported by ZFS.

In general the downstream consumers would appreciate a more timely release of the compatibility patches. Thanks in advance.

### How will this feature improve OpenZFS?

Easier integration for rolling-release bleeding-edge Linux distributions.

### Additional context

https://github.com/NixOS/nixpkgs/issues/150517

**Comment by Mic92** [comment]
There are no patches required to get 5.15 running. You just need to bump `META` actually.

**Comment by snowsnoot** [comment]
Just a note on something to watch out for. On FC34, dnf autoupdate last night upgraded my kernel to from 5.15.6 to 5.15.7 and in the process removed zfs, zfs-dkms, zfs-dracut and zfs-test from my system, replacing it with zfs-fuse from the Feodra repos. Now I can't run any zfs related commands but the pool still runs OK.

```
================================================================================
 Package              Arch       Version                Repository         Size
================================================================================
Installing:
 kernel               x86_64     5.15.7-100.fc34        updates            14 k
 kernel-core          x86_64     5.15.7-100.fc34        updates            35 M
 kernel-devel         x86_64     5.15.7-100.fc34        updates            15 M
 kernel-modules       x86_64     5.15.7-100.fc34        updates            32 M
Upgrading:
 libjcat              x86_64     0.1.9-1.fc34           updates            71 k
 rust-srpm-macros     noarch     20-1.fc34              updates           9.2 k
Installing dependencies:
 zfs-fuse             x86_64     0.7.2.2-18.fc34        fedora            1.5 M
Removing:
 kernel               x86_64     5.14.13-200.fc34       @updates            0  
 kernel-core          x86_64     5.14.13-200.fc34       @updates           76 M
 kernel-devel         x86_64     5.14.13-200.fc34       @updates           60 M
 kernel-modules       x86_64     5.14.13-200.fc34       @updates           31 M
Removing dependent packages:
 zfs                  x86_64     2.1.1-1.fc34           @@commandline     1.6 M
 zfs-dkms             noarch     2.1.1-1.fc34           @@commandline      62 M
 zfs-dracut           noarch     2.1.1-1.fc34           @@commandline      39 k
 zfs-test             x86_64     2.1.1-1.fc34           @@commandline      30 M

Transaction Summary
================================================================================
Install  5 Packages
Upgrade  2 Packages
Remove   8 Packages
```

**Comment by amarshall** [comment]
@snowsnoot To prevent it from unexpectedly happening in the future, can run e.g. `echo zfs | sudo tee /etc/dnf/protected.d/zfs.conf` to mark the package as protected. See [docs](https://dnf.readthedocs.io/en/latest/conf_ref.html#protected-packages-label).

**Comment by Atemu** [comment]
2.1.2 is out: https://github.com/openzfs/zfs/releases/tag/zfs-2.1.2

**Comment by Mic92** [comment]
Right, this one can be closed.
