### ISSUE TITLE
zdb gets confused by datasets starting with numbers

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#12845]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11
Kernel Version	| 5.10.0-9-amd64
Architecture	| x86_64
OpenZFS Version	| c9d62d135 or so

### Describe the problem you're observing
(I'll go figure out a "correct" handling for this later, I just wanted to mention it in case I forgot after I ran into it...)

I tried to examine a child dataset under a dataset named "1M", at the top of a pool, "lz4newtestpool".
```
# sudo zdb -dbdbdbdbdbdb lz4newtestpool/1M/largefiles 256
failed to hold objset 1: Invalid argument
zdb: can't open 'lz4newtestpool/1M/largefiles': Invalid argument
```

But if I rename 1M to sigh1M, it works as expected.

I would presume this is due to:
https://github.com/openzfs/zfs/blob/510885a84ce85a484cc228066e97d8c61717d414/cmd/zdb/zdb.c#L8525-L8539

since patching the second check to not exit(1) and reset objset_id to -1 allows us to proceed, albeit having printed the error.

### Describe how to reproduce the problem
`sudo zdb -d pool/1zzz`

### Include any warning/errors/backtraces from the system logs
GOTO 10

**Comment by PaulZ-98** [comment]
It turns out that the -d <pool>/dataset | objsetID is not going to be a good zdb command line interface for using the numeric objset id, for the reason you're seeing.

I had originally done
```
zdb tank -N 236:2.   (objset:object)
```
but we didn't go with that.  Now we have objectID ranges to consider if we adopt a ":" separator.  Ideas welcome.

**Comment by rincebrain** [comment]
I'd probably opt for a variant of that, really - something like `zdb tank -N 236 [object or range[,...]]`, since I don't think it's ever currently legal to specify multiple datasets no matter how you phrase it, and if it were, then we could (ew) go for positional-based parsing where it affects later arguments?

I'd still prefer it if the existing logic did something like "try as path name" => "if it fails, try as objsetid", and then you can unambiguously specify it if you need to? (Mostly in that order because I think people are more likely to run into the case of "I have a dataset named 100 and want to reference it when there's an objsetid 100" than "I have an objsetid 100 and there's a dataset named 100 i wanted to reference instead".)

**Comment by PaulZ-98** [comment]
Let me try to get the "try as dataset name" => "if it fails and (if numeric looking), try as objsetID" working.
