### ISSUE TITLE
Setting zfs properties when pool under load takes a very long time

### ISSUE THREAD

**Issue by Anteros5** [openzfs/zfs#12855]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 9 and 10
Kernel Version	| 4.19.0-x
Architecture	| amd64
OpenZFS Version	| 0.8.4 -0. 2.1

### Describe the problem you're observing

When a slower pool made of hdds (didn't quite observe this with an ssd one) is under heavier load (for example with zfs send that's sending data away from that pool) changing zfs properties via "zfs set" can take anywhere from 5 to 50 seconds per property.

I'm not certain if that is a valid behavior or not, as the operation itself doesn't seem like one that would be very I/O intensive from what I can tell, but it makes creating zvols with number of properties a very lengthy endeavor on hdd pools under load.

### Describe how to reproduce the problem
I've been able to reproduce the issue on a number of servers running various versions of ZFS from 0.8.x to 2.1.0 on debian 9 and 10.
Simply creating a snapshot of a zvol with data located on a hdd pool and initiating zfs send of it to an adjacent ssd pool will make any "zfs set" operation on the hdd pool zvols take a very long time (my results varied from 5 to 50 seconds depending on the server)

**Comment by GregorKopka** [comment]
Piping something like a `| pv -L 3k|` into the send|recv pipe could maybe show if this stems from a load or a locking issue.

**Comment by Anteros5** [comment]
I've done that before while testing the behavior, usually slowing the send via pv would reduce the amount of time required to set a property, the bigger the throttling the faster the set would be (altho still quite slow unless throttled very very heavily)
