### ISSUE TITLE
zpool iostat shows wrong cumulative stats

### ISSUE THREAD

**Issue by dani** [openzfs/zfs#12866]
From the zpool-iostat man page, zpool iostat command starts by displaying cumulative (since boot) stats, no matter if we add an interval and a count arg. It's not the case. I don't know what the first value is coming from, but it clearly isn't cumulative since boot.

Here I'm running a first time zpool iostat on my zpool pool. It first shows a cumulative read count of 64 (which clearly is wrong, but lets pretend it's OK), then for the next 5 sec, it shows around 100 read/sec

```
root@pbs:~# zpool iostat zpool -pH 1 5
zpool   1483556872192   509307953152    64      12      281656  308598
zpool   1483556872192   509307953152    128     47      527325  2595750
zpool   1483562782720   509302042624    94      155     388304  6364099
zpool   1483562782720   509302042624    121     0       580126  0
zpool   1483562782720   509302042624    101     0       416897  0
root@pbs:~# 
```

Now lets run it again
```
root@pbs:~# zpool iostat zpool -pH 1 5
zpool   1483586248704   509278576640    64      13      285592  332480
zpool   1483586248704   509278576640    90      0       372035  0
zpool   1483586248704   509278576640    120     0       575921  0
zpool   1483586248704   509278576640    120     247     494535  5742332
zpool   1483580772352   509284052992    105     34      596563  351400
root@pbs:~#
```

The initial value (which should be cumulative) is still showing 64, while it should be at least 64+128+94+121+101 (508). Similar issue affect the bandwidth values. Eg, here I run two zpool iostat command in a row
```
root@pbs:~# zpool iostat zpool -pH
zpool   1484181708800   508683116544    64      23      287254  590925
root@pbs:~# zpool iostat zpool -pH
zpool   1484181708800   508683116544    64      23      287190  590794
root@pbs:~# 
```

The second output shows inferior values for bandwisth read and write, which shouldn't be possible if they were cumulative.

This is running ZFS 2.1.1 on Debian Bullseye with a 5.13.19 kernel (it's a Proxmox Backup Server, which is based on Debian Bullseye with a more recent kernel)

**Comment by IvanVolosyuk** [comment]
Both reads/writes and bandwidth are values per second. The more time passes the larger denominator. If your pool is idle the values can go down.
The cumulative here means average since boot. It works similar to 'iostat' linux command.

**Comment by dani** [comment]
OK my bad, my understanding was it should be cumulative since boot, but with average, I just have to multiply those values with the uptime in seconds to get the values I'm interested in. Thanks.
