### ISSUE TITLE
Cannot destroy: dataset is busy on empty unused dataset

### ISSUE THREAD

**Issue by jdeluyck** [openzfs/zfs#12881]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox (Debian)
Distribution Version	| Stable - 11.2
Kernel Version	|  5.13.19-2-pve
Architecture	| amd64
OpenZFS Version	| 2.1.1

### Describe the problem you're observing
I've created a bunch of datasets, but one of them is stuck: I can't delete it, no matter what I do. I can mount/umount it, but not delete it.
I've tried rebooting, but that doesn't help.

Today I had the same issue on another dataset, and there I tried renaming the dataset, after which I was able to delete it.

`fuser` does not report any open files in this dataset.

### Describe how to reproduce the problem
Uncertain

### Include any warning/errors/backtraces from the system logs
```
# zfs destroy rpool/nas/docker/volumes/sonarr-media
cannot destroy 'rpool/nas/docker/volumes/sonarr-media': dataset is busy
```

**Comment by AllKind** [comment]
Try `grep sonarr-media /proc/*/mounts` to find the process keeping the dataset busy.

**Comment by jdeluyck** [comment]
Argh. Ok, that was incredibly stupid. A docker container that has r/o rights on a parent dataset also locked this dataset somehow. And ofcourse that doesn't show up in fuser as to why. Thanks @AllKind .
