### ISSUE TITLE
loop mounting images broken with kernel 5.16

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#12926]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| ubuntu 
Distribution Version	| jammy
Kernel Version	| [5.16.0-051600-generic](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/) 
Architecture	| x86_64
OpenZFS Version	| 2.1.2

### Describe the problem you're observing

Reading from a loop device fails with a `can't read superblock` error.
Snap is broken for the same reason.
Creating a loop device from a file on a zpool succeeds, but reading from it throws errors.

### Describe how to reproduce the problem

This fails:
```
cd <folder on zpool>
dd if=/dev/zero of=file bs=1k count=1000
# remove existing loop mount
losetup -d /dev/loop0 || true
losetup /dev/loop0 file
mkfs -t ext4 /dev/loop0 # This fails
mount -t ext4 /dev/loop0 /mnt
```
I get this error:
```
mkfs -t ext4 /dev/loop0
mke2fs 1.46.5 (30-Dec-2021)

Filesystem too small for a journal
Discarding device blocks: done
Warning: could not erase sector 2: Input/output error
Creating filesystem with 250 4k blocks and 128 inodes

Allocating group tables: done
Warning: could not read block 0: Input/output error
Warning: could not erase sector 0: Input/output error
Writing inode tables: done
ext2fs_write_inode_full: Input/output error while writing reserved inodes
```

Trying the same on a file in an xfs mount succeeds.
```
mkfs -t ext4 /dev/loop0
mke2fs 1.46.5 (30-Dec-2021)

Filesystem too small for a journal
Discarding device blocks: done
Creating filesystem with 250 4k blocks and 128 inodes

Allocating group tables: done
Writing inode tables: done
Writing superblocks and filesystem accounting information: done
```

**Comment by mikroskeem** [comment]
Unable to reproduce on 5.15.x at least.

More details:

Type | Version/Name
-- | --
Distribution Name | NixOS
Distribution Version | nixos-21.11.334921.8588b14a397
Kernel Version | `5.15.11 #1-NixOS`
Architecture | x86_64
OpenZFS Version | 2.1.2

**Comment by satmandu** [comment]
The issue only arose for me once I went from 5.15-> 5.16.

**Comment by mikroskeem** [comment]
Though I just noticed this in dmesg:
```
[77126.695434] blk_update_request: operation not supported error, dev loop0, sector 4194176 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
[77126.695527] blk_update_request: operation not supported error, dev loop0, sector 2312 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
[77126.695662] blk_update_request: operation not supported error, dev loop0, sector 67888 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
[77126.696273] blk_update_request: operation not supported error, dev loop0, sector 2097152 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
```

I made 2G file using `truncate` and did `mkfs.ext4`.

**Comment by satmandu** [comment]
FYI I'm not seeing an issue when booted into 5.15.13.

**Comment by satmandu** [comment]
Confirming that this is still an issue with zfs 2.1.2 on the final 5.16.0 kernel.

**Comment by satmandu** [comment]
Sadly, there was no difference when building the kernel and module with `gcc-10` on ubuntu 20.04.

**Comment by satmandu** [comment]
Here is what I see in dmesg: 
```
[ 1311.279962] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[ 1311.279992] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.279997] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.280016] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.280019] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.280032] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.280035] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.280047] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.280050] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.280063] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.280066] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.308431] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[ 1311.308454] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.308458] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.310497] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.310502] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.310519] I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 1311.310521] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.310536] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1311.310554] Buffer I/O error on dev loop0, logical block 0, async page read
[ 1314.899858] loop: Write error at byte offset 917504, length 4096.
[ 1314.899968] loop: Write error at byte offset 139264, length 4096.
```

**Comment by satmandu** [comment]
My guess would be that changes in https://github.com/torvalds/linux/commit/47e9624616c80c9879feda536c48c6a3a0ed9835 are causing the problem.

**Comment by satmandu** [comment]
And it looks like loop mounting on zfs volumes being broken by kernel updates has been fixed with prior patches: https://github.com/openzfs/zfs/commit/5475aada9474464f973788c1b2fc6216486fb303

**Comment by behlendorf** [comment]
This appears to be caused by the loopback driver using the fallocate `FALLOC_FL_ZERO_RANGE ` flag which is not supported.  ZFS reports the flag as unsupported, and the error is logged to the console, but the loopback drive appears to carry on regardless.

```
blk_update_request: operation not supported error, dev loop0, sector ... op 0x9:(WRITE_ZEROES) flags 0x800800 ...
``` 

There are some other filesystems, like tmpfs, which also don't support `FALLOC_FL_ZERO_RANGE` so I expect you'd see the same behavior there using a loopback device.  @satmandu if you have a 5.16.0 kernel handy would you mind checking that behavior for me?

It sure does look like torvalds/linux@47e9624 was inadvertently responsible for this issue.  By retiring the xor transfer code we're now using the aio handlers.  The best fix here would really be to add support for `FALLOC_FL_ZERO_RANGE` to `zpl_fallocate_common()`.  It seems to me we really should be able to treat this the same way a `FALLOC_FL_PUNCH_HOLE`.

**Comment by satmandu** [comment]
I'm not seeing an error creating a tmpfs filesystem off of a zfs root on 5.16, but that could just be a special case.

This gives no errors:
```
mkdir /tmptest
mount -t tmpfs -o size=100m,mode=1777 tmptest /tmptest
dmesg > /tmptest/dmesg
cat /tmptest/dmesg
```

**Comment by satmandu** [comment]
Interestingly or not, with the changes in https://github.com/openzfs/zfs/pull/12975  (which don't have any changes to support `FALLOC_FL_ZERO_RANGE`)`mkfs` of a loop fs succeeds, but mount of the loopback fs fails, giving this error on `5.16.1-051601-generic`:
```
[  165.041508] operation not supported error, dev loop0, sector 1792 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
[  165.041638] operation not supported error, dev loop0, sector 272 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
[  165.041788] operation not supported error, dev loop0, sector 88 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0
```

**Comment by rincebrain** [comment]
So, as you say, I get those operation not supported complaints in dmesg, but unlike you, mounting seems to work fine?

```
$ sudo truncate -s 500M /meowpool/tryme/boom
$ sudo losetup -f /meowpool/tryme/boom
$ losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE            DIO LOG-SEC
/dev/loop0         0      0         0  0 /meowpool/tryme/boom   0     512
$ sudo mkfs.ext4 /dev/loop0
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: f15263b5-b3e9-4014-b2c6-36ab16e075b4
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

$ sudo mount /dev/loop0 /mnt2/
$ sudo cp -a . /mnt2/
cp: error copying './module/zfs/zfs.o' to '/mnt2/./module/zfs/zfs.o': No space left on device
cp: error copying './module/zfs/zfs.mod.o' to '/mnt2/./module/zfs/zfs.mod.o': No space left on device
[etc]
```

(I originally tried with a larger file and that works fine, but I wanted to try smaller and see if that was related to your issue...)

**Comment by rincebrain** [comment]
(With #12975 applied)

```
$ sudo zpool create sparsepool /sp -O compression=lz4
$ sudo zfs create sparsepool/testme
$ sudo truncate -s 1G /sparsepool/testme/1
$ sudo losetup -f /sparsepool/testme/1
$ sudo losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                        DIO LOG-SEC
/dev/loop1         0      0         1  1 /var/lib/snapd/snaps/bare_5.snap                   0     512
/dev/loop6         0      0         1  1 /var/lib/snapd/snaps/snapd_14295.snap              0     512
/dev/loop4         0      0         1  1 /var/lib/snapd/snaps/gtk-common-themes_1519.snap   0     512
/dev/loop2         0      0         1  1 /var/lib/snapd/snaps/firefox_863.snap              0     512
/dev/loop0         0      0         1  1 /var/lib/snapd/snaps/core20_1270.snap              0     512
/dev/loop7         0      0         0  0 /sparsepool/testme/1                               0     512
/dev/loop5         0      0         1  1 /var/lib/snapd/snaps/snap-store_558.snap           0     512
/dev/loop3         0      0         1  1 /var/lib/snapd/snaps/gnome-3-38-2004_87.snap       0     512
$ sudo mkfs.ext4 /dev/loop7
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done
Creating filesystem with 262144 4k blocks and 65536 inodes
Filesystem UUID: ba31f861-0d9b-40c6-816e-cfce9c67b00e
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

$ sudo mkdir /mnt2
$ sudo mount /dev/loop7 /mnt2
$ ls
aclocal.m4          configure.ac                                               libuutil3_2.1.99-686_amd64.deb      python3-pyzfs_2.1.99-686_amd64.deb  zfs_config.h
aclocal.m4~         contrib                                                    libzfs5_2.1.99-686_amd64.deb        README.md                           zfs_config.h.in
AUTHORS             copy-builtin                                               libzfs5-devel_2.1.99-686_amd64.deb  RELEASES.md                         zfs_config.h.in~
autogen.sh          COPYRIGHT                                                  libzpool5_2.1.99-686_amd64.deb      rpm                                 zfs-dracut_2.1.99-686_amd64.deb
bin                 COPYRIGHT~                                                 LICENSE                             scripts                             zfs-initramfs_2.1.99-686_amd64.deb
build               etc                                                        Makefile                            sendfile                            zfs-kmod-2.1.99-686_ga2678ac5e.src.rpm
cmd                 include                                                    Makefile.am                         stamp-h1                            zfs.release
CODE_OF_CONDUCT.md  kmod-zfs-5.16.1-051601-generic_2.1.99-686_amd64.deb        Makefile.in                         TEST                                zfs.release.in
config              kmod-zfs-devel_2.1.99-686_amd64.deb                        man                                 tests                               zfs-test_2.1.99-686_amd64.deb
config.log          kmod-zfs-devel-5.16.1-051601-generic_2.1.99-686_amd64.deb  META                                udev
config.status       lib                                                        module                              zfs_2.1.99-686_amd64.deb
configure           libnvpair3_2.1.99-686_amd64.deb                            NEWS                                zfs-2.1.99-686_ga2678ac5e.src.rpm
configure~          libtool                                                    NOTICE                              zfs-2.1.99.tar.gz
$ sudo cp -a . /mnt2/
$ uname -a
Linux ubuntu2204 5.16.1-051601-generic #202201160933 SMP PREEMPT Sun Jan 16 09:39:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

(I also tried with explicitly using dd instead of truncate, and with compression=off - made no difference.)

**Comment by rincebrain** [comment]
Well, that was easy.

```
before:
$ sudo fallocate -v -z -o 1048576 -l 12800000 bees
fallocate: fallocate failed: Operation not supported
$ du -sh bees
101M	bees

after:
$ sudo fallocate -v -z -o 1048576 -l 12800000 bees
$ du -sh bees
88M     bees
          100000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          120000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          140000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          160000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          180000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          1a0000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          1c0000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          1e0000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          200000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
          220000  L0 HOLE [L0 ZFS plain file] size=20000L birth=68652L
[etc]
                segment [0000000000000000, 0000000000100000) size    1M
                segment [0000000000d20000, 0000000006400000) size 86.9M
```

**Comment by satmandu** [comment]
https://github.com/openzfs/zfs/pull/12975 now fixes this issue for me.

Hopefully, https://github.com/openzfs/zfs/pull/12975 will get pushed to a tagged release at some point soon so I can bug the debian/ubuntu people about trying to put out a release that includes 2.x ! (And yes it would be nice if ubuntu's LTS this year got zfs 2.x but of course, that's out of scope for this issue.)

**Comment by RJVB** [comment]
> Confirming that this is still an issue with zfs 2.1.2 on the final 5.16.0 kernel.

I think it is too on 5.15.95 (with ZFS 2.1.2) :(

**Comment by satmandu** [comment]
This is not an issue on newer kernels such as 6.5.x with the released OpenZFS 2.2.0...

**Comment by RJVB** [comment]
> This is not an issue on newer kernels such as 6.5.x with the released OpenZFS 2.2.0...

You'd hope not, no, not for an issue marked resolved. But not everyone runs the latest-and-supposedly-greatest.

**Comment by rincebrain** [comment]
This is fixed since 2.1.3 and in 2.2.0.

Saying "still an issue on the version it was originally reported on" is not constructive.

If you're going to run a version from 2021, your options are to cherrypick the fix from the future, or make whoever is making you run that version do it.

**Comment by behlendorf** [comment]
The fix for this was also included in the 2.1 releases as of v2.1.3.

**Comment by RJVB** [comment]
> This is fixed since 2.1.3 and in 2.2.0.
> 
> Saying "still an issue on the version it was originally reported on" is not constructive.

Except I wasn't: the original report was about 5.16 and at least 1 comment claims the issue didn't exist on 5.15 .

I did just apply #12975 and the image with an XFS fs on it that works fine under kernel 5.6 and earlier continues to give me the same error. (Yes, I did rebuild my initrd...)
Is there an additional commit that I need to backport?

**Comment by RJVB** [comment]
```
> sudo /opt/local/bin/gdd if=/dev/zero of=/var/cache/test.img bs=1M count=512
512+0 records in
512+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 0.361218 s, 1.5 GB/s

> sudo losetup -v -f /var/cache/test.img
Loop device is /dev/loop0

> sudo mkfs.xfs -L test /dev/loop0
meta-data=/dev/loop0             isize=512    agcount=4, agsize=32768 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=0
data     =                       bsize=4096   blocks=131072, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=855, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mkfs.xfs: pwrite64 failed: Unknown error -5
```

**Comment by behlendorf** [comment]
@RJVB if possible I'd encourage you to update to the 2.1.3 release (or newer).  This was the first official release to support the 5.16 kernel and includes all of the required kernel compatibility changes.  If you must use a 5.16 kernel with custom patched 2.1.2 you'll need to cherry pick all of the "Linux x.y compat" changes between [2.1.2 and 2.13](https://github.com/openzfs/zfs/compare/zfs-2.1.2...zfs-2.1.3) found in the [release notes](https://github.com/openzfs/zfs/releases/tag/zfs-2.1.3).  As well as 8ef01afbfc.

**Comment by RJVB** [comment]
On Friday October 20 2023 15:41:38 Brian Behlendorf wrote:
> If you must use a 5.16 kernel with custom patched 2.1.2 you'll need to cherry pick all of the "Linux x.y compat" changes between [2.1.2 and 2.1.3]

Again, this is with 5 dot FIFteen, not 16... 

But, supposing I do create patches for all those compat changes (easy enough with PATCH[i] lines in dkms.conf), will those interfere with the kmod on earlier kernel versions?

**Comment by RJVB** [comment]
Anyway, I'm going to try to update my ZFS packages to something newer too. I was hoping to do that sometime after the kernel upgrade but maybe it'll take me less time & effort this time... I think my Devuan "Chimaera" install is on 2.1.11, I suppose that version should do?

**Comment by behlendorf** [comment]
@RJVB it looks like 4372e96f4b4b21c8e79c0c961589f61b11859e07 and b657f2c59220dba92607aa253ed2a6a1f6d9bec8 should be enough to resolve this.  Anything 2.1.3 or newer will include these changes and should be fine.

**Comment by RJVB** [comment]
Thanks, but I had already upgraded my packaging to the 2.1.11 build that's in Devuan Chimaera (a "modest" upgrade but I'd already been using that version). I can confirm the issue is solved.

Now I'm just wondering if I have a compelling reason to update everywhere ;)
