### ISSUE TITLE
zpool_influxdb not installed when building ZFS 2.1.2 DKMS

### ISSUE THREAD

**Issue by remingtonc** [openzfs/zfs#12960]
### Discussed in https://github.com/openzfs/zfs/discussions/12945
Moving to issue given documentation built, but no package installed, feels suspect. Hopefully a simple build issue in my methodology.

<div type='discussions-op-text'>

<sup>Originally posted by **remingtonc** January  7, 2022</sup>
Hi all! Installing ZFS 2.1.2 on Ubuntu 20.04 via instructions with DKMS: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#dkms-1

```
$ sudo apt-get install dkms
$ cd zfs
$ ./configure --enable-systemd
$ make -j1 deb-utils deb-dkms
$ for file in *.deb; do sudo gdebi -q --non-interactive $file; done
```

`zpool_influxdb` does not install with this methodology. Am I missing something in getting this utility built?

The documentation is present at least..
```
remingtonc@r8-n10:/tmp$ ls /usr/share/man/man8/ | grep infl
zpool_influxdb.8.gz
```
</div>

**Comment by rincebrain** [comment]
I admittedly do not have 2.1.x laying around installed, but on git master:
```
$ dpkg -S /usr/libexec/zfs/zpool_influxdb
zfs: /usr/libexec/zfs/zpool_influxdb
```

So dpkg -L zfs doesn't report zpool_influxdb being installed?

**Comment by remingtonc** [comment]
Ah this is a very nifty command:
```
remingtonc@r8-n10:~$ dpkg -L zfs | grep influxdb
/usr/lib/x86_64-linux-gnu/zfs/zpool_influxdb
/usr/share/man/man8/zpool_influxdb.8.gz
```
Looks like it was installed in `/usr/lib/x86_64-linux-gnu/zfs/` which I was not expecting. I should have run a find. Thank you for your assistance.
