### ISSUE TITLE
Unending numbers of checksum errors sometimes

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#12962]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.3
Kernel Version	| 5.11.0-27-generic
Architecture	| x86_64
OpenZFS Version	| 2.0.7

### Describe the problem you're observing
On a test raidz1, ashift=9, made of two partitions on a 1TB USB3 SSD and a 500 GB 512e USB3 spinning hard drive, I noticed that during scrub, I'll get back checksum errors seemingly at random - always blamed on the 500GB disk, continuing to recur after scrubbing to completion with none unrecoverable, and always with output like this in `zpool events`:
```
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0x4 0x22 0x2b 0x19 0x1c 0x17 0x1c 0x19 0x4 0x27 0x2a 0x11 0x19 0x18 0x1a 0x20 0x6 0x26 0x34 0x11 0x11 0x19 0x17 0x1b 0x3 0x28 0x30 0x10 0x16 0x1c 0x17 0x1d 0x4 0x24 0x31 0xf 0x1a 0x19 0x19 0x1f 0x6 0x22 0x2f 0x10 0x1b 0x1a 0x17 0x1a 0x6 0x26 0x2d 0x10 0x13 0x1b 0x14 0x1a 0x4 0x1f 0x2c 0x19 0x16 0x21 0x1d 0x17
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0xe 0x12 0x12 0x19 0x15 0x17 0x1b 0x1b 0x11 0xd 0x15 0x14 0x18 0x21 0x21 0x1a 0x12 0x15 0x13 0x17 0x1a 0x18 0x1d 0x1d 0x11 0xf 0x12 0x18 0x25 0x24 0x25 0x21 0x18 0x17 0x13 0x25 0x1b 0x1f 0x1d 0x17 0x10 0x10 0x18 0x20 0x19 0x1a 0x18 0x1d 0x12 0xd 0x16 0x18 0x14 0x1d 0x1a 0x19 0xc 0x11 0x15 0x1b 0x1f 0x1f 0x18 0x17
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0x13 0x15 0x14 0x1c 0x1c 0x1b 0x1b 0x19 0x13 0x10 0x16 0x1e 0x19 0x16 0x19 0x15 0x14 0x1b 0x20 0x21 0x1e 0x1e 0x1b 0x19 0x18 0x16 0x19 0x1a 0x1f 0x1b 0x22 0x23 0x14 0x15 0x15 0x1c 0x1a 0x1c 0x16 0x17 0x11 0x16 0x11 0x16 0x12 0x16 0x18 0x1a 0x17 0x13 0x17 0x17 0x1b 0x1e 0x1e 0x1b 0x15 0x14 0x16 0x16 0x1d 0x21 0x1a 0x1c
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0x18 0x16 0x15 0x21 0x1d 0x20 0x1e 0x1b 0x1a 0x13 0x18 0x1d 0x15 0x1d 0x1b 0x12 0xc 0x13 0x11 0x1b 0x1a 0x1a 0x17 0x14 0xf 0x12 0x12 0x14 0x13 0x1c 0x15 0x19 0xc 0x12 0x11 0x19 0x1c 0x1e 0x24 0x1d 0x14 0x14 0x1d 0x19 0x1c 0x1d 0x20 0x16 0x11 0x12 0x17 0x22 0x18 0x1c 0x20 0x1f 0x18 0x12 0x1c 0x19 0x17 0x20 0x1d 0x23
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0xf 0xf 0x19 0x18 0x20 0x1b 0x1d 0x18 0xf 0x14 0xf 0x1d 0x1c 0x1e 0x21 0x1a 0x14 0x17 0x12 0x1f 0x1f 0x23 0x1a 0x16 0xc 0x14 0x16 0x14 0x1d 0x17 0x1b 0x20 0x1a 0x14 0x19 0x19 0x11 0x1c 0x14 0x1e 0x11 0x14 0x19 0x18 0x16 0x20 0x1b 0x1d 0xe 0x15 0x16 0x1e 0x1a 0x1b 0x1c 0x1f 0x19 0x15 0x22 0x20 0x15 0x19 0x1a 0x19
        bad_set_histogram = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
        bad_cleared_histogram = 0x6 0x1c 0x1d 0xb 0xd 0x16 0x12 0x16 0x3 0x11 0x26 0xc 0x9 0x17 0xc 0x16 0x2 0x1a 0x1d 0x12 0x9 0x18 0x15 0x16 0x1 0x14 0x23 0x11 0xd 0x13 0x13 0x18 0x6 0x17 0x1c 0xc 0x14 0x17 0x11 0x17 0x3 0x15 0x20 0x12 0x11 0x1a 0x19 0x14 0x3 0x14 0x21 0x15 0xf 0x16 0x12 0x16 0x5 0x14 0x1c 0xd 0xd 0x16 0x17 0x19
```

The machine has another pool, made of a 3-way mirror of 3 spinning USB disks, which does not suffer from this problem.

Someone on IRC reported very similar behavior on their end a couple days ago to me, with always bad_cleared_histogram and never bad_set_histogram, and someone on Slack chimed in saying they saw similar, but they were both using much larger SAS topologies with real controllers, and the former was using mirrors.

The other person was also using 2.1.1 and still had it happening even when they swapped the disks reporting them out for spares, so...

### Describe how to reproduce the problem
???

Suspicious it might have to do with the 500GB being much slower, but might just be coincidence. Will continue to experiment and report back.

### Include any warning/errors/backtraces from the system logs
? None logged in dmesg, dbgmsg just contains debug prints I added confirming that yes, it's erroring on that disk every time, and the checksum really is wrong.

**Comment by mcmilk** [comment]
I could write some checksum verify tool which can go into tests/functional/checksums... all assembly types may need some more checking I think.
This includes the fltcher*() routines, the raidz routines and the cryptographic ones.

**Comment by rincebrain** [comment]
I haven't updated the bug, but it's not ZFS doing something wrong here, I should close it unless one of the other people wants to assert theirs isn't wrong.

(My problem turns out to be the disk was doing weird things in error state and for some reason on this one system, not...reporting errors up the USB stack? It sure does on others though.)
