### ISSUE TITLE
udev race condition?

### ISSUE THREAD

**Issue by rilott** [openzfs/zfs#12966]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| 
Kernel Version	| 5.10.51
Architecture	| x86_64
OpenZFS Version	| 2.1.1-1

### Describe the problem you're observing
On boot my pool is not imported and importing takes many minutes, it seems udev is spinning on all cores fighting over symlinks.
I have 84 disks connected via two SAS HBA cards to a JBOD (so there are 2 SAS paths to each disk). I have 1 pool consisting of 7 x 12-disk raidz2 vdevs, named 'pool1'. After I've manually imported my pool, zpool status output doesn't look great (I created all vdevs using the wwn initially, I accept that multipath shenanigans might result in the following output, I might look at multipathd and replace all these with equivilent mpath names (multipathd also has issues with udev as a result of this)):

```
        NAME                                           STATE     READ WRITE CKSUM
        pool1                                          ONLINE       0     0     0
          raidz2-0                                     ONLINE       0     0     0
            wwn-0x5000cca2c232aeb4                     ONLINE       0     0     0
            sdci                                       ONLINE       0     0     0
            sdp                                        ONLINE       0     0     0
            wwn-0x5000cca2c2335d00                     ONLINE       0     0     0
            sddj                                       ONLINE       0     0     0
            sddk                                       ONLINE       0     0     0
            wwn-0x5000cca2c23566c4                     ONLINE       0     0     0
            wwn-0x5000cca2c2367eb8                     ONLINE       0     0     0
            wwn-0x5000cca2c23546a8                     ONLINE       0     0     0
            wwn-0x5000cca2c232a634                     ONLINE       0     0     0
            wwn-0x5000cca2c27e2548                     ONLINE       0     0     0
            sdbu                                       ONLINE       0     0     0
```

### Describe how to reproduce the problem
Reboot the server

### Include any warning/errors/backtraces from the system logs

On boot I have thousands of messages in dmesg like this:
```
Dec 06 11:17:54 <> systemd-udevd[4817]: sdfh: Found 'b128:160' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4824]: sdfi: Found 'b69:240' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4655]: sdea: Found 'b65:96' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4819]: sdfg: Found 'b8:96' claiming '/run/udev/links/disk\x2fby-label\x2fpool1'
Dec 06 11:17:54 <> systemd-udevd[5266]: dm-43: Found 'b128:224' claiming '/run/udev/links/disk\x2fby-label\x2fpool1'
Dec 06 11:17:54 <> systemd-udevd[5231]: dm-40: Found 'b128:32' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4791]: sdfa: Found 'b129:192' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4791]: sdfa: Found 'b129:112' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[5288]: dm-45: Found 'b65:240' claiming '/run/udev/links/disk\x2fby-label\x2fpool1'
Dec 06 11:17:54 <> systemd-udevd[4585]: sddn: Found 'b68:240' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4625]: sddt: Found 'b129:144' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4961]: dm-16: Found 'b68:224' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[5298]: sdcu: Found 'b130:32' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[5437]: dm-53: Found 'b66:208' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[4914]: dm-10: Found 'b8:128' claiming '/run/udev/links/disk\x2fby-label\x2fpool1'
Dec 06 11:17:54 <> systemd-udevd[4757]: sdeu: Found 'b8:48' claiming '/run/udev/links/disk\x2fby-uuid\x2f14834675496984423962'
Dec 06 11:17:54 <> systemd-udevd[5391]: sddc: Found 'b128:160' claiming '/run/udev/links/disk\x2fby-label\x2fpool1'
```

I've uploaded the full output of `journalctl -eu systemd-udevd` when I do `udevadm trigger -d /sys/class/block/sddd` here: https://pastebin.com/dJJ3qXAM

systemd-udevd is spinning on all cores, seemingly fighting over these symlinks. Does zfs create these and if so, can I disable it?

Happy to go off and report this to systemd/whoever if it should be with them

Thanks!

**Comment by behlendorf** [comment]
> Does zfs create these and if so, can I disable it?

Those symlinks are being managed by the distribution provided udev rules for your system to populate `/dev/`.  They're entirely outside the control of ZFS.

The thrashing you're seeing is also very likely the cause of your non-uniform vdev names in `zpool status`.  What's probably happening is `zpool import` is running before all of the `/dev/disk/by-id/` symlinks have been created.  Since those paths don't exist, rather than failing to import the pool due to missing device path, ZFS detects the alternate `/dev/sdX` paths and opens the devices using those paths instead.   You'll want to make sure the import happens after all the symlinks have been created.

**Comment by rilott** [comment]
Thank you for taking a look, I'll investigate udev further! Closing this issue

**Comment by pikrzysztof** [comment]
> Thank you for taking a look, I'll investigate udev further! Closing this issue

Have you managed to find a workaround better than `while ! zpool import -d /dev/disk/by-id; sleep 2; done` ?

**Comment by rilott** [comment]
In the end I modified a few udev rules and that fixed it for me:

```
13-dm-disk.rules:
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_UUID_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-uuid/$env{ID_FS_UUID_ENC}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_FS_LABEL_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"

60-persistent-storage.rules:
# by-label/by-uuid links (filesystem metadata)
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_UUID_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-uuid/$env{ID_FS_UUID_ENC}"
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_LABEL_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"

63-md-raid-arrays.rules:
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_UUID_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-uuid/$env{ID_FS_UUID_ENC}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_FS_LABEL_ENC}=="?*", ENV{ID_FS_TYPE}!="zfs_member", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"
```

Basically adding `ENV{ID_FS_TYPE}!="zfs_member"` to any rule that was causing the problem.
