### ISSUE TITLE
[5.17] PDE_DATA() replaced by pde_data()

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#13004]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04
Kernel Version	| 5.17.0-051700rc1-generic
Architecture	| x86_64
OpenZFS Version	| 2.1.2

### Describe the problem you're observing

5.17-rc1 replaces PDE_DATA() with pde_data() [in this commit ](https://github.com/torvalds/linux/commit/359745d78351c6f5442435f81549f0207ece28aa) (more info [here](https://lore.kernel.org/all/20211124081956.87711-2-songmuchun@bytedance.com/T/#u)) to avoid a clash with nubus driver.

> PDE_DATA(inode) is introduced to get user private data and hide the
> layout of struct proc_dir_entry. The inode->i_private is used to do
> the same thing as well. Save a copy of user private data to inode->
> i_private when proc inode is allocated. This means the user also can
> get their private data by inode->i_private.
> 
> Introduce pde_data() to wrap inode->i_private so that we can remove
> PDE_DATA() from fs/proc/generic.c and make PTE_DATE() as a wrapper
> of pde_data(). It will be easier if we decide to remove PDE_DATE()
> in the future.

This leads to this issue when building zfs 2.1.2 patched with https://github.com/openzfs/zfs/pull/12989 and https://github.com/openzfs/zfs/pull/12975: 
```
checking whether PDE_DATA() is available... configure: error:
        *** None of the expected "PDE_DATA" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
```

**Comment by ckane** [comment]
@behlendorf  - I can confirm I've also encountered this and have a setup where I can test fixes. I'll try taking a look at it this week, but let me know if you (or someone else) gets to it first.

**Comment by nabijaczleweli** [comment]
Try #13007 on for size?
