### ISSUE TITLE
gentoo-sources-5.15.16, zfs-2.1.2-1, enable-linux-builtin: No "capability" interfaces detected (error)

### ISSUE THREAD

**Issue by voidzero** [openzfs/zfs#13018]
Linux amd64, Funtoo (based on Gentoo), glibc 2.33, running kernel 5.9.0-pf2.

My system is a bit behind on updates, so, I have unpacked gentoo-sources-5.15.16, checked out origin/zfs-2.1-release, and am trying to `./configure --with-linux=/usr/src/linux/ --enable-linux-builtin`. I can't imagine that gentoo-sources has breaking patches. But I am getting the following error:

```
checking whether the BIO_RW_UNPLUG enum is available... no
checking whether struct blk_plug is available... yes
checking whether get_disk_and_module() is available... no
checking whether get_disk_ro() is available... yes
checking whether generic_readlink is global... no
checking whether ql->discard_granularity is available... yes
checking whether inode_owner_or_capable() exists... no
*** None of the expected "capability" interfaces were detected.
*** This may be because your kernel version is newer than what is
*** supported, or you are using a patched custom kernel with
*** incompatible modifications.
*** 
*** ZFS Version: zfs-2.1.2-1
*** Compatible Kernels: 3.10 - 5.15
```

Please see the attached files: the config.log from zfs, and my kernel .config.

[kernel-config.gz](https://github.com/openzfs/zfs/files/7943140/kernel-config.gz)
[config.log.gz](https://github.com/openzfs/zfs/files/7943141/config.log.gz)

Thank you

**Comment by szubersk** [comment]
@voidzero Would you mind sharing kernel source tarball used in the process? I couldn't replicate this issue on vanilla 5.15.19.

**Comment by voidzero** [comment]
Yes, I'll get this done somewhere this week (tomorrow I hope)!
Mark

**Comment by szubersk** [comment]
@voidzero Is the issue still valid?

**Comment by voidzero** [comment]
I have to revisit this later. I'll reopen this when I get the chance - sorry - having some unfortunate circumstances irl.

**Comment by szubersk** [comment]
@voidzero Feel free to reopen this ticket if you encounter the issue again. Best of luck in your non-GitHub life!
