### ISSUE TITLE
dracut fails to mount zfs root

### ISSUE THREAD

**Issue by mangoducksparkles** [openzfs/zfs#13012]
I'm trying to install arch linux on encrypted zfs using dracut. Everything seems to go well up until after it begins booting and I input my password. Then it fails to mount the root, throwing the error `archlinux mount[733]: mount: /sysroot: unknown filesystem type 'zfs_member'.` and kicks me to the emergency shell. I'm able to access and mount anything from the zfs pool manually in the emergency shell, so I don't know why it's throwing an error.

I ran the following to setup the boot image (from within `arch-chroot` in the target partition):
```
# dracut -f --uefi --regenerate-all --early-microcode --add zfs --add-drivers zfs
# bootctl install
```
Here is my rdsosreport.txt:
[rdsosreport.txt](https://github.com/openzfs/zfs/files/7931518/rdsosreport.txt)
Here is the output of `systemctl status sysroot.mount` in case that's useful (the error said to run that for more info):
[systemctl status sysroot.mount.txt](https://github.com/openzfs/zfs/files/7931529/systemctl.status.sysroot.mount.txt)

I hope it's acceptable for me to post this here. I apologize if this is the wrong place. Searching for help on zfs and dracut led me here. I have some familiarity with linux, but this is my first attempt at a more complicated install than just running an installer from a live CD. Thank you.

**Comment by nabijaczleweli** [comment]
Looks like you didn't set `root=`?

**Comment by mangoducksparkles** [comment]
That guide says "If not set, importable pools are searched for a bootfs attribute." I set the bootfs attribute for the pool. It's able to import the pool and decrypt it.

I tried adding the `root=ZFS:arch/root/default` command line parameter anyway, but that throws the error `FATAL: Don't know how to handle 'root=ZFS:arch/root/default'`

**Comment by nabijaczleweli** [comment]
Does it really say you can pass `root=ZFS:xxx`? You can't, I don't know why that's in there. Can you try with `root=zfs:a/r/d` or `root=ZFS=a/r/d`?

My working theory is that either (a) your initrd doesn't have the ZFS bit in or (b) a no-`root=` condition meant a preference for
```
      Where: /sysroot
       What: /dev/gpt-auto-root
```
Either way, forcing a valid ZFS `root=` should (dis)prove one or the other.

**Comment by mangoducksparkles** [comment]
`root=zfs:AUTO` did the trick! TYSM!

In case any other noobs follow in my footsteps, I used `dracut --print-cmdline` to get the default kernel command line parameters. I then created `/etc/dracut.conf.d/cmdline.conf` with `kernel_cmdline="` + the default parameters + `root=zfs:AUTO"`, and it booted like a charm!

**Comment by nabijaczleweli** [comment]
Yeah, the dracut README was absolutely criminal (as a bonus: it didn't even *note* `zfs:AUTO`). I've rewritten it here, it should actually be "correct" and "okay": https://github.com/openzfs/zfs/pull/13017/files#diff-a4e5621a10d56ba821096a336ca1c8b7f34b6937ffdac2b7a1f49ac9c2f9efb9

**Comment by Dragon-debian** [comment]
I think systemd-gpt-auto generator is interfering with zfs hooks, Im not sure. try to disable it and try `root=zfs:arch/root/default` again. to disable this, add `rd.systemd.gpt_auto=0` to kernel command line.
whats the `mountpoint` value of the root dataset? is it `legacy`? maybe #12706 is related to this.

**Comment by mangoducksparkles** [comment]
So, I removed `root=` from the command line altogether, and added `rd.systemd.gpt_auto=0`. So, to clarify, the complete command line is now `rootfstype=zfs rootflags=rw,relatime,xattr,posixacl rd.systemd.gpt_auto=0`. I reran `dracut` and `bootctl` as I noted above, then rebooted. It was able to boot successfully with no trouble.

`zfs get mountpoint` yields:
```
NAME               PROPERTY    VALUE       SOURCE
arch               mountpoint  none        local
arch/data          mountpoint  none        inherited from arch
arch/data/home     mountpoint  /home       local
arch/root          mountpoint  none        inherited from arch
arch/root/default  mountpoint  /           local
```
