### ISSUE TITLE
incorrect used when zfs+drbd

### ISSUE THREAD

**Issue by meilihao** [openzfs/zfs#13011]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Kylin
Distribution Version	| V10
Kernel Version	| 4.19.90
Architecture	| aarch64
OpenZFS Version	| 0.8.6
### Describe the problem you're observing
drbd secondary device use more space(almost drbd primary device size).
> drbd r21 on node-162 is secondary role.

![截图_选择区域_20220125144641](https://user-images.githubusercontent.com/4382586/150929701-478efe39-f66a-4c0b-9e72-762cb52f4c65.png)
![截图_选择区域_20220125144722](https://user-images.githubusercontent.com/4382586/150929704-6162987f-e2b7-4677-87e3-83c2d3bf0a14.png)
![截图_选择区域_20220125150338](https://user-images.githubusercontent.com/4382586/150929714-138da07b-9bcc-4121-9f2e-9cc522b9b5bc.png)
![截图_选择区域_20220125150407](https://user-images.githubusercontent.com/4382586/150929718-6f63c7e9-1c47-46bd-8ca4-e96dd03aa5ff.png)
![截图_选择区域_20220125144955](https://user-images.githubusercontent.com/4382586/150929708-79e3b9e9-7f93-42d2-a213-2f017f24cf44.png)
![截图_选择区域_20220125145021](https://user-images.githubusercontent.com/4382586/150929710-d531a0be-9844-40ed-8267-5bf5736ef163.png)

### Describe how to reproduce the problem
1. create 2 pools(p1, p2) on each node with the same disk and vdev
2. create 2 zvol with 1T: v1(on p1),v2(on p2), then create and up drbd device(v1 is primary, v2 is secondary)
3. after drbd first synced,  p2 used size - p1 used size ≈ v1 size(`(1.46-1.01)/45.56%≈1T`)

**Comment by rincebrain** [comment]
refreservations are set by default on zvols, so even though the REFER of the secondary is only 32 MB, it's going to be accounted for as a 1T allocation because that's the size of the refreservation.

You can see this breakdown in the `usedby*` properties.

**Comment by meilihao** [comment]
But the available space of p2 pool is obviously 1T less than expected.

**Comment by rincebrain** [comment]
If you really want to, you can override the existence of the refreservation (e.g. make the zvols "sparse"), but that exists by default because very few things react well to getting an error when they try to write to a block device and it's out of space for the write.

**Comment by meilihao** [comment]
@rincebrain Sorry, because of the picture, the zvol's role may be confused.

this is secondary role:
![2022-01-27_17-12-59](https://user-images.githubusercontent.com/4382586/151328306-2bfeef3e-8292-4a34-8aa4-8e64160478cd.png)

this is primary role:
![2022-01-27_17-13-36](https://user-images.githubusercontent.com/4382586/151328312-9edddffd-61fd-4d63-85c3-555c26e9ead4.png)

**Comment by rincebrain** [comment]
I understand.

I'm telling you this is working as intended.
