### ISSUE TITLE
Feature request: (initramfs) If no dataset is specified on the root= kernel command line, the user will be prompted to choose a dataset to use.

### ISSUE THREAD

**Issue by digitalsignalperson** [openzfs/zfs#13028]
### Describe the feature would like to see added to OpenZFS

I was imagining that in in the initramfs script, if a dataset is not provided, the user could be prompted to choose a dataset to use.

This would be almost the same mechanism as the existing prompt to choose a snapshot if not provided. For reference from the README.initramfs.markdown:

> If no snapshot is specified on the root= kernel command line, but there is an @, the user will be prompted to choose a snapshot to use.

In initramfs/scripts/zfs we have the function ask_user_snap() with description 
> \# Get a list of snapshots, give them as a numbered list
> \# to the user to choose from.

it's less than 50 lines of code and perhaps can be copied for this new feature.

Perhaps the two prompts could work together as well (if an @ is provided, but a dataset is not provided and a snapshot is not provided, prompt for both)

### How will this feature improve OpenZFS?

This would provide a simple and robust tool, either for occasional troubleshooting or more frequent day to day use to boot into different environments. The prompt to pick a dataset is effectively a KISS boot environment picker.

### Additional context

Current behaviour is 

> If a dataset is specified, it will be used as the root filesystem. Otherwise, this script will attempt to find a root filesystem automatically (in the specified pool or all pools, as described above).

where it seems the initramfs script will look for a pool with 'bootfs' property which points to the dataset to use

**Comment by nabijaczleweli** [comment]
Isn't this just uhhhhhh https://github.com/zbm-dev/zfsbootmenu but worse?

**Comment by digitalsignalperson** [comment]
closing - it's easy enough to hack on a hook like this:
https://www.reddit.com/r/archlinux/comments/j9iqu5/guide_how_to_boot_off_a_zfs_snapshot_of_the_root/

also semi-related, but I was confused about the readme here https://github.com/openzfs/zfs/tree/master/contrib/initramfs which although clearly states it's for "initramfs-tools", it took me a sec to understand that the mkinitcpio hook is different (e.g. can't specify snapshot to boot from)
