### ISSUE TITLE
SPLError: 864:0:(zfs_vfsops.c:347:zfs_space_delta_cb()) SPL PANIC

### ISSUE THREAD

**Issue by ghost** [openzfs/zfs#1303]
This system is running rc14 with only 3.5Gbyte of RAM. This happened during an rsync.

```
VERIFY3(sa.sa_magic == 0x2F505A) failed (1319160994 == 3100762)
SPLError: 864:0:(zfs_vfsops.c:347:zfs_space_delta_cb()) SPL PANIC
SPL: Showing stack for process 864
Pid: 864, comm: txg_sync Tainted: P           ---------------    2.6.32-279.22.1.el6.x86_64 #1
Call Trace:
[<ffffffffa02dd5a7>] ? spl_debug_dumpstack+0x27/0x40 [spl]
[<ffffffffa02dec81>] ? spl_debug_bug+0x81/0xd0 [spl]
[<ffffffffa0452226>] ? zfs_space_delta_cb+0x286/0x290 [zfs]
[<ffffffffa03ce5a9>] ? dbuf_rele_and_unlock+0x169/0x210 [zfs]
[<ffffffffa03dd235>] ? dmu_objset_userquota_get_ids+0xc5/0x420 [zfs]
[<ffffffff814eb4fe>] ? mutex_lock+0x1e/0x50
[<ffffffffa03eab83>] ? dnode_sync+0xa3/0xa60 [zfs]
[<ffffffffa03d13a9>] ? dbuf_sync_list+0x59/0x80 [zfs]
[<ffffffffa03eafef>] ? dnode_sync+0x50f/0xa60 [zfs]
[<ffffffff814eb4fe>] ? mutex_lock+0x1e/0x50
[<ffffffffa03da819>] ? dmu_objset_sync_dnodes+0x89/0xb0 [zfs]
[<ffffffffa03daa2f>] ? dmu_objset_sync+0x1ef/0x360 [zfs]
[<ffffffffa03d9b20>] ? dmu_objset_write_ready+0x0/0x50 [zfs]
[<ffffffffa03daba0>] ? dmu_objset_write_done+0x0/0x70 [zfs]
[<ffffffffa03ed03c>] ? dsl_dataset_sync+0x4c/0x60 [zfs]
[<ffffffffa03fc1bf>] ? dsl_pool_sync+0xcf/0x540 [zfs]
[<ffffffffa041047e>] ? spa_sync+0x39e/0xa00 [zfs]
[<ffffffff8105f8ac>] ? try_to_wake_up+0x24c/0x3e0
[<ffffffff81012a69>] ? read_tsc+0x9/0x20
[<ffffffffa0422d87>] ? txg_sync_thread+0x307/0x590 [zfs]
[<ffffffff810527f9>] ? set_user_nice+0xc9/0x130
[<ffffffffa0422a80>] ? txg_sync_thread+0x0/0x590 [zfs]
[<ffffffffa02e64d8>] ? thread_generic_wrapper+0x68/0x80 [spl]
[<ffffffffa02e6470>] ? thread_generic_wrapper+0x0/0x80 [spl]
[<ffffffff81090876>] ? kthread+0x96/0xa0
[<ffffffff8100c0ca>] ? child_rip+0xa/0x20
[<ffffffff810907e0>] ? kthread+0x0/0xa0
[<ffffffff8100c0c0>] ? child_rip+0x0/0x20
SPL: Dumping log to /tmp/spl-log.1361200575.864
```

The log is at http://wwwlehre.dhbw-stuttgart.de/~bziller/spl-log.1361200575.864.gz

**Comment by woffs** [comment]
same here:

    Apr 21 12:18:25 griselda kernel: [  762.087675] VERIFY3(sa.sa_magic == 0x2F505A) failed (1429611505 == 3100762)
    Apr 21 12:18:25 griselda kernel: [  762.087680] PANIC at zfs_vfsops.c:400:zfs_space_delta_cb()
    Apr 21 12:18:25 griselda kernel: [  762.087681] Showing stack for process 664
    Apr 21 12:18:25 griselda kernel: [  762.087684] CPU: 0 PID: 664 Comm: txg_sync Tainted: P           O  3.16.0-0.bpo.4-amd64 #1 Debian 3.16.7-ckt7-1~bpo70+1
    Apr 21 12:18:25 griselda kernel: [  762.087685] Hardware name: LENOVO 2756N1G/MAHOBAY, BIOS 9SKT70AUS 06/07/2013
    Apr 21 12:18:25 griselda kernel: [  762.087687]  0000000000000000 ffffffffa035c220 ffffffff81543f17 ffffffffa036fab0
    Apr 21 12:18:25 griselda kernel: [  762.087690]  ffffffffa020ef62 ffff8800c2686840 ffffffffa0370008 0000000000000000
    Apr 21 12:18:25 griselda kernel: [  762.087692]  ffff880300000030 ffff8803db5fba38 ffff8803db5fb9d8 ffff88037aae1b08
    Apr 21 12:18:25 griselda kernel: [  762.087694] Call Trace:
    Apr 21 12:18:25 griselda kernel: [  762.087721]  [<ffffffff81543f17>] ? dump_stack+0x41/0x51
    Apr 21 12:18:25 griselda kernel: [  762.087729]  [<ffffffffa020ef62>] ? spl_panic+0xc2/0x100 [spl]
    Apr 21 12:18:25 griselda kernel: [  762.087746]  [<ffffffffa02a05bf>] ? dbuf_write.isra.9+0x1cf/0x410 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087767]  [<ffffffffa0294790>] ? arc_cksum_compute.isra.18+0xd0/0xd0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087778]  [<ffffffffa0293160>] ? arc_evictable_memory+0x80/0x80 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087788]  [<ffffffffa0296bd0>] ? arc_adapt_thread+0x4b0/0x4b0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087793]  [<ffffffff810b0db8>] ? __wake_up+0x48/0x70
    Apr 21 12:18:25 griselda kernel: [  762.087811]  [<ffffffffa032a9b8>] ? zfs_space_delta_cb+0xc8/0x1a0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087827]  [<ffffffffa02af35f>] ? dmu_objset_userquota_get_ids+0xdf/0x4e0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087844]  [<ffffffffa02bed38>] ? dnode_sync+0xc8/0x950 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087860]  [<ffffffffa02ad6e6>] ? dmu_objset_sync_dnodes+0xb6/0xe0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087874]  [<ffffffffa02ad8a7>] ? dmu_objset_sync+0x197/0x2f0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087885]  [<ffffffffa0294790>] ? arc_cksum_compute.isra.18+0xd0/0xd0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087896]  [<ffffffffa0293160>] ? arc_evictable_memory+0x80/0x80 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087906]  [<ffffffffa0296bd0>] ? arc_adapt_thread+0x4b0/0x4b0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087924]  [<ffffffffa02ce5c4>] ? dsl_pool_sync+0x94/0x440 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087945]  [<ffffffffa02e85fc>] ? spa_sync+0x45c/0xbb0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087948]  [<ffffffff810b119e>] ? autoremove_wake_function+0xe/0x30
    Apr 21 12:18:25 griselda kernel: [  762.087951]  [<ffffffff810b0db8>] ? __wake_up+0x48/0x70
    Apr 21 12:18:25 griselda kernel: [  762.087970]  [<ffffffffa02f940d>] ? txg_sync_thread+0x36d/0x5f0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087988]  [<ffffffffa02f90a0>] ? txg_fini+0x2c0/0x2c0 [zfs]
    Apr 21 12:18:25 griselda kernel: [  762.087995]  [<ffffffffa020c5ea>] ? thread_generic_wrapper+0x7a/0x90 [spl]
    Apr 21 12:18:25 griselda kernel: [  762.088002]  [<ffffffffa020c570>] ? __thread_create+0x160/0x160 [spl]
    Apr 21 12:18:25 griselda kernel: [  762.088006]  [<ffffffff81090551>] ? kthread+0xc1/0xe0
    Apr 21 12:18:25 griselda kernel: [  762.088010]  [<ffffffff81090490>] ? flush_kthread_worker+0xb0/0xb0
    Apr 21 12:18:25 griselda kernel: [  762.088013]  [<ffffffff8154a33c>] ? ret_from_fork+0x7c/0xb0
    Apr 21 12:18:25 griselda kernel: [  762.088017]  [<ffffffff81090490>] ? flush_kthread_worker+0xb0/0xb0

upgraded from zfs v4 to v5 some days ago. How to get rid of this
particular bad entry?
