### ISSUE TITLE
Removing a disk file from a mirror does not produce an error

### ISSUE THREAD

**Issue by shivanshu3** [openzfs/zfs#13041]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.3 LTS
Kernel Version	| 5.4.0-96-generic
Architecture	| x86-64
OpenZFS Version	| zfs-0.8.3-1ubuntu12.13, zfs-kmod-0.8.3-1ubuntu12.13

### Describe the problem you're observing
I have a pool with a single mirror backed by 2 files. When I delete one of these files and run `zpool scrub` I expect it to show me that the pool is degraded, but that doesn't happen. It shows that everything is healthy, until I reboot the machine, and then the pool finally becomes degraded.

### Describe how to reproduce the problem
Create 2 disk files, 300MB each:
```
dd if=/dev/zero of=/home/sg/zpool_testing/disk1.img bs=1M count=300
dd if=/dev/zero of=/home/sg/zpool_testing/disk2.img bs=1M count=300
```

Output:
```
300+0 records in
300+0 records out
314572800 bytes (315 MB, 300 MiB) copied, 0.407219 s, 772 MB/s
300+0 records in
300+0 records out
314572800 bytes (315 MB, 300 MiB) copied, 0.266665 s, 1.2 GB/s
```

Create a ZFS pool with 1 mirror backed by the 2 files created above. Add some data in this newly created pool and print zpool status.
```
zpool create pool1 mirror /home/sg/zpool_testing/disk1.img /home/sg/zpool_testing/disk2.img
echo hello world > /pool1/hello.txt
zpool status
```

Output:
```
  pool: pool1
 state: ONLINE
  scan: none requested
config:

        NAME                                  STATE     READ WRITE CKSUM
        pool1                                 ONLINE       0     0     0
          mirror-0                            ONLINE       0     0     0
            /home/sg/zpool_testing/disk1.img  ONLINE       0     0     0
            /home/sg/zpool_testing/disk2.img  ONLINE       0     0     0

errors: No known data errors
```

Delete a disk from the mirror, scrub the pool, and print the pool status:
```
rm /home/sg/zpool_testing/disk2.img
zpool scrub pool1
sleep 1
zpool status
```

Output:
```
  pool: pool1
 state: ONLINE
  scan: scrub repaired 0B in 0 days 00:00:00 with 0 errors on Sun Jan 30 02:46:46 2022
config:

        NAME                                  STATE     READ WRITE CKSUM
        pool1                                 ONLINE       0     0     0
          mirror-0                            ONLINE       0     0     0
            /home/sg/zpool_testing/disk1.img  ONLINE       0     0     0
            /home/sg/zpool_testing/disk2.img  ONLINE       0     0     0

errors: No known data errors
```

Restarting the server and running `zpool status` finally outputs the error which should have been shown before:
```
  pool: pool1
 state: DEGRADED
status: One or more devices could not be opened.  Sufficient replicas exist for
        the pool to continue functioning in a degraded state.
action: Attach the missing device and online it using 'zpool online'.
   see: http://zfsonlinux.org/msg/ZFS-8000-2Q
  scan: scrub repaired 0B in 0 days 00:00:00 with 0 errors on Sun Jan 30 02:46:46 2022
config:

        NAME                                  STATE     READ WRITE CKSUM
        pool1                                 DEGRADED     0     0     0
          mirror-0                            DEGRADED     0     0     0
            /home/sg/zpool_testing/disk1.img  ONLINE       0     0     0
            15136532953254090313              UNAVAIL      0     0     0  was /home/sg/zpool_testing/disk2.img

errors: No known data errors
```

**Comment by shivanshu3** [comment]
I am able to repro this on Arch Linux as well, which uses much more recent versions of the Linux kernel and ZFS.
Kernel version: `5.16.3-arch1-1`
ZFS versions: `zfs-2.1.99-717_g73e972af7a`, `zfs-kmod-2.1.99-717_g73e972af7a`

**Comment by Haravikk** [comment]
Hopefully someone will correct me if I'm wrong, but removing a file from a directory doesn't immediately delete all of its data, all that does is remove one reference to the file.

Files are also referenced by file pointers (or handles, the terminology seems to vary), i.e- programs that currently have that file open for reading and/or writing. Since ZFS is still using the file it will maintain an open file pointer, and until that pointer is closed all of the data continues to remain on disk and is still (over)writeable. You would have to export and then reimport the pool to force ZFS to close any file pointer(s) and detect that the file is now missing, and doing so should also free the space.

It's not unlike a file in a ZFS pool with snapshots; if you delete a file but it was saved in one or more snapshots then the file still exists, it won't be deleted until the snapshots are.

**Comment by shivanshu3** [comment]
ZFS didn't create any hard links of the file. And if ZFS has the file open,
it shouldn't let me simply delete the file. What you're saying makes sense
at a high level but this behavior still seems buggy to me.

**Comment by gmelikov** [comment]
rm uses `unlink*` inside https://man7.org/linux/man-pages/man2/unlink.2.html

```
unlink() deletes a name from the filesystem.  If that name was
       the last link to a file and no processes have the file open, the
       file is deleted and the space it was using is made available for
       reuse.

       If the name was the last link to a file but any processes still
       have the file open, the file will remain in existence until the
       last file descriptor referring to it is closed.
```

Looks like you try to stress-test ZFS, helpful link https://jrs-s.net/2016/05/16/zfs-practicing-failures/

**Comment by shivanshu3** [comment]
I see, that makes sense, thank you for the explanation and sorry for the false alarm!
