### ISSUE TITLE
zfs module and prog versions missmatch after build from source on ubuntu 20.04

### ISSUE THREAD

**Issue by dipol0** [openzfs/zfs#13045]
### Discussed in https://github.com/openzfs/zfs/discussions/13035

<div type='discussions-op-text'>

<sup>Originally posted by **dipol0** January 29, 2022</sup>
Hi. Sorry my english.

OS Ubuntu 20.04 lts
gcc 10.3.0

I build zfs from source use:

_git clone https://github.com/openzfs/zfs.git_

[As in documentation](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html?highlight=build) i make:

_sh ./autogen.sh
./configure_

> !!! _cat zfs.release_
> get - _2.1.99-716_g7633c0aed_

Ok. Next... I integrate ZFS to Linux kernel sources (v.5.5.17) and build new kernel. Continue in ZFS...

_make -s -j$(nproc)
sudo make install; sudo ldconfig; sudo depmod_

Install new kernel, reboot.... And zfs-volumes not mounted. I check prog and modules version:

_zpool version
zfs-2.1.99-705_g8d6a598a2
zfs-kmod-2.1.99-716_g7633c0aed_

Fist i think may be previous installation not correct or some thing...
Go to source:

_cd ~/src/zfs/cmd/zpool/.libs$
./zpool version_

and get same:

_zfs-2.1.99-705_g8d6a598a2
zfs-kmod-2.1.99-716_g7633c0aed_

**what wrong?**

i remove zfs 

_sudo make uninstall; sudo ldconfig; sudo depmod_

i remove sources and repeat all steps from git clone.... but it made made kernel module with new verzion zfs but zpool, zfs and etc create wrong (old) version. May be i mistake somewhere ?

Tnx.

UPD:

if i run warper:

_cd ~/src/zfs/cmd/zpool/$
./zpool version_

then show correct version _zfs-2.1.99-716_g7633c0aed_</div>

**Comment by rincebrain** [comment]
You're not installing the new userland libraries and binaries, and you have old ones in your path somewhere.

Just running the versions in e.g. cmd/zpool/.libs/$FOO will use your system libraries, while using the wrapper at e.g. cmd/zpool/zpool will use the local libraries in the tree.

Go look at `which zpool`, compare to where make install is installing your userland binaries It's probably something like /usr/sbin/zpool versus /usr/local/sbin/zpool.)

**Comment by dipol0** [comment]
**rincebrain**

tnx.

Previously a run configure as:

_./configure --prefix=/ --libdir=/lib --includedir=/usr/include --datarootdir=/usr/share --enable-linux-builtin=yes --with-linux=/home/user/src/linux-5.13.19 --with-linux-obj=/home/user/src/linux-5.13.19_

and all be fine. But not now.

I clean zfs install, and run:

_./configure --with-linux=/home/user/src/linux-5.13.19 --with-linux-obj=/home/user/src/linux-5.13.19_

continue... make and install... and now all looks fine

zpool version show:

_zfs-2.1.99-717_g73e972af7
zfs-kmod-2.1.99-717_g73e972af7_

Yes. zpool and etc pros not in /usr/sbin location. Now all in /usr/local/sbin

I thik need close this "issue". most likely Its be my mistake.
