### ISSUE TITLE
Linux 5.16 broke FPU handling

### ISSUE THREAD

**Issue by AttilaFueloep** [openzfs/zfs#13042]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| rolling
Kernel Version	|  5.16.3-arch1-1
Architecture	| x86
OpenZFS Version	|  zfs-2.1.99-717_g73e972af7a, zfs-kmod-2.1.99-1

### Describe the problem you're observing

Recent master broke SIMD acceleration for AES-GCM, I suspect the recent ICP changes. Both, `pclmulqdq` and `avx` are missing.

Sorry, I can't look into this before midweek.

### Describe how to reproduce the problem

```sh
cat /sys/module/icp/parameters/icp_gcm_impl 
cycle [fastest] generic
```

**Comment by AttilaFueloep** [comment]
@nabijaczleweli

**Comment by rincebrain** [comment]
```
$ sudo zfs version
zfs-2.1.99-715_gc70bb2f61
zfs-kmod-2.1.99-715_gc70bb2f61
$ grep . /sys/module/icp/parameters/icp_*impl
/sys/module/icp/parameters/icp_aes_impl:cycle [fastest] generic x86_64 aesni
/sys/module/icp/parameters/icp_gcm_impl:cycle [fastest] avx generic pclmulqdq
$ uname -r
4.19.0-18-amd64
$
```

So I don't know that it's recent master that's the problem - I would wonder about 5.16 having more fallout.

**Comment by nabijaczleweli** [comment]
Can't wait to get blamed for every vaguely-ICP-related change this calendar year.

**Comment by AttilaFueloep** [comment]
@nabijaczleweli  Sorry, could've sworn that it worked with Linux 5.16.2 and 17b2ae0b24, but obviously it did not. I really should've been more thorough and not acting in a rush before tagging you, my apologies. 

@rincebrain Had a quick look and I concur, those two commits broke fpu handling. IIUC we are not using `struct fpu` but just `union fpstate_regs` to allocate our own memory region where we store the FPU registers (but even if, we can still access the union via `fpu->fpstate`). The move of `XSTATE_XSAVE` seems to be no big deal either, it shouldn't be too hard to roll our own code to XSAVE{,OPT,S} the FPU state. I'll try to put something together by midweek.

**Comment by dm17** [comment]
https://arstechnica.com/gadgets/2020/01/linus-torvalds-zfs-statements-arent-right-heres-the-straight-dope/ - for the sake of background, seems related. (Yes, I'm a ZFS admin who has no plans of moving off of ZFS, no matter what Linus says.)
