### ISSUE TITLE
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.15.15-76051515 -generic

### ISSUE THREAD

**Issue by bighungry** [openzfs/zfs#13061]
I am trying to install OpenZFS on Pop!_OS 20.04 and while the packages install correctly, ZFS is not installed.

Here is the output:

austin@av-farm:/mnt/farm16.0$ sudo apt install zfsutils-linux
[sudo] password for austin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnvpair3linux libuutil3linux libzfs4linux libzpool4linux zfs-zed
Suggested packages:
  nfs-kernel-server samba-common-bin zfs-initramfs | zfs-dracut
The following NEW packages will be installed:
  libnvpair3linux libuutil3linux libzfs4linux libzpool4linux zfs-zed
  zfsutils-linux
0 upgraded, 6 newly installed, 0 to remove and 5 not upgraded.
Need to get 2,142 kB of archives.
After this operation, 6,882 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 libnvpair3linux amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [60.3 kB]
Get:2 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 libuutil3linux amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [54.8 kB]
Get:3 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 libzfs4linux amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [232 kB]
Get:4 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 libzpool4linux amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [1,236 kB]
Get:5 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 zfsutils-linux amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [482 kB]
Get:6 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 zfs-zed amd64 2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c [76.4 kB]
Fetched 2,142 kB in 4s (512 kB/s) 
Selecting previously unselected package libnvpair3linux.
(Reading database ... 235973 files and directories currently installed.)
Preparing to unpack .../0-libnvpair3linux_2.0.6-1ubuntu2pop0~1642612525~20.04~51
ca23c_amd64.deb ...
Unpacking libnvpair3linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Selecting previously unselected package libuutil3linux.
Preparing to unpack .../1-libuutil3linux_2.0.6-1ubuntu2pop0~1642612525~20.04~51c
a23c_amd64.deb ...
Unpacking libuutil3linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Selecting previously unselected package libzfs4linux.
Preparing to unpack .../2-libzfs4linux_2.0.6-1ubuntu2pop0~1642612525~20.04~51ca2
3c_amd64.deb ...
Unpacking libzfs4linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Selecting previously unselected package libzpool4linux.
Preparing to unpack .../3-libzpool4linux_2.0.6-1ubuntu2pop0~1642612525~20.04~51c
a23c_amd64.deb ...
Unpacking libzpool4linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Selecting previously unselected package zfsutils-linux.
Preparing to unpack .../4-zfsutils-linux_2.0.6-1ubuntu2pop0~1642612525~20.04~51c
a23c_amd64.deb ...
Unpacking zfsutils-linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Selecting previously unselected package zfs-zed.
Preparing to unpack .../5-zfs-zed_2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c_am
d64.deb ...
Unpacking zfs-zed (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Setting up libnvpair3linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Setting up libuutil3linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Setting up libzfs4linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Setting up libzpool4linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Setting up zfsutils-linux (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.15.15-76051515
-generic
Created symlink /etc/systemd/system/zfs-import.target.wants/zfs-import-cache.ser
vice → /lib/systemd/system/zfs-import-cache.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-import.target → /lib/sy
stemd/system/zfs-import.target.
Created symlink /etc/systemd/system/zfs-mount.service.wants/zfs-load-module.serv
ice → /lib/systemd/system/zfs-load-module.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-load-module.service → /
lib/systemd/system/zfs-load-module.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-mount.service → /lib/sy
stemd/system/zfs-mount.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-share.service → /lib/sy
stemd/system/zfs-share.service.
Created symlink /etc/systemd/system/zfs-volumes.target.wants/zfs-volume-wait.ser
vice → /lib/systemd/system/zfs-volume-wait.service.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-volumes.target → /lib/s
ystemd/system/zfs-volumes.target.
Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target → /lib/sy
stemd/system/zfs.target.
zfs-import-scan.service is a disabled or a static unit, not starting it.
Setting up zfs-zed (2.0.6-1ubuntu2pop0~1642612525~20.04~51ca23c) ...
Created symlink /etc/systemd/system/zed.service → /lib/systemd/system/zfs-zed.se
rvice.
Created symlink /etc/systemd/system/zfs.target.wants/zfs-zed.service → /lib/syst
emd/system/zfs-zed.service.
Processing triggers for systemd (245.4-4ubuntu3.15pop0~1642720691~20.04~baa7bbb)
 ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...

**Comment by AllKind** [comment]
are linux-image-$(uname-r) and zfs-dkms installed? you'd need those...

**Comment by szubersk** [comment]
I think this is a legitimate bug report. There's a gap in the docs. https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/index.html#installation says
```
Since Ubuntu 16.04, ZFS is included in the default Linux kernel packages. To install the ZFS utilities:

apt update
apt install zfsutils-linux
```
Not a bit about `zfs-dkms` package. Mentioning @rlaager as requested. Indeed
```
$ doas debootstrap --no-check-gpg  --include=zfsutils-linux focal chroot
```
produces no ZFS kernel module files in `chroot` directory.

@bighungry Add `universe` component and install `zfs-dkms` package. Installing `zfsutils-linux` covers only user space utilities.

**Comment by rlaager** [comment]
Pop! OS is not Ubuntu. I have no idea if Pop! OS ships a binary ZFS module as part of their kernel. This report suggests no.

**Comment by szubersk** [comment]
Richard, I agree it is not Ubuntu, it is based on Ubuntu, though: https://en.wikipedia.org/wiki/Pop!_OS

**Comment by rlaager** [comment]
And Ubuntu is based on Debian, buy they handle these things differently.

**Comment by OKT96** [comment]
I had the same error during installation but on pop! os 21.10
It worked after installing zfs-dkms @szubersk thanks :)

**Comment by GogoFC** [comment]
I just had the same error on jammy.

`grub-probe /boot ` returns `error: unknown filesystem.` and nothing gets installed in `/boot/efi` dir.

**Comment by enedil** [comment]
Just had the same problem on Fedora 37. I have zfs-dkms package installed. Any clues?

**Comment by rickygm** [comment]
any solution?

**Comment by rickygm** [comment]
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.18.0-425.13.1.el8_7.x86_64 AlmaLinux 8

**Comment by enedil** [comment]
On Fedora, I managed to get it working by removing `zfs-release` and `zfs`, and later installing `zfs` again, as indicated in the docs.

**Comment by afberendsen** [comment]
module does not compile on Fedora 37 new kernel update

```Running scriptlet: zfs-dkms-2.1.9-1.fc37.noarch                                                                                                             142/143
Loading new zfs-2.1.9 DKMS files...
Building for 6.2.8-200.fc37.x86_64
Building initial module for 6.2.8-200.fc37.x86_64
Error! Bad return status for module build on kernel: 6.2.8-200.fc37.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/2.1.9/build/make.log for more information.
warning: %post(zfs-dkms-2.1.9-1.fc37.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package zfs-dkms
  Installing       : zfs-2.1.9-1.fc37.x86_64                                                                                                                  143/143
  Running scriptlet: zfs-2.1.9-1.fc37.x86_64                                                                                                                  143/143
Created symlink /etc/systemd/system/zfs-import.target.wants/zfs-import-cache.service → /usr/lib/systemd/system/zfs-import-cache.service.
```
Log file shows
```ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'bio_start_io_acct'
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'bio_end_io_acct_remapped'
make[4]: *** [scripts/Makefile.modpost:138: /var/lib/dkms/zfs/2.1.9/build/module/Module.symvers] Error 1
make[3]: *** [Makefile:1977: modpost] Error 2
make[3]: Leaving directory '/usr/src/kernels/6.2.8-200.fc37.x86_64'
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/2.1.9/build/module'
make[1]: *** [Makefile:933: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/2.1.9/build'
make: *** [Makefile:794: all] Error 2
```

**Comment by rickygm** [comment]
This problem has not been solved yet, which part of the doc are you referring to?

**Comment by enedil** [comment]
To be fair I already don't remember what I had in mind back then. Sorry.

**Comment by 0xzfs** [comment]
For those who are missing zfs-dkms, first install that as suggested by few already.

If it still won't work, try running:
`sudo dpkg-reconfigure zfs-dkms
sudo modprobe zfs`

tho it mostly happens after kernel upgrade that the zfs module is "lost", it shouldn't be the case after a fresh zfs-dkms install.

**Comment by shakibamoshiri** [comment]
On Debian 11 this helps too

### error
```bash
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.10.0-32-amd64
```

### install headers
```bash
apt install linux-headers-$(uname -r)
```

### test 
```bash
modprobe zfs
```

**Comment by Kangaroux** [comment]
Had this issue on Debian 13. The `apt install` from the docs installed the wrong headers for me.

```bash
# OK: 6.12.101
apt install linux-headers-$(uname -r)

# (docs) BAD: 6.12.107
apt install linux-headers-$(dpkg --print-architecture)
```

**Comment by wommy** [comment]
@Kangaroux why not
`apt install linux-headers`

**Comment by Kangaroux** [comment]
> [@Kangaroux](https://github.com/Kangaroux) why not `apt install linux-headers`

~~Because that installed the wrong headers.~~ Sorry I can't read. `linux-headers` isn't available for me.

```
# apt show linux-headers
Package: linux-headers
State: not a real package (virtual)
Notice: Can't select candidate version from package linux-headers as it has >
Notice: Can't select versions from package 'linux-headers' as it is purely v>
Notice: No packages found
```
