### ISSUE TITLE
NFS export of a mountpoint containing spaces fails

### ISSUE THREAD

**Issue by LubosKolouch** [openzfs/zfs#13153]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| rolling
Kernel Version	| 5.16.10-arch1-1
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.2-1

### Describe the problem you're observing
When i sharenfs a dataset mounted to a mountpoint containing space, it is exported wrongly - only the part before the space is there

### Describe how to reproduce the problem

zfs create ZA17DCV8/aaa -o mountpoint="/mnt/c/a space"

zfs list
ZA17DCV8/aaa                                 96K  1.53T       96K  /mnt/c/a space

zfs sharenfs=on ZA17DCV8/aaa

mnt/c/a        <world>(sync,wdelay,hide,crossmnt,no_subtree_check,mountpoint,sec=sys,rw,secure,root_squash,no_all_squash)

exportfs -a

exportfs: Failed to stat /mnt/c/a: No such file or directory

**Comment by nabijaczleweli** [comment]
Confirmed:
```
# zfs create tarta-zoot/spaced\ out -o sharenfs=on
# cat /etc/exports.d/zfs.exports
# !!! DO NOT EDIT THIS FILE MANUALLY !!!

/mnt/filling/machine/1200-S121 *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt,no_subtree_check,no_root_squash,async)
/spaced out *(sec=sys,rw,no_subtree_check,mountpoint,crossmnt)
```

According to exports(5):
> Blank lines are ignored.  A pound sign ("#") introduces a comment to the end of the line. Entries may be continued across newlines using a backslash. If an export name contains spaces it should be quoted using double quotes. You can also specify spaces or other unusual character in the export name using a backslash followed by the character code as three octal digits.

And, indeed, doing `"/spaced out" *(sec...` and `/spaced\040out *(sec` does work.
Surprisingly, `/достопримечательности` is okay, as is `/a#b` and `/a\040#b`, but `/a #b` and `/a<TAB>b` are *not* – we need to escape isspace() and / in `nfs_add_entry()` (and then re-parse that!) and it'll be fine.

**Comment by nabijaczleweli** [comment]
ha. ha. ha. im gonna throw up
![image](https://user-images.githubusercontent.com/6709544/156036245-d8f65ed9-936d-4f68-bbad-2b3a95f608b1.png)
