### ISSUE TITLE
Use a stronger hash algorithm for signing RPMs

### ISSUE THREAD

**Issue by DemiMarie** [openzfs/zfs#13176]
### Describe the feature would like to see added to OpenZFS

OpenZFS RPM packages are currently signed using SHA-1.  This causes problems with tools, such as Qubes OS’s `rpmcanon`, which forbid SHA-1 by default.  It also causes problems in FIPS mode where SHA-1 is not allowed.

### How will this feature improve OpenZFS?

Users will be able to verify signatures on OpenZFS RPMs even if SHA-1 is disabled.

### Additional context

https://github.com/cfcs/qubes-storage-zfs/tree/7e240c7bc2ada378d8c0a7350d781aa11f14c4a3 currently recommends bypassing signature verification for this reason, which is bad.

**Comment by tonyhutter** [comment]
I'll try to do this with the next release RPMs.  It seems pretty straightforward:

```
rpmsign --addsign --digest-algo=sha256 <RPM FILE>
```

**Comment by tonyhutter** [comment]
I've updated the internal script we use to sign RPMs.  All ZFS RPMs going forward will be signed using SHA256.  Closing issue.
