### ISSUE TITLE
include python3.10 in aclocal.m4

### ISSUE THREAD

**Issue by UweSauter** [openzfs/zfs#13204]
I have no experience with Autotools but noticed that Python 3.10 is not listed in 2.1.3's `aclocal.m4` which also propagates to `configure`.

`aclocal.m4`
```
 922 AC_DEFUN([AM_PATH_PYTHON],
 923  [
 924   dnl Find a Python interpreter.  Python versions prior to 2.0 are not
 925   dnl supported. (2.0 was released on October 16, 2000).
 926   m4_define_default([_AM_PYTHON_INTERPRETER_LIST],
 927 [python python2 python3 dnl
 928  python3.9 python3.8 python3.7 python3.6 python3.5 python3.4 python3.3 dnl
 929  python3.2 python3.1 python3.0 dnl
 930  python2.7 python2.6 python2.5 python2.4 python2.3 python2.2 python2.1 dnl
 931  python2.0])
 932 
 933   AC_ARG_VAR([PYTHON], [the Python interpreter])
 ```
 and `configure`
 ```
 16813         # Find any Python interpreter.
 16814     if test -z "$PYTHON"; then
 16815       for ac_prog in python python2 python3  python3.9 python3.8 python3.7 python3.6 python3.5 python3.4
             python3.3  python3.2 python3.1 python3.0  python2.7 python2.6 python2.5 python2.4 python2.3 python2       .2 python2.1  python2.0
 16816 do
 16817   # Extract the first word of "$ac_prog", so it can be a program name with args.
```

Autotools are just too much a mystery to me that I could patch that on my own.

**Comment by szubersk** [comment]
@UweSauter I'm not sure what your report is about. Do you have Python 3.10 installed? If so, did you try compiling OpenZFS on that machine?

**Comment by nabijaczleweli** [comment]
Uhh. Patch, what, exactly? `AM_PATH_PYTHON` originates in autohell (you can tell because it's prefixed with automake_):
```
$ grep -r AM_PATH_PYTHON /usr/share/aclocal-*/
/usr/share/aclocal-1.16/python.m4:# AM_PATH_PYTHON([MINIMUM-VERSION], [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])
/usr/share/aclocal-1.16/python.m4:# If the MINIMUM-VERSION argument is passed, AM_PATH_PYTHON will
/usr/share/aclocal-1.16/python.m4:AC_DEFUN([AM_PATH_PYTHON],
```
If you're running Python 3.10 your distributor will also provide you with automake that handles it. Or not. Either way, this is a job for `reportbug` or equivalent. Also, `aclocal.m4` is not even part of the distribution (for obvious reasons, since it's generated by automake), so – huh?

**Comment by UweSauter** [comment]
I found this while compiling `zfs-dkms` from Arch Linux' [AUR package](https://aur.archlinux.org/packages/zfs-dkms) on my Raspberry Pi 4.
Arch Linux for ARM provides Python 3.10.2 and automake 1.16.5 and running your command gives the same result:
```console
# grep -r AM_PATH_PYTHON /usr/share/aclocal-*
/usr/share/aclocal-1.16/python.m4:# AM_PATH_PYTHON([MINIMUM-VERSION], [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])
/usr/share/aclocal-1.16/python.m4:# If the MINIMUM-VERSION argument is passed, AM_PATH_PYTHON will
/usr/share/aclocal-1.16/python.m4:AC_DEFUN([AM_PATH_PYTHON],
```

So, as I already stated, I have no experience with Autotools. Just to be 100% clear, do I understand you correctly that this is not a ZFS issue but that Arch Linux needs to include Python 3.10 support in its automake package? If so I will gladly open a ticket with Arch Linux.

Thanks.

**Comment by UweSauter** [comment]
Oh, I see that this really is an issue of the latest stable automake release and is addressed in https://bugs.gnu.org/53530 which means that Python 3.10 support should be available with the next automake release.

**Comment by szubersk** [comment]
@UweSauter looks like you could try dirty-patching your automake installation, it's just a one-liner.

Grats to @nabijaczleweli for resolving the issue before it was fully expressed!
Let's reopen this ticket when Python 3.16 is released ;)
```
--- a/m4/python.m4
+++ b/m4/python.m4
@@ -38,6 +38,7 @@ AC_DEFUN([AM_PATH_PYTHON],
   dnl supported. (2.0 was released on October 16, 2000).
   m4_define_default([_AM_PYTHON_INTERPRETER_LIST],
 [python python2 python3 dnl
+ python3.15 python3.14 python3.13 python3.12 python3.11 python3.10 dnl
  python3.9 python3.8 python3.7 python3.6 python3.5 python3.4 python3.3 dnl
  python3.2 python3.1 python3.0 dnl
  python2.7 python2.6 python2.5 python2.4 python2.3 python2.2 python2.1 dnl
```
