### ISSUE TITLE
Please update META again for kernel 5.16

### ISSUE THREAD

**Issue by dioni21** [openzfs/zfs#13212]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 35
Kernel Version	| 5.16.11
Architecture	| x86_64
OpenZFS Version	| 2.1.99-837_g7901b6268

### Describe the problem you're observing

I've been using OpenZFS on Linux 5.16 with no trouble at all, compiling it from master, and upgrading Fedora normally.  Yesterday dnf removed zfs, because it depended on kernel-devel-5.14, which was being removed from my setup.

I found the error to be in the META file, which limits kernel version to 5.15.  I upgraded it to 5.16 and now I could install the latest git version, 2.1.99-913_gdad2b19ff without any compilation errors.

**Comment by behlendorf** [comment]
PR opened.  We'll want to remember to bump this for 5.17 when it's released ZFS has been tested against the release.
