### ISSUE TITLE
dsl_bookmark.c: 'first_len' may be used uninitialized

### ISSUE THREAD

**Issue by dioni21** [openzfs/zfs#13247]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| fc35
Kernel Version	| 5.16.11
Architecture	| x86_64
OpenZFS Version	| git 6322a77ce7e661facac3335721dde9eff9ceb634

### Describe the problem you're observing

Can't compile from source if debug is enabled

### Describe how to reproduce the problem

```
git clean -dfx;git reset --hard
./autogen.sh
./configure --enable-silent-rules --enable-dependency-tracking --config-cache --enable-linux-builtin --disable-nls --with-config=all --enable-asan --enable-ubsan --enable-debuginfo --enable-debug --enable-debug-kmem --enable-debug-kmem-tracking CFLAGS=-Wno-stringop-overflow
make -j 12 rpm-utils
make -j 12 rpm-dkms
```

### Include any warning/errors/backtraces from the system logs

```
../../module/zfs/dsl_bookmark.c: In function 'dsl_bookmark_create_nvl_validate':
../../module/zfs/dsl_bookmark.c:189:33: error: 'first_len' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  189 |                 switch (*(bmark + first_len)) {
      |                          ~~~~~~~^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [Makefile:1364: dsl_bookmark.lo] Error 1
```

Please excuse me for not sending a PR.

**Comment by nabijaczleweli** [comment]
False positive: `first_len` being initialised is equivalent to `first` being non-null, which would already trigger UB in
```c
		if (strncmp(first, bmark, first_len) != 0)
```
above.

That being said, silencing this is a one-liner, so could you try #13258?
