### ISSUE TITLE
Build issue on Centos 8 Stream + Elrepo kernel-ml 5.17.0 + dkms 3.0.3 for ZFS 2.1.4

### ISSUE THREAD

**Issue by akrherz** [openzfs/zfs#13253]
Thank you for the quick ZFS 2.1.4 release to support kernel 5.17.0.  I gave this combination a try today and ran into a compile failure that I am unsure who to blame, but figured I would document it here for other's benefit.  I suspect this isn't a ZFS issue...

### System information
Type | Version/Name
 --- | ---
Distribution Name	| Centos 8 Stream
Distribution Version	| fully `dnf update`d
Kernel Version	| 5.17.0-1.elrepo
Architecture	| x86_64
OpenZFS Version	| 2.1.4

running `dkms install -m zfs -v 2.1.4 -k 5.17.0-1.el8.elrepo.x86_64` results in:

```
checking whether modules can be built... no
configure: error: 
	*** Unable to build an empty module.
```

```
$ cat /var/lib/dkms/zfs/2.1.4/build/build/conftest/build.log
make: Entering directory '/usr/src/kernels/5.17.0-1.el8.elrepo.x86_64'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if [ "gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)" != ""gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)"" ]; then \'
make: *** [Makefile:1717: prepare] Error 1
make: Target 'modules' not remade because of errors.
make: Leaving directory '/usr/src/kernels/5.17.0-1.el8.elrepo.x86_64'
```

So I needed to do the following patch to the `/usr/src/kernels/5.17.0-1.el8.elrepo.x86_64/Makefile` file

```diff
--- a/Makefile
+++ b/Makefile
@@ -1714,9 +1714,9 @@ PHONY += prepare
 # now expand this into a simple variable to reduce the cost of shell evaluations
 prepare: CC_VERSION_TEXT := $(CC_VERSION_TEXT)
 prepare:
-   @if [ "$(CC_VERSION_TEXT)" != "$(CONFIG_CC_VERSION_TEXT)" ]; then \
+   @if [ "$(CC_VERSION_TEXT)" != $(CONFIG_CC_VERSION_TEXT) ]; then \
        echo >&2 "warning: the compiler differs from the one used to build the kernel"; \
-       echo >&2 " The kernel was built by: $(CONFIG_CC_VERSION_TEXT)"; \
+       echo >&2 " The kernel was built by: "$(CONFIG_CC_VERSION_TEXT); \
        echo >&2 " You are using: $(CC_VERSION_TEXT)"; \
    fi
```

Again, I don't believe this to be a ZFS issue, but figured I would document it here.  Thank you.

**Comment by szubersk** [comment]
@akrherz Would you share also the line from the kernel config containing `CONFIG_CC_VERSION_TEXT`?

**Comment by akrherz** [comment]
> @akrherz Would you share also the line from the kernel config containing `CONFIG_CC_VERSION_TEXT`?

`/usr/src/kernels/5.17.0-1.el8.elrepo.x86_64/.config` has this, if this is what you are asking for.
```
CONFIG_CC_VERSION_TEXT="gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)"
```

**Comment by szubersk** [comment]
Looks normal. I wonder why it get double-quoted.

**Comment by szubersk** [comment]
@akrherz Seems like it's a Kbuild issue introduced in

```
commit 129ab0d2d9f38b9d43df35235fc66c6740d6928b                                                                                                               
Author: Masahiro Yamada <masahiroy@kernel.org>                                                                                                                
Date:   Tue Dec 14 11:53:53 2021 +0900                                                                                                                        
                                                                                                                                                              
    kbuild: do not quote string values in include/config/auto.conf
     
    The previous commit fixed up all shell scripts to not include
    include/config/auto.conf.
     
    Now that include/config/auto.conf is only included by Makefiles,
    we can change it into a more Make-friendly form.
     
    Previously, Kconfig output string values enclosed with double-quotes
    (both in the .config and include/config/auto.conf):
     
        CONFIG_X="foo bar"
     
    Unlike shell, Make handles double-quotes (and single-quotes as well)
    verbatim. We must rip them off when used.
```

Feel free to report it to the kernel developers. I think we could close this ticket as it is not OpenZFS-specific bug.

**Comment by akrherz** [comment]
Cross-referencing posting this to the [ElRepo kernel-ml bug tracker 1215](https://elrepo.org/bugs/view.php?id=1215)

**Comment by madhur** [comment]
I have the same issue while building, Is there any update?

**Comment by szubersk** [comment]
@madhur Did you read this thread?

**Comment by toracat** [comment]
The issue was caused by a bug introduced in kernel 5.17. As mentioned in the referenced ELRepo's bug tracker, the patch needs to be reported upstream at kernel.org. ELRepo builds kernel-ml/lt from the upstream source code without any modifications.

**Comment by toracat** [comment]
Actually someone has already reported the bug with a patch that is basically the same as what @akrherz proposed:

https://lkml.org/lkml/2022/3/7/1896

**Comment by szubersk** [comment]
Thank you @akrherz and @toracat for reporting this problem upstream!

**Comment by toracat** [comment]
As it turned out, the referenced patch in kernel 5.17 triggered an issue that caused failure of external module build. You can find the details in the ELRepo bug tracker. An updated set of kernel-ml that has a fix should be released any minute now.

**Comment by akrherz** [comment]
Thanks all, closing.
