### ISSUE TITLE
zpool remove of log device hangs

### ISSUE THREAD

**Issue by nakermann1973** [openzfs/zfs#13273]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| up-to-date
Kernel Version	| 5.15.26
Architecture	| x86_64
OpenZFS Version	| 2.1.2

### Describe the problem you're observing
When I try to remove my ZIL, the ~~pool hangs, and no longer accepts any I/O~~ command hangs preventing any further pool operations.  Rebooting fixes the problem, but the log remains attached.

```
        logs
          mirror-1                                             ONLINE       0     0     0
            ata-INTEL_SSDSC2BA200G3_BTTV4492017R200GGN-part1   ONLINE       0     0     0
            ata-INTEL_SSDSC2BA200G3T_BTTV332502CA200GGN-part1  ONLINE       0     0     0
```

I have successfully attached and detached individual devices from the ZIL mirror.  I see the issue when trying to remove the mirror, or trying to remove the last remaining device.

### Describe how to reproduce the problem
Run `zpool remove zp0 mirror-1` 

### Include any warning/errors/backtraces from the system logs
I don't see any messages in /var/log/messages, or /var/log/kern

**Comment by rincebrain** [comment]
You could try turning A) turning up the logging by setting `zfs_flags` to a nonzero value, and/or B) doing a DEBUG build with `--enable-debug` to configure (which will make `zfs_flags` default to "almost all the options" on load).

**Comment by nakermann1973** [comment]
I have set `zfs_flags` to `1`, and have also removed one side of the mirror with no issues:

```
# cat /sys/module/zfs/parameters/zfs_flags
1
# zpool status zp0
...
        logs
          ata-INTEL_SSDSC2BA200G3_BTTV4492017R200GGN-part1   ONLINE       0     0     0
...
```

The command `zpool remove zp0 ata-INTEL_SSDSC2BA200G3_BTTV4492017R200GGN-part1` does not return and cannot be cancelled.

Unfortunately, I still see no additional related messages in any of the following:
* /proc/spl/kstat/zfs/dbgmsg
* /var/log/messages
* /var/log/dmesg 
* /var/log/kern.log

Note: /var/log is hosted on an ext4 filesystem, and regular system logs are still posted there.

Also, I have updated my initial diagnosis.  Not all I/O on the pool stops.  Rather, no further actions can be taken on the pool, and this has an effect on docker, causing my containers to start failing health checks.  

`iotop` shows both the `zpool remove` and `[txg_sync]` commands using ~100% io.

I have left it in this state for ~30 minutes.  Should I be waiting longer?

**Comment by nakermann1973** [comment]
I have updated the title to reflect that (a) it is not related to mirrored log devices and (b), the command hangs, but I/O does not stop.

**Comment by rincebrain** [comment]
I wouldn't suggest waiting more than a minute, if that - `zpool remove` on its own shouldn't take more than O(seconds).

**Comment by nakermann1973** [comment]
I will try get some more logs in the next few weeks (when I can tolerate some additional downtime on the host)
