### ISSUE TITLE
DKMS install of 2.1.4 w/ Python 3.10 installed throws python distutils deprecation warnings

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#13280]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| ubuntu
Distribution Version	| jammy
Kernel Version	| 5.17.1
Architecture	| x86_64
OpenZFS Version	| 2.1.4

### Describe the problem you're observing

Python 3.10 shows a python 3.12 deprecation message during a dkms install:
```
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<stdin>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```

### Describe how to reproduce the problem
```
dkms install zfs/2.1.4 -k `uname -r`
```

(This may be related to `ax_python_devel.m4` but updating that to the version in `Autoconf Archive v2022.02.11` breaks the ability of configure to find python.
### Include any warning/errors/backtraces from the system logs
(This is only a cosmetic error at this point.)

**Comment by rincebrain** [comment]
Yes, the one from Autoconf Archive is buggy and makes a number of poor assumptions, [like that string comparison does what we want for version number comparison](https://github.com/openzfs/zfs/commit/08cd0717359b1a18693e3c8e6d6e5a2819b35a48). (IIRC I didn't try to submit how I fixed it here there because I used the `packaging` module to help with the version calculations.)

Since we've ejected pre-3.5 support, this should be a simple update to fix the sysconfig references.

(Also, for completeness, #12833)

**Comment by behlendorf** [comment]
A PR with the required change against the zfs-2.1.5-staging branch would be welcome.

**Comment by rincebrain** [comment]
Apparently not so easy, because while Debian patches their distutils to change the paths to their preferred versions, [they do not patch sysconfig the same way](https://ffy00.github.io/blog/02-python-debian-and-the-install-locations/). Oy.

**Comment by pmwoodward3** [comment]
Just got the same error with 2.1.6 w/ Ubuntu.

**Comment by Reno-Sifana** [comment]
I have a same issue during apt install zfs-dkms on Linux Mint 21.1 (Vera) Cinnamon Edition. Apt install stuck at 85% when i try to install zfs-dkms. luckify Linux Mint have timeshift preinstalled. So i can revert previous state to force uninstall zfs-dkms package.
