### ISSUE TITLE
zfs diff shows original file as deleted when hard link to file is created and deleted between diff points

### ISSUE THREAD

**Issue by evandeaubl** [openzfs/zfs#13283]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| N/A, rolling release
Kernel Version	| 5.17.1-arch1-1
Architecture	| x86_64
OpenZFS Version	| 2.1.4

### Describe the problem you're observing

When I do a `zfs diff` between two snapshots (or a snapshot and the live filesystem), and between those two snapshots, I have created a hard link to a particular file, and then deleted that hard link, `zfs diff` shows the original file as deleted.

This seems to only happen when the original file and the hard link are in separate directories. When the original file and hard link are in the same directory, the original file shows as modified. I'm not entirely convinced that's correct either, but at least the result is plausible given metadata changes under the covers (ideally the original file didn't change, so it shouldn't be showing a mod at all, but I could understand that the information available may make it difficult/impossible to make that determination).

### Describe how to reproduce the problem

```
$ zfs create pool1/test-dataset
$ cd test-dataset
$ mkdir src dest
$ cd src
$ echo "this is a file" >file
$ zfs snapshot pool1/test-dataset@snap1
$ cd ../dest
$ ln ../src/file
$ rm file
$ zfs diff pool1/test-dataset@snap1 pool1/test-dataset
M	/mnt/pool1/test-dataset/dest
-	/mnt/pool1/test-dataset/src/file
$ zfs snapshot pool1/test-dataset@snap2
$ zfs diff pool1/test-dataset@snap1 pool1/test-dataset@snap2
M	/mnt/pool1/test-dataset/dest
-	/mnt/pool1/test-dataset/src/file
```

**Comment by krisjwebb** [comment]
I am having the same problem.  The issue is that ZFS has stored the dnode for the file as the dest/file and once it is removed zfs diff cannot seem to resolve the change properly?
