### ISSUE TITLE
dmu_tx_delay sleeps for an insanely long time

### ISSUE THREAD

**Issue by asomers** [openzfs/zfs#13289]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| stable/13
Kernel Version	| stable/13
Architecture	| amd64
OpenZFS Version	|  zfs-2.1.1-FreeBSD_g71c609852 zfs-kmod-2.1.1-FreeBSD_g71c609852

### Describe the problem you're observing

On some very busy servers `dmu_tx_delay` routinely delays some threads by a very long time, up to three hours.  Typically by the time I notice it there will be half a dozen control path operations (`zfs rename`, `zfs destroy`, `zfs snapshot`, etc) that have been delayed by 40 minutes or so, and a few thousand ordinary writes that have been delayed by an unknown amount of time.  But there _won't_ be any control path operations that have been delayed by less than 40 minutes and more than a few seconds.  It seems that there is a small window of time when operations get insanely delayed, and after that window things proceed as normal.

Here are some typical stacks of delayed processes as shown by procstat.  The `pause_sbt` and `dmu_tx_wait` frames are key:
```
  PID    TID COMM                TDNAME              KSTACK                       
64265 693365 zfs                 -                   mi_switch+0xc1 sleepq_timedwait+0x2f _sleep+0x1ab pause_sbt+0xfe dmu_tx_wait+0x3cc dmu_tx_assign+0x412 spa_history_log_nvl+0x7c spa_history_log+0x35 zfs_ioc_log_history+0xf2 zfsdev_ioctl_common+0x526 zfsdev_ioctl+0x143 devfs_ioctl+0xc6 VOP_IOCTL_APV+0x41 vn_ioctl+0x2d4 devfs_ioctl_f+0x1e kern_ioctl+0x25b sys_ioctl+0xf1 amd64_syscall+0x10c 
85866 353219 XXX                 -                   mi_switch+0xc1 sleepq_timedwait+0x2f _sleep+0x1ab pause_sbt+0xfe dmu_tx_wait+0x3cc dmu_tx_assign+0x412 zfs_write+0x4ee zfs_freebsd_write+0x44 VOP_WRITE_APV+0x9b vn_write+0x28b vn_io_fault_doio+0x43 vn_io_fault1+0x15c vn_io_fault+0x1a4 dofilewrite+0x88 kern_pwritev+0x62 sys_pwrite+0x8b amd64_syscall+0x10c fast_syscall_common+0xf8
```

I used dtrace to prove that   dmu_tx_delay is the culprit.  I made a histogram of the sleep times that it passes to `pause_sbt`.  Note that these are not the same as the delay shown in the sdt:zfs::delay-mintime probe.  Rather, they're the cumulative sum of all of those delays.  The units are in 2**32ths of a second:
```
$ cat ~/dmu-tx-wait.d 
sdt:zfs::delay-mintime
{
        this->trigger = 1;
}
fbt:kernel:pause_sbt:entry
/this->trigger == 1/
{
        @sbt = quantize(args[1]);
}
fbt:zfs:dmu_tx_wait:return
{
        this->trigger = 0;
}
```
```
           value  ------------- Distribution ------------- count    
               0 |                                         0        
               1 |                                         1        
               2 |                                         0        
               4 |                                         0        
               8 |                                         0        
              16 |                                         0        
              32 |                                         0        
              64 |                                         0        
             128 |                                         0        
             256 |                                         0        
             512 |                                         0        
            1024 |                                         0        
            2048 |                                         0        
            4096 |                                         0        
            8192 |                                         1        
           16384 |                                         1        
           32768 |                                         5        
           65536 |                                         3        
          131072 |                                         15       
          262144 |                                         33       
          524288 |                                         115      
         1048576 |                                         332      
         2097152 |                                         1767     
         4194304 |                                         7924     
         8388608 |@                                        15011    
        16777216 |@                                        17574    
        33554432 |@                                        22097    
        67108864 |@                                        25260    
       134217728 |@@@                                      54019    
       268435456 |@@@                                      57017    
       536870912 |@@@                                      59009    
      1073741824 |@@@@@                                    78969    
      2147483648 |@@@@@@@@                                 127177   
      4294967296 |@@@@@@@@@@@@                             204807   
      8589934592 |                                         0        
     17179869184 |                                         0        
     34359738368 |                                         0        
     68719476736 |                                         0        
    137438953472 |                                         0        
    274877906944 |                                         0        
    549755813888 |                                         0        
   1099511627776 |                                         0        
   2199023255552 |                                         0        
   4398046511104 |                                         0        
   8796093022208 |                                         0        
  17592186044416 |                                         3522     
  35184372088832 |                                         0 
```
As you can see, the mode is about 1 second.  That's still pretty long, but nowhere near as long as the outliers, which are sleeping for about 4096 seconds.

### Describe how to reproduce the problem

Unfortunately I can't reproduce it on any non-production system.  The production systems have a very busy and complicated workload involving tons of `zfs recv`, `zfs rename`, `zfs snapshot`, `zfs destroy`, and plenty of ordinary reads and writes too.  In most cases the pools are fairly full, but I've also seen it on pools that were only 80% full.

**Comment by rincebrain** [comment]
If I understand this correctly, it's accumulating all the `pause_sbt`s that happen between entering `dmu_tx_delay` for the first time and finally getting out of `dmu_tx_wait`, yes?

Do you have any data on the distribution of the individual calls?

Assuming you get a couple of large waits, my only immediate guess for how you could end up waiting that long, reading over both, is if `tx_start` or `dp_last_wakeup` come in with some impossibly large value, since we don't really validate the contents of either before taking the MAX between them for when we sleep, and the amount we're adding to either seems pretty well bounded. So I'd go peer into those and see if they occasionally come back with impossibly huge values too.

(If you're getting a billion small waits, my count of ideas goes from 1 to 0.)

(Normally I'd jut go try to reproduce it myself, rather than just suggesting things unsolicited, but I don't have a bunch of spare spinning disks to make a mostly-full pool churning recvs on FBSD right now...)

**Comment by asomers** [comment]
By "distribution of the individual calls" are you referring to the fact that `pause_sbt` might be called multiple times for each `dmu_tx_delay`?  No, but I just added that to my dtrace script.  We'll see what it comes up with.  I don't see any way for `dp_last_wakeup` to get set to some weird value unless it's by a dangling pointer.  And in any case I can't easily trace it, because it needs to be compared to `now`, which isn't a function argument.  Ditto for `tx_start`.  What if `dirty` were greater than `zfs_dirty_data_max`?  That could cause `min_tx_time` to go negative.  Hm no I don't think that would do it either.  Unless I add a new SDT probe, my best hope now would be to track successive values of `tx_start` to see if they jump by a large amount.  But I don't know how to do that with dtrace.  Is it possible to create a global variable in a D script?

**Comment by rincebrain** [comment]
I was assuming that the resulting value would be significantly different from the normal values of "now" to be visible on a histogram, but thinking about it, that would only be true if it were a short time window.

I did mean that assuming `pause_sbt` might be called multiple times, as I assumed that was why you were probing that way, but no, that's just a dance to only catch `pause_sbt` calls from that caller, I was just confused because you're catching return of `dmu_tx_wait`, and I would have expected it to be `dmu_tx_delay` if that was the intent.

Yeah, I don't see a reasonable way for tx_start to get mis-set unless the system time jumped backward a large value or we were passed a nonsense struct pointer, given that it's set once, AFAICT.

I was, admittedly, assuming that the mintime probe was reporting all small values if you were probing yourself and not just citing it coming back reporting enormous wait times.

I'm not sure what "successive" would necessarily mean here - I believe you can define non-local-thread variables, but usually you'd want that to be indexed against something like pid/tid/... otherwise you'd just end up rapidly stepping on each other if multiple threads of execution happen at once, right?

I believe you can do something like `@lasttime[cpu] = val1;`, or even `lasttime = val1;` if you really want it global, but it's been a while since I wrote DTrace probes much. :)

**Comment by asomers** [comment]
> I did mean that assuming `pause_sbt` might be called multiple times, as I assumed that was why you were probing that way, but no, that's just a dance to only catch `pause_sbt` calls from that caller, I was just confused because you're catching return of `dmu_tx_wait`, and I would have expected it to be `dmu_tx_delay` if that was the intent.

Ahh, that's just because `dmu_tx_delay` got inlined, and does not have an fbt probe.

**Comment by asomers** [comment]
Ooh, dtrace revealed that sometimes `dirty` _is_ greater than `zfs_dirty_data_max`.  At least 32 MB greater, somtimes. According to the assertion, disabled in release builds, that's not supposed to happen.

**Comment by rincebrain** [comment]
Oh boy.

That seems like a simple conditional to cap, at least, in addition to being
a bug that it can happen.

**Comment by asomers** [comment]
> Ooh, dtrace revealed that sometimes `dirty` _is_ greater than `zfs_dirty_data_max`. 

That was wrong.  It was just me interpreting dtrace incorrectly.

The actual cause of the bug was a time conversion error in FreeBSD.  If dmu_tx_delay tried to sleep for anywhere from 2s to 4295s, it would actually sleep for 0s - 2s.  That interacted badly with the throttle in dmu_tx_delay.  What happened was that writes came in fast enough to keep the dirty data persistently above the soft limit of `delay_min_bytes` and getting very close to `zfs_dirty_data_max`.  So dmu_tx_delay tried to delay threads for very close to `zfs_delay_max_ns` (100ms).  But ZFS was still processing far more than 10 IOPs.  So the accumulated delay, in the `wakeup` variable, grew very large without having much effect.  Suddenly, once `wakeup` reached 4295s, the sleep began working as intended.  Then, many threads suddenly found themselves in a long uninterruptible sleep.  But quickly the amount of dirty data fell, so new threads didn't get delayed at all.

Fixing the time conversion should definitely fix the bug, though I'll still need a few weeks of runtime to be confident.  I'm also disabling the dmu_tx_delay entirely by setting `zfs_delay_min_dirty_percent` to 100.  I really don't understand the rationale for that function.

And FTR the bug technically affects older FreeBSD versions too.  But until release 13.0, the code was different, with the result that the bug could only be triggered within 4 seconds of boot.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263073
