### ISSUE TITLE
5.18-rc2 build fails due to default_attrs being changed to default_groups

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#13319]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04
Kernel Version	| 5.18-rc2
Architecture	| x86_64
OpenZFS Version	| 2.1.4 (with all patches available for 5.18 support to date)

### Describe the problem you're observing

https://github.com/torvalds/linux/commit/cdb4f26a63c391317e335e6e683a614358e70aeb removes the `default_attrs` pointer used by `os/linux/zfs/zfs_sysfs.c`:
```
kobject: kobj_type: remove default_attrs
Now that all in-kernel users of default_attrs for the kobj_type are gone
and converted to properly use the default_groups pointer instead, it can
be safely removed.
```

A dkms build fails thusly:
```
zfs_sysfs.c: In function ‘zfs_kobj_init’:
build/module/zfs/../os/linux/zfs/zfs_sysfs.c:188:29: error: ‘struct kobj_type’ has no member named ‘default_attrs’
  188 |         zkobj->zko_kobj_type.default_attrs = zkobj->zko_default_attrs;
      |                             ^
```

**Comment by thesamesam** [comment]
Duplicate of https://github.com/openzfs/zfs/pull/13357

**Comment by satmandu** [comment]
And also fixed by https://github.com/openzfs/zfs/pull/13369
