### ISSUE TITLE
zpool scrub detects CKSUM errors, but no dmesg details and might not update (error files list) status -v

### ISSUE THREAD

**Issue by mjevans** [openzfs/zfs#13313]
Distribution Name	| Arch Linux
Distribution Version	| rolling
Kernel Version	| 5.17.1-arch1-1
Architecture	| amd64 / x86-64 (an Intel model CPU)
OpenZFS Version	| 2.1.4-1

Yes, ECC RAM, and no dmesg to suspect underlying hardware issues (the only suspicious entry is related to perf).

I recently rsynced from an old ZFS pool to a new ZFS pool; and then (wisely after experience) scrubbed immediately.

One file was listed as corrupted, so remove the file, resync, should scrub clean, right?

Wrong.

Subsequent scrubs reported more CKSUM errors across all disks in the pool.

Since I rsycned the files over I had a rough idea of where the issue had happened, and tried to move the entire subtree around.  An additional read error (and corrupted file) was only found THEN.

I'd already scrubbed the pool at least 3x by this point, and the file in question was not discovered as corrupted until accessed by a userspace program.

Why would zpool clear NAME ; zpool scrub NAME show checksum errors but not list additional corrupted files?
Also, why doesn't a CKSUM error get added to the dmesg log along with the file(s) it includes as well as the involved block devices and sectors?

```syslog
[ 2586.518786] perf: interrupt took too long (2503 > 2500), lowering kernel.perf_event_max_sample_rate to 79800
[ 3923.194839] perf: interrupt took too long (3133 > 3128), lowering kernel.perf_event_max_sample_rate to 63600
[ 8614.519802] perf: interrupt took too long (3958 > 3916), lowering kernel.perf_event_max_sample_rate to 50400
[68004.340857] perf: interrupt took too long (4949 > 4947), lowering kernel.perf_event_max_sample_rate to 40200
```

**Comment by rincebrain** [comment]
Flooding dmesg with checksum errors seems like it would be of limited benefit, given the numbers of them that sometimes occur.

What's the pool layout? What model(s) of disk, storage controller, and anything else in-between (e.g. LUKS or something else)? What are the dataset settings?

IME if scrub keeps finding new errors on successive operations, something is terribly broken, since scrub checks ~everything each time - either the checksum calculations are screwing up, or parity, or something in the storage IO path is mangling things...the list of options gets messier and messier.

**Comment by mjevans** [comment]
Looking at the output from zpool events -v I can see why you say dumping these to dmesg would get very chatty.

zpool status -v might mention the zpool events command for further details.

```
# zpool events -v NEWPOOL
TIME                           CLASS
#
# zpool events -v OLDPOOL
TIME                           CLASS
#
# zpool events -v
... ereport.fs.zfs.checksum
```

Before I go crazy about something (I just double-checked the zpool creation command I used) is there a better page than the manual page that describes the keys in that key value list?  I see 'vdev_ashift = 0x9' which would be the drive's emulated sector size rather than the ashift=12 value the pool was created with (which is also listed in zpool get ashift)?  Reading man zpool-events only says "the ashift value of the vdev", which is no more clear than the key name.

Here's the most recent event I found with anything that seems uniquely identifying or worthless redacted.

```
Apr  9 2022 21:28:58.130142053 ereport.fs.zfs.checksum
        class = "ereport.fs.zfs.checksum"
        ena = REDACTED
        detector = (embedded nvlist)
                version = 0x0
                scheme = "zfs"
                pool = REDACTED
                vdev = REDACTED
        (end detector)
        pool = "NEWPOOL"
        pool_guid = REDACTED
        pool_state = 0x0
        pool_context = 0x0
        pool_failmode = "wait"
        vdev_guid = REDACTED
        vdev_type = "disk"
        vdev_path = "/dev/disk/by-partlabel/REDACTED"
        vdev_ashift = 0x9
        vdev_complete_ts = 0x3e06d3db11ba
        vdev_delta_ts = 0xb4a28
        vdev_read_errors = 0x0
        vdev_write_errors = 0x0
        vdev_cksum_errors = 0x8
        vdev_delays = 0x0
        parent_guid = REDACTED
        parent_type = "raidz"
        vdev_spare_paths = 
        vdev_spare_guids = 
        zio_err = 0x34
        zio_flags = 0x100880
        zio_stage = 0x200000
        zio_pipeline = 0x1f00000
        zio_delay = 0x0
        zio_timestamp = 0x0
        zio_delta = 0x0
        zio_priority = 0x0
        zio_offset = 0x8a3fafb000
        zio_size = 0x1a000
        zio_objset = 0x36
        zio_object = 0x3c522
        zio_level = 0x0
        zio_blkid = 0x14e9
        time = 0x62525d0a 0x7c1cf65 
        eid = 0x4b
```

This is the same object that previously had a filename, two actually since it was hard-linked, and was deleted after the first scrub.

```
# zdb -d NEWPOOL 0x3c522
Dataset mos [META], ID 0, cr_txg 4, 346M, 11229 objects

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
zdb: dmu_object_info() failed, errno 2
```

**Comment by rincebrain** [comment]
You could examine `zdb -l [the partition that ZFS is on on one disk in the vdev]` or just `zdb -L [pool]` if it's imported to see what the status is according to the labels.

Can you share what the `zpool create` command used according to `zpool history | head -n 2` was?

Generally, if `zpool events` says the ashift of the vdev is 9, I would believe it.

You probably would like `zdb -d NEWPOOL/0x36 0x3c522` to peer into it - object IDs are per-dataset/objset.

I'm still curious whether any of your events have the fields I mentioned for checksum error patterns.

**Comment by mjevans** [comment]
```
zpool create -o ashift=12 -o feature@zstd_compress=enabled -o feature@skein=enabled -o feature@large_blocks=enabled -m /mouth/path POOLNAME raidz2  /dev/disk/by-partlabel/... 12 different times

zdb -l /dev/disk/by-partlabel/(random member vdev) | grep shift
        metaslab_shift: 34
        ashift: 12

zdb -d NEWPOOL/0x36 0x3c522
Dataset `NEWPOOL` [ZPL], ID 54, cr_txg 1, REDACTED objects

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
zdb: dmu_object_info() failed, errno 2
```

There aren't any snapshots or multiple datasets, so the same details don't surprise me, what does surprise me is this file sticking around in the corrupted files list of zpool status -v; I assume it only clears that list when there are no CKSUM errors, which is what was so aggravating about other entries not being added.

**Comment by mjevans** [comment]
Update from after the most recent scrub finished overnight, after removing the _second_ file (also multiple hard-links).

Zero CKSUM errors, everything worked as expected.  So it was a second bad file, that the previous scrubs didn't list but userspace (rsync) access discovered when ZFS refused to read the file.  Somewhat fortunately I've resolved my test case on this issue.

**Comment by mjevans** [comment]
The title of this bug is still correct.  A second file was corrupt and not listed in zpool status -v; but was caught by checksum errors (even after the first file had been deleted and restored).

To anyone else landing on this with a similar issue: attempt any userspace IO operation on your files, even a weak checksum creation routine like a crc/sfv/md5sum.  That will force ZFS to identify any corrupt files not updated in the pool list for any reason.

I also had reason to reboot my home server today and checked some BIOS settings.  It seems that years ago I must have loaded performance defaults and not checked thoroughly.  Both Spread Spectrum, and worse, Intel's Turbo Boost were enabled.  Extremely tentatively I will assume the root cause of the initial data corruption was a bit-flip in a register or during processing.  My rebuilt array uses a larger configuration as well as zstd (default, 3?) compression and might have pushed the CPU a tiny bit harder than the previous configuration.

**Comment by rincebrain** [comment]
FWIW, I would suspect it is less that scrub didn't notice and that it was not flipped when scrub read it, but flipped when you read it later, since there's not really any data scrub doesn't try checking, to the best of my knowledge. (I'm not going to claim it's impossible for scrub to have bugs, but I would lean toward it being wrong once and right once over wrong on disk and overlooked, in this case.)
