### ISSUE TITLE
MySQL's ib_logfile1 cannot be created properly

### ISSUE THREAD

**Issue by tomposmiko** [openzfs/zfs#13329]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Ubuntu
Distribution Version	|  22.04 and 18.04
Kernel Version	|  5.15 and 5.4
Architecture	| amd64
OpenZFS Version	| zfs-2.1.2-1ubuntu3 and zfs-2.1.4-0york0~18.04

### Describe the problem you're observing
I'm not sure, if it's caused by ZFS, though its probability is quite high.

If I start Percona MySQL Server 8.0 backed with ZFS, I get the following error:
```
2022-04-14T21:10:15.443147Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.27-18) starting as process 2259
2022-04-14T21:10:15.463221Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-04-14T21:10:15.547437Z 1 [ERROR] [MY-012963] [InnoDB] Log file ./ib_logfile1 is of different size 0 bytes than other log files 17793024 bytes!
2022-04-14T21:10:15.547485Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Generic error.
2022-04-14T21:10:16.534037Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2022-04-14T21:10:16.534204Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2022-04-14T21:10:16.534296Z 0 [ERROR] [MY-010119] [Server] Aborting
```

### Describe how to reproduce the problem
Create a dataset with recent ZFS version, get it mounted to /var/lib/mysql and initialize a database instance on it (eg. `apt install percona-server-server`). Version 5.7 works properly.
I tested Percona only, did not test classic MySQL.

I am pretty sure, it worked with a previous version from York's repository, just don't know, which was that, because I restarted that machine with the recent version.
MySQL works well if the database is created somewhere else, eg. on xfs or ext4 and migrated to ZFS.

**Comment by tomposmiko** [comment]
The version, that worked properly was probably `2.1.1-0york0~20.04`. I just don't know, how should I test it, because that version is already not in that repository.

**Comment by rincebrain** [comment]
Maybe fallout from #12724, as a wild guess?

You could adjust the tunable mentioned in there - I think it's the case that `dmu_offset_next_sync` defaults to 0 and was planned to be 1 in 2.1.5... - and try again?

**Comment by tomposmiko** [comment]
```
root@csepcsop:~# echo 1 > /sys/module/zfs/parameters/zfs_dmu_offset_next_sync
root@csepcsop:~# 
```
And it still the same.

**Comment by rincebrain** [comment]
My three guesses were either the aforementioned thing, they're checking the filesize too soon after creating the file in some exciting fashion (ZFS will, IIUC, actually tell you it's 0 bytes until it winds up flushed out, which can surprise the hell out of things which expect otherwise despite not having forced it to sync), or some as-yet-unknown bug in either Percona or ZFS.

You could try fiddling with innodb_use_native_aio in Percona, and if that works, then we have somewhere specific to focus on; otherwise, I'll see about testing it when I get a chance, though I personally am likely to be busy the next couple days.

**Comment by tomposmiko** [comment]
[log.tar.gz](https://github.com/openzfs/zfs/files/8494007/log.tar.gz)

I attached the strace output of `mysqld --user=mysql` after removing ib_logfile* files.

**Comment by rincebrain** [comment]
The above appears to be a different error from the one you mentioned before:
```
write(2, "2022-04-15T04:50:15.111962Z 1 [ERROR] [MY-012642] [InnoDB] Tried to read 65536 bytes at offset 17792000, but was only able to read 512 of FD 8, filename /var/lib/mysql/ib_logfile0\n", 180) = 180
mprotect(0x7f13ba67d000, 4096, PROT_READ|PROT_WRITE) = 0
write(2, "2022-04-15T04:50:15.112038Z 1 [ERROR] [MY-012592] [InnoDB] Operating system error number 2 in a file operation.\n", 112) = 112
write(2, "2022-04-15T04:50:15.112101Z 1 [ERROR] [MY-012593] [InnoDB] The error means the system cannot find the path specified.\n", 118) = 118
mprotect(0x7f13ba67e000, 8192, PROT_READ|PROT_WRITE) = 0
write(2, "2022-04-15T04:50:15.112159Z 1 [ERROR] [MY-012594] [InnoDB] If you are installing InnoDB, remember that you must create directories yourself, InnoDB does not create them.\n", 170) = 170
write(2, "2022-04-15T04:50:15.112195Z 1 [ERROR] [MY-012646] [InnoDB] File ./ib_logfile0: 'read' returned OS error 71. Cannot continue operation\n", 134) = 134
mprotect(0x7f13ba680000, 4096, PROT_READ|PROT_WRITE) = 0
write(2, "2022-04-15T04:50:15.112254Z 1 [ERROR] [MY-012981] [InnoDB] Cannot continue operation.\n", 86) = 86
```

**Comment by tomposmiko** [comment]
Now I am a bit confused. So I deleted the mysql datadir.
And ran from scratch:

`strace -ff -s 388888 -o /root/1/log mysqld --initialize --user=mysql`
` strace -ff -s 388888 -o /root/2/log mysqld --user=mysql`
log:
```
2022-04-15T05:26:03.617017Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.27-18) initializing of server in progress as process 1649
2022-04-15T05:26:03.641552Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-04-15T05:26:05.021629Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-04-15T05:26:06.828908Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2022-04-15T05:26:06.828946Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2022-04-15T05:26:06.887280Z 6 [Note] [MY-010454] [Server] A temporary password is generated for root@localhost: BgJ(qe<wh1#p
2022-04-15T05:28:25.055731Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.27-18) starting as process 1762
2022-04-15T05:28:25.080524Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-04-15T05:28:25.192897Z 1 [ERROR] [MY-012963] [InnoDB] Log file ./ib_logfile1 is of different size 0 bytes than other log files 17793024 bytes!
2022-04-15T05:28:25.192975Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Generic error.
2022-04-15T05:28:26.172563Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2022-04-15T05:28:26.172802Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2022-04-15T05:28:26.172914Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-04-15T05:28:26.173413Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.27-18)  Percona Server (GPL), Release '18', Revision '24801e21b45'.
```
strace files:

[init.tar.gz](https://github.com/openzfs/zfs/files/8494072/init.tar.gz)
[run.tar.gz](https://github.com/openzfs/zfs/files/8494074/run.tar.gz)

**Comment by tomposmiko** [comment]
Also tried with this setting:

```
root@b:/var/lib/mysql# cat /sys/module/zfs/parameters/zfs_dmu_offset_next_sync 
1
```
It can be changed online, right?

**Comment by rincebrain** [comment]
Sure, changing it online should do the right thing - it certainly did in testing the fix before.

**Comment by tomposmiko** [comment]
I also tested it with `innodb_use_native_aio` on and off, the outcome is the same as well as with classic mysql from ubuntu (so no percona is needed).

**Comment by rincebrain** [comment]
Having gone digging, this really seems like the case in #12745, but that should really be dealt with correctly in 2.1.3 and 2.1.4 (though, notably, not in 2.1.2).

So are you absolutely sure both userland and kernel module are 2.1.4 when you're testing?

**Comment by tomposmiko** [comment]
So no double checking and more confirmation needed?

**Comment by rincebrain** [comment]
Not particularly, no, probably until someone comes up with a good solution.

Excitingly, it reproduces on git master (0dd34a1955b06cdea460f2f1711b72536a5a511b).

CC @behlendorf since he wrote the original fix, I'm not sure I'll have time to look into this myself in the next couple days, and "MySQL on ZFS isn't working sometimes" seems bad - tl;dr it seems like doing `mysqld --initialize` with /var/lib/mysql as a ZFS dataset on at least Ubuntu is producing things that smell awfully like the later bugs in #11900 - on my 20.04 testbed, `ib_logfile0` is ending up variable sizes on different runs and failing on startup because they're not multiples of pagesize, and even if that succeeds, `ib_logfile1` is ending up 0b...

**Comment by tomposmiko** [comment]
thanks so much for your efforts!

**Comment by rincebrain** [comment]
A couple of data points.

* Someone on IRC reported they couldn't reproduce it with the official MySQL Docker images (based on Debian 10, it looks like) running 8.0.27-1debian10 on a Gentoo host and 5.15.32 kernel.
* On stock Debian 11 running 5.10.0-13-amd64, 2.1.4 works fine with MariaDB but fails with Percona MySQL 8.0.27-18-1.bullseye and MySQL 8.0.28-1debian11.
* Fails with `zfs_dmu_offset_next_sync`=0 or 1, as the reporter said.

**Comment by rincebrain** [comment]
Okay, I'm about to turn into a pumpkin for most of the day at least, but this corrects the problem at a glance, though it hasn't been run through the test suite yet or had a test added for this failure mode...

https://github.com/rincebrain/zfs/commit/c03b64c10be97f000be7a4cd40c3011ef5ad8c60

**Comment by panlinux** [comment]
Maybe I missed it in the above conversation, but this seems to be a simple reproducer and easy checker.

Working:
```
root@nsn7:~# touch foo.img
root@nsn7:~# fallocate -z -l 10M foo.img
root@nsn7:~# l foo.img 
-rw-r--r-- 1 root root 10M abr 18 15:12 foo.img
```

Incorrect:
```
root@j1:~# touch foo.img
root@j1:~# fallocate -z -l 10M foo.img
root@j1:~# ll foo.img 
-rw-r--r-- 1 root root 0 Apr 18 18:06 foo.img
```

**Comment by rincebrain** [comment]
You will find something very much like that in the new test case in the
linked PR.

**Comment by tomposmiko** [comment]
@rincebrain Do you have any information on the release date?

**Comment by behlendorf** [comment]
We don't expect to tag 2.15 for a month or so.  However, it may be cherry-picked in to the Ubuntu release sooner, https://github.com/openzfs/zfs/pull/13338#issuecomment-1104121635.

**Comment by tomposmiko** [comment]
What's the release policy, when do you release a new version?


Unfortunately, I still need to stay on Bionic for a while.
So ppa is in use:
https://launchpad.net/~jonathonf/+archive/ubuntu/zfs.

@jonathonf my understanding is that you do not cherry pick commits, just automatically build packages upon github releases. Is that correct? Or would you mind include this fix?

**Comment by stevenj** [comment]
I just hit this issue.  As a temporary workaround until 2.1.5 drops, I made a sparse zvol, partitioned it and formatted it as ext4.  MySQL works properly in this configuration.

**Comment by Eurythmax** [comment]
@stevenj can you give me some guide for your temp fix? I would need that too. 

Installing this didnt helped me: https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/4831

**Comment by stevenj** [comment]
@Eurythmax Something like:
1. Make a sparse zvol:  `# zfs create -s -V 50g tank/vol0`
This will make a new disk device, such as `/dev/zd0`
2. Partition it like: `parted /dev/zd0`  
And you just partition it for EXT4 as if it was a physical drive.  This will create a partitioned device like `/dev/zd0p1`
3. Now you can format it with ext4 like so: `mkfs.ext4 /dev/zd0p1`
And if you want to mount it every boot:
4. Add to `/etc/fstab` : `/dev/zd0p1        /ext4-zvol   ext4   defaults                                 0 0`

Its hard to be specific because your setup will not be the same as mine, but this should give you the general idea.  All the real work is in step 1.  This is just carving up some of your zpool into a new raw block device, which you can use just like any other raw block device.  Except its not raw, its got all the redundancy/configuration of the underlying pool.  The size you specify there is the maximum size, the `-s` option says, don't reserve all that space up front.  You won't waste more pool space than the underlying data in the DB uses (plus some overhead).

Normally i wouldn't ever do this.  There is no value (to me in general day to day use) to NOT using zfs for the filesystem.  But for testing, or workarounds like this, its pretty handy.  Its also handy for giving a disk device to a VM.

**Comment by artw** [comment]
Just hit this bug too.  This worked `truncate -s 128M /var/lib/mysql/ib_logfile*`

**Comment by kamzata** [comment]
> fallocate -z -l 10M foo.img

Thanks but nothing's changed.

```
 ⌁ root  ~  1  apt update && apt full-upgrade
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up mysql-server-8.0 (8.0.29-0ubuntu0.22.04.2) ...
Renaming removed key_buffer and myisam-recover options (if present)
Warning: Unable to start the server.
Job for mysql.service failed because the control process exited with error code.
See "systemctl status mysql.service" and "journalctl -xeu mysql.service" for details.
invoke-rc.d: initscript mysql, action "start" failed.
● mysql.service - MySQL Community Server
     Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-05-30 16:06:43 CEST; 3ms ago
    Process: 1342 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
    Process: 1350 ExecStart=/usr/sbin/mysqld (code=exited, status=1/FAILURE)
   Main PID: 1350 (code=exited, status=1/FAILURE)
     Status: "Server startup in progress"
      Error: 22 (Invalid argument)
        CPU: 271ms
dpkg: error processing package mysql-server-8.0 (--configure):
 installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-8.0; however:
  Package mysql-server-8.0 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-8.0
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by kamzata** [comment]
> Just hit this bug too. This worked `truncate -s 128M /var/lib/mysql/ib_logfile*`

Thanks but nothing's changed.

```
 ⌁ root  ~  1  apt update && apt full-upgrade
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up mysql-server-8.0 (8.0.29-0ubuntu0.22.04.2) ...
Renaming removed key_buffer and myisam-recover options (if present)
Warning: Unable to start the server.
Job for mysql.service failed because the control process exited with error code.
See "systemctl status mysql.service" and "journalctl -xeu mysql.service" for details.
invoke-rc.d: initscript mysql, action "start" failed.
● mysql.service - MySQL Community Server
     Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-05-30 16:06:43 CEST; 3ms ago
    Process: 1342 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
    Process: 1350 ExecStart=/usr/sbin/mysqld (code=exited, status=1/FAILURE)
   Main PID: 1350 (code=exited, status=1/FAILURE)
     Status: "Server startup in progress"
      Error: 22 (Invalid argument)
        CPU: 271ms
dpkg: error processing package mysql-server-8.0 (--configure):
 installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-8.0; however:
  Package mysql-server-8.0 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-8.0
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by NakaTheShifu** [comment]
Hi, would like to note that this bug is also experienced on Proxmox 7.2-4, with the following packages.

```
❯ apt list --installed | grep zfs
libzfs4linux/stable,stable,now 2.1.4-pve1 amd64 [installed,automatic]
zfs-initramfs/stable,stable,now 2.1.4-pve1 all [installed]
zfs-zed/stable,stable,now 2.1.4-pve1 amd64 [installed]
zfsutils-linux/stable,stable,now 2.1.4-pve1 amd64 [installed]
```

**Comment by kamzata** [comment]
> Hi, would like to note that this bug is also experienced on Proxmox VE 7.2-4, with the following packages.
> 
> ```
> ❯ apt list --installed | grep zfs
> libzfs4linux/stable,stable,now 2.1.4-pve1 amd64 [installed,automatic]
> zfs-initramfs/stable,stable,now 2.1.4-pve1 all [installed]
> zfs-zed/stable,stable,now 2.1.4-pve1 amd64 [installed]
> zfsutils-linux/stable,stable,now 2.1.4-pve1 amd64 [installed]
> ```
> 
> > Just hit this bug too. This worked `truncate -s 128M /var/lib/mysql/ib_logfile*`
> 
> Would confirm that this works only **for the first time** on database startup, but fails to work on restart.

The trick doesn't work anymore after mysql has been upgraded in Ubuntu 22.04 LXC container.

**Comment by nicodier** [comment]
Just noticed this bug when my Ubuntu LXC's upgraded the MySQL package tonight. I'm on Proxmox 7.2-7 (Linux pve2 5.15.39-2-pve #1 SMP PVE 5.15.39-2 (Wed, 20 Jul 2022 17:22:19 +0200) x86_64 GNU/Linux) hypervisor with:
libzfs4linux/stable,now 2.1.5-pve1 amd64 [installed,automatic]
zfs-initramfs/stable,now 2.1.5-pve1 all [installed]
zfs-zed/stable,now 2.1.5-pve1 amd64 [installed]
zfsutils-linux/stable,now 2.1.5-pve1 amd64 [installed]


`2022-07-29T08:13:25.733986Z 1 [ERROR] [MY-012962] [InnoDB] The redo log file ./#innodb_redo/#ib_redo5 size 2940928 is not a multiple of innodb_page_size`

Temporary fix for me:
`apt dist-upgrade
Do you want to continue? [Y/n] 
Setting up mysql-server-8.0 (8.0.30-0ubuntu0.20.04.2) ...
mysqld will log errors to /var/log/mysql/error.log
mysqld is running as pid 2836797
dpkg: error processing package mysql-server-8.0 (--configure):
 installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-8.0; however:
  Package mysql-server-8.0 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-8.0
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)


# truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo5
# ls -lh /var/lib/mysql/#innodb_redo/#ib_redo5
-rw-r----- 1 mysql mysql 48M Jul 29 10:50 /var/lib/mysql/#innodb_redo/#ib_redo5
# truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo0


Do you want to continue? [Y/n] 
Setting up mysql-server-8.0 (8.0.30-0ubuntu0.20.04.2) ...
mysqld will log errors to /var/log/mysql/error.log
mysqld is running as pid 2837347
Skipping profile in /etc/apparmor.d/disable: usr.sbin.mysqld
Setting up mysql-server (8.0.30-0ubuntu0.20.04.2) ...

`

**Comment by obazda20** [comment]
@nicodier 
I've the same issue and cant fix it. And i rolled back to 8.0.29. Please Try to restart your database. 

I got an error like

'The redo log file ./#innodb_redo/#ib_redo0 is smaller than 65536 bytes, which indicates it was not generated by InnoDB or become corrupted. Please restore the correct file.' 

my zfs is not compressed and upgraded to zfs-2.1.5

**Comment by artw** [comment]
Guys, the workaround is to truncate (resize) all files to the size that mysql is ok with. Worked for me more than 10 times already

**Comment by nicodier** [comment]
@obazda20 please delete  ./#innodb_redo/#ib_redo0  if it is smaller than  65536 bytes. afterwards restart mysql, then it will throw another error, you should now truncate it to 48M and restart mysql again. This worked for me.

**Comment by kamzata** [comment]
This worked for me:

```
truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo*
```

**Comment by lflare** [comment]
With ZFS 1.2.5, you only need to truncate it back to size once, and it should work on subsequent restarts

> Just noticed this bug when my Ubuntu LXC's upgraded the MySQL package tonight. I'm on `Proxmox 7.2-7 (Linux pve2 5.15.39-2-pve #1 SMP PVE 5.15.39-2 (Wed, 20 Jul 2022 17:22:19 +0200) x86_64 GNU/Linux)` hypervisor with: libzfs4linux/stable,now 2.1.5-pve1 amd64 [installed,automatic] zfs-initramfs/stable,now 2.1.5-pve1 all [installed] zfs-zed/stable,now 2.1.5-pve1 amd64 [installed] zfsutils-linux/stable,now 2.1.5-pve1 amd64 [installed]
> 
> `2022-07-29T08:13:25.733986Z 1 [ERROR] [MY-012962] [InnoDB] The redo log file ./#innodb_redo/#ib_redo5 size 2940928 is not a multiple of innodb_page_size`
> 
> Temporary fix for me:
> 
> apt dist-upgrade Do you want to continue? [Y/n] Setting up mysql-server-8.0 (8.0.30-0ubuntu0.20.04.2) ... mysqld will log errors to /var/log/mysql/error.log mysqld is running as pid 2836797 dpkg: error processing package mysql-server-8.0 (--configure): installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1 dpkg: dependency problems prevent configuration of mysql-server: mysql-server depends on mysql-server-8.0; however: Package mysql-server-8.0 is not configured yet.
> 
> dpkg: error processing package mysql-server (--configure): dependency problems - leaving unconfigured Errors were encountered while processing: mysql-server-8.0 mysql-server E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
> `# truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo5` `# truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo0`
> 
> apt dist-upgrade Do you want to continue? [Y/n] Setting up mysql-server-8.0 (8.0.30-0ubuntu0.20.04.2) ... mysqld will log errors to /var/log/mysql/error.log mysqld is running as pid 2837347 Skipping profile in /etc/apparmor.d/disable: usr.sbin.mysqld Setting up mysql-server (8.0.30-0ubuntu0.20.04.2) ...

Check that you are actually running ZFS 2.1.5. Updating it alone isn't enough I believe, you have to reboot the system too.

```bash
❯ zfs version
zfs-2.1.5-pve1
zfs-kmod-2.1.5-pve1
```

**Comment by sk0le** [comment]
So, im noob, right, and sorry if this is not good enough of explanation.

I've bought VPS, with ubuntu 20.04, it has ZFS as file system, and i cannot install mysql
I used this command:
```
truncate -s 48M /var/lib/mysql/#innodb_redo/#ib_redo*
```
And when i restart it works, its active.
But when i try to lets say, install git with sudo apt install git
I get this message:
```
 installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-8.0; however:
  Package mysql-server-8.0 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-8.0
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
And I've been trying to make this work for 2 days now, so if anyone would help me, it would be perfect.

**Comment by sk0le** [comment]
Hi, im new to this, sorry if i did not explain something good.

So i've had same error, ive fixed it with truncate.

Now, when i try to lets say install git on my machine i get this
![Screenshot_9](https://user-images.githubusercontent.com/46717596/183268930-99f94222-d363-4e07-a2e7-acb81712f0a4.png)

Ubuntu 20.04 using ZFS file system.
