### ISSUE TITLE
unreported data error

### ISSUE THREAD

**Issue by iddq** [openzfs/zfs#13340]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	| 5.16.0-6-amd64
Architecture	|
OpenZFS Version	| zfs-2.1.4-1 zfs-kmod-2.1.4-1

### Describe the problem you're observing
I did an experiment in which I changed the data on one of the disks in a mirror. The file was still readable but I didn't get any error messages which I think would be expected due to the checksum error.

**Comment by szubersk** [comment]
@iddq AFAIK there was no need to report anything as a pool was able to self heal from the other untainted copy.

**Comment by iddq** [comment]
@szubersk I think it would be good to report this error immediately otherwise it will remain hidden until scrub

**Comment by rincebrain** [comment]
Mirrors do not, AIUI, read both disks every time, so you've got 50/50 odds of it noticing initially, and then caching the block means you don't have to look again.

A scrub would have noticed, though, because they do check every copy, unless you ran one and didn't?

**Comment by behlendorf** [comment]
I'd just add that the ZFS Test Suite does include several test cases where verify that checksum errors are correctly reported and self-healed.  These tests cover all supported VDEV layouts and validate correct behavior even when a pool is in a degraded state.  That said, if you have a test case for a scenario you believe is not handled correctly please post it.  But given the considerations already mentioned above I believe things are working as expected.
