### ISSUE TITLE
EACCES on F_SETLK

### ISSUE THREAD

**Issue by TPolzer** [openzfs/zfs#13355]
I was trying to migrate my Thunderbird profile storage by making a symlink from ~/.thunderbird to the actual location (both on zfs, but different datasets).

That doesn't work on ZFS:
```
newfstatat(AT_FDCWD, "/home/tobias/.thunderbird/4ku9o9un.default/.parentlock", 0x7ffed48eabe0, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/tobias/.thunderbird/4ku9o9un.default/.parentlock", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 7
fcntl(7, F_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0, l_pid=-1997421397}) = 0
fcntl(7, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = -1 EACCES (Permission denied)
```

I was trying to find out whether this is WAI, but couldn't find any information. If it's not easily fixable, it should probably at least be documented?

**Comment by TPolzer** [comment]
Actually, it seems my initial diagnosis was wrong and this doesn't have anything to do with the presence of a symlink, but somehow with the existing directory (with a fresh one it's fine).

Permissions on the profile directory (4ku9o9un.default) are 0700, owned by my running user and group. Ideas how to debug this would be appreciated.

**Comment by szubersk** [comment]
Is `l_pid=-1997421397` in
```
fcntl(7, F_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0, l_pid=-1997421397}) = 0
```
an expected value?

**Comment by TPolzer** [comment]
I didn't write that code (it's Thunderbird), but my understanding is this
is simply uninitialized memory that's left untouched for F_UNLCK.

**Comment by szubersk** [comment]
I apologize, my previous comment was completely misdirected.

Would you share more information about the system and OpenZFS version you use? It's much better to follow the new issue template structure, it saves a lot of time asking additional questions.

https://github.com/openzfs/zfs/issues/new?assignees=&labels=Type%3A+Defect&template=bug_report.md&title=

**Comment by TPolzer** [comment]
Hm, sorry about that, somehow I didn't get the template when creating the issue...

Turns out it was a good idea, the syslog looks like this problem exists between me and AppArmor.

### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Debian GNU/Linux bookworm/sid
Kernel Version	| 5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29) x86_64 GNU/Linux
Architecture	| amd64
OpenZFS Version	| 2.1.4-1


### Describe the problem you're observing
See first two comments
### Describe how to reproduce the problem
Unclear, I cannot reproduce this on a fresh directory.
### Include any warning/errors/backtraces from the system logs
> audit: type=1400 audit(1650532873.128:664): apparmor="DENIED" operation="file_lock" profile="thunderbird" name="/home/tobias/private/.icedove/4ku9o9un.default/.parentlock" pid=1101922 comm="thunderbird" requested_mask="k" denied_mask="k" fsuid=1000 ouid=1000

**Comment by TPolzer** [comment]
Indeed, this was fixed by
```
sudo aa-complain /etc/apparmor.d/usr.bin.thunderbird
```

Closing this bug as ZFS unrelated, sorry for the noise.

**Comment by szubersk** [comment]
No issue at all, we're glad your problem is solved!
