### ISSUE TITLE
zfs recv mounts received dataset on busy mountpoint on Linux

### ISSUE THREAD

**Issue by sotiris-bos** [openzfs/zfs#13378]
### System information

Type | Arch Linux LTS
 --- | ---
Distribution Name	| Arch Linux LTS
Distribution Version	| 
Kernel Version	| 5.15.32-1-lts
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.4-1

### Describe the problem you're observing
I have a root-on-zfs system installed on the pool named rpool, with datasets underneath for various locations as /var, /home, /usr etc. I am backing rpool recursively to a second local pool called tank, at tank/rpool via sanoid. I am using unencrypted datasets.
I am using zfs mounts for mounting the datasets to their respective locations.

As soon as I complete the snapshot send, without any receive options, Linux mounts the tank/rpool/XXXX datasets to the already busy mounts that the original rpool/XXX datasets are occupying. This results, at least partly, in new files being written to tank/rpool/XXX instead of rpool/XXX.

I understand I can zfs recv with the -u option to avoid this, but how can the above be the default action?

**Comment by szubersk** [comment]
> I understand I can zfs recv with the -u option to avoid this, but how can the above be the default action?

Syncoid's `--recvoptions`switch allows passing `-u` to `zfs recv`.
I don't really see an issue with OpenZFS here.

**Comment by sotiris-bos** [comment]
> > I understand I can zfs recv with the -u option to avoid this, but how can the above be the default action?
> 
> Syncoid's `--recvoptions`switch allows passing `-u` to `zfs recv`. I don't really see an issue with OpenZFS here.

I know, that is what I ended up doing, I just thought that steps were taken as mentioned here: https://github.com/openzfs/zfs/issues/2442 to avoid mounting the dataset on already busy mounts.

I thought the default would be off for overlay as mentioned here, https://github.com/openzfs/zfs/commit/f67d709080f3d4a247191f0d25cbedc5da103f78 however it appears to be on, at least for me, when I never enabled it.

```
# zfs get overlay tank
NAME  PROPERTY  VALUE    SOURCE
tank  overlay   on       default
```

Is this something distro-specific?

**Comment by rincebrain** [comment]
`overlay` has defaulted to on [since at least 2.0](https://github.com/openzfs/zfs/blob/ad81baab7779cd2113669d30de72bb925e684525/man/man8/zfsprops.8#L1212-L1215).

**Comment by szubersk** [comment]
When one doesn't provide a property value explicitly, the value from the parent component is to be assumed. Had the root filesystem not have the value defined the default hardcodes would have been in effect. Properties are distro-specific only in the case where there can't be a single default available on all systems nominated.

It's better to use https://zfsonlinux.topicbox.com/groups/zfs-discuss for non issue-related discussions.

```
commit f5f6fb03b7e5e3d06da4c04b26319758568ae238
Author: Ryan Moeller <ryan@iXsystems.com>
Date:   Fri Mar 6 12:28:19 2020 -0500

    Change default to overlay=on
    
    Filesystems allow overlay mounts by default on FreeBSD and Linux.
    
    Respect the native convention by switching the default to overlay=on,
    while retaining the option to turn the property off for compatibility
    with other operating systems' conventions.
    
    Update documentation and tests accordingly.
    
    Reviewed-by: Richard Laager <rlaager@wiktel.com>
    Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
    Signed-off-by: Ryan Moeller <ryan@iXsystems.com>
    Closes #10030

diff --git module/zcommon/zfs_prop.c module/zcommon/zfs_prop.c
index 8dfadfaaf..3ba3b8a84 100644
--- module/zcommon/zfs_prop.c
+++ module/zcommon/zfs_prop.c
@@ -406,7 +406,7 @@ zfs_prop_init(void)
        zprop_register_index(ZFS_PROP_NBMAND, "nbmand", 0, PROP_INHERIT,
            ZFS_TYPE_FILESYSTEM | ZFS_TYPE_SNAPSHOT, "on | off", "NBMAND",
            boolean_table);
-       zprop_register_index(ZFS_PROP_OVERLAY, "overlay", 0, PROP_INHERIT,
+       zprop_register_index(ZFS_PROP_OVERLAY, "overlay", 1, PROP_INHERIT,
            ZFS_TYPE_FILESYSTEM, "on | off", "OVERLAY", boolean_table);
 
        /* default index properties */
```

**Comment by sotiris-bos** [comment]
Thank you for your answers, I now know more than I did before coming here.

I still think that automounting with overlay on by default is problematic. A single -u flag omitted for whatever reason can mean days or weeks of data being written to the overlay in the case of someone that is doing local backups to another pool, with a possibly lengthy troubleshooting and solving.

I only caught this because I am doing daily backups and they would fail because the destination dataset was changed between the snapshots. I never encountered this before because I was using encrypted datasets that would not mount because of me not unlocking the backups.

I just think this configuration is too prone to user error. If you think this is a non-issue, by all means go ahead and close to avoid cluttering up the repo. I will go ahead and post to the topicbox group as well.

Thank you again

**Comment by szubersk** [comment]
It could have gone one way or another. It went into `overlay=on` and no `-u` in `zfs recv`.

We could construct examples for it, e. g. when the receiving part wants to ensure that the filesystem is always mounted and the content refreshed after each transfer because data received is served to the clients. I think we are bike-shedding here as it is really a coin toss and the end user has options to configure the behavior the way they want to.

I'd suggest closing this report.
