### ISSUE TITLE
zfs holds using 100% CPU and exponentially slower with more snapshots

### ISSUE THREAD

**Issue by rightaway** [openzfs/zfs#13372]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|arch
Distribution Version	|
Kernel Version	|5.17.4-arch1-1
Architecture	|
OpenZFS Version	|zfs-2.1.4-1

### Describe the problem you're observing

`zfs holds` with a list of snapshots is taking 100% CPU and the amount of time it takes is exponential with the number of snapshots

```
25 snapshots     0.03s user 0.29s system 99% cpu 0.315 total
50 snapshots     0.10s user 1.27s system 99% cpu 1.368 total
100 snapshots    0.26s user 5.32s system 99% cpu 5.625 total
200 snapshots    1.18s user 17.22s system 99% cpu 18.457 total
```

### Describe how to reproduce the problem

Run `zfs holds` with several snapshots.

**Comment by nabijaczleweli** [comment]
It's just cubic actually (well, probably quadratic but the curve fits marginally better): https://www.wolframalpha.com/input?i=polynomial+fit+%7B15%2C0.177%7D%2C%7B30%2C0.653%7D%2C%7B45%2C1.289%7D%2C%7B60%2C2.129%7D%2C%7B75%2C3.264%7D%2C%7B90%2C4.397%7D%2C%7B100%2C5.996%7D%2C%7B117%2C8.552%7D

But yes, I can repro this:
```
15
real    0m0.177s
user    0m0.020s
sys     0m0.157s

30
real    0m0.653s
user    0m0.068s
sys     0m0.584s

45
real    0m1.289s
user    0m0.144s
sys     0m1.145s

60
real    0m2.129s
user    0m0.220s
sys     0m1.909s

75
real    0m3.264s
user    0m0.356s
sys     0m2.907s

90
real    0m4.397s
user    0m0.432s
sys     0m3.965s

100
real    0m5.996s
user    0m0.620s
sys     0m5.375s

117
real    0m8.552s
user    0m0.893s
sys     0m7.658s
```

Funnily enough, you don't even have to specify different snapshots.

**Comment by nabijaczleweli** [comment]
haha. lmfao. it's just quadratic over argc:
```c
	for (i = 0; i < argc; ++i) {
		char *snapshot = argv[i];
		const char *delim;
		const char *snapname;

		delim = strchr(snapshot, '@');
		if (delim == NULL) {
			(void) fprintf(stderr,
			    gettext("'%s' is not a snapshot\n"), snapshot);
			++errors;
			continue;
		}
		snapname = delim + 1;
		if (recursive)
			snapshot[delim - snapshot] = '\0';

		cb.cb_recursive = recursive;
		cb.cb_snapname = snapname;
		cb.cb_nvlp = &nvl;

		/*
		 *  1. collect holds data, set format options
		 */
		ret = zfs_for_each(argc, argv, flags, types, NULL, NULL, limit,
		    holds_callback, &cb);
		if (ret != 0)
			++errors;
	}
```

**Comment by nabijaczleweli** [comment]
@rightaway mind trying #13373?

**Comment by rightaway** [comment]
@nabijaczleweli Thanks for fixing. I've only installed it from my package manager https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/index.html#installation I'm not sure how to use it from source.

Could you check if `zfs holds` with `-r` has sped up for you? It was unusable because it was so slow when I pass all snapshots to it. I am looking for a fast command to show me all holds that exist so that I can manage it in backup scripts. I suggested https://github.com/openzfs/zfs/issues/13306 but do you know how to do it in the meantime?

**Comment by nabijaczleweli** [comment]
`zfs holds -Hr $(zfs list -t snap -Ho name)` (117 snapshots) went from 43.264 to 0.811 seconds, yes. To avoid the superlinearity you can `zfs list -t snap -Ho name | while read -r snap; do zfs holds -Hr "$snap"; done` I guess?
