### ISSUE TITLE
zfs should build  without  "---without-python or --disable-pyzfs"

### ISSUE THREAD

**Issue by andybe** [openzfs/zfs#13394]
try to build an "ARCH iso" 

how ever this is zfs-2.1.4  mkdksm conf has been to be patched:

==> dkms install --no-depmod zfs/2.1.4 -k 5.17.5-arch1-1
Deprecated feature: REMAKE_INITRD
configure: error: "Python >= 3.4 is required"

patch has been changed to (but still no luck):
--- scripts/dkms.mkconf.bk	2022-04-30 17:38:29.376581217 +0200
+++ scripts/dkms.mkconf	2022-04-30 17:39:16.753437330 +0200
@@ -28,14 +28,9 @@
 PRE_BUILD="configure
   --prefix=/usr
   --with-config=kernel
-  --with-linux=\$(
-    if [ -e "\${kernel_source_dir/%build/source}" ]
-    then
-      echo "\${kernel_source_dir/%build/source}"
-    else
-      echo "\${kernel_source_dir}"
-    fi
-  )
+  --without-python --disable-pyzfs
+  --disable-pyzfs
+  --with-linux="\${kernel_source_dir}"
   --with-linux-obj="\${kernel_source_dir}"
   \$(
     [[ -n \"\${ICP_ROOT}\" ]] && \\
@@ -69,7 +63,7 @@
 "
 AUTOINSTALL="yes"
 REMAKE_INITRD="no"
-MAKE[0]="make"
+MAKE[0]="make -C module/"
 STRIP[0]="\$(
   [[ -r \${PACKAGE_CONFIG} ]] \\
   && source \${PACKAGE_CONFIG} \\

**Comment by andybe** [comment]
In the past it works out of the box "build an iso on the fly".

**Comment by szubersk** [comment]
@andybe what Python version do you have installed?

**Comment by andybe** [comment]
> 

In principal 3.10, but that isn't the issue. It  python doesn't work it should disable python + pyzfs. That's my point.

**Comment by behlendorf** [comment]
@andybe would you mind cherry-picking adeccfea177ee674913a87d95ddacbd699ed1c67 to verify it resolves the issue.

That said, you're right there's no python dependency for `scripts/dkms.mkconf` and disabling it there is entirely reasonable.  We just happen to be running those configure checks from a common section of the `configure` script which is why you hit you.

**Comment by andybe** [comment]
> 

On "normal" installation, not rip down system for an iso. It works.
