### ISSUE TITLE
Strange Behaviour-Total size of filesystem decreases automatically

### ISSUE THREAD

**Issue by constantmanish** [openzfs/zfs#13407]
We have a pool named P_Pool and three file systems associated with it.
1.P_application
2.P_Storage
3.P_store

We have seen a strange behavior that the total size of these file systems automatically decreases sometimes, and disk usage gets to 100% for a brief moment of time and it gets back to normal again. What could be the reason of such behavior? is this expected to happen?
we are using zfs 0.8.3-1ubuntu12.10

**Comment by rincebrain** [comment]
Could you be more precise by what you mean by "usage gets to 100% for a brief moment then back to normal again" - do you mean disk IO maxes out, or the space available briefly becomes 0, or ?

As far as total size, that's calculated from [used by filesystem] + [free space on filesystem], and on ZFS, [free space on filesystem] varies as you write to any filesystem on the pool, unless you have a quota restricting it from using all available free space potentially.

**Comment by constantmanish** [comment]
HI @rincebrain , Thank you for your prompt reply.  Regarding the usage getting to 100% for a brief moment I do mean that the used space becomes equal to the total size, i.e free space becomes 0, this free space gets to 0 because the total size decreases without any changes on the used size. And free space increases without any changes on the used size , rather the total size increases. 
Filesystem            Size  Used Avail Use% Mounted on
X_Pool/ROOT/lp_root   39G   19G   21G  48% /
X_Pool/application    57G   36G   21G  64% /opt
X_Pool/app_store      31G  1.3G   29G   5% /opt/makalu/store
X_Pool/storage        51G   31G   21G  60% /opt/makalu/storage

In the above statistic of df -h , when we see such behavior, the Size decreases without any changes in the Used but use% gets to 100% causing filesystem space getting full.

**Comment by rincebrain** [comment]
Exciting.

I don't immediately know of any bug that I've seen go by that would cause that, though I'm not an all-knowing oracle - I'd probably first suggest trying a newer version, as it's not impossible it's been fixed since (January 2020 + whatever Ubuntu cherrypicked)
