### ISSUE TITLE
Kernel panic when attempting to mount iso located on zfs filesyszem

### ISSUE THREAD

**Issue by sus-impost0r** [openzfs/zfs#13457]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Puppy Ubuntu-compatible
Distribution Version	| 16.04 LTS
Kernel Version	| 4.1.31
Architecture	| i686
OpenZFS Version	| 2.1.4-1 built from git

### Describe the problem you're observing
When attempting to mount an iso file located on my zfs file system, I get a kernel panic with varying messages, including most often "failed to handle paging request" and "kernel null lointer dereference at ...".
The location of the mount point is irrelevant. The issue occurs regardless of the iso file mounted.
It's apparently specific  o this computer.
I will transcribe the panic screen if asked to.

### Describe how to reproduce the problem
`mount file.iso directory`

### Include any warning/errors/backtraces from the system logs
(to be filled)

**Comment by rincebrain** [comment]
It would be pretty helpful if you could share something showing the panic at least, even if you don't hand-transcribe it, so we have some idea where it might be failing and how.

**Comment by jittygitty** [comment]
@sus-impost0r yea curious to see that log, you can post a photo if its too much text to type, also any specific setup info on this pc

**Comment by sus-impost0r** [comment]
I thought this might be a known issue, which is why I didn't initially transcribe it, my bad.

@jittygitty
> specific setup info
Like what? I'm using zstd compression on the file system and it's on an external HDD. I'm pretty sure it shouldn't matter, but `/` is an aufs and the filesystem is mounted in a direct subdirectory of `/`. The zfs installation is on a squashfs mounted on top of `/`.

I didn't notice anything out of the ordinary in the kernel log.

I forgot to mention that `mount` never completes, and that I also tested with git master -- same result.

Sorry for the late response.
```
BUG: Unable to handle kernel null pointer dereference at 00000004
IP: [<c10cfb3f>] __rmqueue+0x7f/0x430
*pdpt = 0000000000000000 *pde = f000ff53f000ff53
Oops: 0002 [#1] PREEMPT SMP
Modules linked in: [...] zfs(PO) zunicode(PO) zzstd(O) zlua(O) zcommon(PO) znvpair(PO) zavl(PO) [...]
CPU: 0 PID: 7806 Comm: z_wr_iss Tainted: P        0 4.1.31 #1
Hardware name: IBM 252565G/252565G, BIOS 74ET48WW (1.17A) 06/07/2005
task: dbf6ac70 ti: d02a6000 task.ti: d02a6000
EIP: 0060:[<c10cfb3f>] EFLAGS: 00010012 CPU: 0
EIP is at __rmqueue+0x7f/0x340
EAX: 00000000 EBX: df2656d4 ECX: 00000003 EDX: 00000000
ESI: c1b6602c EDI: 00000141 EBP: 00000000 ESP: d02a7bac
DS: 007b ES: 007b FS: 00d8 GE: 0000 SS: 0068
CR0: 8005003b CR2: 00000004 CR3: 01bf8000 CR4: 000006f0
Stack:
 ce471840 01007bac 00000003 df2565d4 00000000 c1b65f40 df2656c0 0000001b
 0000006c de2da000 00000000 c1b66150 c1b65f40 00000141 00000000 c10d014f
 00000001 00000141 0000cddc c1b65f40 00000008 00000246 d02a7c04 00000003
Call Trace:
[<c10d014f>] ? get_page_from_freelist+0x34f/0x610
[<c146cddd>] ? blk_mq_insert_requests+0x9d/0xc0
[<c10d0620>] ? __alloc_pages_nodemask+0x130/0x7f0
[<e16d438a>] ? vdev_disk_io_start+0x49a/0x9c0
[<c110174e>] ? new_slab+0x5e/0x240
[<c110329a>? ? slab_alloc.isra.14.constprop.17+0x2aa/0x310
[<e16c4945>] ? zio_vdev_io_start+0x215/0x6c0 [zfs]
[<c105fb27>] ? preempt_count_add+0x77/0xa0
[<c187840d>] ? _raw_spin_lock+0xd/0x40
[<c187848d>] ? _raw_spin_unlock+0xd/0x30
[<e16b5aac>] ? zio_wait_for_children+0x9c/0x1b0 [zfs]
[<c110345c>] ? kmem_cache_alloc+0x8c/0xc40
[<e0a68d2c>] ? spl_kmem_cache_alloc+0x7c/0xc40 [spl]
[<e16b689a>] ? zio_vdev_io_done+0x2a/0x270 [zfs]
[<c105fb27>] ? preempt_count_add+0x77/0xa0
[<e16b5aac>] ? zio_wait_for_children+0x9c/0x1b0 [zfs]
[<e16b8c7a>] ? zio_execute+0xea/0x310 [zfs]
[<e165c8a8>] ? vdev_mirror_rebuilding+0x80/0x80 [zfs]
[<e16ba7ad>] ? zio_write_compress+0xa7d/0x17d0 [zfs]
[<e16c4d70>] ? zio_vdev_io_start+0x640/0x6c0 [zfs]
[<c187848d>] ? raw_spin_unlock+0xd/0x30
[<e0a7029a>] ? tsd_hash_search.isra.0+0x4a/0x60 [spl]
[<e16b8c7a>] ? zio_execute+0xea/0x310 [zfs]
[<c1076340>] ? __wake_up+0x30/0x50
[<e0a6ed37>] ? taskq_thread+0x237/0x540 [spl]
[<c1077fa9>] ? cpuacct_charge+0x19/0x50
[<c10689a5>] ? pick_next_entity+0xb5/0x210
[<e1064770>] ? wake_up_process+0x40/0x40
[<e16b8b90>] ? zio_execute_stack_check+0x70/0x70 [zfs]
[<e0a6eb00>] ? taskq_thread_should_stop+0x70/0x70 [spl]
[<c105c118>] ? kthread+0x98/0xb0
[<c1050000>] ? sigqueue_free+0x60/0x70
[<c1878b01>] ? ret_from_kernel_thread+0x21/0x30
[<c105c080>] ? kthread_worker_fn+0x140/0x140l
Code: 00 00 8d 84 03 90 00 00 00 39 c1 89 4c 24 0c 0f 84 bf 00 00 00 8b 4c 24 08 8b 44 24 0c 8d 58 ec 8b 10 09 5c 24 18 09 c3 8b 40 04 <09> 42 04 89 10 8d 04 c9 c7 03 00 01 00 00 c7 43 04 00 02 00 00
EIP: [<c10cfb3f>] __rmqueue+0x7f/0x340 SS:ESP 0086:d02a7bac
CR2: 0000000000000004
---[ end trace 73c3d1ccd9d1aff0 ]---
note: z_wr_iss[7806] exited with preempt_count 1
```

**Comment by rincebrain** [comment]
There are a number of things here that make me unsurprised it broke.

One is that it's running an uncommon kernel version, so I'm not astonished if something might have broken without the automated testing noticing.

One is that ZFS has had problems interacting with overlay filesystems before, and it seems like even the original author hasn't supported aufs on that kernel version in 5 years.

One is that it's running Linux 32-bit x86, on which my personal experience in the last 2 years is that OpenZFS should not be trusted to hold my spam folder, let alone data. (I'm sure other people will chime in to say it's fine. I spent a couple days trying to get a single zfs receive of a sub-1GB dataset with no non-default settings to not panic, across multiple hardware configs. I did not succeed. I filed a bug about reproducibly panicking the system by running the test suite over a year ago that nobody's looked at. Linux/i686 is definitely not a maintained platform in any sense that matters.)

**Comment by sus-impost0r** [comment]
> One is that ZFS has had problems interacting with overlay filesystems before, and it seems like even the original author hasn't supported aufs on that kernel version in 5 years.

Ah, too bad.

> One is that it's running an uncommon kernel version, so I'm not astonished if something might have broken without the automated testing noticing.

I'll try and see how to run it, then post results here.

> Linux/i686 is definitely not a maintained platform in any sense that matters.

Any idea what makes it so system-dependent?

**Comment by rincebrain** [comment]
(Handwavey because it's early and I'm tired, apologies...)

The big ones that come to mind are that some kinds of accesses that would be safe when you're using 64-bit as your unit that you operate on at once are not necessarily if you're doing it as multiple 32-bit operations, and the one that I expected to make it bad but not unstable was that you need address space for memory allocations, and on Linux, your options for splitting between the kernel and userland are pretty static - I believe on recent kernels your options are a (user/kernel) 2G/2G split and a 3G/1G split. (I believe FreeBSD/i386 does something clever to get a better split with different performance characteristics, but have not tried it since someone told me that.)

ZFS likes RAM, but what it really _needs_ is virtual address space, and when you're living in 32-bit limitations, that can be a sad need indeed.

**Comment by jittygitty** [comment]
@sus-impost0r Yea unfortunately I think @rincebrain may be right on all counts. I'd say if you ran a x64 kernel someone might care to dig further, wish zfs had its own overlay system, but unfortunately yea I don't think anyone cares about 32bit anymore.

**Comment by sus-impost0r** [comment]
Yeah, that's fair. I don't have a lot of ram, either -- closing.
