### ISSUE TITLE
ZFS mountpoint is only empty directory

### ISSUE THREAD

**Issue by mbman81** [openzfs/zfs#1345]
After creating 2 zpools in linux (each a 2 disk mirror), the automount mounts both upon reboot.  However, one of the zpool zfs mounts appear to be empty folder.  The contained zfs's do not mount either.

I've tried to export, delete folders, re-import, reboot, same thing happens. 

'zfs get mounted zpool0' returns a no as well. 

If I export and re-import without reboot it seems to work.   

This is with the ubuntu ppa release (ubuntu-zfs).

**Comment by PeterHeja** [comment]
I know this is a closed stale ticket, but for me disabling selinux did the trick.
However, it is not recommended to do so.
