### ISSUE TITLE
/etc/conf.d/zfs installed as executable in Alpine

### ISSUE THREAD

**Issue by otommod** [openzfs/zfs#13496]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Alpine Linux
Distribution Version	| 3.15
Kernel Version	| 5.15
Architecture	| x86_64
OpenZFS Version	| zfs 2.1.4-1, zfs-kmod 2.1.1-1

### Describe the problem you're observing

`/etc/conf.d/zfs` is executable.  It needn't be.

**Comment by nabijaczleweli** [comment]
The version field in the table shows you're running your distributor's package. Have you considered posting that bug to Alpine? The same casein assigns `initconfdir=/etc/default` on debian, and `/e/d/zfs` is non-executable for me.

**Comment by otommod** [comment]
I have done so already, [here it is](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13840)

**Comment by nabijaczleweli** [comment]
Hm; can confirm! `etc/default/zfs.in` is -x, so `etc/default/zfs` is -x, but `$DESTDIR/etc/default/zfs` is +x.
