### ISSUE TITLE
cannot unshare '/testpool/testfs': system error: NFS share removal failed

### ISSUE THREAD

**Issue by 0mp** [openzfs/zfs#13534]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04.4 LTS
Kernel Version	| 5.4.0-113-generic
Architecture	| amd64
OpenZFS Version	| 2.1.99-1

### Describe the problem you're observing

I was running some selected tests from the test suite (those included in #12263) and all my setup and cleanup steps were failing.

### Describe how to reproduce the problem

Run a test, e.g.:

```
./scripts/zfs-tests.sh -x -v -t tests/functional/user_namespace/user_namespace_004.ksh
```

### Include any warning/errors/backtraces from the system logs

The relevant logs seem to be in the setup stderr logs:

```
cannot unshare '/testpool/testfs': system error: NFS share removal failed
could not destroy 'testpool': could not unmount datasets
```

It turns out that I had to install NFS-related packages to make the tests work even though I wasn't testing NFS functionalities.

Now I know that I should install all the tools listed at https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html but I'd like to ask if it could make sense to detect the missing utilities earlier on and print out a nice message about it.

**Comment by ellisonpatterson** [comment]
It did not do this before, seems to be happening due to a some recent change.

**Comment by behlendorf** [comment]
It'd probably be a good idea to issue a warning if certain utilities are missing.  However, they shouldn't be required by all of the tests so this looks like a recently introduced bug.  There was was recent refactoring of the NFS share functionality in PR #13330 which may be responsible for this.

**Comment by ChromaxS** [comment]
This is happening to me on an Arch/linux install that did not the `nfs-tools` package installed. I was able to install that package and the command succeeded afterwards. The dataset did not have NFS sharing enabled (nor do any of its parents):
```
root@archlinux home # zfs destroy -r zfs/os/ubuntu-bionic-user
cannot unshare 'zfs/os/ubuntu-bionic-user': system error: NFS share removal failed
root@server home # zfs get all zfs/os/ubuntu-bionic-user | grep share
zfs/os/ubuntu-bionic-user  sharenfs              off                                                       default
zfs/os/ubuntu-bionic-user  sharesmb              off                                                       default
root@server home # strace -s1024 -T -f -o ~/a zfs destroy -r zfs/os/ubuntu-bionic-user
322 1560731 access("/usr/sbin/exportfs", F_OK) = -1 ENOENT (No such file or directory) <0.000012>
323 1560731 write(2, "cannot unshare 'zfs/os/ubuntu-bionic-user': system error: NFS share removal failed\n", 99) = 99 <0.000019>
324 1560731 close(3)                        = 0 <0.000007>
325 1560731 close(4)                        = 0 <0.000005>
326 1560731 exit_group(1)                   = ?
327 1560731 +++ exited with 1 +++
root@server home # pacman -S nfs-utils
...
:: Proceed with installation? [Y/n] y
...
root@server home # zfs destroy -r zfs/os/ubuntu-bionic-user
root@server home #
```

**Comment by problame** [comment]
Hitting this issue on a "minimal" CentOS 7 as well. "minimal" meaning, use CentOS 7 netinstall iso and select the "minimal" profile of packages. 

I resolved it using `yum install nfs-utils`

Dependency on `nfs-utils` is listed for the ZTS, but looks like it's required at runtime as well: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html#running-zloop-sh-and-zfs-tests-sh

So, I guess it should become a `Requires` of the RPM?
