### ISSUE TITLE
zpool create with draid: children check fails

### ISSUE THREAD

**Issue by jorgegv** [openzfs/zfs#13541]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 8.6
Kernel Version	|4.18.0-372.9.1.el8.x86_64
Architecture	|x86_64
OpenZFS Version	|zfs-2.1.4-1.el8.x86_64

### Describe the problem you're observing

In the man page for creating a dRAID vdev (https://openzfs.github.io/openzfs-docs/Basic%20Concepts/dRAID%20Howto.html#create-a-draid-vdev) it says:

- _children - The expected number of children. Useful as a cross-check when listing a large number of devices. An error is returned when the provided number of children differs._

But when using the `Nc` option with `zpool create`, it does not seem to work.

### Describe how to reproduce the problem

- New VM created, 2 cores, 24 GB RAM, 40 GB root disk (`/dev/vda`) plus 12 x 400GB disks for ZFS testing (`/dev/vd[b-m]`)
- ZFS installed following instruction for RHEL8 based clones, ZFS module loaded with `modprobe zfs`
- Run the following command: `zpool create test draid2:3d:12c:1s /dev/vd[b-m]`

The commands succeeds and creates a weird dRAID2 pool with 2 groups of 5 disks (3 data, 2 parity), plus 1 distributed spare, but with a total of 12 disks. Beware that _12_ physical devices are supplied in the command line.

According to man page, this command should fail for either of the following reasons:
- Because the expected number of disks on the dRAID configuration does not match the value supplied in the `12c` config value...
- or because the dRAID config expects 11 devices but we are supplying 12 on the command line

In short, I believe the command should fail for multiple reasons, but instead it succeeds, and it's not clear then what is the final deployed configuration. Output from `zpool status` after success is:

```
[root@zfs-test ~]# zpool status
  pool: test
 state: ONLINE
config:

	NAME                  STATE     READ WRITE CKSUM
	test                  ONLINE       0     0     0
	  draid2:3d:12c:1s-0  ONLINE       0     0     0
	    vdb               ONLINE       0     0     0
	    vdc               ONLINE       0     0     0
	    vdd               ONLINE       0     0     0
	    vde               ONLINE       0     0     0
	    vdf               ONLINE       0     0     0
	    vdg               ONLINE       0     0     0
	    vdh               ONLINE       0     0     0
	    vdi               ONLINE       0     0     0
	    vdj               ONLINE       0     0     0
	    vdk               ONLINE       0     0     0
	    vdl               ONLINE       0     0     0
	    vdm               ONLINE       0     0     0
	spares
	  draid2-0-0          AVAIL   

errors: No known data errors
```
This output sort of matches the command line, but it does not match the supplied dRAID config, which should only have 11 children, and not 12. What king of dRAID device has been created? What has ZFS done with the extra supplied device? It does not seem to be anopther virtual spare, since it is not shown in the `spares` section...

If the `12c` part in the `zpool create` command is replaced with a `11c` (which matches the desired dRAID2 config), them the command fails as expected:

```
[root@zfs-test ~]# zpool create test draid2:3d:11c:1s /dev/vd[b-m]
invalid number of dRAID children; 11 required but 12 provided
```
In my opinion, since the `c` modifier can be calculated from the requested dRAID configuration, it should be also checked for consistency and fail if it does not match.

**Comment by behlendorf** [comment]
> The commands succeeds and creates a weird dRAID2 pool with 2 groups of 5 disks (3 data, 2 parity), plus 1 distributed spare, but with a total of 12 disks.

It looks to me like the `zpool create` command is behaving as intended, and the `Nc` option is being enforced properly.   In your example, 12 devices have been listed on the command line which exactly matches the expected number of children `12c`.

Where I think there's some confusion is that dRAID does not require that `children % (data + parity) == 0`.  As long as `data + parity <= children` a pool with the requested level of redundancy can be created.  So in your example all 12 drives are being used and the distributed spare space is spread over all of the devices.

If you're interested in the internal details of how the RAID groups are managed there's a detailed [comment](https://github.com/openzfs/zfs/blob/master/module/zfs/vdev_draid.c#L45-L166) in the source which explains the layout.

**Comment by jorgegv** [comment]
OK, now I understand how it works. I was assuming that the D+P groups were being handled by whole devices (which would then imply my previous conclusions). But they are not. Instead, every device is managed as a big group of small pieces, and those pieces are the ones that are handled to get the desired redundancy level, and also where the virtual spares are taken from.

Thanks for the clarification, I believe this issue can then be dismissed :-)
