### ISSUE TITLE
Sub-dataset shadows over parent's same-named file (directory).

### ISSUE THREAD

**Issue by jtagcat** [openzfs/zfs#13567]
```sh
base=tank
zfs create $base/test
mkdir /$base/test/foo
echo foobar > /$base/test/foo/bar

zfs create $base/test/foo
ls /$base/test/foo # empty output

zfs destroy $base/test/foo
ls /$base/test/foo # bar

zfs destroy $base/test -r
```

Expected: `zfs create $base/test/foo` one of:
- err: same-named file (dir) exists
- Parent's directory contents are moved in to sub-dataset.

### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11 (bullseye)
Kernel Version	| 5.10.0-8-amd64
Architecture	| amd64
OpenZFS Version	| zfs-2.0.3-9

**Comment by rincebrain** [comment]
Yes, that is how mounts with any filesystem work. Nothing about that is ZFS-specific.

If you want to forbid it from mounting over non-empty directories, change the `overlay` property, but it defaults to "on" because that's what e.g. `mount` would do.
