### ISSUE TITLE
2.1.5 dracut fails to load zfs kernel module

### ISSUE THREAD

**Issue by prometheanfire** [openzfs/zfs#13573]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| you know...
Kernel Version	| 5.18.5-r1
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.5-staging

### Describe the problem you're observing
dracut is not finding the zfs module for 2.1.5

### Describe how to reproduce the problem
/usr/bin/dracut --force --kernel-image /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/bzImage /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/initrd 5.18.5-gentoo-dist --keep -v --debug

### Include any warning/errors/backtraces from the system logs
`/usr/bin/dracut --force --kernel-image /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/bzImage /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/initrd 5.18.5-gentoo-dist --keep -v --debug 2>&1 | tee dracut-zfs.log`

posted to https://gist.github.com/3e3afb69f7bec2c528c4f02365df28f7

```
dracut --list-modules | grep zfs

dracut: Executing: /usr/bin/dracut --list-modules
zfsexpandknowledge
zfs
```

**Comment by prometheanfire** [comment]
https://github.com/openzfs/zfs/pull/13010/files#diff-22405e99fd7136e3e27a96eac249dc6ed93c6eb9d86498155a1545dac45690bbR92 is also trying to install a file that doesn't exist, next debug step is to revert that full commit...

**Comment by prometheanfire** [comment]
yep, reverting 115e0598180ebbb7cb37c01d48bc601aaf7bb35f fixed it

**Comment by prometheanfire** [comment]
Looking at https://github.com/openzfs/zfs/commits/zfs-2.1.5-staging/contrib/dracut/

0671f7270695278020254615f421caa77193a2c0 is the last commit that works

**Comment by behlendorf** [comment]
Thanks for catching this.  I believe that makes sense since commit ebbfc6cb8 should make the install fatal if something is missing.  In your case what file was it complaining about, any idea why it's missing?

Would you also mind confirming that reverting these patches from the stack resolves the issue?  These aren't must have changes, but they were not expected to be problematic since there were backports from master.

115e05981 Multiple dracut module install script cleanups
4252517f5 Remove absolute paths to udev rules and binaries for dracut
ebbfc6cb8 Make dracut fail if essential files cannot be installed

**Comment by prometheanfire** [comment]
I tried with via checkout only (the 0671f72 commit).  I'll try with revert patches individually first.

It looks like the log file gist was too long and got truncated.  It was saying it was unable to find the zfs module, but when I run --list-modules with dracut it is listed.  Let me regenerate some logs and test some patches.

**Comment by prometheanfire** [comment]
well, first, separate issue is...

`Failed to add dependency on unit, unit zfs-load-module.service does not exist.`  That's a debianism, talked a little about it in the pull-request yesterday.  The line should probably be removed.

**Comment by prometheanfire** [comment]
```
dracut: *** Including module: zfs ***
dracut-install: Failed to find module 'zfs'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/portage/sys-kernel/gentoo-kernel-bin-5.18.5-r1/temp/dracut.P8KjE1/initramfs --kerneldir /lib/modules/5.18.5-gentoo-dist/ -m zfs
dracut: installkernel failed in module zfs
```

The error for me seems to be specifically https://github.com/openzfs/zfs/commit/ebbfc6cb853d2d2f3f0671362d5ff5588be39e9d#diff-22405e99fd7136e3e27a96eac249dc6ed93c6eb9d86498155a1545dac45690bbR22 where it adds the `-c` option to instmods.

**Comment by prometheanfire** [comment]
setting -c does has the function do the following.

1. `local _optional="-o"`
2. `if [[ $1 == '-c' ]]; then unset _optional`
3. which makes `-o` NOT be passwd to dracut_install `${_optional:+-o}`
4. this means `If SOURCE does not exist, do not fail`
5. `

`/usr/bin/dracut --force --kernel-image /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/bzImage /usr/src/linux-5.18.5-gentoo-dist/arch/x86/boot/initrd 5.18.5-gentoo-dist --keep

was run to get a useful debug dir, still got:

```
dracut: *** Including module: zfs ***
dracut-install: Failed to find module 'zfs'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.GOQONy/initramfs --kerneldir /lib/modules/5.18.5-gentoo-dist/ -m zfs
dracut: installkernel failed in module zfs
Not removing /var/tmp/dracut.GOQONy.
```

`/usr/lib/dracut/dracut-install -D /var/tmp/dracut.GOQONy/initramfs --kerneldir /lib/modules/5.18.5-gentoo-dist/ -m zfs --debug` got me the following (added `--debug`)


dracut-install: Program arguments:
dracut-install: /usr/lib/dracut/dracut-install
dracut-install: -D
dracut-install: /var/tmp/dracut.GOQONy/initramfs
dracut-install: --kerneldir
dracut-install: /lib/modules/5.18.5-gentoo-dist/
dracut-install: -m
dracut-install: --debug
dracut-install: zfs
dracut-install: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin
dracut-install: LDD=ldd
dracut-install: Handle module 'zfs'
dracut-install: Failed to find module 'zfs'
```

reinstalled zfs-kmod

it found the module this time.  so I think we are good, no bug

will update description and make a pull request to not try installing the debianism systemd unit.

`Failed to add dependency on unit, unit zfs-load-module.service does not exist.`

**Comment by prometheanfire** [comment]
https://github.com/openzfs/zfs/pull/13574 was made for the systemd unit install issue

summary here may be user error, kernel module was not installed, though the actual module was there (maybe it wasn't in an index somewhere).

```
find /lib/modules/5.18.5-gentoo-dist/ | grep zfs
/lib/modules/5.18.5-gentoo-dist/extra/zfs
/lib/modules/5.18.5-gentoo-dist/extra/zfs/zfs.ko
```
