### ISSUE TITLE
zfs set mountpoint does not warn for existing data in the specified folder

### ISSUE THREAD

**Issue by slavanap** [openzfs/zfs#13570]
```
mkdir -p /new/path
touch /new/path/dummy
zfs create pool/set
zfs mount -a
zfs set mountpoint=/new/path pool/set
```

`zfs set` does not warn if any files exist in `/new/path` and mounts dataset on top of that data containing folder.

My feature request is to add a warning message to stderr if data exists under `/new/path` in that case.

**Comment by rincebrain** [comment]
You can set `overlay=off` if you want it to forbid this, but otherwise, that's just how `mount` works with any filesystem, ZFS included, by default.

**Comment by slavanap** [comment]
@rincebrain thank you for your comment. I think I've got mislead by recent change of default value of overlay parameter from off to on.
