### ISSUE TITLE
mount-zfs.sh fail to import pool

### ISSUE THREAD

**Issue by drJeckyll** [openzfs/zfs#13600]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	|
Kernel Version	| 5.18.7
Architecture	| x64
OpenZFS Version	| 2.1.5

### Describe the problem you're observing
Just upgrade kernel to 5.18.7 (from 5.17.8) with zfs-2.1.5 and my box failed to boot with message:
`Unable to import pool EVO` 

### My solution
It seems that here: https://github.com/openzfs/zfs/blob/c8871ff784731f56bab58efe6077fff38fa74c5a/contrib/dracut/90zfs/mount-zfs.sh.in#L85 command is wrong and missing property. Executing `zpool get -Ho name "EVO"` on my system show `bad property list: invalid property 'EVO'`. So changing command to: `zpool get -Ho name free "EVO"` seems to fixed issue.

**Comment by behlendorf** [comment]
Thanks for catching this typo.  It looks to me like this should be `zpool get -Ho value name "${ZFS_POOL}"`.  I'll go ahead and open a PR.

**Comment by behlendorf** [comment]
@drJeckyll if possible would you mind testing the proposed fix in #13602.  It's a little different than yours but gets the same job done.

**Comment by drJeckyll** [comment]
@behlendorf Changing the line seems to work for me. Also https://github.com/openzfs/zfs/pull/13602#issuecomment-1169696632 - will do the trick too.

**Comment by behlendorf** [comment]
@drJeckyll thanks for verifying the fix.  We've merged the fix to master and will get it in the next point release.
