### ISSUE TITLE
Meta: Include consequences of bugfixes in PR/commit messages

### ISSUE THREAD

**Issue by gdevenyi** [openzfs/zfs#13612]
While my ability to develop code for ZFS is limited, I try to keep abreast of the happenings by reading the PRs/commits, and I've found this common difficulty.

Take for example: [`9e0b42e` (#13015)](https://github.com/openzfs/zfs/pull/13015/commits/9e0b42e8c52a777a3ec64ee6c9a2a5395fd2a451)

This PR/commit message tells me on a technical level what the bug was, and how it was fixed, but it doesnt tell me
- how this bug could be triggered
- what the consequences of the bug are (crash? Data loss? inability to import pool?)

I'd like to request a new checkbox be added for the PR/commit process that provide's a user-level interpretation of what changes are wherever possible. This results in a sort of self-documenting history of reasons/motivations which can be lost otherwise, and enables the eventual autogenerated changelog to be more useful when a release is generated.

Thanks for your consideration.

**Comment by gdevenyi** [comment]
A follow-up of an additional request, document as well
- when a bug is fixed indicate which releases the bug affected

**Comment by gdevenyi** [comment]
https://github.com/openzfs/zfs/releases/tag/zfs-2.1.6 does not track user-visible bugfixes in the way requested.

**Comment by tonyhutter** [comment]
> 'I'd like to request a new checkbox be added for the PR/commit process that provide's a user-level interpretation of what changes are wherever possible.

Yes, reviewers should be reviewing the commit message to make sure they're clear.  Often all that's needed is the addition of a  simple "here's what it does" line if there existing message is technical (example https://github.com/openzfs/zfs/pull/13797#issuecomment-1258604811).

>    when a bug is fixed indicate which releases the bug affected

You should be able to look this up from the release notes.  Each commit in the release notes has a link back to the issue it fixes (assuming it had a `#Closes` line in the commit message).

**Comment by gmelikov** [comment]
Looks like this issue already had answer, let's close it, but we have another issues to discuss such topics, for ex. https://github.com/openzfs/zfs/issues/13755 .
