### ISSUE TITLE
No loadable module support error with official UEK R7 on Oracle Linux 8.6 and OpenZFS 2.1.5

### ISSUE THREAD

**Issue by mightyspiky** [openzfs/zfs#13625]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Oracle Linux
Distribution Version	| 8.6
Kernel Version	| 5.15.0-0.30.19.el8uek
Architecture	| x86_64
OpenZFS Version	| 2.1.5

### Describe the problem you're observing

While trying to install the zfs-dkms rpm I made from sources, I get the following error. I'm almost certain this official kernel packaged from Oracle has loadable module support since, among others, there is a specific modules rpm that installs along the kernel core rpm. If I install the same rpm on UEK R6 (5.4.17) instead of UEK R7 (5.15.0), it installs fine. Here's the error on UEK R7:

  Installing       : zfs-dkms-2.1.5-1.el8.noarch                                                                                                                                    16/26 
  Running scriptlet: zfs-dkms-2.1.5-1.el8.noarch                                                                                                                                    16/26 
Loading new zfs-2.1.5 DKMS files...
Building for 5.15.0-0.30.19.el8uek.x86_64
Building initial module for 5.15.0-0.30.19.el8uek.x86_64
EFI variables are not supported on this system
configure: error: 
		*** This kernel does not include the required loadable module
		*** support!
		***
		*** To build OpenZFS as a loadable Linux kernel module
		*** enable loadable module support by setting
		*** `CONFIG_MODULES=y` in the kernel configuration and run
		*** `make modules_prepare` in the Linux source tree.
		***
		*** If you don't intend to enable loadable kernel module
		*** support, please compile OpenZFS as a Linux kernel built-in.
		***
		*** Prepare the Linux source tree by running `make prepare`,
		*** use the OpenZFS `--enable-linux-builtin` configure option,
		*** copy the OpenZFS sources into the Linux source tree using
		*** `./copy-builtin <linux source directory>`,
		*** set `CONFIG_ZFS=y` in the kernel configuration and compile
		*** kernel as usual.
			
Error! Bad return status for module build on kernel: 5.15.0-0.30.19.el8uek.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/2.1.5/build/make.log for more information.
warning: %post(zfs-dkms-2.1.5-1.el8.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package zfs-dkms

### Describe how to reproduce the problem

1. Compile the sources on another kernel (ex: UEK R6 which is version 5.4.17) since compiling on UEK R7 (5.15.0) will result in the same error as above.

2. Install the resulting rpms on a booted server with UEK R7 (5.15.0) and see the error above along the fact that there is no new ZFS module in the proper /lib/modules/... sub dir.

**Comment by rincebrain** [comment]
The `config.log` from running configure manually might be informative.

**Comment by mightyspiky** [comment]
I still haven't looked at config.log but I've done this:

[root@server ~]# grep CONFIG_MODULES= /boot/config-5.15.0-0.30.19.el8uek.x86_64 
CONFIG_MODULES=y
[root@server ~]#

So it seems to confirm me that the message shown while compiling doesn't seem to relate to the real underlying problem.

**Comment by behlendorf** [comment]
That does look like it's enabled.  Regardless, the `CONFIG_MODULES` check did fail so the next step would be to check the `config.log` which should shed some light on why.  You'll want to search for the "checking whether CONFIG_MODULES is defined" text.

**Comment by mightyspiky** [comment]
Here's the output of build/build.log file:

make: Entering directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9.1.0.2)
  You are using:           gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10.1.0.1)
  MODPOST /root/zfs-2.1.5/build/Module.symvers
make: Leaving directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'

**Comment by rincebrain** [comment]
Specifically, I would expect something like `build/config_modules/build.log` to exist and be more helpful, though "I found gcc 8 to build with and the kernel was built with gcc 11" could be an interesting source of problems in theory, though I haven't seen it break in a long time from that.

**Comment by mightyspiky** [comment]
There's no such file.

```
[root@oldy zfs-2.1.5]# ls build/config_modules/
config_modules.c  Makefile
[root@oldy zfs-2.1.5]#
```

**Comment by rincebrain** [comment]
Cute. How about `build/build.log.config`?

**Comment by mightyspiky** [comment]
I think we have something here:

```
make: Entering directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9.1.0.2)
  You are using:           gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10.1.0.1)
  CC [M]  /root/zfs-2.1.5/build/config_debug_lock_alloc_license/config_debug_lock_alloc_license.o
  CC [M]  /root/zfs-2.1.5/build/config_modules/config_modules.o
  CC [M]  /root/zfs-2.1.5/build/config_debug_lock_alloc/config_debug_lock_alloc.o
  CC [M]  /root/zfs-2.1.5/build/config_zlib_inflate/config_zlib_inflate.o
  CC [M]  /root/zfs-2.1.5/build/config_trim_unusued_ksyms/config_trim_unusued_ksyms.o
  CC [M]  /root/zfs-2.1.5/build/config_block/config_block.o
  CC [M]  /root/zfs-2.1.5/build/config_zlib_deflate/config_zlib_deflate.o
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-ftrivial-auto-var-init=zero’
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_block/config_block.o] Error 1
make[2]: Target '__build' not remade because of errors.
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_block] Error 2
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_debug_lock_alloc_license/config_debug_lock_alloc_license.o] Error 1
make[2]: Target '__build' not remade because of errors.
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_debug_lock_alloc_license] Error 2
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_trim_unusued_ksyms/config_trim_unusued_ksyms.o] Error 1
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_debug_lock_alloc/config_debug_lock_alloc.o] Error 1
make[2]: Target '__build' not remade because of errors.
gcc: error: unrecognized command line option ‘-fzero-call-used-regs=used-gpr’
make[2]: Target '__build' not remade because of errors.
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_trim_unusued_ksyms] Error 2
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_modules/config_modules.o] Error 1
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_debug_lock_alloc] Error 2
make[2]: Target '__build' not remade because of errors.
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_zlib_inflate/config_zlib_inflate.o] Error 1
make[2]: Target '__build' not remade because of errors.
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_zlib_inflate] Error 2
make[2]: *** [scripts/Makefile.build:277: /root/zfs-2.1.5/build/config_zlib_deflate/config_zlib_deflate.o] Error 1
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_modules] Error 2
make[2]: Target '__build' not remade because of errors.
make[1]: *** [scripts/Makefile.build:540: /root/zfs-2.1.5/build/config_zlib_deflate] Error 2
make[1]: Target '__build' not remade because of errors.
make: *** [Makefile:1948: /root/zfs-2.1.5/build] Error 2
make: Target 'modules' not remade because of errors.
make: Leaving directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'
make: Entering directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9.1.0.2)
  You are using:           gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10.1.0.1)
  MODPOST /root/zfs-2.1.5/build/Module.symvers
make: Leaving directory '/usr/src/kernels/5.15.0-0.30.19.el8uek.x86_64'
```

**Comment by rincebrain** [comment]
Ah, it was the compiler, indirectly.

It's trying to build with a gcc 11 flag that gcc 8 has no notion of, because that's what the kernel was built for.

I'd do whatever Oracle's equivalent of enabling gcc 11 with scl is and build it that way.

**Comment by mightyspiky** [comment]
It seems I'm stuck with gcc 8 on Oracle Linux 8 as there is no multiple versions I can choose in appstream repo (the equivalent of software collections in all EL8 clones). There's a package named gcc-toolset-11 which was installed already but it seems that's not it.

**Comment by mightyspiky** [comment]
gcc-toolset-11 was it finally! Executing "scl enable gcc-toolset-11 bash" and running configure again works now! The only problem I have is trying to enable that system-wide in order for zfs-dkms rpm package to be installed successfully on updates. I might use kABI-tracking kmod instead of DKMS meanwhile while I'm figuring that out. Thanks for your help rincebrain.

**Comment by mightyspiky** [comment]
While trying to execute the make command for kABI-tracking kmod ("make -j1 rpm-utils rpm-kmod"), I get this:

checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for x86_64-redhat-linux-gnu-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/zfs-build-root-AWOIF2Lk/BUILD/zfs-2.1.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
error: Bad exit status from /tmp/zfs-build-root-AWOIF2Lk/TMP/rpm-tmp.vwjs5G (%build)


RPM build errors:
    Bad exit status from /tmp/zfs-build-root-AWOIF2Lk/TMP/rpm-tmp.vwjs5G (%build)
make[1]: *** [Makefile:1688: rpm-common] Error 1
make[1]: Leaving directory '/root/zfs-2.1.5'
make: *** [Makefile:1643: rpm-utils] Error 2
[root@server zfs-2.1.5]#

**Comment by mightyspiky** [comment]
If I exit from the new shell I created with the scl command, then run the same make command (kABI-tracking kmod) it gets much further:

```
...
Wrote: /tmp/zfs-build-root-nwMfZRLO/RPMS/x86_64/libuutil3-debuginfo-2.1.5-1.el8.x86_64.rpm
Wrote: /tmp/zfs-build-root-nwMfZRLO/RPMS/x86_64/libzfs5-debuginfo-2.1.5-1.el8.x86_64.rpm
Wrote: /tmp/zfs-build-root-nwMfZRLO/RPMS/x86_64/zfs-test-debuginfo-2.1.5-1.el8.x86_64.rpm
Executing(%clean): /bin/sh -e /tmp/zfs-build-root-nwMfZRLO/TMP/rpm-tmp.iSKEZl
+ umask 022
+ cd /tmp/zfs-build-root-nwMfZRLO/BUILD
+ cd zfs-2.1.5
+ /usr/bin/rm -rf /tmp/zfs-build-root-nwMfZRLO/BUILDROOT/zfs-2.1.5-1.el8.x86_64
+ exit 0
Executing(--clean): /bin/sh -e /tmp/zfs-build-root-nwMfZRLO/TMP/rpm-tmp.T3zxvo
+ umask 022
+ cd /tmp/zfs-build-root-nwMfZRLO/BUILD
+ rm -rf zfs-2.1.5
+ exit 0
make[1]: Leaving directory '/root/zfs-2.1.5'
make  pkg="zfs-kmod" \
	def='--define "build_src_rpm 1" ' srpm-common
make[1]: Entering directory '/root/zfs-2.1.5'
make[2]: Entering directory '/root/zfs-2.1.5'
make[2]: Leaving directory '/root/zfs-2.1.5'
error: line 12: Dependency tokens must begin with alpha-numeric, '_' or '/': BuildRequires:  %kernel_module_package_buildreqs
make[1]: *** [Makefile:1672: srpm-common] Error 1
make[1]: Leaving directory '/root/zfs-2.1.5'
make: *** [Makefile:1612: srpm-kmod] Error 2
[root@oldy zfs-2.1.5]#
```

**Comment by behlendorf** [comment]
You'll want to use the `--with-spec=redhat` configure option to build the kABI-tracking kmods.  Otherwise the resulting kmods will be tied to a specific kernel version.

```
./autogen.sh
./configure --with-spec=redhat
make kmod-rpms
```

**Comment by mightyspiky** [comment]
I've followed the kABI-tracking kmod section of this page: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html?highlight=custom

So, yes, I've used "--with-spec=redhat". I get very close but not quite yet. Some rpm packages are made but I don't reach the completion of zfs-kmod package.

**Comment by behlendorf** [comment]
Were you able to install all the build dependencies from that page?  It looks like you may be missing `kernel-rpm-macros`.

**Comment by mightyspiky** [comment]
Oops! Thank you for that. Indeed, kernel-rpm-macros was not installed. I get the kABI-tracking kmod to compile correctly but it gets compiled for the 4.18 stock kernel from Red Hat instead of the newer Oracle one (version 5.15.0). Since I'm currently booted into that newer kernel, I thought the compilation would be targeting that kernel. How can I change that?

**Comment by rincebrain** [comment]
#13627 contains my thoughts on that feature.

If it's not picking the running kernel, you probably don't have the kernel-headers package installed for it, in my experience.

**Comment by mightyspiky** [comment]
I have both kernel-devel (headers for Red Hat kernel) and kernel-uek-devel (headers for Oracle kernel).

**Comment by rincebrain** [comment]
You could try explicitly specifying `--with-linux=/lib//modules/$(uname -r)/source/` or `/build/` or wherever UEK sticks the symlink to /usr/src/... and see if that fails - unlike without that, it will fail if you give it an explicit location and it can't find headers there.

(You could also just directly give it `/usr/src/linux-headers-$(uname -r)` or equivalent, I just am in the habit of using the modules symlink because it's not always there.)

**Comment by mightyspiky** [comment]
By the way, the rpm package "kernel-abi-stablelists" should be added to the doc for Red Hat section on this page: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html?highlight=custom

**Comment by mightyspiky** [comment]
I've tried removing completely the Red Hat kernel and headers for it but now the compilation fails with:

```
Installing zfs-kmod-2.1.5-1.el8.src.rpm
rpm: no arguments given for query
error: Failed build dependencies:
	kernel-devel is needed by zfs-kmod-2.1.5-1.el8.x86_64
```

... even though I have the kernel-uek-devel package. So, I'll have to add "--with-linux" argument. Is it with the configure or with the make command?

**Comment by rincebrain** [comment]
configure, but it'll still fail after that, I think.

Surprised Oracle doesn't make the UEK devel package provides kernel-devel to avoid things like this.

**Comment by mightyspiky** [comment]
They don't want their kernels to conflict with Red Hat ones, which I think is ok. For example, one could decide to install only Red Hat kernel things or only Oracle ones or both.

**Comment by rincebrain** [comment]
Saying "this can also fulfill this dependency" isn't a conflict.

**Comment by rincebrain** [comment]
You could go edit the RPM spec definitions to accept kernel-devel _or_ kernel-uek-devel, just as it would have been simple for them to have said something like `Provides: kernel-devel-$(uname -r)` in the kernel-uek-devel definition.

(`kernel-devel-uname-r` is not a package on anything, as far as I know. `kernel-devel-$(uname -r)`, however, would substitute the version number of the running kernel on the end, e.g. `kernel-devel-5.15.0-0.30.19.el8uek.x86_64`)

**Comment by mightyspiky** [comment]
Where is the RPM spec definition? I thought it was in rpm/generic/zfs-kmod.spec.in :

```
%else

# Building local packages attempt to to use the installed kernel.
%{?rhel:BuildRequires: kernel-uek-devel}
%{?fedora:BuildRequires: kernel-uek-devel}
%{?suse_version:BuildRequires: kernel-source}
```

Even with that, the compilation for kABI-tracking mod fails with:

```
Installing zfs-kmod-2.1.5-1.el8.src.rpm
rpm: no arguments given for query
error: Failed build dependencies:
	kernel-devel is needed by zfs-kmod-2.1.5-1.el8.x86_64
```

**Comment by behlendorf** [comment]
The `kernel-rpm-macros` package should provide a set of macro's which define these dependency correctly for the platform.  Take a look at the `%kernel_module_package*` macro's in the `/usr/lib/rpm/macros.d/macros.kmp`.  I would have expected that package to provide the right names for the uek kernel.  Perhaps an alternate package is provided?  If not you could always manually edit it.

**Comment by mightyspiky** [comment]
I'm now getting a little bit further. I can now build kABI-tracking mod for UEK R6 (5.4) kernel from Oracle, thanks to your last post behlendorf. As for UEK R7 (5.15.0), I must execute "scl enable gcc-toolset-11 bash" before any configure command or else I'll get the error about CONFIG_MODULES (my original bug report) *but* if I stay in this new shell for the subsequent "make" commands, it fails with the following:

```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/zfs-build-root-GUJnSXxO/BUILD/zfs-2.1.5':
configure: error: C compiler cannot create executables
```
 So, in my previous attempts, I was getting out of that new shell (the one created with "scl enable gcc-toolset-11 bash") after the "./configure --with-spec=redhat" command, just before the "make -j1 rpm-utils rpm-kmod" command. The problem I have now is that that last make command eventually run a configure command which fails since I'm not in the special shell anymore. So, I'm stuck with an error in either case (in and out of the special shell). My guess is that I should solve the error in the special shell, the one above about C compiler which cannot create executables.

**Comment by rincebrain** [comment]
I'd still just edit the rpm spec preprocessed definitions (rpm/generic/*.in) to allow kernel-uek-devel, personally, but you do you.

(Note that the .in files, like all files ending in .in, get preprocessed into the actual files during the ./configure stage, so you have to rerun configure afterward.)

**Comment by mightyspiky** [comment]
rincebrain, I have no more problem with kernel-devel vs kernel-uek-devel thing since modifying the file /usr/lib/rpm/macros.d/macros.kmp as indicated by behlendorf. My only remaining problem is that I get the error "C compiler cannot create executables" when executing the make command while using gcc 11 (via "scl enable gcc-toolset-11 bash").

**Comment by rincebrain** [comment]
Well, the output from that error is in a logfile somewhere in your working directory - for that failure case, it might even be in config.log directly.

I would suggest finding it and seeing how it's somehow doing this wrong.

**Comment by mightyspiky** [comment]
I cannot proceed as you suggest right now because I don't want to continue experimenting on my main server while my zpool is down. My next step is building on a test OL9 vm with UEK R7 and try using the rpms on OL8 but I have to wait for Oracle to release the OL9 KVM image template. Thanks for your help.

**Comment by mightyspiky** [comment]
I've proceeded with an Oracle Linux 8 test LXC container and I've been able to reproduce the problem ("C compiler cannot create executables") I have on my main system while compiling for kernel version 5.15.0. In config.log, I've been looking for the string "executables" and didn't find anything meaningful. I looked for errors and find many so I don't know which ones could be related to the problem. Here's three:

```
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9.1.0.2) (GCC)
... rest of stderr output deleted ...
configure:4562: $? = 0
configure:4551: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4562: $? = 1
configure:4551: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
```

and the second one:

```
configure:66509: gcc -o conftest -g -O2   conftest.c  -Wl,-framework -Wl,CoreFoundation >&5
conftest.c:60:10: fatal error: CoreFoundation/CFPreferences.h: No such file or directory
   60 | #include <CoreFoundation/CFPreferences.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

and the third one:

```
configure:68827: checking for library containing xdrmem_create
configure:68857: gcc -o conftest -g -O2   conftest.c  >&5
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /tmp/ccg77DRo.o: in function `main':
/root/zfs-2.1.5/conftest.c:74: undefined reference to `xdrmem_create'
collect2: error: ld returned 1 exit status
configure:68857: $? = 1
```

**Comment by rincebrain** [comment]
At least in my local system, when I hand it an invalid compiler, it has in config.log:
```
configure:4125: checking whether the C compiler works
configure:4147: /not/there    conftest.c  >&5
./configure: line 4149: /not/there: No such file or directory
configure:4151: $? = 127
configure:4189: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "zfs"
| #define PACKAGE_TARNAME "zfs"
| #define PACKAGE_VERSION "2.1.99"
| #define PACKAGE_STRING "zfs 2.1.99"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define ZFS_META_NAME "zfs"
| #define ZFS_META_VERSION "2.1.99"
| #define SPL_META_VERSION ZFS_META_VERSION
| #define ZFS_META_RELEASE "1302_g23efcb785"
| #define SPL_META_RELEASE ZFS_META_RELEASE
| #define ZFS_META_LICENSE "CDDL"
| #define ZFS_META_ALIAS "zfs-2.1.99-1302_g23efcb785"
| #define SPL_META_ALIAS ZFS_META_ALIAS
| #define ZFS_META_AUTHOR "OpenZFS"
| #define ZFS_META_KVER_MIN "3.10"
| #define ZFS_META_KVER_MAX "5.18"
| #define PACKAGE "zfs"
| #define VERSION "2.1.99"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4194: error: in `/home/rich/zfs':
configure:4196: error: C compiler cannot create executables
See `config.log' for more details
```

My guess would be it either is failing on that, or that the kernel config is passing a compiler flag that is somehow not correct, and it's dying when it checks building against the kernel headers.

**Comment by mightyspiky** [comment]
The "configure" runs ok. I get the error when executing the make command. Maybe it doesn't log in the config.log at the root of the zfs decompressed archive (the one i'm looking)..?

**Comment by mightyspiky** [comment]
The error was in /tmp/zfs-build-root-pNAU6JfC/BUILD/zfs-2.1.5/config.log and was about a missing annobin.so plugin so I installed gcc-toolset-11-annobin-plugin-gcc and get past the error about "C compiler cannot create executables" after that. Now, I'm stuck with this:

```
Installing zfs-kmod-2.1.5-1.el8.src.rpm
rpm: no arguments given for query
Executing(%prep): /bin/sh -e /tmp/zfs-build-root-a7K5pYya/TMP/rpm-tmp.ZAQknJ
+ umask 022
+ cd /tmp/zfs-build-root-a7K5pYya/BUILD
+ '[' -d /usr/src/kernels/5.4.17-2136.309.4.el8uek.x86_64 ']'
+ echo 'Kernel build directory isn'\''t set properly, cannot continue'
Kernel build directory isn't set properly, cannot continue
+ exit 1
error: Bad exit status from /tmp/zfs-build-root-a7K5pYya/TMP/rpm-tmp.ZAQknJ (%prep)
```

It seems it wants the 5.4.17 kernel headers but I don't have anything related to that kernel on this LXC container. I've installed the stuff (kernel-uek-*) for 5.15.0 version. I guess it may be because my container is using the 5.4.17 of the physical host. I hope there's a way to build for another version than the booted kernel.

**Comment by rincebrain** [comment]
I've never checked that this interacts with the kmod build the way one might expect, I think, but look at `./configure --with-linux=` and `--with-linux-obj=`.

**Comment by mightyspiky** [comment]
I've tricked the compilation into thinking it was booted on 5.15.0. First, I moved /usr/bin/uname into /usr/bin/uname.orig and then put the following content into /usr/bin/uname:

`uname.orig $@ | perl -pe 's/5.4.17-2136.309.4.el8uek.x86_64/5.15.0-0.30.20.el8uek.x86_64/g'`

I know that is ugly but, after doing that, I re-ran the make command and it worked! On my main physical system, I'm now using kABI-tracking mod of zfs 2.1.5 on UEK R7 (5.15.0)!!

Thank you very much to you rincebrain and also to behlendorf for the much appreciated help. I think we can now close this issue.

**Comment by 9ktz** [comment]
I'm facing the exact same issue

**Comment by mightyspiky** [comment]
> I'm facing the exact same issue

All the answers are in the posts above my friend. I'll resume them here:

1. Install all dependencies mentionned here: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
2. Install gcc-toolset-11-annobin-plugin-gcc
3. Replace kernel-devel by kernel-uek-devel in /usr/lib/rpm/macros.d/macros.kmp and rpm/generic/zfs-kmod.spec.in (that last one relative to zfs untared archive)
4. Remove kernel-abi-whitelists from /usr/lib/rpm/macros.d/macros.kmp
5. Boot on target kernel (UEK R7) or else do the trick with uname command (I explain it just above your comment 9ktz)
6. cd into zfs untared archive then execute this to compile
scl enable gcc-toolset-11 "./configure --with-spec=redhat"
scl enable gcc-toolset-11 "make -j1 rpm-kmod rpm-utils"
7. Replace uname with original uname command if it has been modified before compilation

**Comment by 9ktz** [comment]
I resided to an older version of the kernel previously working. I mostly commented  to denote that resolving the issue by resorting on mere hacks is unlike to be the best course of action.

**Comment by mightyspiky** [comment]
> I resided to an older version of the kernel previously working. I mostly commented to denote that resolving the issue by resorting on mere hacks is unlike to be the best course of action.

I agree with you and would be pleased to have something cleaner but, at least for now, I have something that work.

**Comment by mightyspiky** [comment]
I've decided to close the issue as my feeling at the time was that it would not ever be possible to have a clean solution based on the workaround I've found and that this workaround was "good enough" for me.

**Comment by Lathanderjk** [comment]
It`s not a real kABI tracking kmod but regular kmod it's depend on kernel on which was build.
I builded on uek R7 5.15.0-5.76.5.1.el8uek and its working only on this particular kernel, after update to uek 5.15.0-6.80.3.1.el8uek no module has been found ( i even tried to reinstall kmod-zfs).

Also is installing kernel-uek-core with specific version as dependency.
...
Description  : This package provides the zfs kernel modules built for
                      :  the Linux kernel 5.15.0-5.76.5.1.el8uek.x86_64 for the x86_64
                      : family of processors.


It is strange because i tried similiar setup for kABI drbd module and its working fine.

I tried to build regular kmod also just for curiosity but same outcome  https://github.com/openzfs/zfs/issues/13625#issuecomment-1176939322

**Comment by rincebrain** [comment]
As was explained to me, the kABI stability tracking doesn't pretend to promise every symbol won't change between kernels, only certain ones, and OpenZFS uses some symbols which aren't in that list, so it can't promise that wouldn't break between versions.

**Comment by mightyspiky** [comment]
> > I'm facing the exact same issue
> 
> All the answers are in the posts above my friend. I'll resume them here:
> 
> 1. Install all dependencies mentionned here: https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html  (Install kernel-uek-devel instead of kernel-devel)
> 2. Install gcc-toolset-11-annobin-plugin-gcc
> 3. Replace kernel-devel by kernel-uek-devel in /usr/lib/rpm/macros.d/macros.kmp and rpm/generic/zfs-kmod.spec.in (that last one relative to zfs untared archive)
> 4. Remove kernel-abi-whitelists from /usr/lib/rpm/macros.d/macros.kmp
> 5. Boot on target kernel (UEK R7) or else do the trick with uname command (I explain it just above your comment 9ktz)
> 6. cd into zfs untared archive then execute this to compile:
>    scl enable gcc-toolset-11 "./configure --with-spec=redhat"
>    scl enable gcc-toolset-11 "make -j1 rpm-kmod rpm-utils"
> 7. Replace uname with original uname command if it has been modified before compilation

I've just applied those steps for upgrading from UEK R7 (kernel 5.15.0) to UEK R8 (kernel 6.12.0). I only had to replace gcc-toolset-11 with gcc-toolset-14 and that's it.
