### ISSUE TITLE
ZFS 2.0.7 unsupported on LTS >= 5.15.37, Missing (supported) ZFS LTS Release

### ISSUE THREAD

**Issue by pittagurneyi** [openzfs/zfs#13624]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| 
Kernel Version	| 5.15.32-gentoo-r1
Architecture	| x86_64
OpenZFS Version	| zfs-2.0.7-r0-gentoo

### Describe the problem you're observing

Although the release notes for 2.0.7 say that kernel versions up to 5.15 are supported, a function renaming in 5.15.37, which was backported from 5.16+, causes sendfile errors.

This has been reported for kernel versions 5.16+ in [Issue 12971](https://github.com/openzfs/zfs/issues/12971).

Also seen in [Issue 13401 "iov_iter_fault_in_readable is now fault_in_iov_iter_readable"](https://github.com/openzfs/zfs/issues/13401).

### Describe how to reproduce the problem

If I upgrade the kernel on any of my Gentoo systems to a newer 5.15 LTS release than 5.15.36, the system will be broken once I boot into it.

Emerging a package using portage will fail at the copy stage, i.e. when it moves the processed data from the sandbox into the ZFS root filesystem.

Installing/rebuilding/upgrading packages is no longer possible.

### Include any warning/errors/backtraces from the system logs

See the linked issue.

### Possible solution

After some searching I found a patch that solves the problem of the renamed function: ["Linux 5.16 compat: Added mapping for iov_iter_fault_in_readable " by Rich Ercolani](https://github.com/openzfs/zfs/pull/12975/commits/a0b11a8996b55a0bb3c1c100fa6f392ca90d74b0).

I applied it to 2.0.7 and the problem went away. Although I believe this patch could not cause undesirable side effects, I'd ask that a ZFS developer takes a look at it and would prefer a new official release to patching it myself.

I've been spending some time in the past months reading the issue tracker on problems occuring in ZFS 2.1.x and I'm not yet convinced I should upgrade from 2.0.7 to 2.1.x on my production machines. This leaves me in a bad spot. I don't want to risk 2.1.x yet, but bugs that affect 2.0.7 aren't getting fixed anymore.

At this point in time I'd ask that you, the ZFS developers, please reconsider creating another 2.0.x release for those of us who would like to stay on the LTS kernel 5.15 and ZFS 2.0.x for the foreseeable future. I'm guessing/hoping that I'm not the only one. For me stability and data safety are the most important factors.

Perhaps the release could be limited to bug fixes that are related to serious issues, like data corruption. Keeping it compatible with 5.15 would be great as well, as I intend to stay on 5.15 for at least a year. I would not want/need/require any patches that make kernels 5.16+ available.

There appear to be bug fixes that are not in any 2.0.x release yet, specifically those related to [Issue 11900 "SEEK_DATA fails randomly"](https://github.com/openzfs/zfs/issues/11900):

- [Issue 13329 "MySQL's ib_logfile1 cannot be created properly"](https://github.com/openzfs/zfs/issues/13329) fixed in 2.1.5 by [Pull request 13338 "Corrected oversight in ZERO_RANGE behavior"](https://github.com/openzfs/zfs/pull/13338).
- [Pull request 12746 "Default to zfs_dmu_offset_next_sync=1"](https://github.com/openzfs/zfs/pull/12746), included in 2.1.5

I believe they affect 2.0.x, but please correct me if I'm wrong.

If creating another release is not possible, then please adjust the release notes for 2.0.7, so the supported kernel versions are limited to <= 5.15.36.

Also, it would be great, if someone could look at the two linked pull requests and tell me if it would be safe for me to apply those (tests/... excluded) to 2.0.7 myself. They seem to be quite small.

In evaluating the current state of 2.1.x I'm facing the problem, that I don't always understand the severity of bug fixes, as this is unclear to me - most of the time - from the technical commit messages and I have to start digging into the issues that lead to that fix.

Therefore, the following is something I'd like to see as well, as it would help me understand the problems being fixed:

[Issue 13612 "Meta: Include consequences of bugfixes in PR/commit messages"](https://github.com/openzfs/zfs/issues/13612)

Considering the severity of issues I have witnessed in the past, I would like to see a continously updated list of current and past bugs that affect data safety in any way. Categories that I'm most worried about are:

- silent data corruption
- data corruption

In my opinion I should be able to review the risks of using my currently selected version of ZFS by looking at a table. Perhaps one could put severity-related categories in column headings and list issues - time sorted - in column 1, while the affected ZFS versions are placed in the associated table cell. Issues that have no fixes yet should be highlighted.

Let's say such a table would look like this:

#Issue | silent data corruption | data corruption | kernel panic/system crash
 --- | --- | --- | ---
12345, 2022-06-03	|  < 2.1.5, < 2.0.7 | < 2.1.5, < 2.0.7 |
12344, 2022-05-02     |                             |                            | < 2.0.6

Then, by looking at it, I'd immediately know to upgrade to 2.0.7 or 2.1.5 after reviewing the linked issue. If it were "only" kernel panics I could look at what kind of hardware, etc. is affected and then decide if I want to risk it or not.

However, if the table looked like this

#Issue | silent data corruption | data corruption | kernel panic/system crash
 --- | --- | --- | ---
12345, 2022-06-03     |  < 2.1.5      |   < 2.1.5                           |
12344, 2022-05-02     |  < 2.1.5, < 2.0.7 | < 2.1.5, < 2.0.7 |
12343, 2022-04-01     |  **unfixed, >= 2.1.3**      |   **unfixed, >= 2.1.3**                           |

then the decision I have to face becomes much harder, because in this theoretical scenario 2.0.7 hasn't received the fix for 12345, while 2.1.x  still has unfixed serious issues. Neither staying at 2.0.7 nor moving to 2.1.5 are good options.

At the moment, this is how I feel when looking at 2.1.x.

If such metadata, in human readable format, could be included in commit messages, then autogenerating such a table would also be an option, correct?

Thank you all for your great work on this project!

**Comment by thesamesam** [comment]
As far as I'm aware, 2.0.x is functionally dead. I don't think it's wise to continue using it, even if it's not been officially declared EOL. This is why 2.1.x has been marked stable in Gentoo already, too.

What issues are you hitting in 2.1.x that are unfixed, exactly? The issues in your table don't seem to correspond to bugs which make sense in this context.

**Comment by gyakovlev** [comment]
FYI,
2.0.7 includes fixes for SEEK_DATA problem:
https://github.com/openzfs/zfs/commit/a524f8d6afa141dd82bc60554610679614ea0f54
https://github.com/openzfs/zfs/commit/33fa3985a9791a6dcd2ee60ac9ea21486d068c0f

those commits are on 2.0.x branch and are included with 2.0.7 tag.

I agree that compat PR looks harmless to me, we can easily add it.

btw, I wanted to remove 2.0.7 from gentoo but haven't done so yet.

**Comment by Evernow** [comment]
> If that is correct, then practically, there is no LTS release.
> 
> Based on the definition provided in that file, 2.1.5 would both be the _OpenZFS current_ AND _OpenZFS LTS_ release, which makes no sense from my point of view.
> 
> A "LTS" release should provide you with a longer supported, proven and stable release, which receives only important patches. Such a release, to become proven and stable, would have had to mature in the past and now remain behind the current release. As 0.8 is no longer supported and 2.0 apparently EOL, that would leave only the current release, which, at the moment, can't really be a LTS release. It will/may become one in the future, if enough time has passed and if it doesn't still suffer from bugs.

Note I am just a user, but from memory what I gathered when this was being discussed is that right now OpenZFS LTS is the current release aswell, and when a future OpenZFS release comes around (3.0 I believe) then that will be the current release, and 2.1 will remain the LTS release until it is end of life on ~July 2023

This is similar to Ubuntu LTS right now, where the current and LTS release are right now the same. There are multiple projects that follow this same release formatting (RHEL, Firefox, Linux kernel, KDE Plasma, NVIDIA drivers, SUSE, Oracle Linux, Python, etc). 

> If it were really stable, then it should not contain broken functionality, like ZFS encryption.

Can you please link to the bug report? I run a RHEL (and Fedora) box with overall about 300TB of encrypted pools and have not experienced a single issue when using the latest ZFS releases. 

> I consider OpenZFS current to be field testing of new code, which I consider unacceptable in most circumstances, when the data I'm working with is not irrelevant.

It is not, look at the release notes: https://github.com/openzfs/zfs/releases

It is only receiving bug fixes on point releases, not new features. Unless you count new kernel support as new features that is, but it seems to be acceptable as long as the LTS release is also the current release. 

> Now am I really forced to use a non-LTS version of ZFS again?

OpenZFS 2.1 is supported till ~July 2023, after which you will have to update if you wish to keep receiving bug fixes.

**Comment by freqlabs** [comment]
2.1 isn't "current" it's close to two years old. We're due for 2.2 IMO. New features from the past two years aren't in 2.1, just bug fixes.

**Comment by freqlabs** [comment]
You're right, I was looking at zfs-2.0.0 not zfs-2.1.0 by mistake.

It's hard to keep track of issues in multiple branches even as a developer. For the most part I'm just periodically skimming through commits to master looking for things that look like a bug fix rather than a feature or performance improvement and seeing if they apply to the zfs-2.1-release branch. If so, I'll create a backport PR for it myself or mention it in a release staging PR if one is open. When we find an issue in a release branch it tends to still be applicable in master, so the issue gets fixed in master first and then backported eventually after it has been vetted in master for a while.

I don't bother trying to backport anything to 2.0 anymore because as far as I'm aware, there are no further releases planned on that branch. So much code has changed since that branched that the maintenance burden has become daunting and time consuming. You don't see bugs being fixed in 2.0 as much as in newer branches not because there aren't bugs, but because it's not being maintained.

2.0 was specifically intended to not be LTS because of the huge code restructuring and influx of features that took place for the 2.0 release. We anticipated there being wrinkles still to be ironed out.

2.1 has had time to mature the code base a bit further. It's the version that is used in FreeBSD 13 and TrueNAS CORE 13 and TrueNAS SCALE releases. It's the version that's actively maintained and used. It's the LTS branch. Bugs are being found and fixed in it because that's what people are using.

That said, I wouldn't be opposed if someone volunteered to be the maintainer of a 2.0 LTS branch.

**Comment by freqlabs** [comment]
As a TrueNAS developer I am personally responsible for ensuring that we have very few additional features on top of the upstream release. Most of them are backported from the upstream master branch after having been merged into OpenZFS, and the only really big features are things we had to develop for SCALE to provide feature parity on Linux with long-existing functionality in FreeBSD, specifically then NFSv4 ACL support and consistent xattr namespacing. There are also several minor performance optimizations for our specific use cases that are not candidates for being backported to upstream stable releases. We do not have any huge extra features that we did not develop, such as encryption or draid, before they are in an upstream release. Any issues you have with ZFS in a release of TrueNAS are almost certainly issues you would have running an official release of OpenZFS.

**Comment by freqlabs** [comment]
Yep it wasn't my call to put it in, but I am the one who removed that when the guy who was working on it left. That was then, this is now. I absolutely share your sentiment about preferring to fix existing bugs over introducing shiny new features. I also think it is important to make sure that existing features work across platforms as much as possible, and are reasonably well tested and documented. You are welcome to help.

**Comment by gdevenyi** [comment]
Seems @pittagurneyi and I have very similar concerns about the purpose of versions, LTS and such, also storing the same kind of data. I can say that I'm still running 0.8.6 on all my storage servers due to the current state of the release branches.

**Comment by thesamesam** [comment]
I co-maintain ZFS in Gentoo with @gyakovlev. It's not really clear to me what versions of ZFS are LTS in reality. I don't really want to keep stable pinned to some version which doesn't even work with latest LTS kernels, as that will cause more harm than good as well.

If ZFS forms some sensible policy and keeps making releases for older ZFS branches, then we might be able to track that in stable, yeah (at the very least could probably keep the ebuilds around even if they were shadowed in stable by something newer).

We're really led by what ZFS decides to do and there's not much point in worrying about our side of things until that's straightened out.

> just to be safe, masked coreutils-9.x, 

Keep in mind that other software may use `copy_file_range` and friends.

>Could we now please open the discussion again on the necessity of a reliable, supported, older LTS release where those of us who depend on our data can "relax"? This is all giving me anxiety every time I open the ZFS issue tracker.

I think this is a bigger issue regarding focus on bug fixes/QA vs new features and so on which I can't really offer input on.

**Comment by gmelikov** [comment]
This issue was about specific already not actual release and kernel, so let's close it as not actual. Questions about release policy may be discussed in another open issues, for ex. here https://github.com/openzfs/zfs/issues/13755
