### ISSUE TITLE
ZFS choose not to use AES-IN on encrypted pool.

### ISSUE THREAD

**Issue by lsylipei** [openzfs/zfs#13651]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu Server
Distribution Version	| 22.04LTS
Kernel Version	| 5.15.0-41-generic
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.4-0ubuntu0.1

### Describe the problem you're observing

I recently install 22.04LTS Ubuntu Server version on my Dell R730xd server. Server has 2x E5-2686 v4 @ 2.30GHz, total 36C/72 threads, 256GB memory.
After Ubuntu installed, I just do apt update, apt upgrade, then apt install zfsutils-linux. 

I build a ZFS stripe pool with 4x intel 670p 2TB NVME hard drive with encryption on. Then I notice ZFS is not using AES-IN at all.
```
sudo zpool create -f -m /mnt/nvme -O encryption=aes-256-gcm -O keyformat=passphrase -O keylocation=prompt nvme nvme0n1 nvme1n1 nvme2n1 nvme3n1
```

I did use perf top to check it shows the following when I copy a large file from other non encrypt ssd to this pool.

```
  71.48%  [kernel]                    [k] gcm_generic_mul
  13.66%  [kernel]                    [k] aes_generic_encrypt
   2.15%  [kernel]                    [k] gcm_mode_encrypt_contiguous_blocks
   1.91%  [kernel]                    [k] aes_encrypt_block
   1.82%  [kernel]                    [k] aes_xor_block
```

It looks like ZFS choose not to use AES-IN at all. But I did use openssl to verify the AES-IN works on this system.
```
root@testub:/mnt/ssd# openssl speed -elapsed -evp aes-128-cbc
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC     555328.03k   656223.25k   669154.56k   672292.52k   673603.58k   673650.01k

root@testub:/mnt/ssd# OPENSSL_ia32cap="~0x200000200000000" openssl speed -elapsed -evp aes-128-cbc
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-CBC     180846.61k   297741.33k   309245.70k   315153.07k   315869.87k   316336.81k
```
Also I tried truenas scale, looks like ZFS works on there.

**Comment by rincebrain** [comment]
Ubuntu pulled in changes in the Linux stable tree that broke FPU access a few months ago and didn't bother cherrypicking the fixes present in e.g. 2.1.5 that would fix this as well.

https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1977699 is their bug. https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1969482 has more state on why they're still totally broken.

Please test bugs against the latest stable release before reporting them here instead of to Ubuntu.

**Comment by lsylipei** [comment]
Thanks for finding those info, will report bug to ubuntu next time.
