### ISSUE TITLE
argument 2 of type 'const uint8_t[64]' {aka 'const unsigned char[64]'} with mismatched bound

### ISSUE THREAD

**Issue by mightyspiky** [openzfs/zfs#13658]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Oracle Linux
Distribution Version	| 8.6
Kernel Version	| 5.15.0-0.30.20.el8uek
Architecture	| aarch64
OpenZFS Version	| 2.1.5

### Describe the problem you're observing

When compiling kABI-tracking mod of zfs 2.1.5 on Oracle Linux 8.6 for aarch64 with the same commands I used with success for x86_64 with same kernel version, I get the following late after executing the make command:

```
...
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp/algs/sha1/sha1.o
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp/algs/sha2/sha2.o
/tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp/algs/sha1/sha1.c:422:44: error: argument 2 of type 'const uint8_t[64]' {aka 'const unsigned char[64]'} with mismatched bound [-Werror=array-parameter=]
  422 | SHA1Transform(SHA1_CTX *ctx, const uint8_t blk[64])
      |                              ~~~~~~~~~~~~~~^~~~~~~
/tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp/algs/sha1/sha1.c:69:39: note: previously declared as 'const uint8_t *' {aka 'const unsigned char *'}
   69 | static void SHA1Transform(SHA1_CTX *, const uint8_t *);
      |                                       ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:277: /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp/algs/sha1/sha1.o] Error 1
make[7]: *** Waiting for unfinished jobs....
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/bptree.o
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/btree.o
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/bqueue.o
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/dataset_kstats.o
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/dbuf.o
make[6]: *** [scripts/Makefile.build:540: /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/icp] Error 2
make[6]: *** Waiting for unfinished jobs....
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/dbuf_stats.o
...
  CC [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/vdev_raidz_math_aarch64_neonx2.o
  LD [M]  /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module/zfs/zfs.o
make[5]: *** [Makefile:1950: /tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module] Error 2
make[5]: Leaving directory '/usr/src/kernels/5.15.0-0.30.20.el8uek.aarch64'
make[4]: *** [Makefile:55: modules-Linux] Error 2
make[4]: Leaving directory '/tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5/module'
make[3]: *** [Makefile:929: all-recursive] Error 1
make[3]: Leaving directory '/tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5'
make[2]: *** [Makefile:790: all] Error 2
make[2]: Leaving directory '/tmp/zfs-build-root-uly0q25d/BUILD/zfs-2.1.5'
error: Bad exit status from /tmp/zfs-build-root-uly0q25d/TMP/rpm-tmp.qut1ba (%build)


RPM build errors:
    Bad exit status from /tmp/zfs-build-root-uly0q25d/TMP/rpm-tmp.qut1ba (%build)
make[1]: *** [Makefile:1688: rpm-common] Error 1
make[1]: Leaving directory '/root/zfs-2.1.5-20220714_205133/zfs-2.1.5'
make: *** [Makefile:1627: rpm-kmod] Error 2
[root@vm zfs-2.1.5]#
```

### Describe how to reproduce the problem

1. Trick the system with a modified uname command into thinking it was booted with the target kernel version (5.15.0) instead of the actual one (5.4.17) as mentioned in the last post of this issue: https://github.com/openzfs/zfs/issues/13625
2. scl enable gcc-toolset-11 "./configure --with-spec=redhat"
3. scl enable gcc-toolset-11 "make -j1 rpm-utils rpm-kmod"

**Comment by rincebrain** [comment]
#13192

**Comment by mightyspiky** [comment]
UweSauter said on march 12th that this file (sha1.c) was removed in master.. Why is it still here in 2.1.5? Also, contrarily to his issue, here it is treated as en error (not a warning) so it makes the compilation fails. Indeed, we can see the message "cc1: all warnings being treated as errors". If it is really benign, can I modify a setting somewhere to make the compiler treat warnings as warnings instead of treating them as errors?

**Comment by rincebrain** [comment]
Probably because it wasn't breaking build anywhere in 2.1.X.

There are two places that come to mind that might be spitting up -Werror into your CFLAGS - if you're building with --enable-debug, we do that (though I keep meaning to write a flag to stop that, because sometimes you want a debug build and don't want to go fix a bunch of missing linting just to shut it up), or the Oracle kernel might have backported the new kernel config option for enabling -Werror or just been built that way, and then I believe building against that kernel would default to the same CFLAGS again.

**Comment by mightyspiky** [comment]
So, I'll have to wait for a future zfs version I guess, right?

**Comment by rincebrain** [comment]
You can forcibly override the CFLAGS to include -Wno-error=[whatever it's upset about], or go drop sha1.c from the list of included files, since it's doing nothing.

**Comment by rincebrain** [comment]
Just apply https://github.com/openzfs/zfs/commit/a798b485aeff2bb0419ca95e5ed1cdd6bf7b6c00 probably.

**Comment by mightyspiky** [comment]
Thanks but I might wait for a future version because that's too much editing for me. What about your other solution (overriding CFLAGS)? Would it require an easier/smaller modification?

**Comment by mightyspiky** [comment]
Sorry for the newbie question. I think I'll close the issue because it has been responded to mostly, if not in its entirety. Thank you again rincebrain.

**Comment by rincebrain** [comment]
Aww, but I got you a present... #13661.

**Comment by mightyspiky** [comment]
I'm hoping that the current 4 failing checks will be easy to resolved.

**Comment by mightyspiky** [comment]
I've just tried with ZFS 2.1.6 and it compiles ok now. Thank you rincebrain 👍
