### ISSUE TITLE
Publish rpms on epel9

### ISSUE THREAD

**Issue by felfert** [openzfs/zfs#13738]
Subject says it all.
PLEASE create packages for RHEL9/Rocky9/Alma9

**Comment by tonyhutter** [comment]
https://github.com/zfsonlinux/zfsonlinux.github.com/pull/70 just got merged today, so hope to have packages out early next week.  See also: https://github.com/openzfs/zfs/issues/13542

**Comment by tonyhutter** [comment]
@felfert please give it a try on EL9:
```
dnf install https://zfsonlinux.org/epel/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
```

**Comment by felfert** [comment]
Works perfectly. Tested the following on a virtualized (OpenStack) Alma9.

dnf install https://zfsonlinux.org/epel/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
dnf install zfs
modprobe zfs
zpool create ...
zfs create ...
(Played around in the resulting file system)

Cheers
 -Fritz
