### ISSUE TITLE
403 Forbidden error on RHEL 7.9, but NOT CentOS 7.9

### ISSUE THREAD

**Issue by bits45** [openzfs/zfs#13739]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Red Hat Enterprise Linux 
Distribution Version	| 7.9
Kernel Version	| 3.10.0-1160.71.1.el7
Architecture	| x86_64
OpenZFS Version	| 2.1

### Describe the problem you're observing
On RHEL 7.9, all zfs repos are returning with  "failure: repodata/repomd.xml from zfs-kmod: [Errno 256] No more mirrors to try.
http://download.zfsonlinux.org/epel/7Server/kmod/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden".
This does NOT occur with the latest CentOS 7.9 - zfs installs great.
I've tried on two different builds of RHEL 7.9.  Both are standard installations.  All other RH repos, including EPEL, works just fine to install packages and updates.

### Describe how to reproduce the problem
just run 'yum install zfs' using zfs or zfs-kmod repo definition entry.

**Comment by tonyhutter** [comment]
I'm guessing you're using RHEL7 Server, which seems to use "7Server" instead of "7" for it's `$releasever` variable.  That's why you're getting a non-existent repo:
```
[zfs-kmod]
name=ZFS on Linux for EL$releasever - kmod
baseurl=http://download.zfsonlinux.org/epel/$releasever/kmod/$basearch/
...
```
I just created a symlink from `7Server -> 7`, so it *should* be good now.   Please try it again.

**Comment by bits45** [comment]
Works great now.  Thanks!  You guys rock!
