### ISSUE TITLE
dRAID: make_leaf_vdev() permits VDEV_TYPE_DRAID_SPARE

### ISSUE THREAD

**Issue by freqlabs** [openzfs/zfs#13766]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	| 2.1 thru master I expect

### Describe the problem you're observing
`cmd/zpool/zpool_vdev.c:make_leaf_vdev()` handles `zpool_is_draid_spare(arg)` as `VDEV_TYPE_DRAID_SPARE`, but that doesn't really make sense. dRAID spares are distributed. You can't construct a pool spec with a specific dspare device. Furthermore, `zpool_is_draid_spare()` checks for a string in the form of "draid%llu-%llu-%llu". I haven't bothered testing it (sorry) but I assume that would cause the pool creation to fail somewhere further along in the process.

This code should probably be removed.

### Describe how to reproduce the problem
/shrug read the code

**Comment by behlendorf** [comment]
My recollection is this is needed because `zpool replace` must be able to construct a pool spec which references the distributed spare.  But you're right, it really doesn't make any sense as part of `zpool create`.

**Comment by freqlabs** [comment]
Ah of course, I forgot to check what else uses `make_root_vdev()`.
