### ISSUE TITLE
Coverity seems to no longer be doing scans of the project

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#13835]
The coverity project was setup for zfsonlinux/zfs, but since we are now openzfs/zfs, the coverity link goes to an unregistered project and we can no longer get information from coverity’s static analyzer. I am not a member of the github organization at the moment, so I cannot volunteer to set it up.

**Comment by jumbi77** [comment]
Ping @behlendorf directly just to get sure.

**Comment by ryao** [comment]
It turns out that this requires someone to actively submit builds. I just volunteered, so I will be doing this going forward. My tentative plan is to submit a new build each week.
