### ISSUE TITLE
I hope to have a rpm package based on fedora aarch64 architecture

### ISSUE THREAD

**Issue by gesangtome** [openzfs/zfs#13850]
I have a raspberry pi 4B and installed fedora workstation based on aarch64 architecture on it. When I installed zfs using the source provided by openzfs, I found that aarch64 package was not provided, especially wanted one. expect!

**Comment by ryao** [comment]
I believe @behlendorf maintains the Fedora packaging (correct me if I am wrong).

That said, it would be faster to build it yourself ahead of him adding aarch64 packages.

**Comment by gesangtome** [comment]
@ryao Thanks!
