### ISSUE TITLE
syncfs(3) hangs until the end of the next TXG

### ISSUE THREAD

**Issue by Baughn** [openzfs/zfs#13860]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| NixOS
Distribution Version	| nixos-unstable 2022-09-22
Kernel Version	| 5.18.19
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.5-1

### Describe the problem you're observing

NixOS calls `sync -f /nix/store` during system rebuilds. This ends up calling syncfs. Assuming /nix/store is not set up with sync=disabled, syncfs then blocks until the end of the next TXG instead of triggering an early commit.

### Describe how to reproduce the problem

Run `sync -f /any/zfs/filesystem`, on a filesystem with sync=standard.

For bonus points, run `echo 300 > /sys/module/zfs/parameters/zfs_txg_timeout` first. This is my standard configuration; it dramatically reduces write activity on desktop systems (which tend to repeatedly rewrite the same files), or for servers such as Minecraft.

The command will block for up to 5 minutes, instead of returning ~immediately.

### Include any warning/errors/backtraces from the system logs

None; this is working as intended, near as I can tell. However, the intent of `sync -f` is to force an immediate commit; it shouldn't be waiting for the full timeout.

**Comment by Baughn** [comment]
Note that it should be perfectly safe to run with `sync=disabled` on /nix/store; the worst that might happen is you'll need to load the previous generation on boot, after a crash. This may still not be desirable on unattended systems, since /boot and /nix/store can get out of sync that way.

**Comment by behlendorf** [comment]
You can use `zpool sync` to force an immediate pool sync.

**Comment by Baughn** [comment]
While that works, it would be ideal if I could avoid submitting FS-specific workarounds to the OS code.

**Comment by Baughn** [comment]
This no longer seems to be a problem.
