### ISSUE TITLE
Commit 48cf170d5 breaks PowerPC build on FreeBSD

### ISSUE THREAD

**Issue by mmatuska** [openzfs/zfs#13934]
### System information
Type | Version/Name
 --- | ---
Distribution Name	|    FreeBSD
Distribution Version	|       14.0-CURRENT
Kernel Version	|        14.0-CURRENT main-n258120-c7046f76c2c0
Architecture	|    PowerPC
OpenZFS Version	|    2.1.99-FreeBSD_gc629f0bf6

### Describe the problem you're observing

lib/libspl/include/sys/simd.h: getauxval() declared on line 456 is redeclared on line 461

https://github.com/openzfs/zfs/blob/c629f0bf62e351355716f9870d6c2e377584b016/lib/libspl/include/sys/simd.h#L456-L461

### Describe how to reproduce the problem

Try to compile for PowerPC on FreeBSD

### Include any warning/errors/backtraces from the system logs

```
In file included from /usr/src/sys/contrib/openzfs/module/icp/algs/aes/aes_impl.c:28:
/usr/src/sys/contrib/openzfs/lib/libspl/include/sys/simd.h:461:22: error: static declaration of 'getauxval' follows non-static declaration
static unsigned long getauxval(unsigned long key)
                     ^
/usr/src/sys/contrib/openzfs/lib/libspl/include/sys/simd.h:456:22: note: previous declaration is here
extern unsigned long getauxval(unsigned long type);
                     ^
```

**Comment by mmatuska** [comment]
@mcmilk please verify

**Comment by mcmilk** [comment]
> @mcmilk please verify

I am sorry for this. The declaration of `extern unsigned long getauxval(unsigned long type)` belongs to the linux section.
I created a PR for fixing this: https://github.com/openzfs/zfs/pull/13936 - could you test this please.
