### ISSUE TITLE
Eliminate ARC's distinction between data and metadata for eviction

### ISSUE THREAD

**Issue by adamdmoss** [openzfs/zfs#13950]
### Describe the feature would like to see added to OpenZFS

The ARC should treat data and metadata equally (at least for the purposes of eviction) 

### How will this feature improve OpenZFS?

I believe it should simplify the ARC and help to eliminate issues such as https://github.com/openzfs/zfs/issues/10508 .  The eviction code, for example, quite imperfectly jumps through hoops to keep the eviction balance between ARC_BUFC_DATA and ARC_BUFC_METADATA arc lists 'fair' in a slightly doomed manner which I believe would just 'come out in the wash' if they were not distinct in the first place.

### Additional context

I seem to recall some Illumos engineers saying their version of ZFS does this and it turned out to be a good win.  [citation needed]
That anecdote is the strongest argument I have, to be honest, though having spent a lot of time in the ARC code it's a tempting direction if only for the sake of simplicity.

I imagine there was (or seemed like) a good reason to treat data and metadata separately in the first place though; not sure if that theory has been proven-out.

Downsides:
- There may be devil in the details to keep supporting primarycache=metadata.
- Code churn
- OpenZFS's test harness more or less exercises ARC robustness but I don't think we have anything (automated or otherwise) to prove that an ARC change is a perf win/loss, short of throwing it out to the world and letting people try it via a potentially very long release/feedback/response loop... but that's a bigger issue.

**Comment by ryao** [comment]
I remember the Solaris guys saying that they adopted this and it was a win. It is a little surprising that we have not done it yet.

**Comment by rincebrain** [comment]
Oracle Solaris, I believe, did indeed do this among other ARC changes, though I don't think there's a particularly good list of what those are outside their walls.

[This](https://blogs.oracle.com/solaris/post/changes-to-zfs-arc-memory-allocation-in-113) looks interesting, though.

**Comment by devZer0** [comment]
how can this be a win for people who have a metadata centric workload ? 

i know several examples where  "too early metadata eviction" is a big problem, leading to unecessary disk excercise and runtime enlargement by factors larger then 20

**Comment by ryao** [comment]
Instead of putting a hard limit on metadata in ARC, you could have metadata consume more space up to the full ARC size depending on what the algorithm determines is appropriate. Thus, it should be a sin in metadata centric workloads.

**Comment by devZer0** [comment]
if it works depends what's zfs's notion of metadata centric workload.

to have rsync backup run nightly on your pool is a metadata centric workload for me - but will zfs have the same understanding of that  ?  

if mru/mfu is being used to decide what's important to keep cached , zfs may oversee that it's better to keep a directory/file metadata entry in cache, even if only used once a day.

zfs keeps anything in cache what is needed frequently and what was used recently - that's different to keeping in cache what's providing the best performance benefit from the end-user-perspective.

**Comment by ryao** [comment]
ZFS has a separate ARC Meta Limit that keeps it from using space in ARC for metadata when it thinks the space should go to metadata rather than data.

**Comment by adamdmoss** [comment]
I whipped up a simplest-possible-thing at https://github.com/adamdmoss/zfs/tree/arclists - not extensively tested, YMMV etc.

**Comment by ryao** [comment]
@adamdmoss It needs some cleanup:

```
module/zfs/arc.c:468:12: error: 'zfs_arc_meta_adjust_restarts' defined but not used [-Werror=unused-variable]
[1064](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1065)
 static int zfs_arc_meta_adjust_restarts = 4096;
[1065](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1066)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1066](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1067)
module/zfs/arc.c:467:12: error: 'zfs_arc_meta_strategy' defined but not used [-Werror=unused-variable]
[1067](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1068)
 static int zfs_arc_meta_strategy = ARC_STRATEGY_META_BALANCED;
[1068](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1069)
            ^~~~~~~~~~~~~~~~~~~~~
[1069](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1070)
module/zfs/arc.c:466:12: error: 'zfs_arc_meta_prune' defined but not used [-Werror=unused-variable]
[1070](https://github.com/adamdmoss/zfs/actions/runs/3119550160/jobs/5059580577#step:7:1071)
 static int zfs_arc_meta_prune = 10000;
```

**Comment by ryao** [comment]
The kernel module parameters and their man page documentation should also be removed.

Once the warnings/errors are fixed, you could put it into a draft pull request so that the continuous integration infrastructure runs the test suite against it. It can take around 4 to 6 hours to get results (I forget exactly how long).

**Comment by adamdmoss** [comment]
There should only be warnings-as-errors, not errors.  There are reasons I didn't make it a PR. :)

**Comment by adamdmoss** [comment]
I've gotten rid of those three now though!

**Comment by adamdmoss** [comment]
> The kernel module parameters and their man page documentation should also be removed.

To be clear, I don't intend to do a PR - I was just prototyping out of interest to see how it behaved.  If people are really excited I could always finish the job, though.

**Comment by adamdmoss** [comment]
FWIW after an hour or so of playing around with this, I guess the draft behaves as I'd expect.  No explosions.  Data-vs-meta eviction 'comes out in the wash', MRU vs MFU balancing still works.  Data-vs-metadata accounting still looks plausible, though (by design) I doubt the ARC obeys metadata limits any more except insofar as they fall within overall ARC budget.  Switching from data-heavy to metadata-heavy workloads and back adapts gracefully enough in casual testing.

As to whether it helps or hurts vs master - hard to say without human invention; as I said in the summary, I don't think we have objective performance / case-capture tests for ARC.  I have my own local tests but I'm just-another-user-with-an-ad-hoc-test and an intrinsic bias.

**Comment by ryao** [comment]
I suspect that there are organizations that can evaluate the performance of this. Even I could, although it would take some time (that I do not have right now given that I already have a number of other projects).

**Comment by devZer0** [comment]
could you describe (for us noobs) what your patch exactly does @adamdmoss ?   i don't understand how eliminating arc's distinction of data and metadata can help.   in linux pagecache, we can use vfs_cache_pressure  to prefer metadata over ordinary data. so how does this help with metadata centric workloads and how can we make sure, metadata keeps getting cached ?

**Comment by ryao** [comment]
The ARC algorithm will intelligently learn what data should remain in cache. There is no need to give it special treatment.

**Comment by adamdmoss** [comment]
Right, that is the premise.

**Comment by scineram** [comment]
Great idea, as Oracle did it. However would it make sense to keep at least the separate arcstats? Just for visibility.

**Comment by zfsuser** [comment]
What would be the consequences for L2ARC?

**Comment by zfsuser** [comment]
Here a link to a discussion regarding merging of data and metadata: https://github.com/openzfs/zfs/issues/10957#issuecomment-697231557

**Comment by adamdmoss** [comment]
> What would be the consequences for L2ARC?

None AFAICT

**Comment by malventano** [comment]
> The ARC should treat data and metadata equally (at least for the purposes of eviction)
> I believe it should simplify the ARC and help to eliminate issues such as #10508 .

You're citing my thread as something your suggestion would correct, but I suspect your proposal would do the exact opposite. For many use cases, metadata cache misses carry a significantly higher performance penalty than data cache misses. This would be correctable if zfs_arc_meta_min functioned properly, or if metadata carried a more appropriate priority in MFU eviction decisions, or if MFU was even working as expected (lots of data being touched once for a large copy should not cause metadata being accessed every 5 minutes to be evicted). The penalty of slow metadata access is so widely understood that it is why special vdev's exist. Even if this proposal could somehow correct the issue, I don't think the answer is to hit it with such a large hammer as to break lots of other functionality (every other ZFS component that distinguishes between data and metadata). Also, given the special vdev does exist, your proposal would remove properties that some may wish to dial in the *opposite* direction (user with special vdev on fast storage might *reduce* metadata limits for arc).

We don't need metadata and data treated equally in arc. We need the exact opposite, and we need those metadata specific parameters to function correctly.

**Comment by nim-odoo** [comment]
> I believe it should simplify the ARC and help to eliminate issues such as https://github.com/openzfs/zfs/issues/10508 .

That's one way to see it. Let's remove a functionality so we will remove the associated issues.

I think being able to distinguish the data and metadata in the cache is a really nice feature. It would be nicer if users wouldn't be hit by weird behaviors. See for example https://github.com/openzfs/zfs/issues/10508#issuecomment-947723776 Setting `primarycache=metadata` leads to very weird evictions. So there is already something wrong going on there.

> The ARC algorithm will intelligently learn what should remain in cache.

As an end user, it's more useful to be able to force a behavior rather than letting the ARC algorithm decide. The case of rsync is a valid use case for this. The ARC algorithm will never have the whole context behind its usage. The end user may have good functional reasons to push metadata rather than data in the ARC.

**Comment by youzhongyang** [comment]
No, distinction between data and metadata when it comes to eviction is a bad idea. We've frequently seen long period of high iowait (something like 20~40% for 0.5hour+) due to eviction. Doing the right thing with less tuning parameters is more desirable.

**Comment by ryao** [comment]
ARC is supposed to self tune, so it should discover distinctions on its own. The idea needs testing.

**Comment by bghira** [comment]
this reminds me of removing the block layer from ZVOLs, which made them a lot less performant and less useful.

**Comment by ryao** [comment]
> this reminds me of removing the block layer from ZVOLs, which made them a lot less performant and less useful. but at that time, ryao was proposing that the change would be beneficial. since then, ryao hasn't made much effort toward improving that code, and now it's up to others. so, zvols are still broken.

It was supposed to be and was better in certain workloads, but sadly, the extra time needed to finish the requests was bad for queue depth limited workloads. Getting the best of both worlds needed us to hook into the DMU's asynchronous code paths, but I never had time to do that. I understand that #12166 is supposed to do that.

That said, I think we can all agree that better benchmark setups are needed.

**Comment by malventano** [comment]
> No, distinction between data and metadata when it comes to eviction is a bad idea. We've frequently seen long period of high iowait (something like 20~40% for 0.5hour+) due to eviction. Doing the right thing with less tuning parameters is more desirable.

It's entirely possible that the issue you saw was due to metadata eviction that should not have happened, and could be *more likely* to occur if the distinction was removed.

> No, distinction between data and metadata when it comes to eviction is a bad idea. We've frequently seen long period of high iowait (something like 20~40% for 0.5hour+) due to eviction. Doing the right thing with less tuning parameters is more desirable.

The current tuning parameters are not working properly. Perhaps those issues should be addressed first.

> ARC is supposed to self tune, so it should discover distinctions on its own.

You are overestimating its capabilities. It needs additional context to be as smart as you assume it is. That context comes in the form of distinguishing between metadata and data.

> That said, I think we can all agree that better benchmark setups are needed.

Indeed, but real-world observations are always more realistic than benchmarks, and in this case, we have multiple field reports tracking metadata eviction occurring when it shouldn't. Removing arc's distinction for metadata would make the problem worse for those cases, as there would be no way to require that metadata specifically remains in the arc (a feature that currently appears to be bugged based on those reports).

**Comment by adamdmoss** [comment]
The nice thing about having a prototype in-hand is we don't really have to endlessly theorize about how it might be a good/terrible idea.  IMHO.

**Comment by aheid** [comment]
There was some talk (leadership meeting?) about making the ARC aware of how "expensive" it would be to re-fetch a block. The background was that if you had a heterogeneous pool some blocks could take a lot longer to read than others. Thus it would be more valuable to keep the expensive or slow blocks in cache, and evict the cheap or fast blocks. If the ARC then could be aware of the "price" of evicting a block, it could improve the effective performance of the cache.

I was wondering if this could also solve the metadata caching issue described here. One could implement the proposed change eliminate ARC's explicit distinction of metadata and data blocks, but introduce a tunable which allows one to weight metadata blocks as more "expensive" than data blocks. The ARC would then juggle its MRU and MFU oblivious to what the blocks hold, but would evict the "cheapest" blocks first. People with metadata-heavy workloads could set the tunable to heavily favor evicting data blocks, and vice versa if so desired.

Just idle thoughts from a non-expert...

**Comment by IvanVolosyuk** [comment]
Self-tuning is awesome in theory, but there are mixed workloads where fine-tuning can be beneficial. I just figured out in my system that while my system and my VMs use arc/l2arc quite effectively I have a video stream constantly recorded to one of my datasets which introduce churn on my l2arc lowering it effectiveness by several times. I disabled secondarycache completely for that dataset and changed primarycache to metadata to stop washing the useful data out of arc, but still allowing effective writes without need of reading metadata back on each write.

Thus, distinction or at least tracking of the type of data give a valuable tool to adminstrators. Per-dataset tunable is awesome!

**Comment by shodanshok** [comment]
I tested here in https://github.com/openzfs/zfs/issues/12028#issuecomment-1291818413 @adamdmoss draft removing data/metadata distinction in the eviction path and, for what they are worth, my results where not particularly good. So I would left metadata special handling as-is (or even improve it).

**Comment by adamdmoss** [comment]
Thanks for the testing, I really appreciate it!
