### ISSUE TITLE
Importing a degraded pool with zvols is extremely slow

### ISSUE THREAD

**Issue by asomers** [openzfs/zfs#13999]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| 
Distribution Version	|
Kernel Version	| FreeBSD 13.1-RELEASE
Architecture	| amd64
OpenZFS Version	| zfs-2.1.4-FreeBSD_g52bad4f23 zfs-kmod-2.1.4-FreeBSD_g52bad4f23

### Describe the problem you're observing

I have a degraded pool with about 1000 zvols.  Importing this pool takes more than an hour.  Procstat shows the following stack trace for most of that time:
```
mi_switch+0xc2
_cv_wait+0x113
txg_wait_synced_impl+0xb9
txg_wait_synced+0xb
zil_close+0xdf
zvol_create_minor_impl+0x67c
zvol_create_minors_recursive+0xf5
spa_import+0x718
zfs_ioc_pool_import+0xb0
zfsdev_ioctl_common+0x548
zfsdev_ioctl+0x143
devfs_ioctl+0xc6
vn_ioctl+0x1a4
devfs_ioctl_f+0x1e
kern_ioctl+0x25b
sys_ioctl+0xf1
amd64_syscall+0x10c
fast_syscall_common+0xf8 
```
Both dtrace and `find /dev/zvol -type c | wc` show that `zvol_create_minor_impl` can take up to 15s to create a single zvol.  At the same time, the `zfs-dbgmsg` dtrace probe shows plenty of activity like this:
```
dsl_scan.c:2451:dsl_scan_visitds(): scanned dataset 471355 (<POOL>/<DATASET>@<SNAP>) with min=2694762 max=2694782; suspending=0
```
So my theory is that the resilver is blocking transactions from syncing for several seconds at a time, which holds up `zil_close`.  That happens even though there shouldn't be any zil entries for these zvols, as they haven't been used for a long time.

### Possible solution

Would it be possible to safely skip `zil_close`, or skip the `txg_wait_synced` within it, if there were no entries to replay in `zil_replay`?

### Describe how to reproduce the problem

I can very easily reproduce the problem on a healthy, already-imported pool just by trying to create a new zvol while user writes are in progress.  Run these two commands in different terminals:
```
sudo dd if=/dev/random bs=16k of=/testpool/randfile.concurrent2
```
and
```
time sudo zfs create -V 64m -s testpool/zvoltest/vol.21
```
The `zfs create` command by itself typically takes less than one second.  But while `dd` is running it can take more than a minute.  And for much of that time it has a similar stack trace as above:
```
mi_switch+0x157
sleepq_switch+0x107
_cv_wait+0x166
txg_wait_synced_impl+0x288
txg_wait_synced+0x29
zil_close+0x2c3
zvol_os_create_minor+0x9ca
zvol_create_minor+0x7f
dmu_objset_create+0xfe
zfs_ioc_create+0x497
zfsdev_ioctl_common+0x5da
zfsdev_ioctl+0x1e5
devfs_ioctl+0xcd
vn_ioctl+0x131
devfs_ioctl_f+0x1e
kern_ioctl+0x202
sys_ioctl+0x12a
amd64_syscall+0x12e 
```

**Comment by allanjude** [comment]
Is it mostly on snapshots? I would expect you'd be able to skip the ZIL bits on a snapshot since it is read only.

**Comment by asomers** [comment]
> Is it mostly on snapshots? I would expect you'd be able to skip the ZIL bits on a snapshot since it is read only.

No, most of these zvols don't have any snapshots.
