### ISSUE TITLE
Zfs Installation failed on dependency error

### ISSUE THREAD

**Issue by arun-tvz** [openzfs/zfs#14046]
Distribution Name:	Amazon linux2
Kernel Version:	5.10.135-122.509
Architecture: x86_64
OpenZFS Version	2.1.6
 
I'm trying to install the zfs in my Amazon linux 2 machine there it fails with the following errors:

Commands used: 
  `sudo yum install https://zfsonlinux.org/epel/zfs-release.el8_6.noarch.rpm 
`
`sudo yum install -y kernel-devel`

`sudo yum install zfs`

Errors 

```
Error: Package: libzfs5-2.1.6-1.el8.x86_64 (zfs)
           Requires: libtirpc.so.3()(64bit)
Error: Package: libzfs5-2.1.6-1.el8.x86_64 (zfs)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: libzpool5-2.1.6-1.el8.x86_64 (zfs)
           Requires: libtirpc.so.3()(64bit)
Error: Package: libnvpair3-2.1.6-1.el8.x86_64 (zfs)
           Requires: libtirpc.so.3()(64bit)
Error: Package: libzpool5-2.1.6-1.el8.x86_64 (zfs)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: zfs-2.1.6-1.el8.x86_64 (zfs)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: libnvpair3-2.1.6-1.el8.x86_64 (zfs)
           Requires: libtirpc.so.3(TIRPC_0.3.0)(64bit)
Error: Package: zfs-2.1.6-1.el8.x86_64 (zfs)
           Requires: libtirpc.so.3()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
After this I checked for this dependency I think its installed if not let me know how to Install it.
```
[ec2-user ~]$ yum list libtirpc
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed Packages
libtirpc.x86_64                                                       0.2.4-0.16.amzn2                                                       installed 
Available Packages
libtirpc.i686                                                         0.2.4-0.16.amzn2                                                       amzn2-core
```

This is the error that I got while doing the steps and If try with older versions it seems working but to load modules we needed to reboot, Is there any way to Install it in correct way (Modules loaded without reboot).

**Comment by szubersk** [comment]
@arun-tvz Amazon Linux 2 observes RHEL 7 compatibility (as of now at least). Please try
```
sudo yum -y install https://zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm kernel-devel
sudo  yum -y install zfs
```
It worked for me flawlessly on instance spawned from `ami-07620139298af599e (amzn2-ami-kernel-5.10-hvm-2.0.20220606.1-x86_64-gp2)`.

Please let us know if it solved your problem, and if so, feel free to close this issue report.

**Comment by arun-tvz** [comment]
Yep its Installed but when we try to access any zfs command its module not getting loaded 
```
[ec2-user ~]$ zfs list tank
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
[ec2-user ~]$ /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.10.135-122.509.amzn2.x86_64
[ec2-user@ ~]$ sudo /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.10.135-122.509.amzn2.x86_64
```

**Comment by szubersk** [comment]
There's a weird and subtle bug in how AL2 resolves dependencies from `amazon-linux-extras` streams. When having a kernel update pending but still running an older kernel, `yum -y install kernel-devel` install headers for the newer kernel, not the running one. This interferes with how `dkms` works and prevents it from compiling the kernel module.

To circumvent the issue first upgrade kernel and reboot instance
```
sudo  yum -y upgrade
sudo reboot
```

Commands above guarantee that you run the newest kernel version. Now execute
```
sudo yum -y install https://zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm kernel-devel
sudo yum -y install zfs
```

and enjoy OpenZFS on Amazon Linux 2.

**Comment by szubersk** [comment]
Would you share the error log?

**Comment by szubersk** [comment]
Would you share the output of
```
uname -a
ls -l /usr/src/kernels
```
?

**Comment by szubersk** [comment]
Without reboot:
```
sudo yum -y install https://zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm kernel-devel-$(uname -r)
sudo yum -y install zfs
```

Please mind that any `yum upgrade` can upgrade the kernel image and headers package, resulting in OpenZFS kernel module recompilation. Best to double check after upgrade if zfs.ko module is available in `/lib/modules/<new kernel version>`.

**Comment by arun-tvz** [comment]
Nope Installation only succeed, modules are not coming to  /lib/modules/5.4.209-116.367.amzn2.x86_64 even after reboot,
There are just two relevant dirs only  
 -  /usr/src/zfs-2.0.7/module/zfs/
 - /var/lib/dkms/zfs/2.0.7/build/module/zfs/

**Comment by szubersk** [comment]
You'd need to remove the packages to start from a clean slate and install them again.
```
yum -y remove zfs kernel-devel
```

**Comment by arun-tvz** [comment]
I'm Doing all things in a fresh amazon linux only nothing helps, before I can't do the installation now I could but the module loading isn't happening..

**Comment by szubersk** [comment]
Which AMI and region do you use?

**Comment by arun-tvz** [comment]
we found another way to do it, gonna use ubuntu ami for it it works fine with that, Thanks all for your help

**Comment by szubersk** [comment]
If it solves your problem, fine. I just want you to know that I successfully installed OpenZFS on Amazon Linux 2. There's a chance that you use version 1 of AL.

Thanks for closing this ticket and providing a resolution.
