### ISSUE TITLE
Cannot Decrypt Dataset(s) Under v2.1.6 Created Using v2.1.0

### ISSUE THREAD

**Issue by Haravikk** [openzfs/zfs#14083]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| MacOS
Distribution Version	| 10.15.7
Kernel Version	| Darwin 19.6.0
Architecture	| Intel x86_64
OpenZFS Version	| 2.1.0/2.1.6

### Describe the problem you're observing
I have two zpools and a number datasets, some encrypted some not, all created under v2.1.0. After upgrading to v2.1.6 I found I was unable to load the keys for any of the encrypted datasets via any command that can do so (`zfs mount -l`, `zfs load-key` etc.).

I decided not to run `zpool upgrade` on either pool for fear of being unable to downgrade if it didn't fix it. Instead I tried creating a new test zpool (using a file) and copied one of my datasets across using `zfs send -w` but couldn't load the key there either.

All of my keys are simple prompt (passphrase) type keys, and I'm definitely entering the correct values. Fortunately downgrading back to 2.1.0 went smoothly and I can continue using my datasets without issue, but I was hoping to take advantage of the much improved encryption performance of later versions.

### Describe how to reproduce the problem
1. Under OpenZFS 2.1.0 create an encrypted dataset with a basic key prompt. For example: `zfs create -o encryption=on -o keylocation=prompt -o keyformat=passphrase zpool/test`
2. Upgrade to 2.1.6.
3. Attempt to load the key for the encrypted dataset.

ZFS will claim the key is incorrect, despite the same key working to decrypt the dataset under 2.1.0.

### Notes
Unfortunately versions 2.1.1-2.1.5 were never fully released for macOS so I'm unable to test those to see if there is a more precise version at which this issue began. I can't imagine the key format has changed though so I'm at a total loss as to why I can't decrypt my datasets under 2.1.6?

In case it helps with reproducing, or in case there is something specific to me that's the problem, I've created a raw send file (2mb) for a small test dataset that should demonstrate this problem when received by a zpool under 2.1.6, the passphrase to load the key is `thisisatest`. You can download this at the link below: https://www.dropbox.com/s/qicvihvwn167a7a/test.sendfile.zip?dl=0

After unzipping you should be able to import using `cat test.sendfile >> zfs receive -d zpool`

Also in case there are any other clues, here is the output of `zfs get all` for one of my other encrypted datasets (command run under 2.1.0):

````
NAME            PROPERTY                VALUE                   SOURCE
zdata/haravikk  type                    filesystem              -
zdata/haravikk  creation                Tue Jan 18 13:39 2022   -
zdata/haravikk  used                    156G                    -
zdata/haravikk  available               87.8G                   -
zdata/haravikk  referenced              85.8G                   -
zdata/haravikk  compressratio           1.47x                   -
zdata/haravikk  mounted                 yes                     -
zdata/haravikk  quota                   none                    default
zdata/haravikk  reservation             none                    default
zdata/haravikk  recordsize              128K                    default
zdata/haravikk  mountpoint              /Users/haravikk         local
zdata/haravikk  sharenfs                off                     default
zdata/haravikk  checksum                on                      default
zdata/haravikk  compression             zstd                    inherited from zdata
zdata/haravikk  atime                   on                      default
zdata/haravikk  devices                 on                      default
zdata/haravikk  exec                    on                      default
zdata/haravikk  setuid                  on                      default
zdata/haravikk  readonly                off                     local
zdata/haravikk  zoned                   off                     default
zdata/haravikk  snapdir                 hidden                  default
zdata/haravikk  aclmode                 discard                 default
zdata/haravikk  aclinherit              restricted              default
zdata/haravikk  createtxg               20594                   -
zdata/haravikk  canmount                on                      local
zdata/haravikk  xattr                   sa                      inherited from zdata
zdata/haravikk  copies                  2                       inherited from zdata
zdata/haravikk  version                 5                       -
zdata/haravikk  utf8only                on                      -
zdata/haravikk  normalization           formD                   -
zdata/haravikk  casesensitivity         insensitive             -
zdata/haravikk  vscan                   off                     default
zdata/haravikk  nbmand                  off                     default
zdata/haravikk  sharesmb                off                     default
zdata/haravikk  refquota                none                    default
zdata/haravikk  refreservation          none                    default
zdata/haravikk  guid                    2573759543303897741     -
zdata/haravikk  primarycache            all                     default
zdata/haravikk  secondarycache          all                     default
zdata/haravikk  usedbysnapshots         0B                      -
zdata/haravikk  usedbydataset           85.8G                   -
zdata/haravikk  usedbychildren          70.4G                   -
zdata/haravikk  usedbyrefreservation    0B                      -
zdata/haravikk  logbias                 latency                 default
zdata/haravikk  objsetid                31                      -
zdata/haravikk  dedup                   off                     default
zdata/haravikk  mlslabel                none                    default
zdata/haravikk  sync                    standard                default
zdata/haravikk  dnodesize               auto                    inherited from zdata
zdata/haravikk  refcompressratio        1.34x                   -
zdata/haravikk  written                 85.8G                   -
zdata/haravikk  logicalused             151G                    -
zdata/haravikk  logicalreferenced       57.0G                   -
zdata/haravikk  volmode                 default                 default
zdata/haravikk  filesystem_limit        none                    default
zdata/haravikk  snapshot_limit          none                    default
zdata/haravikk  filesystem_count        none                    default
zdata/haravikk  snapshot_count          none                    default
zdata/haravikk  snapdev                 hidden                  default
zdata/haravikk  acltype                 nfsv4                   default
zdata/haravikk  context                 none                    default
zdata/haravikk  fscontext               none                    default
zdata/haravikk  defcontext              none                    default
zdata/haravikk  rootcontext             none                    default
zdata/haravikk  relatime                on                      inherited from zdata
zdata/haravikk  redundant_metadata      all                     default
zdata/haravikk  overlay                 on                      default
zdata/haravikk  encryption              aes-256-gcm             -
zdata/haravikk  keylocation             prompt                  local
zdata/haravikk  keyformat               passphrase              -
zdata/haravikk  pbkdf2iters             350000                  -
zdata/haravikk  encryptionroot          zdata/haravikk            -
zdata/haravikk  keystatus               available               -
zdata/haravikk  special_small_blocks    0                       default
zdata/haravikk  com.apple.browse        on                      inherited from zdata
zdata/haravikk  com.apple.ignoreowner   off                     inherited from zdata
zdata/haravikk  com.apple.mimic         hfs                     inherited from zdata
zdata/haravikk  com.apple.devdisk       on                      inherited from zdata
````

**Comment by rincebrain** [comment]
I think this is just #13709, so you might find [this](https://github.com/openzfs/zfs/issues/13709#issuecomment-1232430808) useful, and I have it on good authority this will be treated as a bug and fixed.

**Comment by Haravikk** [comment]
Strange, I'm not seeing an I/O error as in #13709, I just get an error like the key is wrong (when it isn't). I'll see if I can find time later in the week to setup a simpler test environment and see if the same workaround works or not!

There's definitely something that needs fixing! I'm surprised no tests picked this up though, are some new tests needed to check for encryption regressions? Or are only some users affected?

**Comment by rincebrain** [comment]
So, the thing is, this requires you have a pool written by the old version and unlock on the new version, IIUC. I think most of the test suite cases involve creating a filesystem anew or receiving a send stream anew, and since the data that was problematic is regenerated on recv, it wouldn't have been caught by those.

That's just speculation, though, I haven't gone and checked all the test cases to confirm that.

**Comment by rincebrain** [comment]
What's the key for that test send stream? I can't really tell if it's failing because I don't know the key or failing because it's broken without that data point, I think...

**Comment by Haravikk** [comment]
Whoops, should have known I'd forget! The password is `thisisatest`, I'll add it to the first post as well.

**Comment by rincebrain** [comment]
@lundman is the source to 2.1.6RC1 and RC2 available somewhere? I got curious to find what the delta was between them and couldn't find anything newer than 2 months ago...

**Comment by rincebrain** [comment]
`If you can access this file on ZFS v2.1.6 then I have no idea what is going on, because I cannot`

Just as a data point, yes, that recvs and unlocks fine on OpenZFS on Linux 2.1.2 and 2.1.6.

**Comment by Haravikk** [comment]
Okay, in that case it must have been macOS specific, sorry!
