### ISSUE TITLE
Mismatch between pool hostid and system hostid after upgrading kernel

### ISSUE THREAD

**Issue by mightyspiky** [openzfs/zfs#14096]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Oracle Linux
Distribution Version	| 8.6
Kernel Version	| 5.15.0-3.60.5.1.el8uek
Architecture	| x86_64
OpenZFS Version	| 2.1.6

### Describe the problem you're observing

After upgrading to kernel version 5.15.0-3.60.5.1.el8uek, "zpool status" gives a warning about "Mismatch between pool hostid and system hostid on imported pool.". If I manually export then import the pool, the warning goes away but as soon as I reboot, the problem reappears. I've also tried the workaround mentioned by @behlendorf in https://github.com/openzfs/zfs/issues/9367#issuecomment-536045345 but it doesn't work. If I rollback to kernel version 5.15.0-2.52.3.el8uek, the problem is not present.

This problem appears on my x86_64 system which has a raidz of three drives. I also have a aarch64 vm with same distribution and kernel version (5.15.0-3.60.5.1.el8uek) which has a zpool consisting in a single drive and that zpool hasn't the problem.

### Describe how to reproduce the problem

1. Boot on kernel version 5.15.0-3.60.5.1.el8uek and ZFS 2.1.6
2. zpool status <pool>

**Comment by ryao** [comment]
I have had an issue like this in the past. The problem was an initramfs that had a different hosted than my system. I am not sure if that is your problem here, but it is worth checking.

**Comment by mightyspiky** [comment]
Indeed, I've copied etc/hostid from the initramfs into /etc/hostid on the host (the file on the host was inexistant before) and the problem disappeared. Thanks.
