### ISSUE TITLE
Can not set zfs_vdev_cache_size

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#14107]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 9.0
Kernel Version	| 5.14.0-70.26.1.el9_0.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.6-1

### Describe the problem you're observing
Can not set/enable `zfs_vdev_cache_size`:
```
[root@localhost parameters]# echo 16777216 > zfs_vdev_cache_size
-bash: zfs_vdev_cache_size: Permission denied
```

I understand that vdev cache is deemed as unneeded and possibile harmful for performance. However, I would like to measure it in my workload. Unless the option is already broken/partially removed, setting it should be allowed.

### Describe how to reproduce the problem
Try setting `zfs_vdev_cache_size`

### Include any warning/errors/backtraces from the system logs

None

**Comment by behlendorf** [comment]
It should be settable at module load time, `modprobe zfs zfs_vdev_cache_size=16777216`.  Or with a small patch.

```diff
diff --git a/module/zfs/vdev_cache.c b/module/zfs/vdev_cache.c
index f0a17600d..83b856bc9 100644
--- a/module/zfs/vdev_cache.c
+++ b/module/zfs/vdev_cache.c
@@ -429,7 +429,7 @@ vdev_cache_stat_fini(void)
 ZFS_MODULE_PARAM(zfs_vdev, zfs_vdev_, cache_max, UINT, ZMOD_RW,
        "Inflate reads small than max");
 
-ZFS_MODULE_PARAM(zfs_vdev, zfs_vdev_, cache_size, UINT, ZMOD_RD,
+ZFS_MODULE_PARAM(zfs_vdev, zfs_vdev_, cache_size, UINT, ZMOD_RW,
        "Total size of the per-disk cache");
 
 ZFS_MODULE_PARAM(zfs_vdev, zfs_vdev_, cache_bshift, UINT, ZMOD_RW,
```

**Comment by shodanshok** [comment]
@behlendorf thanks for the quick reply, I was derailed by the docs which [here](https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#zfs-vdev-cache-size) state that the change is "dynamic". I'll try and report back.

Regards.

**Comment by shodanshok** [comment]
I can confirm that vdev cache was not useful for the issue I was trying to tackle. More details [here](https://zfsonlinux.topicbox.com/groups/zfs-discuss/T01121e152af85f9f-M19a0cdf718d4f75e49e1629b)

Closing.
