### ISSUE TITLE
zfs rpm release 2.2 obsoletes itself in Fedora 

### ISSUE THREAD

**Issue by aNDy-Squirrel** [openzfs/zfs#14108]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 36
Kernel Version	|  5.19.16-200.fc36.x86_64
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.6-1

### Describe the problem you're observing
`dnf check-update `gives me:

```
Obsoleting Packages
zfs-release.noarch                                  2-2.fc36                                 @@commandline         
    zfs-release.noarch                              2-2.fc36                                 @@commandline 
```
and examining the rpm:
```
rpm  -qp zfs-release-2-2.fc36.noarch.rpm --obsoletes
zfs-release <= 2-2.fc36
zfs-release-fedora <= 2-2.fc36
```
suggests that the rpm obsoletes its own version.

I am not an expert, but it looks to me as a packaging issue. Everything else works fine.

### Describe how to reproduce the problem
Install zfs via the repo on zfsonlinux.org: 
`dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm`

I have two systems with similar set-up, and both have this issue.

**Comment by jollyrogue** [comment]
This happens on Rocky Linux 8 too.

I installed ZFS per the documentation on a fresh install, and `zfs-release 2.2` obsoleting itself in favor of `zfs-release 2.2` shows up immediately.

**Comment by mreymann** [comment]
Same issue on AlmaLinux 9.1:
`$ yum check-update
Last metadata expiration check: 0:08:49 ago on Wed 12 Apr 2023 02:08:14 PM CEST.
Obsoleting Packages
zfs-release.noarch                                                                     2-2.el9                                                                  @@commandline
    zfs-release.noarch                                                                 2-2.el9                                                                  @@commandline

$ rpm  -q zfs-release-2-2.el9.noarch --obsoletes
zfs-release <= 2-2.el9
zfs-release-el <= 2-2.el9`

**Comment by agvol** [comment]
> Same issue on AlmaLinux 9.1:
> 
> ```
> $ yum check-update
> Last metadata expiration check: 0:08:49 ago on Wed 12 Apr 2023 02:08:14 PM CEST.
> Obsoleting Packages
> zfs-release.noarch                                                                     2-2.el9                                                                  @@commandline
>     zfs-release.noarch                                                                 2-2.el9                                                                  @@commandline
> 
> $ rpm  -q zfs-release-2-2.el9.noarch --obsoletes
> zfs-release <= 2-2.el9
> zfs-release-el <= 2-2.el9
> ```

Try to make update 
`dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm`

**Comment by aNDy-Squirrel** [comment]
> Try to make update `dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm`

That solved it for me. I uninstalled the 2-2 version first, but I am not sure whether that is necessary or would happen anyway. Thanks!

Issue can be closed.
