### ISSUE TITLE
signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust

### ISSUE THREAD

**Issue by little-helper-001** [openzfs/zfs#14205]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| ArchLinux
Distribution Version	|
Kernel Version	| 6.0.8-hardened1-1-hardened
Architecture	| x86
OpenZFS Version	| zfs-2.1.6-1

### Describe the problem you're observing

Trying to run any command with Arch's package manager pacman results in something along the lines of:
```
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community                                    7.2 MiB  3.16 MiB/s 00:02 [########################################] 100%
 archzfs                                     14.1 KiB  36.5 KiB/s 00:00 [########################################] 100%
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

**Comment by ryao** [comment]
I suggest reporting this to the Arch Linux developers. They are in a better position to investigate it.

**Comment by AttilaFueloep** [comment]
Did you follow the instructions given in the [archzfs wiki](https://github.com/archzfs/archzfs/wiki#using-the-archzfs-repository)? If you did and it's still broken, I'd look at https://github.com/archzfs/archzfs/issues/346 before following Richards suggestion to open an new issue there.

This issue can be closed, since the archzfs repo is the proper place to report to.

**Comment by AttilaFueloep** [comment]
https://github.com/archzfs/archzfs/issues/342#issuecomment-656938477 is also worth to look at.

**Comment by zow34tq** [comment]
> I suggest reporting this to the Arch Linux developers. They are in a better position to investigate it.

Ill tell you now abd never again i load a custom server client side loaded clone certificate program titled .conf('conficker') to surrender government overlord abuse of discretions...

So it basically just loads a subcontractor titleivx-i sus apple montigo applied univramgraphic sys.andeoid.es.ses.sel.setsPara sloc..2sl2.3 point insertion of the security camera embedded net and Java programming services PHP... Then it translates it all back to html 

.∆/g.load csp.sus/updatewin7.1asdk('O') tracker4

**Comment by zow34tq** [comment]
@gmelikov ℹ️🆕👌🏿

/*/*/ .∆/g.load csp.sus/updatewin7.1asdk
Append.xtor.breakpt4.500

**Comment by little-helper-001** [comment]
Thank you @AttilaFueloep. I did in fact follow the procedure yesterday and it did result in the same error message as mentioned above. However after a good nights sleep for my computer and me, refreshing they arch keyring and then following the very same instructions resulted in them finishing without an error message today! So as of now the problem is resolved. I will close the issue with this comment, still a lot of thanks to all taking the time to answer!
