### ISSUE TITLE
linux: zfs volume snapshot rename does not generate KOBJ_CHANGE, /dev/zvol/.... link is not updated

### ISSUE THREAD

**Issue by JKDingwall** [openzfs/zfs#14223]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| Focal / 20.04
Kernel Version	| 5.4.0-133-generic (local build of Ubuntu tag)
Architecture	| amd64
OpenZFS Version	| zfs-2.1.6-1 / zfs-kmod-2.1.6-1

### Describe the problem you're observing

When a volume snapshot is renamed `zfs rename pool/volume@snap pool/volume@other` the corresponding /dev/zvol/... link is not updated.  Running `udevadm monitor` shows no uevent is generated for the action.  If the volume (not snapshot) is renamed then uevents are generated and all links are correct.

### Describe how to reproduce the problem

```
root@ubuntu:~# zfs create -V 20G ztank/james

root@ubuntu:~# zfs snapshot ztank/james@1

root@ubuntu:~# zfs snapshot ztank/james@2

root@ubuntu:~# ls -l /dev/zvol/ztank/james*
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james -> ../../zd2736
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james@1 -> ../../zd2752
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james@2 -> ../../zd2768

root@ubuntu:~# zfs rename ztank/james@1 ztank/james@3

root@ubuntu:~# ls -l /dev/zvol/ztank/james*
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james -> ../../zd2736
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james@1 -> ../../zd2752
lrwxrwxrwx 1 root root 12 Nov 24 13:00 /dev/zvol/ztank/james@2 -> ../../zd2768
```

The expected result is that the @1 symlink is removed and an @3 one is created.

### Include any warning/errors/backtraces from the system logs

No messages are recorded in syslog or kern.log which indicate an error.

**Comment by JKDingwall** [comment]
I don't know if this is interesting:

```
root@ubuntu:~# /lib/udev/zvol_id /dev/zd2736
ztank/james

root@ubuntu:~# /lib/udev/zvol_id /dev/zd2768
ztank/james@2

root@ubuntu:~# /lib/udev/zvol_id /dev/zd2752
Unable to open device file: /dev/zd2752

root@ubuntu:~# ls -l /dev/zd2752
brw-rw---- 1 root disk 230, 2752 Nov 24 13:44 /dev/zd2752
```

**Comment by JKDingwall** [comment]
If there is patch we would be willing to test it.

**Comment by ryao** [comment]
> If there is patch we would be willing to test it.

I had hoped that the group that last touched this infrastructure would write the patch, but they have not. I guess I will need to do it, although I cannot do it immediately.

**Comment by JKDingwall** [comment]
This is a bit of a sticking point for us at the moment and we've not managed to come up with a workaround.  Is it a simple issue that someone unfamiliar with the zfs code base could resolve with a bit of guidance?

**Comment by ryao** [comment]
@JKDingwall I had asked the last people to touch this if they would fix it and I thought they would, but they have not. I will need to write my own fix for this, although finding time in the next few weeks will be difficult.

**Comment by ryao** [comment]
Unfortunately, it has been somewhat difficult finding time to do this. I plan to do it, although if you would like it done faster, I suggest contacting Klara Systems to get it done.

**Comment by SpiffyB** [comment]
Has there been any progress on this? This is a serious blocker for a project I'm working on currently.

**Comment by JKDingwall** [comment]
I can still reproduce this problem in zfs-2.2.6.  I've added a couple of printks and for the snapshot rename I can see that `zvol_rename_minors_impl()` is entered but there is no subsequent call to `zvol_os_rename_minor()`.  I'll continue trying to follow what is happening...

**Comment by JKDingwall** [comment]
The printk I added to `zvol_rename_minor_impl()`:

```
        printk(KERN_ERR "ZFS: zvol_rename_minors_impl(%s->%s)...\n", oldname, newname);
```

If I rename a zvol with snapshots, e.g. `zfs rename pool/james pool/dingwall`:

```
ZFS: zvol_rename_minors_impl(diskconvm/james->diskconvm/dingwall)
```

If I rename a snapshot , e.g. `zfs rename pool/dingwall@apple pool/dingwall@orange`

```
ZFS: zvol_rename_minors_impl(apple->orange)...
```

So I suspect the problem is that `zvol_rename_minors_impl()` is not called with the full zfs path.

**Comment by JKDingwall** [comment]
a0bd735adb1b1eb81fef10b4db102ee051c4d4ff removed code which prefixed `fsname` to the snapshot name before calling `zvol_rename_minors()`.  That goes back to 0.7.0 (!) but as long time zfs users I can't remember when we first observed this problem.  I'll see if I can reinstate the code which was removed.

```
-#ifdef _KERNEL
-       oldname = kmem_asprintf("%s@%s", fsname, oldsnapname);
-       newname = kmem_asprintf("%s@%s", fsname, newsnapname);
-       zvol_rename_minors(oldname, newname);
-       strfree(newname);
-       strfree(oldname);
-#endif
```
