### ISSUE TITLE
mmap_read_001_pos fails because mmap_write_001_pos fills up the test device (chmod: changing permissions of ...: No space left on device)

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#14277]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| bookworm
Kernel Version	| 6.0.0-6-amd64
Architecture	| amd64
OpenZFS Version	| 2.1.7

### Describe the problem you're observing
While running the `zfs-tests/tests/functional/mmap`  test, `mmap_write_001_pos.ksh` performs writes for 30 seconds.  This is (apparently) long enough to fill up the device so bad that `chmod 777` fails with "no space left on device".

I was able to get the test to succeed by changing the writing wait to 10 seconds.

### Describe how to reproduce the problem
Run the test suite with a fast ssd and a recent kernel.

Apparently there were some performance gains in openzfs/Linux, because this only started becoming an issue recently! :confetti_ball:

### Include any warning/errors/backtraces from the system logs

````
Test: /usr/share/zfs/zfs-tests/tests/functional/mmap/mmap_read_001_pos (run as root) [00:00] [FAIL]
09:31:51.75 ASSERTION: read()s from mmap()'ed file contain correct data.
09:31:51.76 chmod: changing permissions of '/tmp/tmp.lLp9pQs2BS/testdir': No space left on device
09:31:51.76 ERROR: chmod 777 /tmp/tmp.lLp9pQs2BS/testdir exited 1
```

**Comment by ryao** [comment]
> Apparently there were some performance gains in openzfs/Linux, because this only started becoming an issue recently!

The only things that improve performance in 2.1.7 that come to mind would be 1d2b0563f731cf74d8e6cdecad559eb5fa1a3cd7 and d9de079a4b9cde7b1a958512ce8948a57324c518.

That said, this issue is not being detected by the buildbot:

http://build.zfsonlinux.org/known-issues.html

I assume that you are running it on your own hardware.

**Comment by aerusso** [comment]
Sorry: yes, I am indeed only seeing on my own hardware.  This also after a jump from 2.1.5 to 2.1.7 for reasons that aren't important.  I think it's valuable for people to be able to run the tests on their own hardware to gain confidence in their setup.

Would it make sense to have that test write up to a certain amount of data, or is the duration of 30 seconds somehow probing certain pathways of interest?  I'm very suspicious of altering tests, especially old ones I do not fully understand.

**Comment by ryao** [comment]
> Sorry: yes, I am indeed only seeing on my own hardware. This also after a jump from 2.1.5 to 2.1.7 for reasons that aren't important. I think it's valuable for people to be able to run the tests on their own hardware to gain confidence in their setup.

It is not a problem. It is just that usually, reports of ZTS issues are from the buildbot, so I was a little surprised.

> Would it make sense to have that test write up to a certain amount of data, or is the duration of 30 seconds somehow probing certain pathways of interest? I'm very suspicious of altering tests, especially old ones I do not fully understand.

I cannot answer this off the top of my head. I will probably not have time to look into this more deeply for at least a week. If you write a patch to do this and submit it in a PR, you will likely get much more rapid feedback on the idea from other contributors doing code review.

**Comment by behlendorf** [comment]
There's nothing special about the 30 seconds.  It's simply long enough that we're likely to hit the deadlock if it's accidentally reintroduced.  Either dropping the time to 10 seconds or limiting the file size would be fine.
