### ISSUE TITLE
Code of Contribution link broken, typo in contrib/initramfs/scripts/zfs

### ISSUE THREAD

**Issue by introt** [openzfs/zfs#14298]
I don't do sign-offs (sorry), so I can't open a PR for this. Here are commits containing the fixes: https://github.com/introt/zfs/tree/thattheany

And here's as much of the form as I could fill out:

### Motivation and Context

1. The link to OpenZFS's Code of Conduct is broken
2. There is a typo in `contrib/initramfs/scripts/zfs`

### Description

1. The broken link has been replaced with an up to date one
2. The `the` has been removed

### How Has This Been Tested?

1. The new link has been opened in a web browser
2. N/A

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

**Comment by behlendorf** [comment]
Thanks for reporting this, I've gone ahead and opened https://github.com/openzfs/zfs/pull/14307 with the fix.
