### ISSUE TITLE
open with O_TMPFILE flag fails on Linux 6.1

### ISSUE THREAD

**Issue by ThomasLamprecht** [openzfs/zfs#14301]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox VE (Debian derivative)
Distribution Version	| 7.x (11 Bullseye)
Kernel Version	| 6.1.0
Architecture	| x86_64
OpenZFS Version	| 2.1.7

### Describe the problem you're observing

Opening (for example) "/tmp" with O_TMPFILE flags on a system with the "/tmp" directory located on ZFS fails with `EOPNOTSUPP` while it works with ZFS 2.1.7 on e.g., the LTS 5.15.83 kernel or ZFS 2.1.6 on 5.19 kernel.

The executing user does not matters, tried root and an unpriv. user (the error would be different there too, so just mentioning for completeness sake) . File Owner/Access on `/tmp` is also OK (`Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)`)

It also works if I change the directory to one that isn't on ZFS (e.g., the tmpfs backed `/run`).

### Describe how to reproduce the problem

See the following example reproducer, tested on a systemd booted with 6.1.0 kernel and ZFS 2.1.7:

```C
#define _GNU_SOURCE

#include <stdio.h>
#include <fcntl.h>
#include <errno.h>

int main() {
    int fd = open("/tmp", O_TMPFILE | O_RDWR);

    if (fd < 0) {
        perror("opening '/tmp' for tmp-file failed");
        return -1;
    }
    return 0;
}
```

```bash
$ gcc zfs-open-tmpfile-fail.c -o zfs-open-tmp-fail
$ ./zfs-open-tmp-fail
opening '/tmp' for tmp-file failed: Operation not supported
```

Same example works fine if tested on e.g., 5.19. FWICT there was some rework in the vfs layer w.r.t. tmpfiles, e.g., adding a 
`vfs_tmpfile_open` symbol  (would ZFS need to wire that up?) and reworking a bit of code, but did not checked all to closely.

**Comment by behlendorf** [comment]
Thanks for reporting this, digging a little deeper it looks like torvalds/linux@863f144f12add1f4eab80b70561a90857c524a8b modified the `.tmpfile` interface again.  We'll need up update the configure checks to detect this new version and do the right thing.
