### ISSUE TITLE
Provide browsable RPM repos

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#14300]
### Describe the feature would like to see added to OpenZFS
Please provide browsable RPM repos.

### How will this feature improve OpenZFS?
Browsable repos will facilitate exploring RPM packages and selecting the right one for specific RH/CentOS point releases.

### Additional context
Currently, pointing the browser to a repo as `http://download.zfsonlinux.org/epel/7/kmod/` results in an `AccessDenied` error.

**Comment by gmelikov** [comment]
Duplicate of https://github.com/openzfs/zfs/issues/11216

**Comment by shodanshok** [comment]
> Duplicate of #11216

Well, it seems my search skill is weak today... thank you for pointing me to the previous issue.
Closing.
