### ISSUE TITLE
DTL not working properly?

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#14388]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux 9.1
Distribution Version	| 9.1
Kernel Version	| 5.14.0-162.6.1.el9_1.0.1.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.7

### Describe the problem you're observing
Detaching and immediately reattaching a mirror vdev causes >100GB to be resynced. This is an HDD pool, so no chances so much data were written in 5s at most, still `zpool status` reports the following:

```
  pool: tank
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Thu Jan 12 21:40:41 2023
        1.62T scanned at 470M/s, 1.60T issued at 465M/s, 1.62T total
        130G resilvered, 99.10% done, 00:00:32 to go
config:

        NAME                                STATE     READ WRITE CKSUM
        tank                                ONLINE       0     0     0
          mirror-0                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-1.0        ONLINE       0     0     0
            pci-0000:01:00.1-ata-2.0        ONLINE       0     0     0
          mirror-1                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-6          ONLINE       0     0     0
            pci-0000:01:00.1-ata-5.0        ONLINE       0     0     0  (resilvering)
        logs
          mirror-5                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-4.0-part4  ONLINE       0     0     0
            pci-0000:01:00.1-ata-3.0-part4  ONLINE       0     0     0
        cache
          pci-0000:01:00.1-ata-3.0-part5    ONLINE       0     0     0
          pci-0000:01:00.1-ata-4.0-part5    ONLINE       0     0     0
```

Notice how it resilvered 130 GB, still running.

It was my understanding that, thanks to DTL, only data modified during the detached state need to be resilvered. Am I wrong?

EDIT: it is even *worse*. After finished, resilvered restarted again, this time from ~50%:
```
  pool: tank
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Thu Jan 12 22:47:57 2023
        1.62T scanned at 2.53G/s, 840G issued at 1.28G/s, 1.62T total
        12.8G resilvered, 50.71% done, 00:10:35 to go
config:

        NAME                                STATE     READ WRITE CKSUM
        tank                                ONLINE       0     0     0
          mirror-0                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-1.0        ONLINE       0     0     0
            pci-0000:01:00.1-ata-2.0        ONLINE       0     0     0
          mirror-1                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-6          ONLINE       0     0     0
            pci-0000:01:00.1-ata-5.0        ONLINE       0     0     0  (resilvering)
        logs
          mirror-5                          ONLINE       0     0     0
            pci-0000:01:00.1-ata-4.0-part4  ONLINE       0     0     0
            pci-0000:01:00.1-ata-3.0-part4  ONLINE       0     0     0
        cache
          pci-0000:01:00.1-ata-3.0-part5    ONLINE       0     0     0
          pci-0000:01:00.1-ata-4.0-part5    ONLINE       0     0     0
```

### Describe how to reproduce the problem
Executing `zpool detach tank <dev>; sleep 5;  zpool attach tank <dev>` on a lightly-loaded pool results in much data being resilvered.

**Comment by gertvdijk** [comment]
I believe re-attaching a device in a mirror causes it to be fully initialized as if it's a fresh/new drive.

Perhaps you meant to _offline_ the device? If I need to move a drive physically and I want to take it offline temporarily I use `zpool offline -f pool device`, followed by a `zpool online pool device` which then resilvers very quickly.

**Comment by shodanshok** [comment]
I thought about that but, if so, why the first resilver started at ~90% syncing "only" 150 GB? And as it finished, why to restart with a *new* resilver at the 50% mark?

**Comment by shodanshok** [comment]
Uhm, ok, `detach` seems to [really clear the disk label](https://github.com/openzfs/zfs/blob/018f26041d67447de28c293c35e1f664ce3c1abb/module/zfs/spa.c#L7165). So it will inevitably resilver the entire disk upon attaching. Still, I don't know why two resilvers were done.

Anyway, I am closing this issue. Thanks @gertvdijk for your help.
