### ISSUE TITLE
How about rewrite `zpool iostat/status` with `libncurse` just like `htop`

### ISSUE THREAD

**Issue by LittleNewton** [openzfs/zfs#14419]
### Describe the feature would like to see added to OpenZFS

Nowdays, the zfs utilities like `zpool iostat` and `zpool status` with x seconds parameter will print a lot of words in the terminal. For a normal tmux session, the large amount of outputs will make it hard/slow when loading from a remote ssh session because syncing 9999999 lines of outputs is a challenge to the network. However, if this command's output can be implemented with `libncurse` just like `htop`, this could be better for tmux reloading.

I don't know how to describe this feature in normal words. But if you have used `htop` command on linux, you could understand my request easily.

### How will this feature improve OpenZFS?

It will make zfs monitoring more friendly to use.

### Additional context

![image](https://user-images.githubusercontent.com/17793356/214048617-524b8946-d7d4-440d-8207-886d8d03aca4.png)

**Comment by LittleNewton** [comment]
@malventano Thank you very much. Command with `watch` solved my problem almost perfectly.

For someone with the same difficult, you can use command like `watch -t -n 0.1 'zpool iostat -yv 1 1'` to show the monitor info and the fresh frequency is almost as good as the native zpool-iostat output.

**Comment by malventano** [comment]
`watch -t -n 0.1 'zpool iostat -yv 0.9 1` :)
