### ISSUE TITLE
zed(8) manual page is missing in the web page

### ISSUE THREAD

**Issue by OleHolmNielsen** [openzfs/zfs#14435]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	|

### Describe the problem you're observing
The zed(8) manual page is missing in the web page https://openzfs.github.io/openzfs-docs/man/8/index.html.
The man-page is actually present in the Linux RPM package.

### Describe how to reproduce the problem
View the web page https://openzfs.github.io/openzfs-docs/man/8/index.html.

**Comment by gmelikov** [comment]
Thank you, fixed in https://github.com/openzfs/openzfs-docs/commit/e08d869fedec6615f2b078336d02df1d30c8e1cb

**Comment by OleHolmNielsen** [comment]
Thanks a lot for the quick fix! Now I can see the manual page https://openzfs.github.io/openzfs-docs/man/8/zed.8.html
