### ISSUE TITLE
zfs [2.1.8] status [0...9] hangs   zfs status [a-z] not

### ISSUE THREAD

**Issue by fgordonZ** [openzfs/zfs#14438]
Hello all 

Just compiled 2.1.8 works great like always big thanks   (running FreeBSD 13.1)

One thing I noticed a while ago and is still the case is

zfs status 12345  => hangs "forever?"
zfs status  abcdef => does not and returns

12345  and  abcdef   are NOT existing zpools.   :)

Maybe this affects other things too?

**Comment by freqlabs** [comment]
When you give a number it is interpreted as a loop interval. So for instance `zpool status 5` will print the status of all pools every 5 seconds.

**Comment by fgordonZ** [comment]
Oh ok xD thanks   yes thats true - sorry xD
