### ISSUE TITLE
zloop fails with zdb: leaked MOS object (persistent error log)

### ISSUE THREAD

**Issue by ahrens** [openzfs/zfs#14434]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	| 9cd71c8604d52def22ffaddc35755712f0fb9349

### Describe the problem you're observing
When running zloop, sometimes zdb fails due to detecting leaked objects:
```
MOS object 733 (persistent error log) leaked
MOS object 734 (persistent error log) leaked
```
It's possible that this is a bug in zdb: it might need to be taught about the new DMU_OT_ERROR_LOG objects that were introduced by #12812 (cc @gamanakis).  e.g. in dump_mos_leaks(), we simply call `mos_obj_refd(spa->spa_errlog_last)`, but now the spa_errlog_last contains a mapping from objset id to another DMU_OT_ERROR_LOG object, which also needs to be marked as in-use.

### Describe how to reproduce the problem
zloop.sh

**Comment by gamanakis** [comment]
Thanks for reporting this. I have an idea how to fix it. Will take a look.
