### ISSUE TITLE
CKSUM data error on mirror'ed vdev after failure of its pair

### ISSUE THREAD

**Issue by ghost** [openzfs/zfs#14465]
Hello, and thank you for your time reading this.

I have a simple setup of one pool over four drives, setup as two mirrors of two vdevs. I am using Ubuntu 22.04 LTS, running on 5.15.0-58-generic. One of the four drives failed just after beeing attached upon the latest boot with `blk_update_request: critical target error, dev sdd, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0`. I later discovered that it was improperly connected.

This, however, should have been no matter at all if I understand mirrors correctly: data should've been read and written on `sdd` mirror partner until either the drive re-appeared or a new drive was installed as a replacement. Apparently though, data corruption occured on the second drive because the output of `zpool status` is now: 

```
root@donnet-serv:~# zpool status -v
  pool: qnapool
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 05:17:38 with 1014870 errors on Sat Feb  4 23:21:52 2023
config:

	NAME                                             STATE     READ WRITE CKSUM
	qnapool                                          DEGRADED     0     0     0
	  mirror-0                                       ONLINE       0     0     0
	    scsi-1ST8000DMST8000DM004-2CX188_ZCT40F6M    ONLINE       0     0     0
	    scsi-1WDC_WD80WDC_WD80EFBX-68AZZN0_VRHUS75K  ONLINE       0     0     0
	  mirror-1                                       DEGRADED     0     0     0
	    1811765304917987891                          UNAVAIL      0     0     0  was /dev/disk/by-id/scsi-1ST8000VNST8000VN004-2M2101_WSD3KQBS-part1
	    scsi-1TOSHIBA_TOSHIBA_HDWG480_71Q0A03KFR0H   DEGRADED     0     0 2.18M  too many errors

errors: Permanent errors have been detected in the following files:

        qnapool/storezone:<0x0>
        qnapool/<filenames>...
```

I have read the wiki page linked to the ZFS-8000-8A message and understand that I have lost the local data and must restore from backups. My question is the following: what could have happened, how can I found it out, and how can I avoid it in the future ? This is my first "problem" with ZFS (I have had some drives die in mirrors and replaced them before but that is all). I don't understand why losing a disk would create errors on the other drive...

Thank you for your time!

**Comment by rincebrain** [comment]
What I was kind of hoping for was either `ereport.fs.zfs.authentication` or checksum, the latter of which would tell us which checksum bits it got upset about. (The error code it has, 0x34, is EBADE on x86, which is used for checksum error.)

**Comment by rincebrain** [comment]
So, that resilver was updating the failed disk with things that happened since it vanished, not trying to rewrite anything erroring on the other leg of the mirror.

And yes, zpool status's estimates of resilver times are just bad.

I'd probably just suggest trying to run 2.1.9 and seeing if it misbehaves less, as a number of problems have been fixed in the interim, though I don't immediately recognize that backtrace. I guess #12775 has some backtraces which might be similar, though with how many backtraces are in there, that's not a very specific statement...

I didn't actually ask, I guess, but is ZFS native encryption in use here?
