### ISSUE TITLE
Considering to update ZSTD to 1.5.5

### ISSUE THREAD

**Issue by ptr1337** [openzfs/zfs#14489]
### Describe the feature would like to see added to OpenZFS

The linux kernel has recently updated zstd to the 1.5.2 release.
Some days ago the 1.5.4 got released with performance enhancement compared to 1.5.2.

### How will this feature improve OpenZFS?

Faster compression

### Additional context

Release Changelog:
https://github.com/facebook/zstd/releases/tag/v1.5.4

**Comment by zrav** [comment]
Superseded by 1.5.5: https://github.com/facebook/zstd/releases/tag/v1.5.5

**Comment by gdevenyi** [comment]
1.5.5 also have a corruption fix, not sure this impacts ZFS
https://news.ycombinator.com/item?id=35446847

**Comment by aluo-x** [comment]
The corruption fix was for a bug introduced in zstd 1.5.0 (see zstd bug 3517), it seems that zfs uses zstd 1.4.5 with upstream patches ported by @ryao 

It seems like zstd versioning was discussed in #12840 but nothing ever came of it.

**Comment by behlendorf** [comment]
As summarized in this https://github.com/openzfs/zfs/issues/12840#issuecomment-1059759178 updating the zstd version is more involved than one might guess.  It's not something we're planning on doing until we have a very compelling reason.  We'll of course continue to backport any critical upstream fixes to the zstd 1.4.5 version we're using.

**Comment by KaliszAd** [comment]
Seems like version 1.5.7 improves performance for small blocks considerably. (https://github.com/facebook/zstd/releases/tag/v1.5.7)
