### ISSUE TITLE
Performance degradation in NVMe L2ARC configured ZFS upgrading from 2.1.4 to 2.1.6

### ISSUE THREAD

**Issue by voraharshit** [openzfs/zfs#14494]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Amazon Linux 2
Distribution Version	| Amazon Linux 2 AMI 2.0.20230119.1 x86_64
Kernel Version	| 5.10.165-143.735.amzn2.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.6

### Describe the problem you're observing
Upgrading from ZFS 2.1.4 to ZFS 2.1.6, I'm seeing increased read latency and reduced bandwidth, IOPS.

I bisected it to the following commit: [39e038cdc61a9af2549fa3ed1f42c16dbcbe4ca6](https://github.com/openzfs/zfs/pull/12285/commits/39e038cdc61a9af2549fa3ed1f42c16dbcbe4ca6)
I have the l2arc_exclude_special tunable set to 0 as is the default. Reverting this commit seems to fix the issue. The issue is only affecting performance for a NVMe L2ARC configured ZFS. ZFS without L2ARC is unaffected.

**Comment by allanjude** [comment]
Do you have a special vdev in your pool?

**Comment by voraharshit** [comment]
No, I do not have a special vdev.

**Comment by voraharshit** [comment]
Please let me know if I can provide any additional details or if there was any advice on how I should investigate this further

**Comment by KungFuJesus** [comment]
This isn't surprising at all looking at the diff.  The test for "is cacheable" is considerably more expensive.

**Comment by behlendorf** [comment]
@voraharshit thanks for reporting this.  If possible could you provide some detail on how significantly this impacted read latency and IOPs.  @gamanakis could you look in how we can best  optimize this.

**Comment by gamanakis** [comment]
I should be able to come up with a PR.

**Comment by gamanakis** [comment]
@voraharshit would you be able to apply #14563 and see if it helps?

**Comment by voraharshit** [comment]
Thank you @behlendorf, @gamanakis  for looking into this! I'll try the PR and get back with some performance details.

**Comment by voraharshit** [comment]
[#14563](https://github.com/openzfs/zfs/pull/14563) is working perfectly, and I'm seeing performance numbers similar to before commit [39e038cdc61a9af2549fa3ed1f42c16dbcbe4ca6](https://github.com/openzfs/zfs/pull/12285/commits/39e038cdc61a9af2549fa3ed1f42c16dbcbe4ca6)

**Comment by gamanakis** [comment]
Thank you @voraharshit!
