### ISSUE TITLE
autoreplace does not work with /dev/disk/by-id/ devices in a pool

### ISSUE THREAD

**Issue by alexxbull** [openzfs/zfs#14559]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11
Kernel Version	| 5.10
Architecture	| x86_64
OpenZFS Version	| 2.1.7

### Describe the problem you're observing
I have a zpool with raidz1 vdevs containing devices assigned by their `/dev/disk/by-id/wwn-` path. The pool has `autoreplace` set to `on` and `ZED` is running. Trying to auto replace a device by removing it and inserting a blank disk fails although the disk does get appropriately labeled and partitioned. Auto replacing is successful (sometimes) however when using devices assigned  by their devname path `/dev/sdx` but this is not guaranteed as the devname may change on the replaced drive. Additionally, I have an array of disks shared between multiple computers so I need to use `/dev/disk/by-id/` paths to identify each unique drive.

### Describe how to reproduce the problem

1. Create a pool with a raidz1 vdev containing devices assigned by their `/dev/disk/by-id/wwn-` path. 
2. Enable and run `ZED` and set the `autoreplace` and `multihost` properties on the pool to `on`. (I had to set `multihost=on` for a removed device to be detected and labeled `UNAVAIL` in `zpool status`). 
3. Remove one of the devices from the pool and wait until zfs detects it is unavailable via `zpool status`. 
4. Insert a blank (non-partitioned) drive to replace the removed device. 
5. The replacement will not succeed and `zpool status` will continue to show the device as `UNAVAIL`.
6. (optional) Verify the disk was appropriately labeled and partitioned via `lsblk`. 

### Include any warning/errors/backtraces from the system logs

ZED logs a lot of output so I snipped what I think is the primary cause of this issue:
`zfs_mod: expected replacement disk /dev/disk/by-id/wwn-<old_drive_wwn>-part1 is missing`

This error message is produced by [L493](https://github.com/openzfs/zfs/blob/zfs-2.1.7/cmd/zed/agents/zfs_mod.c#L493) in `zfs/cmd/zed/agents/zfs_mod.c` after inserting a blank drive to replace the removed device. My interpretation is this is caused because `udev` cannot find the dev id path `/dev/disk/by-id/wwn-<old_drive_wwn>-part1`. This makes sense since that drive was removed but zfs is still checking for the old dev id path.

**Comment by Low-power** [comment]
Consider using names under `disk/by-path/` instead; they may provide predictable names based on physical localtion, under some configurations.

**Comment by alexxbull** [comment]
> Consider using names under `disk/by-path/` instead; they may provide predictable names based on physical localtion, under some configurations.

While `autoreplace` does work when using `disk/by-path`, my setup would not work cleanly with `disk/by-path`. I have an array of disks shared between multiple computers and the `disk/by-path` is different on each computer for the same disk. It's because of this that I'm using the `disk/by-id` to identify each drive.

**Comment by behlendorf** [comment]
When using `autoreplace` it's recommended that the `/dev/disk/by-vdev/` paths be used.  By setting up an `/etc/zfs/vdev_id.conf` file you can request udev create devices which use the same admin-friendly names across all the hosts.  It also allows you to easily include things like the physical slot number in the device name.

https://openzfs.github.io/openzfs-docs/man/5/vdev_id.conf.5.html

The other thing to know about the `autoreplace` code is it's designed to only kick in when the replacement drive appears in the same location as the original device.  In practice, this means the old and new devices need to use the same name which is why `by-id` doesn't work and `by-path` does.

**Comment by alexxbull** [comment]
Thanks, I was able to get `autoreplace` to work with the `/dev/disk/by-vdev` paths after configuring a `/etc/zfs/vdev_id.conf` file. I did assume the old and new devices needed the same name based on the log error I was getting showing the old wwn id but I wasn't sure if that was intended. Anyways, I'll close this issue and use `vdev_id` as a workaround.
