### ISSUE TITLE
ztest: MOS leaks

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#14585]
Some of the zloop runs on recent commits merged to master show MOS leaks.

```
MOS object 179 (persistent error log) leaked
```

https://github.com/openzfs/zfs/actions/runs/4308081564

```
MOS object 468 (persistent error log) leaked
MOS object 469 (persistent error log) leaked
MOS object 470 (persistent error log) leaked
MOS object 471 (persistent error log) leaked
MOS object 472 (persistent error log) leaked
MOS object 473 (persistent error log) leaked
MOS object 474 (persistent error log) leaked
MOS object 475 (persistent error log) leaked
```

https://github.com/openzfs/zfs/actions/runs/4287500668

**Comment by behlendorf** [comment]
Was this issue not resolved by #14442 (commit ac2038a19c3b7e9ba913a850e05ba773725bd25d)?

**Comment by ryao** [comment]
Unfortunately, no. That commit was merged a month ago and these test failures happened last week.

**Comment by ryao** [comment]
@gamanakis It looks like the patch you wrote to address this did not fix the issue.

**Comment by ryao** [comment]
@ahrens Since you filed #14434, I am pinging you too, since the issue seems to still be unresolved.

**Comment by gamanakis** [comment]
@ryao could you give #14592 a try?

**Comment by ryao** [comment]
> @ryao could you give #14592 a try?

This was detected by the github workflow on commits merged to master. I spotted it when looking at the reports. I do not currently have the ability to reproduce it myself.
