### ISSUE TITLE
zfs-2.1.9 & Linux 6.2.7 & llvmclang 17.0.0 fails to build with objtool: unsupported pointer realignment & modified stack frames

### ISSUE THREAD

**Issue by oven8Mitts** [openzfs/zfs#14660]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11 (build system)
Kernel Version	| 6.2.7 (from kernel.org not Debian)
Architecture	| x86_64
OpenZFS Version	| 2.1.9 release. 

### Describe the problem you're observing
Unable to build zfs with Clang LLVM17 when using the copy-builtin script, can be reproduced when selecting zfs to be built directly in tree only(not as a module). 

The same warnings appear when ZFS is built as a module in tree, although I receive GPL errors instead during linking stages. 

All warnings and errors go away when ZFS is answered "n" when doing kernel configuration.

### Describe how to reproduce the problem
Use the copy-built in script to add ZFS to your kernel sources and build zfs directly into the kernel, not as a module. Similar errors occur when building as an in-tree module. 
### Include any warning/errors/backtraces from the system logs

```
fs/zfs/icp/icp.o: warning: objtool: _aesni_ctr32_ghash_6x+0x57a: return with modified stack frame
fs/zfs/icp/icp.o: warning: objtool: _aesni_ctr32_ghash_no_movbe_6x+0x59a: return with modified stack frame
fs/zfs/icp/icp.o: warning: objtool: aesni_gcm_decrypt+0x48: unsupported stack pointer realignment
fs/zfs/icp/icp.o: warning: objtool: aesni_gcm_encrypt+0x52: unsupported stack pointer realignment
fs/zfs/icp/icp.o: warning: objtool: SHA256TransformBlocks+0x20: unsupported stack pointer realignment
fs/zfs/icp/icp.o: warning: objtool: SHA512TransformBlocks+0x23: unsupported stack pointer realignment

ld.lld-17: error: <internal>:(.eh_frame) is being placed in '.eh_frame'
make[1]: *** [scripts/Makefile.vmlinux:35: vmlinux] Error 1
```

**Comment by theoparis** [comment]
I'm having the same issue but I specified:
```
CC=clang KERNEL_LLVM=1 LLVM=1 LD=ld.lld ./configure --enable-linux-builtin --with-linux=$PWD/../linux --prefix=/mnt/theos/usr --with-linux-obj=$PWD/../linux 
```

and then ran
```
make -j12 LLVM=1 YACC=byacc
``` on the kernel and it gave the same lld error 🤔
