### ISSUE TITLE
Can´t rename any file in a dataset

### ISSUE THREAD

**Issue by Gustavo-4523** [openzfs/zfs#14676]
Hey, i am starting my carrer in IT and i have came across some new things, and some of then are challenging.
I am actualy trying to implement an ZFS dataset in windows server 2019, i have successfully create a pool in raidz2, and it can storage files and is persistent and all, but i can't see to solve the issue with SMB share in new datasets.

![SMB](https://user-images.githubusercontent.com/128062562/227986003-6efb4d99-6d8a-4d39-bf64-ed1d598e6f01.png)

Plus, in a dataset, i can't create new files or move old ones there, or create workspaces

![new folder error](https://user-images.githubusercontent.com/128062562/227986132-c6f5b773-30ae-42d7-85df-eb64a4b92875.png)
![git hub](https://user-images.githubusercontent.com/128062562/227986157-07a8e1ac-70a6-4f1c-99f1-c1a4bfad2bef.png)

I know this problaly is a newbie issue and fairly easy to solve, but i dont came across any solution. If im asking this in the wrong section i'm sorry in advance

**Comment by rincebrain** [comment]
This seems like a question for [openzfsonwindows](https://github.com/openzfsonwindows/openzfs), at least until Windows support eventually (assumedly) gets upstreamed here?

**Comment by Gustavo-4523** [comment]
thanks, i will move to the right place.
