### ISSUE TITLE
Errors-only Scrub

### ISSUE THREAD

**Issue by Haravikk** [openzfs/zfs#14680]
### Describe the feature would like to see added to OpenZFS

I would like an option to have `zfs scrub` only scrub known errors so that they can be verified as corrected.

Basically instead of attempting to scrub all records, this mode would use the list of known errors on a pool to instead only scrub the affected records, and clear the errors if they are no longer incorrect (or no longer in use).

I would propose `-e` as the option to enable this "errors-only" scrub.

### How will this feature improve OpenZFS?

It will allow for much faster scrubs when the goal is to verify that errors have been corrected.

I realise this is a somewhat niche case, but I've encountered errors in the past that were only temporary (likely network issues or a dodgy controller) rather than on-disk corruption, and scrubbing will clear them but it takes a very long time. Naturally a full scrub is recommended regardless, but that could always be done with `zpool scrub -ew tank && zpool scrub tank` to clear the errors quickly then run the full scrub afterwards.

While I know that `zpool clear` can be used to "discard" the errors, I would prefer the confirmation that the errors were corrected, but without the long delay of a full scrub.

**Comment by rincebrain** [comment]
#12355

**Comment by Haravikk** [comment]
Not sure how I missed that (I did attempt a search, I swear)! I guess this issue is redundant if there's an existing feature in progress to do exactly this.
