### ISSUE TITLE
Repair Dataset(s) Using zfs send/receive

### ISSUE THREAD

**Issue by Haravikk** [openzfs/zfs#14688]
### Describe the feature would like to see added to OpenZFS

Apologies if this already exists, I feel like I've heard of something similar before but I couldn't find it anywhere.

Given a pool with corrupted data, I would like to be able to perform a selective `zfs send` from another pool that can be used to repair it. This means essentially three stages are required:

1. Generate a manifest of the corrupted records for the damaged pool
2. On another pool, locate the corresponding healthy records and generate a send stream.
3. On the damaged pool, receive the send stream and use it to replace the damaged records.

This would of course work most effectively when dealing with two pools where one is a backup of the other, i.e- snapshots of one are being sent to the other.

### How will this feature improve OpenZFS?

This should make it a lot faster to repair smaller amounts of corruption without having to discard and restore entire datasets; as only the (un)damaged records should need to be sent.

It will work best in cases where the records are reasonably expected to exist on both ends, i.e- both the source and target contain the same snapshots, and one or the other can be rolled back to discard any remaining (unrecoverable) corruption. Essentially it would allow a source to be repaired using a backup, or vice versa.

This would save a lot of time compared to discarding and restoring an entire dataset, and wouldn't represent as great a loss of redundancy (i.e- the dataset(s) existing in one fewer location until the restoration is complete).

**Comment by problame** [comment]
This features has been released now with OpenZFS 2.2. Time to close the issue?
