### ISSUE TITLE
Unknown symbol spl_signal_kobj_evt error on Debian Bullseye built zfs-2.1.10

### ISSUE THREAD

**Issue by turkerali** [openzfs/zfs#14752]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Debian GNU/Linux 11 (bullseye)
Distribution Version	| 11 (bullseye)
Kernel Version	|  Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.10

### Describe the problem you're observing
Today I downloaded and built the zfs-2.1.10 version on Debian Bullseye.
Build completed successfully. I removed the older kernel zfs module (2.1.9), and 
then installed the new zfs-dkms_2.1.10-1_amd64.deb package.

After installing new zfs module, modprobe failed with "Unknown symbol spl_signal_kobj_evt error"
Please note that reinstalling 2.1.9 version works fine, only 2.1.10 fails.

### Describe how to reproduce the problem
wget https://github.com/openzfs/zfs/releases/download/zfs-2.1.10/zfs-2.1.10.tar.gz
tar -xzvf zfs-2.1.10.tar.gz
cd zfs-2.1.10
sh autogen.sh
./configure
make -s -j$(nproc)
make deb-utils deb-dkms
(exported zfs pool, stopped zfs services)
rmmod zfs 
dpkg -i zfs-dkms_2.1.10-1_amd64.deb
(builds module fine)
modprobe zfs (fails to load new module, dmesg message is below)

### Include any warning/errors/backtraces from the system logs

```
[4974077.117060] ZFS: Unloaded module v2.1.9-1
[4974235.129099] zfs: Unknown symbol spl_signal_kobj_evt (err -2)
```

**Comment by robn** [comment]
I see you only removed the `zfs` module. There's a few modules that make up ZFS, and my guess is that some of the others are still loaded, and they don't connect up properly.

Try:

```
rmmod zfs icp zavl zlua zunicode zzstd zcommon znvpair spl
```

(ignore any `not currently loaded` errors).

and then

```
modprobe zfs
```

**Comment by turkerali** [comment]
Thanks for the quick response.  You're 100% right.
Your suggestion below resolved the issue:

```
rmmod zfs icp zavl zlua zunicode zzstd zcommon znvpair spl
```
