### ISSUE TITLE
FreeBSD: BLAKE3 pool corruption after ULE tuning

### ISSUE THREAD

**Issue by ekhramtsov** [openzfs/zfs#14785]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|FreeBSD
Distribution Version	|[04989ef426f9](https://cgit.freebsd.org/src/commit/?id=04989ef426f9)
Kernel Version	|[04989ef426f9](https://cgit.freebsd.org/src/commit/?id=04989ef426f9)
Architecture	|amd64
OpenZFS Version	|zfs-2.1.99-FreeBSD_g[431083f75](https://github.com/openzfs/zfs/commit/431083f75)

### Describe the problem you're observing
[[Re: BLAKE3 unstability?](https://www.mail-archive.com/search?l=freebsd-current@freebsd.org&q=subject:%22Re%5C%3A+BLAKE3+unstability%5C%3F%22&o=newest)]

### Describe how to reproduce the problem
```
#!/bin/sh
set -e
cleanup() {
	zpool destroy test
	mdconfig -d -u 0
	rm /tmp/test
	sysctl kern.sched.preempt_thresh=48
	sysctl kern.sched.steal_thresh=2
}
trap cleanup EXIT

sysctl kern.sched.steal_thresh=1
sysctl kern.sched.preempt_thresh=121
truncate -s 10G /tmp/test
mdconfig -f /tmp/test -S 4096
zpool create test /dev/md0
zfs create -o checksum=blake3 test/b
dd if=/dev/random of=/test/b/noise bs=1M count=4096
sync
zpool scrub test
sleep 3
zpool status
```
### Include any warning/errors/backtraces from the system logs

```
$ zpool status test
  pool: test
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 00:00:00 with 26 errors on Sun Apr 23 12:05:11 2023
config:

	NAME        STATE     READ WRITE CKSUM
	test        ONLINE       0     0     0
	 md0       ONLINE       0     0    52

errors: 26 data errors, use '-v' for a list
```

**Comment by rincebrain** [comment]
I would suspect, from reading the thread's thoughts on this, that the per-CPU ctx reuse cleverness is to blame here, as I think the ctx usage would have to essentially all be in a critical section or under a lock for this to be safe.

@mcmilk

**Comment by mjguzik** [comment]
Solid.

```
void
abd_checksum_blake3_native(abd_t *abd, uint64_t size, const void *ctx_template,
    zio_cksum_t *zcp)
{
        ASSERT(ctx_template != NULL);

#if defined(_KERNEL)
        BLAKE3_CTX *ctx = blake3_per_cpu_ctx[CPU_SEQID_UNSTABLE];
#else
        BLAKE3_CTX *ctx = kmem_alloc(sizeof (*ctx), KM_SLEEP);
#endif

        memcpy(ctx, ctx_template, sizeof (*ctx));
        (void) abd_iterate_func(abd, 0, size, blake3_incremental, ctx);
        Blake3_Final(ctx, (uint8_t *)zcp);

#if !defined(_KERNEL)
        memset(ctx, 0, sizeof (*ctx));
        kmem_free(ctx, sizeof (*ctx));
#endif
}
```

Assuming surprise migrations are the only problem here, this needs to do critical_enter() on FreeBSD and  kpreempt_disable on Linux. However, if this code is reachable from interrupt context as well, this wont be sufficient -- a dedicated set of bufs for that context would be needed. Additionally if any of this is doing anything which can put it off cpu, it is not going to work either.

That said, normally Linux distros ships with kernels which are not preemptible in arbitrary spots, so this probably does not break there at all.

The global array is pretty nasty, but that's for another time.

@ekhramtsov can you please test https://people.freebsd.org/~mjg/.junk/blake3_zfs.diff

**Comment by rincebrain** [comment]
I have one that adds a per-object lock, and falls back to just taking an allocation if it fails, and I haven't broken it yet.

I'm just trying to test it before suggesting it...

**Comment by mjguzik** [comment]
Locking is rather expensive.

```
(gdb) ptype /o BLAKE3_CTX
type = struct {
/*      0      |      32 */    uint32_t key[8];
/*     32      |     112 */    blake3_chunk_state_t chunk;
/*    144      |       1 */    uint8_t cv_stack_len;
/*    145      |    1760 */    uint8_t cv_stack[1760];
/* XXX  7-byte hole      */
/*   1912      |       8 */    const void *ops;

                               /* total size (bytes): 1920 */
                             }

```

Both Linux and FreeBSD support 2KB slabs, so this can be allocated without much hassle if needed.

**Comment by rincebrain** [comment]
Which is more expensive, locking, or turning off pre-emption and interrupts entirely?

ISTR the reason for the pre-allocation in the first place was that it was, in fact, not sufficiently cheap on Linux, possibly related to Linux's default of zeroing memory on allocation and/or free in most distros if you actually use the allocator.

**Comment by ryao** [comment]
At a minimum, we should be wrapping the lifetime of `ctx = blake3_per_cpu_ctx[CPU_SEQID_UNSTABLE];` by `kpreempt_disable()`/`kpreempt_enable()`.

**Comment by ekhramtsov** [comment]
> @ekhramtsov can you please test https://people.freebsd.org/~mjg/.junk/blake3_zfs.diff

I confirm, base [176939bd361a](https://cgit.freebsd.org/src/commit/?id=176939bd361a) GENERIC + blake3_zfs.diff works fine here.

**Comment by rincebrain** [comment]
My point was that I think interrupts being on still breaks you sometimes, so at the point where you need the full disable, ...

I wasn't suggesting you not mitigate the problem now.

I have lost any interest in working on this, though, so don't wait on me.

**Comment by mcmilk** [comment]
> > @ekhramtsov can you please test https://people.freebsd.org/~mjg/.junk/blake3_zfs.diff
> 
> I confirm, base [176939bd361a](https://cgit.freebsd.org/src/commit/?id=176939bd361a) GENERIC + blake3_zfs.diff works fine here.

This should work fine, until some ctx is rescheduled to another CPU. So I have a bad feeling with it. But when it works for now, we have more time to code a good solution via `abd_checksum_blake3_tmpl_init()/abd_checksum_blake3_tmpl_free()`

**Comment by mjguzik** [comment]
You are going to have to elaborate on this one. The entire premise of the patch is that it *prevents* other threads from using the buffer until it is done with it.

**Comment by mcmilk** [comment]
@mjguzik - see https://github.com/openzfs/zfs/issues/14785#issuecomment-1520917828

**Comment by ryao** [comment]
> My point was that I think interrupts being on still breaks you sometimes, so at the point where you need the full disable, ...
> 
> I wasn't suggesting you not mitigate the problem now.
> 
> I have lost any interest in working on this, though, so don't wait on me.

Keeping interrupts enabled only breaks things if we can access this memory from an interrupt context. I do not believe that we can. My preference is to disable interrupts in this code, but either way is fine.

**Comment by ryao** [comment]
> > > @ekhramtsov can you please test https://people.freebsd.org/~mjg/.junk/blake3_zfs.diff
> > 
> > 
> > I confirm, base [176939bd361a](https://cgit.freebsd.org/src/commit/?id=176939bd361a) GENERIC + blake3_zfs.diff works fine here.
> 
> This should work fine, until some ctx is rescheduled to another CPU. So I have a bad feeling with it. But when it works for now, we have more time to code a good solution via `abd_checksum_blake3_tmpl_init()/abd_checksum_blake3_tmpl_free()`

Disabling preemption prevents rescheduling to another CPU.

**Comment by ryao** [comment]
> @mjguzik - see [#14785 (comment)](https://github.com/openzfs/zfs/issues/14785#issuecomment-1520917828)

There is a different ctx used after rescheduling in that case, so it is okay.

**Comment by ryao** [comment]
> You are going to have to elaborate on this one. The entire premise of the patch is that it _prevents_ other threads from using the buffer until it is done with it.

Would you open a PR with this patch?
