### ISSUE TITLE
ZTS: zdb/zdb_encrypted

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#14791]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13.2
Kernel Version	|
Architecture	|
OpenZFS Version	|

### Describe the problem you're observing

The new `zdb/zdb_encrypted` test case is reliably failing on FreeBSD 13.2.

This test was integrated without a full CI run on FreeBSD so it's likely a minor flaw in the test which went unnoticed.

@robn would you mind taking a look at this.  It's currently the only test failing on FreeBSD so it's be extra nice to fix!

### Describe how to reproduce the problem

Reliably reproducible by the CI and should be easy to reproduce locally.

### Include any warning/errors/backtraces from the system logs

http://build.zfsonlinux.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29/builds/8417/steps/shell_4/logs/summary

```
Test: /usr/local/share/zfs/zfs-tests/tests/functional/cli_root/zdb/zdb_encrypted (run as root) [00:03] [FAIL]
17:49:20.50 NOTE: begin default_setup_noexit
17:49:20.60 SUCCESS: zpool create -f testpool md0
17:49:20.62 SUCCESS: zfs create testpool/testfs
17:49:20.65 SUCCESS: zfs set mountpoint=/mnt/testdir testpool/testfs
17:49:20.67 SUCCESS: zfs create testpool/testctr
17:49:20.69 SUCCESS: zfs set canmount=off testpool/testctr
17:49:20.72 SUCCESS: zfs create testpool/testctr/testfs1
17:49:20.75 SUCCESS: zfs set mountpoint=/mnt/testdir1 testpool/testctr/testfs1
17:49:20.78 SUCCESS: zfs create -V 150m testpool/testvol
17:49:20.78 SUCCESS: default_setup_noexit md0 md1 md2
17:49:20.78 ASSERTION: 'zdb -K' should enable reading from an encrypted dataset
17:49:21.10 SUCCESS: eval echo password | zfs create -o mountpoint=/mnt/testdir2 -o encryption=on -o keyformat=passphrase testpool/testfs2
17:49:21.10 NOTE: test file /mnt/testdir2/somefile is objid 2, size       24
17:49:21.13 SUCCESS: zpool sync -f testpool
17:49:22.53 SUCCESS: eval zdb -dddd testpool/testfs2 2 | grep -q 'object encrypted'
17:49:24.22 ERROR: eval zdb -K password -dddd testpool/testfs2 2 | grep -q 'size\s      24$' exited 1
17:49:24.22 NOTE: Performing test-fail callback (/usr/local/share/zfs/zfs-tests/callbacks/zfs_dmesg.ksh)
```

**Comment by robn** [comment]
Dang. I'll take a run at it next 24h. Thanks for letting me know!
