### ISSUE TITLE
cannot export 'rpool': pool is busy, debian/ubuntu

### ISSUE THREAD

**Issue by calvin2021y** [openzfs/zfs#14800]
### System information

debian 12 (ubuntu also has same problem)

```sh
zpool --version
zfs-2.1.9-3
zfs-kmod-2.1.9-3
```
amd64

### Describe the problem you're observing

during the install process,  after `mount | grep -v zfs | tac | awk '/\/mnt/{print $3}' | xargs -i{} umount -lf {}`

can not export rpool

### Describe how to reproduce the problem

follow the step from https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html

### Include any warning/errors/backtraces from the system logs

`strace zpool export -a`

https://gist.github.com/calvin2021y/86da83b58e0ff83274bf94ed4e73aecc#file-zfs_export_strace-txt

**Comment by calvin2021y** [comment]
I am use `dropbear-initramfs` without disk crypt,  after reboot I get login into initramfs.  I am not sure how to make the boot continue from ssh.

**Comment by calvin2021y** [comment]
after a few reboot, a nvme root dist also have this problem.  what is the root cause for this ?  any docs about fix this by a remote ssh connection ?

**Comment by kapitainsky** [comment]
So I have couple of machines running Debian 11 and I followed the same guide:

https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html

No issues.

You mentioned Debian 12 which is not released yet. Maybe you should check on Debian User Forums?
