### ISSUE TITLE
6.4 kernel support?

### ISSUE THREAD

**Issue by runboy93** [openzfs/zfs#14838]
I know there is no atm even 6.3 kernel support, but still it is always better to go on with newer releases, 6.4-rc1 just got released.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/?h=v6.4-rc1

**Comment by IvanVolosyuk** [comment]
I don't think it works this way. Changes in kernel are incremental in nature, so first we have to do #14622 I think and it may be a lot of work.

**Comment by rincebrain** [comment]
I should point out, that's 6.3 support, I haven't looked at whether 6.4 needs any more.
