### ISSUE TITLE
Mounting file system takes forever when there's a lot of file systems

### ISSUE THREAD

**Issue by FransUrbo** [openzfs/zfs#1484]
I'm trying to debug some sharesmb/shareiscsi command speed issues, and created 700 filesystems.

Booting this system 'takes forever', mostly because it needs to fork and wait for 'mount.zfs' to finish.

Looking at lib/libzfs/libzfs_mount.c:do_mount(), it references libmount, which seems to be availible in util-linux since version 2.18, which was released (according to the FTP site) 19-Jan-2012.

Current version is 2.23.1 - https://www.kernel.org/pub/linux/utils/util-linux/v2.23/libmount-docs/.

So 'we' really need to investigate this, and possibly add support for libmount...

**Comment by mailinglists35** [comment]
not sure if I have commented in the right place - does my comment on #845 belong here?
https://github.com/zfsonlinux/zfs/issues/845#issuecomment-164076284

**Comment by mailinglists35** [comment]
> no one (can/would) expects 1k+ filesystems to mount, *snap*, like that...

well, I do :) - why would it have to take forever?
