### ISSUE TITLE
Support RHEL 9.2

### ISSUE THREAD

**Issue by tonyhutter** [openzfs/zfs#14856]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| RHEL
Distribution Version	| 9.2
Kernel Version	| 5.14.0-162.23.1.el9_
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.11

### Describe the problem you're observing
RHEL & AlmaLinux 9.2 were released today.  We need to rebuild the kmod packages.

**Comment by gitcnd** [comment]
My workaround here is probably your answer: https://github.com/openzfs/zfs/issues/14857
TLDR;
```
remove kernel-devel
install the correct kernel-devel for your running kernel
rpmbuild -ba zfs-kmod.spec
```

**Comment by tonyhutter** [comment]
New kmods are out for EL9.2.  You'll see them as the 'zfs-2.1.11-2' packages.  DKMS were updated to 'zfs-2.1.11-2' as well to keep the same version number convention.
