### ISSUE TITLE
zfsprops(7) reference to the Snapshots section of zfsconcepts(7) links to the wrong page (self-referencing)

### ISSUE THREAD

**Issue by grahamperrin** [openzfs/zfs#14868]
### Describe the problem you're observing

Under <https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#snapdir>: 

> … as discussed in the [Snapshots](https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#Snapshots) section of [zfsconcepts(7)](https://openzfs.github.io/openzfs-docs/man/7/zfsconcepts.7.html). …

* the first of the two links refers to the wrong page (zfsprops(7) has no such section)
* the second is OK.

**Comment by gmelikov** [comment]
Duplicate of https://github.com/openzfs/openzfs-docs/issues/251

**Comment by grahamperrin** [comment]
Thanks, and my apologies for using the wrong repo.
