### ISSUE TITLE
Installing generated Debian DKMS package fails

### ISSUE THREAD

**Issue by dalbani** [openzfs/zfs#14887]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 12
Kernel Version	| 6.1.0-9
Architecture	| amd64
OpenZFS Version	| 2.1.99 (a.k.a. master)

Following the generation of Debian packages with `make native-deb-utils`, the installation of `openzfs-zfs-dkms_2.1.99-1_all.deb` fails:
```
make[3]: Leaving directory '/usr/src/linux-headers-6.1.0-9-amd64'
make[2]: Leaving directory '/var/lib/dkms/zfs/2.1.99/build/module'
Making all in include
make[2]: Entering directory '/var/lib/dkms/zfs/2.1.99/build/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/var/lib/dkms/zfs/2.1.99/build/include'
make[2]: Entering directory '/var/lib/dkms/zfs/2.1.99/build'
make[2]: *** No rule to make target 'copy-builtin', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/var/lib/dkms/zfs/2.1.99/build'
make[1]: *** [Makefile:984: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/2.1.99/build'
make: *** [Makefile:888: all] Error 2
```

My understanding is that the following files are missing from this `.deb` file:
```
copy-builtin CODE_OF_CONDUCT.md NEWS NOTICE RELEASES.md
```

Not being an expert in Debian packages, I suppose this is due to these files being referenced at: https://github.com/openzfs/zfs/blob/ad0a554614b096698d9969340c4c593690042d5b/Makefile.am#L40 but not being included in the list at: https://github.com/openzfs/zfs/blob/ad0a554614b096698d9969340c4c593690042d5b/contrib/debian/rules.in#L10

Yet I tried to add them to `DKMSFILES` but it apparently didn't work.
Manually adding those files in `data.tar.xz` inside `openzfs-zfs-dkms_2.1.99-1_all.deb` did fix the issue though.

In order to prevent this "silent" issue from happening again, what about _actually_ building the DMKS module in the CI workflow, instead of dropping it at: https://github.com/openzfs/zfs/blob/ad0a554614b096698d9969340c4c593690042d5b/.github/workflows/scripts/setup-dependencies.sh#L26

**Comment by dalbani** [comment]
If my understanding is correct, @usaleem-ix, you were the implementer of the Debian package in https://github.com/openzfs/zfs/pull/13451?
So I'm mentioning you here in case you're interested.

**Comment by rincebrain** [comment]
Pinging @mcmilk is probably more productive given who produced that CI setup.

**Comment by mcmilk** [comment]
@dalbani - you are correct, I have not created that debian stuff, but I re-used the changed workflow files within my `setup-dependencies.sh` script.

I thought the reason for bulding all and deleting it afterwars is for testing purpose... so I hadn't changed these lines.
For speeding up the build + testing process, we re-use the built modules of the first steps for the other workflows, this speeds up the setup-time for a well running test system to around [9 minutes](https://github.com/openzfs/zfs/actions/runs/5027889642/jobs/9018509579).

When you know - what needs to be changed, maybe you can create a pull request for it?

**Comment by dalbani** [comment]
I'd totally understand the reasoning of *not* installing `openzfs-zfs-dkms_2.1.99-1_all.deb` (thus not building the kernel module "again") in the CI workflow, in order to keep build time low.
My point about including it in CI was more that the issue could have been caught earlier on.
Anyway, the first step is to get `make native-deb-utils` generate a fully functional package.
Any suggestions on what to do with these `copy-builtin CODE_OF_CONDUCT.md NEWS NOTICE RELEASES.md`?

**Comment by dalbani** [comment]
> Any suggestions on what to do with these `copy-builtin CODE_OF_CONDUCT.md NEWS NOTICE RELEASES.md`?

I don't know what I did wrong in my first attempt, but it looks like the solution is only a matter of changing the content of the `DKMSFILES` variable.
It's all good now:
```
...
Loading new zfs-2.1.99 DKMS files...
It is likely that 5.15.49-linuxkit belongs to a chroot's host
Building for 6.1.0-9-amd64
Building initial module for 6.1.0-9-amd64
Done.

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.1.0-9-amd64/updates/dkms/

spl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.1.0-9-amd64/updates/dkms/
depmod...
```
