### ISSUE TITLE
ZFS fails to mount at boot. Systemd says "Executable path is not absolute"

### ISSUE THREAD

**Issue by angstymeat** [openzfs/zfs#14943]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.9
Kernel Version	| 3.10.0-1160.90.1.el7.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.99-1984_g8653f1d

### Describe the problem you're observing
File systems fail to mount at boot. When checking the status for `zfs-import-scan.service`, I get `Executable path is not absolute, ignoring: zpool import -aN -o cachefile=none $ZPOOL_IMPORT_OPTS`.

After editing the ZFS files under `/usr/lib/systemd/system/` to use absolute paths to zpool & zfs, the pool imports correctly at boot.

This happened after upgrade from `2.1.99-1710_g973934b`, which booted correctly.

This is also happening on another CentOS 7 system with kernel `5.4.244-1.el7.elrepo.x86_64`, and a Rocky Linux 9 system with kernel `5.14.0-284.11.1.el9_2.x86_6`.

### Describe how to reproduce the problem
Installed currently available ZFS from git repository, compiled, installed, and rebooted.

### Include any warning/errors/backtraces from the system logs
```
Jun 05 16:26:04 localhost systemd[1]: [/usr/lib/systemd/system/zfs-import-scan.service:17] Executable path is not absolute, ignoring: zpool import -aN -o cachefile=none $ZPOOL_IMPORT_OPTS
Jun 05 16:26:04 localhost systemd[1]: zfs-import-scan.service lacks both ExecStart= and ExecStop= setting. Refusing.
Jun 05 16:26:04 localhost systemd[1]: Cannot add dependency job for unit zfs-import-scan.service, ignoring: Unit is not loaded properly: Invalid argument.
```

**Comment by AllKind** [comment]
Most likely caused by this: 79b20949b25c8db4d379f6486b0835a6613b480c 
I guess your systemd version would be of interest.

**Comment by angstymeat** [comment]
The CentOS 7 systems are 219.78, and the RL9 is 252.13.

**Comment by angstymeat** [comment]
The assumption in 79b2094 is wrong. EL7 is using a supported kernel and is listed as one of the supported OS on the OpenZFS site (https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html), and it comes with 219.

Still, that doesn't explain the failure with RL9 using 252, if this is supposed to be a feature available in 239+.

RL8.8 is v239, but I haven't tried installing on any of my RL8 systems, yet.

**Comment by xnox** [comment]
> that doesn't explain the failure with RL9 using 252

do you have logs from RL9 system? Is it the same failure? or like are some of the binaries in the RPM shipped in paths that are not part of the default systemd path? If so, which one specifically?

**Comment by angstymeat** [comment]
@rincebrain I am sorry! I had multiple terminal windows opened and I thought I had rebooted my RL9 test VM, when it was a different one. I'm an idiot for wasting your time on RL9, it is working, and it's working in RL8.

I _am_ having the problem with CentOS 7, though.
