### ISSUE TITLE
spl-0.7.13 fails to build under kernel 4.18.0-372.9.1.el8.x86_64

### ISSUE THREAD

**Issue by arshad512** [openzfs/zfs#14976]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| centos
Distribution Version	| 8.5
Kernel Version	| 4.18.0-372.9.1.el8
Architecture	| x86_64
OpenZFS Version	| 0.7.13

### Describe the problem you're observing
Building spl-0.7.13 (zfs-0.7.13) under kernel 4.18.0-372.9.1 fails with **error: incompatible types when returning type ‘atomic_long_t’ {aka ‘struct <anonymous>’} but ‘kthread_t *’ {aka ‘struct task_struct *’} was expected   return (SEM(rwp)->owner);**. My understanding was that spl + zfs (0.13.7) supported kernels are 2.6.32 - 5.0-rc3 (https://github.com/openzfs/zfs/releases?page=5)

### Describe how to reproduce the problem
$ wget https://github.com/zfsonlinux/zfs/releases/download/zfs-0.7.13/spl-0.7.13.tar.gz
$ tar -xvzf spl-0.7.13.tar.gz
$ cd spl-0.7.13
$ sh autogen.sh 
$ ./configure --with-linux=/usr/src/kernels/4.18.0-372.9.1.el8.x86_64/
$ make 

### Include any warning/errors/backtraces from the system logs
```
...
Making all in module
make[2]: Entering directory '/root/allwork/spl-0.7.13/module'
make -C /usr/src/kernels/4.18.0-372.9.1.el8.x86_64 M=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/kernels/4.18.0-372.9.1.el8.x86_64'
  CC [M]  /root/allwork/spl-0.7.13/module/spl/spl-proc.o
In file included from /root/allwork/spl-0.7.13/include/sys/taskq.h:36,
                 from /root/allwork/spl-0.7.13/include/sys/kmem_cache.h:28,
                 from /root/allwork/spl-0.7.13/module/spl/spl-proc.c:30:
/root/allwork/spl-0.7.13/include/sys/rwlock.h: In function ‘rw_owner’:
/root/allwork/spl-0.7.13/include/sys/rwlock.h:84:18: error: incompatible types when returning type ‘atomic_long_t’ {aka ‘struct <anonymous>’} but ‘kthread_t *’ {aka ‘struct task_struct *’} was expected
  return (SEM(rwp)->owner);
         ~~~~~~~~~^~~~~~~~
make[5]: *** [scripts/Makefile.build:316: /root/allwork/spl-0.7.13/module/spl/spl-proc.o] Error 1
make[4]: *** [scripts/Makefile.build:556: /root/allwork/spl-0.7.13/module/spl] Error 2
make[3]: *** [Makefile:1577: _module_/root/allwork/spl-0.7.13/module] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.18.0-372.9.1.el8.x86_64'
make[2]: *** [Makefile:11: modules] Error 2
make[2]: Leaving directory '/root/allwork/spl-0.7.13/module'
make[1]: *** [Makefile:614: all-recursive] Error 1
make[1]: Leaving directory '/root/allwork/spl-0.7.13'
make: *** [Makefile:495: all] Error 2

```

**Comment by rincebrain** [comment]
Those numbers are not really germane to Red Hat's kernels, which backport all sorts of fun from the "future".

...also, why are you trying to use a version from 2019 in 2023?

**Comment by arshad512** [comment]
> Those numbers are not really germane to Red Hat's kernels, which backport all sorts of fun from the "future".
> 

This is stock kernel. 
```
# cat /etc/redhat-release 
Rocky Linux release 8.5 (Green Obsidian)
[root@rocky85zfsd zfs]# uname -r
4.18.0-372.9.1.el8.x86_64
```
> ...also, why are you trying to use a version from 2019 in 2023?
I wanted to quickly build version 0.7.13 (there are sites still supporting this version) and I was at 8.5 release rocky/centos. I had a quick look at the release notes and saw it is supported.  "Compatible with 2.6.32 - 5.0-rc3 Linux kernels". However, the 'make' failed, as reported above. My report only mentioned that the **build** fails againat a supported kernel (per release notes) which is essential to claim that it is supported.

**Comment by rincebrain** [comment]
ELx kernels, which CentOS/RHEL/Rocky/Alma/etc ship by default, are heavily modified from upstream kernel.org kernels at that version, and no force on earth applies a reasonable versioning system to them.

**Comment by arshad512** [comment]
It does not make sense then. If I am understanding correctly.

Take for example my other box which is centos stock kernel but 3.10. It does work here.  
```
# uname -r
3.10.0-1160.15.2.el7.x86_64
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

IMHO, if 4.18 is supported it should work. (By work I mean build, not concrened about features here) if the release notes says supported. It looks like this has slipped throught the cracks. Please note I do not intend to push a bug forcefully. Intention was to highlight that 0.7.13 fails to **build** against stock centos/rocky 8.5. In fact I should have opened it as a Q & A (hindsight I think).

**Comment by rincebrain** [comment]
Red Hat backports all kinds of things to their kernel trees. Sometimes they break external modules by adding or replacing interfaces. The fact that it works on an el7 kernel does not mean it should work on an el8 kernel, or even a newer or older el7 kernel.

Distro kernels can and do include whatever they want without changing the numbering, and the version numbers given in releases are best-effort for the vanilla kernel release versions at the time of release, which is why they don't get retroactively updated to say, for example, "6.4" if it turns out kernel 6.4.0 included no breaking changes but wasn't out at the time of the release.

It's absolutely unsurprising to me that a distro kernel for a version of RHEL that wasn't released yet when the ZoL version you were building released does not build. Most distros backport only relatively minor changes for the lifetime of their kernel tree...but that's not what RH does.

I would suggest using a contemporaneous vanilla kernel.org release if you need this precise version to build.

**Comment by tonyhutter** [comment]
> Intention was to highlight that 0.7.13 fails to build against stock centos/rocky 8.5. In fact I should have opened it as a Q & A (hindsight I think).

Got it - thanks for spelling this out.  We'll take it an advisory that 0.7.13 is no longer building on EL 8.5.

**Comment by arshad512** [comment]
> > Intention was to highlight that 0.7.13 fails to build against stock centos/rocky 8.5. In fact I should have opened it as a Q & A (hindsight I think).
> 
> Got it - thanks for spelling this out. We'll take it an advisory that 0.7.13 is no longer building on EL 8.5.

Thanks @tonyhutter

**Comment by arshad512** [comment]
0.7.13 is no longer builds on EL 8.5 (4.18.0-372.9.1.el8 kernel)

**Comment by ahesford** [comment]
The RH custom version suffix `-372.9.1` alone is enough to indicating a shocking number of modifications to the stock kernel!
