### ISSUE TITLE
build fails on linux 6.3/risc-v

### ISSUE THREAD

**Issue by q66** [openzfs/zfs#14974]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Chimera Linux
Distribution Version	| rolling
Kernel Version	| 6.3.7
Architecture	| riscv64
OpenZFS Version	| 2.1.12

### Describe the problem you're observing

The kernel module build fails:

```
  MODPOST /builddir/linux-stable-zfs-bin-2.1.12.6.3.7/zfs/2.1.12/build/module/Module.symvers
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'PageHuge'
```

I believe the issue is this: https://github.com/torvalds/linux/blob/master/arch/riscv/include/asm/cacheflush.h#L24

The relevant upstream commit should be this: https://github.com/torvalds/linux/commit/d33deda095d3637d218e7eed441633b2a01e1413

This was previously worked around for powerpc, in https://github.com/openzfs/zfs/commit/589f59b52af86455cf71421e63c34557c7ee6f91

### Describe how to reproduce the problem

Build the kernel module on riscv with kernel 6.3.

**Comment by sevan** [comment]
This applies to 6.2 as well. Just hit it via DKMS on Ubuntu/riscv64 23.04, which has switched from 5.19.0 to 6.2.0 kernel.

**Comment by palmer-dabbelt** [comment]
If there's something we can do on the `arch/riscv` side of things just LMK (or send a patch ;)).  Maybe we just need a `flush_dcache_page_nongpl(...)` for non-GPL modules?
