### ISSUE TITLE
panic: VERIFY3(zilog->zl_lwb_inflight[txg & TXG_MASK] > 0) failed (0 > 0)

### ISSUE THREAD

**Issue by phoatfreebsd** [openzfs/zfs#14988]
### System information

Type | FreeBSD 14.0-CURRENT #0 main-n263576-32b28e3ae28f4
 --- | ---
Distribution Name	| FreeBSD CURRENT
Distribution Version	| 32b28e3ae28f4
Kernel Version	| 32b28e3ae28f4
Architecture	| AMD64
OpenZFS Version	| ZFS filesystem version: 5

### Describe the problem you're observing
Panic during stress tests

### Describe how to reproduce the problem
cd /usr/src/tools/test/stress2/misc; ./all.sh zfs9.sh
### Include any warning/errors/backtraces from the system logs

Console log @ https://people.freebsd.org/~pho/stress/log/log0449.txt

**Comment by rincebrain** [comment]
For reference, freebsd/freebsd-src@32b28e3ae28f4d48520ada6ca703b508da8761a7 is synced to openzfs/zfs@feff9dfed.

Wondering if this is somehow fallout of #14841 @amotin or if it's a coincidence...

**Comment by amotin** [comment]
As I can see, https://github.com/openzfs/zfs/pull/14841 only increased already existing for quite a while race window.  I hope https://github.com/openzfs/zfs/pull/14999 fix it.
