### ISSUE TITLE
cannot mount 'dataset': Insufficient privileges

### ISSUE THREAD

**Issue by arch-user-france1** [openzfs/zfs#15038]
### System information

Type | zfs/2.1.12
 --- | ---
Distribution Name	| Fedora
Distribution Version	|  Fedora release 37 (Thirty Seven)
Kernel Version	| 6.3.8-100.fc37.x86_64
Architecture	| amd64
OpenZFS Version	| zfs-2.1.12-1

### Describe the problem you're observing
Usually, created datasets are mounted automatically. However, observed on Fedora, if a user is granted the following privileges to the dataset `create,dedup,destroy,mount,quota,secondarycache,snapshot`, it will not mount.
The command to mount ZFS datasets does not work, either:
```
> zfs mount 'dataset'
cannot mount 'dataset': Insufficient privileges
```

### Describe how to reproduce the problem
1. Create a user `adduser myzfsuser`
2. Create a new dataset and change the owner and group to the user's name with `chown`
3. Grant the user the required privileges `create` and `mount`
4. Create a new dataset by the user's behalf
5. Try to mount the dataset using `zfs mount` by the user's behalf
6. See error

### Include any warning/errors/backtraces from the system logs
```
cannot mount 'pool/datasetl1/datasetl2': Insufficient privileges
```

**Comment by rincebrain** [comment]
This is expected to not work at all on Linux, there are hardcoded limits in Linux outside the OpenZFS codebase around mount, which is why the man pages all say "delegating this won't work on Linux".

**Comment by arch-user-france1** [comment]
I will try to use limited root rights in that case.
