### ISSUE TITLE
cannot mount: filesystem already mounted && cannot unmount: no such pool or dataset

### ISSUE THREAD

**Issue by JosefRypacek** [openzfs/zfs#15075]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04.2 LTS
Kernel Version	| 5.19.0-46-generic
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.5-1ubuntu6~22.04.1 zfs-kmod-2.1.5-1ubuntu6

### Describe the problem you're observing
I have encrypted pool data with multiple datasets. I've found that one one of them has low USED / REFER and the parent one is increasing. It seems that all data went to the parent dataset. I think this dataset worked correctly in the past. I also tried to restart my computer several times.
I have no idea how to proceed / which useful information I should add here.

```
# zfs list
NAME                        USED  AVAIL     REFER  MOUNTPOINT
data                       11.7T  3.73T      318M  /data
data/ds-1                   205K  3.73T      205K  /data/ds-1
```

```
# zfs mount
data/ds-1             /data/ds-1
```

```
# mount
data/ds-1 on /data/ds-1 type zfs (rw,noatime,noxattr,noacl)
```

```
# zfs unmount data/ds-1
cannot unmount '/data/ds-1': no such pool or dataset
```

```
# zfs mount data/ds-1
cannot mount 'data/ds-1': filesystem already mounted
```

```
root@nas139:/data# zfs get all data/ds-1
NAME                PROPERTY               VALUE                  SOURCE
data/ds-1  type                   filesystem             -
data/ds-1  creation               Ne led  8 10:33 2023   -
data/ds-1  used                   205K                   -
data/ds-1  available              3.74T                  -
data/ds-1  referenced             205K                   -
data/ds-1  compressratio          1.00x                  -
data/ds-1  mounted                yes                    -
data/ds-1  quota                  none                   default
data/ds-1  reservation            none                   default
data/ds-1  recordsize             512K                   local
data/ds-1  mountpoint             /data/ds-1    default
data/ds-1  sharenfs               off                    default
data/ds-1  checksum               on                     default
data/ds-1  compression            lz4                    local
data/ds-1  atime                  off                    local
data/ds-1  devices                on                     default
data/ds-1  exec                   on                     default
data/ds-1  setuid                 on                     default
data/ds-1  readonly               off                    default
data/ds-1  zoned                  off                    default
data/ds-1  snapdir                hidden                 default
data/ds-1  aclmode                discard                default
data/ds-1  aclinherit             restricted             default
data/ds-1  createtxg              10964159               -
data/ds-1  canmount               on                     default
data/ds-1  xattr                  off                    local
data/ds-1  copies                 1                      default
data/ds-1  version                5                      -
data/ds-1  utf8only               off                    -
data/ds-1  normalization          none                   -
data/ds-1  casesensitivity        sensitive              -
data/ds-1  vscan                  off                    default
data/ds-1  nbmand                 off                    default
data/ds-1  sharesmb               off                    default
data/ds-1  refquota               none                   default
data/ds-1  refreservation         none                   default
data/ds-1  guid                   4682010827057620206    -
data/ds-1  primarycache           all                    default
data/ds-1  secondarycache         all                    default
data/ds-1  usedbysnapshots        0B                     -
data/ds-1  usedbydataset          205K                   -
data/ds-1  usedbychildren         0B                     -
data/ds-1  usedbyrefreservation   0B                     -
data/ds-1  logbias                latency                default
data/ds-1  objsetid               12681                  -
data/ds-1  dedup                  off                    default
data/ds-1  mlslabel               none                   default
data/ds-1  sync                   standard               default
data/ds-1  dnodesize              legacy                 default
data/ds-1  refcompressratio       1.00x                  -
data/ds-1  written                205K                   -
data/ds-1  logicalused            42K                    -
data/ds-1  logicalreferenced      42K                    -
data/ds-1  volmode                default                default
data/ds-1  filesystem_limit       none                   default
data/ds-1  snapshot_limit         none                   default
data/ds-1  filesystem_count       none                   default
data/ds-1  snapshot_count         none                   default
data/ds-1  snapdev                hidden                 default
data/ds-1  acltype                off                    default
data/ds-1  context                none                   default
data/ds-1  fscontext              none                   default
data/ds-1  defcontext             none                   default
data/ds-1  rootcontext            none                   default
data/ds-1  relatime               off                    default
data/ds-1  redundant_metadata     all                    default
data/ds-1  overlay                on                     default
data/ds-1  encryption             off                    default
data/ds-1  keylocation            none                   default
data/ds-1  keyformat              none                   default
data/ds-1  pbkdf2iters            0                      default
data/ds-1  special_small_blocks   0                      default
data/ds-1  com.sun:auto-snapshot  false                  local
```

**Comment by JosefRypacek** [comment]
Yes, this is the thing.

```
# df -h /data/ds-1
df: /data/ds-1: No such file or directory
```

I've disabled my script to load zfs keys and mount all datasets and found the issue. The `data/ds-1` is not encrypted (used as fast temporary cache) and so is automatically mounted before actual /data.

Is there any solution for this? I see this is probably non-standard configuration, but it should not lead to such a state.

**Comment by rincebrain** [comment]
If you were using the systemd mount generator, it should automatically mark children as dependent on the parent so this doesn't transpire.

If you're going to run your own bespoke unlock and mount tool, you'll have to handle that yourself.

**Comment by JosefRypacek** [comment]
Thanks. All unencrypted pools/datasets are mounted automatically (I have not to setup anything).
But for the encrypted one I'm using `zfs mount -la`. So I think the system should not mount data/ds-1.

I only have tracking files for `bpool` and `rpool` in `/etc/zfs/zfs-list.cache/` and not for `data`.
https://openzfs.github.io/openzfs-docs/man/8/zfs-mount-generator.8.html

Anyway, I'll read some docs to find out if I'm able to setup this correctly as I have no idea how it works / should work.

**Comment by JosefRypacek** [comment]
Last night I got idea for simple workaround - set mountpoint for unencrypted dataset `data/ds-1` of encrypted pool/dataset `data` to separate directory (e.g. `/unenc-ds-1`). This works as expected. Anyway I read mentioned documentation and also following one and enabled systemd mount generator for data pool. This solved the problem and there is no need to call `zfs mount -la`.
https://wiki.archlinux.org/title/ZFS#Automatic_Start

I've found that by default there is zfs-mount.service but it has disadvantage of this issue and datasets are also not mounted as early which may colidate with other services (e.g. docker).

Thanks

**Comment by darkpixel** [comment]
This is happening on my systems.

Tank is encrypted.  Nothing mounts when the system boots until we ```zfs load-key -a```,

After that we typically run ```zfs mount -a``` and go about our business.

Occasionally weird stuff happens without us noticing and some datasets don't mount.

```
filename:       /lib/modules/6.8.4-2-pve/zfs/zfs.ko
version:        2.2.3-pve2
```

```
root@uslaysdnas01:/tank# zfs mount tank/scans
cannot mount 'tank/scans': filesystem already mounted
root@uslaysdnas01:/tank# zfs umount tank/scans
cannot unmount '/tank/scans': no such pool or dataset
root@uslaysdnas01:/tank# df -h /tank/scans
df: /tank/scans: No such file or directory
root@uslaysdnas01:/tank# zfs get all tank/scans
NAME        PROPERTY              VALUE                     SOURCE
tank/scans  type                  filesystem                -
tank/scans  creation              Sat Nov 21 20:01 2020     -
tank/scans  used                  282M                      -
tank/scans  available             5.00G                     -
tank/scans  referenced            1.67M                     -
tank/scans  compressratio         1.09x                     -
tank/scans  mounted               yes                       -
tank/scans  quota                 none                      default
tank/scans  reservation           none                      default
tank/scans  recordsize            128K                      default
tank/scans  mountpoint            /tank/scans               default
tank/scans  sharenfs              off                       default
tank/scans  checksum              on                        default
tank/scans  compression           lz4                       inherited from tank
tank/scans  atime                 on                        default
tank/scans  devices               on                        default
tank/scans  exec                  on                        default
tank/scans  setuid                on                        default
tank/scans  readonly              off                       default
tank/scans  zoned                 off                       default
tank/scans  snapdir               hidden                    default
tank/scans  aclmode               discard                   default
tank/scans  aclinherit            restricted                default
tank/scans  createtxg             433                       -
tank/scans  canmount              on                        default
tank/scans  xattr                 on                        default
tank/scans  copies                1                         default
tank/scans  version               5                         -
tank/scans  utf8only              off                       -
tank/scans  normalization         none                      -
tank/scans  casesensitivity       sensitive                 -
tank/scans  vscan                 off                       default
tank/scans  nbmand                off                       default
tank/scans  sharesmb              off                       default
tank/scans  refquota              5G                        local
tank/scans  refreservation        none                      default
tank/scans  guid                  497829106193199365        -
tank/scans  primarycache          all                       default
tank/scans  secondarycache        all                       default
tank/scans  usedbysnapshots       280M                      -
tank/scans  usedbydataset         1.67M                     -
tank/scans  usedbychildren        0B                        -
tank/scans  usedbyrefreservation  0B                        -
tank/scans  logbias               latency                   default
tank/scans  objsetid              2203                      -
tank/scans  dedup                 off                       default
tank/scans  mlslabel              none                      default
tank/scans  sync                  standard                  default
tank/scans  dnodesize             legacy                    default
tank/scans  refcompressratio      1.09x                     -
tank/scans  written               0                         -
tank/scans  logicalused           277M                      -
tank/scans  logicalreferenced     1.37M                     -
tank/scans  volmode               default                   default
tank/scans  filesystem_limit      none                      default
tank/scans  snapshot_limit        none                      default
tank/scans  filesystem_count      none                      default
tank/scans  snapshot_count        none                      default
tank/scans  snapdev               hidden                    default
tank/scans  acltype               off                       default
tank/scans  context               none                      default
tank/scans  fscontext             none                      default
tank/scans  defcontext            none                      default
tank/scans  rootcontext           none                      default
tank/scans  relatime              on                        default
tank/scans  redundant_metadata    all                       default
tank/scans  overlay               on                        default
tank/scans  encryption            aes-256-ccm               -
tank/scans  keylocation           none                      default
tank/scans  keyformat             raw                       -
tank/scans  pbkdf2iters           0                         default
tank/scans  encryptionroot        tank                      -
tank/scans  keystatus             available                 -
tank/scans  special_small_blocks  0                         default
tank/scans  snapshots_changed     Mon Apr 29  8:15:23 2024  -
```

**Comment by rincebrain** [comment]
As explained above, that's probably that you're not using the systemd mount generator and sometimes it's mounting something "later" logically, before something "earlier", e.g. mounting "/tank" after "/tank/scans" would produce this result.

You can forcibly mount it more than once, with something like `mount -t zfs -o zfsutil tank/scans [wherever]`, but that doesn't fix the underlying issue.

**Comment by darkpixel** [comment]
I don't think anything is mounting it "earlier".
The datasets are encrypted, so they don't get mounted.
The system boots up and basically accepts SSH connections with very few services running--most of them are set to disabled.
Once I ```zfs load-key -a```, we manually start services like Samba.

**Comment by rincebrain** [comment]
If it says "mounted: yes" and it is not visibly mounted, I have so far never seen a case where it was not because the mount was being "hidden" - e.g. mounting `/tank/scans` and then mounting something at `/tank` would result in it, indeed, being mounted, but not visible until the thing it's mounted "under" is unmounted again.

If you like, concretely, the next time this comes up, for any path which displays this behavior, if it should be at e.g. `/foo/bar/baz`, try unmounting whatever's at `/foo/bar` and/or `/foo` and seeing if it magically reappears, which would confirm or deny my suspicion.

(Another possibility, in theory, would be if it's mounted but not visible to you in the namespace you're in, but I would expect you to be aware that you're doing wonky things with namespaces where that would be possible if it did...)

**Comment by darkpixel** [comment]
It's pretty rare that we reboot in the first place and it also doesn't occur every time, so it might be another 6-12 months before we get the opportunity to test. ;)

When it happens I'll do some digging to see if I can find anything that might be attempting to mount the datasets in a strange way.

**Comment by rincebrain** [comment]
You could also do something like a BPF probe that logs every "mount" call and set it up to start logging very early in boot, so that you would have a very visible "mount /foo/bar/baz" followed by "mount /foo" or something.

**Comment by rincebrain** [comment]
I forgot the other thing you could do, though it's going to cause visible breakage if you do.

The `overlay` property on datasets will make it error if you try to mount something on a non-empty mountpoint. It's not set to do that by default, because, you know, that's not how `mount` on any other filesystem works, but you could set it and watch what breaks the next time this happens (again, assuming I'm right).

**Comment by oldshensheep** [comment]
I have the same issue, and it can be reliably reproduced.
The problem is, as the rincebrain said:
> mounting /tank/scans and then mounting something at /tank

Here is the part of `systemd-analyze plot` output.
![image](https://github.com/openzfs/zfs/assets/29306733/c98976d4-f822-407c-8dbe-c9f97d6379e6)

As you can see `home.mount` is executed after `home-mio-codes.mount` that why I can't see the files in `/home/mio/codes/`, but according to systemd man https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html#Implicit%20Dependencies 
> If a mount unit is beneath another mount unit in the file system hierarchy, both a requirement dependency and an ordering dependency between both units are created automatically.

This is the output of  `systemd-analyze plot`.
![image](https://github.com/openzfs/zfs/assets/29306733/402f3719-a1aa-46a8-af35-e78d9e15bf0e)

Don't know what happened.

---------
I set the /home mount point to legacy, but not /home/mio/codes. Therefore, /home/mio/codes should not be managed by systemd, and maybe something unknown mounted it before systemd.

----------

I read all your comments again and found the problem. There is a `zfs-mount.service` before all other mount units. I overrode its Before and After settings, and the problem is solved!

So if you have `zfs-mount.service` enabled and are using systemd to manage your mount points, you may need to change their order.
