### ISSUE TITLE
Complile error: not import "VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver" namespace

### ISSUE THREAD

**Issue by shivabohemian** [openzfs/zfs#15081]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian GNU/Linux
Distribution Version	| 11 (bullseye)
Kernel Version	| rockchip kernel 5.10.110
Architecture	| arm64
OpenZFS Version	| 2.1.12

### Describe the problem you're observing

When I try to compile ZFS with Rockchip Kernel 5.10, I encountered an error while using the './configure' command. Upon my investigation, I found that it uses the 'EXPORT_SYMBOL_NS' macro when exporting some functions like 'kernel_read', which causes ZFS compilation to fail. What should I do to successfully compile ZFS?

### Describe how to reproduce the problem

Always. By the way, the kernel I used: https://github.com/rockchip-linux/kernel/commit/d483eed85ffb9879b103cd8d6b3fae367fa6193e

### Include any warning/errors/backtraces from the system logs

configure error:
<img width="656" alt="截屏2023-07-19 22 21 50" src="https://github.com/openzfs/zfs/assets/39078424/dba22c87-5ac1-4b75-9273-001f4f4730c8">

this is the error in build.log:
The error:
ERROR: modpost: module clear_inode uses symbol clear_inode from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module inode_set_flags uses symbol inode_set_flags from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module kernel_read uses symbol kernel_read from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module kernel_write uses symbol kernel_write from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module timestamp_truncate uses symbol timestamp_truncate from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

**Comment by rincebrain** [comment]
Think you'd get to go through and patch everywhere with a reference to any of those with a MODULE_IMPORT_NS(etc).

**Comment by shivabohemian** [comment]
Thank you for your response! It sounds good that I patch the source file with a MODULE_IMPORT_NS. 
Actually I'm a beginner, and I'd like to know what steps I should take to pass the configure check.
There are many "m4" macro files used for checks, is there a convenient way using MODULE_IMPORT_NS to make unified modifications?

**Comment by linnaea** [comment]
See here https://github.com/radxa/kernel/issues/54#issuecomment-1501031920

Rockchip BSP kernel is forked from Android Common Kernel, don't think ZFS would support the Android kernel any time soon.

**Comment by shivabohemian** [comment]
> See here [radxa/kernel#54 (comment)](https://github.com/radxa/kernel/issues/54#issuecomment-1501031920)
> 
> Rockchip BSP kernel is forked from Android Common Kernel, don't think ZFS would support the Android kernel any time soon.

Wow, I'll try. Thank you so much for your help!
