### ISSUE TITLE
zpool get does not query vdev properties

### ISSUE THREAD

**Issue by jimsalterjrs** [openzfs/zfs#15115]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 22.04
Kernel Version	| 5.15.0-69-generic
Architecture	| x86-64
OpenZFS Version	| zfs-2.1.5-1ubuntu6~22.04.1 , zfs-kmod-2.1.5-1ubuntu6~22.04.1

### Describe the problem you're observing

According to the manpage at https://openzfs.github.io/openzfs-docs/man/8/zpool-get.8.html, I should be able to use zpool get to query vdev properties. In particular, I'd like to pull the physpath of all vdevs. Unfortunately, zpool get does not honor either the `all-vdevs` argument or the names of any particular vdevs, interpreting either as an additional pool to query instead of identifying them as vdev names.

### Describe how to reproduce the problem

root@elden:/# zpool get all rpool all-vdevs | head
**cannot open 'all-vdevs': no such pool**
NAME   PROPERTY                       VALUE                          SOURCE
rpool  size                           1.81T                          -
rpool  capacity                       19%                            -
rpool  altroot                        -                              default
rpool  health                         ONLINE                         -
rpool  guid                           8091481277891027180            -
rpool  version                        -                              default
rpool  bootfs                         rpool/ROOT/ubuntu.2023.01.15   local
rpool  delegation                     on                             default
rpool  autoreplace                    off                            default

**Comment by behlendorf** [comment]
I believe the confusion here is that unfortunately we're not keeping versioned man pages at https://openzfs.github.io/openzfs-docs/man/index.html.  There's actually an open issue for this https://github.com/openzfs/openzfs-docs/issues/447.  The online man pages are generated from from the master branch of the git repo and in this case that means it's describing functionality which won't be available until the 2.2 release.

**Comment by jimsalterjrs** [comment]
Thanks @behlendorf -- I wondered if it might be something like that, but I couldn't find any information on how recently that feature might have popped up.

**Comment by gmelikov** [comment]
Done 
![image](https://github.com/openzfs/zfs/assets/3868786/0e5df238-c376-4a9e-86e8-761d9486ca84)

Feel free to give any usability feedback, I've added redirects from previous urls too.
