### ISSUE TITLE
There's no zfs-2.2.99 tag so all RPMs have the same version '2.2.99-1'

### ISSUE THREAD

**Issue by siebenmann** [openzfs/zfs#15112]
### System information

Type | Version/Name
 --- | ---
Distribution Name | Fedora
Distribution Version	| 37 and 38
Kernel Version	| 6.3.x currently
Architecture	| x86_64
OpenZFS Version	| git tip from commit ca960ce56ce1bfe207e4d80ba6e5ab67ea41b32f

### Describe the problem you're observing

Because there is no 'zfs-2.2.99' tag, all RPMs built from the current git tip get the RPM version of '2.2.99-1', which makes it complicated to upgrade from one git tip build to another one. When building from a git repo (without .nogitrelease), config/zfs-meta.m4 file is what determines `ZFS_META_RELEASE` and it uses `git describe --match=zfs-<VERSION>`, which requires an annotated tag of the same version in order to work.

It's possible that this affects other package builds and versioning (eg `zfs version`), but I have direct experience only with RPM builds.

**Comment by behlendorf** [comment]
Sorry about that.  I've created the 2.2.99 tag.
