### ISSUE TITLE
Re-release OpenZFS under BSD 2 or 3 clause license or a GPL compatible license

### ISSUE THREAD

**Issue by delgh1** [openzfs/zfs#15120]
### Describe the feature would like to see added to OpenZFS

Re-release OpenZFS under BSD 2 or 3 clause license or a GPL compatible license so that zfs kernel modules can be shipped with linux kernel without any legal implications.

### How will this feature improve OpenZFS?

I foresee much greater adoptions of OpenZFS among users, if linux users can use zfs at ease like other filesystems.
Tons of tickets here because of license incompatibility would not be even raised -> devs can focus on their more important work.

*Copyright holders: please remember OpenZFS is for GNU/Linux and FreeBSD.*

### Additional context

I'm not goot at debate, nor am I a native speaker of English. So I kept it short.

**Comment by amotin** [comment]
@delgh1 You obviously don't understand how licenses work.  License change would require permission from all the copyright holders, and so far Oracle was not going to give one, not mentioning difficulties to collecting permissions from all numerous developers who contributed to it after that.
