### ISSUE TITLE
ZFS asks for root permissions to list datasets and other simple commands that I could run without root before

### ISSUE THREAD

**Issue by PoisonFrog** [openzfs/zfs#15157]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Kernel Version	|  6.4.7
Architecture	| AMD64
OpenZFS Version	|  2.1.12-1

### Describe the problem you're observing
I'm having an issue that out of nowhere commands that didn't ask for root permission like "zfs list" are asking for root permissions all of a sudden. When I try to run "zfs list" it outputs "_Permission denied the ZFS utilities must be run as root._"

Funny thing is that I have another Arch machine running the same version of ZFS (but not same kernel) that doesn't have this issue.

**Comment by rincebrain** [comment]
#15146 would be my guess.

**Comment by PoisonFrog** [comment]
> #15146 would be my guess.

Yeah, seems to be the exactly same issue. I'll close this one since there is an open issue for it already.
