### ISSUE TITLE
Unprivileged user cannot run non critical commands such as "zfs list" after recent archlinux upgrade

### ISSUE THREAD

**Issue by odror** [openzfs/zfs#15162]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	|
Kernel Version	| 6/4/8
Architecture	|  x86_64
OpenZFS Version	| zfs-2.1.12-1

### Describe the problem you're observing
After latest upgrade a non privileged user cannot perform. Non critical commands such as " zfs list" "or "zpool list"

### Describe how to reproduce the problem

When typing "zfs list" i get the following error:
Permission denied the ZFS utilities must be run as root. 

There is no issue is using "sudo zfs list"

**Comment by rincebrain** [comment]
#15146

**Comment by odror** [comment]
Duplicate
