### ISSUE TITLE
cp failing sporadically due to EAGAIN being returned from copy_file_range

### ISSUE THREAD

**Issue by Tobi29** [openzfs/zfs#15170]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Arch Linux
Distribution Version	|Rolling release
Kernel Version	|6.4.9-zen1-1-zen
Architecture	|x86_64
OpenZFS Version	|2.2.99-61_g8ce2eba9e6

### Describe the problem you're observing

Copying files using e.g. `cp` occasionally fails, giving an error like `cp: error copying 'file_a' to 'file_b': Resource temporarily unavailable`.
This is caused by `copy_file_range` in zfs returning `EAGAIN`, something that seems to have been added in f21662d9a69c6be3b48abcb873b93955a92f34a8.
The man page for `copy_file_range` does not mention `EAGAIN` as a possible error and I cannot say how many other programs, beyond `cp`, also handle `EAGAIN` as a hard error in this case.
Switching to `cp --reflink=never` fixes the problem.

The end result of this is that many automation scripts, e.g. makepkg on Arch Linux, are unusable because of files, because they trigger this error very frequently.

### Describe how to reproduce the problem

This example script triggers the issue almost every time:

```bash
#!/bin/bash

dd if=/dev/urandom of=file_a bs=4MiB count=1
cp file_a file_b
dd if=/dev/urandom of=file_a bs=4MiB count=1
cp file_a file_b

# just cleanup
rm file_a file_b
```

It is required to run these commands in very quick succession.

### Include any warning/errors/backtraces from the system logs

The mentioned script would output:

```
1+0 records in
1+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.00903691 s, 464 MB/s
1+0 records in
1+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.00990963 s, 423 MB/s
cp: error copying 'file_a' to 'file_b': Resource temporarily unavailable
```

Nothing can be seen in `dmesg`.

**Comment by rincebrain** [comment]
@oromenahar

**Comment by oromenahar** [comment]
Got an update on this, will be merged pretty fast.
Thanks for this issue.
