### ISSUE TITLE
After multiple system failures, hard locks and hangs ZFS pool attempting to increase fill beyond max

### ISSUE THREAD

**Issue by kryptt** [openzfs/zfs#15206]
Using:
  zfs-2.1.12-r0-gentoo
  zfs-kmod-2.1.12-r0-gentoo
on:
Gentoo stable (linux/amd64/17.1/desktop/gnome/systemd/merged-usr)  6.1.41-gentoo-x86_64

After multiple system hangs, and unstability my main zfs pool seems to be in an 'unsafe' state: 

I am now able to keep the system running with the zfs_recover parameter,  but I conitnuously get a 'double add in segment error'. It is consistently the same segment.

[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:43:58 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:49:56 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]
[Fri Aug 25 09:49:56 2023] WARNING: zfs: attempting to increase fill beyond max; probable double add in segment [3395d418000:33966fa4000]

What are my options here?

**Comment by amotin** [comment]
Run good long memory test before potentially faulty memory trashed your data even more.  Copy the data off the pool and recreate it from scratch. zfs_recover should not be taken easy, it is really the last resort to try saving the data.

**Comment by kryptt** [comment]
Thanks, I had done a memory check, but not recently enough... If it weren't for your suggestion I don't know how bad it would have gotten!!!
