### ISSUE TITLE
Receiving a full send as a clone using `-o origin=` fails

### ISSUE THREAD

**Issue by muay-throwaway** [openzfs/zfs#15254]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Ubuntu 
Distribution Version	| 22.04.3 LTS
Kernel Version	| 6.2.0-31-generic
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.5-1ubuntu6~22.04.1

### Describe the problem you're observing

The `-o origin=` argument is meant to be able to take a full send of a filesystem and receive it as a clone to save disk space. In particular, the following scenario, as described by @ahrens ([1](https://github.com/openzfs/openzfs/pull/23), [2](https://illumos.topicbox.com/groups/zfs/T8b9853ddacbe5966-M0d621559ac480719a52b731f/review-request-6393-zfs-receive-a-full-send-as-a-clone)):

> For example, maybe on the source you have:
> 
> A ---- B ---- C
> 
> And you have sent to the target a full of B, and the incremental B->C:
> 
> B ---- C
> 
> You later realize that you want to have A on the target.  You will have to do a full send of A, but nopwrite can save you space on the target if you receive it as a clone of B, assuming that A and B have some blocks in common:
> 
> B ---- C
>  &nbsp;&nbsp;\\
>  &nbsp;&nbsp;&nbsp;A

However, it appears this no longer works; the receiving filesystem rejects a full send due to existing snapshots.

### Describe how to reproduce the problem

Take three snapshots, a, b, and c (in order) on a sending filesystem. Send snapshots b and c. Attempt to send snapshot a later as a clone with `-o origin`.

```
zfs create apool/fs
zfs snapshot apool/fs@a
zfs snapshot apool/fs@b
zfs snapshot apool/fs@c
zfs send apool/fs@b | zfs receive bpool/fs
zfs send -I apool/fs@b apool/fs@c | zfs receive bpool/fs
zfs send -v apool/fs@a | zfs receive -v -o origin=bpool/fs@b bpool/fs
```

This send/recv is rejected with the following message:
```
full send of apool/fs@a estimated size is 12.6K
total estimated size is 12.6K
using provided clone origin bpool/fs@b
cannot receive new filesystem stream: destination 'bpool/fs' exists
must specify -F to overwrite it
```

Providing the `-F` argument yields the following
```
full send of apool/fs@a estimated size is 12.6K
total estimated size is 12.6K
using provided clone origin bpool/fs@b
cannot receive new filesystem stream: destination has snapshots (eg. bpool/fs@b)
must destroy them to overwrite it
```

**Comment by muay-throwaway** [comment]
I am not sure if this is an intended regression or an unintentional bug. Is this actually a defect? Or an intended feature change?

**Comment by rincebrain** [comment]
You seem to be trying to receive into the same filesystem you want to be a clone of.

Try something like 
`zfs send -v apool/fs@a | zfs receive -v -o origin=bpool/fs@b bpool/fs2`

**Comment by muay-throwaway** [comment]
@rincebrain Ah, thank you! I was under the impression that a snapshot received as a clone could still be nested under the same filesystem based on #10325, but, on further review, that was what the question asker was proposing, not what was given in the answer. Closing as resolved.

**Comment by muay-throwaway** [comment]
Actually, after further testing, I am reopening, in case what I am seeing may be a defect.

Right after the first snapshot a, I added a large lorem ipsum text file (~233M) to `apool/fs`:
```
zfs create apool/fs
# I separately created a large lorem ipsum file and copied to apool/fs
cp -v lorem_2.txt /apool/fs/
zfs snapshot apool/fs@a
zfs snapshot apool/fs@b
zfs snapshot apool/fs@c
zfs send apool/fs@b | zfs receive bpool/fs
zfs send -I apool/fs@b apool/fs@c | zfs receive bpool/fs
zfs send -v apool/fs@a | zfs receive -v -o origin=bpool/fs@c bpool/fs2
```
This gives the following messages:
```
full send of apool/fs@a estimated size is 234M
total estimated size is 234M
using provided clone origin bpool/fs@c
receiving full stream of apool/fs@a into bpool/fs2@a
TIME        SENT   SNAPSHOT apool/fs@a
01:57:58   92.3M   apool/fs@a
01:57:59    159M   apool/fs@a
01:58:00    233M   apool/fs@a
received 234M stream in 3 seconds (77.9M/sec)
```
Snapshots a, b, and c are identical in data content. When I later re-send snapshot a to be received as a clone, it should theoretically not occupy any more disk space. However, I see the disk usage being duplicated:
```
NAME                   AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
apool                   598M   234M        0B     25K             0B       233M
apool/fs                598M   233M        0B    233M             0B         0B
bpool                   365M   467M        0B     25K             0B       467M
bpool/fs                365M   233M        0B    233M             0B         0B
bpool/fs2               365M   233M        0B    233M             0B         0B
```

**Comment by rincebrain** [comment]
snapshot A was before it was finished writing it all out permanently, some of it was in the log, so on first mount it's finishing the log playback and doing the rest of the writes, if I had to guess.

**Comment by muay-throwaway** [comment]
Good thinking! I destroyed the pools and repeated the steps, including a roughly half-hour break after the `cp` step for good measure. I saw the same result, however. I repeated and saw the same result with both SSDs and HDDS (pool of mirrors).

**Comment by rincebrain** [comment]
What's the checksum on the dataset? nopwrite is only germane if you're using something better than fletcher4.

**Comment by muay-throwaway** [comment]
@rincebrain You are a genius. Yes, on the test dataset, I had left the checksum algorithm on the default. With sha512 as the checksum and compression on, the clone filesystem contained only KiB of data.

Thank you for your help! I apologize for construing this as a bug.

**Comment by rincebrain** [comment]
No worries, that probably means the man page should get a footnote explaining that lest people be equally surprised by the outcome.
