### ISSUE TITLE
Please add inverse command to `zpool offline -f`

### ISSUE THREAD

**Issue by hilbix** [openzfs/zfs#15266]
### Describe the feature would like to see added to OpenZFS

There apparently is no inverse to the command `zpool offline -f` without restarting the pool.

If a device is offlined (accidentally or for some purpose),
the only option to bring back that device is to stop the pool completely
and start it again.  This contradicts 24/7.

This here is to suggest a command or a (documented) way to remove the "Faulted" or "Unavailable" state on a device,
such that it can be successfully "online"d again while keeping the pool active.

### How will this feature improve OpenZFS?

- Easy way to get around common human errors (like unplugging the wrong cable or pulling the wrong device)
- Better 24/7
- Make commands symmetrical

### Additional context

If I am not mistaken, the faulted state is kept somewhere in the `zpool.cache`,
because I think I sometimes needed to remove it to get rid of some wrongly introduced FAULTED state.

However bringing back a device from FAULTED state always requires something similar to a reboot.
Therefor my idea would be to make `online` symmetric to `offline`:

```
zpool offline POOL device
zpool online -t POOL device
zpool online -f POOL device
```

Where `-f` corresponds to option `zpool offline -f` and `-t` corresponds with `zpool offline -t`.

Hence with `online -f` you can remove the permanent FAULTED flag (after the device is successfully onlined)
while `online -t` does the same but only temporarily (not removing the permanent FAULTED or OFFLINE state),
such that a permanently FAULTED device would become FAULTED again with the next reboot or `online`
without flags.

This also gives us additional options without implementing a complex administrative procedure:

- Operators only get access to the `offline` without flags and `offline` with option `-t`
- Admins get the full access to `online` and `offline`
- By using `offline -f` Admins can prevent Operators to accidentally bring up a device again
- As Operators can only use `online -t` their actions are only temporary and need Admin approval to become permanent

It may look like abusing these options, and this certainly is.  But it seems just too easy to me to have such an opportunity.
For example if some fiber breaks and is replaced by a low capacity backup for a while.  Then you want to offline
some redundant SAN drives to reduce the load on the backup link, such, that the normal operating cannot
accidentally interfere.  However on weekends you want to bring it temporarily online to catch up.
You can do this by issuing notes, or create some complex software setup and stuff,
but we are humans and computers should not dictate how and what we do, it must be the other way round.

Note that I do not need the latter.  I just need a way to take back the FAULTED state on a drive.
Because 2-4 times a year I manage to bring one of the devices into FAULTED state just because of (my) human error
(for example by unplugging the wrong cable) and then I always need to reboot the pool, which is very annoying
because this means some downtime which is entirely unnecessary.

**Comment by rincebrain** [comment]
`zpool clear`

**Comment by hilbix** [comment]
Until today I was not aware **of the fact, that `zpool clear` is meant to be the inverse of `zpool offline -f`** because that is not mentioned in the manual.  However I always used that command on accident.  I must have used it, because else the FAULTED state would have persisted across reboots.  However after reboot the devices left FAULTED state, so I got the impression that `reboot` did the trick.  Sorry for my confusion.

Now I have looked into the sources, too, and get the impression, that I was in err and not the `reboot` but the `zpool clear` brought back the device.  **However this still needs a reboot for some unknown reason, see below!**  Perhaps it is some Ubuntu thing or caused by my very special setup here.

> What I am trying to archive is to online a `cache` vdev only for certain workloads.
> After using `zpool offline -f` the device stayed in FAULTED state, but a reboot fixed it.
> Today I found out that there is apparently more to it, see below.

I will continue to monitor my setup here and if I find out why a reboot makes the difference I will report back,
here, at this location.  Keep it closed, if it is a bug I will open a bug.

HTH

--------------------------------------

Note that `zpool clear` is not mentioned in the manual pages of `zpool offline` at my side (Ubuntu 22.04 LTS):

```
# man zpool offline | cat
ZPOOL-OFFLINE(8)                                       BSD System Manager's Manual                                      ZPOOL-OFFLINE(8)

NAME
     zpool-offline — take physical devices offline in ZFS storage pool

SYNOPSIS
     zpool offline [-ft] pool device…
     zpool online [-e] pool device…

DESCRIPTION
     zpool offline [-ft] pool device…
             Takes the specified physical device offline.  While the device is offline, no attempt is made to read or write to the de‐
             vice.  This command is not applicable to spares.

             -f      Force fault.  Instead of offlining the disk, put it into a faulted state.  The fault will persist across imports
                     unless the -t flag was specified.

             -t      Temporary.  Upon reboot, the specified physical device reverts to its previous state.

     zpool online [-e] pool device…
             Brings the specified physical device online.  This command is not applicable to spares.

             -e      Expand the device to use all available space.  If the device is part of a mirror or raidz then all devices must be
                     expanded before the new space will become available to the pool.

SEE ALSO
     zpool-detach(8), zpool-remove(8), zpool-reopen(8), zpool-resilver(8)

OpenZFS                                                      August 9, 2019                                                      OpenZFS
```

> It is not mentioned in Debian Bookworm, either.

--------------------------------------

It happened today again:

```
zpool online pool dev
zpool clear pool dev
zpool status
```

Device stays in FAULTED state.  So I stopped everything which accessed ZFS.  Then:

```
zpool export pool
systemctl stop zfs-zed.service
for a in zfs icp zcommon zunicode zzstd zlua zavl znvpair spl; do rmmod "$a"; done
rm -f /etc/zfs/zpool.cache
modprobe zfs
zpool import pool
zpool status
```

Device still in FAULTED state.

```
zpool clear pool dev
zpool status
```

Device still in FAULTED state.

```
rm -f /etc/zfs/zpool.cache
reboot
```

Then (as `zpool.cache` is gone no pool is mounted by init):

```
zpool import pool
```

The device is ONLINE again.

To stress it:

- The device was in FAULTED state immediately before reboot
- The device was no more in FAULTED state after reboot
- I did not use `zpool offline -t`
- Export/Import does not help
- Unloading ZFS from kernel does not help

I cannot do more tests, as the system is busy.  But as the problem shows up randomly, I certainly will have the chance to investigate a bit further.

**Comment by rincebrain** [comment]
It's not mentioned explicitly, no, because `zpool clear` is how you would reset the `FAULTED` state on a device no matter whether it was deliberately induced or not.

That could be mentioned in the manual, but that's why it's not specially called out right now, I think.

**Comment by hilbix** [comment]
OK, a few minutes back it happened again.  And now I was able to solve the mystery:

**ZFS is absolutely right in putting it in FAULTED state**, because the device faulted immediately **after** (or while) being onlined (which caused my confusion thinking that it staid in FAULTED state.  However it FAULTED again).

The FAULT is neiter due to hardware, driver nor corrupt contents.  **The FAULT at my side is due to some wrong bookkeeping in the Linux Kernel,** nothing which ZFS can do about.  AFAICS even the Kernel is not at fault, it seems to be just some bloody bad race condition combined with some lack of error reporting or verification of `lvm2`.

Nothing gets really hurt, though, except that things do not work as expected (which only hurts the Admin .. a bit).

After `vgscan` and `vgchange -ay`, the VG with the LV used by ZFS is reported up by all the common tools and therefor seems to be in perfect health state.  **However this is a lie, the LV still is inaccessible.**

In fact the LV's table (`device_name`) listed in `dmsetup table` still refers to the **old** mapping before the device was offlined.  Hence ZFS tries to access the LV and - luckily - hits something, which has no device attached anymore.  Hence it FAULTs.

This also explains, why a reboot does indeed help:  The Kernel starts up with a clean devicemapper-table, so the device can be accessed and properly onlined.  Hence ZFS removes the FAULTED state as advertised.


## Lesson learned

When there is trouble with some `ZFS` vdev on Linux, also **have a very close look into `dmsetup`**.  Perhaps there are still some old remains in it which need to be cleaned up with `dmsetup rm`.  And **do not forget about `losetup -a`**, as a few years back, a colleague nearly got mad about the fact that `dmsetup rm` refused to work.  This was because a loopback device still "secretly" kept a reference to it, but you won't see that anywhere else, so if you do not happen to think about `losetup` you won't ever find it.

--------------------

AFAICS the root cause of my trouble here is (I hope this is interesting, too):

The script, which offlines the device, also powers down the device.  This happens in parallel.

However `zpool offline` is not instant and takes a bit longer.  Hence ZFS "unuses" the device a bit too late, such that the device is deleted faster from device tree than "unused".  Hence the table in `dmsetup` is still locked when the device is deleted by `udev`, such that the old table continues to persist afterwards.

Now, when re-enabling the device, it comes up and gets a new device name (i.E. `/dev/sdd` instead of `/dev/sdc` before).  But the LV occupies the same name in `dmsetup` as before, of course.  As there already is a table for the entry of lhe LV in devicemapper, which still refers to the old device (i.E. `/dev/sdc`), `vgchange -ay` does not touch this existing table of the LV (for good).  However it does not seem to report this fact back properly (or at least I was not able to spot some prominent message).  So everything looks to be in a sane state, even that the mapping is completely wrong.
