### ISSUE TITLE
zstdcheck fails

### ISSUE THREAD

**Issue by ahrens** [openzfs/zfs#15282]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	|70ea484e3ec56c529c6c5027ffc43840100ce224

### Describe the problem you're observing

The `checkstyle` github action always fails, because `make zstdcheck` fails.  For example, see [here](https://github.com/openzfs/zfs/actions/runs/6203803487/job/16844968949?pr=15281).

```
...
0000000000004c80 g     F .text	0000000000000010 __pfx_zfs_ZSTD_DCtx_reset
0000000000004d30 g     F .text	0000000000000010 __pfx_zfs_ZSTD_sizeof_DStream
0000000000004d90 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decodingBufferSize_min
0000000000004dd0 g     F .text	0000000000000010 __pfx_zfs_ZSTD_estimateDStreamSize
0000000000004e10 g     F .text	0000000000000010 __pfx_zfs_ZSTD_estimateDStreamSize_fromFrame
0000000000005190 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decompressStream
0000000000005c60 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decompressStream_simpleArgs
zstd/lib/decompress/zstd_decompress_block.o:     file format elf64-x86-64
00000000000044f0 g     F .text	0000000000000010 __pfx_zfs_ZSTD_getcBlockSize
0000000000004560 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decodeLiteralsBlock
00000000000049b0 g     F .text	0000000000000010 __pfx_zfs_ZSTD_buildFSETable
0000000000004e90 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decodeSeqHeaders
00000000000050d0 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decompressBlock_internal
0000000000005310 g     F .text	0000000000000010 __pfx_zfs_ZSTD_checkContinuity
0000000000005370 g     F .text	0000000000000010 __pfx_zfs_ZSTD_decompressBlock
make: *** [Makefile:14103: zstdcheck] Error 2
```
### Describe how to reproduce the problem

`make zstdcheck`

**Comment by ahrens** [comment]
@nabijaczleweli or @rincebrain I think you might have added `zstdcheck`, can you help us understand what problem it is reporting here?

**Comment by rincebrain** [comment]
I didn't add it, but at a glance, something's started adding a prefix to all the symbol names on your system? At a glance, on Linux, that seems to be a CFI thing, from torvalds/linux@b341b20d648b

But for example, on my Debian system, at 8af8d2abb, `make zstdcheck` passes.

**Comment by ahrens** [comment]
I haven't run it on my system, but it fails in the github runner environment specified by the github action `.github/workflows/checkstyle.yaml`:
```
    runs-on: ubuntu-22.04
```

**Comment by nabijaczleweli** [comment]
Clearly, given `@OBJDUMP@ -t $(addprefix zstd/,$(ZSTD_UPSTREAM_OBJS)) | awk '/file format/ {print}  $$2 == "g" && !/ zfs_/ {++ret; print}  END {exit ret}'` and the ` 0000000000003b80 g     F .text	0000000000000010 __pfx_zfs_ZSTD_getDictID_fromDict` output, this checks for global symbols that don't start with `zfs_`. Considering
```
nabijaczleweli@tarta:~/store/code/zfs$ git grep __pfx_
nabijaczleweli@tarta:~/store/code/zfs$ git grep __pfx
nabijaczleweli@tarta:~/store/code/zfs$ git grep _pfx
nabijaczleweli@tarta:~/store/code/zfs$ git grep pfx
Binary file tests/zfs-tests/tests/functional/cli_root/zpool_upgrade/blockfiles/zfs-pool-v3hotspare3.dat.bz2 matches
```
(current HEAD – 8af8d2abb1ee928beea16e12390dd7b8cf76244f) I can't really see where the "pfx" thing is coming from, considering the symbols are renamed with a huge fuckoff autogenerated file in the
```
module/zstd/include/zstd_compat_wrapper.h:#define       ZSTD_calloc zfs_ZSTD_calloc
module/zstd/include/zstd_compat_wrapper.h:#define       ZSTD_free zfs_ZSTD_free
module/zstd/include/zstd_compat_wrapper.h:#define       ZSTD_getErrorCode zfs_ZSTD_getErrorCode
```
form. Is ubuntu shipping a weird or otherwise broken toolchain?

**Comment by nabijaczleweli** [comment]
or i could read the edit upthread with the linux link; #15284

**Comment by ahrens** [comment]
Thanks @nabijaczleweli !
