### ISSUE TITLE
Dkms : building v2.2.12 for linux 6.1.0-12 freezes computer (debian bookworm)

### ISSUE THREAD

**Issue by Notmarrco** [openzfs/zfs#15299]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian bookworm
Distribution Version	| 12
Kernel Version	| 6.1.0-12-amd64
Architecture	| 64bits
OpenZFS Version	| 2.1.12

### Describe the problem you're observing

After migrating from kernel v5 to v6.1, the zfs compilation using dkms fails.

I didn't succeed in building zfs2.1.11 so I tried with 2.1.12 from backports and the issue is still there.

My issue is that  after some time "building initial module for 6.1.0-12-amd64", my server freezes.
I tried to let the compilation be done all night, but at the end I was still stuck at this "building intial module" stage.

So I had to reboot the computer, and now I can't find any log or trace of what happened.

What can I do to get more context please ?

### Describe how to reproduce the problem

For me it's just a matter of installing `apt install zfs-dkms`.

Also after a reboot `dpkg --configure all` leads to the same issue.

### Include any warning/errors/backtraces from the system logs

Sorry I have none, and don't know how to get more.

**Comment by rincebrain** [comment]
If you're having a problem with Debian's packages for OpenZFS, you should probably report a Debian bug.

**Comment by Notmarrco** [comment]
Thanks @rincebrain , I'm not sure where it comes from since the steps in debian package are pretty straightforward, and it seemed to me it was a problem during compile time.

In the end I just played manually each step from the `zfs-dkms.postinst` file : 

```sh
dkms build -m zfs -v 2.1.12
dkms install -m zfs -v 2.1.12
/sbin/modprobe zfs
```

and ... it works ...
