### ISSUE TITLE
The openzfs not to repair bad data when the kenrel report IO error ( cause the raidz data incomplete )

### ISSUE THREAD

**Issue by homerl** [openzfs/zfs#15292]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7
Kernel Version	|  3.10.0-957.1.3.el7_lustre.x86_64
Architecture	|  x86_64
OpenZFS Version	|  0.7.13-1

### Describe the problem you're observing
Some devices show many read/write I/O errors in the dmesg from time to time. The errors may last for seconds or minutes.    
```
mpt3sas_cm0: log_info(0x3112010a): originator(PL), code(0x12), sub_code(0x010a)
sd 1:0:135:0: [sddx] tag#33 FAILED Result: hostbyte=DID_SOFT_ERROR driverbyte=DRIVER_OK
sd 1:0:135:0: [sddx] tag#33 CDB: Write(16) 8a 00 00 00 00 05 00 df 7d bc 00 00 00 f2 00 00
blk_update_request: I/O error, dev sddx, sector 21489483196
sd 1:0:132:0: [sddv] tag#92 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
sd 1:0:132:0: [sddv] tag#92 Sense Key : Aborted Command [current]
sd 1:0:132:0: [sddv] tag#92 Add. Sense: Nak received
sd 1:0:132:0: [sddv] tag#92 CDB: Read(16) 88 00 00 00 00 05 0b cc 46 67 00 00 00 50 00 00
```

### Describe how to reproduce the problem
The hardware will trigger it, I don't know how to reproduce it.      
In the production env,  the 4x Dell ME484 JBOD will trigger this issue, just ME484 only, the others ME484 is OK, All of the Seagate, Dell MD1280(5U 84 bay) is OK.     
eg: the IO expander timeout      
```
mpt3sas_cm0: log_info(0x3112010c): originator(PL), code(0x12), sub_code(0x010c)
scsi_io_completion: 421 callbacks suppressed
..... read/wrote IO errors.....
```

### Include any warning/errors/backtraces from the system logs

The zpool to show health and no errors before a scrub, but then for the scrub to find errors     
```
  pool: ost_4
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub in progress since Fri Sep 15 23:36:27 2023
	144T scanned out of 211T at 667M/s, 29h23m to go
	94.0M repaired, 68.11% done
config:

	NAME                        STATE     READ WRITE CKSUM
	ost_4                       ONLINE       0     0     0
	  raidz3-0                  ONLINE       0     0     0
	    scsi-35000039a48594311  ONLINE       0     0     0
	    scsi-35000039a485abcc5  ONLINE       0     0     0
	    scsi-35000039a4878ea51  ONLINE       0     0     0
	    scsi-35000039a48530b3d  ONLINE       0     0     0
	    scsi-35000039a4862d34d  ONLINE       0     0     0
	    scsi-35000039a4878eb61  ONLINE       0     0     0
	    scsi-35000cca2a174411c  ONLINE       0     0     0
	    scsi-35000039a4852c661  ONLINE       0     0     0
	    scsi-35000039a4878eb39  ONLINE       0     0     0
	    scsi-35000039a4862798d  ONLINE       0     0   845  (repairing) 
	    scsi-35000039a48714e81  ONLINE       0     0   774  (repairing)
	    scsi-35000039a486959c5  ONLINE       0     0   966  (repairing)
	    scsi-35000039a486959d5  ONLINE       0     0 1.38K  (repairing)
	    scsi-35000cca28482c204  ONLINE       0     0 1.04K  (repairing)
	    scsi-35000039a48714ec1  ONLINE       0     0 1.94K  (repairing)  
	    scsi-35000cca29563ed60  ONLINE       0     0   914  (repairing)
	    scsi-35000cca29562a99c  ONLINE       0     0 1.17K  (repairing)
	    scsi-35000039a486b9915  ONLINE       0     0 1.72K  (repairing)
	    scsi-35000cca28478f4c8  ONLINE       0     0 1.11K  (repairing)

errors: No known data errors
```

The scrub result indicates a lot of incomplete data in this zpool. The Linux kernel knows about the SCSI errors, but openzfs did not repair them when the scrub was not run. If a user does not monitor the SCSI errors and sets the zpool to scrub every two months, the accumulation of small errors may result in more serious problems, such as incomplete metadata. This means that the zpool may crash if the errors are allowed to accumulate for an extended period of time.     

If the kernel reports I/O errors, can ZFS repair them immediately?         
In this case, it is too late to scrub the zpool. When the error shows, the scrub may have already been done half a month ago, which is enough time to cause irreparable damage.           

In the second case, the scrub may not be able to fix the errors forever, since each scrub may find new errors.        
Here is not silent error because the kernel shows the read/write errors      
And the scrub is too hard when I get a read/write error from the log, Hope the ZOL 2.X fix this.    
Thanks.

**Comment by amotin** [comment]
IIRC ZFS considers write successful if at least one copy of the data was written.  Otherwise it would be fatal, since attempt to retry writes after all retries on lower levels immediately will likely fail too.  All ZFS can do (and does) in case of unrecoverable write error is freeze the pool.  It could possibly be checked how error statistics is handled from the point of accounting partial errors though.

PS: You are running so old version of ZFS that any reports of yours may be outdated. ZFS 2.0 version you mention is already outdated also, 2.1 is now production and 2.2 is coming soon.

**Comment by IvanVolosyuk** [comment]
In this case the problem can be in PSU or disk controller which triggered system instability during scrub. The data is safe at rest, but a lot of disk activity overloads PSU and causes disk errors on read.

**Comment by IvanVolosyuk** [comment]
If kernel detects io error on block device - zfs will get the error and handle it accordingly. There is not much zfs can do if device starts to through write errors other than retry failed write, report error counts and mark the device as faulted. Common practice is to have hot spares and zed daemon configured for hot swap, monitoring and reporting those errors by whatever means necessary.
