### ISSUE TITLE
Allow changing pool GUIds

### ISSUE THREAD

**Issue by Ericson2314** [openzfs/zfs#15326]
Sorry if this already has an issue, the closest I found was https://github.com/openzfs/zfs/issues/11404 

### Describe the feature would like to see added to OpenZFS

I would like to be able to modify the GUID of an existing pool.

### How will this feature improve OpenZFS?

I `dd` my drive to a new disk. I did this instead of `send`/`receive` because it would allow me to be lazy and not setup partition encryption etc. again.

I can open each pool with `zpool import -d`, but I can't import both at once because they have the same GUID. This is reasonable.

I would like to thus open one of them and do `zpool set guid=....` but this is not allowed. I get that this is a bad idea for multiple vdez pools where physical devices come online/offline, but seems like a less useful restriction for the simple single-device case. And it is an artificial restriction in any event, right?

**Comment by tonyhutter** [comment]
Did you try `zpool reguid`? (https://openzfs.github.io/openzfs-docs/man/v2.1/8/zpool-reguid.8.html)

**Comment by Ericson2314** [comment]
Oh! I failed to fine that. Excellent! (Will report back in a moment.)

**Comment by Ericson2314** [comment]
Yeah that worked just great!
