### ISSUE TITLE
Inconsistent Space Conservation with nopwrite in Incremental ZFS Snapshots

### ISSUE THREAD

**Issue by ghost** [openzfs/zfs#15325]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu, FreeBSD
Distribution Version	|  22.04, 13.2
Kernel Version	| 5.4, 14.0-RELEASE
Architecture	|x86_64
OpenZFS Version	| 2.1.5, 2.1.9

### Describe the problem you're observing
I am observing unexpected behavior with ZFS nopwrite, impacting space conservation for snapshots. This occurs with large files undergoing minimal modifications, and the achieved space conservation with nopwrite seems less than expected. Despite minimal modifications to the file, the incremental snapshot size is almost equivalent to the original snapshot. When modifications are made directly within the ZFS pool, the snapshots are as small as expected (<1MB).

### Describe how to reproduce the problem
1. Create a ZFS Pool using the following command:
   ```sh
   zpool create -o ashift=12 -O compression=on -O checksum=edonr -O dedup=off poolname /dev/sdb
   ```
2. Copy a 2GB file (filled by urandom) into the pool and take a snapshot.
3. Modify a few kilobytes in the middle of the original file using `dd` and overwrite the file in the pool, then take another snapshot.
```sh
sudo zfs send --raw -i poolname@incr poolname@orig > incr.zfs.snap
sudo zfs send --raw poolname@orig > orig.zfs.snap
```

### Include any warning/errors/backtraces from the system logs

n/a

### Additional Information
- `nopwrite` is confirmed active via `kernelmod`.
- No alteration in file size after applying `dd` modifications.
- Both `edonr` and `sha256` checksums have been tested.
- Compression is enabled, following the guidelines from #6534.
- `dedup` has been tested in both on and off states, with similar results.
- Similar behaviors are observed on both FreeBSD and Ubuntu.
- A thread discussing this issue has been started on the mailing list: [ZFS on Linux Topicbox](https://zfsonlinux.topicbox.com/groups/zfs-discuss/T53001e3d4b8fe4ee)

I'm looking for insights, possible corrections to user errors, or alternative methods to effectively use nopwrite for space conservation in ZFS snapshots, especially with minimally modified large files. Any clarification on the observed discrepancy in nopwrite’s space conservation on incremental snapshots would be immensely valuable.

**Comment by rincebrain** [comment]
You probably wanted conv=notrunc on the Linux dd command. I'm sure FreeBSD has an equivalent.

**Comment by GregorKopka** [comment]
When you `zfs snapshot poolname@orig` and afterwards `poolname@incr` (as I understand your reproducer) you _should_ get an error on `zfs send -i poolname@incr poolname@orig`, as @incr is after @orig (and it should be the other way around):

```
# zfs create data/test
# zfs snapshot data/test@a
# zfs snapshot data/test@b
# zfs send -i data/test@b data/test@a > /dev/null
warning: cannot send 'data/test@a': not an earlier snapshot from the same fs
```
Please check your reproducer and post the full chain of commands you actually ran.

Should you not get an error message when doing the send on the root dataset (which should not be used to hold data anyway, as of its limitation that it can not be destroyed, renamed or received) _then_ you would have found a bug.
