### ISSUE TITLE
Unable to remove any device from special after adding one device of different physical sector size

### ISSUE THREAD

**Issue by kftsehk** [openzfs/zfs#15352]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	|
Kernel Version	| 6.1.55-1-lts
Architecture	| x64
OpenZFS Version	| zfs-2.1.13-1

### Describe the problem you're observing

Able to add top level device of different sector size to `special` device, but unable to remove any (both new and existing) afterwards.

### Describe how to reproduce the problem

```
My pool:
        NAME          STATE     READ WRITE CKSUM
        brick         ONLINE       0     0     0
          mirror-0    ONLINE       0     0     0
            sda       ONLINE       0     0     0
            sde       ONLINE       0     0     0  (resilvering)
        special
          sdb         ONLINE       0     0     0  # SSD, sector size: logical 512/physical 512
          sdd         ONLINE       0     0     0 # HDD, sector size: logical 512/physical 4096
        cache
          nvme0n1p3   ONLINE       0     0     0
```

```
sudo zpool add brick special /dev/sdb
sudo zpool add brick special /dev/sdd

# both command runs successfully despite different sector size, resulting in the above config
```

`sudo zpool remove brick /dev/sdd`
```
cannot remove /dev/sdd: invalid config; all top-level vdevs must have the same sector size and not be raidz.
```
`sudo zpool remove brick /dev/sdb`
```
cannot remove /dev/sdb: invalid config; all top-level vdevs must have the same sector size and not be raidz.
```

### Include any warning/errors/backtraces from the system logs

No related log/errors from dmesg / zpool events, welcome any command suggestion I will edit to attach

**Comment by rincebrain** [comment]
Yes, that's expected.

>              Top-level vdevs can only be removed if the primary pool storage does not contain a top-level raidz vdev, all top-level vdevs have the same sector size, and the keys for all encrypted datasets are loaded.

- `zpool-remove(8)`

You can request that be changed as a feature, but it's currently behaving as expected.

**Comment by kftsehk** [comment]
I am sorry but, maybe I have some confusion with what top level dev or sector size refers to.

I am able to 
- create a new pool
- populated the special dev with few hundred MBs of 4K-96K random data files
- attach HDD `/dev/sde1` as mirror of `/dev/sdc`, and remove it afterwards
- add HDD `/dev/sde1` as primary vdev, and remove it afterwards
here is the timestamped evidence, shows on this new pool, physical sector size seem not blocking the above operations.

`/dev/sde`

```
$ sudo smartctl -a /dev/sde                                                                       
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.1.55-1-lts] (local build)                                             
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Toshiba MG08ACA... Enterprise Capacity HDD                                                        
Device Model:     TOSHIBA MG08ACA16TE
Serial Number:    81P0A0LGFWTG
LU WWN Device Id: 5 000039 b18db5c57
Firmware Version: 4303
User Capacity:    16,000,900,661,248 bytes [16.0 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database 7.3/5528
ATA Version is:   ACS-3 T13/2161-D revision 5
SATA Version is:  SATA 3.3, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Oct  5 10:50:43 2023 HKT
SMART support is: Available - device has SMART capability.                                                          
SMART support is: Enabled
```

`/dev/sdc`
```
$ sudo smartctl -a /dev/sdc                                                                       
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.1.55-1-lts] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org
                                                                                                                    
=== START OF INFORMATION SECTION ===                                                                                
Model Family:     Samsung based SSDs
Device Model:     Samsung SSD 860 EVO 500GB
Serial Number:    S3YANB0M393704W
LU WWN Device Id: 5 002538 e40e9818d
Firmware Version: RVT02B6Q
User Capacity:    500,107,862,016 bytes [500 GB]                                                                    
Sector Size:      512 bytes logical/physical                                                                        
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches                                                                                        
TRIM Command:     Available, deterministic, zeroed
Device is:        In smartctl database 7.3/5528
ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Oct  5 10:51:30 2023 HKT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

![image](https://github.com/openzfs/zfs/assets/20808792/eeccc12e-3001-4a0d-b898-98cb3588e5e9)
![image](https://github.com/openzfs/zfs/assets/20808792/6b7946da-d47f-43cf-819e-3da9903085c7)
![image](https://github.com/openzfs/zfs/assets/20808792/0ab6bd32-d00e-4e1a-ada3-8124e74e9ca2)
![image](https://github.com/openzfs/zfs/assets/20808792/1bdff9d1-fbaa-48e9-bf77-066e4aaddb85)

**Comment by rincebrain** [comment]
I would suggest you look at what the ashift on each vdev in that pool is. I would bet that they're all the same number, probably 12.

**Comment by kftsehk** [comment]
@rincebrain thanks for your kind suggestion, you are right
I am not aware that one of the SSD had automatically set to ashift=9 while all other has 12 in previous pool. I guess it will be very hard if not impossible to implement such feature to migrate data between different ashift, maybe I will close this issue instead of make it a feature request.

**Comment by amotin** [comment]
I would guess removal of vdev with ashift=12 should not be a problem, while with ashift=9 may be impossible, or at least depend.

**Comment by kftsehk** [comment]
@amotin no, in my case both vdev in special cannot be removed

**Comment by amotin** [comment]
I didn't mean it works now, only that it should be possible theoretically. ;)

**Comment by rincebrain** [comment]
Both are doable, theoretically - after all, a certain other company implemented it in their closed source product.

It'd be a pain, but I think it's not impossible to implement in theory.

**Comment by amotin** [comment]
I don't see how could you evacuate the data from device with ashift=9 to device with ashift=12.  You would get error either immediately during removal or at very later on attempt to access the data at sub-logical-sector offsets.

**Comment by rincebrain** [comment]
I have no insight into how that company implemented it, though I have a few ideas how I'd do it, I just have been told that their implementation does not suffer from these constraints.
