### ISSUE TITLE
srpm build failing with bash completion location complaints

### ISSUE THREAD

**Issue by adamdmoss** [openzfs/zfs#15355]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu 22.04.3 LTS 
Distribution Version	| Ubuntu 22.04.3 LTS
Kernel Version	| 6.5.0-1003-oem
Architecture	| x64
OpenZFS Version	| git master

### Describe the problem you're observing
Since approximately eb955f6e930e2516bbc4c569f33b5314835c45b6 a `--with-config=srpm` build fails for me like so:
```
+ /usr/lib/rpm/brp-remove-la-files
Processing files: zfs-2.2.99-308_g621fe1260.x86_64
error: File not found: /tmp/zfs-build-adam-KVjzreNT/BUILDROOT/zfs-2.2.99-308_g621fe1260.x86_64/etc/bash_completion.d/zfs


RPM build errors:
    File not found: /tmp/zfs-build-adam-KVjzreNT/BUILDROOT/zfs-2.2.99-308_g621fe1260.x86_64/etc/bash_completion.d/zfs
make[1]: *** [Makefile:14265: rpm-common] Error 1
```
### Describe how to reproduce the problem
A have a stabby workaround PR at https://github.com/openzfs/zfs/pull/15354

**Comment by siv0** [comment]
Thanks for the report!  I managed to reproduce it.

Issue was not noticed because I did not test the patch with building rpms on a debian-derived distro (which is also what `make deb` is doing).

I'll try to come up with a fix.

**Comment by siv0** [comment]
opened https://github.com/openzfs/zfs/pull/15365
