### ISSUE TITLE
"failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [openzfs/zfs#15369]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| Latest
Kernel Version	| 6.4.10
Architecture	| x64	
OpenZFS Version	| 2.2.0-rc4

### Describe the problem you're observing

Mounting ZFS filesystems fails with
`failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory`

Further mount attempts may fail with
`cannot mount '<dataset>': filesystem already mounted`

And `zpool export -f <pool>`
results in
`cannot unmount '<dataset>': no such pool or dataset`

### Describe how to reproduce the problem

`zfs mount -a`

### Include any warning/errors/backtraces from the system logs
Can be provided upon request indicating what particular log is needed.

**Comment by elementc** [comment]
Noticed the same error message when performing a `zfs mount -a` following upgrading from ubuntu 23.04 to 23.10:
```
failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory
```
Curiously, the command exits cleanly (exit code 0) and the expected mount actions actually occur.

Happy to provide further context from my end too!

```
casey on WATERFALCON in ~ 
at 22:32:02 🍀 zfs --version
zfs-2.2.0~rc3-0ubuntu4
zfs-kmod-2.2.0~rc3-0ubuntu4

casey on WATERFALCON in ~ 
at 22:32:06 🍀 uname -a
Linux WATERFALCON 6.5.0-9-generic #9-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct  7 01:35:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

casey on WATERFALCON in ~ 
at 22:32:10 🍀 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

**Comment by camj2** [comment]
I'm experiencing the same issue on my Void Linux machine. Linux 6.5.8, ZFS 2.2.0. Everything boots fine and works as expected. The error is printed twice on tty1 every boot though since ZFS 2.2.0.
