### ISSUE TITLE
Some file files not listed on site http://download.zfsonlinux.org/ (but able to download).

### ISSUE THREAD

**Issue by HunsGrubber** [openzfs/zfs#15425]
Problem with site http://download.zfsonlinux.org
Im truing to download repository for offline use:
wget --no-parent --reject html -r http://download.zfsonlinux.org/epel/8/x86_64/
Looks ok but  yum update trow error about missing files.
For example files: 4572378bbe19cf6d543529552f479646f7ff4e0ac6e4bd2d14a078c75604a17b-primary.xml.gz
7769721b6abf1afd998dbeff61d384cb1e6ed03713e12b4b9a50d678e6d45f9e-filelists.xml.gz
But it is possible to download this files directly:
wget http://download.zfsonlinux.org/epel/8/x86_64/repodata/4572378bbe19cf6d543529552f479646f7ff4e0ac6e4bd2d14a078c75604a17b-primary.xml.gz

Possible index.html not updated or problem with autoindex feature.

**Comment by tonyhutter** [comment]
The index.html files needed to be refreshed.  I just refreshed them, so it should be good now.  I also updated our internal scripts to auto-refresh them when we copy the new release RPMs to s3, so this should no longer be an issue going forward.
