### ISSUE TITLE
Builds for Ubuntu dont seem right (Version mismatch)

### ISSUE THREAD

**Issue by EngineLessCC** [openzfs/zfs#15461]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu 22.04
Distribution Version	| 22.04.3
Kernel Version	| 5.15.0-87-generic
Architecture	| x86_64
OpenZFS Version	| 2.2.0 .. and 2.1.5??

### Describe the problem you're observing

After building (and reboot) 2.2.0 i noticed `zpool version` shows mismatching entries:
- zfs-2.2.0-1
- zfs-kmod-2.1.5-1ubuntu6~22.04.1

Why does the kmod show version 2.1.5?
apt shows ive installed 2.2:

libzfs5/now 2.2.0-1 amd64 [installed,local]
zfs-dkms/now 2.2.0-1 amd64 [installed,local]
zfs/now 2.2.0-1 amd64 [installed,local]

### Describe how to reproduce the problem

- Download latest release from github
- sh autogen.sh
- ./configure
- make -s -j12 deb
- apt install ./libnvpair3_2.2.0-1_amd64.deb ./libzfs5_2.2.0-1_amd64.deb ./libuutil3_2.2.0-1_amd64.deb ./libzpool5_2.2.0-1_amd64.deb ./zfs_2.2.0-1_amd64.deb ./zfs-dkms_2.2.0-1_amd64.deb

### Include any warning/errors/backtraces from the system logs
n/a

**Comment by EngineLessCC** [comment]
Im not sure if this is an ubuntu or zfs repo issue, but:
manually doing:

- dkms build -m zfs -v 2.2.0
- dkms install -m zfs -v 2.2.0

resolves this mismatch, but this shouldnt be done manually, dkms should automatically choose the correct module.

**Comment by amigatomte** [comment]
The zfs-dkms package is broken. See https://github.com/openzfs/zfs/issues/15328#issuecomment-1739826420
`/usr/lib/dkms/common.postinst zfs 2.2.0` fixed it for me.

**Comment by AllKind** [comment]
@EngineLessCC 
You really should NOT use zfs v. 2.2.0! Heavy data corruption bugs in that one!
I strongly recommend to use 2.2.3. There the dkms install routine is also fixed.
