### ISSUE TITLE
The size of the file created by the `dd` command is incorrect.

### ISSUE THREAD

**Issue by shivabohemian** [openzfs/zfs#15480]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11
Kernel Version	| 5.10.110
Architecture	| arm64
OpenZFS Version	| 2.2.0

### Describe the problem you're observing
When I create a file using `dd` command, like that `dd if=/dev/zero of=file.img bs=2G count=1`, the size of the file is always 512 bytes.
<img width="295" alt="截屏2023-11-02 10 03 09" src="https://github.com/openzfs/zfs/assets/39078424/9d4d3c37-ba11-47b3-a528-26e67b873379">

### Describe how to reproduce the problem
1. Create a simple zpool. `zpool create -f test sda sdb`
2. Create a big file using `dd` command. `dd if=/dev/zero of=file.img bs=2G count=1`
3. Now you can check the size of the file using `du -sh *`

### Include any warning/errors/backtraces from the system logs
None.

**Comment by amotin** [comment]
By default pool has compression enabled, and you are writing all zeroes. What exactly disk usage to you expect to see?

**Comment by robn** [comment]
Its because you're using `/dev/zero`. ZFS sees a big run of zeroes and stores a "hole", which is kinda just saying "there are 2G of zeroes here".

Try `/dev/random` instead, to get real non-zero bytes. That will show you more what you expect.

**Comment by shivabohemian** [comment]
Got it~ I did not notice that `compression` was enabled by default in version 2.2.0, and it was disabled by default in 2.1.12. So there's a difference between them.

**Comment by gdevenyi** [comment]
Probably should use /dev/urandom otherwise you'll exhaust your entropy and the write will take forever
