### ISSUE TITLE
Fedora 39 repo

### ISSUE THREAD

**Issue by edgan** [openzfs/zfs#15483]
Please make a Fedora 39 repository.

**Comment by edgan** [comment]
I have successfully recompiled the zfs-2.2.0-1.fc38.src.rpm on a Fedora 39 system, and I am now using it.

**Comment by vishusandy** [comment]
Since no instructions were posted I'll post what I used to get zfs working after upgrading to fedora 39

```
sudo -i

sudo dnf install --skip-broken epel-release gcc make autoconf automake libtool rpm-build kernel-rpm-macros libtirpc-devel libblkid-devel libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel libattr-devel elfutils-libelf-devel kernel-devel-$(uname -r) kernel-abi-stablelists-$(uname -r | sed 's/\.[^.]\+$//') python3 python3-devel python3-setuptools python3-cffi libffi-devel ncompress
sudo dnf install --skip-broken --enablerepo=epel --enablerepo=powertools python3-packaging dkms

cd /usr/local/src
git clone https://github.com/zfsonlinux/zfs.git
cd zfs
./autogen.sh
./configure
make -j1 rpm-utils rpm-dkms
sudo yum localinstall *.x86_64.rpm *.noarch.rpm
```

I followed the instructions from https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html#rhel-centos-and-fedora for DKMS.
I had to substitute the last line (that should have been `sudo yum localinstall *.$(uname -p).rpm *.noarch.rpm`) with `sudo yum localinstall *.x86_64.rpm *.noarch.rpm`, but after that I rebooted and it worked.  It did say the transaction failed but it didn't seem to matter.

**Comment by Alexandero89** [comment]
With the last release when there was no 38 repo, it simply worked to take the packages of the 37 repo.
Doesn't that work this time?

Specifically, it is in the file /etc/yum.repos.d/zfs.repo.
The file looks something like this:
```
[zfs]  
name=ZFS on Linux for Fedora $releasever  
baseurl=http://download.zfsonlinux.org/fedora/$releasever/$basearch/  
  
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-openzfs
```
There then simply replace
`baseurl=http://download.zfsonlinux.org/fedora/$releasever/$basearch/`
with 
`baseurl=http://download.zfsonlinux.org/fedora/38/$basearch/`
and you're done.

You should of course change it again later as soon as there is an official 39 repo.

**Comment by edgan** [comment]
Here is the gist of what I did:
```
sudo -i
dnf -y groupinstall "Development Tools"
dnf -y install rpm-build wget
wget http://download.zfsonlinux.org/fedora/38/SRPMS/zfs-2.2.0-1.fc38.src.rpm
rpm -i zfs-dkms-2.2.0-1.fc38.src.rpm
dnf install libaio-devel libattr-devel libblkid-devel libffi-devel libtirpc-devel libudev-devel libuuid-devel ncompress openssl-devel python3-cffi python3-devel python3-packaging python3-setuptools
cd rpmbuild/SPECS
rpmbuild -bb zfs.spec
cd ../RPMS/x86_64
rpm -U libzfs5-2.2.0-1.fc39.x86_64.rpm zfs-2.2.0-1.fc39.x86_64.rpm
```

This was done on a server that was upgraded from Fedora 38 to 39, and already had zfs-dkms installed from 38.

`rpm -qa | grep zfs | sort`:
```
libzfs5-2.2.0-1.11.fc39.x86_64
zfs-2.2.0-1.11.fc39.x86_64
zfs-dkms-2.2.0-1.fc38.noarch
zfs-release-2-3.fc38.noarch
```
```

You could add this to be more complete:
```
sudo -i
wget http://download.zfsonlinux.org/fedora/38/SRPMS/zfs-dkms-2.2.0-1.fc38.src.rpm
rpm -i zfs-dkms-2.2.0-1.fc38.src.rpm
cd rpmbuild/SPECS
SOURCE_DATE_EPOCH=`date +%s` rpmbuild -bb zfs-dkms.spec
cd ../RPMS/noarch
dnf install zfs-dkms-2.2.0-1.fc39.noarch.rpm
```

**Comment by tonyhutter** [comment]
Thanks all for being patient.  Fedora 39 packages are out now:
```
sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-4$(rpm --eval "%{dist}").noarch.rpm
```

**Comment by MynaITLabs** [comment]
FYI, Fedora 39 for 2025 March  (dnf updated). Note version updates
# sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-6$(rpm --eval "%{dist}").noarch.rpm
`
Last metadata expiration check: 0:00:12 ago on Fri 14 Mar 2025 03:09:45 PM PDT.
[MIRROR] zfs-release-2-6.fc39.noarch.rpm: Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
[MIRROR] zfs-release-2-6.fc39.noarch.rpm: Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
[MIRROR] zfs-release-2-6.fc39.noarch.rpm: Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
[MIRROR] zfs-release-2-6.fc39.noarch.rpm: Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
[FAILED] zfs-release-2-6.fc39.noarch.rpm: Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
Status code: 404 for https://zfsonlinux.org/fedora/zfs-release-2-6.fc39.noarch.rpm (IP: 192.168.100.6)
`
# sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-5$(rpm --eval "%{dist}").noarch.rpm
`
Last metadata expiration check: 0:08:24 ago on Fri 14 Mar 2025 03:03:45 PM PDT.
zfs-release-2-5.fc39.noarch.rpm                                                                                                                        218 kB/s |  13 kB     00:00
Dependencies resolved.
=======================================================================================================================================================================================
 Package                                      Architecture                            Version                                      Repository                                     Size
=======================================================================================================================================================================================
Installing:
 zfs-release                                  noarch                                  2-5.fc39                                     @commandline                                   13 k

Transaction Summary
=======================================================================================================================================================================================
Install  1 Package

Total size: 13 k
Installed size: 6.1 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                               1/1
  Installing       : zfs-release-2-5.fc39.noarch                                                                                                                                   1/1
  Running scriptlet: zfs-release-2-5.fc39.noarch                                                                                                                                   1/1
  Verifying        : zfs-release-2-5.fc39.noarch                                                                                                                                   1/1

Installed:
  zfs-release-2-5.fc39.noarch

Complete!

`
```
