### ISSUE TITLE
Support RHEL 9.3

### ISSUE THREAD

**Issue by tjikkun** [openzfs/zfs#15525]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| RHEL
Distribution Version	| 9.3
Kernel Version	| 5.14.0-362.8.1.el9_3
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.13 / zfs-2.2.0

### Describe the problem you're observing
RHEL & AlmaLinux 9.3 were released last week. A rebuild of the kmod packages is needed.

**Comment by shodanshok** [comment]
Same issue on Rocky 9.3 x86_64

Trying to force-load the module via `insmod` results in `zfs: disagrees about version of symbol module_layout`

**Comment by tmzullinger** [comment]
It looks like builds for 9.3 were pushed earlier this week.  `kmod-zfs-2.1.13-2.el9` and `kmod-zfs-2.2.1-1.el9` are both built for `kernel-5.14.0-362.8.1.el9_3.x86_64`.

**Comment by PeterFalken** [comment]
I only see `kmod-zfs-2.1.13-2.el9` for 9.3 listed at http://download.zfsonlinux.org/epel/9/kmod/x86_64/
I might be missing something.

**Comment by tmzullinger** [comment]
The zfs 2.2 packages are still in the testing repo.  2.2 is still pretty new and most folks running large filesystems aren't the adventurous types. :)

**Comment by necouchman** [comment]
Yeah, based on some of the more critical issues being sorted out in 2.2.x, and the fact that the EL-based distros (RHEL/CentOS/Rocky/etc.) value stability over cutting/bleeding edge, I'd say it's better that way.
