### ISSUE TITLE
Possible bug: zstd-11 compressed data larger than zstd-10

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#15673]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| arch
Distribution Version	| current
Kernel Version	| 6.6
Architecture	| x64
OpenZFS Version	| 2.2.2

### Describe the problem you're observing

Sending data from a pool made on ZFS 2.1 to a new 2.2.2 pool where the source compression is ZSTD-10 and target is ZSTD-11 produces a bigger dataset on the target pool despite both of them being single VDEV 4T NVMEs. Only difference is the old pool is 512b and the new one is 4k. What's even more strange is that the new pool only gets the _last_ snapshot but the old one has prior snaps.

### Include any warning/errors/backtraces from the system logs
```
NAME                              USED  LUSED  RATIO  COMPRESS
targetpool/images                      185G   121G  1.06x  zstd-11
targetpool/images/arch                14.6G  14.7G  1.01x  zstd-11
```
vs
```
NAME                                        USED  LUSED  RATIO  COMPRESS
sourcepool/images                                109G   160G  1.49x  zstd-10
sourcepool/images/arch                          22.3G  22.5G  1.01x  zstd-10
```

**Comment by sempervictus** [comment]
@gmelikov: sorry, there's nothing really to record though since its just as simple as the explanation in the description: `zfs snap sourcepool/images@export ; zfs send sourcepool/images@export|zfs recv -vFu targetpool/images` and same for every underlying dataset. No `-R` or similar recv-side machinations involved; crypto not in-play (dm-crypt underneath).

**Comment by rincebrain** [comment]
Not a bug in two ways.

First, sometimes the compression can just be worse because they're a bunch of different compression algorithms under the hood and sometimes the presets will work better at 10 than 11, or whatever.

But what I think is actually biting you is that ashift 12 is crap for compression efficiency, particularly on anything with small recordsize, where the difference between "compressing from 4k to 3.5k" and "incompressible" matters quite a lot more often.

**Comment by ryao** [comment]
@rincebrain's explanation is correct. I do not think this is a bug either.

**Comment by sempervictus** [comment]
Thanks folks, appreciate the explanation. Was thinking along the lines of "ZSTD is deterministic based on load/time available" so maybe my system was just more busy from the decompression of send to efficiently compress recv.

**Comment by rincebrain** [comment]
That's not it at all.

It doesn't scale up or down the compression based on load, and while I believe the allocator can fragment writes if it's under significant pressure, that's after the compressor ever saw the data.

If you apply the same data, regardless of whether your load is no cores or 5x the total cores, it should produce the same compressed result.

**Comment by sempervictus** [comment]
Read you re the 4k thing, seems to bite in a variety of ways in terms of RAIDZ space and compression :-\. Unfortunately block sizes are only going up so probably merits an architectural solution at some point to make better use of the _type_ of space available (hell, if using object stores that becomes 64M).

**Comment by rincebrain** [comment]
I'm not sure there is an easy answer for it. There's kind of a fundamental tradeoff in terms of size of modification versus minimum write size, so even if you did something like a log data structure to group changes, you'd then need something like lifetime tracking or you'd still have to modify huge chunks at once eventually in exchange for better compression savings with the larger minimum size.
