### ISSUE TITLE
REMAKE_INITRD is required but deprecated for Root on ZFS

### ISSUE THREAD

**Issue by Zocker1999NET** [openzfs/zfs#15706]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Debian GNU/Linux
Distribution Version	|  Bookworm
Kernel Version	|  6.1.0-16
Architecture	|  arm64
OpenZFS Version	|  2.1.11-1

### Describe the problem you're observing

The documentation on https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bookworm%20Root%20on%20ZFS.html is not applicable anymore. It proposes to add `REMAKE_INITRD=yes` to `/etc/dkms/zfs.conf`, so that after ZFS is upgraded, the initramfs is updated to contain the new module. Otherwise, a system with root on ZFS will fail to boot (see #10355).
However, this feature is deprecated and even seems to issue errors in future versions of dkms (as why the default `REMAKE_INITRD=no` was removed from zfs in #12781).

For me, it seems `REMAKE_INITRD=yes` seems to be still effective, at least my initramfs gets updated afterwards and my system still boots after an update. However, I have following question regarding future ZFS on root setups. Might there be already something else active for when `REMAKE_INITRD=yes` is not effective anymore?
If not, something of that sort needs to be added to the documentation, otherwise, as I understand it, systems will not be able after an update of the kernel & zfs-dkms without manually triggering an update of the initramfs.

### Describe how to reproduce the problem

* follow the ZFS on root documentation for Debian bookworm
* after `REMAKE_INITRD=yes` is set and the zfs module is updated, dkms issues “Deprecated feature: REMAKE_INITRD (/etc/dkms/zfs.conf)”

**Comment by eduncan911** [comment]
I don't want to be the "me too" person, but this has been a serious pain in the arse since I moved to ZFS as Root on all our house machines. 

Only recently have I found this miraculous config option that has save oh so many all nighters of fixing the kiddos homework machine.

If it's still effective, turn perhaps a module or script is still being triggered?

**Comment by rlaager** [comment]
Sorry, I didn't see this until now (a year later!). Since this is an issue with the docs, I'm going to close this in favor of openzfs/openzfs-docs#534. (I don't think it's possible to move issues even if I wanted. But since that one has been filed, I'll just use that.)
