### ISSUE TITLE
Slot power control breaks build on FreeBSD

### ISSUE THREAD

**Issue by mmatuska** [openzfs/zfs#15709]
a9520e6e5 breaks build on FreeBSD, as zpool_disk_wait() has not been implemented for FreeBSD

In addition, zpool_power_current_state() and zpool_power() should include (void) lines to suppress unused parameter warnings.

### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| main (freebsd/freebsd-src@9bf957fc9)
Kernel Version	| freebsd/freebsd-src@9bf957fc9
Architecture	| amd64
OpenZFS Version	| zfs-2.2.99-279-g233d34e47

### Describe the problem you're observing
OpenZFS cannot be build, as the FreeBSD implementation of  zpool_disk_wait() introduced in a9520e6e5 is missing.

### Describe how to reproduce the problem
Try to build OpenZFS

**Comment by mmatuska** [comment]
@tonyhutter @behlendorf it would be great to to test at least building on both Linux and FreeBSD before doing commits.

**Comment by rincebrain** [comment]
It should, but it appears sometime in the last couple days [the FreeBSD 13-stable builder stopped running things](https://build.openzfs.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29) for some reason, since it reported a failure on #15695...

**Comment by tonyhutter** [comment]
Yea, looks like buildbot was messed up.  I just re-strarted it.  Hopefully that and #15716 will get things back to normal.

**Comment by rincebrain** [comment]
Is there any way we could modify the config so the buildbot failing to report any FBSD tests fails closed, e.g. and blocks the PR merge, rather than failing open?

**Comment by mmatuska** [comment]
Fixed in 07e95b4670dc421ec726a2b4efa97a22fe572005 #15716
