### ISSUE TITLE
Discourage ashift=0

### ISSUE THREAD

**Issue by crawsome** [openzfs/zfs#15750]
### Describe the feature would like to see added to OpenZFS

During pool creation, would it be a good idea to discourage ashift=0? 
Maybe this can be done by querying the drive's ashift values automatically during creation, or simply warning the user about the setting. 

### How will this feature improve OpenZFS?

If ashift accuracy is ensured, this will scale-up to drive reliability and performance for all users, leading to longer drive retention, faster throughput, etc. This will also help users who are reading low-quality guides to get ZFS setup quickly. (Like myself)

### Additional context

Hopefully I'm in the right place. I wanted to start a discussion about an idea I had after I learned about ashift. 

My ashift was set to 0 by default. I read online that that's worst possible setting. `zpool create pool_name raidz1 drive1,drive2,drive3` gave me a default ashift value of 0. The drives are brand-new WD Red 20TB drives purchased a few days ago. 

It's possible I'm still doing something wrong but both my pools, created over a year apart are 0, though I didn't specifically set it. 

A typical user journey is googling the command syntax, and the guides don't take-into-account to set the ashift. [Your docs do though, hindsight is 20/20](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2022.04%20Root%20on%20ZFS.html) But even Ubuntu has a walkthrough that doesn't mention it, and even ChatGPT neglected to account for it when I asked. (I know it's a lesson in "read the docs" but I think a control would help, here too.)

I acknowledge it's possible my experience is anecdotal and there's something else I don't have right, but at the very least, if a pool is about to be initialized with ashift=0, I think it would be a nice-to-have to warn the user against it. Version below. 

```
zfs version
zfs-2.1.5-1ubuntu6~22.04.2
zfs-kmod-2.1.5-1ubuntu6~22.04.1

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

```

**Comment by rincebrain** [comment]
What?

The pool property `ashift` just overrides the default per-top-level-vdev property `ashift`'s existing autodetection of the drive's reported physical sector size.

Having it be `0` just means that it used the autodetection.

Setting it to `12` means you won't run into issues later if you move to 4kn/512e disks, but it also reduces space efficiency for small things, so that's why it's not a default.

**Comment by rincebrain** [comment]
You might have found [the documentation that explains everything I just said](https://openzfs.github.io/openzfs-docs/man/master/7/zpoolprops.7.html#ashift) useful to read before posting this.

**Comment by crawsome** [comment]
>the value 0 (the default) means to auto-detect using the kernel's block layer and a ZFS internal exception list.

That resolves that then. This can close. Thank you all for your time. 

Lessons learned, don't believe Google/Servfault/Reddit and I'll and search the docs for the definition next time.

**Comment by milahu** [comment]
> My ashift was set to 0 by default. I read online that that's worst possible setting.

the output of `zpool get` can be confusing
if you dont know that `ashift=0` means "use the physical block size"

the "worst possible setting" would be `ashift=1` &rarr; pool sector size: 2 bytes

you can get the actual `ashift` value with `zdb --config`

```
# zpool get ashift some_pool
NAME       PROPERTY  VALUE   SOURCE
some_pool  ashift    0       default

# zdb --config some_pool | grep -w ashift:
                ashift: 12

# python -c 'print(2**12)'
4096

# zdb --config some_pool | grep -w path:
                path: '/dev/sdb1'

# fdisk -l /dev/sdb | grep "^Sector size"
Sector size (logical/physical): 512 bytes / 4096 bytes

# cat /sys/block/sdb/queue/physical_block_size
4096
```
