### ISSUE TITLE
Corrupted atimes

### ISSUE THREAD

**Issue by ossimoi** [openzfs/zfs#15762]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Gentoo
Distribution Version	|2.14
Kernel Version	|6.6.11
Architecture	|x86_64
OpenZFS Version	|2.2.99-288_ga382e2119

### Describe the problem you're observing
touching a file corrupts its atime.

```
# echo test > test  
# ls -lu
-rw-r--r-- 1 root root 5 Jan 12 05:01 test
# touch test
# ls -lu
-rw-r--r-- 1 root root 5 -72340172838076674 test
# stat -c%x test
-72340172838076674.-16843010
# cat test
test
# ls -lu
-rw-r--r-- 1 root root 5 Jan 12 05:02 test

```

**Comment by robn** [comment]
@ossimoi thanks for reporting this! My stupid mistake. Fixes posted in #15773 and #15774.
