### ISSUE TITLE
cp --reflink=always fails on Rocky Linux 9.3 with OpenZFS 2.2.2-2 & 2.2.2-1

### ISSUE THREAD

**Issue by hanneskasp** [openzfs/zfs#15867]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux 
Distribution Version	| 9.3
Kernel Version	|5.14.0-362.18.1.el9_3.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.2.2-2

### Describe the problem you're observing
Hello,
reflink seems to be not working on Rocky Linux 9.3 with OpenZFS 2.2.2-2 & 2.2.2-1

```
cp --reflink=always testfile link
cp: failed to clone 'link' from 'testfile': Operation not supported
```

I also see that the zpool information shows that block loning is not used.

```
zpool get all |grep clon
reflinktest bcloneused                     0                              -
reflinktest bclonesaved                    0                              -
reflinktest bcloneratio                    1.00x                          -
reflinktest feature@block_cloning          enabled                        local
```

If I do the same on Ubuntu 24.04 nightly build, then the cp command succeeds and the zpool information looks good
```
zpool get all |grep clon
backupszfs  bcloneused                     1K                             -
backupszfs  bclonesaved                    1K                             -
backupszfs  bcloneratio                    2.00x                          -
backupszfs  feature@block_cloning          active                         local

```

### Describe how to reproduce the problem
I followed the description from here https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html

```
dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
dnf config-manager --enable zfs-testing
dnf install -y epel-release
dnf install -y kernel-devel
dnf install -y zfs
zpool create reflinktest /dev/sdb
cp /etc/resolv.conf /reflinktest/testfile
cd /reflinktest
cp --reflink=always testfile link
cp: failed to clone 'link' from 'testfile': Operation not supported
```

### Include any warning/errors/backtraces from the system logs
I did not see anything obvious, but if you tell me what to do, then I can check

**Comment by amotin** [comment]
Block cloning was temporarily disabled in ZFS 2.2.2 due to number of bugs found. Upcoming 2.2.3 should fix all the know ones, but you still need to allow it via zfs_bclone_enabled module parameter for now, just to be safe at this point.

**Comment by hanneskasp** [comment]
wow, that was a fast answer :-) 

thanks, then we will check again with 2.2.3 once it's available
