### ISSUE TITLE
bash completion support

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#1588]
I imported bash-completion support from ZFS-FUSE about a year ago in response to a Gentoo bug report:

http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-fs/zfs/files/bash-completion?revision=1.1&view=markup
https://bugs.gentoo.org/show_bug.cgi?id=402979

ZFS-FUSE never advanced past pool version 26; I suspect that this file was created against an even earlier pool version. It would be nice if someone updated this against the modern ZFSOnLinux code and did the prerequisite work to get it merged. I have noticed that issues that  file for low priority things have been fixed by other volunteers, so I am filing this with them in mind. This is a low priority for me, although it is something that I think many people would enjoy.

**Comment by mailinglists35** [comment]
When I install with dkms, I get bash completion; when I install from git zip, I don't. It would be useful to automaticallt get bash completion in the second case, too.

**Comment by behlendorf** [comment]
@mailinglists35 the `contrib/bash_completion.d/zfs` bash completions file just needs to be installed on your system, usually this is under `/etc/bash_completion.d/`.
