### ISSUE TITLE
Unusably slow read speeds and normal write speeds on encrypted dataset with ZFS 2.2.3

### ISSUE THREAD

**Issue by ChordMankey** [openzfs/zfs#16016]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 39
Kernel Version	| 6.7.9-200.fc39
Architecture	| x86_64 (64-bit)
OpenZFS Version	| 2.2.3-1

### Describe the problem you're observing
I am workng with a pool of 5 10TB  drives (mounted in an external enclosure connected via USB) in a RAID-Z2 configuration, with a dataset with default native encryption (further details in how to reproduce section). Here I am faced with writes in the 200 MB/s range while reads are in the 10 to 20 MB/s range with constant hanging to the point where I can't access the files that I moved into the dataset. The files are mostly video files that I tested by either playing them or copying them out of the dataset and pool and observing. I didn't notice any unusual spikes in CPU or RAM usage.

I tried creating a non-encrypted dataset in the same pool to test and the read speeds were operational, so I think it's fair to say that encryption is what's causing the issue. I am new to ZFS and don't have a deep understanding of all the moving parts involved, but based on browsing other issues I was beginning to think whether it had something to do with AVX, but I get the following:
```shell
[username@fedora ~]$ cat /sys/module/zfs/parameters/zfs_vdev_raidz_impl
cycle [fastest] original scalar sse2 ssse3 avx2
```

In that regard, it might also be worth mentioning that I'm running on an AMD Ryzen 7 5800X. I will be happy to provide any further information that is needed, thanks in advance!

### Describe how to reproduce the problem
1. 
```shell
sudo zpool create mypool raidz2 drive1 drive2 drive3 drive4 drive5
sudo zfs create -o encryption=on -o keylocation=file:///key/path.key -o keyformat=passphrase mypool/mydataset
```
2. Copy some data into the dataset
3. Try to read copied files

### Include any warning/errors/backtraces from the system logs

No errors

**Comment by useranon350** [comment]
Have you tried running "zpool iostat -yr 1" while copying and reading the files to see how much of the IO is sync vs. async? Also, have you tried setting atime=off? My first instinct when weird file performances issue show up is that there might be something pathologically synchronous or read-modify-write going on somewhere.

If there aren't any spikes in CPU usage, I wouldn't expect the encryption to be the problem. Have you compared the performance vs. a non-encrypted dataset?

**Comment by ChordMankey** [comment]
Hi @useranon350, thanks for the reply. I tried reading a video file with `zpool iostat -yr 1` running for both an encrypted and non-encrypted dataset with the following results:

```
Non-encrypted:

z2hgstext     sync_read    sync_write    async_read    async_write      scrub         trim         rebuild  
req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
512             0      0      0      0      0      0      0      0      0      0      0      0      0      0
1K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
2K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
4K              2      0      0      0      0      0      0      0      0      0      0      0      0      0
8K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
16K            11      0      0      0     15      0      9      0      0      0      0      0      0      0
32K            21      0      0      0     39      2    940      0      0      0      0      0      0      0
64K             0      0      0      0      0     10      0    135      0      0      0      0      0      0
128K            0      0      0      0      0     28      0    228      0      0      0      0      0      0
256K            0      0      0      0      0      1      0    170      0      0      0      0      0      0
512K            0      0      0      0      0      0      0     59      0      0      0      0      0      0
1M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
2M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
4M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
8M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
16M             0      0      0      0      0      0      0      0      0      0      0      0      0      0
------------------------------------------------------------------------------------------------------------


Encrypted:

z2hgstext     sync_read    sync_write    async_read    async_write      scrub         trim         rebuild  
req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
512             0      0      0      0      0      0      0      0      0      0      0      0      0      0
1K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
2K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
4K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
8K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
16K             0      0      0      0      0      0      0      0      0      0      0      0      0      0
32K             5      0      0      0     48      0      0      0      0      0      0      0      0      0
64K             0      0      0      0      0     10      0      0      0      0      0      0      0      0
128K            0      0      0      0      0     12      0      0      0      0      0      0      0      0
256K            0      0      0      0      0      0      0      0      0      0      0      0      0      0
512K            0      0      0      0      0      0      0      0      0      0      0      0      0      0
1M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
2M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
4M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
8M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
16M             0      0      0      0      0      0      0      0      0      0      0      0      0      0
------------------------------------------------------------------------------------------------------------
```

It fluctuates from the above, to going all zeros on both the encrypted and non-encrypted datasets, but in the case of the encrypted one the video hangs when everything goes zero. In the case of the non-encrypted dataset, the video continues playing without issue even when everything goes 0.

`atime` was on but I tried turning it off but observed no noticeable change unfortunately. I'm at a loss for what the issue is and would really like to figure this out as I can no longer even get the data in the encrypted dataset out.

**Comment by Haravikk** [comment]
Did you create the pool using v2.2.3?

I've been having a long running issue with poor performance every time I try to upgrade beyond v2.1.0; if possible you should try that version to see if it gives you more consistent performance, however it's likely you won't be able to use your existing pool(s) if they were created under v2.2.3, as they'll have features enabled that v2.1.0 doesn't support.

But if you are able to confirm that it's the same issue (newer versions run poorly) it could be helpful, especially since you seem to have narrowed it down to poor encryption performance.

In my own case I've tested every combination of hardware accelerated implementations (anything you can select via an option found under `sysctl -a | grep '_impl:') and found that none of these makes any difference to the performance, so whatever the problem is it's somewhere else within the ZFS code, and has been introduced somewhere after v2.1.0.

**Comment by ChordMankey** [comment]
Hi @Haravikk, Yes I did use v2.2.3 to create the pool. At this stage I'm willing to cut my losses and give up on the data in the pool if I can just get native encryption working with reasonable read speeds on a lower version, although I'd prefer to not lose the data of course.

Although I don't think v2.1.0 will be an option for me as I'm running kernel v6.7 but I can try v2.1.15. I would be happy to try out this version although it's not very obvious how I can do this on Fedora using dnf, as it is I can't remove the exiting version of zfs as it's protected, I will continue looking into how to go ahead with this downgrade but if you have any insight on the best way to go about it that would be most appreciated.

To answer your next question, I initially only had one encrypted dataset and one non-encrypted one which I made purely to test whether the issue persists for non-encrypted as well. However I made another encrypted dataset today just to check whether the issue was dataset specific and the behavior was quite peculiar. As with the previous one, the write speeds were normal with the exception of a file copy operation into the dataset hanging stand-still for about a minute. And the read performance seemed normal for about 5 seconds before it completely hung on a copy operation out of the dataset following which I started getting the unusable speeds I mentioned in the original post. Long story short, I'm facing the issue in multiple encrypted datasets.

Btw is the issue you're facing also specific to encrypted datasets?

Finally, a few points that may add some additional context:
1. I tried running the command `sysctl -a | grep '_impl:'` and get no output, does this imply that I don't have any options for hardware acceleration?
2. I noticed that since installing zfs and setting up my pool and datasets, my boot time is significantly longer. I wonder whether there's possibly something silently going wrong during boot causing this issue.

**Comment by ChordMankey** [comment]
Regarding downgrading, I checked the repository using the following:
```shell
[username@fedora ~]$ dnf list zfs --showduplicates
Installed Packages
zfs.x86_64                                                                                                                          2.2.3-1.fc39                                                                                                                          @zfs
Available Packages
zfs.x86_64                                                                                                                          2.2.1-1.fc39                                                                                                                          zfs 
zfs.x86_64                                                                                                                          2.2.2-1.fc39                                                                                                                          zfs 
zfs.x86_64                                                                                                                          2.2.3-1.fc39                                                                                                                          zfs 
```

Which gives me the impression that the Fedora repository doesn't include v2.1.x

**Comment by Haravikk** [comment]
Sorry, ignore my mention of `sysctl`, that's how the macOS version of ZFS is configured; Linux does things differently.

It's possible that those of us having trouble on the macOS version may have just found a possible cause for our problem; since downgrading doesn't seem to be an option for you, you might want to try what we've done:

```
zfs set primarycache=none <pool>
zfs set secondarycache=none <pool>
```

(swapping for your own pool/root dataset name)

Telling ZFS to stop using ARC on macOS has just made my system **much** more responsive, though obviously the lack of caching is far from ideal (but the performance degradation has been way worse). You may need to do this for for additional datasets if you've tweaked these properties on any of them. If this makes no difference for you, then definitely set it back again (default is `=all`).

Sorry if this is derailing your issue, as it's possible the two are unrelated, but it sounded so similar to what I've been experiencing on macOS releases it seems worth a try to see if they might be the same, as it's possible the issue isn't macOS specific but merely affects macOS more severely/consistently.

**Comment by useranon350** [comment]
> Hi @useranon350, thanks for the reply. I tried reading a video file with `zpool iostat -yr 1` running for both an encrypted and non-encrypted dataset with the following results:
> 
> ```
> Non-encrypted:
> 
> z2hgstext     sync_read    sync_write    async_read    async_write      scrub         trim         rebuild  
> req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
> ----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
> 512             0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 1K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 2K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 4K              2      0      0      0      0      0      0      0      0      0      0      0      0      0
> 8K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 16K            11      0      0      0     15      0      9      0      0      0      0      0      0      0
> 32K            21      0      0      0     39      2    940      0      0      0      0      0      0      0
> 64K             0      0      0      0      0     10      0    135      0      0      0      0      0      0
> 128K            0      0      0      0      0     28      0    228      0      0      0      0      0      0
> 256K            0      0      0      0      0      1      0    170      0      0      0      0      0      0
> 512K            0      0      0      0      0      0      0     59      0      0      0      0      0      0
> 1M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 2M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 4M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 8M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 16M             0      0      0      0      0      0      0      0      0      0      0      0      0      0
> ------------------------------------------------------------------------------------------------------------
> 
> 
> Encrypted:
> 
> z2hgstext     sync_read    sync_write    async_read    async_write      scrub         trim         rebuild  
> req_size      ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg    ind    agg
> ----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
> 512             0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 1K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 2K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 4K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 8K              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 16K             0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 32K             5      0      0      0     48      0      0      0      0      0      0      0      0      0
> 64K             0      0      0      0      0     10      0      0      0      0      0      0      0      0
> 128K            0      0      0      0      0     12      0      0      0      0      0      0      0      0
> 256K            0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 512K            0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 1M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 2M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 4M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 8M              0      0      0      0      0      0      0      0      0      0      0      0      0      0
> 16M             0      0      0      0      0      0      0      0      0      0      0      0      0      0
> ------------------------------------------------------------------------------------------------------------
> ```
> 
> It fluctuates from the above, to going all zeros on both the encrypted and non-encrypted datasets, but in the case of the encrypted one the video hangs when everything goes zero. In the case of the non-encrypted dataset, the video continues playing without issue even when everything goes 0.
> 
> `atime` was on but I tried turning it off but observed no noticeable change unfortunately. `relatime` was also on but I imagine if switching `atime` off had no effect, the same would be the case for `relatime`. I'm at a loss for what the issue is and would really like to figure this out as I can no longer even get the data in the encrypted dataset out.

It looks like something is generating a ton of write activity when you are reading the files, to the point that the majority of the disk activity is taken up by writing in the non-encrypted case. Oddly, that isn't happening in the problematic encrypted case. There's definitely something weird going on.

Are you able to read the video files any faster on a second attempt? i.e. cat the file to /dev/null a few times to force into into the ARC (the ZFS cache), then try playing it. If the problem persists, it means the problem is occurring after the data is already read from the disks. If the problem disappears, then it means the problem is related to the disk reads.

You could also try making a dataset with "sync=always" to enforce synchronous write and test the encrypted vs. non-encrypted writes. Sync writes will definitely be worse than your current performance, but it will be interesting to see how they differ between encrypted and un-encrypted. It's possible whatever is causing the performance problems is only hidden on writes because ZFS is caching them in RAM and writing them out in sequential chunks, but the read workload is random IO. It *should* be prefetching sequential files like yours, but it's possible something is going wrong with that system.

You could also try adding "options zfs zfs_dmu_offset_next_sync=0" to your modprobe.d configs. I don't see why it would make a difference in your scenario, but many people have encountered weird performance problems in recent patches because that option started defaulting to 1.

**Comment by filip-paczynski** [comment]
Well, I don't know anything about ZFS encryption, but writes during read are somewhat suspicious.  
Also, there seem to be very little actual reads, so it is likely that it reads from ARC, or reads very slowly.
To observe read latencies use `zpool iostat -ql 1` or `zpool iostat -qlv 1` for per-disk latencies.
To observer ARC behaviour use `arcstat 1`

You might want to take a look at system log (for any disk read errors/bus resets etc.) and `zpool events` (for info on corrected on-disk cksum errors, if any - which may help to explain writes), maybe also use `smartctl` to do a long-online scan of each disk.
If it all seems fine, might check read perf of disk themselves by dd-ing them into null one by one:
`dd if=/dev/physical-disk of=/dev/null bs=128k status=progress`.

Might also benefit from [turning NCQ off](https://unix.stackexchange.com/questions/211550/how-to-really-disable-ncq-in-linux), or not.

> (mounted in an external enclosure connected via USB)  

Some of these are problematic - seen some threads here about them (especially UAS), however I don't use one, so can't contribute much.

In this case `smartctl` and `dd` probably I'd rather do **on exported pool**... just to avoid causing some timeouts and associated problems for ZFS.

**Comment by ChordMankey** [comment]
@Haravikk 
Unfortunately, bypassing ARC/caching made no difference to the read performance. And no worries I don't think this derails the issue since the symptoms are similar enough, and I'm open to trying whatever I can to resolve or at least figure out the issue.

**Comment by ChordMankey** [comment]
@useranon350 
I tried force caching the file as you suggested and while it takes about 20 minutes to actually cat the file to `/dev/null`, once that's done the file reads very fast as expected and I'm able to read/watch the cached video file without issue. I think with that experiment we can conclude that the issue is related to disk reads right?

I tried creating a new encrypted dataset with sync=always and write speeds are a lot slower at ~25MiB/s (not sure if this big of a hit is expected). However, reading is at a speed that is manageable where a video file can actually play and seek without a noticeable lag. Trying to actually copy a file out of the new dataset to quantifiably observe read speed, I got basically 1GiB/s read speed for a 5GiB file. I'm not sure if sync=always causes the file to be cached while writing it or something but I was not able to replicate this behaviour on my pre-existing dataset by updating the sync property using `sudo zfs set sync=always mypool/mydataset`. Although I didn't restart or anything after updating the sync property as I didn't know whether such action was required.

Next, for a new non-encrypted dataset with sync=always, the write speeds are similarly slow at ~30MiB/s and the read speeds are similarly fast.

**Comment by ChordMankey** [comment]
@filip-paczynski 
For context, here are some snippets from `zpool iostat -ql 1` in different scenarios, the lines of `.` signify long periods of inactivity (repeats of the lines before and after the dots) which happens constantly on the encrypted datasets to the point where there's more idling than actual reads.

Encrypted read with cache disabled (First run of `cat /mypool/mydataset/file.mkv > /dev/null`):

```
              capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub   trim  rebuild   syncq_read    syncq_write   asyncq_read  asyncq_write   scrubq_read   trimq_write  rebuildq_write
pool        alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait   wait   wait   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0      0      1      0      0      0      0      0      0      0      0
.
.
.
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0      0      1      0      0      0      0      0      0      0      0
mypool    564G  44.9T     53      0  1.85M      0  955ms      -  955ms      -  533ns      -  490ns      -      -      -      -      0      1      0      0      0      1      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0      0      1      0      0      0      0      0      0      0      0
.
.
.
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0      0      1      0      0      0      0      0      0      0      0
mypool    564G  44.9T     33      0  1.20M      0     1s      -     1s      -  676ns      -  708ns      -      -      -      -      0      1      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T     15      0   543K      0  626us      -  626us      -  628ns      -  537ns      -      -      -      -      0      2      0      0      0      1      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      2      0      0      0      1      0      0      0      0      0      0      0      0
```


Encrypted read with cache enabled (Second run of `cat /mypool/mydataset/file.mkv > /dev/null`):
```
              capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub   trim  rebuild   syncq_read    syncq_write   asyncq_read  asyncq_write   scrubq_read   trimq_write  rebuildq_write
pool        alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait   wait   wait   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      1      0      0      0    575      3      0      0      0      0      0      0      0      0
.
.
.
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      1      0      0      0    575      3      0      0      0      0      0      0      0      0
mypool    564G  44.9T    555      0  67.3M      0    36s      -  558ms      -    77s      -    35s      -      -      -      -      0      1      0      0    504      6      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0    504      6      0      0      0      0      0      0      0      0
.
.
.
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      1      0      0    504      6      0      0      0      0      0      0      0      0
mypool    564G  44.9T    223      0  26.2M      0    19s      -  808ms      -   25ms      -    19s      -      -      -      -      0      0      0      0    106      9      0      0      0      0      0      0      0      0
mypool    564G  44.9T    278      0  32.1M      0  322ms      -    3ms      -      -      -  319ms      -      -      -      -      0      0      0      0    914      9      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0    914      9      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0    914      9      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0    914      9      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0    914      9      0      0      0      0      0      0      0      0
```




Encrypted write:
```
              capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub   trim  rebuild   syncq_read    syncq_write   asyncq_read  asyncq_write   scrubq_read   trimq_write  rebuildq_write
pool        alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait   wait   wait   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ   pend  activ
----------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
.
.
.
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0    274      0  1.84M      -    2ms      -    1ms      -  434ns      -    1ms      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0    906      0  33.3M      -    1ms      -    1ms      -  724ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.35K      0  43.9M      -    1ms      -    1ms      -    3us      -    2ms      -      -      -      0      0      0      8      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.26K      0  48.1M      -    1ms      -    1ms      -  662ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.21K      0  46.1M      -    1ms      -    1ms      -  644ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.31K      0  49.9M      -    1ms      -    1ms      -  623ns      -      -      -      -      -      0      0      0     13      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0    885      0  33.0M      -    1ms      -    1ms      -  577ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.45K      0  47.8M      -    2ms      -    1ms      -    1us      -    5ms      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.25K      0  47.8M      -    1ms      -    1ms      -  649ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.20K      0  45.8M      -    1ms      -    1ms      -  665ns      -      -      -      -      -      0      0      0      8      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.26K      0  48.1M      -    1ms      -    1ms      -  667ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.28K      0  48.6M      -    1ms      -    1ms      -  754ns      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0  1.51K  3.99K  46.3M   12ms    2ms   12ms    1ms  768ns   11us      -    6ms      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0      0      0      0      -      -      -      -      -      -      -      -      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
mypool    564G  44.9T      0    297  3.99K  1.86M   12ms    3ms   12ms    1ms  768ns  403ns      -    2ms      -      -      -      0      0      0      0      0      0      0      0      0      0      0      0      0      0
```

The `zpool events` command shows a whole lot of `ereport.fs.zfs.delay`, I don't think those are checksum errors but the event log is absolutely littered with them so they're probably related? Would appreciate any further insight. Snippet below:
```
Mar 26 2024 02:16:28.210596056 ereport.fs.zfs.delay
Mar 26 2024 02:16:28.216596056 ereport.fs.zfs.delay
Mar 26 2024 02:16:28.239596054 ereport.fs.zfs.delay
Mar 26 2024 02:16:28.306596049 ereport.fs.zfs.delay
Mar 26 2024 02:16:28.326596047 ereport.fs.zfs.delay
Mar 26 2024 02:16:28.327596047 ereport.fs.zfs.delay
Mar 26 2024 02:16:58.947593775 ereport.fs.zfs.delay
Mar 26 2024 02:16:58.949593775 ereport.fs.zfs.delay
Mar 26 2024 02:16:58.968593773 ereport.fs.zfs.delay
Mar 26 2024 02:16:59.077593765 ereport.fs.zfs.delay
Mar 26 2024 02:16:59.084593765 ereport.fs.zfs.delay
Mar 26 2024 02:16:59.104593763 ereport.fs.zfs.delay
Mar 26 2024 02:16:59.106593763 ereport.fs.zfs.delay
Mar 26 2024 02:16:59.858593707 sysevent.fs.zfs.history_event
Mar 26 2024 02:17:00.010593696 sysevent.fs.zfs.config_sync
Mar 26 2024 02:17:00.010593696 sysevent.fs.zfs.pool_import
Mar 26 2024 02:17:00.011593696 sysevent.fs.zfs.history_event
Mar 26 2024 02:17:00.233593679 sysevent.fs.zfs.config_sync
Mar 26 2024 12:36:52.742327479 ereport.fs.zfs.delay
Mar 26 2024 12:36:52.743327478 ereport.fs.zfs.delay
Mar 26 2024 12:36:52.744327476 ereport.fs.zfs.delay
```

Regarding `smartctl`, I already ran slow tests on every drive before creating the zpool which reported back healthy. The SMART statistics also look all good for all the drives. Here's a snippet of the log from one of the drives:
```
SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%     38095         -
# 2  Extended offline    Interrupted (host reset)      20%     38070         -
# 3  Short offline       Completed without error       00%     37993         -
# 4  Vendor (0x70)       Completed without error       00%     37941         -
# 5  Vendor (0x71)       Completed without error       00%     37941         -
```

Regarding the external USB enclosure, I thought that issues originating from it are unlikely since the non-encrypted datasets work perfectly fine, unless of course there's something that I'm missing.

**Comment by ChordMankey** [comment]
Finally, I haven't had the time to try all the things mentioned in the comments but I figured I have enough findings to report back. These are the remaining tests that I need to try out:
- Try adding "options zfs zfs_dmu_offset_next_sync=0" to your modprobe.d configs.
 - Haven't messed around with modprobe yet so I need to read up and find out how to go about this first.
- Check read perf of disk themselves by dd-ing them into null one by one: `dd if=/dev/physical-disk of=/dev/null bs=128k status=progress`.
 - Having a bit of trouble with this one with the error `dd: failed to open '/dev/sdf': No such file or directory`, it seems to be expecting a directory as input, will look further into this.
 - I'm also not sure what you meant by exported pool but I imagine it involves a clone of some sort of the pool which unfortunately isn't possible for me cause I don't have spare storage for another test setup.
- Turning NCQ off
 - I don't know what this is and need to read up on it and try it when I have some time.

**Comment by rrevans** [comment]
FYI- #13736 reports issues with native encryption as well.

**Comment by filip-paczynski** [comment]
@rrevans 
> FYI- #13736 reports issues with native encryption as well.

Good point, but the read speeds here are even more abysmal.

@ChordMankey  
The lines with long periods of inactivity might be helpful for someone :)
(not necessarily me).

Honesty, this is beyond my knowledge. Hope someone more experienced with ZFS encryption will look into this.
What I try to do here is to capture as much data as possible so that a ZFS developer can access it easily in the future. (I'm just a long-term user)
Maybe I will notice something striking, but really cannot promise anything. 

`zpool events` output `ereport.fs.zfs.delay` is about req spending more that 30 seconds in queue. Which is correct reporting in this case.

What else comes to mind:
1. Disable data cache for test datasets: execute `zfs set primarycache=metadata,secondarycache=metadata pool/tested_dataset` on both encrypted and unencrypted datasets
3. Disable NCQ by adding `libata.force=noncq` on kernel cmd line
   - If You do not have experience with dracut (or whatever Fedora uses these days) and editing kernel params, then the easiest way to do this is to activate "edit kernel cmd line" function on boot screen (might be on "advanced" menu), this is one-time setting, will not affect any permanent settings, will revert to default after reboot.
2. Reboot (and disable NCQ via boot screen if applicable)
   - cache on testing datasets is now disabled, second exec of `cat` should behave the same as the first one
   - check if NCQ is disabled: `dmesg | grep -i ncq`
5. Provide full output of `arc_summary` (maybe use [pastebin](https://pastebin.com/) since GH does not have collapsible sections) 
6. Re-try `cat /mypool/mydataset/file.mkv > /dev/null` on both encrypted and unencrypted datasets
   - Maybe on a smaller file...
   - Capture its output, do not replace any lines with `.` - use pastebin

In general the delays seem crazy. However, there is something else here regarding `total_disk_wait` on first read and number of `syncq_read/activ` always being `1`... curious. 

Does kernel report any issues with timeouts, SCSI errors or anything like that? (`dmesg` or /var/log/kern.log, messages, syslog)

**Comment by filip-paczynski** [comment]
@ChordMankey 

> Try adding "options zfs zfs_dmu_offset_next_sync=0" to your modprobe.d configs.

AFAIK this is about writes, likely not applicable in this case

>> Check read perf of disk themselves by dd-ing them into null one by one: `dd if=/dev/physical-disk of=/dev/null bs=128k status=progress`.
>       
>   Having a bit of trouble with this one with the error `dd: failed to open '/dev/sdf': No such file or directory`, it seems to be expecting a directory as input, will look further into this.

No, `dd` expects a device or file on `if=`. If there was `/dev/sdf` on boot or few seconds ago and now its gone, then we might be dealing with disappearing devices here. Which is a very rude thing for a hard drive to do.

>I'm also not sure what you meant by exported pool but I imagine it involves a clone of some sort of the pool which unfortunately isn't possible for me cause I don't have spare storage for another test setup.

Not at all, I meant to make pool totally unused, untouched and unmonitored while doing the `dd` thing.
1. Close all files and folder windows, and terminals currently using any file or directory from the pool
2. execute `zpool export pool_name`
3. do the `dd` thing
4. execute `zpool import pool_name`
5. If the pool does not re-appear automatically after reboot, execute `zpool import pool_name`

>> Turning NCQ off
>
> I don't know what this is and need to read up on it and try it when I have some time.

NCQ allows hard drive (or other hard-drive-like device) to wait for more commands and re-order them.
The crucial part here is that we do not want the drive to wait.

**Comment by amotin** [comment]
> NCQ allows hard drive (or other hard-drive-like device) to wait for more commands and re-order them. The crucial part here is that we do not want the drive to wait.

@filip-paczynski NCQ allows hard drive to receive several commands and process them in the most efficient order, respecting specific drive mechanical characteristics.  We do want that, since no software scheduler can do it properly due to lack of required information.  Drive may not know what commands are more time-critical than others, so it may prefer sequential I/O to random, but ZFS scheduler should be able to throttle background activity if interactive begins to suffer.  Please leave NCQ alone unless the hardware is known broken with it.

**Comment by ChordMankey** [comment]
My apologies for the large delay in responding. After all this debugging and getting no conclusive results, I was finally able to connect the drives directly to my PC, bypassing the external enclosure, and everything is working well. So the enclosure was the problem after all.

In case anyone benefits from this information, the enclosure in question is a Sabrent device, so definitely avoid those. The advice on avoiding external enclosures is definitely not unfounded and I learned this lesson the hard way.

Thanks a lot to everyone on this thread for all the support and guidance!
