### ISSUE TITLE
Linux 6.9 compat: bdev_open_by_path replaced by bdev_file_open_by_path

### ISSUE THREAD

**Issue by satmandu** [openzfs/zfs#16027]
As of https://github.com/torvalds/linux/commit/910202f00a435c56cf000bc6d45ecaabac4dd598 and Linux 6.9-rc1 `struct bdev_handle *bdev_open_by_path` has been replaced by `struct file *bdev_file_open_by_path`.

### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 23.10
Kernel Version	| 6.9-rc1
Architecture	| x86_64
OpenZFS Version	| 2.2.3

### Describe the problem you're observing

This change breaks building OpenZFS 2.2.3 on Linux Kernel 6.9-rc1:

```
checking whether blkdev_get_by_path() exists and takes 3 args... no
checking whether blkdev_get_by_path() exists and takes 4 args... no
checking whether bdev_open_by_path() exists... configure: error:
        *** None of the expected "blkdev_get_by_path()" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        *** 
```

**Comment by robn** [comment]
Thanks for the report. I'm already working on the patch series.
