### ISSUE TITLE
Kernel NULL pointer dereference

### ISSUE THREAD

**Issue by multi** [openzfs/zfs#16050]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch
Distribution Version	| -
Kernel Version	| 6.7.11-hardened1-1-hardened
Architecture	| x86_64
OpenZFS Version	| 2.2.99-398_g39be46f43f

### Describe the problem you're observing

Running syncoid reboots the machine.
It was working fine with [8f2f6cd](https://github.com/openzfs/zfs/commit/8f2f6cd2ac688916adb2caf979daf95365ccb48f)

Running scrub on `pool` shows 0B repaired and zero errors. Waiting `backup` scrub to finish ...

### Describe how to reproduce the problem

Run syncoid

```
syncoid --recursive --no-sync-snap --create-bookmark --sendoptions="Lcepw" --recvoptions="u" pool backup/pool
```

### Include any warning/errors/backtraces from the system logs

It's headless machine (+ volatile journald storage). The last thing in the logs is from cron -> syncoid.

**Comment by multi** [comment]
I've tried reverting to kernel 6.7.9-hardened1-1-hardened, also attached a monitor and captured some shots (sorry for the low quality...)

This time it oops almost instantly ...

![IMG_5415](https://github.com/openzfs/zfs/assets/616057/3b10d294-b393-4356-ae9d-8de8ee2c4762)
![IMG_5414](https://github.com/openzfs/zfs/assets/616057/96fadc97-217a-42ff-ab9d-2e73adcfcda0)

I have `transparent_hugepage=never` in kernel args also, if it's relevant ...

Running `6.6.23-1-lts` atm, 15 mins so far without oops

ps. `backup` scrub is still running (started from the begging few times, because of the reboots)

**Comment by lnicola** [comment]
The stack trace looks different, but can you try booting with `zfs.zfs_vdev_disk_classic=1`? CC #16045

**Comment by multi** [comment]
@lnicola 

>can you try booting with zfs.zfs_vdev_disk_classic=1

OK, will try

---

Meanwhile just downgraded zfs to https://github.com/openzfs/zfs/commit/8f2f6cd2ac688916adb2caf979daf95365ccb48f
kernel 6.7.11-hardened - no oops, syncoid works

**Comment by robn** [comment]
Similarly, if you can rebuild and test with #16049 / 1c22ed4 applied (with `zfs_vdev_disk_classic=0`) and let us know, that'd be great. Thank you!

**Comment by multi** [comment]
Here you go

- 6.7.11-hardened + non-patched zfs [39be46f](https://github.com/openzfs/zfs/commit/39be46f43f96fb7420386d03751b01f5cb376d6b) + `zfs.zfs_vdev_disk_classic=1` - no oops, syncoid works
- 6.7.11-hardened + patched zfs [1c22ed4](https://github.com/openzfs/zfs/commit/1c22ed4549e6dd9e8251420ed495a6f1979884ea) + `zfs.zfs_vdev_disk_classic=0` - no oops, syncoid works

**Comment by lnicola** [comment]
:shipit:

**Comment by robn** [comment]
@multi thanks, that's great news. I'm confident that this is #16049 too.

**Comment by multi** [comment]
I've tried also 6.7.9-hardened + patched zfs + zfs_vdev_disk_classic=0 - no oops

But noticed something odd - two (mostly, sometimes all) of disks never goes to sleep, since yesterday... I'm pretty sure it's somehow related with this journey (at least the timing matches) :)

Last 2 days
<img width="425" alt="last 2 days" src="https://github.com/openzfs/zfs/assets/616057/0f383152-4a4d-49fa-8cfa-a18111c9c84f">

Last 7 days
<img width="409" alt="last 7 days" src="https://github.com/openzfs/zfs/assets/616057/07eabcbc-41bf-4ce9-816b-2e5b9e65ab39">

Tried 6.7.9-hardened + [8f2f6cd](https://github.com/openzfs/zfs/commit/8f2f6cd2ac688916adb2caf979daf95365ccb48f) + zfs_vdev_disk_classic=0 - just to confirm, if all disks goes to sleep as it should be - and no. The same two disks (from a raidz2 of 6) never goes to sleep :/

**Comment by robn** [comment]
@multi oh, interesting! Could you open a new issue please? I have followup questions but I'd like it track it separately. Cheers :)
