### ISSUE TITLE
ZFS doesn't work with CONFIG_CFI_CLANG

### ISSUE THREAD

**Issue by michael-brade** [openzfs/zfs#16142]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  Debian
Distribution Version	| unstable
Kernel Version	|  6.1.86, 6.7.12
Architecture	|  amd64
OpenZFS Version	| 2.2.3

### Describe the problem you're observing

I am using ZFS on Root with zfs native encryption. If I compile the kernel with clang 18 and `CONFIG_CFI_CLANG`, the zfs modules cannot even get loaded successfully. I can't see the beginning of the error clearly, but the RIP says:

```
Modules linked in: zfs(0+) spl(0)
...
RIP: 0010:zfs_blake3_compress_in_place_sse2
...
note: modprobe exited with irqs disabled
Killed

Failed to load ZFS modules.
```

**Comment by rincebrain** [comment]
#15911

**Comment by michael-brade** [comment]
oh.. sorry, I missed this. Closing as duplicate.
