### ISSUE TITLE
RPM repo broken for epel 9.3 - missing 2.1.15-2 packages

### ISSUE THREAD

**Issue by ianb-mp** [openzfs/zfs#16179]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 9.3
Kernel Version	| 5.14.0-362.24.1.el9_3.0.1.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.15

### Describe the problem you're observing

Attempting to install zfs 2.1.15-2 fails with this error:
```
$ dnf install zfs
ZFS on Linux for EL9 - kmod                                                                                                                                                          6.9 kB/s | 2.9 kB     00:00    
Error: 
 Problem: package zfs-2.1.15-2.el9.x86_64 from zfs-kmod requires zfs-kmod = 2.1.15, but none of the providers can be installed
  - conflicting requests
  - nothing provides kernel(__alloc_pages) = 0x721dbc2e needed by kmod-zfs-2.1.15-2.el9.x86_64 from zfs-kmod
  - nothing provides kernel(__blk_alloc_disk) = 0x01865137 needed by kmod-zfs-2.1.15-2.el9.x86_64 from zfs-kmod 
 [...]
  - nothing provides kernel(write_cache_pages) = 0x30a4cdde needed by kmod-zfs-2.1.15-2.el9.x86_64 from zfs-kmod
  - nothing provides kernel(write_inode_now) = 0x3f0b016c needed by kmod-zfs-2.1.15-2.el9.x86_64 from zfs-kmod
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

When I look here: http://download.zfsonlinux.org/epel/9.3/kmod/x86_64/ I can see no packages for 2.1.15-2

### Describe how to reproduce the problem

Installing ZFS using kABI-tracking kmod using this doco: https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html

**Comment by tonyhutter** [comment]
zfs-2.1.15-2 is in the 9.4 repo:

http://download.zfsonlinux.org/epel-testing/9.4/kmod/x86_64/

My guess is that Rocky hasn't updated to 9.4 yet.

**Comment by tmzullinger** [comment]
Indeed.  Additionally, the `zfs.repo` file uses `$releasever` which resolves to 9 on Rocky.  There's not really much that can be done.  This is just one of the bumps which happens twice a year when RHEL updates are pushed.  It'll pass in a few days.

Someday, I really need to submit a PR to provide the kmod packages the way they are done by RPM Fusion for modules like nvidia, where each kernel that changes the ABI gets a new build and the package names then include the kernel version.  (There's still a `kmod-nvidia` metapackage which pulls in the latest as needed.)  I just haven't spent the time to work all that out yet. :/

For a module like zfs which uses many kernel functions which are not included in the RHEL ABI guarantees, that would make these transitions (and general kernel updates) a bit easier.  It's got the benefits of dkms combined with those of akmods.  Not having to have a compiler on each host like is needed for dkms is a plus for many.  It does also make it easier to ship an `akmods-zfs` package which builds a new `kmod-zfs-$(uname -r)` package similar to dkms, but installed as an rpm which is more palatable to other folks.

**Comment by ianb-mp** [comment]
> zfs-2.1.15-2 is in the 9.4 repo

ok. My understanding of the issue I'm seeing is 9.3 is trying to install zfs-2.1.15-2 from the 9.4 repo, and failing due to incompatibility (??)

> My guess is that Rocky hasn't updated to 9.4 yet.

Correct. RL 9.4 due any day now 🤞 

> Additionally, the zfs.repo file uses $releasever which resolves to 9 on Rocky

Which explains why 9.3 is trying to install zfs-2.1.15-2 - is just gets whatever is latest?

**Comment by tonyhutter** [comment]
> Which explains why 9.3 is trying to install zfs-2.1.15-2 - is just gets whatever is latest?

I'm guessing it's trying to install from:

http://download.zfsonlinux.org/epel/9/

...which just points to the latest 9.x release.  Technically we build RPMs AlmaLinux for 9.x (which is at 9.4).

**Comment by tmzullinger** [comment]
> > My guess is that Rocky hasn't updated to 9.4 yet.
> 
> Correct. RL 9.4 due any day now 🤞

Or about an hour after your post. ;-)

**Comment by tonyhutter** [comment]
@ianb-mp is it ok to close this issue?

**Comment by ianb-mp** [comment]
Yes, happy to close. Thanks for your help.
