### ISSUE TITLE
el8 "zfs-testing" repositories still tracking 2.2.3-1.

### ISSUE THREAD

**Issue by ashleyw-gh** [openzfs/zfs#16170]
Hi, How long after the 2.2.4 release is it likely before the 2.2.4 release is shown under the "zfs-testing" repositories on el8?
At the moment, the zfs-testing repositories on Rocky 8 are tracking 2.2.3-1.
It would be great if the version can be bumped up/
thanks for great work.

```
# rpm --eval %{?dist}
.el8
# dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
# dnf config-manager --enable zfs-testing
# dnf install -y epel-release
# dnf install -y kernel-devel zfs
# zfs --version
zfs-2.2.3-1
zfs-kmod-2.2.3-1
```

**Comment by tonyhutter** [comment]
Thanks for the heads-up, please try it again.

**Comment by ashleyw-gh** [comment]
looking great now. thanks for super fast response
```
# zfs --version
zfs-2.2.4-1
zfs-kmod-2.2.4-1
```
(for others make sure you run a yum clean all etc to make sure the caches are cleaned).
