### ISSUE TITLE
Support for Intel SHA Extensions

### ISSUE THREAD

**Issue by jvandertil** [openzfs/zfs#1618]
Unsure if this is already the case, or that this is considered too low level / not applicable.

But to improve the performance of the sha256 hashing algorithm, the Intel SHA extensions could be implemented. As described here: http://software.intel.com/en-us/articles/intel-sha-extensions

Or is this something that would have to be implemented in the Linux kernel / some other library?

**Comment by split-n** [comment]
Is this still not interested? SHA Extension is now available since EPYC Naples and Xeon Ice Lake.

**Comment by cybojanek** [comment]
> Is this still not interested? SHA Extension is now available since EPYC Naples and Xeon Ice Lake.

I'm working on this here: https://github.com/openzfs/zfs/pull/12549

**Comment by mcmilk** [comment]
@jvandertil - this issue is resolved via https://github.com/openzfs/zfs/pull/13741 ;-)
