### ISSUE TITLE
VERIFY3(dev->l2ad_hand + distance < dev->l2ad_end) failed

### ISSUE THREAD

**Issue by VoxSciurorum** [openzfs/zfs#16202]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13.3-STABLE
Kernel Version	| 13.3-STABLE
Architecture	| amd64
OpenZFS Version	| zfs-2.1.15-FreeBSD_gfb6d53206

### Describe the problem you're observing

While receiving an rsync incremental update, and doing nothing else, my server crashed with

panic: VERIFY3(dev->l2ad_hand + distance < dev->l2ad_end) failed (161060749312 < 161060749312)

This is in `l2arc_evict` in arc.c.  I suspect `<` may need to be `<=`.

### Describe how to reproduce the problem

It happened only once.

### Include any warning/errors/backtraces from the system logs

The `dev` pointer points at
```
 l2ad_hand = 161051246592,
 l2ad_start = 4198400,
 l2ad_end = 161060749312,
 l2ad_first = 0,
 l2ad_writing = 0,
```
Variable `distance` is 9502720, equal to `l2ad_end - l2ad_hand`, as expected from the panic message.

My server has a raidz2 pool on hard drives with a cache on SSD.  RAM is 24 GB.

Reported to FreeBSD at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279038.

**Comment by gamanakis** [comment]
Thanks for reporting this, you are probably right. I will take a look.
