### ISSUE TITLE
Feature Request: Mount a backup dataset file to a pool.

### ISSUE THREAD

**Issue by davidngrc** [openzfs/zfs#16259]
Hi, from this article,
ZFS Backups to Files
https://johnhollowell.com/blog/posts/zfs-backups-to-files/

zfs dataset can be backup to a file by using command like this
zfs send -R tank@full-backup | ssh dest.example.com "cat > /path/to/saved/file.zfsnap"

I try it, it work.
but it seems there is no way of direct mounting this /path/to/saved/file.zfsnap dataset file to a pool.
please help.

**Comment by amotin** [comment]
Replication stream is not a file system by itself.  It is a stream of changed blocks.  It has no table of contents, indexes or anything like that.  Directories are represented as a set of writes, same as files.  It would be extremely difficult if not impossible to read it directly.  It would be easier to receive the stream somewhere.
