### ISSUE TITLE
fs/zfs/os/linux/zfs/vdev_file.c:26:10: fatal error: 'fcntl.h' file not found

### ISSUE THREAD

**Issue by xsoalokinx** [openzfs/zfs#16266]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	|
Kernel Version	| 6.8.12-gentoo
Architecture	| amd64
OpenZFS Version	| 2.2.4

### Describe the problem you're observing

Kernel fails to build when including zfs into kernel sources.

clang version 17.0.6
musl version 1.2.4

### Describe how to reproduce the problem

LLVM=1 LLVM_IAS=1 make

### Include any warning/errors/backtraces from the system logs

```
mkdir -p /usr/src/linux-6.8.12-gentoo/tools/objtool && make O=/usr/src/linux-6.8.12-gentoo subdir=tools/objtool --no-print-directory -C objtool 
  INSTALL libsubcmd_headers
  CALL    scripts/checksyscalls.sh
  CC      fs/zfs/os/linux/zfs/vdev_file.o
fs/zfs/os/linux/zfs/vdev_file.c:26:10: fatal error: 'fcntl.h' file not found
   26 | #include <fcntl.h>
      |          ^~~~~~~~~
1 error generated.
make[4]: *** [scripts/Makefile.build:243: fs/zfs/os/linux/zfs/vdev_file.o] Error 1
make[3]: *** [scripts/Makefile.build:481: fs/zfs] Error 2
make[2]: *** [scripts/Makefile.build:481: fs] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-6.8.12-gentoo/Makefile:1921: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2

```

**Comment by robn** [comment]
`vdev_file.c` in 2.2.4 does not include `fcntl.h`, but rather `sys/fcntl.h`. Also, line 26 of that file is something different.

So, can you provide more info about how you're pulling OpenZFS into the kernel sources? Preferably steps that we can use to reproduce this.

**Comment by xsoalokinx** [comment]
> `vdev_file.c` in 2.2.4 does not include `fcntl.h`, but rather `sys/fcntl.h`. Also, line 26 of that file is something different.
> 
> So, can you provide more info about how you're pulling OpenZFS into the kernel sources? Preferably steps that we can use to reproduce this.

https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/zfs/zfs-2.2.4.ebuild

```
#!/bin/bash

set -e

export LLVM=1
export LLVM_IAS=1

ver="${1}"
portdir=/var/db/repos/gentoo
tmpdir=/var/tmp
ebuild=/var/db/repos/gentoo/sys-fs/zfs/zfs-"$ver".ebuild
work="$tmpdir"/portage/sys-fs/zfs-"$ver"/work/zfs-"$ver"
dest=/usr/src/linux

cd "$dest" && make prepare && make scripts
ebuild "$ebuild" clean prepare
cd "$work"
./autogen.sh
./configure --enable-linux-builtin --with-linux{,-obj}="$dest"                  
./copy-builtin "$dest"
```

**Comment by xsoalokinx** [comment]
It looks like the patch here is what is responsible for changing the include;
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/zfs/files/2.2.3-musl.patch

**Comment by robn** [comment]
Thanks. You'll need to report this to the packager then; if a modification they've made has broken something there's nothing we can do about it here.

**Comment by xsoalokinx** [comment]
> Thanks. You'll need to report this to the packager then; if a modification they've made has broken something there's nothing we can do about it here.

thank you for the help, will close this.
