### ISSUE TITLE
unable to remove slog devices

### ISSUE THREAD

**Issue by likewhoa** [openzfs/zfs#1629]
I had an issue a week ago were my drive that was assigned for the slog and cache failed (yes i didn't have the slog mirrored) and upon a reboot the pool could not be imported until i ran <code>zpool remove pool device</code> for the cache and log and i also had to import the pool with <code>zpool import -fFm -N pool</code>.

I ordered 2 new ssd drives to mirror the slog and added them but I made one mistake in that process, I ran the add command without -o ashift=13 so you would think I would be able to remove the slog again by putting it offline and then running the remove command but I get this now.

<code>cannot remove dm-5: operation not supported on this type of pool</code> so now I am stuck with an slog mirror which I cannot remove.

Below is my <code>zpool status</code>

<code>
  pool: likewhoa
 state: ONLINE
  scan: scrub repaired 0 in 4h38m with 0 errors on Wed Aug  7 02:57:33 2013
config:

```
    NAME        STATE     READ WRITE CKSUM
    likewhoa    ONLINE       0     0     0
      raidz2-0  ONLINE       0     0     0
        dm-4    ONLINE       0     0     0
        dm-0    ONLINE       0     0     0
        dm-1    ONLINE       0     0     0
        dm-2    ONLINE       0     0     0
        dm-3    ONLINE       0     0     0
        dm-9    ONLINE       0     0     0
        dm-8    ONLINE       0     0     0
        dm-7    ONLINE       0     0     0
    logs
      mirror-1  ONLINE       0     0     0
        dm-5    ONLINE       0     0     0
        dm-10   ONLINE       0     0     0
    cache
      dm-6      ONLINE       0     0     0
      dm-11     ONLINE       0     0     0
```

errors: No known data errors
</code>

Distro: Gentoo Linux AMD64 hardened no-multilib
Kernel: 3.9.9
ZFS/SPL: 0.6.1-r3

**Comment by adamboutcher** [comment]
After an hour of googling this was the answer to my question of how to remove a SLOG.

Confusing as you do zpool add <pool> log <raid> <dev> and the zpool output shows logs and not log too.

**Comment by luisliz** [comment]
Only good answer maybe this should go on the docs somehow?

**Comment by amotin** [comment]
For member of mirror would work `zpool detach`, after which `zpool remove` for remaining disk would work.  Just as an alternative way.
