### ISSUE TITLE
FreeBSD: zdb "Memory fault" in ZTS

### ISSUE THREAD

**Issue by tonyhutter** [openzfs/zfs#16311]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13
Kernel Version	|
Architecture	| x86_64
OpenZFS Version	| master

### Describe the problem you're observing
While doing testing for https://github.com/openzfs/zfs/pull/15838 I started hitting "Memory fault" zdb errors on FreeBSD 13.  I was testing out running ZTS on a VM running within a github runner, so I assumed it was my weird test environment was the problem.  Then I saw it in the test results for an unrelated PR (#16304):

https://build.openzfs.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29/builds/2278/steps/shell_4/logs/log

Just search for "Memory fault" in the logs and you'll see a ton of failures.

### Describe how to reproduce the problem
I can only reproduce it on a github runner using the non-standard setup in https://github.com/openzfs/zfs/pull/15838. 

### Include any warning/errors/backtraces from the system logs
```
15:42:17.55 Call trace:
15:42:17.55 0x821ed3b66 <libspl_backtrace+0x26> at /usr/local/lib/libzpool.so.5
15:42:17.55 0x214c15 <main+0x1235> at /var/tmp/constrained_path.CUiLlO/zdb
15:42:17.55 0x826a502d0 <pthread_sigmask+0x540> at /lib/libthr.so.3
15:42:17.55 0x826a4f88b <pthread_setschedparam+0x84b> at /lib/libthr.so.3
15:42:17.55 0x7ffffffff923 <_fini+0x7fffffdd55a7> at ???
15:42:17.55 0x82422f3f3 <nvlist_free+0x13> at /usr/local/lib/libnvpair.so.3
15:42:17.55 /usr/local/share/zfs/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh[120]: check_removal[105]: log_must[70]: log_pos: line 265: 41670: Memory fault
15:42:17.55 ERROR: zdb -bbcc testpool exited 267
```

**Comment by tonyhutter** [comment]
Another sighting (#16270):

https://build.openzfs.org/builders/FreeBSD%20stable%2F13%20amd64%20%28TEST%29/builds/2141/steps/shell_4/logs/log

**Comment by mcmilk** [comment]
PR https://github.com/openzfs/zfs/pull/16332/ should fix this.
