### ISSUE TITLE
zpool <TAB> completion only works after running zfs <TAB>

### ISSUE THREAD

**Issue by Impact123** [openzfs/zfs#16320]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 12 (Bookworm)
Kernel Version	| 6.1.0-22-amd64
Architecture	| x86_64 (amd64)
OpenZFS Version	| 2.2.4 (zfs-2.2.4-1~bpo12+1)

### Describe the problem you're observing
I noticed that the` zpool <TAB>` completion does not work until after one has already run `zfs <TAB>`.
This seems to be due to the fact that `/usr/share/bash-completion/completions/zpool` does not exist but` /usr/share/bash-completion/completions/zfs` does.
A simple "fix" that worked for me is to symlink `/usr/share/bash-completion/completions/zfs` to `/usr/share/bash-completion/completions/zpool` or `source`ing the `/usr/share/bash-completion/completions/zfs` file.

### Describe how to reproduce the problem
1. Open a new shell, type `zpool ` and press `TAB`
2. Type `zfs ` and press `TAB`
3. Type `zpool ` and press `TAB`
4. Note the difference between `1` and `3`.

**Comment by Harry-Chen** [comment]
Related downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074597
