### ISSUE TITLE
Pool-level raid type configurable between vdevs

### ISSUE THREAD

**Issue by DoctorD90** [openzfs/zfs#16347]
### Describe the feature would like to see added to OpenZFS

Based on current development, at the pool level, data is striped between vdevs in the pool. My idea is to allow the end user the ability to configure the pool with stripe/mirroring/raidz1-2-3 between vdevs.

### How will this feature improve OpenZFS?

Stripe does not provide redundancy (the raidz1-2-3 already implemented do). People may want to benefit from ZFS data management not only in the vdevs but also at the pool level, thanks to a "second" tier. This would allow more complex layouts (e.g., raid10, raid01, raid50, raid05, raid60, raid06).

**Comment by amotin** [comment]
Why would you need a second layer of redundancy?  ZFS now mostly relies on each individual vdev to be self-sufficient and redundant.  "Mostly" because metadata and some critical data may be stored in multiple copies, which are spread between different vdevs, so pool may remain partially accessible even after loosing one of top-level vdevs.  But doing it for all the data is too expansive.  Much more reasonable and cost effective way to improve data safety is to set up separate backup system to replicate the data there.  RAID IS NOT A BACKUP!

**Comment by DoctorD90** [comment]
Hi! Thank you for your quick response. It is clear that there is no intention/willingness to implement it and that is fine. I am replying not to open "disputes" or being polemic but just to clarify your misunderstanding. May I kindly ask where I mentioned "backup purposes" in my feature request? I was just pointing out that something really great like ZFS, per pool, forces each user to rely on the less-secure node/vdev (in case of multiple vdev), or as you said, to implement multiple/complex systems (not for backup). Compared to the other existing raid approaches mentioned, it forces the stripe, while allowing users to choose the type of raid to use at the pool level, it would be easily comparable to the other existing and used methods.
I have not reinvented the wheel with other raid types that are not currently (and probably never will be) implemented in ZFS. If they have been invented, implemented, and used over the years, there are "probably" people who feel the need for them (but I am not and will not open discussions about cost/benefit/utility - it is not my scope). Mine was just an idea to replicate "easily" (although at the implementation level it probably isn't) and extend the use of ZFS to the possible needs of those who currently rely on Raid10/01/50/05/60/06-like scheme and who might want to adopt ZFS for its advantages over other raid (and non-backup) solutions.
In any case, the direction of development on this topic seems very clear and immutable, so thank you for the clarity.

**Comment by amotin** [comment]
I didn't mean "no, because I said so".  But you are asking for features without providing sufficient motivation, and I've asked you about it.  There were endless variations of RAID invented over the years, but it does not mean all of them make sense for ZFS or even real life in general, outside of marketing.  If you think I am wrong, please give examples when implementing both RAID50 and RAID05 or RAID10 and RAID01 make sense.

I was not saying that your system is a backup.  But it is actually a [quote](https://www.raidisnotabackup.com/) in the industry, meaning that no level of RAID redundancy can substitute a backup.  The only point to build RAIDZ of mirrors, mirror of RAIDZs, etc is to further increase protection against disk failures.  But same time it more than linearly increases price and complexity of the system, that may actually reduce reliability, while at that level chance of simultaneous death of so many disks in so unlikely, that it must be something catastrophic, like a power surge, fire or flood, in which case all the redundancy you can build does not matter.  What matters though is a reliable off-site backup.

**Comment by DoctorD90** [comment]
Thank you very much for the clarification. I am used to the idea that when a "ticket" is closed, the discussion is to be considered over, and I am not used to push it as I understand that there can be multiple reasons: other development priorities, complexity and implementation time vs. benefits, development direction, etc. I am usually for the "if you really want to, write it and propose it" (I am not so much for forks when it comes to one feature). Unfortunately, I am not skilled enough to write code for a file system, so I accept the direction the developers want/decide to keep. For this reason I did not provide further details but I was careful that my request was not misunderstood with the quote "raid is not a backup" 😃

Regarding motivations/examples, I obviously have no visibility into how Raids are handled in the "big companies"/SOHO but since I have approached ZFS, I am discovering a world of qualities and advantages and possibilities; the only "fixed" thing is the management of vdevs within a pool (stripping only).

As a non-zfs-expert approaching the new technology, and thus a view unencumbered by the "blinders" (not in a negative sense) that are normal for those who are always working on their topic, I noticed a few points that led me to open this request, in the spirit of perhaps suggesting something not evaluated/thought of being focused ( maybe) on more important and higher priority issues.
Within the single vdev, you can configure a single disk, a stripe (0), a mirror (1), a raidz1-2 (5-6) and even a raidz3, so maximum freedom to choose virtually any configuration you want.
The moment you add a vdev, you are automatically "forced" to a stripe between vdevs, so, wanting to compare it with existing architectures, ZFS already allows a 0x raid (01, 02, 05, 06). Anyone (for whatever reason, which I have no interest in addressing at this time since one could configure all possible scenarios, and one would waste time on "futile" discussions about personal assessment of validity losing the focus - I prefer to remain unbiased) who is interested in adopting composite architectures (1x, 5x, 6x, x0, x1, x5, x6), is forced to "lose" the advantages of the ZFS file system by having to migrate and vary to other (more or less complex) solutions. In any case, my current point is that ZFS "loses a chunk of users."

I opened this request as I don't have the expertise to understand the technical impact of such an implementation (change of layer management between vdevs) otherwise I would have evaluated and proposed the code directly. I don't have data in hand, as I obviously haven't invested time in market research to understand the user share % of those architectures, as the fundamental focus is whether it is technically feasible or requires a complete rework. Maybe stripe has always been used, and maybe it could be "relatively" simple to define to use the same algorithms developed within the vdev, for inter-vdev management of the pool. The motivations then behind my idea are to allow the user an additional level of "customization," thus encompassing virtually all architectures with one change. This could lead ZFS to become the de facto industry standard since it would become a solution to be evaluated in any scenario, increasing its adoption, usage and thus users, including perhaps additional developers to date "uninvolved" since not "affected." This is why I was asking whether or not changing the management algorithm between vdevs is a deep and complicated rework.

At the moment if you want (and I have read on the internet people who have looked for workarounds to do it) to get such a solution, you have to use zvols but through different systems otherwise you get deadlocks as I have discovered and experienced firsthand; however, this forces "complex" solutions. But it also means that there are people actually interested in such an architecture, and with this modification ZFS could satisfy them.

My point is: ZFS already has "unintentionally" covered the 0x architecture, why not give users the freedom to cover all the others as well? ZFS by default already has a "2-level" raid management structure, why not allow total customization? ... if for technical/algorithm reasons I think there is very little we can/should discuss.

Regarding my very own need, thank you for the suggestion! I had read something about it, but I found the drawbacks you mentioned, so I discarded it, as I agree with you. Being "priceless" data for me, I aim for a "data-safety" that the first used system does not go "offline" forever forcing me already to immediately use the first backup. In case of problems, having multiple disks (in a 61 configuration), although more expensive, by differentiating and distributing the risk of losing all the disks for a resilvering, I would increase the chance that the main system would still be viable without data loss, and I would not have to rely on the first backup (which I am re-implementing with the use of the fantastic snapshot/send/recv).

Thank you very much, and I apologize for the long answer. However, I hope I have explained better and provided clearer reasons.
