### ISSUE TITLE
ZFS LOAD-KEY ERROR

### ISSUE THREAD

**Issue by vulg123** [openzfs/zfs#16350]
### Discussed in https://github.com/openzfs/zfs/discussions/16349

<div type='discussions-op-text'>

<sup>Originally posted by **vulg123** July 13, 2024</sup>
Good morning
Please guys, after enter this `sudo zfs load-key rpool/ROOT/ubuntu_uy913x0` 
I got this output `Key load error: Keys must be loaded for encryption root of 'rpool/ROOT/ubuntu_uy913x' (rpool)`.

Please I dont know how to solve it

Please
Please
</div>

**Comment by gmelikov** [comment]
Please don't spam with questions in issues, closed.
