### ISSUE TITLE
Iteration Time for Native Encryption

### ISSUE THREAD

**Issue by loadfred** [openzfs/zfs#16368]
### Describe the feature would like to see added to OpenZFS

Allow custom iteration time for native ZFS encryption (time required to wait after password is entered).

Like how cryptsetup/LUKS has their --iter-time (milliseconds) parameter, to discourage brute force.

### How will this feature improve OpenZFS?

Optional way to prevent brute force attacks, by purposefully making decryption a longer wait.

**Comment by amotin** [comment]
Unlike network services or somehow else restricted environment, how do you expect this to help in case somebody connect the pool to a system having no such delay?  Please see pbkdf2iters dataset property for a way ZFS handles this now.

**Comment by loadfred** [comment]
whoops yeah you're right it already exists as pbkdf2iters
