### ISSUE TITLE
blkptr at xxx DVA 1 has invalid OFFSET

### ISSUE THREAD

**Issue by Commifreak** [openzfs/zfs#16386]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Unraid
Distribution Version	| 6.12.11
Kernel Version	| 6.1.99
Architecture	| x64
OpenZFS Version	| 2.1.15.1

### Describe the problem you're observing
I observed deletion errors during rsync. Long story short:

* rm is giving me `Invalid exchange (52)`
* ls -la is giving me question marks for affected files
* dbgmsg is showing `blkptr at 00000000a9978ea1 DVA 1 has invalid OFFSET` (same message with different addresses for affected file operations)
* zpool status is saying, everything is ok.
* scrub always shows `scrub repaired 0B in 05:01:45 with 1 errors` (everytime I run it)

How can I correct this errors?

### Describe how to reproduce the problem
I dont know.

### Include any warning/errors/backtraces from the system logs

```
  pool: hdd
 state: ONLINE
  scan: scrub repaired 0B in 05:01:45 with 1 errors on Tue Jul 23 15:30:50 2024
config:

NAME        STATE     READ WRITE CKSUM
hdd         ONLINE       0     0     0
  mirror-0  ONLINE       0     0     0
    sde1    ONLINE       0     0     0
    sdf1    ONLINE       0     0     0

errors: No known data errors
```

```
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799952   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 000000007e0e87a3 DVA 1 has invalid OFFSET 18379474156722466816
1721799954   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000c5bac5aa DVA 1 has invalid OFFSET 18379474156722466816
1721799954   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000c5bac5aa DVA 1 has invalid OFFSET 18379474156722466816
1721799955   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000f1fe3b25 DVA 1 has invalid OFFSET 18379474156722466816
1721799955   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000efec810d DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
1721799961   zio.c:941:zfs_blkptr_verify_log(): hdd: blkptr at 00000000eae2c25c DVA 1 has invalid OFFSET 18379474156722466816
```

**Comment by amotin** [comment]
Unless those messages are somehow false positives (offset 18379474156722466816 can not be right, there are no disks that big), there is no solution for that -- some block pointer on the pool is corrupted and there is no way to repair it.  It may be a result of some software or hardware memory corruption, that got written to the pool.

**Comment by Commifreak** [comment]
So I need to recreate the pool?

**Comment by amotin** [comment]
Yes. I think it is the only way aside of leaving it as-is.

**Comment by Commifreak** [comment]
Can I remove these entries from the zdb somehow to get simply rid of this?

**Comment by amotin** [comment]
No. zdb is primarily read-only. And since everything on the pool is protected by checksums, you can not modify the single block without modifying everything above it.  You've already tried to delete the file without success.  You may try to delete the dataset, but I am not sure what would happen in that case - at best some small space leak, at worst something bad.  So I'd recommend to evacuate/backup the data any way first.

**Comment by Commifreak** [comment]
I‘ll recreate the pool as its not that complex. Thanks for all help! 😀
