### ISSUE TITLE
el8 "zfs-testing" repositories still tracking 2.2.4-2

### ISSUE THREAD

**Issue by ashleyw-gh** [openzfs/zfs#16430]
Hi, How long after the 2.2.5 release is it likely before the 2.2.5 release is shown under the "zfs-testing" repositories on el8?
At the moment, the zfs-testing repositories on Rocky 8 are tracking 2.2.4-2.
It would be great if the version can be bumped up.
thanks for yet another awesome release.
```
# rpm --eval %{?dist}
.el8
# dnf install https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
# dnf config-manager --enable zfs-testing
# dnf install -y epel-release
# dnf install -y kernel-devel zfs
# zfs --version
zfs-2.2.4-2
zfs-kmod-2.2.4-2
```

**Comment by tonyhutter** [comment]
@ashleyw-gh thanks for reporting this.  I'll take a look.

**Comment by tonyhutter** [comment]
Ok, I'm seeing the same 2.2.4 RPMs with EL8.  EL9 has 2.2.5 though.   It seems the 2.2.5 RPMs exist in the EL8 repo, but maybe the repodata just needs updating...

**Comment by tonyhutter** [comment]
I figured it out - http://download.zfsonlinux.org/epel-testing/8.10 had the updated files, but http://download.zfsonlinux.org/epel-testing/8 did not.  I just updated the files and zfs-2.2.5 is showing up now.
