### ISSUE TITLE
Unable to import ONLINE pool

### ISSUE THREAD

**Issue by kyeotic** [openzfs/zfs#16461]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox
Distribution Version	| 8.2.2
Kernel Version	| 6.8.4-2-pve
Architecture	|
OpenZFS Version	| zfs-2.2.3-pve2

### Describe the problem you're observing

Unable to import `ONLINE` pool.

```
root@homelab:~# zpool import
   pool: tank
     id: 12367558582491436533
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        tank                                             ONLINE
          raidz1-0                                       ONLINE
            ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105328K  ONLINE
            ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105332H  ONLINE
            ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105404L  ONLINE

root@homelab:~# zpool import tank
cannot import 'tank': I/O error
        Destroy and re-create the pool from
        a backup source.
```

I have tried several variations of import, all of them result in the same error

### Describe how to reproduce the problem

I do not know how I got into this state. A reddit user helped me investigate, but other than a failing leak test we were unable to find a cause for the failure. The full thread for that is [here](https://www.reddit.com/r/zfs/comments/1emf5xt/comment/lh29fd4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

Here is the failing leak test

```
root@homelab:~# zdb -b -e -p /dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105328K-part1 tank
 
Traversing all blocks to verify nothing leaked ...

loading concrete vdev 0, metaslab 234 of 349 ...entry_offset < sm->sm_start + sm->sm_size (0xc73ab5edda000 < 0x3ac00000000)
ASSERT at module/zfs/space_map.c:173:space_map_iterate()Aborted
root@homelab:~# zdb -b -e -p /dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105332H-part1 tank
 
Traversing all blocks to verify nothing leaked ...

loading concrete vdev 0, metaslab 234 of 349 ...entry_offset < sm->sm_start + sm->sm_size (0xc73ab5edda000 < 0x3ac00000000)
ASSERT at module/zfs/space_map.c:173:space_map_iterate()Aborted
root@homelab:~# zdb -b -e -p /dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S6PNNS0W105404L-part1 tank 

Traversing all blocks to verify nothing leaked ...

loading concrete vdev 0, metaslab 234 of 349 ...entry_offset < sm->sm_start + sm->sm_size (0xc73ab5edda000 < 0x3ac00000000)
ASSERT at module/zfs/space_map.c:173:space_map_iterate()Aborted
```

**Comment by tonyhutter** [comment]
Do you see any weird errors in `cat /proc/spl/kstat/zfs/dbgmsg`?

**Comment by rincebrain** [comment]
That error looks like spacemap corruption, since I think that trip is pronounced "this spacemap has an entry that claims to be outside the range of itself", and not by a small number.

So I am going to hazard a guess a readonly import would work to get data off, and you might be able to get away with rolling back a couple transactions, depending on how long ago it got munged.

I don't particularly have any clever guesses about _why_ it's munged, I'm not aware of any known outstanding bugs in that code, but I've also not been looking for them.

**Comment by kyeotic** [comment]
@tonyhutter There is a lot in there, and I don't know what I am looking for. Here are some lines that look interesting to me

```
1724094951   spa_misc.c:418:spa_load_note(): spa_load(tank, config trusted): read 11 log space maps (11 total blocks - blksz = 131072 bytes) in 0 ms
1724094951   metaslab.c:2445:metaslab_load_impl(): metaslab_load: txg 0, spa tank, vdev_id 0, ms_id 333, smp_length 24752, unflushed_allocs 24576, unflushed_frees 57344, freed 0, defer 0 + 0, unloaded time 762094 ms, loading_time 0 ms, ms_max_size 13158711296, max size error 13158653952, old_weight 840000000000001, new_weight 840000000000001
1724094951   zio.c:1018:zfs_blkptr_verify_log(): bad blkptr at ffffb7ed845e7a00: DVA[0]=0x0/0x0 DVA[1]=0x22000000a70000/0xec0000002d0000 DVA[2]=0x800000/0x0 prop=0x22000000730000 pad=0xe4000000fd0000,0x0 phys_birth=0x0 birth=0x0 fill=0x0 cksum=0x0/0x0/0x0/0x0
1724094951   zio.c:1050:zfs_blkptr_verify_log(): tank: blkptr at ffffb7ed845e7a00 DVA 1 has invalid VDEV 2228224
1724094951   zio.c:1018:zfs_blkptr_verify_log(): bad blkptr at ffffb7ed845e7a80: DVA[0]=0x0/0x0 DVA[1]=0xcb000000e70000/0xa0000008e0000 DVA[2]=0x10000000000000/0x0 prop=0x530000006d0000 pad=0x9c0000006e0000,0x0 phys_birth=0x0 birth=0x0 fill=0x0 cksum=0x0/0x0/0x0/0x0
1724094951   zio.c:1050:zfs_blkptr_verify_log(): tank: blkptr at ffffb7ed845e7a80 has invalid TYPE 83
```

**Comment by rincebrain** [comment]
I'd probably try older txgs then, which is also a game you can experiment with with zdb.

zdb -L will skip it trying to evaluate the spacemaps and possibly print more useful errors, though probably the same ones from that log.

`bad blkptr at ffffb7ed5fc8ba00: DVA[0]=0x0/0x0 DVA[1]=0x430000008a0000/0x74000000220000 DVA[2]=0x0/0x0 prop=0x8d000000890000 pad=0x31000000710000,0x0 phys_birth=0x0 birth=0x0 fill=0x0 cksum=0x0/0x0/0x0/0x0`

That...should not be possible to happen, "in theory" - that seems like it wrote out an incomplete block pointer record, which would also track with
`1724169016   zio.c:1050:zfs_blkptr_verify_log(): tank: blkptr at ffffb7ed5fc8ba00 has invalid TYPE 141`

So I'd still try readonly importing older txgs and see if things are any nicer.

**Comment by kyeotic** [comment]
> So I'd still try readonly importing older txgs and see if things are any nicer.

@rincebrain how do I do that? I'm not sure how to find a txg on a pool without importing it.

**Comment by rincebrain** [comment]
`zdb -ul [some device in the pool] | | grep -E '\Wtxg ='` will give you a list of the ones in the uberblock still, then you can try them backwards in order, first readonly (`zpool import -o readonly -T [number] [...]`) then, after you've done that and found it not wanting, and backed up anything you wanted a more recent copy of than your existing backups, readwrite.

**Comment by kyeotic** [comment]
After a few weeks without a pool I finally recreated this one a few hours before you posted that, so unfortunately I won't know if that would have worked. Thanks for trying though, if this happens again I will have one more step to try.
