### ISSUE TITLE
Cannot build on Fedora with kernel 6.10.x

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs#16544]
### System information

Type | Version/Name
Linux | 6.10
Distribution Name	| Fedora
Distribution Version	| 39
Kernel Version	|  6.10.10-100.fc39.x86_64
Architecture	| x68_64
OpenZFS Version	| latest master  ec0209418fa613e0ee306daf91a9f7208aee6e10

### Describe the problem you're observing

```
+ for f in /var/lib/dkms/zfs/*
+ test -L /var/lib/dkms/zfs/2.2.99
+ test -d /var/lib/dkms/zfs/2.2.99
++ basename /var/lib/dkms/zfs/2.2.99
+ ver=2.2.99
++ rpm -q kernel-devel '--queryformat=%{version}-%{release}.%{arch} '
+ for kver in $(rpm -q kernel-devel --queryformat='%{version}-%{release}.%{arch} ')
+ dkms install -m zfs -v 2.2.99 -k 6.10.10-100.fc39.x86_64
Sign command: /lib/modules/6.10.10-100.fc39.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
...
checking whether bio->bi_opf is defined... yes
checking whether bio_set_op_attrs is available... no
checking whether bio_set_dev() is available... yes
checking whether bio_set_dev() is GPL-only... yes
checking whether bio_set_dev() is a macro... no
checking whether bio_end_io_t wants 1 arg... yes
checking whether bio->bi_status exists... yes
checking whether bio has bi_iter... yes
checking whether submit_bio() wants 1 arg... yes
checking whether current->bio_list exists... yes
checking whether blkg_tryget() is available... no
checking whether bio->bi_bdev->bd_disk exists... yes
checking whether block_device_operations->submit_bio() returns void... yes
checking whether linux/blk-cgroup.h exists... yes
checking whether bio_alloc() wants 4 args... yes
checking whether blkdev_get_by_path() exists and takes 3 args... no
checking whether blkdev_get_by_path() exists and takes 4 args... no
checking whether bdev_open_by_path() exists... configure: error: 
	*** None of the expected "blkdev_get_by_path()" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.2.99-813_g70d3b8d24
	*** Compatible Kernels: 3.10 - 6.7
```

**Comment by robn** [comment]
I'm not sure what you're building, but this isn't latest master.

```
	*** ZFS Version: zfs-2.2.99-813_g70d3b8d24
	*** Compatible Kernels: 3.10 - 6.7
```

```
$ git show ec02094:META | grep Linux
Linux-Maximum: 6.10
Linux-Minimum: 3.10
```

**Comment by edgan** [comment]
The packaged version of zfs 2.2.6 works just fine for me with the 6.10.6-200.fc40.x86_64 kernel on Fedora 40. What doesn't work for me is the same version of zfs with a 6.11 kernel on Fedora 41 beta, but that isn't surprising. I do see signs of 6.11 support in master.

https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora/index.html

https://github.com/search?q=repo%3Aopenzfs%2Fzfs%206.11&type=code

**Comment by Rudd-O** [comment]
I'm glad to see that 2.3.0-rc1 has in fact support for 6.11.  Thank you, folks!

**Comment by Rudd-O** [comment]
Update: yes, the part of my end-to-end test was trying to install ZFS onto the host system to be able to run ZFS on the host (in order to provision the guest images for the end-to-end test), but due to an oversight of mine, it was not finding the ZFS RPMs for the version of Fedora of the host.  That has been corrected now.  Apologies for the overeager bug report.
