### ISSUE TITLE
Fedora 41 repo

### ISSUE THREAD

**Issue by marmarek** [openzfs/zfs#16590]
### Describe the feature would like to see added to OpenZFS

Fedora 41 is going to be released in about a month (https://fedorapeople.org/groups/schedule/f-41/f-41-key-tasks.html), current beta has kernel 6.11. Is there a chance for release with F41 repo before final F41 release?

### How will this feature improve OpenZFS?

Helps Fedora users that like to update early.

### Additional context

Related comment: https://github.com/openzfs/zfs/issues/16544#issuecomment-2372557723

**Comment by edgan** [comment]
Fedora 41 is expected to be released on October 29th 2024.

**Comment by edgan** [comment]
It has been released.

**Comment by luerhard** [comment]
Fedora 41 is out. I now cannot access my pool anymore. I tried reinstalling the repo but it did not help:

```
sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-5$(rpm --eval "%{dist}").noarch.rpm
Updating and loading repositories:
 ZFS on Linux for Fedora 41                                                                                                                                                                                                                           100% |   1.5 KiB/s |   1.4 KiB |  00m01s
>>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Repositories loaded.
```

Am I doing something wrong or is there just not zfs for fedora 41 yet?

**Comment by edgan** [comment]
> Fedora 41 is out. I now cannot access my pool anymore. I tried reinstalling the repo but it did not help:
> 
> ```
> sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-5$(rpm --eval "%{dist}").noarch.rpm
> Updating and loading repositories:
>  ZFS on Linux for Fedora 41                                                                                                                                                                                                                           100% |   1.5 KiB/s |   1.4 KiB |  00m01s
> >>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
> >>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
> >>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
> >>> Status code: 404 for http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml (IP: 52.92.212.195) - http://download.zfsonlinux.org/fedora/41/x86_64/repodata/repomd.xml - repomd.xml
> >>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> Repositories loaded.
> ```
> 
> Am I doing something wrong or is there just not zfs for fedora 41 yet?

#16645 

Fedora 40 with updates, and Fedora 41 on release both use a 6.11 kernel. A released version of zfs that supports 6.11 hasn't happened yet. So there is no point to making a Fedora 41 repository till they make such a release of zfs. It is expected to be 2.2.7, and the official policy is when it is ready.

**Comment by luerhard** [comment]
Interesting. Time to use the macbook then until zfs is ready and I can use my PC again ...

Pretty sure I already was on 6.11 in Fedora 40 though.

**Comment by tonyhutter** [comment]
Fedora 41 was released today - we're testing it right now: https://github.com/openzfs/zfs/pull/16700

**Comment by mpatton125** [comment]
> Fedora 40 with the latest updates, and Fedora 41 on release both use a 6.11 kernel. A released version of zfs that supports 6.11 hasn't happened yet. So there is no point to making a Fedora 41 repository till they make such a release of zfs. It is expected to be 2.2.7, and the official policy is when it is ready.

Not sure what you are on about.  I am running 6.11.5-200.fc40.x86_64 kernel and ZFS is working just fine.

**Comment by edgan** [comment]
> Not sure what you are on about. I am running 6.11.5-200.fc40.x86_64 kernel and ZFS is working just fine.
> 
> zfs-2.2.6-1 zfs-kmod-2.2.6-1

You are right. I had not rebooted my Fedora 40 server that uses zfs, because I expected it to break for all the reasons listed below.


https://github.com/openzfs/zfs/issues/16645

```
cat zfs-2.2.6/META 
Meta:          1
Name:          zfs
Branch:        1.0
Version:       2.2.6
Release:       1
Release-Tags:  relext
License:       CDDL
Author:        OpenZFS
Linux-Maximum: 6.10
Linux-Minimum: 3.10
```

https://github.com/openzfs/zfs/releases:
```
[zfs-2.2.6]
Supported Platforms

    Linux: compatible with 4.18 - 6.10 kernels
    FreeBSD: compatible with releases starting from 12.2-RELEASE
````

**Comment by edgan** [comment]
So I ended up needing to recompile just the zfs-dkms after modifying the spec file to say 6.11.999 instead of 6.10.999 for the kernel-devel dependency.

http://download.zfsonlinux.org/fedora/40/SRPMS/zfs-dkms-2.2.6-1.fc40.src.rpm

This is where I expect some developer to say, but there are X, Y, and Z reasons that 6.11 is unsupported with zfs-2.2.6. On the other hand, as I see above, Fedora 41 got "released".

I don't actually see Fedora 41 here. 

http://download.zfsonlinux.org/fedora/

**Comment by ftc2** [comment]
i say this at the risk of being off topic in case it helps someone.

if you're on fedora 41 (or otherwise on 6.11), afaik you can just use koji to install 6.10 and then stay there until openzfs supports 6.11.

these two posts summarize how and have some tips:
https://forum.level1techs.com/t/picking-a-new-server-os/208353/3
https://forum.level1techs.com/t/picking-a-new-server-os/208353/30

**Comment by edgan** [comment]
> i say this at the risk of being off topic in case it helps someone.
> 
> if you're on fedora 41 (or otherwise on 6.11), afaik you can just use koji to install 6.10 and then stay there until openzfs supports 6.11.
> 
> these two posts summarize how and have some tips: https://forum.level1techs.com/t/picking-a-new-server-os/208353/3 https://forum.level1techs.com/t/picking-a-new-server-os/208353/30

Just ran across this bug.

#16621

**Comment by ftc2** [comment]
i don't get it. you installed 6.10, and openzfs still isn't working?

**Comment by edgan** [comment]
> i don't get it. you installed 6.10, and openzfs still isn't working?

There are different circumstances.

1. Fedora 40/41 and explicitly booting 6.10. Yes, this works without issue.
2. Fedora 40 with 6.10 installed but booting 6.11. This throws the error I just linked to.
3. Fedora 41 with 6.11 installed with a modified zfs-dkms. This throws the error I just linked to.

I am about to test a modify zfs-dkms with the patch.

**Comment by edgan** [comment]
> Fedora 41 was released today - we're testing it right now: #16700

@tonyhutter How is the testing going?

**Comment by tonyhutter** [comment]
@edgan we'll support Fedora 41 with zfs-2.2.7, which going though iterations here https://github.com/openzfs/zfs/pull/16720.

**Comment by awused** [comment]
With kernel 6.12 out, will that patchset also include 6.12 compatibility?  It does seem to have a bunch of 6.12 commits but the description is still only 6.11.

I've been putting off updating because of lagging openzfs support, but if openzfs starts supporting 6.11 but 6.12 is already available in Fedora 41, it's going to severely complicate my upgrade and I'll probably end up putting it off until openzfs manages to support the current kernel again.

**Comment by wedsonlopes** [comment]
> Interesting. Time to use the macbook then until zfs is ready and I can use my PC again ... (thanks for the response!)
> 
> Pretty sure I already was on 6.11 in Fedora 40 though.

I'm not sure if this helps, but I was able to work around the issue by compiling this version directly:
https://github.com/openzfs/zfs/releases/tag/zfs-2.3.0-rc2

I don't recommend doing this because it's a pre-release, but I think the same thing can be done on a stable version, anyway this step-by-step guide helped me access my data again:

```
# if anything here is missing follow the warning when running ./configure to fix it.

dnf install -y cppcheck shellcheck checkbashisms1 python3-devel libudev-devel libuuid-devel libtirpc-devel

dnf install -y  libuuid-devel 

wget https://github.com/openzfs/zfs/releases/download/zfs-2.3.0-rc2/zfs-2.3.0-rc2.tar.gz

tar -xzvf zfs-2.3.0-rc2.tar.gz

cd zfs-2.3.0-rc2/

./configure --prefix=/usr --sbindir=/usr/sbin

make -j$(nproc)

make install

modprobe zfs

zfs version

zpool list

zpool status
```

```
root@essie-pc:/home/wedson/Downloads/zfs-2.3.0-rc2# zfs version
zfs-2.3.0-rc2
zfs-kmod-2.2.6-1
root@essie-pc:/home/wedson/Downloads/zfs-2.3.0-rc2# zpool list
NAME     SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
backup   444G   332G   112G        -         -     1%    74%  1.00x    ONLINE  -
root@essie-pc:/home/wedson/Downloads/zfs-2.3.0-rc2# zpool status -v
  pool: backup
 state: ONLINE
  scan: scrub repaired 0B in 00:15:52 with 0 errors on Mon Nov 11 16:09:19 2024
config:

	NAME                                          STATE     READ WRITE CKSUM
	backup                                        ONLINE       0     0     0
	  ata-KINGSTON_SA400S37480G_50026B778238C6AA  ONLINE       0     0     0

errors: No known data errors
root@essie-pc:/home/wedson/Downloads/zfs-2.3.0-rc2# 
```

**Comment by gregwalters** [comment]
I did a Fedora 39 -> 41 system-upgrade without realizing that ZoL wasn't ready yet. Fortunately the DKMS process worked:
```
[root@storj ~]# rpm -qa | grep -i zfs
libzfs5-2.2.6-1.fc39.x86_64
zfs-dkms-2.2.6-1.fc39.noarch
zfs-2.2.6-1.fc39.x86_64
[root@storj ~]# cat /etc/fedora-release
Fedora release 41 (Forty One)
[root@storj ~]# zpool status
  pool: storj
 state: ONLINE
  scan: scrub repaired 0B in 08:02:58 with 0 errors on Sun Dec  1 10:07:18 2024
config:

	NAME                                  STATE     READ WRITE CKSUM
	storj                                 ONLINE       0     0     0
	  ata-WDC_aaaaaaaaaa  ONLINE       0     0     0
	  ata-WDC_bbbbbbbbb  ONLINE       0     0     0

errors: No known data errors
[root@storj ~]# uname -a
Linux storj 6.11.10-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:51:20 UTC 2024 x86_64 GNU/Linux
```

That is, perhaps, another path people can take if they must. Of course, I'm scared to do any updates until this issue is fixed so I don't break my unexpectedly working setup.

**Comment by tonyhutter** [comment]
zfs-2.2.7 has been released: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.7

It includes packages for Fedora 41:
```
dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-6$(rpm --eval "%{dist}").noarch.rpm
dnf install zfs
```
Thanks all for being patient!
