### ISSUE TITLE
zfs --version CLI nomore works in zfs-2.3.0rc1

### ISSUE THREAD

**Issue by whoschek** [openzfs/zfs#16615]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| OpenZFS
Distribution Version	| ubuntu-22.04
Kernel Version	| 
Architecture	|
OpenZFS Version	| 2.3.0rc1

### Describe the problem you're observing

`zfs --version` nomore works in zfs-2.3.0rc1. Instead, it errors out with:

```
Invalid option '-'
usage: zfs command args ...
where 'command' is one of the following:\
  version [-j]
  create [-Pnpuv] [-o property=value] ... filesystem
```

as shown in detail in the log here: https://github.com/whoschek/bzfs/actions/runs/11204871144/job/31143773762
Here is how exactly the job is being run: https://github.com/whoschek/bzfs/blob/main/.github/workflows/python-app.yml#L151-L155

I understand that `zfs version` has been added, but keep in mind that the `zfs --version` CLI command has worked fine going all the way back to at least zfs-0.8.3 until and including zfs-2.2.6. Existing programs and scripts rely on this feature for runtime checks and will now break. Please make available again the old behavior to retain compatibility.

@usaleem-ix @amotin I'm not sure, but maybe this JSON related change caused the regression: https://github.com/openzfs/zfs/commit/aa15b60e58599c8851358f6c7f85097f79fcfe55#diff-cf9364a9cff2478f377b7c4f69664b4140102fa2642e79d12d9d35f8b525a3bdR2189

**Comment by behlendorf** [comment]
@whoschek thanks for reporting this, and for the quick fix @robn.
