### ISSUE TITLE
Clang trips `-Wcast-function-type-strict` during compilation of 2.2.x an 2.3.x w/ Linux 6.11.3

### ISSUE THREAD

**Issue by intelfx** [openzfs/zfs#16672]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| N/A
Kernel Version	| 6.11
Architecture	| x86_64
OpenZFS Version	| 2.2.6, 2.3.0-rc2

### Describe the problem you're observing

When building ZFS as an in-tree module with `LLVM=1`, it trips Clang warning `-Wcast-function-type-strict` (which becomes an error if `./configure --enable-debug` is used).

### Describe how to reproduce the problem

```console
$ cd ~/linux
$ git checkout v6.11.3
$ make LLVM=1 prepare

$ cd ~/zfs
$ git checkout zfs-2.3-release
$ ./autogen.sh
$ ./configure KERNEL_LLVM=1 --prefix=/usr --with-config=all --with-linux=$HOME/linux --enable-linux-experimental --enable-linux-builtin=yes --enable-debug
$ ./copy-builtin ~/linux

$ cd ~/linux
$ make LLVM=1 oldconfig
<...enable CONFIG_ZFS...>
$ make LLVM=1 fs/zfs/
```

### Include any warning/errors/backtraces from the system logs

```console
$ make LLVM=1 fs/zfs/
<...>
fs/zfs/zfs/arc.c:9798:9: error: cast from 'void (*)(void *) __attribute__((noreturn))' to 'thread_func_t' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
 9798 |         (void) thread_create(NULL, 0, l2arc_feed_thread, NULL, 0, &p0,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9799 |             TS_RUN, defclsyspri);
      |             ~~~~~~~~~~~~~~~~~~~~
./include/zfs/os/linux/spl/sys/thread.h:53:32: note: expanded from macro 'thread_create'
   53 |         __thread_create(stk, stksize, (thread_func_t)func, #func,       \
      |                                       ^~~~~~~~~~~~~~~~~~~
fs/zfs/zfs/arc.c:9840:11: error: cast from 'void (*)(void *) __attribute__((noreturn))' to 'thread_func_t' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
 9840 |                         (void) thread_create(NULL, 0, l2arc_dev_rebuild_thread,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9841 |                             dev, 0, &p0, TS_RUN, minclsyspri);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/zfs/os/linux/spl/sys/thread.h:53:32: note: expanded from macro 'thread_create'
   53 |         __thread_create(stk, stksize, (thread_func_t)func, #func,       \
      |                                       ^~~~~~~~~~~~~~~~~~~
2 errors generated.
```

As far as I can see, this is bogus, because the only thing that does not match in those signatures is the noreturn attribute _in the rhs_, which is semantically OK (it's alright if the caller expects the function to return and it doesn't, unlike the inverse).

But, LLVM's [D134831](https://reviews.llvm.org/D134831) suggests that this `-Wcast-function-type-strict` was added in part to catch the signature mismatches that would trip CFI, and I'm not an expert in CFI.

**Comment by robn** [comment]
Thanks for the report. If you're able to, could you see if #16673 sorts this out for you?

**Comment by intelfx** [comment]
@robn Yup — this is exactly what I did locally, and it indeed fixes the build.
