### ISSUE TITLE
Update zfs-dkms-2.2.6 package for Fedora 40 to support 6.11 kernels

### ISSUE THREAD

**Issue by edgan** [openzfs/zfs#16710]
Fedora 40 is now on 6.11 kernels. The existing zfs-dkms-2.2.6-1.fc40.noarch package allows only 6.10 kernels. Yet updates will install 6.11 kernels, and as long as a 6.10 kernel is installed the package stays happy. But when enough 6.11 kernels get installed then zfs-dkms is going to get uninstalled for not meeting dependencies, or dnf is going to throw an error. Yet zfs does seem to work with the 6.11 kernels, both compiling and running. So it seems like the package's dependencies need to be updated to allow 6.11, and a new release made.

kernel versions:
```
6.10.9-200.fc40.x86_64
6.11.3-200.fc40.x86_64
6.11.4-201.fc40.x86_64
6.11.5-200.fc40.x86_64
```

**Comment by edgan** [comment]
Just ran across this bug.

#16621

**Comment by edgan** [comment]
#16720

**Comment by nstiurca** [comment]
> Yet updates will install 6.11 kernels

One such update in particular is hopping to Fedora 41, which dropped 6.10 kernel entirely. Please enable this for Fedora 41 as well.
