### ISSUE TITLE
File truncate operation does not work with dedup on and fast dedup enabled

### ISSUE THREAD

**Issue by serjponomarev** [openzfs/zfs#16718]
I decided to test file deletion as described in issue [16697](https://github.com/openzfs/zfs/issues/16697) with FDT enabled but using file truncation as described in issue [16708](https://github.com/openzfs/zfs/issues/16708) and found that with deduplication enabled with the FDT feature, file truncation does not work.

To check this, simply create a file:
`truncate -s 1T /zpool/test.io`
Check the file size:
`du -h --apparent-size /zpool/test.io`
`1.0T	 /zpool/test.io`

Then truncate the file, for example:
`truncate -s 1G /zpool/test.io`
Check the file size:
`du -h --apparent-size /zpool/test.io`
`1.0T	 /zpool/test.io`
The file size will not change.

If you reduce the file size to 0, the truncation operation will work.

If you create a pool with deduplication enabled, but without the FDT feature, this problem does not occur.

**Comment by amotin** [comment]
I have difficulties to understand how it might be related to FDT, but not to traditional dedup, or how it can be related to dedup at all.  I am not sure what exactly `du -h --apparent-size` shows.  What does `ls -l` show you?  If you want to exclude a transient effects, I'd make sure to add `zpool sync` calls in strategic places before you measure any disk usage.

**Comment by serjponomarev** [comment]
> I have difficulties to understand how it might be related to FDT, but not to traditional dedup, or how it can be related to dedup at all. I am not sure what exactly `du -h --apparent-size` shows. What does `ls -l` show you? If you want to exclude a transient effects, I'd make sure to add `zpool sync` calls in strategic places before you measure any disk usage.

What I tried before posting this issue:
1. zpool sync
2. reduced txg timeout to 1 second
3. made a snapshot to flush the data

So, I also don't understand why truncate and file resizing doesn't happen with deduplication and FDT enabled, but nevertheless, this issue is reproducible. Check it out, it will take a couple of minutes.

**Comment by allanjude** [comment]
Can you inspect the file before and after the truncation to the smaller size, with:
```zdb -dddddd -bbbbbb $pool/$dataset $inode-number```

As you mentioned, you might need to `zpool sync` before the zdb run for it to show up

Does the DMU see the resize happen?

**Comment by serjponomarev** [comment]
The issue turned out to be with ZFS, which another engineer had built from source. After I rebuilt ZFS from the source, the problem disappeared, and I was unable to reproduce it. 
Why that particular build behaved this way remains a mystery.

I apologize for any confusion caused.
