### ISSUE TITLE
Compiler output during kernel installation

### ISSUE THREAD

**Issue by smlrrlms** [openzfs/zfs#16739]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|	Debian
Distribution Version	|	12.8
Kernel Version	|	6.1.0-27
Architecture	|	amd64
OpenZFS Version	|	2.2.6-1~bpo12+3

### Describe the problem you're observing

There is a compiler output during kernel package installation (when ZFS kernel modules are compiling).
But there is no compiler output during ZFS package installation.
Please hide the compiler output, it isn't necessary in release version of package.

### Describe how to reproduce the problem

Try to install kernel package when zfs-dkms had already installed.

**Comment by robn** [comment]
Could you please show the commands you use, and the output you see?

FYI, `2.2.6-1~bpo12+3` is Debian's packaged version of OpenZFS, not ours. I'll still take a look but this may be a problem specific to Debian's packaging, in which case you'll need to report it to Debian.

**Comment by AllKind** [comment]
> There is a compiler output during kernel package installation (when ZFS kernel modules are compiling).

I'm guessing what you see is the output of the `configure` step, which is executed by the `dkms` program.
The output of the module compiling step is actually sent to a file called `make.log` in i.e: /var/lib/dkms/zfs/2.2.6/6.8.0-47-generic/x86_64/log/.
dkms just automates what a user normally would do manually (`configure` and `make`) with either the source code package of zfs, or from the git repository. 
From the top of my head, there is no option provided by the `dkms` program to hide the output of `configure`.

> But there is no compiler output during ZFS package installation.

However way you install the userland packages of ZFS (i.e: zfsutils-linux) will provide more or less output. If you use `apt`, you'll see the usual console messages - unpacking, install, etc...
If you use a graphical install method like with qdebi you'll see less of what is going on under the hood.

> Try to install kernel package when zfs-dkms had already installed.

The install of the `linux-headers-$(uname -r)` will trigger `dkms`, which will then run `configure` and `make` to create the kernel modules for that particular kernel version.

If I'm not totally missing the point here, I don't think there is anything openzfs can do about that.

**Comment by Harry-Chen** [comment]
@AllKind Thanks for your answer.

I maintain openzfs in Debian. The output is produced by dkms running `configure`, whenever new zfs or kernel headers are installed.

Personally I do not think it is too verbose. It actually comforts some users since re-configuring and re-compiling zfs typically takes a large portion of "apt upgrade" time.

**Comment by smlrrlms** [comment]
Hello and thanks for the answers, you're right about "configure" step.
But what is the result of only "configure" output but not "make" output?
it ain't helping with debug (or helps partially) and only disappointing users.
And in some situations this large output of "configure" part can overwrite "apt upgrade" command output (I mean terminal output buffer).
Therefore, this isn't some critical part but it'll be nice to hide "configure" part for shorter output in release versions of package.

**Comment by AllKind** [comment]
As said, `dkms` does execute `configure`. There is no way I'd know of to pass that as an option to dkms (I contributed some patches to dkms a while ago and there I read wast parts of the code, so I'm pretty sure).

For some reason the authors of dkms decided to send the configure output to console and the make output to a file.
So as said nothing that openzfs can do about that.
If it's really important to you, you can start a discussion at the dkms github repository https://github.com/dell/dkms.

Regarding the terminal output buffer -  I think most terminals have an option to modify the size of it.

Personally speaking I like the verbose output. I can immediately see what happened.
Guess it's a matter of personal taste. Some like it, some do not.

**Comment by smlrrlms** [comment]
But I don't have an option to hide it, the package doesn't give it to me, but okay, it is matter of personal taste but, in this case, without choice.
