### ISSUE TITLE
ZFS 2.1.15 DKMS does not build on Almalinux 9.5

### ISSUE THREAD

**Issue by jszarin** [openzfs/zfs#16779]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Almalinux
Distribution Version	| 9.5
Kernel Version	| 5.14.0-503.11.1.el9_5.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.15-3

### Describe the problem you're observing

DKMS fails when building for the released 9.5 kernel version  5.14.0-503.11.1.el9_5

### Describe how to reproduce the problem

sudo dkms install -m zfs -v 2.1.15 -k 5.14.0-503.11.1.el9_5.x86_64

### Include any warning/errors/backtraces from the system logs

DKMS Build fails:

`checking whether submit_bio() wants 1 arg... yes
checking whether current->bio_list exists... yes
checking whether blkg_tryget() is available... no
checking whether bio->bi_bdev->bd_disk exists... yes
checking whether block_device_operations->submit_bio() returns void... yes
checking whether linux/blk-cgroup.h exists... yes
checking whether bio_alloc() wants 4 args... yes
checking whether blkdev_get_by_path() exists and takes 3 args... no
checking whether blkdev_get_by_path() exists and takes 4 args... no
checking whether bdev_open_by_path() exists... configure: error: 
	*** None of the expected "blkdev_get_by_path()" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.1.15-3
	*** Compatible Kernels: 3.10 - 6.7
	

Cleaning build area...(bad exit status: 2)
Failed command:
make -C /lib/modules/5.14.0-503.11.1.el9_5.x86_64/build M=/var/lib/dkms/zfs/2.1.15/build cleanBuilding module(s)...(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=5.14.0-503.11.1.el9_5.x86_64
Error! Bad return status for module build on kernel: 5.14.0-503.11.1.el9_5.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/2.1.15/build/make.log for more information.`

-->

**Comment by AllKind** [comment]
Looks the same as this: https://github.com/openzfs/zfs/issues/16746

**Comment by jszarin** [comment]
Duplicate of other EL9.5 issue

**Comment by jszarin** [comment]
Duplicate
