### ISSUE TITLE
Directory not listing content and appear empty but files present. 

### ISSUE THREAD

**Issue by MarcoMarcoaldi** [openzfs/zfs#16841]
I use zfs-2.3.99-108_g44446dccd and zfs-kmod-2.3.99-108_g44446dccd on AlmaLinux 9 with SELINUX Disabled and Kernel : Linux Server170 6.11.8-1.el9.elrepo.x86_64

After rollback of snapshot the js directory seem empty but : 

[root@Server170 htdocs]# rm -rf pizza
rm: cannot remove 'pizza': Directory not empty
[root@Server170 htdocs]# cd pizza
[root@Server170 pizza]# ls -alh
total 0
[root@Server170 pizza]# cd ..
[root@Server170 htdocs]# du -h pizza
8.5K    pizza
[root@Server170 htdocs]# 

[root@Server170 htdocs]# stat pizza
  File: pizza
  Size: 21              Blocks: 17         IO Block: 1536   directory
Device: 27h/39d Inode: 10296       Links: 7
Access: (0750/drwxr-x---)  Uid: ( 1001/ricambigXXXXXXXXXXX)   Gid: ( 1001/ricambigXXXXXXXXXXX)
Access: 2024-12-06 00:01:15.459337849 +0100
Modify: 2021-06-07 16:26:39.000000000 +0200
Change: 2024-12-06 11:59:31.091468781 +0100
 Birth: 2024-12-05 20:21:02.374360227 +0100
 
I scrub the pool but 0 byte repared. I restored from previous backup after rename the directory. But now cannot remove the directory.

After export and reimport pool, the directory listing fine and i can delete it.

**Comment by snajpa** [comment]
@MarcoMarcoaldi is this reproducible for you? can you create a new dataset + snapshot and get it to fail like this again? What are the steps if so?

**Comment by MarcoMarcoaldi** [comment]
I try several time but no success.

Yesterday i follow this step :

1. Make snapshot about 140GB of data and about 600.000 files.
2. After about 1 minute, i go in htdocs dir and do a rm -rf 
3. After that i rollback the previous snapshot, but directory empty.
4. I try several time, and after that i reboot the server and work correctly.
5. Today a customer make a call and tell me the /js directory is ampty and webserver cannot serve .it.
6. I mount a Borg Backup and overwrite the /js empty dir, but when i try to overwrite the dir, i receive an error about the file exist.
7. I mount the snapsnot using mount -t zfs on /mnt/zfs and navigate in js directory and seem its all ok.
8. I try scrub a pool, without any correction.
9. I rename /js directory in /pizza and reupload /js from backup.
10. i stop nginx and mariadb service, export pool, reimport pool and now i can see file inside /pizza directory and delete them

**Comment by MarcoMarcoaldi** [comment]
Today, we have the same error after rollback.

**Comment by MarcoMarcoaldi** [comment]
Hi,

I was able to replicate the error, and it appears to have occurred because the Nginx web server and PHP-FPM processes were not properly shut down before performing the rollback. I retried the operation after ensuring that both Nginx and PHP-FPM were correctly stopped, and the ZFS rollback worked perfectly this time.
