### ISSUE TITLE
build fails for kernel: 6.12.3-amd64 (x86_64): passing argument 2 of ‘dequeue_signal’ from incompatible pointer type

### ISSUE THREAD

**Issue by smr99** [openzfs/zfs#16847]
### System information

Type | Version/Name
 --- | 2.2.6 ---
Distribution Name	| Debian
Distribution Version	| sid
Kernel Version	| 6.12.3
Architecture	| x86_64
OpenZFS Version	| 2.2.6

### Describe the problem you're observing

Installing the Debian package zfs-dkms generates a kernel module for each installed kernel by compiling the sources.  For kernel 6.12.3, it fails.  The build has succeeded on 6.11 kernels up to 6.11.10.

### Describe how to reproduce the problem

Install Debian kernel 6.12.3 and zfs-dkms.

### Include any warning/errors/backtraces from the system logs

Excerpt from build log:
```
/var/lib/dkms/zfs/2.2.6/build/module/os/linux/spl/spl-thread.c: In function ‘issig’:
/var/lib/dkms/zfs/2.2.6/build/module/os/linux/spl/spl-thread.c:186:28: error: passing argument 1 of ‘dequeue_signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  186 |         if (dequeue_signal(task, &set, &__info) != 0) {
      |                            ^~~~
      |                            |
      |                            struct task_struct *
In file included from /usr/src/linux-headers-6.12.3-common/include/linux/rcuwait.h:6,
                 from /usr/src/linux-headers-6.12.3-common/include/linux/percpu-rwsem.h:7,
                 from /usr/src/linux-headers-6.12.3-common/include/linux/fs.h:33,
                 from /usr/src/linux-headers-6.12.3-common/include/linux/compat.h:17,
                 from /usr/src/linux-headers-6.12.3-common/arch/x86/include/asm/ia32.h:7,
                 from /usr/src/linux-headers-6.12.3-common/arch/x86/include/asm/elf.h:10,
                 from /usr/src/linux-headers-6.12.3-common/include/linux/elf.h:6,
                 from /usr/src/linux-headers-6.12.3-common/include/linux/module.h:19,
                 from /var/lib/dkms/zfs/2.2.6/build/include/os/linux/spl/sys/thread.h:27,
                 from /var/lib/dkms/zfs/2.2.6/build/module/os/linux/spl/spl-thread.c:26:

```

Note: full build log is available as attachment to Debian Bug report here: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1089488;filename=make.log;msg=5

**Comment by AllKind** [comment]
That's because version 2.2.6 does not support kernel 6.12. https://github.com/openzfs/zfs/blob/zfs-2.2.6/META
The upcoming 2.2.7 release will: https://github.com/openzfs/zfs/pull/16720

**Comment by n0xena** [comment]
until 2.2.7 gets released you can also use 2.3.0-rc3 - running it fine on 6.12.3 on arch here

**Comment by robn** [comment]
> until 2.2.7 gets released you can also use 2.3.0-rc3 - running it fine on 6.12.3 on arch here

Careful with this though: 2.3 has new pool features that 2.2 can't use, so if your intent is to eventually run 2.2.7, at least do not run `zpool upgrade`, but probably better to just wait.

**Comment by Golbinex** [comment]
@robn If I won't use any 2.3 features, is 2.3.0-rc3 pretty stable for use? 2.2.7 release takes long time without indication when it could get merged and my hardware is not compatible with 6.6 kernel.

**Comment by AllKind** [comment]
Another alternative is to pull https://github.com/tonyhutter/zfs/tree/zfs-2.2.7-hutter and build that (I don't think much else will be changed on that PR). I'm running it for a week now on 6.12.3.

**Comment by Golbinex** [comment]
@AllKind It's tricky to use different ZFS source on NixOS, but I managed to do it until 2.2.7 get's finally merged.
In case someone needs it:
```
let
  zfs_overlay = (self: super: {
    zfs = super.zfs.overrideAttrs (prev: {
      version = "2.2.7";
      src = pkgs.fetchFromGitHub {
        owner = "tonyhutter";
        repo = "zfs";
        rev = "e269af1b3c7b1b1c000d05f147a2f75e5e72e0ca";
        hash = "sha256-nFOB0/7YK4e8ODoW9A+RQDkZHG/isp2EBOE48zTaMP4=";
      };
    });
  });
  zfs_kernel_overlay = (self: super: {
      linuxPackages_6_12 = super.linuxPackages_6_12.extend (lpself: lpsuper: {
        zfs_2_2 = super.linuxPackages_6_12.zfs_2_2.overrideAttrs (oldAttrs: {
              src = pkgs.fetchFromGitHub {
                owner = "tonyhutter";
                repo = "zfs";
                rev ="e269af1b3c7b1b1c000d05f147a2f75e5e72e0ca";
                hash = "sha256-nFOB0/7YK4e8ODoW9A+RQDkZHG/isp2EBOE48zTaMP4=";
              };
              version = "2.2.7";
        });
      });
    });
in
{
  nixpkgs.config.allowBroken = true;
  nixpkgs.overlays = [ zfs_overlay zfs_kernel_overlay ];
}
```

**Comment by brneto** [comment]
Why is this closed if I still see the incompatibility between kernel 6.12.3 and zfs 2.3.1-1? What version of open zfs will be compatible with kernel 6.12.3 for debian bookworm?

**Comment by wearepariah** [comment]
any luck getting things working @brneto?
I am in the same boat.

**Comment by berchris-requiao-hpe** [comment]
@wearepariah I actually got it working. I simply got the ZFS modules from bookworm-backports which has a newer version. I noticed that the compilation fail for some reason but I just reinstalled it again and it worked on the second time and so far so good.
