### ISSUE TITLE
Linux 6.12 LTS support for zfs 2.3.0

### ISSUE THREAD

**Issue by jjpe** [openzfs/zfs#16850]
### Describe the feature would like to see added to OpenZFS

Now that Linux 6.12 has [officially](https://www.kernel.org/category/releases.html) been designated an LTS release, it would be nice if zfs 2.3.0 could add support for it before it's officially released.

### How will this feature improve OpenZFS?
It will improve OpenZFS by supporting the latest LTS kernel release, which would have positive downstream effects.
And in any case, I believe that Linux 6.12 LTS will be supported eventually anyway, so why not add it to 2.3.0, as that is not yet stable?

### Additional context
N/A

**Comment by amotin** [comment]
@jjpe 2.3.0-rc3/4 should already support 6.12.  The only question seems to be: when 2.3.0 get released, but hopefully soon.

**Comment by LunarLambda** [comment]
See also the [META](https://github.com/openzfs/zfs/blob/master/META) file and [the commit from Nov 21](https://github.com/openzfs/zfs/commit/225e76cd7d43939751bfbcdefaea28b58699cbf1)

2.3.0-rc3 (Nov 8) does not officially list support for 6.12. There is an [accepted pull request](https://github.com/openzfs/zfs/pull/16794) for 2.3.0-rc4 which will support 6.12.

**Comment by k3d3** [comment]
Is it safe to run 2.3.0-rc3, or is it still experimental?

**Comment by LunarLambda** [comment]
rc stands for "release candidate", it's neither experimental nor beta, but it may have bugs or other issues that need fixing before the proper 2.3.0 release. So basically a pre-release version for testing to see if the software is ready for the next release.

It should be fine to use but you may want to hold off on using the new features until 2.3.0 releases proper.

**Comment by k3d3** [comment]
Oh yeah, I know what RC means - I'm mainly asking because most project owners treat release candidates at fairly different readiness levels, especially the first RCs.

But good to know, thanks!

**Comment by devsk** [comment]
Is 6.12 support going to be added to zfs-2.2.x series? Or is it strictly 2.3.x only?

**Comment by LunarLambda** [comment]
As far as I know 2.3 does not have any backwards incompatible changes, so there's no reason to make a 2.2.x backport with 6.12 support

**Comment by robn** [comment]
> Is 6.12 support going to be added to zfs-2.2.x series? Or is it strictly 2.3.x only?

@devsk 2.2.7 (currently being prepped in https://github.com/openzfs/zfs/pull/16720) should have 6.12 support.

**Comment by AllKind** [comment]
I pulled and built the proposed patchset for 2.2.7 - https://github.com/tonyhutter/zfs/tree/zfs-2.2.7-hutter - and run it with kernel 6.12 without problems for some days now.

**Comment by tonyhutter** [comment]
zfs-2.2.7 was released today with 6.12 kernel support: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.7

**Comment by behlendorf** [comment]
zfs-2.3.0-rc4 has also been released with 6.12 kernel support: https://github.com/openzfs/zfs/releases/tag/zfs-2.3.0-rc4
