### ISSUE TITLE
Wrong information inside the zfs-create man page on the 2.1-release branch

### ISSUE THREAD

**Issue by makhomed** [openzfs/zfs#16891]
### System information
Type | Version/Name
 --- | ---
OpenZFS Version	| zfs-2.1.16-1

### Describe the problem you're observing

Wrong information inside the zfs-create man page on the 2.1-release branch

### Describe how to reproduce the problem

https://github.com/openzfs/zfs/blob/zfs-2.1-release/man/man8/zfs-create.8#L237-L243
```
.Ss ZFS Volumes as Swap
ZFS volumes may be used as swap devices.
After creating the volume with the
.Nm zfs Cm create Fl V
enable the swap area using the
.Xr swapon 8
command.
Swapping to files on ZFS filesystems is not supported.
```

This manual bug only present on the 2.1-release branch:

https://github.com/openzfs/zfs/blob/zfs-2.1-release/man/man8/zfs-create.8#L237-L243
 
Inside 2.2-release release branch this bug already fixed:
 
https://github.com/openzfs/zfs/blob/zfs-2.2-release/man/man8/zfs-create.8#L237-L239
 
Inside 2.3-release release branch this bug already fixed:
 
https://github.com/openzfs/zfs/blob/zfs-2.3-release/man/man8/zfs-create.8#L237-L239

P.S.

More details - in the OpenZFS FAQ - [Using a zvol for a swap device on Linux](https://openzfs.github.io/openzfs-docs/Project%20and%20Community/FAQ.html#id25) and ZFS issue https://github.com/openzfs/zfs/issues/7734

**Comment by amotin** [comment]
Anybody who care about 2.1 is always welcome to open a PR.  But the question are does anybody care, and will there be another 2.1 release for this to appear at.
