### ISSUE TITLE
ZFS 2.2.x on Rocky/Alma 9.5

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#16898]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux 9
Distribution Version	| 9.5
Kernel Version	| 5.14.0-503.19.1.el9_5.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.x

### Describe the problem you're observing
Installing ZFS on Rocky / Alma Linux 9.5 provides ZFS 2.1.16 by default. To use the newest 2.2.x release one has to enable the `testing` repo.

Is this the expected behavior? ie: ZFS 2.1.x is considered the correct long-term stable release for such long-term distros? Or it is better to use the 2.2.x repository (as the project is already moving to the 2.3.x release)?

### Describe how to reproduce the problem
`yum install zfs` on Rocky / Alma Linux 9.5

### Include any warning/errors/backtraces from the system logs

None

**Comment by tonyhutter** [comment]
> Is this the expected behavior? 

Yes it is.  And if history is any indication we will switch it over to the 2.2.x branch once 2.3.x has been stabilized for awhile. I see we switched RHEL 7 from 0.8.6 -> 2.0.5, for example.

**Comment by tonyhutter** [comment]
@akrherz that's correct.  The last 2.1 release was back in December 2024.  I would imagine we switch EL over to 2.2.x after the next 2.2 release.  Note that you can enable the `zfs-testing` or `zfs-testing-kmod` repo if you want the newer zfs version on EL.

**Comment by akrherz** [comment]
Thank you@tonyhutter and agreed, but you have to do some tricks to get 2.2 from zfs-testing and not get 2.3 as both are in that repo.

**Comment by tonyhutter** [comment]
@akrherz I've never used it - but I think you can use a combination of `dnf downgrade zfs-2.2.7` and `dnf versionlock zfs-2.2.7`.  `dnf versionlock` may be a plugin you have to install.
