### ISSUE TITLE
cannot destroy dataset: dataset is busy

### ISSUE THREAD

**Issue by seletskiy** [openzfs/zfs#1810]
I've see similar issues, but all of them were closed.

I'm experiencing such kind of problem right now:

```
# zfs destroy zroot/2013-10-15T065955229209
cannot destroy 'zroot/2013-10-15T065955229209': dataset is busy

# zfs umount zroot/2013-10-15T065955229209
cannot unmount 'zroot/2013-10-15T065955229209': not currently mounted

# zfs list | grep zroot/2013-10-15T065955229209
zroot/2013-10-15T065955229209                2.86G  25.0G  11.0G  /var/lib/heaver/instances/2013-10-15T065955229209

# umount /var/lib/heaver/instances/2013-10-15T065955229209
umount: /var/lib/heaver/instances/2013-10-15T065955229209: not mounted

# pacman -Qi zfs | grep Version
Version        : 0.6.1_3.9.9-1

# uname -a
Linux hub.host.s 3.9.9-1-apparmor #1 SMP PREEMPT Thu Jul 11 17:45:29 NOVT 2013 x86_64 GNU/Linux
```

It's quite annoying, because of I need to constantly reboot host to get it to work.

I can provide any debug information needed.

**Comment by WyseNynja** [comment]
Whatever fix was done here isn't enough for my case.

I ran `timedatectl set-ntp true` and then started running into this error on debian jessie with docker 17.06.1-ce. Now when I try to remove a dataset (when docker+zfs cleans up old containers) it errors. Following it with grep led me to systemd. Turning set-ntp to false works, but my clock is drifting so I would prefer not to do that. I'm not sure what the repercussions of changing `PrivateTmp=true` to something else are or even what file to change to do that. Any suggestions? I read the systemd bug report and they closed this as "not a bug." I think the fix might need to be in docker somewhere but am not sure about this.

Steps to reproduce:

1. On a debian Jessie host with docker 17.06.1-ce installed, run `timedatectl set-ntp true`

2. Create a docker-compose.yml:
```
version: '3'

volumes:
  data:

services:
  test:
    image: alpine
    command: tail -f /dev/null
    restart: always
    volumes:
      - data:/data/
```

3. Run `docker-compose up -d` and everything should work fine.

4. Now modify the docker-compose.yml so compose will want to restart it:
```
version: '3'

services:
  test:
    image: alpine
    command: tail -f /dev/null
    restart: always
```

5. Run `docker-compose up -d` again and it will fail the same way the original report showed:
```
$ docker-compose up -d
Recreating quick_test_1 ... 
Recreating quick_test_1 ... error

ERROR: for quick_test_1  driver "zfs" failed to remove root filesystem for 5f310a1d949f02084468a58142b8f00a70c7dce612076e188c3ba47d28dca737: exit status 1: "/sbin/zfs zfs destroy -r storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0" => cannot destroy 'storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0': dataset is busy


ERROR: for test  driver "zfs" failed to remove root filesystem for 5f310a1d949f02084468a58142b8f00a70c7dce612076e188c3ba47d28dca737: exit status 1: "/sbin/zfs zfs destroy -r storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0" => cannot destroy 'storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0': dataset is busy
```

```
# grep storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0 /proc/*/mounts
/proc/919/mounts:storage/docker/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0 /var/lib/docker/zfs/graph/01689fe6f409b0486a136023b150f4436d7d1a83bb9102d76970aa4e11cd82e0 zfs rw,relatime,xattr,noacl 0 0

# ps -p 919
  PID TTY          TIME CMD
  919 ?        00:00:00 systemd-timesyn
```

Let me know if I should open this task for the docker team instead. For now I'll disable ntp.

**Comment by heppu** [comment]
For me the problem was that the parent dataset had `canmount=on`. So doing:
```
zfs set canmount=off pool-0/parent
```
allowed me to run succesfully:
```
zfs destroy pool-0/parent/child
```
