### ISSUE TITLE
Folder created by zfs? is blocking mount process

### ISSUE THREAD

**Issue by androos** [openzfs/zfs#1827]
I Have a Gentoo Hardened 3.11 Server with all file systems but /boot as zfs. The System is up-to-date.
I have one pool which has zfs containers for /usr , /usr/portage and /usr/portage/distfiles

After every second boot, the folder /usr/portage exists and because of that the system fails to mount /usr with "directory not empty"
I have to remove the folder and boot up again to start my system.

rpool                              1,92T   763G   136K  none
rpool/BACKUP                       1,64T  1,28T   186G  /bak
rpool/GENTOO                       13,0G  15,0G   136K  none
rpool/GENTOO/distfiles             1,99G  5,01G  1,99G  /usr/portage/distfiles
rpool/GENTOO/portage                990M  6,03G   990M  /usr/portage
rpool/HOME                           10G  48,3G  1,75G  /home
rpool/ROOT                         85,6G  50,0G   136K  none
rpool/ROOT/rootfs                  35,6G  39,5G   499M  /
rpool/ROOT/rootfs/boot              500M   658M  20,3M  none
rpool/ROOT/rootfs/opt                 5G  4,99G  5,49M  /opt
rpool/ROOT/rootfs/tmp                 5G  5,00G   544K  /tmp
rpool/ROOT/rootfs/usr                 6G  4,58G  4,42G  /usr
rpool/ROOT/rootfs/var              18,6G  11,3G  1,68G  /var
rpool/ROOT/rootfs/var/tmp          5,64G  5,00G  3,30M  /var/tmp
rpool/ROOT/rootfs/var/tmp/portage   651M  2,36G   651M  /var/tmp/portage
rpool/SRV                           172G   763G  60,4G  /srv
rpool/SRV/VMAIL                      10G  44,6G  5,37G  /srv/vmail
rpool/SRV/mysql                     102G  97,4G  2,63G  /srv/mysql

**Comment by nashero** [comment]
This last solution is the only one that worked for us, ie editing the mount option by providing it an overlay switch. I had a large pool in the proxmox pve that stopped working after upgrade from ZoL 0.6.1 to 0.6.3, it refused to mount on the directory structure no matter which zpool or zfs command was tried. Then I edited the /etc/init.d/zfs as shown above and it worked like a charm. Thank you very much!
