### ISSUE TITLE
vdev_id and multiple disk enclosures

### ISSUE THREAD

**Issue by ramonfernandez** [openzfs/zfs#2074]
Greetings!

I've daisy-chained two MSA60 12-disk enclosures to a box running ZFS via a SAS1068E controller (the second port has a third MSA60 attached to it, so I've come to the point where I need the daisy-chaining). I use the vdev_id.conf displayed below. Using one enclosure per port I do get devices A1..A12 and B1..B12 in /dev/disk/by-vdev, but when the second enclosure is connected I don't get any more devices (ie: A13..A24).

The disks are recognized by the system (ie: I get /dev/sd?? nodes) and are accessible. I'm using 0.6.2-1~precise from the Ubuntu ppa on a 3.11.0-15-generic kernel (but this is not yet a production box so I'm open to trying other versions of ZFS).

Is this expected? Or am I doing something wrong? I can set up aliases for all new disks, but having vdev IDs is such a nice feature that I'm sad to not have it :-)

Thanks in advance fro any help you can provide!
Cheers,
Ramón.
# /etc/zfs/vdev_id.conf

multipath     no
topology      sas_direct
phys_per_port 4
channel 0c:00.0  0         A
channel 0c:00.0  1         B

**Comment by dbdavids** [comment]
I am having this issue as well with a supermicro storage server.  The second enclosure in the system is not being recognized by vdev as a second set of disks on the same channel and does not show up.  I am going to try the patch above (out of the box it is crashing on line 144 as s drop in vdev replacement) with the current 6.4 release.

**Comment by dbdavids** [comment]
As Ramon said earlier, with this code, you need to add:
	"sas_switch")
after line 133 to make this work.  I will submit this change back later.

**Comment by DeHackEd** [comment]
Just to add my $0.02, this fixes my chained enclosure problems as well. Supermicro's "front and back" enclosures (eg: <a href="https://www.supermicro.com/products/chassis/4U/847/SC847E16-R1K28JBOD.cfm">this beast</a>) uses distinct, chained expanders for the front and back sides so this fix is needed.

For quick reference 62f2d9ec744e7b6bb17011f4d54a7554ede8cb39 plus the syntax fix for the `case` statement works. I can make a quick patch that's rebased if needed.

**Comment by behlendorf** [comment]
@DeHackEd please do, let's get a PR open with the proposed fix.

**Comment by behlendorf** [comment]
The vdev_id support was extend some time ago to support multiple enclosures in various arrangements.  Closing.

**Comment by Nihlus** [comment]
How was this issue resolved? I'm looking at the current documentation for vdev_id to try and set up a daisy-chained enclosure configuration but I don't see any of the discussed solutions in there. I've been unable to find a proper configuration for this type of topology.

**Comment by behlendorf** [comment]
The changes in #11526 and #12660 were intended to support daisy-changed JBODs.

**Comment by Nihlus** [comment]
> The changes in #11526 and #12660 were intended to support daisy-changed JBODs.

Thanks! I didn't see the `multijbod` option documented anywhere, but using it appears to work fine. I am hitting the same issue as #16572, however (I have two head nodes accessing daisy-chained enclosures from opposite ends of the redundant path), so I'll continue the discussion there.
