### ISSUE TITLE
RAIDZ1: unable to replace a drive with itself

### ISSUE THREAD

**Issue by mcrbids** [openzfs/zfs#2076]
Trying to simulate failure scenarios with a 3+1 RAIDZ1 array in order to prepare for eventualities. 

```
# create spfstank raidz1 -o ashift=12 sda sdb sdc sdd 
# zfs create spfstank/part
# dd if=/dev/random of=/spfstank/part/output.txt bs=1024 count=10000
```

manually pull out /dev/sdc without shutting anything down. As expected, zpool status shows the drive in a bad state: 

```
# zpool status 
-- SNIP -- 
ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637  UNAVAIL     16   122     0  corrupted data
-- SNIP -- 
```

This status doesn't change when I re-insert the drive. So I want to simulate re-introducing a drive that's extremely incoherent relative to the state of the ZFS pool. So, making sure that the drive is "offline", I introduce a raft of changes: 

```
# zpool offline spfstank ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637
# dd if=/dev/zero of=/dev/disk/by-id/ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637 bs=1024 count=100000
```

102 MB of changes, to be exact. Now, I want to re-introduce the drive to the pool and get ZFS to work it out. At this point, the status of the drive is: 

```
# zpool status 
-- SNIP -- 
ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637  OFFLINE     16   122     0
-- SNIP -- 
```

I try to replace the drive with itself: 

```
# zpool replace spfstank ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637 -f 
cannot replace ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637 with ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637: ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637 is busy

# zpool replace spfstank /dev/sdc /dev/sdc -f 
invalid vdev specification
the following errors must be manually repaired:
/dev/sdc1 is part of active pool 'spfstank'

# zpool replace spfstank /dev/sdc  -f 
invalid vdev specification
the following errors must be manually repaired:
/dev/sdc1 is part of active pool 'spfstank'
```

I was able to "fix" this with: 

```
# zpool online spfstank ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637
# zpool clear spfstank
# /sbin/zpool scrub spfstank
```

During the scrub, the status of the drive changes: 

```
zpool status 
-- SNIP -- 
ata-WDC_WD40EZRX-00SPEB0_WD-WCC4E0546637  ONLINE       0     0     9  (repairing)
-- SNIP -- 
```

There doesn't seem to be a way to "replace" a known incoherent drive with itself.

**Comment by gordan-bobic** [comment]
It would be really handy to be able to do this without physically removing the disk. A prime example of the use case is when changing partitions around, e.g. dropping a partition to make more space for a zfs one.

**Comment by Spongman** [comment]
i'm running in to this as well. i don't understand, how is this not considered a bug any more?

labelclear is clearly broken: it's impossible to clear a partition that was created as part of a whole-disk pool.

**Comment by shevek** [comment]
I have this issue too. I can't labelclear an offline disk to reinsert it in the pool.

**Comment by shevek** [comment]
Workaround: `strace -e pread64 zdb -l $DEV >/dev/null`

Gives a bunch of offsets:
```
pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 0) = 262144
pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 262144) = 262144
pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 12000127614976) = 262144
pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 12000127877120) = 262144
```

Clout these offsets with `dd` and charlie's your uncle.

Here's your free firearm. You'll find what remains of your foot somewhere near the end of your leg.

**Comment by TheLinuxGuy** [comment]
> Clout these offsets with `dd` and charlie's your uncle.
> 
> Here's your free firearm. You'll find what remains of your foot somewhere near the end of your leg.

For the un-initiated, do you have a sample command and do we need to divide the numbers by the disk block size? e.g:  offset 12000127614976 from your example divided by 512 block size = 23437749248

**Comment by shevek** [comment]
You don't need optimality, just firepower. Use dd with byte units and no division is required. Anyway, I can't math.

**Comment by devZer0** [comment]
did anybody try wipefs? that also seems to be able to remove zfs information from the disks without overwriting as a whole...

**Comment by scintilla13** [comment]
I've tried wipefs -a and it doesn't work.

**Comment by dev-sngy** [comment]
> did anybody try wipefs? that also seems to be able to remove zfs information from the disks without overwriting as a whole...

According to the man page:

       When option -a is used, all magic strings that are visible for
       libblkid are erased. In this case the wipefs scans the device again
       after each modification (erase) until no magic string is found.

       Note that by default wipefs does not erase nested partition tables on
       non-whole disk devices.  For this the option --force is required.

So I tried:

    wipefs -all --force

But that didn't work for me...

**Comment by dev-sngy** [comment]
> Workaround: `strace -e pread64 zdb -l $DEV >/dev/null`
> 
> Gives a bunch of offsets:
> 
> ```
> pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 0) = 262144
> pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 262144) = 262144
> pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 12000127614976) = 262144
> pread64(8, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 12000127877120) = 262144
> ```
> 
> Clout these offsets with `dd` and charlie's your uncle.
> 
> Here's your free firearm. You'll find what remains of your foot somewhere near the end of your leg.

These sayings like "firearm" and "charlie's your uncle" are extremely not intuitive for a foreigner like me :( 

Can you provide a dd commands example for the more unlearned of us out here? (i.e. to clarify which parameter is used to do what from this strace output.)

Thanks in advance.

**Comment by shevek** [comment]
Translating the pread() results from MY drives roughly into dd commands gives:
```
dd if=/dev/zero of=$DEV bs=1 seek=0 count=262144
dd if=/dev/zero of=$DEV bs=1 seek=262144 count=262144
dd if=/dev/zero of=$DEV bs=1 seek=12000127614976 count=262144
dd if=/dev/zero of=$DEV bs=1 seek=12000127877120 count=262144
```
However, the pread() values will differ for YOUR drive(s), so I strongly recommend you learn to load and aim your own firearm. The trick with dd is to use bs=1 when you don't want performance and can't do mathematics (like me).

**Comment by mddeff** [comment]
@shevek - floor sufficiently swiss cheezed from weapons fire, and still no joy;

## Background
`dozer1` **had** 2 disks in mirror, `sds1` and `sdr1`.  At somepoint `sdl` (previously usb drive) was removed, and either through reboot or some other means, udev moved `sds` to `sdl`.  Disk is 14.6T; full DD would take 3.16 days.

## Initial status
```
[root@fs01 etc]# zpool status
  pool: dozer1
 state: DEGRADED
status: One or more devices has been taken offline by the administrator.
	Sufficient replicas exist for the pool to continue functioning in a
	degraded state.
action: Online the device using 'zpool online' or replace the device with
	'zpool replace'.
  scan: none requested
config:

	NAME                      STATE     READ WRITE CKSUM
	dozer1                    DEGRADED     0     0     0
	  mirror-0                DEGRADED     0     0     0
	    sdr                   ONLINE       0     0     0
	    17256646544208471230  OFFLINE      0     0     0  was /dev/sds1

```

## Trying to clear
```

[root@fs01 etc]# strace -e pread64 zdb -l /dev/sdl >/dev/null
pread64(5, "\0\1\0\0\0\0\0\0\1\0\0\0000\0\0\0\7\0\0\0\1\0\0\0\23\0\0\0doze"..., 13920, 0) = 13920
pread64(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 0) = 262144
pread64(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 262144) = 262144
pread64(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 16000900136960) = 262144
pread64(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 262144, 16000900399104) = 262144
+++ exited with 2 +++
[root@fs01 etc]# for f in 0 262144 16000900136960 16000900399104; do dd if=/dev/zero of=/dev/sdl bs=1 seek=$f count=262144; done
262144+0 records in
262144+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.507745 s, 516 kB/s
262144+0 records in
262144+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.508549 s, 515 kB/s
262144+0 records in
262144+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.499234 s, 525 kB/s
262144+0 records in
262144+0 records out
262144 bytes (262 kB, 256 KiB) copied, 0.496669 s, 528 kB/s

[root@fs01 etc]# partprobe /dev/sdl
### LSBLK shows sdl has no partitions, so far so good

[root@fs01 etc]# zpool replace -f dozer1 17256646544208471230 /dev/sdl
cannot replace 17256646544208471230 with /dev/sdl: /dev/sdl is busy, or device removal is in progress
### LSBLK shows:
...
sdl               8:176  0  14.6T  0 disk 
├─sdl1            8:177  0  14.6T  0 part 
└─sdl9            8:185  0     8M  0 part 
...
[root@fs01 etc]# zpool replace -f dozer1 17256646544208471230 /dev/sdl
invalid vdev specification
the following errors must be manually repaired:
/dev/sdl1 is part of active pool 'dozer1'
[root@fs01 etc]# zpool labelclear -f /dev/sdl1
/dev/sdl1 is a member (ACTIVE) of pool "dozer1"
```
When I try to offline/delete /dev/sdl1, ZFS says its not in the pool (I'm assuming because it's checking cache?).  When I try to add it, it checks the metadata and says its already part of the pool.


# Success!

So doing a `zpool detach dozer1 17256646544208471230` and then `zpool attach dozer1 /dev/sdr /dev/sdl` worked like a charm!  Crumbs for those who need it.  

That being said, the fact that `labelclear` doesn't work as intended is still an issue.

**Comment by newboydj169** [comment]
hi Deff,
when I issue this command, zpool will tell me:
cannot detach 6936166286967168998: no valid replicas
6936166286967168998 is the disk fault and I want to replace or remove.
any idea, thanks in advance.

Joe

> So doing a `zpool detach dozer1 17256646544208471230` and then `zpool attach dozer1 /dev/sdr /dev/sdl` worked like a charm! Crumbs for those who need it.
>

**Comment by HLeithner** [comment]
> Understandable as you're new to ZFS but this sounds like a bit of PEBKAC and not any fault of the underlying technology.

wrong assumption and sound aggressive but ok 

> If your disk has unrecoverable read or write errors which are surfacing as checksum errors in ZFS, you shouldn't be attempting to replace it with itself, you should be replacing it with a known-good spare.

Actually to check if the drive is defect or not is the challenge here, I replaced the drive with a new one and got the same problem so I moved the old disk to a new system and tested it on this. Since on the other system the drive worked without problems I moved it back to the original system in another drive bay, that worked. So it seems a cable, the controller or the backplane is broken. But I was unable to reuse the drive in the old raid because of the error above. I'm not sure if this is really a border case
 
> This robust and admin-friendly filesystem is trying to save your data from you yourself. This bug is a very low priority and unusual corner case. Let's not insult the thankless hard work of others in bug reports please.

That wasn't my intention, sorry if this sound like this. I really love zfs and how it evolves. The intention of my comment was to maybe increase the priority or at least to notices that this may not be an edge case.
