### ISSUE TITLE
Problem with upgrade from 0.6.2 (released version)

### ISSUE THREAD

**Issue by FransUrbo** [openzfs/zfs#2145]
I noticed this in https://github.com/zfsonlinux/grub/issues/9.

It _seems_ (still not absolutly verified) that there is a problem if/when the module is still 0.6.2, but the userland comes from HEAD. Or at least, that's the only thing I can think of this far.

```
debian:~# df -h .
Filesystem           Size  Used Avail Use% Mounted on
rpool/ROOT/debian-1   16G  1.2G   15G   8% /
debian:~# zpool status
  pool: rpool
 state: ONLINE
  scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        rpool                                    ONLINE       0     0     0
          ata-VBOX_HARDDISK_VBd6e3d348-7c453f68  ONLINE       0     0     0
          ata-VBOX_HARDDISK_VB49020f73-ef98ed15  ONLINE       0     0     0

errors: No known data errors
[... do the upgrade ...]
debian:~# zpool status
no pools available
debian:~# dmesg | grep ZFS:
[    2.363408] ZFS: Loaded module v0.6.2-525_gd584a01, ZFS pool version 5000, ZFS filesystem version 5
debian:~# dpkg -S `which zpool`
zfsutils: /sbin/zpool
debian:~# dpkg -l zfsutils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  zfsutils                          0.6.3-0.4~g0ad85e~whe amd64                 command-line tools to manage ZFS filesystems
```

After a reboot, the pool is back as it's supposed to.

**Comment by wom-bat** [comment]
I'm seeing the same issue after upgrading to 0.6.4

I see after boot:
   SPL: Loaded module v0.6.4-1b-wheezy
   ZFS: Loaded module v0.6.4-1.1-Z-wheezy, ZFS pool version 5000, ZFS filesystem version 5

Command:
Message:
Error:

Manually import the root pool at the command prompt and then exit.
Hint: Try: zpool import -R / -M
....
# zpool import -R / -N
# zpool status
no pools available
# zdb | head
bucket:
    version: 5000
    name: 'bucket'
    state: 0
    txg: 11288530


cmdline is:
BOOT_IMAGE=/vmlinuz-3.16.0-4-amd64 bootfs=bucket/ROOT/lemma-1 ro boot=zfs rootdelay=10

Help?
