### ISSUE TITLE
zfs normalization and file name length

### ISSUE THREAD

**Issue by user318** [openzfs/zfs#2234]
I have faced a problem when using zfs filesystem normalization option. If I have name which is fit into max file name size (255 bytes), but which canonical form is lager. Than I will receive errors "Operation unsupported" when trying to do operations with this name:

``` shell
# zfs get normalization rpool
NAME   PROPERTY       VALUE          SOURCE
rpool  normalization  formD          -
# str=ёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёё
# echo -n $str | wc -c
254
# touch $str
touch: cannot touch ‘ёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёёё’: Operation not supported
```

Documentation says that normalization does not change file name that will be stored. It is just used in comparing file mames.
I think that somewhere it uses the same limit for string size as for max file name. But normal form can be several times lager than file name. May be this code should somehow be reconsidered.

**Comment by tomboysweat** [comment]
I have met the same problem. Any help would be greatly appreciated. Thank you.
