### ISSUE TITLE
MMAP Optimization

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#225]
The current implementation fully supports mmap but the is some additional cleanup in the implementation which is desirable.

First off it would be best to update the readpage and writepage hooks to use zfs_fillpage and zfs_putapage respectively. This was not done initially because it was easier to use the existing zpl_common_read/write() calls. Updating zfs_fillpage and zfs_putapage to be Linux VM friendly will take a little bit of work, but the end result will be cleaner, faster code. So it's worth doing.

Second, the Linux port still uses the same trick as Solaris for mmap'ed files. That is two copies of the mmap'ed regression are kept, one in the page cache and one in the ARC. The ZFS code is very careful to keep the two synchronized but it is still a wart on the overall design. I believe I may be possible to unify the Linux page cache with the ZFS ARC removing this design issue. This would hopefully cleanup the mmap() code considerably by removing the need to synchronize the caches.

**Comment by pgassmann** [comment]
> Sent you a pull request for first optimization mentioned on this issue. Please review the code
> Pull Request: https://github.com/behlendorf/zfs/pull/300

Workin Link to pull request: #300
