### ISSUE TITLE
linux-3.15 feature: renameat2

### ISSUE THREAD

**Issue by tuxoko** [openzfs/zfs#2256]
linux-3.15 merge window has been closed. It introduced a new syscall `renameat2` which does cross rename between two files atomically. This is potentially quite useful, however it needs filesystem support.

I think we might want to implement it, so I open up this feature request issue.
I might try to dig into this myself, however probably not very soon. So feel free to comment if you'd like to pick it up.

Thanks

**Comment by haasn** [comment]
Hi. Just popping in to point out that openSuSE Tumbleweed currently bricks your system if `renameat2()` fails. So clearly, distros except this syscall to work to the extent of not even containing fallback code for it failing.

**Comment by cyphar** [comment]
I can revive the PR I originally worked on and was worked on by @snajpa (#9414).

**Comment by BtbN** [comment]
Same as https://github.com/openzfs/zfs/pull/9414 this can probably be finally closed?
Or is something still missing after https://github.com/openzfs/zfs/commit/86db35c447aa3f4cc848497d78d54ec9c985d1ed and https://github.com/openzfs/zfs/commit/dbf6108b4df92341eea40d0b41792ac16eabc514 ?

**Comment by cyphar** [comment]
This can be closed now that #14070 (the final version of the carried PR) has been merged.
