### ISSUE TITLE
File Attributes

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#229]
Internally ZFS already has all the code in place to correctly handle the file attributes (immutable/read-only/etc). They should even be enforced if you import a pool from a different platform with these attributes set. What's missing are the needed interfaces to userspace to manipulate them. Under Linux this is typically done with the lsattr/chattr utilities. However, the file attributes supported by these tools only partly overlap with the set of Solaris file attributes. That means we either need to write our own tool to manipulate them on Linux, or we need to port the Solaris utility. A prerequisite for this work will be to get the security policy handlers working to ensure only authorized users can manipulate the file attributes.

**Comment by CMCDragonkai** [comment]
@behlendorf Is there documentation or manual that lists which attributes are supported and what they do on a ZFS system?
