### ISSUE TITLE
Vdev reshaping (new feature)

### ISSUE THREAD

**Issue by pdemarino** [openzfs/zfs#2327]
Scanning through the library, I was struck by the fact that implementing a vdev reshaping function (a highly desirable idea, IMHO) might not be an impossible task, provided a few conditions are met, i.e., that a vdev is replaced with a larger one, and there is no overlap among devices. The Block Pointer Rewrite logic might not be necessary.

The logic I have in mind is the following:
1) Upon request for a reshape of a specific vdev, a new virtual vdev is created, that sits "on top" of the vdev to be reshaped.
2) This virtual vdev would have 2 leaf nodes: the old and the new vdev. It would direct all reads AND all writes to both leaf vdevs; and apply the usual automatic correction processes whenever reads don't match. This means that you will have achieved the on-disk restructuring once you've read all the data.
3) From this point, you treat the process as a resilver on the entire vdev.
4) Once the resilver is done, destroy the old vdev and put the leaf vdev back where it belongs as a top-level entity.

I am sure that the vdev "replace" logic would have to be handled with great care; but the other steps don't seem impossible: however, before I take a stab at trying to implement this (setting up a virtual machine etc.), I was hoping to get some feedback from the community on whether I'm missing something that would make attempting the entire enterprise a massive loss of time.

**Comment by GregorKopka** [comment]
@behlendorf (and others who might look at this)
necro post: we can send/recv snapshots, which will change BPs (since the data is then stored at a different location) without changing the data - so it should be possible to change/update block pointers.
