### ISSUE TITLE
File name too long. ZFS have the filename length limit?

### ISSUE THREAD

**Issue by x09** [openzfs/zfs#2344]
ZFS have the filename length limit?

[root@shadowbox WORK_DATA]# rpm -qa | grep zfs
zfs-dkms-0.6.2-1.el6.noarch
zfs-release-1-3.el6.noarch
dkms-2.2.0.3-14.zfs1.el6.noarch
zfs-0.6.2-1.el6.x86_64

[root@shadowbox WORK_DATA]# cat /etc/redhat-release
CentOS release 6.5 (Final)

[root@shadowbox WORK_DATA]# touch '/BOX/WORK_DATA/Map/Литератуа/Статьи_Отчеты_Квазигеология/Иванов Иван Иванович. - Сейсмостратиграфический анализ Южного полушария головного мозга (на примере песчаных залежей поверхности Марса в день лунного солнцестояния) - год издания 2212.pdf'

touch: cannot touch `/BOX/WORK_DATA/Map/Литератуа/Статьи_Отчеты_Квазигеология/Иванов Иван Иванович. - Сейсмостратиграфический анализ Южного полушария головного мозга (на примере песчаных залежей поверхности Марса в день лунного солнцестояния) - год издания 2212.pdf': File name too long

**Comment by vitlav** [comment]
It seems we have longname feature since ZFS 2.3.0 (see https://github.com/openzfs/zfs/pull/15921)
This feature allows creating files and directories with name up to 1023 bytes in length. 
It can be enabled via `zfs set longname=on <filesystem>`
Can we close the issue?
