### ISSUE TITLE
[dracut] zfs dracut related stuff should be updated to latest dracut release

### ISSUE THREAD

**Issue by alexxy** [openzfs/zfs#245]
Dracut related stuff should be updated to latest dracut release and merged to dracut upstream

**Comment by Rudd-O** [comment]
FransUrbo, there is no problem submitting the ZFS dracut module upstream, dracut only adds ZFS support to the initramfs if you actually are booting from a ZFS system or if you explicitly request that it be added.  It's just a bunch of scripts and other file systems have it too.
