### ISSUE TITLE
ZFS and vm.swappiness

### ISSUE THREAD

**Issue by CMCDragonkai** [openzfs/zfs#2538]
According to this answer http://unix.stackexchange.com/a/88820/56970

Tuning the `vm.swappiness` lower should make the kernel prefer to swap pages from file cache instead of anonymous pages. I think that means application memory is more likely to stay in in RAM then filesystem memory cache, when pages need to be evicted to swap.

How does this interact with ZFS? I'm curious specifically relating to this statement:

> Conversely setting the vm.swappiness to 0 will prevent the kernel from evicting anonymous pages in favour of pages from the file cache. This might be useful if programs do most of their caching themselves, which might be the case with some databases.

**Comment by kpande** [comment]
@behlendorf is this still the plan, to merge the ARC into the linux page cache?
