### ISSUE TITLE
ZFS on linux no xattr  for symbolic links

### ISSUE THREAD

**Issue by tac12** [openzfs/zfs#272]
It is possible to set xattr  for files and directories,  but not for symbolic links.

**Comment by jsoref** [comment]
Fwiw, while it appears that ZFS in theory supports this feature, afaict, it isn't actually usable for symbolic links w/ Linux as of today (Ubuntu Bionic):
* [StackExchange: extended attribute on symbolic link](https://unix.stackexchange.com/questions/16537/extended-attribute-on-symbolic-link
* [man 7 xattr](http://man7.org/linux/man-pages/man7/xattr.7.html)

I hit this while trying to use:
```
rsync -azx --stats -h -P \
 --no-specials --no-devices \
 --rsync-path='rsync --fake-super' \
 --numeric-ids \
 --delete-after
 path/to/backup backup@remotehost:/backups/hostname/
```
