### ISSUE TITLE
mmap of immutable file behaves differently on zfs vs. ext4/btrfs

### ISSUE THREAD

**Issue by jdsa** [openzfs/zfs#2724]
I use an application called Geeqie to view photos.

Geeqie cannot open files from zfs (0.6.3) when those files are marked immutable. However, it _can_ open them when marked immutable on ext4 or btrfs.

I'm not a programmer but I believe I traced it to this line in the Geeqie source:

```
il->mapped_file = mmap(0, il->bytes_total, PROT_READ|PROT_WRITE, MAP_PRIVATE, load_fd, 0);
```

This returns `MAP_FAILED` on zfs, but works on the other filesystems.

The offending part appears to be the `PROT_WRITE` flag.

Should zfs behave as the others do here?

**Comment by scineram** [comment]
Is this issue now Linux specific? Because now zfs_map() is not used on FreeBSD AFAIK.

**Comment by behlendorf** [comment]
@scineram that's probably a fair way to characterize it.  Let me tag this as a Linux specific issue for now and reopen it so we can continue to track it.  I don't think anything has changed in this regard.

**Comment by Low-power** [comment]
It isn't just a conformance issue; it creates real problem:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052472
