### ISSUE TITLE
CentOS 7:  Load the module manually by running 'insmod <location>/zfs.ko' as root.

### ISSUE THREAD

**Issue by kirantpatil** [openzfs/zfs#2732]
Hi,

I installed zfsonlinux on CentOS 7 using http://zfsonlinux.org/epel.html

Now if I try to do any operation it shows zfs module is not installed.

[root@fractal-2590f1 ~]# zpool list
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
[root@fractal-2590f1 ~]# zfs create
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
[root@fractal-2590f1 ~]# zfs list
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

I tried to find zfs.ko file and it is not generated, how should I fix it ?

[root@fractal-2590f1 ~]# uname -a
Linux fractal-2590f1.fractal.lan 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

**Comment by bala-v** [comment]
Hello, I am getting this same error on Amazon linux after configure, make and make install were successful:-

$ zpool status
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

$ rpm -qa |grep kernel
kernel-3.14.33-26.47.amzn1.x86_64
kernel-3.14.27-25.47.amzn1.x86_64
kernel-tools-3.14.33-26.47.amzn1.x86_64
kernel-headers-3.14.33-26.47.amzn1.x86_64
kernel-devel-3.14.33-26.47.amzn1.x86_64

Is the issue because kernel is below the tools, headers and devel versions?

**Comment by naisanza** [comment]
I'm having the same problem after building from source on CentOS 7

**Comment by behlendorf** [comment]
Make sure the kernel devel headers match the running kernel.  Additional debugging why why the modules can't be loaded can be found in `dmesg`.

**Comment by gilgamezh** [comment]
The problem is that you are installing a different version of kernel-dev.

I solved it with a `yum upgrade`

**Comment by bala-v** [comment]
I did rebooted the system and now the kernel and kernel-devel are matching, but still get the same error:-
$sudo rpm -qa |grep kernel
kernel-tools-3.14.33-26.47.amzn1.x86_64
kernel-devel-3.14.33-26.47.amzn1.x86_64
kernel-headers-3.14.33-26.47.amzn1.x86_64
kernel-3.14.33-26.47.amzn1.x86_64

@behlendorf - $dmesg |grep zfs returns nothing. Any other ideas?.

**Comment by behlendorf** [comment]
Exactly what is the error.  According to dmesg the module was loaded.

**Comment by bala-v** [comment]
@behlendorf - The step that helped was sudo modprobe zfs (after the kernel reboot with matching kernel, kernel-devel and headers). I am good now. Thanks.

**Comment by wriedel** [comment]
Hi Folks,
best would be to just uninstall zfs, spl and dmks and start from scratch. 
Had the same issue and this is how I solved it ;-)

[root@tank-odd ~]# zpool status
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

[root@tank-odd ~]# yum remove zfs
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.4-1.el7.centos will be erased
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================
 Package                            Arch                                  Version                                             Repository                           Size
========================================================================================================================================================================
Removing:
 zfs                                x86_64                                0.6.4-1.el7.centos                                  @zfs                                771 k

Transaction Summary
========================================================================================================================================================================
Remove  1 Package

Installed size: 771 k
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : zfs-0.6.4-1.el7.centos.x86_64                                                                                                                        1/1
  Verifying  : zfs-0.6.4-1.el7.centos.x86_64                                                                                                                        1/1

Removed:
  zfs.x86_64 0:0.6.4-1.el7.centos

Complete!

[root@tank-odd ~]# yum remove spl
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package spl.x86_64 0:0.6.4-1.el7.centos will be erased
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================
 Package                            Arch                                  Version                                             Repository                           Size
========================================================================================================================================================================
Removing:
 spl                                x86_64                                0.6.4-1.el7.centos                                  @zfs                                 47 k

Transaction Summary
========================================================================================================================================================================
Remove  1 Package

Installed size: 47 k
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : spl-0.6.4-1.el7.centos.x86_64                                                                                                                        1/1
  Verifying  : spl-0.6.4-1.el7.centos.x86_64                                                                                                                        1/1

Removed:
  spl.x86_64 0:0.6.4-1.el7.centos

Complete!

[root@tank-odd ~]# yum remove dmks
Loaded plugins: fastestmirror, langpacks
No Match for argument: dmks
No Packages marked for removal
[root@tank-odd ~]# yum remove dkms
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7 will be erased
--> Processing Dependency: dkms >= 2.2.0.2 for package: spl-dkms-0.6.4-1.el7.centos.noarch
--> Processing Dependency: dkms >= 2.2.0.3-20 for package: zfs-dkms-0.6.4-1.el7.centos.noarch
--> Running transaction check
---> Package spl-dkms.noarch 0:0.6.4-1.el7.centos will be erased
---> Package zfs-dkms.noarch 0:0.6.4-1.el7.centos will be erased
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================
 Package                              Arch                               Version                                                Repository                         Size
========================================================================================================================================================================
Removing:
 dkms                                 noarch                             2.2.0.3-30.git.7c3e7c5.el7                             @epel                             221 k
Removing for dependencies:
 spl-dkms                             noarch                             0.6.4-1.el7.centos                                     @zfs                              2.5 M
 zfs-dkms                             noarch                             0.6.4-1.el7.centos                                     @zfs                               11 M

Transaction Summary
========================================================================================================================================================================
Remove  1 Package (+2 Dependent packages)

Installed size: 14 M
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : zfs-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   1/3
  Erasing    : spl-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   2/3
  Erasing    : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                               3/3
  Verifying  : spl-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   1/3
  Verifying  : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                               2/3
  Verifying  : zfs-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   3/3

Removed:
  dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7

Dependency Removed:
  spl-dkms.noarch 0:0.6.4-1.el7.centos                                               zfs-dkms.noarch 0:0.6.4-1.el7.centos

Complete!

[root@tank-odd ~]# yum install zfs
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centosmirror.netcup.net
 * epel: mirror.fraunhofer.de
 * extras: centos.copahost.com
 * updates: centos.copahost.com
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.4-1.el7.centos will be installed
--> Processing Dependency: zfs-kmod = 0.6.4 for package: zfs-0.6.4-1.el7.centos.x86_64
--> Processing Dependency: spl = 0.6.4 for package: zfs-0.6.4-1.el7.centos.x86_64
--> Running transaction check
---> Package spl.x86_64 0:0.6.4-1.el7.centos will be installed
--> Processing Dependency: spl-kmod = 0.6.4 for package: spl-0.6.4-1.el7.centos.x86_64
---> Package zfs-dkms.noarch 0:0.6.4-1.el7.centos will be installed
--> Processing Dependency: dkms >= 2.2.0.3-20 for package: zfs-dkms-0.6.4-1.el7.centos.noarch
--> Running transaction check
---> Package dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7 will be installed
---> Package spl-dkms.noarch 0:0.6.4-1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================================================================
 Package                              Arch                               Version                                                 Repository                        Size
========================================================================================================================================================================
Installing:
 zfs                                  x86_64                             0.6.4-1.el7.centos                                      zfs                              315 k
Installing for dependencies:
 dkms                                 noarch                             2.2.0.3-30.git.7c3e7c5.el7                              epel                              77 k
 spl                                  x86_64                             0.6.4-1.el7.centos                                      zfs                               26 k
 spl-dkms                             noarch                             0.6.4-1.el7.centos                                      zfs                              423 k
 zfs-dkms                             noarch                             0.6.4-1.el7.centos                                      zfs                              1.8 M

Transaction Summary
========================================================================================================================================================================
Install  1 Package (+4 Dependent packages)

Total download size: 2.6 M
Installed size: 15 M
Is this ok [y/d/N]: y
Downloading packages:
(1/5): dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch.rpm                                                                                                |  77 kB  00:00:00
(2/5): spl-0.6.4-1.el7.centos.x86_64.rpm                                                                                                         |  26 kB  00:00:01
(3/5): spl-dkms-0.6.4-1.el7.centos.noarch.rpm                                                                                                    | 423 kB  00:00:01
(4/5): zfs-0.6.4-1.el7.centos.x86_64.rpm                                                                                                         | 315 kB  00:00:05
(5/5): zfs-dkms-0.6.4-1.el7.centos.noarch.rpm                                                                                                    | 1.8 MB  00:00:05
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                   373 kB/s | 2.6 MB  00:00:07
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                               1/5
  Installing : spl-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   2/5
Removing old spl-0.6.4 DKMS files...

------------------------------
Deleting module version: 0.6.4
completely from the DKMS tree.
------------------------------
Done.
Loading new spl-0.6.4 DKMS files...
Building for 3.10.0-229.1.2.el7.x86_64
Building initial module for 3.10.0-229.1.2.el7.x86_64
Done.

spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/
Adding any weak-modules

depmod...

DKMS: install completed.
  Installing : spl-0.6.4-1.el7.centos.x86_64                                                                                                                        3/5
  Installing : zfs-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   4/5
Removing old zfs-0.6.4 DKMS files...

------------------------------
Deleting module version: 0.6.4
completely from the DKMS tree.
------------------------------
Done.
Loading new zfs-0.6.4 DKMS files...
Building for 3.10.0-229.1.2.el7.x86_64
Building initial module for 3.10.0-229.1.2.el7.x86_64
Done.

zavl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

znvpair.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

zunicode.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

zcommon.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/

zpios.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-229.1.2.el7.x86_64/extra/
Adding any weak-modules

depmod...

DKMS: install completed.
  Installing : zfs-0.6.4-1.el7.centos.x86_64                                                                                                                        5/5
  Verifying  : spl-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   1/5
  Verifying  : spl-0.6.4-1.el7.centos.x86_64                                                                                                                        2/5
  Verifying  : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                               3/5
  Verifying  : zfs-dkms-0.6.4-1.el7.centos.noarch                                                                                                                   4/5
  Verifying  : zfs-0.6.4-1.el7.centos.x86_64                                                                                                                        5/5

Installed:
  zfs.x86_64 0:0.6.4-1.el7.centos

Dependency Installed:
  dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7      spl.x86_64 0:0.6.4-1.el7.centos      spl-dkms.noarch 0:0.6.4-1.el7.centos      zfs-dkms.noarch 0:0.6.4-1.el7.centos

Complete!

[root@tank-odd ~]# zpool status
no pools available

**Comment by brian-lamb-software-engineer** [comment]
Im going to give you all a tip here. Alot of times, the issue is mostly that the kernel has been updated, which will then break the entire dkms/spl/zfs infrastructure until `zfsonlinux`  gets an update for that kernel.  

So, the only thing you can normally do at that point is revert your kernel when you accidentally let yum kernel update run before the correct zfs libs have been released for that kernel yet.  

This will cause zfs downtime.   You will then need to wait it out, usually a few weeks, or revert kernel.
