### ISSUE TITLE
Cannot specify different NFS share options for multiple hosts

### ISSUE THREAD

**Issue by nitro322** [openzfs/zfs#2773]
I'm not sure if this is a bug or just my misunderstanding of how to do this, but it doesn't appear to be possible to specify different export options for multiple hosts for a single filesystem.  For example:

zfs set sharenfs='rw=@host1.home.net,no_subtree_check,no_root_squash,rw=@host2.home.net,no_subtree_check,root_squash,' data

I want my data filesystem to be exported to host1 w/ full read-write access, including root.  However, I want host2 to have read-write access only for standard users, NOT root.

The above sharenfs parameters do let me mount the data share from both host1 and host2, but I get root write access is denied on both host1 and host2.  It appears that the root_squash at the end of the list for host2 is overriding the no_root_squash option for host1, as if I change it to no_root-squash or just remove it altogether then both host1 and host2 can write.

I guess this makes sense sense the above parameter list is entirely comma-delimited (so how would ZFS know to apply the second set of options only to host2?), but I can't find any other way to make the share work.  I tried using a colon, semi-colon, parentheses, etc. to delimit the two hosts, but I get an "invalid options" message every time I try anything different.

Am I missing something obvious here, or is this a current limitation?  If the latter, is there any way to work around this (preferrably without switching to doing everything through /etc/exports, because I've already encountered limitations there that pushed me back to using ZFS' sharenfs :-) )?

Thanks.

**Comment by ptx0** [comment]
FWIW this is still an ongoing issue

**Comment by dave-fl** [comment]
Attempting to bring my existing OmniOS pool into ZOL and am seeing this:

zfs cannot share share(1M) failed

Investigating I noticed I cannot set using the same options eg.

zfs set sharenfs=rw=@10.250.0.3/32:@10.255.0.55/32,root=@10.250.0.3/32   somedataset

Is this not supported?

**Comment by gerardba** [comment]
This is still an issue on 0.7.12. Is there a workaround that allows using the sharenfs property on the 0.7 or 0.8 branch?
Using sharenfs comes useful when the zpool can move across servers (eg. for DR/HA).
