### ISSUE TITLE
Fedora 21 Repository

### ISSUE THREAD

**Issue by maci0** [openzfs/zfs#2782]
Hi, I think it is time to create a Fedora 21 repository so people who are testing the alpha/beta releases can use ZoL as well. Other 3rd party repos like rpmfusion already have F21 repositories.

**Comment by qualar2** [comment]
Back from my holidays and I've still not got this working, according to http://open-zfs.org/wiki/Features hole_birth is not supported on ZFSonLinux so how did the feature ever get enabled? (I've only had Gentoo and Fedora talking to the drives).

The documentation says features cannot be disable once enabled, is there a work around as I've probably not used these features?

Paul

**Comment by qualar2** [comment]
Ah, I see references to hole_birth in my git checked out version of ZFS, so I'm going to install that version and hope the kernel doesn't crash (not panicing though)

**Comment by ozialien** [comment]
Been using ZFS on Fedora without any problems up to 20 but 21 is a problem child.   After a while the systems disk I/O across the board siezes up and zfs pools are stuck.   No dmesg no specific I/O failure message etc...  Wondered if anybody had experienced this.

**Comment by qualar2** [comment]
Yes @ozialien , every few days (3-5) I come to a hung system in the morning. I also find the garbage collector isn't freeing up space. If I "zfs umount -a" and re-mount them every night, then both problems go away.

**Comment by behlendorf** [comment]
Those issues are very likely due to kernel side changes which have been addressed in master.  Once 0.6.4 rolls out to the repositories those issues should be addressed.  Alternately you _could_ roll back your kernel.
