### ISSUE TITLE
L2arc checksum errors

### ISSUE THREAD

**Issue by ColdCanuck** [openzfs/zfs#2879]
I have noticed that the L2 checksum error count as reported by /proc/spl/kstat/zfs/arcstats  l2_cksum_bad starts to show non-zero after the L2cache has been filled and wraps around.

I have observed this on three different machines with three different cache devices (SSD, /dev/zram, and  a file backed block device mounted on /dev/loop.  In all cases there are zero errors until the L2cache fills and presumably wraps around.

zfs version is 0.6.3 from Darik's PPA for Ubuntu 12.04
dmesg | grep ZFS
[    6.521205] ZFS: Loaded module v0.6.3-2~precise, ZFS pool version 5000, ZFS filesystem version 5

kernel is:
Linux version 3.5.0-54-generic (buildd@allspice) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014

The phenomenon is independent of cache size, i've tried 4, 8 and 64GB sizes.

L2arc compression is on

cat /sys/module/zfs/parameters/l2arc_nocompress 
0

Since it happens on three very different types of block devices, and on different machines, I don't think the underlying device is causing data corruption. My guess would be a bug in the "wrap code", but that's only from the fact that the errors start to accumulate once the underlying block device has been filled.

My hope is that this just lowers the cache efficiency; the data with the bad checksum is simply ignored.

**Comment by hunleyd** [comment]
Just curious if you were able to repro this @maci0 as I'm seeing it on my zram-based l2arc as well (uptime ~25 days):
l2_cksum_bad                    4    1950160
l2_io_error                     4    0

and yes, my l2arc dev is added after a reboot (by a systemd service script, if it matters)

**Comment by maci0** [comment]
in the past i have had problems with zram and other filesystems.. those boiled down to the need to use the systems PAGESIZE as blocksize for the FS.. maybe that applies here as well...
