### ISSUE TITLE
Writes to sparse volumes do not return errors on full zpool

### ISSUE THREAD

**Issue by JKDingwall** [openzfs/zfs#2889]
This was initially raised at https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/sIj_G2WmLbk

Once a zpool is full then instead of an IO error being returned to a writing application the writes disappear in to some void with just a kernel log message to indicate a problem.  The commands which illustrate this are:

root@zyub1204:~# zfs list
NAME        USED  AVAIL  REFER  MOUNTPOINT
diskconvm   398K  31.3G    30K  /diskconvm

root@zyub1204:~# zfs create -V 28G diskconvm/filler
root@zyub1204:~# zfs list
NAME               USED  AVAIL  REFER  MOUNTPOINT
diskconvm         28.9G  2.37G    30K  /diskconvm
diskconvm/filler  28.9G  31.3G    16K  -

root@zyub1204:~# zfs create -s -V 2G diskconvm/sparse
root@zyub1204:~# zfs list
NAME               USED  AVAIL  REFER  MOUNTPOINT
diskconvm         28.9G  2.37G    30K  /diskconvm
diskconvm/filler  28.9G  31.3G    16K  -
diskconvm/sparse    16K  2.37G    16K  -

root@zyub1204:~# zfs snapshot diskconvm/sparse@origin
root@zyub1204:~# zfs list
NAME                      USED  AVAIL  REFER  MOUNTPOINT
diskconvm                28.9G  2.37G    30K  /diskconvm
diskconvm/filler         28.9G  31.3G    16K  -
diskconvm/sparse           16K  2.37G    16K  -
diskconvm/sparse@origin      0      -    16K  -

root@zyub1204:~# dd if=/dev/urandom of=/dev/diskconvm/sparse bs=1M count=1536
1536+0 records in
1536+0 records out
1610612736 bytes (1.6 GB) copied, 196.857 s, 8.2 MB/s
root@zyub1204:~# zfs list
NAME                      USED  AVAIL  REFER  MOUNTPOINT
diskconvm                30.4G   875M    30K  /diskconvm
diskconvm/filler         28.9G  29.7G    16K  -
diskconvm/sparse         1.52G   875M  1.52G  -
diskconvm/sparse@origin    15K      -    16K  -

root@zyub1204:~# zfs snapshot diskconvm/sparse@backup1
root@zyub1204:~# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
diskconvm                 30.4G   875M    30K  /diskconvm
diskconvm/filler          28.9G  29.7G    16K  -
diskconvm/sparse          1.52G   875M  1.52G  -
diskconvm/sparse@origin     15K      -    16K  -
diskconvm/sparse@backup1      0      -  1.52G  -

root@zyub1204:~# strace dd if=/dev/urandom of=/dev/diskconvm/sparse bs=1M count=1024 2>&1 | tee /tmp/dd-strace.log
...
read(0, "\302\3\37\256\212\343\215I\241_\264:\20\\0373\357\316H\3\356\37\346\214`\252\177Y\337u\346>"..., 1048576) = 1048576
write(1, "\302\3\37\256\212\343\215I\241_\264:\20\\\0373\357\316H\3\356\37\346\214`\252\177Y\337u\346>"..., 1048576) = 1048576
close(0)                                = 0
close(1)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f959b12e000
read(0, "# Locale name alias data base.\n#"..., 4096) = 2570
read(0, "", 4096)                       = 0
close(0)                                = 0
munmap(0x7f959b12e000, 4096)            = 0
open("/usr/share/locale/en_GB/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_GB/LC_MESSAGES/coreutils.mo", O_RDONLY) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=15001, ...}) = 0
mmap(NULL, 15001, PROT_READ, MAP_PRIVATE, 0, 0) = 0x7f959b12b000
close(0)                                = 0
open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=619, ...}) = 0
mmap(NULL, 619, PROT_READ, MAP_PRIVATE, 0, 0) = 0x7f959b12a000
close(0)                                = 0
write(2, "1024+0 records in\n1024+0 records"..., 371024+0 records in
1024+0 records out
) = 37
write(2, "1073741824 bytes (1.1 GB) copied", 321073741824 bytes (1.1 GB) copied) = 32
clock_gettime(CLOCK_MONOTONIC, {638917, 302156157}) = 0
write(2, ", 261.924 s, 4.1 MB/s\n", 22, 261.924 s, 4.1 MB/s
) = 22
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

In kernel log:
[638914.184668] end_request: critical space allocation error, dev zd16, sector 1963008

root@zyub1204:~# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
diskconvm                 31.3G      0    30K  /diskconvm
diskconvm/filler          28.9G  28.9G    16K  -
diskconvm/sparse          2.37G      0  1.52G  -
diskconvm/sparse@origin     15K      -    16K  -
diskconvm/sparse@backup1   873M      -  1.52G  -

root@zyub1204:~# zfs snapshot diskconvm/sparse@backup2
cannot create snapshots : out of space

Assuming urandom is random enough then all the 1024Gb that was written should have been transferred to the snapshot.
The volume may have continued because it was overwriting space previously allocated.  So if we try to write 2Gb which
will run in to the unreferenced space we really should see a failure...

root@zyub1204:~# strace dd if=/dev/urandom of=/dev/diskconvm/sparse bs=1M count=2048 2>&1 | tee /tmp/dd-strace.log
...
read(0, "4U\213yp\215\26\230\377`\357\372\246\243\36\250\203\211\212C\364\354RHr|L\244\36\10\375\273"..., 1048576) = 1048576
write(1, "4U\213yp\215\26\230\377`\357\372\246\243\36\250\203\211\212C\364\354RHr|L\244\36\10\375\273"..., 1048576) = 1048576
read(0, "\214\302S\337Vg\217]\37J)t!\vKn%.a\337)z\1Uftp\363\300a0\235"..., 1048576) = 1048576
write(1, "\214\302S\337Vg\217]\37J)t!\vKn%.a\337)z\1Uftp\363\300a0\235"..., 1048576) = 1048576
read(0, "\25%=\0252\276.\203\254\332\202V\302OJo_\326\340\251\%T\311\327PEb\362\355\303\36"..., 1048576) = 1048576
write(1, "\25%=\0252\276.\203\254\332\202V\302OJo_\326\340\251\%T\311\327PEb\362\355\303\36"..., 1048576) = 1048576
close(0)                                = 0
close(1)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f870431b000
read(0, "# Locale name alias data base.\n#"..., 4096) = 2570
read(0, "", 4096)                       = 0
close(0)                                = 0
munmap(0x7f870431b000, 4096)            = 0
open("/usr/share/locale/en_GB/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_GB/LC_MESSAGES/coreutils.mo", O_RDONLY) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=15001, ...}) = 0
mmap(NULL, 15001, PROT_READ, MAP_PRIVATE, 0, 0) = 0x7f8704318000
close(0)                                = 0
open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = 0
fstat(0, {st_mode=S_IFREG|0644, st_size=619, ...}) = 0
mmap(NULL, 619, PROT_READ, MAP_PRIVATE, 0, 0) = 0x7f8704317000
close(0)                                = 0
write(2, "2048+0 records in\n2048+0 records"..., 372048+0 records in
2048+0 records out
) = 37
write(2, "2147483648 bytes (2.1 GB) copied", 322147483648 bytes (2.1 GB) copied) = 32
clock_gettime(CLOCK_MONOTONIC, {639559, 693860672}) = 0
write(2, ", 382.147 s, 5.6 MB/s\n", 22, 382.147 s, 5.6 MB/s
) = 22
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
root@zyub1204:~# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
diskconvm                 31.3G      0    30K  /diskconvm
diskconvm/filler          28.9G  28.9G    16K  -
diskconvm/sparse          2.37G      0  1.52G  -
diskconvm/sparse@origin     15K      -    16K  -
diskconvm/sparse@backup1   873M      -  1.52G  -

**Comment by bprotopopov** [comment]
@behlendorf, @GregorKopka, @JKDingwall, 

I may be missing something, but I think there is a minor issue with the experiment; in order to see the I/O errors on full pool condition, one needs to either use O_DIRECT or fsync() when writing to the zvol. Otherwise, the write goes through the page cache, and by the time the I/O error for a page arises, the write that issued it is long gone.

I recommend repeating the experiments using the following command:

```
dd if=/dev/urandom of=/dev/diskconvm/sparse bs=1M count=1536 oflag=direct
```

**Comment by bprotopopov** [comment]
Here is a quick test I ran on a small pool:
```
[root@centos-6 build]# zpool create tpool /tmp/1 /tmp/2
[root@centos-6 build]# zfs create -V1T -s -b 64k tpool/zvol
[root@centos-6 build]# dd if=/dev/urandom of=/dev/zvol/tpool/zvol bs=1M count=200 oflag=direct conv=fdatasync
dd: writing `/dev/zvol/tpool/zvol': Input/output error
129+0 records in
128+0 records out
134217728 bytes (134 MB) copied, 28.9681 s, 4.6 MB/s
[root@centos-6 build]# zpool status -v
  pool: tpool
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	tpool       ONLINE       0     0     0
	  /tmp/1    ONLINE       0     0     0
	  /tmp/2    ONLINE       0     0     0

errors: No known data errors
[root@centos-6 build]# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tpool   160M   128M  31.7M         -    65%    80%  1.00x  ONLINE  -
  /tmp/1    80M  63.8M  16.2M         -    66%    79%
  /tmp/2    80M  64.5M  15.5M         -    65%    80%
```
