### ISSUE TITLE
Debian sources.list

### ISSUE THREAD

**Issue by markdesouza** [openzfs/zfs#2913]
When installing  zfsonlinux_3~wheezy_all.deb, it creates an apt sources.list entry: 
deb http://archive.zfsonlinux.org/debian wheezy main

As zfs appears to no longer appears to host i386 packages, this needs to be:
deb [arch=amd64] http://archive.zfsonlinux.org/debian wheezy main

**Comment by allentiak** [comment]
Should this one be closed?

**Comment by FransUrbo** [comment]
> Should this one be closed?
> 
Yes.
