### ISSUE TITLE
Inappropriate error with 'zfs diff' if filesystem is not mounted

### ISSUE THREAD

**Issue by jvsalo** [openzfs/zfs#3325]
Version: at least 0.6.4 affected

If you execute 'zfs diff' between 2 snapshots of a filesystem-dataset, but the dataset is not mounted, you get:

`Cannot diff an unmounted snapshot: operation not applicable to datasets of this type`

1) It does not matter/help if the snapshot(s) are mounted. It only matters whether the FS is mounted.
2) The operation is certainly applicable to datasets of this type.

After mounting the filesystem, 'zfs diff' operates correctly.

**Comment by gmelikov** [comment]
Close as stale.

If it's actual - feel free to reopen.

**Comment by lostdj** [comment]
Still present in 0.8.0-rc3. Getting exactly the same error under the same circumstances.

**Comment by tomposmiko** [comment]
The same here.

**Comment by AceSlash** [comment]
Same on 0.8.3 .
```
# zfs create tank/test
# zfs get mountpoint tank/test
NAME       PROPERTY    VALUE       SOURCE
tank/test  mountpoint  none        inherited from tank
# zfs snapshot tank/test@1
# zfs snapshot tank/test@2
# zfs diff tank/test@1 tank/test@2
Cannot diff an unmounted snapshot: operation not applicable to datasets of this type
```

**Comment by darrenfreeman** [comment]
I just hit this with 0.8.4, and it was sufficiently confusing as to make me search for an explanation for that error message. I first tried mounting both snapshots, and that didn't solve the problem.

The error message is confusing, it should state that the operation would succeed if the dataset were mounted.

**Comment by risner** [comment]
Still an issue on FreeBSD 13.0:
root@OLDcore:/home/risner/.ssh # zfs --version
zfs-2.0.0-FreeBSD_gf11b09dec
zfs-kmod-2.0.0-FreeBSD_gf11b09dec

Unmounted poudriere jails:
# zfs diff datatank/poudriere/jails@to_new datatank/poudriere/jails@final
Cannot diff an unmounted snapshot: operation not applicable to datasets of this type

**Comment by h1z1** [comment]
Haven't bisected it but this doesn't happen with 2.1.

```
# zfs create thumper/test
# zfs snapshot thumper/test@1
# zfs snapshot thumper/test@2
# zfs diff thumper/test@1 thumper/test@2
# zfs -V
zfs-2.1.99-1
zfs-kmod-2.1.99-1
#
```

**Comment by siilike** [comment]
You are forgetting to unmount the dataset after creating it.
