### ISSUE TITLE
zfs module busy infinite loop: vmap allocation [...] failed

### ISSUE THREAD

**Issue by sehe** [openzfs/zfs#34]
A reboot is required (SysRq+B)

<pre>
bash$ zpool create inkernel /dev/sda3
</pre>

or sometime later:

<pre>
bash$ zfs create inkernel/zfs
bash$ zfs create inkernel/data
bash$ cat zfs.pool_repl | mbuffer -m 180M | zfs receive -vFd inkernel/zfs
receiving full stream of zfs@crossedover into inkernel/zfs@crossedover
received 22.5KB stream in 1 seconds (22.5KB/sec)
receiving incremental stream of zfs@replicate into inkernel/zfs@replicate
received 20.6KB stream in 1 seconds (20.6KB/sec)
in @  160 MB/s, out @  177 kB/s,  124 kB total, buffer  62% fullreceiving full stream of zfs/BUDGETTEER@ec2 into inkernel/zfs/BUDGETTEER@ec2
in @  0.0 kB/s, out @  0.0 kB/s,  588 kB total, buffer 100% full
</pre>

Hangs forever, 1 CPU core stuck at 100% and the log is flooded with messages:

<pre>
Jul 16 00:26:27 localhost kernel: [  969.528505] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528509] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528512] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528516] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528519] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528523] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528526] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528530] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528534] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:27 localhost kernel: [  969.528537] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532504] __ratelimit: 2515704 callbacks suppressed
Jul 16 00:26:32 localhost kernel: [  974.532505] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532509] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532513] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532516] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532520] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532523] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532527] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532530] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532534] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:32 localhost kernel: [  974.532537] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536503] __ratelimit: 2500972 callbacks suppressed
Jul 16 00:26:37 localhost kernel: [  979.536505] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536509] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536512] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536516] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536520] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536523] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536527] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536530] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536534] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:37 localhost kernel: [  979.536538] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540504] __ratelimit: 2505043 callbacks suppressed
Jul 16 00:26:42 localhost kernel: [  984.540506] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540509] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540513] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540516] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540520] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
Jul 16 00:26:42 localhost kernel: [  984.540524] vmap allocation for size 8392704 failed: use vmalloc=<size> to increase size.
</pre>

sda3 is a 19.62GiB SSD partition.

Versions:
SPL

<pre>
sehe@lucid:~/custom/spl/cmd$ git log -1 --oneline; git describe --dirty
8f813bb Proposed fix for oops on SIGINT in splat atomic:64-bit test.
spl-0.4.9-36-g8f813bb
</pre>

ZFS

<pre>
sehe@lucid:~/custom/kernelzfs$ git log -1 --oneline ; git describe --dirty
21191af Merge commit 'refs/top-bases/top' into top
zfs-0.4.9-1968-g21191af-dirty
</pre>

Stock pae kernel, 8GB RAM, free:

<pre>
sehe@lucid:/tmp$ uname -a
Linux lucid 2.6.32-23-generic-pae #37-Ubuntu SMP Fri Jun 11 09:26:55 UTC 2010 i686 GNU/Linux
</pre>

This may be related to splat failure reported in http://github.com/behlendorf/spl/issues#issue/24

**Comment by CurlyMoo** [comment]
I experience the same issues on a Hummingboard Pro with a 32bit Quad Core and 4GB ram.

>  If that doesn't work real 64-bit hardware is the only fix in the short term.

Would using a Raspberry Pi 3 with a 64bit OS solve the issue despite the 1GB ram? Or do we need to look for a Intel or AMD solution?

**Comment by behlendorf** [comment]
@CurlyMoo any 64-bit kernel will address the majority of the vmalloc() issues.
