### ISSUE TITLE
Support swap on zvol

### ISSUE THREAD

**Issue by pendor** [openzfs/zfs#342]
Currently placing swap inside a zvol leads to deadlocks and system death as soon as memory usage grows into swap.  Running ZFS with full-device for a root pool will require swap on zvol for systems that require (or prefer to have) swap.  Supporting this isn't critical priority as the system can always be setup with dedicated swap partitions and ZFS on a partition of its own, but running on full device can give better performance and is more in line with "The ZFS Way".

Discussion on this is present here:

http://groups.google.com/a/zfsonlinux.org/group/zfs-discuss/browse_thread/thread/699693ebd2706b45#

Lock can be reproduced with:

```
zpool create rpool mirror sda sdb
zfs create -V 2G rpool/swap
mkswap /dev/rpool/swap
swapon /dev/rpool/swap
memtester 1800m # Some value near the max free in your system
cd /usr/src/linux && make clean && make -j20 # Do something that will hit memory a lot
```

**Comment by CMCDragonkai** [comment]
Has anybody tried using a sparse ZVOL as the swap space? There's a blog post talking about it: http://blog.thilelli.net/post/2011/08/03/Interesting-Use-Case-Of-Solaris-Swap-Space

It seems like an interesting way to allow SWAP to dynamically grow and contract.

What could be disadvantages of it?

**Comment by fejiso** [comment]
@CMCDragonkai further fragmentation, which would make swapping even slower.

I just tried and I see the same freeze as with actual reservation.

**Comment by CMCDragonkai** [comment]
@fejiso What do you mean by the "same freeze"? 

I'm not so concerned with swap space speed, as I just think of it as backup memory.

**Comment by fejiso** [comment]
@CMCDragonkai I experience the same type of deadlocks as described in this issue, both with reservation enabled and disabled. I haven't performed any performance test but dynamic allocation will certainly cause fragmentation and make swap access slower.

**Comment by CMCDragonkai** [comment]
With the issue being closed, I thought the problem is solved. You should
post some diagnostics in case we can fix it again?

**Comment by fejiso** [comment]
After looking all around the web this is the only issue that looks remotely similar to what I experienced. In my case overcommitting VMs did it, when memory pressure from VMs started to compete with ARC got the load skyrocketed and eventually the system went unresponsive. ARC downsized as memory pressure increased, but that turned into slower disk access, that kicked the load further up. Very little, if any, swap space from the zvol was used.

I've tried pretty much every setting I could find: from running memory hogs to trigger swapping, limiting RES size of apps through cgroups, disabling transparent (and not) huge tables...

The only thing that fixed the situation was to have a separate swap partition. Zram devices also were used as expected.

All the sysctl vm values were default except for vm.swappiness set to 100 and inotify limit to 1000000.

The affected machine is now running BTRFS. As I couldn't easily shrink the mirrored zpool to accommodate a swap partition, I chose to switch as I might need to change the array geometry relatively often. I can, though, try to reproduce the issue using the partitions I have now as swap space.

**Comment by CMCDragonkai** [comment]
I just stress tested it as well with 32GB zvol swap, 32 GB ram and 32GB
tmpfs with 330 MB zram. Tried to put a 33GB zeroed file into tmpfs and
everything locked up. Saw my harddrive led blink for a few times and then
nothing. Had to power down using SysRq.
