### ISSUE TITLE
Parity declustered RAIDz/mirror

### ISSUE THREAD

**Issue by thegreatgazoo** [openzfs/zfs#3497]
Intel is working on parity declustered RAIDz/mirror for ZFS on Linux. Designs and early prototype/code will be shared with the community when available. Feedback from the community will be greatly appreciated.

More details to come later.

![draid](https://cloud.githubusercontent.com/assets/6722662/23642395/9783ef8e-02b7-11e7-8d7e-31d1053ee4ff.png)
![raidz](https://cloud.githubusercontent.com/assets/6722662/23642396/9790e432-02b7-11e7-8198-ae9f17c61d85.png)

**Comment by ronnyegner** [comment]
@thegreatgazoo  What exactly is a "declustered RAIDz/mirror"?

**Comment by kernelOfTruth** [comment]
@ronnyegner http://www.pdl.cmu.edu/PDL-FTP/Declustering/ASPLOS.pdf , http://www.enterprisestorageforum.com/technology/features/article.php/3883346/Can-Declustering-Save-RAID-Storage-Technology.htm

**Comment by dswartz** [comment]
Link is hosed?

**Comment by kernelOfTruth** [comment]
@dswartz worked for me, might have been a browser issue - better now ?

**Comment by dswartz** [comment]
Fails consistently with 500 server configuration error on my kindle.  Maybe the site is not handling mobile browsers right?  I am in the road ATM so I can't really check now...

**Comment by thegreatgazoo** [comment]
Slides at the developer summit 2015: https://drive.google.com/file/d/0B4BF1vnv6p0-bGVrQXg3dmY1Uzg/view

**Comment by Ornias1993** [comment]
@kpande According to @ahrens this is actually still/again active.

https://twitter.com/mahrens1/status/1191717726118563842

**Comment by ofaaland** [comment]
It is active.  Latest code is currently at https://github.com/openzfs/zfs/pull/9558

**Comment by Ornias1993** [comment]
@ofaaland You don't say:

> commented on 5 Nov 2019

**Comment by behlendorf** [comment]
PR #10102 contains the latest version of dRAID.

**Comment by behlendorf** [comment]
PR #10102 has been merged adding the dRAID feature.  Closing.
