### ISSUE TITLE
Fragmentation mitigation with large file blocks

### ISSUE THREAD

**Issue by don-brady** [openzfs/zfs#3541]
Commit f1512ee6 (illumos issue 5027) introduced support for larger blocks in ZFS (> 128K).
 
Metaslab Fragmentation
 
When used with RAIDZ, the allocations for large blocks can be quite large and at odd sizes (with skip sectors + parity).  This issue is will explore ways to minimize metaslab fragmentation when larger blocks are allocated alongside the much smaller sized compressed metadata.
 
Intel is currently working on a solution to address fragmentation with large file blocks.

**Comment by behlendorf** [comment]
The fragmentation metric would be a good way to quantify any improvements made to the allocater.

**Comment by jumbi77** [comment]
Can i may ask the status? Is that fragmentation linux specific or OpenZFS related? Much Thanks
