### ISSUE TITLE
dead code in dmu_tx_count_write() checking for DMU_MAX_ACCESS

### ISSUE THREAD

**Issue by nwf** [openzfs/zfs#3731]
`zfs_write` uses the `z_max_blksz` field (i.e. the dataset record size) to determine how big a piece of the file it should write at once.  However, `dmu_tx_hold_write` calls `dmu_tx_count_write` which may fail the transaction with EFBIG if the total amount of data, including metadata, to be changed exceeds "2 \* DMU_MAX_ACCESS".  `zfs_write` will then fail to `dmu_tx_assign` and will return with EFBIG.  Instead, it should probably reduce the chunk size (down to some floor, though maybe down to 1 byte) and try again?

**Comment by kpande** [comment]
@nwf can you review this and see if it's still a concern?

**Comment by nwf** [comment]
Not sure why it's on me to answer that, but in any case... No, this seems not to be an issue.  The relevant use of `EFBIG` at https://github.com/zfsonlinux/zfs/blob/424fd7c3e080255935646d2beaa2655c116cc37a/module/zfs/dmu_tx.c#L233-L234 after 3ec3bc2167352df525c10c99cf24cb24952c2786 is effectively a dead store: there is no path through `dmu_tx_count_write` thereafter which reads the value of `err` set here.  It shows up in `__set_error` instrumentation, but that's it; this is probably even more confusing than it would be if it were merely a dead store!  I suggest the pair of lines be removed and this issue closed.

**Comment by kpande** [comment]
ah, just because you were the original author. thanks for the quick response.

**Comment by nwf** [comment]
Relevant code appears unaltered since time of filing.
