### ISSUE TITLE
Input/Output error accessing snapshots over nfs while backup in progress

### ISSUE THREAD

**Issue by wonder** [openzfs/zfs#3930]
Hello,

I'm running 0.6.5.2-1~trusty and we export some pool in nfs that are used to backup files over nfs.
When the backup is still running, we are not able to browse the snapshots, we get Input/Output error.
Sometimes it works, sometimes it doesn't. If i try multiple times to change to desire directory, it works.

root@hera [~]# cd /backup
root@hera [/backup]# ls
./  ../  .backupmount_locks  incremental/
root@hera [/backup]# cd .zfs
-bash: cd: .zfs: Input/output error
root@hera [/backup]# cd .zfs
-bash: cd: .zfs: Input/output error
root@hera [/backup]# cd ~
root@hera [~]# cd /backup/.zfs
root@hera [/backup/.zfs]# ls
/bin/ls: reading directory .: Input/output error
root@hera [~]# cd /backup/.zfs/snapshot/08-10-2015/incremental/accounts
root@hera [/backup/.zfs/snapshot/08-10-2015/incremental/accounts]# ls
account1 account2

**Comment by tomassrnka** [comment]
Hi, we are experiencing the same problem on trusty / ZFS git from beginning of January.

**Comment by behlendorf** [comment]
@tomassrnka can you include the zfs version you're seeing this with.

**Comment by tomassrnka** [comment]
We are running ZFS from GIT from 18.1.2016 (3.13.0.74v0.6.5-128ws1) - the latest commit in our build is https://github.com/zfsonlinux/zfs/commit/bc89ac8479c0b265c539b579fda2bef1997d423c .

**Comment by tomassrnka** [comment]
Apparently, it works sometimes:

```
ignatius:/backups/.zfs/snapshot# ls -la
total 0
dr-xr-xr-x 2 root root 2 Feb  5 12:49 ./
dr-xr-xr-x 1 root root 0 Jan 22 20:06 ../
dr-xr-xr-x 1 root root 0 Feb  5 12:49 01-02-2016-01-33/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 02-02-2016-02-31/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 03-02-2016-02-15/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 04-02-2016-03-27/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 05-02-2016-05-10/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 26-01-2016-20-55/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 27-01-2016-22-23/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 28-01-2016-22-29/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 29-01-2016-23-37/
dr-xr-xr-x 1 root root 0 Feb  5 12:49 31-01-2016-00-49/
ignatius:/backups/.zfs/snapshot# ls -la
ls: cannot open directory .: Input/output error
ignatius:/backups/.zfs/snapshot# ls -la
ls: cannot open directory .: Input/output error
ignatius:/backups/.zfs/snapshot# ls -la
ls: cannot open directory .: Input/output error
ignatius:/backups/.zfs/snapshot# ls -la
ls: cannot open directory .: Input/output error
```

**Comment by wonder** [comment]
I'm seeing this problem with 0.6.5.4-1~trusty .

**Comment by behlendorf** [comment]
Is the `ls` being done locally on the NFS server or on a client?

**Comment by tomassrnka** [comment]
It's done on a client. The resulsts are the same on NFSv3 and v4.

**Comment by tjikkun** [comment]
I am seeing the same thing. For me "When the backup is still running" means when a zfs receive is running.
My guess is that it has to do with the remount that is being done on receiving snapshots, as mentioned in https://github.com/zfsonlinux/zfs/issues/4811#issuecomment-229082982
