### ISSUE TITLE
createmany test failure

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#401]
Andreas Dilger: to cause this I ran lustre/tests/createmany -m /ztest/test/foo 2000000 (approximately) to create the original reported number of free inodes, and then it still reported about 450k free inodes (I assume because of metadnode compression using less than 512 bytes/dnode), so I ran createmany -m /ztest/test/f 450000 and it is now hung at around 390000 files, with df -i reporting still 189000 inodes/ 94500kB free.  The pool is only 1GB in size, so it is currently 91% full.  I had it 100% full yesterday, though there were a lot more files with data - this was purely zero-length inodes.

<pre>
Pid: 21433, comm: z_ioctl_int/0 Tainted: P 2.6.32.26-175.fc12.x86_64 #1 Dell DXP051                  
RIP: 0010:[<ffffffff814594e6>] [<ffffffff814594e6>] _spin_lock+0x1a/0x25
Call Trace:
[<ffffffff8145840f>] ?  __mutex_unlock_slowpath+0x1a/0x3e
[<ffffffff814583f3>] ? mutex_unlock+0x1b/0x1d
[<ffffffffa06dc24d>] ? zio_done+0xa0a/0xa29 [zfs]
[<ffffffffa06dc1eb>] ? zio_done+0x9a8/0xa29 [zfs]
[<ffffffffa06db130>] ? zio_execute+0xb1/0xd5 [zfs]
[<ffffffffa03adff4>] ? taskq_thread+0x271/0x2b3 [spl]
[<ffffffff81051ec5>] ?  default_wake_function+0x0/0x14
[<ffffffffa03add83>] ? taskq_thread+0x0/0x2b3 [spl]
[<ffffffff810746b2>] ? kthread+0x7f/0x87
[<ffffffff81012d6a>] ? child_rip+0xa/0x20
[<ffffffff81074633>] ? kthread+0x0/0x87
[<ffffffff81012d60>] ? child_rip+0x0/0x20
</pre>

**Comment by ryao** [comment]
@behlendorf This is not a duplicate of #2523. Instead, it is a duplicate of #3091.
