### ISSUE TITLE
partial overwrite of metadata holes results in loss of hole birth info

### ISSUE THREAD

**Issue by bprotopopov** [openzfs/zfs#4023]
When an Ln (n>0) hole is partially overwritten, the remaining (Ln-1) holes do not inherit the Ln's hole's birth epoch. Other properties, such as dmu type, level, and logical size, are not set properly either. In fact, the block pointers for the Ln-1 holes are completely zeroed out. 

As a result, when the hole_birth feature is active, an incremental zfs send stream will not consider those Ln-1 holes "new", and therefore will not include the corresponding FREE records in the stream. This, in turn, results in data loss at the site of the stream receipt. 

Let's consider the following use case. Snapshot s1 has a non-zero L1 block range (say block 128-256). After a number of I/O operations, this range is zeroed out, and it is now represented by a single L1 hole. Then this L1 hole is partly overwritten, resulting in a collection of "old" (birth epoch zero) holes in the range under discussion. Then snapshot s2 is created, and zfs send -i s1 s2 is generated. 

If the hole_birth feature is active, the resulting stream will not contain the FREE records for the holes in the block range in question, and therefore, when the stream is received, the corresponding data blocks will not be zeroed out (data loss).

Here is an example of this case illustrated with zdb dumps.

Before the overwrite, snapshot s1 has an L1 hole:

```
      7c0000   L0 1:2584800:10000 10000L/10000P F=1 B=346/346
      7d0000   L0 1:2594800:10000 10000L/10000P F=1 B=346/346
      7e0000   L0 1:25a4800:10000 10000L/10000P F=1 B=346/346
      7f0000   L0 1:25b4800:10000 10000L/10000P F=1 B=346/346
      800000  L1  4000L B=548
     1000000  L1  0:7c23e00:400 1:7c2d200:400 4000L/400P F=128 B=1268/1268
     1000000   L0 0:7808c00:10000 10000L/10000P F=1 B=1268/1268
     1010000   L0 0:7818c00:10000 10000L/10000P F=1 B=1268/1268
     1020000   L0 0:7828c00:10000 10000L/10000P F=1 B=1268/1268
```

The L1 hole is at offset 800000. After a partial overwrite (10 blocks written at the beginning of the L1 range):

```
      7d0000   L0 1:2594800:10000 10000L/10000P F=1 B=346/346
      7e0000   L0 1:25a4800:10000 10000L/10000P F=1 B=346/346
      7f0000   L0 1:25b4800:10000 10000L/10000P F=1 B=346/346
      800000  L1  0:ea36000:600 1:f2d6000:600 4000L/600P F=10 B=1749/1749
      800000   L0 1:f246000:10000 10000L/10000P F=1 B=1749/1749
      810000   L0 1:f256000:10000 10000L/10000P F=1 B=1749/1749
      820000   L0 1:f266000:10000 10000L/10000P F=1 B=1749/1749
      830000   L0 1:f276000:10000 10000L/10000P F=1 B=1749/1749
      840000   L0 1:f286000:10000 10000L/10000P F=1 B=1749/1749
      850000   L0 1:f296000:10000 10000L/10000P F=1 B=1749/1749
      860000   L0 1:f2a6000:10000 10000L/10000P F=1 B=1749/1749
      870000   L0 1:f2c6000:10000 10000L/10000P F=1 B=1749/1749
      880000   L0 1:f2b6000:10000 10000L/10000P F=1 B=1749/1749
      890000   L0 0:ea26000:10000 10000L/10000P F=1 B=1749/1749
     1000000  L1  0:7c23e00:400 1:7c2d200:400 4000L/400P F=128 B=1268/1268
     1000000   L0 0:7808c00:10000 10000L/10000P F=1 B=1268/1268
```

Dump of the new L1 block's contents:
zdb tpool -R 0:ea36000:600:di

```
Found vdev: /dev/sdk1
DVA[0]=<1:f246000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=2041f382f58d:408f994ef048de7:daf0e1cadf74f53:47c3fdb952a1e13f
DVA[0]=<1:f256000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=20306f1938d5:403381ccd468d8a:713a193137858160:d91b1c5cecb306af
DVA[0]=<1:f266000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=1fe160444ab9:3fcbaeb1f31c86e:11198655b490d3b5:76cd3d278385af3e
DVA[0]=<1:f276000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=201cb0f386db:4035cd7deb41749:6b4d734a11ce04b5:1fbc2dc2f169dcae
DVA[0]=<1:f286000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=202d87c1a695:403d7ff6a1a6f53:66b049fa47216fb4:848b133855fab5b
DVA[0]=<1:f296000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=200db48ae914:40163392a6e1f2a:62ad5c6b01c39d36:b1fa1b14d986fa82
DVA[0]=<1:f2a6000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=1feb72709d3a:3f8dbd7a3f1e98f:ab207f926cc8b2fc:c9a1145f06e1f9ab
DVA[0]=<1:f2c6000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=1fd90de96ff0:3f98dc852f15900:a3cd2aed016bc0a9:eb9f507ffe495f15
DVA[0]=<1:f2b6000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=20361039de8d:40b6d13e4438295:75686dbb7da50937:3217ceae84d5b538
DVA[0]=<0:ea26000:10000> [L0 zvol object] fletcher4 uncompressed LE contiguous unique single size=10000L/10000P birth=1749L/1749P fill=1 cksum=202a397fecd2:405130f54a9a83d:cda024b471659627:edf740c0ca1563eb
HOLE [L0 unallocated] size=200L birth=0L
HOLE [L0 unallocated] size=200L birth=0L
HOLE [L0 unallocated] size=200L birth=0L
...
HOLE [L0 unallocated] size=200L birth=0L
HOLE [L0 unallocated] size=200L birth=0L
HOLE [L0 unallocated] size=200L birth=0L
```

The uncompressed data is likely due to the /dev/urandom source. The volume does have lz4 compression set (and had before the overwrite - inherited from the pool).

The new L0 holes have birth epoch 0, instead of 548, as in the original L1 hole.

**Comment by kernelOfTruth** [comment]
https://www.illumos.org/issues/6370 ZFS send fails to transmit some holes
https://www.illumos.org/issues/4370 avoid transmitting holes during zfs send

**Comment by bprotopopov** [comment]
When reading Ln metadata holes with non-zero birth epochs in dbuf_read_impl(), instead of initializing the dbuf data with zeros, initialize with Ln-1 hole block pointers of same dmu type and birth epoch as Ln hole, and of proper level and logical size, in order to make sure the new (Ln-1) holes inherit correct hole info. This is important when generating incremental zfs send streams with hole_birth feature active, where the proper hole birth is required in order to generate proper FREE records for the new holes.

With this change, the partly overwritten region looks as follows:

          7e0000   L0 1:25a4800:10000 10000L/10000P F=1 B=346/346
          7f0000   L0 1:25b4800:10000 10000L/10000P F=1 B=346/346
          800000  L1  0:f844a00:400 1:4858c00:400 4000L/400P F=0 B=1974/1974
          800000   L0 10000L B=1974
          810000   L0 10000L B=1974
          820000   L0 10000L B=1974
          830000   L0 10000L B=1974
          840000   L0 10000L B=1974
          850000   L0 10000L B=1974
          860000   L0 10000L B=1974
          870000   L0 10000L B=1974
          880000   L0 10000L B=1974
          890000   L0 10000L B=1974
          8a0000   L0 10000L B=548
          8b0000   L0 10000L B=548
          8c0000   L0 10000L B=548
          8d0000   L0 10000L B=548
          ...
          fd0000   L0 10000L B=548
          fe0000   L0 10000L B=548
          ff0000   L0 10000L B=548
         1000000  L1  0:7c23e00:400 1:7c2d200:400 4000L/400P F=128 B=1268/1268

Note that in this case, the region was partly overwritten with zeros, so the 10 blocks at the beginning have birth epoch 1974, whereas the L0 holes generated by replacing the L1 hole inherit its birth epoch 548.

**Comment by bprotopopov** [comment]
This issue is similar to 
https://www.illumos.org/issues/5695 dmu_sync'ed holes do not retain birth time

**Comment by bprotopopov** [comment]
It turns out that there are many places in the code that zero out block pointers inside indirect dbufs.

**Comment by bprotopopov** [comment]
Turns out it is quite easy to reproduce the issue using blkdiscard command on the zvol. One can easily create an L1 hole that, when partially overwritten, will result in an invalid collection of L0 "old" holes.

**Comment by kpande** [comment]
@behlendorf what's the status of this hole_birth bugs in general?

**Comment by rlaager** [comment]
@behlendorf I'd like to repeat that question. What is the status on `hole_birth` these days? If I understand correctly from zpool-features(5), the entire point of `hole_birth` is to accelerate `zfs send -i` operations. But because of the bugs, we ignore the `hole_birth` data on `zfs send` anyway. So `hole_birth` is useless, both in ZoL and OpenZFS, right?

If we think all of the `hole_birth` bugs are fixed in OpenZFS, then I think we need the following changes:
0) Merge any missing `hole_birth` fixes from OpenZFS to ZoL.
1) Add a hole_birth_v2. (Maybe make hole_birth depend on it?)
2) Rework `send_holes_without_birth_time` in some way. For example:
* If `send_holes_without_birth_time` is `1`, retain the existing behavior of never sending a birth time. That way, the behavior matches the name, and we retain the ability to address similar problems with hole_birth_v2.
* If `send_holes_without_birth_time` is `0`, only send holes from TXGs after `hole_birth_v2`. In other words, we would _always_ ignore `hole_birth`-only holes.
* Set the default of `send_holes_without_birth_time` to `0`.

Since 0.8.0 is feature-frozen at this point, the `hole_birth_v2` would have to wait until later.

**Comment by behlendorf** [comment]
> What is the status on hole_birth these days? If I understand correctly from zpool-features(5), the entire point of hole_birth is to accelerate zfs send -i operations. But because of the bugs, we ignore the hole_birth data on zfs send anyway. So hole_birth is useless, both in ZoL and OpenZFS, right?

That's right.  There were several fixes applied to resolve the hole birth bug.  I believe they've all been applied to Linux and the issue should be resolved.  However, since it's purely a performance optimization we've left it disabled by default on Linux out of an abundance of caution.

Given how much trouble it caused users initially we'd of course need to test it extensively before considering re-enabling as the default.  I think your proposal makes good sense and it's something we should queue up for after 0.8.0.
