### ISSUE TITLE
Volume quota not enforced over NFS

### ISSUE THREAD

**Issue by mkraemerATtum** [openzfs/zfs#4148]
Dear All,

testing ZFS on Linux I ran into a problem with volume quotas on ZFS exports. While volume quotas are correctly enforced and treated, when accessing the ZFS on the local system, when trying the same via NFS (v4) it is possible to exceed the quota limit. Furthermore the failing of the write process is not reported correctly to the NFS client. 

In the following example (see console log below) a empty zfs volume (tank/test) is created and the quota is set to 100M. While a local 'dd' is stopped, when reaching the limit doing the same on a remote client a ~614M file is generated and the remote client reports quota exceeded at ~1.5G. Thus a few 100M are written to nowhere without reporting. While the actual file size and size until the clients show reports are not fixed to a certain value -- file size varies between 550-700M and quota exceeded is reported between 1.2-2.0G -- the problem is persistent  and could be reproduced at a second test system. The first system is running Centos 7 with ZFS 0.6.5.3-1, the second SL 6.7 with ZFS 0.6.5.3-1.

If O_DIRECT is used to open files the behaviour is as expected, i.e. the quota is correctly enforced. 

Regards

Markus

Console log server

```
[root@server test]# zfs get quota tank/test
NAME       PROPERTY  VALUE  SOURCE
tank/test  quota     100M   local
[root@server test]# pwd
/tank/test
[root@server test]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
tank/test       100M  128K  100M   1% /tank/test
[root@server test]# dd if=/dev/zero of=bla
dd: writing to ‘bla’: Disk quota exceeded
204802+0 records in
204801+0 records out
104858112 bytes (105 MB) copied, 32.6697 s, 3.2 MB/s
[root@server test]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
tank/test       100M  100M     0 100% /tank/test
[root@server test]# rm bla
rm: remove regular file ‘bla’? y
[root@server test]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
tank/test       100M  128K  100M   1% /tank/test

.... (execute cmd on client see below) ....

[root@server test]# ls -lh
total 100M
-rw-r--r-- 1 XXXXXX  adusers 614M Dec 28 16:39 bla
[root@server test]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
tank/test       100M  100M     0 100% /tank/test
[root@server test]# zfs get compression tank/test
NAME       PROPERTY     VALUE     SOURCE
tank/test  compression  off       local

```

Console log client:

```
[XXXXXX@client test]$ pwd
/mnt/server/tank/test
[XXXXXX@client test]$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
-               100M     0  100M   0% /mnt/server/tank/test
[XXXXXX@client test]$ dd if=/dev/zero of=bla
dd: writing to `bla': Disk quota exceeded
3434269+0 records in
3434268+0 records out
1758345216 bytes (1.8 GB) copied, 59.6715 s, 29.5 MB/s
[XXXXXX@client test]$ ll -h
total 100M
-rw-r--r--. 1 XXXXXX adusers 614M Dec 28  2015 bla
[XXXXXX@client test]$ mount | grep server
server:/ on /mnt/server type nfs (rw,vers=4,addr=XXXXX,clientaddr=XXXXX)
```

**Comment by behlendorf** [comment]
@mkraemerATtum thanks for the detailed bug report.  I suspect this is related to the NFS client caching most of this data before sending any of it to the server asynchronously.  If that's the case you can likely prevent the issue by using synchronous NFS mounts.  That's almost certainly why O_DIRECT works.  Someone will need to dig deeper to see if there is anything we can do at the ZFS level to catch this sooner.

**Comment by mkraemerATtum** [comment]
Thank you for your fast response. I can confirm, that using synchronous NFS prevent the problem. However I doubt, that this is only the client. On production systems I am currently using XFS with "project quotas", which works reliable. If only the client cache matters I cannot understand how this is working with XFS quotas. For the client, this should look very similar.

Talking into account that synchronous NFS mounts means a significant performance impact in many scenarios, it is not a good solution and unfortunately at the moment rules out the usage of ZFS on our side.

Nevertheless thank you for looking into this. Let me know, if you need some more information.

**Comment by mkraemerATtum** [comment]
I just want to add. Even if the client would report something wrong. The local file should not exceed the quota, i.e. if the quota is set to 100M the generate file should not be 614M.

**Comment by mkraemerATtum** [comment]
Further investigations of the problem revealed some further insights. It seems that using asynchronous NFS mounts the files created on the FS are sparse files (at least when using /dev/zero). The allocated disk space respects the quota. I explicitly turned compression and de-duplication off in the first place. Thus it's really the NFS client or server, which is causing this behaviour.

**Comment by richardelling** [comment]
> On Dec 29, 2015, at 3:17 AM, mkraemerATtum <notifications@github.com> wrote:
> 
> Further investigations of the problem revealed some further insights. It seems that using asynchronous NFS mounts the files created on the FS are sparse files (at least when using /dev/zero). The allocated disk space respects the quota. I explicitly turned compression and de-duplication off in the first place. Thus it's really the NFS client or server, which is causing this behaviour.
> 
> 

A few points to consider:

1. In ZFS, quota is enforced on the size of the files, not the length (duh)

2. Compression and dedup affect the size of files

3. Quota is checked at the close of a txg, nominally every 5 seconds for most distros.
    Thus it is possible to go over for a short time. Due to the nature of transactional 
    systems, like ZFS, it is impractical to enforce outside of a transaction's scope.

 -- richard

**Comment by mkraemerATtum** [comment]
Dear Richard,

On 12/29/2015 06:27 PM, Richard Elling wrote:
>
> > On Dec 29, 2015, at 3:17 AM, mkraemerATtum
> <notifications@github.com> wrote:
> >
> > Further investigations of the problem revealed some further
> insights. It seems that using asynchronous NFS mounts the files
> created on the FS are sparse files (at least when using /dev/zero).
> The allocated disk space respects the quota. I explicitly turned
> compression and de-duplication off in the first place. Thus it's
> really the NFS client or server, which is causing this behaviour.
> >
> >
>
> A few points to consider:
>
> 1. In ZFS, quota is enforced on the size of the files, not the length
> (duh)
That's how I understood the docu. However I was just surprised, that the
files were created as sparse files by using NFS. Compression and debup
should not apply as these features have been disabled during the test.
>
> 2. Compression and dedup affect the size of files
That is the reason for me to disabling both feature from the beginning,
when doing this test.
>
> 3. Quota is checked at the close of a txg, nominally every 5 seconds
> for most distros.
> Thus it is possible to go over for a short time. Due to the nature of
> transactional
> systems, like ZFS, it is impractical to enforce outside of a
> transaction's scope.
Thank you for this information. Although I know that txg are done every
5 seconds, I did not know, that this is the time the quota is checked.

Thus as I already concluded in the last comment ZFS act as I expect,
while NFS client and/or server does not. However would be nice, if this
could be found in the docu.

Sorry for bothering you.

Regards

Markus
>
> -- richard
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/4148#issuecomment-167835082>.
>

-- 
- -- 
+-----------------------------------+--------------------------+
| Dipl.-Phys. Markus Kraemer        |                          |
| Technische Universitaet Muenchen  | Room    PH1 3276         |
| Physik-Department E18             |                          |
| James-Franck-Strasse              | Phone  +49 89 289-12379  |
| D-85747 Garching                  | Fax    +49 89 289-12570  |
+-----------------------------------+--------------------------+

**Comment by behlendorf** [comment]
> I was just surprised, that the files were created as sparse files by using NFS. Compression and debup should not apply as these features have been disabled during the test.

I'm surprised as well, this shouldn't be the case.  I/O originating from NFS takes almost the same call path as local I/O and will be compressed or dedupped based on the dataset properties.  The only significant difference is that the NFS I/O will arrives via the async I/O interfaces in smaller sized chunks.

One other thing to keep in mind is that a zero filed file in ZFS is treated as a very specific special case.  The blocks aren't compressed in the normal sense but are detected as __holes__ and recorded in the block pointer as a hole containing no data.  I suspect you'll see the expected results in you use any other data pattern.  Also some of this hole checking code happens outside the compression checks so it's possible it may be applied for your workload even when compression is disabled.

> I did not know, that this is the time the quota is checked.

Yes, this is a subtle difference between zfs and other Linux filesystems like ext4 / xfs which don't use a similar transactional object store.  Only updating the quota objects once per-transaction group makes the good much more tractable and improves performance.

> Sorry for bothering you.

No problem, thanks for posting your observation.  There may in fact be a subtle issue here which should at least be better documented.

**Comment by kpande** [comment]
#8415 might also address this documentation change. I will look into that.
