### ISSUE TITLE
support copy_file_range() syscall

### ISSUE THREAD

**Issue by derekdai** [openzfs/zfs#4237]
This is a interesting new syscall first appeared in linux kernel 4.4 that offloaded file copy from user space to kernel, and I think this is a great way to implement a lightweight copying in between zfs file systems. Is there a plan to support it on ZoL?

**Comment by DeHackEd** [comment]
At the end of the day ZFS doesn't have anything to offer which "accelerates" the process. This system call merely removes the copies from user and kernel spaces. In most situations that's not going to be substantially faster than your disks or controllers can perform the IO.

**Comment by derekdai** [comment]
The storage won't go faster because of this syscall, but it saves resources from
* Prevent data from been copy to and from kernel and user space
* zfs can choose the best block size to copy to and from
* zfs don't need to recalculate checksum
* zfs don't need to decompress blocks
* zfs can do deduplication more efficiently
