### ISSUE TITLE
NEX-3485 Deferred deletes causing loss of service for NFS clients on cluster failover

### ISSUE THREAD

**Issue by kernelOfTruth** [openzfs/zfs#4248]
Could this be useful & is it applicable in some form ?

https://github.com/Nexenta/illumos-nexenta/commit/e308c335ab83c291079b491ae2997702a42f40b1

**Comment by behlendorf** [comment]
It's definitely useful and we made a similar change to ZoL a while back.  Although we increased these values a bit more.

```
        dp->dp_iput_taskq = taskq_create("z_iput", max_ncpus, defclsyspri,
            max_ncpus * 8, INT_MAX, TASKQ_PREPOPULATE | TASKQ_DYNAMIC);
```
