### ISSUE TITLE
ARC exhausted when destroy a snapshot who have a huge deadlist

### ISSUE THREAD

**Issue by GeLiXin** [openzfs/zfs#4254]
Hi,
    We have a snapshot with a huge deadlist, which about 10 million entries in it.  And the Arc size of our  
equipment is more or less 1GB.
    Every time we attempt to destroy that snap, we get failed  due to arc exhausted and have to reboot our equipment. We can't release the space referenced by the snap now!
    The function 'dsl_destroy_snapshot_sync_impl' will iterate all the entries in deadlist, and each consume 128 Byte Arc memory due to the cache of blkptr. That means more than 1GB Arc will be request in a single TXG to do so. It's a bad constraint to both ZFS Arc strategy and the hardware configuration. 
    Do you have any idea to fix this situation without expanding the RAM? Can we take the destroy process into several TXG instead of a single one? Or several limited deadlist instead of one unlimited deadlist?
    Thanks!

**Comment by kpande** [comment]
@GeLiXin is this still an issue?

**Comment by GeLiXin** [comment]
@kpande thanks for your attention, I didn't pay close attention to ZFS improvements these years, but, if ZFS still iterate the entries in an unlimited deadlist in a single txg, it always have the possibility to happen.
