### ISSUE TITLE
`zfs diff` shows pathes with escape sequences

### ISSUE THREAD

**Issue by intelfx** [openzfs/zfs#4290]
For example:

```
/mnt/datastore2/datastore2-Internal/Transmission/resume/OS\0040X\0040Yosemite\004010.10.5.dmg.4bd316181d4437ee.resume
```

The `utf8only` property for the dataset is on, if this makes a difference. Everything is in UTF-8, I can see the correct file name by listing (the console is in UTF-8 as well).

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/pull/4291 Illumos 4448 zfs diff misprints unicode characters

**Comment by intelfx** [comment]
@kernelOfTruth: IIUC, that commit only changes the escaping form. Why does this escaping exist in the first place? How can I distinguish an escaped Cyrillic `й` from a file which is named `\320\271`?

**Comment by kernelOfTruth** [comment]
@intelfx not sure what the initial rationale was behind that

yes, that clearly indicates that a different approach is needed

**Comment by intelfx** [comment]
Is this escaping needed at all? Do other (Linux) filesystems mangle file names on the fly?

**Comment by behlendorf** [comment]
The rational here predates my involvement too.  A short while back this was converted on Linux to at least use the standard 4-digit octal escape notation to disambiguate it, \0NNN.  But frankly this code is long overdue for someone who understands such things to fix it up.

**Comment by intelfx** [comment]
@behlendorf Well, while we wait for someone who understands the code, will you accept a trivial patch which adds, say, a `--raw` option to zfs-diff to disable any escaping (in case I'm completely sure that all the file names are OK)?

**Comment by behlendorf** [comment]
That sounds entirely reasonable to me.

**Comment by tuxoko** [comment]
FWIW, you can put in inside `echo -e "<escape string>"` get the raw byte.

**Comment by x09** [comment]
> 1482989669.361475978	M	/PRJ3/prj2013/Archive/\320\236\321\202\321\207\320\265\321\202\040\320\277\320\276\040\320\223\320\265\320\276\321\204\320\270\320\267\320\270\321\207\320\265\321\201\320\272\320\276\320\274\321\203\040\320\273\321\203

How read it ?

**Comment by KTannenberg** [comment]
I'm a bit late to the party, so I'll just leave this message for my future self 😄 
You can do `zfs diff <snap1> <snap2> | xargs -L1 echo -e` to interpret escape sequences.

**Comment by KTannenberg** [comment]
I'm a little bit late the party, so I'll just leave this for my future self 😄 
You can just use xargs with echo to convert escape sequences:
```bash
zfs diff snapshot1 snapshot2 | xargs -r -d\\n -L1 echo -e
```

Posix-compatible version is 
```sh
zfs diff snapshot1 snapshot2 | tr '\n' '\0' | xargs -r -0 -L1 echo -e
```
