### ISSUE TITLE
Some files missing copyright statements (but got license info)

### ISSUE THREAD

**Issue by petterreinholdtsen** [openzfs/zfs#4356]
While working on the debian/copyright file for the Debian package of zfsonlinux, I discovered a few files with license information but no copyright statement.  Perhaps someone should claim copyright for these files?  Here is a list:

Files: cmd/arcstat/*
Copyright: no-info-found
License: CDDL-1.0 or only

Files: include/linux/utsname_compat.h
Copyright: no-info-found
License: CDDL

Files: include/sys/trace.h
  include/sys/trace_acl.h
  include/sys/trace_arc.h
  include/sys/trace_dbgmsg.h
  include/sys/trace_dbuf.h
  include/sys/trace_dmu.h
  include/sys/trace_dnode.h
  include/sys/trace_multilist.h
  include/sys/trace_txg.h
  include/sys/trace_zil.h
  include/sys/trace_zrlock.h
  include/sys/zfs_delay.h
Copyright: no-info-found
License: CDDL

Files: lib/libspl/include/attr.h
  lib/libspl/include/stropts.h
Copyright: no-info-found
License: CDDL

Files: lib/libspl/include/sys/policy.h
Copyright: no-info-found
License: CDDL-1.0 or only

Files: module/zfs/dbuf_stats.c
  module/zfs/spa_stats.c
  module/zfs/trace.c
Copyright: no-info-found
License: CDDL

**Comment by behlendorf** [comment]
@petterreinholdtsen the authoritative copyright information is tracked by the git commit history.  Like many open source projects many different organizations, companies, and individuals have contributed to these files.
