### ISSUE TITLE
The speed of random reading zvol is too slow with zfs-0.6.5.5 in centos7 OS

### ISSUE THREAD

**Issue by xuyizhao** [openzfs/zfs#4429]
The speed of random reading zvol is too slow with zfs-0.6.5.5 on centos7 OS.
The iodepth of block device is only 1 when setting iodepth 32 in fio.
The iodepth of block device is 8 in zfs-0.6.0-rc6. 
1. I don't understand why not use multiple threads to process zio in zfs-0.6.5.5.
2. I don't understand the description of commit 37f9dac592bf5889c3efb305c48ac39b4c7dd140.
   I want to know whether arc_read function merges read IOs or not.

---

commit 37f9dac592bf5889c3efb305c48ac39b4c7dd140
Author: Richard Yao ryao@gentoo.org
Date:   Fri Jul 4 18:43:47 2014 -0400

 However, the DMU alreadydoes write merging while arc_read() should implicitly 
merge read IOs because only 1 thread is permitted to fetch the buffer into ARC.

**Comment by ReTheOff** [comment]
I couldn't help but chime in on this, sorry , its just a "me too" post.  I don't have any technical details to help, but I was wondering why my KVM virtual machines were all running very slow after updating to 0.6.5.5.  I just found this issue and now think I'll downgrade back to 0.6.4x.  I only have running lab systems at the moment, so its no problem.  But I'm am seeing significant performance drops, and they are random.  VM's used to boot in seconds, and now take over a minute.  On my main development VM (running Linux) I moved off of ZVOL for guest storage and onto a raw image file. This worked great and I had very good performance over the ZVOL.  But I don't want to do this for all the VM's. I do see the problem more noticeably in Windows guests.  Also, I notice the issue in both Centos 7 and Fedora 23.  If there's any tests I can run to help, let me know.  Just my simple dd tests ("dd if=/dev/zero of=test.perf bs=1M count=256 conv=fdatasync")  in a linux guest, I was getting 15MB/s on ZVOL storage, when after moving to raw image file I got > 400MB/s.  I know that's not a perfect, real-world test, but that's too large a difference not to notice.

**Comment by behlendorf** [comment]
@xuyizhao @ReTheOff it would be helpful if you could post a simple test case which reproduces this issue.  An example `fio` script would be ideal and a list of any tuning you may have tried.  Let me flag @ryao on this issue since he authored the recent zvol 37f9dac changes.

**Comment by ReTheOff** [comment]
Ok, did some testing, and I stand corrected. Also I apologize for jumping to conclusions. And @xuyizhao  sorry for hijacking your reports.  Looks like I am incorrectly pointing fingers at ZFS since it was the last thing I changed and it happened on multiple hosts. But after a lot more testing I think something else is wrong.  

Most importantly, after testing and getting normal results from ZVOL's, I downgraded one host to 0.6.4.2 and my Windows guests still exhibit the same stalling and hanging.  At this point I am fairly sure something else has changed, and its not ZFS that's causing the performance issue on KVM guests.

Here is a gist with all my test output if interested. (although this is probably all irrelevant now)
[https://gist.github.com/ReTheOff/40b30584ea312f187bed](https://gist.github.com/ReTheOff/40b30584ea312f187bed)

Thank you for your help and all the awesome work on ZFS!

**Comment by woquflux** [comment]
fio.ini

```
[global]
size=50G
direct=1
iodepth=64 
runtime=120000
time_based
filename=/dev/tank/lv1 
numjobs=1 
group_reporting
[rand-read]
rw=randread
bs=8k
```
result
```
$zpool iostat 1
               capacity     operations    bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
tank         365G   745G    488  1.26K  3.81M  39.0M
tank         365G   745G  3.33K      0  26.7M      0
tank         365G   745G  3.37K      0  27.0M      0
tank         365G   745G  3.44K      0  27.5M      0
tank         365G   745G  3.61K      0  28.9M      0
tank         365G   745G  3.33K      0  26.6M      0
```

iostat
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.15    0.00    1.09    0.07    0.00   98.69

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.10     0.00  138.80  355.31     1.09    10.78    49.17     0.09    0.17    0.19    0.17   0.09   4.42
sdc               0.10     0.00  138.21  362.12     1.08    10.78    48.53     0.09    0.17    0.19    0.17   0.09   4.39
sdd               0.10     0.00  138.55  355.70     1.08    10.78    49.14     0.08    0.17    0.19    0.16   0.09   4.41

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.00    0.29    0.53    0.00   99.06

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00 1237.00    0.00     9.66     0.00    16.00     0.24    0.19    0.19    0.00   0.19  23.60
sdc               0.00     0.00 1209.00    0.00     9.45     0.00    16.00     0.20    0.17    0.17    0.00   0.17  20.00
sdd               0.00     0.00 1032.00    0.00     8.06     0.00    16.00     0.21    0.20    0.20    0.00   0.20  20.70

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.00    0.25    0.55    0.00   99.09

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00 1275.00    0.00     9.96     0.00    16.00     0.25    0.20    0.20    0.00   0.20  25.50
sdc               0.00     0.00 1279.00    0.00     9.99     0.00    16.00     0.24    0.19    0.19    0.00   0.19  24.10
sdd               0.00     0.00 1115.00    0.00     8.71     0.00    16.00     0.20    0.18    0.18    0.00   0.18  20.20
```

The iodepth parameter from 1 to 64 does not seem to have any effect, on the 0.6.5.11 version.

**Comment by woquflux** [comment]
@behlendorf I can't find a version of zfs that I can use.

0.6.4.2: rngd limits performance,and can't be installed on Redhat 7.4.
0.6.5.11: iodepth do not work,pool read performance;
0.7.x: poor performance #7834

**Comment by behlendorf** [comment]
@woquflux I'd suggest trying, https://github.com/zfsonlinux/zfs/pull/8011 which will be added to 0.7.12, and setting `spl_taskq_thread_dynamic=0`.  Both should improve the random read performance.

**Comment by woquflux** [comment]
I don't think this helps, because I encountered a problem with random writes in the 0.7.x version, and the read performance is temporarily acceptable.

**Comment by woquflux** [comment]
@tuxoko 

Is it possible to apply the commit 692e55b8fe to the 0.6.5 branch? 0.6.5 can be very happy to use
