### ISSUE TITLE
Unintuitive error message setting sharenfs=on

### ISSUE THREAD

**Issue by grantwwu** [openzfs/zfs#4534]
If the NFS server is not installed and you attempt to set sharenfs=on on a filesystem, you get the following unintuitive error message:

```
cannot share '<filesystem name>': share(1M) failed        
property may be set but unable to reshare filesystem
```

**Comment by jpellman** [comment]
+1

**Comment by fm365** [comment]
I encountered this problem too.

**Comment by KES777** [comment]
You have no installed required system libs:

    sudo apt install nfs-kernel-server

**Comment by grantwwu** [comment]
@KES777 Yes, as I said, this happens "If the NFS server is not installed"

**Comment by foxpalace** [comment]
hihihi - what a nonsense - please check before tranfser some TBs - just waiting hours and then boom  - lol

**Comment by grantwwu** [comment]
@foxpalace What?

**Comment by jpellman** [comment]
@grantwwu I think @foxpalace started a file transfer, didn't realize that an NFS mount point wasn't mounted, and then sync'd a bunch of data to a root volume instead, thus filling it up.  Presumably the reason the NFS mount point wasn't mounted was due to sharenfs=on not working.

**Comment by grantwwu** [comment]
@jpellman I applaud and appreciate your translation abilities.

It's still irrelevant to this thread though; there _is_ an error message, which still ought to have given pause to the person before they did the transfer.  The issue is that the error message is confusing.

**Comment by foxpalace** [comment]
yes - i didn't control the settings - therefore is my software - I transfered some TBs of Data and on the end ... böhm - your settings are wrong - all data on the second machine deleted after hours of transfer ... its like: hoooouuuu middlefinger

**Comment by jpellman** [comment]
@grantwwu  It's reassuring to know that my minor in French wasn't totally useless :)

**Comment by mswezey23** [comment]
this worked for me too - sudo apt install nfs-kernel-server
