### ISSUE TITLE
Bias in zvol's space account violate the semantic feature of volume

### ISSUE THREAD

**Issue by GeLiXin** [openzfs/zfs#4544]
When we create a volume and set  space reservation for it , we insinuate the user that they can absolutely use the space we announced in 'volsize'. Actaully, bias in zvol's space account violate the semantic feature of volume.

This will always happen in raidz pool, the worst case is raidz2 with 9 disks and let's take the worst case for a example. 

Zvol's default blocksize is 8192, when we going to write a block we account the asize via 'vdev_psize_to_asize'. In this case, the psize is 8192 and the asize is 12288. The asize will set to the dva  in the blkptr of our block. After the calling of spa_sync we come to the 'dbuf_write_done', which account the dataset's new space consume via 'bp_get_dsize_sync'. In this case , the vdev_deflate_ratio is 397(computed by 128k blocksize)  and our dsize is 9528, which is much bigger(116%) than our actual space use 8192. The space reservation for volume, which only consider the additional space consume of metadata, is not enough, obviously.

Generally speaking,  the space account of volume may much bigger than it's actaully used, that's because of volume default block size isn't the one we compute our vdev_deflate_ratio. When the ZFS user's main requirements is volume, that's become a big problem: all of the pool space is devided into several volumes(no space left),  but none of my volumes can be used normally(it can't get any extra space than it's reservation while it's reservation isn't enough).

Our term get a list of the biases in some typical situation, this issue isn't difficult to fix and we use the ds_flags in dsl_dataset_phys_t  to solve the compatibility.

---

raidz1 3 disks, ASIZE is 12288, vdev_deflate_ratio IS 341/512, dsize is 8184(lsize:8192).
raidz1 4 disks, ASIZE is 11264, vdev_deflate_ratio IS 383/512, dsize is 8426(lsize:8192).
raidz1 5 disks, ASIZE is 10240, vdev_deflate_ratio IS 409/512, dsize is 8180(lsize:8192).
raidz1 6 disks, ASIZE is 10240, vdev_deflate_ratio IS 425/512, dsize is 8500(lsize:8192).
raidz1 7 disks, ASIZE is 10240, vdev_deflate_ratio IS 436/512, dsize is 8720(lsize:8192).
raidz1 8 disks, ASIZE is 10240, vdev_deflate_ratio IS 445/512, dsize is 8900(lsize:8192).
raidz1 9 disks, ASIZE is 9216, vdev_deflate_ratio IS 455/512, dsize is 8190(lsize:8192).
raidz1 10 disks, ASIZE is 9216, vdev_deflate_ratio IS 458/512, dsize is 8244(lsize:8192).
raidz1 11 disks, ASIZE is 9216, vdev_deflate_ratio IS 464/512, dsize is 8352(lsize:8192).
raidz1 12 disks, ASIZE is 9216, vdev_deflate_ratio IS 468/512, dsize is 8424(lsize:8192).
raidz1 13 disks, ASIZE is 9216, vdev_deflate_ratio IS 471/512, dsize is 8478(lsize:8192).
raidz1 14 disks, ASIZE is 9216, vdev_deflate_ratio IS 474/512, dsize is 8532(lsize:8192).
raidz1 15 disks, ASIZE is 9216, vdev_deflate_ratio IS 474/512, dsize is 8532(lsize:8192).
raidz1 16 disks, ASIZE is 9216, vdev_deflate_ratio IS 478/512, dsize is 8604(lsize:8192).
raidz1 17 disks, ASIZE is 9216, vdev_deflate_ratio IS 481/512, dsize is 8658(lsize:8192).
raidz1 18 disks, ASIZE is 9216, vdev_deflate_ratio IS 481/512, dsize is 8658(lsize:8192).
raidz1 19 disks, ASIZE is 9216, vdev_deflate_ratio IS 481/512, dsize is 8658(lsize:8192).
raidz1 20 disks, ASIZE is 9216, vdev_deflate_ratio IS 485/512, dsize is 8730(lsize:8192).

---

raidz2 4 disks, ASIZE is 16896, vdev_deflate_ratio IS 255/512, dsize is 8415(lsize:8192).
raidz2 5 disks, ASIZE is 15360, vdev_deflate_ratio IS 305/512, dsize is 9150(lsize:8192).
raidz2 6 disks, ASIZE is 12288, vdev_deflate_ratio IS 341/512, dsize is 8184(lsize:8192).
raidz2 7 disks, ASIZE is 12288, vdev_deflate_ratio IS 364/512, dsize is 8736(lsize:8192).
raidz2 8 disks, ASIZE is 12288, vdev_deflate_ratio IS 383/512, dsize is 9192(lsize:8192).
raidz2 9 disks, ASIZE is 12288, vdev_deflate_ratio IS 397/512, dsize is 9528(lsize:8192).
raidz2 10 disks, ASIZE is 10752, vdev_deflate_ratio IS 408/512, dsize is 8568(lsize:8192).
raidz2 11 disks, ASIZE is 10752, vdev_deflate_ratio IS 416/512, dsize is 8736(lsize:8192).
raidz2 12 disks, ASIZE is 10752, vdev_deflate_ratio IS 424/512, dsize is 8904(lsize:8192).
raidz2 13 disks, ASIZE is 10752, vdev_deflate_ratio IS 428/512, dsize is 8988(lsize:8192).
raidz2 14 disks, ASIZE is 10752, vdev_deflate_ratio IS 436/512, dsize is 9156(lsize:8192).
raidz2 15 disks, ASIZE is 10752, vdev_deflate_ratio IS 441/512, dsize is 9261(lsize:8192).
raidz2 16 disks, ASIZE is 10752, vdev_deflate_ratio IS 445/512, dsize is 9345(lsize:8192).
raidz2 17 disks, ASIZE is 10752, vdev_deflate_ratio IS 445/512, dsize is 9345(lsize:8192).
raidz2 18 disks, ASIZE is 9216, vdev_deflate_ratio IS 455/512, dsize is 8190(lsize:8192).
raidz2 19 disks, ASIZE is 9216, vdev_deflate_ratio IS 455/512, dsize is 8190(lsize:8192).
raidz2 20 disks, ASIZE is 9216, vdev_deflate_ratio IS 455/512, dsize is 8190(lsize:8192).

---

**Comment by behlendorf** [comment]
I agree this isn't something which isn't at all made clear today.  If you have a proposed solution for this I'd encourage you to open a pull request with the suggested change so it can be commented on.

**Comment by GeLiXin** [comment]
@behlendorf  thanks for your attention. In consideration of compatibility, I have two solutions for this.
One is handle the zvol which use default volblocksize only.  not perfect , but makes a step forward and solved the most common case. All we need is an idle bit in blk_prop of blkptr_t.
Another I deliberated is to handle various blocksize both in volume and filesystem,  more complex
and more exciting.but it may need 8 bits in the blk_pad of blkptr_t.
What about your suggestion on the choice of the two solutions?Or if you have some other suggestion, I will be very thankful to hear it.

**Comment by rlaager** [comment]
@GeLiXin Why is an on-disk format change necessary? The issue here is simply that the code which calculates the default refreservation on zvols is calculating too small of a value. Make that code either calculate the worst-possible value for any pool topology, or make it actually look at the pool topology and calculate correctly.

**Comment by GeLiXin** [comment]
@rlaager because the refreservation on zvols isn't the root of the problem, it just appears
 to be the scapegoat. The root of the problem is we use the wrong vdev_deflate_ratio which calculated by 128K blocksize to account the zvols space which use 8k blocksize. In other words, the zvol didn't use extra space than it's refreservation actually,  but we think it have used , by mistake, and result in an insufficient refreservation problem. In my opinion, If we simply enlarge the refreservaion to evade the mistake, not only leave the bias in zvol's space account, but also a meaningless space waste, which may be 16% of our total space.
The reason I want an on-disk format change is for the consideration of compatibility. Select a new correct deflate ratio is easy but how about the block already existing in our client's pool? These blocks are born with old deflate ratio, if we kill them with a different deflate ratio, the space statistics of dataset may come to chaos. So I plan to use a bit in blkptr_t to identify new blocks from the old, the old blocks will be killed with old defate ratio. Benefit by strategy of Copy-On-Write in ZFS,  most of the old blocks may be killed finally, and new blocks with correct space account will appear more and more. At last we do not need to change the refreservation value of existing zvols, and zvols won't encounter the problem looks like out of pool space any more.

**Comment by rlaager** [comment]
If at all possible, rather than using a bit in the block pointer, I think you should use the enabled_txg feature to track the transaction group number of when this feature ("fixed_deflate") was enabled. This doesn't burn block pointer space for a one-time (per pool) transition.
