### ISSUE TITLE
numerous unnecessary calls to ddt_stat_add() from txg_sync thread

### ISSUE THREAD

**Issue by thegreatgazoo** [openzfs/zfs#4564]
Today I was tracing the txg_sync thread on an idle pool where dedup was never turned on:

``` shell
echo ':mod:zfs' > set_ftrace_filter
echo `pidof txg_sync` > set_ftrace_pid
echo function_graph > current_tracer
```

The tracing lasted for about 5 txg and there were numerous ddt_stat_add() calls:

``` shell
grep -w spa_sync trace | wc -l
5
grep ddt_stat_add trace | wc -l
9920
wc -l trace
11739 trace
```

The spa_sync function spent about 85% of its CPU time in ddt_stat_add() calls:

```
20)               |  spa_sync [zfs]() {
20)               |      ddt_get_dedup_dspace [zfs]() {
20) ! 1170.106 us |      }
20) ! 1376.319 us |  }
```

The ddt_get_dedup_dspace() calls ddt_stat_add() within several nested for loops. That's a complete waste of CPU time and total pollution of CPU caches, because dedup has never been enabled on the pool.

**Comment by behlendorf** [comment]
Nice find, definitely something worth optimizing.  One easy improvement would be skip the loops when the ddt_tree is empty, similar to what's already done in ` ddt_sync_table()`.  There are lots of way to do even better but they'd probably take a little more work, and this should catch the case where a pool has never had dedup enabled.

```diff
diff --git a/module/zfs/ddt.c b/module/zfs/ddt.c
index 12c1b73..2fc7650 100644
--- a/module/zfs/ddt.c
+++ b/module/zfs/ddt.c
@@ -503,9 +503,12 @@ ddt_get_dedup_histogram(spa_t *spa, ddt_histogram_t *ddh)
 
        for (c = 0; c < ZIO_CHECKSUM_FUNCTIONS; c++) {
                ddt_t *ddt = spa->spa_ddt[c];
+
+               if (avl_numnodes(&ddt->ddt_tree) == 0)
+                       continue;
+
                for (type = 0; type < DDT_TYPES; type++) {
-                       for (class = 0; class < DDT_CLASSES;
-                           class++) {
+                       for (class = 0; class < DDT_CLASSES; class++) {
                                ddt_histogram_add(ddh,
                                    &ddt->ddt_histogram_cache[type][class]);
                        }
```
