### ISSUE TITLE
"cannot receive incremental stream:" when receiving a snapshot incremental file stream in a clone

### ISSUE THREAD

**Issue by flaviomreis** [openzfs/zfs#4693]
Hello guys,

Sorry my english, I am brazilian.

This script does not works. It's trying receive a snapshot incremental stream file to a clone of a dataset:
zfs create pool00/dataset01
zfs set mountpoint=/dataset01 pool00/dataset01
echo "1" >> /dataset01
zfs snapshot pool00/dataset01@a
echo "2" >> /dataset01
zfs snapshot pool00/dataset01@b
echo "3" >> /dataset01
zfs snapshot pool00/dataset01@c
echo "4" >> /dataset01
zfs snapshot pool00/dataset01@d
zfs send -i a pool00/dataset01@b > /tmp/pool00_dataset01_b.img
zfs destroy pool00/dataset01@b
zfs clone pool00/dataset01@a pool00/dataset01_a
cat /tmp/pool00_dataset01_b.img | zfs receive pool00/dataset01_a
cannot receive incremental stream: most recent snapshot of pool00/dataset01_a does not
match incremental source

Can you help me please? I try to resolve with zfs-discuss@list.zfsonlinux.org>, by Gregor Kokpa advice me to report a bug.

Thanks

**Comment by kpande** [comment]
it's not clear whether this is unexpected behaviour. can @ahrens or @behlendorf chime in with some details on incremental recv to clone? I wouldn't expect this to work.
