### ISSUE TITLE
Feature request: way to suppress 'features not enabled' warning in zpool status

### ISSUE THREAD

**Issue by GregorKopka** [openzfs/zfs#5016]
This 'nag screens' in zpool status

```
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
```

and

```
status: The pool is formatted using a legacy on-disk format.  The pool can
        still be used, but some features are unavailable.
action: Upgrade the pool using 'zpool upgrade'.  Once this is done, the
        pool will no longer be accessible on software that does not support
        feature flags.
```

are extremely annoying: While the warning might be interesting to some, I _know_ that there are unactivated features on some of my pools (not by accident).

I would like to be able to suppress this on a per-pool level, for example throught a property 'featurewarning=disabled'.

**Comment by FingerlessGlov3s** [comment]
Shame this isn't a setting :-(

**Comment by carlreinke** [comment]
Or maybe a new option `zpool upgrade --suppress` which would set the disabled features to a new `suppressed` state, which is just like `disabled` except that you don't get an upgrade nag.

**Comment by tuxick** [comment]
I 'fixed' it for now by simply removing the UNAVAIL from zfs_health.sh. Maybe making this configurable in the script is the simplest solution.

**Comment by mufunyo** [comment]
Honestly, `zpool clear` should just clear this status until the user tries to enable a feature that is unsupported by the pool version, at which point `zpool upgrade` can be suggested again.

**Comment by freqlabs** [comment]
Maybe "features:" and "format:" can be additional sections only shown with `-v` output?

**Comment by behlendorf** [comment]
This functionality was added with the new compatibility property starting with the 2.1.0 release

.https://github.com/openzfs/zfs/releases/tag/zfs-2.1.0
