### ISSUE TITLE
zvol performance is decreasing  when the number of writing process increasing

### ISSUE THREAD

**Issue by dsw0350** [openzfs/zfs#5019]
I test zfs-0.6.5.7 with a test tool "orion" and  I find that zvol performance is decreasing when the number of writing process increasing.

I create zpool with 8 4G disks and 4 500G zfs volumes(volume block size:4k).

I use the test command: orion -run advanced -testname sd -num_disks 8 -size_small 4 -type rand -simulate raid0 -stripe 4 -cache_size 0 -matrix row -num_large 0 -write

the content of sd.lun:
/dev/zd0
/dev/zd16
/dev/zd32
/dev/zd48

And I  get the following test data:
number of process  |    iops
1                              |    3616
2                              |    1458
3                              |    1141
4                              |     957
5                              |    848
6                              |    779
7                              |    725
8                              |    672
16                            |    630
24                            |    606
32                            |    582
40                            |    555
48                            |    532
56                            |    515
64                            |    495
72                            |    474
80                            |    463
88                            |    461
96                            |    449
104                          |    437
112                          |    428
120                          |    418
128                          |    411
136                          |    405
144                          |    394
152                          |    387
160                          |    384

I think zvol iops should be more with multi process writing concurrently. 
What should I do to improve zvol performance?
Any one can give any advices?

Thank you very much!

**Comment by dsw0350** [comment]
I wonder why the zvol performance is decreasing when the number of writing process increasing.

**Comment by GeLiXin** [comment]
The disk IO delay displays exponential growth on extreme workload,  and resource competition such as memory and lock may reduce your performance too. That means your workload isn't the heavier the better.

**Comment by kpande** [comment]
@dsw0350 please re-test on newer versions and let us know your results.
