### ISSUE TITLE
zvol objsets don't need 7 dnode levels

### ISSUE THREAD

**Issue by tuxoko** [openzfs/zfs#5026]
Currently, every dataset will be created with 7 levels.
In reality, zvol only have 2 objects. One for volume data, and one ZAP which contains only "size".

This patch seems to do the trick which force `levels = 2` when creating zvol. However, if I use `levels = 1` it would crash.
https://gist.github.com/tuxoko/b076905d8f67e3d9d60e782a8ec7bf9a

**Comment by behlendorf** [comment]
Does limiting the tree depth significantly impact the performance?

**Comment by tuxoko** [comment]
It's helpful for import time. Other than that it might help sync heavy load might.
