### ISSUE TITLE
zfs_log_setattr uses mask value incompatible to other OSes

### ISSUE THREAD

**Issue by tuxoko** [openzfs/zfs#5046]
zfs_log_setattr uses ATTR_\* for mask, which is defined on Linux and incompatible to AT_\* which is used by other OSes. This makes pools with dirty log unsafe to cross import between Linux and other OSes.

However, we cannot blindly change the code to use AT_*, otherwise the current Linux user will get corrupted if they happens to have dirty log during upgrade. One way to safely solve this is to leave it as is and introduce a new TX_SETATTR2 type and fix the mask there.

BTW, `zdb -iii` on Linux interpret the mask using AT_*, so it's not even consistent on Linux.

**Comment by kpande** [comment]
@ahrens and @ZackaryWelch might be interested in this.
