### ISSUE TITLE
man-pages wanted

### ISSUE THREAD

**Issue by kernelOfTruth** [openzfs/zfs#5113]
libnvpair
nvlist_alloc

seems to be missing (while looking into https://github.com/illumos/illumos-gate/commit/48dd5e630c9b1773b7b10d08a3b90b6c9062d713 7261 nvlist code should enforce name length limit)

will see if I spot additional ones ...

**Comment by behlendorf** [comment]
avl and kstat are two others.  Initially only man pages for utilities were added to the repo, not man pages for these C libraries.  This could be added to a man3 directory.  That should be part of the -devel packages.

**Comment by Spencer-Kinny** [comment]
@behlendorf 
Can I use man pages available online for this PR.

**Comment by behlendorf** [comment]
@Spencer-Kinny yes.  The source code for libnvpair, libavl, and other libraries came from Illumos so these would be the most appropriate pages to use, https://illumos.org/man.

**Comment by Spencer-Kinny** [comment]
@behlendorf 
Just to confirm, I will be using the following links for the man pages:

libnvpair: https://illumos.org/man/3lib/libnvpair
nvlist_alloc: https://illumos.org/man/3nvpair/nvlist_alloc
avl: https://illumos.org/man/9f/avl
kstat: https://illumos.org/man/1M/kstat

Also, do I need to create separate man pages for the ones that are linked in SEE ALSO section

**Comment by behlendorf** [comment]
Good question.  To be honest, I'm not sure there's a compelling need to add any of these man pages to the repository.  My feeling is it would be sufficient to simply add a link to the Illumos documentation from the relevant source files.  That would be:

./module/avl/avl.c -> https://illumos.org/man/9f/avl

./module/nvpair/nvpair.c ->  https://illumos.org/man/3lib/libnvpair and https://illumos.org/man/3nvpair/nvlist_alloc

./module/os/linux/spl/spl-kstat.c -> https://illumos.org/man/1M/kstat
./module/os/freebsd/spl/spl_kstat.c -> https://illumos.org/man/1M/kstat

**Comment by Spencer-Kinny** [comment]
Okay @behlendorf 

Instead of adding man pages, I'll start adding the links as comments in the above said source files

**Comment by Spencer-Kinny** [comment]
@behlendorf 
Submitted the PR
