### ISSUE TITLE
High CPU usage with huge block sizes

### ISSUE THREAD

**Issue by DeHackEd** [openzfs/zfs#5121]
Yes, I know overriding the module parameter and enabling `zfs set recordsize=4M` is a bit over the top. I have logical and sane reasons for doing this. Anyway.

<pre># perf top -g --max-stack 6
-   29.57%    29.57%  [kernel]   [k] memcpy_erms
   - memcpy_erms
      - 92.43% dbuf_new_size
           dnode_set_blksz
           dmu_object_set_blocksize
-   31.37%     0.02%  [kernel] [k] dbuf_new_size
   - dbuf_new_size
      - dnode_set_blksz
         - dmu_object_set_blocksize
            - zfs_grow_blocksize
                 zfs_write
</pre>

ZFS is a slightly old git tree with ABD on it (my own so-called bleedingedge7 tree). I am downloading files ranging in size from 1 to 4 megabytes to a single dataset at about 1 gigabit per second (approximately). ZFS is using 15-20% of the whole available CPU time across all cores/threads.

Machine specs:
- Dual socket Xeon E5-2620 v4 (2.1 GHz, 8 cores, hyperthreaded, total 32 threads)
- 128 GB of ECC memory
- Drives: 32x 4TB SATA disks in 4 instances of 8-way RAID-Z2.

It seems ZFS spends an awfully large amount of time growing the stored object as it downloads the files over the network. This might be improved through application optimization as it write()s in 8k chunks but right now I'm not in a position to do that.

Edit: formatting only

**Comment by behlendorf** [comment]
@DeHackEd is there any way you could precreate the files using `truncate(1)` or perform a write to an offset a few MB in to the file.  This should act as a hint to ZFS and result in the file being originally created with large blocks.

**Comment by dweeezil** [comment]
Makes me wonder if datasets ought to have a ```minrecordsize``` property.  This issue is certainly exacerbated in the world of ```large_blocks```.

**Comment by DeHackEd** [comment]
I think I can make use of the truncate method, I'll see how that goes and report back tomorrow.

**Comment by DeHackEd** [comment]
By `truncate()`ing the files prior to writing, CPU usage has been reduced dramatically in spite of the application writing to the file in 8k pieces.

Leaving this issue open for now. The workaround works, but I feel there could still be improvement long term.

**Comment by behlendorf** [comment]
We should give some thought to how to gracefully handle this.  A `minrecordsize` property is definitely an option but it would be nice if it somehow just did the right thing in this case.  Ideas welcome.

**Comment by GeLiXin** [comment]
Could we handle this refer to the logical of prefetch stream?  
Predicts further write and double our blocksize growth if the incoming write matchs our previous prediction.

**Comment by kpande** [comment]
@DeHackEd can you reevaluate this on newer versions?

**Comment by DeHackEd** [comment]
Right now, no I'm not really in a position to test it. I don't recall seeing any pushes that would suggest to me it's fixed either.

I'll keep an eye out in case the opportunity presents itself. Maybe I can steal the lab 30-drive server later this month or something.
