### ISSUE TITLE
vdev_nonrot not updated on attach or detach

### ISSUE THREAD

**Issue by inkdot7** [openzfs/zfs#5220]
When testing #4637, I noticed that the `vdev_nonrot` (of parents) not are updated when attaching or detaching devices to an mirror.  I.e. if attaching an HDD to an all-SSD mirror, the mirror is still marked nonrot, as is the pool.  The status is correct after an export/import cycle.

I think the issue is very minor.  Perhaps also messy to deal with, if one has to descend to all zvols for updating...

**Comment by GregorKopka** [comment]
Some questions:
- What's the point in tracking this flag up into the the pool vdev?
- Should one rotating device turn the parent vdev to be rotating - or could it be of use to introduce a type of 'mixed' in case of ambiguity?

**Comment by ss23** [comment]
@GregorKopka 
It's tracked for a few optimizations, e.g. penalizing seeks more on rotational media (`vdev_mirror.c: vdev_mirror_load`). 

The logic for how mixed disk types is already implemented in `vdev.c: vdev_open_children`:
```c
        vd->vdev_nonrot = B_TRUE;
        for (int c = 0; c < children; c++)
                vd->vdev_nonrot &= vd->vdev_child[c]->vdev_nonrot;
```

**Comment by GregorKopka** [comment]
@ss23 
That's for the decision from which mirror side to read from. I can understand to track the rotationg status into the top vdev of a mirror as these are used to implement replace (so a mirror leaf might turn into a mirror itself) so the (outer) mirror can read the status of the replacing (then mirror) leaf.

But I don't get
> the mirror is still marked nonrot, **as is the pool**.

why track rotational status up into the pool root vdev?

**Comment by inkdot7** [comment]
I do not think there is much reason to track the rotational status up in the pool.
There are also definite performance differences within the nonrotational category, like SSD vs NVRAM.
So better if things can work dynamically like the mirror read code's major decision (9f500936): to use the least loaded device(s), which turned out to work well in giving SSD-like performance for a mix of HDD+SSD.
