### ISSUE TITLE
zfs-test contains archful data in a noarch directory and needs to be moved (0.7.0-rc2)

### ISSUE THREAD

**Issue by Conan-Kudo** [openzfs/zfs#5355]
When upgrading my packaging for zfs from 0.6.5.8 to 0.7.0-rc2, I got a complaint from `rpmbuild` indicating that zfs-test (a noarch package) includes archful data (a.k.a compiled binaries) in a noarch area (`/usr/share`).

Lo and behold, there's now `/usr/share/zfs/zfs-tests` which includes quite a few compiled binaries along with test configurations.

Please move them out of `/usr/share/zfs` and put it elsewhere that makes sense for archful data.

**Comment by behlendorf** [comment]
What distribution's packages are you using?  The RPM packages which are generated directly from the ZFS on Linux repository have already created architecture specific zfs-test-* packages for this very reason.  For example: `zfs-test-0.7.0-rc2.el7.centos.x86_64.rpm`.

**Comment by Conan-Kudo** [comment]
@behlendorf I forked from the zfs packaging here to create my own. At the time, none of the contents of zfs-test were archful (they were all scripts in `/usr/share/zfs`), so I turned it noarch.

That being said, it's still wrong to put archful data in a directory that is intended for noarch data.

**Comment by behlendorf** [comment]
Fair point.  The test binaries should be split off in to a `/usr/libexec/zfs-tests` sub-directory.  It would be great if you could propose of pull request for this.

**Comment by Vaelatern** [comment]
This is still the case.

**Comment by Conan-Kudo** [comment]
Now that I've been reminded of this, I'll see if I can make some time to take a look at fixing this...

**Comment by kpande** [comment]
@Conan-Kudo assigned to you :-)
