### ISSUE TITLE
deadlock on pool import (z_null_int 100% CPU)

### ISSUE THREAD

**Issue by TioNisla** [openzfs/zfs#5492]
`
root@amnesiac:~# uname -a
Linux amnesiac 4.8.14 #1 SMP PREEMPT Wed Dec 14 09:59:53 +05 2016 x86_64 Intel(R) Xeon(R) CPU X5660 @ 2.80GHz GenuineIntel GNU/Linux

root@amnesiac:~# modinfo zfs
filename:       /lib/modules/4.8.14/extra/zfs/zfs.ko
version:        0.7.0-rc2
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     B357B02D2BF763509AC3896

root@amnesiac:~# modinfo spl
filename:       /lib/modules/4.8.14/extra/spl/spl.ko
version:        0.7.0-rc2
license:        GPL
author:         OpenZFS on Linux
description:    Solaris Porting Layer
srcversion:     BF45F2B8E8A961F56A146A9

root@amnesiac:~# ps auxww | grep z_null_int
root       675 99.9  0.0      0     0 ?        R<   15:12  28:26 [z_null_int]

root@amnesiac:~# echo w > /proc/sysrq-trigger
[ 1809.172146] sysrq: SysRq : Show Blocked State
[ 1809.172170]   task                        PC stack   pid father
[ 1809.172183] zpool           D 0000000000015340     0   414    411 0x00000000
[ 1809.172187]  ffff88042b545a00 0000000000000000 0000000000000003 ffff88042b790000
[ 1809.172188]  ffff88042812da10 ffff88042812dac8 ffff88042812da38 0000000000000000
[ 1809.172190]  ffff88042b664000 ffffffff81373783 ffff88042812dac0 ffffffffa0045926
[ 1809.172191] Call Trace:
[ 1809.172197]  [<ffffffff81373783>] ? schedule+0x33/0x90
[ 1809.172211]  [<ffffffffa0045926>] ? cv_wait_common+0xc6/0x100 [spl]
[ 1809.172214]  [<ffffffff81063fc0>] ? wake_atomic_t_function+0x50/0x50
[ 1809.172246]  [<ffffffffa04f183b>] ? txg_wait_synced+0xcb/0x110 [zfs]
[ 1809.172263]  [<ffffffffa04ea835>] ? spa_config_update+0xb5/0x110 [zfs]
[ 1809.172279]  [<ffffffffa04e727e>] ? spa_import+0x54e/0x710 [zfs]
[ 1809.172293]  [<ffffffffa0517efc>] ? zfs_ioc_pool_import+0xcc/0x100 [zfs]
[ 1809.172307]  [<ffffffffa051b35a>] ? zfsdev_ioctl+0x45a/0x4e0 [zfs]
[ 1809.172309]  [<ffffffff810f5a2a>] ? do_vfs_ioctl+0x8a/0x5b0
[ 1809.172310]  [<ffffffff810f5f86>] ? SyS_ioctl+0x36/0x70
[ 1809.172312]  [<ffffffff8137761b>] ? entry_SYSCALL_64_fastpath+0x13/0x8f
[ 1809.172321] txg_sync        D 0000000000015340     0   968      2 0x00000000
[ 1809.172323]  ffff880423e50000 0000000000000001 ffff88042364fbe8 ffff880423650000
[ 1809.172324]  ffff88042364fc00 7fffffffffffffff ffff880426c5e990 0000000000000001
[ 1809.172325]  ffff880426c5e1a0 ffffffff81373783 0000000000000000 ffffffff8137693c
[ 1809.172327] Call Trace:
[ 1809.172328]  [<ffffffff81373783>] ? schedule+0x33/0x90
[ 1809.172329]  [<ffffffff8137693c>] ? schedule_timeout+0x19c/0x240
[ 1809.172333]  [<ffffffffa007c47d>] ? nvlist_free+0x4d/0xa0 [znvpair]
[ 1809.172334]  [<ffffffff8137325e>] ? io_schedule_timeout+0x5e/0x90
[ 1809.172336]  [<ffffffffa00458f7>] ? cv_wait_common+0x97/0x100 [spl]
[ 1809.172337]  [<ffffffff81063fc0>] ? wake_atomic_t_function+0x50/0x50
[ 1809.172350]  [<ffffffffa053b5b5>] ? zio_wait+0xc5/0x140 [zfs]
[ 1809.172365]  [<ffffffffa04fc02b>] ? vdev_label_sync_list+0xeb/0x160 [zfs]
[ 1809.172380]  [<ffffffffa04fc194>] ? vdev_config_sync+0xf4/0x170 [zfs]
[ 1809.172397]  [<ffffffffa04e2296>] ? spa_sync+0x4a6/0xce0 [zfs]
[ 1809.172413]  [<ffffffffa04f2241>] ? txg_sync_thread+0x2d1/0x450 [zfs]
[ 1809.172429]  [<ffffffffa04f1f70>] ? txg_quiesce_thread+0x350/0x350 [zfs]
[ 1809.172431]  [<ffffffffa0041017>] ? thread_generic_wrapper+0x67/0x80 [spl]
[ 1809.172433]  [<ffffffffa0040fb0>] ? __thread_exit+0x10/0x10 [spl]
[ 1809.172434]  [<ffffffff8104bfe8>] ? kthread+0xb8/0xd0
[ 1809.172435]  [<ffffffff8137780f>] ? ret_from_fork+0x1f/0x40
[ 1809.172436]  [<ffffffff8104bf30>] ? kthread_worker_fn+0x100/0x100
[ 1809.172437] zpool           D 0000000000015340     0  1024      1 0x00000004
[ 1809.172439]  ffff880428a6e400 ffffffff81064ec1 ffffffff810f9c00 ffff880429224000
[ 1809.172440]  ffff880429223de0 ffffffffa06bb124 ffff880428a6e400 00000000ffffffff
[ 1809.172441]  ffffffffa06bb128 ffffffff81373783 ffffffffa06bb120 ffffffff81373adc
[ 1809.172442] Call Trace:
[ 1809.172444]  [<ffffffff81064ec1>] ? mutex_optimistic_spin+0x51/0x1c0
[ 1809.172445]  [<ffffffff810f9c00>] ? __dentry_kill+0xa0/0x150
[ 1809.172447]  [<ffffffff81373783>] ? schedule+0x33/0x90
[ 1809.172448]  [<ffffffff81373adc>] ? schedule_preempt_disabled+0xc/0x20
[ 1809.172449]  [<ffffffff813753b2>] ? __mutex_lock_slowpath+0xb2/0x120
[ 1809.172451]  [<ffffffffa007c540>] ? nv_mem_zalloc.isra.12+0x20/0x30 [znvpair]
[ 1809.172452]  [<ffffffff8137542e>] ? mutex_lock+0xe/0x20
[ 1809.172469]  [<ffffffffa04e9dd1>] ? spa_all_configs+0x31/0xd0 [zfs]
[ 1809.172483]  [<ffffffffa0518341>] ? zfs_ioc_pool_configs+0x11/0x40 [zfs]
[ 1809.172496]  [<ffffffffa051b35a>] ? zfsdev_ioctl+0x45a/0x4e0 [zfs]
[ 1809.172498]  [<ffffffff810f5a2a>] ? do_vfs_ioctl+0x8a/0x5b0
[ 1809.172499]  [<ffffffff810f5f86>] ? SyS_ioctl+0x36/0x70
[ 1809.172500]  [<ffffffff8137761b>] ? entry_SYSCALL_64_fastpath+0x13/0x8f
`

**Comment by kpande** [comment]
this was resolved in #5495, correct?
