### ISSUE TITLE
Test case: nopwrite_volume failure

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#5510]
Type                                | Version/Name
  ---                                  |     --- 
ZFS Version                  | 0.7.0-rc2
SPL Version                  | 0.7.0-rc2

### Describe the problem you're observing

Occasional failures of the nopwrite_volume test case during automated testing.

### Describe how to reproduce the problem

A full run of the ZFS Test Suite can occasionally produce the issue.

### Include any warning/errors/backtraces from the system logs

[Full log](
http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20i686%20%28TEST%29/builds/405/steps/shell_11/logs/log)

```
est: /usr/share/zfs/zfs-tests/tests/functional/nopwrite/nopwrite_volume (run as root) [00:15] [FAIL]
03:56:33.06 ASSERTION: nopwrite works on volumes
03:56:33.16 SUCCESS: /sbin/zfs set compress=on testpool.23846/testvol.nopwrite
03:56:33.28 SUCCESS: /sbin/zfs set checksum=sha256 testpool.23846/testvol.nopwrite
03:56:43.31 SUCCESS: /sbin/zfs clone testpool.23846/testvol.nopwrite@a testpool.23846/clone
03:56:43.46 SUCCESS: /sbin/zfs set compress=on testpool.23846/clone
03:56:43.57 SUCCESS: /sbin/zfs set checksum=sha256 testpool.23846/clone
03:56:47.43 NOTE: Comparing 29878272 and 4378624 given 2% (calculated: 14.65%)
03:56:47.44 ERROR: verify_nopwrite testpool.23846/testvol.nopwrite testpool.23846/testvol.nopwrite@a testpool.23846/clone exited 1
03:56:47.44 
03:56:47.44 NOTE: Performing local cleanup via log_onexit (cleanup)
03:56:48.10 SUCCESS: /sbin/zfs destroy -R testpool.23846/testvol.nopwrite
Test: /usr/share/zfs/zfs-tests/tests/functional/nopwrite/cleanup (run as root) [00:00] [PASS]
03:56:48.58 SUCCESS: rm -f -rf /var/tmp/testdir23846
03:56:48.60 lsblk: /dev/mapper/loop0: not a block device
```

**Comment by behlendorf** [comment]
Resolved by 95401cb6f7aa9ec3dd2d61335d2dcc9459c2661c.

**Comment by Nasf-Fan** [comment]
It seems that I hit the trouble again on zfs-0.7.0:
http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20i686%20%28TEST%29/builds/3165/steps/shell_8/logs/stdio
http://build.zfsonlinux.org/builders/Ubuntu%2014.04%20i686%20%28TEST%29/builds/3165/steps/shell_8/logs/log

**Comment by behlendorf** [comment]
Reopening so it can be investigated.
