### ISSUE TITLE
ARC Data cache been evict when hitting Metadata limit

### ISSUE THREAD

**Issue by AndCycle** [openzfs/zfs#5537]
this is an observation recently on my system,
I just see the behavior as I work on my munin to visualize ARC usage

Gentoo 
kernel ver 4.4.39
spl-zfs-0.6.5.8
zfs-0.6.5.8

with patch https://github.com/zfsonlinux/zfs/pull/4850

as you can see the data size is drop to almost zero when metadata usage hit the limit.

![yazol_zfs_stats_arc_size_breakdown-day](https://cloud.githubusercontent.com/assets/4460370/21537240/5c3377b0-cdc9-11e6-9996-7724c9e002eb.png)

![yazol_zfs_stats_arc_size-day](https://cloud.githubusercontent.com/assets/4460370/21537238/5a476ca4-cdc9-11e6-8c90-a4d35fe8251f.png)

![meminfo_phisical-day](https://cloud.githubusercontent.com/assets/4460370/21537253/a22e3610-cdc9-11e6-81f8-b34c53168a34.png)

**Comment by perfinion** [comment]
Related to https://github.com/zfsonlinux/zfs/issues/5418 ?

**Comment by AndCycle** [comment]
@perfinion maybe, it's hard to tell what happened because currently there is no tool to monitor arcstats continuously,

here is my current work in progress for munin to monitor it,

https://github.com/AndCycle/contrib/blob/yazol_plugin/plugins/zfs/yazol_zfs_stats_

**Comment by dweeezil** [comment]
@AndCycle I have a hunch this is due to the balanced-mode adjuster.  Try setting ```zfs_arc_meta_strategy=0```.

**Comment by richardelling** [comment]
FYI, both telegraf and collectd open source aggregators have agents that collect ARC stats. In the commercial world, there have been collectors available for a very long time, I'd recommend Circonus.

**Comment by kpande** [comment]
i think by 'continuously' they mean more frequent intervals than those collectors allow for.

**Comment by AndCycle** [comment]
@kpande I think he got me, I didn't try out that much monitoring tool as many of them lack builtin visualize tool, and as a personal server I only search through free solution for this, 

munin is one that easy enough to do, although the base of munin is pretty sucks and full of bugs, and many contribute plugin have incorrect way to do the calculation which force me to write one for my own,

**Comment by AndCycle** [comment]
@dweeezil you got it.

![yazol_zfs_stats_arc_size-day 1](https://cloud.githubusercontent.com/assets/4460370/21546868/4ad7d868-ce1d-11e6-80bb-0e3a93155673.png)
![yazol_zfs_stats_arc_size_breakdown-day 1](https://cloud.githubusercontent.com/assets/4460370/21546870/4d9ea0f4-ce1d-11e6-8ebe-86e68150d1b0.png)

**Comment by kernelOfTruth** [comment]
referencing https://github.com/zfsonlinux/zfs/issues/5128#issuecomment-247823375 (Poor cache performance) and https://github.com/zfsonlinux/zfs/issues/5418 (ARC efficiency regression) again

**Comment by kernelOfTruth** [comment]
@dweeezil could also be memcg

here's some notes that I collected while investigating into the matter and which landed in /etc/modprobe.d/zfs.conf

```
# Your system is having trouble keeping the metadata under the limit and its not showing much evictable memory. 
# Try setting the tunable zfs_arc_meta_strategy to zero and see if the traditional metadata-only adjuster doesn't work better.
#
# The problem appears to be the continuing evolution of memory cgroups (memcg). 
# If you boot with cgroup_disable=memory the reclaiming should start working again. I've not worked up a patch yet.
#
# options zfs zfs_arc_meta_strategy=0
```

**Comment by AndCycle** [comment]
for ref. 
I do have `Memory Resource Controller for Control Groups` and lot's cgroup related option selected in my kernel.

**Comment by dweeezil** [comment]
[This](https://github.com/zfsonlinux/zfs/blob/master/module/zfs/zfs_vfsops.c#L1244) was added to help deal with the memcg issue.  There didn't seem to be any way to coax the normal SB shrinker into doing the Right Thing.

**Comment by kernelOfTruth** [comment]
referencing https://github.com/zfsonlinux/zfs/issues/3303#issuecomment-111760476 arc_adapt left spinning after rsync with lots of small files

it might be also worth it to take a look at

```
/sys/module/zfs/parameters/zfs_arc_meta_adjust_restarts
```

**Comment by kpande** [comment]
is this a problem with ABD?
