### ISSUE TITLE
ztest: (!copied) is equivalent to (hdr->b_l1hdr.b_freeze_cksum == NULL)

### ISSUE THREAD

**Issue by dweeezil** [openzfs/zfs#5721]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 14.04
Linux Kernel                 | 3.14 and 4.9.2 (both generic upstream kernels)
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc3_57_g544b805 (or slightly older master)
SPL Version                  | 0.7.0-rc3 (or slightly older master)

### Describe the problem you're observing
Assertion hit in ```arc_buf_try_copy_decompressed_data()``` as shown in issue subject.
### Describe how to reproduce the problem
Usually by writing files to a ZFS dataset without compression enabled.
### Include any warning/errors/backtraces from the system logs
I've got 3 paths to this panic starting from:
 - spa_load() in "zpool import" task
 - zio_execute() in z_rd_int task
 - zio_execute() in z_wr_iss

The full stack traces are available [here](https://gist.github.com/dweeezil/9b56c7002232d7ffa9d8a4e99ad47c18).

This happens pretty sporadically during routing testing, typically involving writes to datasets without compression enabled.  I've not gotten, nor tried to find yet, a reliable reproducer.  Obviously this requires a debug-enabled build.

**Comment by dweeezil** [comment]
I now have a pool in an 1GiB file vdev which will reproduce this problem 100% of the time simply by trying to import it.

**Comment by dweeezil** [comment]
The triggering condition is setting ```zfs_flags=1``` to enable dprintf (and disabling everything else).

**Comment by dweeezil** [comment]
These ```b_freeze_cksum``` tests should be suppressed if ```ZFS_DEBUG_MODIFY``` is clear in ```zfs_flags```.

**Comment by behlendorf** [comment]
Yes, it definitely appears that way.  There are several other concerning `b_freeze_cksum` debug checks which don't appear to be protected by ZFS_DEBUG_MODIFY which are also worth double-checking.

**Comment by behlendorf** [comment]
Closing, resolved by #8979.
