### ISSUE TITLE
Pool with "faulted" vdevs detected, but still importable

### ISSUE THREAD

**Issue by DeHackEd** [openzfs/zfs#5901]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7
Linux Kernel                 | 4.9.11-1.el7.elrepo.x86_64
Architecture                 | amd64
ZFS Version                  | zfs-0.7.0-rc3_143_g8614ddf
SPL Version                  | spl-0.7.0-rc3_4_ge0aacd9

### Describe the problem you're observing

<pre># zpool import
   pool: poolname
     id: 1972519149537850716
  state: UNAVAIL
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	poolname    UNAVAIL  insufficient replicas
	  raidz2-0  ONLINE
	    A0      ONLINE
	    A24+0   ONLINE
	    A1      ONLINE
	    A24+1   ONLINE
	    A2      ONLINE
	    A24+2   ONLINE
	    A3      ONLINE
	    A24+3   ONLINE
	  raidz2-1  DEGRADED
	    A4      ONLINE
	    A24+4   ONLINE
	    A5      ONLINE
	    A24+5   ONLINE
	    A6      ONLINE
	    A24+6   ONLINE
	    A7      ONLINE
	    A24+7   FAULTED  corrupted data
	  raidz2-2  ONLINE
	    A8      ONLINE
	    A24+8   ONLINE
	    A9      ONLINE
	    A24+9   ONLINE
	    A10     ONLINE
	    A24+10  ONLINE
	    A11     ONLINE
	    A24+11  ONLINE
	  raidz2-3  UNAVAIL  insufficient replicas
	    A12     FAULTED  corrupted data
	    A24+12  ONLINE
	    A13     FAULTED  corrupted data
	    A24+13  FAULTED  corrupted data
	    A14     FAULTED  corrupted data
	    A24+14  FAULTED  corrupted data
	    A15     FAULTED  corrupted data
	    A24+15  FAULTED  corrupted data
	  raidz2-4  ONLINE
	    A16     ONLINE
	    A24+16  ONLINE
	    A17     ONLINE
	    A24+17  ONLINE
	    A18     ONLINE
	    A24+18  ONLINE
	    A19     ONLINE
	    A24+19  ONLINE
	cache
	  zfsL2ARC
	spares
	  A20
	  A24+20
	  A21
# zpool import poolname
# zpool list
NAME       SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
poolname   145T   102G   145T         -     0%     0%  1.00x  ONLINE  -

</pre>

### Describe how to reproduce the problem

(Note: this is just a theory. I can't reproduce right now)

All these drives are in an array that lost power while the server remained powered. Said server was rebooted to purge the damaged pool and get everything back up to "sane" conditions again. The pool was in this state, but was easily imported. Scrub also detected no errors.

Explicit export clears the issues and makes the pool appear healthy again.

### Include any warning/errors/backtraces from the system logs

Can't find any logs or errors outside the `zpool import` output above.

**Comment by kpande** [comment]
I can confirm this bug in 0.6.5 but with a different scenario using object storage as backend, a stripe-only pool (no mirrors, parity and copies=1) had checksum errors on more than one vdev and the pool I/O was not suspended. I could import the pool, attempting to execute zfs-related commands or I/O would hang until the system was rebooted.
