### ISSUE TITLE
Require new code to pass build in-tree for commit to master

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#5911]
Certain kernel configurations such as monolithic builds, those requiring signed modules and disposing of the original signing key at build time, or those using CONFIG_PAX_RAP=y requite that SPL and ZFS be built in-tree. While configuring the sources for this sort of build is documented, new code coming into master does not validate builds in-tree as a requirement to merge. For example, the recent 4.11 API commit (a3478c0747) throws a defined #error when building in-tree with 4.9.16 using the current grsec patch, whereas the same exact sources build fine in DKMS (but require CONFIG_PAX_RAP=n to actually be loadable in the kernel).

Since the configurations requiring this capability are often used in mission critical systems (hardened, embedded, etc), i suggest passing in-tree builds against the current stable releases as a validation requirement for merging to master.

**Comment by sempervictus** [comment]
#5912 is another example of build issues seeping in which aren't supported in-tree since its strictly C89.

With that PR merged in, i'm stil stuck, now with:

```
fs/zfs/zfs/zpl_ctldir.c:111:1: error: type defaults to ‘int’ in declaration of ‘ZPL_GETATTR_WRAPPER’ [-Werror=implicit-int]
fs/zfs/zfs/zpl_ctldir.c:157:13: error: ‘zpl_root_getattr’ undeclared here (not in a function)
fs/zfs/zfs/zpl_ctldir.c:392:1: error: type defaults to ‘int’ in declaration of ‘ZPL_GETATTR_WRAPPER’ [-Werror=implicit-int]
fs/zfs/zfs/zpl_ctldir.c:420:13: error: ‘zpl_snapdir_getattr’ undeclared here (not in a function)
fs/zfs/zfs/zpl_ctldir.c:541:1: error: type defaults to ‘int’ in declaration of ‘ZPL_GETATTR_WRAPPER’ [-Werror=implicit-int]
fs/zfs/zfs/zpl_ctldir.c:565:13: error: ‘zpl_shares_getattr’ undeclared here (not in a function)
fs/zfs/zfs/zpl_inode.c:361:1: error: type defaults to ‘int’ in declaration of ‘ZPL_GETATTR_WRAPPER’ [-Werror=implicit-int]
fs/zfs/zfs/zpl_inode.c:713:13: error: ‘zpl_getattr’ undeclared here (not in a function)
fs/zfs/zfs/zpl_file.c:389:29: error: passing argument 1 of ‘generic_write_checks’ from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/zpl_file.c:389:35: error: passing argument 2 of ‘generic_write_checks’ from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/zpl_file.c:389:8: error: too many arguments to function ‘generic_write_checks’
```
Those last error saying that too many arguments are being passed is what makes me think its an autoconf/automake issue,

**Comment by behlendorf** [comment]
Yes, this does look like an issue introduced by the recent 4.11 compatibility changes. 
 @ofaaland or @tuxoko could you look in to this.

@sempervictus we do already require that all changes be built in tree for exactly this reason.  The [Kernel Built-in](http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29) builder does this using the [this script](https://github.com/zfsonlinux/zfs-buildbot/blob/master/scripts/bb-build-linux.sh) and the very latest kernel.org kernel.  That provides us some coverage since those tests [did pass](http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29/builds/11778), but clearly not enough.  Perhaps we could add an additional builder with does the same build with a PAX enabled kernel and additional CONFIG_* flags to provide more coverage.  Where would be the best place to clone such a kernel from?

**Comment by sempervictus** [comment]
I would actually look to something like the [Arch](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/linux-grsec) Linux or Alpine packaging scripts for this since they are just shell scripts which acquire and patch source trees. I think a pre-build step issuing the configure and copy-builtin commands should handle getting the version of ZFS to be tested into the kernel tree.

The shell scripts (PKGBUILD in the case of Arch) can pin versions or pull from git repos pre-populated with versioned and patched source trees allowing us to target specific versions with specific PKGBUILDs. [](url)

Question is, how do we handle installation of the new kernel with the modules, reboot into it, and ztest subsequent to the reboot acros platforms?

**Comment by ofaaland** [comment]
@sempervictus, 

I have a cloned copy of linus' kernel git tree, and the only 4.9 tags are 4.9 and 4.9-rc[1-8].  Looks like after 2.6 they stopped the 3-part version scheme.

Where did you get 4.9.16?  Arch?

**Comment by tuxoko** [comment]
@ofaaland Linus' git tree doesn't have stable update. You can get them from linux-stable.git

The build error seems like configure error, @sempervictus can you post the config.log

**Comment by sempervictus** [comment]
@behlendorf: #5912 is actually needed to build in-tree since, AFAIK, Linux doesn't allow C99 when building the kernel itself.

@tuxoko:  here's how i've been testing this - 
```
#!/bin/bash
KDIR="//path/to/kernel/tree"
ZDIR="$(dirname $(readlink -f $0))"
cd "$ZDIR"
cd spl
./configure --enable-linux-builtin --with-linux=$KDIR && ./copy-builtin $KDIR
cd ../zfs
./configure --enable-linux-builtin --with-linux=$KDIR --with-spl=$KDIR && ./copy-builtin $KDIR
cd "$KDIR" && make -j20 2>&1 | tee /tmp/kern_zfs_build-$(date +%Y%m%d-%H%M).log
```
[SPL](http://pastebin.com/3cBupx7k) config segment
[ZFS](http://pastebin.com/6zfcUGVC) config segment

**Comment by tuxoko** [comment]
@sempervictus 
You didn't run `./autogen.sh`

**Comment by sempervictus** [comment]
Sorry, was run prior outside the script after I merged all the PRs. Re-running momentarily

**Comment by sempervictus** [comment]
So i think i figured out whats going on, but not why. I'm trying to build SPL and ZFS directly into the kernel for 4.9.14-6, but SPL and ZFS configure output shows them to be detecting my current _running_ version which is 4.9.14-2. Are there flags i should be passing to autogen in order to have it recognize that we're going for in-tree and that the build directory and source version have nada to do with the running kernel?

**Comment by ofaaland** [comment]
I think this is what you are looking for:

> $./configure --help | grep linux
>  --enable-linux-builtin  Configure for builtin in-tree kernel modules
>  --with-linux=PATH       Path to kernel source
>  --with-linux-obj=PATH   Path to kernel build objects

For example, see the stdio from one of the builders:

http://build.zfsonlinux.org/builders/Kernel.org%20Default%20x86_64%20%28BUILD%29/builds/11753/steps/shell_2/logs/stdio

**Comment by ofaaland** [comment]
@sempervictus , can you attach the config.log from the SPL and ZFS builds?  It has the output from failed configure tests, including the code that configure tried to build and the compiler complaints.

**Comment by sempervictus** [comment]
ofaaland:i'll try to build against a thinner kernel for logging, but the build in-tree is now failing @:
```FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'blk_queue_write_cache'```
The --with-linux-obj and --with-spl-obj all pointing to the kernel tree fails, and i tried pulling that from the buildbot's own build scripts.

**Comment by sempervictus** [comment]
@ofaaland: when i point --with-linux-obj to the linux source tree, configure fails with:
```
checking kernel source directory... ../linux-4.9
checking kernel build directory... ../linux-4.9
checking kernel source version... Not found
configure: error: 
	*** Cannot find UTS_RELEASE definition.
	*** Please run 'make prepare' inside the kernel source tree.
```
Running make prepare before the ZFS tree goes into the kernel excludes it from the resulting .config, which is a bit of a mess. I'll see what i can do to work around that in the packaging, probably have to re-copy the input config after doing the built-in stuff.

**Comment by sempervictus** [comment]
So the workaround seems to be to make prepare prior and make clean; make prepare after copy-builtin, but the GPL-only problem persists no matter how i do this. If i build as a module, i get the blk_queue_write_cache problem, if i build directly into the kernel, it just doesn't boot (hangs at loading initramfs from grub).

**Comment by ofaaland** [comment]
@sempervictus 
OK.
1. What distro and version are you building on?
2. Are you able to build spl and zfs vanilla, against the running kernel, without error?  e.g. no --with-linux-* or --enable-linux-builtin arguments to configure

**Comment by ofaaland** [comment]
@sempervictus nevermind question 2 above.  However it would be interesting to know the distro and version your build machine is on.

**Comment by sempervictus** [comment]
It's arch, so rolling, kernel is pulled from official linux archives, gets grsec, bfq, and network related patches, then SPL and ZFS.

**Comment by ofaaland** [comment]
OK, thanks.

**Comment by sempervictus** [comment]
Well, i got it to build, but i can't seem to get it to load. According to PAX, ZFS is overwriting a function pointer causing a massive kernel crash, and halting the system. Can't capture the text, but i did grab an image: https://imagebin.ca/v/3GUR0FDqWYHc

Cant seem to find Brad Spengler's github handle to ping him on this.
Anyone have thoughts on why this is happening?

**Comment by tuxoko** [comment]
It's the RAP. It has some sort of function pointer protection. I assume it doesn't like the way thread_generic_wrapper does with function pointer.

**Comment by bunder2015** [comment]
PAX appears to be EOL.  https://grsecurity.net/passing_the_baton.php

**Comment by sempervictus** [comment]
Not exactly - they're ending their public releases, but the work seems to
be getting forward ported in a few repos while KSPP catches up (and Mr.
Cook seems to be making rather fast progress splitting up the GRSEC
functions into their own trees at
https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/).
This may actually result in much wider availability and use of the
functionality, especially given that its GPLv2 code, which doesnt suffer
from CDDL license constraints like ZoL.

There's also commercial orgs - hosting providers, medical facilities, etc,
which should be able to afford whatever grsec is asking (compared to the
attack surface it covers). They tend to have more media comprising their
VDEVs than most of us have seen in a single facility.

Lets see where upstream goes with this - if they punt to SELinux/RSBAC, it
would be sad. Full MPROTECT mitigations from PAX ported into mainline
however would be a godsend.

**Comment by sempervictus** [comment]
So this
```
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'blk_queue_write_cache'
```
is still a problem in-tree. A bit confused as to why its not out-of-tree, but then again the buid system is more confusing than the C. :)

**Comment by tonyhutter** [comment]
@sempervictus this may be unrelated, but you might want to look at https://github.com/zfsonlinux/zfs/commit/f68b51aa3f7594e17dff7f4b9d6b3af31d01795b and https://github.com/zfsonlinux/zfs/pull/7447/commits/c5e01cc02a09aaf942b31f930ac7e02960909bcc for your  `blk_queue_write_cache` issue.  They're slated to go into 0.7.9.

**Comment by sempervictus** [comment]
Thank you sir, will back port those and see what happens. There's a similar problem with rcu_tree functions as well.
