### ISSUE TITLE
NFS on ZFS : knsfd continues to lock snapshot directory.

### ISSUE THREAD

**Issue by hideAki76** [openzfs/zfs#6000]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04 (Xenial Xerus)
Linux Kernel                 | 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9-1(#5833 patched)
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing
I use sharenfs to share the snapshot directory.
A knfsd process continues to lock the snapshot directory.

### Describe how to reproduce the problem

1. Share NFS & take snapshot
   server$ sudo zfs create pool/share
   server$ sudo zfs set sharenfs=rw=@192.168.x.x/24,insecure,sync,no_subtree_check,fsid=1 pool/share
   server$ sudo touch share/sharefile
   server$ sudo zfs snap pool/share@1

2. Mount
   client$ sudo mount -t nfs4 -r server:/share /tmp/mount
   
3. Browse snapshot file
   client$ less /tmp/mount/.zfs/snapshot/1/sharefile
   
4. Unmount
   client$ sudo umount /tmp/mount/
   
5. Destroy
   server$ sudo zfs destroy pool/share@1
   cannot destroy snapshot pool/share@1: dataset is busy

### Include any warning/errors/backtraces from the system logs

command output:
```
server$ fuser -va share/.zfs/snapshot/1/
                     USER        PID ACCESS COMMAND
share/.zfs/snapshot/1:
                     root     kernel mount share/.zfs/snapshot/1
                     root     kernel knfsd share/.zfs/snapshot/1
                     
```

Syslog excerpt:
```
No errors are recorded.
```

**Comment by kpande** [comment]
this is not a bug, but a limitation of the current NFS snapshot browsing implementation as described in https://github.com/zfsonlinux/zfs/commit/73d84cf876a883ae42eaaedfb6eeaff62706df88 using the hackish workarounds that `.zfs/snapshot` does.

**Comment by behlendorf** [comment]
@hideAki76 commit 9b77d1c9585572b7ce3af204d40278752d5f5842, which is in the master branch has improved the situation in regards to accessing snapshots over nfs.  I'd be interested to see what you're results are using the master version of zfs.

**Comment by hideAki76** [comment]
@behlendorf I already tried it (0.7.0-master version and 0.6.5.9-1-#5833Patched). It did not improve. The behavior of that problem occurs only with sharenfs.

**Comment by hideAki76** [comment]
I love commit 9b77d1c. The fix solved many of the problems (symlink, Dentry still in use, and more...). But, this problem was not solved.

**Comment by tuxoko** [comment]
@hideAki76 
The only way seems to be unexport the zfs.
I'm not sure if you're able to only unexport the snapshot. As far as I can see it seems to refuse to unexport it if it's implicitly exported by crossmnt. Seems like an issue with nfs server.

**Comment by hideAki76** [comment]
**zfs sharenfs command setting ( filesystem zfs ) :**

```
server$ fuser -va /opt/zfs/share/
                     USER        PID ACCESS COMMAND
/opt/zfs/share/:
                     root     kernel mount /opt/zfs/share/
                     root     kernel knfsd /opt/zfs/share/
```
knfsd continues to lock.

**kernel-nfs-server "exports file" setting ( filesystem ext4 ) :**
```
server$ fuser -va /opt/nfs/share/
                     USER        PID ACCESS COMMAND
/opt/nfs/share:
```
knfsd process does not exist.

Why does knfsd lock on zfs file system?

**Comment by tuxoko** [comment]
@hideAki76 
> knfsd process does not exist.

It's actually called nfsd.

> Why does knfsd lock on zfs file system?

Because it's exporting it.

**Comment by rothbri6** [comment]
Inquiring if any work has been done with this issue.  I have ran into the same issue on RHEL 7.4 with zfsonllinux 0.7.2.  We are managing our own nfs mounts, and zfs snapshots wont delete any that you have mounted unless you unshare the mount.

**Comment by gmelikov** [comment]
It's reproducible on master e4e94ca3154a9e58ac20e5409c003895ec859964 ,you can't destroy snapshot even when nfs client was unmounted, only after nfsd restart (if you opened snapshot via nfs).

**Comment by AaronJackson** [comment]
e4e94ca was version 0.8.2 right? I am running 0.7.12 and I'm able to destroy snapshots which have been accessed over NFS by doing `exportfs -ra`. This seems a bit safer than restarting nfsd, especially if there are soft mounted NFS clients.

ZFS version 0.7.12-1
CentOS 3.10.0-862.14.4.el7.x86_64

I'm now wondering if adding `crontab -ra` to my crontab is a sensible solution.
