### ISSUE TITLE
zfs utils fail if POSIXLY_CORRECT=1

### ISSUE THREAD

**Issue by jelmd** [openzfs/zfs#6004]
ZFS utils fail/spit out meaning less error messages if env var *POSIXLY_CORRECT* is set (e.g. to 1).

Took quite some time, to find out, that buggy CLI parsing (tool execution under the hood?)  caused proper commands to fail. E.g.:
```
# zpool create -f -o ashift=9 -o failmode=continue -O compression=on rpool /dev/sda2
too many arguments
usage: mount <dataset> <mountpoint>
cannot mount 'rpool': Invalid argument
```
or
```
# zfs mount rpool
too many arguments
usage: mount <dataset> <mountpoint>
cannot mount 'rpool': Invalid argument
```
and even is somehow dangerous
```
# zfs create -p rpool/ROOT/linux
too many arguments
usage: mount <dataset> <mountpoint>
cannot mount 'rpool/ROOT': Invalid argument
# zfs list
NAME         USED  AVAIL  REFER  MOUNTPOINT
rpool       81,5K  15,1G    19K  /rpool
rpool/ROOT    19K  15,1G    19K  /rpool/ROOT
```
The ROOT zfs didn't exist before the zfs create ...
 
### How to reproduce the problem
`export POSIXLY_CORRECT=1` and start working with zfs utils.

### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04.1 (xenial)
Linux Kernel                 | 4.4.0-31-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu10
SPL Version                  | 0.6.5.6-0ubuntu1

**Comment by jelmd** [comment]
Found out, that the root cause is actually the mount utility of util-linux. E.g.
`zfs create rpool/zones/bla`  internally execs `/bin/mount -t zfs -o defaults,atime,dev,exec,rw,suid,nomand,zfsutil rpool/zones/bla /zones/bla`, and [util-linux/libmount/src/context_mount.c:exec_helper()](https://github.com/karelzak/util-linux/blob/master/libmount/src/context_mount.c#L607) turns it into `/sbin/mount.zfs rpool/zones/bla /zones/bla -o rw,zfsutil` which is obviously buggy.

Wondering, why zfs doesn't use the '-i' flag when execing /bin/mount - this would workaround the bug introduced by exec_helper().

**Comment by jelmd** [comment]
Problem still exists and shoots us into the foot again and again.

**Comment by behlendorf** [comment]
@jelmd this should be resolved in the master branch since the `zfs` command  no longer directly calls `/bin/mount`.

**Comment by jelmd** [comment]
Ah ok, thanx a lot!

**Comment by behlendorf** [comment]
Closing as mentioned above.  This issue is believed to have been resolved.
