### ISSUE TITLE
Unexplained ARC metadata usage

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#6042]
In thinking about performance at work and also thinking about it because of #6040, it occurs to me that if we have a situation where we need to lookup an indirect block, we have multiple copies, one is in cache and the others are not, we can randomly select an uncached copy and generate an unnecessary IO. This hurts cache efficiency, which hurts performance on particularly large indirect block trees that do not fit entirely in RAM. This effect gets amortized by ARC on the upper levels of the indirect block tree and can be mitigated on the lowest level by doing `redundant_metadata=most`, but it would be nice if we modified the code to check for cached copies before making a random selection.

I would like to hear what others think about this. I suspect there is an opportunity here to reduce unnecessary IOs, but it is possible that I made a mistake in reasoning. I have far bigger bottlenecks to tackle for work and given the easy way of mitigating this issue, this will not be a priority for a while.

**Comment by richardelling** [comment]
Which "cache" are you referring to here? Obviously not the ARC...

**Comment by ryao** [comment]
@richardelling I am referring to the ARC. It caches indirect blocks for files and zvols. If we are traversing them, we have at least two options and randomly select between them. My reasoning is that a random IO workload will have metadata misses unless we have sufficient cache for all copies to be cached.

I have some empirical evidence from work to support this. On a system with 256GB of RAM and 0.6.5.9, running a random IO workload with 4x 400GB zvols, IOPS increased from 23,000 to 26,000 after primarycache=metadata and increasing arc_meta_limit to the maximum size of ARC. Some quick math suggests the indirection tree would be 1.6TB / 4KB / 128 * 16KB + 1.6TB / 4KB / 128^2 * 16KB + 1.6TiB / 4KB / 128^3 * 16KB ... ~ 55.4GB. However, arc metadata usage easily exceeded 100GB. I can only account for this by considering ditto blocks. It probably should be said that sync=always was set, which made IOPS measured every second rather consistent and allowed me to see an increase from a reduced metadata miss rate.

The empirical evidence suggests to me that we are double caching ditto blocks in ARC.

**Comment by richardelling** [comment]
I'll take a closer look, but I do not recall the DVA being used as an index in the ARC, which is what you are suggesting.

Also, larger L1 size is quite useful and effective (16KB -> 128KB in your above calculations)

**Comment by ryao** [comment]
@richardelling You are right. ARC is using BP_IDENTITY to cache, so it shouldn't issue unnecessary reads or double cache. However, I am seeing larger cache utilization than my calculations suggest such that I am seeing reads from what I assume are metadata misses. There is no compression or deduplication in use, although the system where the tests are run is using raidz2.

As for 128KB indirect blocks, they don't actually impact my calculations too much because the number of pointers stored in L1 would be the same. Compressed ARC on the other hand would increase the amount we can store in cache and benefit from even better compression ratios on 128KB L1 blocks.

**Comment by ryao** [comment]
@richardelling You are right. ARC is using `BP_IDENTITY` to cache, so it shouldn't issue unnecessary reads or double cache. However, I am seeing larger cache utilization than my calculations suggest such that I am seeing reads from what I assume are metadata misses. There is no compression or deduplication in use, although the system where the tests are run is using raidz2.

It might be that the parity blocks from raidz2 would explain things. The setup that I was given to diagnose at work is suffering from IO amplification due to ashift=12, volblocksize=4K and raidz2 being combined. Every 4KB written to the zvol turns into 12KB on disk. I'll add that to my list of things to investigate.

As for 128KB indirect blocks, they don't actually impact my calculations too much because the number of pointers stored in L1 would be the same. Compressed ARC on the other hand would increase the amount we can store in cache and benefit from even better compression ratios on 128KB L1 blocks.
