### ISSUE TITLE
Zpool history not working.

### ISSUE THREAD

**Issue by nonooo** [openzfs/zfs#6155]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian jessie (XEN dom0) 
Distribution Version    | jessie fully uptodate. 
Linux Kernel                 | #1 SMP Debian 3.16.43-2 (2017-04-30         
Architecture                 | 64 bits
ZFS Version                  | 0.6.5.9-2~bpo8+1         
SPL Version                  | 0.6.5.9-1~bpo8+1  

### Describe the problem you're observing

I can't zpool history.

### Describe how to reproduce the problem
```
root@g8server:/usr/share/grub# zpool  history patapouf
History for 'patapouf':
zpool: libzfs_pool.c :3853 :  l'assertion « nvlist_add_nvlist_array(*nvhisp, ZPOOL_HIST_RECORD, records, numrecords) == 0 » a échoué.
Abandon  
```

please let me know if you need more info.

**Comment by behlendorf** [comment]
Closing as unreproducible.  @nonooo if you're still able to reproduce this let us know and we can reopen this issue.

**Comment by nonooo** [comment]
Well I am still able to reproduce on my "patapouf" pool but I have not yet updated to 0.7 series.. I will update the server this weekend and check if it is still not working.
To be honest this is not a "real" issue for me, everything else is working fine... but if you think this is worth it I will make your test (I can't dd the pool to you because I got photo of my children in it and I don't want them to be "on" the internet)

**Comment by behlendorf** [comment]
@nonooo thanks for offering but no need, this isn't a critical issue.  If you have everything else working as intended I'd suggest leaving your system as is.  The error you posted above is enough for us to better handle this issue.  Reopening.
