### ISSUE TITLE
Processes hang in uninterruptible sleep when trying to read flock'd file.

### ISSUE THREAD

**Issue by tcaputi** [openzfs/zfs#6188]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.04
Linux Kernel                 |  4.4.0-24-generic
Architecture                 |  x86_64
ZFS Version                  |  0.6.5.8
SPL Version                  |  0.6.5.8

### Describe the problem you're observing
The system running zfs was reported to me when it was observed that there were several processes hanging that were all non-responsive and unkillable. After looking around a little bit, it seemed that the system had several processes that were hanging in uninterruptible sleep trying to `cat` a file on the zpool that is managed under an advisory lock. Looking at htop, I noticed that the `txg_quiesce` thread was persistently using about 80% CPU. Other processes were also using a lot of CPU power, but as of now it is unclear if that is related to this bug. When I took a look at the txg history in `/proc`, I noticed that transaction groups were flying by at a rate of tens per second. During all of this, the disks were not under any significant load (almost completely idle).

### Describe how to reproduce the problem
At this time I do not have specific commands to replicate this.

### Include any warning/errors/backtraces from the system logs

I was able to get the kern.log output of `echo t > /proc/sysrq-trigger`, but this is a bit big to paste here and I was unable to find anything particularly interesting there. The system was rebooted before I had the chance to collect more data.

**Comment by dweeezil** [comment]
@tcaputi Taking a bit of a flyer here, but is there any chance the filesystem on which this was observed was approaching a quota limit?  That seems to be a frequent cause of rapid txg syncs.

**Comment by tcaputi** [comment]
@dweeezil Not that I'm aware of. I don't believe we use any quota limits internally in our products. @behlendorf suggested that it the quick txg sync time is probably due to something persistently waiting on the txg, although I'm not sure what
