### ISSUE TITLE
Slow TRIM-performance on ZVOLs

### ISSUE THREAD

**Issue by RubenKelevra** [openzfs/zfs#6307]
Hey Guys,

I know this might be not a major problem, but I just added the trim-capability to my virtual machines.

I use KVM based VMs which are switched from VIRTIO to VIRTIO-SCSI. You can add manually a flag called discard="unmap" which then export the SCSI-command unmap to the underlaying file-system as discard.

Those VMs run on ZVOLs with a volblocksize of 8k and inside the VM a ext4 with some optimizations (usually used for RAIDs) to create writes in larger sizes to enhance the performance on those 8K blocks (different story!).

I started a live-cd and mounted this EXT4 inside it. I did a full trim, while the filesystem has never been trimmed before and is 314 G in size but use only 9 G.

I learned that fstrim is working 10 times faster if sync is disabled (which should be pretty safe when "writing" empty blocks). So the whole operation only took 9 minutes when sync is disabled.

I started with sync=standard, where it just made 100 MB in 4-6 seconds (reduction of usedbydataset) while with sync=disabled it managed to make 1000 MB in 4-6 seconds (reduction of usedbydataset).

So I guess there's a lot of room for improvements. I guess it's somewhat safe to do the discard-command async and just return the request as fast as possible.

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  ArchLinux
Linux Kernel Hypervisor                | 4.9.34-1-lts
Linux Kernel VM (LiveCD)               | 4.11.3-1-ARCH
Architecture                 |  x64
ZFS Version                  | 0.6.5.10
SPL Version                  | 0.6.5.10

**Comment by bunder2015** [comment]
There were some zvol improvements in 0.7.0-rc4 and I believe there are more to come in the future.  Any chance you could give it a try?

**Comment by RubenKelevra** [comment]
Sure, I try it this evening (in around 16 hours in my timezone).

**Comment by mailinglists35** [comment]
> I guess it's somewhat safe to do the discard-command async and just return the request as fast as possible.

I would not expect this to happen as default behaviour

**Comment by jeff-dagenais** [comment]
Is this still a relevant issue with the latest versions?

**Comment by jeff-dagenais** [comment]
I was asking simply because I have a setup under proxmox and was looking for arguments for or against an upgrade. No longer an immediate issue for me, but the ticket should either be closed or updated. I unfortunately don't have time or setup (or strong expertise for that matter) to provide educated information. Cheers!

**Comment by RubenKelevra** [comment]
Well, my setup was unexpectedly blocked by a issue in the last stable of ZFS which seems to be gone in the master. 

If you plan to use ZFS below virtual machines, be warned, zvols might be slower than usual raw files - you should test this. I've run some tests on my notebook lately and the performance numbers are still quite unsatisfactory.

You can improve the overall speed with larger blocks than 8K for the zvol and using tuning parameters (usually refered as stripe and stride size) for ext4 to advice if (inside the VM) to use larger portions of datablocks together whenever possible.

I haven't tested this side by side yet, but use this for years without any issues.

XFS on the other hand is quite slow on ZVOLs compared to ext4. Maybe different patterns or something responding harder to the additionally I/O wait time there.

Overall: raw files are fine. If you're pressured with less disk space, you might want to consider ZVOLs because they don't grow. You also have smaller diffs.

You need to set trim exported as unmap via SCSI to the VM, you can find detailed informations on that here:

https://chrisirwin.ca/posts/discard-with-kvm/

Many of my machines have actually sync=disabled, 'cause I just don't care - and most applications also not, that a sync is actually written. You may loose 10-20 seconds written (and synced!) on a powerloss, but all data is still consistent - just 20 seconds back in time.

In 99.9 of all cases, this is unproblematic. Emails might be an exception. But for such data you might want to create a special ZVOLs where you just enable the sync. :)
