### ISSUE TITLE
OOM panic due to external fragmentation with zfs 0.7

### ISSUE THREAD

**Issue by batchuravi** [openzfs/zfs#6381]
We are seeing panic on oom after running a workload consisting of an av scan and light client 
 workload for a couple of hours. 

We are running with 32G memory. Test creates about 1 millions files spread accross 5 pools. After that test queries file attributes, change attributes, read the file and rewrites the first 4k bytes of the file.

From the stack trace (below) it looks like fork cannot succeed because there is no contiguous 16k free chunk.

```
crash> bt
PID: 12218  TASK: ffff88010571ea40  CPU: 2   COMMAND: "java"
 #0 [ffff8804cce27910] machine_kexec at ffffffff8105d4f0
 #1 [ffff8804cce27980] crash_kexec at ffffffff8110c288
 #2 [ffff8804cce27a50] panic at ffffffff811825d9
 #3 [ffff8804cce27ad0] check_panic_on_oom at ffffffff81187526
 #4 [ffff8804cce27ae0] out_of_memory at ffffffff81187c80
 #5 [ffff8804cce27b80] __alloc_pages_slowpath at ffffffff8118d2e6
 #6 [ffff8804cce27c70] __alloc_pages_nodemask at ffffffff8118d619
 #7 [ffff8804cce27d40] alloc_kmem_pages_node at ffffffff8118e999
 #8 [ffff8804cce27d70] dup_task_struct at ffffffff8107ff8e
 #9 [ffff8804cce27db0] copy_process at ffffffff81081797
#10 [ffff8804cce27e90] _do_fork at ffffffff81082e5e
#11 [ffff8804cce27f40] sys_clone at ffffffff81083069
#12 [ffff8804cce27f50] entry_SYSCALL_64_fastpath at ffffffff816cf76e
    RIP: 00007fc05c0b2a71  RSP: 00007fc05cdb1428  RFLAGS: 00000206
    RAX: ffffffffffffffda  RBX: 00007fc004402700  RCX: 00007fc05c0b2a71
    RDX: 00007fc0044029d0  RSI: 00007fc004401ff0  RDI: 00000000003d0f00
    RBP: 0000000000000000   R8: 00007fc004402700   R9: 00007fc004402700
    R10: 00007fc0044029d0  R11: 0000000000000206  R12: 00007fc05cdb1500
    R13: 00007fc0044029c0  R14: 0000000000000000  R15: 0000000000000003
    ORIG_RAX: 0000000000000038  CS: 0033  SS: 002b
crash> 
```

From vmcore-dmesg.txt there are no higher order free pages although there is a lot of free memory in solitary 4k pages:
```
[    0.453357] Node 0 DMA: 0*4kB 0*8kB 0*16kB 1*32kB (U) 1*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15840kB
[    0.453365] Node 0 DMA32: 6002*4kB (UMEH) 5015*8kB (UMEH) 3620*16kB (UMEH) 284*32kB (UME) 54*64kB (UME) 10*128kB (UME) 9*256kB (ME) 2*512kB (M) 0*1024kB 0*2048kB 0*4096kB = 139200kB
[    0.453373] Node 0 Normal: 527308*4kB (UM) 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2109232kB
[    0.453386] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
```
Note that there as an issue (4953) filed last year but that was with an earlier version of ZFS (0.6.5.x) without ABD. The workload at that time did not have any scans. It was metadata intensive. It is possible though that in both cases there might have been a lot of small memory allocations.

zfs version:        0.7.0-rc3 with (rc3 time frame) trim implementation and some minor changes. 
spl version:        0.7.0-rc3
Linux kernel version: 4.4.14
Architecture:   x86_64
Centos release 6.8

**Comment by batchuravi** [comment]
Want to add that in the issue we saw all files created were of size 4k. Also the tests would not have changed the file sizes.

**Comment by tuxoko** [comment]
Do you have compression on?
Also can you get `/proc/slabinfo`, `/proc/spl/kstat/zfs/arcstats` and `/proc/spl/kstat/zfs/abdstats` just before OOM happens?

One thing we can try is to avoid using slab on 4k abd,
or even remove the size check so don't use slab at all.
```diff
diff --git a/module/zfs/abd.c b/module/zfs/abd.c
index 765ac7f..e562813 100644
--- a/module/zfs/abd.c
+++ b/module/zfs/abd.c
@@ -583,7 +583,7 @@ abd_alloc(size_t size, boolean_t is_metadata)
 {
 	abd_t *abd;
 
-	if (!zfs_abd_scatter_enabled || size <= PAGESIZE)
+	if (!zfs_abd_scatter_enabled || size < PAGESIZE)
 		return (abd_alloc_linear(size, is_metadata));
 
 	VERIFY3U(size, <=, SPA_MAXBLOCKSIZE);
```

**Comment by batchuravi** [comment]
@tuxoko, we did not have compression enabled for data. I believe metadata is compressed.

Just before the OOM we collected /proc/spl/kstat/zfs/arcstats and /proc/spl/kmem/slab. Attached is a file containing that output.
[arc_and_slab_stats.TXT](https://github.com/zfsonlinux/zfs/files/1166575/arc_and_slab_stats.TXT)

**Comment by batchuravi** [comment]
@tuxoko, this morning we discovered that smbd processes running in user space were consuming significantly larger amount of memory than expected. We suspect a leak (in smbd). Those user space allocations could have caused the fragmentation we are seeing by making multiple 4k allocations from the buddy allocator.

**Comment by tuxoko** [comment]
So, do things work fine without using smbd?

**Comment by batchuravi** [comment]
@tuxoko we need to use smbd while using our tests to exercize zfs. We are investigating the smbd leak.

The issue might have been that the scan, in the process of pulling in different inodes, could have allocated and freed slabs sized less than 16k, and, consequently fragmented the free memory. We tried out a linux setting to ensure that all slabs are of size at least 16k and monitored amount of memory fragmentation. The situation was significantly better. After comparable durations of the run we saw considerable number of large order chunks. 

We are planning to run with this setting for multiple days to see whether it will work fine.

**Comment by batchuravi** [comment]
After running for longer durations with 16k slab size we still see memory fragmentation although we did not encounter a panic (of the kind mentioned above). We still see several free chunks in buddy info which are as small as 4k.

**Comment by GregorKopka** [comment]
@batchuravi would you please share what 'linux setting' you did that avoids activation of the OOM killer?
(so should others run into the sane issue could find an easy to apply band-aid here that can be applied till the underlying issue is fixed)

**Comment by gaurkuma** [comment]
@GregorKopka You can pass a kernel command line parameter "slub_min_order=2", that would force kernel to allocate atleast 16K slabs.
