### ISSUE TITLE
0.7.0 Update kABI-tracking kmod Weak Modules

### ISSUE THREAD

**Issue by dcrdev** [openzfs/zfs#6413]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.3
Linux Kernel                 | 3.10.0-514.26.2
Architecture                 | x86_64
ZFS Version                  | zfs-0.7.0-1
SPL Version                  | spl-0.7.0-1

### Describe the problem you're observing
Whilst updating my system - I received several 'Permission Denied' messages whilst the post trans scripts were being run:

```/sbin/weak-modules: line 174: /tmp/weak-modules.CWPkux/old_initramfs/./usr/lib/modules/3.10.0-514.26.2.el7.x86_64/extra/spl/spl/spl.ko: Permission denied
/sbin/weak-modules: line 174: /tmp/weak-modules.CWPkux/old_initramfs/./usr/lib/modules/3.10.0-514.26.2.el7.x86_64/extra/spl/spl/spl.ko: Permission denied
```
This results in an unbootable system - CentOS is on a ZFS root.

### Describe how to reproduce the problem
Start with a CentOS 7.3 install on a ZFS root, running ZoL 0.6.x - upgrade the system and receive the above errors.

**Comment by dcrdev** [comment]
Ok so rebuilding the initramfs before rebooting solves this issue - no idea about the weak modules error, I thought that generally that only affected the dkms packages?

Why does zfs-dracut not trigger something to instruct dracut to rebuild the initramfs?

**Comment by dcrdev** [comment]
Also getting this warning on shutdown now:
"dracut Warning : ZFS Will force-import pools if necessary."

**Comment by dcrdev** [comment]
OK so it appears that passing the kernel parameter zfs_force=1 now shows the above message - it didn't with the 0.6.x series; I'm passing that parameter to ensure the system boots in case the pool doesn't get exported fast enough on shutdown. I guess it's more of an informative statement than a warning.

In any case I think there needs to be something in the zfs-dracut package that rebuilds the initramfs on update, otherwise it's just not a reliable solution. To be clear here I'm not talking kernel upgrades - but ZoL upgrades.

**Comment by behlendorf** [comment]
Our plan for the next major release is to pull the `spl.ko` in to the zfs packages in order to avoid this entire dependency problems when updating ZoL.  That way everything will always be in sync and we'll only do one build.

Along with that I agree we need to investigate why the initramfs wasn't rebuilt when ZFS was upgraded.

**Comment by ssergiienko** [comment]
> Along with that I agree we need to investigate why the initramfs wasn't rebuilt when ZFS was upgraded

Hope this could be useful to mention that the issue is not only about kABI-tracking kmod and DKMS-style is affected too. Upgrading my system ZFS 0.6 -> 0.7 always make it unbootable and executing `dracut -f` after upgrade fixes the problem.
Error during boot (import pool) is:
```
Symbol `spa_feature_table' has different size in shared object, consider re-linking
```
