### ISSUE TITLE
0.7.1 Input/output error from /bin/ls

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#6489]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | SL
Distribution Version    | 7.3
Linux Kernel                 | 3.10.0-514.26.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
/bin/ls generations "Input/output error" while running zfs receive for an incremental snapshot update. This happens significantly more frequently if a background scrub is running.

### Describe how to reproduce the problem
watch -n.1 ls -l /some/ZFS/path
while receiving a ZFS incremental snapshot (discovered using zrep script)

### Include any warning/errors/backtraces from the system logs
None seen

**Comment by stuartthebruce** [comment]
This also happens on SL7.4 running kernel-3.10.0-693.2.2.el7.x86_64, zfs-0.7.2-1.el7_4.x86_64, and spl-0.7.2-1.el7_4.x86_64.

Note, zpool scrub comes up clean, and /bin/ls is reliable when there is not zfs receive running. Has anyone else seen this problem?

**Comment by behlendorf** [comment]
Are you performing an `ls` in the same dataset you're receiving an incremental snapshot in to?

**Comment by loli10K** [comment]
Duplicate of https://github.com/zfsonlinux/zfs/issues/3930

**Comment by kpande** [comment]
@stuartthebruce can you reproduce this one still? and as @behlendorf asked, it is in the same dataset the recv is running on?
