### ISSUE TITLE
PANIC at sa.c:1283:sa_build_index()

### ISSUE THREAD

**Issue by hyegeek** [openzfs/zfs#6500]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | NA (mostly stable and up to date)
Linux Kernel                 | 4.9.41-gentoo
Architecture                 | x86_64
ZFS Version                  | 0.7.0 (started on 0.6.5.9)
SPL Version                  | 0.7.0

### Describe the problem you're observing
Get a kernel panic when I try to unmerge an older kernel version. Probably related to touching a file with issues.
### Describe how to reproduce the problem
emerge -C =sys-kernel/gentoo-sources-4.9.13
### Include any warning/errors/backtraces from the system logs

```
Aug 10 18:39:25 gar kernel: VERIFY(BSWAP_32(sa_hdr_phys->sa_magic) == SA_MAGIC) failed
Aug 10 18:39:25 gar kernel: PANIC at sa.c:1283:sa_build_index()
Aug 10 18:39:25 gar kernel: Showing stack for process 18520
Aug 10 18:39:25 gar kernel: CPU: 0 PID: 18520 Comm: emerge Tainted: P           O    4.9.41-gentoo.zfs #1
Aug 10 18:39:25 gar kernel: Hardware name: ASUS All Series/B85M-E, BIOS 2304 05/25/2015
Aug 10 18:39:25 gar kernel:  ffffc9002617b548 ffffffff81319d3b ffffffffa054c8b9 0000000000000503
Aug 10 18:39:25 gar kernel:  ffffc9002617b558 ffffffffa002618d ffffc9002617b6d8 ffffffffa002623d
Aug 10 18:39:25 gar kernel:  0000000002404200 0000000000000028 ffffc9002617b6e8 ffffc9002617b688
Aug 10 18:39:25 gar kernel: Call Trace:
Aug 10 18:39:25 gar kernel:  [<ffffffff81319d3b>] dump_stack+0x4d/0x72
Aug 10 18:39:25 gar kernel:  [<ffffffffa002618d>] spl_dumpstack+0x3d/0x40 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa002623d>] spl_panic+0xad/0xf0 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa005a146>] ? avl_find+0x56/0xa0 [zavl]
Aug 10 18:39:25 gar kernel:  [<ffffffff8117e980>] ? address_space_init_once+0x30/0x60
Aug 10 18:39:25 gar kernel:  [<ffffffff8117ea24>] ? inode_init_once+0x74/0x90
Aug 10 18:39:25 gar kernel:  [<ffffffffa044d042>] ? sa_cache_init+0x72/0x90 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0022859>] ? spl_kmem_cache_alloc+0xf9/0x860 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0409476>] ? dbuf_rele_and_unlock+0x256/0x500 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa044ef6c>] sa_byteswap+0x23c/0xf90 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0450837>] sa_handle_get_from_db+0x127/0x190 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04aa839>] zfs_znode_hold_compare+0x959/0xf40 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04ab397>] zfs_inode_update+0x187/0x6b0 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0424ac5>] ? dmu_zfetch+0x3b5/0x1230 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0409476>] ? dbuf_rele_and_unlock+0x256/0x500 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffff810b0aab>] ? getrawmonotonic64+0x2b/0xc0
Aug 10 18:39:25 gar kernel:  [<ffffffffa0027a7c>] ? __cv_init+0x3c/0x60 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0424ed1>] ? dmu_zfetch+0x7c1/0x1230 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0409476>] ? dbuf_rele_and_unlock+0x256/0x500 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0027a7c>] ? __cv_init+0x3c/0x60 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04086c9>] ? dbuf_fill_done+0xe9/0xf0 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0022859>] ? spl_kmem_cache_alloc+0xf9/0x860 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffff8114bc49>] ? __kmalloc_node+0x29/0x1a0
Aug 10 18:39:25 gar kernel:  [<ffffffffa0020dfa>] ? spl_kmem_alloc+0xaa/0x180 [spl]
Aug 10 18:39:25 gar kernel:  [<ffffffffa040a3b1>] ? dbuf_read+0x591/0x920 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa0414b94>] ? dmu_object_info_from_dnode+0x64/0x80 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04adf49>] zfs_zget+0x169/0x1f0 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa048a294>] zfs_dirent_lock+0x524/0x610 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa048a3f5>] zfs_dirlook+0x75/0x270 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04a13a4>] zfs_lookup+0x314/0x380 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa04be9ac>] zpl_fallocate_common+0x63c/0x850 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffff811717ae>] ? lookup_fast+0x1be/0x2e0
Aug 10 18:39:25 gar kernel:  [<ffffffff8117d8a1>] ? __d_lookup+0x81/0x140
Aug 10 18:39:25 gar kernel:  [<ffffffff8116ed51>] lookup_slow+0x91/0x140
Aug 10 18:39:25 gar kernel:  [<ffffffff81171d48>] walk_component+0x1b8/0x270
Aug 10 18:39:25 gar kernel:  [<ffffffff81170106>] ? path_init+0x1f6/0x370
Aug 10 18:39:25 gar kernel:  [<ffffffff8118463f>] ? mntput+0x1f/0x30
Aug 10 18:39:25 gar kernel:  [<ffffffff81172418>] path_lookupat+0x58/0x100
Aug 10 18:39:25 gar kernel:  [<ffffffff811742a9>] filename_lookup+0x99/0x150
Aug 10 18:39:25 gar kernel:  [<ffffffffa044cab8>] ? rrw_exit+0x48/0x130 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffffa044cde1>] ? rrm_exit+0x41/0x70 [zfs]
Aug 10 18:39:25 gar kernel:  [<ffffffff81173f2d>] ? getname_flags+0x6d/0x1f0
Aug 10 18:39:25 gar kernel:  [<ffffffff81174401>] user_path_at_empty+0x31/0x40
Aug 10 18:39:25 gar kernel:  [<ffffffff81169b7e>] vfs_fstatat+0x4e/0xa0
Aug 10 18:39:25 gar kernel:  [<ffffffff8116a042>] SyS_newlstat+0x22/0x40
Aug 10 18:39:25 gar kernel:  [<ffffffff8153c2e4>] entry_SYSCALL_64_fastpath+0x17/0x98

```

**Comment by behlendorf** [comment]
This was almost certainly a duplicate of #6414 which was fixed in 0.7.1.  You'll want to update your system as soon as possible.

**Comment by behlendorf** [comment]
@hyegeek good, I've glad you've upgraded.  Unfortunately what you describe is a possible side effect of this nasty bug.  The good news is that it's understood and fixed in the 0.7.1 release and we've added test coverage to ensure it never happens again.

**Comment by hyegeek** [comment]
So what I'm hearing is every one of my zfs systems should be upgraded ASAP.

I will start that process...

**Comment by behlendorf** [comment]
Only systems with `dnodesize != legacy` are vulnerable to this specific issue.  My recommendation is to set `dnodesize=legacy` on any 0.7.0 systems as an immediate workaround, after upgrading them to 0.7.1 you can set `dnodesize=auto` again.

**Comment by hyegeek** [comment]
Now I'm a bit confused. This is starting to sound like the problem started with 0.7.0. This is certainly not the case for me as it hit me in April and I only now had to rebuild because of it.

I'm also having trouble locating the dnodesize setting. It does not appear to be understood by either the zfs set/get or zpool set/get commands. I do have the following on my 0.7.1 pool

```
unsupported@org.zfsonlinux:large_dnode         inactive                                       local
```

What command would I issue to set things to legacy? Does it need to be done for 0.6.x.x?

Thanks.

**Comment by behlendorf** [comment]
If this dates back to 0.6.5.9 then this isn't the issue I suspect it was.  The issues I was referring to was accidentally introduce in 0.7.0-rc5 and quickly resolved in 0.7.1.  Only those releases would have been vulnerable and only if the admin has specifically run `zfs set dnodesize=auto` on the dataset after upgrading the pool to enable the feature.  Your pool clearly has the feature inactive so it must be a different issue.

There were some issues similar to this in older releases but all known issues were resolved by the 0.6.5.5 tag.  Is it possible the pool at some point in time was running a release older than this and the on-disk problems weren't discovered until much latter?

**Comment by hyegeek** [comment]
The issue show up on my machine around a month after I upgraded to sys-fs/zfs-kmod-0.6.5.9. Sounds like it is different. Do you want to have me run commands on the effected filesystem?

On my 0.7.1 machine, I have upgraded the pool, but it does not know anything about dnodesize

```
# zpool upgrade
This system supports ZFS pool feature flags.

All pools are formatted using feature flags.

Every feature flags pool has all supported features enabled.

# zfs set dnodesize=auto gar
cannot set property for 'gar': invalid property 'dnodesize'
```

**Comment by behlendorf** [comment]
@hyegeek sounds like a different issue.  Are you sure you're running matched user space and kernel space packages?  From the 0.7.1 zfs man pages, `man zfs`.

```
     dnodesize=legacy|auto|1k|2k|4k|8k|16k
       Specifies a compatibility mode or literal value for the size of dnodes
       in the file system. The default value is legacy.  Setting this property
       to a value other than legacy requires the large_dnode pool feature to
       be enabled.

       Consider setting dnodesize to auto if the dataset uses the xattr=sa
       property setting and the workload makes heavy use of extended
       attributes. This may be applicable to SELinux-enabled systems, Lustre
       servers, and Samba servers, for example. Literal values are supported
       for cases where the optimal size is known in advance and for perfor‐
       mance testing.

       Leave dnodesize set to legacy if you need to receive a send stream of
       this dataset on a pool that doesn't enable the large_dnode feature, or
       if you need to import this pool on a system that doesn't support the
       large_dnode feature.

       This property can also be referred to by its shortened column name,
       dnsize.
```

**Comment by hyegeek** [comment]
Looks like the kernel I booted off to start my recover is indeed running the older one. Sorry about that. I'm almost finished updated the system (I had to rollback to april!) and I'll reboot with the updated zfs at that point.

Not sure how I got the older kernel/ramdisk (I thought I copied the latest), but at least things are explained. Thanks.

**Comment by behlendorf** [comment]
@hyegeek it sounds like you've gotten to the root of the problem.  Shall we close this out?

**Comment by hyegeek** [comment]
Since this issue showed up first under 0.6.5.9, I'm not sure we really know what happened. The upgrade to 0.7.0 simply made the problem worse are opposed to causing it. If that is consistent with what you believe about the issue, we can close it, otherwise, we should probably try to figure out what happened.

**Comment by behlendorf** [comment]
So we don't know of any issues in 0.6.5.9 which could have caused this.  Is it possible that you might not have been running 0.6.5.9  and were instead using an older release from the initramfs?  The version information would be in the console logs if you still have them.

**Comment by hyegeek** [comment]
That is very unlikely. The only reason things got odd now is I had a mix of rolled back OS and not rolled back /boot.

**Comment by hyegeek** [comment]
Now that my updates are done, I've set the dnodesize to auto.

Just to recap what happened on the version mismatch, I did boot off of the kernel I thought I did with both zfs 0.7.1 modules and tools. It then booted into an old os (rolled back because of the corruption). That's why the mismatch.

The issue reported here did occur under 0.6.5.9. The machine was upgraded from 0.6.5.8 on March 11th and the corruption occurred sometime in April. I would see the panic whenever I tried to unmerge one of my kernel version, but since there was no other issues, I left it for later.

Last Thursday, I upgraded to 0.7.0 to see if that would help, it still paniced when I tried to unmerge the kernel. I then saw that 0.7.1 was available in portage and upgraded to that. At that point, just mounting the root partition caused the panic.

**Comment by ironMann** [comment]
Here's a stack trace of a possibly related issue. This was testing unrelated code, but the stack-trace is suspicious. TL;DR `db->db_blkid` is invalid in `dbuf_read()`

```
[ 2499.657116] VERIFY3(zai.zai_st_max_blk > blkid) failed (3 > 18446744073709551614)
[ 2499.661687] PANIC at dmu_zfetch.c:298:dmu_zfetch()
[ 2499.665365] Showing stack for process 543
[ 2499.668731] CPU: 1 PID: 543 Comm: setfacl Tainted: P           OE   4.11.11-300.fc26.x86_64 #1
[ 2499.674040] Hardware name: Xen HVM domU, BIOS 4.2.amazon 02/16/2017
[ 2499.678651] Call Trace:
[ 2499.681193]  dump_stack+0x63/0x84
[ 2499.684168]  spl_dumpstack+0x42/0x50 [spl]
[ 2499.687544]  spl_panic+0xc8/0x110 [spl]
[ 2499.700229]  dmu_zfetch+0x712/0x800 [zfs]
[ 2499.710063]  dbuf_read+0x885/0x1150 [zfs]
[ 2499.719794]  dmu_spill_hold_by_dnode+0x4c/0x160 [zfs]
[ 2499.723326]  dmu_spill_hold_by_bonus+0x42/0x60 [zfs]
[ 2499.726763]  sa_build_layouts+0x891/0xd00 [zfs]
[ 2499.736215]  sa_modify_attrs+0x37a/0x630 [zfs]
[ 2499.739568]  sa_attr_op+0x123/0x450 [zfs]
[ 2499.742706]  sa_bulk_update_impl+0x8b/0x180 [zfs]
[ 2499.746224]  sa_update+0xa2/0x150 [zfs]
[ 2499.749254]  zfs_sa_set_xattr+0x222/0x280 [zfs]
[ 2499.752636]  zpl_xattr_set_sa.isra.14+0x263/0x290 [zfs]
[ 2499.763286]  zpl_xattr_set+0x31e/0x410 [zfs]
[ 2499.766046]  zpl_set_acl+0x14c/0x210 [zfs]
[ 2499.771800]  zpl_xattr_acl_set_default+0xa2/0x100 [zfs]
[ 2499.777879]  __vfs_setxattr+0x69/0x80
[ 2499.780302]  __vfs_setxattr_noperm+0x72/0x1a0
[ 2499.783024]  vfs_setxattr+0xa7/0xb0
[ 2499.785440]  setxattr+0x114/0x190
[ 2499.805085]  path_setxattr+0xbd/0xd0
[ 2499.807333]  SyS_setxattr+0x14/0x20
[ 2499.809510]  entry_SYSCALL_64_fastpath+0x1a/0xa9
```

Full[ link to the builder](http://build.zfsonlinux.org/builders/Fedora%2026%20x86_64%20%28TEST%29/builds/579/steps/shell_8/logs/console/text)
