### ISSUE TITLE
ARC consuming 38% CPU for no reason

### ISSUE THREAD

**Issue by brendangregg** [openzfs/zfs#6531]
This is a production system that has ZFS installed, but is not using ZFS. No pools, datasets, or ARC buffers.

It has suffered a performance loss as ZFS was consuming 38% CPU system-wide. This is a 4 CPU system. Here is the bottom of a CPU flame graph (open in a new tab to zoom):

![screen shot 2017-08-18 at 3 07 50 pm](https://user-images.githubusercontent.com/1101211/29479462-3b07cc8e-8427-11e7-853b-67a0af07e216.png)

Zooming into the arc_reclaim thread:

![screen shot 2017-08-18 at 3 08 08 pm](https://user-images.githubusercontent.com/1101211/29479491-5d99b1d6-8427-11e7-8901-76b218454f1f.png)

This multilist work is new to me, but... do we really need to be selecting eviction lists using an entropy-based random function? Could this just be round robin?

There's also the shrink_zone CPU consumer on the right, which I'd guess is related to the ARC holding onto locks while in arc_adjust().

This system was almost running at memory capacity (about 99%), so I would think it is frequently entering arc_reclaim() and shrink_zone(). The workaround has been to reduce the Java heap size by a tiny bit.

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | Xenial
Linux Kernel                 | 4.4.0-87-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4

**Comment by scotte** [comment]
Here's what top was showing as we managed to catch one of the systems described above by @brendangregg in this state:

```
KiB Mem : 16431044 total,   215356 free, 15894868 used,   320820 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   190228 avail Mem

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
5014 www-data  20   0 18.837g 0.014t  52596 S 231.9 94.3 308:41.48 java
  51 root      20   0       0      0      0 R 100.0  0.0  42:06.98 kswapd1
 748 root      20   0       0      0      0 R  36.5  0.0  17:29.39 arc_reclaim
1250 root      20   0    9512    124      0 S   8.3  0.0   6:20.67 rngd
```

**Comment by bunder2015** [comment]
Just curious, does this still happen on 0.7.x?

**Comment by gaurkuma** [comment]
I think we should not even call arc_adjust when ARC is less than c_min or when we do not need to shrink back to target size. 

if (arc_size > arc_c_min) && (arc_size > arc_c)
   arc_adjust()

Also, the other thing i do not understand is if we really need to call arc_adjust in the reclaim thread. When kernel is under memory pressure, kswapd will invoke the registered shrinker functions which will call arc_adapt and reduce arc_c. If arc_c goes below arc_size, it will end up calling arc_adjust anyways. Can't we just rely on the kernel triggers (direct or indirect) to know when to shrink.

**Comment by brendangregg** [comment]
@gaurkuma right. At the very least, arc_adjust() should bail early (or not be called) if the arc_size is zero.

**Comment by ironMann** [comment]
`spa_get_random()` switched to using a PRNG in `0.7`. But I agree, the reclaim thread should be parked if there's nothing in the arc.

**Comment by richardelling** [comment]
I believe the test should be if the spa_namespace_avl is empty in the arc_reclaim_thread() loop.

**Comment by loli10K** [comment]
> This is a production system that has ZFS installed, but is not using ZFS. No pools, datasets, or ARC buffers.

@brendangregg is `zed` (ZFS Event Daemon) running on this system? And if it is by any chance running can you still reproduce this issue when you kill/stop it?

**Comment by gaurkuma** [comment]
@richardelling spa_namespace_avl check may not be sufficient because I can have unused pools. For e.g in our use case we create pools upfront on multiple nodes in a cluster and some of them may not even get used for quite some time.
