### ISSUE TITLE
kmod package generation fails

### ISSUE THREAD

**Issue by phreaker0** [openzfs/zfs#6539]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04.3 LTS
Linux Kernel                 | 4.12.0-pf7+
Architecture                 | x86_64
ZFS Version                  | master
SPL Version                  | master

### Describe the problem you're observing

since the native encryption patch (#5769) was merged kmod packages can't be generated any more.

### Describe how to reproduce the problem

$ cd zfs
$ ./configure
$ make pkg-utils pkg-kmod

### Include any warning/errors/backtraces from the system logs

relevant output from the make command:
```
  CCLD     many_fds
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_load_key'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_change_key'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_unload_key'
collect2: error: ld returned 1 exit status
Makefile:622: recipe for target 'many_fds' failed
```

**Comment by cwedgwood** [comment]
@tcaputi i'm also see this:

~~~
Making all in libzfs
make[8]: Entering directory '/tmp/zfs-build-cw-er5o2E5H/BUILD/zfs-0.7.0/tests/zfs-tests/tests/functional/libzfs'
  CC       many_fds.o
  CCLD     many_fds
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_reopen'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_sync'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_receive_with_cmdprops'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_load_key'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_unload_key'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_promote'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_rollback_to'
../../../../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_change_key'
collect2: error: ld returned 1 exit status
~~~

**Comment by tcaputi** [comment]
I ran into this a while back. A while back (not sure about the exact commit) we changed the build process which seems to have changed where binaries are getting stored. This means that it wasn't removing the old libraries and was actually linking against them (even though ldd was swearing that it wasn't). Eventually I found out by removing the binary it claimed to be linking against and running ldd again which revealed the previously installed one.

**Comment by cwedgwood** [comment]
@tcaputi sorry i dragged you into this ... i was being a bit hasty ... but now i've got a work-around and a poor explanation as to why it doesn't affect everyone

basically, it's a quirk with how deb packages are built and it's unreliable if you have previous versions of zfs installed ... the build system will find the older (wrong) libraries and badness ensues

there are some issues that already touch on this, the simplest option is perhaps just to build zfs on a fairly clean system (with at most only one kernel installed because of another quirk related but much older than this)

**Comment by ptx0** [comment]
yep, is an issue here, too.

**Comment by zeigerpuppy** [comment]
after I hit this error, using a chroot environment worked for me to build the zfs debs

**Comment by stewartadam** [comment]
I've been seeing this trying to build 0.8.0-rc1 as well, but it's inconsistent - it appears to fail half the time. @cwedgwood do you remember what you saw when it finding the older/wrong library?

In my case the full path to the libzfs library is given to the linker so it's got the right, recently compiled, .la/.so file for libzfs. Were you seeing `$BUILDROOT/lib/libzfs/.libs/libzfs.so.2.0.0` linking with the installed version of `libzfs_core.so.1`?

**Comment by iamGavinJ** [comment]
I've just hit this problem trying to build 0.8.1 on a "dirty" ubuntu server which has previously had `zfsutils-linux` for Bionic installed.

@stewartadam not sure if this `ldd` output is relevant, since I can't be sure if the library path is being specified explicitly somewhere in the makefile, but it shows the correct version of `libzfs_core.so.1`

```
root@a:/usr/src/zfs-0.8.1/lib/libzfs/.libs# ldd libzfs.so
	linux-vdso.so.1 (0x00007ffcb31c2000)
	libnvpair.so.1 => /usr/src/zfs-0.8.1/lib/libnvpair/.libs/libnvpair.so.1 (0x00007f0559f8f000)
	libuutil.so.1 => /usr/src/zfs-0.8.1/lib/libuutil/.libs/libuutil.so.1 (0x00007f0559d80000)
	libzfs_core.so.1 => /usr/src/zfs-0.8.1/lib/libzfs_core/.libs/libzfs_core.so.1 (0x00007f0559b7a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0559972000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f0559725000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0559387000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f0558f0f000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f0558d08000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0558aeb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f05588cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f05584db000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f055a41c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f05582d7000)
```

**Comment by meilihao** [comment]
I have the same error with cwedgwood. I found old zfs-0.7.7 (built by myself) in my system, build zfs-0.8.6 is ok after clean it.
