### ISSUE TITLE
Random Write amplification 2~3x？

### ISSUE THREAD

**Issue by woquflux** [openzfs/zfs#6555]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Redhat
Distribution Version    | 7.2
Linux Kernel                 | 3.10.0-327.el7.x86_64
Architecture                 | 
ZFS Version                  | 0.6.4.2
SPL Version                  | 0.6.4.2

### Describe the problem you're observing

Write amplification 2~3x when fio test

These screenshots show details:

![qq20170824-160731](https://user-images.githubusercontent.com/30719174/29656643-9bff15c8-88e7-11e7-9eba-8134f73be7f1.png)
![addb81a0-d7db-45b0-937f-e156bfd6cf2b](https://user-images.githubusercontent.com/30719174/29656653-a4c967e4-88e7-11e7-960f-7b84ed359c70.png)

```
$zfs get copies qbackup
NAME     PROPERTY  VALUE   SOURCE
qbackup  copies    1       default
```

### Describe how to reproduce the problem
Zfs config
```
$cat /sys/module/zfs/parameters/zfs_vdev_aggregation_limit
8192
$cat /sys/module/zfs/parameters/zfs_dirty_data_max
214748364

zpool create test sdd  # 60G Intel ssd
zfs create -V 10G test/test1
OR
zpool create qbackup sfd0 # 3.2TB Flashcard
zfs create -V 100G qbackup/test1
```

Fio config
```
[global]
numjobs=1
rw=randwrite
bs=8k
runtime=60
ioengine=libaio
direct=1
iodepth=1
name=jicki
group_reporting
[file1]
filename=/dev/qbackup/test1
```

**Comment by richardelling** [comment]
I believe this is working as designed. For a brand new dataset, there is no pre-existing metadata. By default, there will be 2 copies of metadata and 1 copy of the data. So this benchmark is creating and writing new metadata (2x) + 1 data for every random block written. 

Over time, the metadata will catch up and data that shares metadata blocks should result in fewer overall writes.

**Comment by woquflux** [comment]
Thanks for your reply~

So this phenomenon should be disappeared If I did precondition like dd the entire disk?

**Comment by behlendorf** [comment]
I believe @richardelling is correct.  It's important thing to keep in mind that you _should not_ expect a 1-to-1 relationship between `write(2)` system calls and I/Os to the pool.  There are a variety of factors which can can result in an inflation of IOs (multiple copies of meta data, spill blocks, etc) and others which will reduce the number of IOs (aggregation of writes by the ARC or vdev disk layer, compression, deduplication, nop-wriites, etc).  Preconditioning your device with `dd` won't have any impact on what ZFS needs to write or how it writes it.

**Comment by woquflux** [comment]
Thanks,I will try again~

**Comment by woquflux** [comment]
I understand that numbers of IO increase. But I found another thing strange.

![37348239](https://user-images.githubusercontent.com/30719174/30947246-296bbe3e-a43b-11e7-9a78-6a81a5a8adfb.png)

Throughput amplification 2~3x too ...

My fio config:
```
[global]
bs=8k
ioengine=libaio
#rw=randread
rw=randwrite
time_based
runtime=3600
direct=1
group_reporting
iodepth=1
[job1]
size=200G
filename=/dev/test/test1
```
My zfs config:
```
zpool create test   /dev/sdg -f  # Intel 3500 SSD 240G
zfs create -V 200G test/test1 -o volblocksize=4k
```

I tried to change bs to 128k of fio , the problem gone.

**Comment by behlendorf** [comment]
@woquflux thanks for the clear reproducer.  That does seem odd, I'll do some investigating.

**Comment by woquflux** [comment]
Maybe smaller blocks need more metadata to flush?

**Comment by woquflux** [comment]
@behlendorf What is the new progress，please?

**Comment by behlendorf** [comment]
@woquflux nothing new to report.  I haven't been able to investigate yet.

**Comment by woquflux** [comment]
@behlendorf 
I found the performance is the best when set the bs size same as physical_block_size(/sys/block/zd64/queue)

Could I change this value to 8K (default is 32K)?
