### ISSUE TITLE
Native encryption - Odd behavior for copies=3: inherited and at dataset creation

### ISSUE THREAD

**Issue by Lady-Galadriel** [openzfs/zfs#6557]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | Rolling
Linux Kernel                 | 4.9.34
Architecture                 | AMD64
ZFS Version                  | 0.7.0-33_g08de8c16
SPL Version                  | 0.7.0-12_g9df9692

### Describe the problem you're observing
This is for ZFS native encrypted datasets only. You can inherit `copies=3` or create a dataset with `copies=3` without warning or error. It still only makes 2 copies, since 3 copies is not allowed for native ZFS encryption.

Please consider disallowing `-o copies=3` during encrypted dataset creation. And perhaps a warning on inheriting `copies=3`, that it will be turned into `copies=2` on the encrypted dataset.

Note that changing `copies=3` after ZFS encrypted dataset creation does give a useful error message;
`cannot set property for 'crpytpool/test': encrypted datasets cannot have 3 copies`

### Describe how to reproduce the problem
`zfs set copies=3 POOL`
`zfs create -o encryption=on ... POOL/DATASET`
`zfs get copies POOL POOL/DATASET`
`NAME      PROPERTY  VALUE   SOURCE`
`POOL      copies    3       local`
`POOL/DATASET  copies    3       local`

`zfs create -o copies=3 -o encryption=on ... POOL/DATASET`

### Include any warning/errors/backtraces from the system logs

There aren't any errors per say, just odd behaviour.

**Comment by loli10K** [comment]
May be related to https://github.com/zfsonlinux/zfs/issues/5229

**Comment by Lady-Galadriel** [comment]
@loli10K, Yes, I agree it's related. Basically we keep this simply as a tracker whence the parent issue #5229 is resolved. Then simply re-test this specific case.

**Comment by cwedgwood** [comment]
See https://github.com/zfsonlinux/zfs/blob/master/include/sys/spa.h#L296 as to why.

**Comment by tcaputi** [comment]
Yeah, this is the same issue as #5229. The good news is that the encryption patch is coded to be resistant to this problem. It will only use the maximum 2 copies

**Comment by Lady-Galadriel** [comment]
@cwedgwood, Yes, I know `copies=3` is not supported for ZFS native encrypted datasets. It's as @loli10K says, just a different code path that allows odd behaviour.

**Comment by Lady-Galadriel** [comment]
Thinking about it a bit more, I would think that both of these should give fatal errors;

`zfs create -o copies=3 -o encryption=on ... POOL/DATASET`

`zfs set copies=3 POOL`
`zfs create -o encryption=on ... POOL/DATASET`

For the inherited case, you can work around the issue by forcing only 2 copies ala;

`zfs set copies=3 POOL`
`zfs create -o copies=2 -o encryption=on ... POOL/DATASET`
