### ISSUE TITLE
Receiving stream with bad parameters results in misleading error "kernel modules must be upgraded"

### ISSUE THREAD

**Issue by stewartadam** [openzfs/zfs#6574]
Creating separate issue from 'Scenario 4' described in #6547 per request.

### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    | 25
Linux Kernel                 | 4.12.8-200.fc25
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1 (with encryption patches)
SPL Version                  | 0.7.1-1

I've installed SPL from the upstream f25 repo and compiled 0.7.1 from source, patching in:
* Add libtpool (thread pools) (46364cb2f35545a7fc915df9593b719a94c43a83)
* Send / Recv Fixes following b52563 (9b8407638da71ea9f4afb21375f991869f19811f)
* Native Encryption for ZFS on Linux (b52563034230b35f0562b6f40ad1a00f02bd9a05)

### Describe the problem you're observing
When resuming a `zfs send` transfer but specifying an incorrect destination, ZFS produces an incorrect error message `cannot receive incremental stream: kernel modules must be upgraded to receive this stream.`.

The problem is unrelated entirely to kernel modules and rather that the wrong dataset has been specified for the `zfs recv` operation.

### Describe how to reproduce the problem
```
truncate -s 100M /root/src.img
truncate -s 100M /root/replica.img
zpool create src /root/src.img
zpool create replica /root/replica.img
zfs create -o encryption=on -o keyformat=passphrase -o keylocation=prompt replica/encrypted
zfs create src/myfiles
dd if=/dev/urandom of=/src/myfiles/random.bin bs=1M count=30
zfs snapshot src/myfiles@migration
zfs create src/myfiles/child
dd if=/dev/urandom of=/src/myfiles/child/random.bin bs=1M count=3
zfs snapshot src/myfiles/child@migration
zfs send src/myfiles@migration | zfs recv -s replica/encrypted/myfiles
zfs send src/myfiles/child@migration | pv -L 500K | zfs recv -s replica/encrypted/myfiles/child
# press ^c after a second or two of transfer starting

TOKEN=$(zfs get -H receive_resume_token "replica/encrypted/myfiles/child" | cut -f3 | grep -ve '^-$')

zfs send -t "$TOKEN" | zfs recv -s replica/encrypted/myfiles
# cannot receive incremental stream: kernel modules must be upgraded to receive this stream.

zfs send -t "$TOKEN" | zfs recv -s replica/encrypted/myfiles@migration
# cannot receive incremental stream: kernel modules must be upgraded to receive this stream.

zfs send -t "$TOKEN" | zfs recv -s replica/encrypted/myfiles/child@migration
# works
```

**Comment by stewartadam** [comment]
See also https://github.com/zfsonlinux/zfs/issues/6547#issuecomment-325382438.

**Comment by jgottula** [comment]
See also https://github.com/zfsonlinux/zfs/issues/6366#issuecomment-330737890 [specifically section 2 of that comment], where I ~~talk~~ complain about essentially the exact same situation.

> In the course of doing something like receiving a snapshot, there's a decent number of reasons why the ioctl might result in an errno like EEXIST or EINVAL due to various different problems in the kernel module. But libzfs, at least in zfs_receive_one and probably elsewhere, takes a fairly dumb approach and mostly just uses the errno itself and maybe some other limited hints to infer what went wrong, and can very easily jump to the wrong conclusion as a result.

**Comment by LnxGnome** [comment]
+1 "cannot receive incremental stream: kernel modules must be upgraded to receive this stream" error with CentOS 7.8.2003 (Kernel 3.10.0-1127.8.2.el7.x86_64) & zfs-**0.7.13**-1.el7_6.x86_64 (OS updated > 7.6, zfs held back), no patches, no encryption.

```
zfs send -t "$TOKEN" | mbuffer -O ip:port   
-/\/-  
mbuffer -I port | zfs recv -uvsF replica
# fails

zfs send -t "$TOKEN" | mbuffer -O ip:port   
-/\/-  
mbuffer -I port | zfs recv -uvsF replica/myfiles/child
# works
```

Using different hosts with "`-/\/-`" being an IPoIB network
