### ISSUE TITLE
arcstat.py cache hit and miss reversed

### ISSUE THREAD

**Issue by dd1dd1** [openzfs/zfs#6589]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.3
Linux Kernel                 |  3.10.0-514.26.2.el7.x86_64
Architecture                 | 
ZFS Version                  |  0.7.0-1
SPL Version                  |  0.7.0-1

### Describe the problem you're observing

arcstat.py reports 100% cache miss instead of 0% cache miss when running from cached data. "hits" and "misses" counters in /proc/spl/kstat/zfs/arcstats appear to be swapped ("misses" counts cache hits, "hits" counts cache misses).

### Describe how to reproduce the problem

go to a zfs pool and run "du -ks *" 10 times. Before this, ensure there is nobody else is using the pool (no scrub running, etc, simplest is to see if "iostat -x 1" reports all disks idle). run "iostat -x 1" and "vmstat 1" while doing this to observe presence of disk i/o. run "arcstat.py 1" 

The first time the cache is warmed, you should see some disk i/o, on subsequent runs, the cache is warm and you will see no disk i/o (or very little disk i/o). (I presume your test machine is not a raspberry pi with 0.5GB RAM and you have not otherwise reduced the size of the arc cache to 1 byte or less).

So on these subsequent runs of "du" you should see no disk i/o and "arcstat.py" should report 0% cache misses (all read requests come from cache, there is no disk i/o, yes?).

But instead, arcstat.py reports "100" for cache misses in miss%, dm%, mm%.

This is confirmed by looking at "hits" and "misses" in /proc/spl/kstat/zfs/arcstats, on can easily see
that "hits" is rarely incremented while "misses" is incremented all the time.

K.O.

**Comment by zviratko** [comment]
I/O might not hit the disks even with cache miss - it might be served from Linux cache... (I see tens of thousands of metadata misses on my systems without the IO hitting drives)
