### ISSUE TITLE
undefined reference to `SHA256TransformBlocks'

### ISSUE THREAD

**Issue by nunompad** [openzfs/zfs#6600]
Type                                | zfs-0.7.0 and zfs-0.7.1
  ---                                  |     --- 
Distribution Name       |  debian
Distribution Version    | 8.9
Linux Kernel                 | Linux 3.10.107
Architecture                 |  arm
ZFS Version                  |  0.7 and 0.7.1
SPL Version                  |  0.7 and 0.7.1

The version 0.6.5.11 compiles without error.

The classes SHA256 and SHA512 are only declared in x86.

Compile error:
```
  CCLD     sha2_test
../../../../../lib/libicp/.libs/libicp.a(sha2.o): In function `SHA2Update':
/home/nmesqui/git/BPI-M2U-bsp/zfs/lib/libicp/../../module/icp/algs/sha2/sha2.c:864: undefined reference to `SHA512TransformBlocks'
/home/nmesqui/git/BPI-M2U-bsp/zfs/lib/libicp/../../module/icp/algs/sha2/sha2.c:834: undefined reference to `SHA256TransformBlocks'
/home/nmesqui/git/BPI-M2U-bsp/zfs/lib/libicp/../../module/icp/algs/sha2/sha2.c:857: undefined reference to `SHA256TransformBlocks'
/home/nmesqui/git/BPI-M2U-bsp/zfs/lib/libicp/../../module/icp/algs/sha2/sha2.c:836: undefined reference to `SHA512TransformBlocks'
collect2: error: ld returned 1 exit status
Makefile:643: recipe for target 'sha2_test' failed
make[6]: *** [sha2_test] Error 1
```

**Comment by behlendorf** [comment]
@nunompad I'm trying to understand how this happened, could you explain how you were compiling ZFS? Were you perhaps cross-compiling (which should work)?  We do [regularly test](http://build.zfsonlinux.org/builders/Debian%208%20arm%20%28BUILD%29) on arm and haven't observed this.

The  `SHA512TransformBlocks` function is the optimized x86_64 version which should only be defined when ` __amd64` is defined at compile time.  Otherwise, you'll get the generic non-arch specific `SHA256Transform`.

**Comment by nunompad** [comment]
This are my  envirument variables:

export ARCH=arm
export BOARD=--prefix=/usr
export SOC=r40
export MACH=sun8iw11p1
export CROSS_COMPILE=arm-linux-gnueabihf-
export UBOOT_CONFIG=sun8iw11p1_config
export KERNEL_CONFIG=sun8iw11p1smp_bpi_defconfig
export LICHEE_PLATFORM="linux"
export GPU_TYPE="mali400"
export TOPDIR=/home/nmesqui/git/BPI-M2U-bsp
export TARGET_PLATFORM=azalea
export TARGET_PRODUCT=azalea-m2ultra

**Comment by nunompad** [comment]
if the lines in zfs/module/icp/Makefile it compile without errors.

#ifeq ($(TARGET_ASM_DIR), asm-x86_64)
#ASM_SOURCES := asm-x86_64/aes/aeskey.o
#ASM_SOURCES += asm-x86_64/aes/aes_amd64.o
#ASM_SOURCES += asm-x86_64/aes/aes_intel.o
#ASM_SOURCES += asm-x86_64/modes/gcm_intel.o
#ASM_SOURCES += asm-x86_64/sha1/sha1-x86_64.o
#ASM_SOURCES += asm-x86_64/sha2/sha256_impl.o
#ASM_SOURCES += asm-x86_64/sha2/sha512_impl.o
#endif
