### ISSUE TITLE
Symlink permission issue

### ISSUE THREAD

**Issue by tobia** [openzfs/zfs#6687]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 8.9
Linux Kernel                 | 4.4.76-93 packaged by Proxmox PVE
Architecture                 | x86_64
ZFS Version                  | v0.6.5.9-1
SPL Version                  | v0.6.5.9-1

### Describe the problem you're observing

I have two symlinks to the same target. The target is readable by anybody. One of the symlinks ("bad") is owned by 1001 and only works for user 1001. *Not ever root can use it, it results in Permission denied.* The other symlink ("good") can be used by anybody. 

    # ls -lni
    10609277 lrwxrwxrwx 1 1001 100 12 Nov  7  2016 bad -> dir
    10609301 drwxrwxr-x 9 1001 100 11 Jun  3  2016 dir
    17429605 lrwxrwxrwx 1    0   0 12 Sep 27 12:54 good -> dir
    # cmp <(readlink good) <(readlink bad)

    # id
    uid=0(root) gid=0(root) groups=0(root)
    # ls good
    (directory entries...)
    # ls bad
    ls: cannot access bad: Permission denied

    $ id
    uid=1001(tobia) ...
    $ ls good
    (directory entries...)
    $ ls bad
    (directory entries...)

### Describe how to reproduce the problem

I don't know. I ran a few `chown -R`, `chmod -R`, and `setfacl -R` on that directory in the past few days, and I ended up with this weird link. I have not yet rebooted.

### Include any warning/errors/backtraces from the system logs

Every time I try to access the bad link, I get the following line in the system log:

`Sep 27 13:31:39 krishna kernel: [1222740.665800] audit: type=1302 audit(1506511899.188:5701): item=0 name="/rpool/data/subvol-106-disk-1/opt/bad" inode=10609277 dev=00:be mode=0120777 ouid=1001 ogid=100 rdev=00:00 nametype=NORMAL`

Here is the `zdb -dddd` output for the two links:

```
# zdb -dddd rpool/data/subvol-106-disk-1 10609277
Dataset rpool/data/subvol-106-disk-1 [ZPL], ID 394, cr_txg 2471211, 75.3G, 5029913 objects, rootbp DVA[0]=<0:81dd947000:1000> DVA[1]=<0:1ec7d92000:1000> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=5895167L/5895167P fill=5029913 cksum=1344f425d5:64bf7d6ee0d:121e33346391e:255a7cfe497934

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
  10609277    1    16K    512      0    512    0.00  ZFS plain file
                                        188   bonus  System attributes
	dnode flags: USERUSED_ACCOUNTED 
	dnode maxblkid: 0
	path	/opt/bad
	uid     1001
	gid     100
	atime	Fri Jun 30 18:33:43 2017
	mtime	Mon Nov  7 13:06:32 2016
	ctime	Wed Sep 27 12:54:22 2017
	crtime	Fri Jun 30 18:33:43 2017
	gen	2472900
	mode	120777
	size	12
	parent	19383
	links	1
	pflags	40800000104

# zdb -dddd rpool/data/subvol-106-disk-1 17429605
Dataset rpool/data/subvol-106-disk-1 [ZPL], ID 394, cr_txg 2471211, 75.3G, 5029913 objects, rootbp DVA[0]=<0:81d3ed5000:1000> DVA[1]=<0:1ec80a8000:1000> [L0 DMU objset] fletcher4 lz4 LE contiguous unique double size=800L/200P birth=5895170L/5895170P fill=5029913 cksum=150faf3a2b:6b85e4e7a73:12e1a4166a94f:2612f2363b6b5b

    Object  lvl   iblk   dblk  dsize  lsize   %full  type
  17429605    1    16K    512      0    512    0.00  ZFS plain file
                                        188   bonus  System attributes
	dnode flags: USERUSED_ACCOUNTED 
	dnode maxblkid: 0
	path	/opt/good
	uid     0
	gid     0
	atime	Wed Sep 27 12:54:30 2017
	mtime	Wed Sep 27 12:54:30 2017
	ctime	Wed Sep 27 12:54:30 2017
	crtime	Wed Sep 27 12:54:30 2017
	gen	5894890
	mode	120777
	size	12
	parent	19383
	links	1
	pflags	40800000104
```

*Wild guess:* could there be some orphan code from Solaris that still reads and writes a symlink's own permissions?

**Comment by behlendorf** [comment]
@tobia I don't see anything strange in the `zdb` output, they both look like valid links.  Is it possible you've set an acl on the bad link which is denying permission?  Or perhaps this due to selinux?
