### ISSUE TITLE
System crash/freeze

### ISSUE THREAD

**Issue by gilcn** [openzfs/zfs#6697]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.4.1708
Linux Kernel                 | 3.10.0-693.2.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1 / 0.7.2
SPL Version                  | 0.7.1 / 0.7.2

### Describe the problem you're observing
Last sunday, I found a host (a mailstore hosting 49k mailboxes) completely frozen for no particular reason. The system, which was working perfectly before, was upgraded from 0.6.5.11 to 0.7.1 a couple of days before the crash.

The freeze happened during the execution of a pretty IO intensive script which runs every sunday. The server screen was black, system was unresponsive and, after rebooting, I didn't find any relevant infos in the system logs. ☹️

Yesterday, while experimenting with zfs send/receive on two test servers (different hardware, same OS & ZFS/SPL versions), I managed to freeze the receiving host in a reproducible manner. This freeze is happening with both 0.7.1 & 0.7.2 versions (kmod packages).

I don't know if this is the same bug in both cases but the result is the same : complete freeze, no message whether on the screen or in the logs!

### Describe how to reproduce the problem
receiverhost# nc -l -p 12345 | zfs receive -v tank/dataset
senderhost# zfs send -D -L -c -v tank/dataset@snap01 | nc receiverhost 12345

After a few seconds, the receiving host freezes. Omitting the -D flag doesn't trigger this freeze.

**Comment by bunder2015** [comment]
Just throwing it out there, does CentOS enable magic sysrq?  You might be able to generate a stack trace with it if they do.

**Comment by gilcn** [comment]
@bunder2015 : That is not enabled by default but I can enable it on my test system. What's the key sequence to enter to generate the stack trace?

**Comment by bunder2015** [comment]
Should be alt+sysrq+L

**Comment by gilcn** [comment]
Well... The system doesn't react to magic sysrq :-\.

**Comment by intentions** [comment]
I've seen this problem a few times with some of my servers, if you have IPMI tools installed then you can check the log to see if a CATERR has been asserted.

command line:
> sudo ipmitool sel list

or in the BMC gui, if your system has one.
