### ISSUE TITLE
zdb -S tank leads to system crash

### ISSUE THREAD

**Issue by Harvie** [openzfs/zfs#6739]
eI've run **zdb -S tank** but then i changed my mind and stoped it using "ctrl+c". During next hours something managed to eat almost 30GB of RAM cache and resulted in complete system crash due to insufficient ram and i have strong suspicion that it was caused by me executing this command. (L1ARC was limited to 20GB max). Pool Usage 48.86% (877.46 GiB of 1.75 TiB).

1.) I guess this is a bug
2.) Is there way to stop the deduplication simulation without crash? (dedup is set to off)
3.) If this is something i should expect, it should probably be mentioned in **man zdb**
4.) Moved to #6740

![image](https://user-images.githubusercontent.com/276504/31322664-67cd2960-ac9c-11e7-83fd-c857f373fcbb.png)

That middle bar in graph with cache jumping up and down is probably somehow related to ZFS. It was OK after reboot.

**Comment by kernelOfTruth** [comment]
like @MyPod pointed out:

@Harvie please hardware, software, system, etc. details

**Comment by Harvie** [comment]
Proxmox VE 5.0 (Debian 9 - Stretch), HP ProLiant DL160 g7

```
filename:       /lib/modules/4.10.17-3-pve/zfs/zfs.ko
version:        0.6.5.11-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     B9DC860740C2225772C1B4F
```
```
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 12h14m with 0 errors on Sun Oct  8 12:38:35 2017
config:

	NAME                            STATE     READ WRITE CKSUM
	tank                            ONLINE       0     0     0
	  mirror-0                      ONLINE       0     0     0
	    sda                         ONLINE       0     0     0
	    sdb                         ONLINE       0     0     0
	logs
	  wwn-0x50026b723a0354f8-part5  ONLINE       0     0     0
	cache
	  wwn-0x50026b723a0354f8-part6  ONLINE       0     0     0

errors: No known data errors
```
log+cache = SSD

**Comment by Harvie** [comment]
@richardelling so what do you think might have caused the issue?

**Comment by richardelling** [comment]
I have no idea, but it isn't due to zdb.
