### ISSUE TITLE
Encrypted ZFS restore Problem

### ISSUE THREAD

**Issue by dotmanila** [openzfs/zfs#6806]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu 16.04
Distribution Version    | AWS r4.xlarge instance with 2 EBS volumes 20GB each
Linux Kernel                 | Linux ip-10-1-2-117 4.4.0-1039-aws 
Architecture                 | x86_64
ZFS Version                  | v0.7.0-157_gc9427c4, ZFS pool version 5000, ZFS filesystem version 5
SPL Version                  | version:        0.7.0-20_g35a44fc

### Describe the problem you're observing
When restoring an encrypted volume/pool I can either get a crash (AWS instance crashes and restarts) 

```
Nov  1 16:27:14 ip-10-1-2-117 kernel: [ 9752.942899]  xvdb: xvdb1 xvdb9
Nov  1 16:27:14 ip-10-1-2-117 kernel: [ 9752.948188]  xvdb: xvdb1 xvdb9
Nov  1 16:32:39 ip-10-1-2-117 kernel: [    0.000000] Initializing cgroup subsys cpuset```

Or an error about key echange:

```
ubuntu@ip-10-1-2-87:/backups$ sudo cp zfskey /dev/shm/
ubuntu@ip-10-1-2-87:/backups$ sudo zfs load-key mysql-data
cannot open 'mysql-data': dataset does not exist
ubuntu@ip-10-1-2-87:/backups$ sudo zfs load-key mysql/data
ubuntu@ip-10-1-2-87:/backups$ sudo zfs load-key mysql/logs
ubuntu@ip-10-1-2-87:/backups$ sudo zfs mount -a
filesystem 'mysql/data' can not be mounted: Invalid exchange
cannot mount 'mysql/data': Invalid argument
ubuntu@ip-10-1-2-87:/backups$```

### Describe how to reproduce the problem
This gist will walk through bootstrapping an instance, building ZFS running the tests up to the problem:

https://gist.github.com/dotmanila/82c1dc620149827fc81fafe6af30130d

**Comment by tcaputi** [comment]
This problem is being caused by a problem with the raw send file format. This shouldn't be hard to fix, but it will require upgrading ZFS on both the source and the target machines (once I have a patch) to fix it.
