### ISSUE TITLE
stats needs to be documented

### ISSUE THREAD

**Issue by colttt** [openzfs/zfs#6871]
Hello,

zfs/ZoL ahs a lot of stats (mostly in /proc/spl/kstat/zfs/), but the meaning of this or what are good/bad values are completely missing. It would be nice if you add this in the documentation. Thats also be needed if you want to monitor you zfs

**Comment by scotws** [comment]
I've run into this problem with my rewrites of arc_summary.py -- there is lots more that kstats produces than what is currently print out, but there doesn't seem to be a comprehensive document that explains what is important and what is not. Unless we are missing something, what you can find is bits and pieces, like you don't want too much of the ghosted stuff being accessed.

**Comment by behlendorf** [comment]
I'd welcome additional documentation of the kstats.  They were primarily introduced for developers to provide better visibility in to the internals but some of them certainly could be useful for monitoring.

**Comment by pashford** [comment]
I started working on the *arcstats.5* page as a background task.  I assume that we should eventually document the entire */proc/spl* tree.

This will be a time consuming process, as most of these values are only documented in the code, with *module/zfs/arc.c* as a starting point.

Most of these values don't have a specific good/bad point; that would often depend on the system and workload,  Specifically, values that would be good on one system/workload might be bad on another.  Where it's clear that certain values/ranges/ratios will be good/bad, that could be put into the documentation, but I believe this would be better as the start for a new ZFS Tuning guide in the WIKI.  Comments?

**Comment by richardelling** [comment]
I've started some documentation of tunables and am planning to tackle stats next.

The stats plan is to approach it from the perspective of how to use the stats to answer questions and make decisions, rather than detail each stat. The reason is that many stats are not useful by themselves, but are useful in relation to another stat. For example, ARC hits by itself is useless, but the ARC hit ratio is very useful.

**Comment by pashford** [comment]
@richardelling,

> The stats plan is to approach it from the perspective of how to use the stats to answer questions and make decisions, rather than detail each stat.

I might be in error, but I believe that would effectively make the *arcstats.5* man page into a mini tuning guide.  That's a **lot** of information to put into a man page.  Just getting the descriptions of the stats into the man page will result in a rather large man page (about 5-6 pages).  I believe that adding tuning information/suggestions would make the man page way too large to be effectively used, yet still too small to provide all the information needed to make good tuning decisions.  Of course, it's also possible that I'm not understanding what you really mean here.

At this time, I'm about 1/4 done with initial descriptions of the various stats.  These will need to be converted from programmer-speak to something vaguely resembling English.

**Comment by richardelling** [comment]
To be clear, I'm not proposing tuning wisdom in a man page. Man pages are a poor delivery vehicle for such information.

**Comment by pashford** [comment]
@richardelling,

Agreed.

Would you like me to continue putting the initial page together?  After I get the basic information in it, you could do the fine-tuning.

**Comment by richardelling** [comment]
let's work together, I don't have a good email for you, but I'm Richard.Elling@RichardElling.com

**Comment by colttt** [comment]
hello,

any news on this?

**Comment by tapaswenipathak** [comment]
Hi @pashford, are you still working on this ticket?
