### ISSUE TITLE
zfs diff sometimes very slow

### ISSUE THREAD

**Issue by woffs** [openzfs/zfs#6920]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9 (Stretch)
Linux Kernel                 | 4.9.51
Architecture                 | x86_64
ZFS Version                  | 0.7.3
SPL Version                  | 0.7.3

### Describe the problem you're observing

`zfs diff -HF pool/snap1 pool/snap2` normally is moderate fast (some minutes), but sometimes takes very long (several days) while producing very little but constant disk I/O and hogging just 1 CPU. It takes place on datasets with many files, but only sometimes and unpredictable.

### Describe how to reproduce the problem

The datasets hold backups and get filled via rsync daily and are snapshotted daily. Then `zfs diff` is run between the snapshots to get file lists of changed files.

### Include any warning/errors/backtraces from the system logs

perf top -U
```
Samples: 18K of event 'cycles', Event count (approx.): 8972483612
Overhead  Shared O  Symbol
  20.73%  [kernel]  [k] zap_leaf_lookup_closest
  10.26%  [kernel]  [k] memmove
   9.72%  [kernel]  [k] zap_leaf_array_read
   7.43%  [kernel]  [k] up_read
   7.43%  [kernel]  [k] down_read
   5.91%  [kernel]  [k] fzap_cursor_retrieve
   3.22%  [kernel]  [k] zap_entry_read
```

$ egrep ^(ar)?c|^size|^p\> /proc/spl/kstat/zfs/arcstats
```
p                               4    25342114344
c                               4    50688182272
c_min                           4    6442450944
c_max                           4    50688182272
size                            4    50506368440
compressed_size                 4    30213347328
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    376973175
arc_meta_used                   4    23148165448
arc_meta_limit                  4    38016136704
arc_dnode_limit                 4    6442450944
arc_meta_max                    4    28417261944
arc_meta_min                    4    6442450944
arc_need_free                   4    0
arc_sys_free                    4    1584005696
```

**Comment by woffs** [comment]
$ zpool iostat -v torx 10 2
```
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
torx        13.9T  4.22T    833    101  12.3M  1.70M
  raidz2    13.9T  4.22T    833    101  12.3M  1.70M
    E0          -      -     93      9  1.36M   136K
    E1          -      -     91      8  1.36M   136K
    E2          -      -     94      8  1.36M   136K
    E3          -      -     11     59   128K  1.48M
    E4          -      -     94      8  1.36M   136K
    E5          -      -     92      8  1.36M   136K
    E6          -      -     91      8  1.36M   136K
    E7          -      -     90      8  1.36M   136K
    E8          -      -     90      9  1.36M   136K
    E9          -      -     90      9  1.36M   136K
----------  -----  -----  -----  -----  -----  -----
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
torx        13.9T  4.22T      3      0  1.95K      0
  raidz2    13.9T  4.22T      3      0  1.95K      0
    E0          -      -      0      0    204      0
    E1          -      -      0      0    102      0
    E2          -      -      0      0    153      0
    E3          -      -      0      0    255      0
    E4          -      -      0      0    204      0
    E5          -      -      0      0    204      0
    E6          -      -      0      0    153      0
    E7          -      -      0      0    204      0
    E8          -      -      0      0    255      0
    E9          -      -      0      0    255      0
----------  -----  -----  -----  -----  -----  -----
```

**Comment by woffs** [comment]
Subsequent calls of `zfs diff` onto the same pair of snapshots take reproducible very long time (I aborted manually after 5h). `zfs diff` between other snapshot pairs of the same dataset is fast (36s).

**Comment by dominikh** [comment]
The thread at https://zfsonlinux.topicbox.com/groups/zfs-discuss/T3d7c034221b1220a-Mac8fdaa32ad829183baad855/zfs-discuss-understanding-zfs-diff-performance might help explain the performance of `zfs diff`, in particular how its big-O complexity isn't all that great.

**Comment by itamarst** [comment]
In that thread there's a patch to make `zfs diff` much faster—any chance that could get merged?

**Comment by dominikh** [comment]
I'd love to see this revisited. Quick testing suggests that this problem still exists.

**Comment by bghira** [comment]
open a new issue then, this one is from v0.7 and likely irrelevant. the description doesn't even have a reproducer - it says pool/snap1, but that's not a snapshot path etc.

**Comment by bmillwood** [comment]
I've also run into crushingly slow performance from zfs diff, using `zfs-2.2.3-1`. For posterity, the thread dominikh linked to seems to suggest that the slow part is going from inode number back to link name. The patch adds link name as an attribute to the inode, which enables this lookup quickly (perhaps there would be other use cases for this too?). Comments later on point out that inodes can have more than one link, which you could still handle in the attribute by storing a list, but then there are use cases where inodes could have very large numbers of links, which can lead to the attribute getting large.

I'm recording this here rather than opening a new issue because it sounds like the main thing we're missing is a repro case? It sounds like a bit of work but probably not fundamentally hard to come up with one. I don't promise I'll get round to it, but I might.
