### ISSUE TITLE
invalid backup stream when having multiple datasets

### ISSUE THREAD

**Issue by 24x7ict** [openzfs/zfs#6923]
### System information

We have multiple servers with this issue, from Debian 8 to 9 with old and new versions of ZFS.

ZFS version:        0.6.5.7-8-jessie and higher
SPL version:        0.6.5.7-5-jessie and higher

Debian 8 and 9, different kernels

We use the following back-up routine on all servers:

Every server has a single ZPOOL that is replicated to a standby back-up server AND a off-site back-up server. This works without any problems.

Whenever we expand the server with a second ZPOOL and apply the same back-up routine, we constantly get "invalid backup stream" errors.

**So working situation:**
ZFS storage server
First ZPOOL 
-> ZFS snapshot replica to standby server
zfs send hdd/images@test1 hdd/images@test2 | ssh standby-server zfs receive data/backup-hdd
-> ZFS snapshot replica to off-site server
zfs send hdd/images@test1 hdd/images@test2 | ssh offsite-server zfs receive data/backup-hdd

**Non-working situation:**
ZFS storage server
First ZPOOL 
-> ZFS snapshot replica to standby server
zfs send hdd/images@test1 hdd/images@test2 | ssh standby-server zfs receive data/backup-hdd
-> ZFS snapshot replica to off-site server
zfs send hdd/images@test1 hdd/images@test2 | ssh offsite-server zfs receive data/backup-hdd
Second ZPOOL 
-> ZFS snapshot replica to standby server
zfs send ssd/images@test1 ssd/images@test2 | ssh standby-server zfs receive data/backup-ssd
-> ZFS snapshot replica to off-site server
zfs send ssd/images@test1 ssd/images@test2 | ssh offsite-server zfs receive data/backup-ssd

We schedule back-up every hour, so sometimes multiple are active.

We also have the invalid backup stream error when 2 ZFS servers are sending ZFS snapshots to each other every hour and sometimes overlap.

So ZFS server 1 <-> ZFS server 2
ZFS01: zfs send hdd/images@test1 hdd/images@test2 | ssh ZFS02 zfs receive hdd/backup-zfs01
ZFS02: zfs send hdd/images@test1 hdd/images@test2 | ssh ZFS01 zfs receive hdd/backup-zfs02

I think it's a combination of the following:
- 2 datasets on source server
- Making a snapshot replica to a single backup server at the same time
- Maybe fail because both zpools from source server go to same zpool on backup server (only datasets are different)?

Please let me know if this can be solved.

I will try the following now and let you know the results:

The ZFS server with 2 ZPOOLs will back-up every ZPOOL to a different back-up server. So ZPOOL hdd will go to backup-server01 and ZPOOL ssd will go to backup-server02.

**Comment by rincebrain** [comment]
I'd suggest trying with the 0.6.5.11 packages in stretch-backports and jessie-backports-sloppy if you can, just to confirm it's not something that's already fixed in a newer point release, although a quick read of the changelog doesn't show any obvious fixes.

What are the feature flags enabled on the pools, if any (zpool get all [pool] | grep 'feature@')?

What is the exact set of commands being run, and what are the exact zfs send/recv commands being run by those commands? (e.g. are you running sanoid/znapzend/something else, or a cronjob that runs on the hour, and what commands are in those?)

If I understand what you're describing correctly, this is not expected to fail, but I'd need the details I ask for above to be certain. One question I do have is that zfs send [snap1] [snap2], without flags, definitely won't work.

Would it be possible to use something like tee to capture the snapshots being received on-disk somewhere temporarily, so that you can go back and look at what the send streams you were getting were after noticing the error, so we can determine whether it's a problem with the send stream somehow or something on the system itself?

**Comment by 24x7ict** [comment]
We have this on any server.

Here is a newer server:
ZFS and SPL version:        0.7.3-1

"
  pool: hdd
 state: ONLINE
  scan: resilvered 6.18G in 0h1m with 0 errors on Sat Nov 18 14:29:36 2017
config:

        NAME                                       STATE     READ WRITE CKSUM
        hdd                                        ONLINE       0     0     0
          mirror-0                                 ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z82T67-part1  ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z82TMW-part1  ONLINE       0     0     0
          mirror-1                                 ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83LE7-part1  ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83MX8-part1  ONLINE       0     0     0
          mirror-2                                 ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83P99-part1  ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83N03-part1  ONLINE       0     0     0
          mirror-3                                 ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83PB9-part1  ONLINE       0     0     0
            ata-ST2000DM006-2DM164_Z4Z83Q9S-part1  ONLINE       0     0     0

errors: No known data errors

  pool: ssd
 state: ONLINE
  scan: scrub repaired 0B in 0h0m with 0 errors on Sun Nov 12 06:24:54 2017
config:

        NAME                                               STATE     READ WRITE CKSUM
        ssd                                                ONLINE       0     0     0
          raidz1-0                                         ONLINE       0     0     0
            ata-Crucial_CT525MX300SSD1_173718C9341E-part3  ONLINE       0     0     0
            ata-Crucial_CT525MX300SSD1_173718C93637-part3  ONLINE       0     0     0
            ata-Crucial_CT525MX300SSD1_173718C96A6C-part3  ONLINE       0     0     0
            ata-Crucial_CT525MX300SSD1_173718C9964C-part3  ONLINE       0     0     0

errors: No known data errors
"

The script we use:
`### 24x7 Hosting BV
### ZFS REPLICA SCRIPT
### Push versie van server naar backup-server
### Gemaakt door Nomad de Leeuw

### INFO ###
### SSH keys authoriseren op NAS
### ssh-copy-id nas IP
### Dit bestand opslaan in /root/replica.sh
### Cron aanmaken in /etc/crontab
### nano /etc/crontab
### 0 1-22 * * * root /root/replica.sh > /root/backuplog.txt
### 0 23 * * * root /root/replica.sh | mail -s "ZFS replica backup klantnaam" backup@24x7.nl

### Naam van lokale dataset die je mee neemt in de backup ###
dataset=ssd/proxmox
### IP van de backup nas ###
nasip=192.168.25.21
### Dataset van de backup NAS met een "\" voor de /, dus data\/proxmox ###
remotedataset=data\/backup-ssd
### Backup log locatie, wordt daarna per mail verzonden ###
backuplog=/root/backuplog-ssd.txt
### Mail adres voor back-up logs ###
mail=backup@24x7.nl
### Unieke tag, zo weet hij de snapshots te vinden en kan je meerdere backups doen ###
tag=tag-replica-klantnaam-ssd
### Klantnaam / Server naam
naam=Klantnaam

### LATEN WE BEGINNEN ###

nieuw=$(shuf -i 1-9999 -n 1)-$tag

if
ps aux | grep $tag | grep -v grep
then
echo "Replica is nog bezig, de replica back-up wordt gestopt" | mail -s "ZFS replica $naam is nog bezig" $mail
exit
fi

if
ssh $nasip zfs list -t snapshot | grep $tag > /dev/null
then
echo "ZFS replica back-up is gestart"
echo $(date +"%d-%m-%y %H:%M")
zfs snapshot $dataset@$nieuw
oud=$(ssh $nasip zfs list -t snapshot -H -S creation -o name -d 1 $remotedataset | grep $tag | head -1 | sed s@$remotedataset@@)
zfs send -i $dataset$oud $dataset@$nieuw | ssh $nasip zfs receive $remotedataset
else
echo "############################################################################"
echo "Geen snapshots gevonden, eerste sync starten"
zfs snapshot $dataset@$nieuw
zfs send $dataset@$nieuw | ssh $nasip zfs receive -F $remotedataset
fi

if
ssh $nasip zfs list -t snapshot | grep $remotedataset@$nieuw > /dev/null
then
echo "############################################################################"
echo "Back-up is gelukt"
echo $(date +"%d-%m-%y %H:%M")
for localdestroy in $(zfs list -t snapshot -H -S creation -o name -d 1 $dataset | grep $tag | grep -v $nieuw)
do
zfs destroy "$localdestroy"
done
for remotedestroy in $(ssh $nasip zfs list -t snapshot -H -S creation -o name -d 1 $remotedataset | grep $tag | grep -v $nieuw)
do
ssh $nasip zfs destroy "$remotedestroy"
done
echo "############################################################################"
echo "Snapshots die aanwezig zijn op de server en NAS (moet identiek zijn)"
echo "-----------Server----------"
zfs list -t snapshot | grep $tag
echo "------------NAS------------"
ssh $nasip zfs list -t snapshot | grep $tag
echo "############################################################################"
echo "Retentie snapshots op de NAS"
ssh $nasip zfs list -t snapshot | grep $remotedataset
echo "############################################################################"
echo "Zpool status"
echo "-----------Server----------"
zpool status
echo "------------NAS------------"
ssh $nasip zpool status
echo "############################################################################"
echo "OS RAID status"
echo "-----------Server----------"
mdadm --detail /dev/md0 2> /dev/null
echo "------------NAS------------"
ssh $nasip mdadm --detail /dev/md0 2> /dev/null
else
echo "############################################################################"
echo "Back-up mislukt!!!!!!!!!!!"
echo "############################################################################"
echo "Snapshots die aanwezig zijn op de back-up NAS"
ssh $nasip zfs list -t snapshot | grep $tag
echo "############################################################################"
echo "Snapshots die aanwezig zijn op de server"
zfs list -t snapshot | grep $tag
echo "############################################################################"
cat $backuplog | mail -s "ZFS replica $naam is mislukt!!!" $mail
fi
`

**Comment by rincebrain** [comment]
You, uh, are gonna need to use triple backticks, not single, with that script for it to usefully display, I think.

**Comment by 24x7ict** [comment]
Done ;-)

**Comment by rincebrain** [comment]
My _guess_, which I haven't been able to reproduce in playing with this, is that there might be a bug (a race or otherwise) in the logic that detects whether a send is already running, and having two sends going makes it slow enough that it's still going when it goes to start the next send, and then something strange ensues.

Tell me this - if you comment out the zfs destroys in the backup command, does it still sometimes error out like this?

**Comment by 24x7ict** [comment]
The ZFS destroys only trigger when a replica worked, not when it fails.

I've been able to work around the issue bij doing a zfs rollback to the latest snapshot on the back-up server side. Seems like it has some data after the most recent snapshot, which gets deleted when I do a rollback to the snapshot.

We have this issue sometimes on our remote back-up server because of failed itnernet/connectivity, we get "does not match incremental source" and we also fix this with a rollback.

So maybe I can change my script to apply this fix upon errors.

**Comment by rincebrain** [comment]
-F _should_  force a rollback, though if you've changed some data and then taken a new snapshot on the backup side, that rollback won't do what you necessarily need, since it only rolls back to the most recent snapshot.

Fix it with a rollback to the most recent snapshot on the backup side, or the most recent snapshot that the sender also has (if these differ)?

zfs send -R with zfs receive -F might do what you want, but it's a rather big hammer, and I'd test precisely what it does before using it more generally.

**Comment by 24x7ict** [comment]
The reason why we don't use -F is because we create snapshots on the back-up server to keep retention. I will try it with a retention snapshot after the back-up script has finished correctly.

So I will add -F on the sync and use a retention snapshot at the end of the script when it's done.

**Comment by 24x7ict** [comment]
I thought it was solved by using -F or rollback but that doesn't seem to be the issue. I will try to find a way to reproduce the error.
