### ISSUE TITLE
.deb installation not enabling automatic imports

### ISSUE THREAD

**Issue by Redsandro** [openzfs/zfs#6934]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Linux Mint 18.3 AKA Ubuntu 16.04.3
Distribution Version    | Sylvia / Xenial
Linux Kernel                 | 4.13
Architecture                 | x86_64
ZFS Version                  | ~0.7.0-17
SPL Version                  | Multiple between 0.7.0-rc2 and current master 0.7.0-xxx

### Describe the problem you're observing

I've compiled (`make deb`) and installed multiple versions from git/master on multiple machines. Some Debian machines and some Ubuntu machines.

Now unless I'm mistaken, I feel like the first couple of installs (Debian) everything worked out of the box. But lately, when testing on Ubuntu machines, I notice that no pool is being imported at startup. I have to do this manually.

I feel like either:

* The installation is no longer doing certain steps; or
* The documentation doesn't mention certain manual steps that need to be taken; or
* I'm making mistakes.

#### Workaround

After some googling around I read about steps like the following need to be taken:

```
systemctl unmask zfs-*
systemctl enable zfs-import
systemctl enable zfs-mount
systemctl enable zfs-share
systemctl enable zfs-zed
update-rc.d zfs-import enable
update-rc.d zfs-mount enable
update-rc.d zfs-share enable
update-rc.d zfs-zed enable
```

I'm reasonably sure I didn't have to do that before. What changed? Is it 'me' or 'you'?

**Comment by gdevenyi** [comment]
Ubuntu and debian packages default to enabling services when installing. Centos and redhat do not, it seems ZFS chose the redhat path
