### ISSUE TITLE
Zpool import taints kernel

### ISSUE THREAD

**Issue by G-man88** [openzfs/zfs#6944]
Distribution Name   Artful Aardvark    | 
Distribution Version 17.10   | 
Linux Kernel   4.13.0-19-generic               | 
Architecture                 | 
ZFS Version  0.6.5.11-1ubuntu3          | 
SPL Version  0.6.5.11-1ubuntu1               | 

Commands to find ZFS/SPL versions:
modinfo zfs | grep -iw version
modinfo spl | grep -iw version 
I have an issue where my zpool taints my kernel. I was running on 17.04 because my Nas is running on Ryzen. I got it working for the most part without issue for a few months when yesterday it started to freeze so I rebooted the system, and it hanged for a while. I then manually turned it off but the zpool didn't mount so I shut it down again and I got Tainted: P error and it would hang. I then decided to upgrade to Ubuntu 17.10, but I'm getting the same issue The error I'm getting below It keeps repeating that error and just hangs.  Forgive me for not being well versed in how to submit these issues. If there is anything else you need please let me know and I'll post it. 

```
task txg_sync:2323 blocked for more than 120 seconds 
      Tainted: P                0          4.13.0-19-generic #22-Ubuntu
```

**Comment by DeHackEd** [comment]
Unfortunately there's nothing that can be done. ZFS is not GPL licensed and is not a stock module. Both of these are sufficient for a kernel to become tainted when the driver is loaded

**Comment by G-man88** [comment]
Thank you for posting, but is there anything at all I can do to resolve this issue with my zpool? I don't know a lot about zfs so I'm up a creek without a paddle. I just want to understand this a bit better.

**Comment by DeHackEd** [comment]
Now I am confused by what the problem is. Maybe you accidentally commented out your post?

**Comment by G-man88** [comment]
Sorry I didn't notice that. The whole comment is up now.

**Comment by rincebrain** [comment]
@G-man88 your comment does not, in fact, appear to be intact.

Could you possibly use pastebin or something else for dmesg + the console output if GH comments aren't easy to wrestle into submission?

**Comment by G-man88** [comment]
@rincebrain I'm sorry I'm not sure what you mean. This is the first time I've used this and I'm pretty ignorant with it right now.

**Comment by rincebrain** [comment]
@G-man88 The only line I see in your comment that could be technical output is
```
Tainted: P                0          4.13.0-19-generic #22-Ubuntu
```

I was asking if you could use a pastebin service (like paste.ubuntu.com, or pastebin.com) to paste the output of the command "dmesg", as well as the repeating line(s) that you get when the system misbehaves like this, rather than trying to figure out how to make Github comments display properly.

**Comment by DeHackEd** [comment]
The "tainted" warning is for kernel devs looking at this for troubleshooting of possible kernel bugs. 'P' means proprietary (non-GPL) license was loaded. All it means is don't go whining to LKML if it breaks.

**Comment by G-man88** [comment]
@rincebrain sorry here is that paste https://pastebin.com/BpFkvnRm let me know if there's anything else I can give you. I'm new to all of this.

**Comment by G-man88** [comment]
@DeHackEd I gotcha, I just grabbed the error I was getting that hangs my system. Honestly I'm just trying to repair my zpool it's a 30 TB RaidZ2 I'll be pretty crestfallen if I lose it.

**Comment by rincebrain** [comment]
@G-man88 That looks like nothing interesting has gone on - can you possibly get the logs from prior boots, presumably just before it became unresponsive?

The commands, since that log indicates you're using systemd, would be of the form
```
journalctl --boot=-1
```
(Or -2 for two boots ago, and so on. )

Also, if you'd like to discuss this in more realtime, you can poke into #zfsonlinux on Freenode. You shouldn't end up losing your zpool even if we can't resolve whatever this problem is - if nothing else, illumos derivatives or FreeBSD could be booted on the system to extract your data, though I don't imagine that will remotely be necessary.

**Comment by ronnyegner** [comment]
@G-man88 When the system starts could you try:
`
zpool import`

To see what zfs thinks about the pool?

**Comment by G-man88** [comment]
Well, I was able to get the zpool to import by making it read only then making it read write. I have no idea what was going wrong with the zpool. When I run a zpool status it tells me all pools are healthy. I would love to know why it did that. I'm going to reboot it a few times later today to make sure it doesn't repeat before I close this issue. If all goes well I'll close the issue tomorrow.

**Comment by G-man88** [comment]
Well I'm glad I didn't close this issue. After a reboot it did the same thing. 

@ronnyegner A zpool import take a minute but it imports fine so long as I don't mount it. It says "errors: No known data errors" and all the drives are online. If I try to import the pool though it will hang my system and cause a tainted kernel error. Is there a way to clean the pool or something?

**Comment by G-man88** [comment]
@rincebrain When I try to run journalctl I get "Specifying boot ID or boot offset has no effect, no persistent journal was found" so I'm not sure if I need to enable it or what.

**Comment by rincebrain** [comment]
@G-man88 Yeah, some distros don't enable it by default. https://unix.stackexchange.com/a/159390 should be sufficient instructions on how to do that.

**Comment by G-man88** [comment]
@rincebrain Here is that boot log you requested. https://pastebin.com/cVZx2mq5 

I hope it helps get to the bottom of this.

**Comment by rincebrain** [comment]
@G-man88 that seems to be truncated in width - did you copy and paste it out of a terminal, possibly?

Is that log from a boot where the zpool import hung?

**Comment by G-man88** [comment]
@rincebrain  Yeah I copied it from a terminal page, I didn't notice the width issue. I redid it here https://pastebin.com/5n7y9zua

**Comment by rincebrain** [comment]
@G-man88 Those seem to be from two different boots - like I mentioned, -b -1 will give "the boot immediately before this one", -2 will do the one before that, and so on, so if you lock the machine up and have to reboot again, -1 will point to a different one.

The second one you pasted seems to have not finished booting - ZED hasn't started, and I don't see any interesting ZFS log entries in either, immediately, while the first one seems to have cleanly shut down, which I wouldn't necessarily expect it to be able to do with a hung ZFS thread.

Could try doing sudo su -c "echo 1 > /sys/module/zfs/parameters/zfs_dbgmsg_enable; echo 1023 > /sys/module/zfs/parameters/zfs_flags;", then try to import the pool and mount the FSes, and then cat /proc/spl/kstat/zfs/dbgmsg and see what showed up in there - even if syslog doesn't have anything fun, that really should. It doesn't persist across reboots, though, so if the system completely stops responding, you can't get it afterward. (You could have something periodically copying the contents out of the file to disk.)
