### ISSUE TITLE
Remove specified entry from ZAP directly without lookup internally

### ISSUE THREAD

**Issue by Nasf-Fan** [openzfs/zfs#6948]
Currently, zap_remove()/zap_remove_by_dnode() needs to lookup the specified index (or name) to locate the entry internally with the directory locked, then remove the found entry. In fact, for most of cases, the caller has already performed lookup before calling zap_remove()/zap_remove_by_dnode(). But related lookup result cannot be used by the zap_remove()/zap_remove_by_dnode().

I am wondering whether or not we can extend related API (and locks) to allow lookup the entry outside and directly use the lookup result for removing, that will save some lookup overhead. That will improve unlink/delete performance, especially for large directory.

**Comment by bzzz77** [comment]
another option - zap_remove_and_return() returning value

**Comment by behlendorf** [comment]
I like @bzzz77's suggestion which would fit nicely in to the existing interface, although I'd suggest naming it  `zap_lookup_and remove()`.
