### ISSUE TITLE
Linux 4.13+: Warnings from objtool while compiling the 'icp' kernel module: "unsupported stack pointer realignment" (in SHA1/SHA2 functions)

### ISSUE THREAD

**Issue by jgottula** [openzfs/zfs#6950]
I don't know how important these build-time warnings actually are, but I've typed up a full report here anyway.

## The warnings

I was building the latest zfs master, 4e9b156960562373e005798575a3fbc6d66e32ff, for Linux 4.14.5, on x86_64 today.

Here's what came up during the build process:
```
/home/build/zfs/zfs-20171212-latest/archzfs/packages/linux/zfs-linux-git/src/zfs/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
/home/build/zfs/zfs-20171212-latest/archzfs/packages/linux/zfs-linux-git/src/zfs/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
/home/build/zfs/zfs-20171212-latest/archzfs/packages/linux/zfs-linux-git/src/zfs/module/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
```
Those warnings correspond to these particular instructions from the objdump'd object files:
```
0000000000000000 <sha1_block_data_order>:
      ...
      11:       48 83 e4 c0             and    rsp,0xffffffffffffffc0
      ...
```
```
0000000000000000 <SHA256TransformBlocks>:
      ...
      19:       48 83 e4 c0             and    rsp,0xffffffffffffffc0
      ...
```
```
0000000000000000 <SHA512TransformBlocks>:
      ...
      1c:       48 83 e4 c0             and    rsp,0xffffffffffffffc0
      ...
```

## The recent update to objtool 

It looks like this warning will only appear when compiling for Linux 4.13 or later, since the objtool patchset that added new warnings (including the "unsupported stack pointer realignment" one) was merged into the mainline kernel in 4.13.

Here's some additional info on that objtool patchset:
- LKML: [objtool: stack validation 2.0](https://lkml.org/lkml/2017/6/1/38)
- Patchwork: [objtool: stack validation 2.0](https://patchwork.kernel.org/patch/9814577/)
- Commit: [baa41469a7b992c1e3db2a39854219cc7442e48f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=baa41469a7b992c1e3db2a39854219cc7442e48f)

[Here's the specific part of the objtool code that's complaining.](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/objtool/check.c?id=baa41469a7b992c1e3db2a39854219cc7442e48f#n1101)
[And here's some internal documentation regarding what it's complaining about.](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/objtool/check.c?id=baa41469a7b992c1e3db2a39854219cc7442e48f#n961)

## The ZoL source lines being complained about

Here are the relevant assembly code source file lines in ZoL:

https://github.com/zfsonlinux/zfs/blob/4e9b156960562373e005798575a3fbc6d66e32ff/module/icp/asm-x86_64/sha1/sha1-x86_64.S#L79
https://github.com/zfsonlinux/zfs/blob/4e9b156960562373e005798575a3fbc6d66e32ff/module/icp/asm-x86_64/sha2/sha256_impl.S#L96
https://github.com/zfsonlinux/zfs/blob/4e9b156960562373e005798575a3fbc6d66e32ff/module/icp/asm-x86_64/sha2/sha512_impl.S#L97

## 32-bit

As far as I can tell, i386 builds of zfs won't emit this warning, as from what I can see, the asm implementations of the three SHA functions in question are only used for the kernel module on x86_64, and everything else just uses the C implementations.

But I don't have an i386 Linux box/VM ready-at-hand to do a quick build and actually confirm for sure that these warnings don't happen there.

**Comment by jgottula** [comment]
Also, I thought it'd be worth mentioning that the asm implementations of SHA1/SHA2 in the ICP module come from Illumos, which in turn got them from OpenSSL; quite a long time ago, by the looks of it (2009 at the very latest).

It looks like the upstream OpenSSL implementation has advanced quite a bit since Illumos branched their code off; among other things, the OpenSSL version now has specializations for SSSE3, AVX, AVX2+BMI, and Intel SHA instruction set extensions now.

So that might be worth looking at sometime. (And/or #2351.)

**Comment by h1z1** [comment]
Still outstanding as of latest git.  Funny thing is this was the first hit on google for that error :)

**Comment by c0d3z3r0** [comment]
Confirmed on Debian testing with ZFS 0.7.11, custom Kernel 4.19.1

~~~
[...]
/var/lib/dkms/zfs/0.7.11/build/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
  AS [M]  /var/lib/dkms/zfs/0.7.11/build/module/icp/asm-x86_64/sha2/sha512_impl.o
/var/lib/dkms/zfs/0.7.11/build/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
/var/lib/dkms/zfs/0.7.11/build/module/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
  LD [M]  /var/lib/dkms/zfs/0.7.11/build/module/icp/icp.o
make[3]: *** [Makefile:1517: _module_/var/lib/dkms/zfs/0.7.11/build/module] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-4.19.1'
make[2]: *** [Makefile:27: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.7.11/build/module'
make[1]: *** [Makefile:701: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.7.11/build'
make: *** [Makefile:572: all] Error 2
root@debian:/usr/src/kernel# dkms status
spl, 0.7.11, 4.18.0-2-amd64, x86_64: installed
spl, 0.7.11, 4.19.1, x86_64: installed
zfs, 0.7.11, 4.18.0-2-amd64, x86_64: installed
~~~

**Comment by darrenfreeman** [comment]
What are the consequences of this? Is it safe to ignore?

**Comment by 3f8wohoo** [comment]
can confirm this for `0.7.12` kernel `4.19.14` on debian stretch:

```
...
aking all in 02zfsexpandknowledge
Making all in 90zfs
Making all in initramfs
Making all in module
/root/zfs-0.7.12/module/icp/asm-x86_64/sha1/.tmp_sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
/root/zfs-0.7.12/module/icp/asm-x86_64/sha2/.tmp_sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
/root/zfs-0.7.12/module/icp/asm-x86_64/sha2/.tmp_sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
```

**Comment by behlendorf** [comment]
Yes, it's safe to ignore.  Though of course we would like to resolve the warning.

**Comment by sempervictus** [comment]
This is still a thing on Arch Linux GCC 10.2 against 5.10.12:
```
fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
  AS      fs/zfs/icp/asm-x86_64/sha2/sha256_impl.o
  CC      arch/x86/kernel/acpi/boot.o
  CC      fs/zfs/zcommon/zfs_fletcher_superscalar.o
  CC      arch/x86/kernel/acpi/sleep.o
fs/zfs/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
  AS      fs/zfs/icp/asm-x86_64/sha2/sha512_impl.o
  CC      crypto/asymmetric_keys/asymmetric_type.o
fs/zfs/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
```

**Comment by AndyLavr** [comment]
Fix it, the kernel will be adopting this fix soon:

https://lore.kernel.org/patchwork/cover/1383999/

**Comment by AttilaFueloep** [comment]
Thanks to the excellent information in this ticket, I'd say `objtool` is complaining that we don't  use a DRAP register while aligning the stack to a 64 byte boundary. A DRAP register is a `gcc` concept. Since we are notoriously low on registers in the crypto code, I'd say it isn't worth the effort to mimic gcc generated stack alignment. I think the best approach will be to just silence the warning with `STACK_FRAME_NON_STANDARD` or `OBJECT_FILES_NON_STANDARD`. Is there any benefit in  an `objtool` conforming stack with hand written assembly?

**Comment by behlendorf** [comment]
I'm fine with silencing the warning for all the reasons you mentioned.

**Comment by AttilaFueloep** [comment]
OK, will open a PR once #11733  settles.

**Comment by AndyLavr** [comment]
> I think the best approach will be to just silence the warning with `STACK_FRAME_NON_STANDARD` or `OBJECT_FILES_NON_STANDARD`

"objtool, modules: Discard objtool annotation sections for modules"
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e390f9a9689a42f477a6073e2e7df530a4c1b740


I use such a patch on my local test branch, there are no problems, everything works and the build goes without any warnings.


```patch
diff --git a/fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.S b/fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
index dc71ae2..b7f0296 100644
--- a/fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
+++ b/fs/zfs/icp/asm-x86_64/modes/aesni-gcm-x86_64.S
@@ -1239,6 +1239,7 @@
        ret
 .size  atomic_toggle_boolean_nv,.-atomic_toggle_boolean_nv
 
+.data
 .align 64
 .Lbswap_mask:
 .byte  15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
@@ -1253,6 +1254,13 @@
 .byte  65,69,83,45,78,73,32,71,67,77,32,109,111,100,117,108,101,32,102,111,114,32,120,56,54,95,54,52,44,32,67,82,89,80,84,79,71,65,77,83,32,98,121,32,60,97,112,112,114,111,64,111,112,101,110,115,115,108,46,111,114,103,62,0
 .align 64
 
+
+.pushsection .discard.func_stack_frame_non_standard, "aw"
+.long _aesni_ctr32_ghash_no_movbe_6x - .
+.long aesni_gcm_decrypt - .
+.long aesni_gcm_encrypt - .
+.popsection
+
 /* Mark the stack non-executable. */
 #if defined(__linux__) && defined(__ELF__)
 .section .note.GNU-stack,"",%progbits
diff --git a/fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.S b/fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.S
index 90cc36b..501a3a5 100644
--- a/fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.S
+++ b/fs/zfs/icp/asm-x86_64/modes/ghash-x86_64.S
@@ -652,6 +652,8 @@
        .byte   0xf3,0xc3
 .cfi_endproc
 .size  gcm_ghash_avx,.-gcm_ghash_avx
+
+.data
 .align 64
 .Lbswap_mask:
 .byte  15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0
diff --git a/fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.S b/fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.S
index cb92378..da854a3 100644
--- a/fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.S
+++ b/fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.S
@@ -1348,6 +1348,10 @@
 
 #endif /* lint || __lint */
 
+.pushsection .discard.func_stack_frame_non_standard, "aw"
+.long sha1_block_data_order - .
+.popsection
+
 #ifdef __ELF__
 .section .note.GNU-stack,"",%progbits
 #endif
diff --git a/fs/zfs/icp/asm-x86_64/sha2/sha256_impl.S b/fs/zfs/icp/asm-x86_64/sha2/sha256_impl.S
index 766b753..57867fc 100644
--- a/fs/zfs/icp/asm-x86_64/sha2/sha256_impl.S
+++ b/fs/zfs/icp/asm-x86_64/sha2/sha256_impl.S
@@ -2058,6 +2058,10 @@
        .long   0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
 #endif /* !lint && !__lint */
 
+.pushsection .discard.func_stack_frame_non_standard, "aw"
+.long SHA256TransformBlocks - .
+.popsection
+
 #ifdef __ELF__
 .section .note.GNU-stack,"",%progbits
 #endif
diff --git a/fs/zfs/icp/asm-x86_64/sha2/sha512_impl.S b/fs/zfs/icp/asm-x86_64/sha2/sha512_impl.S
index 6e37618..1239d53 100644
--- a/fs/zfs/icp/asm-x86_64/sha2/sha512_impl.S
+++ b/fs/zfs/icp/asm-x86_64/sha2/sha512_impl.S
@@ -2083,6 +2083,10 @@
        .quad   0x5fcb6fab3ad6faec,0x6c44198c4a475817
 #endif /* !lint && !__lint */
 
+.pushsection .discard.func_stack_frame_non_standard, "aw"
+.long SHA512TransformBlocks - .
+.popsection
+
 #ifdef __ELF__
 .section .note.GNU-stack,"",%progbits
 #endif

```

**Comment by AttilaFueloep** [comment]
@AndyLavr 
> ```diff
> +.pushsection .discard.func_stack_frame_non_standard, "aw"
> +...
> ```

Actually I'd prefer to use the C macro `STACK_FRAME_NON_STANDARD`for that. IIUC in the end it inserts exactly that. Since the MacOS and Windows ports use the ICP as well, it would be better not to add Linux specific directives to the assembly file.

**Comment by AndyLavr** [comment]
> Actually I'd prefer to use the C macro `STACK_FRAME_NON_STANDARD`for that.

I've provided my variant for Linux. I have no other systems. It also allowed us to move bswap_mask to the .data section and get rid of the "can't find jump dest instruction" warning.

**Comment by AttilaFueloep** [comment]
Much appreciated. Regarding bswap_mask please see https://github.com/openzfs/zfs/pull/11733#issuecomment-798267788. Not sure if we officially support clang on Linux? But I'll have a look anyhow.

**Comment by AndyLavr** [comment]
@AttilaFueloep

>  Regarding bswap_mask please see [#11733 (comment)]

[Please see](https://github.com/openzfs/zfs/pull/11733#issuecomment-798401482)

> Not sure if we officially support clang on Linux? But I'll have a look anyhow.

 Clang + LTO build support has already been added to the Linux tree.
