### ISSUE TITLE
ZFS mount/unmount process stuck

### ISSUE THREAD

**Issue by itcrowdsource** [openzfs/zfs#6966]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    | 16.04 / Xenial
Linux Kernel                 | 4.4.0-101-generic
Architecture                 | x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts cpufreq
ZFS Version                  | version:        0.6.5.6-0ubuntu16
SPL Version                  | version:        0.6.5.6-0ubuntu4

### Describe the problem you're observing
Specifically were encountering issues within LXD. The ZFS mount point seems to be locked after restarting a LXC container that uses ZFS. This doesnt seem to be a LXD-related problem but rather a bug within ZFS.

LXD log:
action=shutdown created=2017-11-24T15:01:04+0000 ephemeral=false lvl=info msg="Shutting down container" name=c2 t=2017-12-15T05:44:10+0000 timeout=-1s used=2017-11-24T15:06:55+0000
action=shutdown created=2017-11-24T15:01:04+0000 ephemeral=false lvl=info msg="Shut down container" name=c2 t=2017-12-15T05:44:40+0000 timeout=-1s used=2017-11-24T15:06:55+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=c2 t=2017-12-15T05:44:40+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/c2\" is actually not a mountpoint." t=2017-12-15T05:44:50+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=c2 t=2017-12-15T05:44:50+0000

### Describe how to reproduce the problem
1. lxc restart NAME
2. Container is stuck in the shutdown process
3. After a while the container isnt running anymore
4. Unable to start the container

https://github.com/lxc/lxd/issues/4104

Probably also related to:
https://github.com/zfsonlinux/zfs/issues/5796

**Comment by stgraber** [comment]
This will be addressed by the fix in #7120 so the issue should probably be considered a duplicate of #5796.

**Comment by behlendorf** [comment]
There is an updated version of the #7207.

**Comment by DeadlyMercury** [comment]
I have simmilar problem, but I have no answer from zfs like "ZFS returned EBUSY": it just hangs.
Last message in monitor is:
message: Mounting ZFS storage volume for container "bl-adm" on storage pool "default".

And after that commands like "zfs list" hangs too with no info, only kernel errors like:
INFO: task lxd:26664 blocked for more than 120 seconds.

#7207 marked as closed and fixed in version 0.7.9. I tried to install it from ppa, but it did not help.

**Comment by behlendorf** [comment]
This may be a duplicate of #7659.

**Comment by vazir** [comment]
@stgraber do you think the fix is going to be in the 18.04 anytime soon?

**Comment by DeadlyMercury** [comment]
@vazir you can watch it here:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1781364
