### ISSUE TITLE
Different sector size error message wrong or misleading

### ISSUE THREAD

**Issue by ThomDietrich** [openzfs/zfs#6975]
Hello everyone.
The optimal sector size error related to a device replacement is misleading or simply wrong. As you can see below, the error presented doesn't make much sense and is not helpful. What is the alleged "optimal sector size", how does a user need to handle that issue? I'd suggest to improve the message as did [another user already](https://github.com/zfsonlinux/zfs/pull/2427#issuecomment-321887912).

----

My case - help would also be appreciated:

I am in the process of replacing a hard drive when faced with this error:

```shell
 $ sudo zpool replace tank 12849889439322109762 ata-ST2000DM006-2DM164_Z4Z90YHR
cannot replace 12849889439322109762 with ata-ST2000DM006-2DM164_Z4Z90YHR: new device has a different optimal sector size; use the option '-o ashift=N' to override the optimal size

 $ sudo zpool replace -o ashift=12 tank 12849889439322109762 ata-ST2000DM006-2DM164_Z4Z90YHR
cannot replace 12849889439322109762 with ata-ST2000DM006-2DM164_Z4Z90YHR: new device has a different optimal sector size; use the option '-o ashift=N' to override the optimal size
```

```shell
 $ sudo zpool status
  pool: tank
 state: DEGRADED
config:

        NAME                                    STATE     READ WRITE CKSUM
        tank                                    DEGRADED     0     0     0
          raidz1-0                              ONLINE       0     0     0
            ... REDACTED
          raidz1-1                              DEGRADED     0     0     0
            12849889439322109762                UNAVAIL      0     0     0  was /dev/disk/by-id/ata-SAMSUNG_HD204UI_S2H7J1CZ907120-part1
            ata-SAMSUNG_HD204UI_S2H7J90B321120  ONLINE       0     0     0
            ata-SAMSUNG_HD204UI_S2H7J9JB902323  ONLINE       0     0     0
            ata-SAMSUNG_HD204UI_S2H7J9JB902334  ONLINE       0     0     0
          raidz1-2                              ONLINE       0     0     0
            ... REDACTED
        spares
          ata-ST2000DM006-2DM164_Z4Z90YHR       AVAIL

errors: No known data errors
```

(I've tried both with a spare and an external drive with the same effect)

Other than issues I found on the matter, I payed attention to the 4K issue (I hope) back when the pool was created by specifically setting it up with `ashift=12`, as you can see from zdb:

```shell
 $ sudo zdb tank
...
ashift: 12
...
```

The obvious difference I can see is, that the new drives are indeed 4K devices, while the old ones weren't.

Old drive:

```
 $ sudo hdparm -I /dev/disk/by-id/ata-ST2000DL003-9VT166_6YD1HK6W
        Logical/Physical Sector size:           512 bytes
```

New drive:
```
 $ sudo hdparm -I /dev/disk/by-id/ata-ST2000DM006-2DM164_Z4Z90YHR
        Logical  Sector size:                   512 bytes
        Physical Sector size:                  4096 bytes
        Logical Sector-0 offset:                  0 bytes
```

What can I do about that? Thanks for you work and help!

### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  Ubuntu 14.04.5 LTS
Linux Kernel                 |  3.13.0-137-generic
Architecture                 | x86_64
ZFS Version                  |  0.6.5.11-1~trusty
SPL Version                  |  0.6.5.11-1~trusty

**Comment by DeHackEd** [comment]
You're doing it wrong. `ashift=12` is what the drive specifies, but your old disks specify `ashift=9`. This direction causes the error message.

I suppose it could be rewritten, or maybe even suggest what option to use. But as someone who's done it, it sucks.

**Comment by rincebrain** [comment]
@ThomDietrich Can you share all of the lines from zdb tank | grep ashift?

**Comment by ThomDietrich** [comment]
@DeHackEd thanks for your prompt answer! I see. Well I already expected it to be somehow related to that. But even with your answer I didn't get what I'm doing wrong. What "sucks"? What's your suggestion for my next step?

@rincebrain here you go. Now I kinda see my problem...

```
 $ sudo zdb tank | more

Cached configuration:
        version: 5000
        name: 'tank'
        state: 0
        vdev_children: 3
        vdev_tree:
            type: 'root'
            id: 0
            children[0]:
                type: 'raidz'
                id: 0
                ashift: 12
                children[0]:
                children[1]:
                children[2]:
                children[3]:
            children[1]:
                type: 'raidz'
                id: 1
                ashift: 9
                children[0]:
                children[1]:
                children[2]:
                children[3]:
            children[2]:
                type: 'raidz'
                id: 2
                ashift: 9
                children[0]:
                children[1]:
                children[2]:
                children[3]:
```

I suspect this is bad? 🙈

**Comment by ThomDietrich** [comment]
```
sudo zpool replace -o ashift=9 tank 12849889439322109762 ata-ST2000DM006-2DM164_Z4Z90YHR
```
worked. Thanks guys!

Now my first question is: Is the constallation my system is in bad? (not that I can do anything about it now)

Second question: Clearly the error message could be improved. Wdyt?

**Comment by rincebrain** [comment]
Well, two of your vdevs are ashift=9 (512b), and one is ashift=12 (4kb).

Briefly, drives that are 4k native or emulating 512b sectors, in order to do a 512b write, need to read 4k off the disk, modify those 512b, and write the 4k back. ashift "essentially" is the smallest unit that the vdev devices will address, and so while using 4k on 512b drives is fine, using 512b on 4k drives involves lots of read-modify-write cycles.

So you'd need to specify -o ashift=9 to put the 4k drive in the ashift=9 vdev, but that has severe negative performance implications.

To fix this, you'd need to remake the pool, and use -o ashift=12 each time if you made the pool with zpool create then zpool add. 

I would agree the message could be more specific, and ideally would come with a warning about how using ashift=9 on a 4k drive has serious negative performance implications.

**Comment by ThomDietrich** [comment]
Thanks for the explanation! Remaking the pool is as you can imagine not an option. From what I understood it would be a workaround to replace a drive in the first (ashift 12) raidz with the new hard drive, then use the free (old) hard drive as the replacement in the second (ashift 9) raidz. Correct?

Side note: is ashift=12 a default by now? Seems like a huge pitfall.

Regarding the message: Yes that would be a huge improvement.

**Comment by rincebrain** [comment]
You could replace a drive in the ashift=12 vdev and if the drive you replaced is a 512b native drive, you could use it to replace a drive in the ashift=9 vdevs without horrific implications.

The default, if you don't specify, is to try to use whatever is the native size of the drives, though there is a hardcoded override list of drives which lie about their native size.
