### ISSUE TITLE
Documentation of ACLs should be fixed

### ISSUE THREAD

**Issue by fejesjoco** [openzfs/zfs#6994]
There are issues in the manpage of zfs(8).

aclinherit talks about ACEs, acltype talks about ACLs, this is inconsistent.

aclinherit doesn't mention what kind of ACEs it's talking about. Since neither regular file permission bits not POSIX ACLs have write_acl/write_owner, this must be NFSv4. So that should be mentioned here explicitly.

acltype has two values. Again this doesn't say what it's talking about and one can only guess. Does "off" turn off both NFSv4 and POSIX ACLs, or just POSIX? Does "posixacl" enable both NFSv4 and POSIX, or only POSIX? I can even read it in a way that I can either have POSIX ACLs or no ACLs, which would mean NFSv4 ACLs are not even supported under Linux.

The source code has many mentions of an aclmode property but this is not documented anywhere.

Since the document talks about multiple ACL types, it might be worth mentioning if regular file permission bits work as usual or not (this is especially interesting across dataset mount boundaries).

If you can confirm these points, I can volunteer to send a PR.

**Comment by dcrdev** [comment]
I would echo the need for documentation here - it unclear.

As I understand it setting acls via nfs - only a subset of nfs acls are translated into posix acls. With setting nfsv4 acls in zfs, the need to do this translation is not needed as it's a 1-1 map.

When acls is set to off, I believe it uses zfs acls which are not supported by Linux - but are supported to a limited extent in things like samba where you can enable the zfs acl vfs extension.

The last time I read up on this though, I believe the nfsv4 acl mode hadn't been implemented yet in ZoL. 

That's what I could ascertain from this issue:
https://github.com/zfsonlinux/zfs/issues/6391

Also this one:
https://github.com/zfsonlinux/zfs/issues/4966
