### ISSUE TITLE
Silent drive failures with kernel debug messages

### ISSUE THREAD

**Issue by darrenfreeman** [openzfs/zfs#7070]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9.3
Linux Kernel                 | 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2
Architecture                 | x86-64
ZFS Version                  | 0.7.5 (from tarball)
SPL Version                  | 0.7.5 (from tarball)

### Describe the problem you're observing

I've moved to a new LSI2008 SAS controller, which I think is more reliable than the beehive of different cards I had before. However now I'm getting checksum errors and quite significant amounts of data needing to be resilvered, and it looks like one of the SSDs in the mirror is dropping out for days, before being readded on a reboot + zfs import. (Due to broken init scripts, zfs import is needed on every boot.)

But how can this be? Surely a drive falling off the controller shouldn't show as ONLINE, and no errors, during multiple scrubs. I scrub every day. Yet after a reboot, I've got nearly 100 GB of data to resilver.

This has happened enough times now, for me to think that internally, zfs is failing this drive and not considering it during future scrubs, which is why nothing ever needs repairing. But it's not presenting this to the user via zpool status. The drive is marked as ONLINE with no errors. Scrubs happen daily and nothing seems to be amiss. Then you reboot and zpool import, which clears the failed status, and wow, 40% of my dataset needs resilvering.

I moved from an older git version about the same age as 0.7.2, to 0.7.5, at the same time as migrating the hardware. But the amount of data needing to be resilvered after this migration was such that it still looks like I had a silent drive failure for days or even weeks prior to the reboot required for migration to new hardware.

Well, now the drive has been marked as UNAVAILABLE with checksum errors:

```
  pool: ssd
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
        invalid.  Sufficient replicas exist for the pool to continue
        functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: scrub repaired 0B in 0h53m with 0 errors on Sat Jan 20 08:08:30 2018
config:

        NAME        STATE     READ WRITE CKSUM
        ssd         DEGRADED     0     0     0
          mirror-0  DEGRADED     0     0     0
            ssd1    UNAVAIL      0     0    14  corrupted data
            ssd0    ONLINE       0     0     0

errors: No known data errors
```

At this point, I inspected /var/log/messages, and indeed this drive has thrown up a bunch of errors within the driver for the SAS card. About 15 minutes of very similar errors that look like the first few lines, followed by this:

```
Jan 20 00:44:54 xxx kernel: [20008.105603] sd 0:0:2:0: [sdc] tag#3 FAILED Result: hostbyte=DID_SOFT_ERROR driverbyte=DRIVER_OK
Jan 20 00:44:54 xxx kernel: [20008.105608] sd 0:0:2:0: [sdc] tag#3 CDB: Write(10) 2a 00 32 71 17 88 00 00 10 00
Jan 20 00:44:54 xxx kernel: [20008.105636] sd 0:0:2:0: [sdc] tag#5 FAILED Result: hostbyte=DID_SOFT_ERROR driverbyte=DRIVER_OK
Jan 20 00:44:54 xxx kernel: [20008.105638] sd 0:0:2:0: [sdc] tag#5 CDB: Write(10) 2a 00 01 94 55 e0 00 00 08 00
Jan 20 00:44:55 xxx kernel: [20008.355524] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:55 xxx kernel: [20008.355530] sd 0:0:2:0: [sdc] tag#0 FAILED Result: hostbyte=DID_SOFT_ERROR driverbyte=DRIVER_OK
Jan 20 00:44:55 xxx kernel: [20008.355536] sd 0:0:2:0: [sdc] tag#0 CDB: Write(10) 2a 00 14 47 80 88 00 00 30 00
Jan 20 00:44:55 xxx kernel: [20008.607517] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:55 xxx kernel: [20008.607526] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:56 xxx kernel: [20009.358550] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:56 xxx kernel: [20009.358553] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:56 xxx kernel: [20009.558502] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:44:56 xxx kernel: [20009.558505] mpt2sas_cm0: log_info(0x31120303): originator(PL), code(0x12), sub_code(0x0303)
Jan 20 00:55:21 xxx kernel: [20634.996104] usb 4-2: USB disconnect, device number 2
Jan 20 04:15:12 xxx kernel: [32625.632170] z_zvol          D    0 30925      2 0x00000000
Jan 20 04:15:12 xxx kernel: [32625.632176]  ffffa0479ac48c00 0000000000000000 ffffa0466d46d200 ffffa047dfad8940
Jan 20 04:15:12 xxx kernel: [32625.632178]  ffffa047bbc401c0 ffffb6a309da3ca0 ffffffffb1a02923 ffffffffb1a04b5e
Jan 20 04:15:12 xxx kernel: [32625.632180]  0000000000000000 ffffa047dfad8940 ffffa047b5fa50d8 ffffa0466d46d200
Jan 20 04:15:12 xxx kernel: [32625.632183] Call Trace:
Jan 20 04:15:12 xxx kernel: [32625.632193]  [<ffffffffb1a02923>] ? __schedule+0x233/0x6d0
Jan 20 04:15:12 xxx kernel: [32625.632195]  [<ffffffffb1a04b5e>] ? mutex_lock+0xe/0x30
Jan 20 04:15:12 xxx kernel: [32625.632196]  [<ffffffffb1a02df2>] ? schedule+0x32/0x80
Jan 20 04:15:12 xxx kernel: [32625.632216]  [<ffffffffc0a795e6>] ? taskq_wait_outstanding+0x86/0xd0 [spl]
Jan 20 04:15:12 xxx kernel: [32625.632225]  [<ffffffffb14b86c0>] ? prepare_to_wait_event+0xf0/0xf0
Jan 20 04:15:12 xxx kernel: [32625.632357]  [<ffffffffc0c2824b>] ? zvol_task_cb+0x1fb/0x550 [zfs]
Jan 20 04:15:12 xxx kernel: [32625.632359]  [<ffffffffb1a0292b>] ? __schedule+0x23b/0x6d0
Jan 20 04:15:12 xxx kernel: [32625.632364]  [<ffffffffc0a7a2b6>] ? taskq_thread+0x286/0x460 [spl]
Jan 20 04:15:12 xxx kernel: [32625.632367]  [<ffffffffb14a10e0>] ? wake_up_q+0x70/0x70
Jan 20 04:15:12 xxx kernel: [32625.632372]  [<ffffffffc0a7a030>] ? task_done+0x90/0x90 [spl]
Jan 20 04:15:12 xxx kernel: [32625.632375]  [<ffffffffb1495ea7>] ? kthread+0xd7/0xf0
Jan 20 04:15:12 xxx kernel: [32625.632376]  [<ffffffffb1495dd0>] ? kthread_park+0x60/0x60
Jan 20 04:15:12 xxx kernel: [32625.632379]  [<ffffffffb1a07911>] ? ret_from_fork+0x41/0x50
```

**Comment by darrenfreeman** [comment]
Just looked at the failing drive with smartctl, this is the interesting line:

199 CRC_Error_Count         0x003e   085   085   000    Old_age   Always       -       14296

The identical, but non-failing, drive has a count of 0. Both are Samsung SSD 850 EVO 500GB.

**Comment by rincebrain** [comment]
@darrenfreeman That SMART attribute is for link errors; you may wish to try replacing the cable connected to the misbehaving drive.

Also, this is more of a support request and less of a bug, so you should probably use #zfsonlinux on Freenode or the zfs-discuss@ mailing list for questions like this.

**Comment by darrenfreeman** [comment]
I considered that it might turn out to be just a support issue.. but the kernel stack trace made me think there's something more going on. Since those are rarely good.

**Comment by darrenfreeman** [comment]
Have joined the zfs-discuss mailing list. Probably don't need any help with this, if you can confirm there's no evidence of a bug.
