### ISSUE TITLE
selinux messages, invalid context, relabel inode or filesystem in question?

### ISSUE THREAD

**Issue by array42** [openzfs/zfs#7073]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Fedora
Distribution Version    |  26
Linux Kernel                 |  4.14.11-200.fc26.x86_6
Architecture                 |  x86_64
ZFS Version                  |  0.7.5-1 (zfs, 0.7.5, 4.14.11-200.fc26.x86_64, x86_64: installed)
SPL Version                  |  0.7.5-1 (spl, 0.7.5, 4.14.11-200.fc26.x86_64, x86_64: installed)

### Describe the problem you're observing
setroubleshootd is running at 100% CPU
dmesg shows lots of messages like this, with different inodes and context messages, where context looks like file content or random bytes:
```
SELinux: inode=139911 on dev=zfs was found to have an invalid context=\xe9\xca\xd2\xcbx\x94U.  This indicates you may need to relabel the inode or the filesystem in question.
```
### Describe how to reproduce the problem
The machine had a power loss, then just imported the pool back after a reboot. These errors started to show up. Did not do anything special. At the moment there is a scrub running, also some files are being copied to the pool. So what action should be taken?
### Include any warning/errors/backtraces from the system logs

**Comment by dcrdev** [comment]
Have you tried:
```
sudo touch /.autorelabel && sudo reboot
```

?

**Comment by RiderExMachina** [comment]
> ```
> sudo touch /.autorelabel && sudo reboot
> ```

This topic was closed several years ago, but this ended up making a huge difference on my end. Thank you!
