### ISSUE TITLE
On recent kernels, zfs_zevent_console=1 outputs many spurious linefeeds

### ISSUE THREAD

**Issue by akorn** [openzfs/zfs#7082]
This is almost certainly due to the change explained in https://lwn.net/Articles/732420/ -- if you call `printk()` several times, each invocation will cause a new line to be written to dmesg unless you use `KERN_CONT`.

Supposedly, you should instead marshal your entire line into a single buffer and use `printk()` to print that.

**Comment by akorn** [comment]
(Incidentally, I also think `zfs_zevent_cols` is superfluous -- whatever you view the messages on can wrap them. I don't think there is need for pre-wrapping in kernelspace. I don't think this merits filing a new issue, but if fixing the `printk` usage is easier if you also drop `zfs_zevent_cols`, I think it'd be good riddance.)

**Comment by DeHackEd** [comment]
From IRC: https://pastebin.com/SbtYRcs1 for an example of broken output

**Comment by behlendorf** [comment]
@akorn thanks for letting us know.   I'm actually a little surprised anyone is enabling the console logging functionality and would be interested in how your using it.  This is functionality we've considering removing entirely.

**Comment by akorn** [comment]
I have a system not unlike `logcheck` that post-processes logfiles, and, based on regular expressions, discards all messages classified as "known benign". It sends me the others via email for review.

I'm sure it would be possible to set this up with `zed` somehow, but I had already been using it when `zed` was introduced (or when I first noticed `zed`, at any rate).

While it wouldn't be a terrible blow to lose `zfs_zevent_console`, I think it's useful to see these messages interleaved with other kernel events, in the same stream. Makes it easier to spot if other problems coincide with zfs events.

**Comment by akorn** [comment]
AFAIK the problem still persists, but since it made `zfs_zevent_console` pretty much useless I have stopped using it.

I think that knob should either go away as you, @behlendorf, suggested, or the output should be fixed.

**Comment by behlendorf** [comment]
I'd recommend we remove it.
