### ISSUE TITLE
utf8only property explicitly set but source is not local

### ISSUE THREAD

**Issue by fejesjoco** [openzfs/zfs#7092]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | buster
Linux Kernel                 | 4.14.0-3
Architecture                 | amd64
ZFS Version                  | 0.7.5-1
SPL Version                  | 0.7.5-1

### Describe the problem you're observing

I created my pool with: `zpool create -o ashift=12 -O atime=on -O relatime=on -O canmount=noauto -O mountpoint=/ -O utf8only=on -O devices=off ...`

`zpool get all` and `zfs get all` shows local for the manually set properties, except for utf8only. I expect utf8only to also show local.

```
root@hp:~# zfs get all rpool | grep "local\|utf8"
rpool  mountpoint            /                      local
rpool  atime                 on                     local
rpool  devices               off                    local
rpool  canmount              noauto                 local
rpool  utf8only              on                     -
rpool  relatime              on                     local
```

**Comment by DeHackEd** [comment]
Since this property can only be set at dataset creation time, the property isn't really "normal" in that sense. It's also not inheritable because that would suggest that changing a parent dataset's setting or moving this dataset to another location could change its value. It can't.

Whether it was set locally or inherited is largely irrelevant.

**Comment by fejesjoco** [comment]
You highlighted a new bug: it is actually inheritable. When I created sub-datasets, they inherited the utf8only=on setting. Just because it's read only, it would still make sense to show it as local/inheritable because that is exactly what's happening: I set it locally on the root dataset and it was inherited in child datasets.

**Comment by DeHackEd** [comment]
```
# zpool create tank ....
# zfs create tank/subfs1 -o utf8only=on
# zfs create tank/subfs1/subfs2
# zfs rename tank/subfs1/subfs2 tank/newtoplevel
# zfs get utf8only tank/newtoplevel
...
```
What should be displayed here? `utf8only` is not set "local" because it was not set on the dataset directly. It is not "inherited" because its parent, `tank`, does not have utf8only set. So, yeah, weird effect but it's also a weird property.

**Comment by fejesjoco** [comment]
I didn't consider reparenting datasets. So what happens is that ZFS sets utf8only based on the parent on creation, right? That means it should be local forever.
