### ISSUE TITLE
ZED should emit events for VDEVs on pool creation / destruction

### ISSUE THREAD

**Issue by jgrund** [openzfs/zfs#7106]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS Linux
Distribution Version    | 7 (Core)
Linux Kernel                 | 3.10.0-693.5.2
Architecture                 | x86_64
ZFS Version                  | 0.7.5-1
SPL Version                  | 0.7.5-1

### Describe the problem you're observing

When creating a zpool, there is currently no information emitted about it's VDEVs.

VDEV info *is* emitted on `statechange` events, when a VDEV moves from `ONLINE` to `FAULTED` for instance. It should also be emitted on pool create / destroy.

**Comment by behlendorf** [comment]
@jgrund can you please include your use case for why having these additional events would be useful.

**Comment by jgrund** [comment]
Hi, sure.

We are creating an event-based application that utilizes `ZED` to monitor pools / datasets.

In order to get a holistic picture (and to get state on application startup), we are using `libzfs` to fetch the vdev tree as well as some other props.

Having the tree exposed as events would be useful because it would be one less thing we'd need to query from libzfs; ideally we could consume and assemble the tree from the event stream instead.
