### ISSUE TITLE
Provide command to generate zpool.cache on demand

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#711]
Stale zpool.cache files are causing downstream headaches when booting off ZFS and instructions for generating new ones are convoluted at best. It would be useful if we had a command to refresh the zpool.cache file. It could be called `zpool refresh`.

**Comment by CMCDragonkai** [comment]
@behlendorf Is the zpool.cache file created during the `zpool create` command? Does the creation of this file require the `etc/zfs` directory to be created in the first place?

In NixOS, the `etc/zfs` directory doesn't exist in the first place, because `zfs` is installed into `/nix` directory.

**Comment by behlendorf** [comment]
@CMCDragonkai yes,the `/etc/zfs` directory needs to already exist and this is usually taken care of in the packaging.  If for whatever reason a different location is preferred for NixOS the patch can be overridded with the `spa_config_path` module option.

**Comment by CMCDragonkai** [comment]
You mean something like this:

```
echo "options zfs spa_config_path=" >> /etc/modprobe.d/zfs.conf
```

I read somewhere that if `spa_config_path` is set to false, there won't be a `zpool.cache` file. **Does this affect the operation of the `zdb` command?** Also the Slack wiki mentions to delete the `zpool.cache` file on shutdown.

> Remove /etc/zfs/zpool.cache on shutdown. This is recommended because if it is present when you import a pool, it might use this old cache to determine the device filenames in the pool, which may have changed filenames since the last boot, especially the non-persistent /dev/sd* device filenames. It is safest to avoid any usage of the zpool.cache file at boot in initramfs, zfs module load, and at zpool import of other pools. 
>
> http://slackwiki.com/ZFS_root
