### ISSUE TITLE
Mounting a dataset as read-only "alters" it and incremental snapshot receiving made impossible

### ISSUE THREAD

**Issue by sjau** [openzfs/zfs#7128]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Nixos
Distribution Version    |  Unstable
Linux Kernel                 |  4.14.14
Architecture                 |  Linux
ZFS Version                  |  1d53657bf561564162e2ad6449f80fa0140f1dd6
SPL Version                  |  23602fdb39e1254c669707ec9d2d0e6bcdbf1771

### Describe the problem you're observing

I have the following scenario:

In a small office with only a handful of people there's a need (quite regularly) to get old versions of some database (ms access) files. So this far I've been using rsync + hardlinking to create daily versions (if altered). Those rsynced data is stored on a seperate drive on the server and there's also 2 offsite backups as well. However, I'm still fairly new to ZFS (but use it a lot now), I want to change that to snapshots and incremental sending.

So I've been testing how to best set this up. My thoughts was to just mount this "backup" dataset as read-only. No write access needed. Since I mount it as read-only my thought of train was, that it can still receive incremental snapshots. However that seems not to be the case as it keeps telling me it has been altered.

So what I did then is mount that dataset as read-only, roll it back and try again an incremental send. This seems to work and new snapshots actually appear in the .zfs folder.

For me, mounting as read-only shouldn't alter the dataset so I wonder why there's such a behaviour? Also having it mounted, rolling back the snapshot wil being mounted as ro and then being able to receive new snapshots is somehwat a mystery to me as why it works (I'm glad it does work).

So is there bug that the dataset "advances" even when mounted as read-only?

### Describe how to reproduce the problem

```
root@subi:~# ssh root@10.200.0.2 "zfs send tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-12h00" | zfs receive tankSubi/encZFS/TEST
root@subi:~# mkdir /tmp/TEST
root@subi:~# mount -o ro -t zfs tankSubi/encZFS/TEST /tmp/TEST/
root@subi:~# cd /tmp/TEST
root@subi:/tmp/TEST# cd .zfs
root@subi:/tmp/TEST/.zfs# cd snapshot
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-05-12h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-12h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-13h00" | zfs receive tankSubi/encZFS/TEST
cannot receive incremental stream: destination tankSubi/encZFS/TEST has been modified since most recent snapshot
root@subi:/tmp/TEST/.zfs/snapshot# zfs rollback tankSubi/encZFS/TEST@zfs-auto-snap_hourly-2018-02-05-12h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-12h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-13h00" | zfs receive tankSubi/encZFS/TEST
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-05-12h00  zfs-auto-snap_hourly-2018-02-05-13h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-13h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-14h00" | zfs receive tankSubi/encZFS/TEST
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-05-12h00  zfs-auto-snap_hourly-2018-02-05-13h00  zfs-auto-snap_hourly-2018-02-05-14h00
root@subi:/tmp/TEST/.zfs/snapshot# 
```

So is this intended behaviour that mounting a dataset as read-only will alter/advance it so that a rollback is required before being able to receive an incremental snapshot?
Is it also intended behaviour that once it's mounted as read-only and rolled backup, that new snapshots will just show up in the .zfs folder without anew rollback?

**Comment by richardelling** [comment]
best practice is to keep the snapshots unmounted and use clones to access the data.

**Comment by kpande** [comment]
regardless of best practice isn't this a bug?

**Comment by loli10K** [comment]
> However that seems not to be the case as it keeps telling me it has been altered.

@sjau i may be missing something here, but i'm not finding this information in the output you pasted in the issue description.

I'm only seeing
```
WARNING: could not send tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-12h00:
incremental source (tankJL/Nixos@zfs-auto-snap_hourly-2018-02-05-12h00) is not earlier than it
```
which is a **zfs send** error, so not related to **receiving** "altered" datasets, and

```
cannot receive: failed to read from stream
```
which is only because the input stream being received is empty (due the first error).

**Comment by sjau** [comment]
Sorry, deleted the wrong lines... here again fresh:

```
root@subi:~# zfs list
NAME                    USED  AVAIL  REFER  MOUNTPOINT
tankSubi                790G   109G   120K  none
tankSubi/encZFS         790G   109G   184K  legacy
tankSubi/encZFS/Media   574G   109G   566G  legacy
tankSubi/encZFS/Nixos   114G   109G  95.9G  legacy
tankSubi/encZFS/VMs     102G   109G  99.2G  legacy
root@subi:~# rmdir /tmp/TEST
rmdir: failed to remove '/tmp/TEST': No such file or directory
root@subi:~# ssh root@10.200.0.2 "zfs send tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-12h00" | zfs receive tankSubi/encZFS/TEST
root@subi:~# mkdir /tmp/TEST
root@subi:~# mount -o ro -t zfs tankSubi/encZFS/TEST /tmp/TEST/
root@subi:~# cd /tmp/TEST
root@subi:/tmp/TEST# cd .zfs
root@subi:/tmp/TEST/.zfs# cd snapshot
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-08-12h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-12h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-13h00" | zfs receive tankSubi/encZFS/TEST
cannot receive incremental stream: destination tankSubi/encZFS/TEST has been modified
since most recent snapshot
root@subi:/tmp/TEST/.zfs/snapshot# zfs rollback tankSubi/encZFS/TEST@zfs-auto-snap_hourly-2018-02-08-12h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-12h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-13h00" | zfs receive tankSubi/encZFS/TEST
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-08-12h00  zfs-auto-snap_hourly-2018-02-08-13h00
root@subi:/tmp/TEST/.zfs/snapshot# ssh root@10.200.0.2 "zfs send -i tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-13h00 tankJL/Nixos@zfs-auto-snap_hourly-2018-02-08-14h00" | zfs receive tankSubi/encZFS/TEST
root@subi:/tmp/TEST/.zfs/snapshot# ls
zfs-auto-snap_hourly-2018-02-08-12h00  zfs-auto-snap_hourly-2018-02-08-13h00  zfs-auto-snap_hourly-2018-02-08-14h00
```

Still the problem exists. Feel free to try it yourself.

**Comment by loli10K** [comment]
> Still the problem exists. Feel free to try it yourself.

I'm not questioning the fact this can be reproduced, i was actually trying to, but the issue description was very misleading.

**Comment by pcd1193182** [comment]
I can reproduce this on other platforms as well (Specifically illumos):
```
root@pd-ssd:/export/home/delphix# zfs create perfpool/test
root@pd-ssd:/export/home/delphix# echo a > /perfpool/test/a
root@pd-ssd:/export/home/delphix# zfs snapshot perfpool/test@s1
root@pd-ssd:/export/home/delphix# echo b > /perfpool/test/a
root@pd-ssd:/export/home/delphix# zfs snapshot perfpool/test@s2
root@pd-ssd:/export/home/delphix# zfs send perfpool/test@s1 | zfs receive perfpool/recvfs
root@pd-ssd:/export/home/delphix# ls /perfpool/recvfs/
a
root@pd-ssd:/export/home/delphix# zfs umount perfpool/recvfs
root@pd-ssd:/export/home/delphix# zfs mount -o ro perfpool/recvfs
root@pd-ssd:/export/home/delphix# zfs send -i perfpool/test@s1 perfpool/test@s2 | zfs receive perfpool/recvfs
cannot receive incremental stream: destination perfpool/recvfs has been modified
since most recent snapshot
root@pd-ssd:/export/home/delphix# zfs umount perfpool/recvfs
root@pd-ssd:/export/home/delphix# zfs send -i perfpool/test@s1 perfpool/test@s2 | zfs receive perfpool/recvfs
cannot receive incremental stream: destination perfpool/recvfs has been modified
since most recent snapshot
root@pd-ssd:/export/home/delphix# zfs rollback perfpool/recvfs@s1
root@pd-ssd:/export/home/delphix# zfs send -i perfpool/test@s1 perfpool/test@s2 | zfs receive perfpool/recvfs
root@pd-ssd:/export/home/delphix#
```

**Comment by pcd1193182** [comment]
I think this bug used to exist in our operating system, but I think we fixed it at some point. Let me look around and see if I can find a record of it.

**Comment by pcd1193182** [comment]
Ok, I tried reproducing this on my ZoL box, and I haven't been able to do so. I also can't find any history of issues related to this in our OS; I may have been imagining it, or I may have not been looking hard enough.  I would suggest trying to gather more debugging information; if you can get it into the state where you can't receive an incremental, try `zfs snapshot tankSubi/encZFS/TEST@test` and then use `zfs diff` to compare that snapshot with the previous one. If it shows files that have been modified, that might help us track down what has been going on.

**Comment by loli10K** [comment]
> I think this bug used to exist in our operating system, but I think we fixed it at some point.

I tried reproducing this issue with commits prior to https://github.com/zfsonlinux/zfs/commit/6a2185660d000c99b14556c7eb1108c5609faf41 (_OpenZFS 8930 - zfs_zinactive: do not remove the node if the filesystem is readonly_) without success.

**Comment by loli10K** [comment]
Duplicate of https://github.com/zfsonlinux/zfs/issues/6741
