### ISSUE TITLE
zpool import panic: VERIFY(rs == NULL)

### ISSUE THREAD

**Issue by turrini** [openzfs/zfs#7157]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  SystemRescueCD
Distribution Version    |  5.1.2
Linux Kernel                 |  4.9.60
Architecture                 |  amd64
ZFS Version                  |  0.7.5
SPL Version                  |  0.7.5

### Describe the problem you're observing
Can't import pool, panic:
VERIFY(rs == NULL)
PANIC at range_tree.c:179:range_tree_add()

But I'm able to import it with readonly=on and zfs_recover=1

### Describe how to reproduce the problem
zpool import -f -N debian-38fda1 (and it hangs forever)

### Include any warning/errors/backtraces from the system logs

![photo_2018-02-10_10-08-18](https://user-images.githubusercontent.com/1717170/36062396-7bf41934-0e4a-11e8-9e78-9aba4025c4b5.jpg)

**Comment by bunder2015** [comment]
Can you try with the 0.7.6 iso?

**Comment by ptx0** [comment]
you have corrupt spacemaps probably from bad or simply non-ECC laptop memory, the delicate circuitry on the modules makes errors more likely. unfortunately you will need to rebuild the pool.

**Comment by bunder2015** [comment]
Please ignore my previous message, I'm afraid ptx0 is probably right.

https://github.com/zfsonlinux/zfs/issues/3210#issuecomment-84812008

**Comment by kelvinhammond** [comment]
I have this same error with ECC ram.
