### ISSUE TITLE
zfs_dbgmsg user-land issues

### ISSUE THREAD

**Issue by dweeezil** [openzfs/zfs#7162]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | All
Distribution Version    | Any
Linux Kernel                 | N/A
Architecture                 | N/A
ZFS Version                  | Post 3b36f8319d56842c85782e7842218a7499f3cf16 (maybe)
SPL Version                  | N/A
### Describe the problem you're observing
User-land output from zfs_dbgmsg() is ugly.

### Describe how to reproduce the problem
Run zdb or ztest with environment ZFS_DEBUG=on.

### Include any warning/errors/backtraces from the system logs
N/A

### Actual issue
Upstream OpenZFS has a pair of ```printf()```-like debugging facilities:
  - ```zfs_dbgmsg()``` generates the ```zfs__dbgmsg``` DTRACE probe and then stores the ```printf()```-formatted message in an in-memory buffer.
  - ```dprintf()``` generates the ```zfs__dprintf``` DTRACE probe with the ```printf()```-formatted message as part of the trace payload.

Both of these facilities are designed to be used in conjunction with illumos' ```mdb``` debugger.  In openzfs/openzfs@b4952e17e88, the ```zfs_dbgmsg_print()``` function was added to allow user-land (ztest) to display the contents of the in-memory buffer containing messages from ```zfs_dbgmsg()```.

Due to the lack of ```mdb``` or a suitable equivalent, these facilities have been implemented differently in ZoL but do not generate clean output in user-land.

In ZoL, both ```dprintf()``` and ```zfs_dbgmsg()``` map to ```__dprintf()```.  This is a problem in user-land because messages sent with ```zfs_dbgmsg()``` are not terminated with a newline whereas those sent by ```dprintf()``` are.  Somewhat unrelated, the upstream ```zfs_dbgmsg_print()``` function has no effect in ZoL because user-land never stores the messages in the in-memory buffer.

The most noticeable impact of this issue is that when running ```ztest``` with ```ZFS_DEBUG=on```, the messages generated by ```zfs_dbgmsg()``` will not be terminated by a newline and also there will be numerous superfluous ```ZFS_DBGMSG``` lines from ```zfs_dbgmsg_print()``` when it tries to dump the (empty) in-memory buffer.

This issue report is mainly a call for feedback from developers as to how this all really ought to work in ZoL.  I'm think is's perfectly reasonable that all the debugging is sent to stdout in user-land so there's no concerns about over-running an in-memory buffer.  However, the output (from ```ztest```) becomes intermixed with ztest's own output and there's also the issue of the missing newlines (see above).  For my own debugging, I work around the issue by modifying ```__dprintf()``` with this little hack:
```
diff --git a/lib/libzpool/kernel.c b/lib/libzpool/kernel.c
index 09e69ef..29b6170 100644
--- a/lib/libzpool/kernel.c
+++ b/lib/libzpool/kernel.c
@@ -758,6 +758,8 @@ __dprintf(const char *file, const char *func, int line, const char *fmt, ...)
                va_start(adx, fmt);
                (void) vprintf(fmt, adx);
                va_end(adx);
+               if (strchr(fmt, '\n') == NULL)
+                       (void) printf("\n");
                funlockfile(stdout);
        }
 }
```

**Comment by behlendorf** [comment]
Agreed, we should take some time and consider exactly how we want the logging to work under Linux.  

I put together a [WIP patch](https://github.com/behlendorf/zfs/commit/33bee587664e63cca2b6dc6d12b1cafb007e9426)  a while back in an attempt to cleanup some of the code in this area and make it more understandable.  It might act as a good starting point for this work, but it does not try to address the core issue.  Under Linux exactly what do we want the difference to be between `zfs_dbgmsg()` and `dprinf()`?  How should each behave in user and kernel space?  When should developers use one vs the other.

I know @ahrens has some good thoughts on what he expected the behavior to be but I'm unable to find them now.  Perhaps he wouldn't mind posting them again, since I do think this bit  cleanup is long overdue.

**Comment by ahrens** [comment]
The original intent (which is implemented on illumos) is that zfs_dbgmsg() is always captured, and dprintf() is almost never captured.  Specifically, dprintf() is not compiled on nondebug builds, and on debug builds it is compiled in but disabled by default, and can be enabled by changing a tunable (`zfs_flags`).

Tangential to your question, here are some general principles I recently wrote up for when to call zfs_dbgmsg():

1. We don't want to pollute the log with typically-irrelevant messages, so don't print too many messages in the "normal" code path - O(1) per txg.

2. We want to know for sure what happened, so make the message specific (e.g. *which* thing am I operating on).

3. Do print a message when something unusual or unexpected happens - e.g. error cases.

4. Print a message when making user-initiated on-disk changes.
