### ISSUE TITLE
"metadata is corrupted" 'fixed' by removing a Device file...

### ISSUE THREAD

**Issue by Celmor** [openzfs/zfs#7184]
### System information

Type                                | Version/Name
  ---                                  |     ---
Distribution Name       | Linux NixOS
Linux Kernel            | 4.9.77
Architecture            | x86_64
ZFS Version             | 0.7.0-1 (commit [4c46b99](https://github.com/zfsonlinux/zfs/commit/4c46b99d24a6e71b3c72462c11cb051d0930ad60))`*`
SPL Version             | 0.7.0-1 (commit [23602fd](https://github.com/zfsonlinux/spl/commit/23602fdb39e1254c669707ec9d2d0e6bcdbf1771))

`*` added patches to ZFS ([expression](https://paste.simplylinux.ch/view/2c94b9be)):
- [Mic92's patches updated for current zfs master](https://github.com/sjau/zfs/commit/72591199b36e4b4bddb6650717b5bb3121d508da.patch)
- [Stability patch #6864](https://patch-diff.githubusercontent.com/raw/zfsonlinux/zfs/pull/6864.patch)

SPL [expression](https://paste.simplylinux.ch/view/6206107b)/[patches](https://github.com/NixOS/nixpkgs/tree/master/pkgs/os-specific/linux/spl)

### Describe the problem you're observing
Wasn't able to import DataBackup pool because of "**metadata is corrupted**" with zpool suggesting "_Destroy and re-create the pool from a backup source_."

### Describe how to reproduce the problem
- Removing Device file for one of the disks of the mirrored vdev makes pool importable
- Commented '_#..._' out output relating to other pool
```
# uname -a
Linux nixos 4.9.77 #1-NixOS SMP Wed Jan 17 08:39:00 UTC 2018 x86_64 GNU/Linux

# zpool import -No readonly=on DataBackup
cannot import 'DataBackup': I/O error
	Destroy and re-create the pool from
	a backup source.

# zpool import
   pool: DataBackup
     id: 15297398777247163884
  state: FAULTED
 status: The pool metadata is corrupted.
 action: The pool cannot be imported due to damaged devices or data.
   see: http://zfsonlinux.org/msg/ZFS-8000-72
 config:

	DataBackup                                   FAULTED  corrupted data
	  mirror-0                                   ONLINE
	    ata-HGST_HDN724040ALE640_PK1338P4HVX34B  ONLINE
	    sdd                                      ONLINE
#...

# lsblk -f | grep zfs
#...                
├─sdc1 zfs_member  DataBackup 15297398777247163884                 
├─sdd1 zfs_member  DataBackup 15297398777247163884

# lsblk | grep $(basename $(readlink /dev/disk/by-id/ata-HGST_HDN724040ALE640_PK1338P4HVX34B))
sdc      8:32   0   3.7T  0 disk 
├─sdc1   8:33   0   3.7T  0 part 
└─sdc9   8:41   0     8M  0 part

# rm /dev/sdc1

# zpool import DataBackup

# zpool status DataBackup
  pool: DataBackup
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
	invalid.  Sufficient replicas exist for the pool to continue
	functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: resilvered 1.21T in 0 days 03:50:19 with 0 errors on Sat Jan 27 06:02:23 2018
config:

	NAME                     STATE     READ WRITE CKSUM
	DataBackup               DEGRADED     0     0     0
	  mirror-0               DEGRADED     0     0     0
	    6204277785589605098  UNAVAIL      0     0     0  was /dev/disk/by-id/ata-HGST_HDN724040ALE640_PK1338P4HVX34B-part1
	    sdd                  ONLINE       0     0     0

errors: No known data errors
```
Considering to run `partprobe /dev/sdc && zpool labelclear /dev/sdc1 && zpool replace DataBackup 6204277785589605098 /dev/sdc1` now to fix the data on the other disk, but not sure if these are the right commands yet (haven't received an answer on the irc channel so far), alternatively would dd the _good_ disk over the _bad_ disk.

**Comment by loli10K** [comment]
This will (hopefully) be fixed by https://github.com/openzfs/openzfs/commit/619c0123a513678d5824d6b1c4d7e8fad3c63e76 (_9075 Improve ZFS pool import/load process and corrupted pool recovery_) once it gets merged.

**Comment by Celmor** [comment]
Not sure but I might have overwritten `/dev/disk/by-id/ata-HGST_HDN724040ALE640_PK1338P4HVX34B-part1` with the same data as sdd at some point (have a 3rd disk from which I often duplicated a disk of DataBackup)
This is the zdb output for each disk:
```
# zdb -l  /dev/disk/by-id/ata-HGST_HDN724040ALE640_PK1338P4HVX34B-part1 | grep guid
    pool_guid: 15297398777247163884
    top_guid: 17479763665280800965
    guid: 7688493249387590645
        guid: 17479763665280800965
            guid: 6204277785589605098
            guid: 7688493249387590645
    pool_guid: 15297398777247163884
    top_guid: 17479763665280800965
    guid: 6204277785589605098
        guid: 17479763665280800965
            guid: 6204277785589605098
            guid: 7688493249387590645
# zdb -l /dev/sdd1 | grep guid
    pool_guid: 15297398777247163884
    top_guid: 17479763665280800965
    guid: 7688493249387590645
        guid: 17479763665280800965
            guid: 6204277785589605098
            guid: 7688493249387590645
```
Even if the disks contain the same data and zfs thinks one of them was the other disk of the mirrored vdev, it shouldn't say that the zpool is corrupt and I need to restore from backup if it still has a good disk.

**Comment by behlendorf** [comment]
This may be resolved in master by 6cb8e5306d9696d155ae7a808f56c4e46d69b64c, but I'm leaving it open until we can confirm or deny this.

**Comment by samuelxhu** [comment]
@behlendorf  Hi, Brian, I tried to cherry-pick 6cb8e53 to ZFS 0.7.12, but unfortunately failed as there are so many Hunk failures. It seems not an easy job to backport it to 0.7.12.

As being able to import a pool is extremely important in any case, could it possble for you to arrange an official backport this fix to 0.7.X, say potentially 0.7.13? That would be very benificial to all 0.7.X users.

thanks in advance for kind considerations

**Comment by samuelxhu** [comment]
Understood, thanks a lot for the clarification.

**Comment by samuelxhu** [comment]
Hope a pool exported by the final 0.8.0 version can be imported by 0.7.X as
well:-)
