### ISSUE TITLE
zfs-mount ignores noauto for zvols in fstab

### ISSUE THREAD

**Issue by gyakovlev** [openzfs/zfs#7374]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | gentoo
Distribution Version    | current
Linux Kernel                 | 4.15.14-gentoo
Architecture                 | x86_64
ZFS Version                  | 0.7.7-r0-gentoo
SPL Version                  | 0.7.7-r0-gentoo

### Describe the problem you're observing

zfs-mount initscript  ignores `noauto` mount option for zvols

At this point I'm unsure why zfs-mount tries to handle zvols? Is there any kind of use-case I'm missing?
As it seems pretty much every distro out there should have their own subset of scripts/tools what handle regular block device fstab mounts.

I see 2 ways of dealing with the situation:
1. Remove zvol handling altogether.  It's just regular block device and should be handled by existing toolset. It was around for decades and should handle all edge cases by now.
2. add an additional check for `noauto` field in fstab.

@loli10K mind if I ask for any comments on how will redhat6 handle it if we remove zvol handling from zfs-mount? will something else mount those volumes? my guess is yes, just want to confirm.

@everyoneelse any comments for other linux distros that use provided sysvinit scripts?

I only use gentoo, it will handle it just fine.

sidenote:
systemd services are fine atm.
every zvol fstab entry get's it's own service created by systemd-fstab-generator, and zfs-mount does not touch zvols at all.

### Describe how to reproduce the problem
User has the following line in /etc/fstab
```fstab
 # cat /etc/fstab
/dev/zvol/noauto/fs /noautofs any defaults,noauto 0 0	# should be filtered out but it's not
```

zfs-mount will mount it anyway

```sh
fsck "$dev" && mount "$mntpt"
```
All it takes to mount a filesystem marked with `noauto` is explicit mount call, exactly what initscript does.
### Include any warning/errors/backtraces from the system logs
```sh
 # cat /etc/fstab
/dev/zvol/noauto/fs /noautofs any ro,noauto 0 0	# should be filtered out but it's not
/dev/zd1 /noautofs any ro,noauto 0 0	# should be filtered out but it's not

 # set -x
 # read_fstab "^/dev/(zd|zvol)" #that's how zfs-mount runs it
+ read_fstab '^/dev/(zd|zvol)'
+ local 'match=^/dev/(zd|zvol)'
+ local i var TMPFILE
++ env
++ grep --colour=auto '^FSTAB_'
++ sed 's,=.*,,'
+ unset
+ i=0
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo /dev/zvol/noauto/fs
+ echo /noautofs
+ egrep --colour=auto -qE '^none|^swap'
+ egrep --colour=auto -qE '^swap'
+ echo any
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo '/dev/zvol/noauto/fs /noautofs any ro,noauto 0 0	# should be filtered out but it'\''s not'
+ eval export FSTAB_dev_0=/dev/zvol/noauto/fs
++ export FSTAB_dev_0=/dev/zvol/noauto/fs
++ FSTAB_dev_0=/dev/zvol/noauto/fs
++ printf '%b\n' /dev/zvol/noauto/fs
++ sed s,/,_,g
+ fs=_dev_zvol_noauto_fs
+ eval export FSTAB_0=/noautofs
++ export FSTAB_0=/noautofs
++ FSTAB_0=/noautofs
+ i=1
+ read -r fs mntpnt fstype opts
+ egrep --colour=auto -qE '^#|^$'
+ echo /dev/zd1
+ egrep --colour=auto -qE '^none|^swap'
+ echo /noautofs
+ egrep --colour=auto -qE '^swap'
+ echo any
+ grep --colour=auto -qE '^/dev/(zd|zvol)'
+ echo '/dev/zd1 /noautofs any defaults,noauto 0 0	# should be filtered out but it'\''s not'
+ eval export FSTAB_dev_1=/dev/zd1
++ export FSTAB_dev_1=/dev/zd1
++ FSTAB_dev_1=/dev/zd1
++ printf '%b\n' /dev/zd1
++ sed s,/,_,g
+ fs=_dev_zd1
+ eval export FSTAB_1=/noautofs
++ export FSTAB_1=/noautofs
++ FSTAB_1=/noautofs
+ i=2
+ read -r fs mntpnt fstype opts

 # env | grep FSTAB
FSTAB_1=/noautofs
FSTAB_0=/noautofs
FSTAB_dev_1=/dev/zd1
FSTAB_dev_0=/dev/zvol/noauto/fs
```

**Comment by gyakovlev** [comment]
taking closer look it seems that there are even more issues:
1. `mountpoint=legacy` datasets are mounted regardless of `canmount=noauto`
2. `mountpoint=legacy` datasets are mounted regardless of fstab `noauto`
3. `fsck` being run for zvols regardless of fstab settings.

**Comment by omnivagant** [comment]
Still a number of issues here. I found that `zfs-mount` doesn't respect the sixth field in fstab entries being 0 or empty (which defaults to 0) and runs `fsck` anyway.
