### ISSUE TITLE
Replacing drive in a pool with multipath | EDIT: can offline and replace with non mpath disk; must export/import to reenable multipath

### ISSUE THREAD

**Issue by johnr14** [openzfs/zfs#7413]
### System information

Distribution Name       |   Proxmox 5.1 testing
Distribution Version     |  Debian 9.4 stretch
Linux Kernel                |  4.13.16-1-pve
Architecture                 |  x86_64
ZFS Version                |  v0.7.7-1
SPL Version                |  v0.7.7-1

### Describe the problem you're observing

I want to replace a drive with an other one in a pool that is online and that has multipath enabled.

_I believe that it would work if I export the pool, flush multipath, reload the pool with normal /dev/sdX device and replace the drive._ Then re-export the pool, reload multipath and re-import the pool.

However, that's not really a good option if the pool is beeing used as it's a long downtime.

The other way would be to do as cousins commented on 30 Mar 2015 on #3215 and offline the drive prior to replacing, but also not working.

The pool is as follow : 
```
        NAME        STATE     READ WRITE CKSUM
	Apool       ONLINE       0     0     0
	  raidz2-0  ONLINE       0     0     0
	    mpathr  ONLINE       0     0     0
	    mpathq  ONLINE       0     0     0
	    mpathu  ONLINE       0     0     0
	    mpathv  ONLINE       0     0     0
	    mpathw  ONLINE       0     0     0  -> /dev/sdf to /dev/mapper/mpaths or /dev/sdh
	    mpatht  ONLINE       0     0     0
```

The drive that is to be replaced is : 
```
#multipath -ll /dev/sdf
mpathw (35000cca3b7cb3d84) dm-14 ATA,WDC WD80EZZX-11C
size=7.3T features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  |- 0:0:2:0  sdf  8:80   active ready  running
  `- 0:0:19:0 sdv  65:80  active ready  running
```

### Describe how to reproduce the problem
```
#zpool replace Apool mpathw mpaths
cannot open '/dev/mapper/mpaths': Device or resource busy
cannot replace mpathw with mpaths: no such device in pool

#zpool replace Apool sdf sdh -f
/dev/sdh is in use and contains a unknown filesystem.

#multipath -f /dev/mapper/mpaths

#zpool replace Apool sdf sdh 
cannot replace sdf with sdh: no such device in pool

#zpool replace Apool mpathw sdh 
cannot replace mpathw with sdh: no such device in pool

#zpool offline Apool mpathw 
cannot offline mpathw: no such device in pool

#zpool offline Apool sdf
cannot offline sdf: no such device in pool
```

### Include any warning/errors/backtraces from the system logs

No system logs errors.

**Comment by danielewood** [comment]
Here are my notes from dealing with multipath a few months ago for the first time and replacing a drive. There are/were many things wrong with this system, like completely missing multipath.conf.

These notes should get your mpaths device in a usable state for import.


Replace failed disk:
1. Physically remove disk
2. Find failed multipath disk:
```
[root@jupiter ~]# multipath -ll
A14 (350014ee000000474) dm-30 WD,WD2001FYYG-01SL3
size=1.8T features='0' hwhandler='0' wp=rw
`-+- policy='round-robin 0' prio=1 status=active
  |- #:#:#:#  -   #:#    failed faulty running
  `- #:#:#:#  -   #:#    failed faulty running
```
3. Remove multipath disk:
```
[root@jupiter ~]# multipath -F
<CTRL+C as it will just hang forever>
[root@jupiter ~]# multipath -F
```
4. Physically insert new disk (record WWN from drive label first).
5. Add the WWN to /etc/multipath.conf as a new alias (WWN can be found on physical disk label, for WD disks, add a 3 to the beginning)
```
multipaths {
        multipath {
        wwid   "350014e0000000d97"
        alias  "A14"
        }
}
```
6. reload multipath service (only reloads config and rescans, will not interrupt live systems)
```
[root@jupiter ~]# service multipathd reload
[root@jupiter ~]# multipath -v2
[root@jupiter ~]# multipath -ll A14
A14 (350014e0000000d97) dm-30 WD,WD2001FYYG-01SL3
size=1.8T features='0' hwhandler='0' wp=rw
`-+- policy='round-robin 0' prio=1 status=active
  |- 6:0:18:0 sdq  65:0   active ready running
  `- 7:0:40:0 sdbo 68:32  active ready running
```

**Comment by tonyhutter** [comment]
```
> #zpool replace Apool mpathw mpaths
> cannot open '/dev/mapper/mpaths': Device or resource busy
> cannot replace mpathw with mpaths: no such device in pool
```
This should have worked, assuming `mpaths` was just a blank disk that wasn't being used for anything.  In your case it looks like something was using the disk.

**Comment by johnr14** [comment]
Ok, great I am testing your ideas.
@danielewood I have the drive already in.

So I made a more friendly multipath.conf
but I can't flush the mpath of a drive already in the pool. Also, I can't offline it to change the mapper.

```
#zpool offline Apool /dev/mapper/WD8TB-2
#zpool offline Apool WD8TB-2
#zpool offline Apool /dev/sdar
cannot offline DRIVE: no such device in pool
```
```
multipath -ll WD8TB-2
archive-5 (35000cca3b7cb3d84) dm-24 ATA,WDC WD80EZZX-11C
size=7.3T features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
`-+- policy='round-robin 0' prio=1 status=active
  |- 0:0:33:0 sdar 66:176 active ready running
  `- 0:0:44:0 sdbb 67:80  active ready running
```

Just saw #2276 and I tried to offline the drive with guid and it worked !

```
#zpool offline Apool 16652179745355271605
Apool          DEGRADED     0     0     0
	  raidz2-0     DEGRADED     0     0     0
	    archive-1  ONLINE       0     0     0
	    archive-2  ONLINE       0     0     0
	    archive-3  ONLINE       0     0     0
	    archive-4  ONLINE       0     0     0
	    WD8TB-2    OFFLINE      0     0     0
	    WD8TB-1    ONLINE       0     0     0
```
However, **I still can't attach a new mapped device** : 
```
#zpool replace Apool 16652179745355271605 /dev/mapper/archive-5
cannot open '/dev/mapper/archive-5': Device or resource busy
cannot replace 16652179745355271605 with /dev/mapper/archive-5: /dev/mapper/archive-5 is busy
```
But if I flush multipath on device archive-5, it will work. @tonyhutter I don't get errors while flushing the drive, so I suppose only multipath daemon was using it, but it prevents zpool from using it ?
```
#multipath -f archive-5
#zpool replace Apool 16652179745355271605 /dev/sdw
```
Now it is replacing !
```
# zpool status
  pool: Apool
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Fri Apr 13 15:17:21 2018
	16.0G scanned out of 32.5T at 335M/s, 28h16m to go
	2.67G resilvered, 0.05% done
config:

	NAME             STATE     READ WRITE CKSUM
	Apool            DEGRADED     0     0     0
	  raidz2-0       DEGRADED     0     0     0
	    archive-1    ONLINE       0     0     0
	    archive-2    ONLINE       0     0     0
	    archive-3    ONLINE       0     0     0
	    archive-4    ONLINE       0     0     0
	    replacing-4  DEGRADED     0     0     0
	      WD8TB-2    OFFLINE      0     0     0
	      sdw        ONLINE       0     0     0  (resilvering)
	    WD8TB-1      ONLINE   
```

I still have to export then reload multipath and after that reimport the pool to re-enable multipath. Also I could online the WD8TB-2 with the guid.

```
#zpool online Apool 16652179745355271605
#zpool export Apool
#multipath -r
#zpool import -d /dev/mapper Apool
#zpool status Apool
Apool            ONLINE       0     0     0
	  raidz2-0       ONLINE       0     0     0
	    archive-1    ONLINE       0     0     0
	    archive-2    ONLINE       0     0     0
	    archive-3    ONLINE       0     0     0
	    archive-4    ONLINE       0     0     0
	    replacing-4  ONLINE       0     0     0
	      WD8TB-2    ONLINE       0     0     0
	      archive-5  ONLINE       0     0     0  (resilvering)
	    WD8TB-1      ONLINE       0     0     0
```
So I don't believe I can replace a drive with multipath without exporting the pool. 
Looks like this is a continuation of #2276.

**Comment by danielewood** [comment]
Glad I could help you at least get your multi-path mapper in a sane state.

Here is a more complete version for my /etc/multipath.conf in case it helps someone else:
```
blacklist {
        wwid "1ATA     WDC WD800AAJS-00PSA0                         WD-WCAPA0287748"
        wwid "1ATA     WDC WD800AAJS-00PSA0                         WD-WCAPC0160383"
        devnode "^sda$"
        devnode "^sdb$"
        devnode "^sdc$"
}
defaults {
        path_grouping_policy    multibus
        user_friendly_names     yes
}
multipaths {
        multipath {
                wwid                    ".*"
                path_grouping_policy    multibus
        }
        multipath {
                wwid   "350014aaaaaaaaaa0c"
                alias  "A1"
        }
        multipath {
                wwid   "350014aaaaaaaaa030"
                alias  "A2"
        }
        multipath {
                wwid   "350014bbbbbbbba0c"
                alias  "B1"
        }
        multipath {
                wwid   "350014bbbbbbbb030"
                alias  "B2"
        }

```

I need more testing when I have another drive die, but I think the better route to go on my blacklist is to blacklist everything and rely 100% on manual assignments. Because if your system boot drives are in a mdadm mirror and multipath picks one up when you insert the new replacement, you're gonna have a fun time figuring out that multipath is the problem the first time it happens.

**Comment by johnr14** [comment]
I am trying myself at looking at the code to help fix this problem.
There is a reference to multipath in : `lib/libzfs/libzfs_import.c`
_For multipath nodes use the persistent uuid based identifier_
so I tried : 
`zpool add Apool spare /dev/disk/by-id/dm-uuid-mpath-35000cca3b7cb3d84 `
but it didn't work.

Also I found this : 
```
         /*
         * Normal disks use ID_PATH for their physical path.  Device mapper
         * devices are virtual and don't have a physical path.  For them we
         * use ID_VDEV instead, which is setup via the /etc/vdev_id.conf file.
         * ID_VDEV provides a persistent path to a virtual device.  If you
         * don't have vdev_id.conf setup, you cannot use multipath autoreplace.
         */
```
**So if vdev_id.conf where to be configurated, it would work ?**
Is it the channels or the alias that needs to be configured ?
I think that ZFS should resolve multipath disk and add an entry to vdev_id.conf if that's the only thing missing.

**Comment by johnr14** [comment]
Also, I had errors on a drive in my multipath pool. I could not re-online the drive to resilver/scrub. 
I offlined the pool, removed multipath and when reimporting the pool, resilver started. With multipath it didn't work no mater what I tried.
