### ISSUE TITLE
dnf/yum reinstall of dkms rpms removes dkms config

### ISSUE THREAD

**Issue by dioni21** [openzfs/zfs#7457]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Fedora
Distribution Version    | 27
Linux Kernel                 | 4.15.16-300.fc27.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.8
SPL Version                  | 0.7.8

### Describe the problem you're observing
When we issue a reinstall, dkms rpms delete installed data.

### Describe how to reproduce the problem
dkms status
dnf reinstall zfs-dkms spl-dkms
dkms status

### What I would expect?
To fix any dkms damage, instead of having to do all of it manually (dkms uninstall, dkms add, dkms install, etc.)

**Comment by c3d** [comment]
Same with F28 and 0.7.9

**Comment by c3d** [comment]
I am no longer trying with the Fedora packages. I tend to build manually whenever Fedora installs the latest kernel. In general, I find the source build to work well, but the `dnf` package were causing more problem than they were solving. I'll retry when I have five minutes, and re-open if I see the problem on F33.
