### ISSUE TITLE
ZFS loses physical block drive on rsync and nfs-mount sporadically

### ISSUE THREAD

**Issue by TitusLabienus** [openzfs/zfs#7511]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  ArchLinux
Distribution Version    | 
Linux Kernel                 | 4.16
Architecture                 | 
[NfsMount.log](https://github.com/zfsonlinux/zfs/files/1976962/NfsMount.log)
x64
ZFS Version                  | 0.7.8
SPL Version                  | 0.7.8

### Describe the problem you're observing
Upon performing particular operations, ZFS loses the physical drive sporadically. lsblk then still shows the zvols, but the physical block volume is gone (eg. /dev/sdb is missing).  ZFS and the block drive remain unusable/inaccessible until reboot.

### Describe how to reproduce the problem
` # via rsync from- and to ZFS folders`
`rsync -va --remove-source-files --progress <NonZfsFolderSrc> <ZfsFolderDst>`
`# or by NFS sharing a nested ZFS folder`
`mount <IP>:<ZfsRootDataset> <Mountpoint>`

Reproducibility: rsync: ~30min-2h NFS: 1-10min

### Include any warning/errors/backtraces from the system logs

[NfsMount.log](https://github.com/zfsonlinux/zfs/files/1976977/NfsMount.log)

**Comment by rincebrain** [comment]
Assuming the pool is 'ZfsRed':
```
Mai 01 17:13:36 vbm-pc kernel: WARNING: Pool 'ZfsRed' has encountered an uncorrectable I/O failure and has been suspended.
Mai 01 17:13:37 vbm-pc kernel: WARNING: Pool 'ZfsRed' has encountered an uncorrectable I/O failure and has been suspended.
```

So as it says, no IO to the pool is going to succeed until whatever's causing it to suspend is resolved.

What does `zpool get all` on the pool say when it's working normally?

**Comment by albionxy** [comment]
Yes it is the ZfsRed pool. Here is the zpool get all:
[ZfsRedGetAll.txt](https://github.com/zfsonlinux/zfs/files/1977255/ZfsRedGetAll.txt)
