### ISSUE TITLE
Pool imported and exported by zfsonlinux is no longer readable by Solaris

### ISSUE THREAD

**Issue by likan999** [openzfs/zfs#7552]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| Fedora release 28 (Twenty Eight)
Linux Kernel	| 4.16.8-300.fc28.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.9-1
SPL Version	| 0.7.9-1

### Describe the problem you're observing
I created a zpool in Solaris 11.3 and exported it. The I imported on linux and then exported it. Then I want to import into Solaris 11.3 again but it failed.

### Describe how to reproduce the problem
```
# First create the zpool on Solaris:
hidden$ sudo uname -a
SunOS solaris-server 5.11 11.3 i86pc i386 i86pc

hidden$ sudo zpool create -o version=28 -o autoexpand=on -O version=5 raid-5x1.5T raidz c8t1d0 c8t2d0 c8t3d0 c8t4d0 c8t5d0

# Then export it
hidden$ sudo zpool export raid-5x1.5T

# Now go to Linux and import it and then export it
hidden$ uname -a
Linux <redacted> 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

hidden$ sudo zpool import raid-5x1.5T
hidden$ zpool status -v
  pool: raid-5x1.5T
 state: ONLINE
status: The pool is formatted using a legacy on-disk format.  The pool can
	still be used, but some features are unavailable.
action: Upgrade the pool using 'zpool upgrade'.  Once this is done, the
	pool will no longer be accessible on software that does not support
	feature flags.
  scan: none requested
config:

	NAME         STATE     READ WRITE CKSUM
	raid-5x1.5T  ONLINE       0     0     0
	  raidz1-0   ONLINE       0     0     0
	    sdc      ONLINE       0     0     0
	    sdd      ONLINE       0     0     0
	    sdg      ONLINE       0     0     0
	    sdf      ONLINE       0     0     0
	    sde      ONLINE       0     0     0

errors: No known data errors

hidden$ sudo zpool export raid-5x1.5T


# Now go back to Solaris and try to import it

hidden$ sudo zpool import -f
  pool: raid-5x1.5T
    id: <redacted>
 state: UNAVAIL
status: Some critical pool data has been overwritten by another pool.
action: The pool cannot be imported as critical data is missing. You
        can try using -f to force an import, but there may not be
        enough data to override this.
config:

        raid-5x1.5T  UNAVAIL  overwritten by another pool
          raidz1-0   ONLINE
            c8t1d0   ONLINE
            c8t2d0   ONLINE
            c8t3d0   ONLINE
            c8t4d0   ONLINE
            c8t5d0   ONLINE

device details:

```

**Comment by richardelling** [comment]
This is not expected to work. There is a bug fix in Solaris 11 on-disk pool format 28 that is not compatible with the open source format 28. This fix occurred after the OpenSolaris code was closed by Oracle. Please file a bug with Oracle as the open source community is not in a position to fix.

**Comment by likan999** [comment]
@richardelling So if I use version 27 should I expect it to work?

**Comment by likan999** [comment]
@richardelling I tested it doesn't work for version 27 as well. Which version do you think I should use instead?

**Comment by richardelling** [comment]
Ask Oracle

**Comment by ahrens** [comment]
@likan999 I'm guessing you do not have the same problem going from/to illumos?  How about from/to older versions of Solaris?  And how about with older versions of ZoL?

While it's possible that Oracle has done something "sneaky" with the on-disk format (as Richard implies), this is a surprising way for that to manifest.  It's also possible that ZoL is silently upgrading some aspect of the on-disk format even with using version=27/28.  That would be a bug in ZoL which we would want to investigate.

All that said, it would be really helpful if you could get Oracle to tell you how exactly they determine that it's been `overwritten by another pool` (that logic must be specific to Oracle).
