### ISSUE TITLE
spl_kmem strdup(...) conflicts with libc strdup(...) when built into ARCH=um kernel

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#7588]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| any
Distribution Version	| any
Linux Kernel	| any
Architecture	| any
ZFS Version	| any
SPL Version	| any

### Describe the problem you're observing

Migrated from zfsonlinux/spl#650.
Initial PR in #6633

@DHowett said:

The definition and export of strdup from the SPL conflicts with the use of libc strdup in `arch/um`.
As a result, when in-arch consumers seek to allocate string copies on the host heap they end up calling through to kmalloc, or the zfs module attempts to allocate/free on the host heap. This causes crashes on boot and interaction with the ZFS module.

Remediations:
* Replace the use of strdup/strfree in ZFS+SPL with `kstrdup(..., GFP_KERNEL)` and `kfree`. This is likely untenable, as there are a lot of these.
* Replace or scope the use of strdup+free in `arch/um`. This is probably also untenable as upstream kernel maintainers might be somewhat offended that another in-tree build might want to stomp the name `strdup`.

---

@behlendorf said:

These function really should never have been added to the SPL let alone exported.  Let's remove `strdup` and `strfree` from the SPL entirely and convert all existing ZFS consumers to `spa_strdup()` and `spa_strfree()` which already exist and won't cause a namespace conflict.  The few SPL consumers there are can be converted to directly call the `k*` kernel functions.

**Comment by ahrens** [comment]
If you end up chruning a ton of code for this, you might consider also  renaming it from `spa_strdup` to `zfs_strdup`, since this is not spa-specific.
