### ISSUE TITLE
dkms build with debug fails on sparc64

### ISSUE THREAD

**Issue by cross** [openzfs/zfs#7599]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| buster/sid
Linux Kernel	| 4.16.0-1-sparc64-smp
Architecture	| sparc64
ZFS Version	| 0.7.9-3
SPL Version	| 0.7.9-3

### Describe the problem you're observing

When building dkms with debug (setting ZFS_DKMS_ENABLE_DEBUG=yes in /etc/default/zfs), -Werror causes build to fail.

### Describe how to reproduce the problem

Modify /etc/default/zfs to set ZFS_DKMS_ENABLE_DEBUG=yes, and run "dkms build -m zfs/0.7.9". It is presumed that you would need to be on a sparc/sparc64 to see this, but not confirmed by testing on i386/x86_64.

### Include any warning/errors/backtraces from the system logs

Attached is the `/var/lib/dkms/zfs/0.7.9/build/make.log` after the failed build.

[make.log](https://github.com/zfsonlinux/zfs/files/2065665/make.log)

**Comment by jehos** [comment]
same, If I use `ZFS_DKMS_ENABLE_DEBUG=yes`, 

`warning: this statement may fall through [-Wimplicit-fallthrough=]` is changed to `error: this statement may fall through [-Werror=implicit-fallthrough=]` and the compile fails.

**Comment by jehos** [comment]
I think that is problem..

https://github.com/zfsonlinux/zfs/blob/master/config/zfs-build.m4#L9

```
AC_DEFUN([ZFS_AC_DEBUG_ENABLE], [
	DEBUG_CFLAGS="-Werror"
	DEBUG_CPPFLAGS="-DDEBUG -UNDEBUG"
	DEBUG_LDFLAGS=""
	DEBUG_ZFS="_with_debug"
	AC_DEFINE(ZFS_DEBUG, 1, [zfs debugging enabled])

	KERNEL_DEBUG_CFLAGS="-Werror"
	KERNEL_DEBUG_CPPFLAGS="-DDEBUG -UNDEBUG"
])
```

**Comment by behlendorf** [comment]
@jehos that would explain it.  It looks like the compiler on sparc64 is generating some additional warnings.  Most of these warnings were already addressed in master and could be backported.

If possible would you mind trying to build the latest version from github and see if there are still warnings which haven't been addressed.  Unfortunately, we don't have a sparc64 system setup for testing.
