### ISSUE TITLE
Debian stretch ignore parameters in /etc/defaults/zfs

### ISSUE THREAD

**Issue by colttt** [openzfs/zfs#7627]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Stretch
Linux Kernel	| 4.9.0-6
Architecture	| amd64
ZFS Version	| 0.6.5.9-5
SPL Version	| 0.6.5.9-1

### Describe the problem you're observing
If I set "ZFS_MOUNT='no'" in the /etc/defaults/zfs but it will be still mounted during boot time. Thats quite annoying if you want to run this in a cluster environment.

### Describe how to reproduce the problem
see above

```
/etc/default/zfs:
ZFS_MOUNT='no'
ZFS_UNMOUNT='yes'
ZFS_SHARE='yes'
ZFS_UNSHARE='yes'
ZPOOL_IMPORT_ALL_VISIBLE='no'
VERBOSE_MOUNT='no'
DO_OVERLAY_MOUNTS='no'
ZPOOL_IMPORT_OPTS=""
MOUNT_EXTRA_OPTIONS=""
ZFS_DKMS_ENABLE_DEBUG='no'
ZFS_DKMS_ENABLE_DEBUG_DMU_TX='no'
ZFS_DKMS_DISABLE_STRIP='no'
ZFS_INITRD_PRE_MOUNTROOT_SLEEP='0'
ZFS_INITRD_POST_MODPROBE_SLEEP='0'
```

**Comment by gmelikov** [comment]
Please try 0.7 release from stretch backports, it may be fixed in reworked ZED.

**Comment by colttt** [comment]
Hi @gmelikov,
I'm not an expert but when I grep for "ZFS_MOUNT", I found this in /etc/defaults and /etc/zfs/zfs-functions, I searched also in this git-repo for this and found it only in zfs/etc/init.d/zfs-mount.in, but Debian Stretch use systemd instead of sys-v-init, also for the zfs things. For me it looks like that the variable _ZFS_MOUNT_ is not used anymore?!

**Comment by beren12** [comment]
You can still use sysvinit but we're waiting on debian to merge the patch to install the init files with later releases. feel free to chime in on the bug asking them to get off their asses and merge it :-)

**Comment by colttt** [comment]
with 0.7 from the backports it's the same :(

**Comment by GregorKopka** [comment]
@colttt With systemd you'll have zfs-import-cache.service import all pools in zpool.cache and zfs-mount.service mount the filesystems in them. Should you also have zfs-import-scan.service active it'll import/mount any other pools it finds. 

Disable what you don't want, in case you 'cluster' (have the physical drives accessible from multiple machines) your problem most likely isn't mounting filesystem(s) but the import of the pool(s).

**Comment by richardelling** [comment]
For cluster environments, where the pool is only imported on one node at a time, you need to use the pool `cachefile` parameter. For most cluster configs, the cachefile is managed by the cluster software and not a default init script (for obvious reasons)

**Comment by aerusso** [comment]
I wrote this in another bug report, but it really should be here: `/etc/default/zfs` is used inconsistently. Debian downstream needs to ship this file because the initramfs system uses it, but the file doesn't explain that part of it only applies to sysv init scripts. The documentation should reflect that. 

There are other options in this file that maybe should be supported by systemd init scripts
So, the question we need to answer is: which of these parameters are specifically only supported by sysv init? Those should be labeled clearly. The others should be supported with an `EnvironmentFile` directive in the systemd units.
