### ISSUE TITLE
improve documentation of zpool import -d/-c vs -s

### ISSUE THREAD

**Issue by woquflux** [openzfs/zfs#7656]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Redhat
Distribution Version	| 7.4
Linux Kernel	| 3.10.0-327.el7.x86_64
Architecture	| 
ZFS Version	| 0.7.5-1
SPL Version	| 0.7.5-1

### Describe the problem you're observing
![image](https://user-images.githubusercontent.com/30719174/41887784-c6482944-7934-11e8-97cc-7447a4e668f1.png)

According to the description of the document. `zpool import` and `zpool import -d /dev/`should be the same

But...

![image](https://user-images.githubusercontent.com/30719174/41887875-4213602a-7935-11e8-9e67-7e996ed015e8.png)

**Comment by richardelling** [comment]
This is a documentation bug (deficiency).

What has happened in this case is likely due to partitioning and a remnant label set. There really isn't  a perfect general-case solution for all Linux distros and the procedure to recover is the same regardless of the remnants.

**Comment by GregorKopka** [comment]
In case it would only be a partitioning/remnant label set issue I would expect the faulted pool to also show up without the _-d /dev_, but it dosn't.

Seeing that -d seemingly triggers something additional (to, in this case, not looking in /dev but in /dev) in the zfs import procedure makes me a bit nervous (as most of my systems use -d and history taught me that unknown sideeffects tend to come up and bite, hard, later).

What _exactly_ is the deficiency in the documentation?

**Comment by GregorKopka** [comment]
@behlendorf Am I correct to interprete the gist of your comment as 'for zpool import -d implies -s' ?
