### ISSUE TITLE
ZFS Shares not exported until sharenfs property re-set

### ISSUE THREAD

**Issue by jgruiz75** [openzfs/zfs#7692]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  16.04LTS
Linux Kernel	|  4.4.0-130-generic
Architecture	|  x64
ZFS Version	|   0.6.5.6-0ubuntu20
SPL Version	|  0.6.5.6-0ubuntu4

### Describe the problem you're observing
 I have set up ZFS and NFS using ZFS shares as described in https://pthree.org/2012/12/31/zfs-administration-part-xv-iscsi-nfs-and-samba/. As you can see in my log below, although I have set zfs-share to run zfs share -a during boot, the shares are still not exported. Even weirder, is that  zfs share -a still doesn't when I manually run it. I can only get zfs shares to work if I reset the sharenfs property of one of the shares and then re-run zfs share -a. See below
```
$ showmount -e
Export list for apu:
/mnt localhost
$ sudo zfs share -a
$ showmount -e
Export list for apu:
/mnt localhost
$ sudo zfs share pool1
cannot share 'pool1': filesystem already shared
$ sudo zfs get sharenfs pool1
NAME   PROPERTY  VALUE     SOURCE
pool1  sharenfs  on        local
$ sudo zfs set sharenfs=on pool1
$ showmount -e
Export list for apu:
/s/apu/a/homes *
/s/apu/a       *
/s/apu/a/sys   *
/mnt           localhost
$ sudo zfs share -a
$ showmount -e
Export list for apu:
/s/apu/b       *
/s/apu/a/homes *
/s/apu/a       *
/s/apu/a/sys   *
/s/apu/b/cwc   *
/mnt           localhost
```
### Describe how to reproduce the problem
Problem happens after every reboot

**Comment by cherrot** [comment]
I use zfs `0.7.11-2` on my ArchLinux and I have a similar problem. ( In my case `zfs share -a` seems like an useless command.)

When I boot my computer,  there is no exported NFS volume:
```
showmount -e
Export list for cherrotNAS:
```

And `zfs share -a` gives no help.

I have to re-run `zfs set sharenfs=on MYPOOL` manually to enable NFS:

```
zfs set sharenfs=on data
showmount -e
Export list for cherrotNAS:
/data *
```
