### ISSUE TITLE
zfs-0.7.x receive fails with "invalid backup stream" while zfs-0.6.x.y succeeds

### ISSUE THREAD

**Issue by pk1234** [openzfs/zfs#7726]
We are sending zfs data streams from lots of machines to our backup server. This worked perfectly for a long time until we upgraded our backup server from linux 4.4.80 / zfs-0.6.5.9 to linux 4.4.116 / zfs-0.7.6

Data streams that were produced on Sun servers running Sollaris 10 (last free version) cannot be loaded anymore.

I was able to reproduce the problem with an absolute minimalistic pool that I created on one of our Solaris 10 machines with the following commands:
```
dd if=/dev/zero bs=1024k count=64 >/tmp/64MB
zpool create Z_TEST /tmp/64MB
touch /Z_TEST/`date +%d.%m.%Y-%H:%M:%S`
zfs snapshot Z_TEST@snap1
zfs send -R Z_TEST@snap1 >/tmp/Z_TEST.stream
zpool destroy Z_TEST
```
If I load this stream on our backup machines with the following commands
```
dd if=/dev/zero bs=1024k count=64 >/tmp/64MB
zpool create Z_TEST /tmp/64MB
zfs receive -Fd Z_TEST </tmp/Z_TEST.stream
strace -f zfs receive -Fd Z_TEST </tmp/Z_TEST.stream >strace.out 2>&1
```
then `zfs receive` will succeed with zfs-0.6.5.9 but will fail with zfs-0.7.6 with the error message
`cannot receive new filesystem stream: invalid backup stream`

I compared the strace-files and there are only little differences:
- zfs-0.6.5.9 opens /etc/mtab while zfs-0.7.6 opens /proc/self/mounts.
- zfs-0.6.5.9 loads data with a bunch of successful ioctl-calls while zfs-0.7.6 fails on such a ioctl call with EINVAL

Kind regards

Peter Koch

[Z_TEST.zip](https://github.com/zfsonlinux/zfs/files/2207248/Z_TEST.zip): contains the data stream and both strace files

**Comment by pk1234** [comment]
I tested every version between 0.6.5.9 and 0.7.9 and `zfs receive -Fd Z_TEST <Z_TEST.stream` works with every version <= 0.6.5.11 and fails with every version >= 0.7.0.

Also I compiled zfs-0.7.0 with --enable-debug. Since strace-output shows that one ioctl fails with EINVAL I grepped for "error 22" in /proc/spl/kstat/zfs/dbgmsg.

Here's what I found:
```
1532028613   dnode.c:1231:dnode_hold_impl(): error 22
1532028613   zap.c:766:fzap_checksize(): error 22
````

Peter

**Comment by rincebrain** [comment]
@pk1234 It'd be useful if you could do a git bisect on all the versions between 0.6.5 and 0.7.0 (and I don't mean just tagged release versions, since it sounds like you did that.)

Per the source of dnode_hold_impl:
```
 * EINVAL - Invalid object number or flags.
```

How helpful.

Can you maybe try grep -C10 'error 22' in dbgmsg?

**Comment by pk1234** [comment]
`zap.c:766:fzap_checksize(): error 22` occurs 8 times in dbgmsg while `dnode.c:1231:dnode_hold_impl(): error 22`occurs only once. This makes me believe, that dnode_hold_impl() is the culprit.

Here's some more output from dbgmsg:
```
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dnode.c:2063:dnode_next_offset_level(): error 3
1532028613   dnode.c:2063:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dbuf.c:2259:dbuf_findbp(): error 2
1532028613   dnode.c:1983:dnode_next_offset_level(): error 3
1532028613   dnode.c:2063:dnode_next_offset_level(): error 3
1532028613   dnode.c:2063:dnode_next_offset_level(): error 3
1532028613   dnode.c:1231:dnode_hold_impl(): error 22
1532028613   dsl_dir.c:448:dsl_dir_hold(): looking up %recv in obj34
1532028613   dsl_dir.c:448:dsl_dir_hold(): looking up %recv in obj34
1532028613   txg.c:655:txg_wait_synced(): txg=41 quiesce_txg=41 sync_txg=41
1532028613   txg.c:659:txg_wait_synced(): broadcasting sync more tx_synced=40 waiting=41 dp=ffff8823aa12f800
1532028613   txg.c:592:txg_quiesce_thread(): txg=41 quiesce_txg=42 sync_txg=41
1532028613   txg.c:600:txg_quiesce_thread(): quiesce done, handing off txg 41
1532028613   txg.c:542:txg_sync_thread(): txg=41 quiesce_txg=42 sync_txg=41
1532028613   zfeature.c:239:feature_get_refcount(): error 95
1532028613   zfeature.c:239:feature_get_refcount(): error 95
1532028613   zfeature.c:239:feature_get_refcount(): error 95
1532028613   zfeature.c:239:feature_get_refcount(): error 95
1532028613   zfeature.c:239:feature_get_refcount(): error 95
1532028613   dnode_sync.c:120:free_blocks(): ds=ffff8823b4b64800 obj=5 num=1
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
1532028613   dsl_dir.c:448:dsl_dir_hold(): looking up %recv in obj34
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
1532028613   zap_micro.c:926:zap_lookup_impl(): error 2
```

I have been using subversion instead of git so far. So I have to install git and read "git in a nutshell" first before I can do git-bisect. I will do that during the weekend and post reults here.

Maybe I should find out how to debug a kernel module as well.

Peter

**Comment by pk1234** [comment]
Accidently closed issue

**Comment by ahrens** [comment]
Tagging @pcd1193182 and @tcaputi who may be able to help diagnose this.

**Comment by tcaputi** [comment]
Unfortunately I am on vacation this week. If it is not resolved by then feel free to ping me again

**Comment by ahrens** [comment]
The error is coming from:
```
int
dnode_hold_impl(objset_t *os, uint64_t object, int flag, int slots,
    void *tag, dnode_t **dnp)
{
...
	if (object == 0 || object >= DN_MAX_OBJECT)
		return (SET_ERROR(EINVAL));
```
The the stream contains:
```
...
FREEOBJECTS firstobj = 138538465099776 numobjs = 1099511627776
FREEOBJECTS firstobj = 139637976727552 numobjs = 1099511627776
FREEOBJECTS firstobj = 140737488355328 numobjs = 140737488355328
FREEOBJECTS firstobj = 281474976710656 numobjs = 140737488355328
```
That last FREEOBJECTS extends past DN_MAX_OBJECT (its `firstobj` == `DN_MAX_OBJECT`).

This may be related to https://github.com/zfsonlinux/zfs/commit/e6d3a843d6ced970cbc74a3f809d744c30a7ec7c, where we made `receive_freeobjects()` actually pay attention to the return value from `dmu_object_next()`.  We may need to early-abort the no-op request to free objects after DN_MAX_OBJECT, which can't exist.  (Despite being 2 years old, this commit is not in 0.6.*.)

**Comment by pk1234** [comment]
Thanks everybody for diagnosing this problem.

My plans were (and still are) to learn how to do kernel-debugging so I can put  a breakpoint in dnode_hold_impl() and provide you with a backtrace. Also I will do a git-bisect between 0.6.5.11 and 0.7.0

Is there anything else I can do?

**Comment by ahrens** [comment]
@pk1234 Thanks for reporting this and digging into what's going on.  I think that @pcd1193182 has a handle on the problem now and can take it from here.

**Comment by pk1234** [comment]
I will wait for @pcd1193182.

In the meantime I added `if (obj==DN_MAX_OBJECT) continue;` as a temporary fix into receive_freeobjects(). This will only affect data streams with objects numbers that are exactly DN_MAX_OBJECT
```
receive_freeobjects(struct receive_writer_arg *rwa,
    struct drr_freeobjects *drrfo)
{
        uint64_t obj;
        int next_err = 0;

        if (drrfo->drr_firstobj + drrfo->drr_numobjs < drrfo->drr_firstobj)
                return (SET_ERROR(EINVAL));

        for (obj = drrfo->drr_firstobj == 0 ? 1 : drrfo->drr_firstobj;
            obj < drrfo->drr_firstobj + drrfo->drr_numobjs && next_err == 0;
            next_err = dmu_object_next(rwa->os, &obj, FALSE, 0)) {
                dmu_object_info_t doi;
                int err;

                if (obj==DN_MAX_OBJECT) continue;
                err = dmu_object_info(rwa->os, obj, &doi);
                if (err == ENOENT)
                        continue;
                else if (err != 0)
                        return (err);

                err = dmu_free_long_object(rwa->os, obj);
                if (err != 0)
                        return (err);

                if (obj > rwa->max_object)
                        rwa->max_object = obj;
        }
        if (next_err != ESRCH)
                return (next_err);
        return (0);
}
```
I had a look at the data streams from our Solaris machines. `zstreamdump -v` shows that all these data streams end with the following FREEOBJECTS records:
```
....
... lots of FREEOBJECTS-records with numobjs=1099511627776>
...
FREEOBJECTS firstobj = 133040906960896 numobjs = 1099511627776
FREEOBJECTS firstobj = 134140418588672 numobjs = 1099511627776
FREEOBJECTS firstobj = 135239930216448 numobjs = 1099511627776
FREEOBJECTS firstobj = 136339441844224 numobjs = 1099511627776
FREEOBJECTS firstobj = 137438953472000 numobjs = 1099511627776
FREEOBJECTS firstobj = 138538465099776 numobjs = 1099511627776
FREEOBJECTS firstobj = 139637976727552 numobjs = 1099511627776
FREEOBJECTS firstobj = 140737488355328 numobjs = 140737488355328
FREEOBJECTS firstobj = 281474976710656 numobjs = 140737488355328
```
So the last FREEOBJECTS-record in every Solaris data stream has an invalid object number.

By the way: Is DN_MAX_OBJECT the maximal valid object number (as its name implies)? Or is it the first invalid object number.

So maybe we should change:
```
        if (object == 0 || object >= DN_MAX_OBJECT)
                return (SET_ERROR(EINVAL));
```
in dnode.c into:
```
        if (object == 0 || object > DN_MAX_OBJECT)
                return (SET_ERROR(EINVAL));
```

**Comment by ahrens** [comment]
`DN_MAX_OBJECT` is actually the first invalid object ID.  You're right that a better name would be something like `ZFS_MAX_NUM_OBJECTS`.

**Comment by pcd1193182** [comment]
This issue was fixed as part of the Redacted Send/Receive PR #7958
