### ISSUE TITLE
ZFS 0.7.9 fails dkms method compilation on CentOS 7.5.1804 / 3.10.0-862.9.1 

### ISSUE THREAD

**Issue by AeonJJohnson** [openzfs/zfs#7745]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	|  7.5.1804
Linux Kernel	| 3.10.0-862.9.1.el7
Architecture	| x86_64
ZFS Version	| 0.7.9
SPL Version	| 0.7.9

### Describe the problem you're observing
DKMS compilation and installation fails during zfs compilation
```
...
Making all in 90zfs
Making all in initramfs
Making all in module
/home/aeon/devel/zfs/module/zcommon/zfs_fletcher_avx512.o: warning: objtool: fletcher_4_avx512f_byteswap()+0x4e: can't find jump dest instruction at .text+0x171
/home/aeon/devel/zfs/module/zfs/vdev_raidz_math_avx512bw.o: warning: objtool: raidz_zero_abd_cb()+0x33: can't find jump dest instruction at .text+0x3d
/home/aeon/devel/zfs/module/zfs/vdev_raidz_math_avx512f.o: warning: objtool: mul_x2_2()+0x24: can't find jump dest instruction at .text+0x39
```

### Describe how to reproduce the problem

1. New OS install. 
2. Yum update OS current. 
3. Follow DKMS installation process [Phase1](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#red-hat-centos-and-fedora) and [Phase2](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#dkms)

I'm going to backtrack into previous kernel releases to see where this starts to occur.

**Comment by behlendorf** [comment]
These warnings shouldn't result in any build failures they just haven't been suppressed yet.  They are the result of the kernel being configured with CONFIG_STACK_VALIDATION.  The version of objtool provided by the kernel get's a little bit confused when checking the resulting modules.

**Comment by AeonJJohnson** [comment]
I'm a jack@$$, I should've checked to see if the object files were generated or not. That and I clearly need to up my caffeine intake.

/I'll show myself out.

**Comment by behlendorf** [comment]
No problem!  Actually, I'm going to reopen this so we remember to either suppress the warnings or rework the code in a way which makes `objtool` happier.
