### ISSUE TITLE
zpool with permanent error on file <0xffffffffffffffff>:<0x1>

### ISSUE THREAD

**Issue by hostingnuggets** [openzfs/zfs#7762]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 8.11
Linux Kernel	| 3.16.57-2 (2018-07-14)
Architecture	| amd64
ZFS Version	| 0.6.5.9-5~bpo8+1
SPL Version	| 0.6.5.9-1~bpo8+1

### Describe the problem you're observing
My ZFS RAIDZ1 pool with 4 Samsung SSD disks of 960 GB (P/N: MZ7KM960HAHP) has a permanent error which I can't seem to get rid of or fix. I tried to scrub the pool many times, I tried to clear the pool also I checked the disks running a long selftest using smartctl but no errors can be found with the disks themselves.

### Describe how to reproduce the problem
n/a

### Include any warning/errors/backtraces from the system logs
Example:
zpool status:
```
  pool: data
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0 in 1h28m with 0 errors on Wed Aug  1 16:50:16 2018
config:

	NAME                                                     STATE     READ WRITE CKSUM
	data		                                         ONLINE       0     0     0
	  raidz1-0                                               ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM960HAHP-00005_REMOVEDSERIALN        ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM960HAHP-00005_REMOVEDSERIALN        ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM960HAHP-00005_REMOVEDSERIALN        ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM960HAHP-00005_REMOVEDSERIALN        ONLINE       0     0     0
	logs
	  mirror-1                                               ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM240HAGR-00005_REMOVEDSERIALN-part2  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM240HAGR-00005_REMOVEDSERIALN-part2  ONLINE       0     0     0

errors: Permanent errors have been detected in the following files:

        <0xffffffffffffffff>:<0x1>
```

zpool events -v (last event only)
```
Aug  2 2018 12:39:42.730962997 ereport.fs.zfs.data
        class = "ereport.fs.zfs.data"
        ena = 0x5ddb7308e9100001
        detector = (embedded nvlist)
                version = 0x0
                scheme = "zfs"
                pool = 0xd8f7549f8aeb1283
        (end detector)
        pool = "data"
        pool_guid = 0xd8f7549f8aeb1283
        pool_context = 0x0
        pool_failmode = "wait"
        zio_err = 0x5
        zio_flags = 0x80
        zio_stage = 0x200000
        zio_pipeline = 0x2f0002
        zio_delay = 0x0
        zio_timestamp = 0x0
        zio_delta = 0x0
        zio_objset = 0xffffffffffffffff
        zio_object = 0x1
        zio_level = 0x1
        zio_blkid = 0xe40e
        time = 0x5b62df6e 0x2b919c35 
        eid = 0x3fd9
```

**Comment by huwei1024** [comment]
Can you solved this issue?

**Comment by hostingnuggets** [comment]
@huwei1024 unfortunately I never received any answer so I just re-created the pool. As far as I understand such errors with ZFS  are not possible to fix.

**Comment by andkem** [comment]
I had this exact error message on my pool. It turns out that I had a snapshot of a zvol, i.e. a block device on ZFS, and that the error was in the snapshot's data. Removing the snapshot and running a scrub cleared the error. It being in a snapshot of a zvol explains why ZFS didn't provide a file path to a broken file since there was none to be given.
