### ISSUE TITLE
zpool create with zvols can hang when racing with udev

### ISSUE THREAD

**Issue by tcaputi** [openzfs/zfs#7773]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 14.04
Linux Kernel	| 4.4.0-112-generic
Architecture	| x86_64
ZFS Version	| 1897bc0d

### Describe the problem you're observing
While testing a PR I hit a hang during the `zfs_copies_003` test. The problem has to do with some code we have to avoid a lock inversion in the zvol opening code. The code in `zvol_first_open()` acknowledges that it is attempting to do a lock inversion, which it must do because it is called while the bdev's `bd_mutex` is already held from the linux kernel. In an effort to prevent problems, it uses a `mutex_tryenter()` loop pattern to attempt to wait until it is safe to take the lock. The problem, however, is that the Linux kernel does not drop the mutex long enough for other threads to acquire it and, as a result, it loops forever. Here is an illustration with stack traces:

```
[<ffffffff8123dfce>] __blkdev_get+0x2be/0x4e0
[<ffffffff8123e3a4>] blkdev_get+0x1b4/0x300
[<ffffffff8123e9c2>] blkdev_open+0x82/0xd0
[<ffffffff81201247>] do_dentry_open+0x227/0x320
[<ffffffff81202315>] vfs_open+0x55/0x80
[<ffffffff81210e8d>] path_openat+0x1ad/0x12d0
[<ffffffff8121331e>] do_filp_open+0x7e/0xd0
[<ffffffff81202699>] do_sys_open+0x129/0x270
[<ffffffff812027fe>] SyS_open+0x1e/0x20
[<ffffffff8181052d>] entry_SYSCALL_64_fastpath+0x2b/0xe7
[<ffffffffffffffff>] 0xffffffffffffffff
```
`__blkdev_get()` is stuck in a restart loop here (resulting from the udev process). `__blkdev_get()` calls `zvol_open()` -> `zvol_first_open()`, which returns the `-ERESTARTSYS` when it realizes it can not safely acquire the `spa_namespace_lock`. We attempt to call `schedule()` when we return to `zvol_open()`, but this is useless because the kernel is still holding the `bd_mutex`. This thread is running at 100% CPU and spams dbgmsg with error logs from this function.

```
[<ffffffff8180cb45>] schedule+0x35/0x80
[<ffffffff8180cdde>] schedule_preempt_disabled+0xe/0x10
[<ffffffff8180e645>] __mutex_lock_slowpath+0x95/0x110
[<ffffffff8180e6df>] mutex_lock+0x1f/0x2f
[<ffffffff8123dd6f>] __blkdev_get+0x5f/0x4e0
[<ffffffff8123e3f4>] blkdev_get+0x204/0x300
[<ffffffff8123eb6c>] blkdev_get_by_path+0x6c/0xb0
[<ffffffffc05cd786>] vdev_disk_open+0x1e6/0x4c0 [zfs]
[<ffffffffc05c9d28>] vdev_open+0x168/0x860 [zfs]
[<ffffffffc05ca475>] vdev_open_children+0x55/0x170 [zfs]
[<ffffffffc05e8872>] vdev_root_open+0x72/0x140 [zfs]
[<ffffffffc05c9d28>] vdev_open+0x168/0x860 [zfs]
[<ffffffffc05ca5f2>] vdev_create+0x22/0xa0 [zfs]
[<ffffffffc05ac102>] spa_create+0x572/0xcd0 [zfs]
[<ffffffffc060f01e>] zfs_ioc_pool_create+0x29e/0x310 [zfs]
[<ffffffffc0610070>] zfsdev_ioctl+0x640/0x790 [zfs]
[<ffffffff812163fd>] do_vfs_ioctl+0x2dd/0x4c0
[<ffffffff81216659>] SyS_ioctl+0x79/0x90
[<ffffffff8181052d>] entry_SYSCALL_64_fastpath+0x2b/0xe7
```
Meanwhile, the `zpool create` never seems to realize that the lock is being unlocked and never actually acquires it. This thread is holding the `spa_namespace_lock` (which is causing the restart loop on the other thread), but never acquires the `bd_mutex` to make progress, despite the fact that the other thread is repeatedly dropping it and reacquiring it. This stack trace shows up as a hung task in dmesg after a few minutes.

I think we need to rethink how we are doing our locking here. In the `__blkdev_get()` function, the comment above the `-ERESTARTSYS` handling says "Lost a race with 'disk' being deleted, try again. See md.c", which implies it was never really intended to be used as we are using it. The cleanest fix possible would be to add a call to `schedule()` in the linux kernel before reacquiring the `bd_mutex`, but I'm not sure if we'll be able to make that happen.

### Describe how to reproduce the problem
Run the `zfs_copies` tests with a low number of cores (I used 2). For me it happens every time, but it seems like it should be a random race condition.

**Comment by bunder2015** [comment]
I had problems with zfs_copies_003 as well in #6295, I wonder if its the same problem.

**Comment by tcaputi** [comment]
Yeah, that's almost definitely the same issue. You could probably mark that as a duplicate of this one (just because this one has more detail about what's going wrong).
