### ISSUE TITLE
Zpool replace issue - cannot replace - device is too small

### ISSUE THREAD

**Issue by maitza88** [openzfs/zfs#7832]
Hello there.

Using kmod zfs-0.6.5.9-1.el7.centos.x86_64 built for kernel 4.4.62-1.el7.elrepo.x86_64.

Zpool is currently created with whole disks (using /dev/disk/by-id) and there is no partitioning scheme on the zpool member disk. After a disk failed in one vdev, trying to replace it with the same disk part number and model fails with the exception that the device is too small.

What I noticed is that zfs is trying to partition newly added disk (the one replacing the faulty one) with the following partitioning scheme , so the first partition that it is trying to use is indeed smaller than a whole disk. I tried to labelclear the new disk, zeroing it and so on (did not try to zero it at the end of the disk - there is the label information).

        NAME                                                            STATE     READ WRITE CKSUM
      test                                                       DEGRADED     0     0     0
          raidz1-0                                                      DEGRADED     0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV318600UU400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV31920356400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV31910058400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301LC400NGN  FAULTED      3   727     0  too many errors
          raidz1-1                                                      ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV52330149400NGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319001KR400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319202LZ400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301ZH400NGN  ONLINE       0     0     0
          raidz1-2                                                      ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301LH400NGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319001NF400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV318600UT400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301XP400NGN  ONLINE       0     0     0
          raidz1-3                                                      ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301LZ400NGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319202E1400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV523301LL400NGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV5233021L400NGN  ONLINE       0     0     0
          raidz1-4                                                      ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319202RH400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G3_BTTV319202R6400HGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV5233015T400NGN  ONLINE       0     0     0
            /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV5233006L400NGN  ONLINE       0     0     0

errors: No known data errors 
Model: ATA INTEL SSDSC2BA40 (scsi)
Disk /dev/sdz: 400GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End    Size    File system  Name                  Flags
 1      1049kB  400GB  400GB                zfs-a9108849e5a373f5
 9      400GB   400GB  8389kB

This is how a currently used disk in the zpool looks like : 
 lsblk -f | grep sdq
sdq       zfs_member         Pool-A          683124868951454539

parted /dev/sdq print
Error: /dev/sdq: unrecognised disk label
Model: ATA INTEL SSDSC2BA40 (scsi)
Disk /dev/sdq: 400GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags:

I know that by default, when not detecting a partition or slice, zfs is trying to partition the disk like described above. 

I wonder how at the creation time, it did not create partitions on each disk used because in other examples (using same kernel version and same zfs version) the pool was created with partitions on each disk.

Is there any workaround for this so I can succesfully replace the failed disk with the one that I already tried ?

**Comment by GregorKopka** [comment]
Man zpool states
>disk    A block device, typically located under /dev.  ZFS can use individual slices or partitions, though the recommended mode of operation is to use whole disks.  A disk can be specified by a full path, or it can be a shorthand name (the relative portion of the path under /dev).  A whole disk can be specified by omitting the slice or partition designation.  For example, sda is equivalent to /dev/sda.  **When given a whole disk, ZFS automatically labels the disk, if necessary.**

The bold part didn't seem to have happened in this case - leading to being unable to replace one of the original drives in the pool with an identical one (as far as I understood the issue) as zpool replace seems to insist on partitioning the replacement drive.

I think we have a valid issue here, be it that the documentation should be more clear about how zpool detects if a disk is a full drive or a partition (so pitfalls like here can be avoided when creating pools) _or_ a description of a workaround to make zpool replace use a specified block device verbatim (and skip the partitioning) _or_ that zpool replace (possibly also zpool create/add/attach) lacks a command line switch to disable the auto-partitioning magic of zfs (or that man zpool as of 0.7.9-r0-gentoo dosn't list it, should it already exist).

@maitza88: The first line from _zpool history tank_ should give you the exact command the pool was created with.

**Comment by maitza88** [comment]
pool was not created via command line(so the zpool create command is not in zpool history). It was created using an api taht calls some kind of zfs subsystem commands, behind the layer of zfs command-line.

root@uk-rdg-evr01-bstor-ssd04-h1246  ~# zpool history -i | head -50
History for 'test':
2018-08-16.14:32:54 [txg:5] create pool version 5000; software version 5000/5; uts blabla 4.4.62-1.el7.elrepo.x86_64 #1 SMP Tue Apr 18 11:02:11 EDT 2017 x86_64.

Fun fact is that creating the pool from command line it partitions EFI every disk in the pool. When creating it from the API, it does not. 

Any ideas why ?

Thanks
