### ISSUE TITLE
Snapshot permission/ownership issue

### ISSUE THREAD

**Issue by olegblecher** [openzfs/zfs#7844]
### System information
Distribution Name	| Ubuntu
Distribution Version	| 16.04
Linux Kernel	| 4.4.0-134-generic
Architecture	| x86_64
ZFS Version	| 0.6.5.6-0ubuntu25
SPL Version	| 0.6.5.6-0ubuntu4

### Describe the problem you're observing
Hi all. I have tried posting this question in the [LXD project's GitHub page](https://github.com/lxc/lxd/issues/3314) first, and they've sent me here.

Some background: I am running and LXD-container where I'm running Samba on Debian 9, joined to an AD-server. I've configured Samba so that users can access previous versions of files/folders with the shadow copies-function (via ZFS snapshots).

This machine has a folder called `/shared`, which is a separate ZFS dataset, mounted in to the container with LXD/LXC's magical attachment function. All works well up to this point. 

Now, to the interesting part:

I can see all snapshots (by going in to `.zfs/snapshot`) inside the container, but I cannot see any files in them. However, if I manually run `cd /var/lib/lxd/storage-pools/tank1/custom/shared/.zfs/snapshot` on the host machine, and then into any snapshot, and then back, I see that the snapshot's folder has changed owners, from **root:root**, to **100000:100000**, and that the permissions have changed from 555 to 775. After I've done that, I can see the specific snapshot mounted in by running `cat /proc/self/mountinfo`. I can also access previous versions of the folder in Windows Explorer.

A little workaround I've discovered is to run `chown -R 100000:100000 .zfs/snapshot`, but that does not affect any newer snapshots. It does, however, allow me to reach all the data that is inside the snapshots from within the LXD-container (which is ultimately what I want to do).

100000 is quite a special user and group, and I cannot delegate any ZFS-permissions to it. Any ideas on how I can "force" 100000:100000 to be the owner of all snapshots on a particular ZFS? Setting up a cron job for that feels too nasty... Any thoughts are welcome.

Edit: I am using Sanoid for snapshots. So it's a regular cron job that is being run by **root** that creates the ZFS snapshots.

**Comment by mschilli87** [comment]
@olegblecher
> I have tried posting this question in the LXD project's GitHub page first, and they've sent me here.

I can't find any related issue on https://github.com/lxc/lxd/issues and github claims this is your first issue ever. Would you mind linking the discussion that referred you here in case it has any additional useful information and to avoid spendind extra time due to elsewhere solved cross-posts?

**Comment by olegblecher** [comment]
@mschilli87 absolutely - I've edited my original post here, and here's the link: https://github.com/lxc/lxd/issues/3314

I wasn't the one who posted the original issue on LXD's page, I've just added my own experiences there.

**Comment by siebenmann** [comment]
This sounds like it involves mount namespaces. Unfortunately snapshots and non-default mount namespaces don't interact well at the moment, because ZFS auto-mounts snapshots by running a user-level `mount` command and this `mount` runs in the main (PID 1) namespace. What happens in the container's mount namespace depends on how that's set up, but I think this sort of outcome is at least possible.

**Comment by olegblecher** [comment]
Thanks @siebenmann. Is there any risk in running `chown -R 100000:100000` on the snapshot folder inside the host machine right after a new snapshot had been taken?
