### ISSUE TITLE
DKMS package is looking pretty in Ubuntu

### ISSUE THREAD

**Issue by Redsandro** [openzfs/zfs#7850]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu, Linux Mint
Distribution Version	| 16.04 LTS, 18.04 LTS, Linux Mint 18, Linux Mint 19
Linux Kernel	| 4.9.0 up to 4.15.0
Architecture	| x86_64
ZFS Version	| 0.7.*
SPL Version	| 0.7.*

### Describe the problem you're observing

There is this issue that I'm observing with different ZFS- and Linux versions since I started to compile from master. Everything works. However, I do need to manually recompile on every kernel update. I assume the DKMS package is supposed to handle this, but, well, it doesn't (on my test environments).

I'm wondering if I'm missing a step; if the documentation (see below) might be outdated or incomplete. Perhaps there's this one obvious undocumented prerequisite for making this work that I'm just oblivious about.

Note that there are no error messages during compilation or installing the .deb packages.

### Describe how to reproduce the problem

After compiling as described in the [Building ZFS](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) section with `make deb` as the final step, you end up with a couple of packages including a [DKMS package](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages).

The instructions end there, so here's that obvious step I might be doing wrong:

```
# SPL
for i in *.deb; do gdebi $i; done

# ZFS
for i in lib*.deb; do gdebi $i; done
for i in zfs*.deb; do gdebi $i; done
echo zfs >> /etc/modules
modprobe zfs
```

Please note that everything is working fine, except for DKMS. I have to recompile after every kernel upgrade.

---

I'm also wondering if these steps can be simplified by a single line as mentioned in the [Casual Build Instructions](https://github.com/zfsonlinux/pkg-zfs#casual-build-instructions), but I haven't touched that yet, because (almost) everything is working and I don't want to jeopardize that by running steps I don't really understand.

**Comment by rincebrain** [comment]
You may notice that the packaging there hasn't been updated in 3 years.

Also, the instructions don't include "install the packages" because some people need different packages.

This would be better asked and answered on a mailing list or IRC than here, because it doesn't immediately appear to be a bug in the packages themselves or the documentation.

**Comment by Redsandro** [comment]
> Perhaps there's this one obvious undocumented prerequisite for making this work that I'm just oblivious about.

I think the problem is that the suggested `make deb` creates conflicting packages. The docs aren't clear (enough) about what packages need to be installed when. The answer (for DKMS) is `deb-utils` and `deb-dkms`.

For completeness, this is how I got ZFS on Linux running (with DKMS) on Linux Mint 19 and Ubuntu 18.04.

## Building and installing ZFS+DKMS

```bash
wget https://github.com/zfsonlinux/zfs/releases/download/zfs-0.8.0-rc1/zfs-0.8.0-rc1.tar.gz
tar -xzf zfs-0.8.0-rc1.tar.gz
mv zfs-0.8.0{,-rc1}
cd zfs-0.8.0-rc1
./configure
make -s -j$(nproc) && make deb-utils deb-dkms && spd-say "ZFS packages are ready" || spd-say "ZFS compilation error"
for DEB in *.deb; do gdebi --non-interactive $DEB; done
```

> __Note:__ `spd-say` is unnecessary. I use it so I don't have to keep track of the progress. It provides an audio cue for when the compilation is finished (or failed).

## Enable ZFS now

So you don't have to reboot before using ZFS.

```bash
sudo modprobe zfs
```

## Enable services

So your pools and shares are there after a reboot.

```bash
sudo systemctl enable zfs-import-cache
sudo systemctl enable zfs-import-scan
sudo systemctl enable zfs-import.target
sudo systemctl enable zfs-mount
sudo systemctl enable zfs-share
sudo systemctl enable zfs-zed
sudo systemctl enable zfs.target
```

---

It is worth noting that these (simplified) steps work only from `zfs-0.8.0-rc1` and up, because:

> As of this release the spl is included in the zfs tarball and is no longer provided separately.

This helps, because for the separate spl compilation step and referencing the result, there were also many different examples, which made it confusing to choose how to compile the two to someone who doesn't exactly know _how_ it should be used.

Thanks to whomever decided to integrate the two, so we can now use one `make` command. I think it was @behlendorf. :+1: 

---

My final question would be: Why do we have to modprobe and enable all these services? deb packages should be able to take care of this. Are there build switches to instruct the deb packages to do all this for us, so the steps could be even simpler?

Either way, I'm leaving this open. I know how to build things properly now, but the documentation still needs maintenance by someone who knows what is actually obsolete and what is important.
