### ISSUE TITLE
ZFS ARC not accounted in Cached field in /proc/meminfo

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#7883]
There is probably an existing issue for this, but I cannot find it (and don't have time for an exhaustive search), so I am opening a new one.

I noticed today that `vm_node_stat` is exported. This is read by `meminfo_proc_show` to determine the value of the Cached field.

If we do atomic updates to `vm_node_stat[NR_FILE_PAGES]`, we should be able to account for ARC in the Cached field in /proc/meminfo. I noticed this on Linux 4.18.0-rc8. I haven't looked at earlier kernels to see the situation there. I don't have time to do anything with this right now, but I wanted to post this here for either my future self or someone else to try using.

One more note. We should consider batching atomic updates to `vm_node_stat[NR_FILE_PAGES]` so that we don't serialize every single ABD allocation/deallocation with every thing else that touches that.

**Comment by ryao** [comment]
We might also need to decrement/increment `vm_node_stat[NR_LRU_BASE + LRU_ACTIVE_ANON]` to remove ARC's usage from the Used field.

**Comment by Atemu** [comment]
This is still important to me.

**Comment by behlendorf** [comment]
Reopening.  This would be nice and potentially resolve a variety of issues if we can determine a reasonable way to implement it.
