### ISSUE TITLE
SPL symbol unavailable or missing deps in 4.18 kernel config with builtin spl-0.7.10

### ISSUE THREAD

**Issue by fling-** [openzfs/zfs#7890]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  gentoo
Distribution Version	| 17.1
Linux Kernel	| 4.18
Architecture	| amd64
ZFS Version	| none
SPL Version	| 0.7.10

### Describe the problem you're observing
Can't enable `CONFIG_SPL` in 4.18 kernel config
`oldconfig` does not suggest to enable the symbol when it is missing from config
`oldconfig` removes the symbol from the config when it is present

It works fine with 4.17
### Describe how to reproduce the problem
Using https://gist.github.com/fling-/80b9afcad301d985dfb72753b53b463e

### Include any warning/errors/backtraces from the system logs
`oldconfig` output is
```
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
```
but it is expected to include this prompt:
```
Solaris Porting Layer (SPL) (SPL) [N/m/y/?] (NEW)
```

**Comment by fling-** [comment]
@PMT on irc suggested to test with 0.8
with zfs-0.8-rc1 builtin 4.18 `oldconfig` asks for
```ZFS filesystem support (ZFS) [N/m/y/?] (NEW)```
Which is expected as there is no separate spl for 0.8 anymore

**Comment by behlendorf** [comment]
@fling- from your comments it's not clear to me if this really is an issue with the 0.7.10 spl tag.  Could you please clarify.

**Comment by fling-** [comment]
@behlendorf it is an issue with 0.7.10 spl tag

**Comment by behlendorf** [comment]
@fling- the issue with 4.18 is due to torvalds/linux@104daea149c45cc84842ce77a9bd6436d19f3dd8, proposed commit behlendorf/spl@88611c5416c96bf75817d7ab026b309fe4677372 resolves the issue and we'll get it pulled in to 0.7.11.  And as you posted above this issue does not effect 0.8.0-rc1 due to the spl merge.  Thanks for catching this!
