### ISSUE TITLE
Problem with ZFS and NFS/CIFS/SSHFS

### ISSUE THREAD

**Issue by jcfernandez-890825** [openzfs/zfs#7907]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Proxmox
Distribution Version	|  5.2-2
Linux Kernel	|  4.15.18-4-pve
Architecture	|  x86_64
ZFS Version	|  0.7.9-1
SPL Version	|  0.7.9-1

### Describe the problem you're observing
When a write to a VFS (NFS, CIFS, SSHFS) is issued, both **ZFS/ARC** and **Linux Page Cache** try to put the file(s) to RAM, replicating the file twice on RAM, should **Linux Page Cache** consumes all free memory, **ZFS/ARC** is evicted to [zfs_arc_min] and the system start to use swap while there is still memory available. Is there a way to avoid both behaviors? (I mean the file been replicated twice on RAM and the system swapping while there's still memory available)

 ### Describe how to reproduce the problem
Use:
dd if=/dev/zero of=/path/to/mount-nfs-cifs-sshfs/file100G bs=1M count=102400
rsync -rvh /path/to/src/file /path/to/mount-nfs-cifs-sshfs
cp -av /path/to/src/file /path/to/mount-nfs-cifs-sshfs

**Comment by behlendorf** [comment]
You can prevent the page cache from cannibalizing the ARC by setting `zfs_arc_pc_percent`.  As for the double caching since they're independent filesystems there's no existing way for them to shares a common cache.

```
       zfs_arc_pc_percent (uint)
                   Percent of pagecache to reclaim arc to

                   This  tunable  allows  ZFS arc to play more nicely with the
                   kernel's LRU pagecache. It can guarantee that the arc  size
                   won't  collapse  under  scanning pressure on the pagecache,
                   yet still allows arc to be reclaimed down to zfs_arc_min if
                   necessary.  This value is specified as percent of pagecache
                   size (as measured by NR_FILE_PAGES) where that percent  may
                   exceed   100.   This  only  operates  during  memory  pres‐
                   sure/reclaim.

                   Default value: 0% (disabled).
```

**Comment by CMCDragonkai** [comment]
@behlendorf Just so I understand you, what exactly should be setting that number to?

**Comment by behlendorf** [comment]
@CMCDragonkai I'd suggest starting by setting `zfs_arc_pc_percent=100`.  This will effectively split any free memory on the system 50-50 between the Linux page cache and the ZFS ARC.  Depending on your exact configuration you might want to further adjust things to bias toward one cache or the other.

**Comment by behlendorf** [comment]
@CMCDragonkai you're correct, the ARC will only cache data for the ZFS filesystems.  @jcfernandez-890825 can you clarify the exact configuration your using.
