### ISSUE TITLE
"unable to handle kernel paging request" at kmem_cache_alloc, and hung processes

### ISSUE THREAD

**Issue by vthriller** [openzfs/zfs#7987]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| —
Linux Kernel	| gentoo-sources-4.9.95
Architecture	| x86_64
ZFS Version	| 0.7.9-r0-gentoo
SPL Version	| 0.7.9-r0-gentoo

### Describe the problem you're observing

- spotted unusual CPU usage statistics (lots of iowait)
- typed in `dmesg` and [found a bunch of oopses](https://github.com/zfsonlinux/zfs/files/2448173/zol079hang.txt)
- tried random processes like `ls` on one of the ZFS mountpoints only to see them hang in `D` state indefinitely
- typed in `htop` and found the following in `D` state:
  - `txg_sync`
  - `khugepaged`
  - `dbuf_evict`
  - and a couple of aforementioned userspace processes (but nothing that I didn't run while poking this thing around)

### Describe how to reproduce the problem

No idea what triggered this, was away at the moment when CPU usage jumped up according to monitoring system, and no cron jobs were scheduled around said time either.

**I have a slight suspicion that it might have something to do with zram-backed swap**, so I'm currently swapping it off to a disk-backed swap, although I doubt that it might affect anything at this point.

### Include any warning/errors/backtraces from the system logs

Again, [this is what `dmesg` shows at the moment.](https://github.com/zfsonlinux/zfs/files/2448173/zol079hang.txt)

**Comment by vthriller** [comment]
> I have a slight suspicion that it might have something to do with zram-backed swap, so I'm currently swapping it off to a disk-backed swap, although I doubt that it might affect anything at this point.

Well, `swapoff` processes stalled relatively quickly and are not killable, and `swapon --show` shows the exact same values for well over an hour now. No new kernel log messages though.

Unfortunately this kernel has `CONFIG_CRASH_DUMP` _unset_, so I'm going to leave this issue as it is and force-reboot the system after 136 days of uptime.

At last, [here are the traces for all blocked processes (`sysrq-w`)](https://github.com/zfsonlinux/zfs/files/2448472/zol079-sysrq-w.txt).

(#4319 and #6880 is the closest I was able to google, but I'm not sure whether these issues are really that relevant.)

**Comment by vthriller** [comment]
> I have a slight suspicion that it might have something to do with zram-backed swap

Well, 156 days of uptime later I got the same thing without zram block devices.

**Comment by kpande** [comment]
try reproducing it with a new version, provide logs, backtraces etc would probably help...

**Comment by vthriller** [comment]
Well, [backtraces didn't change that much from the last time](https://github.com/zfsonlinux/zfs/files/3238136/zfs-2019-05-30-hang.txt), except for missing ARC functions in the middle of the stack.

> try reproducing it with a new version

Thanks, I'm already planning an upgrade for both kernel and ZoL.
