### ISSUE TITLE
Instead DEAD Process on "zpool import"

### ISSUE THREAD

**Issue by elbrinke** [openzfs/zfs#7998]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Server
Distribution Version	| 18.04
Linux Kernel	| Linux  4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Architecture	| 64 bit
ZFS Version	| [  100.206321] ZFS: Loaded module v0.7.5-1ubuntu16.3, ZFS pool version 5000, ZFS filesystem version 5
SPL Version	| version:        0.7.5-1ubuntu1

### Describe the problem you're observing
I have a zpool drive which I use for backup purposes called: backup. When i run `zpool import`, i can see the zfs pool:

```
user@host:~$ sudo zpool import
[sudo] password for sysadmin: 
   pool: backup
     id: 8548575151524541541
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	backup                                          ONLINE
	  usb-WD_My_Book_1555_56251001420154201214-0:0  ONLINE
```
However, when i try to import the zpool using: `sudo zpool import backup`

It simply hangs and when i check the process - it shows a DEAD process. 

When i plug the same drive into another server and do a zpool import backup, it works without any issues. 

When i check the zfs import scan, i get:
```
systemctl status zfs-import-scan.service
● zfs-import-scan.service - Import ZFS pools by device scanning
   Loaded: loaded (/lib/systemd/system/zfs-import-scan.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2018-10-08 16:05:26 SAST; 59min ago
           └─ ConditionPathExists=!/etc/zfs/zpool.cache was not met
     Docs: man:zpool(8)
```
Am i missing something? Why would it import on one server but not the other?

**Comment by DeHackEd** [comment]
Lacking context, I'm guessing when you say 'DEAD' you actually mean a process in the `D` state which usually means disk IO wait.

**Comment by elbrinke** [comment]
hi @DeHackEd , oh i see. Then you are right. It's in D state..

**Comment by rincebrain** [comment]
@elbrinke This is not a support forum, and you would be better served with asking on IRC or the mailing list.

That said, I would suspect the contents of dmesg would shed light on this.
