### ISSUE TITLE
/bin/ls hangs on dataset from working zpool perhaps coupled to other zpool failures on the same system

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#8013]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Scientific Linux
Distribution Version	|  7.5
Linux Kernel	|  3.10.0-862.14.4.el7
Architecture	|  x86_64
ZFS Version	|  0.7.11-1
SPL Version	|  0.7.11-1

### Describe the problem you're observing

/bin/ls hangs on a filesystem for a working zpool (zpool scrub passes without error, zpool and zfs get work, zdb -C dumps data). This is potentially related to 2 other zpool on this system reporting "One or more devices are faulted in response to IO failures.", however, there is another working zpool on this system where /bin/ls on the corresponding dataset does not hang.

What useful debugging information should I glean from this system (e.g., zdb something) before rebooting to clear the problem?

### Describe how to reproduce the problem

```
/bin/ls /data2
```

This command hangs even though the corresponding zpool (data2) does not report any obvious problems and "zpool scrub data2" completed without any error. Note "/bin/ls /data3" works, and the other two zpool on this system (data1 and data4) are in a failed state. In addition, failmode=continue is enabled for all 4 zpool. 

### Include any warning/errors/backtraces from the system logs

```
[root@node2178 ~]# zfs list
NAME    USED  AVAIL  REFER  MOUNTPOINT
data2  18.7G  3.49T  18.7G  /data2
data3  19.1G  3.49T  19.1G  /data3
[
root@node2178 ~]# /bin/ls /data3
current  in_use.lock

[root@node2178 ~]# /bin/ls /data2
^C

[root@node2178 ~]# zpool list
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
data1  3.62T  9.55G  3.62T         -     0%     0%  1.00x  ONLINE  -
data2  3.62T  18.7G  3.61T         -     0%     0%  1.00x  ONLINE  -
data3  3.62T  19.1G  3.61T         -     0%     0%  1.00x  ONLINE  -
data4  3.62T   449M  3.62T         -     0%     0%  1.00x  ONLINE  -

[root@node2178 ~]# zpool status
  pool: data1
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-JQ
  scan: none requested
config:

	NAME                      STATE     READ WRITE CKSUM
	data1                     ONLINE       0 13.0K     0
	  wwn-0x5000c5009bfa9e84  ONLINE      69   258     0

errors: 13324 data errors, use '-v' for a list

  pool: data2
 state: ONLINE
  scan: scrub repaired 0B in 0h4m with 0 errors on Thu Oct 11 11:14:05 2018
config:

	NAME                      STATE     READ WRITE CKSUM
	data2                     ONLINE       0     0     0
	  wwn-0x5000c5009c790e21  ONLINE       0     0     0

errors: No known data errors

  pool: data3
 state: ONLINE
  scan: none requested
config:

	NAME                      STATE     READ WRITE CKSUM
	data3                     ONLINE       0     0     0
	  wwn-0x5000c5009d2e818a  ONLINE       0     0     0

errors: No known data errors

  pool: data4
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-JQ
  scan: none requested
config:

	NAME                      STATE     READ WRITE CKSUM
	data4                     ONLINE       0 9.69K     0
	  wwn-0x5000c5009c831c1d  ONLINE     111   225     0

errors: 9922 data errors, use '-v' for a list

[root@node2178 ~]# zpool get failmode data{1..4}
NAME   PROPERTY  VALUE     SOURCE
data1  failmode  continue  local
data2  failmode  continue  local
data3  failmode  continue  local
data4  failmode  continue  local
```

**Comment by kpande** [comment]
this is a known issue where suspended pools with zero redundancy can take the whole filesystem out for a long lunch. @dweeezil is working on the ability to forcibly unload these 'stuck' pools from memory.

as for why the 'working' pool gets stuck too, it is probably due to some taskq that is shared among the pools that is blocking forever on I/O to the 'stuck' pool. @rincebrain has a technique to 'kick' the taskq, perhaps they can chime in and remind me that trick.

**Comment by kpande** [comment]
can you provide all stack traces on the system (/proc/*/stack)

**Comment by stuartthebruce** [comment]
@kpande, I recently learned of @dweeezil work and I eagerly look forward to testing that. The reason I bothered with another ticket is that with 2 broken and 2 working zpool on a signle system system I able to access a dataset for one working zpool but not the other. Ideally I would rather not have to forcibly unload broken zpool (when the code update is available) to regain access to the dataset(s) on working zpool. Please find attached the output from,
'''
[root@node2178 ~]# tar czvf stack.tar.gz /proc/*/stack
'''

[stack.tar.gz](https://github.com/zfsonlinux/zfs/files/2470450/stack.tar.gz)

**Comment by rincebrain** [comment]
Not really "my" trick, per se, but writing nonzero to /sys/module/spl/parameters/spl_taskq_kick is the thing you're alluding to.

Per spl-module-parameters(5):
```
                   Kick stuck taskq to spawn threads. When writing a non-zero value to it, it will scan all the taskqs. If any of them have a pending task more than 5 seconds old, it will kick
                   it to spawn more threads. This can be used if you find a rare deadlock occurs because one or more taskqs didn't spawn a thread when it should.
```

**Comment by kpande** [comment]
thanks @rincebrain I always forget that it's an SPL module parameter.

**Comment by stuartthebruce** [comment]
The following did not help,

```
[root@node2178 ~]# echo 1 > /sys/module/spl/parameters/spl_taskq_kick
```

Is there any other debugging information that would be useful in case this is a new bug?

**Comment by rincebrain** [comment]
If you shared dmesg's contents anywhere in here, I haven't seen it, so that could be helpful.

You could try `echo 1 | sudo tee /sys/module/zfs/parameters/zfs_dbgmsg_enable`, saving the contents of /proc/spl/kstat/zfs/dbgmsg, running `ls /data2`, then saving the contents of [...]/dbgmsg again and comparing the two, to see what that specific access logged, if anything.

**Comment by stuartthebruce** [comment]
I have attached some log files showing various kernel task timeout, zed, smartd, and sd error messages. However, the system was rebooted before I could try setting zfs_dbgmsg_enable. I will give that a try the next time I see this problem.

[messages-20181016.gz](https://github.com/zfsonlinux/zfs/files/2489713/messages-20181016.gz)

**Comment by stuartthebruce** [comment]
@kpande agreed there was a HW failure with some (but not all) of the HDD in that system. However, the problem I am trying to solve is how to run O(1000) marginal HDD in a cluster without having ZFS block on HW failures since the next level in the software stack is setup to handle those failures.
