### ISSUE TITLE
el7_5 release trying to install el7_4 packages from the el7_5 directory

### ISSUE THREAD

**Issue by barureddy** [openzfs/zfs#8035]
I'm installing zfs on centos 7.5. The http://download.zfsonlinux.org/epel/zfs-release.el7_5.noarch.rpm once installed is calling on the 7.4 zfs packages from the 7.5 github directory and failing to find the files. I believe this is just a naming issue.

**Comment by alatteri** [comment]
did you try a yum clean all?
