### ISSUE TITLE
grub-probe fails with Unknown Filesystem

### ISSUE THREAD

**Issue by arizonafox** [openzfs/zfs#804]
Installed and was using zfs. On last update, grub failed to boot complaining that the the kernel needed to be loaded. Began install per Djahorn on second drive, then instead of using debootstrap, copied the failed system onto new setup. When reaching chroot stage have been troubleshooting grub-probe issue (ie it will not properly do grub install because of it). Below are the results of the apt-get commands that he suggests for grub troubleshooting. How can I get grub-probe working so I can fix this system?

root@ubuntu:/# apt-get install --reinstall zfs-grub
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'grub-common' instead of 'zfs-grub'
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/2,356 kB of archives.
After this operation, 0 B of additional disk space will be used.
Can not write log, openpty() failed (/dev/pts not mounted?)
(Reading database ... 232194 files and directories currently installed.)
Preparing to replace grub-common 1.99-21ubuntu3+zfs1 (using .../grub-common_1.99-21ubuntu3+zfs1_amd64.deb) ...
Unpacking replacement grub-common ...
Processing triggers for ureadahead ...
Processing triggers for man-db ...
Can not write log, openpty() failed (/dev/pts not mounted?)
Setting up grub-common (1.99-21ubuntu3+zfs1) ...
root@ubuntu:/# apt-cache search zfs-grub
grub-common - GRand Unified Bootloader (common files)
root@ubuntu:/# apt-cache show zfs-grub
N: Can't select versions from package 'zfs-grub' as it is purely virtual
N: No packages found
root@ubuntu:/# apt-cache policy grub-common zfs-grub
grub-common:
  Installed: 1.99-21ubuntu3+zfs1
  Candidate: 1.99-21ubuntu3+zfs1
  Version table:
     1.99-21ubuntu3.1 0
        500 http://archive.ubuntu.com/ubuntu/ precise-updates/main amd64 Packages
 **\* 1.99-21ubuntu3+zfs1 0
        900 http://ppa.launchpad.net/zfs-native/grub/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
     1.99-21ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
zfs-grub:
  Installed: (none)
  Candidate: (none)
  Version table:

**Comment by rstarkey** [comment]
Hi, sorry to bring up a long closed issue but ... I followed https://github.com/zfsonlinux/zfs/wiki/Ubuntu%2016.04%20Root%20on%20ZFS
and I'm running into this bug with grub failing zfs checksums *and* I can reproduce it on a regular basis.  In my case though, a simple reboot clears the issue for a short about of time and then the checksum issue reappears.  

I don't think is a documentation issue.  :)

How can I support getting this fixed?
