### ISSUE TITLE
Slow reads on large files.  All SSD pool.

### ISSUE THREAD

**Issue by alatteri** [openzfs/zfs#8066]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.5 
Linux Kernel	| 3.10.0-862.14.4.el7.x86_64
Architecture	| x86_64
ZFS Version	| .7.11-1
SPL Version	| .7.11-1

### Describe the problem you're observing
I’ve been benchmarking an all SSD array, 3 x raidz1 vdevs, 6 Samsung SATA SSDs in each vdev.  I am seeing great write speeds, but the reads get drastically slower as the file sizes get into the 50-100 MB range.  I am using Blackmagic Design Disk IO benchmark program, which is designed for my industry, media production.  It will write an image sequence of a given frame size and number of frames, give read, read-reverse, read-random & read-write results.

I’ve run each test 3 times and averaged the result.

File size/number of frames/read speed

10MB 	10000	4,449.88 MB/s
20MB	4000	4,682.74 MB/s
50MB	2000	2,788.48 MB/s
100MB	1000	1208.09  MB/s

At 100MB, the speed is almost a quarter that of 10MB files.  When I’ve tested the same hardware setup with XFS, I get 6GB/s read speeds linearly across all file size ranges.  I’ve also tried ashift=12, and gotten the same results.

ashift=13
recordsize=1M
checksum=on
compression=off
atime=off
xattr=sa
primarycache=metadata
secondarycache=metadata
sync=disabled
dnodesize=auto

If I enable cache=all, the reads speeds get bumped up to 3GB/s, but this is still 25% the speed of an ARC read on 10MB file.

Hardware is Dell T630, 512GB RAM, H730P in HBA Mode, all the latest firmwares.

Also tested this on a clean install of CentOS 7.5 Minimal on HP z820 and LSI3008 HBA, same results.

I've tried a variety of pool layouts, tunable, and dataset options, and even in tried Ubuntu 18.10.  Always the same reduction in performance with large files.

### Describe how to reproduce the problem
Create a new all ssd pool, raidz1, 3 vdevs, 6 disks each vdev.  Utilizing Blackmagic Design Disk IO, run ./TestIO /path/to/mount 100(frame size in MB) 1000(number of frames) 10(threads) 0 0(disable DirectIO)

**Comment by alatteri** [comment]
I've tried every tunable suggested to me.  I've tried on 2 different sets of hardware, .8.0rc1, Ubuntu and even other people have tried the same test on their hardware.  The results are always the same.  At 100MB/frame, the read speed is always capped around 1,200 - 1,500MB/s range.  Well under the speed capable by the hardware.  I've confirmed Harvard speeds with XFS, and am able to max out the PCI bandwidth with reads at 6 GB/s.  I was unable to revert to .6.5.X brand as those have been removed from the repo, but I know there are a few bugs documenting performance regressions with .7.X branch.  Unsure if those are related to this.

**Comment by gmelikov** [comment]
@alatteri in mailing lists I and other people suggest you to try other benchmark tools too (fio, or at least dd). Maybe I've missed it, but it would be great to see every benchmark results here too.

**Comment by gmelikov** [comment]
@alatteri can you give a link to this "Blackmagic Design Disk IO benchmark" for Linux? I've only found a thread from 2013 which says it doesn't exist.

**Comment by alatteri** [comment]
> @alatteri in mailing lists I and other people suggest you to try other benchmark tools too (fio, or at least dd). Maybe I've missed it, but it would be great to see every benchmark results here too.

I'd be happy to try a fio run, but I am not very clear on what syntaxes for it would re-create the type of workload I have.  Any suggestions?

**Comment by alatteri** [comment]
I re-ran the tests using 4 vdevs of 2xSSD mirrors, and the results are even worse than raidz1
10MB 10000	4,449.88 MB/s
20MB	4000	2809.43 MB/s
50MB	2000	1789.65 MB/s
100MB	1000	816.54 MB/s

**Comment by alatteri** [comment]
Ran these tests with a stripe of 8 SSDs direct connect to the HBA.  The speeds at 100MB/frame are barely more than that of a single SSD.  Something is definitely wrong.  The writes are all scaling linearly with each SSD, at around 4GB/s.  XFS stripe reads are also scaling linearly at 4GB/s.

10MB 10000	2,546.02 MB/s
20MB	4000	2629.97 MB/s
50MB	2000	1,676.49 MB/s
100MB	1000	790.9 MB/s

**Comment by gmelikov** [comment]
@alatteri I tried `TestIO` from your link, but can't get consistent numbers, unfortunately I can't look further now in it.

Tried fio, it gives consistent numbers for data in ARC (I don't have large pools for seamless tests now, sorry):

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 9
Linux Kernel	| 4.15.18-7-pve
Architecture	| x86_64
ZFS Version	| .7.11
SPL Version	| .7.11

```
# zfs get compression,recordsize,mountpoint rpool/test
NAME        PROPERTY     VALUE       SOURCE
rpool/test  compression  off         local
rpool/test  recordsize   128K        default
rpool/test  mountpoint   /test       inherited from rpool

$ cat ./test.fio 
[global]
#files size
size=100M
ioengine=libaio
#1-sync 0-async
sync=1

[JOB]
rw=read
group_reporting
blocksize=1024k
direct=0
iodepth=1
#independent threads count
numjobs=10

$ fio ./test.fio /test/
JOB: (g=0): rw=read, bs=1M-1M/1M-1M/1M-1M, ioengine=libaio, iodepth=1
...
fio-2.16
Starting 10 processes

JOB: (groupid=0, jobs=10): err= 0: pid=16019: Wed Nov  7 17:27:09 2018
  read : io=1000.0MB, bw=5586.7MB/s, iops=5586, runt=   179msec
    slat (usec): min=154, max=31358, avg=1426.10, stdev=2935.67
    clat (usec): min=0, max=20, avg= 2.53, stdev= 1.37
     lat (usec): min=155, max=31363, avg=1435.98, stdev=2941.15
    clat percentiles (usec):
     |  1.00th=[    1],  5.00th=[    1], 10.00th=[    1], 20.00th=[    2],
     | 30.00th=[    2], 40.00th=[    2], 50.00th=[    2], 60.00th=[    3],
     | 70.00th=[    3], 80.00th=[    3], 90.00th=[    4], 95.00th=[    4],
     | 99.00th=[    7], 99.50th=[    8], 99.90th=[   19], 99.95th=[   20],
     | 99.99th=[   20]
    lat (usec) : 2=13.20%, 4=74.00%, 10=12.40%, 20=0.30%, 50=0.10%
  cpu          : usr=0.00%, sys=37.74%, ctx=305, majf=0, minf=2644
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=1000/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=1000.0MB, aggrb=5586.7MB/s, minb=5586.7MB/s, maxb=5586.7MB/s, mint=179msec, maxt=179msec
```

It's interesting what is the cause of `TestIO` behavior. I don't see a bug in ZFS for now, and prefer to close this one.

**Comment by alatteri** [comment]
Hi George... Thanks for taking the time to run your test.  But if I am interpreting the results properly, that FIO ran for less than 200ms, and only transferred 1000MB essentially from RAM.   That is quite a different situation than the testing and real-world situations I have in which I need 1500MB/s sustained indefinitely.  Since my data loads can in the multi-TBs and will not completely fit into ARC, I need to be able to count on raw disk transfer speed to achieve realtime access.  This is were I am seeing vast difference in performance of ZFS vs. raw hardware capability with XFS.

**Comment by gmelikov** [comment]
@alatteri you are free to use my fio config template and change it as you need for tests.

**Comment by woquflux** [comment]
seq-read or write with numjobs > 1 brings the illusion of high performance

**Comment by gmelikov** [comment]
@woquflux I've just repeated issuer's test by fio. Yes, benchmarks can't show you full picture.

**Comment by janetcampbell** [comment]
Look at zpool iostat -r for unaggregated 4K reads.  These may be due to indirect sync writes, which will be more common with bigger files.  Those end up fragmented from their metadata on-disk and double IOP requirements to access.

If you're still fighting this, post a zfs get all, zpool status, your kernel config, and a few seconds of "zpool iostat -r 1" while you're reading, and a few seconds while you're writing.
