### ISSUE TITLE
zfs unable to automount 

### ISSUE THREAD

**Issue by hetzbh** [openzfs/zfs#8166]
System is CentOS 7.5.1804, ZFS/SPL is 0.7.12-1 (using the RPM/YUM repo packages). Kernel is 3.10.0-862.14.4.el7.x86_64

Looks like #4722 came to visit again...

doing df -h shows a list of snapshots along with everything else. Example:

> nas2/stuff                                        4.4T  1.4T  3.1T  31% /nas2/stuff
tmpfs                                             1.6G     0  1.6G   0% /run/user/1000
nas2/stuff@zfs-auto-snap_daily-2018-11-14-0113    4.4T  1.4T  3.1T  31% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-14-0113
nas2/stuff@zfs-auto-snap_daily-2018-11-16-0147    4.4T  1.4T  3.1T  31% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-16-0147
nas2/stuff@zfs-auto-snap_daily-2018-11-15-0145    4.4T  1.4T  3.1T  31% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-15-0145
nas2/stuff@zfs-auto-snap_daily-2018-11-17-0134    4.4T  1.4T  3.1T  31% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-17-0134
nas2/stuff@zfs-auto-snap_daily-2018-11-18-0117    4.4T  1.4T  3.1T  31% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-18-0117
nas2/stuff@zfs-auto-snap_daily-2018-11-05-0146    4.1T  1.1T  3.1T  27% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-05-0146
nas2/stuff@zfs-auto-snap_daily-2018-11-06-0148    4.1T  1.1T  3.1T  27% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-06-0148
nas2/stuff@zfs-auto-snap_daily-2018-11-07-0127    4.1T  1.1T  3.1T  27% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-07-0127
nas2/stuff@zfs-auto-snap_daily-2018-11-04-0116    4.1T  1.1T  3.1T  27% /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-04-0116

journalctl shows tons of warnings:

> Dec 02 04:42:12 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-10-13-0002/nas2/stuff@zfs-auto-snap_weekly-2018-10-13-0002: 256
Dec 02 04:42:15 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_monthly-2018-09-20-0008/nas2/stuff@zfs-auto-snap_monthly-2018-09-20-0008: 256
Dec 02 04:42:16 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-02-0140/nas2/stuff@zfs-auto-snap_daily-2018-11-02-0140: 256
Dec 02 04:42:16 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-10-13-0002/nas2/stuff@zfs-auto-snap_weekly-2018-10-13-0002: 256
Dec 02 04:42:17 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_daily-2018-11-03-0109/nas2/stuff@zfs-auto-snap_daily-2018-11-03-0109: 256
Dec 02 04:42:20 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-10-13-0002/nas2/stuff@zfs-auto-snap_weekly-2018-10-13-0002: 256
Dec 02 04:42:21 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-10-27-0049/nas2/stuff@zfs-auto-snap_weekly-2018-10-27-0049: 256
Dec 02 04:42:23 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_monthly-2018-09-20-0008/nas2/stuff@zfs-auto-snap_monthly-2018-09-20-0008: 256
Dec 02 04:42:24 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-11-03-0129/nas2/stuff@zfs-auto-snap_weekly-2018-11-03-0129: 256
Dec 02 04:42:27 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_weekly-2018-10-13-0002/nas2/stuff@zfs-auto-snap_weekly-2018-10-13-0002: 256
Dec 02 04:42:31 nas2.hetzlabs.io kernel: WARNING: Unable to automount /nas2/stuff/.zfs/snapshot/zfs-auto-snap_monthly-2018-10-20-0025/nas2/stuff@zfs-auto-snap_monthly-2018-10-20-0025: 256

Trying to unmount all the snapshots won't help at all since it's coming back..
Trying to do stat of any of the above directories shows the error: object is remote.

The solution with the updatedb.conf doesn't help since I didn't have any zfs in this config file.

Any suggestions?

edit: after removing all snapshots, df -h output is back to normal, but the journalctl still shows the unable to automount errors..

**Comment by colttt** [comment]
same here:
```
Jan  8 06:25:57 zfs-serv1 kernel: [12592426.673147] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:25:58 zfs-serv1 kernel: [12592427.844705] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:25:59 zfs-serv1 kernel: [12592428.898400] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:26:00 zfs-serv1 kernel: [12592429.939463] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:26:01 zfs-serv1 kernel: [12592430.962453] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:26:01 zfs-serv1 kernel: [12592430.968970] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:26:02 zfs-serv1 kernel: [12592432.002706] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:26:04 zfs-serv1 kernel: [12592434.076151] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:26:56 zfs-serv1 kernel: [12592486.293509] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:26:57 zfs-serv1 kernel: [12592487.392469] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:26:58 zfs-serv1 kernel: [12592488.486553] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:27:00 zfs-serv1 kernel: [12592489.580488] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:27:01 zfs-serv1 kernel: [12592490.635775] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:27:01 zfs-serv1 kernel: [12592490.656972] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:27:02 zfs-serv1 kernel: [12592491.742038] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:27:04 zfs-serv1 kernel: [12592493.876427] WARNING: Unable to automount /nc_storage/localdata/.zfs/snapshot/bareos/nc_storage/localdata@bareos: 256
Jan  8 06:27:57 zfs-serv1 kernel: [12592546.721195] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:27:58 zfs-serv1 kernel: [12592547.915990] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
Jan  8 06:27:59 zfs-serv1 kernel: [12592548.966930] WARNING: Unable to automount /nc_storage/mariadb/.zfs/snapshot/bareos/nc_storage/mariadb@bareos: 256
```
my distribution is:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```
my Kernel:
```
uname -a
Linux zfs-serv1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
```
zfs version:
```
modinfo zfs
filename:       /lib/modules/4.9.0-7-amd64/updates/dkms/zfs.ko
version:        0.7.9-3~bpo9+1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     3ED35D12544F53FC04DF2C3
depends:        spl,znvpair,zcommon,zunicode,zavl,icp
retpoline:      Y
vermagic:       4.9.0-7-amd64 SMP mod_unload modversions
[...]

modinfo spl
filename:       /lib/modules/4.9.0-7-amd64/updates/dkms/spl.ko
version:        0.7.9-3~bpo9+1
license:        GPL
author:         OpenZFS on Linux
description:    Solaris Porting Layer
srcversion:     2080768537B4B3B2FA210A5
depends:        
retpoline:      Y
vermagic:       4.9.0-7-amd64 SMP mod_unload modversions
```
