### ISSUE TITLE
Incorrect disk IO caused by blk-mq direct issue can lead to file system corruption on 4.19 kernel

### ISSUE THREAD

**Issue by gmelikov** [openzfs/zfs#8191]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| any
Distribution Version	| any
Linux Kernel	| 4.19 without https://bugzilla.kernel.org/show_bug.cgi?id=201685#c255 patch
Architecture	| x86
ZFS Version	| any
SPL Version	| any

### Describe the problem you're observing

See https://bugzilla.kernel.org/show_bug.cgi?id=201685 , this issue is created to track a kernel bug.

### Describe how to reproduce the problem
4.19+ kernel with blk-mq with `cat /sys/block/*/queue/scheduler = none` may corrupt data (on any FS). ZFS may rebuild it if redundancy is available.

### Include any warning/errors/backtraces from the system logs

Eric Benoit's https://bugzilla.kernel.org/show_bug.cgi?id=201685#c180:
```
NAME                        STATE     READ WRITE CKSUM
nipigon                     ONLINE       0     0     0 
  mirror-0                  ONLINE       0     0     0 
    wwn-0x5000c5006407e87e  ONLINE       0     0    17 
    wwn-0x5000c5004e4e92a9  ONLINE       0     0     6 
```

**Comment by bunder2015** [comment]
MQ would appear to the real culprit here, as nvme uses "none" scheduler regardless of the CONFIG_SCSI_MQ_DEFAULT setting.

**Comment by kpande** [comment]
it's not guaranteed that ZFS can rebuild it. I corrupted metadata in a test pool with blk-mq on nvme.

**Comment by gmelikov** [comment]
Fixed in kernel.
