### ISSUE TITLE
Init scripts doesn't work for Debian + OpenRC setup. 

### ISSUE THREAD

**Issue by cdluminate** [openzfs/zfs#8204]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| unstable 
Linux Kernel	| 4.18.20
Architecture	| amd64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing

Unlike Gentoo, Debian doesn't use `/sbin/openrc-init` as the pid1, but still use the init program from `sysvinit-core`. As a result, executing init scripts in the openrc way on Debian won't work, that because e.g. https://github.com/zfsonlinux/zfs/blob/master/etc/init.d/zfs-zed.in#L101  assumes the system pid1 is openrc once the `/sbin/openrc-run` is detected, and sysvinit doesn't understand the openrc way.

A dirty hack is provided in https://github.com/zfsonlinux/zfs/issues/8063 which works quite well for both Debian+sysvinit and Debian+openrc setups. A better solution requires us to detect the actual init program type. According to https://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell , a possible solution may look like

```diff
-if [ ! -e /sbin/openrc-run ]; then
-the sysvinit way
-else
-the openrc way
-fi
+if [ -e /sbin/openrc-run ] && strings $(strings /proc/1/cmdline) | grep openrc >/dev/null; then
+the openrc way
+else
+the sysvinit way
+fi
```

### Describe how to reproduce the problem

1. setup Debian unstable base system
1. install zfsutils-linux (with debian init patch reverted)
2. install aptitude
3. aptitude install sysvinit-core
4. apt install openrc
5. reboot

### Include any warning/errors/backtraces from the system logs

None, but zpools will no longer be automatically imported.

**Comment by kpande** [comment]
but gentoo requires `#!/sbin/openrc-run`  be used. and on debian, OpenRC is not supported as a first class init system, only systemd is..

**Comment by gyakovlev** [comment]
nak from gentoo.

gentoo does not use `/sbin/openrc-init` by default. Users can configure it, but it's experimental and not feature-complete yet. So by default gentoo uses `sysvinit`'s `/sbin/init`, same way as debian does according to your description.

`/sbin/openrc-run` is a different beast, it's used to interpret initscripts and not related to `/sbin/init` or `/sbin/openrc-init`, don't confuse it.

again, the script checks for  `/sbin/openrc-run` and not `/sbin/openrc-init`!

**Comment by cdluminate** [comment]
> your problem seems to be that the script assumes it should be run by `/sbin/openrc-run` if it's found and creates openrc-specific start/stop functions and omits the `case` loop, but in reality you expect it to be run by `sysvinit` with openrc installed, right?

@gyakovlev  Yes. For Debian+sysvinit+openrc, it should enter the `case` code branch instead of the `openrc-run` code branch because in fact the openrc-run branch doesn't do anything because sysvinit don't recogonize the way openrc-run registers hooks.

**Comment by gyakovlev** [comment]
on gentoo system the shebang of the file is
`#!/sbin/openrc-run`, on debian it probably is  `#!/sbin/runscript` but that condition forces openrc functions despite expecting runscript. can you check it what's your shebang?

not sure what is the correct way of detecting if the script is really run under openrc as service manager, I'll check it and report back. 

we need to make sure it works in all scenarios: gentoo-sysvinit, gentoo-openrc-init, debian-sysvinit, debian-openrc, and it makes me want just create gentoo-only initscripts and don't use this fragile hackery.

**Comment by heroxbd** [comment]
`if [ ! -e /sbin/openrc-run ]` is not a predictor, a system can have OpenRC installed but not used.  This is the cause of this bug, the shebang of this script in Debian is `/bin/sh`, not `openrc-run`.

@cdluminate  `openrc-run` This has nothing to do with OpenRC-init.  

> we need to make sure it works in all scenarios: gentoo-sysvinit, gentoo-openrc-init, debian-sysvinit, debian-openrc, and it makes me want just create gentoo-only initscripts and don't use this fragile hackery.

It does not matter what PID 1 you have.  Therefore you are facing with only 2 cases here: `OpenRC` and `sysv-rc`.

**Comment by gyakovlev** [comment]
> runscript is the old name of openrc-run, they are the same thing.

yeah, I haven't used debian for a while, thanks for clarification.

> It does not matter what PID 1 you have. Therefore you are facing with only 2 cases here: OpenRC and sysv-rc.

true, I meant is the script should not make assumptions about init, but pick up correct service manager and not guess by checking if file exists. Like you said it can exists but be unused.

> This is the cause of this bug, the shebang of this script in Debian is /bin/sh, not openrc-run.

it may be a symptom, not the cause, it depends how debian wants to run the script.
seems they want to run the script under sysvinit despite having openrc installed or active.

looks like Makefile makes  (no pun intended) some assumptions about openrc the same way as initscript
https://github.com/zfsonlinux/zfs/blob/a8577bdb32e091645df901d8501e44ef50748389/etc/init.d/Makefile.am#L24-L28

I guess the if zfs package is built on a system without openrc shebang is set to `#!/bin/sh`, but the script still misses the `case` loop and tries to set openrc-specific functions.

@cdluminate @heroxbd can you help me understand  how exactly openrc is used on debian in your case?
does it replace service manager completely or it works with it in conjunction with  sysvinit and manages it's own set of services?
I checked this page https://wiki.debian.org/OpenRC and it's still not quite clear.


my current thoughts are that the script should:
if shebang is openrc - try to use openrc-run unconditionally/
if shebang is sh - never check if openrc-run is executable and create sysvinit functions.

any ideas how to correctly check the caller of the script in POSIX `sh` or `dash`, without bashisms?
bash has `$PPID`, `caller` builtin, `$BASH_SOURCE` but it seems those things can't be used in that case.

**Comment by cdluminate** [comment]
How about this patch?

```patch
Index: zfs/etc/init.d/zfs-import.in
===================================================================
--- zfs.orig/etc/init.d/zfs-import.in
+++ zfs/etc/init.d/zfs-import.in
@@ -308,8 +308,7 @@ do_start()
 
 # ----------------------------------------------------
 
-if [ ! -e /sbin/openrc-run ]
-then
+if ! (echo @SHELL@ | grep openrc 1>/dev/null 2>/dev/null); then
 	case "$1" in
 		start)
 			do_start
Index: zfs/etc/init.d/zfs-mount.in
===================================================================
--- zfs.orig/etc/init.d/zfs-mount.in
+++ zfs/etc/init.d/zfs-mount.in
@@ -199,8 +199,7 @@ do_stop()
 
 # ----------------------------------------------------
 
-if [ ! -e /sbin/openrc-run ]
-then
+if ! (echo @SHELL@ | grep openrc 1>/dev/null 2>/dev/null); then
 	case "$1" in
 		start)
 			do_start
Index: zfs/etc/init.d/zfs-share.in
===================================================================
--- zfs.orig/etc/init.d/zfs-share.in
+++ zfs/etc/init.d/zfs-share.in
@@ -58,7 +58,7 @@ do_stop()
 
 # ----------------------------------------------------
 
-if [ ! -e /sbin/openrc-run ]; then
+if ! (echo @SHELL@ | grep openrc 1>/dev/null 2>/dev/null); then
 	case "$1" in
 		start)
 			do_start
Index: zfs/etc/init.d/zfs-zed.in
===================================================================
--- zfs.orig/etc/init.d/zfs-zed.in
+++ zfs/etc/init.d/zfs-zed.in
@@ -98,7 +98,7 @@ do_reload()
 
 # ----------------------------------------------------
 
-if [ ! -e /sbin/openrc-run ]; then
+if ! (echo @SHELL@ | grep openrc 1>/dev/null 2>/dev/null); then
 	case "$1" in
 		start)
 			do_start
```

**Comment by cdluminate** [comment]
https://github.com/zfsonlinux/zfs/pull/8359
