### ISSUE TITLE
ZoL with large number of file systems

### ISSUE THREAD

**Issue by phillipp** [openzfs/zfs#821]
We have a setup where we host around 180k home directories of users on a zfs filesystem.

As filesystems are cheap in zfs and we could use the space accounting features, we are thinking about migrating the directories to a filesystem for each user.

Is such a large setup possible on linux?
Are there any gotchas?
Will this be stable?
What about the mount times on startup?
Is file system creating time linear with growing number of fs in the pool?

**Comment by mailinglists35** [comment]
@phillipp could you post an update of how it's going, ie zfs mount times, zfs list zfs snapshot etc? including hw configuration
