### ISSUE TITLE
zfs- 0.7.12 keeping flush zfs_member to parentblock

### ISSUE THREAD

**Issue by drscrewdriver** [openzfs/zfs#8219]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  MANJARO
Distribution Version	| 18.0
Linux Kernel	|  4.19.8-2-MANJARO
Architecture	| x86-64
ZFS Version	|  0.7.12
SPL Version	| 0.7.12

### Include any warning/errors/backtraces from the system logs

wipefs -n /dev/sda
DEVICE OFFSET       TYPE       UUID                 LABEL
sda    0xee779ff000 zfs_member 13548849399464694727 mainpool
sda    0xee779fe000 zfs_member 13548849399464694727 mainpool
sda    0xee779fd000 zfs_member 13548849399464694727 mainpool
sda    0xee779fc000 zfs_member 13548849399464694727 mainpool
sda    0xee779fb000 zfs_member 13548849399464694727 mainpool
sda    0xee779fa000 zfs_member 13548849399464694727 mainpool
sda    0xee779f9000 zfs_member 13548849399464694727 mainpool
sda    0xee779f8000 zfs_member 13548849399464694727 mainpool
sda    0xee779f7000 zfs_member 13548849399464694727 mainpool
sda    0xee779f6000 zfs_member 13548849399464694727 mainpool
sda    0xee779f5000 zfs_member 13548849399464694727 mainpool
sda    0xee779f4000 zfs_member 13548849399464694727 mainpool
sda    0xee779f3000 zfs_member 13548849399464694727 mainpool
sda    0xee779f2000 zfs_member 13548849399464694727 mainpool
sda    0xee779f1000 zfs_member 13548849399464694727 mainpool
sda    0xee779f0000 zfs_member 13548849399464694727 mainpool
sda    0xee779ef000 zfs_member 13548849399464694727 mainpool
sda    0xee779ee000 zfs_member 13548849399464694727 mainpool
sda    0xee779ed000 zfs_member 13548849399464694727 mainpool
sda    0xee779ec000 zfs_member 13548849399464694727 mainpool
sda    0xee779eb000 zfs_member 13548849399464694727 mainpool
sda    0xee779ea000 zfs_member 13548849399464694727 mainpool
sda    0xee779e9000 zfs_member 13548849399464694727 mainpool
sda    0xee779e8000 zfs_member 13548849399464694727 mainpool
sda    0xee779e7000 zfs_member 13548849399464694727 mainpool
sda    0xee779e6000 zfs_member 13548849399464694727 mainpool
sda    0xee779e5000 zfs_member 13548849399464694727 mainpool
sda    0xee779e4000 zfs_member 13548849399464694727 mainpool
sda    0xee779e3000 zfs_member 13548849399464694727 mainpool
sda    0x1fe        dos                             
sda    0x1d2        atari

 zpool status
  pool: mainpool
 state: ONLINE
  scan: scrub repaired 0B in 0h2m with 0 errors on Tue Dec 18 23:51:48 2018
config:

        NAME        STATE     READ WRITE CKSUM
        mainpool    ONLINE       0     0     0
          sda3      ONLINE       0     0     0

errors: No known data errors

  pool: zfspool
 state: ONLINE
  scan: resilvered 0B in 0h10m with 0 errors on Thu Dec 20 18:11:17 2018
config:

        NAME                                          STATE     READ WRITE CKSUM
        zfspool                                       ONLINE       0     0     0
          ata-HGST_HUS726T4TALE6L4_V6G26THM           ONLINE       0     0     0
          ata-HGST_HUS726T4TALE6L4_V6G26VDM           ONLINE       0     0     0
          ata-HGST_HUS726T4TALE6L4_V6G1N51M           ONLINE       0     0     0
        logs
          ata-SanDisk_SD9SB8W1T00_180988800019-part7  ONLINE       0     0     0
          ata-SanDisk_SD9SB8W1T00_180988800019-part8  ONLINE       0     0     0
        cache
          ata-SanDisk_SD9SB8W1T00_180988800019-part6  ONLINE       0     0     0

errors: No known data errors
I'm using ssd-storage sda  sda3 partition  mainpool.  Some others in my zfspool storage pool , new version of zfs keep add type=zfs_member  to parentblock . I had wipefs to clean signatures. But it back now.

**Comment by rincebrain** [comment]
This doesn't appear to be a bug, or a question.

You probably want to try and talk to people on the zfs-discuss mailing list or #zfsonlinux on Freenode.

**Comment by AndCycle** [comment]
@drscrewdriver so ... you wanna wipe sda and you didn't export your mainpool first?
