### ISSUE TITLE
Unable to split pool: Source pool must be composed only of mirrors

### ISSUE THREAD

**Issue by dioni21** [openzfs/zfs#8225]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 29
Linux Kernel	| 4.19.10-300.fc29.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.0-rc2_40_g00f198de6
SPL Version	| 0.8.0-rc2_40_g00f198de6

### Describe the problem you're observing

I'm trying to split a pool, but get error `Source pool must be composed only of mirrors`

### Describe how to reproduce the problem

```
# zpool status -vLP
  pool: tank
 state: ONLINE
  scan: scrub repaired 0B in 0 days 06:56:30 with 0 errors on Mon Dec 24 07:37:26 2018
remove: Removal of vdev 2 copied 7.77G in 0h2m, completed on Sat Dec 22 16:48:55 2018
    1.51M memory used for removed device mappings
config:

        NAME           STATE     READ WRITE CKSUM
        tank           ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            /dev/sdc1  ONLINE       0     0     0
            /dev/sdf1  ONLINE       0     0     0
        special 
          mirror-3     ONLINE       0     0     0
            /dev/dm-2  ONLINE       0     0     0
            /dev/dm-4  ONLINE       0     0     0
        logs
          mirror-1     ONLINE       0     0     0
            /dev/dm-1  ONLINE       0     0     0
            /dev/dm-3  ONLINE       0     0     0

errors: No known data errors

# zpool split -nLP tank newtank
Unable to split tank: Source pool must be composed only of mirrors

```

### Include any warning/errors/backtraces from the system logs

None that I could observe

### Extra notes

The source pool originally had a non-mirror cache vdev, but I removed it before trying to split.

Also, it had a non-mirror vdev configuration for a small time.  I was using zfs 0.7.12, but an accident made me re-add a 10TB disk as a new vdev, instead of re-attaching it as part of the original mirror.  That made me upgrade to 0.8.0-rc2 and use vdev removal features, and hence the "removed device mappings".

**Comment by behlendorf** [comment]
@dioni21 you've stumbled on to one of the cases not currently handled by the device removal code.  The vdev you previously removed from the pool is preventing the split since it was internally converted to an indirect vdev.  This is why you're seeing that error message.  The good news is that technically this pool could be split, however the code to handle splitting an indirect vdev still needs to be written.

I've tagged this as a feature request so we can more easily track it.

**Comment by dioni21** [comment]
@behlendorf Thanks for your answer.

I'll solve my current problem by creating the new pool from zero.
