### ISSUE TITLE
vdev_open maybe crash when vdev_probe return NULL

### ISSUE THREAD

**Issue by Leroy8508** [openzfs/zfs#8244]
Linux Kernel	| centos - 3.10.0-862.14.4.el7.x86_64
ZFS Version	|  master

### Describe the problem you're observing
vdev_open function has a bug, maybe NULL pointer crash
1. vdev_probe function maybe return NULL
2. zio_wait need use zio pointer, can crash when use this zio
![return_null](https://user-images.githubusercontent.com/7160777/50754797-ddaa6380-1291-11e9-9276-baddc4b2b044.png)
![use_null](https://user-images.githubusercontent.com/7160777/50754803-e307ae00-1291-11e9-9d6e-6fde4e667fc9.png)
![zio_wait](https://user-images.githubusercontent.com/7160777/50754806-e69b3500-1291-11e9-9374-c8f0794c028a.png)

**Comment by behlendorf** [comment]
Actually, the way this code is structured and called it looks like it is impossible for the `vdev_probe(vd, NULL)` call to return NULL.  When NULL is passed for the `zio_t *` a new parent zio will always be allocated and returned.  That said, this code is anything but clear when reading it casually so I wouldn't object to adding some additional error handling to `vdev_open()`.

**Comment by Leroy8508** [comment]
we found this problem, because we pulled a piece of disk from the server and loaded it over time, trigger this crash.
