### ISSUE TITLE
L2ARC won't function after multiple l2arc device add/remove cycle

### ISSUE THREAD

**Issue by AndCycle** [openzfs/zfs#8294]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| 
Linux Kernel	| 4.14.83-gentoo
Architecture	| x86-64
ZFS Version	| 0.7.12-r1-gentoo
SPL Version	| 0.7.12-r1-gentoo

little home lab server,

Intel S1200RP board with E3-1231 v3 and 32GB ECC memory,
zfs_arc_max been limited to 4GB, zfs_arc_min 2GB, 
no extra tuning for zfs module.

multiple zpool with raidz2 or mirror configuration, no dedup, only lz4 compression.
```
NAME         SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zarchive02    58T  47.2T  10.8T         -     0%    81%  1.00x  ONLINE  -
zaside      10.9T  5.89T  4.98T         -    12%    54%  1.00x  ONLINE  -
zassist      446G   174G   272G       28G    64%    38%  1.00x  ONLINE  -
zmess       27.2T  18.1T  9.19T         -    26%    66%  1.00x  ONLINE  -
zroot        444G   339G   105G         -    72%    76%  1.00x  ONLINE  -
ztank       32.5T  25.2T  7.29T         -    31%    77%  1.00x  ONLINE  -
```

### Describe the problem you're observing

no data write to L2ARC after add/remove SLOG/L2ARC device multiple times,

l2_feeds is still counting when L2ARC device present but no l2_writes_sent increment at all,
no data been written to L2ARC.

### Describe how to reproduce the problem

just playing around SLOG/L2ARC with 2 extra SSD,
keeps doing zpool add/remove slog and l2arc and repartition the SSD,
fit it for 4 zpool backed with traditional harddrive,

doing metadata heavy operation like `find /home` to test the different

then there is no data writing to L2ARC.

everything goes normal after reboot.

### Include any warning/errors/backtraces from the system logs

no error at all.

**Comment by matveevandrey** [comment]
Can confirm that faced this issue couple of time during performance testing
