### ISSUE TITLE
Feature: Allow disabling drive becoming FAULTED in read-only mode

### ISSUE THREAD

**Issue by briantopping** [openzfs/zfs#8377]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS 7
Distribution Version	| 7.6.1810
Linux Kernel	| 4.20.6-1.el7.elrepo.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.12-1
SPL Version	| 0.7.12-1
 

### Describe the problem you're observing
I am working with a raidz1 pool created under FreeBSD. I need to import that pool and copy it to a Linux file system with CPIO. Should be easy enough. I’m getting very random read errors that are faulting drives out and eventually losing data. I want the drives to stop faulting so I can finish the copy. I think it has to due with SMR drives being driven too hard and reading up neighboring tracks from head slop.

ZFS already models this behavior: If a pool is degrading ZFS won’t fault remaining drives when faulting one more drive would fault the pool. So again, if the drive is in RO mode after `--yes-i-really-really-mean-it` flag is added, why does ZFS throw away a known good arbitrator of data? The existing behavior should in fact be extended in the same way. I appreciate that the operator needs to intervene, but if this is the last means to recover data because of bad SMR drives.. 

`zpool clear` will allow all four to get back online, but then the process repeats. All four drives are fine, and when they are available, there is never any lost data. But when one is taken out of service, inevitably the three remaining drives in the raidz1 are not enough to get working copies of all files. It would have been better not to fault a drive that may well have had good data for that address.

It does seem dangerous if the system were allow writing to a drive giving errors, and it also seems dangerous to just let the drive keep going without operator indication that the drive needs attention. But disabling the drive completely is causing unnecessary, correctible errors.

### Request
This diff may hardcode the behavior I am looking for:
```
[root@centos01 zfs-0.7.12]# diff lib/libzfs/libzfs_pool.c.orig lib/libzfs/libzfs_pool.c
2651a2652,2653
> 	return (zfs_error(hdl, EZFS_NOREPLICAS, msg));
> 
```

It should force the behavior of not faulting the last good drive, but do so with all drives. (Of it's not happening at all now, so I can't be sure it's going to work.) A proper implementation would check for a feature flag and compare the OS error to determine if it was a hard fault vs. a checksum fault. If it is just an accumulation of checksum errors, don't fault the drive. (The code probably doesn't even belong in this function, I found it after 90 seconds of grepping and am kind of embarrassed I posted to the list in the first place...)

Thanks!

**Comment by rincebrain** [comment]
If you're getting random errors off your drives, that's not just SMR eccentricities, something is Wrong with your system.

It might be the drives, it might be the cables, it might be whatever SATA or SAS controller is plugged in, it might be flipping bits in RAM.

But the behavior you're describing Should Not Happen.

**Comment by richardelling** [comment]
zed is responsible for retiring failing drives. Ideally, the tunables for the SERD engine would be 
tunable. But for now they are hard-coded in the source, zfs_diagnosis.c.

For this case, as a workaround, have you tried disabling zed?

**Comment by rincebrain** [comment]
Sure, I wasn't trying to suggest this feature had no value, I just wanted to address the apparent assumption that this was a Normal Thing for SMR drives to do.

**Comment by briantopping** [comment]
> Sure, I wasn't trying to suggest this feature had no value, I just wanted to address the apparent assumption that this was a Normal Thing for SMR drives to do.
Thanks, I've been operating on very little sleep, my initial response was unnecessary, apologies again. 

The replacement chassis has no errors after 24 hours of copying, so I'm sure you were correct. The old chassis is a few hours in to using a different SFF cable to the backplane, but only with kernel `md` and running https://github.com/ncw/stressdisk. It will run for another few hours before filling the disks and proceeding apace with some unknown strategy, but so far, nothing concerning from `dmesg`. The `md` resilver was running at 225MB/sec, I just don't know it's feedback loop and whether it knows whether everything written is valid. `stressdisk` should provide that information when it finally fills the array.

**Comment by briantopping** [comment]
@richardelling Thanks for the input. I'll look there for any changes to offer as a contribution. 

I had not tried disabling `zed`, although I think it was mentioned on-list. This is really my first experience with Linux ZFS and AFAIC it's been flawless (but I wouldn't know how to disable `zed` as a result). Admittedly I've been moving to Ceph due to requirements changes, but I'm still recommending ZFS in different contexts. This has been a very valuable experience and now that FUSE is not necessary, it's pretty easy to advocate for. Nice work!

**Comment by ExceptionGit** [comment]
How disable "auto FAULTED" behavior in zed (without disabling zed) when i get read/write errors?
