### ISSUE TITLE
consider to use kvmalloc instead of vmalloc at frequent allocations (especially kmem_cache_alloc)

### ISSUE THREAD

**Issue by BrainSlayer** [openzfs/zfs#8382]
this is no bug report, but while studying the zfs code i found out that the current vmem handling isnt well handled and inefficient. especially for larger allocations kmem is still available but blocked to be used since kmem might have higher expense on seeking large continous memory. this is somewhat true, but there is a better aproach than just using vmalloc since vmalloc has a higher  overhead than kmalloc. in 4.12. the linux kernel introduced kvmalloc which tries basicly to allocate even large blocks with kmalloc and falls back to vmalloc if fail. but with kmalloc allocation is done with __GFP_NORETRY flag which does solve than problem.

i see a high potential for performance enhancements in the spl own kmem_cache implementation using this approach
in the current zstd implementation i write i'm working already on a proposal of such a conditional implementation in kmem_cache_create and a optional kvmem_alloc allocator including a kvmalloc implemenation for older kernels

for reference see https://lwn.net/Articles/711653/

**Comment by richardelling** [comment]
Agree, there is work to be done in this area. How can people assist?

**Comment by BrainSlayer** [comment]
i'm already working on base of my zstd tree since it has the most effect here due the frequent context and workspace allocations. and with working i mean its done already, but i'm still benchmarking and doing stress tests. when its done i can split it up to create a new pull request. i also changed parts of some other zfs codeparts where vmem_alloc is used, but not required at all. you may review my changes here. this is the commit with my current kvmalloc changes in zfs https://github.com/BrainSlayer/zfs/commit/d49a20921b498071af520aac8aa974e7e16b9bdb

**Comment by behlendorf** [comment]
It would be great if you could split this improvement out in to its own PR.  And as always performance results are welcome!  This could definitely be useful for the spl's kmem cache.

Let me add this might not be as bad as it first appears, at least for `vmem_alloc()`.  The `vmem_alloc()` functions are written such that for any allocation smaller than 2M a `kmalloc()` will be attempted first.  Only when that fails do we fallback to using `vmalloc()`.  This has the advantage of letting us use `vmem_alloc()` when we know the allocation could be large, but we only pay the worst of the performance penalty when it actually is.   See the comment in `include/spl/sys/vmem.h`.

The other thing to be aware of here is that the code depends on the fact that `kmem_alloc()` must **never** call `vmalloc()`.  Doing so will introduce deadlocks in various call paths.

**Comment by BrainSlayer** [comment]
yes, it tries kmalloc but its implemented in a bad way. because you try 
to alloc with with kmalloc but without noretry flag.
at memory pressure that means kmalloc may slow down the allocation since 
it will retry several times until it gets a allocated block.
thats the difference with kvmalloc which is more lazy here with kmalloc 
to avoid allocation delays.

btw. the vmalloc implementation is also not optimal. you missed to mask 
__GFP_HIGHMEM as gfp flag at __vmalloc
i corrected this. this might not be important for x64, but for i386 its 
important and for mips cpus its absolute requirement.
mips has a 512 mb limitation without highmem, but some cpu 
implementations already limit it at 128mb. everything higher
is only accessible with highmem.

but the main change i made is introducing KMC_KVMEM for 
kmem_cache_create and i also will use kvmalloc instead of vmalloc for 
KMC_VMEM
case if GFP_KERNEL is masked. (kvmalloc is undefined for other cases). 
so KM_PUSHPAGE und KM_SLEEP kmem_cache_alloc will make use of kvmalloc
ah and yes i'm aware of never using vmalloc in that context. my 
alternate spl_kvmalloc implementation for older kernels does make use of 
__vmalloc
but basicly there is no real reason for. vmalloc is basicly identical 
with __vmalloc. vmalloc does GFP_KERNEL|GFP_HIGHMEM, __vmalloc allows 
you to specify
own flags. but thats the only difference. i dont know why there should 
be deadlocks here. its unlikelly with vmalloc.

Am 06.02.2019 um 23:19 schrieb Brian Behlendorf:

**Comment by BrainSlayer** [comment]
btw. this would be the correction for the allocation delay problem if 
KM_SLEEP is used (KM_NOSLEEP already masks noretry)

--- a/module/spl/spl-kmem.c
+++ b/module/spl/spl-kmem.c
@@ -223,7 +223,11 @@ spl_kmem_alloc_impl(size_t size, int flags, int node)
                                 return (NULL);
                         }
                 } else {
-                       ptr = kmalloc_node(size, lflags, node);
+                       if (flags & KM_VMEM)
+                               ptr = kmalloc_node(size,
+                                   lflags | __GFP_NORETRY, node);
+                       else
+                               ptr = kmalloc_node(size, lflags, node);
                 }

                 if (likely(ptr) || (flags & KM_NOSLEEP))

Am 06.02.2019 um 23:19 schrieb Brian Behlendorf:

**Comment by BrainSlayer** [comment]
damn. can't do a pull request since i cannot fork zfs a second time. and my other repo has zstd builtin. but since i posted already the patch link here. is someone able to work on that base or todo a review on it?

**Comment by kpande** [comment]
@BrainSlayer i don't understand, can you make a new branch using `git checkout -b <new branch name>`? you can add the zfsonlinux/zfs repo as a remote and `git reset --hard zfsonlinux/master` in your new branch.

**Comment by BrainSlayer** [comment]
@kpande 
git remote add upstream https://github.com/zfsonlinux/zfs.git
git reset --hard upstream/master
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.

**Comment by kpande** [comment]
oops, you need a `git fetch upstream`.

**Comment by kpande** [comment]
btw, `git reset --hard` removes local changes. `git reset` without will reposition git history and unstaged any differences locally. I'm not 100% sure what you're trying to accomplish here, but beware it can remove your modifications.

**Comment by BrainSlayer** [comment]
consider the following. i have a fork of zfs with ongoing development which has not been merged but is on master. this development is going on over many months now. removing them all would take days. now i made a new branch and fetched the upstream. but now git says " The current branch vmem_alloc has no upstream branch." blahblah. git push --set-upstream origin vmem_alloc but whatever i set. now it asks for a password. github is shithub

**Comment by BrainSlayer** [comment]
whoops my fault. need to use ssh of course

**Comment by kpande** [comment]
well, in `git config -e` you can make sure the `[origin]` section looks like this:

```
[remote "origin"]
        url = ssh://git@github.com/username/zfs.git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by BrainSlayer** [comment]
i did it already exact in that way. pull request is already done. thank you for support. (git and i will never be friends)

**Comment by kpande** [comment]
thanks for the PR!

**Comment by c0d3z3r0** [comment]
#8384
