### ISSUE TITLE
F29 : Black screen, kernell dead

### ISSUE THREAD

**Issue by pierreblavy2** [openzfs/zfs#8388]
### System information

Version | Fedora29

 --- | --- 
Distribution Name	|  Fedora
Distribution Version	| 4.20.6-200.fc29.x86_64
Linux Kernel	| 4.20.6-200.fc29.x86_64
Architecture	| x86_64
ZFS Version	| zfs, 0.7.12 
SPL Version	| spl, 0.7.12

### Describe the problem you're observing
After a fresh new install of fedora 29 + zfsonlinux, the system refuse to boot, instead few seconds after GRUB there is a blakc screen (no error can be read).

### Describe how to reproduce the problem
Install fedora 29
dnf install kernel-devel zfs;

### Other info
WORKAROUND1 : boot in safe mode, you'll not have access to zfs, but at least you can boot on something.

EDIT (after mskarbek's comment)
WORKAROUND2 : see https://github.com/zfsonlinux/zfs/issues/8388#issuecomment-461834937

**Comment by mskarbek** [comment]
First things first - 0.7.12 is not compatible with kernel 4.20, if you want to use ZFS on Fedora manually install kernel 4.19.15 (https://koji.fedoraproject.org/koji/buildinfo?buildID=1179413) and lock kernel updates until 0.7.13 is released.
Second `zfs` package should not depend on DKMS. ZFS can be installed with kmod or dkms modules, enforcing `dkms` in `zfs` will bring unnecessary and undesired dependencies when installed with kmod modules packages.

**Comment by pierreblavy2** [comment]
Thank for the quick answer. I'll try to downgrade my kernell.

#doc : https://fedoramagazine.org/install-kernel-koji/
dnf install \
  https://kojipkgs.fedoraproject.org//packages/kernel/4.19.15/300.fc29/x86_64/kernel-4.19.15-300.fc29.x86_64.rpm\
  https://kojipkgs.fedoraproject.org//packages/kernel/4.19.15/300.fc29/x86_64/kernel-core-4.19.15-300.fc29.x86_64.rpm\
  https://kojipkgs.fedoraproject.org//packages/kernel/4.19.15/300.fc29/x86_64/kernel-modules-4.19.15-300.fc29.x86_64.rpm

**Comment by f1yankees** [comment]
Hello,

Thank you for posting as this fixed my issue with 0.7.12 and worked perfectly.

I noticed that 0.7.13 has been released - is it safe to progress to this version now and allow the kernel to update to 4.20?  If so, what is the best way to proceed?  Thanks!

**Comment by mskarbek** [comment]
First, update ZFS and then update the kernel to 4.20.

**Comment by devZer0** [comment]
0.7.13 is (as the readme tells)    "Compatible with 2.6.32 - 5.0-rc3 Linux kernels."
