### ISSUE TITLE
zpool corrupt metadata improve error message

### ISSUE THREAD

**Issue by tehsu** [openzfs/zfs#8411]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  ArchLinux
Distribution Version	|  latest, rolling
Linux Kernel	|  4.20.6-arch1-1-ARCH
Architecture	| AMD64
ZFS Version	| 0.7.12_4.20.6.arch1.1-1]
SPL Version	| 0.7.12_4.20.6.arch1.1-1

### Describe the problem you're observing
This is pretty simple, if any one of my mirrors disappears, for example I have 3 mirrors and only 2 are available, ZFS says the metadata is corrupted and needs to be destroyed and recreated, it slipped my mind that I had 3 mirrors and thought the 2 were normal and I was at a loss with my data. Everything points to lost data as shown below, trying to clear it using 'zpool clear zpool' returns no such pool. Finally, I ran a 'zdb' and found that I have 3 mirrors instead of 2, so I went and checked my drives and something was a little loose and after a reboot I was back in action. It could of been bad if I just recreated it, maybe a good addition would be to show missing disks when a mirror goes missing not just remove it from the zpool status/import commands.

zpool import
   pool: zpool
     id:
  state: FAULTED
 status: The pool metadata is corrupted.
 action: The pool cannot be imported due to damaged devices or data.
	The pool may be active on another system, but can be imported using
	the '-f' flag.
   see: http://zfsonlinux.org/msg/ZFS-8000-72
 config:

     zpool                                           FAULTED  corrupted data

### Describe how to reproduce the problem
Pull a mirror out of the pool and boot it up

**Comment by bunder2015** [comment]
This may be correct, however ZFS-8000-3C (ZPOOL_STATUS_MISSING_DEV_NR) might be more appropriate.  Can you give us more information about your setup?  You seem to have removed the issue template.  Thanks

**Comment by tehsu** [comment]
updated
