### ISSUE TITLE
SPL/ZFS RPM KMOD build issue with custom kernel on Fedora 29

### ISSUE THREAD

**Issue by ianc1215** [openzfs/zfs#8425]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 29 
Linux Kernel	| 4.19.23_1.fc29.xen+-1 (built from upstream source)
Architecture	| x86_64
ZFS Version	| 0.7.12-1
SPL Version	| 0.7.12-1

### Describe the problem you're observing
I am trying to build SPL and ZFS kmods for Fedora 29. I am building them against a custom kernel I built from upstream source (kernel.org). When I run `/.configure --with-linux=/usr/src/kernels/4.19.23-1.fc29.xen+/ --with-linux-obj=/usr/src/kernels/4.19.23-1.fc29.xen+/` the configuration completes with not errors.
When I run the `make rpm-kmod` however I receive an error stating the following;
```
Installing spl-kmod-0.7.12-1.fc29.src.rpm
error: Failed build dependencies:
	kernel-devel-uname-r = 4.19.23-1.fc29.xen+ is needed by spl-kmod-0.7.12-1.fc29.x86_64
make[1]: *** [Makefile:1098: rpm-common] Error 1
make[1]: Leaving directory '/home/ian/src/spl'
make: *** [Makefile:1049: rpm-kmod] Error 2
```
However, if I comment out these lines in `spl/scripts/kmodtool` the build completes with no errors.
```
Requires:         kernel-uname-r = ${kernel_uname_r} (line 168)
BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r} (line 169)
Requires:         kernel-devel-uname-r = ${kernel_uname_r} (line 282)
BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r} (line 283)
```
I receive the same error with a few more build dependancy failures for the zfs module.
```
Installing zfs-kmod-0.7.12-1.fc29.src.rpm
error: Failed build dependencies:
	kernel-devel-uname-r = 4.19.23-1.fc29.xen+ is needed by zfs-kmod-0.7.12-1.fc29.x86_64
	kmod-spl-devel = 0.7.12 is needed by zfs-kmod-0.7.12-1.fc29.x86_64
	kmod-spl-devel-uname-r = 4.19.23-1.fc29.xen+ is needed by zfs-kmod-0.7.12-1.fc29.x86_64
	kmod-spl-uname-r = 4.19.23-1.fc29.xen+ is needed by zfs-kmod-0.7.12-1.fc29.x86_64
make[1]: *** [Makefile:1227: rpm-common] Error 1
make[1]: Leaving directory '/home/ian/src/zfs'
make: *** [Makefile:1178: rpm-kmod] Error 2
```
Same thing for `zfs/scripts/kmodtool` the build completes with no errors
```
Requires:         kernel-uname-r = ${kernel_uname_r} (line 168)
BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r} (line 169)
Requires:         kernel-devel-uname-r = ${kernel_uname_r} (line 282)
BuildRequires:    kernel-devel-uname-r = ${kernel_uname_r} (line 283)
Requires:        kmod-${kmodname}-${kernel_uname_r} >= %{?epoch:%{epoch}:}%{version}-%{release} (line 314)
```
It should be noted, I am not actually running on this kernel while I am compiling. I have only installed the bare essentials to run a kmod build for another system which I do not want the build tools on.

### Describe how to reproduce the problem
If I use a modified `scripts/kmodtool` the build completes. If I restore the original `scripts/kmodtool` the builds begin to fail again.

I had also found a previous open ticket referring to the exact same problem on a different system.
https://github.com/zfsonlinux/zfs/issues/2046

**Comment by ianc1215** [comment]
I think I might have come up with a way to get around this issue. Since I building a custom kernel that includes `zfs.ko` technically the linux kernel is providing zfs-kmod to the system. I made an alteration to the script `linux-kernel-src/scripts/package/mkspec` That way when a new rpm is generated from the linux source the package tells rpm that it provides zfs-kmod.

I would consider this a hack since I am not sure this the best way or would this be worthy of a patch? I was thinking the code could be added to the `copy-builtin` script, That way whenever the zfs code is copied over it updates the script with the appropriate version.

**Comment by mskarbek** [comment]
The best way would be to produce correct kernel packages that follow Fedora convention. That way you will produce required `kernel`, `kernel-core` and `kernel-devel` packages which will fulfill `zfs` and `kmod-zfs` packages build and install requirements.

**Comment by ianc1215** [comment]
Without dragging this out any how one does that? All of the documentation I have found so far is old.
