### ISSUE TITLE
kernel 5.0 CONFIG_IOSCHED_NOOP was removed

### ISSUE THREAD

**Issue by prometheanfire** [openzfs/zfs#8427]
upstream removed the option, I'm not sure what should be done right now other than removing the check.

https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/commit/?h=for-4.21/block&id=f382fb0bcef4c37dc049e9f6963e3baf204d815c

**Comment by h1z1** [comment]
How on EARTH is that considered legacy??  CFQ and deadline were removed too.

**Comment by prometheanfire** [comment]
None still exists (nvme drive defaulted to it).  the mq stuff has taken over it seems...

    [none] mq-deadline kyber bfq

**Comment by bunder2015** [comment]
I'm working on a PR to update dracut to default to none, then noop for partitioned pools, based off a similar function in initramfs.  They'll probably want to pick up the change as well, along with a couple module bits (ie vdev_elevator_switch)

**Comment by richardelling** [comment]
Rather than try to fix this, let's deprecate the vdev_elevator_switch altogether. That work should be done by a sysadmin and trying to keep up with this over time as schedulers come and go isn't sustainable.

**Comment by bunder2015** [comment]
I think that's a little premature since other than adding new schedulers we don't care about, this is the first time they've changed the one we do use... but in the meantime I've pushed through the PR for dracut.

**Comment by prometheanfire** [comment]
linked?

**Comment by bunder2015** [comment]
It was suggested in 8436 that writing udev rules to force the scheduler would be a better way to go.  In theory we could drop the dracut/initrd code as well as the bits in the modules.

**Comment by nabijaczleweli** [comment]
I think this can be closed – neither dracut nor i-t set the scheduler, and `zfs_vdev_scheduler` was removed alongside `vdev_elevator_switch`.
