### ISSUE TITLE
zfs create/destroy/mount bad scalability with respect to number of mounted datasets

### ISSUE THREAD

**Issue by baryluk** [openzfs/zfs#845]
With about 1000 datasets on my zfs pool, it takes about 20 seconds to create new one, or to mount one more.
zfs import or zfs mount -a can take about hour.

I belive bug is in mount.zfs, which checks /etc/mtab and /proc/mounts multiple times
and updates this files. This extremally unacassary, and makes
zfs mount/create/destroy/import extermally slow when system or zfs have multiple mounted datasets.

Solution would be to have a something better than plain linear
structure in mtab, or better just ignore mtab at all, and try to mount without checking
if it is mounted, and do checking only in case of error.

```
root@lavinia:~# time zpool import smptank3

real    22m18.381s
user    2m34.898s
sys 19m9.852s
root@lavinia:~# zfs list | wc -l
722

root@lavinia:~# time zfs create smptank3/a

real    0m4.796s
user    0m0.888s
sys 0m3.420s
```

Precise measurments visualised on this plot  http://i.imgur.com/oZGlb.png

strace zfs create / mount, shows that big amount of time is spent on reading/writing to /etc/mtab.

```

open("/dev/zfs", O_RDWR)                = 4
open("/etc/mtab", O_RDONLY)             = 5
open("/etc/dfs/sharetab", O_RDONLY)     = 6
open("/etc/dfs/sharetab", O_RDONLY)     = 7
close(7)                                = 0
lseek(5, 0, SEEK_SET)                   = 0
read whole file
lseek(5, 0, SEEK_SET)                   = 0
read whole file
lseek(5, 0, SEEK_SET)                   = 0
read whole file
lseek(5, 0, SEEK_SET)                   = 0
read whole file
...
/// exactly 724 lseeks + full file reads, which is equal to number of already mounted datases
...

open("/etc/dfs/sharetab.wAwWn4", O_RDWR|O_CREAT|O_EXCL, 0600) = 7
lseek(7, 0, SEEK_CUR)                   = 0
close(7)                                = 0
close(4)                                = 0
close(5)                                = 0
close(6)                                = 0

...

open("/etc/mtab", O_RDONLY)             = 9
open("/etc/dfs/sharetab", O_RDONLY)     = 10
open("/etc/dfs/sharetab", O_RDONLY)     = 11
close(11)                               = 0
lseek(9, 0, SEEK_SET)                   = 0
lseek(9, 0, SEEK_SET)                   = 0
lseek(9, 0, SEEK_SET)                   = 0
lseek(9, 0, SEEK_SET)                   = 0

// similary 724 lseeks

close(5)                                = 0
close(6)                                = 0
close(7)                                = 0
open("/etc/dfs/sharetab.BQrkk0", O_RDWR|O_CREAT|O_EXCL, 0600) = 5
lseek(5, 0, SEEK_CUR)                   = 0
close(5)                                = 0
close(8)                                = 0
close(9)                                = 0
close(10)                               = 0
close(4)                                = 0
```

aftear each lseek, a whole /etc/mtab file is read.

/etc/mtab  should be read only once, and stored in memory.
If possible it should be not used at all. Just try to mount, if it fails, check why,
if it successed, just append proper line to /etc/mtab (with proper file locking).

Thanks,
Witek

**Comment by mailinglists35** [comment]
I have 600 datasets in a 30% fragmented mirror pool build from two regular 1Tb sata drives, operating in an old system (intel Q33 Express chipset with 4Gb of ram and core2duo  E8200  @ 2.66GHz).
zpool import takes more than 30 seconds.

what are expected numbers (like, let's assume ZOL code is perfect and there's nothing can be done to speed it up) per create/destroy/mount operation given the above configuration? (create was much slower, took some several minutes)

Also, I've noticed a few seconds (3-4) from total are consumed by "systemd --user" when mount command is running (mount takes 0..1% cpu and systemd process takes 20% for each opened login session - and this multiplies with number of login shells I have open - near the end of the import operation when zfs code has finished initialization and waits for mount to finish) - is this normal or should I file an issue to systemd?

**Comment by Rudd-O** [comment]
This may be worthy of another bug, @mailinglists35.

**Comment by mailinglists35** [comment]
@behlendorf is it normal/expected on latest release (which already has mtab cache enabled) to still observe `zfs create` reading mtab as many times as the number of existing datasets?

    root@linux:/usr/local/src/zfs-linux-0.6.5.7# time strace -f zfs create pool/test > /tmp/create 2>&1
    
    real    0m13.391s
    user    0m0.228s
    sys     0m12.632s
    
    root@linux:/usr/local/src/zfs-linux-0.6.5.7# time strace -f zfs list > /tmp/list 2>&1     
    real    0m12.356s
    user    0m0.144s
    sys     0m11.920s
    
    root@linux:/usr/local/src/zfs-linux-0.6.5.7# grep -c mtab /tmp/create /tmp/list
    /tmp/create:1638
    /tmp/list:1
