### ISSUE TITLE
CHKSUM errors in pool, but not in drives.

### ISSUE THREAD

**Issue by capnbb** [openzfs/zfs#8480]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Scientific Linux 
Distribution Version	|  7.6
Linux Kernel	| 3.10.0-957.5.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.12-1
SPL Version	| 0.7.12-1

### Describe the problem you're observing
Following a hardware fault (bad SAS expander) we started seeing CHKSUM errors at the VDEV level, but *not* at the disk level, zpool status would also report:
 
"errors: Permanent errors have been detected in the following files:"

Multiple rounds of "zpool clear, zpool scrub" could not repair the CHKSUM errors.

Deleting the corrupt files, and restoring them from backup appeared to work, however other files or inodes would later be listed as corrupt if we re-ran zpool scrub.

This pool had other problems (ZFS refused to allow us to remove the hot-spare drives that had been pulled into the array during the fault), making us think that the pool needed to be wiped.
In an attempt to fix the issue, the contents of the pool were pushed to a second server. This failed due to the CHKSUM errors, but as rsync'ing 400TB data would have taken a month, and broken sync with our snapshot backups, we forced the push using:
echo 1 > /sys/module/zfs/parameters/zfs_send_corrupt_data ignore

This initially appeared to work fine. So the original server's pool was wiped and rebuilt, and the pool pushed back to it.

Unfortunately, after running zpool scrub, we again saw CHKSUM errors at the VDEV level, but not at the disk level.
What makes things worse, is that in addition to seeing this on the original server, we started seeing this error on the second server which the pool was copied to, and both of the backup servers that we use for keeping snapshots, even after deleting the copied pool.

Disabling drive write cache, and setting /sys/module/zfs/parameters/zfs_vdev_raidz_impl to [original].
have no effect.

Using zdb to looking at one of the corrupt files:
root@dstore1 ~]# stat -c'%i' /file/name/redacted/xyz
2377712
[root@dstore1 ~]# zdb -bbbbb dstore1 2377712
Dataset mos [META], ID 0, cr_txg 4, 3.30G, 1533 objects

Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type

zdb: dmu_bonus_hold(2377712) failed, errno 2

"zpool events -v" during a scrub shows a great deal
 due to it's size I have copied the contents to:
<http://p.ip.fi/wwco>

This problem was previously reported at the end of https://github.com/zfsonlinux/zfs/issues/5018 
but as this may be a different issue, I have been asked to post as a new ticket.

zpool status
```
[root@dstore1 ~]# zpool status -v
  pool: dstore1
 state: ONLINE
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 51h50m with 21 errors on Wed Mar  6 16:01:48 2019
config:

	NAME                        STATE     READ WRITE CKSUM
	dstore1                     ONLINE       0     0    21
	  raidz1-0                  ONLINE       0     0     4
	    wwn-0x5000cca254df6d38  ONLINE       0     0     0
	    wwn-0x5000cca254e12b37  ONLINE       0     0     0
	    wwn-0x5000cca254e10426  ONLINE       0     0     0
	    wwn-0x5000cca254e4b029  ONLINE       0     0     0
	    wwn-0x5000cca254df5910  ONLINE       0     0     0
	    wwn-0x5000cca254e48bd1  ONLINE       0     0     0
	    wwn-0x5000cca254df6f34  ONLINE       0     0     0
	    wwn-0x5000cca23bd9cd86  ONLINE       0     0     0
	  raidz1-1                  ONLINE       0     0     4
	    wwn-0x5000cca23bda212a  ONLINE       0     0     0
	    wwn-0x5000cca254e4e2fb  ONLINE       0     0     0
	    wwn-0x5000cca254dfd8b8  ONLINE       0     0     0
	    wwn-0x5000cca254e1e184  ONLINE       0     0     0
	    wwn-0x5000cca254e4c80d  ONLINE       0     0     0
	    wwn-0x5000cca254e15a33  ONLINE       0     0     0
	    wwn-0x5000cca23bd9cd83  ONLINE       0     0     0
	    wwn-0x5000cca254e4da90  ONLINE       0     0     0
	  raidz1-2                  ONLINE       0     0     6
	    wwn-0x5000cca23bda11df  ONLINE       0     0     0
	    wwn-0x5000cca23bd96da0  ONLINE       0     0     0
	    wwn-0x5000cca254e44ee8  ONLINE       0     0     0
	    wwn-0x5000cca254e4e5f3  ONLINE       0     0     0
	    wwn-0x5000cca23bda0b91  ONLINE       0     0     0
	    wwn-0x5000cca23bd9e2fb  ONLINE       0     0     0
	    wwn-0x5000cca23bd9cf02  ONLINE       0     0     0
	    wwn-0x5000cca23bd9f0a0  ONLINE       0     0     0
	  raidz1-3                  ONLINE       0     0     6
	    wwn-0x5000cca23bd9dcf4  ONLINE       0     0     0
	    wwn-0x5000cca23bd9b599  ONLINE       0     0     0
	    wwn-0x5000cca23bd9afd5  ONLINE       0     0     0
	    wwn-0x5000cca254e1e1c7  ONLINE       0     0     0
	    wwn-0x5000c500916fdc96  ONLINE       0     0     0
	    wwn-0x5000cca254df67ff  ONLINE       0     0     0
	    wwn-0x5000cca254dfcbbe  ONLINE       0     0     0
	    wwn-0x5000cca254df66e3  ONLINE       0     0     0
	  raidz1-4                  ONLINE       0     0     4
	    wwn-0x5000cca254e4e864  ONLINE       0     0     0
	    wwn-0x5000cca254e4e1d0  ONLINE       0     0     0
	    wwn-0x5000cca254de02bc  ONLINE       0     0     0
	    wwn-0x5000cca254e4b119  ONLINE       0     0     0
	    wwn-0x5000cca254df6797  ONLINE       0     0     0
	    wwn-0x5000cca254e1e1d9  ONLINE       0     0     0
	    wwn-0x5000cca254e4e5fc  ONLINE       0     0     0
	    wwn-0x5000cca254e400e3  ONLINE       0     0     0
	  raidz1-5                  ONLINE       0     0     0
	    wwn-0x5000cca254e4e1e6  ONLINE       0     0     0
	    wwn-0x5000cca254df675b  ONLINE       0     0     0
	    wwn-0x5000cca254e48bae  ONLINE       0     0     0
	    wwn-0x5000cca254e15cc2  ONLINE       0     0     0
	    wwn-0x5000cca254df8484  ONLINE       0     0     0
	    wwn-0x5000cca254dfa556  ONLINE       0     0     0
	    wwn-0x5000c50093639a7b  ONLINE       0     0     0
	    wwn-0x5000cca23bd99add  ONLINE       0     0     0
	  raidz1-6                  ONLINE       0     0     6
	    wwn-0x5000cca254df5930  ONLINE       0     0     0
	    wwn-0x5000cca254e4e197  ONLINE       0     0     0
	    wwn-0x5000cca254e485ff  ONLINE       0     0     0
	    wwn-0x5000c500b006ed04  ONLINE       0     0     0
	    wwn-0x5000cca23bd95bfd  ONLINE       0     0     0
	    wwn-0x5000cca254e158cd  ONLINE       0     0     0
	    wwn-0x5000cca254e17ea9  ONLINE       0     0     0
	    wwn-0x5000cca23bd980bb  ONLINE       0     0     0
	  raidz1-7                  ONLINE       0     0     6
	    wwn-0x5000cca254e48b4d  ONLINE       0     0     0
	    wwn-0x5000cca254e1c2bc  ONLINE       0     0     0
	    wwn-0x5000cca254df5019  ONLINE       0     0     0
	    wwn-0x5000cca254e4e1d6  ONLINE       0     0     0
	    wwn-0x5000cca254e4e18d  ONLINE       0     0     0
	    wwn-0x5000cca254e4b0f7  ONLINE       0     0     0
	    wwn-0x5000cca254df6e60  ONLINE       0     0     0
	    wwn-0x5000cca254df7102  ONLINE       0     0     0
	  raidz1-8                  ONLINE       0     0     6
	    wwn-0x5000cca254e14a51  ONLINE       0     0     0
	    wwn-0x5000cca254df66f9  ONLINE       0     0     0
	    wwn-0x5000cca254e0a0bd  ONLINE       0     0     0
	    wwn-0x5000cca254e4e23b  ONLINE       0     0     0
	    wwn-0x5000cca254e4c7a7  ONLINE       0     0     0
	    wwn-0x5000cca254df5902  ONLINE       0     0     0
	    wwn-0x5000cca23bca301b  ONLINE       0     0     0
	    wwn-0x5000cca254e4b117  ONLINE       0     0     0
	  raidz1-9                  ONLINE       0     0     0
	    wwn-0x5000cca254e4253b  ONLINE       0     0     0
	    wwn-0x5000cca254df6807  ONLINE       0     0     0
	    wwn-0x5000c50093637383  ONLINE       0     0     0
	    wwn-0x5000cca254e4e2fd  ONLINE       0     0     0
	    wwn-0x5000cca254e1e1db  ONLINE       0     0     0
	    wwn-0x5000cca254df8379  ONLINE       0     0     0
	    wwn-0x5000cca254e4e1e5  ONLINE       0     0     0
	    wwn-0x5000cca254df5984  ONLINE       0     0     0
	  raidz1-10                 ONLINE       0     0     0
	    wwn-0x5000cca254dfc4e5  ONLINE       0     0     0
	    wwn-0x5000cca254dfc5f8  ONLINE       0     0     0
	    wwn-0x5000cca23bda0d2d  ONLINE       0     0     0
	    wwn-0x5000cca23bd9b44c  ONLINE       0     0     0
	    wwn-0x5000cca23bd9dda2  ONLINE       0     0     0
	    wwn-0x5000cca254e4af06  ONLINE       0     0     0
	    wwn-0x5000cca254e4b11a  ONLINE       0     0     0
	    wwn-0x5000cca254e48d30  ONLINE       0     0     0
	cache
	  nvme0n1                   ONLINE       0     0     0
	spares
	  wwn-0x5000cca254df67bb    AVAIL   
	  wwn-0x5000cca254e49595    AVAIL   

errors: Permanent errors have been detected in the following files:

        <0x4>:<0x23c310>
        <0x4>:<0x23c41a>
        <0x4>:<0x2637a5>
        <0x4>:<0x231ca8>
        <0x4>:<0x23bbd1>
        <0x4>:<0x210fd5>
        <0x4a7>:<0x31551b>
        <0x4a7>:<0x31551d>
        <0x4a7>:<0x2bfc9a>

```
Any help or ideas appreciated!

Jake

**Comment by behlendorf** [comment]
> CHKSUM errors at the VDEV level, but not at the disk level

This could be better explained in the documentation.  But when the error is reported for the raidz vdev and _not_ an individual disk it indicates the correct block (matching checksum) could not be reconstructed from the parity data.  Or in other words the damage exceeds the available number of parity devices.  Without a valid copy of the block it's impossible to determine which of the disks is contributing incorrect data so no checksum errors are attributed to individual disks.

This is unfortunately why you're seeing permanent errors in some files.  Those blocks just can't be repaired.

From your description of the hardware fault it sound like it's _possible_ the failing SAS expander may have resulted in some writes not making it to disk.  That would cause damage like this, and depending on how many writes were being lost it could easily go unnoticed until that data was read back.

**Comment by capnbb** [comment]
Hi Brian - many thanks for taking time to explain what is going on.

I've tried deleting the corrupt files, but running scrub shows errors in inodes; see above zpool status.

Is there anyway of restoring the pool to health? Or do we have to rsync the data to another server,  wipe the pool, and then restore? This will be a very slow process as each server has 430TB, as do their backup servers.

again, many thanks for your advice.
