### ISSUE TITLE
vdev_enc_sysfs_path not validated on startup

### ISSUE THREAD

**Issue by IainCollins262** [openzfs/zfs#8512]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.6
Linux Kernel	| 3.10.0-957.el7.x86_64
Architecture	| x86_64
ZFS Version	| zfs-0.7.13-1.el7_6.x86_64
SPL Version	| spl-0.7.13-1.el7_6.x86_64

### Describe the problem you're observing
I have a zpool.cache file which contains references to vdev_enc_sysfs_path paths which are no longer valid. The zpool itself appears to work correctly but when I use "zpool offline -f" to put one of the vdev's into a faulted state this invalid path is passed to ZED's statechange-led.sh script and the drives fault LED is not turned on as a result.

The zpool.cache was correct when the zpool was created but the enclosure path changed after the system was powered back on.

### Describe how to reproduce the problem
I've been able to reproduce the problem by:
1) Manually editing the zpool.cache file and change the vdev_enc_sysfs_path entries (e.g. Change /sys/class/enclosure/1:0:12:0/13 to /sys/class/enclosure/8:0:12:0/13)
2) Reboot the machine
3) After calling zpool status to ensure that the zpool is still running use zpool offline -f to force one of the vdevs into a failure state.

### Include any warning/errors/backtraces from the system logs

There are no ZFS warning/errors in any of the system logs which I have been able to find.

**Comment by don-brady** [comment]
AFAIK the sysfs paths should be dynamically updated at pool import (via `update_vdev_config_dev_strs()`) so this could be a regression.  @tonyhutter might have more insight.

**Comment by tonyhutter** [comment]
Yea, it updates on pool import, but I've never tested it with a zpool.cache. In the short term you can try regenerating your cache file or disabling the cache file completely (https://github.com/zfsonlinux/zfs/wiki/FAQ#generating-a-new-etczfszpoolcache-file).  Long term, I'll need to see why `vdev_enc_sysfs_path` isn't getting regenerated on pool import.  Assigning to myself.

**Comment by IainCollins262** [comment]
I've just tried `zpool set cachefile=/etc/zfs/zpool.cache tank` and `zpool set cachefile=none tank` (without rebooting) and this had no effect, the invalid `vdev_enc_sysfs_path` path was still being passed to the ZED scripts when I took a vdev offline.

Don't know if this helps but after disabling the cachefile I rebooted the machine. After importing the zpool the newly generated cachefile contained corrected `vdev_enc_sysfs_path` paths.

i.e.:
`<zpool set cachefile=none tank>`
Reboot
`zpool import tank`

Thanks

**Comment by IainCollins262** [comment]
Also exporting the zpool and then re-importing the zpool fixes the invalid `vdev_enc_sysfs_path` values.

**Comment by IainCollins262** [comment]
I've had a quick scan through the source code (So apologies if I've missed anything) but it looks like `update_vdev_config_dev_strs()` is never going to be called when importing a zpool from a cache file.

`update_vdev_config_dev_strs()` looks like it is only ever called when `zpool_find_import_impl()` is called by `zpool_search_import()` but the code isn't getting that far as it is returning the result of `zpool_find_import_cached()` instead.
