### ISSUE TITLE
Change zfs_immediate_write_sz behavior (or update man page)

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#8530]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	| 7.6
Linux Kernel	| kernel-3.10.0-957.10.1.el7
Architecture	| x86_64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing
From zfs-module-parameters man page, `zfs_immediate_write_sz` should be:
> **Largest** data block to write to zil. Larger blocks will be treated as if the dataset being written to had the property setting logbias=throughput. Default: 32,768

However, from my tests it seems that block larger **or equal** than `zfs_immediate_write_sz` are written in indirect mode. Indeed, this seems confirmed by the code [here](https://github.com/zfsonlinux/zfs/blob/a8577bdb32e091645df901d8501e44ef50748389/module/zfs/zfs_log.c#L514):

```
else if (!spa_has_slogs(zilog->zl_spa) &&
	    resid >= zfs_immediate_write_sz)
		write_state = WR_INDIRECT;
```

I propose to change the above line to `resid > zfs_immediate_write_sz`. While this is a very small change, it seems a way more obvious behavior: for example, using the default 32768, a 32K write will *not* be written through the ZIL, rather it will be written using indirect mode. With the proposed change, a 32K writes will engage the ZIL.

### Describe how to reproduce the problem
With the default configuration, try a simple `dd if=/dev/urandom of=/tank/test/test.img bs=32K count=1024 oflag=sync` while monitoring disk usage (in another terminal) with `zpool iostat 1`. You'll see a very noticeable write amplification due to the indirect write *not* coalescing the sequential, sync writes just issued.

**Comment by behlendorf** [comment]
@shodanshok good find.  Yes, as I understand it the intent here was the blocks up to `zfs_immediate_write_sz` should be written to the ZIL.  This would be consistent with how `zvol_immediate_write_sz` is implemented [here](https://github.com/zfsonlinux/zfs/blob/a8577bdb32e091645df901d8501e44ef50748389/module/zfs/zvol.c#L666).

```c
        else if (!spa_has_slogs(zilog->zl_spa) &&
            size >= blocksize && blocksize > zvol_immediate_write_sz)
                write_state = WR_INDIRECT;
```

It looks like this behavior was accidentally changed in 1b7c1e5ce90ae27d9bb1f6f3616bf079c168005c.  But let's see if we can get @amotin's thoughts on this to make sure it wasn't done intentionally.

```diff
-       immediate_write_sz = (zilog->zl_logbias == ZFS_LOGBIAS_THROUGHPUT)
-           ? 0 : (ssize_t)zfs_immediate_write_sz;
-
-       slogging = spa_has_slogs(zilog->zl_spa) &&
-           (zilog->zl_logbias == ZFS_LOGBIAS_LATENCY);
-       if (resid > immediate_write_sz && !slogging && resid <= zp->z_blksz)
+       if (zilog->zl_logbias == ZFS_LOGBIAS_THROUGHPUT)
+               write_state = WR_INDIRECT;
+       else if (!spa_has_slogs(zilog->zl_spa) &&
+           resid >= zfs_immediate_write_sz)
```

**Comment by janetcampbell** [comment]
Perhaps it would be good to stress in the man page the degree of effect that indirect sync has on subsequent reads, due to data/metadata fragmentation. Aggregation frequently almost disappears when indirect sync writes take up a lot of space and unaggregated 4K reads multiply.  There seem to be a lot of people out there who aren't fully aware of this.
