### ISSUE TITLE
kmod-zfs kernel 3.10.0-957.10.1 

### ISSUE THREAD

**Issue by stonewalljones** [openzfs/zfs#8570]
### System information

Type | Kmod-ZFS 0.7.13-1
 --- | --- 
Distribution Name	| RHEL
Distribution Version	| 7.6
Linux Kernel	| kernel-3.10.0-957.10.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.13-1
SPL Version	| 0.7.13-1

### Describe the problem you're observing
When I'm running kernel 3.10.0-957.10.1 the zfs module doesn't load. But when I'm running 3.10.0-957.5.1 it doesn't have any issues.
### Describe how to reproduce the problem
Install kmod-zfs on kernel 957.10.1
### Include any warning/errors/backtraces from the system logs
When I run `modprobe zfs` I revice the following error
```
modprobe: FATAL: Module zfs not found.
```

This appears to be because `zfs.ko` does not get linked in the weak-updates folder for kernel 3.10.0-957.10.1

**Comment by qinq-net** [comment]
Shouldn't this be reported to RedHat instead of the upstream?

**Comment by behlendorf** [comment]
@stonewalljones just to confirm, you're using the kABI packages provided here:

https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS#kabi-tracking-kmod

**Comment by stonewalljones** [comment]
> @stonewalljones just to confirm, you're using the kABI packages provided here:
> 
> https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS#kabi-tracking-kmod

Yup I can confirm that.

**Comment by perrygeo** [comment]
I'm getting the same behavior with centos 7.6

* Linux version 3.10.0-957.1.3.el7.x86_64
* kmod-zfs-0.6.5.9-1.el7.centos.x86_64

(should I start a new issue for this?)

**Comment by btwe** [comment]
Here too:
```
969 # dmesg|grep -E 'zfs|spl'
[   26.076426] spl: loading out-of-tree module taints kernel.
[   26.076431] spl: loading out-of-tree module taints kernel.
[   26.076432] spl: loading out-of-tree module taints kernel.
[   26.078986] spl: module verification failed: signature and/or required key missing - tainting kernel
[   26.079093] spl: disagrees about version of symbol ___ratelimit
[   26.079094] spl: Unknown symbol ___ratelimit (err -22)
[   26.079283] spl: disagrees about version of symbol ___ratelimit
[   26.079284] spl: Unknown symbol ___ratelimit (err -22)
[   26.079450] spl: disagrees about version of symbol ___ratelimit
[   26.079451] spl: Unknown symbol ___ratelimit (err -22)
[   26.079615] spl: disagrees about version of symbol ___ratelimit
[   26.079616] spl: Unknown symbol ___ratelimit (err -22)
[   26.079788] spl: disagrees about version of symbol ___ratelimit
[... etc ...]
```

**Comment by behlendorf** [comment]
For the moment consider switching to the DKMS packages, we'll see about getting the repository updated with a rebuilt kmod package for the updated kernel.

**Comment by behlendorf** [comment]
I was not able to reproduce this issue when performing a clean install of the `kmod-zfs-0.7.13-1.el7_6.x86_64` package.

This likely means the issue is with the `/usr/sbin/weak-modules` script which failed to create the necessary symlinks when installing the new kernel.  I confirmed the modules themselves are compatible with the `3.10.0-957.10.1.el7.x86_64` kernel.

To resolve this issue I would suggest uninstalling all of the zfs packages and then reinstalling them using the [process described on the wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS#rhelcentos-7x-kmod-package-upgrade).

**Comment by btwe** [comment]
I can confirm, removing zfs and spl packages, but not zfs-release, and re-installing zfs again, works.
