### ISSUE TITLE
Unable to see ZFS snapshots over NFS

### ISSUE THREAD

**Issue by anderbubble** [openzfs/zfs#8645]
I see that there have been similar issues like this before, but they are all closed, and we appear to be running a sufficient release that shouldn't have this issue.

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| RHEL
Distribution Version	| 7.6
Linux Kernel	| 3.10.0-957.1.3.el7.x86_64
Architecture	| x86_64
ZFS Version	| zfs-release-1-4.el7_3.centos.noarch
SPL Version	| spl-0.7.12-1.el7_3.x86_64

### Describe the problem you're observing

If I `ls .zfs/snapshots/*/` on the ZFS server, we can see the snapshots; however, if I `ls .zfs/snapshots/*/` through an NFS mount of the same ZFS, the snapshot directories appear empty.

### Describe how to reproduce the problem

See above.

### Include any warning/errors/backtraces from the system logs

None observed so far; only incorrect behavior.

**Comment by richardelling** [comment]
Have you tried the NFS server option `crossmnt`?  Depending on your NFS server, this might be otherwise referenced as an NFS cross mount.

**Comment by anderbubble** [comment]
Sorry for not responding to this earlier. You're probably right.

The ZFS fs we were using to prototype snapshots in our environment has encountered a separate error, so we can't test it now; but I'll try to remember to report back here when we're able.

**Comment by dinghuaming** [comment]
> crossmnt
zfs nfs suport  crossmnt option?
i see the error message:

zfs set sharenfs=@192.168.22.106,crossmnt,no_root_squash,  SYSVOL/BACKUP/file/FILE/ding1
cannot set property for 'SYSVOL/BACKUP/file/FILE/ding1': 'sharenfs' cannot be set to invalid options

**Comment by behlendorf** [comment]
Closing.  Crossmnt is now included in the default options and I haven't seen any other reports of this.
