### ISSUE TITLE
Docker build performance extremely slow due to lack of renameat2/overlayfs on ZFS

### ISSUE THREAD

**Issue by dbavatar** [openzfs/zfs#8648]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Any
Distribution Version	| Any
Linux Kernel	| Any
Architecture	| Any
ZFS Version	| Any
SPL Version	| Any

### Describe the problem you're observing
This is more of a feature request than a bug.  I can't find anyone actively tracking this problem, however I do know users of docker that have stopped using ZFS because of this after having stated there's something wrong with ZFS, which is unfortunate.

When using docker on a zfs dataset, the only option is docker's "zfs driver" which uses zfs dataset operations to create layered filesystems. On other filesystems such as ext4 and btrfs, the "overlay2 driver" (utilizing the kernel's overlayfs module) can be used which is extremely fast. Docker build times can go from a fraction of a second on ext4/overlay2 to several minutes on zfs/zfs.

overlay2 driver selection is currently blacklisted on zfs by docker:
https://github.com/moby/moby/blob/master/daemon/graphdriver/overlay2/overlay.go#L165

Note that btrfs added the necessary support in kernel 4.7:
https://github.com/moby/moby/blob/master/daemon/graphdriver/overlay2/overlay.go#L169

### Describe how to reproduce the problem
From a performance perspective:
time the build of a Dockerfile with several layers as so:
```bash
time docker build . -t date_image
```
```Dockerfile
# date_image Dockerfile
FROM scratch
CMD [date]
CMD [date]
CMD [date]
CMD [date]
CMD [date]
# repeat date layer to magnify performance slowdown
```
From a functional perspective:
```c
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <linux/fs.h>
#include <sys/syscall.h>

int main()
{
  int ret;

  ret = syscall(SYS_renameat2, 0, "/zfs/file1", 0, "/zfs/file2", RENAME_EXCHANGE);
  fprintf(stderr, "renameat2 ret=%d errno=%d\n", ret, errno);
  return ret;
}
```
Repeat test for RENAME_WHITEOUT flag as well.

I believe we should be able to use docker on ZFS w/overlay2 after both RENAME_EXCHANGE and RENAME_WHITEOUT are implemented in renameat2()

**Comment by cyphar** [comment]
I've started working on this, and have most of it done but have a question about `dmu_tx_*` and how it's used in this context (`zfs_rename`):

```
	if (tzp)
		error = zfs_link_destroy(tdl, tzp, tx, zflg, NULL);

	if (error == 0) {
		error = zfs_link_create(tdl, szp, tx, ZRENAMING);
		if (error == 0) {
			szp->z_pflags |= ZFS_AV_MODIFIED;
			if (tdzp->z_pflags & ZFS_PROJINHERIT)
				szp->z_pflags |= ZFS_PROJINHERIT;

			error = sa_update(szp->z_sa_hdl, SA_ZPL_FLAGS(zfsvfs),
			    (void *)&szp->z_pflags, sizeof (uint64_t), tx);
			ASSERT0(error);

			error = zfs_link_destroy(sdl, szp, tx, ZRENAMING, NULL);
			if (error == 0) {
				zfs_log_rename(zilog, tx, TX_RENAME |
				    (flags & FIGNORECASE ? TX_CI : 0), sdzp,
				    sdl->dl_name, tdzp, tdl->dl_name, szp);
			} else {
				/*
				 * At this point, we have successfully created
				 * the target name, but have failed to remove
				 * the source name.  Since the create was done
				 * with the ZRENAMING flag, there are
				 * complications; for one, the link count is
				 * wrong.  The easiest way to deal with this
				 * is to remove the newly created target, and
				 * return the original error.  This must
				 * succeed; fortunately, it is very unlikely to
				 * fail, since we just created it.
				 */
				VERIFY3U(zfs_link_destroy(tdl, szp, tx,
				    ZRENAMING, NULL), ==, 0);
			}
		} else {
			/*
			 * If we had removed the existing target, subsequent
			 * call to zfs_link_create() to add back the same entry
			 * but, the new dnode (szp) should not fail.
			 */
			ASSERT(tzp == NULL);
		}
	}

	dmu_tx_commit(tx);
```

Is there a reason the transaction is not aborted in the case of errors? I ask because it's unclear to me whether this is a good idea (after all, `rename()` is meant to be atomic so you should never see the case where the target was unlinked but none of the other).

If we were able to just do `dmu_tx_unassign(tx); dmu_tx_abort(tx);` (as well as the other cleaning up) then we could implement it all like this (`abort` would do the relevant cleanup):

```

	/*
	 * Unlink the source.
	 */
	szp->z_pflags |= ZFS_AV_MODIFIED;
	if (tdzp->z_pflags & ZFS_PROJINHERIT)
		szp->z_pflags |= ZFS_PROJINHERIT;

	error = sa_update(szp->z_sa_hdl, SA_ZPL_FLAGS(zfsvfs),
		(void *)&szp->z_pflags, sizeof (uint64_t), tx);
	ASSERT0(error);

	error = zfs_link_destroy(sdl, szp, tx, ZRENAMING, NULL);
	if (error)
		goto abort;

	/*
	 * Unlink the target.
	 */
	if (tzp) {
		int trename = (flags & RENAME_EXCHANGE) ? ZRENAMING : 0;

		if (trename) {
			tzp->z_pflags |= ZFS_AV_MODIFIED;
			if (sdzp->z_pflags & ZFS_PROJINHERIT)
				tzp->z_pflags |= ZFS_PROJINHERIT;

			error = sa_update(tzp->z_sa_hdl, SA_ZPL_FLAGS(zfsvfs),
				(void *)&tzp->z_pflags, sizeof (uint64_t), tx);
			ASSERT0(error);
		}
		error = zfs_link_destroy(tdl, tzp, tx, trename | zflg, NULL);
		if (error)
			goto abort;
	}

	/*
	 * Create the new target links:
	 *   * We always link the target.
	 *   * RENAME_EXCHANGE: Link the old target to the source.
	 */
	error = zfs_link_create(tdl, szp, tx, ZRENAMING);
	if (error)
		goto abort;

	switch (flags) {
	case RENAME_EXCHANGE:
		error = zfs_link_create(sdl, tzp, tx, ZRENAMING);
		break;
	case RENAME_WHITEOUT:
		// TODO
		break;
	}
	if (error)
		goto abort;

	zfs_log_rename(zilog, tx, TX_RENAME |
		(flags & FIGNORECASE ? TX_CI : 0), sdzp,
		sdl->dl_name, tdzp, tdl->dl_name, szp);

	dmu_tx_commit(tx);
```

**Comment by cyphar** [comment]
I've been working on this and `renameat2(2)` flag support is not sufficient to get overlayfs-on-ZFS working. The main blocker is that currently ZFS uses `d_revalidate` which means overlayfs refuses to use it as an upperdir. In order to fix it (in addition to #8667) we will need to rework a fair amount of the ported `dcache`-interacting code so that `d_revalidate` is no longer needed.

**Comment by dbavatar** [comment]
Too bad stalebot doesn't pick up related work - Seems like @snajpa is close to getting it done.

**Comment by snajpa** [comment]
Yeah, I've finally gotten around to write the tests for ZFS rollback, needed in #9600 ... give me at least a few days for a prototype :)

**Comment by Frederick888** [comment]
I noticed that if I use ZFS as the lower layer of OverlayFS (upper, work, mount point in tmpfs), I cannot append contents to any existing files either.

Sorry for my ignorance, but may I know if this problem is also tracked by this ticket or #9414? Thanks.

**Comment by cyphar** [comment]
@Frederick888 As in `O_APPEND` doesn't work, or gives you an error? That sounds like a separate bug to me -- ZFS should work as a lowerdir for overlayfs and if it doesn't it's either a bug in overlayfs or ZFS.

**Comment by Frederick888** [comment]
@cyphar When using `tee -a` it reports `Invalid argument`, e.g.

```sh
$ zfs list | rg '/home'
tank/data/home     50.0G   367G     38.8G  /home
$ mkdir ~/lower

$ pwd
/tmp/test
$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            24G  308M   24G   2% /tmp
$ mkdir upper work merged

$ printf 'hello world\n' | tee ~/lower/test.txt
hello world
$ sudo mount -t overlay overlay -o lowerdir=/home/frederick/lower,upperdir=./upper,workdir=./work,redirect_dir=follow ./merged
$ cat merged/test.txt
hello world
$ printf 'hello world\n' | tee -a merged/test.txt
tee: merged/test.txt: Invalid argument
hello world
```

Similar when `git pull`, error message being e.g. `error: cannot update the ref 'refs/remotes/origin/master': unable to append to '.git/logs/refs/remotes/origin/master': Invalid argument`.

**Comment by cyphar** [comment]
`-EINVAL` is definitely a weird response to get. I'll take a look -- it is possible it's related to the lack of `renameat2` but that should only matter for `upperdir` not `lowerdir`...

**Comment by thoernle** [comment]
This should be closed because OverlayFS support has already been mergen in https://github.com/openzfs/zfs/pull/9414 ,right?

**Comment by galaxy001** [comment]
With ifs-dkms 2.1.9-1 and kernel 6.1.14-1-lts, I still got the error with `podman`:
```
[22424.607969] overlayfs: upper fs does not support RENAME_WHITEOUT.
[22424.608104] overlayfs: upper fs does not support file handles, falling back to index=off.
[22424.608109] overlayfs: fs on '/home/galaxy/.local/share/containers/storage/overlay/l/ZH4GPIMNPLZLZ5T2J5WAUPB77S' does not support file handles, falling back to xino=off.
```

**Comment by satmandu** [comment]
Overlayfs support is only in the master branch of openzfs at the moment. It should be in 2.2 when it gets released.
