### ISSUE TITLE
ZFS clone does not work for KVM guest image(no boot device)

### ISSUE THREAD

**Issue by tonymmm1** [openzfs/zfs#8649]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos 7
Distribution Version	| 
Linux Kernel	|  3.10.0-957.10.1.el7.x86_64
Architecture	|  x86_64
ZFS Version	|  0.7.13
SPL Version	|  0.7.13

### Describe the problem you're observing
I am trying to make a clone of a zfs dataset with a kvm vm image in this case a raw .img file. However when I create a clone and try to boot the vm in a different vm than the one I used to create the .img file it complains that there is no boot device. The kvm guest that I am trying to clone is a debian 9 instance but the problem persists with both lvm and standard partition installs. Feedback would be appreciated.

### Describe how to reproduce the problem
1. zfs create tank/dataset
2. qemu-img create /mnt/tank/dataset/vm.img +10G
3. configure kvm guest to use this vm image
4. install and configure vm 
5. zfs snapshot tank/dataset@snapshot1
6. zfs clone tank/dataset@snapshot1 tank/dataset-clone
7. create another kvm guest using the cloned dataset dir
8. no boot device error

**Comment by tonymmm1** [comment]
I have done some testing and I actually think this might be a debian issue as centos and windows work using snapshot clones. If someone can correct me that would be swell.

**Comment by Low-power** [comment]
Can't reproduce with ZoL 0.7.13 on Debian
