### ISSUE TITLE
VM Creation on a ZFS-based ESXi datastore.

### ISSUE THREAD

**Issue by comptech10** [openzfs/zfs#8654]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 16.04
Linux Kernel	|  4.4.0-62-generic
Architecture	| AMD64
ZFS Version	| 0.6.5.6-0ubuntu15
SPL Version	| 0.6.5.6-0ubuntu4

### Describe the problem you're observing

I have setup a jbod on Ubuntu with ZFS through NFS 4.1 for a vmware datastore.  After much trying i have found that it works fine if i am using "Spinny Disks".  When using SSDs (which is what I started out with and what i need to use) however, I can browse, create, delete on the ZFSstore through nfs just fine, however, when I start a fresh vm container for the first time, it says "The specified file is not a virtual disk".  If i allow it to sit for a few minutes it starts up just fine and never appears to have an issue again.  If I am ikn a real hurry, I can also get it working by issuing the "touch" command on the vmdk files.  So i have apparently narrowed this problem down to only being an issue in the event of fresh VM creation.  Any guidance in the right direction would be appreciated.  

### Describe how to reproduce the problem
See above

### Include any warning/errors/backtraces from the system logs

see above

**Comment by richardelling** [comment]
This is not a bug. NFS clients can and do cache directory contents. When a new entry is added to a directory, it is up to the client (VMware) to update its view of the directory contents.

**Comment by comptech10** [comment]
That is interesting, it works right away when testing with standard disks...

**Comment by comptech10** [comment]
I have found that through the SSD disks, it takes approximately 1.5 minutes until i can start them IF i leave them alone, if i try to start too early, they appear to take a lot longer
