### ISSUE TITLE
scrub never completes on empty pool with special vdev

### ISSUE THREAD

**Issue by markwiederspahn** [openzfs/zfs#8694]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos
Distribution Version	| 6.10
Linux Kernel	| 2.6.32-754.12.1
Architecture	| X86_64
ZFS Version	| 0.8.0-rc4
SPL Version	| 0.8.0-rc4

### Describe the problem you're observing
scrub acts oddly on a newly created pool with a "special" vdev.

### Describe how to reproduce the problem
zpool create -f xx sdab special sdac
zpool scrub xx
zpool iostat -v xx 5
observe continuous writing to sdac, lower rate of writing to sdab.

touch /xx/junk
observe scrub finishes. Under some unknown conditions, data must be written to "junk" to have the scrub complete. Often just the empty file suffices. 

The problem doesn't occur if any files exist at scrub start.

**Comment by behlendorf** [comment]
@markwiederspahn thanks for reporting this.  I was able to reproduce this issue using the steps described.

**Comment by amotin** [comment]
This PR fixes this issue: https://github.com/openzfs/zfs/pull/10106
