### ISSUE TITLE
Custom kernel zfs module build errors

### ISSUE THREAD

**Issue by eXt73** [openzfs/zfs#8757]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Kubuntu
Distribution Version	| 18.04
Linux Kernel	| 5.0.17-ext73-70.17-kabylake-8th
Architecture	| x86_64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing
building a zfs module under my kernels I received errors of this kind. Where in kernel config I have made a mistake ?
### Include any warning/errors/backtraces from the system logs

"  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_missing.o
/var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_disk.c: In function 'vdev_elevator_switch':
/var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_disk.c:158:10: warning: implicit declaration of function 'elevator_change' [-Wimplicit-function-declaration]
  158 |  error = elevator_change(q, elevator);
      |          ^~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_queue.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_raidz.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_raidz_math.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_raidz_math_scalar.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/vdev_root.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zap.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zap_leaf.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zap_micro.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfeature.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfeature_common.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_acl.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_byteswap.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_ctldir.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_debug.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_dir.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_fm.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_fuid.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_ioctl.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_log.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_onexit.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_replay.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_rlock.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_sa.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_vfsops.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_vnops.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zfs_znode.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zil.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zio.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zio_checksum.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zio_compress.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zio_inject.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zle.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_ctldir.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_export.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_file.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_inode.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_super.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_xattr.o
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zrlock.o
/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_file.c:861:11: error: 'new_sync_read' undeclared here (not in a function)
  861 |  .read  = new_sync_read,
      |           ^~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_file.c:862:12: error: 'new_sync_write' undeclared here (not in a function)
  862 |  .write  = new_sync_write,
      |            ^~~~~~~~~~~~~~
scripts/Makefile.build:276: recipe for target '/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_file.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_file.o] Error 1
make[5]: *** Oczekiwanie na niezakończone zadania....
  CC [M]  /var/lib/dkms/zfs/0.7.13/build/module/zfs/zvol.o
/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_inode.c:782:14: error: 'generic_readlink' undeclared here (not in a function); did you mean 'generic_read_dir'?
  782 |  .readlink = generic_readlink,
      |              ^~~~~~~~~~~~~~~~
      |              generic_read_dir
scripts/Makefile.build:276: recipe for target '/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_inode.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.7.13/build/module/zfs/zpl_inode.o] Error 1
scripts/Makefile.build:492: recipe for target '/var/lib/dkms/zfs/0.7.13/build/module/zfs' failed
make[4]: *** [/var/lib/dkms/zfs/0.7.13/build/module/zfs] Error 2
Makefile:1553: recipe for target '_module_/var/lib/dkms/zfs/0.7.13/build/module' failed
make[3]: *** [_module_/var/lib/dkms/zfs/0.7.13/build/module] Error 2
make[3]: Opuszczenie katalogu '/usr/src/linux-headers-5.0.17-ext73-70.17-kabylake-8th'
Makefile:21: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Opuszczenie katalogu '/var/lib/dkms/zfs/0.7.13/build/module'
Makefile:704: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Opuszczenie katalogu '/var/lib/dkms/zfs/0.7.13/build'
Makefile:575: recipe for target 'all' failed
make: *** [all] Error 2"

**Comment by behlendorf** [comment]
Since the available kernel interfaces can change significantly based on the kernel build options and kernel version, ZFS does its best to detect which interfaces are available.  For your kernel, it appears to have incorrectly detected that the `elevator_change` function, along with several others are available when they're not.

To understand why we'd need to see the `config.log` output, and your kernel configuration to know what functions should be available.  If at all possible, I'd suggest largely applying the distribution's kernel configuration to your custom kernel as a starting point.  Since we do our testing with the distribution provided kernels.
