### ISSUE TITLE
receive_resume_token persists after transfer and cannot be aborted

### ISSUE THREAD

**Issue by mtknapp** [openzfs/zfs#8801]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 9 
Linux Kernel	| 4.14
Architecture	| x86_64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing
There is a receive_resume_token for a dataset but the send/receive that the token exists for has completed already. When trying to abort the receive with `zfs receive -A`, it returns an error saying `[dataset] does not have a resumable receive state to abort`. When trying to resume the send/receive, it prints `cannot resume send: '[dataset]@DAILY-20190318' used in the initial send no longer exists`.
### Describe how to reproduce the problem
I'm not 100% sure if this is how it's produced but I believe it has to do with the fact that we have rotating daily snapshots going on and one of the snapshot being deleted while the send/receive is occurring. It seems to be leaving it in a weird state that it won't recover from.
### Include any warning/errors/backtraces from the system logs
There isn't anything relevant to include here

**Comment by ptx0** [comment]
i also had this happen on 0.8.0, had to recreate the dataset to get rid of the token.

**Comment by prometheanfire** [comment]
I had something like this, but after about 15 minutes (cancel sending after 300MB or so) I was able to remove it.  This was for git master a couple of days ago (so close to 0.8.0).
