### ISSUE TITLE
DKMS configure needs bash but might get dash

### ISSUE THREAD

**Issue by Vaelatern** [openzfs/zfs#8827]
ZFS 0.8.0, packaging for Void Linux.

### Describe the problem you're observing

During DKMS build, if the system `/bin/sh` is symlinked to a minimal yet POSIX compliant shell like dash, then configure will fail with a bad substitution.

The problem is the lines `test "${PYTHON_VERSION:0:2}" = "3."` which unintentionally use a bashism.

It may be pointed out that `test "${PYTHON_VERSION##3.*}" = ""` and a similar one for 2.* will work equally well, while being POSIX compliant.

### Mitigation

Void Linux will either patch configure to use `/bin/bash` or will patch out the PYTHON_VERSION checks to be compliant, as outlined above.

**Comment by siv0** [comment]
I think that both:
* https://github.com/zfsonlinux/zfs/pull/8731
* https://github.com/zfsonlinux/zfs/pull/8813
should address this issue (the author of the second said, that the first might be preferable).

If one of them fixes the problem for you a comment in the respective PR would be great!

hope this helps!

**Comment by Vaelatern** [comment]
Both of those look great, especially the one with minimal changes, but the comprehensive one goes too far into autoconf territory for me to understand.
In any event, Void has chosen to patch the PYTHON_VERSION checks as I outlined above, and will stop doing so when some solution is released.

**Comment by Vaelatern** [comment]
I believe this issue can be closed because 8731 was merged.
