### ISSUE TITLE
libzfs_core should have API documentation

### ISSUE THREAD

**Issue by likema** [openzfs/zfs#8840]
Hi,

Is there any document about userspace libraries `libzfs` and `libzfs_core`?

**Comment by richardelling** [comment]
`libzfs` is not documented, in part because it is not a stable interface.
`libzfs_core` is a stable interface, but does not have a man page, so USTL.

**Comment by likema** [comment]
I found that the keys of `libzfs` and `libzfs_core1` are several `ioctl`.

I there any document about these `ioctl`?

**Comment by behlendorf** [comment]
The `libzfs_core` ioctl() API is largely documented in the source.  A good place to start would be to take a look at the `zfs_keys_*` structures which are declared in `module/zfs/zfs_ioctl.c`.  For each non-legacy `ioctl()` there should be an entry describing the allowed keys and their values.
