### ISSUE TITLE
txg_sync 99% and system lags on zfs 

### ISSUE THREAD

**Issue by c3ph3us** [openzfs/zfs#8963]
hi why ZFS is not yeling to system logs while there is no space left on pool / tank?? 
i have spend 2h looking while my system sudenly lags accessing ZFS while df/dfu shows ~2GB free space on ZFS   txg_sync  io was remaining all time at  98%-99% 
the df alert me on low space only when i set zfs=sync to disabled and check tenth time on disc space there was also no usuless info in zpool ioctl for high txg_sync load and lags 
pleas add some feature preventing user madnes :) 

zfs status 
zpool status 
all above should alert user on low space or IO problems 

maybe this will help https://github.com/netdata/netdata/issues/3833

**Comment by richardelling** [comment]
There are dozens of open-source or for-fee monitors that can generate alerts. Try using the right tool for your business needs.

**Comment by c3ph3us** [comment]
@richardelling we are talking on FS implementation which does nothing to aler on zfs io/write 
failure

###  <b>it's like trying to start a car [ZFS]  engine [IO OP] without knowledge there is no fuel left [FAILURE] because there is no fuel level indicator [SYSLOG FAIL ENTRY].</b>

**Comment by DeHackEd** [comment]
And how does ext4 alert the user when it gets full?

**Comment by h1z1** [comment]
Hard to say given you haven't provided any details besides something is telling you the pool is out of space.  Was that on the root of tank?  A dataset?  zvol?  Snapshot? 

My guess would be the reservation.   ```zfs list -o space,reservation```
