### ISSUE TITLE
ZVOL Performance

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#9]
While there is a full native ZVOL implementation in this code base performance likely is not what it could be.  Mainly this is both the Linux VFS and the ZFS ARC both want to fully manage the cache so we unfortunately end up with two caches.  This means our memory foot print is larger    than it needs to be, and it means we have an extra copy between the caches, but it does not impact correctness.  All syncs are barrier requests I believe are handled correctly.  Longer term there is lots of room for improvement here but it will require fairly extensive changes to either the Linux VFS and VM layer, or additional DMU interfaces to handle managing buffer not directly allocated by the ARC.

One tuning which can be made in the short term here is to configure the ARC to only cache meta data.  This reduces the memory footprint substantially but it does not eliminate that extra copy unfortunately.

**Comment by hostingnuggets** [comment]
So finally when using ZVOLs with ZFS on Linux what kind of settings would you recommend? or simply leave everything as default? I use my ZVOLs for Xen virtual machines with ext4 as filesystem on it. I actually went through the following issue: #4738

**Comment by ptx0** [comment]
please use the mailing list for such questions, thanks @hostingnuggets
