### ISSUE TITLE
DKMS does not recompile module on new kernel Fedora 30

### ISSUE THREAD

**Issue by therevoman** [openzfs/zfs#9005]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 30
Linux Kernel	| 5.1.16-300.fc30.x86_64
Architecture	| x86_64
ZFS Version	| zfs-release-1-5.fc30.noarch zfs-0.8.1-1.fc30.x86_64
SPL Version	| NA

### Describe the problem you're observing
On Fedora 30 Server edition I've installed zfs following the wiki.  When I do a full update (including kernel) and reboot, the zfs module is not loaded.  if I re-install zfs-dkms, the module gets built and everything starts up.

### Describe how to reproduce the problem
Plain Fedora 30 Server installation with zfs-release
Update kernel to newer version and reboot.

**Comment by BlauerHunger** [comment]
I have the same problem. I'm working around it by running dkms install `zfs/0.8.1 -k <new_kernelver>` everytime after `dnf` installs a new kernel, but sometimes I forget doing it and then ugly things happen.

**Comment by johnnyjacq16** [comment]
To see all modules that dkms have built for which kernel do `dkms status`
To build the zfs module for the kernel do `dkms install -m zfs -v <zfs version> -k <new_kernelver>` or what @BlauerHunger did, also you want to update initramfs with the zfs modules by doing `dracut -fv --kver <kernel version>` however updating initramfs with the zfs modules will break SecureBoot, if the zfs modules are not signed.

**Comment by mskarbek** [comment]
With each such issue, I'm a bit closer to make publicly available my repo of kmod packages for Fedora. :/

**Comment by therevoman** [comment]
Thanks for the tips. I do know how to rebuild the module manually.  The
issue is that i am expecting dkms(or whatever) to handle that automatically
so I don't have to remember to do it.

**Comment by mskarbek** [comment]
DKMS is problematic. Just in ZFS there is a long list of issues related to installations/updates leftover without modules properly build. Nvidia drivers are another perfect example. I understand why the user expects that after installing DKMS based packages he is set for life. Not necessarily, and to the point that I just stopped using DKMS entirely and have a private Jenkins job that checks Fedora repo for new kernels and rebuilds kmod packages for me.

**Comment by therevoman** [comment]
Since the box with the issue is going to a remote location (friends house)
with out direct access I need to have automatic updates (for security) and
be able to expect the modules to be built properly.

Curious why I haven't experienced this issue in previous releases.  And I
currently have another box running Ubuntu with zfs on linux that's been
updating for 6 years and never had this issue.  if DKMS is problematic,
what will it take to fix that?  Or, is there a better alternative?

**Comment by fmikker** [comment]
I have experienced this issue in Fedora 29, and now in Fedora 30 it still persists. 
Testing @BlauerHunger 's workaround now and I'll see if the module is loaded correctly upon reboot now.

**Comment by JamesRHarris** [comment]
> problematic. Just in ZFS there is a long list of issues related to installations/updates leftover without modules properly build. Nvidia drivers are another perfect example. I understand why the user expects that after installing DKMS based packages he is set for life. Not necessarily, and to the point that I just stopped using DKMS entirely and have a private Jenkins job that checks Fedora repo for new kernels

I have been using dkms on fedora for six years with two out of tree modules it has never just 'worked' each kernel update I am forced to clean up a mess dkms has left. For example on my one system with two different out of tree drivers it has never uninstalled drivers when removing a kernel. Yet I have another server only running zfs and for some reason it doesn't have a problem removing zfs when removing an old kernel as part of an update.  While that second system can remove zfs modules I have recently migrated to a zfs root and now dracut isn't building initramfs with zfs even after `echo 'add_drivers+="zfs zunicode zavl icp zlua zcommon znvpair spl" > /etc/dracut.conf.d/zfs.conf` manually running `dracut --force --kver <upgraded version>`  creates a new initramfs with zfs modules installed. 
I cant speak for other distros but dkms on fedora is a hot mess that is full of bugs.  I have yet to find anything better. It doesn't seem the Fedora guys care much about out of kernel modules.  Their recent changes to kernel installs just stopped calling the scripts in /etc/kernel/*.d/  . Only recently did they get dkms getting called again on new kernel installs. 

If you are using dkms on fedora I would recommend learning 'dkms status' to see what dkms at least 'thinks' is going on. Then figure out how to use `dkms remove zfs/<zfs version> -k <removed kernel version>`  to clean up old stuff that might be  lying around.  It would also be a good idea to understand `dkms install zfs/<zfs version> -k <new kernel version>`.  You will also likely to need to manually clean out /lib/modules/<removed kernel versions> as fedora wont tidy that up.   Finally dkms 'remove' doesn't seem to clean out /var/lib/dkms/ so you might want to occasionally take a look at /var/lib/dkms/zfs/ and see how many copies of modules you have laying around for kernels that have already been uninstalled.

**Comment by almereyda** [comment]
The last comment let me run

    dkms install zfs/0.8.3 -k 5.4.19-100.fc30.x86_64

which resulted in a successful `modprobe zfs`.
