### ISSUE TITLE
Still about refcount mismatch error

### ISSUE THREAD

**Issue by starmood** [openzfs/zfs#9026]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.0.4.2
Linux Kernel	|  4.15.0-52-generic
Architecture	| 
ZFS Version	|  0.7.5-1ubuntu16.4
SPL Version	|  0.7.5-1ubuntu1

### Describe the problem you're observing
Continue with #7204, I did not see any workable solution from that issue. And I also got same error like "space map refcount mismatch: expected 116 != actual 113" by zdb.

Someone was saying it's harmless, but I had some scripts to get dedup information by zdb. With the error, the return code is always none-zero. That will make script confused. 
If we can't fix this issue, is there any other way to get dedup statistcs than zdb?

### Describe how to reproduce the problem
I think this issue should be not that hard to reproduce. I am using Ubuntu18, and tried ZFS on one phsyical machine and one ESXi VM. After couple weeks low-usage-rate testing, both got the mismatch error, and even on an empty pool,

**Comment by richardelling** [comment]
Question: what are you using `zdb` to get that you cannot also get with `zpool status -D`?

**Comment by ahrens** [comment]
To reiterate my comments from #7204:

The problem reported by "space map refcount mismatch" is with the count of space maps that are using the spacemap_histogram feature flag. An incorrect count here has essentially zero impact on your pool. You can safely continue using the pool without consequence.

In the pool described in #7204, the spacemap_histogram feature flag refcount is actually correct (there are 22 spacemaps using this feature), but ZDB only located 21 of them. The last one (object 6) doesn't seem to be referenced anywhere. I suspect that it's a DTL object that has been leaked. The leaked object is empty. There is no impact on the pool and you can safely continue using it (or other pools with similar errors).

"Leaked" means that this (space map) object in the MOS is not referenced by any other data structures in the pool. So there isn't any way for it to be freed. Assuming that it should have been freed, the only impact is a tiny bit of space (hundreds of bytes) being unnecessarily used.

FYI, I've augmented ZDB to find these kinds of MOS object leaks automatically, in https://github.com/zfsonlinux/zfs/pull/7979, which is part of ZoL 0.8.

**Comment by starmood** [comment]
> Question: what are you using `zdb` to get that you cannot also get with `zpool status -D`?

I am using zdb -D to get dedup info.

**Comment by richardelling** [comment]
We used to do that prior to `zpool status -D` existing.  Since zdb is much less performant and doesn't scale with large pools, consider changing your scripts... your life will be happier.
