### ISSUE TITLE
.zfs/snapshots privileges settings 

### ISSUE THREAD

**Issue by montanaviking** [openzfs/zfs#9028]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by montanaviking** [comment]
Distribution name: Ubuntu 18.04
Version 18.04
Linux Kernel: 4.15.0-54-generic
Architecture: Intel Xeon 64-bit
ZFS version: 0.7.5-1ubuntu16.4
SPL version: 0.7.5-1ubuntu

Checking privileges on .zfs/snapshot shows all users, including guest, have all privileges. 
I presume that this is a security hole. Also, I'm hoping that nobody can directly delete the snapshots.
How do I ensure that only root may read the snapshots?
Thanks and best,
Phil

**Comment by kpande** [comment]
well they use standard file permissions soooo you're really only able to read whatever files are readable for the user in question.. can you just use the mailing list for simple questions?

**Comment by kusumi** [comment]
I think it's missing `inode_init_owner(..., vap->va_mode)` on mkdir, but mkdir/rmdir/rename for ctldir all require `CAP_SYS_ADMIN` anyway.

**Comment by devZer0** [comment]
everything below .zfs/snapshot is readlony, regardless was permission is shown - so this should be a "non issue"

you can try adding or remove files there and will see that you won't succeed

 >How do I ensure that only root may read the snapshots?

why?

if anybody could read /zpool/mydir - why would you want to disallow access to /zpool/.zfs/snapshots/$snapname/mydir ?

**Comment by eharris** [comment]
One potential issue I can see immediately is that if a there was a security issue where something was visible to users in the past when a snapshot was created, but has since been corrected.  Since the snapshot can't be modified to also fix the permissions, how can you reasonably handle this without a way to restrict access to the problematic snapshot?

**Comment by behlendorf** [comment]
The recommended solution is this case would be to destroy any effected snapshots.

**Comment by eharris** [comment]
Being forced to destroy an entire snapshot, and all the value/data that it has, simply to secure a tiny portion of it is not a solution.  Unless there's some way to edit snapshots, which isn't yet available as far as I know, is it?

**Comment by behlendorf** [comment]
Editing snapshots isn't really possible, but providing some administrative controls regarding how they can be used would be.  For example, disabling the `.zfs/snapshots` directory for a dataset.   Or perhaps change the default permissions on the mount point.  Did you have a specific solution in mind for this?

Note: I've gone ahead and migrated this issue to the new "Ideas" tab in the Discussions tab which we've just enabled to better track and discuss these kind of feature requests.
