### ISSUE TITLE
build fails on scripts/dkms.mkconf: Permission denied

### ISSUE THREAD

**Issue by dreamcat4** [openzfs/zfs#9070]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  19.04
Linux Kernel	|  ubuntu's 5.0.0-19-generic
Architecture	| x86_64
ZFS Version	| 0.7.12-1ubuntu5
SPL Version	| 0.7.12-1ubuntu3

### Describe the problem you're observing

Hi there. Got 2 local systems on ubuntu 19.04.

On system A, it is my main system. Lots of packages installed. Using a mainline kernel, which is like 5.1.x. It did not have any previous version of zfs installed onto it. And I can run some certain commands (see next section) to build zfs from source. And everything works. Packages are generated at the end... all fine.

On system B, it's a clean install of 19.04. But with zfs as the root filesystem. So that is ubuntu's version of zfs compiled right into the kernel. I am running all of the same commands to install dependancies (as far as I am aware there are no missing deps on the newer clean system B, according to the build logs). Anyhow... there must be something different going on because system B's build fails with a weird unexplained error. That I cannot possibly fathom.

My impression after reading issue #8585 is that maybe the build process might be taking something from zfs in the system environment. IDK what that could be. But anyhow it's not an option whatsoever for me to build on system B without the host system running zfs because that is the root filesystem. I cannot boot without it !

Another option might be perhaps there is some kind of a build time dependancy which was already pre-existing on system A, and not included in my list of build deps to install. And therefore was not got installed onto the clean new system B. However all of the output from `./configure  --with-config=user` seems to be identical in both of the build logs between these 2 systems.

Here is my DIFF between the successful build log on system A and the failed build on system B. It is not very insightful so perhaps there are some extra debugging flags which I can switch on to reveal more of what is happening under the hood?

https://gist.github.com/dreamcat4/ce90aead67a05024c37268c5d018e840

And here is the full output of the whole failed build after checking out `zfs-0.8.0` release git tag. Starting at `./autogen.sh`

https://gist.github.com/dreamcat4/46cb6d543aa96edcafc66dda9ebbc2da

Have also tried building from different commits today, both `zfs-0.8.1` and `master`. The same exact error occurs, there is no improvement.

### Describe how to reproduce the problem

Run these exact same commands on either system A or system B.

```sh
# ======
# install zfs from source
# https://github.com/zfsonlinux/zfs/wiki/Building-ZFS
# https://github.com/zfsonlinux/zfs/wiki/Custom-Packages#debian-and-ubuntu
sudo apt-get install -y build-essential pkg-config autoconf libtool gawk alien fakeroot gdebi wget zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libaio-dev parted lsscsi ksh libssl-dev libelf-dev linux-headers-$(uname -r) python3 python3-dev python3-setuptools python3-cffi < /dev/null


mkdir -p ~/.dev && cd ~/.dev
git clone https://github.com/zfsonlinux/zfs.git
cd zfs
# _newest_release="zfs-0.8.0"
_newest_release="$(git tag | grep -v -E "\-rc" | sort | tail -1)"
git checkout $_newest_release

./autogen.sh
./configure --with-config=user
make -s -j$(nproc)

make -j1 deb-dkms # <----- build fails on this step


# never makes it this far on system B
make -j1 deb-utils

# if successful, then we can now remove the old / existing zfs
apt-get purge -y zfs* < /dev/null
apt-get purge -y spl spl-dkms < /dev/null
apt-get remove spl dkms spl-dkms < /dev/null
apt-get autoremove -y < /dev/null

# install new debs
for file in *.deb; do sudo gdebi -q --non-interactive $file; done
dkms status
```

### Include any warning/errors/backtraces from the system logs

Unfortunately the output from the current (default) build log is not very illuminating. So perhaps if anybody can suggest to re-run the above commands with some extra debugging flags? Many thanks.

**Comment by dreamcat4** [comment]
This is a critical bug for me so... if somebody can answer for as to how I can debug this issue? Then please let me know!

**Comment by dreamcat4** [comment]
OK so there is no logical error message but: Have figured this out now. My build was breaking for the following reason:

Because on system B, zfs was building on zfs inside of `/tmp`. And I had configured my zfs mounpoint of `/tmp/` not to permit executing anything within that folder. For better security. So therefore the bizarre error message that wasn't clearly getting logged anywhere I could easily see / make out.

SO what's the problem then? Maybe we should check if we can execute within `/tmp` early. And exit with an error message if we cannot. The only reason why I say this is because otherwise the log output is not going to shed any light upon this error condition. And it was pretty frustrating to track down. Much time lost. Since the zfs build logs can become pretty extensive once have switched on make debugging flags / trace etc. And it turned out (in the end!) that no clues were anywhere in there.

So please consider for improvement. Many thanks. Otherwise you may close this bug. Kind Regards.

**Comment by c0d3z3r0** [comment]
~~~
+ STATUS=0
+ [ 0 -ne 0 ]
+ cd zfs-0.8.0
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH
+ umask 022
+ cd /tmp/zfs-build-c0d3-axYZCLiD/BUILD
+ cd zfs-0.8.0
+ scripts/dkms.mkconf -n zfs -v 0.8.0 -f dkms.conf
/tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH: 28: /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH: scripts/dkms.mkconf: Permission denied
error: Bad exit status from /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH (%build)


RPM build errors:
    Bad exit status from /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH (%build)
make[1]: *** [Makefile:1336: rpm-common] Error 1
make[1]: Leaving directory '/home/c0d3/src/zfs'
make: *** [Makefile:1291: rpm-dkms] Error 2
~~~

These two lines

~~~
/tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH: 28: /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH: scripts/dkms.mkconf: Permission denied
error: Bad exit status from /tmp/zfs-build-c0d3-axYZCLiD/TMP/rpm-tmp.sqXmYH (%build)
~~~

tell you that there is some permission problem.
