### ISSUE TITLE
building with QAT support for CentOS 7 results in RPMs without QAT support

### ISSUE THREAD

**Issue by ezonakiusagi** [openzfs/zfs#9073]
Distro: CentOS 7.6
Kernel: 3.10.0-957.21.3.el7.x86_64
ZFS / SPL version: 0.8.1-1

I have Intel QAT located in /opt/intel/QAT

when i build ZFS 0.8.1 from source like this:

$ ./configure --with-spec=redhat --with-qat=/opt/intel/QAT
$ make pkg-utils pkg-kmod

the resulting RPM files contain zfs module that does not have QAT. I check via:

$ modinfo /lib/modules/3.10.0-957.21.3.el7.x86_64/extra/zfs/zfs/zfs.ko | grep qat -c
0

If instead, I just skip the packaging, zfs.ko contains QAT support. so, i took the source RPMs, and manually added the "--with-qat=" option to the %configure in the RPM spec file, and rebuild the RPM. After that the zfs.ko module contains QAT support via this check:

$ modinfo /lib/modules/3.10.0-957.21.3.el7.x86_64/extra/zfs/zfs/zfs.ko  |grep qat
depends:        spl,znvpair,qat_api,icp,zlua,zunicode,zcommon,zavl
parm:           zfs_qat_encrypt_disable:Enable/Disable QAT encryption
parm:           zfs_qat_checksum_disable:Enable/Disable QAT checksumming
parm:           zfs_qat_compress_disable:Enable/Disable QAT compression

my guess is that the --with-qat= option isn't getting passed along to the RPM spec files, and the RPM spec files probably need to incorporate support for building with QAT support.

**Comment by behlendorf** [comment]
It looks like you're right.  The `ZFS_AC_RPM` macro in `config/zfs-build.m4` needs to be updated to pass along the `--with-qat` option to the `rpm/generic/zfs-kmod.spec.in` spec file when provided.  Commit f6940bb9ea1ad6905101ba143859983189d32ac5 did add support for the dkms packages by setting the `ICP_ROOT` environment variable.
