### ISSUE TITLE
Snapshot Clones Created Detached

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#9122]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Arch
Distribution Version	|  Current
Linux Kernel	| 4.14.135++
Architecture	| x86-64
ZFS Version	| master
SPL Version	| ...

### Describe the problem you're observing

Creating a clone branch from a zfs snapshot results in the clone _not having_ the source snapshot in its tree, and being un-promotable/un-sendable with the existing dataset's history.

### Describe how to reproduce the problem
```
# zfs clone pool/set@snap pool/newset && zfs list -t snap -d 1 pool/newset 
no datasets available
# zfs promote pool/newset
cannot promote 'pool/newset': not a cloned filesystem
```

**Comment by sempervictus** [comment]
This one actually hurts - i cloned a snapshot of my Nessus dataaset because the latest update corrupted some plugins, i keep its database in a sub-dataset, now i have to manually move files between temporary mounts to fix this mess.
Given the massive glaring problem that this is, i'm wondering if this is something related to unorthodox build/runtime environments or if this was somehow missed upstream. Only major delta i have off master aside from the grsec patch is the kmem allocator PR.

**Comment by ahrens** [comment]
The clone never has the origin in its list of snapshots. What is the origin property of the (alleged) clone?

**Comment by sempervictus** [comment]
Thanks for looking into this sir.
```
# zfs get origin pool/newset
poo/newset  origin    pool/set@snap  -
```
Still unpromotable, and cant send with `-R` as i get
```
# zfs create otherpool/newset
# zfs snap pool/newset@send
# zfs send -Rve pool/newset@send|zfs recv -vFu otherpool/newset
cannot receive: local origin for clone pool/set@snap does not exist
```
Pretty sure that used to work
