### ISSUE TITLE
We could use a standardized methodology for evaluating the impact of generic performance fixes

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#9124]
Benchmarking performance improvements is often done in a haphazard way, which makes it difficult to evaluate the benefits of changes. I suspect that significant cycles might need to spent by contributors on thinking about benchmarking whenever they have a performance fix. Coming up with workload specific benchmarks is a good thing. However, I feel like in the case of certain certain generic improvements, it would be helpful if we had a standardized test suite for evaluating the performance impact of changes. It should include documentation on what each benchmark is measuring, so that it is possible to understand how ZFS performance changes as it is patched in a systematic way.

The only thing close to this would be the Phoronix Test Suite, but the benchmarks there are mostly useless for various reasons (like not measuring what is intended to be measured or not reflecting any kind of real workload), so I think we should come up with our own. Brendan Gregg's micro-benchmarks are not a bad place to start:

https://gist.github.com/brendangregg/7270ff9698c70d9e7496

However, I feel like we should have more than just that. For example, some real world things like database workloads would be useful.

This is a fairly open ended issue. I am opening it to put the idea out there that we need something. Hopefully, if we put our heads together, we could come up with something. That way, when someone sees a potential generic performance improvement, they won't need to spend too much time trying to figure out how to measure the impact.

**Comment by alatteri** [comment]
I would like to see a set of video post production metrics.  I can contribute source material and test goals for such workload.
