### ISSUE TITLE
Could use label to mark trivial PRs

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#9127]
I feel like we could clear PRs more quickly if reviewers that have limited time to volunteer had the simpler PRs marked for them. I have the ability to add one, but I do not want to make the decision unilaterally. I talked to @ahrens about it on slack. It seems that we both like the idea, but we would like @behlendorf to consider it before it is added.

**Comment by ahrens** [comment]
Unfortunately this doesn't fit into our existing label classes (`Type:`, `Component:`, `Status:`), where we apply at most one of each class of label.  But it might warrant a new class, with labels like `Size: small`, `Size: medium`, `Size: large`?

**Comment by ryao** [comment]
i had envisioned a “trivial change” label like how we have “good first issue”. I don’t mind going with small, medium and large classifications though. We might want to add two more levels though. One called trivial for changes that are only a few lines and one called enormous for major reworks (e.g. encryption). I imagine that we could have the patches classified logarithmically by line count. <10 would be trivial, <100 would be small, <1000 would be medium, <10000 would be large and >=10000 would be enormous.

**Comment by kpande** [comment]
it used to be called bytesized.
