### ISSUE TITLE
ZFS pool won't import if poolid is same

### ISSUE THREAD

**Issue by microcai** [openzfs/zfs#9157]
OS: Gentoo
Kernel: 5.2.8
zfs: 8.1

I create a pool on NVME disk, and then insert NVME disk into type-c to M.2 adapter.
the vdev name changed from nvme1n1p2  to /dev/sdc2

```bash
# sudo zpool import -f -d /dev/sdc2 SSD
cannot import 'SSD': no such pool available
```

but zdb can regonize it
```bash
$ sudo zdb -l /dev/sdc2
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'SSD'
    state: 0
    txg: 5488659
    pool_guid: 18079546026535065507
    errata: 0
    hostid: 8323328
    hostname: 'gentoo'
    top_guid: 3891093024939599707
    guid: 3891093024939599707
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 3891093024939599707
        path: '/dev/nvme1n1p2'
        whole_disk: 0
        metaslab_array: 65
        metaslab_shift: 31
        ashift: 12
        asize: 499565199360
        is_log: 0
        DTL: 144
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1 2 3 
```

**Comment by johnnyjacq16** [comment]
You  should use persistent block device naming (#by-id and by-path) to create your zfs pool.
Use  `/dev/disk/by-id/<your device><partition number>` not `/dev/sdc2` or `/dev/nvme1n1p2` which can change at anytime a reboot occurs.

**Comment by nivedita76** [comment]
@johnnyjacq16 it should still be importable with the -d option specified though, I think?

**Comment by microcai** [comment]
No, the reason is not device name change. but same pool id with already imported POOL.
 use zpool reguid to generate a new pool id for already imported pool solved the problem.

zpool should notice user about duplicated pool id.

**Comment by nivedita76** [comment]
Oh! How did that happen?

**Comment by drescherjm** [comment]
I assumed you cloned your device using dd or similar?

**Comment by drescherjm** [comment]
This seems more like a mailing list post than a bug report.

**Comment by microcai** [comment]
I didnt know the cause when I file this bug.

**Comment by GregorKopka** [comment]
@microcai How do you have the pool still imported when putting the NVMe into the adapter, did you pull the drive while being active?

**Comment by devZer0** [comment]
it's not really clear what you did to have two pools with the same name attached to your system. could you describe in more detail for reproducing?

> zpool should notice user about duplicated pool id.

yes, that may be useful

**Comment by sehe** [comment]
`zpool reguid` was the thing I couldn't for the life of me find back. So thanks for mentioning it again @microcai 

FWIW I created the same situation by getting a backup from an AWS EC2 volume snapshot and attaching to the same instance.
