### ISSUE TITLE
zdb: Statistics for used space by block sizes

### ISSUE THREAD

**Issue by zrav** [openzfs/zfs#9158]
Feature request:
To determine the required drive size to be used by allocation classes small blocks feature, it would be helpful to enable zdb to produce statistics for space consumed per block size, for a given pool or dataset. 
Basically I want to be able to determine "the metadata in this pool/dataset plus all blocks of up to 8K size consume X amount of disk space".

**Comment by DeHackEd** [comment]
While this has merit (hello again), the property for how small a block goes to special vdevs can vary by dataset. So such a report, for simplicity, would probably be forced to assume a global default.

(It'd be cool if you could set your desired settings on the actual dataset and then zdb reads them, but you can't set the property without special vdevs in the first place)

**Comment by zrav** [comment]
I was thinking of having zdb simply print a table of space consumed by block size (a histogram really) for the given dataset or pool (not just a single value computed for an assumed special_small_blocks size). One would simply have to add the values up to the desired size to determine the required space.

**Comment by richardelling** [comment]
Yes, I was thinking along the lines of zdb's `-S` option which simulates dedup. Perhaps just adding the output to `-S` is sufficient?

**Comment by DeHackEd** [comment]
`-S` is incredibly memory-intensive (surprise surprise) whereas the current means of getting a metadata measurement is `zdb -Lbbbs $POOLNAME` which has no such problem. Maybe an additional  `b` or `s` adds those details?

**Comment by zrav** [comment]
Both commands only produce output for an entire pool, which would reduce the usefulness of the block histogram (incidentally -S would also benefit if it could be run per dataset).

**Comment by haasn** [comment]
> Maybe an additional `b` or `s` adds those details?

I just wanted to point out that `-bbbb` does indeed print a block size histogram, which we *can* use (with some extra application of awk or similar) to answer the question of how much space would be consumed by different settings of `special_small_blocks`, at least on a whole-zpool basis.

**Comment by zrav** [comment]
When trying out the new feature I get:
```
space_map_open(&sm, spa_meta_objset(spa), sls->sls_sm_obj, 0, UINT64_MAX, SPA_MINBLOCKSHIFT) == 0 (0x34 == 0)
ASSERT at zdb.c:4682:iterate_through_spacemap_logs()Aborted (core dumped)
```

**Comment by behlendorf** [comment]
@zrav if you're running `zdb` against an imported pool you may encounter ASSERTS like this.  The 0x32 error code indicates a checksum error which is possible when the imported pool is being modified by the kernel modules and simultaneous read in user space by `zdb`.  Try exporting the pool the running `zdb` again.
