### ISSUE TITLE
Ask for confirmation before destroy unclean pool

### ISSUE THREAD

**Issue by Harliff** [openzfs/zfs#9171]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Proxmox
Distribution Version	| 6.0
Linux Kernel	| 5.0.15-1-pve
Architecture	| x86_64
ZFS Version	| 0.8.1-pve1
SPL Version	| 0.8.1-pve1 

### Describe the problem you're observing
zpool destroy running without asking for confirmation, even an fs/volumes exist inside it.
It is possible to destroy production pool instead of e.g. test pool due to mistake.  

It's better destroy non-clean pools only with -F ("force") switch.

### Describe how to reproduce the problem
zpool create mypool /dev/sdb
zfs create mypool/important-data
zpool destroy mypool

**Comment by behlendorf** [comment]
Assuming nothing else has used the devices, a destroyed pool can be re-imported using the `zpool import -D` option described in the man page. 

```
            -D      Imports destroyed pools only.  The -f option is also
                     required.
```

**Comment by martellini** [comment]
#4134

**Comment by Harliff** [comment]
> Assuming nothing else has used the devices, a destroyed pool can be re-imported using the `zpool import -D` option described in the man page.

Didn't know that. Thanks!

**Comment by gmelikov** [comment]
I'll close this issue as a duplicate of more general one #4134

**Comment by erikschul** [comment]
Important to note: IIUC `zpool import -D` will import the pool, but the datasets are lost.
