### ISSUE TITLE
Please help me investigating why one dataset keeps disappearing during runtime.

### ISSUE THREAD

**Issue by maniac0s** [openzfs/zfs#9222]
My storage server on Ubuntu 18.04.3 LTS was now running for half a year, quite stable. It's using zfs (raidZ) for the storage partition.

The pools have refreservation and quota set to keep enough space for snapshots.

    pool                          quota           none       default
    pool                          refquota        none       default
    pool                          refreservation  none       default
    pool/db                       quota           none       default
    pool/db                       refquota        100G       local
    pool/db                       refreservation  100G       local
    pool/storage                  quota           none       default
    pool/storage                  refquota        2T         local
    pool/storage                  refreservation  2T         local

After latest update of the whole system, pool/storage keeps disappearing from filesystem but is still listed in zfs.

    root@server:~# mount | grep pool
    pool on /pool type zfs (rw,xattr,noacl)
    pool/db on /pool/db type zfs (rw,xattr,noacl)
    root@server:~# zfs list
    NAME         USED  AVAIL  REFER  MOUNTPOINT
    pool        2.11T  1.40T   104K  /pool
    pool/db   109G  90.6G  9.40G  /pool/db
    pool/storage  2.01T  1.39T   629G  /pool/storage

My monitoring reports a few times a day pool/storage returning to the filesystem and then disappearing again:

Report from 5:21, dataset came back:

    Host:     backup
    Alias:    backup
    Address:  192.168.1.11
    Service:  Filesystem /pool/storage
    Event:    UNKN -> OK
    Output:   OK - 52.9% used (1.06 of 2.00 TB), trend: +342.55 GB / 24 hours
    Perfdata: /pool/storage=1109740.5;1677721.6;1887436.8;0;2097152 fs_size=2097152;;;; growth=4962844.988964;;;; trend=350775.45978;;;0;87381.333333

Disappears again at 6:07:

    Host:     backup
    Alias:    backup
    Address:  192.168.1.11
    Service:  Filesystem /pool/storage
    Event:    OK -> UNKN
    Output:   UNKN - filesystem not found
    Perfdata: 

I don't see anything wrogng in zpool status either

    root@server:~# zpool status
      pool: pool
     state: ONLINE
      scan: scrub repaired 0B in 4h43m with 0 errors on Tue Aug 27 15:01:28 2019
    config:

                	NAME        STATE     READ WRITE CKSUM
                	pool        ONLINE       0     0     0
                	  raidz1-0  ONLINE       0     0     0
                	    sda     ONLINE       0     0     0
                	    sdb     ONLINE       0     0     0

The server runs somewhat as a backup mirror to another server that uses znapzend to send over snapshots frequently. (I somewhat have the feeling the pool disappears when znapzend starts sending however why only the storage dataset and not the database, I don't know) Both servers should have the same zfs pool-setup if I remember correctly, including snapshots and quota. Both servers recently got a complete system update. The "main" server shows no issues with the datasets, they are not disappearing there.

What's going on here? What can I do to investigate into this behavior?

**Comment by GregorKopka** [comment]
It's likely that the moment you 'update' that filesystem using `zfs recv` it'll vanish for a short while (as it's a roll-forward that changes the contents of the mounted filesystem).

**Comment by maniac0s** [comment]
How can I prevent it from vanishing?

**Comment by maniac0s** [comment]
Does no one have an idea bout this?

**Comment by phreaker0** [comment]
@maniac0s set the dataset to readonly on the backup server so it won't be modified by simple stuff like directory listings (atime updates) and so on. This way no rollback is needed for znapzend:

`zfs set readonly=on pool/storage`

You can also check the pool history around the time when the dataset is unavailable with:

`zpool history pool`

**Comment by maniac0s** [comment]
Thanks for your reply. When it's read-only zfs recv (what znapzend uses) can still write to it?

**Comment by phreaker0** [comment]
@maniac0s yes, zfs recv will work regardless. readonly=on only tells zfs to mount the dataset readonly. I use it too with syncoid and --no-rollback option because I have a duplicated server in a primary/secondary setup where each can take the role of primary in which case the automatic rollback could trigger data loss after a switch.

**Comment by maniac0s** [comment]
Ok I will try. I just ran znapzend manually on the storage dataset after I created the whole pool again and the same issue happened just after znapzend started sending. I will try with readonly now.

**Comment by maniac0s** [comment]
Well seems that didn't help at all.

    root@backup:~# zpool history
    History for 'pool':
    2019-09-16.12:44:31 zpool create pool raidz /dev/sda /dev/sdb
    2019-09-16.12:44:31 zfs create pool/db
    2019-09-16.12:44:31 zfs create pool/storage
    2019-09-16.12:44:31 zfs set refreservation=100G pool/db
    2019-09-16.12:44:31 zfs set refreservation=2.0T pool/storage
    2019-09-16.12:44:31 zfs set refquota=2.0T pool/storage
    2019-09-16.12:44:36 zfs set refquota=100G pool/db
    2019-09-16.12:45:32 zfs set readonly=on pool/storage
    2019-09-16.12:45:41 zfs set readonly=on pool/db

On the main server, running znapzend manually with debug output:

    root@server:~# znapzend -d --runonce=pool/storage
    [Mon Sep 16 12:46:04 2019] [info] znapzend (PID=13927) starting up ...
    [Mon Sep 16 12:46:04 2019] [info] refreshing backup plans...
    [Mon Sep 16 12:46:05 2019] [info] found a valid backup plan for pool/storage...
    [Mon Sep 16 12:46:05 2019] [info] znapzend (PID=13927) initialized -- resuming normal operations.
    [Mon Sep 16 12:46:05 2019] [debug] snapshot worker for pool/storage spawned (14272)
    [Mon Sep 16 12:46:05 2019] [info] creating recursive snapshot on pool/storage
    # zfs snapshot -r pool/storage@2019-09-16-124605
    cannot create snapshot 'pool/storage@2019-09-16-124605': out of space
    no snapshots were created
    # zfs list -H -o name -t snapshot pool/storage@2019-09-16-124605
    cannot open 'pool/storage@2019-09-16-124605': dataset does not exist
    [Mon Sep 16 12:46:06 2019] [warn] taking snapshot on pool/storage failed: ERROR: cannot create snapshot pool/storage@2019-09-16-124605
    [Mon Sep 16 12:46:06 2019] [debug] snapshot worker for pool/storage done (14272)
    [Mon Sep 16 12:46:06 2019] [debug] send/receive worker for pool/storage spawned (14605)
    [Mon Sep 16 12:46:06 2019] [info] starting work on backupSet pool/storage
    # zfs list -H -r -o name -t filesystem,volume pool/storage
    [Mon Sep 16 12:46:06 2019] [debug] sending snapshots from pool/storage to root@192.168.1.11:pool/storage
    # zfs list -H -o name -t snapshot -s creation -d 1 pool/storage
    # ssh -o batchMode=yes -o ConnectTimeout=30 root@192.168.1.11 zfs list -H -o name -t snapshot -s creation -d 1 pool/storage
    # zfs send pool/storage@2019-08-29-210000|ssh -o batchMode=yes -o ConnectTimeout=30 'root@192.168.1.11' 'zfs recv -F pool/storage'
    ^C[Mon Sep 16 12:46:47 2019] [debug] SIGINT received.
    [Mon Sep 16 12:46:47 2019] [info] terminating znapzend (PID=13927) ...
    [Mon Sep 16 12:46:47 2019] [warn] ERROR: cannot send snapshots to pool/storage on root@192.168.1.11
    [Mon Sep 16 12:46:47 2019] [warn] ERROR: suspending cleanup source dataset because at least one send task failed
    [Mon Sep 16 12:46:47 2019] [info] done with backupset pool/storage in 41 seconds
    [Mon Sep 16 12:46:48 2019] [info] znapzend (PID=13927) terminated.

Dataset is gone:

    root@backup:~# zfs list
    NAME         USED  AVAIL  REFER  MOUNTPOINT
    pool        2.10T  1.41T   104K  /pool
    pool/db   100G   100G    96K  /pool/db
    pool/storage  2.00T  2.00T    96K  /pool/storage
    root@backup:~# mount | grep pool
    pool on /pool type zfs (rw,xattr,noacl)
    pool/db on /pool/db type zfs (ro,xattr,noacl)

**Comment by phreaker0** [comment]
There are several issues:

- your main server ran out of space so no recent snapshot could be taken
- you just created the dataset on the backup server as shown by your history, this will be the reason why znapsend fails to replicate because there are no common snapshots
- i don't know how znapsend works exactly but' it's interesting that it tries to replicate even though it checks the remote server pool for snapshots (apparently none are found) and still tries to do a full replication which can't work if the target exists (as far I know)

Assuming your just created pool/storage dataset on the backup server is empty, just destroy it and let znapsend create it.

**Comment by maniac0s** [comment]
> your main server ran out of space so no recent snapshot could be taken

That actually should not happen, that's why I created refquota so it keeps space for snapshots there. The whole raidz is 4TB in size, on the main server the quota is set to 1.5T and on the backup it's set to 2.0T

> you just created the dataset on the backup server as shown by your history, this will be the reason why znapsend fails to replicate because there are no common snapshots

Yes well I destroyed everything on the backup and recreated everything. Maybe znapzend keeps a history of snapshots it send and that fails somehow? Maybe I need to clean this up

> i don't know how znapsend works exactly

Well as far as I understand it, it more or less it's just a wrapper for zfs send/recv over ssh with additional backup plan handling as a daemon service that runs automatically.

By the way: I just tried to copy everything from the dataset with rsync to the backup server and it seems to work flawlessly, So it's either a problem with zfs send/recv or with znapzend in general. While it remains interesting that this causes the dataset to disappear completely from the filesystem but still shown in zfs list. I also see no crash reports in the journalctl output on the backup.

**Comment by phreaker0** [comment]
> > your main server ran out of space so no recent snapshot could be taken
> 
> That actually should not happen, that's why I created refquota so it keeps space for snapshots there. The whole raidz is 4TB in size, on the main server the quota is set to 1.5T and on the backup it's set to 2.0T

I'm just reading your provided logs and it happened :-)

> 
> > you just created the dataset on the backup server as shown by your history, this will be the reason why znapsend fails to replicate because there are no common snapshots
> 
> Yes well I destroyed everything on the backup and recreated everything. Maybe znapzend keeps a history of snapshots it send and that fails somehow? Maybe I need to clean this up

That can't work, you cannot create the dataset on the target and then zfs recv another dataset into it as there can't be a common snapshot. You need to let zfs recv create the dataset on the target for you.

> 
> > i don't know how znapsend works exactly
> 
> Well as far as I understand it, it more or less it's just a wrapper for zfs send/recv over ssh with additional backup plan handling as a daemon service that runs automatically.
> 
> By the way: I just tried to copy everything from the dataset with rsync to the backup server and it seems to work flawlessly, So it's either a problem with zfs send/recv or with znapzend in general. While it remains interesting that this causes the dataset to disappear completely from the filesystem but still shown in zfs list. I also see no crash reports in the journalctl output on the backup.

You used zfs recv/send wrongly. If you remove the dataset on the target and let znapsend create it, it should work too.

**Comment by maniac0s** [comment]
> You used zfs recv/send wrongly. If you remove the dataset on the target and let znapsend create it, it should work too.

Ok but why was it working before? Why did this happen after update and reboot of the backup-server?

I mean I created everything and then let it run for a few months without any issues. Just after updating the system, this issue appeared.

And why is it only happening on the pool/storage dataset and not on pool/db even after I destroyed and recreated both manually?

And then zfs is not acutally showing any error on the backup-server side, it just disappears from the mounts while still been seen in zfs list.

I am just trying to recap what went wrong. So many questions.

**Comment by phreaker0** [comment]
I don't know how you did the initial setup but the current one can't work in my point of view. To debug your actual problem we need to get the ordinary replication working and this should be quite easy if you remove the datasets on the backup server and let znapsend to create them properly on the backup server.

**Comment by maniac0s** [comment]
Ok I have now tried the following: I deleted both backup-plans on the main server and created it again (with the same znapzendzetup command I used the first time, taken from bash history).

    [Mon Sep 16 17:31:10 2019] [warn] destination 'root@192.168.1.11:pool/storage' does not exist or is offline. ignoring it for this round...
    [Mon Sep 16 17:31:10 2019] [warn] ERROR: suspending cleanup source dataset because at least one send task failed
    [Mon Sep 16 17:31:10 2019] [info] done with backupset pool/storage in 1 seconds
    [Mon Sep 16 17:31:10 2019] [debug] send/receive worker for pool/storage done (6220)

It says that the dataset doesn't exist...

https://github.com/oetiker/znapzend/blob/master/README.md also doesn't mention some kind of an initialization command other than znapzendzetup.

**Comment by AttilaFueloep** [comment]
On 9/16/19 5:47 PM, mindphuq wrote:
> It says that the dataset doesn't exist...

You'll need the --autoCreation znapzend flag. You can try with `znapzend
--autoCreation --runonce`.

**Comment by maniac0s** [comment]
But I don't understand. I can see in my bash history, that I never used this flag...
