### ISSUE TITLE
ZFS device shows faulted but I know its good

### ISSUE THREAD

**Issue by cscannell-inacloud** [openzfs/zfs#9229]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu
Distribution Version	|  18.04
Linux Kernel	|  Linux 4.15.0-58-generic on x86_64
Architecture	| x64
ZFS Version	|  0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu2

ZPool Status shows

        NAME                        STATE     READ WRITE CKSUM
        zfs-san                     DEGRADED     0     0     0
          raidz2-0                  DEGRADED     0     0     0
            wwn-0x5000c5004d038886  ONLINE       0     0     0
            wwn-0x5000c500408ac603  ONLINE       0     0     0
            649844116982152511      FAULTED      0     0     0  was /dev/sdd1
            sdc                     ONLINE       0     0     6

I know the disk is fine. This happened after upgrading the OS. When I rebooted I noticed the issue.

I don't have another drive and for the life of me can't figure out how to replace the drive with the same drive?
Can someone help please.

**Comment by GregorKopka** [comment]
`zpool online zfs-san /dev/sdd1` ?
`zpool replace zfs-san 649844116982152511 /dev/sdd1` ?
(both in case it's still /dev/sdd1)

**Comment by INaCloud** [comment]
I tried both commands and got the below responses

root@zfs:~# zpool online zfs-san /dev/sdd1
warning: device '/dev/sdd1' onlined, but remains in faulted state
use 'zpool replace' to replace devices that are no longer present
root@zfs:~# zpool replace zfs-san 649844116982152511 /dev/sdd1
invalid vdev specification
use '-f' to override the following errors:
/dev/sdd1 is part of active pool 'zfs-san'
root@zfs:~# zpool replace zfs-san 649844116982152511 /dev/sdd
/dev/sdd is in use and contains a unknown filesystem.

**Comment by devZer0** [comment]
if zfs faulting it, there is a reason for it. 

maybe the disk is fine during testing, but the controller or cabling isn't. or it does have problems with spinup or whatever.

have a look what the kernel event log is telling, most likely there should be disk/scsi/sata errors....and if they are, it's not an zfs issue...
