### ISSUE TITLE
Build failure on 4.9.135-dappersec kernel. Patch available, needs rewrite and merge to master

### ISSUE THREAD

**Issue by UralZima** [openzfs/zfs#9265]
Hello. This is continuation of https://github.com/zfsonlinux/zfs/issues/7960, which was marked as too heated and not available to comment.
The issue is NOT resolved, the latest master still fails to compile on dappersec kernel.

Old commits to @bunder2015 repo that (must) fix the issue
https://github.com/bunder2015/zfs/commit/85552fbf10f90ea8e025c6191d89523db4ce4dbf
https://github.com/bunder2015/zfs/commit/62306e01caddd8111af93d043ef719cea267fdff
(why 2 similar?)

they was NOT merged to master.
I tried to download patches and apply them to latest master, the result: 
patch -p1 < 85552fbf10f90ea8e025c6191d89523db4ce4dbf.patch 
patching file module/zfs/zfs_sysfs.c
Hunk #2 succeeded at 162 (offset 5 lines).
Hunk #3 succeeded at 203 (offset 5 lines).
Hunk #4 FAILED at 389.
Hunk #5 succeeded at 492 (offset 31 lines).
Hunk #6 succeeded at 505 (offset 31 lines).
Hunk #7 succeeded at 526 (offset 31 lines).
Hunk #8 succeeded at 550 (offset 31 lines).
Hunk #9 succeeded at 565 (offset 31 lines).
Hunk #10 succeeded at 580 (offset 31 lines).
Hunk #11 succeeded at 606 (offset 31 lines).
1 out of 11 hunks FAILED -- saving rejects to file module/zfs/zfs_sysfs.c.rej

cat module/zfs/zfs_sysfs.c.rej
```
--- module/zfs/zfs_sysfs.c
+++ module/zfs/zfs_sysfs.c
@@ -389,13 +409,18 @@ kernel_feature_show(struct kobject *kobj, struct attribute *attr, char *buf)
        return (snprintf(buf, PAGE_SIZE, "supported\n"));
 }
 
+static const struct sysfs_ops zfs_kernel_features_sysfs_ops
+{
+       .show = kernel_feature_show
+};
+
 static int
 zfs_kernel_features_init(zfs_mod_kobj_t *zfs_kobj, struct kobject *parent)
 {
        int err;
 
-       err = zfs_kobj_init(zfs_kobj, ZFS_FEATURE_COUNT, 0,
-           kernel_feature_show);
+       err = zfs_kobj_init_static_sysfsops(zfs_kobj, ZFS_FEATURE_COUNT, 0,
+           &zfs_kernel_features_sysfs_ops);
        if (err)
                return (err);

```

so just 1 hunk failed. I am not a coder, so I don't know how to fix this patch to work on latest master.

Please rewrite @bunder2015 's patches and merge them to master. Thanks!

**Comment by bunder2015** [comment]
I am no longer associated with the zfsonlinux project.  Unfortunately I am not able to work on this.
