### ISSUE TITLE
ZFS 0.8.1 is not built with systemd services for Ubuntu

### ISSUE THREAD

**Issue by kvoit** [openzfs/zfs#9274]
### System information
Distribution Name	|  KUbuntu
Distribution Version	|  19.04
Linux Kernel	|  5.0.0-25-generic
Architecture	|  x86_64
ZFS Version	|  0.8.1-1 (git tag 0.8.1)
SPL Version	|  0.8.1-1 (git tag 0.8.1)

### Describe the problem you're observing

I have compiled ZFS on a few systems since the 0.8 release and I have observed multiple, but not all times, that zfs_xxxxxx_amd64.deb is not build with the systemd services.
I have helped myself with copying from system where it built correctly, but I slowly would like to know what I am doing wrong or how to fix this.

### Describe how to reproduce the problem

```
git clone https://github.com/zfsonlinux/zfs
cd zfs
git checkout zfs-0.8.1
./autogen.sh
./configure --with-config=srpm --enable-systemd
make -j1 deb-utils deb-dkms
dpkg --contents zfs_0.8.1-1_amd64.deb|grep systemd
```
Last line has no matches on some of my systems. I don't have the numbers to make a clear statement, but it MIGHT be that the systems in question have been upgraded multiple times, possibly from times when systemd was not standard in Ubuntu.

**Comment by justinianpopa** [comment]
Did you check if the service files exist at "/usr/lib/systemd/system/" after the packages installed?

Doing a "dpkg --contents zfs_0.8.1-1_amd64.deb | grep systemd" on my generated .deb package from the same version shows the files are there, so it must be a config issue on your side. 
You might want to try "make pkg-utils pkg-dkms" instead altough i have found no difference in my builds.

I usually go to "/usr/lib/systemd/system/" and do a "systemctl enable zfs*" after a git build + deb install to make sure all services are enabled and it seems to work fine since 0.8.0-rc1 to the latest release tag.

**Comment by kvoit** [comment]
Yes, they are not there. Because they are not in the deb file.

I do have systems where it works. There, the last line produces
```
zfs-0.8.1 # dpkg --contents zfs_0.8.1-1_amd64.deb|grep systemd
drwxr-xr-x root/root         0 2019-06-20 18:20 ./usr/lib/systemd/
drwxr-xr-x root/root         0 2019-06-20 18:20 ./usr/lib/systemd/system/
-rw-r--r-- root/root       433 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-import-cache.service
-rw-r--r-- root/root       400 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-import-scan.service
-rw-r--r-- root/root       101 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-import.target
-rw-r--r-- root/root       307 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-mount.service
-rw-r--r-- root/root       410 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-share.service
-rw-r--r-- root/root       167 2019-06-20 18:20 ./usr/lib/systemd/system/zfs-zed.service
-rw-r--r-- root/root        76 2019-06-20 18:20 ./usr/lib/systemd/system/zfs.target
drwxr-xr-x root/root         0 2019-06-20 18:20 ./usr/lib/systemd/system-generators/
-rwxr-xr-x root/root      5657 2019-06-20 18:20 ./usr/lib/systemd/system-generators/zfs-mount-generator
drwxr-xr-x root/root         0 2019-06-20 18:20 ./usr/lib/systemd/system-preset/
-rw-r--r-- root/root       208 2019-06-20 18:20 ./usr/lib/systemd/system-preset/50-zfs.preset
```
and
`dpkg --contents zfs_0.8.1-1_amd64.deb|grep init`
produces nothing.
On systems where it does not work, I instead have files for /etc/init.d in the deb.

I am very happily willing to accept that it is a configuration error on my side, but I do not see how any further configuration should be involved here. I even explicitly set --enable-systemd on the configure.
There seems to have binn an issue with that in the past, but #6591 is closed.

**Comment by justinianpopa** [comment]
Checking `./configure` on my side i see
```
--enable-systemd        install systemd unit/preset files [[default: yes]]
--enable-sysvinit       install SysV init scripts [default: yes]
```
So i guess you could try explicitly disabling sysvinit and leave just systemd or maybe try a build without the `--with-config=srpm` switch. 
I think posting your `config.log` might be helpful as well. 
For example, in my config.log at some point i get :
```
configure:37871: checking for systemd support
configure:37873: result: yes
```
and also of note:
```
ZFS_INIT_SYSTEMD='systemd'
systemdgeneratordir='/usr/lib/systemd/system-generators'
systemdpresetdir='/usr/lib/systemd/system-preset'
systemdunitdir='/usr/lib/systemd/system'
```

**Comment by kvoit** [comment]
I do not have that in my config.log:
[config.log](https://github.com/zfsonlinux/zfs/files/3577581/config.log)

Turns out building without `--with-config=srpm` does the trick. I included it because of [this page](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages). It seems to be quite buggy anyway, though, as it does not built the utils as debs.

Thanks!

**Comment by justinianpopa** [comment]
@kvoit 
Glad to help :)

For reference, the page you mentioned specifies how to build RPM-based packages which are used by Fedora/CentOS/RHEL-based distros (usually using the yum package manager). The author seems to have copy-pasted between different distro instructions without reviewing the command changes for Debian.

Your distribution is Debian-based (since you mentioned Kubuntu in the original issue) so you need to generate deb-based packages (used with the dpkg utility). 

Therefore, use (in your case) `make deb-utils deb-dkms` in the future when building for any Debian-based distro.

**Comment by kvoit** [comment]
I disagree with that. The page has different sections for both RPM and DEB and I don't see how it was less intended to describe how to built Debian packages then to build RPM packages.
The Debian description is just wrong and I would suggest correcting that as a fix for this ticket.
If there are deeper issues connected to the fact that `--with-config=srpm` breaks systemd in deb packages, I cannot judge.

**Comment by chong601** [comment]
Not entirely sure if my issue is the same as this post, but I tried to build ZFS on the following system:

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 16.04.6
Linux Kernel	| 4.15.0-62-generic
Architecture	| x86_64
ZFS Version	| 0.8.1-1 (git tag 0.8.1)
SPL Version	| 0.8.1-1 (git tag 0.8.1)

and what happens is that the pools aren't imported properly at all when using the instructions [here](https://github.com/zfsonlinux/zfs/wiki/Custom-Packages). Sometimes it will import without issues, recently it just refuses to import at all.

Running the `zfs-import` and  `zfs-mount` manually also sometimes yield weird results, while importing using `zpool import <poolname>` works as usual.
And there's no systemd units whatsoever, only plain ol' initscripts.

I might give a try on @kvoit's solution in a few days time when I returned to the office.

For those curious about the boot sequence, i attached a copy of the zipped version of the `systemd-analyze plot` graph when it happened:
[boot-sequence.zip](https://github.com/zfsonlinux/zfs/files/3626444/boot-sequence.zip)

**Comment by typoworx-de** [comment]
Got the same issue with ZFS release 0.8.2 build from source: #9621

**Comment by a1exwang** [comment]
Got the same issue with ZFS release 0.8.3. @kvoit's sulotion works for me!

**Comment by darrenfreeman** [comment]
This is also the case with 0.8.4 on Debian 10.3. @kvoit's solution worked,

```
./configure
make -j1 deb-utils deb-dkms
```

I really wish those instructions on https://github.com/openzfs/zfs/wiki/Custom-Packages could be fixed, as this is a source of pain for many people, I'm sure!

**Comment by behlendorf** [comment]
> The Debian description is just wrong and I would suggest correcting that as a fix for this ticket.

@darrenfreeman @kvoit I've gone ahead and updated the documentation accordingly which was wrong.  Would you mind checking the updated directions, if they look good it'd be nice to close this out.

**Comment by kvoit** [comment]
It looks like the suggested and confirmed changes are in there. I see that  `--with-config=srpm` is also gone from the redhat section. I don't know if that is correct.
Unfortunately, I cannot test because I have since moved on to Ubuntu 20.04, which already ships 0.8.3 and I am not to keen on leaving the repository path now :)

**Comment by gdevenyi** [comment]
I can confirm that the new instructions build debs on 18.04, and there appear to be the systemd files in the right place. However, the services are not enabled on install, which is not how debian/ubuntu service installation works by default. So, the debian/ubuntu instructions should include how to enable the proper services for systemd.

**Comment by kvoit** [comment]
From my recollection I would also recommend to thoroughly remove all remainders from a ZFS install from the main repository. I remember quite a chaos in my systemd entries.

**Comment by gdevenyi** [comment]
> From my recollection I would also recommend to thoroughly remove all remainders from a ZFS install from the main repository. I remember quite a chaos in my systemd entries.

Agree, I would try to make the new ZFS packages block on the special ubuntu-zfs packages that exist so that doesn't happen.

My testing was on a fresh no-zfs system, so there were no conflicts there.

**Comment by behlendorf** [comment]
I've added `--enable-systemd` to the Debian/Ubuntu section which worked for me on Ubuntu 18.04.  Any improvements to the packaging would be welcome.

**Comment by darrenfreeman** [comment]
I haven't tested the `--enable-systemd` change, I will do.

One thing that scares me a little, is the zfs-test package. In issue #8756, a user nuked their data with it. I always remove this package if it happens to be installed, as I don't know enough to safely use it. Perhaps the build instructions should exclude installing this package, and only install it in an optional final step?

**Comment by darrenfreeman** [comment]
Should probably include `./autogen.sh`, if using git rather than tarball.

**Comment by gdevenyi** [comment]
> I've added `--enable-systemd` to the Debian/Ubuntu section which worked for me on Ubuntu 18.04. Any improvements to the packaging would be welcome.

@behlendorf that appears to have been a no-op, --enable-systemd was already the default.

I'll try another phrasing here about differences from RedHat/Centos to Debian/Ubuntu, in RH/Centos, installing apache just installs apache and its start scripts, but it doesn't enable the apache service. In comparison, in Debian/Ubuntu, this service is also enabled and started on install. So my first preference would be for the zfs services to enable themselves on install. Alternatively, perhaps for the instructions in general, can we add the commands which will enable the services?

**Comment by charliehorse55** [comment]
+++ This issue. Someone with more knowledge can hopefully update the [Custom packages wiki](https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html) page.  

 I spent 2 hours debugging systemd scripts, finally got it working. Unfortunately I'm not knowledgeable enough to know exactly what commands are needed. Probably something to purge any existing mainline scripts, then install/enable all the required ones for a manual installation.
