### ISSUE TITLE
Using ZVOL inside a VM (KVM virtualization) make system and ZFS hangs

### ISSUE THREAD

**Issue by voxsoftware** [openzfs/zfs#9275]
### System information

Distribution Name	| Ubuntu
Distribution Version	| 18.04
Linux Kernel	| 4.15.0-58-generic
Architecture	|  x64
ZFS Version	|  0.7.5-1ubuntu16.6
SPL Version	|  0.7.5-1ubuntu2

### Describe the problem you're observing
Using ZVOL inside a VM (KVM virtualization) make system and ZFS hangs

### Describe how to reproduce the problem
Is simple, in a vm with KVM import a ZVOL from other system, make reads and writes greaters than 4GB, and you will see that I/O becomes unresponsive. In dmesg, you can observe errors like: Waiting more than 120 seconds ....

Edit: 
```bash
apt install zfsutils-linux
truncate -s180G /root/disk.raw
zpool create disk0 /root/disk.raw

# i always made this but i think is not relevant
zfs  set compression=lz4 disk0

# import a ZVOL using a backup file received from a dedicated server
cat zvol.bk | zfs recv disk0/test

# mount the zvol 
mount /dev/zvol/disk0/test mnt

# create a dataset for copy 
zfs create disk0/copy 

# copy or move some little file, in my examples i see that hangs after about 4GB
# this operations nevers end, and all I/O System becomes unresponsive
mv mnt/bigfile /disk0/copy/bigfile 

```

**Comment by GregorKopka** [comment]
@voxsoftware I have production systems that run KVM/QEMU backed by zvols and don't see this particular issue. Is the 4GB read in one go (reading a file > 4GB), only under heavy load or is it total reads happened while the VM is running?

Adding the stack traces from dmesg might help to diagnose/solve your problem, *dosn't work, gives errors* is a bit too thin for someone to look at it. Also you're running a quite old ZFS, possibly your should try a newer version.

**Comment by voxsoftware** [comment]
Maybe I don't explain all good. I am not saying that my KVM machine are backed by zvols, I am saying that KVM VPS, with ZFS inside the vm with a file backed, doesn't work with ZVOL. I put an example how reproduce the problem, I tested on many VPS, and always have the same result: ZFS Hangs. 

About the version, I installed using: 
```apt install zfsutils-linux```

**Comment by voxsoftware** [comment]
Inside the vm: 
```bash
apt install zfsutils-linux
truncate -s180G /root/disk.raw
zpool create disk0 /root/disk.raw

# i always made this but i think is not relevant
zfs  set compression=lz4 disk0

# import a ZVOL using a backup file received from a dedicated server
cat zvol.bk | zfs recv disk0/test

# mount the zvol 
mount /dev/zvol/disk0/test mnt

# create a dataset for copy 
zfs create disk0/copy 

# copy or move some little file, in my examples i see that hangs after about 4GB
# this operations nevers end, and all I/O System becomes unresponsive
mv mnt/bigfile /disk0/copy/bigfile 

```

**Comment by devZer0** [comment]
you are using a zfs version which is quite old and has many bugs, could you please update to 0.7.13 and try reproducing your problem with that ?

describe your hosts setup (hardware, disk layout, vm layout/disk-mapping ....)  

do you use qcow2 virtual volumes?
