### ISSUE TITLE
Poor performance of the composite MySql query on the Dataset against Zvol

### ISSUE THREAD

**Issue by monsterbnd** [openzfs/zfs#9291]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.2 LTS (Bionic Beaver)
Linux Kernel	| 4.15.0-58-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu2

### Describe the problem you're observing
I have mysqld Ver 5.7.27-0ubuntu0.18.04.1 for Linux on x86_64
Comparison is performed on the same databases (engine=MyISAM). One is located on a dataset against zvol (ext4).
Compound query execution time:
MySql data on dataset - 20 seconds,
MySql data on zvol formatted in ext4 - 10 seconds.

In both cases iostat does not show read operations with hdd or ssd cache.
"time cat /database dir/* > /dev/null" is approximately the same in both.

### Describe how to reproduce the problem
Test [Database](https://drive.google.com/file/d/18dia2GkADbSDuaUW31UsSEwzEk7VQQ1y/view?usp=sharing).
Test [Query](https://pastebin.com/YWDwXJQk).

### Include any warning/errors/backtraces from the system logs
Zpool [status](https://pastebin.com/PWzs3gSm) and [properties](https://pastebin.com/VZmPz5PK).
Dataset [properties](https://pastebin.com/Aw3LQCww), query [profiling](https://pastebin.com/U7WUPu44), bcc-tools [profiling](https://pastebin.com/cr085vu5).
Zvol [properties](https://pastebin.com/NXUAXN40), query [profiling](https://pastebin.com/4K6zUQ4Y), bcc-tools [profiling](https://pastebin.com/iKwUuWWG).
MySql [config](https://pastebin.com/ummYKa2y).

**Comment by timdau** [comment]
I am also seeing this type of performance issue. In my case its zfs vs ext4 directly on a drive(not on a zvol).
