### ISSUE TITLE
add mdbzfs (explore and undelete files from offline pool) - needed feature for brown paper bag "rm" moments

### ISSUE THREAD

**Issue by zenaan** [openzfs/zfs#9313]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10 Buster
Linux Kernel	| 4.19.0-5
Architecture	| amd64
ZFS Version	| 0.7.12-2+deb10u1
SPL Version	| 0.7.12-2

### Describe the problem you're observing
`mdbzfs` (modified mdb for examining zfs on disk and usable for undeleting files offline) is not available, see https://github.com/max123/mdbzfs

I accidentally deleted my Inbox mbox file, realised this and then immediately powered off.

### Describe how to reproduce the problem
Detail:

Within about 10 seconds of downloading about 500 emails into my Inbox, and foolishly using `up arrows + enter` (instead of retyping the needed command), I ran the command `rm mail/Inbox` which deleted my Inbox mbox file, which was last backed up just over 1 year ago and which contained about 10k emails (about 80MiB).

I then hit the power button, held it for 5 seconds, and rebooted, to discover that sure enough, my `Inbox` mbox file was definitely deleted.

Rather new to zfs, I did not know how to stop Debian from auto importing the associated zfs pool, and so it got imported and exported (twice) before I learnt about `-o readonly=on` and `zpool offline device`, although I am familiar with `vi -n`.

About a day later I've finally backed up most of what I needed from the associated zfs volumes in the relevant (single disk) pool. I'm about to learn about snapshots, so did not (yet) use them.

A web search found the above tool (modified version of mdb), and I need someone who knows how to compile it (and quite possibly jiggle the code to compile with ZoL).

### Include any warning/errors/backtraces from the system logs

Direct from journalctl:

`Sep 11 18:34:25 beleageured_host systemd[1]: pebkac_fubar.service: Some silly git failed to make backups more frequently than >1yr; brown paper bag advised.`

**Comment by zenaan** [comment]
See also the following URLS:

https://www.joyent.com/blog/zfs-forensics-recovering-files-from-a-destroyed-zpool

http://mbruning.blogspot.com/2008/08/recovering-removed-file-on-zfs-disk.html

This might be interesting:
https://www.klennet.com/notes/2019-01-05-zfs-undelete.aspx

First found the dead link to zol archives and mdbzfs here:
https://forums.freebsd.org/threads/restoring-deleted-file-from-zfs-file-system.15720/

**Comment by zenaan** [comment]
And as a reminder to any budding hero, zfs-fuse, and a bunch of very friendly ZoL developers, exist :)

Reading some of the above links (albeit not understanding so much of them), one can imagine a read-only zfs fuse variant which presents mounts for each of the uberblocks of the zpool at issue.

Anything more complicated would be serious bonus points for those leveling up on their public hero persona :)

**Comment by zenaan** [comment]
If anyone knows how to pipe/ combine something with magicrescue to decompress zfs compressed blocks, that would be quite useful.

**Comment by GregorKopka** [comment]
First things first: In case you care about your data _at all_ you should ASAP export the pool, make a block-level backup of all pool member drives (or partitions), physically offline the original drives, store them in a safe location and only work on the copies (even better would be to work on copies of the copies, so you don't have to touch the original in case you need another copy). 

That being said, the question of you getting your data back is a question of the timing.

> Rather new to zfs, I did not know how to stop Debian from auto importing the associated zfs pool, and so it got imported and exported (twice) before I learnt about `-o readonly=on` and `zpool offline device`, although I am familiar with `vi -n`.

Question is how long the pool had been imported and how active it has been (new writes):
ZFS round-robin overwrites the oldest uberblock (basically pointers to the on-disk block that is the root of the current on-disk state) each TXG (30s default setting on an idle pool, can be way shorter under load) and the higher the ashift of the pool members the less uberblocks there are.

Also free'd blocks (that contained the file contents or metadata) might have been overwritten by new data.

In case the last uberblock that pointed toward an on-disk state where your Inbox still exists and the blocks containing the file (data+metadata) havn't been recycled yet... might give the option to roll back the pool (-T flag for `zpool import`) to a point in time before the delete happened, which would restore (parts of) the file.

> Within about 10 seconds of downloading ... I ran the command `rm mail/Inbox`

Given my last paragraph being the case: In case a TXG sync happened *inbetween* these two actions you might have a chance at getting the full freshly downloaded data, else some *will* be lost (as any data added to the file in the TXG where you issued the rm won't have made it to disk).

But in case the on-disk data pointed to by the oldest uberblock dosn't reference that file anymore you would need to scan the pool members for the (now unreferenced) metadata (which might be anywhere, without any clue where it might be should it still exist) but while that might be possible _in theory_ (as validity of a metadata block could be verified through the checksums of the pointed-to data) no code exists that is able to automate this AFAIK. So while you could write it (or force someone with a big bag of money to do it for you) you can likely forget about it (if working at all) being a quick solution.

**Comment by GregorKopka** [comment]
Regarding the `cannot import 'zpih2t': one or more devices is currently unavailable`: you could try to move /etc/zfs/zpool.cache out of the way and retry the import, or point zpool import -d to a directory only containing symlinks to the partitions(s) of the actual pool member vdev(s).

Also: you *really want* to experiment with a copy of your (currently) only copy.
