### ISSUE TITLE
zfs-dkms debian package fails to install

### ISSUE THREAD

**Issue by wyllys66** [openzfs/zfs#9331]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 16.04.4
Linux Kernel	| 4.19.34
Architecture	| x86_64
ZFS Version	| 0.8.1-3~16.04.york0
SPL Version	| 0.8.1-3~16.04.york0

### Describe the problem you're observing

Postinstall scripts for the zfsutils-linux module fail to install when first run due to zfs-mount systemd service failure.  Running it a 2nd time will succeed with no errors.  It not obvious why zfs-mount fails the first time.

### Describe how to reproduce the problem

```
$ sudo apt-get install zfs-dkms
```

### Include any warning/errors/backtraces from the system logs

```
Building initial module for 4.19.34-041934-generic
Done.

zavl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

znvpair.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

zunicode.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

zcommon.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

icp.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

zlua.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

spl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.34-041934-generic/updates/dkms/

depmod....

DKMS: install completed.
Setting up spl-dkms (0.8.1-3~16.04.york0) ...
Setting up zfsutils-linux (0.8.1-3~16.04.york0) ...
Job for zfs-mount.service failed because the control process exited with error code. See "systemctl status zfs-mount.service" and "journalctl -xe" for details.
invoke-rc.d: initscript zfs-mount, action "start" failed.
* zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-09-16 13:09:38 EDT; 126ms ago
     Docs: man:zfs(8)
  Process: 101421 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
 Main PID: 101421 (code=exited, status=1/FAILURE)

Sep 16 13:09:38 ks3gw1 systemd[1]: Starting Mount ZFS filesystems...
Sep 16 13:09:38 ks3gw1 zfs[101421]: The ZFS modules are not loaded.
Sep 16 13:09:38 ks3gw1 zfs[101421]: Try running '/sbin/modprobe zfs' as root to load them.
Sep 16 13:09:38 ks3gw1 systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 13:09:38 ks3gw1 systemd[1]: Failed to start Mount ZFS filesystems.
Sep 16 13:09:38 ks3gw1 systemd[1]: zfs-mount.service: Unit entered failed state.
Sep 16 13:09:38 ks3gw1 systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
dpkg: error processing package zfsutils-linux (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of zfs-zed:
 zfs-zed depends on zfsutils-linux (>= 0.8.1-3~16.04.york0); however:
  Package zfsutils-linux is not configured yet.

dpkg: error processing package zfs-zed (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.2) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 zfsutils-linux
 zfs-zed
E: Sub-process /usr/bin/dpkg returned an error code (1)
$
```

The ZFS module *IS* loaded and working.  Running apt-get install a 2nd time will succeed.
```
$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up zfsutils-linux (0.8.1-3~16.04.york0) ...
Setting up zfs-zed (0.8.1-3~16.04.york0) ...
Processing triggers for systemd (229-4ubuntu21.2) ...
Processing triggers for ureadahead (0.100.0-19) ...
$
```

**Comment by jordanmendler** [comment]
This is still an issue with 5.8.0-1 kernel



Setting up zfs-dkms (0.8.4-2) ...
Removing old zfs-0.8.4 DKMS files...

------------------------------
Deleting module version: 0.8.4
completely from the DKMS tree.
------------------------------
Done.
Loading new zfs-0.8.4 DKMS files...
Building for 5.7.0-2-amd64 5.8.0-1-amd64
Module build for kernel 5.7.0-2-amd64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.8.0-1-amd64
grep: /lib/modules/5.8.0-1-amd64/build/include/linux/miscdevice.h: No such file or directory
configure: error: 
	*** None of the expected "global page state" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-0.8.4-2
	*** Compatible Kernels: 2.6.32 - 5.6
	
Error! Bad return status for module build on kernel: 5.8.0-1-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.8.4/build/make.log for more information.
dpkg: error processing package zfs-dkms (--configure):
 installed zfs-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of zfs-initramfs:
 zfs-initramfs depends on zfs-modules | zfs-dkms; however:
  Package zfs-modules is not installed.
  Package zfs-dkms which provides zfs-modules is not configured yet.
  Package zfs-dkms is not configured yet.

dpkg: error processing package zfs-initramfs (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.139) ...
update-initramfs: Generating /boot/initrd.img-5.8.0-1-amd64
I: The initramfs will attempt to resume from /dev/sda6
I: (UUID=ed50f26c-a201-4381-806d-a9c6b2b4766a)
I: Set the RESUME variable to override this.

**Comment by jordanmendler** [comment]
To make it compile, just symlink the missing folder from kernel source:

`sudo ln -s /usr/src/linux-headers-5.8.0-1-common/include/linux /lib/modules/5.8.0-1-amd64/build/include/linux`

**Comment by vic-blt** [comment]
I have the same problem.
When trying to install ZFS 0.8.4 with kernel 5.8.0-2-amd64 on debian testing, I get this error :
```
Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-2-amd64................(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.0-2-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.8.4/build/make.log for more information.
```
Here's the content of `/var/lib/dkms/zfs/0.8.4/build/make.log` :
```
DKMS make.log for zfs-0.8.4 for kernel 5.8.0-2-amd64 (x86_64)
Mon Sep 28 02:24:23 CEST 2020
./scripts/make_gitrev.sh
/bin/bash: ./scripts/make_gitrev.sh: No such file or directory
make: [Makefile:1518: gitrev] Error 127 (ignored)
make  all-recursive
make[1]: Entering directory '/var/lib/dkms/zfs/0.8.4/build'
Making all in module
make[2]: Entering directory '/var/lib/dkms/zfs/0.8.4/build/module'
list='icp lua'; for targetdir in $list; do \
	make -C $targetdir; \
done
make[3]: Entering directory '/var/lib/dkms/zfs/0.8.4/build/module/icp'
mkdir -p api core spi io os algs algs/aes algs/edonr algs/modes algs/sha1 algs/sha2 algs/skein asm-x86_64 asm-x86_64/aes asm-x86_64/modes asm-x86_64/sha1 asm-x86_64/sha2 asm-i386 asm-generic
make[3]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module/icp'
make[3]: Entering directory '/var/lib/dkms/zfs/0.8.4/build/module/lua'
mkdir -p setjmp
make[3]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module/lua'
make -C /lib/modules/5.8.0-2-amd64/build M=`pwd`  O=/lib/modules/5.8.0-2-amd64/build CONFIG_ZFS=m modules
make[3]: Entering directory '/usr/src/linux-headers-5.8.0-2-amd64'
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/illumos-crypto.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/avl/avl.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lapi.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/nvpair.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_cipher.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/avl/zavl.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-condvar.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-cred.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lauxlib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_digest.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-err.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/fnvpair.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-generic.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lbaselib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/nvpair_alloc_spl.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_mac.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/nvpair_alloc_fixed.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/nvpair/znvpair.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/unicode/u8_textprep.o
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c: In function ‘spl_kmem_alloc_impl’:
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:183:11: error: too many arguments to function ‘__vmalloc’
  183 |     ptr = __vmalloc(size, lflags | __GFP_HIGHMEM,
      |           ^~~~~~~~~
In file included from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vmem.h:30,
                 from /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:28:
/usr/src/linux-headers-5.8.0-2-common/include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lcode.o
make[6]: *** [/usr/src/linux-headers-5.8.0-2-common/scripts/Makefile.build:286: /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.o] Error 1
make[5]: *** [/usr/src/linux-headers-5.8.0-2-common/scripts/Makefile.build:502: /var/lib/dkms/zfs/0.8.4/build/module/spl] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_miscapi.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/api/kcf_ctxops.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lcompat.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/core/kcf_callprov.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lcorolib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/core/kcf_prov_tabs.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/unicode/uconv.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lctype.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/core/kcf_sched.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/ldebug.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/ldo.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/unicode/zunicode.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lfunc.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lgc.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/core/kcf_mech_tabs.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/core/kcf_prov_lib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/llex.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/spi/kcf_spi.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/io/aes.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lmem.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lobject.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/io/edonr_mod.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/io/sha1_mod.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lopcodes.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lparser.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lstate.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/io/sha2_mod.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/io/skein_mod.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/os/modhash.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lstring.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lstrlib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/ltable.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/os/modconf.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/cbc.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/ltablib.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/ccm.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/ltm.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/ctr.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lvm.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/ecb.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/lzio.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/gcm_generic.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/setjmp/setjmp.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/gcm.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/modes.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/aes/aes_impl_generic.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/lua/zlua.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/aes/aes_impl.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/aes/aes_modes.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/edonr/edonr.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/sha1/sha1.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/sha2/sha2.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/skein/skein.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/skein/skein_block.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/skein/skein_iv.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/aes/aeskey.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/aes/aes_amd64.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/aes/aes_aesni.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/modes/gcm_pclmulqdq.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha1/sha1-x86_64.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha256_impl.o
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha512_impl.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/modes/aesni-gcm-x86_64.o
  AS [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/modes/ghash-x86_64.o
/var/lib/dkms/zfs/0.8.4/build/module/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/modes/gcm_pclmulqdq.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/aes/aes_impl_aesni.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/algs/aes/aes_impl_x86-64.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/icp/icp.o
make[4]: *** [/usr/src/linux-headers-5.8.0-2-common/Makefile:1764: /var/lib/dkms/zfs/0.8.4/build/module] Error 2
make[3]: *** [/usr/src/linux-headers-5.8.0-2-common/Makefile:185: __sub-make] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.8.0-2-amd64'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module'
make[1]: *** [Makefile:807: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build'
make: *** [Makefile:676: all] Error 2
```

**Comment by jordanmendler** [comment]
@vic-blt Did you symlink to the correct kernel? The symlink I posted was initially at kernel 5.8.0-1 whereas now its 5.8.0-2. Also which distribution are you on? I'm on Debian Sid.

`ARCH=amd64 ; KERNEL=5.8.0-2 ; sudo ln -s /usr/src/linux-headers-$KERNEL-common/include/linux /usr/src/linux-headers-$KERNEL-$ARCH/include`

**Comment by jordanmendler** [comment]
FYI...

jordan@jordan-laptop:/usr/src/linux-headers-5.8.0-1-amd64/include$ sudo apt-get install --reinstall zfs-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 381 not upgraded.
Need to get 0 B/1,906 kB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 491713 files and directories currently installed.)
Preparing to unpack .../zfs-dkms_0.8.4-2_all.deb ...

-------- Uninstall Beginning --------
Module:  zfs
Version: 0.8.4
Kernel:  5.8.0-1-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

zavl.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/avl/avl/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


znvpair.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/nvpair/znvpair/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zunicode.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/unicode/zunicode/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zcommon.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/zcommon/zcommon/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zfs.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/zfs/zfs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


icp.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/icp/icp/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zlua.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/lua/zlua/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


spl.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-1-amd64/extra/spl/spl/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  zfs
Version: 0.8.4
Kernel:  5.8.0-2-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

zavl.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/avl/avl/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


znvpair.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/nvpair/znvpair/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zunicode.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/unicode/zunicode/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zcommon.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/zcommon/zcommon/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zfs.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/zfs/zfs/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


icp.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/icp/icp/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zlua.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/lua/zlua/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


spl.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.8.0-2-amd64/extra/spl/spl/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.8.4
completely from the DKMS tree.
------------------------------
Done.
Unpacking zfs-dkms (0.8.4-2) over (0.8.4-2) ...
Setting up zfs-dkms (0.8.4-2) ...
Loading new zfs-0.8.4 DKMS files...
Building for 5.8.0-1-amd64 5.8.0-2-amd64
Building initial module for 5.8.0-1-amd64
Done.

zavl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/avl/avl/

znvpair.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/nvpair/znvpair/

zunicode.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/unicode/zunicode/

zcommon.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/zcommon/zcommon/

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/zfs/zfs/

icp.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/icp/icp/

zlua.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/lua/zlua/

spl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-1-amd64/extra/spl/spl/

depmod...

DKMS: install completed.
Building initial module for 5.8.0-2-amd64
Done.

zavl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/avl/avl/

znvpair.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/nvpair/znvpair/

zunicode.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/unicode/zunicode/

zcommon.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/zcommon/zcommon/

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/zfs/zfs/

icp.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/icp/icp/

zlua.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/lua/zlua/

spl.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.8.0-2-amd64/extra/spl/spl/

depmod...

DKMS: install completed.
Processing triggers for initramfs-tools (0.139) ...
update-initramfs: Generating /boot/initrd.img-5.8.0-2-amd64

**Comment by vic-blt** [comment]
> @vic-blt Did you symlink to the correct kernel? The symlink I posted was initially at kernel 5.8.0-1 whereas now its 5.8.0-2. Also which distribution are you on? I'm on Debian Sid.
> 
> `ARCH=amd64 ; KERNEL=5.8.0-2 ; sudo ln -s /usr/src/linux-headers-$KERNEL-common/include/linux /usr/src/linux-headers-$KERNEL-$ARCH/include`

Yep I symlinked the correct kernel. I'm on Debian Testing.

**Comment by vic-blt** [comment]
@jordanmendler I didn't saw the update for zfs.
As stated in the changelog of zfs version 0.8.4-2 [here](https://launchpad.net/debian/+source/zfs-linux/+changelog) :
>    \+ Add Linux 5.8 compat fix (4520-Linux-5.8-compat-__vmalloc.patch)

Which fixes the error `error: too many arguments to function ‘__vmalloc’`.

**Comment by behlendorf** [comment]
Closing.  As mentioned above this was addressed in the packaging.

**Comment by danieldjewell** [comment]
Actually, I think this is more of a merge/duplicate and hasn't been fixed yet. See #9935

**Comment by 3dRikal** [comment]
This is still an issue on 6.1.0-27 as of 2024-11-18
