### ISSUE TITLE
After accidentally letting a ZFS on root volume fill, the zpool is no longer importable

### ISSUE THREAD

**Issue by stevenmcastano** [openzfs/zfs#9388]
I've got an Ubuntu 18.0.4 server that was build with a root filesystem on ZFS. Not knowing the server was low on space a package upgrade was run which started downloading a 700MB .deb file. This filled the disk to 100% and hung the server.

At that point the server was rebooting and would not come back up. The message on the screen was that the was an unrecoverable error on the filesystem.

I immediately made clones and images of this disk and I'm trying to do anything to import the 'rpool' volume and access the data.

* A simple "zpool import rpool" just sits there for hours seeming to do nothing with 1 CPU pegged at 100 in IOwait state.
* Listing the last transactions and trying to restore with -N -FX -T <txg_number> also just sits there
* Trying to import with -o readonly=on, same thing
* I even ran the zfs_revert script the zero's out some of the last transactions, and still nothing.

Are there any other options I'm not trying. There is fairly important data on this disk I would really like to get back. Getting the server to boot again would be amazing, but at this point just a readonly copy of the data would be great to rebuild with.

**Comment by behlendorf** [comment]
> Are there any other options I'm not trying.

Try setting the module option `spa_slop_shift=6` then importing the pool.  This option controls the default amount of reserved space in the pool.  It defaults to **~3.2%** (1/2^5), setting it to 6 will decrease the reserve size to **~1.6%** (1/2^6).  That may provide a enough elbow room to import the pool so a few files can be removed.

That said, filling the pool to 100% capacity should never render the pool unimportable.  There were a couple relevant improvements made is newer version of ZFS.  If possible could you try importing the pool with the 0.8.2 release, it may handle it better.

**Comment by richardelling** [comment]
also, a readonly pool import should work

**Comment by gmelikov** [comment]
Is deduplication enabled?
