### ISSUE TITLE
zfs set sharesmb=on segfaults

### ISSUE THREAD

**Issue by otommod** [openzfs/zfs#9419]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Alpine Linux
Distribution Version	| 3.10
Linux Kernel	| 4.19
Architecture	| x86_64
ZFS Version	| 0.8.1
SPL Version	| 0.8.1

### Describe the problem you're observing
Running `zfs set sharesmb=on mypool` segfaults.  It actually happens with both `off` and `on` and it also happens with `sharenfs`.  I tried other values (quota, atime) and they work fine.  I believe the problem is only with the cli tool and not the kernel module; my pool is running fine.

### Include any warning/errors/backtraces from the system logs
The `zfs` package in the Alpine doesn't have debug symbols so I built it from source.

On debugging the core it seems the problem is in `zfs_do_list_ioctl` because `zhp->zfs_hdl` is `NULL`.

**Comment by nabakishore** [comment]
What is the path on which the property is set? This possibly is coming from a path containing # "bookmark".  It may fail to set zhp->zfs_hdl when zfs_open is called for such path.

**Comment by otommod** [comment]
It was set on the whole pool (named `tank`).  I tried `zfs set sharesmb=off tank` just now and it actually worked.

I am on 
zfs-0.8.2-1
zfs-kmod-0.8.1-1
