### ISSUE TITLE
ZFS 0.7.x repository for CentOS 7.7

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#9421]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS 7
Distribution Version	| 7
Linux Kernel	| 3.10.0-1062.1.1.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.13-1
SPL Version	| 0.7.13-1

### Describe the problem you're observing
Currently, CentOS 7.7 does not have a proper repository for ZFS 0.7.x. Rather, as reported [here](https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS), newer repository will track ZFS 0.8.x

For the moment, I am running ZFS 0.7.13 on CentOS 7.7 without apparent issues - but this is not a strong guarantee that all is really OK. Please consider creating/enabling a repository for tracking ZFS 0.7.x on newer CentOS 7.x releases.

**Comment by dacianstremtan** [comment]
There is a new repo for CentOS 7.7:
https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS

EL7.7 Package: http://download.zfsonlinux.org/epel/zfs-release.el7_7.noarch.rpm

**Comment by behlendorf** [comment]
@shodanshok would it be reasonable to include a version of `0.7.13` in the same repository as 0.8.x.  You could then manually install the older version?

**Comment by shodanshok** [comment]
@behlendorf sure, it seems a good approach. In this case, remaining on `0.7.x` would be nothing more than an appropriate `exclude/include` line in the repo config.

As a side note, how do you feel about having a `zfs-release.el7_latest` tracking the latest RHEL 7.x release, with both `0.7.x` and `0.8.x`, maybe with `kmod` enabled by default, for anyone closely following the latest RHEL/CentOS point release?

**Comment by shodanshok** [comment]
@behlendorf Hi, any news on the matter? Is using the [zfs CentOS 7.6 repository](http://download.zfsonlinux.org/epel/zfs-release.el7_6.noarch.rpm) on a CentOS 7.7 box OK? Thanks.

**Comment by behlendorf** [comment]
There was a CentOS 7.7 repository added, are you having problems with it?

**Comment by shodanshok** [comment]
The current CentOS 7.7 repository has ZFS 0.8.x, which is great, but this issue tracks the availability of ZFS **0.7.x** for CentOS 7.7+

The rationale is that for running, production CentOS7 servers I would like to maintain the 0.7.x branch for the immediate future, switching to ZFS 0.8.x later.

Thanks.

**Comment by behlendorf** [comment]
That's right, my mistake I should have read this issue more closely and I lost track of possibly including 0.7.13 in the repository.  The CentOS 7.6 repository will work fine, and I'll take a note (again) to look in to this.

**Comment by gdevenyi** [comment]
@shodanshok is there much point? https://github.com/zfsonlinux/zfs/issues/9454

**Comment by shodanshok** [comment]
@gdevenyi I would say yes - it make sense as I am using 0.7.13 in almost all my current servers and it does not show any serious problems.

When a newer CentOS 7 releases happen (7.7 in this case, 7.8 in the future) I would like to use an official 0.7.x package for them.

I *do* plan to update to 0.8.x, but I want to wait a bit more.

@behlendorf So you confirm that the 7.6 repository is going to work just fine on CentOS 7.7 (matching my current experience)?

Thanks.

**Comment by behlendorf** [comment]
@shodanshok yes.  From CentOS 7.6 to 7.7 there were no kABI changes for symbols used by the ZFS kmods so they will continue to work fine.  The DKMS packages will clearly get rebuilt against the latest kernel so there's no issue there either.

**Comment by shodanshok** [comment]
@behlendorf It seems that with the upcoming CentOS 7.8 the current ZFS 0.7.x kmod does not work anymore (see https://github.com/openzfs/zfs/issues/10208#issuecomment-616509862). Any plans to update the 0.7.x repository to work with future CentOS 7.x installations?
Thanks.

**Comment by behlendorf** [comment]
Yes, we'll need to rebuild the kmods for CentOS 7.8 cc: @tonyhutter

**Comment by jgrund** [comment]
@behlendorf @tonyhutter Would it be possible to rebuild for CentOS 7.8? 

We are also using ZFS 0.7.13 for now and are currently blocked on this.
