### ISSUE TITLE
swap on zvol causes high system latency when memory pressure occurs

### ISSUE THREAD

**Issue by jmesmon** [openzfs/zfs#9435]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| arch
Distribution Version	| 2019-10-09
Linux Kernel	| 5.3.1-arch1-1-ARCH
Architecture	| x86_64
ZFS Version	| zfs-0.8.2-1

### Describe the problem you're observing

When using a zvol as swap, if something pushes ram usage higher (for example, starting a virtual machine), then high system latency (visible in Xorg) occurs: display stops updating, mouse stops moving, keyboard stops responding. Latency in ssh sessions appears minimal. When the swap device is removed (`swapoff`), the system behavior returns to normal (even with the memory consuming application still running).

### Describe how to reproduce the problem

```
zfs create -V 4G -b $(getconf PAGESIZE) -o compression=zle -o logbias=throughput -o sync=always -o primarycache=metadata -o secondarycache=none -o com.sun:auto-snapshot=false ${ZFS}/swap
mkswap /dev/zvol/${ZFS}/swap
swapon /dev/zvol/${ZFS}/swap
# perform enough zfs access & run applications so that memory is almost filled
# start something that allocates enough memory so that zfs would need to flush some pages from the ARC (this is a presumption given the behavior. I'm starting VirtualBox vms with 8GiB of ram allocated to them)
```

### Include any warning/errors/backtraces from the system logs

No warnings/errors/etc in system logs from this timeframe

**Comment by devZer0** [comment]
https://github.com/zfsonlinux/zfs/issues/7734
