### ISSUE TITLE
zfs falsely reports harddisk was removed by administrator 

### ISSUE THREAD

**Issue by devZer0** [openzfs/zfs#9500]
Distribution Name	|  proxmox pve 
Distribution Version	| 5.4-5
Linux Kernel	| 4.15.18-12-pve)
Architecture	| x86_64
ZFS Version	| 0.7.13-pve1~bpo1
SPL Version	| 0.7.13-pve1~bpo1

zfs is telling that harddisk has been removed by the administrator - but meanwhile, no admin touched this system.

this disk is inside a 2nd node which is automatically powered on on a temporary basis and the 2nd harddisk inside started to get flaky some time ago, i.e. it has defective blocks and sometimes it simply doesn't spin up.

zfs should not tell untruth (which even may lead to misunderstanding in an environment where different sysadmins have a look at the systems)

```
yesterday: 

  pool: rpool
 state: DEGRADED
status: One or more devices has been removed by the administrator.
	Sufficient replicas exist for the pool to continue functioning in a
	degraded state.
action: Online the device using 'zpool online' or replace the device with
	'zpool replace'.
  scan: scrub repaired 6.59G in 7h43m with 0 errors on Mon Oct 21 08:18:55 2019
config:

	NAME                                                          STATE     READ WRITE CKSUM
	rpool                                                         DEGRADED     0     0     0
	  mirror-0                                                    DEGRADED     0     0     0
	    /dev/disk/by-id/ata-SAMSUNG_HE103UJ_S13VJ1KS601796-part3  ONLINE       0     0     0
	    /dev/disk/by-id/ata-ST31000340NS_9QJ4A9C5-part3           REMOVED      0     0     0

the day before:

ZFS Status proxmox2:
  pool: rpool
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub repaired 6.59G in 7h43m with 0 errors on Mon Oct 21 08:18:55 2019
config:

	NAME                                                          STATE     READ WRITE CKSUM
	rpool                                                         ONLINE       0     0     0
	  mirror-0                                                    ONLINE       0     0     0
	    /dev/disk/by-id/ata-SAMSUNG_HE103UJ_S13VJ1KS601796-part3  ONLINE       0     0     0
	    /dev/disk/by-id/ata-ST31000340NS_9QJ4A9C5-part3           ONLINE       0     0 17.6K
```

**Comment by mscottie** [comment]
Since upgrading to 0.8.2-1, I'm seeing this behavior, too, as well as lots of checksum errors on all of the devices in one of my two zpools. Once I stop zed, everything works fine. Start zed again, all this comes back. I'd love to provide some information to help track this down, as it is seriously frightening to see every drive in your pool as DEGRADED.

**Comment by devZer0** [comment]
anti-stale-bot-post

**Comment by devZer0** [comment]
stale bot sucks

**Comment by devZer0** [comment]
@behlendorf or @shodanshok ( sorry to bother you, but these names coming to my mind from which i know they have github account and i can @mention here)  -  can you (or some other persn with permission) please reopen this ticket ?  so i would not  need to add another, new one. 

this issue still exists with zfs 2.2.6 (latest proxmox) and on that system, the vanished drive did remove from the sas port while running and without reboot.   it appears to be "flaky" , having hiccup and probably going to die soon -  but when a drive gets lost by whatever event, zfs should not tell that it had been pulled by an admin, i.e. it should not tell the untruth when not knowing better

**Comment by amotin** [comment]
@devZer0 The ticket was open for ancient ZFS 0.7, while IIRC @ixhamza rewritten that code much later in 2.1 or 2.2 time frame.  I propose you to open a new issue with new data and new motivation.  There were recently observations that current ZFS on Linux and FreeBSD have different reporting for removed disks, that might need to be reconsidered.  But ancient report of something wrong in that area is not helpful.  It needs a deeper look.

**Comment by devZer0** [comment]
ok. then we will need to wait until it happens again and i have fresh live data. thank you.
