### ISSUE TITLE
history_event-zfs-list-cacher.sh cases very high load with large number of zevents

### ISSUE THREAD

**Issue by rbt** [openzfs/zfs#9584]
I'm using Ubuntu 19.10 as configured by the installer (whole disk, compression enabled).

The crux is, I'm getting a very large number of zevents continually generated by containerd within microk8s. It seems to create a zfs filesystem for each instance of a container and later throws it away; with cronjobs this can create a very high load. This part is relatively fast but it does create a zevent for the mount

history_event-zfs-list-cacher.sh, however, takes several seconds to run.

time zfs list -H -o name,mountpoint,canmount,atime,relatime,devices,exec,readonly,setuid,nbmand
<-- snip output -->
real	0m3.415s
user	0m0.257s
sys	0m3.149s

This is the lifecycle for a single job which triggers the event. There may be half a dozen jobs spawning in a minute even within my dev environment. I think "clone" is ignored, but the mountpoint and destroy both trigger a cache rebuild.
```
Nov 13 2019 22:17:47.795814894 sysevent.fs.zfs.history_event
        version = 0x0
        class = "sysevent.fs.zfs.history_event"
        pool = "rpool"
        pool_guid = 0x928fbd0244ed366
        pool_state = 0x0
        pool_context = 0x0
        history_hostname = "rbt-inspiron-123"
        history_dsname = "rpool/containerd/10236"
        history_internal_str = "origin=rpool/containerd/1@snapshot (42512)"
        history_internal_name = "clone"
        history_dsid = 0x78ff
        history_txg = 0x633d3
        history_time = 0x5dccc75b
        time = 0x5dccc75b 0x2f6f2bee 
        eid = 0x1cc69b

Nov 13 2019 22:17:48.379820999 sysevent.fs.zfs.history_event
        version = 0x0
        class = "sysevent.fs.zfs.history_event"
        pool = "rpool"
        pool_guid = 0x928fbd0244ed366
        pool_state = 0x0
        pool_context = 0x0
        history_hostname = "rbt-inspiron-123"
        history_dsname = "rpool/containerd/10236"
        history_internal_str = "mountpoint=legacy"
        history_internal_name = "set"
        history_dsid = 0x78ff
        history_txg = 0x633d4
        history_time = 0x5dccc75c
        time = 0x5dccc75c 0x16a39bc7 
        eid = 0x1cc69c

Nov 13 2019 22:22:22.362682704 sysevent.fs.zfs.history_event
        version = 0x0
        class = "sysevent.fs.zfs.history_event"
        pool = "rpool"
        pool_guid = 0x928fbd0244ed366
        pool_state = 0x0
        pool_context = 0x0
        history_hostname = "rbt-inspiron-123"
        history_dsname = "rpool/containerd/10236"
        history_internal_str = ""
        history_internal_name = "destroy"
        history_dsid = 0x78ff
        history_txg = 0x634aa
        history_time = 0x5dccc86e
        time = 0x5dccc86e 0x159e1950 
        eid = 0x1cc6dc
```

I'm unsure what uses the cache. If mountpoint=legacy could be eliminated then the cache rebuild wouldn't fire for these at all.

On ext filesystems containerd does uses overlay mounts to do something similar, so I think this is a zfs issue to solve rather than a containerd issue to solve.

I'm happy to write a patch but require some direction on what that should look like.

**Comment by rbt** [comment]
Regenerating only the changed mount, instead of all mounts in the pool, resolves my performance issues.

This may be more fragile than desired.

```
*** /home/rbt/work/history_event-zfs-list-cacher.sh.old	2019-11-13 23:52:49.052752420 -0500
--- zed.d/history_event-zfs-list-cacher.sh	2019-11-14 00:34:05.000335315 -0500
***************
*** 64,70 ****
  PROPS="name,mountpoint,canmount,atime,relatime,devices,exec,readonly"
  PROPS="${PROPS},setuid,nbmand"
  
! "${ZFS}" list -H -t filesystem -o $PROPS -r "${ZEVENT_POOL}" > "${FSLIST_TMP}"
  
  # Sort the output so that it is stable
  sort "${FSLIST_TMP}" -o "${FSLIST_TMP}"
--- 64,81 ----
  PROPS="name,mountpoint,canmount,atime,relatime,devices,exec,readonly"
  PROPS="${PROPS},setuid,nbmand"
  
! # If cache file already exists then do a differential for performance
! # on systems with many filesystem mounts.
! #
! # If a cache file does not exist, create it with a full list
! if [ -f "${FSLIST}" ]; then
! 	grep -v -e "^${ZEVENT_HISTORY_DSNAME}\s" "${FSLIST}" > "${FSLIST_TMP}"
! 	if [ "${ZEVENT_HISTORY_INTERNAL_NAME}" != "destroy" ]; then
! 		"${ZFS}" list -H -t filesystem -o $PROPS -r "${ZEVENT_HISTORY_DSNAME}" >> "${FSLIST_TMP}"
! 	fi
! else
! 	"${ZFS}" list -H -t filesystem -o $PROPS -r "${ZEVENT_POOL}" > "${FSLIST_TMP}"
! fi
  
  # Sort the output so that it is stable
  sort "${FSLIST_TMP}" -o "${FSLIST_TMP}"
```

**Comment by richardelling** [comment]
this still has scaling issues, due to sort.

you should consider disabling it entirely because:
 * it is not core to zfs operation, it is an attempt at optimization that few people know about, and even fewer use
* zed is allowed to drop events under load, so it might not be called and therefore the cache cannot be authoritative
* zfs list itself also becomes slow at scale
* bash is probably the wrong language to use here, it might be better written in a more performant language and running as a deamon

**Comment by Ornias1993** [comment]
@richardelling So basically an unsupported legacy feature?
Asking because the actual issue is not very clear.

**Comment by kpande** [comment]
use #9414 and overlayfs, problem solved.

**Comment by behlendorf** [comment]
I'm sure @aerusso would be interested in any performance optimization we should make to improve the cache scalability.  As would @rlaager.

@rbt did I understand correctly that this functionality is enabled by default in 19.04?

**Comment by rbt** [comment]
> @rbt did I understand correctly that this functionality is enabled by default in 19.04?

19.10 has Root on ZFS as an option in the installer; but it is not the default.

Canonical seems to have mechanized these directions, which indicates the cache is a work-around to boot issues.
https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS

**Comment by aerusso** [comment]
@behlendorf Yeah, something like this was my fear. The issue is really that the history event itself should be parsed for the changed information, and the cache file should be patched with that information (calling `zfs list` only if the entry didn't already exist).

The bottleneck here is the call to `zfs list`, not `bash`. After that is fixed, the next one would probably be the text lookup and change for the single line to changed (rewriting the whole file).  @rbt How many datasets do you have?

**Comment by rbt** [comment]
>  @rbt How many datasets do you have?

@aerusso Microk8s/containerd had generated about 3500 datasets, largely clones of container files with few to no modifications. About a dozen datasets were being created and/or destroyed every minute.

Fixing zfs list to only fiddle with the modified entry effectively resolved my performance issue. zfs list step executes a small fraction of a second rather than 3+ seconds.

Overlayfs support is the better solution. containerd's zfs snapshotter has other issues. I don't believe it was destroying everything created but #9414 makes that non-default component unnecessary, so I've not tried to debug it.

Also, having Grub boot support would have fixed it by not needing the cache. The cache seems to be a work around to enable Root on ZFS support.

Ultimately, I opted to create an ext4 image file and mount that via loop, then pointed containerd at that location for storage. So now it's using overlay on ext4 (on zfs) and is happy.

**Comment by aerusso** [comment]
@rbt 

> Fixing zfs list to only fiddle with the modified entry effectively resolved my performance issue. zfs list step executes a small fraction of a second rather than 3+ seconds.


Your code snippet is actually very similar to one iteration of that very file. Unfortunately, we opted for the stupider, but simpler, approach present now.

> The cache seems to be a work around to enable Root on ZFS support.

The `zfs-list.cache` is part of a next-generation integration into systemd (`zfs-mount-generator`), allowing mount dependencies to be automatically resolved, which simplifies some things significantly. It's originally born out of a (my) desire to bind mount paths within zfs datasets and import pools asynchronously (that is not yet implemented). I think it's actually disabled by default, mostly out of concern for your exact use case (many datasets, being updated frequently). I don't know the exact details of why Ubuntu enables it.

All this to say: sorry this performance issue bit you.

**Comment by rlaager** [comment]
It’s in the root-on-ZFS HOWTO because making systemd aware of the mountpoints means it can Do The Right Thing. Otherwise we run into issues with filesystems in /var and things like PrivateTmp. (The previous workaround was to make systemd aware of the mountpoints in /var by using mountpoint=legacy and /etc/fstab.) Ubuntu uses it because it’s in the HOWTO and/or because they reached the same conclusion.
