### ISSUE TITLE
ZFS auto-mount on boot fails, manual import works

### ISSUE THREAD

**Issue by typoworx-de** [openzfs/zfs#9621]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 16.04.6 LTS
Linux Kernel	| 4.4.0-169-generic
Architecture	| x86_64
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

### Describe the problem you're observing
I've build actual ZFS-On-Linux from sources for my Dist (there was no official release fitting to my elder Ubuntu version).

I noticed ZFS only works by manual "zfs import". ZFS Pool import on boot fails. I already tried to enable zfs explicitly in /etc/initramfs-tools/modules - still not making auto-import work.

### Describe how to reproduce the problem
Try to build zfs from source, install the deb's on Ubuntu 16.04. Create/Import a zfs-pool and reboot.
Check if ZFS volumes are mounted.

### Include any warning/errors/backtraces from the system logs
This is an extract of syslog with keyword 'zfs' from my last reboot:

$> grep zfs /var/log/syslog
```
Nov 25 13:42:58 backup zfs[303]: The ZFS modules are not loaded.
Nov 25 13:42:58 backup zfs[303]: Try running '/sbin/modprobe zfs' as root to load them.
Nov 25 13:42:58 backup systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 13:42:58 backup systemd[1]: zfs-mount.service: Unit entered failed state.
Nov 25 13:42:58 backup systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
```

**Comment by typoworx-de** [comment]
It lookls like for some reason the build debian-packages are incomplete. I think they're missing some files which provide systemd services and so on. After copying over etc/* from build sources directory over to /etc/ I got error "failed to execute" on "/etc/systemd/system-generators/zfs-mount-generator", which I've fixed manually (using chmod +x /etc/systemd/system-generators/zfs-mount-generator).

Still ZFS won't mount on reboot automatically!

**Comment by Ornias1993** [comment]
> there was no official release fitting to my elder Ubuntu version

Master is actually still tested vs Ubuntu 16.04, or are you using a very low version of that? What kernel?

**Comment by typoworx-de** [comment]
I'm not using master... I'm using git-tagged release 'zfs-0.8.2' compiled on mainstream-kernel of Ubuntu '4.4.0-169-generic'.

I also can switch to a non-mainstream release (5.x kernel) if required?
Which kernel-version would be recommended?

Btw. I've been using these build-instructions:
https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

**Comment by Ornias1993** [comment]
> there was no official release fitting to my elder Ubuntu version
What I meant that even the current master is fitting your Ubuntu version. As do all releases. So there is an official (aka compatible) release

**Comment by typoworx-de** [comment]
Everything looks to work fine executing manual 'zfs import tank-name'. But it won't do auto-mount on boot. Ubuntu 16 still handles systemd, which is supported by zfs I think?

So in general ZFS seems to work fine. It's just the boot initialisation which is not working as expected at the moment. By the way I'm booting the system using ext4-partition (not zfs).

**Comment by typoworx-de** [comment]
Will I have to manually install any initramfs or systemd scripts? I figured out there are some files in:
/usr/src/zfs-0.8.2/etc/init.d/
/usr/src/zfs-0.8.2/etc/modules-load.d/
/usr/src/zfs-0.8.2/etc/systemd/system/
/usr/src/zfs-0.8.2/etc/systemd/system-generators/

which currently are not found in my system /etc. Are these optional or mandatory to make it work? Installed all build deb's which have been provided after manual build.

And '/etc/default/zfs' is missing - is it still useful or required?

**Comment by typoworx-de** [comment]
I've figured out the scripts inside src/etc/ provided a make script. I've been running ```make && make install``` now which seems to install some scripts I think they've been simply missing by deb-installer.

I'll report if this fixed boot-up providing zfs.

**Comment by typoworx-de** [comment]
Could anyone let me know how to reconfigure sbin-prefix for systemd scripts without manually editing all Makefile's?
--> etc/systemd/system/Makefile

At boot systemd-service scripts for zfs try to execute them in /usr/local/sbin/ instead of /sbin/ (provided using deb after compile / install from source into deb)

**Comment by typoworx-de** [comment]
I've tried fixing with symlinks from /sbin/{zfs,zed,zpool} into /usr/local/sbin/

At boot zfs-import job using systemd script (copied from src: etc/systemd/) still fails. Would be glad if someone could help me to make it work until fixed in main-release.

**Comment by typoworx-de** [comment]
What I've figured out so far:
1. If building zfs-source with prefix "/" (root instead of /usr/local/) all references to zfs-binaries are wrong linking to /usr/local/sbin/{zfs,zpool,zed}
   (Workaround: either build into /usr/local/ _or_ solve by symlink _or_ rewrite all /etc/systemd files manually.
2. Fix permissions: chmod +x /usr/lib/systemd/system-generators/zfs-mount-generator
3. Fix permissions: chmod +x /etc/init.d/*zfs*

Still I was unable to figure out how to make ZFS 0.8.2 auto-mount on boot (still fails!). Manual import of zfs-pool works fine on Ubuntu 16.04 LTS.

**Comment by typoworx-de** [comment]
> > there was no official release fitting to my elder Ubuntu version
> 
> What I meant that even the current master is fitting your Ubuntu version. As do all releases. So there is an official (aka compatible) release

Indeed official Ubuntu release is outdated.

**Comment by Side2005** [comment]
./configure
make -j1 pkg-utils deb-dkms

Did the trick for me. The flag --with-config=srpm kills systemd services.

I now have zfs.target and services like zfs-import and zfs-mount up and running! Sanoid/Syncoid and Autoimport on reboot are working again.

OS: Debian Stretch
Kernel: 4.19.bpo6
ZFS: 0.8.3-1

**Comment by arjunkc** [comment]
I had the same issue, and my fix was the same as @Side2005 
I think this should be documented in [the Custom Packages documentation](https://github.com/openzfs/zfs/wiki/Custom-Packages#debian-and-ubuntu)
