### ISSUE TITLE
Write Coalescing algorithm to optimize all-flash performance in ZFS

### ISSUE THREAD

**Issue by samuelxhu** [openzfs/zfs#9653]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos/Redhat
Distribution Version	|  Centos 7.5
Linux Kernel	| Linux kernel 3.10.x
Architecture	| x86-64
ZFS Version	| ZFS 0.8.x
SPL Version	| 

### Describe the problem you're observing
Actually this is not a bug report, but performance optimization is highly probable given that a proprietary ZFS-based storage vendor announced 400% IOPS performance improvement by an exclusive write-coalescing algorithm. I strongly believe such a write-coalescing algorithm, once implemented in ZFS, should improve the performance of HDD-based or hybird storage pool, not just all-flash ZFS pool. 
### Describe how to reproduce the problem
https://www.techzine.eu/news/cloud/40766/qnap-qes-2-1-0-optimizes-all-flash-performance-in-zfs/

Some details: QNAP has released the new version of its operating system QES. Version 2.1.0 includes new functionality such as the exclusive Write Coalescing algorithm to optimize all-flash performance in ZFS. It also includes software-defined SSD optimization, inline compaction and support for iSER.

The operating system is based on the FreeBSD kernel and uses ZFS. Version 2.1.0 therefore has the Write Coalescing algorithm, which should improve performance. When tested by QNAP itself, this resulted in a 400 percent improvement in random writing performance for the all-flash TES-3085U NAS.

QES 2.1.0 also includes support for software-defined over-provisioning. This allows users to allocate additional over-provisioning space to SSDs and storage pools to prevent performance degradation due to write enhancement. In addition, this should improve the lifespan of SSDs.

The new version of the control system also aggressively saves more space by using advanced inline data sealing techniques. This is particularly useful if many repetitive data or large amounts of small files are ignored. QES 2.1.0 also reinforces existing inline data deduplication and inline data density.

**Comment by Ornias1993** [comment]
`When tested by QNAP itself`
- Thus these results should be taken by a grain of salt.

Considering how QNAP is a disgusting company which even markets ZFS features as being "theirs", without every having done anything back for the opensource community at all. I highly doubt such a company would've done what all companies actively working together with the opensource ZFS community have not.

**Comment by snajpa** [comment]
ZFS already does do write coalescing, it's a transaction group sync in the background which does it. We already benefit from that, it is the #1 reason we use ZFS for our container hosts at vpsFree.cz.

You can tune it to gain more coalescing in time - the most simple one you can tune is `zfs_txg_timeout` and then you'd probably need to tune `zfs_dirty_*` variables too in order to benefit fully. Just beware you need to have enough free memory for that.

**Comment by Ornias1993** [comment]
@snajpa So, what QNAP (most likely) did was just some zfs tweaking?

**Comment by snajpa** [comment]
I'd think so, there are some major performance wins to be had if you tune your ZFS closely to your workload, esp. when the boxes are fully loaded :)

**Comment by Ornias1993** [comment]
Well at least it's now clear QNAP didn't produce almost anything... maybe a little middleware for the ZFS tweaks, but thats about it.

**Comment by Ornias1993** [comment]
@samuelxhu Considering the answer from @snajpa which basically was:
"There are already tuneable that could've somewhat similair effects"

I think this issue is closed, please do so.
