### ISSUE TITLE
ICP: aes-gcm: Incomplete inplace encryption handling

### ISSUE THREAD

**Issue by AttilaFueloep** [openzfs/zfs#9661]
### System information
N/A
### Describe the problem you're observing

This is mainly a question regarding the behaviour of existing code.

In [crypto_update_iov()](https://github.com/zfsonlinux/zfs/blob/51420321068e905445e625def28fadc7c3625e13/module/icp/core/kcf_prov_lib.c#L161) and [crypto_update_uio()](https://github.com/zfsonlinux/zfs/blob/51420321068e905445e625def28fadc7c3625e13/module/icp/core/kcf_prov_lib.c#L211) inplace encryption is handled by setting the output pointer to `NULL`. But `gcm_mode_encrypt_contiguous_blocks()` doesn't seem to handle this correctly. All it does is to [copy an eventual unencrypted remainder inplace](https://github.com/zfsonlinux/zfs/blob/51420321068e905445e625def28fadc7c3625e13/module/icp/algs/modes/gcm.c#L112), doing nothing in all other cases. I don't think this behaviour is correct, it should either copy all output in place or do nothing. But copying the remainder back to where it came from doesn't make much sense to me.

With ~12 hours of zloop I wasn't able to hit this code path once, so we may just assert `out != NULL`? On the other hand, other potential consumers may be affected.

I'm not sure if I understand the intentions of this code correctly though and what the correct behaviour would be if I do. So I'd appreciate any feedback from someone more versed with this code than I am. Maybe I should open an issue on illumos-devel as well?

**Comment by rlaager** [comment]
@tcaputi can you comment?

**Comment by tcaputi** [comment]
I'm not really an expert in this code, to be honest. I just copied it from the Illumos kernel. Someone on the Illumos mailing list might be a better person to ask about the original intent.

That being said. I do think that statement is wrong. It is copying more than just the remainder, but it only does that if there is a remainder. We are the only consumer of the ICP, so this probably doesn't matter too much, but we should correct it or report it to Illumos, if for no other reason than to make sure the Illumos folks dont hit an issue here at some point in the future.

There were also talks in the past about rewriting a good bit of this code to make it faster. I have no idea how far along that work is or if its even still actively being worked on.

http://zfs-create.blogspot.com/2014/05/optimizing-illumos-kernel-crypto.html

**Comment by AttilaFueloep** [comment]
>  It is copying more than just the remainder, but it only does that if there is a remainder

Sorry, my fault, I missworded that. What I wanted to say is it copies a complete GCM block back to where it came from if there was a remainder in the last call and `out` is `NULL` this call. I can't make sense out of this code, maybe it's just a merge error or something.

> We are the only consumer of the ICP, so this probably doesn't matter too much, but we should correct it or report it to Illumos,

Exactly! I asked on [illumos developper](https://illumos.topicbox.com/groups/developer/Tb507ca8024f8c553/kcf-fixes) but got no response so far. Maybe I should write another, more detailed message there?

> There were also talks in the past about rewriting a good bit of this code to make it faster. I have no idea how far along that work is or if its even still actively being worked on.

I pretty much think it's dead. I took another approach and ported the highly optimized  openssl aes-gcm assembler routines to the ICP. Together with chunking encryption (like the code you cited did) this gives a 32 times speedup for large (128 KiB) blocks.  I'm in the final steps of preparation and expect to open a PR in the next couple of days. The issue and PRs I opened were just in preparation for that upcoming PR.

**Comment by tcaputi** [comment]
That's wonderful news! I'm really glad that someone has finally had the time to work on that. @ahrens do you know anyone we could contact about the Illumos KCF? Or is there another place he should post the issue?

**Comment by ahrens** [comment]
@tcaputi I'd try the illumos mailing list (https://illumos.topicbox.com/groups/developer) and Jason King (@jasonbking) may specifically be able to help.

**Comment by AttilaFueloep** [comment]
Jason quickly responded to my initial post a couple of days ago. So let's see what he comes up with.

**Comment by dbussink** [comment]
I did an analysis of the code here and opened a PR with what I think can be cleaned up in #10015.
