### ISSUE TITLE
arcstat showing most fields as zero

### ISSUE THREAD

**Issue by aaronjwood** [openzfs/zfs#9698]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.10
Linux Kernel	| 5.3.0-23-generic #25-Ubuntu SMP
Architecture	| x86_64
ZFS Version	| 0.8.1-1ubuntu14
SPL Version	| 

### Describe the problem you're observing
On my system `arcstat` doesn't seem to work at all. Some examples:
```
arcstat
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
20:43:52     0     0      0     0    0     0    0     0    0    15G   15G
```
```
arcstat -x
    time   mfu   mru  mfug  mrug  eskip  mtxmis  dread  pread  read
20:45:45     0     0     0     0      0       0      0      0     0
```

### Describe how to reproduce the problem
Just run `arcstat` or `arcstat -x`.

**Comment by Fabian-Gruenbichler** [comment]
this is not a bug - you probably want to do "arcstat 30" or some other interval..

**Comment by aaronjwood** [comment]
My fault. I was expecting the older behavior from the tool. Passing an interval of 1 shows valid data after 1 second.

Since the first print always shows zeros for most fields would it make sense to not print anything at all until the first iteration of the interval has been reached?

**Comment by johnramsden** [comment]
I could take a look at this if I know what the expected behavior _should_ be. 

Would it be correct to not print until some data has been generated for at least one column? Or is the behavior currently correct?
