### ISSUE TITLE
ZFS Stripe (RAID0) reporting incorrect disk usage

### ISSUE THREAD

**Issue by luckylinux** [openzfs/zfs#9728]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Proxmox VE / Debian
Distribution Version	|  Debian Buster (10)
Linux Kernel	|  Linux pve61 5.3.13-1-pve #1 SMP PVE 5.3.13-1 (Thu, 05 Dec 2019 07:18:14 +0100) x86_64 GNU/Linux
Architecture	|  amd64
ZFS Version	|  0.8.2-pve2
SPL Version	|  0.8.2-pve2

### Describe the problem you're observing
I believe zfs list reports incorrect space usage for a striped pool (RAID0).
I created a striped pool based on 2 NVME Drives (2 x Corsair MP510 960GB each) for VM storage.
I created a QEMU HDD through Proxmox VE GUI of 960GB.

### Describe how to reproduce the problem
```
zpool status:
 pool: znvme
 state: ONLINE
 scan: none requested
 config:

        NAME                                           STATE     READ WRITE CKSUM
        znvme                                          ONLINE       0     0     0
          nvme-Force_MP510_1902820700012771012F-part1  ONLINE       0     0     0
          nvme-Force_MP510_19478238000128883554-part1  ONLINE       0     0     0
```

zpool list:
```
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
znvme  1.73T   444G  1.30T        -         -     1%    24%  1.00x    ONLINE  -
```

zfs list:
```
NAME                  USED  AVAIL     REFER  MOUNTPOINT
znvme                 990G   730G       96K  none
znvme/vm-100-disk-0   990G  1.25T      444G  -
```

It doesn't make sense to me why the "znvme/vm-100-disk-0" avail is 1.25T (since 990G + 1.25T = 2240 G, which is more than the two drives summed up together).
I deleted all snapshots prior to executing these commands because I suspected that the size mismatch might have been caused by it. The issue is still the same now that all snapshots have been deleted.

I'm also a bit surprised because, usually, if I create a VM in Proxmox it doesn't use all the storage it has available. For instance a 64GB virtual disk will only consume 20GB on ZFS if there is a lot of free space (approximatively same ratio, although with compression=lz4 it can be a bit better). Here it seems, according to zfs list, that it consumes the full disk size, even though the VM (Windows 10) doesn't use more than 70% of it's available disk capacity.

**Comment by drescherjm** [comment]
Compression and other factors make these two sizes very different.

**Comment by drescherjm** [comment]
https://github.com/zfsonlinux/zfs/issues/7565

**Comment by luckylinux** [comment]
Yes but usually zfs list is acknoledged as the "right one". zpool list doesn't for instance keep into account redundancy cost, parity metadata cost, etc.
How can however a dataset have more available space thank its parent (1.25T vs 730G)? And how can the sum of free and used space be more than the individual sum of the capacities of the drives?

**Comment by drescherjm** [comment]
Compression makes the sum larger

**Comment by luckylinux** [comment]
But then which is the right one? On Proxmox VE web interface it claims I have 85% of my pool space used up. How is this possible if the (only) VM disk is 960GB and there are 2x960GB (striped) in the pool?
