### ISSUE TITLE
Report the exact location of a checksum error

### ISSUE THREAD

**Issue by bra-fsn** [openzfs/zfs#9742]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.10
Linux Kernel	| 5.3.0-22-generic
Architecture	| x86_64
ZFS Version	| 0.8.1-1ubuntu14
SPL Version	| 0.8.1-1ubuntu14

### Describe the problem you're observing
If there's a checksum error in any of the pools, `zpool status -v` can be used to check what files are affected.
This produces an output like:
```
errors: Permanent errors have been detected in the following files:

        disk41:<0x27e1818>
        disk41:<0x27e183c>
        /data/disk41/files/c/e/e/7887938.6790777071.t
```
The first two were deleted, the third is still there.
Sometimes those files are large and good data could be extracted from them. It would be good to:

1. report (maybe with an additional -v to status, not to ruin current scripts) the exact location of the error, like: `/data/disk41/files/c/e/e/7887938.6790777071.t [59375616-59506687]`. If multiple (non-continuous) ranges are affected, they could be reported on distinct lines, or printed on the same line with a separator (but this could produce very long lines, which may make it a bad idea).
2. I'm not sure how this works today, but if I would overwrite those ranges with good data, the error should disappear entirely, or the same way as currently with deleted files

**Comment by scineram** [comment]
#8902 is in the works.

**Comment by Ornias1993** [comment]
@scineram You mean "#8902 has been stale/inactive since august".
Anyway, thanks for the reference, picked it up and rebased/changed it as required in #9743 

LGTM.
