### ISSUE TITLE
zfs list and zfs status only show last component of path

### ISSUE THREAD

**Issue by cleverca22** [openzfs/zfs#9771]
```
[root@nas:~]# zpool list -v
NAME                               SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
naspool                           10.9T  9.99T   939G        -         -    68%    91%  1.10x    ONLINE  -
  raidz1                          10.9T  9.99T   939G        -         -    68%  91.6%      -  ONLINE
    wwn-0x50014ee2654606d2-part2      -      -      -        -         -      -      -      -  ONLINE
    wwn-0x50014ee26546090e-part2      -      -      -        -         -      -      -      -  ONLINE
    wwn-0x50014ee20ff0b3f5-part2      -      -      -        -         -      -      -      -  ONLINE
cache                                 -      -      -        -         -      -      -      -  -
  L2                               128G  99.3G  28.7G        -         -     0%  77.6%      -  ONLINE
[root@nas:~]# zpool status
  pool: naspool
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: resilvered 861G in 0 days 11:22:33 with 0 errors on Fri Sep 21 04:45:47 2018
config: 

        NAME                              STATE     READ WRITE CKSUM
        naspool                           ONLINE       0     0     0
          raidz1-0                        ONLINE       0     0     0
            wwn-0x50014ee2654606d2-part2  ONLINE       0     0     0
            wwn-0x50014ee26546090e-part2  ONLINE       0     0     0
            wwn-0x50014ee20ff0b3f5-part2  ONLINE       0     0     0
        cache
          L2                              ONLINE       0     0     0

errors: No known data errors
[root@nas:~]# zpool offline naspool L2
cannot offline L2: no such device in pool

[root@nas:~]# zpool remove naspool L2
cannot remove L2: no such device in pool
```

its not possible to remove or offline a device when using the name that zfs gives

```
[root@nas:~]# ls -l /dev/media/L2  /dev/mapper/media-L2 /dev/dm-2 
brw-rw---- 1 root disk 254, 2 Nov 30 19:56 /dev/dm-2
lrwxrwxrwx 1 root root      7 Nov 30 19:56 /dev/mapper/media-L2 -> ../dm-2
lrwxrwxrwx 1 root root      7 Nov 30 19:56 /dev/media/L2 -> ../dm-2
```
in this case, due to LVM, there are 3 different and equally valid names for the device, but zfs is only showing the last element in the path

`[root@nas:~]# zpool offline naspool /dev/media/L2` does work, but you need to sort of brute-force your way thru every possible name until you find a working one

uuid's from `zpool status -g` also work

versions:
```
[root@nas:~]# zpool version
zfs-0.8.2-1
zfs-kmod-0.8.2-1
```

**Comment by richardelling** [comment]
@cleverca22 can you add to this issue the output of `zdb -C` with the pool imported as shown.

**Comment by Ornias1993** [comment]
it would also be nice if you didn't cut out the standardised issue format, so we would have more information such as Distro, Kernel etc.

Als it's interesting to note in your description (or even title) not all names are cut-off, only `L2` in this case. It sounds a bit like all are cut off, which get confusing with the first log shown.

Anyhow, it seems you are running (parts of) zfs on top of LVM...
AFAIK (please someone correct me if i'm wrong!), thats not an advised nor actually supported thing to do.

(A bit like using single disk raid-0 passthrough to use non it-mode raidcards with zfs, it will work but you might get issues along the way)

**Comment by Ornias1993** [comment]
Looking into why force isn't working:
zpool add passes the force bool to `make_root_vdev`. But `make_root_vdev` wants an `int`, is B_True or B_False compatible with that?

Even if so, `make_root_vdev` doesn't seem to do much with the force argument....
It only passes to `is_device_in_use` and thats about it.

I don't see any checks that require -f to prevent single disk vdev adds in any case.

**Comment by behlendorf** [comment]
@cleverca22 displaying only the last component of the name is the intended default behavior to keep the output readable on standard terminals.  That name may not be unique but internally ZFS will try and match the correct name against a couple different known `/dev/` paths which is usually sufficient.  If you prefer that ZFS always output the full path you can request this with the `-P` option, for example:

```sh
$ zpool list -vP
NAME                                                SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
tank                                               31.5G   523M  31.0G        -         -     0%     1%  1.00x    ONLINE  -
  /dev/disk/by-path/virtio-pci-0000:00:0a.0-part1  31.5G   523M  31.0G        -         -     0%  1.62%      -  ONLINE  
```

Furthermore, if you want this to be the default behavior you can set `ZPOOL_VDEV_NAME_PATH=1` in your environment.  See the `ENVIRONMENT VARIABLES` section of `zpool(8)` for additional options you may find useful.

**Comment by cleverca22** [comment]
```
[root@nas:~]# zdb -C
naspool:
    version: 5000
    name: 'naspool'
    state: 0
    txg: 24406147
    pool_guid: 7200155095284679922
    errata: 0
    hostid: 1226694344
    hostname: 'nas'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 7200155095284679922
        children[0]:
            type: 'raidz'
            id: 0
            guid: 14683827585890324468
            nparity: 1
            metaslab_array: 35
            metaslab_shift: 34
            ashift: 12
            asize: 11995901067264
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 12289
            children[0]:
                type: 'disk'
                id: 0
                guid: 13200055647801956859
                path: '/dev/disk/by-id/wwn-0x50014ee2654606d2-part2'
                whole_disk: 0
                DTL: 4139
                create_txg: 4
                com.delphix:vdev_zap_leaf: 4138
            children[1]:
                type: 'disk'
                id: 1
                guid: 7939413065091060985
                path: '/dev/disk/by-id/wwn-0x50014ee26546090e-part2'
                whole_disk: 0
                DTL: 3194
                create_txg: 4
                com.delphix:vdev_zap_leaf: 3192
            children[2]:
                type: 'disk'
                id: 2
                guid: 17379698086758883238
                path: '/dev/disk/by-id/wwn-0x50014ee20ff0b3f5-part2'
                whole_disk: 0
                DTL: 7060
                create_txg: 4
                com.delphix:vdev_zap_leaf: 7059
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

[root@nas:~]# zpool list -vP
NAME                                               SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
naspool                                           10.9T  10.0T   933G        -         -    69%    91%  1.10x    ONLINE  -
  raidz1                                          10.9T  10.0T   933G        -         -    69%  91.6%      -  ONLINE  
    /dev/disk/by-id/wwn-0x50014ee2654606d2-part2      -      -      -        -         -      -      -      -  ONLINE  
    /dev/disk/by-id/wwn-0x50014ee26546090e-part2      -      -      -        -         -      -      -      -  ONLINE  
    /dev/disk/by-id/wwn-0x50014ee20ff0b3f5-part2      -      -      -        -         -      -      -      -  ONLINE  
cache                                                 -      -      -        -         -      -      -      -  -
  /dev/media/L2                                    128G   100G  27.9G        -         -     0%  78.2%      -  ONLINE  
```

yeah, `-P` adds the paths that it needs and solves things

the `raidz1` elements are also being cut off, the `/dev/disk/by-id/` is missing

and yeah, that lvm disk is an old thing that i initially had some old data on it with lvm, and i was just tossing an L2arch onto it to help things along some, i should probably change it to a bare partition

my distro is: nixos
pools are imported in the initrd by `  "zpool" import -d "/dev/disk/by-id" -N $ZFS_FORCE "$pool"`
but i havent rebooted since adding the L2, so it got imported via a different directory

**Comment by behlendorf** [comment]
@cleverca22 re-reading this I believe I see why the existing logic didn't handle your case.  The `zpool` command checks the following common `/dev/` paths when trying to match the partial name.  The command most likely failed because `/dev/media/L2` is not in that list.  You can specify your import search paths using the `ZPOOL_IMPORT_PATH` environment option.  Is `/dev/media` a standard device path on nixos?

```c
static char *
zpool_default_import_path[DEFAULT_IMPORT_PATH_SIZE] = {
        "/dev/disk/by-vdev",    /* Custom rules, use first if they exist */
        "/dev/mapper",          /* Use multipath devices before components */
        "/dev/disk/by-partlabel", /* Single unique entry set by user */
        "/dev/disk/by-partuuid", /* Generated partition uuid */
        "/dev/disk/by-label",   /* Custom persistent labels */
        "/dev/disk/by-uuid",    /* Single unique entry and persistent */
        "/dev/disk/by-id",      /* May be multiple entries and persistent */
        "/dev/disk/by-path",    /* Encodes physical location and persistent */
        "/dev"                  /* UNSAFE device names will change */
};
```

**Comment by cleverca22** [comment]
`/dev/media` is just all LV's within the LVM VG called `media`
so the name will vary wildly from machine to machine

**Comment by behlendorf** [comment]
Understood.  In that case I don't believe there's anything to be done here, this code is working as intended.  Since you're using a non-standard `/dev/` path you must set `ZPOOL_IMPORT_PATH` accordingly to use the short names.

**Comment by cleverca22** [comment]
only real complaint i have, is that the short names shown by `zpool status` arent accepted as-is

only real improvements i can think of, is to maybe show the full name (or a warning or something) if the short name doesnt exist within the current search path

or for it to just compare the short names directly when doing commands like offline/remove

but i can also understand how zfs on lvm isnt really recommended/supported, and the whole people can be ignored/bypassed by fixing the system config

**Comment by behlendorf** [comment]
> maybe show the full name, if the short name doesn't exist within the current search path

Good thought, that could work.  It wouldn't effect the output for the vast majority of users using devices in the expected paths, which is nice.  And we already do this for file based vdevs since they can reside in any directory on the system.

I've gone ahead at tagged this as a possible small feature to implement.

**Comment by GregorKopka** [comment]
> yeah, `-P` adds the paths that it needs and solves things

Seems like `man zpool` is (at least partly) wrong:

> ZPOOL_VDEV_NAME_PATH  Cause zpool subcommands to output full vdev path names by default.  This behavior is identical to the zpool status -p command line option.

Should be `-P` (uppercase), no?

> but i can also understand how zfs on lvm isnt really recommended/supported, and the whole people can be ignored/bypassed by fixing the system config

Any particular reason why ZFS should _not work_ (not looking for a lecture on bad performance) when backed by LVM LVs?

**Comment by behlendorf** [comment]
> Should be -P (uppercase), no>

Yes indeed, thanks for catching that.  I've opened #9803 for this.

> Any particular reason why ZFS should not work (not looking for a lecture on bad performance) when backed by LVM LVs?

No there isn't.  As far as ZFS is concerned it's a block device like any other.  The only caveat is that the vdev's will use non-standard device paths so you'll want to set `ZPOOL_VDEV_NAME_PATH` in order to use the short names.
