### ISSUE TITLE
Glitched allow report

### ISSUE THREAD

**Issue by jdavidlists** [openzfs/zfs#9792]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10.1 Buster
Linux Kernel	| 4.9.130-2 / 4.9.0-8-amd64
Architecture	| amd64
ZFS Version	| 0.7.12-2+deb10u1
SPL Version	| 0.7.12-2

### Describe the problem you're observing

The output of "zfs allow" has a phantom line with no username.

```
$ zfs allow data
---- Permissions on data ---------------------------------------------
Local+Descendent permissions:
	user  create,destroy,mount,receive,send,snapshot
	user zfsmgr create,destroy,mount,receive,rename,rollback,send,share,snapshot
```

(Note two spaces between "user" and "create.")

### Describe how to reproduce the problem

This seems to happen if a user with permissions is removed; it's mostly a display error.  In cmd/zfs/zfs_main.c, in the print_uge_deleg_perms() function, this code appears twice:

```
if (nice_who_name)
    who_name  = nice_who_name;
```

However, it seems like (at least in this case) nice_who_name is not null.  Rather, it points to a null terminator.  So this problem could be addressed by changing these checks to:

```
if (nice_who_name && *nice_who_name)
    who_name  = nice_who_name;
```

This changes the output to the (arguably) more useful:

```
$ ./zfs allow data
---- Permissions on data ---------------------------------------------
Local+Descendent permissions:
	user 1000 create,destroy,mount,receive,send,snapshot
	user zfsmgr create,destroy,mount,receive,rename,rollback,send,share,snapshot
```

A (trivial) patch against master is attached.

[zfs-allow-uid-diff.txt](https://github.com/zfsonlinux/zfs/files/4011387/zfs-allow-uid-diff.txt)

### Include any warning/errors/backtraces from the system logs

Not applicable.

**Comment by behlendorf** [comment]
Thanks for catching this.  Would you mind opening a PR with the proposed fix.

**Comment by loli10K** [comment]
Attached txt file is just `git` help message unfortunately, though i suggest we port over https://github.com/openzfs/openzfs/pull/690 (and maybe add a test case as requested in https://github.com/openzfs/openzfs/pull/690#issuecomment-419233533)

**Comment by jdavidlists** [comment]
> Attached txt file is just `git` help message unfortunately

Derp! Sorry. :-( 

The actual patch is attached, but the openzfs/openzfs#690 patch looks like a better overall fix.  However, the comment states "The proposed patch also allows 'allow' and 'unallow' to accept numerical IDs, even when they are not known to the system, when -u or -g is explicitly specified."  That would be a nice feature, but I don't see how it's implemented by that patch; it appears to be only about display output.

I can try to prepare a PR for either patch, but I have to re-learn how to do that every time I do it, so it may take awhile.

[zfs-allow-uid-diff.txt](https://github.com/zfsonlinux/zfs/files/4013105/zfs-allow-uid-diff.txt)
