### ISSUE TITLE
Possible memory leak on aarch64 Centos 7.6 of kernel pagesize 64KB 

### ISSUE THREAD

**Issue by samuelxhu** [openzfs/zfs#9804]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Centos 7.6
Distribution Version	|   kernel-alt-4.14.0-115.el7a.0.1
Linux Kernel	|  4.14.0
Architecture	| aarch64 OS pagesize 64KB
ZFS Version	|  0.8.1
SPL Version	|  0.8.1

### Describe the problem you're observing
Running FIO 4KB write test, memory usage grows continuously and eats all the memory. Using arc_summay.pl to check ARC memory usage, and found out that ARC memory usage is under well control. Highly suspicious of memory leak due to kernel pagesize 64KB 

Previously i have tested ZFS 0.8.1 on ARM machine with pagesize 4KB, and works well.

Is it possible that a ZFS memory leak exists for aarch64 of kernel pagesize 64KB ?

### Describe how to reproduce the problem

I used normal configure and make commands for compiling ZFS. Is there an option to set for kernel pagesize 64KB?

**Comment by Ornias1993** [comment]
As far as I have seen with ZFS on BSD, it eats unused memory to cache writes.
Working on fio tests and zfs a lot myself, can you share the fio script/command you used?

**Comment by samuelxhu** [comment]
@Ornias1993 Just normal fio tests, as follows: fio -name iops  -rw=randwrite  -bs=$bs -runtime=$runtime  -iodepth 32 -filename $disk -ioengine libaio -direct=1  --numjobs=$numjob  --group_reporting

**Comment by Ornias1993** [comment]
@samuelxhu Whats the BS and numjobs?
Seems pretty sane... for as far as its filled out ;)

Does the memory usage decrease when writing stops?

**Comment by samuelxhu** [comment]
No, as the 4KB writes go on, memory usage continues to increase, until all
the memory is exhausted and the system crashes due to OOM. It just take
about ten minutes till the system crashes.

I checked ARC usage, and find that ARC is well controlled. very surprising

**Comment by Ornias1993** [comment]
Interesting... it might be one of two things:
- a memory leak
- The write caching not honoring its limits

**Comment by samuelxhu** [comment]
The machine I has problem is on ARM64, whose OS has a pagesize of 64KB.

Just wonder, does ZFS on Linux work well with kernel page size 64KB?
