### ISSUE TITLE
High CPU use caused by dbuf_evict process

### ISSUE THREAD

**Issue by blackknight36** [openzfs/zfs#9875]
I'm having an issue similar to #7922 however the symbols causing high CPU usage are different.  After running for a few hours the dbuf_evict process will start to max out one of the CPU cores causing load to go up.

System information

Type|	Version/Name|
|---|---|
Distribution Name|	CentOS|
Distribution Version|	8.1|
Linux Kernel|	4.18.0-147.3.1.el8_1.x86_64|
Architecture|	x86_64|
ZFS Version|	0.8.2|
SPL Version|	0.8.2|

```
Tasks: 463 total,   2 running, 461 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.4 us, 10.5 sy,  0.0 ni, 88.7 id,  0.0 wa,  0.0 hi,  0.4 si,  0.0 st
MiB Mem : 257151.3 total, 201655.4 free,  51000.2 used,   4495.8 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used. 204320.9 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                          
 1571 root      39  19       0      0      0 R  93.8   0.0 639:13.91 [dbuf_evict]
```

This server has 256 GB of RAM and zfs_arc_max is currently set to 0.  I have not made any changes to the zfs parameters.  Here is what arcstat shows.

```
[root@mdct-fs01 ~]# arcstat -f time,read,miss,miss%,dread,dmis,dm%,pread,pmis,pm%,mread,mmis,mm%,arcsz,c,mfu,mru,mfug,mrug,eskip,mtxmis 1 30
    time  read  miss  miss%  dread  dmis  dm%  pread  pmis  pm%  mread  mmis  mm%  arcsz     c   mfu   mru  mfug  mrug  eskip  mtxmis  
10:03:04     0     0      0      0     0    0      0     0    0      0     0    0    87G  125G     0     0     0     0      0       0  
10:03:05   100     0      0     97     0    0      3     0    0     92     0    0    87G  125G    95     2     0     0      0       0  
10:03:06   336     0      0    336     0    0      0     0    0    328     0    0    87G  125G   137   199     0     0      0       0  
10:03:07    83     0      0     83     0    0      0     0    0     76     0    0    87G  125G    82     1     0     0      0       0  
10:03:08    93     0      0     88     0    0      5     0    0     86     0    0    87G  125G    86     2     0     0      0       0  
10:03:09    93     0      0     93     0    0      0     0    0     85     0    0    87G  125G    93     0     0     0      0       0  
10:03:10    82     0      0     82     0    0      0     0    0     75     0    0    87G  125G    82     0     0     0      0       0  
10:03:11   328     0      0    318     0    0     10     0    0    321     0    0    87G  125G   145   173     0     0      0       0  
10:03:12    82     0      0     82     0    0      0     0    0     75     0    0    87G  125G    81     1     0     0      0       0  
10:03:13   199     0      0    199     0    0      0     0    0    191     0    0    87G  125G   198     1     0     0      0       0  
10:03:14    98     0      0     96     0    0      2     0    0     90     0    0    87G  125G    93     3     0     0      0       0  
10:03:15    70     0      0     70     0    0      0     0    0     64     0    0    87G  125G    69     1     0     0      0       0  
10:03:16   327     7      2    318     0    0      9     7   77    320     7    2    87G  125G   166   152     0     0      0       0  
10:03:17   153     0      0    150     0    0      3     0    0    145     0    0    87G  125G    86    64     0     0      0       0  
10:03:18    79     0      0     79     0    0      0     0    0     72     0    0    87G  125G    79     0     0     0      0       0  
10:03:19    98     0      0     93     0    0      5     0    0     91     0    0    87G  125G    90     3     0     0      0       0  
10:03:20    95     0      0     94     0    0      1     0    0     87     0    0    87G  125G    92     2     0     0      0       0  
10:03:21    93     0      0     93     0    0      0     0    0     85     0    0    87G  125G    91     2     0     0      0       0  
10:03:22   319     0      0    317     0    0      2     0    0    310     0    0    87G  125G   166   151     0     0      0       0  
10:03:23   104     0      0    104     0    0      0     0    0     95     0    0    87G  125G   102     2     0     0      0       0  
10:03:24   113     0      0    110     0    0      3     0    0    104     0    0    87G  125G   108     2     0     0      0       0  
10:03:25   103     0      0    103     0    0      0     0    0     94     0    0    87G  125G   102     1     0     0      0       0  
10:03:26   105     0      0    105     0    0      0     0    0     96     0    0    87G  125G   105     0     0     0      0       0  
10:03:27   340     0      0    335     0    0      5     0    0    331     0    0    87G  125G   159   176     0     0      0       0  
10:03:28   175     0      0    175     0    0      0     0    0    166     0    0    87G  125G   175     0     0     0      0       0  
10:03:29   143     0      0    134     0    0      9     0    0    133     0    0    87G  125G   132     2     0     0      0       0  
10:03:30   105     0      0    105     0    0      0     0    0     96     0    0    87G  125G   105     0     0     0      0       0  
10:03:31   143     1      0    125     0    0     18     1    5    134     1    0    87G  125G   124     1     0     0      0       0  
10:03:32   360     0      0    360     0    0      0     0    0    350     0    0    87G  125G   178   182     0     0      0       0  
10:03:33   105     0      0    105     0    0      0     0    0     96     0    0    87G  125G   104     1     0     0      0       0
```

I also ran perf top which shows the following output.

![Screenshot_2020-01-23_10-15-45](https://user-images.githubusercontent.com/18019703/72997490-7858e000-3dca-11ea-9ee1-edca215ef3be.png)

Does anyybody know what would cause this?

**Comment by justinpryzby** [comment]
I started seeing this after moving ZFS pool from a centos6 server to a centos7 server.  Both running zfs-0.8.4.  Both zpools are storing a postgresql tablespace, with gzip-1 compression.  And built on top of LVM volume (which I know is discouraged) running inside a qemu/KVM VM.  I run ZFS on 10 other postgresql instances and haven't seen this before.  It seems like a bug and not a performance problem.

Please write what's needed to help diagnose the problem.  I can put together a problem report if it happens again, but this is a customer-facing production server, and it's exceedingly painful to use when this happens, so I won't try to trigger it...

**Comment by justinpryzby** [comment]
I started seeing this after moving ZFS pool from a centos6 server to a centos7 server.  Both running zfs-0.8.4.  Both zpools are storing a postgresql tablespace, with gzip-1 compression.  And built on top of LVM volume (which I know is discouraged) running inside a qemu/KVM VM.  I run ZFS on 10 other postgresql instances and haven't seen this before.  It seems like a bug and not a performance problem.

Please write what's needed to help diagnose the problem.  I can put together a problem report if it happens again, but this is a customer-facing production server, and it's exceedingly painful to use when this happens, so I won't try to trigger it...

**Comment by justinpryzby** [comment]
I started seeing this after moving ZFS pool from a centos6 server to a centos7 server.  Both running zfs-0.8.4.  Both zpools are storing a postgresql tablespace, with gzip-1 compression.  And built on top of LVM volume (which I know is discouraged) running inside a qemu/KVM VM.  I run ZFS on 10 other postgresql instances and haven't seen this before.  It seems like a bug and not a performance problem.

Please write what's needed to help diagnose the problem.  I can put together a problem report if it happens again, but this is a customer-facing production server, and it's exceedingly painful to use when this happens, so I won't try to trigger it...

**Comment by blackknight36** [comment]
> I have exactly the same issue.
> Were you able to resolve it? Did it disappear?
> 
> Kernel 5.4.17-2102.202.5.el8
> zfs 0.8.6

Not quite.  I was able to avoid the issue by switching to CentOS 7 and rebuilding the zpool with the older version of zfs.

**Comment by IFM-Ulm** [comment]
Hi Michael,
thanks for the fast reply!
Yesterday, I rebooted the server and the the issue was gone.
However, it re-ocurred exactly the same way the following night. It seems that bacula is running for 3 hours and shortly before it finishes or cleans-up or whatever, it get's stuck.

In top, the bad boys are "dbuf_evict" and "bacula-fd" and in perf top the "mutex_spin_on_owner" and "arc_buf_destroy_impl".

I can see in munin graphs that it behaved exactly the same way as in the night before. It is not running out of memory, it has 100G and ARC is 40G. 

The exact setup was working fine for months before. The only thing I can imagine what was changed, was that we enabled SE-Linux. But we have it running with SE-Linux  on a sister machine and it is working fine.

![Bild 2021-07-14 um 13 18 20](https://user-images.githubusercontent.com/50103615/125613538-11f9ffc2-1918-4a00-bb35-675696508b3d.jpg)

![Bild 2021-07-14 um 13 21 51](https://user-images.githubusercontent.com/50103615/125613919-52633341-91b3-409a-8f4d-af06d8a7ef37.jpg)


The bacula normal operation is from 20:00 til 02:00. Then the bad happens, the drives have almost no IO but the CPUs are totally blocked. At 8:00 I rebooted.

![Bild 2021-07-14 um 13 20 44](https://user-images.githubusercontent.com/50103615/125613831-b2062e01-7d30-4c2e-b6f6-faff5ad1405e.jpg)


I switched off SE-Linux and bacula for now and see whether it will survive the night. Next day, I will turn on bacula again. That is then how it used to be. Then I will go for SE-Linux again and see whether this crashes the thing.

Is it something that I need to allow? Does it need to re-read some data for SE-Linux to be enabled? Should I let it run for 2 days and then it's over?

Thanks for any though.

**Comment by blackknight36** [comment]
> Hi Michael,
> thanks for the fast reply!

Interesting, your configuration is similar to ours.  We run CentOS with bacula and SELinux in enforcing mode.  

Also, what are you using to generate these graphs?

**Comment by IFM-Ulm** [comment]
The graphs are made with Munin
https://munin-monitoring.org
I know I should have switched to Grafana but Munin is so neat and lightweight, it has been serving me for 20 years now and it does the job...
There are some ZFS plugins available: https://gallery.munin-monitoring.org/plugins/munin-contrib/zfs_arcstats/

Allright, I survived the first night without getting stuck. However, no SE-Linux and no bacula was run. Next night, I'll enable bacula again.

I wonder if it is connected to some xattributes that we needed to add to some folders on the samba shared directories. Maybe bacula has a problem reading them? We'll see.

**Comment by IFM-Ulm** [comment]
In case anybody is interested in the topic:
Turning off SE-Linux seemed to do the trick. Bacula ran smoothly again last night.

![Bild 2021-07-16 um 12 58 20](https://user-images.githubusercontent.com/50103615/125937632-95c0c91a-0757-4241-8a10-875bf5cda09f.jpg)

![Bild 2021-07-16 um 12 58 56](https://user-images.githubusercontent.com/50103615/125937693-be42c36d-a1f7-4ec8-aab1-b1a3fb09f2ec.jpg)

It was able to finish and cleanup cashes as expected.

Of course, I am missing the reverse  proof: turning on SE-Linux without bacula, to make sure that it is nothing else which is triggering the bad at 02:00 each night, and then starting bacula to reconfirm that it is indeed the end of bacula which does the triggering.

However, this is a production system, so I can't reboot and impair it on purpose all the time. So for now I am glad that it is stable again and will leave it to the future to investigate this issue. I will set up another machine eventually. I am still happy to hear any comments which anybody likes to contribute at any later time.

**Comment by behlendorf** [comment]
CPU usage should be significantly reduced as if the 2.1.3 release, commit 1259dc6e6a8387c4302f73077f6dbeb3f2e4be13
