### ISSUE TITLE
Question: is there a way to delete the snapshots and keep them too?

### ISSUE THREAD

**Issue by dmaziuk** [openzfs/zfs#9944]
This is not system-specific: we have several clients with small-ish 1-2TB "data" drives, and we have a storage system with lots of room. What I would like to do is basically incremental backups: snapshot the clients and transfer incremental snapshots to the big box. This is working fine except
  * I need to delete old snapshots on the clients  to keep disk usage there down
  * and I want to keep them on the big box because that's the point.

-- And that's the part I can't get to work: `send -R`/`receive -F` deletes old snapshots on the receiving end. Without them I get
> cannot receive incremental stream: destination has been modified since most recent snapshot

Even `receive -u` does that when the storage system flips from one controller to another (it's a dual-headed setup) -- and `-u` is already suboptimal as you can't browse snapshots, you have to pick one and clone it to browse the files.

So the question is, is there a way around `destination has been modified since most recent snapshot` that I am not aware of? Or is this just not doable?

TIA

**Comment by misterbigstuff** [comment]
this is a question for the mailing list, really. you should also check the man page for zfs recv. it will tell you that recv -F is going to remove missing snapshots.

and then try setting readonly=on for your recv filesystem and try again. but you really need to use the mailing list and not delete the issue template.

**Comment by johnnyjacq16** [comment]
To transfer incremental backup run the following command:

`zfs send -R -I  <zfs pool name>/<zfs dataset>@<snapshot name>  <zfs pool name>/<zfs dataset>@<snapshot name>  | zfs recv -F  <zfs pool name>/<zfs dataset>`

Please note that the snapshot on the sending pool must be on the receiving  pool.
Example:
pool A
  snapshot A
  snapshot B

Pool B
  snapshot A

As shown above snapshot A must be on the pool A and pool B to send an incremental snapshot, which will be snapshot B to pool B.
So the command would be:

`zfs send -R -I  <Pool A>/<zfs dataset>@<snapshot A>   <Pool A>/<zfs dataset>@<snapshot B>  | zfs recv -F  <Pool B>/<zfs dataset>`

**Comment by misterbigstuff** [comment]
that doesn't answer their questsion, which would be to use zfs bookmarks.

**Comment by dmaziuk** [comment]
> this is a question for the mailing list, really. you should also check the man page for zfs recv. it will tell you that recv -F is going to remove missing snapshots.
> 
> and then try setting readonly=on for your recv filesystem and try again. but you really need to use the mailing list and not delete the issue template.

Fair enough, though I had better success at picking Brian's brain here in the past: s/n ratio tends to be much better. Still I get the non-answers quoting something I already know.

Thank you for `readonly=on`, I have not thought of trying that. And I guess I need to read up on bookmarks.

**Comment by dmaziuk** [comment]
PS the point, for those who don't know, is that `-F` will "force away" anything that zfs considers a "modification" on the receiver, that causes incremental transfers to fail with `destination has been modified since`. That includes e.g. having the dataset mounted on the receiver.

Unfortunately it will also delete snapshots that don't exist on the sender -- that is the part I don't want.

**Comment by misterbigstuff** [comment]
yeah, recv really needs a --force <foo> option instead of the big hammer -F.

**Comment by dmaziuk** [comment]
I don't think `readonly` will work in my case because the dataset is not mounted on the receiving end in the first place: `receive -u` is the only way to avoid the big hammer.

But it looks that the controller failing over on the receiving end also messes up something in zfs internals to cause the `modifed` error. (Receiver is a bunch of SAS shelves with dual-ported drives and 2 head nodes in a failover config. That have failed over for kernel update.)

Yes, a `--force whatever-it-is-that-zfs-thinks-changed` would be nice. But it would also require knowing what that is: it's something deep inside zfs guts.

**Comment by johnnyjacq16** [comment]
> PS the point, for those who don't know, is that `-F` will "force away" anything that zfs considers a "modification" on the receiver, that causes incremental transfers to fail with `destination has been modified since`. That includes e.g. simply having the dataset mounted on the receiver: that's a "modification" in some zfs internals.
> 
> Unfortunately it will also delete snapshots that don't exist on the sender -- that is the part I don't want.

you could try to hold the snapshot with `zfs hold` command

**Comment by dmaziuk** [comment]
> 
> you could try to hold the snapshot with `zfs hold` command

Yay! Thank you. Now to try this without `-u` as well -- but it appears there **is** a way to delete my snapshots and keep them too. Thanks a lot.

Hopefully this is not a bug that'll get fixed sometime down the road. :)

**Comment by dmaziuk** [comment]
I may have been barking at a wrong tree somewhat: it seems when the receiving system failed over, the new master automagically mounted the datasets. that overrides the `-u` and is what must've caused the `has been modified` error.

However, `zfs hold` seems to work even with the dataset mounted -- with `readonly=on`, now I'm sure I need that.

Summary: it appears it's possible to incrementally send zfs snapshots to a remote pool and then destroy them locally. The remote pool can keep any number of snapshots and have the dataset mounted (read-only) too. All you need top do is place `zfs hold` on the received snapshot(s), then you can incrementally `receive -F` without it wiping everything that does not exist on the sending side.

Thank you everyone

**Comment by GregorKopka** [comment]
Backup scripts should never use -R (also currently not -p, see https://github.com/zfsonlinux/zfs/issues/5341) on `zfs send` as that can lead to involuntary destruction of data on the target system.

**Comment by johnnyjacq16** [comment]
@GregorKopka which other way is there to send a dataset (replication) than `zfs send`.

**Comment by Lady-Galadriel** [comment]
Perhaps we should add somethng in the manual page for `zfs receive`?
A one liner like;

> To preserve existing snapshots on the destination, that no longer exist on the source, you can use `zfs hold DS@SNAP` on the destination.

This exact issue is why I tended not to use ZFS send & receive for certain backups. Now I may revisit that procecss.

**Comment by dmaziuk** [comment]
+1. Even better, where it says for `receive -F` "destroy snapshots and file systems that do not exist on the sending side" simple add "unless the receiving side has a hold on them". Or something along these lines. It should probably be mentioned under `send -R` as well, or have reference to `send -F` there.

**Comment by GregorKopka** [comment]
IMHO ` zfs recv` should get a set of options to determine what _exactly_ the send stream is able to change on the target system. In a fine enough granularity (allow to rollback / destroy snapshots / destroy snapshots prior to common snapshot / destroy clone origins (and the clones) / operate recursively on child datasets / change dataset properties / ...). 

And, while at it, recv needs to be made safe... since as far as I understood it receiving a malicious (checksum checks out but data being garbage) send stream is currently able to corrupt a pool far enough that it'll panic on import and needs to be restored from backup.

But I agree that this issue should be closed and the discussion should be on the mailing list instead, resulting in 'real' (bug reports or feature requests) issues being opened if needed.

**Comment by PaulZ-98** [comment]
@dmaziuk @Lady-Galadriel if holds exist on the source snapshot(s), they can be transmitted as part of zfs send/recv https://github.com/openzfs/zfs/pull/7513 (in case that's helpful)

**Comment by dmaziuk** [comment]
> @dmaziuk @Lady-Galadriel if holds exist on the source snapshot(s), they can be transmitted as part of zfs send/recv #7513 (in case that's helpful)

Yeah, I saw that, but in my case the sender has to destroy old snapshots, that's the point. I'd have to remove that hold so... I didn't see any advantage.
