### ISSUE TITLE
The zfsonlinux/zfs wiki is hard to contribute to

### ISSUE THREAD

**Issue by grahamc** [openzfs/zfs#9969]
GitHub Wikis don't have a way for non-committers to make suggestions other than opening an issue saying "please add xxx to the wiki".

I found this: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html maybe it would be useful.

Here are a couple things I've considered adding to the wiki, but stopped after realizing it wasn't easy to do:

1. Adding a ZFS functional test? Make sure to add it to the Makefile in that directory, and `tests/runfiles/common.run` to have the CI system run it.
2. Working on ZFS on NixOS? `nix-shell '<nixpkgs>' -A zfs` then run `patchPhase; autoreconfPhase; configurePhase` and then run `buildPhase` each time you want to compile.

**edit to make this ticket useful and not a gripe (sorry):** is this repo's wiki a good place to be putting this information, and should I open tickets for small updates like these two?

**Comment by behlendorf** [comment]
I agree.  The options Github provides for wiki access aren't great and I'm sure it prevents many people from contributing.  The approach you linked to looks interesting and in something we could definitely look in to setting up.

I think adding this kind of request to this repository is absolutely fine, and helps us track the issue.

**Comment by Ornias1993** [comment]
In my opinion all wiki here should be fully migrated to the OpenZFS wiki in due time anyway.

**Comment by ghfields** [comment]
With the move of the ZFS repo to the OpenZFS account (scheduled for Feb 25), this seems like a TODO item to consider after everything settles.

FYI.. On Feb 10th, the same link has been shared within the OpenZFS dev slack channel with some positive feedback.

**Comment by ghfields** [comment]
Yesterday, we had another person ask about making wiki contributions easier.  With the repo move successfully completed, it may be time to give this a bit of attention.

**Comment by Ornias1993** [comment]
@ghfields if we move the content of the Github wiki (deleting outdated content) to the actual OpenZFS wiki, that would open up a lot of flexible options for moderation and segregating github and wiki moderation/access...

**Comment by Ornias1993** [comment]
I found a simple solution to this issue:
There is an easy github action, which can be used to select a directory in the main repository ( /wiki for example) to contain .md files that will be automatically added/modified on the wiki on every push :)

**Comment by gmelikov** [comment]
We moved our wiki into a separate repo https://github.com/openzfs/openzfs-docs , where you can easily make a Pull Request, everybody is welcome to tontribute!

**Comment by grahamc** [comment]
Thanks!
