### ISSUE TITLE
Typo in zpool manpage: example 11

### ISSUE THREAD

**Issue by AllKind** [openzfs/zfs#9971]
https://github.com/zfsonlinux/zfs/blob/fa3922df75d722724dd51819cb49da0418d054f5/man/man8/zpool.8#L325

I guess that should be sdc instead of sdd, as sdc was used in the creation of the example pool.

**Comment by behlendorf** [comment]
Actually, I believe the example is correct.  Though perhaps not very intuitive.  My interpretation of what it's trying to say is that on device failure the hot spare `sdc` disk will be automatically used to restore redundancy.  A new device, `sdd` can then be used to replace the failed device `sda`, once rebuild the hot spare `sdc` will again be available for use.  This could definitely be clearer though.
