### ISSUE TITLE
Filter zfs history and events

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#9972]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| 7.7
Linux Kernel	| 3.10.0-1062.4.3.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing
Using very frequent (ie: 1 min interval) `zfs send | recv`, both history and event log are overwelmed by the `send/recv` commands.

`zpool history` example:
```
[root@nas ~]# time zpool history > /dev/null
real    1m5.933s
user    0m9.952s
sys     0m3.973s 
```
History is full of logs about `send/recv`; during the above command disks are very busy and application response time suffer.

`zpool events` example:
```
TIME                           CLASS
Feb  9 2020 18:02:05.039658314 sysevent.fs.zfs.history_event
Feb  9 2020 18:02:05.040658322 sysevent.fs.zfs.history_event
Feb  9 2020 18:02:05.040658322 sysevent.fs.zfs.history_event
...
Feb  9 2020 18:12:04.403116919 sysevent.fs.zfs.history_event
Feb  9 2020 18:12:04.403116919 sysevent.fs.zfs.history_event
Feb  9 2020 18:12:04.787119769 sysevent.fs.zfs.history_event
```
Only about ~1h of events can be viewed; important events as I/O errors can be lost in the noise.

Proposed solution: filter *what* the ZFS module should record as history and event. A tunable would be fine, but a pool property would be even better.

### Describe how to reproduce the problem
Simply generate many `zfs send/recv` between two machines.

**Comment by baryluk** [comment]
`zfs send` doesn't generate any entries in `history` or `events`. It must be from `zfs recv`, and recv definitively should be included in `history` just like `zfs snapshot` or `zfs destroy snapshot`. As of the `zpool events` example you gave, I am not sure where they are coming from.

**Comment by shodanshok** [comment]
@baryluk You are right: on the source, history is mainly related to taking and destroying snapshots for the `send`. I was unclear in the first post. Regarding events, they are all about `sysevent.fs.zfs.history_event` and I have them *both* on source and destination. 

While is 100% correct that all these history/events are logged by default, I think that a filter to specify what history and events to retain would be great.

To maintainers: if the requests is not applicable / appropriate, feel free to close the issue.

**Comment by lapo-luchini** [comment]
This is an issue for me as well. It would be useful being able to filter events and/or increase the number of logged events in history.

FreeBSD uses `zpool history` to check the last time a pool was scrubbed and having frequent `zfs recv` on my pool my `zpool history` only shows 2 days of data, thus it does think I never scrubbed and does it again after two days. I'll probably change my scrub regimen to a monthly cron, but I think this issue is still relevant.
