### ISSUE TITLE
Encountering a crash while running a sysbench synthetic workload. The sysbench scripts being used generate a tpcc-like workload for MySQL. Crash is occurring during the prepare stage (setup) of the test

### ISSUE THREAD

**Issue by eolson78** [openzfs/zfs#9975]
Distribution Name	| CENTOS
Distribution Version	| 6.X
Linux Kernel	| 4.14.58
ZFS Version	| .83

### Describe the problem you're observing
Encountering a crash while running a sysbench synthetic workload. The sysbench scripts being used generate a tpcc-like workload for MySQL. Crash is occurring during the prepare stage (setup) of the test

### Describe how to reproduce the problem

Add 4 100GB SSD vdevs, create a Raid 10 pool
Create a block volume and share as iSCSI LUN
    Launch AWS CentOS 7 instance
    yum install wget
    wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    rpm -ivh mysql-community-release-el7-5.noarch.rpm
    yum update
    yum install mysql-server
    yum install iscsi-initiator-utils
    iscsiadm -m discovery -t st -p <softnas IP>
    iscsiadm -m node -L all
    iscsiadm -m session -P3 | grep disk < note sd# disk from output and use for the following steps
    fdisk /dev/sd#
    mkfs.xfs /dev/sd#1
    mkdir /data && mount /dev/sda# /data
    edit /etc/my.cnf and modify the datadir line to match this line: datadir=/data/mysql
    systemctl start mysqld
    rsync -av /var/lib/mysql /data/
    Create mysql database: mysql -u root -p, create database testdb; , exit
    curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | bash
    yum install sysbench
    git clone https://github.com/Percona-Lab/sysbench-tpcc.git
    cd sysbench-tpcc/
    Run prepare tables and data command from above

Result
=========================
Crash encountered during prepare portion of test.

Jan 11 00:57:07 ip-10-0-0-148 kernel: INFO: task zvol:1424 blocked for more than 120 seconds.
Jan 11 00:57:07 ip-10-0-0-148 kernel:      Tainted: P           O    4.14.158 #1
Jan 11 00:57:07 ip-10-0-0-148 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jan 11 00:57:07 ip-10-0-0-148 kernel: zvol            D    0  1424      2 0x80000000
Jan 11 00:57:07 ip-10-0-0-148 kernel: Call Trace:
Jan 11 00:57:07 ip-10-0-0-148 kernel: __schedule+0x2e4/0x750
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? update_curr+0x15c/0x250
Jan 11 00:57:07 ip-10-0-0-148 kernel: schedule+0x3a/0xa0
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? dequeue_entity+0x306/0x8e0
Jan 11 00:57:07 ip-10-0-0-148 kernel: schedule_preempt_disabled+0xe/0x10
Jan 11 00:57:07 ip-10-0-0-148 kernel: __mutex_lock.clone.1+0x2cd/0x5a0
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? zio_done+0x37/0x1010 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? zio_ready+0x216/0x460 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: __mutex_lock_slowpath+0x17/0x20
Jan 11 00:57:07 ip-10-0-0-148 kernel: mutex_lock+0x33/0x40
Jan 11 00:57:07 ip-10-0-0-148 kernel: dbuf_find+0x5b/0x1d0 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dbuf_hold_impl_arg+0x4f/0x630 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dbuf_hold_impl+0xa8/0xe0 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dbuf_hold_level+0x26/0x40 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? down_read+0x16/0x40
Jan 11 00:57:07 ip-10-0-0-148 kernel: dbuf_hold+0x16/0x20 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dnode_hold_impl+0x104/0xd00 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? kvm_clock_read+0x1e/0x20
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? kvm_clock_get_cycles+0x9/0x10
Jan 11 00:57:07 ip-10-0-0-148 kernel: dnode_hold+0x1b/0x20 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dmu_tx_hold_object_impl+0x4d/0xb0 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: dmu_tx_hold_write+0x39/0x70 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: zvol_write+0x160/0x3b0 [zfs]
Jan 11 00:57:07 ip-10-0-0-148 kernel: taskq_thread+0x306/0x690 [spl]
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? try_to_wake_up+0x2d0/0x2d0
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to+0x2aa/0x530
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x31/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x25/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x25/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x25/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x25/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __switch_to_asm+0x25/0x60
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __schedule+0x2ec/0x750
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? default_wake_function+0x12/0x20
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __wake_up_common+0x8a/0x130
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? param_set_taskq_kick+0x130/0x130 [spl]
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? param_set_taskq_kick+0x130/0x130 [spl]
Jan 11 00:57:07 ip-10-0-0-148 kernel: kthread+0x113/0x150
Jan 11 00:57:07 ip-10-0-0-148 kernel: ? __kthread_init_worker+0x40/0x40
Jan 11 00:57:07 ip-10-0-0-148 kernel: ret_from_fork+0x35/0x40
Jan 11 00:57:07 ip-10-0-0-148 kernel: INFO: task dbuf_evict:1429 blocked for more than 120 seconds.
Jan 11 00:57:07 ip-10-0-0-148 kernel:      Tainted: P           O    4.14.158 #1

**Comment by baryluk** [comment]
It isn't a crash, more likely a deadlock / timeout.

If you could provide a repro steps to do it on single machine without iSCSI that probably would be helpful.

**Comment by misterbigstuff** [comment]
why should they change how they reproduce the issue when they provided thorough steps?
